{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpimpressiontrackingtarget\/completionhandler"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpimpressiontrackingtarget\/completionhandler"]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"completionHandler"}],"externalID":"c:objc(cs)GFPImpressionTrackingTarget(py)completionHandler","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"completionHandler","kind":"identifier"},{"text":": ","kind":"text"},{"text":"GFPImpressionTrackCompletionHandler","kind":"typeIdentifier","preciseIdentifier":"c:GFPImpressionTracker.h@T@GFPImpressionTrackCompletionHandler"}],"role":"symbol","modules":[{"name":"GFPSDK"}],"roleHeading":"Instance Property","title":"completionHandler"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"completionHandler"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:GFPImpressionTracker.h@T@GFPImpressionTrackCompletionHandler","kind":"typeIdentifier","text":"GFPImpressionTrackCompletionHandler","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionTrackCompletionHandler"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionTrackingTarget"]]},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionTrackingTarget\/completionHandler","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPImpressionTrackingTarget/completionHandler":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionTrackingTarget\/completionHandler","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"completionHandler","kind":"identifier"},{"kind":"text","text":": "},{"text":"GFPImpressionTrackCompletionHandler","kind":"typeIdentifier","preciseIdentifier":"c:GFPImpressionTracker.h@T@GFPImpressionTrackCompletionHandler"}],"navigatorTitle":[{"text":"completionHandler","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/gfpsdk\/gfpimpressiontrackingtarget\/completionhandler","title":"completionHandler","kind":"symbol","abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPImpressionTrackCompletionHandler":{"type":"topic","url":"\/documentation\/gfpsdk\/gfpimpressiontrackcompletionhandler","title":"GFPImpressionTrackCompletionHandler","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPImpressionTrackCompletionHandler","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"GFPImpressionTrackCompletionHandler","kind":"identifier"}],"kind":"symbol","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionTrackCompletionHandler"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPImpressionTrackingTarget":{"navigatorTitle":[{"text":"GFPImpressionTrackingTarget","kind":"identifier"}],"title":"GFPImpressionTrackingTarget","url":"\/documentation\/gfpsdk\/gfpimpressiontrackingtarget","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionTrackingTarget","role":"symbol","type":"topic","kind":"symbol","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPImpressionTrackingTarget","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"completionHandler","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"completionHandler"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"void (^)(GFPImpressionTrackingTarget *)","preciseIdentifier":"c:BFv(#*$objc(cs)GFPImpressionTrackingTarget)","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"completionHandler","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTrackingTarget~1completionHandler\/title","value":"completionHandler","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"completionHandler"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTrackingTarget~1completionHandler\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTrackCompletionHandler\/title","value":"GFPImpressionTrackCompletionHandler"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTrackCompletionHandler\/fragments","op":"replace","value":[{"kind":"identifier","text":"GFPImpressionTrackCompletionHandler"}]},{"value":[{"kind":"identifier","text":"GFPImpressionTrackCompletionHandler"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTrackCompletionHandler\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTrackingTarget\/title","value":"GFPImpressionTrackingTarget"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTrackingTarget\/fragments","op":"replace","value":[{"text":"GFPImpressionTrackingTarget","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"GFPImpressionTrackingTarget"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTrackingTarget\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}