{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionTrackingTarget\/customCompleteCheckHandler"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"customCompleteCheckHandler","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionTrackCustomCompleteCheckHandler","kind":"typeIdentifier","preciseIdentifier":"c:GFPImpressionTracker.h@T@GFPImpressionTrackCustomCompleteCheckHandler","text":"GFPImpressionTrackCustomCompleteCheckHandler"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"kind":"symbol","metadata":{"title":"customCompleteCheckHandler","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"customCompleteCheckHandler","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:GFPImpressionTracker.h@T@GFPImpressionTrackCustomCompleteCheckHandler","text":"GFPImpressionTrackCustomCompleteCheckHandler","kind":"typeIdentifier"}],"roleHeading":"Instance Property","role":"symbol","externalID":"c:objc(cs)GFPImpressionTrackingTarget(py)customCompleteCheckHandler","symbolKind":"property","navigatorTitle":[{"text":"customCompleteCheckHandler","kind":"identifier"}],"modules":[{"name":"GFPSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionTrackingTarget"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpimpressiontrackingtarget\/customcompletecheckhandler"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpimpressiontrackingtarget\/customcompletecheckhandler"]}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPImpressionTrackingTarget/customCompleteCheckHandler":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionTrackingTarget\/customCompleteCheckHandler","type":"topic","abstract":[],"url":"\/documentation\/gfpsdk\/gfpimpressiontrackingtarget\/customcompletecheckhandler","navigatorTitle":[{"kind":"identifier","text":"customCompleteCheckHandler"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"customCompleteCheckHandler","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:GFPImpressionTracker.h@T@GFPImpressionTrackCustomCompleteCheckHandler","text":"GFPImpressionTrackCustomCompleteCheckHandler"}],"title":"customCompleteCheckHandler","role":"symbol","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPImpressionTrackingTarget":{"navigatorTitle":[{"text":"GFPImpressionTrackingTarget","kind":"identifier"}],"title":"GFPImpressionTrackingTarget","url":"\/documentation\/gfpsdk\/gfpimpressiontrackingtarget","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionTrackingTarget","role":"symbol","type":"topic","kind":"symbol","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPImpressionTrackingTarget","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPImpressionTrackCustomCompleteCheckHandler":{"navigatorTitle":[{"text":"GFPImpressionTrackCustomCompleteCheckHandler","kind":"identifier"}],"title":"GFPImpressionTrackCustomCompleteCheckHandler","abstract":[],"type":"topic","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionTrackCustomCompleteCheckHandler","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPImpressionTrackCustomCompleteCheckHandler"}],"url":"\/documentation\/gfpsdk\/gfpimpressiontrackcustomcompletecheckhandler","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"customCompleteCheckHandler"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"customCompleteCheckHandler"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:BFb()","text":"_Bool (^)(void)","kind":"typeIdentifier"},{"kind":"text","text":" "},{"text":"customCompleteCheckHandler","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTrackingTarget~1customCompleteCheckHandler\/title","value":"customCompleteCheckHandler"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTrackingTarget~1customCompleteCheckHandler\/fragments","value":[{"kind":"identifier","text":"customCompleteCheckHandler"}]},{"value":"GFPImpressionTrackingTarget","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTrackingTarget\/title","op":"replace"},{"value":[{"kind":"identifier","text":"GFPImpressionTrackingTarget"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTrackingTarget\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTrackingTarget\/navigatorTitle","value":[{"text":"GFPImpressionTrackingTarget","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"GFPImpressionTrackCustomCompleteCheckHandler","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTrackCustomCompleteCheckHandler\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTrackCustomCompleteCheckHandler\/fragments","op":"replace","value":[{"kind":"identifier","text":"GFPImpressionTrackCustomCompleteCheckHandler"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTrackCustomCompleteCheckHandler\/navigatorTitle","value":[{"kind":"identifier","text":"GFPImpressionTrackCustomCompleteCheckHandler"}]}]}]}