{"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionTrackingTarget\/init(trackView:trackThreshold:completionHandler:completeCheckHandler:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"convenience"},{"text":" ","kind":"text"},{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"trackView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GFPImpressionTrackView","preciseIdentifier":"c:objc(cs)GFPImpressionTrackView","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionTrackView"},{"text":", ","kind":"text"},{"text":"trackThreshold","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPImpressionTrackThreshold","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionTrackThreshold","text":"GFPImpressionTrackThreshold"},{"kind":"text","text":", "},{"text":"completionHandler","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionTrackCompletionHandler","kind":"typeIdentifier","text":"GFPImpressionTrackCompletionHandler","preciseIdentifier":"c:GFPImpressionTracker.h@T@GFPImpressionTrackCompletionHandler"},{"kind":"text","text":", "},{"text":"completeCheckHandler","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"customCompleteCheckHandler","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPImpressionTrackCustomCompleteCheckHandler","kind":"typeIdentifier","preciseIdentifier":"c:GFPImpressionTracker.h@T@GFPImpressionTrackCustomCompleteCheckHandler","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionTrackCustomCompleteCheckHandler"},{"kind":"text","text":")"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpimpressiontrackingtarget\/init(trackview:trackthreshold:completionhandler:completecheckhandler:)"]},{"paths":["\/documentation\/gfpsdk\/gfpimpressiontrackingtarget\/init(trackview:trackthreshold:completionhandler:completecheckhandler:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"role":"symbol","navigatorTitle":[{"text":"initWithTrackView:trackThreshold:completionHandler:completeCheckHandler:","kind":"identifier"}],"symbolKind":"init","roleHeading":"Initializer","fragments":[{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"trackView"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPImpressionTrackView","text":"GFPImpressionTrackView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"trackThreshold"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPImpressionTrackThreshold","text":"GFPImpressionTrackThreshold","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"GFPImpressionTrackCompletionHandler","kind":"typeIdentifier","preciseIdentifier":"c:GFPImpressionTracker.h@T@GFPImpressionTrackCompletionHandler"},{"kind":"text","text":", "},{"text":"completeCheckHandler","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"GFPImpressionTrackCustomCompleteCheckHandler","preciseIdentifier":"c:GFPImpressionTracker.h@T@GFPImpressionTrackCustomCompleteCheckHandler"},{"text":")","kind":"text"}],"title":"init(trackView:trackThreshold:completionHandler:completeCheckHandler:)","externalID":"c:objc(cs)GFPImpressionTrackingTarget(im)initWithTrackView:trackThreshold:completionHandler:completeCheckHandler:","modules":[{"name":"GFPSDK"}]},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionTrackingTarget"]]},"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPImpressionTrackThreshold":{"title":"GFPImpressionTrackThreshold","url":"\/documentation\/gfpsdk\/gfpimpressiontrackthreshold","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPImpressionTrackThreshold"}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"GFPImpressionTrackThreshold","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionTrackThreshold","abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPImpressionTrackingTarget":{"navigatorTitle":[{"text":"GFPImpressionTrackingTarget","kind":"identifier"}],"title":"GFPImpressionTrackingTarget","url":"\/documentation\/gfpsdk\/gfpimpressiontrackingtarget","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionTrackingTarget","role":"symbol","type":"topic","kind":"symbol","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPImpressionTrackingTarget","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPImpressionTrackView":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"GFPImpressionTrackView","kind":"identifier"}],"role":"symbol","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionTrackView","kind":"symbol","type":"topic","url":"\/documentation\/gfpsdk\/gfpimpressiontrackview","title":"GFPImpressionTrackView","navigatorTitle":[{"kind":"identifier","text":"GFPImpressionTrackView"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPImpressionTrackCompletionHandler":{"type":"topic","url":"\/documentation\/gfpsdk\/gfpimpressiontrackcompletionhandler","title":"GFPImpressionTrackCompletionHandler","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPImpressionTrackCompletionHandler","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"GFPImpressionTrackCompletionHandler","kind":"identifier"}],"kind":"symbol","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionTrackCompletionHandler"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPImpressionTrackCustomCompleteCheckHandler":{"navigatorTitle":[{"text":"GFPImpressionTrackCustomCompleteCheckHandler","kind":"identifier"}],"title":"GFPImpressionTrackCustomCompleteCheckHandler","abstract":[],"type":"topic","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionTrackCustomCompleteCheckHandler","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPImpressionTrackCustomCompleteCheckHandler"}],"url":"\/documentation\/gfpsdk\/gfpimpressiontrackcustomcompletecheckhandler","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPImpressionTrackingTarget/init(trackView:trackThreshold:completionHandler:completeCheckHandler:)":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionTrackingTarget\/init(trackView:trackThreshold:completionHandler:completeCheckHandler:)","fragments":[{"kind":"keyword","text":"convenience"},{"text":" ","kind":"text"},{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"trackView","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GFPImpressionTrackView","preciseIdentifier":"c:objc(cs)GFPImpressionTrackView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"trackThreshold"},{"text":": ","kind":"text"},{"text":"GFPImpressionTrackThreshold","preciseIdentifier":"c:objc(cs)GFPImpressionTrackThreshold","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completionHandler"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:GFPImpressionTracker.h@T@GFPImpressionTrackCompletionHandler","text":"GFPImpressionTrackCompletionHandler","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completeCheckHandler"},{"kind":"text","text":": "},{"preciseIdentifier":"c:GFPImpressionTracker.h@T@GFPImpressionTrackCustomCompleteCheckHandler","kind":"typeIdentifier","text":"GFPImpressionTrackCustomCompleteCheckHandler"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"initWithTrackView:trackThreshold:completionHandler:completeCheckHandler:","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/gfpsdk\/gfpimpressiontrackingtarget\/init(trackview:trackthreshold:completionhandler:completecheckhandler:)","title":"init(trackView:trackThreshold:completionHandler:completeCheckHandler:)","kind":"symbol","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","value":"initWithTrackView:trackThreshold:completionHandler:completeCheckHandler:","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithTrackView:trackThreshold:completionHandler:completeCheckHandler:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithTrackView:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionTrackView","text":"GFPImpressionTrackView","preciseIdentifier":"c:objc(cs)GFPImpressionTrackView"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"trackView"},{"kind":"text","text":" "},{"text":"trackThreshold:","kind":"identifier"},{"kind":"text","text":"("},{"text":"GFPImpressionTrackThreshold","preciseIdentifier":"c:objc(cs)GFPImpressionTrackThreshold","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionTrackThreshold","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"trackThreshold","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"completionHandler:"},{"text":"(","kind":"text"},{"text":"void (^)(GFPImpressionTrackingTarget *)","kind":"typeIdentifier","preciseIdentifier":"c:BFv(#*$objc(cs)GFPImpressionTrackingTarget)"},{"kind":"text","text":") "},{"kind":"internalParam","text":"completionHandler"},{"kind":"text","text":" "},{"text":"completeCheckHandler:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:BFb()","text":"_Bool (^)(void)","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"customCompleteCheckHandler"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTrackThreshold\/title","value":"GFPImpressionTrackThreshold"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTrackThreshold\/fragments","value":[{"text":"GFPImpressionTrackThreshold","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTrackThreshold\/navigatorTitle","op":"replace","value":[{"text":"GFPImpressionTrackThreshold","kind":"identifier"}]},{"value":"GFPImpressionTrackingTarget","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTrackingTarget\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTrackingTarget\/fragments","value":[{"kind":"identifier","text":"GFPImpressionTrackingTarget"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTrackingTarget\/navigatorTitle","value":[{"kind":"identifier","text":"GFPImpressionTrackingTarget"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTrackView\/title","value":"GFPImpressionTrackView","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTrackView\/fragments","value":[{"text":"GFPImpressionTrackView","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTrackView\/navigatorTitle","value":[{"text":"GFPImpressionTrackView","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTrackCompletionHandler\/title","op":"replace","value":"GFPImpressionTrackCompletionHandler"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTrackCompletionHandler\/fragments","value":[{"text":"GFPImpressionTrackCompletionHandler","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"GFPImpressionTrackCompletionHandler"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTrackCompletionHandler\/navigatorTitle"},{"value":"GFPImpressionTrackCustomCompleteCheckHandler","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTrackCustomCompleteCheckHandler\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTrackCustomCompleteCheckHandler\/fragments","value":[{"text":"GFPImpressionTrackCustomCompleteCheckHandler","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTrackCustomCompleteCheckHandler\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"GFPImpressionTrackCustomCompleteCheckHandler"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTrackingTarget~1init(trackView:trackThreshold:completionHandler:completeCheckHandler:)\/title","value":"initWithTrackView:trackThreshold:completionHandler:completeCheckHandler:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"initWithTrackView:trackThreshold:completionHandler:completeCheckHandler:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTrackingTarget~1init(trackView:trackThreshold:completionHandler:completeCheckHandler:)\/fragments","op":"replace"}]}]}