{"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"kind":"externalParam","text":"trackView"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)GFPImpressionTrackView","text":"GFPImpressionTrackView","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionTrackView"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"trackThreshold"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)GFPImpressionTrackThreshold","text":"GFPImpressionTrackThreshold","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionTrackThreshold"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"keyword","text":"@escaping"},{"kind":"text","text":" "},{"text":"GFPImpressionTrackCompletionHandler","preciseIdentifier":"c:GFPImpressionTracker.h@T@GFPImpressionTrackCompletionHandler","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionTrackCompletionHandler","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpimpressiontrackingtarget\/init(trackview:trackthreshold:completionhandler:)"]},{"paths":["\/documentation\/gfpsdk\/gfpimpressiontrackingtarget\/init(trackview:trackthreshold:completionhandler:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionTrackingTarget\/init(trackView:trackThreshold:completionHandler:)"},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionTrackingTarget"]]},"metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"trackView","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)GFPImpressionTrackView","text":"GFPImpressionTrackView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"trackThreshold","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"GFPImpressionTrackThreshold","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPImpressionTrackThreshold"},{"text":", ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:GFPImpressionTracker.h@T@GFPImpressionTrackCompletionHandler","text":"GFPImpressionTrackCompletionHandler"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithTrackView:trackThreshold:completionHandler:","kind":"identifier"}],"roleHeading":"Initializer","modules":[{"name":"GFPSDK"}],"externalID":"c:objc(cs)GFPImpressionTrackingTarget(im)initWithTrackView:trackThreshold:completionHandler:","role":"symbol","title":"init(trackView:trackThreshold:completionHandler:)","symbolKind":"init"},"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPImpressionTrackingTarget":{"navigatorTitle":[{"text":"GFPImpressionTrackingTarget","kind":"identifier"}],"title":"GFPImpressionTrackingTarget","url":"\/documentation\/gfpsdk\/gfpimpressiontrackingtarget","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionTrackingTarget","role":"symbol","type":"topic","kind":"symbol","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPImpressionTrackingTarget","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPImpressionTrackCompletionHandler":{"type":"topic","url":"\/documentation\/gfpsdk\/gfpimpressiontrackcompletionhandler","title":"GFPImpressionTrackCompletionHandler","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPImpressionTrackCompletionHandler","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"GFPImpressionTrackCompletionHandler","kind":"identifier"}],"kind":"symbol","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionTrackCompletionHandler"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPImpressionTrackingTarget/init(trackView:trackThreshold:completionHandler:)":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionTrackingTarget\/init(trackView:trackThreshold:completionHandler:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"trackView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPImpressionTrackView","text":"GFPImpressionTrackView"},{"kind":"text","text":", "},{"text":"trackThreshold","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)GFPImpressionTrackThreshold","kind":"typeIdentifier","text":"GFPImpressionTrackThreshold"},{"text":", ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"GFPImpressionTrackCompletionHandler","kind":"typeIdentifier","preciseIdentifier":"c:GFPImpressionTracker.h@T@GFPImpressionTrackCompletionHandler"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"initWithTrackView:trackThreshold:completionHandler:"}],"type":"topic","role":"symbol","url":"\/documentation\/gfpsdk\/gfpimpressiontrackingtarget\/init(trackview:trackthreshold:completionhandler:)","title":"init(trackView:trackThreshold:completionHandler:)","kind":"symbol","abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPImpressionTrackThreshold":{"title":"GFPImpressionTrackThreshold","url":"\/documentation\/gfpsdk\/gfpimpressiontrackthreshold","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPImpressionTrackThreshold"}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"GFPImpressionTrackThreshold","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionTrackThreshold","abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPImpressionTrackView":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"GFPImpressionTrackView","kind":"identifier"}],"role":"symbol","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionTrackView","kind":"symbol","type":"topic","url":"\/documentation\/gfpsdk\/gfpimpressiontrackview","title":"GFPImpressionTrackView","navigatorTitle":[{"kind":"identifier","text":"GFPImpressionTrackView"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"initWithTrackView:trackThreshold:completionHandler:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithTrackView:trackThreshold:completionHandler:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithTrackView:"},{"kind":"text","text":"("},{"text":"GFPImpressionTrackView","preciseIdentifier":"c:objc(cs)GFPImpressionTrackView","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionTrackView","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"trackView"},{"text":" ","kind":"text"},{"kind":"identifier","text":"trackThreshold:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)GFPImpressionTrackThreshold","text":"GFPImpressionTrackThreshold","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionTrackThreshold"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"trackThreshold"},{"kind":"text","text":" "},{"kind":"identifier","text":"completionHandler:"},{"kind":"text","text":"("},{"text":"void (^)(GFPImpressionTrackingTarget *)","kind":"typeIdentifier","preciseIdentifier":"c:BFv(#*$objc(cs)GFPImpressionTrackingTarget)"},{"kind":"text","text":") "},{"kind":"internalParam","text":"completionHandler"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTrackingTarget\/title","op":"replace","value":"GFPImpressionTrackingTarget"},{"value":[{"kind":"identifier","text":"GFPImpressionTrackingTarget"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTrackingTarget\/fragments"},{"value":[{"kind":"identifier","text":"GFPImpressionTrackingTarget"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTrackingTarget\/navigatorTitle","op":"replace"},{"op":"replace","value":"GFPImpressionTrackCompletionHandler","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTrackCompletionHandler\/title"},{"op":"replace","value":[{"text":"GFPImpressionTrackCompletionHandler","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTrackCompletionHandler\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTrackCompletionHandler\/navigatorTitle","value":[{"text":"GFPImpressionTrackCompletionHandler","kind":"identifier"}]},{"op":"replace","value":"initWithTrackView:trackThreshold:completionHandler:","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTrackingTarget~1init(trackView:trackThreshold:completionHandler:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTrackingTarget~1init(trackView:trackThreshold:completionHandler:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithTrackView:trackThreshold:completionHandler:"}]},{"value":"GFPImpressionTrackThreshold","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTrackThreshold\/title"},{"op":"replace","value":[{"kind":"identifier","text":"GFPImpressionTrackThreshold"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTrackThreshold\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"GFPImpressionTrackThreshold"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTrackThreshold\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTrackView\/title","value":"GFPImpressionTrackView"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTrackView\/fragments","value":[{"kind":"identifier","text":"GFPImpressionTrackView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTrackView\/navigatorTitle","value":[{"kind":"identifier","text":"GFPImpressionTrackView"}]}]}]}