{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpimpressiontrackingtarget\/trackview"]},{"paths":["\/documentation\/gfpsdk\/gfpimpressiontrackingtarget\/trackview"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"trackView"},{"kind":"text","text":": "},{"text":"GFPImpressionTrackView","preciseIdentifier":"c:objc(cs)GFPImpressionTrackView","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionTrackView"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"metadata":{"symbolKind":"property","title":"trackView","modules":[{"name":"GFPSDK"}],"role":"symbol","externalID":"c:objc(cs)GFPImpressionTrackingTarget(py)trackView","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"trackView","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"GFPImpressionTrackView","preciseIdentifier":"c:objc(cs)GFPImpressionTrackView"}],"navigatorTitle":[{"text":"trackView","kind":"identifier"}]},"kind":"symbol","identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionTrackingTarget\/trackView","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionTrackingTarget"]]},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPImpressionTrackingTarget/trackView":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"trackView"}],"title":"trackView","url":"\/documentation\/gfpsdk\/gfpimpressiontrackingtarget\/trackview","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionTrackingTarget\/trackView","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"trackView","kind":"identifier"},{"text":": ","kind":"text"},{"text":"GFPImpressionTrackView","preciseIdentifier":"c:objc(cs)GFPImpressionTrackView","kind":"typeIdentifier"}],"abstract":[],"type":"topic","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPImpressionTrackView":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"GFPImpressionTrackView","kind":"identifier"}],"role":"symbol","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionTrackView","kind":"symbol","type":"topic","url":"\/documentation\/gfpsdk\/gfpimpressiontrackview","title":"GFPImpressionTrackView","navigatorTitle":[{"kind":"identifier","text":"GFPImpressionTrackView"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPImpressionTrackingTarget":{"navigatorTitle":[{"text":"GFPImpressionTrackingTarget","kind":"identifier"}],"title":"GFPImpressionTrackingTarget","url":"\/documentation\/gfpsdk\/gfpimpressiontrackingtarget","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionTrackingTarget","role":"symbol","type":"topic","kind":"symbol","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPImpressionTrackingTarget","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","value":"trackView","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"kind":"identifier","text":"trackView"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)GFPImpressionTrackView","text":"GFPImpressionTrackView","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionTrackView"},{"kind":"text","text":" * "},{"kind":"identifier","text":"trackView"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTrackingTarget~1trackView\/title","value":"trackView"},{"value":[{"text":"trackView","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTrackingTarget~1trackView\/fragments","op":"replace"},{"value":"GFPImpressionTrackView","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTrackView\/title"},{"op":"replace","value":[{"text":"GFPImpressionTrackView","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTrackView\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTrackView\/navigatorTitle","value":[{"kind":"identifier","text":"GFPImpressionTrackView"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTrackingTarget\/title","value":"GFPImpressionTrackingTarget"},{"op":"replace","value":[{"kind":"identifier","text":"GFPImpressionTrackingTarget"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTrackingTarget\/fragments"},{"op":"replace","value":[{"text":"GFPImpressionTrackingTarget","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTrackingTarget\/navigatorTitle"}]}]}