source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '13.0'

def real_podspec # Real
  pod 'NAMSDK', '>= 8.0.0'
  pod 'NAMSDK/MediationNDA', '>= 8.0.0'
  pod 'NAMSDK/MediationNDAVideo', '>= 8.0.0'
  pod 'NAMSDK/MediationNDARich', '>= 8.0.0'

  pod 'NAMSDKMediationDFP'
  pod 'NAMSDKMediationIMA'
  pod 'NAMSDKMediationFAN'
  pod 'NAMSDKMediationInMobi'
  pod 'NAMSDKMediationUnity'
  pod 'NAMSDKMediationAppLovin'
  pod 'NAMSDKMediationVungle'
  pod 'NAMSDKMediationDT'
  pod 'NAMSDKMediationIronSource'
  pod 'NAMSDKMediationAPS'
  pod 'NAMSDKMediationLAN'
end


def local_podspec # Local
  pod 'NAMSDK', :path => "../"               # SDK 본체
  pod 'NAMSDK/MediationNDA', :path => "../"
  pod 'NAMSDK/MediationNDAVideo', :path => "../"
  pod 'NAMSDK/MediationNDARich', :path => "../"

  pod 'NAMSDKMediationDFP', :path => "../"
  pod 'NAMSDKMediationIMA', :path => "../"
  pod 'NAMSDKMediationFAN', :path => "../"
  pod 'NAMSDKMediationInMobi', :path => "../"
  pod 'NAMSDKMediationUnity', :path => "../"
  pod 'NAMSDKMediationAppLovin', :path => "../"
  pod 'NAMSDKMediationVungle', :path => "../"
  pod 'NAMSDKMediationDT', :path => "../"
  pod 'NAMSDKMediationIronSource', :path => "../"
  pod 'NAMSDKMediationAPS', :path => "../"
  pod 'NAMSDKMediationLAN', :path => "../"
end


def headerBidding_sdk
  pod 'AmazonPublisherServicesSDK' # 헤더비딩 Amazon
end

def sample
  pod 'SnapKit'
end

target 'SwiftSample' do
  use_frameworks!
  
  #local_podspec
  real_podspec
  headerBidding_sdk
  sample

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    
    target.build_configurations.each do |config|
      
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'  

    end
  end
end
