{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpbannermediatordelegate\/bannermediator(_:didload:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpbannermediatordelegate\/bannermediator(_:didload:)"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerMediatorDelegate"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"bannerMediator"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"mediator"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPBannerMediator","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerMediator","text":"GFPBannerMediator"},{"kind":"text","text":", "},{"text":"didLoad","kind":"externalParam"},{"kind":"text","text":" "},{"text":"nativeAd","kind":"internalParam"},{"kind":"text","text":": "},{"text":"GFPNativeAd","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAd","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPNativeAd"},{"text":")","kind":"text"}]}]}],"metadata":{"symbolKind":"method","title":"bannerMediator(_:didLoad:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"bannerMediator"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GFPBannerMediator","preciseIdentifier":"c:objc(cs)GFPBannerMediator"},{"text":", ","kind":"text"},{"text":"didLoad","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"GFPNativeAd","preciseIdentifier":"c:objc(cs)GFPNativeAd","kind":"typeIdentifier"},{"kind":"text","text":")"}],"role":"symbol","roleHeading":"Instance Method","navigatorTitle":[{"text":"bannerMediator:didLoadNativeAd:","kind":"identifier"}],"externalID":"c:objc(pl)GFPBannerMediatorDelegate(im)bannerMediator:didLoadNativeAd:","required":true,"modules":[{"name":"GFPSDK"}]},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerMediatorDelegate\/bannerMediator(_:didLoad:)","interfaceLanguage":"swift"},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerMediatorDelegate/bannerMediator(_:didLoad:)":{"navigatorTitle":[{"kind":"identifier","text":"bannerMediator:didLoadNativeAd:"}],"role":"symbol","kind":"symbol","title":"bannerMediator(_:didLoad:)","required":true,"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"bannerMediator","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)GFPBannerMediator","text":"GFPBannerMediator","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didLoad"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)GFPNativeAd","kind":"typeIdentifier","text":"GFPNativeAd"},{"text":")","kind":"text"}],"type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerMediatorDelegate\/bannerMediator(_:didLoad:)","abstract":[],"url":"\/documentation\/gfpsdk\/gfpbannermediatordelegate\/bannermediator(_:didload:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerMediator":{"type":"topic","navigatorTitle":[{"text":"GFPBannerMediator","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/gfpsdk\/gfpbannermediator","role":"symbol","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPBannerMediator"}],"title":"GFPBannerMediator","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerMediator"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAd":{"abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAd","url":"\/documentation\/gfpsdk\/gfpnativead","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPNativeAd"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPNativeAd"}],"type":"topic","kind":"symbol","title":"GFPNativeAd"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerMediatorDelegate":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"GFPBannerMediatorDelegate"}],"kind":"symbol","url":"\/documentation\/gfpsdk\/gfpbannermediatordelegate","role":"symbol","abstract":[],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPBannerMediatorDelegate"}],"title":"GFPBannerMediatorDelegate","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerMediatorDelegate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","value":"bannerMediator:didLoadNativeAd:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"bannerMediator:didLoadNativeAd:","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"bannerMediator:"},{"text":"(","kind":"text"},{"text":"GFPBannerMediator","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerMediator","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPBannerMediator"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"mediator"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didLoadNativeAd:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPNativeAd","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAd","text":"GFPNativeAd"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"nativeAd"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"bannerMediator:didLoadNativeAd:","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerMediatorDelegate~1bannerMediator(_:didLoad:)\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerMediatorDelegate~1bannerMediator(_:didLoad:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"bannerMediator:didLoadNativeAd:","kind":"identifier"}]},{"value":"GFPBannerMediator","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerMediator\/title"},{"value":[{"kind":"identifier","text":"GFPBannerMediator"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerMediator\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"GFPBannerMediator"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerMediator\/navigatorTitle"},{"value":"GFPNativeAd","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAd\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAd\/fragments","value":[{"text":"GFPNativeAd","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"GFPNativeAd"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAd\/navigatorTitle","op":"replace"},{"value":"GFPBannerMediatorDelegate","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerMediatorDelegate\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerMediatorDelegate\/fragments","op":"replace","value":[{"text":"GFPBannerMediatorDelegate","kind":"identifier"}]},{"value":[{"text":"GFPBannerMediatorDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerMediatorDelegate\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}