{"metadata":{"modules":[{"name":"GFPSDK"}],"externalID":"c:objc(pl)GFPBannerMediatorDelegate(im)bannerMediator:didFailToLoadBannerAdaptorWithError:","symbolKind":"method","title":"bannerMediator(_:didFailToLoadBannerAdaptorWithError:)","navigatorTitle":[{"kind":"identifier","text":"bannerMediator:didFailToLoadBannerAdaptorWithError:"}],"roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"bannerMediator","kind":"identifier"},{"kind":"text","text":"("},{"text":"GFPBannerMediator","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPBannerMediator"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didFailToLoadBannerAdaptorWithError"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@NaverAdsServices@objc(cs)GFPError","text":"GFPError","kind":"typeIdentifier"},{"text":")","kind":"text"}],"required":true,"role":"symbol"},"sections":[],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpbannermediatordelegate\/bannermediator(_:didfailtoloadbanneradaptorwitherror:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpbannermediatordelegate\/bannermediator(_:didfailtoloadbanneradaptorwitherror:)"]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerMediatorDelegate"]]},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerMediatorDelegate\/bannerMediator(_:didFailToLoadBannerAdaptorWithError:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bannerMediator","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"mediator"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerMediator","text":"GFPBannerMediator","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPBannerMediator"},{"kind":"text","text":", "},{"text":"didFailToLoadBannerAdaptorWithError","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"error"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@NaverAdsServices@objc(cs)GFPError","text":"GFPError","kind":"typeIdentifier"},{"text":")","kind":"text"}]}],"kind":"declarations"}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerMediatorDelegate":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"GFPBannerMediatorDelegate"}],"kind":"symbol","url":"\/documentation\/gfpsdk\/gfpbannermediatordelegate","role":"symbol","abstract":[],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPBannerMediatorDelegate"}],"title":"GFPBannerMediatorDelegate","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerMediatorDelegate"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerMediator":{"type":"topic","navigatorTitle":[{"text":"GFPBannerMediator","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/gfpsdk\/gfpbannermediator","role":"symbol","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPBannerMediator"}],"title":"GFPBannerMediator","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerMediator"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerMediatorDelegate/bannerMediator(_:didFailToLoadBannerAdaptorWithError:)":{"title":"bannerMediator(_:didFailToLoadBannerAdaptorWithError:)","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerMediatorDelegate\/bannerMediator(_:didFailToLoadBannerAdaptorWithError:)","role":"symbol","url":"\/documentation\/gfpsdk\/gfpbannermediatordelegate\/bannermediator(_:didfailtoloadbanneradaptorwitherror:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"bannerMediator:didFailToLoadBannerAdaptorWithError:"}],"type":"topic","required":true,"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bannerMediator"},{"text":"(","kind":"text"},{"text":"GFPBannerMediator","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPBannerMediator"},{"text":", ","kind":"text"},{"text":"didFailToLoadBannerAdaptorWithError","kind":"externalParam"},{"kind":"text","text":": "},{"text":"GFPError","kind":"typeIdentifier","preciseIdentifier":"c:@M@NaverAdsServices@objc(cs)GFPError"},{"kind":"text","text":")"}],"abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"bannerMediator:didFailToLoadBannerAdaptorWithError:","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"bannerMediator:didFailToLoadBannerAdaptorWithError:"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"text":"bannerMediator:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"GFPBannerMediator","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPBannerMediator","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerMediator"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"mediator"},{"kind":"text","text":" "},{"kind":"identifier","text":"didFailToLoadBannerAdaptorWithError:"},{"text":"(","kind":"text"},{"text":"GFPError","kind":"typeIdentifier","preciseIdentifier":"c:@M@NaverAdsServices@objc(cs)GFPError"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"error"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"value":"GFPBannerMediatorDelegate","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerMediatorDelegate\/title","op":"replace"},{"op":"replace","value":[{"text":"GFPBannerMediatorDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerMediatorDelegate\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerMediatorDelegate\/navigatorTitle","value":[{"text":"GFPBannerMediatorDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerMediator\/title","value":"GFPBannerMediator"},{"value":[{"text":"GFPBannerMediator","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerMediator\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerMediator\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"GFPBannerMediator"}]},{"op":"replace","value":"bannerMediator:didFailToLoadBannerAdaptorWithError:","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerMediatorDelegate~1bannerMediator(_:didFailToLoadBannerAdaptorWithError:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"bannerMediator:didFailToLoadBannerAdaptorWithError:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerMediatorDelegate~1bannerMediator(_:didFailToLoadBannerAdaptorWithError:)\/fragments"}]}]}