{"metadata":{"title":"combined(with:)","role":"symbol","modules":[{"name":"GFPSDK"}],"roleHeading":"Instance Method","symbolKind":"method","navigatorTitle":[{"text":"combinedWith:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"combined","kind":"identifier"},{"kind":"text","text":"("},{"text":"with","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)GFPExtraRequestParam","text":"GFPExtraRequestParam","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"GFPExtraRequestParam","preciseIdentifier":"c:objc(cs)GFPExtraRequestParam","kind":"typeIdentifier"}],"externalID":"c:objc(cs)GFPExtraRequestParam(im)combinedWith:"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"combined","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"with"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"requestParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPExtraRequestParam","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPExtraRequestParam","text":"GFPExtraRequestParam","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"GFPExtraRequestParam","preciseIdentifier":"c:objc(cs)GFPExtraRequestParam","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPExtraRequestParam"}]}]}],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpextrarequestparam\/combined(with:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpextrarequestparam\/combined(with:)"]}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPExtraRequestParam"]]},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPExtraRequestParam\/combined(with:)","interfaceLanguage":"swift"},"sections":[],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPExtraRequestParam":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPExtraRequestParam","type":"topic","abstract":[],"url":"\/documentation\/gfpsdk\/gfpextrarequestparam","navigatorTitle":[{"text":"GFPExtraRequestParam","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"GFPExtraRequestParam","kind":"identifier"}],"title":"GFPExtraRequestParam","role":"symbol","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPExtraRequestParam/combined(with:)":{"type":"topic","abstract":[],"title":"combined(with:)","role":"symbol","url":"\/documentation\/gfpsdk\/gfpextrarequestparam\/combined(with:)","navigatorTitle":[{"text":"combinedWith:","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPExtraRequestParam\/combined(with:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"combined","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"with"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPExtraRequestParam","kind":"typeIdentifier","text":"GFPExtraRequestParam"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPExtraRequestParam","text":"GFPExtraRequestParam"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"combinedWith:","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"combinedWith:"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"GFPExtraRequestParam","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPExtraRequestParam","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPExtraRequestParam"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"combinedWith:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPExtraRequestParam","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPExtraRequestParam","text":"GFPExtraRequestParam"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"requestParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"GFPExtraRequestParam","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPExtraRequestParam\/title"},{"value":[{"text":"GFPExtraRequestParam","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPExtraRequestParam\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPExtraRequestParam\/navigatorTitle","value":[{"kind":"identifier","text":"GFPExtraRequestParam"}],"op":"replace"},{"op":"replace","value":"combinedWith:","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPExtraRequestParam~1combined(with:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"combinedWith:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPExtraRequestParam~1combined(with:)\/fragments"}]}]}