{"metadata":{"role":"symbol","modules":[{"name":"GFPSDK"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"?([","kind":"text"},{"preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier","text":"AnyHashable"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"])","kind":"text"}],"externalID":"c:objc(cs)GFPExtraRequestParam(im)initWith:","roleHeading":"Initializer","title":"init(_:)","navigatorTitle":[{"text":"initWith:","kind":"identifier"}],"symbolKind":"init"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"aDict","kind":"internalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"])","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPExtraRequestParam\/init(_:)"},"variants":[{"paths":["\/documentation\/gfpsdk\/gfpextrarequestparam\/init(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpextrarequestparam\/init(_:)"]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPExtraRequestParam"]]},"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPExtraRequestParam/init(_:)":{"role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPExtraRequestParam\/init(_:)","url":"\/documentation\/gfpsdk\/gfpextrarequestparam\/init(_:)","navigatorTitle":[{"kind":"identifier","text":"initWith:"}],"title":"init(_:)","abstract":[],"type":"topic","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?(["},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"kind":"text","text":"])"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPExtraRequestParam":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPExtraRequestParam","type":"topic","abstract":[],"url":"\/documentation\/gfpsdk\/gfpextrarequestparam","navigatorTitle":[{"text":"GFPExtraRequestParam","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"GFPExtraRequestParam","kind":"identifier"}],"title":"GFPExtraRequestParam","role":"symbol","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","value":"initWith:","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWith:"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWith:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSDictionary","text":"NSDictionary","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"aDict","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPExtraRequestParam~1init(_:)\/title","value":"initWith:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWith:"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPExtraRequestParam~1init(_:)\/fragments"},{"value":"GFPExtraRequestParam","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPExtraRequestParam\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPExtraRequestParam\/fragments","op":"replace","value":[{"text":"GFPExtraRequestParam","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPExtraRequestParam\/navigatorTitle","value":[{"kind":"identifier","text":"GFPExtraRequestParam"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}