{"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoMediator\/loadVideoAdaptorWithAdUnitID:videoContext:adParam:videoParam:timeoutInterval:","interfaceLanguage":"occ"},"metadata":{"roleHeading":"Instance Method","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"loadVideoAdaptorWithAdUnitID:videoContext:adParam:videoParam:timeoutInterval:"}],"fragments":[{"kind":"text","text":"- "},{"text":"loadVideoAdaptorWithAdUnitID:videoContext:adParam:videoParam:timeoutInterval:","kind":"identifier"}],"modules":[{"name":"GFPSDK"}],"symbolKind":"method","externalID":"c:objc(cs)GFPVideoMediator(im)loadVideoAdaptorWithAdUnitID:videoContext:adParam:videoParam:timeoutInterval:","title":"loadVideoAdaptorWithAdUnitID:videoContext:adParam:videoParam:timeoutInterval:"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"loadVideoAdaptorWithAdUnitID:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"adUnitID"},{"kind":"text","text":" "},{"text":"videoContext:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoContext","text":"GFPVideoContext"},{"text":" *) ","kind":"text"},{"text":"videoContext","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"adParam:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)GFPAdParam","text":"GFPAdParam","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdParam","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"adParam","kind":"internalParam"},{"kind":"text","text":" "},{"text":"videoParam:","kind":"identifier"},{"kind":"text","text":"("},{"text":"GFPVideoAdParam","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdParam","preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPVideoAdParam"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"videoParam"},{"kind":"text","text":" "},{"text":"timeoutInterval:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"NSTimeInterval"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"timeoutInterval"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpvideomediator\/loadvideoadaptorwithadunitid:videocontext:adparam:videoparam:timeoutinterval:"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoMediator"]]},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdParam":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdParam","abstract":[],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPAdParam"}],"navigatorTitle":[{"text":"GFPAdParam","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpadparam","type":"topic","kind":"symbol","title":"GFPAdParam"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoMediator/loadVideoAdaptorWithAdUnitID:videoContext:adParam:videoParam:timeoutInterval:":{"title":"loadVideoAdaptorWithAdUnitID:videoContext:adParam:videoParam:timeoutInterval:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"loadVideoAdaptorWithAdUnitID:videoContext:adParam:videoParam:timeoutInterval:"}],"role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoMediator\/loadVideoAdaptorWithAdUnitID:videoContext:adParam:videoParam:timeoutInterval:","navigatorTitle":[{"text":"loadVideoAdaptorWithAdUnitID:videoContext:adParam:videoParam:timeoutInterval:","kind":"identifier"}],"abstract":[],"kind":"symbol","url":"\/documentation\/gfpsdk\/gfpvideomediator\/loadvideoadaptorwithadunitid:videocontext:adparam:videoparam:timeoutinterval:","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoMediator":{"title":"GFPVideoMediator","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoMediator","role":"symbol","kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPVideoMediator"}],"navigatorTitle":[{"kind":"identifier","text":"GFPVideoMediator"}],"type":"topic","url":"\/documentation\/gfpsdk\/gfpvideomediator"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdParam":{"abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPVideoAdParam"}],"role":"symbol","navigatorTitle":[{"text":"GFPVideoAdParam","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdParam","url":"\/documentation\/gfpsdk\/gfpvideoadparam","kind":"symbol","title":"GFPVideoAdParam"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdParam\/title","op":"replace","value":"GFPAdParam"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdParam\/fragments","value":[{"kind":"identifier","text":"GFPAdParam"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdParam\/navigatorTitle","value":[{"kind":"identifier","text":"GFPAdParam"}]},{"op":"replace","value":"GFPVideoMediator","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoMediator\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoMediator\/fragments","value":[{"kind":"identifier","text":"GFPVideoMediator"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoMediator\/navigatorTitle","value":[{"text":"GFPVideoMediator","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdParam\/title","op":"replace","value":"GFPVideoAdParam"},{"value":[{"kind":"identifier","text":"GFPVideoAdParam"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdParam\/fragments"},{"value":[{"kind":"identifier","text":"GFPVideoAdParam"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdParam\/navigatorTitle"}]}]}