{"metadata":{"symbolKind":"property","role":"symbol","externalID":"c:objc(cs)GFPVideoMediator(py)reportDelegate","modules":[{"name":"GFPSDK"}],"navigatorTitle":[{"text":"reportDelegate","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"reportDelegate"},{"text":": (any ","kind":"text"},{"kind":"typeIdentifier","text":"GFPEventReportDelegate","preciseIdentifier":"c:objc(pl)GFPEventReportDelegate"},{"text":")?","kind":"text"}],"roleHeading":"Instance Property","title":"reportDelegate"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"weak"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"reportDelegate"},{"kind":"text","text":": (any "},{"text":"GFPEventReportDelegate","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)GFPEventReportDelegate","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPEventReportDelegate"},{"text":")? { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpvideomediator\/reportdelegate"]},{"paths":["\/documentation\/gfpsdk\/gfpvideomediator\/reportdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoMediator"]]},"kind":"symbol","identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoMediator\/reportDelegate","interfaceLanguage":"swift"},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoMediator":{"title":"GFPVideoMediator","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoMediator","role":"symbol","kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPVideoMediator"}],"navigatorTitle":[{"kind":"identifier","text":"GFPVideoMediator"}],"type":"topic","url":"\/documentation\/gfpsdk\/gfpvideomediator"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoMediator/reportDelegate":{"title":"reportDelegate","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"reportDelegate"},{"text":": (any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)GFPEventReportDelegate","text":"GFPEventReportDelegate"},{"text":")?","kind":"text"}],"role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoMediator\/reportDelegate","navigatorTitle":[{"kind":"identifier","text":"reportDelegate"}],"abstract":[],"kind":"symbol","url":"\/documentation\/gfpsdk\/gfpvideomediator\/reportdelegate","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPEventReportDelegate":{"kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPEventReportDelegate","title":"GFPEventReportDelegate","url":"\/documentation\/gfpsdk\/gfpeventreportdelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"GFPEventReportDelegate","kind":"identifier"}],"abstract":[],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPEventReportDelegate"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"reportDelegate","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"reportDelegate","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"weak","kind":"keyword"},{"kind":"text","text":") "},{"text":"id<GFPEventReportDelegate>","kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)GFPEventReportDelegate"},{"kind":"text","text":" "},{"text":"reportDelegate","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoMediator\/title","op":"replace","value":"GFPVideoMediator"},{"op":"replace","value":[{"kind":"identifier","text":"GFPVideoMediator"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoMediator\/fragments"},{"op":"replace","value":[{"text":"GFPVideoMediator","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoMediator\/navigatorTitle"},{"op":"replace","value":"reportDelegate","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoMediator~1reportDelegate\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoMediator~1reportDelegate\/fragments","value":[{"text":"reportDelegate","kind":"identifier"}]},{"op":"replace","value":"GFPEventReportDelegate","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPEventReportDelegate\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPEventReportDelegate\/fragments","op":"replace","value":[{"text":"GFPEventReportDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPEventReportDelegate\/navigatorTitle","op":"replace","value":[{"text":"GFPEventReportDelegate","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}