{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfprewardedadadaptordelegate\/rewardedadadaptor(_:didcompletewith:)"]},{"paths":["\/documentation\/gfpsdk\/gfprewardedadadaptordelegate\/rewardedadadaptor(_:didcompletewith:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdAdaptorDelegate"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"rewardedAdAdaptor"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"rewardedAdAdaptor","kind":"internalParam"},{"text":": any ","kind":"text"},{"kind":"typeIdentifier","text":"GFPAdAdaptor","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAdaptor","preciseIdentifier":"c:objc(cs)GFPAdAdaptor"},{"text":" & ","kind":"text"},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdAdapting","preciseIdentifier":"c:objc(pl)GFPRewardedAdAdapting","text":"GFPRewardedAdAdapting","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didCompleteWith"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"reward"},{"kind":"text","text":": "},{"text":"GFPReward","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPReward","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPReward"},{"kind":"text","text":"?)"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdAdaptorDelegate\/rewardedAdAdaptor(_:didCompleteWith:)"},"kind":"symbol","metadata":{"title":"rewardedAdAdaptor(_:didCompleteWith:)","symbolKind":"method","modules":[{"name":"GFPSDK"}],"role":"symbol","externalID":"c:objc(pl)GFPRewardedAdAdaptorDelegate(im)rewardedAdAdaptor:didCompleteWithReward:","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rewardedAdAdaptor"},{"kind":"text","text":"(any "},{"text":"GFPAdAdaptor","preciseIdentifier":"c:objc(cs)GFPAdAdaptor","kind":"typeIdentifier"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"GFPRewardedAdAdapting","preciseIdentifier":"c:objc(pl)GFPRewardedAdAdapting"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didCompleteWith"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPReward","text":"GFPReward","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"required":true,"navigatorTitle":[{"kind":"identifier","text":"rewardedAdAdaptor:didCompleteWithReward:"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRewardedAdAdapting":{"type":"topic","abstract":[],"role":"symbol","title":"GFPRewardedAdAdapting","kind":"symbol","url":"\/documentation\/gfpsdk\/gfprewardedadadapting","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPRewardedAdAdapting","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"GFPRewardedAdAdapting"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdAdapting"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPReward":{"kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPReward","url":"\/documentation\/gfpsdk\/gfpreward","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPReward","kind":"identifier"}],"title":"GFPReward","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GFPReward"}],"abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRewardedAdAdaptorDelegate/rewardedAdAdaptor(_:didCompleteWith:)":{"required":true,"role":"symbol","abstract":[],"title":"rewardedAdAdaptor(_:didCompleteWith:)","navigatorTitle":[{"kind":"identifier","text":"rewardedAdAdaptor:didCompleteWithReward:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rewardedAdAdaptor","kind":"identifier"},{"text":"(any ","kind":"text"},{"text":"GFPAdAdaptor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdAdaptor"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"GFPRewardedAdAdapting","preciseIdentifier":"c:objc(pl)GFPRewardedAdAdapting"},{"kind":"text","text":", "},{"text":"didCompleteWith","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPReward","text":"GFPReward"},{"text":"?)","kind":"text"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdAdaptorDelegate\/rewardedAdAdaptor(_:didCompleteWith:)","url":"\/documentation\/gfpsdk\/gfprewardedadadaptordelegate\/rewardedadadaptor(_:didcompletewith:)","kind":"symbol","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdAdaptor":{"navigatorTitle":[{"kind":"identifier","text":"GFPAdAdaptor"}],"title":"GFPAdAdaptor","url":"\/documentation\/gfpsdk\/gfpadadaptor","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAdaptor","abstract":[],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPAdAdaptor"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRewardedAdAdaptorDelegate":{"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"GFPRewardedAdAdaptorDelegate","kind":"identifier"}],"abstract":[],"kind":"symbol","title":"GFPRewardedAdAdaptorDelegate","navigatorTitle":[{"text":"GFPRewardedAdAdaptorDelegate","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdAdaptorDelegate","url":"\/documentation\/gfpsdk\/gfprewardedadadaptordelegate"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"rewardedAdAdaptor:didCompleteWithReward:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"rewardedAdAdaptor:didCompleteWithReward:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"rewardedAdAdaptor:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Q$objc(cs)GFPAdAdaptorobjc(pl)GFPRewardedAdAdapting","text":"GFPAdAdaptor<GFPRewardedAdAdapting>","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"rewardedAdAdaptor"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didCompleteWithReward:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GFPReward","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPReward","preciseIdentifier":"c:objc(cs)GFPReward"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"reward"},{"kind":"text","text":";"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdAdapting\/title","op":"replace","value":"GFPRewardedAdAdapting"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdAdapting\/fragments","op":"replace","value":[{"kind":"identifier","text":"GFPRewardedAdAdapting"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdAdapting\/navigatorTitle","value":[{"text":"GFPRewardedAdAdapting","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPReward\/title","op":"replace","value":"GFPReward"},{"value":[{"text":"GFPReward","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPReward\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPReward\/navigatorTitle","value":[{"text":"GFPReward","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdAdaptorDelegate~1rewardedAdAdaptor(_:didCompleteWith:)\/title","value":"rewardedAdAdaptor:didCompleteWithReward:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rewardedAdAdaptor:didCompleteWithReward:"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdAdaptorDelegate~1rewardedAdAdaptor(_:didCompleteWith:)\/fragments"},{"op":"replace","value":"GFPAdAdaptor","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdaptor\/title"},{"value":[{"kind":"identifier","text":"GFPAdAdaptor"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdaptor\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdaptor\/navigatorTitle","value":[{"text":"GFPAdAdaptor","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"GFPRewardedAdAdaptorDelegate","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdAdaptorDelegate\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdAdaptorDelegate\/fragments","op":"replace","value":[{"text":"GFPRewardedAdAdaptorDelegate","kind":"identifier"}]},{"value":[{"text":"GFPRewardedAdAdaptorDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdAdaptorDelegate\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}