{"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"rewardedAdAdaptor","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"rewardedAdAdaptor","kind":"internalParam"},{"text":": any ","kind":"text"},{"text":"GFPAdAdaptor","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAdaptor","preciseIdentifier":"c:objc(cs)GFPAdAdaptor"},{"text":" & ","kind":"text"},{"kind":"typeIdentifier","text":"GFPRewardedAdAdapting","preciseIdentifier":"c:objc(pl)GFPRewardedAdAdapting","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdAdapting"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didChangedMute"},{"text":" ","kind":"text"},{"text":"isMuted","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}]}],"kind":"declarations"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfprewardedadadaptordelegate\/rewardedadadaptor(_:didchangedmute:)"]},{"paths":["\/documentation\/gfpsdk\/gfprewardedadadaptordelegate\/rewardedadadaptor(_:didchangedmute:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdAdaptorDelegate\/rewardedAdAdaptor(_:didChangedMute:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdAdaptorDelegate"]]},"metadata":{"externalID":"c:objc(pl)GFPRewardedAdAdaptorDelegate(im)rewardedAdAdaptor:didChangedMute:","required":true,"navigatorTitle":[{"text":"rewardedAdAdaptor:didChangedMute:","kind":"identifier"}],"title":"rewardedAdAdaptor(_:didChangedMute:)","role":"symbol","symbolKind":"method","roleHeading":"Instance Method","modules":[{"name":"GFPSDK"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"rewardedAdAdaptor","kind":"identifier"},{"text":"(any ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPAdAdaptor","text":"GFPAdAdaptor","kind":"typeIdentifier"},{"kind":"text","text":" & "},{"text":"GFPRewardedAdAdapting","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)GFPRewardedAdAdapting"},{"text":", ","kind":"text"},{"text":"didChangedMute","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":")","kind":"text"}]},"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdAdaptor":{"navigatorTitle":[{"kind":"identifier","text":"GFPAdAdaptor"}],"title":"GFPAdAdaptor","url":"\/documentation\/gfpsdk\/gfpadadaptor","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAdaptor","abstract":[],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPAdAdaptor"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRewardedAdAdaptorDelegate":{"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"GFPRewardedAdAdaptorDelegate","kind":"identifier"}],"abstract":[],"kind":"symbol","title":"GFPRewardedAdAdaptorDelegate","navigatorTitle":[{"text":"GFPRewardedAdAdaptorDelegate","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdAdaptorDelegate","url":"\/documentation\/gfpsdk\/gfprewardedadadaptordelegate"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRewardedAdAdapting":{"type":"topic","abstract":[],"role":"symbol","title":"GFPRewardedAdAdapting","kind":"symbol","url":"\/documentation\/gfpsdk\/gfprewardedadadapting","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPRewardedAdAdapting","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"GFPRewardedAdAdapting"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdAdapting"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRewardedAdAdaptorDelegate/rewardedAdAdaptor(_:didChangedMute:)":{"required":true,"url":"\/documentation\/gfpsdk\/gfprewardedadadaptordelegate\/rewardedadadaptor(_:didchangedmute:)","navigatorTitle":[{"kind":"identifier","text":"rewardedAdAdaptor:didChangedMute:"}],"abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"rewardedAdAdaptor","kind":"identifier"},{"kind":"text","text":"(any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdAdaptor","text":"GFPAdAdaptor"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"GFPRewardedAdAdapting","preciseIdentifier":"c:objc(pl)GFPRewardedAdAdapting"},{"text":", ","kind":"text"},{"text":"didChangedMute","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdAdaptorDelegate\/rewardedAdAdaptor(_:didChangedMute:)","title":"rewardedAdAdaptor(_:didChangedMute:)"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"rewardedAdAdaptor:didChangedMute:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"rewardedAdAdaptor:didChangedMute:"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"rewardedAdAdaptor:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)GFPAdAdaptorobjc(pl)GFPRewardedAdAdapting","text":"GFPAdAdaptor<GFPRewardedAdAdapting>","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"rewardedAdAdaptor"},{"kind":"text","text":" "},{"kind":"identifier","text":"didChangedMute:"},{"text":"(","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"isMuted"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdaptor\/title","value":"GFPAdAdaptor"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdaptor\/fragments","value":[{"text":"GFPAdAdaptor","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdaptor\/navigatorTitle","value":[{"kind":"identifier","text":"GFPAdAdaptor"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdAdaptorDelegate\/title","value":"GFPRewardedAdAdaptorDelegate"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdAdaptorDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"GFPRewardedAdAdaptorDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdAdaptorDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"GFPRewardedAdAdaptorDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdAdapting\/title","value":"GFPRewardedAdAdapting"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdAdapting\/fragments","value":[{"kind":"identifier","text":"GFPRewardedAdAdapting"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdAdapting\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"GFPRewardedAdAdapting"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdAdaptorDelegate~1rewardedAdAdaptor(_:didChangedMute:)\/title","value":"rewardedAdAdaptor:didChangedMute:","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdAdaptorDelegate~1rewardedAdAdaptor(_:didChangedMute:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"rewardedAdAdaptor:didChangedMute:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}