{"metadata":{"modules":[{"name":"GFPSDK"}],"externalID":"c:objc(pl)GFPRewardedAdAdaptorDelegate(im)rewardedAdAdaptorDidPresentDefaultInAppBrowser:","roleHeading":"Instance Method","title":"rewardedAdAdaptorDidPresentDefault(inAppBrowser:)","role":"symbol","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rewardedAdAdaptorDidPresentDefault","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"inAppBrowser"},{"kind":"text","text":": any "},{"text":"GFPAdAdaptor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdAdaptor"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)GFPRewardedAdAdapting","text":"GFPRewardedAdAdapting"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"rewardedAdAdaptorDidPresentDefaultInAppBrowser:"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"rewardedAdAdaptorDidPresentDefault","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"inAppBrowser"},{"text":" ","kind":"text"},{"text":"rewardedAdAdaptor","kind":"internalParam"},{"text":": any ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPAdAdaptor","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAdaptor","kind":"typeIdentifier","text":"GFPAdAdaptor"},{"text":" & ","kind":"text"},{"preciseIdentifier":"c:objc(pl)GFPRewardedAdAdapting","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdAdapting","kind":"typeIdentifier","text":"GFPRewardedAdAdapting"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfprewardedadadaptordelegate\/rewardedadadaptordidpresentdefault(inappbrowser:)"]},{"paths":["\/documentation\/gfpsdk\/gfprewardedadadaptordelegate\/rewardedadadaptordidpresentdefault(inappbrowser:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdAdaptorDelegate"]]},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdAdaptorDelegate\/rewardedAdAdaptorDidPresentDefault(inAppBrowser:)","interfaceLanguage":"swift"},"sections":[],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRewardedAdAdaptorDelegate/rewardedAdAdaptorDidPresentDefault(inAppBrowser:)":{"role":"symbol","abstract":[],"title":"rewardedAdAdaptorDidPresentDefault(inAppBrowser:)","navigatorTitle":[{"text":"rewardedAdAdaptorDidPresentDefaultInAppBrowser:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"rewardedAdAdaptorDidPresentDefault","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"inAppBrowser"},{"kind":"text","text":": any "},{"preciseIdentifier":"c:objc(cs)GFPAdAdaptor","kind":"typeIdentifier","text":"GFPAdAdaptor"},{"text":" & ","kind":"text"},{"kind":"typeIdentifier","text":"GFPRewardedAdAdapting","preciseIdentifier":"c:objc(pl)GFPRewardedAdAdapting"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdAdaptorDelegate\/rewardedAdAdaptorDidPresentDefault(inAppBrowser:)","url":"\/documentation\/gfpsdk\/gfprewardedadadaptordelegate\/rewardedadadaptordidpresentdefault(inappbrowser:)","kind":"symbol","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRewardedAdAdaptorDelegate":{"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"GFPRewardedAdAdaptorDelegate","kind":"identifier"}],"abstract":[],"kind":"symbol","title":"GFPRewardedAdAdaptorDelegate","navigatorTitle":[{"text":"GFPRewardedAdAdaptorDelegate","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdAdaptorDelegate","url":"\/documentation\/gfpsdk\/gfprewardedadadaptordelegate"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdAdaptor":{"navigatorTitle":[{"kind":"identifier","text":"GFPAdAdaptor"}],"title":"GFPAdAdaptor","url":"\/documentation\/gfpsdk\/gfpadadaptor","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAdaptor","abstract":[],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPAdAdaptor"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRewardedAdAdapting":{"type":"topic","abstract":[],"role":"symbol","title":"GFPRewardedAdAdapting","kind":"symbol","url":"\/documentation\/gfpsdk\/gfprewardedadadapting","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPRewardedAdAdapting","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"GFPRewardedAdAdapting"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdAdapting"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"rewardedAdAdaptorDidPresentDefaultInAppBrowser:","path":"\/metadata\/title","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"rewardedAdAdaptorDidPresentDefaultInAppBrowser:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"rewardedAdAdaptorDidPresentDefaultInAppBrowser:"},{"text":"(","kind":"text"},{"text":"GFPAdAdaptor<GFPRewardedAdAdapting>","preciseIdentifier":"c:Q$objc(cs)GFPAdAdaptorobjc(pl)GFPRewardedAdAdapting","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"rewardedAdAdaptor"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"rewardedAdAdaptorDidPresentDefaultInAppBrowser:","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdAdaptorDelegate~1rewardedAdAdaptorDidPresentDefault(inAppBrowser:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"rewardedAdAdaptorDidPresentDefaultInAppBrowser:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdAdaptorDelegate~1rewardedAdAdaptorDidPresentDefault(inAppBrowser:)\/fragments"},{"value":"GFPRewardedAdAdaptorDelegate","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdAdaptorDelegate\/title"},{"value":[{"text":"GFPRewardedAdAdaptorDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdAdaptorDelegate\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdAdaptorDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"GFPRewardedAdAdaptorDelegate"}]},{"value":"GFPAdAdaptor","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdaptor\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdaptor\/fragments","value":[{"kind":"identifier","text":"GFPAdAdaptor"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdaptor\/navigatorTitle","value":[{"text":"GFPAdAdaptor","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdAdapting\/title","value":"GFPRewardedAdAdapting","op":"replace"},{"value":[{"kind":"identifier","text":"GFPRewardedAdAdapting"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdAdapting\/fragments","op":"replace"},{"value":[{"text":"GFPRewardedAdAdapting","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdAdapting\/navigatorTitle"}]}]}