{"metadata":{"externalID":"c:@M@GFPSDK@objc(cs)GFPCustomAsset(im)initWith:size:lightModeName:darkModeName:","modules":[{"name":"GFPSDK"}],"title":"init(bundle:size:lightModeName:darkModeName:)","roleHeading":"Initializer","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"bundle"},{"text":": ","kind":"text"},{"text":"Bundle","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSBundle"},{"text":"?, ","kind":"text"},{"text":"size","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier","text":"CGSize"},{"kind":"text","text":", "},{"text":"lightModeName","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"darkModeName","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWith:size:lightModeName:darkModeName:","kind":"identifier"}],"symbolKind":"init","role":"symbol"},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(initWith:size:lightModeName:darkModeName:) "},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"bundle","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bundle","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSBundle"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"size"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"text":", ","kind":"text"},{"text":"lightModeName","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"darkModeName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPCustomAsset\/init(bundle:size:lightModeName:darkModeName:)","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPCustomAsset"]]},"variants":[{"paths":["\/documentation\/gfpsdk\/gfpcustomasset\/init(bundle:size:lightmodename:darkmodename:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpcustomasset\/init(bundle:size:lightmodename:darkmodename:)"]}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPCustomAsset":{"kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPCustomAsset","navigatorTitle":[{"kind":"identifier","text":"GFPCustomAsset"}],"title":"GFPCustomAsset","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPCustomAsset"}],"url":"\/documentation\/gfpsdk\/gfpcustomasset","role":"symbol","abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPCustomAsset/init(bundle:size:lightModeName:darkModeName:)":{"navigatorTitle":[{"kind":"identifier","text":"initWith:size:lightModeName:darkModeName:"}],"type":"topic","title":"init(bundle:size:lightModeName:darkModeName:)","kind":"symbol","url":"\/documentation\/gfpsdk\/gfpcustomasset\/init(bundle:size:lightmodename:darkmodename:)","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPCustomAsset\/init(bundle:size:lightModeName:darkModeName:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"bundle","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSBundle","kind":"typeIdentifier","text":"Bundle"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"size"},{"kind":"text","text":": "},{"text":"CGSize","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":", "},{"text":"lightModeName","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"darkModeName","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":")","kind":"text"}],"role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"initWith:size:lightModeName:darkModeName:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWith:size:lightModeName:darkModeName:"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWith:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSBundle","text":"NSBundle","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"bundle"},{"text":" ","kind":"text"},{"kind":"identifier","text":"size:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@S@CGSize","text":"CGSize","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"size","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"lightModeName:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"lightModeName","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"darkModeName:"},{"kind":"text","text":"("},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"darkModeName","kind":"internalParam"},{"kind":"text","text":";"}]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPCustomAsset\/title","value":"GFPCustomAsset"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPCustomAsset\/fragments","value":[{"text":"GFPCustomAsset","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPCustomAsset\/navigatorTitle","value":[{"text":"GFPCustomAsset","kind":"identifier"}],"op":"replace"},{"value":"initWith:size:lightModeName:darkModeName:","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPCustomAsset~1init(bundle:size:lightModeName:darkModeName:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWith:size:lightModeName:darkModeName:"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPCustomAsset~1init(bundle:size:lightModeName:darkModeName:)\/fragments","op":"replace"}]}]}