{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"make"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":" "},{"kind":"internalParam","text":"impType"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@GFPImpressionType","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionType","text":"GFPImpressionType","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"adImpressionInfo","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdImpressionInfo","preciseIdentifier":"c:objc(cs)GFPAdImpressionInfo","text":"GFPAdImpressionInfo","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPImpressionTrackThreshold","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionTrackThreshold","text":"GFPImpressionTrackThreshold"}]}]}],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpimpressiontrackthreshold\/make(with:adimpressioninfo:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gfpsdk\/gfpimpressiontrackthreshold\/make(with:adimpressioninfo:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionTrackThreshold"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionTrackThreshold\/make(with:adImpressionInfo:)"},"sections":[],"metadata":{"title":"make(with:adImpressionInfo:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"make","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"GFPImpressionType","kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPImpressionType"},{"text":", ","kind":"text"},{"text":"adImpressionInfo","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"GFPAdImpressionInfo","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdImpressionInfo"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"c:objc(cs)GFPImpressionTrackThreshold","kind":"typeIdentifier","text":"GFPImpressionTrackThreshold"}],"navigatorTitle":[{"kind":"identifier","text":"makeImpressionTrackThresholdWith:adImpressionInfo:"}],"symbolKind":"method","externalID":"c:objc(cs)GFPImpressionTrackThreshold(cm)makeImpressionTrackThresholdWith:adImpressionInfo:","role":"symbol","roleHeading":"Type Method","modules":[{"name":"GFPSDK"}]},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdImpressionInfo":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"GFPAdImpressionInfo","kind":"identifier"}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"GFPAdImpressionInfo","kind":"identifier"}],"abstract":[{"type":"text","text":"GFPAdImpressionInfo"}],"role":"symbol","title":"GFPAdImpressionInfo","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdImpressionInfo","url":"\/documentation\/gfpsdk\/gfpadimpressioninfo"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPImpressionTrackThreshold":{"title":"GFPImpressionTrackThreshold","url":"\/documentation\/gfpsdk\/gfpimpressiontrackthreshold","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPImpressionTrackThreshold"}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"GFPImpressionTrackThreshold","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionTrackThreshold","abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPImpressionTrackThreshold/make(with:adImpressionInfo:)":{"kind":"symbol","url":"\/documentation\/gfpsdk\/gfpimpressiontrackthreshold\/make(with:adimpressioninfo:)","role":"symbol","navigatorTitle":[{"text":"makeImpressionTrackThresholdWith:adImpressionInfo:","kind":"identifier"}],"abstract":[],"title":"make(with:adImpressionInfo:)","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionTrackThreshold\/make(with:adImpressionInfo:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"make","kind":"identifier"},{"kind":"text","text":"("},{"text":"with","kind":"externalParam"},{"kind":"text","text":": "},{"text":"GFPImpressionType","kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPImpressionType"},{"text":", ","kind":"text"},{"text":"adImpressionInfo","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPAdImpressionInfo","text":"GFPAdImpressionInfo","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"text":"GFPImpressionTrackThreshold","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPImpressionTrackThreshold"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPImpressionType":{"url":"\/documentation\/gfpsdk\/gfpimpressiontype","navigatorTitle":[{"text":"GFPImpressionType","kind":"identifier"}],"type":"topic","title":"GFPImpressionType","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionType","role":"symbol","abstract":[],"kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPImpressionType"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"value":"makeImpressionTrackThresholdWith:adImpressionInfo:","path":"\/metadata\/title","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"+ "},{"text":"makeImpressionTrackThresholdWith:adImpressionInfo:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPImpressionTrackThreshold","kind":"typeIdentifier","text":"GFPImpressionTrackThreshold","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionTrackThreshold"},{"text":" *) ","kind":"text"},{"text":"makeImpressionTrackThresholdWith:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionType","text":"GFPImpressionType","preciseIdentifier":"c:@E@GFPImpressionType"},{"kind":"text","text":") "},{"kind":"internalParam","text":"impType"},{"kind":"text","text":" "},{"kind":"identifier","text":"adImpressionInfo:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdImpressionInfo","text":"GFPAdImpressionInfo","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdImpressionInfo"},{"kind":"text","text":" *) "},{"text":"adImpressionInfo","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdImpressionInfo\/title","value":"GFPAdImpressionInfo","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdImpressionInfo\/fragments","value":[{"text":"GFPAdImpressionInfo","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdImpressionInfo\/navigatorTitle","value":[{"kind":"identifier","text":"GFPAdImpressionInfo"}]},{"op":"replace","value":"GFPImpressionTrackThreshold","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTrackThreshold\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTrackThreshold\/fragments","op":"replace","value":[{"text":"GFPImpressionTrackThreshold","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTrackThreshold\/navigatorTitle","value":[{"text":"GFPImpressionTrackThreshold","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTrackThreshold~1make(with:adImpressionInfo:)\/title","op":"replace","value":"makeImpressionTrackThresholdWith:adImpressionInfo:"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"makeImpressionTrackThresholdWith:adImpressionInfo:"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTrackThreshold~1make(with:adImpressionInfo:)\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionType\/title","op":"replace","value":"GFPImpressionType"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionType\/fragments","value":[{"text":"GFPImpressionType","kind":"identifier"}]},{"value":[{"text":"GFPImpressionType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionType\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}