{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerContext"]]},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerContext\/init(rootViewController:hostMeta:layoutType:webViewOptions:clickDelegate:)","interfaceLanguage":"swift"},"metadata":{"title":"init(rootViewController:hostMeta:layoutType:webViewOptions:clickDelegate:)","role":"symbol","modules":[{"name":"GFPSDK"}],"symbolKind":"init","roleHeading":"Initializer","navigatorTitle":[{"text":"initWithRootViewController:hostMeta:layoutType:webViewOptions:clickDelegate:","kind":"identifier"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rootViewController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"},{"kind":"text","text":"?, "},{"text":"hostMeta","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"layoutType"},{"kind":"text","text":": "},{"text":"GFPBannerViewLayoutType","preciseIdentifier":"c:@E@GFPBannerViewLayoutType","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"webViewOptions","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdBannerWebViewOptions","text":"GFPAdBannerWebViewOptions"},{"text":"?, ","kind":"text"},{"text":"clickDelegate","kind":"externalParam"},{"text":": (any ","kind":"text"},{"preciseIdentifier":"c:@M@GFPSDK@objc(pl)GFPS2SAdClickDelegate","kind":"typeIdentifier","text":"GFPS2SAdClickDelegate"},{"kind":"text","text":")?)"}],"externalID":"c:objc(cs)GFPBannerContext(im)initWithRootViewController:hostMeta:layoutType:webViewOptions:clickDelegate:"},"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/gfpsdk\/gfpbannercontext\/init(rootviewcontroller:hostmeta:layouttype:webviewoptions:clickdelegate:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gfpsdk\/gfpbannercontext\/init(rootviewcontroller:hostmeta:layouttype:webviewoptions:clickdelegate:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"rootViewController"},{"text":": ","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":"?, ","kind":"text"},{"text":"hostMeta","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"layoutType"},{"text":": ","kind":"text"},{"text":"GFPBannerViewLayoutType","kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPBannerViewLayoutType","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerViewLayoutType"},{"kind":"text","text":", "},{"text":"webViewOptions","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPAdBannerWebViewOptions","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdBannerWebViewOptions","kind":"typeIdentifier","text":"GFPAdBannerWebViewOptions"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"clickDelegate"},{"text":": (any ","kind":"text"},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPS2SAdClickDelegate","preciseIdentifier":"c:@M@GFPSDK@objc(pl)GFPS2SAdClickDelegate","kind":"typeIdentifier","text":"GFPS2SAdClickDelegate"},{"kind":"text","text":")?)"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerContext/init(rootViewController:hostMeta:layoutType:webViewOptions:clickDelegate:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"rootViewController","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":"?, "},{"text":"hostMeta","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"], ","kind":"text"},{"text":"layoutType","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPBannerViewLayoutType","text":"GFPBannerViewLayoutType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"webViewOptions"},{"kind":"text","text":": "},{"text":"GFPAdBannerWebViewOptions","preciseIdentifier":"c:objc(cs)GFPAdBannerWebViewOptions","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"clickDelegate","kind":"externalParam"},{"kind":"text","text":": (any "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@GFPSDK@objc(pl)GFPS2SAdClickDelegate","text":"GFPS2SAdClickDelegate"},{"text":")?)","kind":"text"}],"kind":"symbol","navigatorTitle":[{"text":"initWithRootViewController:hostMeta:layoutType:webViewOptions:clickDelegate:","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerContext\/init(rootViewController:hostMeta:layoutType:webViewOptions:clickDelegate:)","abstract":[],"role":"symbol","url":"\/documentation\/gfpsdk\/gfpbannercontext\/init(rootviewcontroller:hostmeta:layouttype:webviewoptions:clickdelegate:)","title":"init(rootViewController:hostMeta:layoutType:webViewOptions:clickDelegate:)","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdBannerWebViewOptions":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdBannerWebViewOptions","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPAdBannerWebViewOptions"}],"navigatorTitle":[{"text":"GFPAdBannerWebViewOptions","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/gfpsdk\/gfpadbannerwebviewoptions","title":"GFPAdBannerWebViewOptions","kind":"symbol","abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerViewLayoutType":{"kind":"symbol","title":"GFPBannerViewLayoutType","url":"\/documentation\/gfpsdk\/gfpbannerviewlayouttype","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPBannerViewLayoutType"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerViewLayoutType","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GFPBannerViewLayoutType"}],"abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerContext":{"kind":"symbol","title":"GFPBannerContext","url":"\/documentation\/gfpsdk\/gfpbannercontext","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPBannerContext"}],"type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerContext","navigatorTitle":[{"kind":"identifier","text":"GFPBannerContext"}],"abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPS2SAdClickDelegate":{"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPS2SAdClickDelegate"}],"kind":"symbol","navigatorTitle":[{"text":"GFPS2SAdClickDelegate","kind":"identifier"}],"abstract":[],"title":"GFPS2SAdClickDelegate","role":"symbol","url":"\/documentation\/gfpsdk\/gfps2sadclickdelegate","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPS2SAdClickDelegate","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithRootViewController:hostMeta:layoutType:webViewOptions:clickDelegate:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithRootViewController:hostMeta:layoutType:webViewOptions:clickDelegate:","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"text":"initWithRootViewController:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":" *) "},{"text":"rootViewController","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"hostMeta:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSDictionary<NSString *,NSString *>","preciseIdentifier":"c:Q$objc(cs)NSDictionary"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"hostMeta"},{"kind":"text","text":" "},{"text":"layoutType:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerViewLayoutType","preciseIdentifier":"c:@E@GFPBannerViewLayoutType","text":"GFPBannerViewLayoutType","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"layoutType"},{"text":" ","kind":"text"},{"text":"webViewOptions:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GFPAdBannerWebViewOptions","preciseIdentifier":"c:objc(cs)GFPAdBannerWebViewOptions","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdBannerWebViewOptions"},{"kind":"text","text":" *) "},{"text":"webViewOptions","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"clickDelegate:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Qo@M@GFPSDK@objc(pl)GFPS2SAdClickDelegate","text":"id<GFPS2SAdClickDelegate>","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"clickDelegate","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"initWithRootViewController:hostMeta:layoutType:webViewOptions:clickDelegate:","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerContext~1init(rootViewController:hostMeta:layoutType:webViewOptions:clickDelegate:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerContext~1init(rootViewController:hostMeta:layoutType:webViewOptions:clickDelegate:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithRootViewController:hostMeta:layoutType:webViewOptions:clickDelegate:"}]},{"value":"GFPAdBannerWebViewOptions","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdBannerWebViewOptions\/title"},{"value":[{"text":"GFPAdBannerWebViewOptions","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdBannerWebViewOptions\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"GFPAdBannerWebViewOptions"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdBannerWebViewOptions\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerViewLayoutType\/title","value":"GFPBannerViewLayoutType","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerViewLayoutType\/fragments","value":[{"text":"GFPBannerViewLayoutType","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"text":"GFPBannerViewLayoutType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerViewLayoutType\/navigatorTitle"},{"value":"GFPBannerContext","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerContext\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerContext\/fragments","value":[{"text":"GFPBannerContext","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerContext\/navigatorTitle","value":[{"kind":"identifier","text":"GFPBannerContext"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPS2SAdClickDelegate\/title","value":"GFPS2SAdClickDelegate"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPS2SAdClickDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"GFPS2SAdClickDelegate"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPS2SAdClickDelegate\/navigatorTitle","value":[{"text":"GFPS2SAdClickDelegate","kind":"identifier"}],"op":"replace"}]}]}