{"metadata":{"symbolKind":"property","title":"layoutType","modules":[{"name":"GFPSDK"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"layoutType","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@GFPBannerViewLayoutType","text":"GFPBannerViewLayoutType","kind":"typeIdentifier"}],"roleHeading":"Instance Property","navigatorTitle":[{"text":"layoutType","kind":"identifier"}],"externalID":"c:objc(cs)GFPBannerContext(py)layoutType"},"sections":[],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerContext\/layoutType","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"layoutType","kind":"identifier"},{"kind":"text","text":": "},{"text":"GFPBannerViewLayoutType","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerViewLayoutType","kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPBannerViewLayoutType"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpbannercontext\/layouttype"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpbannercontext\/layouttype"]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerContext"]]},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerContext":{"kind":"symbol","title":"GFPBannerContext","url":"\/documentation\/gfpsdk\/gfpbannercontext","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPBannerContext"}],"type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerContext","navigatorTitle":[{"kind":"identifier","text":"GFPBannerContext"}],"abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerContext/layoutType":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"layoutType"},{"kind":"text","text":": "},{"text":"GFPBannerViewLayoutType","preciseIdentifier":"c:@E@GFPBannerViewLayoutType","kind":"typeIdentifier"}],"kind":"symbol","navigatorTitle":[{"text":"layoutType","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerContext\/layoutType","abstract":[],"role":"symbol","url":"\/documentation\/gfpsdk\/gfpbannercontext\/layouttype","title":"layoutType","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerViewLayoutType":{"kind":"symbol","title":"GFPBannerViewLayoutType","url":"\/documentation\/gfpsdk\/gfpbannerviewlayouttype","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPBannerViewLayoutType"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerViewLayoutType","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GFPBannerViewLayoutType"}],"abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"layoutType","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"layoutType","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"assign","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@E@GFPBannerViewLayoutType","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerViewLayoutType","kind":"typeIdentifier","text":"GFPBannerViewLayoutType"},{"kind":"text","text":" "},{"kind":"identifier","text":"layoutType"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerContext\/title","op":"replace","value":"GFPBannerContext"},{"value":[{"kind":"identifier","text":"GFPBannerContext"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerContext\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"GFPBannerContext"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerContext\/navigatorTitle","op":"replace"},{"op":"replace","value":"layoutType","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerContext~1layoutType\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerContext~1layoutType\/fragments","value":[{"text":"layoutType","kind":"identifier"}]},{"value":"GFPBannerViewLayoutType","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerViewLayoutType\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerViewLayoutType\/fragments","value":[{"kind":"identifier","text":"GFPBannerViewLayoutType"}]},{"value":[{"text":"GFPBannerViewLayoutType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerViewLayoutType\/navigatorTitle","op":"replace"}]}]}