{"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerContext\/webViewOptions","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerContext"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"webViewOptions","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPAdBannerWebViewOptions","kind":"typeIdentifier","text":"GFPAdBannerWebViewOptions","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdBannerWebViewOptions"},{"kind":"text","text":"? { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]}],"metadata":{"externalID":"c:objc(cs)GFPBannerContext(py)webViewOptions","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"webViewOptions","kind":"identifier"},{"kind":"text","text":": "},{"text":"GFPAdBannerWebViewOptions","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdBannerWebViewOptions"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"webViewOptions"}],"role":"symbol","title":"webViewOptions","symbolKind":"property","modules":[{"name":"GFPSDK"}]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpbannercontext\/webviewoptions"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpbannercontext\/webviewoptions"]}],"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerContext":{"kind":"symbol","title":"GFPBannerContext","url":"\/documentation\/gfpsdk\/gfpbannercontext","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPBannerContext"}],"type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerContext","navigatorTitle":[{"kind":"identifier","text":"GFPBannerContext"}],"abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdBannerWebViewOptions":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdBannerWebViewOptions","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPAdBannerWebViewOptions"}],"navigatorTitle":[{"text":"GFPAdBannerWebViewOptions","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/gfpsdk\/gfpadbannerwebviewoptions","title":"GFPAdBannerWebViewOptions","kind":"symbol","abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerContext/webViewOptions":{"kind":"symbol","type":"topic","abstract":[],"url":"\/documentation\/gfpsdk\/gfpbannercontext\/webviewoptions","navigatorTitle":[{"kind":"identifier","text":"webViewOptions"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"webViewOptions","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPAdBannerWebViewOptions","text":"GFPAdBannerWebViewOptions","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"webViewOptions","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerContext\/webViewOptions"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"value":"webViewOptions","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"webViewOptions","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)GFPAdBannerWebViewOptions","text":"GFPAdBannerWebViewOptions","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdBannerWebViewOptions"},{"text":" * ","kind":"text"},{"text":"webViewOptions","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerContext\/title","op":"replace","value":"GFPBannerContext"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerContext\/fragments","value":[{"kind":"identifier","text":"GFPBannerContext"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerContext\/navigatorTitle","value":[{"text":"GFPBannerContext","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdBannerWebViewOptions\/title","value":"GFPAdBannerWebViewOptions","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdBannerWebViewOptions\/fragments","value":[{"kind":"identifier","text":"GFPAdBannerWebViewOptions"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdBannerWebViewOptions\/navigatorTitle","op":"replace","value":[{"text":"GFPAdBannerWebViewOptions","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerContext~1webViewOptions\/title","value":"webViewOptions","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerContext~1webViewOptions\/fragments","value":[{"kind":"identifier","text":"webViewOptions"}]}]}]}