{"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRenderDisplayAgentType"]]},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"displayAgentTypeInApp","kind":"identifier"},{"kind":"text","text":": "},{"text":"GFPRenderDisplayAgentType","kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPRenderDisplayAgentType","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRenderDisplayAgentType"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfprenderdisplayagenttype\/displayagenttypeinapp"]},{"paths":["\/documentation\/gfpsdk\/gfprenderdisplayagenttype\/displayagenttypeinapp"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRenderDisplayAgentType\/displayAgentTypeInApp","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"GFPSDK"}],"title":"displayAgentTypeInApp","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"GFPDisplayAgentTypeInApp"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"displayAgentTypeInApp","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPRenderDisplayAgentType","text":"GFPRenderDisplayAgentType"}],"role":"symbol","externalID":"c:@E@GFPRenderDisplayAgentType@GFPDisplayAgentTypeInApp","roleHeading":"Type Property"},"sections":[],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRenderDisplayAgentType/displayAgentTypeInApp":{"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"displayAgentTypeInApp","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"GFPRenderDisplayAgentType","preciseIdentifier":"c:@E@GFPRenderDisplayAgentType"}],"navigatorTitle":[{"text":"GFPDisplayAgentTypeInApp","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfprenderdisplayagenttype\/displayagenttypeinapp","abstract":[],"kind":"symbol","role":"symbol","title":"displayAgentTypeInApp","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRenderDisplayAgentType\/displayAgentTypeInApp","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRenderDisplayAgentType":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPRenderDisplayAgentType","kind":"identifier"}],"kind":"symbol","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRenderDisplayAgentType","type":"topic","title":"GFPRenderDisplayAgentType","role":"symbol","url":"\/documentation\/gfpsdk\/gfprenderdisplayagenttype","navigatorTitle":[{"kind":"identifier","text":"GFPRenderDisplayAgentType"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"GFPDisplayAgentTypeInApp"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"GFPDisplayAgentTypeInApp","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"GFPDisplayAgentTypeInApp"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"GFPDisplayAgentTypeInApp","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRenderDisplayAgentType~1displayAgentTypeInApp\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRenderDisplayAgentType~1displayAgentTypeInApp\/fragments","value":[{"text":"GFPDisplayAgentTypeInApp","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRenderDisplayAgentType\/title","value":"GFPRenderDisplayAgentType"},{"value":[{"text":"GFPRenderDisplayAgentType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRenderDisplayAgentType\/fragments"},{"value":[{"kind":"identifier","text":"GFPRenderDisplayAgentType"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRenderDisplayAgentType\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}