{"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"OptionSet.formIntersection(_:)"},{"text":".","type":"text"}],"sections":[],"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRenderDisplayAgentType\/formIntersection(_:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"mutating","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"formIntersection","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"other"},{"text":": ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":")","kind":"text"}]}],"kind":"declarations"}],"metadata":{"modules":[{"relatedModules":["Swift"],"name":"GFPSDK"}],"symbolKind":"method","role":"symbol","title":"formIntersection(_:)","externalID":"s:s9OptionSetPss17FixedWidthInteger8RawValueRpzrlE16formIntersectionyyxF::SYNTHESIZED::c:@E@GFPRenderDisplayAgentType","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"formIntersection"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":")"}],"roleHeading":"Instance Method","conformance":{"availabilityPrefix":[{"text":"Available when","type":"text"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}],"constraints":[{"type":"codeVoice","code":"RawValue"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"FixedWidthInteger"},{"type":"text","text":"."}]},"extendedModule":"Swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRenderDisplayAgentType","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRenderDisplayAgentType\/OptionSet-Implementations"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/gfpsdk\/gfprenderdisplayagenttype\/formintersection(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRenderDisplayAgentType/formIntersection(_:)":{"conformance":{"constraints":[{"type":"codeVoice","code":"RawValue"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"FixedWidthInteger"},{"text":".","type":"text"}],"conformancePrefix":[{"text":"Conforms when","type":"text"}],"availabilityPrefix":[{"type":"text","text":"Available when"}]},"type":"topic","abstract":[],"title":"formIntersection(_:)","role":"symbol","url":"\/documentation\/gfpsdk\/gfprenderdisplayagenttype\/formintersection(_:)","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRenderDisplayAgentType\/formIntersection(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"formIntersection","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":")"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRenderDisplayAgentType":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPRenderDisplayAgentType","kind":"identifier"}],"kind":"symbol","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRenderDisplayAgentType","type":"topic","title":"GFPRenderDisplayAgentType","role":"symbol","url":"\/documentation\/gfpsdk\/gfprenderdisplayagenttype","navigatorTitle":[{"kind":"identifier","text":"GFPRenderDisplayAgentType"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRenderDisplayAgentType/OptionSet-Implementations":{"kind":"article","abstract":[],"title":"OptionSet Implementations","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRenderDisplayAgentType\/OptionSet-Implementations","role":"collectionGroup","url":"\/documentation\/gfpsdk\/gfprenderdisplayagenttype\/optionset-implementations","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"GFPRenderDisplayAgentType","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRenderDisplayAgentType\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRenderDisplayAgentType\/fragments","op":"replace","value":[{"kind":"identifier","text":"GFPRenderDisplayAgentType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRenderDisplayAgentType\/navigatorTitle","value":[{"text":"GFPRenderDisplayAgentType","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}