{"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdBreakResult\/adProviderName()","interfaceLanguage":"swift"},"metadata":{"title":"adProviderName()","role":"symbol","modules":[{"name":"GFPSDK"}],"roleHeading":"Instance Method","symbolKind":"method","navigatorTitle":[{"text":"adProviderName","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"adProviderName","kind":"identifier"},{"kind":"text","text":"() -> "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"externalID":"c:objc(cs)GFPVideoAdBreakResult(im)adProviderName"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"adProviderName","kind":"identifier"},{"kind":"text","text":"() -> "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpvideoadbreakresult\/adprovidername()"]},{"paths":["\/documentation\/gfpsdk\/gfpvideoadbreakresult\/adprovidername()"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdBreakResult"]]},"sections":[],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdBreakResult":{"abstract":[],"kind":"symbol","title":"GFPVideoAdBreakResult","navigatorTitle":[{"text":"GFPVideoAdBreakResult","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdBreakResult","url":"\/documentation\/gfpsdk\/gfpvideoadbreakresult","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"GFPVideoAdBreakResult","kind":"identifier"}],"role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdBreakResult/adProviderName()":{"type":"topic","abstract":[],"title":"adProviderName()","role":"symbol","url":"\/documentation\/gfpsdk\/gfpvideoadbreakresult\/adprovidername()","navigatorTitle":[{"kind":"identifier","text":"adProviderName"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdBreakResult\/adProviderName()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"adProviderName","kind":"identifier"},{"kind":"text","text":"() -> "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"adProviderName"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"adProviderName","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"adProviderName"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"GFPVideoAdBreakResult","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdBreakResult\/title"},{"value":[{"kind":"identifier","text":"GFPVideoAdBreakResult"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdBreakResult\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdBreakResult\/navigatorTitle","value":[{"text":"GFPVideoAdBreakResult","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdBreakResult~1adProviderName()\/title","value":"adProviderName","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"adProviderName","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdBreakResult~1adProviderName()\/fragments","op":"replace"}]}]}