{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpvideoadbreakresult\/init(adsource:videomanager:)"]},{"paths":["\/documentation\/gfpsdk\/gfpvideoadbreakresult\/init(adsource:videomanager:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdBreakResult\/init(adSource:videoManager:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"adSource"},{"text":" ","kind":"text"},{"text":"aAdSource","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdSource","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoAdSource","text":"GFPVideoAdSource"},{"text":"?, ","kind":"text"},{"text":"videoManager","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"aVideoManager"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager","kind":"typeIdentifier","text":"GFPVideoAdManager","preciseIdentifier":"c:objc(cs)GFPVideoAdManager"},{"text":")","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdBreakResult"]]},"sections":[],"kind":"symbol","metadata":{"modules":[{"name":"GFPSDK"}],"externalID":"c:objc(cs)GFPVideoAdBreakResult(im)initWithAdSource:videoManager:","roleHeading":"Initializer","title":"init(adSource:videoManager:)","role":"symbol","symbolKind":"init","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"adSource","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoAdSource","text":"GFPVideoAdSource"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"videoManager"},{"kind":"text","text":": "},{"text":"GFPVideoAdManager","preciseIdentifier":"c:objc(cs)GFPVideoAdManager","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"initWithAdSource:videoManager:"}]},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdBreakResult/init(adSource:videoManager:)":{"kind":"symbol","title":"init(adSource:videoManager:)","url":"\/documentation\/gfpsdk\/gfpvideoadbreakresult\/init(adsource:videomanager:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"adSource"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"GFPVideoAdSource","preciseIdentifier":"c:objc(cs)GFPVideoAdSource"},{"kind":"text","text":"?, "},{"text":"videoManager","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"GFPVideoAdManager","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoAdManager"},{"text":")","kind":"text"}],"type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdBreakResult\/init(adSource:videoManager:)","navigatorTitle":[{"text":"initWithAdSource:videoManager:","kind":"identifier"}],"abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdSource":{"kind":"symbol","title":"GFPVideoAdSource","url":"\/documentation\/gfpsdk\/gfpvideoadsource","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPVideoAdSource","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdSource","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GFPVideoAdSource"}],"abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdManager":{"type":"topic","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager","role":"symbol","url":"\/documentation\/gfpsdk\/gfpvideoadmanager","title":"GFPVideoAdManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPVideoAdManager"}],"kind":"symbol","navigatorTitle":[{"text":"GFPVideoAdManager","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdBreakResult":{"abstract":[],"kind":"symbol","title":"GFPVideoAdBreakResult","navigatorTitle":[{"text":"GFPVideoAdBreakResult","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdBreakResult","url":"\/documentation\/gfpsdk\/gfpvideoadbreakresult","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"GFPVideoAdBreakResult","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","value":"initWithAdSource:videoManager:","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithAdSource:videoManager:"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithAdSource:"},{"text":"(","kind":"text"},{"text":"GFPVideoAdSource","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdSource","preciseIdentifier":"c:objc(cs)GFPVideoAdSource"},{"kind":"text","text":" *) "},{"text":"aAdSource","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"videoManager:"},{"kind":"text","text":"("},{"text":"GFPVideoAdManager","preciseIdentifier":"c:objc(cs)GFPVideoAdManager","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"aVideoManager"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdBreakResult~1init(adSource:videoManager:)\/title","value":"initWithAdSource:videoManager:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdBreakResult~1init(adSource:videoManager:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithAdSource:videoManager:"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdSource\/title","op":"replace","value":"GFPVideoAdSource"},{"value":[{"text":"GFPVideoAdSource","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdSource\/fragments"},{"value":[{"text":"GFPVideoAdSource","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdSource\/navigatorTitle"},{"value":"GFPVideoAdManager","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManager\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManager\/fragments","value":[{"text":"GFPVideoAdManager","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"GFPVideoAdManager"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManager\/navigatorTitle"},{"op":"replace","value":"GFPVideoAdBreakResult","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdBreakResult\/title"},{"op":"replace","value":[{"text":"GFPVideoAdBreakResult","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdBreakResult\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdBreakResult\/navigatorTitle","value":[{"text":"GFPVideoAdBreakResult","kind":"identifier"}]}]}]}