{"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"closeIcon"}],"title":"closeIcon","modules":[{"name":"GFPSDK"}],"roleHeading":"Instance Property","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"closeIcon"},{"kind":"text","text":": "},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?"}],"externalID":"c:@M@GFPSDK@objc(cs)GFPTextAdViewAttribute(py)closeIcon","symbolKind":"property"},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPTextAdViewAttribute\/closeIcon","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPTextAdViewAttribute"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"closeIcon","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier","text":"UIImage"},{"text":"?","kind":"text"}]}]}],"variants":[{"paths":["\/documentation\/gfpsdk\/gfptextadviewattribute\/closeicon"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfptextadviewattribute\/closeicon"]}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPTextAdViewAttribute":{"navigatorTitle":[{"text":"GFPTextAdViewAttribute","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfptextadviewattribute","type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPTextAdViewAttribute","title":"GFPTextAdViewAttribute","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPTextAdViewAttribute"}],"abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPTextAdViewAttribute/closeIcon":{"abstract":[],"kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPTextAdViewAttribute\/closeIcon","url":"\/documentation\/gfpsdk\/gfptextadviewattribute\/closeicon","title":"closeIcon","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"closeIcon"},{"kind":"text","text":": "},{"text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"closeIcon","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"closeIcon","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"closeIcon"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"closeIcon"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPTextAdViewAttribute\/title","op":"replace","value":"GFPTextAdViewAttribute"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPTextAdViewAttribute\/fragments","value":[{"kind":"identifier","text":"GFPTextAdViewAttribute"}]},{"value":[{"text":"GFPTextAdViewAttribute","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPTextAdViewAttribute\/navigatorTitle"},{"op":"replace","value":"closeIcon","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPTextAdViewAttribute~1closeIcon\/title"},{"value":[{"text":"closeIcon","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPTextAdViewAttribute~1closeIcon\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}