{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfptextadviewattribute\/init()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfptextadviewattribute\/init()"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPTextAdViewAttribute"]]},"metadata":{"title":"init()","role":"symbol","externalID":"c:@M@GFPSDK@objc(cs)GFPTextAdViewAttribute(im)init","modules":[{"name":"GFPSDK"}],"navigatorTitle":[{"text":"init","kind":"identifier"}],"fragments":[{"kind":"identifier","text":"init"},{"text":"()","kind":"text"}],"roleHeading":"Initializer","symbolKind":"init"},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPTextAdViewAttribute\/init()","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"override","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"text":"()","kind":"text"}],"languages":["swift"]}]}],"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPTextAdViewAttribute/init()":{"title":"init()","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPTextAdViewAttribute\/init()","role":"symbol","url":"\/documentation\/gfpsdk\/gfptextadviewattribute\/init()","kind":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}],"type":"topic","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPTextAdViewAttribute":{"navigatorTitle":[{"text":"GFPTextAdViewAttribute","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfptextadviewattribute","type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPTextAdViewAttribute","title":"GFPTextAdViewAttribute","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPTextAdViewAttribute"}],"abstract":[]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"value":"init","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"text":"init","kind":"identifier"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"value":"init","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPTextAdViewAttribute~1init()\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPTextAdViewAttribute~1init()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPTextAdViewAttribute\/title","value":"GFPTextAdViewAttribute","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPTextAdViewAttribute\/fragments","op":"replace","value":[{"text":"GFPTextAdViewAttribute","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"GFPTextAdViewAttribute"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPTextAdViewAttribute\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}