{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerProviderOption\/APS"},"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerProviderOption"]]},"sections":[],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpbannerprovideroption\/aps"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpbannerprovideroption\/aps"]}],"metadata":{"title":"GFPBannerProviderOption.APS","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"APS"}],"roleHeading":"Case","role":"symbol","externalID":"c:@M@GFPSDK@E@GFPBannerProviderOption@GFPBannerProviderOptionAPS","symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"GFPBannerProviderOptionAPS"}],"modules":[{"name":"GFPSDK"}]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"APS","kind":"identifier"}],"platforms":["iOS"]}]}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerProviderOption/APS":{"abstract":[],"type":"topic","title":"GFPBannerProviderOption.APS","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"APS","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpbannerprovideroption\/aps","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerProviderOption\/APS","navigatorTitle":[{"text":"GFPBannerProviderOptionAPS","kind":"identifier"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerProviderOption":{"navigatorTitle":[{"text":"GFPBannerProviderOption","kind":"identifier"}],"role":"symbol","title":"GFPBannerProviderOption","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerProviderOption","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPBannerProviderOption"}],"url":"\/documentation\/gfpsdk\/gfpbannerprovideroption","abstract":[{"text":"GFP에서 지원하는 배너광고 제공자 목록","type":"text"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"GFPBannerProviderOptionAPS"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"op":"replace","value":[{"kind":"identifier","text":"GFPBannerProviderOptionAPS"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"GFPBannerProviderOptionAPS"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":"GFPBannerProviderOptionAPS","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerProviderOption~1APS\/title"},{"op":"replace","value":[{"text":"GFPBannerProviderOptionAPS","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerProviderOption~1APS\/fragments"},{"value":"GFPBannerProviderOption","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerProviderOption\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerProviderOption\/fragments","value":[{"text":"GFPBannerProviderOption","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerProviderOption\/navigatorTitle","value":[{"text":"GFPBannerProviderOption","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}