{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpbannerprovideroption\/chartboost"]},{"paths":["\/documentation\/gfpsdk\/gfpbannerprovideroption\/chartboost"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerProviderOption"]]},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerProviderOption\/chartBoost","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"chartBoost"}],"symbolKind":"case","roleHeading":"Case","navigatorTitle":[{"text":"GFPBannerProviderOptionChartBoost","kind":"identifier"}],"modules":[{"name":"GFPSDK"}],"title":"GFPBannerProviderOption.chartBoost","externalID":"c:@M@GFPSDK@E@GFPBannerProviderOption@GFPBannerProviderOptionChartBoost","role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"chartBoost"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerProviderOption":{"navigatorTitle":[{"text":"GFPBannerProviderOption","kind":"identifier"}],"role":"symbol","title":"GFPBannerProviderOption","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerProviderOption","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPBannerProviderOption"}],"url":"\/documentation\/gfpsdk\/gfpbannerprovideroption","abstract":[{"text":"GFP에서 지원하는 배너광고 제공자 목록","type":"text"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerProviderOption/chartBoost":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerProviderOption\/chartBoost","type":"topic","abstract":[],"url":"\/documentation\/gfpsdk\/gfpbannerprovideroption\/chartboost","navigatorTitle":[{"text":"GFPBannerProviderOptionChartBoost","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"chartBoost"}],"title":"GFPBannerProviderOption.chartBoost","role":"symbol","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"GFPBannerProviderOptionChartBoost","op":"replace"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"GFPBannerProviderOptionChartBoost","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"GFPBannerProviderOptionChartBoost"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerProviderOption\/title","op":"replace","value":"GFPBannerProviderOption"},{"value":[{"text":"GFPBannerProviderOption","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerProviderOption\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerProviderOption\/navigatorTitle","value":[{"kind":"identifier","text":"GFPBannerProviderOption"}]},{"value":"GFPBannerProviderOptionChartBoost","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerProviderOption~1chartBoost\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerProviderOption~1chartBoost\/fragments","value":[{"text":"GFPBannerProviderOptionChartBoost","kind":"identifier"}]}]}]}