{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"inMobi","kind":"identifier"}],"languages":["swift"]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerProviderOption"]]},"metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"inMobi"}],"navigatorTitle":[{"text":"GFPBannerProviderOptionInMobi","kind":"identifier"}],"symbolKind":"case","roleHeading":"Case","externalID":"c:@M@GFPSDK@E@GFPBannerProviderOption@GFPBannerProviderOptionInMobi","title":"GFPBannerProviderOption.inMobi","modules":[{"name":"GFPSDK"}]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpbannerprovideroption\/inmobi"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpbannerprovideroption\/inmobi"]}],"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerProviderOption\/inMobi","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerProviderOption":{"navigatorTitle":[{"text":"GFPBannerProviderOption","kind":"identifier"}],"role":"symbol","title":"GFPBannerProviderOption","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerProviderOption","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPBannerProviderOption"}],"url":"\/documentation\/gfpsdk\/gfpbannerprovideroption","abstract":[{"text":"GFP에서 지원하는 배너광고 제공자 목록","type":"text"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerProviderOption/inMobi":{"abstract":[],"url":"\/documentation\/gfpsdk\/gfpbannerprovideroption\/inmobi","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPBannerProviderOptionInMobi"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"inMobi","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerProviderOption\/inMobi","kind":"symbol","title":"GFPBannerProviderOption.inMobi","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"value":"GFPBannerProviderOptionInMobi","op":"replace","path":"\/metadata\/title"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"GFPBannerProviderOptionInMobi","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"GFPBannerProviderOptionInMobi","kind":"identifier"}],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","value":"GFPBannerProviderOption","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerProviderOption\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerProviderOption\/fragments","value":[{"text":"GFPBannerProviderOption","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerProviderOption\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"GFPBannerProviderOption"}]},{"op":"replace","value":"GFPBannerProviderOptionInMobi","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerProviderOption~1inMobi\/title"},{"op":"replace","value":[{"text":"GFPBannerProviderOptionInMobi","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerProviderOption~1inMobi\/fragments"}]}]}