{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdPlayerSetting"]]},"metadata":{"title":"init(action:audioSetting:disableExternalPlayBack:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"action"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@GFPSDK@E@GFPVideoBackgroundActionType","text":"GFPVideoBackgroundActionType"},{"text":", ","kind":"text"},{"text":"audioSetting","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"GFPVideoAudioSettingType","kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPVideoAudioSettingType"},{"kind":"text","text":", "},{"text":"disableExternalPlayBack","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"roleHeading":"Initializer","role":"symbol","externalID":"c:@M@GFPSDK@objc(cs)GFPVideoAdPlayerSetting(im)initWithAction:audioSetting:disableExternalPlayback:","symbolKind":"init","navigatorTitle":[{"text":"initWithAction:audioSetting:disableExternalPlayback:","kind":"identifier"}],"modules":[{"name":"GFPSDK"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpvideoadplayersetting\/init(action:audiosetting:disableexternalplayback:)"]},{"paths":["\/documentation\/gfpsdk\/gfpvideoadplayersetting\/init(action:audiosetting:disableexternalplayback:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(initWithAction:audioSetting:disableExternalPlayback:) ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"action"},{"text":" ","kind":"text"},{"text":"aAction","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"GFPVideoBackgroundActionType","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoBackgroundActionType","preciseIdentifier":"c:@M@GFPSDK@E@GFPVideoBackgroundActionType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"audioSetting"},{"kind":"text","text":" "},{"text":"aType","kind":"internalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAudioSettingType","kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPVideoAudioSettingType","text":"GFPVideoAudioSettingType"},{"kind":"text","text":", "},{"text":"disableExternalPlayBack","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":")"}],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdPlayerSetting\/init(action:audioSetting:disableExternalPlayBack:)"},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoBackgroundActionType":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPVideoBackgroundActionType"}],"type":"topic","title":"GFPVideoBackgroundActionType","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoBackgroundActionType","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPVideoBackgroundActionType","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpvideobackgroundactiontype"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAudioSettingType":{"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPVideoAudioSettingType","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/gfpsdk\/gfpvideoaudiosettingtype","title":"GFPVideoAudioSettingType","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAudioSettingType","type":"topic","navigatorTitle":[{"text":"GFPVideoAudioSettingType","kind":"identifier"}],"role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdPlayerSetting/init(action:audioSetting:disableExternalPlayBack:)":{"abstract":[],"title":"init(action:audioSetting:disableExternalPlayBack:)","type":"topic","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"action","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@GFPSDK@E@GFPVideoBackgroundActionType","text":"GFPVideoBackgroundActionType"},{"kind":"text","text":", "},{"text":"audioSetting","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"GFPVideoAudioSettingType","kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPVideoAudioSettingType"},{"text":", ","kind":"text"},{"text":"disableExternalPlayBack","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":")","kind":"text"}],"url":"\/documentation\/gfpsdk\/gfpvideoadplayersetting\/init(action:audiosetting:disableexternalplayback:)","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdPlayerSetting\/init(action:audioSetting:disableExternalPlayBack:)","navigatorTitle":[{"text":"initWithAction:audioSetting:disableExternalPlayback:","kind":"identifier"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdPlayerSetting":{"navigatorTitle":[{"text":"GFPVideoAdPlayerSetting","kind":"identifier"}],"title":"GFPVideoAdPlayerSetting","url":"\/documentation\/gfpsdk\/gfpvideoadplayersetting","kind":"symbol","abstract":[],"role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdPlayerSetting","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPVideoAdPlayerSetting"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"initWithAction:audioSetting:disableExternalPlayback:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithAction:audioSetting:disableExternalPlayback:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"text":"initWithAction:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoBackgroundActionType","kind":"typeIdentifier","preciseIdentifier":"c:@M@GFPSDK@E@GFPVideoBackgroundActionType","text":"GFPVideoBackgroundActionType"},{"text":") ","kind":"text"},{"text":"aAction","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"audioSetting:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAudioSettingType","text":"GFPVideoAudioSettingType","kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPVideoAudioSettingType"},{"text":") ","kind":"text"},{"text":"aType","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"disableExternalPlayback:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"disableExternalPlayBack"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"value":"GFPVideoBackgroundActionType","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoBackgroundActionType\/title"},{"value":[{"kind":"identifier","text":"GFPVideoBackgroundActionType"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoBackgroundActionType\/fragments","op":"replace"},{"value":[{"text":"GFPVideoBackgroundActionType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoBackgroundActionType\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAudioSettingType\/title","value":"GFPVideoAudioSettingType"},{"value":[{"kind":"identifier","text":"GFPVideoAudioSettingType"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAudioSettingType\/fragments"},{"value":[{"text":"GFPVideoAudioSettingType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAudioSettingType\/navigatorTitle"},{"op":"replace","value":"initWithAction:audioSetting:disableExternalPlayback:","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdPlayerSetting~1init(action:audioSetting:disableExternalPlayBack:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithAction:audioSetting:disableExternalPlayback:"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdPlayerSetting~1init(action:audioSetting:disableExternalPlayBack:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdPlayerSetting\/title","value":"GFPVideoAdPlayerSetting","op":"replace"},{"op":"replace","value":[{"text":"GFPVideoAdPlayerSetting","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdPlayerSetting\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdPlayerSetting\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"GFPVideoAdPlayerSetting"}]}]}]}