{"metadata":{"title":"init(action:)","role":"symbol","externalID":"c:@M@GFPSDK@objc(cs)GFPVideoAdPlayerSetting(im)initWithAction:","modules":[{"name":"GFPSDK"}],"navigatorTitle":[{"kind":"identifier","text":"initWithAction:"}],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"action","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@GFPSDK@E@GFPVideoBackgroundActionType","kind":"typeIdentifier","text":"GFPVideoBackgroundActionType"},{"kind":"text","text":")"}],"roleHeading":"Initializer","symbolKind":"init"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdPlayerSetting"]]},"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"convenience","kind":"keyword"},{"kind":"text","text":" "},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"action","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"aAction"},{"text":": ","kind":"text"},{"text":"GFPVideoBackgroundActionType","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoBackgroundActionType","preciseIdentifier":"c:@M@GFPSDK@E@GFPVideoBackgroundActionType","kind":"typeIdentifier"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpvideoadplayersetting\/init(action:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpvideoadplayersetting\/init(action:)"]}],"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdPlayerSetting\/init(action:)","interfaceLanguage":"swift"},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdPlayerSetting/init(action:)":{"title":"init(action:)","url":"\/documentation\/gfpsdk\/gfpvideoadplayersetting\/init(action:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithAction:"}],"kind":"symbol","type":"topic","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"action"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@GFPSDK@E@GFPVideoBackgroundActionType","kind":"typeIdentifier","text":"GFPVideoBackgroundActionType"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdPlayerSetting\/init(action:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdPlayerSetting":{"navigatorTitle":[{"text":"GFPVideoAdPlayerSetting","kind":"identifier"}],"title":"GFPVideoAdPlayerSetting","url":"\/documentation\/gfpsdk\/gfpvideoadplayersetting","kind":"symbol","abstract":[],"role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdPlayerSetting","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPVideoAdPlayerSetting"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoBackgroundActionType":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPVideoBackgroundActionType"}],"type":"topic","title":"GFPVideoBackgroundActionType","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoBackgroundActionType","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPVideoBackgroundActionType","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpvideobackgroundactiontype"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"initWithAction:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithAction:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"initWithAction:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoBackgroundActionType","preciseIdentifier":"c:@M@GFPSDK@E@GFPVideoBackgroundActionType","text":"GFPVideoBackgroundActionType"},{"text":") ","kind":"text"},{"text":"aAction","kind":"internalParam"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdPlayerSetting~1init(action:)\/title","op":"replace","value":"initWithAction:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithAction:"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdPlayerSetting~1init(action:)\/fragments"},{"op":"replace","value":"GFPVideoAdPlayerSetting","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdPlayerSetting\/title"},{"value":[{"kind":"identifier","text":"GFPVideoAdPlayerSetting"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdPlayerSetting\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdPlayerSetting\/navigatorTitle","value":[{"kind":"identifier","text":"GFPVideoAdPlayerSetting"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoBackgroundActionType\/title","value":"GFPVideoBackgroundActionType","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoBackgroundActionType\/fragments","value":[{"kind":"identifier","text":"GFPVideoBackgroundActionType"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoBackgroundActionType\/navigatorTitle","value":[{"text":"GFPVideoBackgroundActionType","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}