{"metadata":{"role":"symbol","modules":[{"name":"GFPSDK"}],"externalID":"c:objc(pl)GFPBannerAdapting(py)bannerAdSize","symbolKind":"property","title":"bannerAdSize","navigatorTitle":[{"kind":"identifier","text":"bannerAdSize"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"bannerAdSize","kind":"identifier"},{"text":": ","kind":"text"},{"text":"GFPBannerAdSize","preciseIdentifier":"c:objc(cs)GFPBannerAdSize","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"roleHeading":"Instance Property","required":true},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"bannerAdSize","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)GFPBannerAdSize","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerAdSize","text":"GFPBannerAdSize","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpbanneradapting\/banneradsize"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpbanneradapting\/banneradsize"]}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerAdapting"]]},"kind":"symbol","identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerAdapting\/bannerAdSize","interfaceLanguage":"swift"},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerAdapting":{"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GFPBannerAdapting"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPBannerAdapting"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerAdapting","kind":"symbol","title":"GFPBannerAdapting","abstract":[],"url":"\/documentation\/gfpsdk\/gfpbanneradapting"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerAdSize":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"GFPBannerAdSize"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerAdSize","url":"\/documentation\/gfpsdk\/gfpbanneradsize","abstract":[],"kind":"symbol","title":"GFPBannerAdSize","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPBannerAdSize","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerAdapting/bannerAdSize":{"required":true,"role":"symbol","abstract":[],"title":"bannerAdSize","navigatorTitle":[{"kind":"identifier","text":"bannerAdSize"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bannerAdSize"},{"kind":"text","text":": "},{"text":"GFPBannerAdSize","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPBannerAdSize"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerAdapting\/bannerAdSize","type":"topic","kind":"symbol","url":"\/documentation\/gfpsdk\/gfpbanneradapting\/banneradsize"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"bannerAdSize"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"value":[{"text":"bannerAdSize","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"text":"readwrite","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPBannerAdSize","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerAdSize","kind":"typeIdentifier","text":"GFPBannerAdSize"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"bannerAdSize"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","value":"GFPBannerAdapting","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerAdapting\/title"},{"op":"replace","value":[{"text":"GFPBannerAdapting","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerAdapting\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerAdapting\/navigatorTitle","value":[{"text":"GFPBannerAdapting","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerAdSize\/title","value":"GFPBannerAdSize","op":"replace"},{"op":"replace","value":[{"text":"GFPBannerAdSize","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerAdSize\/fragments"},{"value":[{"text":"GFPBannerAdSize","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerAdSize\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerAdapting~1bannerAdSize\/title","value":"bannerAdSize","op":"replace"},{"value":[{"kind":"identifier","text":"bannerAdSize"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerAdapting~1bannerAdSize\/fragments","op":"replace"}]}]}