{"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRichMediaData"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"adType","kind":"identifier"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRichMediaDataAdType","kind":"typeIdentifier","preciseIdentifier":"c:@M@GFPSDK@E@GFPRichMediaDataAdType","text":"GFPRichMediaDataAdType"}]}],"kind":"declarations"}],"metadata":{"title":"adType","symbolKind":"property","modules":[{"name":"GFPSDK"}],"role":"symbol","externalID":"c:@M@GFPSDK@objc(cs)GFPRichMediaData(py)adType","roleHeading":"Instance Property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"adType","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@GFPSDK@E@GFPRichMediaDataAdType","text":"GFPRichMediaDataAdType"}],"navigatorTitle":[{"text":"adType","kind":"identifier"}]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfprichmediadata\/adtype"]},{"paths":["\/documentation\/gfpsdk\/gfprichmediadata\/adtype"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRichMediaData\/adType"},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRichMediaData":{"url":"\/documentation\/gfpsdk\/gfprichmediadata","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPRichMediaData","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRichMediaData","navigatorTitle":[{"text":"GFPRichMediaData","kind":"identifier"}],"abstract":[],"kind":"symbol","title":"GFPRichMediaData","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRichMediaDataAdType":{"abstract":[],"navigatorTitle":[{"text":"GFPRichMediaDataAdType","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRichMediaDataAdType","type":"topic","role":"symbol","title":"GFPRichMediaDataAdType","kind":"symbol","url":"\/documentation\/gfpsdk\/gfprichmediadataadtype","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPRichMediaDataAdType","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRichMediaData/adType":{"navigatorTitle":[{"text":"adType","kind":"identifier"}],"title":"adType","url":"\/documentation\/gfpsdk\/gfprichmediadata\/adtype","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRichMediaData\/adType","role":"symbol","type":"topic","kind":"symbol","abstract":[],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"adType"},{"text":": ","kind":"text"},{"text":"GFPRichMediaDataAdType","kind":"typeIdentifier","preciseIdentifier":"c:@M@GFPSDK@E@GFPRichMediaDataAdType"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"adType","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","value":[{"text":"adType","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRichMediaDataAdType","kind":"typeIdentifier","preciseIdentifier":"c:@M@GFPSDK@E@GFPRichMediaDataAdType","text":"GFPRichMediaDataAdType"},{"kind":"text","text":" "},{"text":"adType","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"GFPRichMediaData","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRichMediaData\/title"},{"value":[{"text":"GFPRichMediaData","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRichMediaData\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRichMediaData\/navigatorTitle","value":[{"kind":"identifier","text":"GFPRichMediaData"}],"op":"replace"},{"op":"replace","value":"GFPRichMediaDataAdType","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRichMediaDataAdType\/title"},{"value":[{"kind":"identifier","text":"GFPRichMediaDataAdType"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRichMediaDataAdType\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRichMediaDataAdType\/navigatorTitle","value":[{"text":"GFPRichMediaDataAdType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRichMediaData~1adType\/title","value":"adType"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRichMediaData~1adType\/fragments","value":[{"text":"adType","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}