{"metadata":{"role":"symbol","externalID":"c:@M@GFPSDK@objc(cs)GFPRichMediaData(py)extendMediaAspectRatioType","navigatorTitle":[{"kind":"identifier","text":"extendMediaAspectRatioType"}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"extendMediaAspectRatioType","kind":"identifier"},{"kind":"text","text":": "},{"text":"GFPRichExtendMediaRatioType","preciseIdentifier":"c:GFPNativeDetailInfo.h@T@GFPRichExtendMediaRatioType","kind":"typeIdentifier"}],"symbolKind":"property","modules":[{"name":"GFPSDK"}],"title":"extendMediaAspectRatioType","roleHeading":"Instance Property"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"extendMediaAspectRatioType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRichExtendMediaRatioType","preciseIdentifier":"c:GFPNativeDetailInfo.h@T@GFPRichExtendMediaRatioType","text":"GFPRichExtendMediaRatioType"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRichMediaData"]]},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRichMediaData\/extendMediaAspectRatioType","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfprichmediadata\/extendmediaaspectratiotype"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfprichmediadata\/extendmediaaspectratiotype"]}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRichExtendMediaRatioType":{"type":"topic","url":"\/documentation\/gfpsdk\/gfprichextendmediaratiotype","abstract":[],"navigatorTitle":[{"text":"GFPRichExtendMediaRatioType","kind":"identifier"}],"role":"symbol","title":"GFPRichExtendMediaRatioType","kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRichExtendMediaRatioType","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"GFPRichExtendMediaRatioType","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRichMediaData/extendMediaAspectRatioType":{"role":"symbol","title":"extendMediaAspectRatioType","navigatorTitle":[{"text":"extendMediaAspectRatioType","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRichMediaData\/extendMediaAspectRatioType","type":"topic","abstract":[],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"extendMediaAspectRatioType","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:GFPNativeDetailInfo.h@T@GFPRichExtendMediaRatioType","text":"GFPRichExtendMediaRatioType","kind":"typeIdentifier"}],"url":"\/documentation\/gfpsdk\/gfprichmediadata\/extendmediaaspectratiotype"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRichMediaData":{"url":"\/documentation\/gfpsdk\/gfprichmediadata","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPRichMediaData","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRichMediaData","navigatorTitle":[{"text":"GFPRichMediaData","kind":"identifier"}],"abstract":[],"kind":"symbol","title":"GFPRichMediaData","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"extendMediaAspectRatioType"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"extendMediaAspectRatioType"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" * "},{"text":"extendMediaAspectRatioType","kind":"identifier"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"value":"GFPRichExtendMediaRatioType","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRichExtendMediaRatioType\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRichExtendMediaRatioType\/fragments","value":[{"text":"GFPRichExtendMediaRatioType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRichExtendMediaRatioType\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"GFPRichExtendMediaRatioType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRichMediaData~1extendMediaAspectRatioType\/title","value":"extendMediaAspectRatioType"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRichMediaData~1extendMediaAspectRatioType\/fragments","value":[{"text":"extendMediaAspectRatioType","kind":"identifier"}],"op":"replace"},{"value":"GFPRichMediaData","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRichMediaData\/title"},{"value":[{"text":"GFPRichMediaData","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRichMediaData\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRichMediaData\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"GFPRichMediaData"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}