{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"text":"adType","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRichMediaDataAdType","text":"GFPRichMediaDataAdType","kind":"typeIdentifier","preciseIdentifier":"c:@M@GFPSDK@E@GFPRichMediaDataAdType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"videoRatioType"},{"text":": ","kind":"text"},{"text":"GFPRichExtendMediaRatioType","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRichExtendMediaRatioType","kind":"typeIdentifier","preciseIdentifier":"c:GFPNativeDetailInfo.h@T@GFPRichExtendMediaRatioType"},{"text":", ","kind":"text"},{"text":"mediaSize","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier","text":"CGSize"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/gfpsdk\/gfprichmediadata\/init(adtype:videoratiotype:mediasize:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfprichmediadata\/init(adtype:videoratiotype:mediasize:)"]}],"kind":"symbol","sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRichMediaData\/init(adType:videoRatioType:mediaSize:)"},"metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"adType","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@GFPSDK@E@GFPRichMediaDataAdType","kind":"typeIdentifier","text":"GFPRichMediaDataAdType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"videoRatioType"},{"kind":"text","text":": "},{"text":"GFPRichExtendMediaRatioType","preciseIdentifier":"c:GFPNativeDetailInfo.h@T@GFPRichExtendMediaRatioType","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"mediaSize","kind":"externalParam"},{"kind":"text","text":": "},{"text":"CGSize","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":")"}],"roleHeading":"Initializer","navigatorTitle":[{"kind":"identifier","text":"initWithAdType:videoRatioType:mediaSize:"}],"role":"symbol","externalID":"c:@M@GFPSDK@objc(cs)GFPRichMediaData(im)initWithAdType:videoRatioType:mediaSize:","title":"init(adType:videoRatioType:mediaSize:)","modules":[{"name":"GFPSDK"}],"symbolKind":"init"},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRichMediaData"]]},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRichMediaData/init(adType:videoRatioType:mediaSize:)":{"role":"symbol","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRichMediaData\/init(adType:videoRatioType:mediaSize:)","abstract":[],"kind":"symbol","url":"\/documentation\/gfpsdk\/gfprichmediadata\/init(adtype:videoratiotype:mediasize:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"adType","kind":"externalParam"},{"kind":"text","text":": "},{"text":"GFPRichMediaDataAdType","preciseIdentifier":"c:@M@GFPSDK@E@GFPRichMediaDataAdType","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"videoRatioType","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:GFPNativeDetailInfo.h@T@GFPRichExtendMediaRatioType","text":"GFPRichExtendMediaRatioType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mediaSize"},{"kind":"text","text":": "},{"text":"CGSize","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"initWithAdType:videoRatioType:mediaSize:"}],"title":"init(adType:videoRatioType:mediaSize:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRichExtendMediaRatioType":{"type":"topic","url":"\/documentation\/gfpsdk\/gfprichextendmediaratiotype","abstract":[],"navigatorTitle":[{"text":"GFPRichExtendMediaRatioType","kind":"identifier"}],"role":"symbol","title":"GFPRichExtendMediaRatioType","kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRichExtendMediaRatioType","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"GFPRichExtendMediaRatioType","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRichMediaData":{"url":"\/documentation\/gfpsdk\/gfprichmediadata","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPRichMediaData","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRichMediaData","navigatorTitle":[{"text":"GFPRichMediaData","kind":"identifier"}],"abstract":[],"kind":"symbol","title":"GFPRichMediaData","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRichMediaDataAdType":{"abstract":[],"navigatorTitle":[{"text":"GFPRichMediaDataAdType","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRichMediaDataAdType","type":"topic","role":"symbol","title":"GFPRichMediaDataAdType","kind":"symbol","url":"\/documentation\/gfpsdk\/gfprichmediadataadtype","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPRichMediaDataAdType","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"initWithAdType:videoRatioType:mediaSize:"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithAdType:videoRatioType:mediaSize:"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"kind":"text","text":") "},{"text":"initWithAdType:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"GFPRichMediaDataAdType","kind":"typeIdentifier","preciseIdentifier":"c:@M@GFPSDK@E@GFPRichMediaDataAdType","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRichMediaDataAdType"},{"kind":"text","text":") "},{"kind":"internalParam","text":"adType"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoRatioType:"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"videoRatioType"},{"kind":"text","text":" "},{"text":"mediaSize:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@S@CGSize","text":"CGSize","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"mediaSize"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRichMediaData~1init(adType:videoRatioType:mediaSize:)\/title","value":"initWithAdType:videoRatioType:mediaSize:"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithAdType:videoRatioType:mediaSize:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRichMediaData~1init(adType:videoRatioType:mediaSize:)\/fragments"},{"op":"replace","value":"GFPRichExtendMediaRatioType","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRichExtendMediaRatioType\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRichExtendMediaRatioType\/fragments","value":[{"text":"GFPRichExtendMediaRatioType","kind":"identifier"}]},{"value":[{"text":"GFPRichExtendMediaRatioType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRichExtendMediaRatioType\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRichMediaData\/title","op":"replace","value":"GFPRichMediaData"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRichMediaData\/fragments","value":[{"kind":"identifier","text":"GFPRichMediaData"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRichMediaData\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"GFPRichMediaData"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRichMediaDataAdType\/title","value":"GFPRichMediaDataAdType","op":"replace"},{"value":[{"kind":"identifier","text":"GFPRichMediaDataAdType"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRichMediaDataAdType\/fragments","op":"replace"},{"op":"replace","value":[{"text":"GFPRichMediaDataAdType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRichMediaDataAdType\/navigatorTitle"}]}]}