{"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"placementType"},{"text":"(","kind":"text"},{"text":"withTimeOffset","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"timeOffset","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}]}],"kind":"declarations"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpvideoadplacement\/placementtype(withtimeoffset:)"]},{"paths":["\/documentation\/gfpsdk\/gfpvideoadplacement\/placementtype(withtimeoffset:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdPlacement\/placementType(withTimeOffset:)"},"metadata":{"symbolKind":"method","modules":[{"name":"GFPSDK"}],"externalID":"c:objc(cs)GFPVideoAdPlacement(cm)placementTypeWithTimeOffset:","title":"placementType(withTimeOffset:)","roleHeading":"Type Method","navigatorTitle":[{"kind":"identifier","text":"placementTypeWithTimeOffset:"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"placementType"},{"kind":"text","text":"("},{"text":"withTimeOffset","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}]},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdPlacement"]]},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdPlacement":{"abstract":[],"kind":"symbol","title":"GFPVideoAdPlacement","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"GFPVideoAdPlacement","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdPlacement","type":"topic","role":"symbol","url":"\/documentation\/gfpsdk\/gfpvideoadplacement","navigatorTitle":[{"kind":"identifier","text":"GFPVideoAdPlacement"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdPlacement/placementType(withTimeOffset:)":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"placementType","kind":"identifier"},{"kind":"text","text":"("},{"text":"withTimeOffset","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"abstract":[],"url":"\/documentation\/gfpsdk\/gfpvideoadplacement\/placementtype(withtimeoffset:)","navigatorTitle":[{"kind":"identifier","text":"placementTypeWithTimeOffset:"}],"kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdPlacement\/placementType(withTimeOffset:)","type":"topic","title":"placementType(withTimeOffset:)","role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"placementTypeWithTimeOffset:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"placementTypeWithTimeOffset:"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"placementTypeWithTimeOffset:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"NSTimeInterval"},{"kind":"text","text":") "},{"kind":"internalParam","text":"timeOffset"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdPlacement\/title","op":"replace","value":"GFPVideoAdPlacement"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdPlacement\/fragments","value":[{"text":"GFPVideoAdPlacement","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"GFPVideoAdPlacement"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdPlacement\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdPlacement~1placementType(withTimeOffset:)\/title","value":"placementTypeWithTimeOffset:"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"placementTypeWithTimeOffset:"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdPlacement~1placementType(withTimeOffset:)\/fragments"}]}]}