{"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionType"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpimpressiontype\/bounce"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpimpressiontype\/bounce"]}],"metadata":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bounce","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@GFPImpressionType","text":"GFPImpressionType","kind":"typeIdentifier"}],"roleHeading":"Type Property","symbolKind":"property","externalID":"c:@E@GFPImpressionType@GFPImpressionTypeBounce","navigatorTitle":[{"text":"GFPImpressionTypeBounce","kind":"identifier"}],"modules":[{"name":"GFPSDK"}],"title":"bounce","role":"symbol"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionType\/bounce"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bounce"},{"text":": ","kind":"text"},{"text":"GFPImpressionType","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionType","preciseIdentifier":"c:@E@GFPImpressionType"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPImpressionType":{"url":"\/documentation\/gfpsdk\/gfpimpressiontype","navigatorTitle":[{"text":"GFPImpressionType","kind":"identifier"}],"type":"topic","title":"GFPImpressionType","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionType","role":"symbol","abstract":[],"kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPImpressionType"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPImpressionType/bounce":{"abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionType\/bounce","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"bounce","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@GFPImpressionType","kind":"typeIdentifier","text":"GFPImpressionType"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"GFPImpressionTypeBounce"}],"title":"bounce","url":"\/documentation\/gfpsdk\/gfpimpressiontype\/bounce"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"value":"GFPImpressionTypeBounce","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GFPImpressionTypeBounce"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"GFPImpressionTypeBounce"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionType\/title","value":"GFPImpressionType"},{"op":"replace","value":[{"kind":"identifier","text":"GFPImpressionType"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionType\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionType\/navigatorTitle","value":[{"kind":"identifier","text":"GFPImpressionType"}]},{"value":"GFPImpressionTypeBounce","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionType~1bounce\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionType~1bounce\/fragments","value":[{"kind":"identifier","text":"GFPImpressionTypeBounce"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}