{"metadata":{"symbolKind":"case","externalID":"c:@E@GFPBannerViewLayoutType@GFPBannerViewLayoutTypeFluidHeight","modules":[{"name":"GFPSDK"}],"navigatorTitle":[{"text":"GFPBannerViewLayoutTypeFluidHeight","kind":"identifier"}],"title":"GFPBannerViewLayoutType.fluidHeight","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"fluidHeight","kind":"identifier"}],"role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fluidHeight"}]}]}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerViewLayoutType\/fluidHeight","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpbannerviewlayouttype\/fluidheight"]},{"paths":["\/documentation\/gfpsdk\/gfpbannerviewlayouttype\/fluidheight"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerViewLayoutType"]]},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerViewLayoutType":{"kind":"symbol","title":"GFPBannerViewLayoutType","url":"\/documentation\/gfpsdk\/gfpbannerviewlayouttype","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPBannerViewLayoutType"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerViewLayoutType","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GFPBannerViewLayoutType"}],"abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerViewLayoutType/fluidHeight":{"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"fluidHeight","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpbannerviewlayouttype\/fluidheight","navigatorTitle":[{"text":"GFPBannerViewLayoutTypeFluidHeight","kind":"identifier"}],"role":"symbol","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerViewLayoutType\/fluidHeight","kind":"symbol","title":"GFPBannerViewLayoutType.fluidHeight"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"value":"GFPBannerViewLayoutTypeFluidHeight","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"GFPBannerViewLayoutTypeFluidHeight","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"GFPBannerViewLayoutTypeFluidHeight"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"GFPBannerViewLayoutType","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerViewLayoutType\/title"},{"value":[{"kind":"identifier","text":"GFPBannerViewLayoutType"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerViewLayoutType\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerViewLayoutType\/navigatorTitle","op":"replace","value":[{"text":"GFPBannerViewLayoutType","kind":"identifier"}]},{"value":"GFPBannerViewLayoutTypeFluidHeight","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerViewLayoutType~1fluidHeight\/title","op":"replace"},{"value":[{"text":"GFPBannerViewLayoutTypeFluidHeight","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerViewLayoutType~1fluidHeight\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}