{"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPPhaseType\/isEmpty","interfaceLanguage":"swift"},"abstract":[{"text":"Inherited from ","type":"text"},{"code":"SetAlgebra.isEmpty","type":"codeVoice"},{"text":".","type":"text"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPPhaseType","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPPhaseType\/SetAlgebra-Implementations"]]},"variants":[{"paths":["\/documentation\/gfpsdk\/gfpphasetype\/isempty"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"modules":[{"relatedModules":["Swift"],"name":"GFPSDK"}],"extendedModule":"Swift","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"isEmpty","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"role":"symbol","roleHeading":"Instance Property","title":"isEmpty","symbolKind":"property","externalID":"s:s10SetAlgebraPsE7isEmptySbvp::SYNTHESIZED::c:@E@GFPPhaseType"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"isEmpty","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPPhaseType/isEmpty":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEmpty"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPPhaseType\/isEmpty","abstract":[],"title":"isEmpty","type":"topic","url":"\/documentation\/gfpsdk\/gfpphasetype\/isempty","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPPhaseType/SetAlgebra-Implementations":{"type":"topic","abstract":[],"title":"SetAlgebra Implementations","url":"\/documentation\/gfpsdk\/gfpphasetype\/setalgebra-implementations","role":"collectionGroup","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPPhaseType\/SetAlgebra-Implementations","kind":"article"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPPhaseType":{"kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPPhaseType","url":"\/documentation\/gfpsdk\/gfpphasetype","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"GFPPhaseType","kind":"identifier"}],"title":"GFPPhaseType","role":"symbol","type":"topic","navigatorTitle":[{"text":"GFPPhaseType","kind":"identifier"}],"abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPPhaseType\/title","value":"GFPPhaseType","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPPhaseType\/fragments","value":[{"kind":"identifier","text":"GFPPhaseType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPPhaseType\/navigatorTitle","value":[{"text":"GFPPhaseType","kind":"identifier"}]}]}]}