{"variants":[{"paths":["\/documentation\/gfpsdk\/gfpnativeextensioninfo\/styleinfo"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpnativeextensioninfo\/styleinfo"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeExtensionInfo"]]},"metadata":{"symbolKind":"property","externalID":"c:objc(cs)GFPNativeExtensionInfo(py)styleInfo","role":"symbol","modules":[{"name":"GFPSDK"}],"navigatorTitle":[{"text":"styleInfo","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"styleInfo"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"GFPNativeStyleInfo","preciseIdentifier":"c:objc(cs)GFPNativeStyleInfo"},{"text":"?","kind":"text"}],"title":"styleInfo","roleHeading":"Instance Property"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeExtensionInfo\/styleInfo"},"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"styleInfo","kind":"identifier"},{"kind":"text","text":": "},{"text":"GFPNativeStyleInfo","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeStyleInfo","preciseIdentifier":"c:objc(cs)GFPNativeStyleInfo","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeStyleInfo":{"title":"GFPNativeStyleInfo","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeStyleInfo","navigatorTitle":[{"text":"GFPNativeStyleInfo","kind":"identifier"}],"abstract":[],"kind":"symbol","type":"topic","url":"\/documentation\/gfpsdk\/gfpnativestyleinfo","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPNativeStyleInfo"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeExtensionInfo":{"url":"\/documentation\/gfpsdk\/gfpnativeextensioninfo","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"GFPNativeExtensionInfo","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeExtensionInfo","title":"GFPNativeExtensionInfo","navigatorTitle":[{"kind":"identifier","text":"GFPNativeExtensionInfo"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeExtensionInfo/styleInfo":{"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"styleInfo"}],"title":"styleInfo","url":"\/documentation\/gfpsdk\/gfpnativeextensioninfo\/styleinfo","kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeExtensionInfo\/styleInfo","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"styleInfo"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"GFPNativeStyleInfo","preciseIdentifier":"c:objc(cs)GFPNativeStyleInfo"},{"kind":"text","text":"?"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","value":"styleInfo","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"styleInfo"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"GFPNativeStyleInfo","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeStyleInfo","preciseIdentifier":"c:objc(cs)GFPNativeStyleInfo"},{"kind":"text","text":" * "},{"kind":"identifier","text":"styleInfo"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeStyleInfo\/title","value":"GFPNativeStyleInfo","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeStyleInfo\/fragments","value":[{"text":"GFPNativeStyleInfo","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeStyleInfo\/navigatorTitle","value":[{"kind":"identifier","text":"GFPNativeStyleInfo"}],"op":"replace"},{"value":"GFPNativeExtensionInfo","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeExtensionInfo\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeExtensionInfo\/fragments","value":[{"text":"GFPNativeExtensionInfo","kind":"identifier"}]},{"op":"replace","value":[{"text":"GFPNativeExtensionInfo","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeExtensionInfo\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeExtensionInfo~1styleInfo\/title","value":"styleInfo"},{"op":"replace","value":[{"kind":"identifier","text":"styleInfo"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeExtensionInfo~1styleInfo\/fragments"}]}]}