{"sections":[],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpadinterfacestyle\/light"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpadinterfacestyle\/light"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"light","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdInterfaceStyle","text":"GFPAdInterfaceStyle","preciseIdentifier":"c:@E@GFPAdInterfaceStyle"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdInterfaceStyle\/light"},"metadata":{"modules":[{"name":"GFPSDK"}],"role":"symbol","roleHeading":"Type Property","title":"light","externalID":"c:@E@GFPAdInterfaceStyle@GFPAdInterfaceStyleLight","symbolKind":"property","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"light","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPAdInterfaceStyle","text":"GFPAdInterfaceStyle"}],"navigatorTitle":[{"kind":"identifier","text":"GFPAdInterfaceStyleLight"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdInterfaceStyle"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdInterfaceStyle":{"navigatorTitle":[{"kind":"identifier","text":"GFPAdInterfaceStyle"}],"type":"topic","url":"\/documentation\/gfpsdk\/gfpadinterfacestyle","kind":"symbol","title":"GFPAdInterfaceStyle","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPAdInterfaceStyle"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdInterfaceStyle","role":"symbol","abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdInterfaceStyle/light":{"type":"topic","url":"\/documentation\/gfpsdk\/gfpadinterfacestyle\/light","role":"symbol","abstract":[],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"light","kind":"identifier"},{"kind":"text","text":": "},{"text":"GFPAdInterfaceStyle","kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPAdInterfaceStyle"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdInterfaceStyle\/light","title":"light","navigatorTitle":[{"text":"GFPAdInterfaceStyleLight","kind":"identifier"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"GFPAdInterfaceStyleLight","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"GFPAdInterfaceStyleLight","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"GFPAdInterfaceStyleLight","kind":"identifier"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdInterfaceStyle\/title","value":"GFPAdInterfaceStyle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdInterfaceStyle\/fragments","value":[{"text":"GFPAdInterfaceStyle","kind":"identifier"}]},{"op":"replace","value":[{"text":"GFPAdInterfaceStyle","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdInterfaceStyle\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdInterfaceStyle~1light\/title","value":"GFPAdInterfaceStyleLight"},{"value":[{"kind":"identifier","text":"GFPAdInterfaceStyleLight"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdInterfaceStyle~1light\/fragments","op":"replace"}]}]}