{"variants":[{"paths":["\/documentation\/gfpsdk\/gfpadinterfacestyle\/subtract(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdInterfaceStyle","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdInterfaceStyle\/SetAlgebra-Implementations"]]},"abstract":[{"type":"text","text":"Inherited from "},{"code":"SetAlgebra.subtract(_:)","type":"codeVoice"},{"type":"text","text":"."}],"metadata":{"role":"symbol","title":"subtract(_:)","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"subtract"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":")"}],"externalID":"s:s10SetAlgebraPsE8subtractyyxF::SYNTHESIZED::c:@E@GFPAdInterfaceStyle","symbolKind":"method","extendedModule":"Swift","modules":[{"name":"GFPSDK","relatedModules":["Swift"]}]},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdInterfaceStyle\/subtract(_:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"mutating"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"subtract"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"other"},{"text":": ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdInterfaceStyle/SetAlgebra-Implementations":{"title":"SetAlgebra Implementations","url":"\/documentation\/gfpsdk\/gfpadinterfacestyle\/setalgebra-implementations","role":"collectionGroup","kind":"article","type":"topic","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdInterfaceStyle\/SetAlgebra-Implementations"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdInterfaceStyle":{"navigatorTitle":[{"kind":"identifier","text":"GFPAdInterfaceStyle"}],"type":"topic","url":"\/documentation\/gfpsdk\/gfpadinterfacestyle","kind":"symbol","title":"GFPAdInterfaceStyle","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPAdInterfaceStyle"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdInterfaceStyle","role":"symbol","abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdInterfaceStyle/subtract(_:)":{"abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"subtract","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":")"}],"role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdInterfaceStyle\/subtract(_:)","url":"\/documentation\/gfpsdk\/gfpadinterfacestyle\/subtract(_:)","type":"topic","title":"subtract(_:)","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdInterfaceStyle\/title","value":"GFPAdInterfaceStyle","op":"replace"},{"op":"replace","value":[{"text":"GFPAdInterfaceStyle","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdInterfaceStyle\/fragments"},{"value":[{"kind":"identifier","text":"GFPAdInterfaceStyle"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdInterfaceStyle\/navigatorTitle"}]}]}