{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdInterfaceStyle\/system"},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdInterfaceStyle"]]},"metadata":{"externalID":"c:@E@GFPAdInterfaceStyle@GFPAdInterfaceStyleSystem","modules":[{"name":"GFPSDK"}],"title":"system","navigatorTitle":[{"text":"GFPAdInterfaceStyleSystem","kind":"identifier"}],"roleHeading":"Type Property","role":"symbol","symbolKind":"property","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"system","kind":"identifier"},{"kind":"text","text":": "},{"text":"GFPAdInterfaceStyle","preciseIdentifier":"c:@E@GFPAdInterfaceStyle","kind":"typeIdentifier"}]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"system"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@GFPAdInterfaceStyle","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdInterfaceStyle","text":"GFPAdInterfaceStyle"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpadinterfacestyle\/system"]},{"paths":["\/documentation\/gfpsdk\/gfpadinterfacestyle\/system"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdInterfaceStyle":{"navigatorTitle":[{"kind":"identifier","text":"GFPAdInterfaceStyle"}],"type":"topic","url":"\/documentation\/gfpsdk\/gfpadinterfacestyle","kind":"symbol","title":"GFPAdInterfaceStyle","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPAdInterfaceStyle"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdInterfaceStyle","role":"symbol","abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdInterfaceStyle/system":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdInterfaceStyle\/system","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"system"},{"text":": ","kind":"text"},{"text":"GFPAdInterfaceStyle","preciseIdentifier":"c:@E@GFPAdInterfaceStyle","kind":"typeIdentifier"}],"abstract":[],"type":"topic","role":"symbol","navigatorTitle":[{"text":"GFPAdInterfaceStyleSystem","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpadinterfacestyle\/system","title":"system","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"GFPAdInterfaceStyleSystem","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"GFPAdInterfaceStyleSystem","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"GFPAdInterfaceStyleSystem","kind":"identifier"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdInterfaceStyle\/title","value":"GFPAdInterfaceStyle"},{"value":[{"kind":"identifier","text":"GFPAdInterfaceStyle"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdInterfaceStyle\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdInterfaceStyle\/navigatorTitle","value":[{"kind":"identifier","text":"GFPAdInterfaceStyle"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdInterfaceStyle~1system\/title","value":"GFPAdInterfaceStyleSystem","op":"replace"},{"op":"replace","value":[{"text":"GFPAdInterfaceStyleSystem","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdInterfaceStyle~1system\/fragments"}]}]}