{"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPCoreConfig"]]},"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpcoreconfig\/initializeinfo"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpcoreconfig\/initializeinfo"]}],"metadata":{"title":"initializeInfo","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"initializeInfo"},{"text":": any ","kind":"text"},{"text":"GFPDictPresentable","kind":"typeIdentifier","preciseIdentifier":"c:@M@GFPSDK@objc(pl)GFPDictPresentable"}],"roleHeading":"Instance Property","role":"symbol","externalID":"c:objc(cs)GFPCoreConfig(py)initializeInfo","symbolKind":"property","navigatorTitle":[{"text":"initializeInfo","kind":"identifier"}],"modules":[{"name":"GFPSDK"}]},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPCoreConfig\/initializeInfo","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"initializeInfo"},{"text":": any ","kind":"text"},{"text":"GFPDictPresentable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPDictPresentable","kind":"typeIdentifier","preciseIdentifier":"c:@M@GFPSDK@objc(pl)GFPDictPresentable"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPCoreConfig":{"abstract":[],"url":"\/documentation\/gfpsdk\/gfpcoreconfig","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPCoreConfig","role":"symbol","title":"GFPCoreConfig","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPCoreConfig","kind":"identifier"}],"navigatorTitle":[{"text":"GFPCoreConfig","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPCoreConfig/initializeInfo":{"abstract":[],"type":"topic","title":"initializeInfo","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"initializeInfo","kind":"identifier"},{"text":": any ","kind":"text"},{"text":"GFPDictPresentable","kind":"typeIdentifier","preciseIdentifier":"c:@M@GFPSDK@objc(pl)GFPDictPresentable"}],"url":"\/documentation\/gfpsdk\/gfpcoreconfig\/initializeinfo","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPCoreConfig\/initializeInfo","navigatorTitle":[{"kind":"identifier","text":"initializeInfo"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPDictPresentable":{"abstract":[],"title":"GFPDictPresentable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPDictPresentable","navigatorTitle":[{"text":"GFPDictPresentable","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPDictPresentable","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/gfpsdk\/gfpdictpresentable"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","value":"initializeInfo","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"initializeInfo","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@GFPSDK@objc(pl)GFPDictPresentable","text":"id<GFPDictPresentable>"},{"kind":"text","text":" "},{"text":"initializeInfo","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPCoreConfig\/title","value":"GFPCoreConfig"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPCoreConfig\/fragments","op":"replace","value":[{"kind":"identifier","text":"GFPCoreConfig"}]},{"value":[{"kind":"identifier","text":"GFPCoreConfig"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPCoreConfig\/navigatorTitle"},{"value":"initializeInfo","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPCoreConfig~1initializeInfo\/title"},{"value":[{"text":"initializeInfo","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPCoreConfig~1initializeInfo\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPDictPresentable\/title","op":"replace","value":"GFPDictPresentable"},{"op":"replace","value":[{"text":"GFPDictPresentable","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPDictPresentable\/fragments"},{"value":[{"text":"GFPDictPresentable","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPDictPresentable\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}