{"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorUtils"]]},"sections":[],"variants":[{"paths":["\/documentation\/gfpsdk\/gfperrorutils\/nativeadrenderingerror(withmediaviewsetting:adviewhasmediaview:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gfpsdk\/gfperrorutils\/nativeadrenderingerror(withmediaviewsetting:adviewhasmediaview:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"nativeAdRenderingError","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withMediaViewSetting","kind":"externalParam"},{"kind":"text","text":" "},{"text":"hasMediaView","kind":"internalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"adViewHasMediaView","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@NaverAdsServices@objc(cs)GFPError","kind":"typeIdentifier","text":"GFPError"}]}],"kind":"declarations"}],"metadata":{"externalID":"c:objc(cs)GFPErrorUtils(cm)nativeAdRenderingErrorWithMediaViewSetting:adViewHasMediaView:","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"nativeAdRenderingError"},{"kind":"text","text":"("},{"text":"withMediaViewSetting","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"adViewHasMediaView","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"GFPError","kind":"typeIdentifier","preciseIdentifier":"c:@M@NaverAdsServices@objc(cs)GFPError"}],"navigatorTitle":[{"text":"nativeAdRenderingErrorWithMediaViewSetting:adViewHasMediaView:","kind":"identifier"}],"modules":[{"name":"GFPSDK"}],"symbolKind":"method","role":"symbol","title":"nativeAdRenderingError(withMediaViewSetting:adViewHasMediaView:)","roleHeading":"Type Method"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorUtils\/nativeAdRenderingError(withMediaViewSetting:adViewHasMediaView:)"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPErrorUtils/nativeAdRenderingError(withMediaViewSetting:adViewHasMediaView:)":{"title":"nativeAdRenderingError(withMediaViewSetting:adViewHasMediaView:)","navigatorTitle":[{"text":"nativeAdRenderingErrorWithMediaViewSetting:adViewHasMediaView:","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfperrorutils\/nativeadrenderingerror(withmediaviewsetting:adviewhasmediaview:)","role":"symbol","kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"nativeAdRenderingError","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withMediaViewSetting"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"adViewHasMediaView","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@NaverAdsServices@objc(cs)GFPError","text":"GFPError"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorUtils\/nativeAdRenderingError(withMediaViewSetting:adViewHasMediaView:)","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPErrorUtils":{"kind":"symbol","title":"GFPErrorUtils","url":"\/documentation\/gfpsdk\/gfperrorutils","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPErrorUtils","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorUtils","navigatorTitle":[{"text":"GFPErrorUtils","kind":"identifier"}],"abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Type Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"nativeAdRenderingErrorWithMediaViewSetting:adViewHasMediaView:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"text":"nativeAdRenderingErrorWithMediaViewSetting:adViewHasMediaView:","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"text":"GFPError","kind":"typeIdentifier","preciseIdentifier":"c:@M@NaverAdsServices@objc(cs)GFPError"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"nativeAdRenderingErrorWithMediaViewSetting:"},{"kind":"text","text":"("},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"hasMediaView","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"adViewHasMediaView:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"adViewHasMediaView","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"nativeAdRenderingErrorWithMediaViewSetting:adViewHasMediaView:","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorUtils~1nativeAdRenderingError(withMediaViewSetting:adViewHasMediaView:)\/title"},{"value":[{"kind":"text","text":"+ "},{"text":"nativeAdRenderingErrorWithMediaViewSetting:adViewHasMediaView:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorUtils~1nativeAdRenderingError(withMediaViewSetting:adViewHasMediaView:)\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorUtils\/title","op":"replace","value":"GFPErrorUtils"},{"value":[{"text":"GFPErrorUtils","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorUtils\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorUtils\/navigatorTitle","value":[{"kind":"identifier","text":"GFPErrorUtils"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}