{"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"title":"GFPATTAuthorizationStatus.authorized","role":"symbol","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"authorized"}],"externalID":"c:@E@GFPATTAuthorizationStatus@GFPATTAuthorizationStatusAuthorized","modules":[{"name":"GFPSDK"}],"roleHeading":"Case","navigatorTitle":[{"text":"GFPATTAuthorizationStatusAuthorized","kind":"identifier"}]},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPATTAuthorizationStatus\/authorized","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"authorized"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpattauthorizationstatus\/authorized"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpattauthorizationstatus\/authorized"]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPATTAuthorizationStatus"]]},"sections":[],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPATTAuthorizationStatus":{"abstract":[],"role":"symbol","url":"\/documentation\/gfpsdk\/gfpattauthorizationstatus","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPATTAuthorizationStatus"}],"navigatorTitle":[{"text":"GFPATTAuthorizationStatus","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPATTAuthorizationStatus","title":"GFPATTAuthorizationStatus","kind":"symbol","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPATTAuthorizationStatus/authorized":{"role":"symbol","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"authorized","kind":"identifier"}],"navigatorTitle":[{"text":"GFPATTAuthorizationStatusAuthorized","kind":"identifier"}],"title":"GFPATTAuthorizationStatus.authorized","abstract":[],"url":"\/documentation\/gfpsdk\/gfpattauthorizationstatus\/authorized","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPATTAuthorizationStatus\/authorized"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"GFPATTAuthorizationStatusAuthorized"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GFPATTAuthorizationStatusAuthorized"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"GFPATTAuthorizationStatusAuthorized"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPATTAuthorizationStatus\/title","value":"GFPATTAuthorizationStatus","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPATTAuthorizationStatus\/fragments","value":[{"kind":"identifier","text":"GFPATTAuthorizationStatus"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPATTAuthorizationStatus\/navigatorTitle","value":[{"text":"GFPATTAuthorizationStatus","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPATTAuthorizationStatus~1authorized\/title","value":"GFPATTAuthorizationStatusAuthorized","op":"replace"},{"value":[{"text":"GFPATTAuthorizationStatusAuthorized","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPATTAuthorizationStatus~1authorized\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}