{"topicSections":[{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPATTAuthorizationStatus\/!=(_:_:)"],"generated":true,"anchor":"Operators","title":"Operators"}],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpattauthorizationstatus\/equatable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPATTAuthorizationStatus"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPATTAuthorizationStatus\/Equatable-Implementations"},"kind":"article","metadata":{"role":"collectionGroup","roleHeading":"API Collection","title":"Equatable Implementations","modules":[{"name":"GFPSDK"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPATTAuthorizationStatus/!=(_:_:)":{"type":"topic","title":"!=(_:_:)","abstract":[],"role":"symbol","url":"\/documentation\/gfpsdk\/gfpattauthorizationstatus\/!=(_:_:)","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPATTAuthorizationStatus\/!=(_:_:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPATTAuthorizationStatus":{"abstract":[],"role":"symbol","url":"\/documentation\/gfpsdk\/gfpattauthorizationstatus","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPATTAuthorizationStatus"}],"navigatorTitle":[{"text":"GFPATTAuthorizationStatus","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPATTAuthorizationStatus","title":"GFPATTAuthorizationStatus","kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPATTAuthorizationStatus\/title","value":"GFPATTAuthorizationStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPATTAuthorizationStatus\/fragments","value":[{"text":"GFPATTAuthorizationStatus","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"GFPATTAuthorizationStatus"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPATTAuthorizationStatus\/navigatorTitle"}]}]}