{"variants":[{"paths":["\/documentation\/gfpsdk\/gfpattauthorizationstatus\/restricted"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gfpsdk\/gfpattauthorizationstatus\/restricted"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPATTAuthorizationStatus"]]},"metadata":{"title":"GFPATTAuthorizationStatus.restricted","role":"symbol","modules":[{"name":"GFPSDK"}],"externalID":"c:@E@GFPATTAuthorizationStatus@GFPATTAuthorizationStatusRestricted","navigatorTitle":[{"text":"GFPATTAuthorizationStatusRestricted","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"restricted"}],"roleHeading":"Case","symbolKind":"case"},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPATTAuthorizationStatus\/restricted","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"restricted"}],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPATTAuthorizationStatus/restricted":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPATTAuthorizationStatus\/restricted","title":"GFPATTAuthorizationStatus.restricted","role":"symbol","url":"\/documentation\/gfpsdk\/gfpattauthorizationstatus\/restricted","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPATTAuthorizationStatusRestricted"}],"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"restricted"}],"abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPATTAuthorizationStatus":{"abstract":[],"role":"symbol","url":"\/documentation\/gfpsdk\/gfpattauthorizationstatus","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPATTAuthorizationStatus"}],"navigatorTitle":[{"text":"GFPATTAuthorizationStatus","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPATTAuthorizationStatus","title":"GFPATTAuthorizationStatus","kind":"symbol","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"GFPATTAuthorizationStatusRestricted","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"value":[{"kind":"identifier","text":"GFPATTAuthorizationStatusRestricted"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"GFPATTAuthorizationStatusRestricted","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","value":"GFPATTAuthorizationStatusRestricted","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPATTAuthorizationStatus~1restricted\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPATTAuthorizationStatus~1restricted\/fragments","value":[{"text":"GFPATTAuthorizationStatusRestricted","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPATTAuthorizationStatus\/title","value":"GFPATTAuthorizationStatus","op":"replace"},{"value":[{"kind":"identifier","text":"GFPATTAuthorizationStatus"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPATTAuthorizationStatus\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPATTAuthorizationStatus\/navigatorTitle","value":[{"kind":"identifier","text":"GFPATTAuthorizationStatus"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}