{"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUnifiedMediatorDelegate\/unifiedMediator(_:didFailToLoadAdaptorWithError:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"unifiedMediator","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"mediator","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUnifiedMediator","preciseIdentifier":"c:objc(cs)GFPUnifiedMediator","kind":"typeIdentifier","text":"GFPUnifiedMediator"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFailToLoadAdaptorWithError"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@NaverAdsServices@objc(cs)GFPError","kind":"typeIdentifier","text":"GFPError"},{"kind":"text","text":")"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpunifiedmediatordelegate\/unifiedmediator(_:didfailtoloadadaptorwitherror:)"]},{"paths":["\/documentation\/gfpsdk\/gfpunifiedmediatordelegate\/unifiedmediator(_:didfailtoloadadaptorwitherror:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"modules":[{"name":"GFPSDK"}],"required":true,"role":"symbol","roleHeading":"Instance Method","title":"unifiedMediator(_:didFailToLoadAdaptorWithError:)","externalID":"c:objc(pl)GFPUnifiedMediatorDelegate(im)unifiedMediator:didFailToLoadAdaptorWithError:","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"unifiedMediator"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"GFPUnifiedMediator","preciseIdentifier":"c:objc(cs)GFPUnifiedMediator"},{"kind":"text","text":", "},{"text":"didFailToLoadAdaptorWithError","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@NaverAdsServices@objc(cs)GFPError","kind":"typeIdentifier","text":"GFPError"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"unifiedMediator:didFailToLoadAdaptorWithError:","kind":"identifier"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUnifiedMediatorDelegate"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPUnifiedMediator":{"abstract":[],"type":"topic","title":"GFPUnifiedMediator","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPUnifiedMediator","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpunifiedmediator","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUnifiedMediator","navigatorTitle":[{"text":"GFPUnifiedMediator","kind":"identifier"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPUnifiedMediatorDelegate":{"type":"topic","navigatorTitle":[{"text":"GFPUnifiedMediatorDelegate","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/gfpsdk\/gfpunifiedmediatordelegate","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPUnifiedMediatorDelegate"}],"title":"GFPUnifiedMediatorDelegate","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUnifiedMediatorDelegate"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPUnifiedMediatorDelegate/unifiedMediator(_:didFailToLoadAdaptorWithError:)":{"type":"topic","required":true,"navigatorTitle":[{"text":"unifiedMediator:didFailToLoadAdaptorWithError:","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/gfpsdk\/gfpunifiedmediatordelegate\/unifiedmediator(_:didfailtoloadadaptorwitherror:)","role":"symbol","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"unifiedMediator"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPUnifiedMediator","text":"GFPUnifiedMediator","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didFailToLoadAdaptorWithError","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@NaverAdsServices@objc(cs)GFPError","kind":"typeIdentifier","text":"GFPError"},{"kind":"text","text":")"}],"title":"unifiedMediator(_:didFailToLoadAdaptorWithError:)","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUnifiedMediatorDelegate\/unifiedMediator(_:didFailToLoadAdaptorWithError:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","value":"unifiedMediator:didFailToLoadAdaptorWithError:","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"unifiedMediator:didFailToLoadAdaptorWithError:"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"unifiedMediator:"},{"text":"(","kind":"text"},{"text":"GFPUnifiedMediator","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUnifiedMediator","preciseIdentifier":"c:objc(cs)GFPUnifiedMediator","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"mediator"},{"kind":"text","text":" "},{"text":"didFailToLoadAdaptorWithError:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"GFPError","kind":"typeIdentifier","preciseIdentifier":"c:@M@NaverAdsServices@objc(cs)GFPError"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"error"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPUnifiedMediator\/title","op":"replace","value":"GFPUnifiedMediator"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPUnifiedMediator\/fragments","value":[{"text":"GFPUnifiedMediator","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPUnifiedMediator\/navigatorTitle","value":[{"text":"GFPUnifiedMediator","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPUnifiedMediatorDelegate\/title","value":"GFPUnifiedMediatorDelegate"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPUnifiedMediatorDelegate\/fragments","value":[{"text":"GFPUnifiedMediatorDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPUnifiedMediatorDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"GFPUnifiedMediatorDelegate"}],"op":"replace"},{"value":"unifiedMediator:didFailToLoadAdaptorWithError:","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPUnifiedMediatorDelegate~1unifiedMediator(_:didFailToLoadAdaptorWithError:)\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPUnifiedMediatorDelegate~1unifiedMediator(_:didFailToLoadAdaptorWithError:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"unifiedMediator:didFailToLoadAdaptorWithError:"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}