{"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUnifiedMediatorDelegate"]]},"variants":[{"paths":["\/documentation\/gfpsdk\/gfpunifiedmediatordelegate\/unifiedmediator(_:didload:)-3koln"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gfpsdk\/gfpunifiedmediatordelegate\/unifiedmediator(_:didload:)-3koln"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"unifiedMediator"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPUnifiedMediator","text":"GFPUnifiedMediator"},{"kind":"text","text":", "},{"text":"didLoad","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)GFPNativeAd","kind":"typeIdentifier","text":"GFPNativeAd"},{"text":")","kind":"text"}],"roleHeading":"Instance Method","modules":[{"name":"GFPSDK"}],"role":"symbol","required":true,"symbolKind":"method","title":"unifiedMediator(_:didLoad:)","externalID":"c:objc(pl)GFPUnifiedMediatorDelegate(im)unifiedMediator:didLoadNativeAd:","navigatorTitle":[{"kind":"identifier","text":"unifiedMediator:didLoadNativeAd:"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUnifiedMediatorDelegate\/unifiedMediator(_:didLoad:)-3koln"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"unifiedMediator"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"mediator","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"GFPUnifiedMediator","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUnifiedMediator","preciseIdentifier":"c:objc(cs)GFPUnifiedMediator"},{"text":", ","kind":"text"},{"text":"didLoad","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"nativeAd"},{"kind":"text","text":": "},{"text":"GFPNativeAd","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAd","preciseIdentifier":"c:objc(cs)GFPNativeAd","kind":"typeIdentifier"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPUnifiedMediatorDelegate":{"type":"topic","navigatorTitle":[{"text":"GFPUnifiedMediatorDelegate","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/gfpsdk\/gfpunifiedmediatordelegate","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPUnifiedMediatorDelegate"}],"title":"GFPUnifiedMediatorDelegate","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUnifiedMediatorDelegate"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPUnifiedMediator":{"abstract":[],"type":"topic","title":"GFPUnifiedMediator","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPUnifiedMediator","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpunifiedmediator","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUnifiedMediator","navigatorTitle":[{"text":"GFPUnifiedMediator","kind":"identifier"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAd":{"abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAd","url":"\/documentation\/gfpsdk\/gfpnativead","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPNativeAd"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPNativeAd"}],"type":"topic","kind":"symbol","title":"GFPNativeAd"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPUnifiedMediatorDelegate/unifiedMediator(_:didLoad:)-3koln":{"type":"topic","required":true,"navigatorTitle":[{"text":"unifiedMediator:didLoadNativeAd:","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/gfpsdk\/gfpunifiedmediatordelegate\/unifiedmediator(_:didload:)-3koln","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"unifiedMediator","kind":"identifier"},{"text":"(","kind":"text"},{"text":"GFPUnifiedMediator","preciseIdentifier":"c:objc(cs)GFPUnifiedMediator","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didLoad","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)GFPNativeAd","kind":"typeIdentifier","text":"GFPNativeAd"},{"text":")","kind":"text"}],"title":"unifiedMediator(_:didLoad:)","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUnifiedMediatorDelegate\/unifiedMediator(_:didLoad:)-3koln"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"unifiedMediator:didLoadNativeAd:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"unifiedMediator:didLoadNativeAd:","kind":"identifier"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"unifiedMediator:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUnifiedMediator","preciseIdentifier":"c:objc(cs)GFPUnifiedMediator","text":"GFPUnifiedMediator"},{"text":" *) ","kind":"text"},{"text":"mediator","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"didLoadNativeAd:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)GFPNativeAd","text":"GFPNativeAd","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAd","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"nativeAd","kind":"internalParam"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPUnifiedMediatorDelegate\/title","value":"GFPUnifiedMediatorDelegate","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPUnifiedMediatorDelegate\/fragments","value":[{"kind":"identifier","text":"GFPUnifiedMediatorDelegate"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPUnifiedMediatorDelegate\/navigatorTitle","value":[{"text":"GFPUnifiedMediatorDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPUnifiedMediator\/title","op":"replace","value":"GFPUnifiedMediator"},{"value":[{"text":"GFPUnifiedMediator","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPUnifiedMediator\/fragments"},{"value":[{"kind":"identifier","text":"GFPUnifiedMediator"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPUnifiedMediator\/navigatorTitle"},{"value":"GFPNativeAd","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAd\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAd\/fragments","op":"replace","value":[{"text":"GFPNativeAd","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAd\/navigatorTitle","value":[{"kind":"identifier","text":"GFPNativeAd"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPUnifiedMediatorDelegate~1unifiedMediator(_:didLoad:)-3koln\/title","value":"unifiedMediator:didLoadNativeAd:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"unifiedMediator:didLoadNativeAd:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPUnifiedMediatorDelegate~1unifiedMediator(_:didLoad:)-3koln\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}