{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unifiedMediator","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"mediator"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPUnifiedMediator","text":"GFPUnifiedMediator","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUnifiedMediator","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didLoad"},{"text":" ","kind":"text"},{"text":"nativeAd","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"GFPNativeSimpleAd","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAd","preciseIdentifier":"c:objc(cs)GFPNativeSimpleAd"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpunifiedmediatordelegate\/unifiedmediator(_:didload:)-5jg9a"]},{"paths":["\/documentation\/gfpsdk\/gfpunifiedmediatordelegate\/unifiedmediator(_:didload:)-5jg9a"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"method","required":true,"modules":[{"name":"GFPSDK"}],"title":"unifiedMediator(_:didLoad:)","roleHeading":"Instance Method","externalID":"c:objc(pl)GFPUnifiedMediatorDelegate(im)unifiedMediator:didLoadNativeSimpleAd:","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unifiedMediator"},{"text":"(","kind":"text"},{"text":"GFPUnifiedMediator","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPUnifiedMediator"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didLoad"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPNativeSimpleAd","text":"GFPNativeSimpleAd"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"unifiedMediator:didLoadNativeSimpleAd:"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUnifiedMediatorDelegate\/unifiedMediator(_:didLoad:)-5jg9a"},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUnifiedMediatorDelegate"]]},"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPUnifiedMediatorDelegate/unifiedMediator(_:didLoad:)-5jg9a":{"required":true,"url":"\/documentation\/gfpsdk\/gfpunifiedmediatordelegate\/unifiedmediator(_:didload:)-5jg9a","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"unifiedMediator","kind":"identifier"},{"text":"(","kind":"text"},{"text":"GFPUnifiedMediator","preciseIdentifier":"c:objc(cs)GFPUnifiedMediator","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didLoad","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPNativeSimpleAd","text":"GFPNativeSimpleAd"},{"text":")","kind":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUnifiedMediatorDelegate\/unifiedMediator(_:didLoad:)-5jg9a","abstract":[],"role":"symbol","navigatorTitle":[{"text":"unifiedMediator:didLoadNativeSimpleAd:","kind":"identifier"}],"title":"unifiedMediator(_:didLoad:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPUnifiedMediatorDelegate":{"type":"topic","navigatorTitle":[{"text":"GFPUnifiedMediatorDelegate","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/gfpsdk\/gfpunifiedmediatordelegate","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPUnifiedMediatorDelegate"}],"title":"GFPUnifiedMediatorDelegate","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUnifiedMediatorDelegate"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeSimpleAd":{"type":"topic","navigatorTitle":[{"text":"GFPNativeSimpleAd","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPNativeSimpleAd"}],"title":"GFPNativeSimpleAd","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAd","url":"\/documentation\/gfpsdk\/gfpnativesimplead","abstract":[],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPUnifiedMediator":{"abstract":[],"type":"topic","title":"GFPUnifiedMediator","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPUnifiedMediator","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpunifiedmediator","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUnifiedMediator","navigatorTitle":[{"text":"GFPUnifiedMediator","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"unifiedMediator:didLoadNativeSimpleAd:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"unifiedMediator:didLoadNativeSimpleAd:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"unifiedMediator:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPUnifiedMediator","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUnifiedMediator","text":"GFPUnifiedMediator","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"mediator"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didLoadNativeSimpleAd:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPNativeSimpleAd","text":"GFPNativeSimpleAd","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAd","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"nativeAd","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPUnifiedMediatorDelegate~1unifiedMediator(_:didLoad:)-5jg9a\/title","value":"unifiedMediator:didLoadNativeSimpleAd:"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPUnifiedMediatorDelegate~1unifiedMediator(_:didLoad:)-5jg9a\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"unifiedMediator:didLoadNativeSimpleAd:"}],"op":"replace"},{"value":"GFPUnifiedMediatorDelegate","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPUnifiedMediatorDelegate\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPUnifiedMediatorDelegate\/fragments","value":[{"kind":"identifier","text":"GFPUnifiedMediatorDelegate"}],"op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"GFPUnifiedMediatorDelegate"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPUnifiedMediatorDelegate\/navigatorTitle"},{"op":"replace","value":"GFPNativeSimpleAd","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAd\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAd\/fragments","value":[{"kind":"identifier","text":"GFPNativeSimpleAd"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAd\/navigatorTitle","value":[{"text":"GFPNativeSimpleAd","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPUnifiedMediator\/title","value":"GFPUnifiedMediator"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPUnifiedMediator\/fragments","op":"replace","value":[{"text":"GFPUnifiedMediator","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPUnifiedMediator\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"GFPUnifiedMediator"}]}]}]}