{"metadata":{"title":"unifiedMediator(_:didReceivedWaterfallResponse:)","externalID":"c:objc(pl)GFPUnifiedMediatorDelegate(im)unifiedMediator:didReceivedWaterfallResponse:","role":"symbol","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"unifiedMediator"},{"text":"(","kind":"text"},{"text":"GFPUnifiedMediator","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPUnifiedMediator"},{"kind":"text","text":", "},{"text":"didReceivedWaterfallResponse","kind":"externalParam"},{"kind":"text","text":": "},{"text":"GFPWaterfallExtra","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPWaterfallExtra"},{"text":")","kind":"text"}],"modules":[{"name":"GFPSDK"}],"navigatorTitle":[{"kind":"identifier","text":"unifiedMediator:didReceivedWaterfallResponse:"}],"roleHeading":"Instance Method","required":true},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUnifiedMediatorDelegate\/unifiedMediator(_:didReceivedWaterfallResponse:)"},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUnifiedMediatorDelegate"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unifiedMediator","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"mediator","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPUnifiedMediator","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUnifiedMediator","text":"GFPUnifiedMediator"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceivedWaterfallResponse"},{"kind":"text","text":" "},{"kind":"internalParam","text":"waterfallList"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPWaterfallExtra","text":"GFPWaterfallExtra","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPWaterfallExtra"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpunifiedmediatordelegate\/unifiedmediator(_:didreceivedwaterfallresponse:)"]},{"paths":["\/documentation\/gfpsdk\/gfpunifiedmediatordelegate\/unifiedmediator(_:didreceivedwaterfallresponse:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPUnifiedMediatorDelegate/unifiedMediator(_:didReceivedWaterfallResponse:)":{"required":true,"url":"\/documentation\/gfpsdk\/gfpunifiedmediatordelegate\/unifiedmediator(_:didreceivedwaterfallresponse:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"unifiedMediator"},{"text":"(","kind":"text"},{"text":"GFPUnifiedMediator","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPUnifiedMediator"},{"text":", ","kind":"text"},{"text":"didReceivedWaterfallResponse","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPWaterfallExtra","text":"GFPWaterfallExtra"},{"kind":"text","text":")"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUnifiedMediatorDelegate\/unifiedMediator(_:didReceivedWaterfallResponse:)","abstract":[],"role":"symbol","navigatorTitle":[{"text":"unifiedMediator:didReceivedWaterfallResponse:","kind":"identifier"}],"title":"unifiedMediator(_:didReceivedWaterfallResponse:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPWaterfallExtra":{"abstract":[],"navigatorTitle":[{"text":"GFPWaterfallExtra","kind":"identifier"}],"title":"GFPWaterfallExtra","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPWaterfallExtra","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPWaterfallExtra"}],"url":"\/documentation\/gfpsdk\/gfpwaterfallextra","kind":"symbol","role":"symbol","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPUnifiedMediatorDelegate":{"type":"topic","navigatorTitle":[{"text":"GFPUnifiedMediatorDelegate","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/gfpsdk\/gfpunifiedmediatordelegate","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPUnifiedMediatorDelegate"}],"title":"GFPUnifiedMediatorDelegate","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUnifiedMediatorDelegate"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPUnifiedMediator":{"abstract":[],"type":"topic","title":"GFPUnifiedMediator","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPUnifiedMediator","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpunifiedmediator","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUnifiedMediator","navigatorTitle":[{"text":"GFPUnifiedMediator","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"unifiedMediator:didReceivedWaterfallResponse:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"unifiedMediator:didReceivedWaterfallResponse:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"unifiedMediator:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPUnifiedMediator","text":"GFPUnifiedMediator","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUnifiedMediator"},{"text":" *) ","kind":"text"},{"text":"mediator","kind":"internalParam"},{"kind":"text","text":" "},{"text":"didReceivedWaterfallResponse:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPWaterfallExtra","text":"GFPWaterfallExtra","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPWaterfallExtra","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"waterfallList"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"value":"unifiedMediator:didReceivedWaterfallResponse:","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPUnifiedMediatorDelegate~1unifiedMediator(_:didReceivedWaterfallResponse:)\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPUnifiedMediatorDelegate~1unifiedMediator(_:didReceivedWaterfallResponse:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"unifiedMediator:didReceivedWaterfallResponse:"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPWaterfallExtra\/title","op":"replace","value":"GFPWaterfallExtra"},{"value":[{"text":"GFPWaterfallExtra","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPWaterfallExtra\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPWaterfallExtra\/navigatorTitle","value":[{"text":"GFPWaterfallExtra","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPUnifiedMediatorDelegate\/title","value":"GFPUnifiedMediatorDelegate","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPUnifiedMediatorDelegate\/fragments","value":[{"text":"GFPUnifiedMediatorDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPUnifiedMediatorDelegate\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"GFPUnifiedMediatorDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPUnifiedMediator\/title","value":"GFPUnifiedMediator"},{"value":[{"text":"GFPUnifiedMediator","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPUnifiedMediator\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPUnifiedMediator\/navigatorTitle","value":[{"kind":"identifier","text":"GFPUnifiedMediator"}],"op":"replace"}]}]}