{"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPURLUtilsExtension\/openURLWith(_:completion:)","interfaceLanguage":"swift"},"metadata":{"role":"symbol","externalID":"c:@M@GFPSDK@objc(cs)GFPURLUtilsExtension(cm)openURLWith:completion:","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"openURLWith","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"GFPS2SAdLandingHandler","kind":"typeIdentifier","preciseIdentifier":"s:6GFPSDK22GFPS2SAdLandingHandlera"},{"text":"?)","kind":"text"}],"modules":[{"name":"GFPSDK"}],"symbolKind":"method","title":"openURLWith(_:completion:)","roleHeading":"Type Method","navigatorTitle":[{"kind":"identifier","text":"openURLWith:completion:"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"openURLWith"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"aURL"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPS2SAdLandingHandler-7ff0","kind":"typeIdentifier","preciseIdentifier":"s:6GFPSDK22GFPS2SAdLandingHandlera","text":"GFPS2SAdLandingHandler"},{"text":"?)","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpurlutilsextension\/openurlwith(_:completion:)"]},{"paths":["\/documentation\/gfpsdk\/gfpurlutilsextension\/openurlwith(_:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPURLUtilsExtension"]]},"kind":"symbol","sections":[],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPURLUtilsExtension":{"kind":"symbol","url":"\/documentation\/gfpsdk\/gfpurlutilsextension","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPURLUtilsExtension"}],"navigatorTitle":[{"text":"GFPURLUtilsExtension","kind":"identifier"}],"type":"topic","abstract":[],"title":"GFPURLUtilsExtension","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPURLUtilsExtension"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPS2SAdLandingHandler-7ff0":{"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"GFPS2SAdLandingHandler","kind":"identifier"}],"navigatorTitle":[{"text":"GFPS2SAdLandingHandler","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPS2SAdLandingHandler-7ff0","url":"\/documentation\/gfpsdk\/gfps2sadlandinghandler-7ff0","kind":"symbol","role":"symbol","abstract":[],"type":"topic","title":"GFPS2SAdLandingHandler"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPURLUtilsExtension/openURLWith(_:completion:)":{"url":"\/documentation\/gfpsdk\/gfpurlutilsextension\/openurlwith(_:completion:)","abstract":[],"type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPURLUtilsExtension\/openURLWith(_:completion:)","title":"openURLWith(_:completion:)","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"openURLWith","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:6GFPSDK22GFPS2SAdLandingHandlera","text":"GFPS2SAdLandingHandler"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"text":"openURLWith:completion:","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Type Method","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"openURLWith:completion:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"openURLWith:completion:"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"openURLWith:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"aURL"},{"kind":"text","text":" "},{"text":"completion:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":" (^","kind":"text"},{"text":")(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":" "},{"text":"","kind":"internalParam"},{"kind":"text","text":")) "},{"text":"completion","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"GFPURLUtilsExtension","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPURLUtilsExtension\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPURLUtilsExtension\/fragments","value":[{"kind":"identifier","text":"GFPURLUtilsExtension"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPURLUtilsExtension\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"GFPURLUtilsExtension"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPURLUtilsExtension~1openURLWith(_:completion:)\/title","value":"openURLWith:completion:"},{"value":[{"text":"+ ","kind":"text"},{"text":"openURLWith:completion:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPURLUtilsExtension~1openURLWith(_:completion:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}