{"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"abstract":[{"text":"광고 영상의 forwardBufferDuration을 설정합니다.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"cf. https:\/\/developer.apple.com\/documentation\/avfoundation\/avplayeritem\/1643630-preferredforwardbufferduration"}],"metadata":{"navigatorTitle":[{"text":"preferredForwardBufferDuration","kind":"identifier"}],"externalID":"c:objc(cs)GFPVideoController(py)preferredForwardBufferDuration","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"preferredForwardBufferDuration","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"}],"modules":[{"name":"GFPSDK"}],"roleHeading":"Instance Property","role":"symbol","title":"preferredForwardBufferDuration"},"variants":[{"paths":["\/documentation\/gfpsdk\/gfpvideocontroller\/preferredforwardbufferduration"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gfpsdk\/gfpvideocontroller\/preferredforwardbufferduration"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"preferredForwardBufferDuration","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoController"]]},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoController\/preferredForwardBufferDuration","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoController/preferredForwardBufferDuration":{"title":"preferredForwardBufferDuration","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoController\/preferredForwardBufferDuration","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"광고 영상의 forwardBufferDuration을 설정합니다."},{"text":" ","type":"text"},{"type":"text","text":"cf. https:\/\/developer.apple.com\/documentation\/avfoundation\/avplayeritem\/1643630-preferredforwardbufferduration"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"preferredForwardBufferDuration"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"}],"navigatorTitle":[{"kind":"identifier","text":"preferredForwardBufferDuration"}],"type":"topic","url":"\/documentation\/gfpsdk\/gfpvideocontroller\/preferredforwardbufferduration"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoController":{"url":"\/documentation\/gfpsdk\/gfpvideocontroller","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPVideoController"}],"role":"symbol","abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"GFPVideoController"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoController","title":"GFPVideoController","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"preferredForwardBufferDuration"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"value":[{"text":"preferredForwardBufferDuration","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"assign","kind":"keyword"},{"kind":"text","text":") "},{"text":"NSTimeInterval","preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier"},{"kind":"text","text":" "},{"kind":"identifier","text":"preferredForwardBufferDuration"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoController~1preferredForwardBufferDuration\/title","op":"replace","value":"preferredForwardBufferDuration"},{"value":[{"text":"preferredForwardBufferDuration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoController~1preferredForwardBufferDuration\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoController\/title","value":"GFPVideoController","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoController\/fragments","value":[{"kind":"identifier","text":"GFPVideoController"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoController\/navigatorTitle","value":[{"text":"GFPVideoController","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}