{"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdInfo\/initWithDictionary:skipInfo:needAdChoiceForRender:","interfaceLanguage":"occ"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdInfo"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"role":"symbol","title":"initWithDictionary:skipInfo:needAdChoiceForRender:","externalID":"c:objc(cs)GFPAdInfo(im)initWithDictionary:skipInfo:needAdChoiceForRender:","navigatorTitle":[{"text":"initWithDictionary:skipInfo:needAdChoiceForRender:","kind":"identifier"}],"symbolKind":"method","modules":[{"name":"GFPSDK"}],"roleHeading":"Instance Method","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDictionary:skipInfo:needAdChoiceForRender:"}]},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpadinfo\/initwithdictionary:skipinfo:needadchoiceforrender:"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithDictionary:"},{"kind":"text","text":"("},{"text":"NSDictionary","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDictionary"},{"text":" *) ","kind":"text"},{"text":"adInfoDict","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"skipInfo:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"GFPAdSkipInfo","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdSkipInfo"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"skipInfo"},{"kind":"text","text":" "},{"kind":"identifier","text":"needAdChoiceForRender:"},{"text":"(","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"needAdChoiceForRender","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}],"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdInfo/initWithDictionary:skipInfo:needAdChoiceForRender:":{"title":"initWithDictionary:skipInfo:needAdChoiceForRender:","role":"symbol","kind":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDictionary:skipInfo:needAdChoiceForRender:"}],"navigatorTitle":[{"kind":"identifier","text":"initWithDictionary:skipInfo:needAdChoiceForRender:"}],"abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdInfo\/initWithDictionary:skipInfo:needAdChoiceForRender:","url":"\/documentation\/gfpsdk\/gfpadinfo\/initwithdictionary:skipinfo:needadchoiceforrender:","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdInfo":{"title":"GFPAdInfo","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPAdInfo"}],"navigatorTitle":[{"kind":"identifier","text":"GFPAdInfo"}],"abstract":[{"type":"text","text":"GFPAdInfo"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdInfo","url":"\/documentation\/gfpsdk\/gfpadinfo","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdInfo\/title","op":"replace","value":"GFPAdInfo"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdInfo\/fragments","op":"replace","value":[{"text":"GFPAdInfo","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdInfo\/navigatorTitle","value":[{"kind":"identifier","text":"GFPAdInfo"}],"op":"replace"}]}]}