{"kind":"symbol","metadata":{"navigatorTitle":[{"text":"rewardedAdInfo","kind":"identifier"}],"title":"rewardedAdInfo","fragments":[{"kind":"identifier","text":"rewardedAdInfo"}],"modules":[{"name":"GFPSDK"}],"externalID":"c:objc(cs)GFPAdInfo(py)rewardedAdInfo","role":"symbol","roleHeading":"Instance Property","symbolKind":"property"},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdInfo"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPRewardedAdInfo","text":"GFPRewardedAdInfo"},{"kind":"text","text":" * "},{"text":"rewardedAdInfo","kind":"identifier"},{"kind":"text","text":";"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpadinfo\/rewardedadinfo"]}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdInfo\/rewardedAdInfo"},"sections":[],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdInfo":{"title":"GFPAdInfo","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPAdInfo"}],"navigatorTitle":[{"kind":"identifier","text":"GFPAdInfo"}],"abstract":[{"type":"text","text":"GFPAdInfo"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdInfo","url":"\/documentation\/gfpsdk\/gfpadinfo","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdInfo/rewardedAdInfo":{"title":"rewardedAdInfo","role":"symbol","kind":"symbol","fragments":[{"kind":"identifier","text":"rewardedAdInfo"}],"abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdInfo\/rewardedAdInfo","url":"\/documentation\/gfpsdk\/gfpadinfo\/rewardedadinfo","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdInfo\/title","value":"GFPAdInfo","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdInfo\/fragments","value":[{"kind":"identifier","text":"GFPAdInfo"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdInfo\/navigatorTitle","value":[{"kind":"identifier","text":"GFPAdInfo"}]}]}]}