{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpnativeadapting\/adchoicesdata()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpnativeadapting\/adchoicesdata()"]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/adChoicesData()"},"kind":"symbol","metadata":{"title":"adChoicesData()","modules":[{"name":"GFPSDK"}],"roleHeading":"Instance Method","navigatorTitle":[{"text":"adChoicesData","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"adChoicesData"},{"text":"() -> ","kind":"text"},{"text":"GFPAdChoicesData","preciseIdentifier":"c:objc(cs)GFPAdChoicesData","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"symbolKind":"method","role":"symbol","externalID":"c:objc(pl)GFPNativeAdapting(im)adChoicesData"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"optional"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"adChoicesData","kind":"identifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"GFPAdChoicesData","preciseIdentifier":"c:objc(cs)GFPAdChoicesData","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdChoicesData"},{"kind":"text","text":"?"}]}]}],"sections":[],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdapting":{"abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPNativeAdapting"}],"kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting","navigatorTitle":[{"kind":"identifier","text":"GFPNativeAdapting"}],"title":"GFPNativeAdapting","role":"symbol","url":"\/documentation\/gfpsdk\/gfpnativeadapting"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdapting/adChoicesData()":{"type":"topic","title":"adChoicesData()","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/adChoicesData()","url":"\/documentation\/gfpsdk\/gfpnativeadapting\/adchoicesdata()","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"adChoicesData"},{"kind":"text","text":"() -> "},{"text":"GFPAdChoicesData","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdChoicesData"},{"kind":"text","text":"?"}],"abstract":[],"navigatorTitle":[{"text":"adChoicesData","kind":"identifier"}],"role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdChoicesData":{"navigatorTitle":[{"kind":"identifier","text":"GFPAdChoicesData"}],"title":"GFPAdChoicesData","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdChoicesData","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPAdChoicesData","kind":"identifier"}],"abstract":[],"url":"\/documentation\/gfpsdk\/gfpadchoicesdata","role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"adChoicesData","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"adChoicesData","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdChoicesData","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdChoicesData","text":"GFPAdChoicesData"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"adChoicesData"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdapting\/title","value":"GFPNativeAdapting","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdapting\/fragments","value":[{"text":"GFPNativeAdapting","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"GFPNativeAdapting"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdapting\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdapting~1adChoicesData()\/title","value":"adChoicesData","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"adChoicesData"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdapting~1adChoicesData()\/fragments"},{"value":"GFPAdChoicesData","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdChoicesData\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdChoicesData\/fragments","op":"replace","value":[{"text":"GFPAdChoicesData","kind":"identifier"}]},{"op":"replace","value":[{"text":"GFPAdChoicesData","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdChoicesData\/navigatorTitle"}]}]}