{"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/gfpsdk\/gfpnativeadapting\/dedup"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/dedup"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPWaterfallDedup","text":"GFPWaterfallDedup"},{"text":" *) ","kind":"text"},{"text":"dedup","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]}],"metadata":{"fragments":[{"text":"- ","kind":"text"},{"text":"dedup","kind":"identifier"}],"externalID":"c:objc(pl)GFPNativeAdapting(im)dedup","roleHeading":"Instance Method","symbolKind":"method","role":"symbol","modules":[{"name":"GFPSDK"}],"navigatorTitle":[{"kind":"identifier","text":"dedup"}],"title":"dedup"},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting"]]},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdapting/dedup":{"role":"symbol","kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"dedup","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpnativeadapting\/dedup","navigatorTitle":[{"kind":"identifier","text":"dedup"}],"abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/dedup","title":"dedup","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdapting":{"abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPNativeAdapting"}],"kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting","navigatorTitle":[{"kind":"identifier","text":"GFPNativeAdapting"}],"title":"GFPNativeAdapting","role":"symbol","url":"\/documentation\/gfpsdk\/gfpnativeadapting"}},"variantOverrides":[{"patch":[{"value":"GFPNativeAdapting","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdapting\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdapting\/fragments","op":"replace","value":[{"kind":"identifier","text":"GFPNativeAdapting"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdapting\/navigatorTitle","op":"replace","value":[{"text":"GFPNativeAdapting","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}