{"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting"]]},"metadata":{"roleHeading":"Instance Property","required":true,"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": (any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)GFPNativeAdaptorDelegate","text":"GFPNativeAdaptorDelegate"},{"text":")?","kind":"text"}],"navigatorTitle":[{"text":"delegate","kind":"identifier"}],"symbolKind":"property","modules":[{"name":"GFPSDK"}],"externalID":"c:objc(pl)GFPNativeAdapting(py)delegate","title":"delegate"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"weak","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"text":": (any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)GFPNativeAdaptorDelegate","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdaptorDelegate","text":"GFPNativeAdaptorDelegate","kind":"typeIdentifier"},{"kind":"text","text":")? { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/delegate","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpnativeadapting\/delegate"]},{"paths":["\/documentation\/gfpsdk\/gfpnativeadapting\/delegate"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdaptorDelegate":{"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"GFPNativeAdaptorDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"GFPNativeAdaptorDelegate","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdaptorDelegate","role":"symbol","url":"\/documentation\/gfpsdk\/gfpnativeadaptordelegate","title":"GFPNativeAdaptorDelegate","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdapting":{"abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPNativeAdapting"}],"kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting","navigatorTitle":[{"kind":"identifier","text":"GFPNativeAdapting"}],"title":"GFPNativeAdapting","role":"symbol","url":"\/documentation\/gfpsdk\/gfpnativeadapting"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdapting/delegate":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/delegate","navigatorTitle":[{"text":"delegate","kind":"identifier"}],"required":true,"kind":"symbol","url":"\/documentation\/gfpsdk\/gfpnativeadapting\/delegate","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"delegate","kind":"identifier"},{"text":": (any ","kind":"text"},{"kind":"typeIdentifier","text":"GFPNativeAdaptorDelegate","preciseIdentifier":"c:objc(pl)GFPNativeAdaptorDelegate"},{"text":")?","kind":"text"}],"title":"delegate","abstract":[]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"delegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"delegate","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"weak","kind":"keyword"},{"kind":"text","text":", "},{"text":"readwrite","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:Qoobjc(pl)GFPNativeAdaptorDelegate","text":"id<GFPNativeAdaptorDelegate>","kind":"typeIdentifier"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdaptorDelegate\/title","op":"replace","value":"GFPNativeAdaptorDelegate"},{"value":[{"kind":"identifier","text":"GFPNativeAdaptorDelegate"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdaptorDelegate\/fragments"},{"value":[{"text":"GFPNativeAdaptorDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdaptorDelegate\/navigatorTitle"},{"value":"GFPNativeAdapting","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdapting\/title","op":"replace"},{"value":[{"text":"GFPNativeAdapting","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdapting\/fragments"},{"value":[{"kind":"identifier","text":"GFPNativeAdapting"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdapting\/navigatorTitle","op":"replace"},{"value":"delegate","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdapting~1delegate\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdapting~1delegate\/fragments","value":[{"text":"delegate","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}