{"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdDelegate"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rewardedAd"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"rewardedAd","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"GFPRewardedAd","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAd","preciseIdentifier":"c:objc(cs)GFPRewardedAd"},{"text":"!, ","kind":"text"},{"kind":"externalParam","text":"didCompleteWith"},{"kind":"text","text":" "},{"kind":"internalParam","text":"reward"},{"text":": ","kind":"text"},{"text":"GFPReward","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPReward","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPReward"},{"text":"!)","kind":"text"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/gfpsdk\/gfprewardedaddelegate\/rewardedad(_:didcompletewith:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfprewardedaddelegate\/rewardedad(_:didcompletewith:)"]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdDelegate\/rewardedAd(_:didCompleteWith:)"},"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"rewardedAd"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPRewardedAd","text":"GFPRewardedAd"},{"kind":"text","text":"!, "},{"text":"didCompleteWith","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"GFPReward","preciseIdentifier":"c:objc(cs)GFPReward","kind":"typeIdentifier"},{"kind":"text","text":"!)"}],"navigatorTitle":[{"text":"rewardedAd:didCompleteWithReward:","kind":"identifier"}],"externalID":"c:objc(pl)GFPRewardedAdDelegate(im)rewardedAd:didCompleteWithReward:","role":"symbol","roleHeading":"Instance Method","title":"rewardedAd(_:didCompleteWith:)","required":true,"modules":[{"name":"GFPSDK"}],"symbolKind":"method"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRewardedAdDelegate":{"kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"GFPRewardedAdDelegate","kind":"identifier"}],"title":"GFPRewardedAdDelegate","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdDelegate","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPRewardedAdDelegate"}],"url":"\/documentation\/gfpsdk\/gfprewardedaddelegate"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRewardedAdDelegate/rewardedAd(_:didCompleteWith:)":{"required":true,"url":"\/documentation\/gfpsdk\/gfprewardedaddelegate\/rewardedad(_:didcompletewith:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"rewardedAd","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GFPRewardedAd","preciseIdentifier":"c:objc(cs)GFPRewardedAd"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"didCompleteWith"},{"kind":"text","text":": "},{"text":"GFPReward","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPReward"},{"kind":"text","text":"!)"}],"type":"topic","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdDelegate\/rewardedAd(_:didCompleteWith:)","role":"symbol","navigatorTitle":[{"text":"rewardedAd:didCompleteWithReward:","kind":"identifier"}],"title":"rewardedAd(_:didCompleteWith:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRewardedAd":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAd","url":"\/documentation\/gfpsdk\/gfprewardedad","navigatorTitle":[{"kind":"identifier","text":"GFPRewardedAd"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPRewardedAd","kind":"identifier"}],"kind":"symbol","abstract":[],"type":"topic","title":"GFPRewardedAd","role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPReward":{"kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPReward","url":"\/documentation\/gfpsdk\/gfpreward","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPReward","kind":"identifier"}],"title":"GFPReward","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GFPReward"}],"abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"rewardedAd:didCompleteWithReward:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"rewardedAd:didCompleteWithReward:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"rewardedAd:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"GFPRewardedAd","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPRewardedAd","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAd"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"rewardedAd"},{"kind":"text","text":" "},{"kind":"identifier","text":"didCompleteWithReward:"},{"text":"(","kind":"text"},{"text":"GFPReward","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPReward","preciseIdentifier":"c:objc(cs)GFPReward"},{"text":" *) ","kind":"text"},{"text":"reward","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"GFPRewardedAdDelegate","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdDelegate\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdDelegate\/fragments","value":[{"kind":"identifier","text":"GFPRewardedAdDelegate"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"GFPRewardedAdDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdDelegate~1rewardedAd(_:didCompleteWith:)\/title","value":"rewardedAd:didCompleteWithReward:"},{"value":[{"text":"- ","kind":"text"},{"text":"rewardedAd:didCompleteWithReward:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdDelegate~1rewardedAd(_:didCompleteWith:)\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAd\/title","op":"replace","value":"GFPRewardedAd"},{"value":[{"kind":"identifier","text":"GFPRewardedAd"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAd\/fragments"},{"op":"replace","value":[{"text":"GFPRewardedAd","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAd\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPReward\/title","value":"GFPReward"},{"value":[{"text":"GFPReward","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPReward\/fragments","op":"replace"},{"op":"replace","value":[{"text":"GFPReward","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPReward\/navigatorTitle"}]}]}