{"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdDelegate\/rewardedAdStarted(_:)"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rewardedAdStarted"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"rewardedAd"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAd","text":"GFPRewardedAd","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPRewardedAd"},{"kind":"text","text":"!)"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfprewardedaddelegate\/rewardedadstarted(_:)"]},{"paths":["\/documentation\/gfpsdk\/gfprewardedaddelegate\/rewardedadstarted(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"rewardedAdStarted(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rewardedAdStarted"},{"text":"(","kind":"text"},{"text":"GFPRewardedAd","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPRewardedAd"},{"text":"!)","kind":"text"}],"roleHeading":"Instance Method","role":"symbol","externalID":"c:objc(pl)GFPRewardedAdDelegate(im)rewardedAdStarted:","required":true,"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"rewardedAdStarted:"}],"modules":[{"name":"GFPSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdDelegate"]]},"sections":[],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRewardedAdDelegate":{"kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"GFPRewardedAdDelegate","kind":"identifier"}],"title":"GFPRewardedAdDelegate","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdDelegate","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPRewardedAdDelegate"}],"url":"\/documentation\/gfpsdk\/gfprewardedaddelegate"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRewardedAdDelegate/rewardedAdStarted(_:)":{"type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdDelegate\/rewardedAdStarted(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"rewardedAdStarted","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPRewardedAd","text":"GFPRewardedAd"},{"text":"!)","kind":"text"}],"abstract":[],"url":"\/documentation\/gfpsdk\/gfprewardedaddelegate\/rewardedadstarted(_:)","title":"rewardedAdStarted(_:)","kind":"symbol","required":true,"navigatorTitle":[{"text":"rewardedAdStarted:","kind":"identifier"}],"role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRewardedAd":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAd","url":"\/documentation\/gfpsdk\/gfprewardedad","navigatorTitle":[{"kind":"identifier","text":"GFPRewardedAd"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPRewardedAd","kind":"identifier"}],"kind":"symbol","abstract":[],"type":"topic","title":"GFPRewardedAd","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"rewardedAdStarted:","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rewardedAdStarted:"}]},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"rewardedAdStarted:","kind":"identifier"},{"kind":"text","text":"("},{"text":"GFPRewardedAd","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAd","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPRewardedAd"},{"text":" *) ","kind":"text"},{"text":"rewardedAd","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"op":"replace","value":"GFPRewardedAdDelegate","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdDelegate\/title"},{"value":[{"kind":"identifier","text":"GFPRewardedAdDelegate"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdDelegate\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdDelegate\/navigatorTitle","value":[{"text":"GFPRewardedAdDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdDelegate~1rewardedAdStarted(_:)\/title","value":"rewardedAdStarted:"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdDelegate~1rewardedAdStarted(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"rewardedAdStarted:","kind":"identifier"}]},{"op":"replace","value":"GFPRewardedAd","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAd\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAd\/fragments","value":[{"text":"GFPRewardedAd","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAd\/navigatorTitle","value":[{"kind":"identifier","text":"GFPRewardedAd"}],"op":"replace"}]}]}