{"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdDelegate"]]},"metadata":{"required":true,"symbolKind":"method","title":"rewardedAdDidPresentDefault(inAppBrowser:)","modules":[{"name":"GFPSDK"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"rewardedAdDidPresentDefault","kind":"identifier"},{"text":"(","kind":"text"},{"text":"inAppBrowser","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)GFPRewardedAd","text":"GFPRewardedAd","kind":"typeIdentifier"},{"kind":"text","text":"!)"}],"roleHeading":"Instance Method","navigatorTitle":[{"text":"rewardedAdDidPresentDefaultInAppBrowser:","kind":"identifier"}],"externalID":"c:objc(pl)GFPRewardedAdDelegate(im)rewardedAdDidPresentDefaultInAppBrowser:"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"optional","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rewardedAdDidPresentDefault"},{"kind":"text","text":"("},{"text":"inAppBrowser","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"rewardedAd","kind":"internalParam"},{"kind":"text","text":": "},{"text":"GFPRewardedAd","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAd","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPRewardedAd"},{"kind":"text","text":"!)"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdDelegate\/rewardedAdDidPresentDefault(inAppBrowser:)","interfaceLanguage":"swift"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfprewardedaddelegate\/rewardedaddidpresentdefault(inappbrowser:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfprewardedaddelegate\/rewardedaddidpresentdefault(inappbrowser:)"]}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRewardedAdDelegate":{"kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"GFPRewardedAdDelegate","kind":"identifier"}],"title":"GFPRewardedAdDelegate","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdDelegate","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPRewardedAdDelegate"}],"url":"\/documentation\/gfpsdk\/gfprewardedaddelegate"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRewardedAd":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAd","url":"\/documentation\/gfpsdk\/gfprewardedad","navigatorTitle":[{"kind":"identifier","text":"GFPRewardedAd"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPRewardedAd","kind":"identifier"}],"kind":"symbol","abstract":[],"type":"topic","title":"GFPRewardedAd","role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRewardedAdDelegate/rewardedAdDidPresentDefault(inAppBrowser:)":{"url":"\/documentation\/gfpsdk\/gfprewardedaddelegate\/rewardedaddidpresentdefault(inappbrowser:)","title":"rewardedAdDidPresentDefault(inAppBrowser:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"rewardedAdDidPresentDefault","kind":"identifier"},{"text":"(","kind":"text"},{"text":"inAppBrowser","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPRewardedAd","text":"GFPRewardedAd"},{"kind":"text","text":"!)"}],"navigatorTitle":[{"kind":"identifier","text":"rewardedAdDidPresentDefaultInAppBrowser:"}],"abstract":[],"kind":"symbol","type":"topic","required":true,"role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdDelegate\/rewardedAdDidPresentDefault(inAppBrowser:)"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"rewardedAdDidPresentDefaultInAppBrowser:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"rewardedAdDidPresentDefaultInAppBrowser:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"rewardedAdDidPresentDefaultInAppBrowser:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPRewardedAd","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAd","text":"GFPRewardedAd","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"rewardedAd"},{"kind":"text","text":";"}]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdDelegate\/title","value":"GFPRewardedAdDelegate"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdDelegate\/fragments","op":"replace","value":[{"text":"GFPRewardedAdDelegate","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"GFPRewardedAdDelegate"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdDelegate\/navigatorTitle"},{"op":"replace","value":"GFPRewardedAd","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAd\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAd\/fragments","value":[{"text":"GFPRewardedAd","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAd\/navigatorTitle","value":[{"text":"GFPRewardedAd","kind":"identifier"}]},{"op":"replace","value":"rewardedAdDidPresentDefaultInAppBrowser:","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdDelegate~1rewardedAdDidPresentDefault(inAppBrowser:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"rewardedAdDidPresentDefaultInAppBrowser:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdDelegate~1rewardedAdDidPresentDefault(inAppBrowser:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}