{"abstract":[{"text":"Rich광고 비디오 정지 시 호출됩니다. player pause 직전에 호출됩니다.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"재생 중 메모리 해제 시에는 호출되지 않습니다."}],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeVideoEventDelegate"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpnativevideoeventdelegate\/nativead(_:richvideowillstopwith:)"]},{"paths":["\/documentation\/gfpsdk\/gfpnativevideoeventdelegate\/nativead(_:richvideowillstopwith:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"platforms":[{"unavailable":false,"beta":false,"name":"iOS","deprecated":false,"introducedAt":"2.0"},{"name":"iPadOS","unavailable":false,"deprecated":false,"beta":false,"introducedAt":"2.0"},{"unavailable":false,"beta":false,"name":"Mac Catalyst","introducedAt":"2.0","deprecated":false}],"symbolKind":"method","required":true,"role":"symbol","title":"nativeAd(_:richVideoWillStopWith:)","modules":[{"name":"GFPSDK"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"nativeAd"},{"text":"(","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"richVideoWillStopWith"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":")"}],"externalID":"c:objc(pl)GFPNativeVideoEventDelegate(im)nativeAd:richVideoWillStopWith:","navigatorTitle":[{"text":"nativeAd:richVideoWillStopWith:","kind":"identifier"}],"roleHeading":"Instance Method"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeVideoEventDelegate\/nativeAd(_:richVideoWillStopWith:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"nativeAd"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"nativeAd","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"richVideoWillStopWith","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"isMuted"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"네이티브 광고 객체"}]}],"name":"nativeAd"},{"content":[{"inlineContent":[{"text":"현재 비디오 Mute여부","type":"text"}],"type":"paragraph"}],"name":"isMuted"}],"kind":"parameters"}],"sections":[],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeVideoEventDelegate":{"role":"symbol","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeVideoEventDelegate","type":"topic","kind":"symbol","url":"\/documentation\/gfpsdk\/gfpnativevideoeventdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPNativeVideoEventDelegate","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"GFPNativeVideoEventDelegate"}],"title":"GFPNativeVideoEventDelegate"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeVideoEventDelegate/nativeAd(_:richVideoWillStopWith:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"nativeAd","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"},{"kind":"text","text":", "},{"text":"richVideoWillStopWith","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"title":"nativeAd(_:richVideoWillStopWith:)","navigatorTitle":[{"text":"nativeAd:richVideoWillStopWith:","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpnativevideoeventdelegate\/nativead(_:richvideowillstopwith:)","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeVideoEventDelegate\/nativeAd(_:richVideoWillStopWith:)","role":"symbol","type":"topic","kind":"symbol","abstract":[{"text":"Rich광고 비디오 정지 시 호출됩니다. player pause 직전에 호출됩니다.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"재생 중 메모리 해제 시에는 호출되지 않습니다."}],"required":true}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"nativeAd:richVideoWillStopWith:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"nativeAd:richVideoWillStopWith:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"nativeAd:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"nativeAd"},{"kind":"text","text":" "},{"kind":"identifier","text":"richVideoWillStopWith:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"isMuted"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"네이티브 광고 객체","type":"text"}]}],"name":"nativeAd"},{"name":"isMuted","content":[{"type":"paragraph","inlineContent":[{"text":"현재 비디오 Mute여부","type":"text"}]}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeVideoEventDelegate\/title","value":"GFPNativeVideoEventDelegate","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeVideoEventDelegate\/fragments","value":[{"text":"GFPNativeVideoEventDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeVideoEventDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"GFPNativeVideoEventDelegate"}],"op":"replace"},{"op":"replace","value":"nativeAd:richVideoWillStopWith:","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeVideoEventDelegate~1nativeAd(_:richVideoWillStopWith:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"nativeAd:richVideoWillStopWith:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeVideoEventDelegate~1nativeAd(_:richVideoWillStopWith:)\/fragments","op":"replace"}]}]}