{"abstract":[{"type":"text","text":"Rich광고 비디오 정지 시 호출됩니다. player pause 후 스테이터스 변경 시, 메모리 해제 시 호출됩니다."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"nativeAd","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"nativeAd"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"},{"kind":"text","text":", "},{"text":"richVideoDidStopWith","kind":"externalParam"},{"kind":"text","text":" "},{"text":"isMuted","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"네이티브 광고 객체","type":"text"}]}],"name":"nativeAd"},{"name":"isMuted","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"현재 비디오 Mute여부"}]}]}]}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpnativevideoeventdelegate\/nativead(_:richvideodidstopwith:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpnativevideoeventdelegate\/nativead(_:richvideodidstopwith:)"]}],"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeVideoEventDelegate\/nativeAd(_:richVideoDidStopWith:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeVideoEventDelegate"]]},"metadata":{"externalID":"c:objc(pl)GFPNativeVideoEventDelegate(im)nativeAd:richVideoDidStopWith:","required":true,"navigatorTitle":[{"kind":"identifier","text":"nativeAd:richVideoDidStopWith:"}],"title":"nativeAd(_:richVideoDidStopWith:)","role":"symbol","symbolKind":"method","roleHeading":"Instance Method","platforms":[{"unavailable":false,"deprecated":false,"beta":false,"introducedAt":"2.0","name":"iOS"},{"introducedAt":"2.0","unavailable":false,"beta":false,"name":"iPadOS","deprecated":false},{"beta":false,"deprecated":false,"name":"Mac Catalyst","introducedAt":"2.0","unavailable":false}],"modules":[{"name":"GFPSDK"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"nativeAd","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"},{"text":", ","kind":"text"},{"text":"richVideoDidStopWith","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeVideoEventDelegate":{"role":"symbol","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeVideoEventDelegate","type":"topic","kind":"symbol","url":"\/documentation\/gfpsdk\/gfpnativevideoeventdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPNativeVideoEventDelegate","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"GFPNativeVideoEventDelegate"}],"title":"GFPNativeVideoEventDelegate"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeVideoEventDelegate/nativeAd(_:richVideoDidStopWith:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"nativeAd"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"},{"text":", ","kind":"text"},{"text":"richVideoDidStopWith","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":")"}],"title":"nativeAd(_:richVideoDidStopWith:)","navigatorTitle":[{"text":"nativeAd:richVideoDidStopWith:","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpnativevideoeventdelegate\/nativead(_:richvideodidstopwith:)","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeVideoEventDelegate\/nativeAd(_:richVideoDidStopWith:)","role":"symbol","type":"topic","kind":"symbol","abstract":[{"text":"Rich광고 비디오 정지 시 호출됩니다. player pause 후 스테이터스 변경 시, 메모리 해제 시 호출됩니다.","type":"text"}],"required":true}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"nativeAd:richVideoDidStopWith:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"nativeAd:richVideoDidStopWith:"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"nativeAd:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"},{"kind":"text","text":" *) "},{"text":"nativeAd","kind":"internalParam"},{"kind":"text","text":" "},{"text":"richVideoDidStopWith:","kind":"identifier"},{"kind":"text","text":"("},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"isMuted","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"네이티브 광고 객체"}]}],"name":"nativeAd"},{"content":[{"inlineContent":[{"text":"현재 비디오 Mute여부","type":"text"}],"type":"paragraph"}],"name":"isMuted"}],"kind":"parameters"},"path":"\/primaryContentSections\/1"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeVideoEventDelegate\/title","value":"GFPNativeVideoEventDelegate"},{"op":"replace","value":[{"kind":"identifier","text":"GFPNativeVideoEventDelegate"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeVideoEventDelegate\/fragments"},{"value":[{"kind":"identifier","text":"GFPNativeVideoEventDelegate"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeVideoEventDelegate\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeVideoEventDelegate~1nativeAd(_:richVideoDidStopWith:)\/title","op":"replace","value":"nativeAd:richVideoDidStopWith:"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeVideoEventDelegate~1nativeAd(_:richVideoDidStopWith:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"nativeAd:richVideoDidStopWith:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}