{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeVideoEventDelegate\/nativeAd(_:richVideoWillPlayWith:)"},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeVideoEventDelegate"]]},"metadata":{"externalID":"c:objc(pl)GFPNativeVideoEventDelegate(im)nativeAd:richVideoWillPlayWith:","platforms":[{"unavailable":false,"introducedAt":"2.0","name":"iOS","deprecated":false,"beta":false},{"deprecated":false,"unavailable":false,"name":"iPadOS","beta":false,"introducedAt":"2.0"},{"deprecated":false,"name":"Mac Catalyst","introducedAt":"2.0","beta":false,"unavailable":false}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"nativeAd"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"},{"kind":"text","text":", "},{"text":"richVideoWillPlayWith","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"nativeAd:richVideoWillPlayWith:"}],"modules":[{"name":"GFPSDK"}],"symbolKind":"method","role":"symbol","title":"nativeAd(_:richVideoWillPlayWith:)","roleHeading":"Instance Method"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"optional","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"nativeAd","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"nativeAd"},{"text":": ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"richVideoWillPlayWith"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"isMuted"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"nativeAd","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"네이티브 광고 객체"}]}]},{"name":"isMuted","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"현재 비디오 Mute여부"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Rich광고 비디오 재생 시 호출됩니다. player start 직전에 호출됩니다."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpnativevideoeventdelegate\/nativead(_:richvideowillplaywith:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpnativevideoeventdelegate\/nativead(_:richvideowillplaywith:)"]}],"sections":[],"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeVideoEventDelegate/nativeAd(_:richVideoWillPlayWith:)":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"nativeAd:richVideoWillPlayWith:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nativeAd","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"richVideoWillPlayWith"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeVideoEventDelegate\/nativeAd(_:richVideoWillPlayWith:)","type":"topic","abstract":[{"type":"text","text":"Rich광고 비디오 재생 시 호출됩니다. player start 직전에 호출됩니다."}],"url":"\/documentation\/gfpsdk\/gfpnativevideoeventdelegate\/nativead(_:richvideowillplaywith:)","kind":"symbol","title":"nativeAd(_:richVideoWillPlayWith:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeVideoEventDelegate":{"role":"symbol","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeVideoEventDelegate","type":"topic","kind":"symbol","url":"\/documentation\/gfpsdk\/gfpnativevideoeventdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPNativeVideoEventDelegate","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"GFPNativeVideoEventDelegate"}],"title":"GFPNativeVideoEventDelegate"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"nativeAd:richVideoWillPlayWith:","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"nativeAd:richVideoWillPlayWith:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"nativeAd:"},{"text":"(","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"},{"text":" *) ","kind":"text"},{"text":"nativeAd","kind":"internalParam"},{"kind":"text","text":" "},{"text":"richVideoWillPlayWith:","kind":"identifier"},{"kind":"text","text":"("},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"isMuted","kind":"internalParam"},{"kind":"text","text":";"}]}]}},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"nativeAd","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"네이티브 광고 객체"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"현재 비디오 Mute여부"}],"type":"paragraph"}],"name":"isMuted"}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeVideoEventDelegate~1nativeAd(_:richVideoWillPlayWith:)\/title","value":"nativeAd:richVideoWillPlayWith:"},{"value":[{"kind":"text","text":"- "},{"text":"nativeAd:richVideoWillPlayWith:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeVideoEventDelegate~1nativeAd(_:richVideoWillPlayWith:)\/fragments","op":"replace"},{"value":"GFPNativeVideoEventDelegate","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeVideoEventDelegate\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeVideoEventDelegate\/fragments","value":[{"kind":"identifier","text":"GFPNativeVideoEventDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeVideoEventDelegate\/navigatorTitle","value":[{"text":"GFPNativeVideoEventDelegate","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}