{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"optional"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"nativeAd"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"nativeAd","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"},{"kind":"text","text":", "},{"kind":"externalParam","text":"richVideoMuteChanged"},{"kind":"text","text":" "},{"text":"isMuted","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"네이티브 광고 객체","type":"text"}]}],"name":"nativeAd"},{"name":"isMuted","content":[{"inlineContent":[{"text":"Mute 여부 상태","type":"text"}],"type":"paragraph"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpnativevideoeventdelegate\/nativead(_:richvideomutechanged:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpnativevideoeventdelegate\/nativead(_:richvideomutechanged:)"]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeVideoEventDelegate"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"kind":"symbol","abstract":[{"text":"Rich광고 비디오 플레이어에 mute 셋팅 시 호출됩니다.","type":"text"}],"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeVideoEventDelegate\/nativeAd(_:richVideoMuteChanged:)","interfaceLanguage":"swift"},"metadata":{"externalID":"c:objc(pl)GFPNativeVideoEventDelegate(im)nativeAd:richVideoMuteChanged:","required":true,"navigatorTitle":[{"text":"nativeAd:richVideoMuteChanged:","kind":"identifier"}],"title":"nativeAd(_:richVideoMuteChanged:)","role":"symbol","symbolKind":"method","roleHeading":"Instance Method","platforms":[{"deprecated":false,"beta":false,"introducedAt":"2.0","name":"iOS","unavailable":false},{"deprecated":false,"unavailable":false,"beta":false,"introducedAt":"2.0","name":"iPadOS"},{"introducedAt":"2.0","unavailable":false,"beta":false,"name":"Mac Catalyst","deprecated":false}],"modules":[{"name":"GFPSDK"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"nativeAd"},{"text":"(","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"richVideoMuteChanged"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}]},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeVideoEventDelegate/nativeAd(_:richVideoMuteChanged:)":{"url":"\/documentation\/gfpsdk\/gfpnativevideoeventdelegate\/nativead(_:richvideomutechanged:)","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeVideoEventDelegate\/nativeAd(_:richVideoMuteChanged:)","type":"topic","required":true,"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"nativeAd"},{"kind":"text","text":"("},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"richVideoMuteChanged"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"abstract":[{"text":"Rich광고 비디오 플레이어에 mute 셋팅 시 호출됩니다.","type":"text"}],"navigatorTitle":[{"text":"nativeAd:richVideoMuteChanged:","kind":"identifier"}],"kind":"symbol","title":"nativeAd(_:richVideoMuteChanged:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeVideoEventDelegate":{"role":"symbol","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeVideoEventDelegate","type":"topic","kind":"symbol","url":"\/documentation\/gfpsdk\/gfpnativevideoeventdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPNativeVideoEventDelegate","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"GFPNativeVideoEventDelegate"}],"title":"GFPNativeVideoEventDelegate"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"nativeAd:richVideoMuteChanged:","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"kind":"text","text":"- "},{"text":"nativeAd:richVideoMuteChanged:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"text":"nativeAd:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"},{"text":" *) ","kind":"text"},{"text":"nativeAd","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"richVideoMuteChanged:","kind":"identifier"},{"kind":"text","text":"("},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"isMuted"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":{"parameters":[{"name":"nativeAd","content":[{"inlineContent":[{"type":"text","text":"네이티브 광고 객체"}],"type":"paragraph"}]},{"name":"isMuted","content":[{"inlineContent":[{"text":"Mute 여부 상태","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},"op":"replace","path":"\/primaryContentSections\/1"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeVideoEventDelegate~1nativeAd(_:richVideoMuteChanged:)\/title","value":"nativeAd:richVideoMuteChanged:","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeVideoEventDelegate~1nativeAd(_:richVideoMuteChanged:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"nativeAd:richVideoMuteChanged:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeVideoEventDelegate\/title","value":"GFPNativeVideoEventDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeVideoEventDelegate\/fragments","value":[{"kind":"identifier","text":"GFPNativeVideoEventDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeVideoEventDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"GFPNativeVideoEventDelegate"}]}]}]}