{"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdRenderingSetting"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bitrateKbps"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"languages":["swift"]}]},{"content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"type":"paragraph","inlineContent":[{"text":"기본값(GFPVideoAdRenderingSettingAutodetectBitrate)인 경우, WIFI 사용중에는 최대, Cellular 환경에서는 최소 bitrate 영샹이 재생됩니다.","type":"text"}]}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpvideoadrenderingsetting\/bitratekbps"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpvideoadrenderingsetting\/bitratekbps"]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdRenderingSetting\/bitrateKbps"},"abstract":[{"text":"광고영상의 최대 bitrate (kbit\/sec)","type":"text"},{"type":"text","text":" "},{"text":"입력값 보다 낮은 bitrate 광고영상 중 가장 높은 bitrate 영샹이 채택되며,","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"입력값 보다 낮은 bitrate 영상이 없는 경우 가장 가까운 bitrate 영샹이 재생됩니다."}],"metadata":{"role":"symbol","modules":[{"name":"GFPSDK"}],"externalID":"c:@M@GFPSDK@objc(cs)GFPVideoAdRenderingSetting(py)bitrateKbps","symbolKind":"property","title":"bitrateKbps","navigatorTitle":[{"text":"bitrateKbps","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bitrateKbps"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"roleHeading":"Instance Property"},"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdRenderingSetting/bitrateKbps":{"role":"symbol","abstract":[{"text":"광고영상의 최대 bitrate (kbit\/sec)","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"입력값 보다 낮은 bitrate 광고영상 중 가장 높은 bitrate 영샹이 채택되며,"},{"text":" ","type":"text"},{"type":"text","text":"입력값 보다 낮은 bitrate 영상이 없는 경우 가장 가까운 bitrate 영샹이 재생됩니다."}],"title":"bitrateKbps","navigatorTitle":[{"text":"bitrateKbps","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bitrateKbps","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"url":"\/documentation\/gfpsdk\/gfpvideoadrenderingsetting\/bitratekbps","type":"topic","kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdRenderingSetting\/bitrateKbps"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdRenderingSetting":{"type":"topic","abstract":[],"kind":"symbol","navigatorTitle":[{"text":"GFPVideoAdRenderingSetting","kind":"identifier"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPVideoAdRenderingSetting"}],"title":"GFPVideoAdRenderingSetting","url":"\/documentation\/gfpsdk\/gfpvideoadrenderingsetting","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdRenderingSetting"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"bitrateKbps","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"bitrateKbps","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"bitrateKbps","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"value":"bitrateKbps","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdRenderingSetting~1bitrateKbps\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdRenderingSetting~1bitrateKbps\/fragments","value":[{"text":"bitrateKbps","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"GFPVideoAdRenderingSetting","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdRenderingSetting\/title"},{"value":[{"kind":"identifier","text":"GFPVideoAdRenderingSetting"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdRenderingSetting\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdRenderingSetting\/navigatorTitle","value":[{"kind":"identifier","text":"GFPVideoAdRenderingSetting"}]}]}]}