{"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdRenderingSetting"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPVideoAdRenderingSettingDefaultStartTimeout"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"}],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdRenderingSetting\/GFPVideoAdRenderingSettingDefaultStartTimeout","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"GFPSDK"}],"symbolKind":"property","navigatorTitle":[{"text":"GFPVideoAdRenderingSettingDefaultStartTimeout","kind":"identifier"}],"title":"GFPVideoAdRenderingSettingDefaultStartTimeout","roleHeading":"Type Property","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"GFPVideoAdRenderingSettingDefaultStartTimeout","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"}],"externalID":"c:@M@GFPSDK@objc(cs)GFPVideoAdRenderingSetting(cpy)GFPVideoAdRenderingSettingDefaultStartTimeout","role":"symbol"},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","variants":[{"paths":["\/documentation\/gfpsdk\/gfpvideoadrenderingsetting\/gfpvideoadrenderingsettingdefaultstarttimeout"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpvideoadrenderingsetting\/gfpvideoadrenderingsettingdefaultstarttimeout"]}],"sections":[],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdRenderingSetting":{"type":"topic","abstract":[],"kind":"symbol","navigatorTitle":[{"text":"GFPVideoAdRenderingSetting","kind":"identifier"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPVideoAdRenderingSetting"}],"title":"GFPVideoAdRenderingSetting","url":"\/documentation\/gfpsdk\/gfpvideoadrenderingsetting","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdRenderingSetting"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdRenderingSetting/GFPVideoAdRenderingSettingDefaultStartTimeout":{"navigatorTitle":[{"kind":"identifier","text":"GFPVideoAdRenderingSettingDefaultStartTimeout"}],"type":"topic","title":"GFPVideoAdRenderingSettingDefaultStartTimeout","kind":"symbol","url":"\/documentation\/gfpsdk\/gfpvideoadrenderingsetting\/gfpvideoadrenderingsettingdefaultstarttimeout","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdRenderingSetting\/GFPVideoAdRenderingSettingDefaultStartTimeout","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPVideoAdRenderingSettingDefaultStartTimeout","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"TimeInterval"}],"role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Type Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"GFPVideoAdRenderingSettingDefaultStartTimeout","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GFPVideoAdRenderingSettingDefaultStartTimeout"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"NSTimeInterval","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"GFPVideoAdRenderingSettingDefaultStartTimeout","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"value":"GFPVideoAdRenderingSetting","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdRenderingSetting\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdRenderingSetting\/fragments","value":[{"kind":"identifier","text":"GFPVideoAdRenderingSetting"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdRenderingSetting\/navigatorTitle","value":[{"kind":"identifier","text":"GFPVideoAdRenderingSetting"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdRenderingSetting~1GFPVideoAdRenderingSettingDefaultStartTimeout\/title","value":"GFPVideoAdRenderingSettingDefaultStartTimeout"},{"op":"replace","value":[{"kind":"identifier","text":"GFPVideoAdRenderingSettingDefaultStartTimeout"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdRenderingSetting~1GFPVideoAdRenderingSettingDefaultStartTimeout\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}