{"kind":"symbol","abstract":[{"type":"text","text":"광고 UI 컴포넌트를 그릴 때 기준을 설정합니다. (기본값은 false)"},{"text":" ","type":"text"},{"text":"false: GFPVideoAdScheduleManager.videoView 혹은 GFPVideoAdmanager.videoView 의 너비에 따라 컴포넌트를 그림.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"true: 광고 영상의 실제 width 에 따라 컴포넌트를 그림."}],"metadata":{"symbolKind":"property","roleHeading":"Instance Property","navigatorTitle":[{"text":"isPreferContentWidthUI","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isPreferContentWidthUI"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"externalID":"c:@M@GFPSDK@objc(cs)GFPVideoAdRenderingSetting(py)isPreferContentWidthUI","role":"symbol","title":"isPreferContentWidthUI","modules":[{"name":"GFPSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdRenderingSetting"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpvideoadrenderingsetting\/isprefercontentwidthui"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpvideoadrenderingsetting\/isprefercontentwidthui"]}],"sections":[],"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdRenderingSetting\/isPreferContentWidthUI","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"isPreferContentWidthUI","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]}],"kind":"declarations"}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdRenderingSetting/isPreferContentWidthUI":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"isPreferContentWidthUI","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"kind":"identifier","text":"isPreferContentWidthUI"}],"type":"topic","url":"\/documentation\/gfpsdk\/gfpvideoadrenderingsetting\/isprefercontentwidthui","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdRenderingSetting\/isPreferContentWidthUI","abstract":[{"text":"광고 UI 컴포넌트를 그릴 때 기준을 설정합니다. (기본값은 false)","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"false: GFPVideoAdScheduleManager.videoView 혹은 GFPVideoAdmanager.videoView 의 너비에 따라 컴포넌트를 그림."},{"type":"text","text":" "},{"type":"text","text":"true: 광고 영상의 실제 width 에 따라 컴포넌트를 그림."}],"title":"isPreferContentWidthUI","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdRenderingSetting":{"type":"topic","abstract":[],"kind":"symbol","navigatorTitle":[{"text":"GFPVideoAdRenderingSetting","kind":"identifier"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPVideoAdRenderingSetting"}],"title":"GFPVideoAdRenderingSetting","url":"\/documentation\/gfpsdk\/gfpvideoadrenderingsetting","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdRenderingSetting"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"isPreferContentWidthUI"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"isPreferContentWidthUI"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isPreferContentWidthUI"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"isPreferContentWidthUI","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdRenderingSetting~1isPreferContentWidthUI\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdRenderingSetting~1isPreferContentWidthUI\/fragments","op":"replace","value":[{"text":"isPreferContentWidthUI","kind":"identifier"}]},{"value":"GFPVideoAdRenderingSetting","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdRenderingSetting\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdRenderingSetting\/fragments","value":[{"text":"GFPVideoAdRenderingSetting","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdRenderingSetting\/navigatorTitle","op":"replace","value":[{"text":"GFPVideoAdRenderingSetting","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}