{"variants":[{"paths":["\/documentation\/gfpsdk\/gfpnativeadaptordelegate\/nativeadwasclicked(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpnativeadaptordelegate\/nativeadwasclicked(_:)"]}],"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdaptorDelegate\/nativeAdWasClicked(_:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"modules":[{"name":"GFPSDK"}],"role":"symbol","symbolKind":"method","title":"nativeAdWasClicked(_:)","navigatorTitle":[{"kind":"identifier","text":"nativeAdWasClicked:"}],"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"nativeAdWasClicked"},{"text":"(any ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPAdAdaptor","kind":"typeIdentifier","text":"GFPAdAdaptor"},{"kind":"text","text":" & "},{"text":"GFPNativeAdapting","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)GFPNativeAdapting"},{"text":")","kind":"text"}],"externalID":"c:objc(pl)GFPNativeAdaptorDelegate(im)nativeAdWasClicked:","required":true},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"nativeAdWasClicked"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"nativeAdaptor","kind":"internalParam"},{"kind":"text","text":": any "},{"preciseIdentifier":"c:objc(cs)GFPAdAdaptor","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAdaptor","text":"GFPAdAdaptor"},{"kind":"text","text":" & "},{"preciseIdentifier":"c:objc(pl)GFPNativeAdapting","text":"GFPNativeAdapting","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdaptorDelegate"]]},"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdapting":{"abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPNativeAdapting"}],"kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting","navigatorTitle":[{"kind":"identifier","text":"GFPNativeAdapting"}],"title":"GFPNativeAdapting","role":"symbol","url":"\/documentation\/gfpsdk\/gfpnativeadapting"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdAdaptor":{"navigatorTitle":[{"kind":"identifier","text":"GFPAdAdaptor"}],"title":"GFPAdAdaptor","url":"\/documentation\/gfpsdk\/gfpadadaptor","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAdaptor","abstract":[],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPAdAdaptor"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdaptorDelegate/nativeAdWasClicked(_:)":{"title":"nativeAdWasClicked(_:)","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdaptorDelegate\/nativeAdWasClicked(_:)","type":"topic","url":"\/documentation\/gfpsdk\/gfpnativeadaptordelegate\/nativeadwasclicked(_:)","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"nativeAdWasClicked"},{"kind":"text","text":"(any "},{"kind":"typeIdentifier","text":"GFPAdAdaptor","preciseIdentifier":"c:objc(cs)GFPAdAdaptor"},{"kind":"text","text":" & "},{"preciseIdentifier":"c:objc(pl)GFPNativeAdapting","kind":"typeIdentifier","text":"GFPNativeAdapting"},{"text":")","kind":"text"}],"kind":"symbol","navigatorTitle":[{"text":"nativeAdWasClicked:","kind":"identifier"}],"required":true,"role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdaptorDelegate":{"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"GFPNativeAdaptorDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"GFPNativeAdaptorDelegate","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdaptorDelegate","role":"symbol","url":"\/documentation\/gfpsdk\/gfpnativeadaptordelegate","title":"GFPNativeAdaptorDelegate","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"nativeAdWasClicked:","op":"replace","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"nativeAdWasClicked:"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"nativeAdWasClicked:"},{"kind":"text","text":"("},{"text":"GFPAdAdaptor<GFPNativeAdapting>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)GFPAdAdaptorobjc(pl)GFPNativeAdapting"},{"text":" *) ","kind":"text"},{"text":"nativeAdaptor","kind":"internalParam"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"value":"GFPNativeAdapting","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdapting\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdapting\/fragments","value":[{"kind":"identifier","text":"GFPNativeAdapting"}],"op":"replace"},{"value":[{"text":"GFPNativeAdapting","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdapting\/navigatorTitle","op":"replace"},{"op":"replace","value":"GFPAdAdaptor","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdaptor\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdaptor\/fragments","value":[{"kind":"identifier","text":"GFPAdAdaptor"}]},{"value":[{"kind":"identifier","text":"GFPAdAdaptor"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdaptor\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdaptorDelegate~1nativeAdWasClicked(_:)\/title","op":"replace","value":"nativeAdWasClicked:"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdaptorDelegate~1nativeAdWasClicked(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"nativeAdWasClicked:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdaptorDelegate\/title","value":"GFPNativeAdaptorDelegate"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdaptorDelegate\/fragments","value":[{"text":"GFPNativeAdaptorDelegate","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdaptorDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"GFPNativeAdaptorDelegate"}]}]}]}