{"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdaptorDelegate"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"nativeAdAdaptor","kind":"identifier"},{"text":"(any ","kind":"text"},{"text":"GFPAdAdaptor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdAdaptor"},{"text":" & ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)GFPNativeAdapting","text":"GFPNativeAdapting"},{"kind":"text","text":", "},{"text":"didChangeUserInterest","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":")"}],"roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(pl)GFPNativeAdaptorDelegate(im)nativeAdAdaptor:didChangeUserInterest:","navigatorTitle":[{"kind":"identifier","text":"nativeAdAdaptor:didChangeUserInterest:"}],"required":true,"modules":[{"name":"GFPSDK"}],"title":"nativeAdAdaptor(_:didChangeUserInterest:)"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"nativeAdAdaptor"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"nativeAdAdaptor"},{"text":": any ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPAdAdaptor","text":"GFPAdAdaptor","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAdaptor"},{"text":" & ","kind":"text"},{"text":"GFPNativeAdapting","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)GFPNativeAdapting","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting"},{"text":", ","kind":"text"},{"text":"didChangeUserInterest","kind":"externalParam"},{"kind":"text","text":" "},{"text":"userInterest","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdaptorDelegate\/nativeAdAdaptor(_:didChangeUserInterest:)"},"variants":[{"paths":["\/documentation\/gfpsdk\/gfpnativeadaptordelegate\/nativeadadaptor(_:didchangeuserinterest:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gfpsdk\/gfpnativeadaptordelegate\/nativeadadaptor(_:didchangeuserinterest:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdaptorDelegate/nativeAdAdaptor(_:didChangeUserInterest:)":{"type":"topic","abstract":[],"required":true,"role":"symbol","title":"nativeAdAdaptor(_:didChangeUserInterest:)","kind":"symbol","url":"\/documentation\/gfpsdk\/gfpnativeadaptordelegate\/nativeadadaptor(_:didchangeuserinterest:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"nativeAdAdaptor","kind":"identifier"},{"text":"(any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdAdaptor","text":"GFPAdAdaptor"},{"text":" & ","kind":"text"},{"preciseIdentifier":"c:objc(pl)GFPNativeAdapting","kind":"typeIdentifier","text":"GFPNativeAdapting"},{"kind":"text","text":", "},{"text":"didChangeUserInterest","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"nativeAdAdaptor:didChangeUserInterest:","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdaptorDelegate\/nativeAdAdaptor(_:didChangeUserInterest:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdapting":{"abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPNativeAdapting"}],"kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting","navigatorTitle":[{"kind":"identifier","text":"GFPNativeAdapting"}],"title":"GFPNativeAdapting","role":"symbol","url":"\/documentation\/gfpsdk\/gfpnativeadapting"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdAdaptor":{"navigatorTitle":[{"kind":"identifier","text":"GFPAdAdaptor"}],"title":"GFPAdAdaptor","url":"\/documentation\/gfpsdk\/gfpadadaptor","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAdaptor","abstract":[],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPAdAdaptor"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdaptorDelegate":{"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"GFPNativeAdaptorDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"GFPNativeAdaptorDelegate","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdaptorDelegate","role":"symbol","url":"\/documentation\/gfpsdk\/gfpnativeadaptordelegate","title":"GFPNativeAdaptorDelegate","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"nativeAdAdaptor:didChangeUserInterest:","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"nativeAdAdaptor:didChangeUserInterest:"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"text":"nativeAdAdaptor:","kind":"identifier"},{"kind":"text","text":"("},{"text":"GFPAdAdaptor<GFPNativeAdapting>","preciseIdentifier":"c:Q$objc(cs)GFPAdAdaptorobjc(pl)GFPNativeAdapting","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"nativeAdAdaptor","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didChangeUserInterest:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"userInterest"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"op":"replace","value":"nativeAdAdaptor:didChangeUserInterest:","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdaptorDelegate~1nativeAdAdaptor(_:didChangeUserInterest:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"nativeAdAdaptor:didChangeUserInterest:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdaptorDelegate~1nativeAdAdaptor(_:didChangeUserInterest:)\/fragments"},{"value":"GFPNativeAdapting","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdapting\/title","op":"replace"},{"value":[{"text":"GFPNativeAdapting","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdapting\/fragments"},{"value":[{"text":"GFPNativeAdapting","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdapting\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdaptor\/title","op":"replace","value":"GFPAdAdaptor"},{"value":[{"kind":"identifier","text":"GFPAdAdaptor"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdaptor\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdaptor\/navigatorTitle","value":[{"text":"GFPAdAdaptor","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdaptorDelegate\/title","value":"GFPNativeAdaptorDelegate","op":"replace"},{"value":[{"text":"GFPNativeAdaptorDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdaptorDelegate\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdaptorDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"GFPNativeAdaptorDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}