{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdInfoEvent"]]},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdInfoEvent\/vimp100","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"vimp100","kind":"identifier"},{"kind":"text","text":": ["},{"text":"GFPAdEventObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdEventObject","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdEventObject"},{"kind":"text","text":"]? { "},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"metadata":{"title":"vimp100","symbolKind":"property","externalID":"c:objc(cs)GFPAdInfoEvent(py)vimp100","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"vimp100"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdEventObject","text":"GFPAdEventObject"},{"kind":"text","text":"]?"}],"modules":[{"name":"GFPSDK"}],"navigatorTitle":[{"text":"vimp100","kind":"identifier"}],"roleHeading":"Instance Property","role":"symbol"},"variants":[{"paths":["\/documentation\/gfpsdk\/gfpadinfoevent\/vimp100"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpadinfoevent\/vimp100"]}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdInfoEvent/vimp100":{"title":"vimp100","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdInfoEvent\/vimp100","role":"symbol","url":"\/documentation\/gfpsdk\/gfpadinfoevent\/vimp100","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"vimp100","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdEventObject","text":"GFPAdEventObject"},{"text":"]?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"vimp100"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdEventObject":{"type":"topic","navigatorTitle":[{"text":"GFPAdEventObject","kind":"identifier"}],"abstract":[{"type":"text","text":"GFPAdEventObject"}],"role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdEventObject","title":"GFPAdEventObject","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPAdEventObject"}],"url":"\/documentation\/gfpsdk\/gfpadeventobject","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdInfoEvent":{"title":"GFPAdInfoEvent","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdInfoEvent","role":"symbol","url":"\/documentation\/gfpsdk\/gfpadinfoevent","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"GFPAdInfoEvent","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"GFPAdInfoEvent"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"vimp100","path":"\/metadata\/title","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"vimp100"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<GFPAdEventObject *>"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"vimp100"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdInfoEvent~1vimp100\/title","value":"vimp100"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdInfoEvent~1vimp100\/fragments","value":[{"text":"vimp100","kind":"identifier"}]},{"value":"GFPAdEventObject","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdEventObject\/title"},{"op":"replace","value":[{"text":"GFPAdEventObject","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdEventObject\/fragments"},{"value":[{"kind":"identifier","text":"GFPAdEventObject"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdEventObject\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdInfoEvent\/title","value":"GFPAdInfoEvent"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdInfoEvent\/fragments","value":[{"text":"GFPAdInfoEvent","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdInfoEvent\/navigatorTitle","value":[{"text":"GFPAdInfoEvent","kind":"identifier"}]}]}]}