{"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpnativead\/delegate"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpnativead\/delegate"]}],"metadata":{"navigatorTitle":[{"text":"delegate","kind":"identifier"}],"externalID":"c:objc(cs)GFPNativeAd(py)delegate","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"delegate"},{"text":": (any ","kind":"text"},{"text":"GFPNativeAdDelegate","preciseIdentifier":"c:objc(pl)GFPNativeAdDelegate","kind":"typeIdentifier"},{"text":")?","kind":"text"}],"modules":[{"name":"GFPSDK"}],"roleHeading":"Instance Property","role":"symbol","title":"delegate"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"weak"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": (any "},{"text":"GFPNativeAdDelegate","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdDelegate","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)GFPNativeAdDelegate"},{"text":")? { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAd"]]},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAd\/delegate","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAd/delegate":{"navigatorTitle":[{"kind":"identifier","text":"delegate"}],"url":"\/documentation\/gfpsdk\/gfpnativead\/delegate","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"text":": (any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)GFPNativeAdDelegate","text":"GFPNativeAdDelegate"},{"kind":"text","text":")?"}],"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAd\/delegate","title":"delegate"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAd":{"abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAd","url":"\/documentation\/gfpsdk\/gfpnativead","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPNativeAd"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPNativeAd"}],"type":"topic","kind":"symbol","title":"GFPNativeAd"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdDelegate":{"abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdDelegate","url":"\/documentation\/gfpsdk\/gfpnativeaddelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPNativeAdDelegate"}],"role":"symbol","navigatorTitle":[{"text":"GFPNativeAdDelegate","kind":"identifier"}],"type":"topic","kind":"symbol","title":"GFPNativeAdDelegate"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"delegate"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"delegate"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"weak","kind":"keyword"},{"kind":"text","text":", "},{"text":"readwrite","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:Qoobjc(pl)GFPNativeAdDelegate","text":"id<GFPNativeAdDelegate>","kind":"typeIdentifier"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":"delegate","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAd~1delegate\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAd~1delegate\/fragments","op":"replace","value":[{"text":"delegate","kind":"identifier"}]},{"op":"replace","value":"GFPNativeAd","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAd\/title"},{"value":[{"kind":"identifier","text":"GFPNativeAd"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAd\/fragments"},{"value":[{"text":"GFPNativeAd","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAd\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdDelegate\/title","op":"replace","value":"GFPNativeAdDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdDelegate\/fragments","value":[{"kind":"identifier","text":"GFPNativeAdDelegate"}]},{"value":[{"text":"GFPNativeAdDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdDelegate\/navigatorTitle"}]}]}