{"metadata":{"title":"bind(with:)","role":"symbol","modules":[{"name":"GFPSDK"}],"roleHeading":"Instance Method","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"bindWith:"}],"required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bind","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"with"},{"kind":"text","text":": (any "},{"text":"GFPNativeAssetProtocol","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)GFPNativeAssetProtocol"},{"text":")?)","kind":"text"}],"externalID":"c:objc(pl)GFPNativeRendererViewProtocol(im)bindWith:"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"bind"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"asset"},{"kind":"text","text":": (any "},{"preciseIdentifier":"c:objc(pl)GFPNativeAssetProtocol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAssetProtocol","kind":"typeIdentifier","text":"GFPNativeAssetProtocol"},{"text":")?)","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpnativerendererviewprotocol\/bind(with:)"]},{"paths":["\/documentation\/gfpsdk\/gfpnativerendererviewprotocol\/bind(with:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeRendererViewProtocol"]]},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeRendererViewProtocol\/bind(with:)","interfaceLanguage":"swift"},"sections":[],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeRendererViewProtocol/bind(with:)":{"type":"topic","abstract":[],"title":"bind(with:)","role":"symbol","url":"\/documentation\/gfpsdk\/gfpnativerendererviewprotocol\/bind(with:)","navigatorTitle":[{"text":"bindWith:","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeRendererViewProtocol\/bind(with:)","required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"bind","kind":"identifier"},{"kind":"text","text":"("},{"text":"with","kind":"externalParam"},{"kind":"text","text":": (any "},{"kind":"typeIdentifier","text":"GFPNativeAssetProtocol","preciseIdentifier":"c:objc(pl)GFPNativeAssetProtocol"},{"text":")?)","kind":"text"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeRendererViewProtocol":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPNativeRendererViewProtocol"}],"url":"\/documentation\/gfpsdk\/gfpnativerendererviewprotocol","abstract":[],"type":"topic","title":"GFPNativeRendererViewProtocol","navigatorTitle":[{"text":"GFPNativeRendererViewProtocol","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeRendererViewProtocol","role":"symbol","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAssetProtocol":{"kind":"symbol","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAssetProtocol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPNativeAssetProtocol","kind":"identifier"}],"navigatorTitle":[{"text":"GFPNativeAssetProtocol","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpnativeassetprotocol","title":"GFPNativeAssetProtocol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"bindWith:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"bindWith:"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"text":"bindWith:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)GFPNativeAssetProtocol","text":"id<GFPNativeAssetProtocol>"},{"kind":"text","text":") "},{"text":"asset","kind":"internalParam"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeRendererViewProtocol~1bind(with:)\/title","value":"bindWith:"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeRendererViewProtocol~1bind(with:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"bindWith:"}],"op":"replace"},{"op":"replace","value":"GFPNativeRendererViewProtocol","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeRendererViewProtocol\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeRendererViewProtocol\/fragments","value":[{"kind":"identifier","text":"GFPNativeRendererViewProtocol"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeRendererViewProtocol\/navigatorTitle","value":[{"kind":"identifier","text":"GFPNativeRendererViewProtocol"}],"op":"replace"},{"value":"GFPNativeAssetProtocol","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAssetProtocol\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAssetProtocol\/fragments","op":"replace","value":[{"text":"GFPNativeAssetProtocol","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAssetProtocol\/navigatorTitle","op":"replace","value":[{"text":"GFPNativeAssetProtocol","kind":"identifier"}]}]}]}