{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"gender"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@GFPUserParamGenderType","kind":"typeIdentifier","text":"GFPUserParamGenderType","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUserParamGenderType"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUserParam"]]},"metadata":{"modules":[{"name":"GFPSDK"}],"title":"gender","roleHeading":"Instance Property","symbolKind":"property","externalID":"c:objc(cs)GFPUserParam(py)gender","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"gender"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"gender","kind":"identifier"},{"kind":"text","text":": "},{"text":"GFPUserParamGenderType","kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPUserParamGenderType"}]},"abstract":[{"type":"text","text":"성별"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpuserparam\/gender"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpuserparam\/gender"]}],"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUserParam\/gender","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPUserParam":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUserParam","url":"\/documentation\/gfpsdk\/gfpuserparam","title":"GFPUserParam","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPUserParam"}],"kind":"symbol","abstract":[],"role":"symbol","navigatorTitle":[{"text":"GFPUserParam","kind":"identifier"}],"type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPUserParamGenderType":{"role":"symbol","type":"topic","title":"GFPUserParamGenderType","navigatorTitle":[{"kind":"identifier","text":"GFPUserParamGenderType"}],"abstract":[],"url":"\/documentation\/gfpsdk\/gfpuserparamgendertype","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPUserParamGenderType"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUserParamGenderType","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPUserParam/gender":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUserParam\/gender","abstract":[{"text":"성별","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"gender","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@GFPUserParamGenderType","kind":"typeIdentifier","text":"GFPUserParamGenderType"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"gender"}],"title":"gender","url":"\/documentation\/gfpsdk\/gfpuserparam\/gender"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"gender"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"gender","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"assign","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@E@GFPUserParamGenderType","text":"GFPUserParamGenderType","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUserParamGenderType","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"gender","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPUserParam\/title","value":"GFPUserParam"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPUserParam\/fragments","value":[{"kind":"identifier","text":"GFPUserParam"}],"op":"replace"},{"op":"replace","value":[{"text":"GFPUserParam","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPUserParam\/navigatorTitle"},{"value":"GFPUserParamGenderType","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPUserParamGenderType\/title"},{"value":[{"kind":"identifier","text":"GFPUserParamGenderType"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPUserParamGenderType\/fragments"},{"op":"replace","value":[{"text":"GFPUserParamGenderType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPUserParamGenderType\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPUserParam~1gender\/title","value":"gender","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPUserParam~1gender\/fragments","value":[{"text":"gender","kind":"identifier"}],"op":"replace"}]}]}