{"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRemindAd"]]},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithDomElement:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)DDXMLElement","text":"DDXMLElement","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"aElement","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"nonLinear:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NonLinear","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/NonLinear","preciseIdentifier":"c:objc(cs)NonLinear"},{"text":" *) ","kind":"text"},{"text":"aNonLinear","kind":"internalParam"},{"kind":"text","text":" "},{"text":"info:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NonlinearInfo","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/NonlinearInfo","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NonlinearInfo"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"aInfo"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@NaverAdsServices@objc(cs)GFPError","text":"GFPError"},{"kind":"text","text":" * *) "},{"kind":"internalParam","text":"aError"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpremindad\/initwithdomelement:nonlinear:info:error:"]}],"kind":"symbol","identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRemindAd\/initWithDomElement:nonLinear:info:error:","interfaceLanguage":"occ"},"metadata":{"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"initWithDomElement:nonLinear:info:error:"}],"title":"initWithDomElement:nonLinear:info:error:","roleHeading":"Instance Method","externalID":"c:objc(cs)GFPRemindAd(im)initWithDomElement:nonLinear:info:error:","modules":[{"name":"GFPSDK"}],"role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDomElement:nonLinear:info:error:"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRemindAd":{"role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRemindAd","navigatorTitle":[{"text":"GFPRemindAd","kind":"identifier"}],"type":"topic","url":"\/documentation\/gfpsdk\/gfpremindad","title":"GFPRemindAd","abstract":[],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPRemindAd","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRemindAd/initWithDomElement:nonLinear:info:error:":{"role":"symbol","abstract":[],"title":"initWithDomElement:nonLinear:info:error:","navigatorTitle":[{"text":"initWithDomElement:nonLinear:info:error:","kind":"identifier"}],"fragments":[{"text":"- ","kind":"text"},{"text":"initWithDomElement:nonLinear:info:error:","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpremindad\/initwithdomelement:nonlinear:info:error:","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRemindAd\/initWithDomElement:nonLinear:info:error:","kind":"symbol","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/NonlinearInfo":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"NonlinearInfo"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/NonlinearInfo","title":"NonlinearInfo","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NonlinearInfo"}],"url":"\/documentation\/gfpsdk\/nonlinearinfo","role":"symbol","abstract":[],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/NonLinear":{"abstract":[],"url":"\/documentation\/gfpsdk\/nonlinear","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/NonLinear","role":"symbol","title":"NonLinear","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NonLinear"}],"navigatorTitle":[{"text":"NonLinear","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRemindAd\/title","value":"GFPRemindAd","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRemindAd\/fragments","value":[{"text":"GFPRemindAd","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"GFPRemindAd"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRemindAd\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1NonlinearInfo\/title","op":"replace","value":"NonlinearInfo"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1NonlinearInfo\/fragments","value":[{"text":"NonlinearInfo","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1NonlinearInfo\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"NonlinearInfo"}]},{"value":"NonLinear","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1NonLinear\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1NonLinear\/fragments","op":"replace","value":[{"text":"NonLinear","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"NonLinear"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1NonLinear\/navigatorTitle"}]}]}