{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRemindAd\/nonLinearInfo"},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRemindAd"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"nonLinearInfo","kind":"identifier"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/NonlinearInfo","text":"NonlinearInfo","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NonlinearInfo"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}]}]}],"metadata":{"title":"nonLinearInfo","symbolKind":"property","modules":[{"name":"GFPSDK"}],"role":"symbol","externalID":"c:objc(cs)GFPRemindAd(py)nonLinearInfo","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"nonLinearInfo","kind":"identifier"},{"kind":"text","text":": "},{"text":"NonlinearInfo","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NonlinearInfo"}],"navigatorTitle":[{"text":"nonLinearInfo","kind":"identifier"}]},"sections":[],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpremindad\/nonlinearinfo"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpremindad\/nonlinearinfo"]}],"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRemindAd/nonLinearInfo":{"navigatorTitle":[{"kind":"identifier","text":"nonLinearInfo"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nonLinearInfo","kind":"identifier"},{"kind":"text","text":": "},{"text":"NonlinearInfo","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NonlinearInfo"}],"abstract":[],"type":"topic","role":"symbol","title":"nonLinearInfo","kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRemindAd\/nonLinearInfo","url":"\/documentation\/gfpsdk\/gfpremindad\/nonlinearinfo"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRemindAd":{"role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRemindAd","navigatorTitle":[{"text":"GFPRemindAd","kind":"identifier"}],"type":"topic","url":"\/documentation\/gfpsdk\/gfpremindad","title":"GFPRemindAd","abstract":[],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPRemindAd","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/NonlinearInfo":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"NonlinearInfo"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/NonlinearInfo","title":"NonlinearInfo","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NonlinearInfo"}],"url":"\/documentation\/gfpsdk\/nonlinearinfo","role":"symbol","abstract":[],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","value":"nonLinearInfo","op":"replace"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"value":[{"text":"nonLinearInfo","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"NonlinearInfo","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/NonlinearInfo","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NonlinearInfo"},{"text":" * ","kind":"text"},{"text":"nonLinearInfo","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","value":"nonLinearInfo","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRemindAd~1nonLinearInfo\/title"},{"value":[{"text":"nonLinearInfo","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRemindAd~1nonLinearInfo\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRemindAd\/title","value":"GFPRemindAd","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRemindAd\/fragments","value":[{"text":"GFPRemindAd","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"GFPRemindAd"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRemindAd\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1NonlinearInfo\/title","value":"NonlinearInfo"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1NonlinearInfo\/fragments","op":"replace","value":[{"kind":"identifier","text":"NonlinearInfo"}]},{"value":[{"kind":"identifier","text":"NonlinearInfo"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1NonlinearInfo\/navigatorTitle"}]}]}