{"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRemindAd"]]},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nonLinear","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NonLinear","preciseIdentifier":"c:objc(cs)NonLinear","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/NonLinear"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpremindad\/nonlinear"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpremindad\/nonlinear"]}],"kind":"symbol","identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRemindAd\/nonLinear","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"text":"nonLinear","kind":"identifier"}],"title":"nonLinear","roleHeading":"Instance Property","externalID":"c:objc(cs)GFPRemindAd(py)nonLinear","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"nonLinear","kind":"identifier"},{"kind":"text","text":": "},{"text":"NonLinear","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NonLinear"}],"modules":[{"name":"GFPSDK"}],"symbolKind":"property","role":"symbol"},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRemindAd/nonLinear":{"navigatorTitle":[{"text":"nonLinear","kind":"identifier"}],"title":"nonLinear","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRemindAd\/nonLinear","type":"topic","url":"\/documentation\/gfpsdk\/gfpremindad\/nonlinear","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"nonLinear"},{"kind":"text","text":": "},{"text":"NonLinear","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NonLinear"}],"role":"symbol","kind":"symbol","abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRemindAd":{"role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRemindAd","navigatorTitle":[{"text":"GFPRemindAd","kind":"identifier"}],"type":"topic","url":"\/documentation\/gfpsdk\/gfpremindad","title":"GFPRemindAd","abstract":[],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPRemindAd","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/NonLinear":{"abstract":[],"url":"\/documentation\/gfpsdk\/nonlinear","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/NonLinear","role":"symbol","title":"NonLinear","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NonLinear"}],"navigatorTitle":[{"text":"NonLinear","kind":"identifier"}],"kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"nonLinear"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"nonLinear","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NonLinear","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/NonLinear","preciseIdentifier":"c:objc(cs)NonLinear"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"nonLinear"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRemindAd~1nonLinear\/title","value":"nonLinear"},{"op":"replace","value":[{"kind":"identifier","text":"nonLinear"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRemindAd~1nonLinear\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRemindAd\/title","value":"GFPRemindAd"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRemindAd\/fragments","value":[{"text":"GFPRemindAd","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRemindAd\/navigatorTitle","value":[{"text":"GFPRemindAd","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1NonLinear\/title","value":"NonLinear"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1NonLinear\/fragments","value":[{"text":"NonLinear","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1NonLinear\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"NonLinear"}]}]}]}