{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPStartEvent\/errorEventInfoWithErrorInfo(_:)"},"metadata":{"roleHeading":"Type Method","modules":[{"name":"GFPSDK"}],"title":"errorEventInfoWithErrorInfo(_:)","role":"symbol","externalID":"c:objc(cs)GFPStartEvent(cm)errorEventInfoWithErrorInfo:","symbolKind":"method","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorEventInfoWithErrorInfo"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPErrorEventInfo","text":"GFPErrorEventInfo"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPStartEvent","text":"GFPStartEvent"},{"text":"!","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"errorEventInfoWithErrorInfo:"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPStartEvent"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpstartevent\/erroreventinfowitherrorinfo(_:)"]},{"paths":["\/documentation\/gfpsdk\/gfpstartevent\/erroreventinfowitherrorinfo(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"errorEventInfoWithErrorInfo"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"errorEventInfo"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorEventInfo","preciseIdentifier":"c:objc(cs)GFPErrorEventInfo","kind":"typeIdentifier","text":"GFPErrorEventInfo"},{"kind":"text","text":"!) -> "},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPStartEvent","preciseIdentifier":"c:objc(cs)GFPStartEvent","kind":"typeIdentifier","text":"GFPStartEvent"},{"text":"!","kind":"text"}]}]}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPStartEvent/errorEventInfoWithErrorInfo(_:)":{"type":"topic","navigatorTitle":[{"text":"errorEventInfoWithErrorInfo:","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"errorEventInfoWithErrorInfo","kind":"identifier"},{"kind":"text","text":"("},{"text":"GFPErrorEventInfo","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPErrorEventInfo"},{"kind":"text","text":"!) -> "},{"text":"GFPStartEvent","preciseIdentifier":"c:objc(cs)GFPStartEvent","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"title":"errorEventInfoWithErrorInfo(_:)","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPStartEvent\/errorEventInfoWithErrorInfo(_:)","role":"symbol","url":"\/documentation\/gfpsdk\/gfpstartevent\/erroreventinfowitherrorinfo(_:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPErrorEventInfo":{"type":"topic","abstract":[],"title":"GFPErrorEventInfo","role":"symbol","url":"\/documentation\/gfpsdk\/gfperroreventinfo","navigatorTitle":[{"kind":"identifier","text":"GFPErrorEventInfo"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorEventInfo","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPErrorEventInfo"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPStartEvent":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"GFPStartEvent"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"GFPStartEvent","kind":"identifier"}],"title":"GFPStartEvent","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPStartEvent","role":"symbol","url":"\/documentation\/gfpsdk\/gfpstartevent"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"errorEventInfoWithErrorInfo:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"errorEventInfoWithErrorInfo:"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPStartEvent","text":"GFPStartEvent","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPStartEvent"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"errorEventInfoWithErrorInfo:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPErrorEventInfo","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorEventInfo","kind":"typeIdentifier","text":"GFPErrorEventInfo"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"errorEventInfo"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPStartEvent~1errorEventInfoWithErrorInfo(_:)\/title","value":"errorEventInfoWithErrorInfo:","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"text":"errorEventInfoWithErrorInfo:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPStartEvent~1errorEventInfoWithErrorInfo(_:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorEventInfo\/title","op":"replace","value":"GFPErrorEventInfo"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorEventInfo\/fragments","op":"replace","value":[{"text":"GFPErrorEventInfo","kind":"identifier"}]},{"op":"replace","value":[{"text":"GFPErrorEventInfo","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorEventInfo\/navigatorTitle"},{"value":"GFPStartEvent","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPStartEvent\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPStartEvent\/fragments","value":[{"text":"GFPStartEvent","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPStartEvent\/navigatorTitle","value":[{"kind":"identifier","text":"GFPStartEvent"}]}]}]}