{"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPStartEvent\/errorEventInfo"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"errorEventInfo","kind":"identifier"},{"kind":"text","text":": "},{"text":"GFPErrorEventInfo","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorEventInfo","preciseIdentifier":"c:objc(cs)GFPErrorEventInfo","kind":"typeIdentifier"},{"kind":"text","text":"! { "},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpstartevent\/erroreventinfo"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpstartevent\/erroreventinfo"]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPStartEvent"]]},"metadata":{"symbolKind":"property","externalID":"c:objc(cs)GFPStartEvent(py)errorEventInfo","role":"symbol","modules":[{"name":"GFPSDK"}],"navigatorTitle":[{"text":"errorEventInfo","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorEventInfo"},{"text":": ","kind":"text"},{"text":"GFPErrorEventInfo","preciseIdentifier":"c:objc(cs)GFPErrorEventInfo","kind":"typeIdentifier"},{"kind":"text","text":"!"}],"roleHeading":"Instance Property","title":"errorEventInfo"},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPStartEvent":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"GFPStartEvent"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"GFPStartEvent","kind":"identifier"}],"title":"GFPStartEvent","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPStartEvent","role":"symbol","url":"\/documentation\/gfpsdk\/gfpstartevent"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPStartEvent/errorEventInfo":{"abstract":[],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"errorEventInfo","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPErrorEventInfo","text":"GFPErrorEventInfo","kind":"typeIdentifier"},{"kind":"text","text":"!"}],"url":"\/documentation\/gfpsdk\/gfpstartevent\/erroreventinfo","navigatorTitle":[{"kind":"identifier","text":"errorEventInfo"}],"type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPStartEvent\/errorEventInfo","title":"errorEventInfo"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPErrorEventInfo":{"type":"topic","abstract":[],"title":"GFPErrorEventInfo","role":"symbol","url":"\/documentation\/gfpsdk\/gfperroreventinfo","navigatorTitle":[{"kind":"identifier","text":"GFPErrorEventInfo"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorEventInfo","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPErrorEventInfo"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"errorEventInfo","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"errorEventInfo","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"text":"GFPErrorEventInfo","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPErrorEventInfo","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorEventInfo"},{"text":" * ","kind":"text"},{"text":"errorEventInfo","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPStartEvent\/title","value":"GFPStartEvent","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"GFPStartEvent"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPStartEvent\/fragments"},{"value":[{"kind":"identifier","text":"GFPStartEvent"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPStartEvent\/navigatorTitle"},{"value":"errorEventInfo","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPStartEvent~1errorEventInfo\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPStartEvent~1errorEventInfo\/fragments","value":[{"kind":"identifier","text":"errorEventInfo"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorEventInfo\/title","value":"GFPErrorEventInfo"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorEventInfo\/fragments","op":"replace","value":[{"text":"GFPErrorEventInfo","kind":"identifier"}]},{"op":"replace","value":[{"text":"GFPErrorEventInfo","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorEventInfo\/navigatorTitle"}]}]}