{"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdProviderType"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"bidMachine","kind":"identifier"},{"text":": ","kind":"text"},{"text":"GFPNativeAdProviderType","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdProviderType","kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPNativeAdProviderType"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpnativeadprovidertype\/bidmachine"]},{"paths":["\/documentation\/gfpsdk\/gfpnativeadprovidertype\/bidmachine"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdProviderType\/bidMachine"},"metadata":{"role":"symbol","modules":[{"name":"GFPSDK"}],"externalID":"c:@E@GFPNativeAdProviderType@GFPNativeAdProviderTypeBidMachine","symbolKind":"property","title":"bidMachine","navigatorTitle":[{"text":"GFPNativeAdProviderTypeBidMachine","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bidMachine","kind":"identifier"},{"kind":"text","text":": "},{"text":"GFPNativeAdProviderType","preciseIdentifier":"c:@E@GFPNativeAdProviderType","kind":"typeIdentifier"}],"roleHeading":"Type Property"},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdProviderType/bidMachine":{"role":"symbol","abstract":[],"title":"bidMachine","navigatorTitle":[{"text":"GFPNativeAdProviderTypeBidMachine","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"bidMachine","kind":"identifier"},{"text":": ","kind":"text"},{"text":"GFPNativeAdProviderType","preciseIdentifier":"c:@E@GFPNativeAdProviderType","kind":"typeIdentifier"}],"url":"\/documentation\/gfpsdk\/gfpnativeadprovidertype\/bidmachine","type":"topic","kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdProviderType\/bidMachine"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdProviderType":{"title":"GFPNativeAdProviderType","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdProviderType","kind":"symbol","role":"symbol","url":"\/documentation\/gfpsdk\/gfpnativeadprovidertype","type":"topic","abstract":[],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPNativeAdProviderType","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"GFPNativeAdProviderType"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"value":"GFPNativeAdProviderTypeBidMachine","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","value":[{"text":"GFPNativeAdProviderTypeBidMachine","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"GFPNativeAdProviderTypeBidMachine"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdProviderType~1bidMachine\/title","value":"GFPNativeAdProviderTypeBidMachine","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdProviderType~1bidMachine\/fragments","value":[{"kind":"identifier","text":"GFPNativeAdProviderTypeBidMachine"}]},{"value":"GFPNativeAdProviderType","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdProviderType\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdProviderType\/fragments","value":[{"text":"GFPNativeAdProviderType","kind":"identifier"}]},{"op":"replace","value":[{"text":"GFPNativeAdProviderType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdProviderType\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}