{"metadata":{"role":"symbol","modules":[{"name":"GFPSDK"}],"externalID":"c:@E@GFPNativeAdProviderType@GFPNativeAdProviderTypeFAN","symbolKind":"property","title":"FAN","navigatorTitle":[{"kind":"identifier","text":"GFPNativeAdProviderTypeFAN"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"FAN","kind":"identifier"},{"text":": ","kind":"text"},{"text":"GFPNativeAdProviderType","kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPNativeAdProviderType"}],"roleHeading":"Type Property"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FAN"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"GFPNativeAdProviderType","preciseIdentifier":"c:@E@GFPNativeAdProviderType","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdProviderType"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpnativeadprovidertype\/fan"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gfpsdk\/gfpnativeadprovidertype\/fan"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdProviderType"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdProviderType\/FAN"},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdProviderType":{"title":"GFPNativeAdProviderType","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdProviderType","kind":"symbol","role":"symbol","url":"\/documentation\/gfpsdk\/gfpnativeadprovidertype","type":"topic","abstract":[],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPNativeAdProviderType","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"GFPNativeAdProviderType"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdProviderType/FAN":{"role":"symbol","abstract":[],"title":"FAN","navigatorTitle":[{"text":"GFPNativeAdProviderTypeFAN","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"FAN","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@GFPNativeAdProviderType","text":"GFPNativeAdProviderType","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdProviderType\/FAN","type":"topic","kind":"symbol","url":"\/documentation\/gfpsdk\/gfpnativeadprovidertype\/fan"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"GFPNativeAdProviderTypeFAN","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"GFPNativeAdProviderTypeFAN","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"GFPNativeAdProviderTypeFAN","kind":"identifier"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdProviderType\/title","value":"GFPNativeAdProviderType","op":"replace"},{"op":"replace","value":[{"text":"GFPNativeAdProviderType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdProviderType\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdProviderType\/navigatorTitle","value":[{"kind":"identifier","text":"GFPNativeAdProviderType"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdProviderType~1FAN\/title","value":"GFPNativeAdProviderTypeFAN"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdProviderType~1FAN\/fragments","value":[{"kind":"identifier","text":"GFPNativeAdProviderTypeFAN"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}