{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdProviderType\/isSubset(of:)"},"sections":[],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpnativeadprovidertype\/issubset(of:)"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdProviderType","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdProviderType\/SetAlgebra-Implementations"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"SetAlgebra.isSubset(of:)"},{"text":".","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isSubset"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"of"},{"kind":"text","text":" "},{"kind":"internalParam","text":"other"},{"kind":"text","text":": "},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}]}],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isSubset"},{"kind":"text","text":"("},{"kind":"externalParam","text":"of"},{"text":": ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"roleHeading":"Instance Method","symbolKind":"method","title":"isSubset(of:)","modules":[{"relatedModules":["Swift"],"name":"GFPSDK"}],"extendedModule":"Swift","role":"symbol","externalID":"s:s10SetAlgebraPsE8isSubset2ofSbx_tF::SYNTHESIZED::c:@E@GFPNativeAdProviderType"},"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdProviderType":{"title":"GFPNativeAdProviderType","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdProviderType","kind":"symbol","role":"symbol","url":"\/documentation\/gfpsdk\/gfpnativeadprovidertype","type":"topic","abstract":[],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPNativeAdProviderType","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"GFPNativeAdProviderType"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdProviderType/isSubset(of:)":{"type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdProviderType\/isSubset(of:)","abstract":[],"title":"isSubset(of:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"isSubset","kind":"identifier"},{"text":"(","kind":"text"},{"text":"of","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"url":"\/documentation\/gfpsdk\/gfpnativeadprovidertype\/issubset(of:)","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdProviderType/SetAlgebra-Implementations":{"kind":"article","type":"topic","role":"collectionGroup","abstract":[],"title":"SetAlgebra Implementations","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdProviderType\/SetAlgebra-Implementations","url":"\/documentation\/gfpsdk\/gfpnativeadprovidertype\/setalgebra-implementations"}},"variantOverrides":[{"patch":[{"op":"replace","value":"GFPNativeAdProviderType","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdProviderType\/title"},{"op":"replace","value":[{"text":"GFPNativeAdProviderType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdProviderType\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdProviderType\/navigatorTitle","value":[{"text":"GFPNativeAdProviderType","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}