{"sections":[],"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdProviderType\/LAN","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LAN"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"GFPNativeAdProviderType","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdProviderType","preciseIdentifier":"c:@E@GFPNativeAdProviderType"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"kind":"symbol","metadata":{"title":"LAN","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"LAN","kind":"identifier"},{"text":": ","kind":"text"},{"text":"GFPNativeAdProviderType","kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPNativeAdProviderType"}],"roleHeading":"Type Property","role":"symbol","externalID":"c:@E@GFPNativeAdProviderType@GFPNativeAdProviderTypeLAN","symbolKind":"property","navigatorTitle":[{"text":"GFPNativeAdProviderTypeLAN","kind":"identifier"}],"modules":[{"name":"GFPSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdProviderType"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpnativeadprovidertype\/lan"]},{"paths":["\/documentation\/gfpsdk\/gfpnativeadprovidertype\/lan"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdProviderType/LAN":{"navigatorTitle":[{"text":"GFPNativeAdProviderTypeLAN","kind":"identifier"}],"title":"LAN","abstract":[],"type":"topic","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdProviderType\/LAN","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"LAN","kind":"identifier"},{"kind":"text","text":": "},{"text":"GFPNativeAdProviderType","kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPNativeAdProviderType"}],"url":"\/documentation\/gfpsdk\/gfpnativeadprovidertype\/lan","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdProviderType":{"title":"GFPNativeAdProviderType","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdProviderType","kind":"symbol","role":"symbol","url":"\/documentation\/gfpsdk\/gfpnativeadprovidertype","type":"topic","abstract":[],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPNativeAdProviderType","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"GFPNativeAdProviderType"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"GFPNativeAdProviderTypeLAN"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"GFPNativeAdProviderTypeLAN","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"GFPNativeAdProviderTypeLAN","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdProviderType~1LAN\/title","value":"GFPNativeAdProviderTypeLAN","op":"replace"},{"value":[{"text":"GFPNativeAdProviderTypeLAN","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdProviderType~1LAN\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdProviderType\/title","value":"GFPNativeAdProviderType"},{"op":"replace","value":[{"text":"GFPNativeAdProviderType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdProviderType\/fragments"},{"value":[{"text":"GFPNativeAdProviderType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdProviderType\/navigatorTitle"}]}]}