{"variants":[{"paths":["\/documentation\/gfpsdk\/gfpnativemediabadgeinfo\/styleinfo"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpnativemediabadgeinfo\/styleinfo"]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeMediaBadgeInfo"]]},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeMediaBadgeInfo\/styleInfo","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"kind":"symbol","metadata":{"title":"styleInfo","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"styleInfo","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"GFPNativeStyleInfo","preciseIdentifier":"c:objc(cs)GFPNativeStyleInfo"}],"roleHeading":"Instance Property","role":"symbol","externalID":"c:objc(cs)GFPNativeMediaBadgeInfo(py)styleInfo","navigatorTitle":[{"text":"styleInfo","kind":"identifier"}],"modules":[{"name":"GFPSDK"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"styleInfo","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)GFPNativeStyleInfo","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeStyleInfo","text":"GFPNativeStyleInfo","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeMediaBadgeInfo":{"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GFPNativeMediaBadgeInfo"}],"abstract":[],"title":"GFPNativeMediaBadgeInfo","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPNativeMediaBadgeInfo","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeMediaBadgeInfo","url":"\/documentation\/gfpsdk\/gfpnativemediabadgeinfo"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeMediaBadgeInfo/styleInfo":{"abstract":[],"title":"styleInfo","url":"\/documentation\/gfpsdk\/gfpnativemediabadgeinfo\/styleinfo","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeMediaBadgeInfo\/styleInfo","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"styleInfo","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"GFPNativeStyleInfo","preciseIdentifier":"c:objc(cs)GFPNativeStyleInfo"}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"styleInfo","kind":"identifier"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeStyleInfo":{"title":"GFPNativeStyleInfo","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeStyleInfo","navigatorTitle":[{"text":"GFPNativeStyleInfo","kind":"identifier"}],"abstract":[],"kind":"symbol","type":"topic","url":"\/documentation\/gfpsdk\/gfpnativestyleinfo","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPNativeStyleInfo"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"styleInfo"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"styleInfo"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPNativeStyleInfo","text":"GFPNativeStyleInfo","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeStyleInfo"},{"kind":"text","text":" * "},{"text":"styleInfo","kind":"identifier"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeMediaBadgeInfo\/title","value":"GFPNativeMediaBadgeInfo","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeMediaBadgeInfo\/fragments","value":[{"kind":"identifier","text":"GFPNativeMediaBadgeInfo"}],"op":"replace"},{"value":[{"text":"GFPNativeMediaBadgeInfo","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeMediaBadgeInfo\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeMediaBadgeInfo~1styleInfo\/title","op":"replace","value":"styleInfo"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeMediaBadgeInfo~1styleInfo\/fragments","value":[{"text":"styleInfo","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeStyleInfo\/title","value":"GFPNativeStyleInfo","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"GFPNativeStyleInfo"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeStyleInfo\/fragments"},{"value":[{"text":"GFPNativeStyleInfo","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeStyleInfo\/navigatorTitle","op":"replace"}]}]}