{"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/NonLinear"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"metadata":{"externalID":"c:objc(cs)NonLinear(im)initWithDomElement:error:","modules":[{"name":"GFPSDK"}],"roleHeading":"Instance Method","title":"initWithDomElement:error:","role":"symbol","symbolKind":"method","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithDomElement:error:"}],"navigatorTitle":[{"text":"initWithDomElement:error:","kind":"identifier"}]},"primaryContentSections":[{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"text":") ","kind":"text"},{"text":"initWithDomElement:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"DDXMLElement","preciseIdentifier":"c:objc(cs)DDXMLElement"},{"text":" *) ","kind":"text"},{"text":"aElement","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"text":"GFPError","kind":"typeIdentifier","preciseIdentifier":"c:@M@NaverAdsServices@objc(cs)GFPError"},{"text":" * *) ","kind":"text"},{"kind":"internalParam","text":"aError"},{"text":";","kind":"text"}]}],"kind":"declarations"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/nonlinear\/initwithdomelement:error:"]}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/NonLinear\/initWithDomElement:error:"},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/NonLinear":{"abstract":[],"url":"\/documentation\/gfpsdk\/nonlinear","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/NonLinear","role":"symbol","title":"NonLinear","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NonLinear"}],"navigatorTitle":[{"text":"NonLinear","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/NonLinear/initWithDomElement:error:":{"navigatorTitle":[{"kind":"identifier","text":"initWithDomElement:error:"}],"url":"\/documentation\/gfpsdk\/nonlinear\/initwithdomelement:error:","abstract":[],"fragments":[{"kind":"text","text":"- "},{"text":"initWithDomElement:error:","kind":"identifier"}],"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/NonLinear\/initWithDomElement:error:","title":"initWithDomElement:error:"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1NonLinear\/title","value":"NonLinear","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1NonLinear\/fragments","value":[{"text":"NonLinear","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1NonLinear\/navigatorTitle","value":[{"text":"NonLinear","kind":"identifier"}],"op":"replace"}]}]}