{"abstract":[{"text":"광고 응답 객체","type":"text"}],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpinterstitialad\/responseinfo"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gfpsdk\/gfpinterstitialad\/responseinfo"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAd\/responseInfo","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"responseInfo"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)GFPLoadResponseInfo","text":"GFPLoadResponseInfo","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLoadResponseInfo"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAd"]]},"metadata":{"modules":[{"name":"GFPSDK"}],"title":"responseInfo","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"responseInfo","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)GFPLoadResponseInfo","text":"GFPLoadResponseInfo","kind":"typeIdentifier"}],"externalID":"c:objc(cs)GFPInterstitialAd(py)responseInfo","role":"symbol","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"responseInfo"}]},"sections":[],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPInterstitialAd/responseInfo":{"role":"symbol","navigatorTitle":[{"text":"responseInfo","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"responseInfo","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPLoadResponseInfo","text":"GFPLoadResponseInfo","kind":"typeIdentifier"}],"type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAd\/responseInfo","title":"responseInfo","kind":"symbol","url":"\/documentation\/gfpsdk\/gfpinterstitialad\/responseinfo","abstract":[{"text":"광고 응답 객체","type":"text"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPLoadResponseInfo":{"title":"GFPLoadResponseInfo","url":"\/documentation\/gfpsdk\/gfploadresponseinfo","role":"symbol","navigatorTitle":[{"text":"GFPLoadResponseInfo","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"GFPLoadResponseInfo","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLoadResponseInfo"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPInterstitialAd":{"navigatorTitle":[{"text":"GFPInterstitialAd","kind":"identifier"}],"abstract":[],"url":"\/documentation\/gfpsdk\/gfpinterstitialad","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAd","type":"topic","kind":"symbol","title":"GFPInterstitialAd","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPInterstitialAd"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","value":"responseInfo","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"responseInfo","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"GFPLoadResponseInfo","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLoadResponseInfo","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPLoadResponseInfo"},{"kind":"text","text":" * "},{"text":"responseInfo","kind":"identifier"},{"kind":"text","text":";"}]}]}},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAd~1responseInfo\/title","value":"responseInfo","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAd~1responseInfo\/fragments","op":"replace","value":[{"text":"responseInfo","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLoadResponseInfo\/title","value":"GFPLoadResponseInfo"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLoadResponseInfo\/fragments","op":"replace","value":[{"kind":"identifier","text":"GFPLoadResponseInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLoadResponseInfo\/navigatorTitle","value":[{"kind":"identifier","text":"GFPLoadResponseInfo"}]},{"value":"GFPInterstitialAd","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAd\/title"},{"value":[{"text":"GFPInterstitialAd","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAd\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAd\/navigatorTitle","value":[{"kind":"identifier","text":"GFPInterstitialAd"}],"op":"replace"}]}]}