{"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"OptionSet.init()"},{"type":"text","text":"."}],"metadata":{"fragments":[{"kind":"identifier","text":"init"},{"text":"()","kind":"text"}],"roleHeading":"Initializer","modules":[{"relatedModules":["Swift"],"name":"GFPSDK"}],"role":"symbol","symbolKind":"init","extendedModule":"Swift","title":"init()","externalID":"s:s9OptionSetPss17FixedWidthInteger8RawValueRpzrlExycfc::SYNTHESIZED::c:@E@GFPNonLinearContainerType","conformance":{"conformancePrefix":[{"text":"Conforms when","type":"text"}],"availabilityPrefix":[{"type":"text","text":"Available when"}],"constraints":[{"type":"codeVoice","code":"RawValue"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"FixedWidthInteger"},{"type":"text","text":"."}]}},"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearContainerType","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearContainerType\/OptionSet-Implementations"]]},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearContainerType\/init()","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"init"},{"text":"()","kind":"text"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpnonlinearcontainertype\/init()"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNonLinearContainerType":{"abstract":[{"text":"RemindText 노출 위치에 따른 Type","type":"text"},{"type":"text","text":" "},{"text":"Container Inner : Content Player 영역 내부 노출.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Container Outer : Content Player 영역 외l부 노출."}],"kind":"symbol","title":"GFPNonLinearContainerType","navigatorTitle":[{"kind":"identifier","text":"GFPNonLinearContainerType"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearContainerType","url":"\/documentation\/gfpsdk\/gfpnonlinearcontainertype","type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPNonLinearContainerType"}],"role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNonLinearContainerType/init()":{"kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"()"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearContainerType\/init()","conformance":{"conformancePrefix":[{"type":"text","text":"Conforms when"}],"constraints":[{"code":"RawValue","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"FixedWidthInteger"},{"type":"text","text":"."}],"availabilityPrefix":[{"type":"text","text":"Available when"}]},"url":"\/documentation\/gfpsdk\/gfpnonlinearcontainertype\/init()","role":"symbol","type":"topic","abstract":[],"title":"init()"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNonLinearContainerType/OptionSet-Implementations":{"title":"OptionSet Implementations","url":"\/documentation\/gfpsdk\/gfpnonlinearcontainertype\/optionset-implementations","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearContainerType\/OptionSet-Implementations","role":"collectionGroup","type":"topic","kind":"article","abstract":[]}},"variantOverrides":[{"patch":[{"value":"GFPNonLinearContainerType","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearContainerType\/title"},{"value":[{"text":"GFPNonLinearContainerType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearContainerType\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"GFPNonLinearContainerType"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearContainerType\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}