{"metadata":{"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"inner"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"GFPNonLinearContainerType","preciseIdentifier":"c:@E@GFPNonLinearContainerType"}],"roleHeading":"Type Property","symbolKind":"property","role":"symbol","modules":[{"name":"GFPSDK"}],"navigatorTitle":[{"text":"GFPNonLinearContainerTypeInner","kind":"identifier"}],"title":"inner","externalID":"c:@E@GFPNonLinearContainerType@GFPNonLinearContainerTypeInner"},"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearContainerType"]]},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearContainerType\/inner","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"inner","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearContainerType","preciseIdentifier":"c:@E@GFPNonLinearContainerType","text":"GFPNonLinearContainerType"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpnonlinearcontainertype\/inner"]},{"paths":["\/documentation\/gfpsdk\/gfpnonlinearcontainertype\/inner"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNonLinearContainerType/inner":{"navigatorTitle":[{"text":"GFPNonLinearContainerTypeInner","kind":"identifier"}],"title":"inner","url":"\/documentation\/gfpsdk\/gfpnonlinearcontainertype\/inner","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearContainerType\/inner","role":"symbol","type":"topic","kind":"symbol","abstract":[],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"inner"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@GFPNonLinearContainerType","text":"GFPNonLinearContainerType","kind":"typeIdentifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNonLinearContainerType":{"abstract":[{"text":"RemindText 노출 위치에 따른 Type","type":"text"},{"type":"text","text":" "},{"text":"Container Inner : Content Player 영역 내부 노출.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Container Outer : Content Player 영역 외l부 노출."}],"kind":"symbol","title":"GFPNonLinearContainerType","navigatorTitle":[{"kind":"identifier","text":"GFPNonLinearContainerType"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearContainerType","url":"\/documentation\/gfpsdk\/gfpnonlinearcontainertype","type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPNonLinearContainerType"}],"role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"GFPNonLinearContainerTypeInner"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GFPNonLinearContainerTypeInner"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"GFPNonLinearContainerTypeInner","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearContainerType~1inner\/title","value":"GFPNonLinearContainerTypeInner"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearContainerType~1inner\/fragments","value":[{"text":"GFPNonLinearContainerTypeInner","kind":"identifier"}],"op":"replace"},{"value":"GFPNonLinearContainerType","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearContainerType\/title"},{"value":[{"text":"GFPNonLinearContainerType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearContainerType\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearContainerType\/navigatorTitle","value":[{"kind":"identifier","text":"GFPNonLinearContainerType"}],"op":"replace"}]}]}