{"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpvideoadinfo\/init(provider:url:remindadlist:remindviewlist:loudnessnormalization:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gfpsdk\/gfpvideoadinfo\/init(provider:url:remindadlist:remindviewlist:loudnessnormalization:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:objc(cs)GFPVideoAdInfo(im)initWithProvider:url:remindAdList:remindViewList:loudnessNormalization:","title":"init(provider:url:remindAdList:remindViewList:loudnessNormalization:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"provider","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"url"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier","text":"URL"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"remindAdList"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPRemindAd","text":"GFPRemindAd","kind":"typeIdentifier"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"remindViewList"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"GFPNonLinearAdView","preciseIdentifier":"c:objc(cs)GFPNonLinearAdView"},{"kind":"text","text":"], "},{"text":"loudnessNormalization","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPLoudnessNormalization","text":"GFPLoudnessNormalization"},{"kind":"text","text":")"}],"roleHeading":"Initializer","modules":[{"name":"GFPSDK"}],"navigatorTitle":[{"kind":"identifier","text":"initWithProvider:url:remindAdList:remindViewList:loudnessNormalization:"}],"role":"symbol","symbolKind":"init"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"provider"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"aProviderName"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"url"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"aURL"},{"kind":"text","text":": "},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"remindAdList"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"aRemindAdList"},{"text":": [","kind":"text"},{"text":"GFPRemindAd","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPRemindAd","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRemindAd"},{"text":"], ","kind":"text"},{"text":"remindViewList","kind":"externalParam"},{"text":": [","kind":"text"},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearAdView","text":"GFPNonLinearAdView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPNonLinearAdView"},{"text":"], ","kind":"text"},{"text":"loudnessNormalization","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"aLoundess","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPLoudnessNormalization","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLoudnessNormalization","text":"GFPLoudnessNormalization","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdInfo"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdInfo\/init(provider:url:remindAdList:remindViewList:loudnessNormalization:)"},"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPLoudnessNormalization":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPLoudnessNormalization","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"GFPLoudnessNormalization"}],"kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLoudnessNormalization","type":"topic","role":"symbol","abstract":[],"url":"\/documentation\/gfpsdk\/gfploudnessnormalization","title":"GFPLoudnessNormalization"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdInfo/init(provider:url:remindAdList:remindViewList:loudnessNormalization:)":{"abstract":[],"url":"\/documentation\/gfpsdk\/gfpvideoadinfo\/init(provider:url:remindadlist:remindviewlist:loudnessnormalization:)","role":"symbol","title":"init(provider:url:remindAdList:remindViewList:loudnessNormalization:)","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdInfo\/init(provider:url:remindAdList:remindViewList:loudnessNormalization:)","navigatorTitle":[{"text":"initWithProvider:url:remindAdList:remindViewList:loudnessNormalization:","kind":"identifier"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"provider","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"url"},{"kind":"text","text":": "},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"remindAdList"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPRemindAd","text":"GFPRemindAd","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"remindViewList","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPNonLinearAdView","text":"GFPNonLinearAdView","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"loudnessNormalization","kind":"externalParam"},{"kind":"text","text":": "},{"text":"GFPLoudnessNormalization","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPLoudnessNormalization"},{"kind":"text","text":")"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNonLinearAdView":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearAdView","title":"GFPNonLinearAdView","type":"topic","url":"\/documentation\/gfpsdk\/gfpnonlinearadview","abstract":[],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPNonLinearAdView"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPNonLinearAdView","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdInfo":{"kind":"symbol","title":"GFPVideoAdInfo","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdInfo","role":"symbol","navigatorTitle":[{"text":"GFPVideoAdInfo","kind":"identifier"}],"type":"topic","url":"\/documentation\/gfpsdk\/gfpvideoadinfo","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPVideoAdInfo"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRemindAd":{"role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRemindAd","navigatorTitle":[{"text":"GFPRemindAd","kind":"identifier"}],"type":"topic","url":"\/documentation\/gfpsdk\/gfpremindad","title":"GFPRemindAd","abstract":[],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPRemindAd","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"initWithProvider:url:remindAdList:remindViewList:loudnessNormalization:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithProvider:url:remindAdList:remindViewList:loudnessNormalization:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithProvider:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"aProviderName"},{"text":" ","kind":"text"},{"text":"url:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSURL","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURL"},{"text":" *) ","kind":"text"},{"text":"aURL","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"remindAdList:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSArray<GFPRemindAd *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"aRemindAdList"},{"kind":"text","text":" "},{"kind":"identifier","text":"remindViewList:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<GFPNonLinearAdView *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"remindViewList"},{"text":" ","kind":"text"},{"text":"loudnessNormalization:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPLoudnessNormalization","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLoudnessNormalization","text":"GFPLoudnessNormalization","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"aLoundess","kind":"internalParam"},{"kind":"text","text":";"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLoudnessNormalization\/title","value":"GFPLoudnessNormalization"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLoudnessNormalization\/fragments","value":[{"text":"GFPLoudnessNormalization","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"GFPLoudnessNormalization"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLoudnessNormalization\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdInfo~1init(provider:url:remindAdList:remindViewList:loudnessNormalization:)\/title","value":"initWithProvider:url:remindAdList:remindViewList:loudnessNormalization:"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdInfo~1init(provider:url:remindAdList:remindViewList:loudnessNormalization:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithProvider:url:remindAdList:remindViewList:loudnessNormalization:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearAdView\/title","value":"GFPNonLinearAdView"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearAdView\/fragments","op":"replace","value":[{"kind":"identifier","text":"GFPNonLinearAdView"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearAdView\/navigatorTitle","op":"replace","value":[{"text":"GFPNonLinearAdView","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdInfo\/title","value":"GFPVideoAdInfo"},{"value":[{"text":"GFPVideoAdInfo","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdInfo\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdInfo\/navigatorTitle","value":[{"text":"GFPVideoAdInfo","kind":"identifier"}],"op":"replace"},{"value":"GFPRemindAd","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRemindAd\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRemindAd\/fragments","value":[{"text":"GFPRemindAd","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"text":"GFPRemindAd","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRemindAd\/navigatorTitle"}]}]}