{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"nonLinearViewList"},{"text":": [","kind":"text"},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearAdView","text":"GFPNonLinearAdView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPNonLinearAdView"},{"text":"]? { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"nonLinearViewList"}],"symbolKind":"property","title":"nonLinearViewList","role":"symbol","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nonLinearViewList","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"GFPNonLinearAdView","preciseIdentifier":"c:objc(cs)GFPNonLinearAdView"},{"text":"]?","kind":"text"}],"externalID":"c:objc(cs)GFPVideoAdInfo(py)nonLinearViewList","modules":[{"name":"GFPSDK"}]},"abstract":[{"text":"로드된 Remind Ad (Text, Banner) View","type":"text"}],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpvideoadinfo\/nonlinearviewlist"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpvideoadinfo\/nonlinearviewlist"]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdInfo"]]},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdInfo\/nonLinearViewList","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdInfo/nonLinearViewList":{"title":"nonLinearViewList","type":"topic","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdInfo\/nonLinearViewList","url":"\/documentation\/gfpsdk\/gfpvideoadinfo\/nonlinearviewlist","abstract":[{"text":"로드된 Remind Ad (Text, Banner) View","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"nonLinearViewList"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"GFPNonLinearAdView","preciseIdentifier":"c:objc(cs)GFPNonLinearAdView"},{"text":"]?","kind":"text"}],"kind":"symbol","navigatorTitle":[{"text":"nonLinearViewList","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdInfo":{"kind":"symbol","title":"GFPVideoAdInfo","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdInfo","role":"symbol","navigatorTitle":[{"text":"GFPVideoAdInfo","kind":"identifier"}],"type":"topic","url":"\/documentation\/gfpsdk\/gfpvideoadinfo","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPVideoAdInfo"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNonLinearAdView":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearAdView","title":"GFPNonLinearAdView","type":"topic","url":"\/documentation\/gfpsdk\/gfpnonlinearadview","abstract":[],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPNonLinearAdView"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPNonLinearAdView","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"nonLinearViewList"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"text":"nonLinearViewList","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<GFPNonLinearAdView *>"},{"kind":"text","text":" * "},{"text":"nonLinearViewList","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"value":"nonLinearViewList","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdInfo~1nonLinearViewList\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdInfo~1nonLinearViewList\/fragments","value":[{"text":"nonLinearViewList","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"GFPVideoAdInfo","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdInfo\/title"},{"value":[{"kind":"identifier","text":"GFPVideoAdInfo"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdInfo\/fragments"},{"value":[{"text":"GFPVideoAdInfo","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdInfo\/navigatorTitle"},{"op":"replace","value":"GFPNonLinearAdView","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearAdView\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearAdView\/fragments","value":[{"kind":"identifier","text":"GFPNonLinearAdView"}]},{"value":[{"text":"GFPNonLinearAdView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearAdView\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}