{"variants":[{"paths":["\/documentation\/gfpsdk\/gfpvideoaudiosettingtype\/auto"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpvideoaudiosettingtype\/auto"]}],"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAudioSettingType\/auto","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"modules":[{"name":"GFPSDK"}],"role":"symbol","roleHeading":"Type Property","title":"auto","externalID":"c:@E@GFPVideoAudioSettingType@GFPVideoAudioSettingTypeAuto","symbolKind":"property","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"auto"},{"text":": ","kind":"text"},{"text":"GFPVideoAudioSettingType","kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPVideoAudioSettingType"}],"navigatorTitle":[{"kind":"identifier","text":"GFPVideoAudioSettingTypeAuto"}]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"auto"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@GFPVideoAudioSettingType","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAudioSettingType","text":"GFPVideoAudioSettingType"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAudioSettingType"]]},"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAudioSettingType":{"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPVideoAudioSettingType","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/gfpsdk\/gfpvideoaudiosettingtype","title":"GFPVideoAudioSettingType","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAudioSettingType","type":"topic","navigatorTitle":[{"text":"GFPVideoAudioSettingType","kind":"identifier"}],"role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAudioSettingType/auto":{"navigatorTitle":[{"text":"GFPVideoAudioSettingTypeAuto","kind":"identifier"}],"title":"auto","abstract":[],"type":"topic","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAudioSettingType\/auto","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"auto","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPVideoAudioSettingType","text":"GFPVideoAudioSettingType"}],"url":"\/documentation\/gfpsdk\/gfpvideoaudiosettingtype\/auto","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"GFPVideoAudioSettingTypeAuto"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"GFPVideoAudioSettingTypeAuto","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"GFPVideoAudioSettingTypeAuto"}]}]}},{"op":"replace","value":"GFPVideoAudioSettingType","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAudioSettingType\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAudioSettingType\/fragments","op":"replace","value":[{"kind":"identifier","text":"GFPVideoAudioSettingType"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAudioSettingType\/navigatorTitle","value":[{"text":"GFPVideoAudioSettingType","kind":"identifier"}],"op":"replace"},{"value":"GFPVideoAudioSettingTypeAuto","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAudioSettingType~1auto\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAudioSettingType~1auto\/fragments","value":[{"kind":"identifier","text":"GFPVideoAudioSettingTypeAuto"}]}]}]}