{"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"impressionInfo"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdImpressionInfo","text":"GFPAdImpressionInfo"}],"roleHeading":"Instance Property","modules":[{"name":"GFPSDK"}],"role":"symbol","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"impressionInfo"}],"title":"impressionInfo","externalID":"c:objc(cs)GFPWaterfallConfig(py)impressionInfo"},"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPWaterfallConfig"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPWaterfallConfig\/impressionInfo"},"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"impressionInfo","kind":"identifier"},{"kind":"text","text":": "},{"text":"GFPAdImpressionInfo","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdImpressionInfo","preciseIdentifier":"c:objc(cs)GFPAdImpressionInfo","kind":"typeIdentifier"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpwaterfallconfig\/impressioninfo"]},{"paths":["\/documentation\/gfpsdk\/gfpwaterfallconfig\/impressioninfo"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPWaterfallConfig":{"navigatorTitle":[{"text":"GFPWaterfallConfig","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPWaterfallConfig","url":"\/documentation\/gfpsdk\/gfpwaterfallconfig","kind":"symbol","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"GFPWaterfallConfig","kind":"identifier"}],"title":"GFPWaterfallConfig","role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPWaterfallConfig/impressionInfo":{"navigatorTitle":[{"kind":"identifier","text":"impressionInfo"}],"type":"topic","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"impressionInfo","kind":"identifier"},{"text":": ","kind":"text"},{"text":"GFPAdImpressionInfo","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdImpressionInfo"}],"url":"\/documentation\/gfpsdk\/gfpwaterfallconfig\/impressioninfo","title":"impressionInfo","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPWaterfallConfig\/impressionInfo","role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdImpressionInfo":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"GFPAdImpressionInfo","kind":"identifier"}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"GFPAdImpressionInfo","kind":"identifier"}],"abstract":[{"type":"text","text":"GFPAdImpressionInfo"}],"role":"symbol","title":"GFPAdImpressionInfo","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdImpressionInfo","url":"\/documentation\/gfpsdk\/gfpadimpressioninfo"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"impressionInfo"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"impressionInfo","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdImpressionInfo","kind":"typeIdentifier","text":"GFPAdImpressionInfo","preciseIdentifier":"c:objc(cs)GFPAdImpressionInfo"},{"kind":"text","text":" * "},{"text":"impressionInfo","kind":"identifier"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPWaterfallConfig\/title","value":"GFPWaterfallConfig"},{"op":"replace","value":[{"kind":"identifier","text":"GFPWaterfallConfig"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPWaterfallConfig\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"GFPWaterfallConfig"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPWaterfallConfig\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPWaterfallConfig~1impressionInfo\/title","value":"impressionInfo"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPWaterfallConfig~1impressionInfo\/fragments","op":"replace","value":[{"text":"impressionInfo","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdImpressionInfo\/title","value":"GFPAdImpressionInfo"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdImpressionInfo\/fragments","op":"replace","value":[{"text":"GFPAdImpressionInfo","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdImpressionInfo\/navigatorTitle","value":[{"text":"GFPAdImpressionInfo","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}