{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPWaterfallConfig\/init(dictionary:error:)"},"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"?("},{"text":"dictionary","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"dict","kind":"internalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"error"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SA","text":"AutoreleasingUnsafeMutablePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"GFPError","kind":"typeIdentifier","preciseIdentifier":"c:@M@NaverAdsServices@objc(cs)GFPError"},{"text":"?>?)","kind":"text"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPWaterfallConfig"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpwaterfallconfig\/init(dictionary:error:)"]},{"paths":["\/documentation\/gfpsdk\/gfpwaterfallconfig\/init(dictionary:error:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"dictionary","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]?, "},{"text":"error","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SA","text":"AutoreleasingUnsafeMutablePointer"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@NaverAdsServices@objc(cs)GFPError","text":"GFPError"},{"text":"?>?)","kind":"text"}],"externalID":"c:objc(cs)GFPWaterfallConfig(im)initWithDictionary:error:","navigatorTitle":[{"kind":"identifier","text":"initWithDictionary:error:"}],"modules":[{"name":"GFPSDK"}],"title":"init(dictionary:error:)","roleHeading":"Initializer","symbolKind":"init","role":"symbol"},"sections":[],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPWaterfallConfig/init(dictionary:error:)":{"type":"topic","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"dictionary"},{"kind":"text","text":": ["},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]?, ","kind":"text"},{"text":"error","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AutoreleasingUnsafeMutablePointer","preciseIdentifier":"s:SA"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:@M@NaverAdsServices@objc(cs)GFPError","text":"GFPError","kind":"typeIdentifier"},{"text":"?>?)","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"initWithDictionary:error:"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPWaterfallConfig\/init(dictionary:error:)","role":"symbol","abstract":[],"title":"init(dictionary:error:)","url":"\/documentation\/gfpsdk\/gfpwaterfallconfig\/init(dictionary:error:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPWaterfallConfig":{"navigatorTitle":[{"text":"GFPWaterfallConfig","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPWaterfallConfig","url":"\/documentation\/gfpsdk\/gfpwaterfallconfig","kind":"symbol","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"GFPWaterfallConfig","kind":"identifier"}],"title":"GFPWaterfallConfig","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"initWithDictionary:error:","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithDictionary:error:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"text":") ","kind":"text"},{"text":"initWithDictionary:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSDictionary","kind":"typeIdentifier","text":"NSDictionary"},{"kind":"text","text":" *) "},{"text":"dict","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"error:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"GFPError","kind":"typeIdentifier","preciseIdentifier":"c:@M@NaverAdsServices@objc(cs)GFPError"},{"text":" * *) ","kind":"text"},{"kind":"internalParam","text":"error"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPWaterfallConfig~1init(dictionary:error:)\/title","op":"replace","value":"initWithDictionary:error:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDictionary:error:"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPWaterfallConfig~1init(dictionary:error:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPWaterfallConfig\/title","value":"GFPWaterfallConfig","op":"replace"},{"value":[{"text":"GFPWaterfallConfig","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPWaterfallConfig\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPWaterfallConfig\/navigatorTitle","value":[{"kind":"identifier","text":"GFPWaterfallConfig"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}