{"metadata":{"role":"collectionGroup","roleHeading":"API Collection","modules":[{"name":"GFPSDK"}],"title":"SetAlgebra Implementations"},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialStatus"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialStatus\/SetAlgebra-Implementations","interfaceLanguage":"swift"},"kind":"article","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpinterstitialstatus\/setalgebra-implementations"]}],"sections":[],"topicSections":[{"anchor":"Initializers","title":"Initializers","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialStatus\/init(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialStatus\/init(arrayLiteral:)"],"generated":true},{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialStatus\/isEmpty"]},{"anchor":"Instance-Methods","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialStatus\/isDisjoint(with:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialStatus\/isStrictSubset(of:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialStatus\/isStrictSuperset(of:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialStatus\/isSubset(of:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialStatus\/isSuperset(of:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialStatus\/subtract(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialStatus\/subtracting(_:)"],"generated":true,"title":"Instance Methods"}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPInterstitialStatus/isStrictSuperset(of:)":{"type":"topic","abstract":[],"title":"isStrictSuperset(of:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"isStrictSuperset","kind":"identifier"},{"kind":"text","text":"("},{"text":"of","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"url":"\/documentation\/gfpsdk\/gfpinterstitialstatus\/isstrictsuperset(of:)","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialStatus\/isStrictSuperset(of:)","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPInterstitialStatus":{"abstract":[],"url":"\/documentation\/gfpsdk\/gfpinterstitialstatus","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialStatus","role":"symbol","title":"GFPInterstitialStatus","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPInterstitialStatus"}],"navigatorTitle":[{"text":"GFPInterstitialStatus","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPInterstitialStatus/isSubset(of:)":{"url":"\/documentation\/gfpsdk\/gfpinterstitialstatus\/issubset(of:)","role":"symbol","type":"topic","abstract":[],"title":"isSubset(of:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isSubset","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"of"},{"text":": ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialStatus\/isSubset(of:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPInterstitialStatus/isDisjoint(with:)":{"kind":"symbol","title":"isDisjoint(with:)","url":"\/documentation\/gfpsdk\/gfpinterstitialstatus\/isdisjoint(with:)","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialStatus\/isDisjoint(with:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"isDisjoint","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPInterstitialStatus/isStrictSubset(of:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"isStrictSubset","kind":"identifier"},{"text":"(","kind":"text"},{"text":"of","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialStatus\/isStrictSubset(of:)","url":"\/documentation\/gfpsdk\/gfpinterstitialstatus\/isstrictsubset(of:)","kind":"symbol","role":"symbol","abstract":[],"type":"topic","title":"isStrictSubset(of:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPInterstitialStatus/subtracting(_:)":{"url":"\/documentation\/gfpsdk\/gfpinterstitialstatus\/subtracting(_:)","title":"subtracting(_:)","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialStatus\/subtracting(_:)","role":"symbol","kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"subtracting","kind":"identifier"},{"kind":"text","text":"("},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"Self","kind":"typeIdentifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPInterstitialStatus/init(arrayLiteral:)":{"role":"symbol","url":"\/documentation\/gfpsdk\/gfpinterstitialstatus\/init(arrayliteral:)","kind":"symbol","type":"topic","abstract":[],"title":"init(arrayLiteral:)","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialStatus\/init(arrayLiteral:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"arrayLiteral","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Self"},{"text":".","kind":"text"},{"preciseIdentifier":"s:s10SetAlgebraP7ElementQa","kind":"typeIdentifier","text":"Element"},{"kind":"text","text":"...)"}],"conformance":{"availabilityPrefix":[{"text":"Available when","type":"text"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}],"constraints":[{"type":"codeVoice","code":"ArrayLiteralElement"},{"text":" is ","type":"text"},{"code":"Self.Element","type":"codeVoice"},{"type":"text","text":"."}]}},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPInterstitialStatus/init(_:)":{"type":"topic","abstract":[],"title":"init(_:)","fragments":[{"text":"init","kind":"identifier"},{"text":"<","kind":"text"},{"text":"S","kind":"genericParameter"},{"kind":"text","text":">("},{"text":"S","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/gfpsdk\/gfpinterstitialstatus\/init(_:)","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialStatus\/init(_:)","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPInterstitialStatus/subtract(_:)":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialStatus\/subtract(_:)","url":"\/documentation\/gfpsdk\/gfpinterstitialstatus\/subtract(_:)","type":"topic","role":"symbol","kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"subtract","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":")"}],"title":"subtract(_:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPInterstitialStatus/isSuperset(of:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isSuperset"},{"kind":"text","text":"("},{"text":"of","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Self"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialStatus\/isSuperset(of:)","url":"\/documentation\/gfpsdk\/gfpinterstitialstatus\/issuperset(of:)","kind":"symbol","role":"symbol","abstract":[],"type":"topic","title":"isSuperset(of:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPInterstitialStatus/isEmpty":{"type":"topic","abstract":[],"title":"isEmpty","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEmpty","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"url":"\/documentation\/gfpsdk\/gfpinterstitialstatus\/isempty","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialStatus\/isEmpty","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"GFPInterstitialStatus","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialStatus\/title"},{"value":[{"text":"GFPInterstitialStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialStatus\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"GFPInterstitialStatus"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialStatus\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}