{"variants":[{"paths":["\/documentation\/gfpsdk\/gfpinterstitialstatus\/subtract(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"Inherited from "},{"code":"SetAlgebra.subtract(_:)","type":"codeVoice"},{"text":".","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"mutating"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"subtract"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"other","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialStatus\/subtract(_:)"},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialStatus","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialStatus\/SetAlgebra-Implementations"]]},"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"subtract"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":")"}],"extendedModule":"Swift","role":"symbol","roleHeading":"Instance Method","externalID":"s:s10SetAlgebraPsE8subtractyyxF::SYNTHESIZED::c:@E@GFPInterstitialStatus","symbolKind":"method","title":"subtract(_:)","modules":[{"name":"GFPSDK","relatedModules":["Swift"]}]},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPInterstitialStatus":{"abstract":[],"url":"\/documentation\/gfpsdk\/gfpinterstitialstatus","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialStatus","role":"symbol","title":"GFPInterstitialStatus","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPInterstitialStatus"}],"navigatorTitle":[{"text":"GFPInterstitialStatus","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPInterstitialStatus/SetAlgebra-Implementations":{"title":"SetAlgebra Implementations","kind":"article","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialStatus\/SetAlgebra-Implementations","role":"collectionGroup","abstract":[],"url":"\/documentation\/gfpsdk\/gfpinterstitialstatus\/setalgebra-implementations"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPInterstitialStatus/subtract(_:)":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialStatus\/subtract(_:)","url":"\/documentation\/gfpsdk\/gfpinterstitialstatus\/subtract(_:)","type":"topic","role":"symbol","kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"subtract","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":")"}],"title":"subtract(_:)"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialStatus\/title","op":"replace","value":"GFPInterstitialStatus"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialStatus\/fragments","op":"replace","value":[{"text":"GFPInterstitialStatus","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"GFPInterstitialStatus"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialStatus\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}