{"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRequestType"]]},"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/gfpsdk\/gfprequesttype\/skadnregister"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gfpsdk\/gfprequesttype\/skadnregister"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"skadnRegister","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"skadnRegister","kind":"identifier"},{"text":": ","kind":"text"},{"text":"GFPRequestType","preciseIdentifier":"c:@E@GFPRequestType","kind":"typeIdentifier"}],"roleHeading":"Type Property","role":"symbol","externalID":"c:@E@GFPRequestType@GFPRequestSKADNRegister","symbolKind":"property","navigatorTitle":[{"text":"GFPRequestSKADNRegister","kind":"identifier"}],"modules":[{"name":"GFPSDK"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRequestType\/skadnRegister"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"skadnRegister","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"GFPRequestType","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRequestType","preciseIdentifier":"c:@E@GFPRequestType"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRequestType/skadnRegister":{"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"skadnRegister","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@GFPRequestType","text":"GFPRequestType","kind":"typeIdentifier"}],"role":"symbol","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRequestType\/skadnRegister","kind":"symbol","type":"topic","url":"\/documentation\/gfpsdk\/gfprequesttype\/skadnregister","title":"skadnRegister","navigatorTitle":[{"text":"GFPRequestSKADNRegister","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRequestType":{"abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRequestType","type":"topic","title":"GFPRequestType","navigatorTitle":[{"text":"GFPRequestType","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/gfpsdk\/gfprequesttype","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPRequestType"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"GFPRequestSKADNRegister"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"GFPRequestSKADNRegister","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"GFPRequestSKADNRegister","kind":"identifier"}],"platforms":["iOS"]}]},"op":"replace"},{"value":"GFPRequestSKADNRegister","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRequestType~1skadnRegister\/title"},{"value":[{"text":"GFPRequestSKADNRegister","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRequestType~1skadnRegister\/fragments","op":"replace"},{"value":"GFPRequestType","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRequestType\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRequestType\/fragments","value":[{"kind":"identifier","text":"GFPRequestType"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRequestType\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"GFPRequestType"}]}]}]}