{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"weak","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bannerDelegate"},{"kind":"text","text":": (any "},{"text":"GFPBannerViewDelegate","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerViewDelegate","preciseIdentifier":"c:objc(pl)GFPBannerViewDelegate"},{"kind":"text","text":")? { "},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}]}]}],"metadata":{"title":"bannerDelegate","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"bannerDelegate","kind":"identifier"},{"text":": (any ","kind":"text"},{"kind":"typeIdentifier","text":"GFPBannerViewDelegate","preciseIdentifier":"c:objc(pl)GFPBannerViewDelegate"},{"text":")?","kind":"text"}],"roleHeading":"Instance Property","role":"symbol","externalID":"c:objc(cs)GFPAdLoader(py)bannerDelegate","extendedModule":"GFPSDK","symbolKind":"property","navigatorTitle":[{"text":"bannerDelegate","kind":"identifier"}],"modules":[{"name":"GFPSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoader"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoader\/bannerDelegate"},"kind":"symbol","variants":[{"paths":["\/documentation\/gfpsdk\/gfpadloader\/bannerdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpadloader\/bannerdelegate"]}],"sections":[],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdLoader/bannerDelegate":{"type":"topic","abstract":[],"title":"bannerDelegate","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"bannerDelegate","kind":"identifier"},{"text":": (any ","kind":"text"},{"kind":"typeIdentifier","text":"GFPBannerViewDelegate","preciseIdentifier":"c:objc(pl)GFPBannerViewDelegate"},{"kind":"text","text":")?"}],"url":"\/documentation\/gfpsdk\/gfpadloader\/bannerdelegate","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoader\/bannerDelegate","navigatorTitle":[{"kind":"identifier","text":"bannerDelegate"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdLoader":{"navigatorTitle":[{"text":"GFPAdLoader","kind":"identifier"}],"kind":"symbol","title":"GFPAdLoader","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoader","url":"\/documentation\/gfpsdk\/gfpadloader","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPAdLoader"}],"type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerViewDelegate":{"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPBannerViewDelegate","kind":"identifier"}],"kind":"symbol","abstract":[],"url":"\/documentation\/gfpsdk\/gfpbannerviewdelegate","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerViewDelegate","title":"GFPBannerViewDelegate","type":"topic","navigatorTitle":[{"text":"GFPBannerViewDelegate","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"bannerDelegate","path":"\/metadata\/title","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"bannerDelegate","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"weak"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)GFPBannerViewDelegate","text":"id<GFPBannerViewDelegate>"},{"text":" ","kind":"text"},{"text":"bannerDelegate","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoader~1bannerDelegate\/title","value":"bannerDelegate","op":"replace"},{"value":[{"text":"bannerDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoader~1bannerDelegate\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoader\/title","value":"GFPAdLoader"},{"op":"replace","value":[{"text":"GFPAdLoader","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoader\/fragments"},{"value":[{"kind":"identifier","text":"GFPAdLoader"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoader\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerViewDelegate\/title","value":"GFPBannerViewDelegate","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerViewDelegate\/fragments","value":[{"kind":"identifier","text":"GFPBannerViewDelegate"}],"op":"replace"},{"value":[{"kind":"identifier","text":"GFPBannerViewDelegate"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerViewDelegate\/navigatorTitle"}]}]}