{"abstract":[{"type":"text","text":"통합 로더에 광고 요청, WF 단계를 건너뛰기 위한 요청"}],"sections":[],"metadata":{"modules":[{"name":"GFPSDK"}],"role":"symbol","extendedModule":"GFPSDK","roleHeading":"Instance Method","title":"loadAdWith(dict:)","externalID":"c:@CM@GFPSDK@@objc(cs)GFPAdLoader(im)loadAdWithDict:","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"loadAdWith"},{"kind":"text","text":"("},{"kind":"externalParam","text":"dict"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"])"}],"navigatorTitle":[{"text":"loadAdWithDict:","kind":"identifier"}]},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoader\/loadAdWith(dict:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadAdWith"},{"kind":"text","text":"("},{"text":"dict","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"preloadWaterfallResponse"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"])"}],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"서비스 측에서 미리 로드된 WF 전문"}],"type":"paragraph"}],"name":"preloadWaterfallResponse"}],"kind":"parameters"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoader"]]},"variants":[{"paths":["\/documentation\/gfpsdk\/gfpadloader\/loadadwith(dict:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gfpsdk\/gfpadloader\/loadadwith(dict:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdLoader/loadAdWith(dict:)":{"type":"topic","title":"loadAdWith(dict:)","abstract":[{"type":"text","text":"통합 로더에 광고 요청, WF 단계를 건너뛰기 위한 요청"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"loadAdWith","kind":"identifier"},{"text":"(","kind":"text"},{"text":"dict","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"kind":"text","text":"])"}],"url":"\/documentation\/gfpsdk\/gfpadloader\/loadadwith(dict:)","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoader\/loadAdWith(dict:)","navigatorTitle":[{"text":"loadAdWithDict:","kind":"identifier"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdLoader":{"navigatorTitle":[{"text":"GFPAdLoader","kind":"identifier"}],"kind":"symbol","title":"GFPAdLoader","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoader","url":"\/documentation\/gfpsdk\/gfpadloader","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPAdLoader"}],"type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"loadAdWithDict:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"loadAdWithDict:","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"loadAdWithDict:"},{"kind":"text","text":"("},{"text":"NSDictionary","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDictionary"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"preloadWaterfallResponse"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"서비스 측에서 미리 로드된 WF 전문","type":"text"}]}],"name":"preloadWaterfallResponse"}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoader~1loadAdWith(dict:)\/title","value":"loadAdWithDict:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoader~1loadAdWith(dict:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"loadAdWithDict:"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoader\/title","op":"replace","value":"GFPAdLoader"},{"value":[{"text":"GFPAdLoader","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoader\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"GFPAdLoader"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoader\/navigatorTitle"}]}]}