{"abstract":[{"type":"text","text":"통합 로더에 광고 요청, WF 단계를 건너뛰기 위한 요청"}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoader"]]},"sections":[],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpadloader\/loadadwith(data:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gfpsdk\/gfpadloader\/loadadwith(data:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"loadAdWith"},{"text":"(","kind":"text"},{"text":"data","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"preloadWaterfallResponse"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier","text":"Data"},{"kind":"text","text":")"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"preloadWaterfallResponse","content":[{"type":"paragraph","inlineContent":[{"text":"서비스 측에서 미리 로드된 WF 전문","type":"text"}]}]}]}],"metadata":{"externalID":"c:@CM@GFPSDK@@objc(cs)GFPAdLoader(im)loadAdWithData:","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"loadAdWith"},{"text":"(","kind":"text"},{"text":"data","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"kind":"text","text":")"}],"extendedModule":"GFPSDK","modules":[{"name":"GFPSDK"}],"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"loadAdWithData:"}],"role":"symbol","title":"loadAdWith(data:)","roleHeading":"Instance Method"},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoader\/loadAdWith(data:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdLoader/loadAdWith(data:)":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"loadAdWith","kind":"identifier"},{"kind":"text","text":"("},{"text":"data","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier","text":"Data"},{"text":")","kind":"text"}],"title":"loadAdWith(data:)","type":"topic","navigatorTitle":[{"text":"loadAdWithData:","kind":"identifier"}],"abstract":[{"type":"text","text":"통합 로더에 광고 요청, WF 단계를 건너뛰기 위한 요청"}],"url":"\/documentation\/gfpsdk\/gfpadloader\/loadadwith(data:)","kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoader\/loadAdWith(data:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdLoader":{"navigatorTitle":[{"text":"GFPAdLoader","kind":"identifier"}],"kind":"symbol","title":"GFPAdLoader","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoader","url":"\/documentation\/gfpsdk\/gfpadloader","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPAdLoader"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","value":"loadAdWithData:","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"loadAdWithData:"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"loadAdWithData:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSData","text":"NSData"},{"text":" *) ","kind":"text"},{"text":"preloadWaterfallResponse","kind":"internalParam"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"preloadWaterfallResponse","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"서비스 측에서 미리 로드된 WF 전문"}]}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoader~1loadAdWith(data:)\/title","value":"loadAdWithData:"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoader~1loadAdWith(data:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"loadAdWithData:","kind":"identifier"}]},{"value":"GFPAdLoader","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoader\/title"},{"value":[{"text":"GFPAdLoader","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoader\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoader\/navigatorTitle","value":[{"text":"GFPAdLoader","kind":"identifier"}]}]}]}