{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoader\/setBannerDelegate(_:bannerOptions:)"},"metadata":{"externalID":"c:objc(cs)GFPAdLoader(im)setBannerDelegate:bannerOptions:","roleHeading":"Instance Method","modules":[{"name":"GFPSDK"}],"role":"symbol","title":"setBannerDelegate(_:bannerOptions:)","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"setBannerDelegate"},{"kind":"text","text":"(any "},{"text":"GFPBannerViewDelegate","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)GFPBannerViewDelegate"},{"kind":"text","text":", "},{"text":"bannerOptions","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"GFPAdBannerOptions","preciseIdentifier":"c:objc(cs)GFPAdBannerOptions"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"setBannerDelegate:bannerOptions:","kind":"identifier"}]},"abstract":[{"type":"text","text":"통합 로더를 통해 배너 광고 로드 시 사용."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"setBannerDelegate","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"bannerDelegate","kind":"internalParam"},{"kind":"text","text":": any "},{"text":"GFPBannerViewDelegate","preciseIdentifier":"c:objc(pl)GFPBannerViewDelegate","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerViewDelegate","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"bannerOptions","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"GFPAdBannerOptions","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdBannerOptions","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdBannerOptions"},{"text":")","kind":"text"}]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"광고 요청 결과를 받을 수 있는 delegate."}]}],"name":"bannerDelegate"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"배너 광고 옵션."}]}],"name":"bannerOptions"}],"kind":"parameters"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoader"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpadloader\/setbannerdelegate(_:banneroptions:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpadloader\/setbannerdelegate(_:banneroptions:)"]}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerViewDelegate":{"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPBannerViewDelegate","kind":"identifier"}],"kind":"symbol","abstract":[],"url":"\/documentation\/gfpsdk\/gfpbannerviewdelegate","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerViewDelegate","title":"GFPBannerViewDelegate","type":"topic","navigatorTitle":[{"text":"GFPBannerViewDelegate","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdBannerOptions":{"navigatorTitle":[{"text":"GFPAdBannerOptions","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"GFPAdBannerOptions","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdBannerOptions","type":"topic","abstract":[],"url":"\/documentation\/gfpsdk\/gfpadbanneroptions","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"GFPAdBannerOptions","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdLoader/setBannerDelegate(_:bannerOptions:)":{"abstract":[{"type":"text","text":"통합 로더를 통해 배너 광고 로드 시 사용."}],"url":"\/documentation\/gfpsdk\/gfpadloader\/setbannerdelegate(_:banneroptions:)","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoader\/setBannerDelegate(_:bannerOptions:)","role":"symbol","title":"setBannerDelegate(_:bannerOptions:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setBannerDelegate","kind":"identifier"},{"text":"(any ","kind":"text"},{"text":"GFPBannerViewDelegate","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)GFPBannerViewDelegate"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"bannerOptions"},{"text":": ","kind":"text"},{"text":"GFPAdBannerOptions","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdBannerOptions"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"setBannerDelegate:bannerOptions:","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdLoader":{"navigatorTitle":[{"text":"GFPAdLoader","kind":"identifier"}],"kind":"symbol","title":"GFPAdLoader","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoader","url":"\/documentation\/gfpsdk\/gfpadloader","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPAdLoader"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","value":"setBannerDelegate:bannerOptions:","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"setBannerDelegate:bannerOptions:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"setBannerDelegate:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id<GFPBannerViewDelegate>","kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)GFPBannerViewDelegate"},{"text":") ","kind":"text"},{"text":"bannerDelegate","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"bannerOptions:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdBannerOptions","text":"GFPAdBannerOptions","preciseIdentifier":"c:objc(cs)GFPAdBannerOptions","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"bannerOptions"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"bannerDelegate","content":[{"type":"paragraph","inlineContent":[{"text":"광고 요청 결과를 받을 수 있는 delegate.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"배너 광고 옵션.","type":"text"}]}],"name":"bannerOptions"}]}},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerViewDelegate\/title","value":"GFPBannerViewDelegate"},{"value":[{"text":"GFPBannerViewDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerViewDelegate\/fragments"},{"value":[{"text":"GFPBannerViewDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerViewDelegate\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdBannerOptions\/title","value":"GFPAdBannerOptions","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdBannerOptions\/fragments","value":[{"text":"GFPAdBannerOptions","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdBannerOptions\/navigatorTitle","op":"replace","value":[{"text":"GFPAdBannerOptions","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoader~1setBannerDelegate(_:bannerOptions:)\/title","value":"setBannerDelegate:bannerOptions:","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoader~1setBannerDelegate(_:bannerOptions:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"setBannerDelegate:bannerOptions:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoader\/title","value":"GFPAdLoader"},{"value":[{"text":"GFPAdLoader","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoader\/fragments"},{"value":[{"kind":"identifier","text":"GFPAdLoader"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoader\/navigatorTitle"}]}]}