{"kind":"symbol","metadata":{"symbolKind":"method","externalID":"c:objc(cs)GFPAdLoader(im)setNativeDelegate:nativeOptions:","navigatorTitle":[{"text":"setNativeDelegate:nativeOptions:","kind":"identifier"}],"modules":[{"name":"GFPSDK"}],"role":"symbol","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setNativeDelegate"},{"kind":"text","text":"(any "},{"preciseIdentifier":"c:objc(pl)GFPNativeAdDelegate","kind":"typeIdentifier","text":"GFPNativeAdDelegate"},{"text":", ","kind":"text"},{"text":"nativeOptions","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"GFPAdNativeOptions","kind":"typeIdentifier","preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPAdNativeOptions"},{"text":"?)","kind":"text"}],"title":"setNativeDelegate(_:nativeOptions:)"},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoader"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setNativeDelegate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"nativeDelegate","kind":"internalParam"},{"kind":"text","text":": any "},{"text":"GFPNativeAdDelegate","preciseIdentifier":"c:objc(pl)GFPNativeAdDelegate","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdDelegate"},{"kind":"text","text":", "},{"text":"nativeOptions","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"GFPAdNativeOptions","preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPAdNativeOptions","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdNativeOptions","kind":"typeIdentifier"},{"text":"?)","kind":"text"}]}],"kind":"declarations"},{"parameters":[{"name":"nativeDelegate","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"광고 요청 결과를 받을 수 있는 delegate."}]}]},{"name":"nativeOptions","content":[{"inlineContent":[{"type":"text","text":"네이티브 광고 옵션 설정"}],"type":"paragraph"}]}],"kind":"parameters"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpadloader\/setnativedelegate(_:nativeoptions:)"]},{"paths":["\/documentation\/gfpsdk\/gfpadloader\/setnativedelegate(_:nativeoptions:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"type":"text","text":"통합 로더를 통해 네이티브 로드 시 사용."}],"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoader\/setNativeDelegate(_:nativeOptions:)","interfaceLanguage":"swift"},"sections":[],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdNativeOptions":{"navigatorTitle":[{"kind":"identifier","text":"GFPAdNativeOptions"}],"url":"\/documentation\/gfpsdk\/gfpadnativeoptions","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPAdNativeOptions","kind":"identifier"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdNativeOptions","abstract":[],"title":"GFPAdNativeOptions"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdLoader":{"navigatorTitle":[{"text":"GFPAdLoader","kind":"identifier"}],"kind":"symbol","title":"GFPAdLoader","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoader","url":"\/documentation\/gfpsdk\/gfpadloader","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPAdLoader"}],"type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdDelegate":{"abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdDelegate","url":"\/documentation\/gfpsdk\/gfpnativeaddelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPNativeAdDelegate"}],"role":"symbol","navigatorTitle":[{"text":"GFPNativeAdDelegate","kind":"identifier"}],"type":"topic","kind":"symbol","title":"GFPNativeAdDelegate"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdLoader/setNativeDelegate(_:nativeOptions:)":{"type":"topic","title":"setNativeDelegate(_:nativeOptions:)","abstract":[{"type":"text","text":"통합 로더를 통해 네이티브 로드 시 사용."}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setNativeDelegate"},{"kind":"text","text":"(any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)GFPNativeAdDelegate","text":"GFPNativeAdDelegate"},{"kind":"text","text":", "},{"text":"nativeOptions","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"GFPAdNativeOptions","kind":"typeIdentifier","preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPAdNativeOptions"},{"kind":"text","text":"?)"}],"url":"\/documentation\/gfpsdk\/gfpadloader\/setnativedelegate(_:nativeoptions:)","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoader\/setNativeDelegate(_:nativeOptions:)","navigatorTitle":[{"text":"setNativeDelegate:nativeOptions:","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"setNativeDelegate:nativeOptions:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setNativeDelegate:nativeOptions:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"setNativeDelegate:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<GFPNativeAdDelegate>","preciseIdentifier":"c:Qoobjc(pl)GFPNativeAdDelegate"},{"text":") ","kind":"text"},{"text":"nativeDelegate","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"nativeOptions:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPAdNativeOptions","text":"GFPAdNativeOptions","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdNativeOptions"},{"text":" *) ","kind":"text"},{"text":"nativeOptions","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"nativeDelegate","content":[{"type":"paragraph","inlineContent":[{"text":"광고 요청 결과를 받을 수 있는 delegate.","type":"text"}]}]},{"content":[{"inlineContent":[{"text":"네이티브 광고 옵션 설정","type":"text"}],"type":"paragraph"}],"name":"nativeOptions"}],"kind":"parameters"},"op":"replace"},{"op":"replace","value":"GFPAdNativeOptions","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdNativeOptions\/title"},{"op":"replace","value":[{"text":"GFPAdNativeOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdNativeOptions\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdNativeOptions\/navigatorTitle","value":[{"text":"GFPAdNativeOptions","kind":"identifier"}]},{"value":"GFPAdLoader","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoader\/title"},{"op":"replace","value":[{"text":"GFPAdLoader","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoader\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoader\/navigatorTitle","value":[{"text":"GFPAdLoader","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdDelegate\/title","value":"GFPNativeAdDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdDelegate\/fragments","value":[{"kind":"identifier","text":"GFPNativeAdDelegate"}]},{"op":"replace","value":[{"text":"GFPNativeAdDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdDelegate\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoader~1setNativeDelegate(_:nativeOptions:)\/title","value":"setNativeDelegate:nativeOptions:"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoader~1setNativeDelegate(_:nativeOptions:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"setNativeDelegate:nativeOptions:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}