{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpadloader\/setnativesimpledelegate(_:nativesimpleoptions:)"]},{"paths":["\/documentation\/gfpsdk\/gfpadloader\/setnativesimpledelegate(_:nativesimpleoptions:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoader"]]},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setNativeSimpleDelegate"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"nativeSimpleDelegate","kind":"internalParam"},{"text":": any ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdDelegate","preciseIdentifier":"c:objc(pl)GFPNativeSimpleAdDelegate","text":"GFPNativeSimpleAdDelegate"},{"kind":"text","text":", "},{"text":"nativeSimpleOptions","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"GFPAdNativeSimpleOptions","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdNativeSimpleOptions","preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPAdNativeSimpleOptions"},{"kind":"text","text":"?)"}]}],"kind":"declarations"},{"parameters":[{"name":"nativeSimpleDelegate","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"광고 요청 결과를 받을 수 있는 delegate."}]}]},{"content":[{"inlineContent":[{"type":"text","text":"네이티브 광고 옵션 설정 (SimpleAdRenderingSetting - Default : YES)"}],"type":"paragraph"}],"name":"nativeSimpleOptions"}],"kind":"parameters"}],"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoader\/setNativeSimpleDelegate(_:nativeSimpleOptions:)","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"type":"text","text":"통합 로더를 통해 네이티브 이미지형 (Native Simple) 로드 시 사용."}],"metadata":{"role":"symbol","modules":[{"name":"GFPSDK"}],"roleHeading":"Instance Method","externalID":"c:objc(cs)GFPAdLoader(im)setNativeSimpleDelegate:nativeSimpleOptions:","title":"setNativeSimpleDelegate(_:nativeSimpleOptions:)","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"setNativeSimpleDelegate:nativeSimpleOptions:"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setNativeSimpleDelegate","kind":"identifier"},{"kind":"text","text":"(any "},{"preciseIdentifier":"c:objc(pl)GFPNativeSimpleAdDelegate","kind":"typeIdentifier","text":"GFPNativeSimpleAdDelegate"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"nativeSimpleOptions"},{"text":": ","kind":"text"},{"text":"GFPAdNativeSimpleOptions","kind":"typeIdentifier","preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPAdNativeSimpleOptions"},{"text":"?)","kind":"text"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeSimpleAdDelegate":{"kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdDelegate","role":"symbol","navigatorTitle":[{"text":"GFPNativeSimpleAdDelegate","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpnativesimpleaddelegate","title":"GFPNativeSimpleAdDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPNativeSimpleAdDelegate"}],"type":"topic","abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdLoader/setNativeSimpleDelegate(_:nativeSimpleOptions:)":{"type":"topic","title":"setNativeSimpleDelegate(_:nativeSimpleOptions:)","abstract":[{"text":"통합 로더를 통해 네이티브 이미지형 (Native Simple) 로드 시 사용.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setNativeSimpleDelegate","kind":"identifier"},{"kind":"text","text":"(any "},{"text":"GFPNativeSimpleAdDelegate","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)GFPNativeSimpleAdDelegate"},{"kind":"text","text":", "},{"kind":"externalParam","text":"nativeSimpleOptions"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPAdNativeSimpleOptions","text":"GFPAdNativeSimpleOptions","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"url":"\/documentation\/gfpsdk\/gfpadloader\/setnativesimpledelegate(_:nativesimpleoptions:)","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoader\/setNativeSimpleDelegate(_:nativeSimpleOptions:)","navigatorTitle":[{"text":"setNativeSimpleDelegate:nativeSimpleOptions:","kind":"identifier"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdNativeSimpleOptions":{"url":"\/documentation\/gfpsdk\/gfpadnativesimpleoptions","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdNativeSimpleOptions","type":"topic","kind":"symbol","title":"GFPAdNativeSimpleOptions","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPAdNativeSimpleOptions"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"GFPAdNativeSimpleOptions"}],"role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdLoader":{"navigatorTitle":[{"text":"GFPAdLoader","kind":"identifier"}],"kind":"symbol","title":"GFPAdLoader","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoader","url":"\/documentation\/gfpsdk\/gfpadloader","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPAdLoader"}],"type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"setNativeSimpleDelegate:nativeSimpleOptions:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"text":"- ","kind":"text"},{"text":"setNativeSimpleDelegate:nativeSimpleOptions:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"text":"setNativeSimpleDelegate:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id<GFPNativeSimpleAdDelegate>","preciseIdentifier":"c:Qoobjc(pl)GFPNativeSimpleAdDelegate","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"nativeSimpleDelegate"},{"text":" ","kind":"text"},{"text":"nativeSimpleOptions:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"GFPAdNativeSimpleOptions","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdNativeSimpleOptions","preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPAdNativeSimpleOptions"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"nativeSimpleOptions"},{"kind":"text","text":";"}]}]}},{"value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"광고 요청 결과를 받을 수 있는 delegate.","type":"text"}]}],"name":"nativeSimpleDelegate"},{"name":"nativeSimpleOptions","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"네이티브 광고 옵션 설정 (SimpleAdRenderingSetting - Default : YES)"}]}]}],"kind":"parameters"},"path":"\/primaryContentSections\/1","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdDelegate\/title","value":"GFPNativeSimpleAdDelegate"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdDelegate\/fragments","value":[{"kind":"identifier","text":"GFPNativeSimpleAdDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdDelegate\/navigatorTitle","op":"replace","value":[{"text":"GFPNativeSimpleAdDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoader~1setNativeSimpleDelegate(_:nativeSimpleOptions:)\/title","op":"replace","value":"setNativeSimpleDelegate:nativeSimpleOptions:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"setNativeSimpleDelegate:nativeSimpleOptions:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoader~1setNativeSimpleDelegate(_:nativeSimpleOptions:)\/fragments"},{"value":"GFPAdNativeSimpleOptions","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdNativeSimpleOptions\/title","op":"replace"},{"value":[{"kind":"identifier","text":"GFPAdNativeSimpleOptions"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdNativeSimpleOptions\/fragments"},{"op":"replace","value":[{"text":"GFPAdNativeSimpleOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdNativeSimpleOptions\/navigatorTitle"},{"value":"GFPAdLoader","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoader\/title"},{"op":"replace","value":[{"kind":"identifier","text":"GFPAdLoader"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoader\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoader\/navigatorTitle","value":[{"kind":"identifier","text":"GFPAdLoader"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}