{"sections":[],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/gfpsdk\/gfpvideooptions\/createglobaloptions(with:usecustoncontrolview:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gfpsdk\/gfpvideooptions\/createglobaloptions(with:usecustoncontrolview:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"createGlobalOptions"},{"kind":"text","text":"("},{"text":"with","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"viewType"},{"kind":"text","text":": "},{"text":"GFPVideoViewType","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoViewType","kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPVideoViewType"},{"text":", ","kind":"text"},{"text":"useCustonControlView","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"useCustomControlView","kind":"internalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Self"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoOptions"]]},"metadata":{"roleHeading":"Type Method","role":"symbol","title":"createGlobalOptions(with:useCustonControlView:)","modules":[{"name":"GFPSDK"}],"symbolKind":"method","navigatorTitle":[{"text":"createGlobalOptionsWithViewType:useCustonControlView:","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"createGlobalOptions"},{"kind":"text","text":"("},{"text":"with","kind":"externalParam"},{"kind":"text","text":": "},{"text":"GFPVideoViewType","kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPVideoViewType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"useCustonControlView"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Self"}],"externalID":"c:objc(cs)GFPVideoOptions(cm)createGlobalOptionsWithViewType:useCustonControlView:"},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoOptions\/createGlobalOptions(with:useCustonControlView:)","interfaceLanguage":"swift"},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoViewType":{"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPVideoViewType"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"GFPVideoViewType"}],"title":"GFPVideoViewType","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoViewType","url":"\/documentation\/gfpsdk\/gfpvideoviewtype","kind":"symbol","role":"symbol","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoOptions":{"type":"topic","url":"\/documentation\/gfpsdk\/gfpvideooptions","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoOptions","role":"symbol","kind":"symbol","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPVideoOptions","kind":"identifier"}],"title":"GFPVideoOptions","navigatorTitle":[{"text":"GFPVideoOptions","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoOptions/createGlobalOptions(with:useCustonControlView:)":{"title":"createGlobalOptions(with:useCustonControlView:)","url":"\/documentation\/gfpsdk\/gfpvideooptions\/createglobaloptions(with:usecustoncontrolview:)","kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createGlobalOptions"},{"kind":"text","text":"("},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"GFPVideoViewType","preciseIdentifier":"c:@E@GFPVideoViewType","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"useCustonControlView","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Self","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoOptions\/createGlobalOptions(with:useCustonControlView:)","navigatorTitle":[{"text":"createGlobalOptionsWithViewType:useCustonControlView:","kind":"identifier"}],"abstract":[]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Type Method","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"createGlobalOptionsWithViewType:useCustonControlView:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"text":"createGlobalOptionsWithViewType:useCustonControlView:","kind":"identifier"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"createGlobalOptionsWithViewType:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@E@GFPVideoViewType","kind":"typeIdentifier","text":"GFPVideoViewType","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoViewType"},{"kind":"text","text":") "},{"kind":"internalParam","text":"viewType"},{"text":" ","kind":"text"},{"kind":"identifier","text":"useCustonControlView:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"useCustomControlView"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"value":"GFPVideoViewType","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoViewType\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoViewType\/fragments","value":[{"kind":"identifier","text":"GFPVideoViewType"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoViewType\/navigatorTitle","value":[{"kind":"identifier","text":"GFPVideoViewType"}],"op":"replace"},{"value":"GFPVideoOptions","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoOptions\/title"},{"value":[{"text":"GFPVideoOptions","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoOptions\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoOptions\/navigatorTitle","value":[{"text":"GFPVideoOptions","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoOptions~1createGlobalOptions(with:useCustonControlView:)\/title","value":"createGlobalOptionsWithViewType:useCustonControlView:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoOptions~1createGlobalOptions(with:useCustonControlView:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"createGlobalOptionsWithViewType:useCustonControlView:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}