{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpvideooptions\/createglobaloptions(with:)"]},{"paths":["\/documentation\/gfpsdk\/gfpvideooptions\/createglobaloptions(with:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoOptions"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"createGlobalOptions","kind":"identifier"},{"kind":"text","text":"("},{"text":"with","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"viewType","kind":"internalParam"},{"kind":"text","text":": "},{"text":"GFPVideoViewType","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoViewType","kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPVideoViewType"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Self"}],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoOptions\/createGlobalOptions(with:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"title":"createGlobalOptions(with:)","symbolKind":"method","modules":[{"name":"GFPSDK"}],"role":"symbol","externalID":"c:objc(cs)GFPVideoOptions(cm)createGlobalOptionsWithViewType:","roleHeading":"Type Method","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createGlobalOptions"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"text":": ","kind":"text"},{"text":"GFPVideoViewType","kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPVideoViewType"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Self"}],"navigatorTitle":[{"kind":"identifier","text":"createGlobalOptionsWithViewType:"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoViewType":{"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPVideoViewType"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"GFPVideoViewType"}],"title":"GFPVideoViewType","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoViewType","url":"\/documentation\/gfpsdk\/gfpvideoviewtype","kind":"symbol","role":"symbol","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoOptions":{"type":"topic","url":"\/documentation\/gfpsdk\/gfpvideooptions","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoOptions","role":"symbol","kind":"symbol","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPVideoOptions","kind":"identifier"}],"title":"GFPVideoOptions","navigatorTitle":[{"text":"GFPVideoOptions","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoOptions/createGlobalOptions(with:)":{"title":"createGlobalOptions(with:)","url":"\/documentation\/gfpsdk\/gfpvideooptions\/createglobaloptions(with:)","kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"createGlobalOptions"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"with"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"GFPVideoViewType","preciseIdentifier":"c:@E@GFPVideoViewType"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Self"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoOptions\/createGlobalOptions(with:)","navigatorTitle":[{"text":"createGlobalOptionsWithViewType:","kind":"identifier"}],"abstract":[]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"createGlobalOptionsWithViewType:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"+ ","kind":"text"},{"text":"createGlobalOptionsWithViewType:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"kind":"identifier","text":"createGlobalOptionsWithViewType:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@E@GFPVideoViewType","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoViewType","text":"GFPVideoViewType","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"viewType"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"GFPVideoViewType","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoViewType\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoViewType\/fragments","op":"replace","value":[{"kind":"identifier","text":"GFPVideoViewType"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoViewType\/navigatorTitle","value":[{"text":"GFPVideoViewType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoOptions\/title","value":"GFPVideoOptions","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"GFPVideoOptions"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoOptions\/fragments"},{"value":[{"kind":"identifier","text":"GFPVideoOptions"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoOptions\/navigatorTitle"},{"value":"createGlobalOptionsWithViewType:","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoOptions~1createGlobalOptions(with:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoOptions~1createGlobalOptions(with:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"createGlobalOptionsWithViewType:","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}