{"metadata":{"role":"symbol","modules":[{"name":"GFPSDK"}],"externalID":"c:objc(cs)GFPVideoOptions(im)initWithPlayPolicy:viewType:","symbolKind":"init","title":"init(playPolicy:viewType:)","navigatorTitle":[{"kind":"identifier","text":"initWithPlayPolicy:viewType:"}],"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"playPolicy"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPVideoPlayPolicy","text":"GFPVideoPlayPolicy"},{"kind":"text","text":", "},{"text":"viewType","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@GFPVideoViewType","text":"GFPVideoViewType","kind":"typeIdentifier"},{"kind":"text","text":")"}],"roleHeading":"Initializer"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"text":"playPolicy","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoPlayPolicy","kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPVideoPlayPolicy","text":"GFPVideoPlayPolicy"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"viewType"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoViewType","preciseIdentifier":"c:@E@GFPVideoViewType","text":"GFPVideoViewType","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpvideooptions\/init(playpolicy:viewtype:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gfpsdk\/gfpvideooptions\/init(playpolicy:viewtype:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoOptions"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoOptions\/init(playPolicy:viewType:)"},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoPlayPolicy":{"abstract":[],"title":"GFPVideoPlayPolicy","url":"\/documentation\/gfpsdk\/gfpvideoplaypolicy","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPVideoPlayPolicy","kind":"identifier"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPVideoPlayPolicy"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoPlayPolicy","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoOptions":{"type":"topic","url":"\/documentation\/gfpsdk\/gfpvideooptions","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoOptions","role":"symbol","kind":"symbol","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPVideoOptions","kind":"identifier"}],"title":"GFPVideoOptions","navigatorTitle":[{"text":"GFPVideoOptions","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoViewType":{"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPVideoViewType"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"GFPVideoViewType"}],"title":"GFPVideoViewType","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoViewType","url":"\/documentation\/gfpsdk\/gfpvideoviewtype","kind":"symbol","role":"symbol","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoOptions/init(playPolicy:viewType:)":{"title":"init(playPolicy:viewType:)","url":"\/documentation\/gfpsdk\/gfpvideooptions\/init(playpolicy:viewtype:)","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"playPolicy","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"GFPVideoPlayPolicy","kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPVideoPlayPolicy"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"viewType"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPVideoViewType","text":"GFPVideoViewType"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"initWithPlayPolicy:viewType:"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoOptions\/init(playPolicy:viewType:)","type":"topic","role":"symbol","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"initWithPlayPolicy:viewType:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithPlayPolicy:viewType:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithPlayPolicy:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"GFPVideoPlayPolicy","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoPlayPolicy","preciseIdentifier":"c:@E@GFPVideoPlayPolicy"},{"kind":"text","text":") "},{"text":"playPolicy","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"viewType:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@E@GFPVideoViewType","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoViewType","text":"GFPVideoViewType"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"viewType"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoPlayPolicy\/title","value":"GFPVideoPlayPolicy"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoPlayPolicy\/fragments","value":[{"text":"GFPVideoPlayPolicy","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoPlayPolicy\/navigatorTitle","value":[{"text":"GFPVideoPlayPolicy","kind":"identifier"}]},{"value":"GFPVideoOptions","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoOptions\/title","op":"replace"},{"value":[{"kind":"identifier","text":"GFPVideoOptions"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoOptions\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoOptions\/navigatorTitle","value":[{"text":"GFPVideoOptions","kind":"identifier"}]},{"value":"GFPVideoViewType","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoViewType\/title"},{"op":"replace","value":[{"kind":"identifier","text":"GFPVideoViewType"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoViewType\/fragments"},{"value":[{"kind":"identifier","text":"GFPVideoViewType"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoViewType\/navigatorTitle","op":"replace"},{"op":"replace","value":"initWithPlayPolicy:viewType:","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoOptions~1init(playPolicy:viewType:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithPlayPolicy:viewType:"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoOptions~1init(playPolicy:viewType:)\/fragments"}]}]}