{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"kind":"externalParam","text":"playPolicy"},{"text":": ","kind":"text"},{"text":"GFPVideoPlayPolicy","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoPlayPolicy","preciseIdentifier":"c:@E@GFPVideoPlayPolicy","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"useCustomControlView"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpvideooptions\/init(playpolicy:usecustomcontrolview:)"]},{"paths":["\/documentation\/gfpsdk\/gfpvideooptions\/init(playpolicy:usecustomcontrolview:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"playPolicy","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@GFPVideoPlayPolicy","text":"GFPVideoPlayPolicy","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"useCustomControlView","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":")","kind":"text"}],"externalID":"c:objc(cs)GFPVideoOptions(im)initWithPlayPolicy:useCustomControlView:","symbolKind":"init","role":"symbol","title":"init(playPolicy:useCustomControlView:)","roleHeading":"Initializer","navigatorTitle":[{"text":"initWithPlayPolicy:useCustomControlView:","kind":"identifier"}],"modules":[{"name":"GFPSDK"}]},"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoOptions"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoOptions\/init(playPolicy:useCustomControlView:)"},"sections":[],"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoOptions/init(playPolicy:useCustomControlView:)":{"type":"topic","title":"init(playPolicy:useCustomControlView:)","url":"\/documentation\/gfpsdk\/gfpvideooptions\/init(playpolicy:usecustomcontrolview:)","kind":"symbol","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"playPolicy"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"GFPVideoPlayPolicy","preciseIdentifier":"c:@E@GFPVideoPlayPolicy"},{"kind":"text","text":", "},{"text":"useCustomControlView","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoOptions\/init(playPolicy:useCustomControlView:)","navigatorTitle":[{"kind":"identifier","text":"initWithPlayPolicy:useCustomControlView:"}],"abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoPlayPolicy":{"abstract":[],"title":"GFPVideoPlayPolicy","url":"\/documentation\/gfpsdk\/gfpvideoplaypolicy","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPVideoPlayPolicy","kind":"identifier"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPVideoPlayPolicy"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoPlayPolicy","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoOptions":{"type":"topic","url":"\/documentation\/gfpsdk\/gfpvideooptions","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoOptions","role":"symbol","kind":"symbol","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPVideoOptions","kind":"identifier"}],"title":"GFPVideoOptions","navigatorTitle":[{"text":"GFPVideoOptions","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"initWithPlayPolicy:useCustomControlView:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithPlayPolicy:useCustomControlView:"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithPlayPolicy:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@E@GFPVideoPlayPolicy","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoPlayPolicy","kind":"typeIdentifier","text":"GFPVideoPlayPolicy"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"playPolicy"},{"text":" ","kind":"text"},{"kind":"identifier","text":"useCustomControlView:"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"text":"useCustomControlView","kind":"internalParam"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0"},{"value":"initWithPlayPolicy:useCustomControlView:","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoOptions~1init(playPolicy:useCustomControlView:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoOptions~1init(playPolicy:useCustomControlView:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithPlayPolicy:useCustomControlView:"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoPlayPolicy\/title","value":"GFPVideoPlayPolicy","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoPlayPolicy\/fragments","value":[{"kind":"identifier","text":"GFPVideoPlayPolicy"}],"op":"replace"},{"value":[{"kind":"identifier","text":"GFPVideoPlayPolicy"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoPlayPolicy\/navigatorTitle","op":"replace"},{"value":"GFPVideoOptions","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoOptions\/title"},{"value":[{"text":"GFPVideoOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoOptions\/fragments","op":"replace"},{"op":"replace","value":[{"text":"GFPVideoOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoOptions\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}