{"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoOptions"]]},"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoOptions\/init(playPolicy:viewType:useCustomControlView:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"playPolicy"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@GFPVideoPlayPolicy","kind":"typeIdentifier","text":"GFPVideoPlayPolicy"},{"text":", ","kind":"text"},{"text":"viewType","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@GFPVideoViewType","kind":"typeIdentifier","text":"GFPVideoViewType"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"useCustomControlView"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"roleHeading":"Initializer","modules":[{"name":"GFPSDK"}],"title":"init(playPolicy:viewType:useCustomControlView:)","navigatorTitle":[{"text":"initWithPlayPolicy:viewType:useCustomControlView:","kind":"identifier"}],"symbolKind":"init","role":"symbol","externalID":"c:objc(cs)GFPVideoOptions(im)initWithPlayPolicy:viewType:useCustomControlView:"},"variants":[{"paths":["\/documentation\/gfpsdk\/gfpvideooptions\/init(playpolicy:viewtype:usecustomcontrolview:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gfpsdk\/gfpvideooptions\/init(playpolicy:viewtype:usecustomcontrolview:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"playPolicy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoPlayPolicy","text":"GFPVideoPlayPolicy","preciseIdentifier":"c:@E@GFPVideoPlayPolicy"},{"kind":"text","text":", "},{"text":"viewType","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@GFPVideoViewType","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoViewType","text":"GFPVideoViewType","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"useCustomControlView"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"platforms":["iOS"]}]}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoViewType":{"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPVideoViewType"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"GFPVideoViewType"}],"title":"GFPVideoViewType","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoViewType","url":"\/documentation\/gfpsdk\/gfpvideoviewtype","kind":"symbol","role":"symbol","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoPlayPolicy":{"abstract":[],"title":"GFPVideoPlayPolicy","url":"\/documentation\/gfpsdk\/gfpvideoplaypolicy","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPVideoPlayPolicy","kind":"identifier"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPVideoPlayPolicy"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoPlayPolicy","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoOptions":{"type":"topic","url":"\/documentation\/gfpsdk\/gfpvideooptions","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoOptions","role":"symbol","kind":"symbol","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPVideoOptions","kind":"identifier"}],"title":"GFPVideoOptions","navigatorTitle":[{"text":"GFPVideoOptions","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoOptions/init(playPolicy:viewType:useCustomControlView:)":{"type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoOptions\/init(playPolicy:viewType:useCustomControlView:)","role":"symbol","abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithPlayPolicy:viewType:useCustomControlView:"}],"url":"\/documentation\/gfpsdk\/gfpvideooptions\/init(playpolicy:viewtype:usecustomcontrolview:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"playPolicy","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPVideoPlayPolicy","text":"GFPVideoPlayPolicy"},{"kind":"text","text":", "},{"text":"viewType","kind":"externalParam"},{"kind":"text","text":": "},{"text":"GFPVideoViewType","kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPVideoViewType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"useCustomControlView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}],"title":"init(playPolicy:viewType:useCustomControlView:)"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"initWithPlayPolicy:viewType:useCustomControlView:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithPlayPolicy:viewType:useCustomControlView:"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithPlayPolicy:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoPlayPolicy","text":"GFPVideoPlayPolicy","preciseIdentifier":"c:@E@GFPVideoPlayPolicy","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"playPolicy","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"viewType:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@E@GFPVideoViewType","text":"GFPVideoViewType","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoViewType","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"viewType"},{"kind":"text","text":" "},{"text":"useCustomControlView:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"useCustomControlView"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoViewType\/title","value":"GFPVideoViewType","op":"replace"},{"value":[{"text":"GFPVideoViewType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoViewType\/fragments"},{"value":[{"kind":"identifier","text":"GFPVideoViewType"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoViewType\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoPlayPolicy\/title","value":"GFPVideoPlayPolicy","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoPlayPolicy\/fragments","value":[{"kind":"identifier","text":"GFPVideoPlayPolicy"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoPlayPolicy\/navigatorTitle","value":[{"text":"GFPVideoPlayPolicy","kind":"identifier"}],"op":"replace"},{"value":"GFPVideoOptions","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoOptions\/title","op":"replace"},{"value":[{"kind":"identifier","text":"GFPVideoOptions"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoOptions\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoOptions\/navigatorTitle","value":[{"text":"GFPVideoOptions","kind":"identifier"}],"op":"replace"},{"value":"initWithPlayPolicy:viewType:useCustomControlView:","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoOptions~1init(playPolicy:viewType:useCustomControlView:)\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoOptions~1init(playPolicy:viewType:useCustomControlView:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithPlayPolicy:viewType:useCustomControlView:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}