{"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"광고 영상의 qoe 로깅을 위해 정보를 전달합니다."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"qoeTrackingInfo","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPQoeTrackingInfo","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPQoeTrackingInfo","text":"GFPQoeTrackingInfo"},{"text":"? { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpvideooptions\/qoetrackinginfo"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpvideooptions\/qoetrackinginfo"]}],"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoOptions\/qoeTrackingInfo","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoOptions"]]},"kind":"symbol","metadata":{"title":"qoeTrackingInfo","modules":[{"name":"GFPSDK"}],"roleHeading":"Instance Property","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"qoeTrackingInfo"}],"role":"symbol","externalID":"c:objc(cs)GFPVideoOptions(py)qoeTrackingInfo","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"qoeTrackingInfo","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPQoeTrackingInfo","kind":"typeIdentifier","text":"GFPQoeTrackingInfo"},{"text":"?","kind":"text"}]},"sections":[],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoOptions/qoeTrackingInfo":{"type":"topic","title":"qoeTrackingInfo","url":"\/documentation\/gfpsdk\/gfpvideooptions\/qoetrackinginfo","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"qoeTrackingInfo","kind":"identifier"},{"kind":"text","text":": "},{"text":"GFPQoeTrackingInfo","kind":"typeIdentifier","preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPQoeTrackingInfo"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoOptions\/qoeTrackingInfo","navigatorTitle":[{"kind":"identifier","text":"qoeTrackingInfo"}],"abstract":[{"type":"text","text":"광고 영상의 qoe 로깅을 위해 정보를 전달합니다."}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPQoeTrackingInfo":{"role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"GFPQoeTrackingInfo"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPQoeTrackingInfo"}],"kind":"symbol","type":"topic","title":"GFPQoeTrackingInfo","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPQoeTrackingInfo","url":"\/documentation\/gfpsdk\/gfpqoetrackinginfo"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoOptions":{"type":"topic","url":"\/documentation\/gfpsdk\/gfpvideooptions","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoOptions","role":"symbol","kind":"symbol","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPVideoOptions","kind":"identifier"}],"title":"GFPVideoOptions","navigatorTitle":[{"text":"GFPVideoOptions","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"qoeTrackingInfo"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"qoeTrackingInfo","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPQoeTrackingInfo","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPQoeTrackingInfo","text":"GFPQoeTrackingInfo"},{"kind":"text","text":" * "},{"kind":"identifier","text":"qoeTrackingInfo"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoOptions~1qoeTrackingInfo\/title","value":"qoeTrackingInfo"},{"value":[{"text":"qoeTrackingInfo","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoOptions~1qoeTrackingInfo\/fragments"},{"value":"GFPQoeTrackingInfo","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPQoeTrackingInfo\/title"},{"value":[{"text":"GFPQoeTrackingInfo","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPQoeTrackingInfo\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPQoeTrackingInfo\/navigatorTitle","value":[{"text":"GFPQoeTrackingInfo","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoOptions\/title","value":"GFPVideoOptions","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoOptions\/fragments","value":[{"kind":"identifier","text":"GFPVideoOptions"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoOptions\/navigatorTitle","value":[{"text":"GFPVideoOptions","kind":"identifier"}],"op":"replace"}]}]}