{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/BaseStaticResource"},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"BaseStaticResource"}],"title":"BaseStaticResource","roleHeading":"Class","externalID":"c:objc(cs)BaseStaticResource","symbolKind":"class","modules":[{"name":"GFPSDK"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"BaseStaticResource","kind":"identifier"}],"role":"symbol"},"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"kind":"symbol","topicSections":[{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/BaseStaticResource\/content","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/BaseStaticResource\/creativeType"],"anchor":"Instance-Properties","title":"Instance Properties","generated":true}],"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject"],"kind":"relationships"},{"type":"inheritedBy","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/StaticResource"],"title":"Inherited By","kind":"relationships"},{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s7CVarArgP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s23CustomStringConvertibleP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH"],"type":"conformsTo","title":"Conforms To","kind":"relationships"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BaseStaticResource","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/basestaticresource"]},{"paths":["\/documentation\/gfpsdk\/basestaticresource"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://com.navercorp.da.gfp.GFPSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/BaseStaticResource/creativeType":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"creativeType","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"abstract":[],"url":"\/documentation\/gfpsdk\/basestaticresource\/creativetype","kind":"symbol","role":"symbol","title":"creativeType","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/BaseStaticResource\/creativeType","type":"topic","navigatorTitle":[{"text":"creativeType","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/SH":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)NSObject":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/s7CVarArgP":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/StaticResource":{"abstract":[],"role":"symbol","url":"\/documentation\/gfpsdk\/staticresource","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StaticResource","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"StaticResource"}],"kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/StaticResource","type":"topic","title":"StaticResource"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/BaseStaticResource/initWithElement:error:":{"kind":"symbol","title":"initWithElement:error:","abstract":[],"role":"symbol","url":"\/documentation\/gfpsdk\/basestaticresource\/initwithelement:error:","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/BaseStaticResource\/initWithElement:error:","type":"topic","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithElement:error:"}],"navigatorTitle":[{"text":"initWithElement:error:","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject"},"doc://com.navercorp.da.gfp.GFPSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ"},"doc://com.navercorp.da.gfp.GFPSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s28CustomDebugStringConvertibleP"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/BaseStaticResource":{"kind":"symbol","title":"BaseStaticResource","abstract":[],"role":"symbol","url":"\/documentation\/gfpsdk\/basestaticresource","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/BaseStaticResource","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"BaseStaticResource","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"BaseStaticResource"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/BaseStaticResource/content":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"content","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"url":"\/documentation\/gfpsdk\/basestaticresource\/content","kind":"symbol","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/BaseStaticResource\/content","abstract":[],"role":"symbol","navigatorTitle":[{"text":"content","kind":"identifier"}],"title":"content"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"BaseStaticResource"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"value":[{"kind":"identifier","text":"BaseStaticResource"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"BaseStaticResource","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/BaseStaticResource\/content","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/BaseStaticResource\/creativeType"],"generated":true,"anchor":"Instance-Properties","title":"Instance Properties"},{"title":"Instance Methods","generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/BaseStaticResource\/initWithElement:error:"]}],"op":"replace"},{"value":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject"]},{"title":"Inherited By","type":"inheritedBy","kind":"relationships","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/StaticResource"]}],"path":"\/relationshipsSections","op":"replace"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"BaseStaticResource","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1BaseStaticResource~1creativeType\/title","value":"creativeType","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1BaseStaticResource~1creativeType\/fragments","value":[{"kind":"identifier","text":"creativeType"}],"op":"replace"},{"value":"StaticResource","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1StaticResource\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1StaticResource\/fragments","value":[{"text":"StaticResource","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1StaticResource\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"StaticResource"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1BaseStaticResource\/title","value":"BaseStaticResource","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1BaseStaticResource\/fragments","value":[{"kind":"identifier","text":"BaseStaticResource"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1BaseStaticResource\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"BaseStaticResource"}]},{"value":"content","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1BaseStaticResource~1content\/title","op":"replace"},{"value":[{"text":"content","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1BaseStaticResource~1content\/fragments","op":"replace"}]}]}