{"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdChoicesViewPosition","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPAdChoicesViewPosition","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"relationshipsSections":[{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/s15BitwiseCopyableP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s25ExpressibleByArrayLiteralP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s9OptionSetP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SY","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s8SendableP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s10SetAlgebraP"]}],"metadata":{"externalID":"c:@E@GFPAdChoicesViewPosition","navigatorTitle":[{"text":"GFPAdChoicesViewPosition","kind":"identifier"}],"title":"GFPAdChoicesViewPosition","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPAdChoicesViewPosition","kind":"identifier"}],"symbolKind":"struct","modules":[{"name":"GFPSDK"}],"roleHeading":"Structure","role":"symbol"},"topicSections":[{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdChoicesViewPosition\/init(rawValue:)"],"generated":true,"anchor":"Initializers","title":"Initializers"},{"anchor":"Type-Properties","generated":true,"title":"Type Properties","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdChoicesViewPosition\/bottomLeftCorner","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdChoicesViewPosition\/bottomRightCorner","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdChoicesViewPosition\/topLeftCorner","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdChoicesViewPosition\/topRightCorner"]},{"anchor":"Default-Implementations","generated":true,"title":"Default Implementations","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdChoicesViewPosition\/Equatable-Implementations","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdChoicesViewPosition\/OptionSet-Implementations","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdChoicesViewPosition\/SetAlgebra-Implementations"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpadchoicesviewposition"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpadchoicesviewposition"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/SY":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/s10SetAlgebraP":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s10SetAlgebraP","title":"Swift.SetAlgebra","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/SQ":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdChoicesViewPosition":{"url":"\/documentation\/gfpsdk\/gfpadchoicesviewposition","role":"symbol","abstract":[],"type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPAdChoicesViewPosition"}],"title":"GFPAdChoicesViewPosition","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdChoicesViewPosition","navigatorTitle":[{"kind":"identifier","text":"GFPAdChoicesViewPosition"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdChoicesViewPosition/OptionSet-Implementations":{"url":"\/documentation\/gfpsdk\/gfpadchoicesviewposition\/optionset-implementations","title":"OptionSet Implementations","abstract":[],"type":"topic","kind":"article","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdChoicesViewPosition\/OptionSet-Implementations","role":"collectionGroup"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdChoicesViewPosition/topLeftCorner":{"type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"GFPAdChoicesViewPositionTopLeftCorner"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdChoicesViewPosition\/topLeftCorner","title":"topLeftCorner","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"topLeftCorner","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPAdChoicesViewPosition","text":"GFPAdChoicesViewPosition"}],"url":"\/documentation\/gfpsdk\/gfpadchoicesviewposition\/topleftcorner","kind":"symbol","role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdChoicesViewPosition/topRightCorner":{"abstract":[],"url":"\/documentation\/gfpsdk\/gfpadchoicesviewposition\/toprightcorner","role":"symbol","title":"topRightCorner","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdChoicesViewPosition\/topRightCorner","type":"topic","navigatorTitle":[{"text":"GFPAdChoicesViewPositionTopRightCorner","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"topRightCorner"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@GFPAdChoicesViewPosition","text":"GFPAdChoicesViewPosition","kind":"typeIdentifier"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdChoicesViewPosition/init(rawValue:)":{"type":"topic","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"title":"init(rawValue:)","url":"\/documentation\/gfpsdk\/gfpadchoicesviewposition\/init(rawvalue:)","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdChoicesViewPosition\/init(rawValue:)","role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/s15BitwiseCopyableP":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s15BitwiseCopyableP","title":"Swift.BitwiseCopyable","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdChoicesViewPosition/bottomRightCorner":{"navigatorTitle":[{"text":"GFPAdChoicesViewPositionBottomRightCorner","kind":"identifier"}],"type":"topic","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bottomRightCorner","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@GFPAdChoicesViewPosition","kind":"typeIdentifier","text":"GFPAdChoicesViewPosition"}],"title":"bottomRightCorner","url":"\/documentation\/gfpsdk\/gfpadchoicesviewposition\/bottomrightcorner","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdChoicesViewPosition\/bottomRightCorner","role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/s25ExpressibleByArrayLiteralP":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s25ExpressibleByArrayLiteralP","type":"unresolvable","title":"Swift.ExpressibleByArrayLiteral"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdChoicesViewPosition/bottomLeftCorner":{"navigatorTitle":[{"text":"GFPAdChoicesViewPositionBottomLeftCorner","kind":"identifier"}],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bottomLeftCorner","kind":"identifier"},{"kind":"text","text":": "},{"text":"GFPAdChoicesViewPosition","kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPAdChoicesViewPosition"}],"title":"bottomLeftCorner","url":"\/documentation\/gfpsdk\/gfpadchoicesviewposition\/bottomleftcorner","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdChoicesViewPosition\/bottomLeftCorner","role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdChoicesViewPosition/Equatable-Implementations":{"url":"\/documentation\/gfpsdk\/gfpadchoicesviewposition\/equatable-implementations","role":"collectionGroup","abstract":[],"type":"topic","title":"Equatable Implementations","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdChoicesViewPosition\/Equatable-Implementations","kind":"article"},"doc://com.navercorp.da.gfp.GFPSDK/s8SendableP":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s8SendableP","title":"Swift.Sendable","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdChoicesViewPosition/SetAlgebra-Implementations":{"abstract":[],"url":"\/documentation\/gfpsdk\/gfpadchoicesviewposition\/setalgebra-implementations","title":"SetAlgebra Implementations","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdChoicesViewPosition\/SetAlgebra-Implementations","role":"collectionGroup","type":"topic","kind":"article"},"doc://com.navercorp.da.gfp.GFPSDK/s9OptionSetP":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s9OptionSetP","title":"Swift.OptionSet","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"GFPAdChoicesViewPosition"},{"value":"enum","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"GFPAdChoicesViewPosition","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","value":[{"text":"GFPAdChoicesViewPosition","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"title":"Enumeration Cases","generated":true,"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdChoicesViewPosition\/bottomLeftCorner","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdChoicesViewPosition\/bottomRightCorner","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdChoicesViewPosition\/topLeftCorner","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdChoicesViewPosition\/topRightCorner"],"anchor":"Enumeration-Cases"}],"op":"replace"},{"value":null,"op":"replace","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPAdChoicesViewPosition"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdChoicesViewPosition\/title","value":"GFPAdChoicesViewPosition"},{"value":[{"text":"GFPAdChoicesViewPosition","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdChoicesViewPosition\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdChoicesViewPosition\/navigatorTitle","value":[{"text":"GFPAdChoicesViewPosition","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdChoicesViewPosition~1topLeftCorner\/title","value":"GFPAdChoicesViewPositionTopLeftCorner"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdChoicesViewPosition~1topLeftCorner\/fragments","value":[{"kind":"identifier","text":"GFPAdChoicesViewPositionTopLeftCorner"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdChoicesViewPosition~1topRightCorner\/title","value":"GFPAdChoicesViewPositionTopRightCorner"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdChoicesViewPosition~1topRightCorner\/fragments","op":"replace","value":[{"text":"GFPAdChoicesViewPositionTopRightCorner","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdChoicesViewPosition~1bottomRightCorner\/title","value":"GFPAdChoicesViewPositionBottomRightCorner","op":"replace"},{"value":[{"text":"GFPAdChoicesViewPositionBottomRightCorner","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdChoicesViewPosition~1bottomRightCorner\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdChoicesViewPosition~1bottomLeftCorner\/title","op":"replace","value":"GFPAdChoicesViewPositionBottomLeftCorner"},{"value":[{"kind":"identifier","text":"GFPAdChoicesViewPositionBottomLeftCorner"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdChoicesViewPosition~1bottomLeftCorner\/fragments"}]}]}