{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPAdAdaptorLoadCompletionHandler"},{"kind":"text","text":" = ("},{"preciseIdentifier":"c:@M@NaverAdsServices@objc(cs)GFPError","text":"GFPError","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"GFPLoadEvent","preciseIdentifier":"c:objc(cs)GFPLoadEvent","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLoadEvent"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"GFPEventExtraInfo","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPEventExtraInfo","preciseIdentifier":"c:objc(cs)GFPEventExtraInfo"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"}]}],"kind":"declarations"}],"sections":[],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpadadaptorloadcompletionhandler"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpadadaptorloadcompletionhandler"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAdaptorLoadCompletionHandler"},"metadata":{"title":"GFPAdAdaptorLoadCompletionHandler","role":"symbol","externalID":"c:GFPAdAdapting.h@T@GFPAdAdaptorLoadCompletionHandler","symbolKind":"typealias","modules":[{"name":"GFPSDK"}],"fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPAdAdaptorLoadCompletionHandler"}],"navigatorTitle":[{"kind":"identifier","text":"GFPAdAdaptorLoadCompletionHandler"}],"roleHeading":"Type Alias"},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPLoadEvent":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPLoadEvent","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"GFPLoadEvent","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLoadEvent","abstract":[],"role":"symbol","url":"\/documentation\/gfpsdk\/gfploadevent","title":"GFPLoadEvent","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPEventExtraInfo":{"navigatorTitle":[{"text":"GFPEventExtraInfo","kind":"identifier"}],"role":"symbol","title":"GFPEventExtraInfo","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPEventExtraInfo"}],"type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPEventExtraInfo","abstract":[],"url":"\/documentation\/gfpsdk\/gfpeventextrainfo"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdAdaptorLoadCompletionHandler":{"navigatorTitle":[{"kind":"identifier","text":"GFPAdAdaptorLoadCompletionHandler"}],"url":"\/documentation\/gfpsdk\/gfpadadaptorloadcompletionhandler","abstract":[],"fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"GFPAdAdaptorLoadCompletionHandler","kind":"identifier"}],"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAdaptorLoadCompletionHandler","title":"GFPAdAdaptorLoadCompletionHandler"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Alias"},{"op":"replace","path":"\/metadata\/title","value":"GFPAdAdaptorLoadCompletionHandler"},{"op":"replace","path":"\/metadata\/symbolKind","value":"typealias"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GFPAdAdaptorLoadCompletionHandler"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"GFPAdAdaptorLoadCompletionHandler"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"typedef"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:BFv(#*$@M@NaverAdsServices@objc(cs)GFPError#*$objc(cs)GFPLoadEvent#*$objc(cs)GFPEventExtraInfo)","text":"void (^)(GFPError *, GFPLoadEvent *, GFPEventExtraInfo *)","kind":"typeIdentifier"},{"kind":"text","text":" "},{"text":"GFPAdAdaptorLoadCompletionHandler","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLoadEvent\/title","value":"GFPLoadEvent"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLoadEvent\/fragments","value":[{"text":"GFPLoadEvent","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLoadEvent\/navigatorTitle","value":[{"kind":"identifier","text":"GFPLoadEvent"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPEventExtraInfo\/title","value":"GFPEventExtraInfo","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"GFPEventExtraInfo"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPEventExtraInfo\/fragments"},{"op":"replace","value":[{"text":"GFPEventExtraInfo","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPEventExtraInfo\/navigatorTitle"},{"value":"GFPAdAdaptorLoadCompletionHandler","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdaptorLoadCompletionHandler\/title","op":"replace"},{"value":[{"kind":"identifier","text":"GFPAdAdaptorLoadCompletionHandler"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdaptorLoadCompletionHandler\/fragments"},{"value":[{"text":"GFPAdAdaptorLoadCompletionHandler","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdaptorLoadCompletionHandler\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}