{"topicSections":[{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdProviderSettingType\/init(rawValue:)"],"generated":true,"title":"Initializers","anchor":"Initializers"},{"anchor":"Type-Properties","generated":true,"title":"Type Properties","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdProviderSettingType\/DFP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdProviderSettingType\/FAN","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdProviderSettingType\/GFP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdProviderSettingType\/LAN","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdProviderSettingType\/bidMachine","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdProviderSettingType\/unity"]},{"generated":true,"anchor":"Default-Implementations","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdProviderSettingType\/Equatable-Implementations","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdProviderSettingType\/OptionSet-Implementations","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdProviderSettingType\/SetAlgebra-Implementations"],"title":"Default Implementations"}],"metadata":{"title":"GFPAdProviderSettingType","symbolKind":"struct","modules":[{"name":"GFPSDK"}],"role":"symbol","externalID":"c:@E@GFPAdProviderSettingType","roleHeading":"Structure","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPAdProviderSettingType"}],"navigatorTitle":[{"text":"GFPAdProviderSettingType","kind":"identifier"}]},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdProviderSettingType","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPAdProviderSettingType"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpadprovidersettingtype"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpadprovidersettingtype"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"sections":[],"relationshipsSections":[{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/s15BitwiseCopyableP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s25ExpressibleByArrayLiteralP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s9OptionSetP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SY","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s8SendableP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s10SetAlgebraP"]}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/s25ExpressibleByArrayLiteralP":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s25ExpressibleByArrayLiteralP","title":"Swift.ExpressibleByArrayLiteral","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdProviderSettingType/FAN":{"url":"\/documentation\/gfpsdk\/gfpadprovidersettingtype\/fan","title":"FAN","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdProviderSettingType\/FAN","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"GFPAdProviderSettingTypeFAN","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"FAN","kind":"identifier"},{"kind":"text","text":": "},{"text":"GFPAdProviderSettingType","kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPAdProviderSettingType"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdProviderSettingType/Equatable-Implementations":{"title":"Equatable Implementations","url":"\/documentation\/gfpsdk\/gfpadprovidersettingtype\/equatable-implementations","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdProviderSettingType\/Equatable-Implementations","role":"collectionGroup","type":"topic","kind":"article","abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdProviderSettingType":{"abstract":[],"role":"symbol","navigatorTitle":[{"text":"GFPAdProviderSettingType","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPAdProviderSettingType","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpadprovidersettingtype","title":"GFPAdProviderSettingType","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdProviderSettingType","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdProviderSettingType/GFPAdProviderSettingTypeNone":{"url":"\/documentation\/gfpsdk\/gfpadprovidersettingtype\/gfpadprovidersettingtypenone","title":"GFPAdProviderSettingTypeNone","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdProviderSettingType\/GFPAdProviderSettingTypeNone","role":"symbol","kind":"symbol","type":"topic","fragments":[{"text":"GFPAdProviderSettingTypeNone","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SY"},"doc://com.navercorp.da.gfp.GFPSDK/s9OptionSetP":{"type":"unresolvable","title":"Swift.OptionSet","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s9OptionSetP"},"doc://com.navercorp.da.gfp.GFPSDK/s15BitwiseCopyableP":{"type":"unresolvable","title":"Swift.BitwiseCopyable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s15BitwiseCopyableP"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdProviderSettingType/GFP":{"url":"\/documentation\/gfpsdk\/gfpadprovidersettingtype\/gfp","title":"GFP","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdProviderSettingType\/GFP","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"GFPAdProviderSettingTypeGFP","kind":"identifier"}],"type":"topic","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFP"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@GFPAdProviderSettingType","kind":"typeIdentifier","text":"GFPAdProviderSettingType"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdProviderSettingType/init(rawValue:)":{"title":"init(rawValue:)","url":"\/documentation\/gfpsdk\/gfpadprovidersettingtype\/init(rawvalue:)","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdProviderSettingType\/init(rawValue:)","role":"symbol","type":"topic","kind":"symbol","abstract":[],"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdProviderSettingType/unity":{"url":"\/documentation\/gfpsdk\/gfpadprovidersettingtype\/unity","type":"topic","title":"unity","kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdProviderSettingType\/unity","abstract":[],"navigatorTitle":[{"text":"GFPAdProviderSettingTypeUnity","kind":"identifier"}],"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unity","kind":"identifier"},{"text":": ","kind":"text"},{"text":"GFPAdProviderSettingType","kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPAdProviderSettingType"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdProviderSettingType/bidMachine":{"url":"\/documentation\/gfpsdk\/gfpadprovidersettingtype\/bidmachine","title":"bidMachine","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdProviderSettingType\/bidMachine","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"GFPAdProviderSettingTypeBidMachine","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"bidMachine","kind":"identifier"},{"kind":"text","text":": "},{"text":"GFPAdProviderSettingType","kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPAdProviderSettingType"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdProviderSettingType/OptionSet-Implementations":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdProviderSettingType\/OptionSet-Implementations","url":"\/documentation\/gfpsdk\/gfpadprovidersettingtype\/optionset-implementations","title":"OptionSet Implementations","kind":"article","abstract":[],"role":"collectionGroup","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdProviderSettingType/SetAlgebra-Implementations":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdProviderSettingType\/SetAlgebra-Implementations","type":"topic","url":"\/documentation\/gfpsdk\/gfpadprovidersettingtype\/setalgebra-implementations","abstract":[],"kind":"article","title":"SetAlgebra Implementations","role":"collectionGroup"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdProviderSettingType/LAN":{"url":"\/documentation\/gfpsdk\/gfpadprovidersettingtype\/lan","title":"LAN","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdProviderSettingType\/LAN","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"GFPAdProviderSettingTypeLAN","kind":"identifier"}],"type":"topic","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"LAN"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@GFPAdProviderSettingType","kind":"typeIdentifier","text":"GFPAdProviderSettingType"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdProviderSettingType/DFP":{"role":"symbol","navigatorTitle":[{"text":"GFPAdProviderSettingTypeDFP","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpadprovidersettingtype\/dfp","title":"DFP","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"DFP","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@GFPAdProviderSettingType","kind":"typeIdentifier","text":"GFPAdProviderSettingType"}],"abstract":[],"type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdProviderSettingType\/DFP"},"doc://com.navercorp.da.gfp.GFPSDK/s10SetAlgebraP":{"title":"Swift.SetAlgebra","type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s10SetAlgebraP"},"doc://com.navercorp.da.gfp.GFPSDK/s8SendableP":{"title":"Swift.Sendable","type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s8SendableP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"value":"GFPAdProviderSettingType","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"enum","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GFPAdProviderSettingType"}]},{"value":[{"text":"GFPAdProviderSettingType","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdProviderSettingType\/DFP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdProviderSettingType\/FAN","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdProviderSettingType\/GFP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdProviderSettingType\/GFPAdProviderSettingTypeNone","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdProviderSettingType\/LAN","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdProviderSettingType\/bidMachine","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdProviderSettingType\/unity"],"generated":true,"anchor":"Enumeration-Cases"}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPAdProviderSettingType"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","value":"GFPAdProviderSettingTypeFAN","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdProviderSettingType~1FAN\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdProviderSettingType~1FAN\/fragments","value":[{"text":"GFPAdProviderSettingTypeFAN","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdProviderSettingType\/title","value":"GFPAdProviderSettingType","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdProviderSettingType\/fragments","op":"replace","value":[{"kind":"identifier","text":"GFPAdProviderSettingType"}]},{"value":[{"text":"GFPAdProviderSettingType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdProviderSettingType\/navigatorTitle","op":"replace"},{"value":"GFPAdProviderSettingTypeGFP","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdProviderSettingType~1GFP\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdProviderSettingType~1GFP\/fragments","op":"replace","value":[{"text":"GFPAdProviderSettingTypeGFP","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdProviderSettingType~1unity\/title","value":"GFPAdProviderSettingTypeUnity","op":"replace"},{"value":[{"kind":"identifier","text":"GFPAdProviderSettingTypeUnity"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdProviderSettingType~1unity\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdProviderSettingType~1bidMachine\/title","value":"GFPAdProviderSettingTypeBidMachine"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdProviderSettingType~1bidMachine\/fragments","value":[{"kind":"identifier","text":"GFPAdProviderSettingTypeBidMachine"}]},{"op":"replace","value":"GFPAdProviderSettingTypeLAN","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdProviderSettingType~1LAN\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdProviderSettingType~1LAN\/fragments","value":[{"text":"GFPAdProviderSettingTypeLAN","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdProviderSettingType~1DFP\/title","value":"GFPAdProviderSettingTypeDFP","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdProviderSettingType~1DFP\/fragments","value":[{"text":"GFPAdProviderSettingTypeDFP","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}