{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPAPIQueryItems"}]}],"kind":"declarations"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"relationshipsSections":[{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"},{"title":"Conforms To","type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s7CVarArgP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s23CustomStringConvertibleP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH"]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpapiqueryitems"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpapiqueryitems"]}],"metadata":{"title":"GFPAPIQueryItems","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPAPIQueryItems","kind":"identifier"}],"roleHeading":"Class","role":"symbol","externalID":"c:objc(cs)GFPAPIQueryItems","symbolKind":"class","navigatorTitle":[{"kind":"identifier","text":"GFPAPIQueryItems"}],"modules":[{"name":"GFPSDK"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAPIQueryItems"},"topicSections":[{"anchor":"Initializers","title":"Initializers","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAPIQueryItems\/init(_:adParam:videoParam:extraParam:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAPIQueryItems\/init(_:scheduleParam:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAPIQueryItems\/init(data:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAPIQueryItems\/init(log:)"],"generated":true},{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAPIQueryItems\/data","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAPIQueryItems\/items"]}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.navercorp.da.gfp.GFPSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAPIQueryItems/init(data:)":{"role":"symbol","abstract":[],"title":"init(data:)","navigatorTitle":[{"kind":"identifier","text":"initWithData:"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"data","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAPIQueryItems\/init(data:)","type":"topic","kind":"symbol","url":"\/documentation\/gfpsdk\/gfpapiqueryitems\/init(data:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAPIQueryItems/initWith:":{"type":"topic","abstract":[],"title":"initWith:","role":"symbol","url":"\/documentation\/gfpsdk\/gfpapiqueryitems\/initwith:","navigatorTitle":[{"kind":"identifier","text":"initWith:"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAPIQueryItems\/initWith:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWith:"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAPIQueryItems/data":{"abstract":[],"title":"data","url":"\/documentation\/gfpsdk\/gfpapiqueryitems\/data","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAPIQueryItems\/data","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"data"},{"kind":"text","text":": "},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"data"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAPIQueryItems/items":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAPIQueryItems\/items","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"items","kind":"identifier"},{"kind":"text","text":": ["},{"text":"URLQueryItem","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation12URLQueryItemV"},{"text":"]","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"items"}],"type":"topic","role":"symbol","kind":"symbol","title":"items","url":"\/documentation\/gfpsdk\/gfpapiqueryitems\/items","abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAPIQueryItems/init(log:)":{"type":"topic","abstract":[],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"log","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPLogReqInfo","kind":"typeIdentifier","text":"GFPLogReqInfo"},{"text":")","kind":"text"}],"title":"init(log:)","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAPIQueryItems\/init(log:)","role":"symbol","kind":"symbol","url":"\/documentation\/gfpsdk\/gfpapiqueryitems\/init(log:)","navigatorTitle":[{"text":"initWithLog:","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAPIQueryItems/init(_:scheduleParam:)":{"abstract":[],"type":"topic","title":"init(_:scheduleParam:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"scheduleParam","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"GFPAdScheduleParam","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdScheduleParam"},{"text":")","kind":"text"}],"url":"\/documentation\/gfpsdk\/gfpapiqueryitems\/init(_:scheduleparam:)","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAPIQueryItems\/init(_:scheduleParam:)","navigatorTitle":[{"kind":"identifier","text":"initWith:scheduleParam:"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/SQ":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)NSObject":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/SH":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/objc(cs)NSObject":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAPIQueryItems":{"url":"\/documentation\/gfpsdk\/gfpapiqueryitems","abstract":[],"title":"GFPAPIQueryItems","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAPIQueryItems","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPAPIQueryItems"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPAPIQueryItems"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAPIQueryItems/init(_:adParam:videoParam:extraParam:)":{"type":"topic","abstract":[],"title":"init(_:adParam:videoParam:extraParam:)","role":"symbol","url":"\/documentation\/gfpsdk\/gfpapiqueryitems\/init(_:adparam:videoparam:extraparam:)","navigatorTitle":[{"text":"initWith:adParam:videoParam:extraParam:","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAPIQueryItems\/init(_:adParam:videoParam:extraParam:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"adParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"GFPAdParam","preciseIdentifier":"c:objc(cs)GFPAdParam"},{"text":"?, ","kind":"text"},{"text":"videoParam","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GFPVideoAdParam","preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPVideoAdParam"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"extraParam"},{"text":": ","kind":"text"},{"text":"GFPExtraRequestParam","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPExtraRequestParam"},{"text":"?)","kind":"text"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"GFPAPIQueryItems","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"GFPAPIQueryItems","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"GFPAPIQueryItems"}]},{"value":[{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAPIQueryItems\/data","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAPIQueryItems\/items"]},{"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAPIQueryItems\/init(_:adParam:videoParam:extraParam:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAPIQueryItems\/init(_:scheduleParam:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAPIQueryItems\/init(data:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAPIQueryItems\/init(log:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAPIQueryItems\/initWith:"],"generated":true}],"op":"replace","path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject"]}]},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"GFPAPIQueryItems","kind":"identifier"},{"kind":"text","text":" : "},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAPIQueryItems~1init(data:)\/title","value":"initWithData:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithData:"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAPIQueryItems~1init(data:)\/fragments"},{"value":"data","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAPIQueryItems~1data\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAPIQueryItems~1data\/fragments","op":"replace","value":[{"text":"data","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAPIQueryItems~1items\/title","op":"replace","value":"items"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAPIQueryItems~1items\/fragments","value":[{"text":"items","kind":"identifier"}],"op":"replace"},{"value":"initWithLog:","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAPIQueryItems~1init(log:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAPIQueryItems~1init(log:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithLog:","kind":"identifier"}]},{"op":"replace","value":"initWith:scheduleParam:","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAPIQueryItems~1init(_:scheduleParam:)\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAPIQueryItems~1init(_:scheduleParam:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWith:scheduleParam:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAPIQueryItems\/title","value":"GFPAPIQueryItems","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAPIQueryItems\/fragments","op":"replace","value":[{"text":"GFPAPIQueryItems","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAPIQueryItems\/navigatorTitle","value":[{"text":"GFPAPIQueryItems","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAPIQueryItems~1init(_:adParam:videoParam:extraParam:)\/title","value":"initWith:adParam:videoParam:extraParam:","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAPIQueryItems~1init(_:adParam:videoParam:extraParam:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWith:adParam:videoParam:extraParam:","kind":"identifier"}],"op":"replace"}]}]}