{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPAdLoader"}]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoader"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpadloader"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpadloader"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"kind":"symbol","relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject"],"type":"inheritsFrom"},{"type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s7CVarArgP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s23CustomStringConvertibleP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH"],"title":"Conforms To"}],"topicSections":[{"generated":true,"anchor":"Initializers","title":"Initializers","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoader\/init(unitID:rootViewController:adParam:)"]},{"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoader\/adParam","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoader\/adUnitID","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoader\/bannerDelegate","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoader\/bannerOptions","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoader\/delegate","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoader\/nativeDelegate","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoader\/nativeOptions","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoader\/nativeSimpleDelegate","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoader\/nativeSimpleOptions","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoader\/requestTimeoutInterval","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoader\/rootViewController"],"generated":true},{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoader\/adLoaderDidFailWithError(_:responseInfo:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoader\/loadAd()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoader\/loadAdInternal(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoader\/loadAdWith(data:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoader\/loadAdWith(dict:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoader\/loadAdWith(string:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoader\/setBannerDelegate(_:bannerOptions:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoader\/setNativeDelegate(_:nativeOptions:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoader\/setNativeSimpleDelegate(_:nativeSimpleOptions:)"],"anchor":"Instance-Methods"}],"metadata":{"title":"GFPAdLoader","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"GFPAdLoader","kind":"identifier"}],"roleHeading":"Class","role":"symbol","externalID":"c:objc(cs)GFPAdLoader","symbolKind":"class","navigatorTitle":[{"kind":"identifier","text":"GFPAdLoader"}],"modules":[{"name":"GFPSDK"}]},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdLoader/loadAdInternal(_:)":{"url":"\/documentation\/gfpsdk\/gfpadloader\/loadadinternal(_:)","role":"symbol","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"loadAdInternal","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPUnifiedMediator","text":"GFPUnifiedMediator"},{"kind":"text","text":")"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoader\/loadAdInternal(_:)","title":"loadAdInternal(_:)","navigatorTitle":[{"kind":"identifier","text":"loadAdInternal:"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdLoader/nativeDelegate":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoader\/nativeDelegate","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"nativeDelegate"}],"title":"nativeDelegate","abstract":[],"url":"\/documentation\/gfpsdk\/gfpadloader\/nativedelegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"nativeDelegate"},{"text":": (any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)GFPNativeAdDelegate","text":"GFPNativeAdDelegate"},{"text":")?","kind":"text"}],"type":"topic","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdLoader/setNativeDelegate(_:nativeOptions:)":{"type":"topic","title":"setNativeDelegate(_:nativeOptions:)","abstract":[{"type":"text","text":"통합 로더를 통해 네이티브 로드 시 사용."}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setNativeDelegate"},{"kind":"text","text":"(any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)GFPNativeAdDelegate","text":"GFPNativeAdDelegate"},{"kind":"text","text":", "},{"text":"nativeOptions","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"GFPAdNativeOptions","kind":"typeIdentifier","preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPAdNativeOptions"},{"kind":"text","text":"?)"}],"url":"\/documentation\/gfpsdk\/gfpadloader\/setnativedelegate(_:nativeoptions:)","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoader\/setNativeDelegate(_:nativeOptions:)","navigatorTitle":[{"text":"setNativeDelegate:nativeOptions:","kind":"identifier"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)NSObject":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdLoader/delegate":{"url":"\/documentation\/gfpsdk\/gfpadloader\/delegate","title":"delegate","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoader\/delegate","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"delegate"}],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"kind":"text","text":": (any "},{"text":"GFPAdLoaderDelegate","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)GFPAdLoaderDelegate"},{"text":")?","kind":"text"}]},"doc://com.navercorp.da.gfp.GFPSDK/SH":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdLoader/adUnitID":{"type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoader\/adUnitID","abstract":[],"title":"adUnitID","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"adUnitID","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"adUnitID","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpadloader\/adunitid","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdLoader/nativeOptions":{"type":"topic","title":"nativeOptions","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"nativeOptions","kind":"identifier"},{"text":": ","kind":"text"},{"text":"GFPAdNativeOptions","kind":"typeIdentifier","preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPAdNativeOptions"}],"url":"\/documentation\/gfpsdk\/gfpadloader\/nativeoptions","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoader\/nativeOptions","navigatorTitle":[{"kind":"identifier","text":"nativeOptions"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdLoader/requestTimeoutInterval":{"role":"symbol","type":"topic","navigatorTitle":[{"text":"requestTimeoutInterval","kind":"identifier"}],"abstract":[{"text":"광고 요청이후 로드 완료시점까지 타임아웃 (Optional)","type":"text"}],"kind":"symbol","title":"requestTimeoutInterval","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requestTimeoutInterval","kind":"identifier"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoader\/requestTimeoutInterval","url":"\/documentation\/gfpsdk\/gfpadloader\/requesttimeoutinterval"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdLoader/bannerDelegate":{"type":"topic","abstract":[],"title":"bannerDelegate","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"bannerDelegate","kind":"identifier"},{"text":": (any ","kind":"text"},{"kind":"typeIdentifier","text":"GFPBannerViewDelegate","preciseIdentifier":"c:objc(pl)GFPBannerViewDelegate"},{"kind":"text","text":")?"}],"url":"\/documentation\/gfpsdk\/gfpadloader\/bannerdelegate","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoader\/bannerDelegate","navigatorTitle":[{"kind":"identifier","text":"bannerDelegate"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdLoader/setBannerDelegate(_:bannerOptions:)":{"abstract":[{"type":"text","text":"통합 로더를 통해 배너 광고 로드 시 사용."}],"url":"\/documentation\/gfpsdk\/gfpadloader\/setbannerdelegate(_:banneroptions:)","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoader\/setBannerDelegate(_:bannerOptions:)","role":"symbol","title":"setBannerDelegate(_:bannerOptions:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setBannerDelegate","kind":"identifier"},{"text":"(any ","kind":"text"},{"text":"GFPBannerViewDelegate","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)GFPBannerViewDelegate"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"bannerOptions"},{"text":": ","kind":"text"},{"text":"GFPAdBannerOptions","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdBannerOptions"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"setBannerDelegate:bannerOptions:","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdLoader/setNativeSimpleDelegate(_:nativeSimpleOptions:)":{"type":"topic","title":"setNativeSimpleDelegate(_:nativeSimpleOptions:)","abstract":[{"text":"통합 로더를 통해 네이티브 이미지형 (Native Simple) 로드 시 사용.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setNativeSimpleDelegate","kind":"identifier"},{"kind":"text","text":"(any "},{"text":"GFPNativeSimpleAdDelegate","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)GFPNativeSimpleAdDelegate"},{"kind":"text","text":", "},{"kind":"externalParam","text":"nativeSimpleOptions"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPAdNativeSimpleOptions","text":"GFPAdNativeSimpleOptions","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"url":"\/documentation\/gfpsdk\/gfpadloader\/setnativesimpledelegate(_:nativesimpleoptions:)","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoader\/setNativeSimpleDelegate(_:nativeSimpleOptions:)","navigatorTitle":[{"text":"setNativeSimpleDelegate:nativeSimpleOptions:","kind":"identifier"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdLoader/adLoaderDidFailWithError(_:responseInfo:)":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoader\/adLoaderDidFailWithError(_:responseInfo:)","role":"symbol","navigatorTitle":[{"text":"adLoaderDidFailWithError:responseInfo:","kind":"identifier"}],"title":"adLoaderDidFailWithError(_:responseInfo:)","abstract":[],"url":"\/documentation\/gfpsdk\/gfpadloader\/adloaderdidfailwitherror(_:responseinfo:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"adLoaderDidFailWithError"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@NaverAdsServices@objc(cs)GFPError","kind":"typeIdentifier","text":"GFPError"},{"kind":"text","text":", "},{"text":"responseInfo","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"GFPLoadResponseInfo","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPLoadResponseInfo"},{"text":")","kind":"text"}],"type":"topic","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdLoader/nativeSimpleOptions":{"type":"topic","title":"nativeSimpleOptions","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nativeSimpleOptions","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPAdNativeSimpleOptions","kind":"typeIdentifier","text":"GFPAdNativeSimpleOptions"}],"url":"\/documentation\/gfpsdk\/gfpadloader\/nativesimpleoptions","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoader\/nativeSimpleOptions","navigatorTitle":[{"kind":"identifier","text":"nativeSimpleOptions"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdLoader/loadAdWith(data:)":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"loadAdWith","kind":"identifier"},{"kind":"text","text":"("},{"text":"data","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier","text":"Data"},{"text":")","kind":"text"}],"title":"loadAdWith(data:)","type":"topic","navigatorTitle":[{"text":"loadAdWithData:","kind":"identifier"}],"abstract":[{"type":"text","text":"통합 로더에 광고 요청, WF 단계를 건너뛰기 위한 요청"}],"url":"\/documentation\/gfpsdk\/gfpadloader\/loadadwith(data:)","kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoader\/loadAdWith(data:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdLoader":{"navigatorTitle":[{"text":"GFPAdLoader","kind":"identifier"}],"kind":"symbol","title":"GFPAdLoader","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoader","url":"\/documentation\/gfpsdk\/gfpadloader","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPAdLoader"}],"type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdLoader/adParam":{"url":"\/documentation\/gfpsdk\/gfpadloader\/adparam","abstract":[],"title":"adParam","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoader\/adParam","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"adParam"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"adParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPAdParam","kind":"typeIdentifier","text":"GFPAdParam"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdLoader/loadAd()":{"url":"\/documentation\/gfpsdk\/gfpadloader\/loadad()","title":"loadAd()","abstract":[{"text":"통합 로더에 광고 요청","type":"text"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoader\/loadAd()","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"loadAd"}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"loadAd"},{"kind":"text","text":"()"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdLoader/rootViewController":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"rootViewController"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier","text":"UIViewController"},{"text":"?","kind":"text"}],"title":"rootViewController","type":"topic","navigatorTitle":[{"text":"rootViewController","kind":"identifier"}],"abstract":[],"url":"\/documentation\/gfpsdk\/gfpadloader\/rootviewcontroller","kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoader\/rootViewController"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdLoader/loadAdWith(string:)":{"role":"symbol","type":"topic","navigatorTitle":[{"text":"loadAdWithString:","kind":"identifier"}],"abstract":[{"text":"통합 로더에 광고 요청, WF 단계를 건너뛰기 위한 요청","type":"text"}],"title":"loadAdWith(string:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"loadAdWith","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"string"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoader\/loadAdWith(string:)","url":"\/documentation\/gfpsdk\/gfpadloader\/loadadwith(string:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdLoader/nativeSimpleDelegate":{"type":"topic","title":"nativeSimpleDelegate","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"nativeSimpleDelegate","kind":"identifier"},{"text":": (any ","kind":"text"},{"text":"GFPNativeSimpleAdDelegate","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)GFPNativeSimpleAdDelegate"},{"text":")?","kind":"text"}],"url":"\/documentation\/gfpsdk\/gfpadloader\/nativesimpledelegate","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoader\/nativeSimpleDelegate","navigatorTitle":[{"text":"nativeSimpleDelegate","kind":"identifier"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdLoader/bannerOptions":{"kind":"symbol","url":"\/documentation\/gfpsdk\/gfpadloader\/banneroptions","type":"topic","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"bannerOptions","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdBannerOptions","text":"GFPAdBannerOptions"}],"navigatorTitle":[{"text":"bannerOptions","kind":"identifier"}],"title":"bannerOptions","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoader\/bannerOptions"},"doc://com.navercorp.da.gfp.GFPSDK/s7CVarArgP":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/SQ":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdLoader/init(unitID:rootViewController:adParam:)":{"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"unitID","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"rootViewController","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier","text":"UIViewController"},{"kind":"text","text":", "},{"text":"adParam","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"GFPAdParam","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdParam"},{"kind":"text","text":")"}],"title":"init(unitID:rootViewController:adParam:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithUnitID:rootViewController:adParam:"}],"abstract":[{"text":"통합 로더 초기화.","type":"text"}],"url":"\/documentation\/gfpsdk\/gfpadloader\/init(unitid:rootviewcontroller:adparam:)","kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoader\/init(unitID:rootViewController:adParam:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdLoader/loadAdWith(dict:)":{"type":"topic","title":"loadAdWith(dict:)","abstract":[{"type":"text","text":"통합 로더에 광고 요청, WF 단계를 건너뛰기 위한 요청"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"loadAdWith","kind":"identifier"},{"text":"(","kind":"text"},{"text":"dict","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"kind":"text","text":"])"}],"url":"\/documentation\/gfpsdk\/gfpadloader\/loadadwith(dict:)","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoader\/loadAdWith(dict:)","navigatorTitle":[{"text":"loadAdWithDict:","kind":"identifier"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdLoader/adCallDelegate":{"fragments":[{"kind":"identifier","text":"adCallDelegate"}],"kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoader\/adCallDelegate","abstract":[],"role":"symbol","url":"\/documentation\/gfpsdk\/gfpadloader\/adcalldelegate","title":"adCallDelegate","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"GFPAdLoader"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"GFPAdLoader","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"GFPAdLoader","kind":"identifier"}]},{"path":"\/topicSections","value":[{"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoader\/adCallDelegate","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoader\/adParam","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoader\/adUnitID","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoader\/bannerDelegate","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoader\/bannerOptions","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoader\/delegate","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoader\/nativeDelegate","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoader\/nativeOptions","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoader\/nativeSimpleDelegate","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoader\/nativeSimpleOptions","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoader\/requestTimeoutInterval","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoader\/rootViewController"],"generated":true},{"generated":true,"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoader\/adLoaderDidFailWithError(_:responseInfo:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoader\/init(unitID:rootViewController:adParam:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoader\/loadAd()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoader\/loadAdInternal(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoader\/loadAdWith(data:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoader\/loadAdWith(dict:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoader\/loadAdWith(string:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoader\/setBannerDelegate(_:bannerOptions:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoader\/setNativeDelegate(_:nativeOptions:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoader\/setNativeSimpleDelegate(_:nativeSimpleOptions:)"]}],"op":"replace"},{"value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject"],"type":"inheritsFrom"}],"op":"replace","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPAdLoader"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoader~1loadAdInternal(_:)\/title","op":"replace","value":"loadAdInternal:"},{"value":[{"text":"- ","kind":"text"},{"text":"loadAdInternal:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoader~1loadAdInternal(_:)\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoader~1nativeDelegate\/title","value":"nativeDelegate","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoader~1nativeDelegate\/fragments","value":[{"text":"nativeDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoader~1setNativeDelegate(_:nativeOptions:)\/title","op":"replace","value":"setNativeDelegate:nativeOptions:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setNativeDelegate:nativeOptions:"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoader~1setNativeDelegate(_:nativeOptions:)\/fragments"},{"value":"delegate","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoader~1delegate\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoader~1delegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"delegate"}]},{"value":"adUnitID","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoader~1adUnitID\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoader~1adUnitID\/fragments","value":[{"kind":"identifier","text":"adUnitID"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoader~1nativeOptions\/title","value":"nativeOptions","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoader~1nativeOptions\/fragments","value":[{"text":"nativeOptions","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoader~1requestTimeoutInterval\/title","op":"replace","value":"requestTimeoutInterval"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoader~1requestTimeoutInterval\/fragments","value":[{"kind":"identifier","text":"requestTimeoutInterval"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoader~1bannerDelegate\/title","value":"bannerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoader~1bannerDelegate\/fragments","value":[{"kind":"identifier","text":"bannerDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoader~1setBannerDelegate(_:bannerOptions:)\/title","value":"setBannerDelegate:bannerOptions:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"setBannerDelegate:bannerOptions:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoader~1setBannerDelegate(_:bannerOptions:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoader~1setNativeSimpleDelegate(_:nativeSimpleOptions:)\/title","value":"setNativeSimpleDelegate:nativeSimpleOptions:"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoader~1setNativeSimpleDelegate(_:nativeSimpleOptions:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"setNativeSimpleDelegate:nativeSimpleOptions:"}],"op":"replace"},{"value":"adLoaderDidFailWithError:responseInfo:","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoader~1adLoaderDidFailWithError(_:responseInfo:)\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoader~1adLoaderDidFailWithError(_:responseInfo:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"adLoaderDidFailWithError:responseInfo:"}],"op":"replace"},{"value":"nativeSimpleOptions","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoader~1nativeSimpleOptions\/title"},{"op":"replace","value":[{"text":"nativeSimpleOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoader~1nativeSimpleOptions\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoader~1loadAdWith(data:)\/title","value":"loadAdWithData:"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoader~1loadAdWith(data:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"loadAdWithData:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoader\/title","op":"replace","value":"GFPAdLoader"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoader\/fragments","value":[{"text":"GFPAdLoader","kind":"identifier"}]},{"op":"replace","value":[{"text":"GFPAdLoader","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoader\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoader~1adParam\/title","value":"adParam"},{"value":[{"kind":"identifier","text":"adParam"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoader~1adParam\/fragments"},{"op":"replace","value":"loadAd","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoader~1loadAd()\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoader~1loadAd()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"loadAd"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoader~1rootViewController\/title","value":"rootViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoader~1rootViewController\/fragments","value":[{"text":"rootViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoader~1loadAdWith(string:)\/title","op":"replace","value":"loadAdWithString:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"loadAdWithString:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoader~1loadAdWith(string:)\/fragments"},{"value":"nativeSimpleDelegate","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoader~1nativeSimpleDelegate\/title"},{"value":[{"text":"nativeSimpleDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoader~1nativeSimpleDelegate\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoader~1bannerOptions\/title","value":"bannerOptions","op":"replace"},{"op":"replace","value":[{"text":"bannerOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoader~1bannerOptions\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoader~1init(unitID:rootViewController:adParam:)\/title","op":"replace","value":"initWithUnitID:rootViewController:adParam:"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoader~1init(unitID:rootViewController:adParam:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithUnitID:rootViewController:adParam:"}]},{"value":"loadAdWithDict:","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoader~1loadAdWith(dict:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"loadAdWithDict:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoader~1loadAdWith(dict:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}