{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPAdLoaderDelegate","kind":"identifier"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(pl)NSObject","text":"NSObjectProtocol","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject"]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpadloaderdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gfpsdk\/gfpadloaderdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"GFPAdLoaderDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPAdLoaderDelegate","kind":"identifier"}],"roleHeading":"Protocol","role":"symbol","externalID":"c:objc(pl)GFPAdLoaderDelegate","symbolKind":"protocol","navigatorTitle":[{"text":"GFPAdLoaderDelegate","kind":"identifier"}],"modules":[{"name":"GFPSDK"}]},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoaderDelegate","interfaceLanguage":"swift"},"topicSections":[{"generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoaderDelegate\/adLoader(_:didFailWithError:responseInfo:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoaderDelegate\/adLoader(_:didReceive:)-18hky","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoaderDelegate\/adLoader(_:didReceive:)-7shq6","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoaderDelegate\/adLoader(_:didReceiveBannerAd:)"],"title":"Instance Methods"}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdLoaderDelegate/adLoader(_:didReceive:)-18hky":{"abstract":[{"type":"text","text":"광고가 성공적으로 로드될 경우 호출됩니다. - NativeSimple"}],"type":"topic","title":"adLoader(_:didReceive:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"adLoader"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdLoader","text":"GFPAdLoader"},{"text":"!, ","kind":"text"},{"text":"didReceive","kind":"externalParam"},{"kind":"text","text":": "},{"text":"GFPNativeSimpleAd","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPNativeSimpleAd"},{"text":"!)","kind":"text"}],"url":"\/documentation\/gfpsdk\/gfpadloaderdelegate\/adloader(_:didreceive:)-18hky","role":"symbol","required":true,"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoaderDelegate\/adLoader(_:didReceive:)-18hky","navigatorTitle":[{"text":"adLoader:didReceiveNativeSimpleAd:","kind":"identifier"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdLoaderDelegate/adLoader(_:didFailWithError:responseInfo:)":{"abstract":[{"type":"text","text":"광고 로드에 실패한 경우 호출됩니다."}],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"adLoader"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdLoader","text":"GFPAdLoader"},{"text":"!, ","kind":"text"},{"text":"didFailWithError","kind":"externalParam"},{"kind":"text","text":": "},{"text":"GFPError","kind":"typeIdentifier","preciseIdentifier":"c:@M@NaverAdsServices@objc(cs)GFPError"},{"text":"!, ","kind":"text"},{"text":"responseInfo","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPLoadResponseInfo","text":"GFPLoadResponseInfo"},{"text":"!)","kind":"text"}],"url":"\/documentation\/gfpsdk\/gfpadloaderdelegate\/adloader(_:didfailwitherror:responseinfo:)","navigatorTitle":[{"kind":"identifier","text":"adLoader:didFailWithError:responseInfo:"}],"type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoaderDelegate\/adLoader(_:didFailWithError:responseInfo:)","title":"adLoader(_:didFailWithError:responseInfo:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdLoaderDelegate/adLoader(_:didReceiveBannerAd:)":{"abstract":[{"text":"광고가 성공적으로 로드될 경우 호출됩니다. - Banner","type":"text"}],"type":"topic","title":"adLoader(_:didReceiveBannerAd:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"adLoader","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPAdLoader","text":"GFPAdLoader","kind":"typeIdentifier"},{"text":"!, ","kind":"text"},{"kind":"externalParam","text":"didReceiveBannerAd"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPBannerView","text":"GFPBannerView","kind":"typeIdentifier"},{"kind":"text","text":"!)"}],"url":"\/documentation\/gfpsdk\/gfpadloaderdelegate\/adloader(_:didreceivebannerad:)","role":"symbol","required":true,"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoaderDelegate\/adLoader(_:didReceiveBannerAd:)","navigatorTitle":[{"text":"adLoader:didReceiveBannerAd:","kind":"identifier"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)NSObject":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdLoaderDelegate":{"navigatorTitle":[{"kind":"identifier","text":"GFPAdLoaderDelegate"}],"title":"GFPAdLoaderDelegate","url":"\/documentation\/gfpsdk\/gfpadloaderdelegate","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoaderDelegate","role":"symbol","type":"topic","kind":"symbol","abstract":[],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPAdLoaderDelegate"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdLoaderDelegate/adLoader(_:didReceive:)-7shq6":{"abstract":[{"text":"광고가 성공적으로 로드될 경우 호출됩니다. - Native","type":"text"}],"type":"topic","title":"adLoader(_:didReceive:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"adLoader"},{"text":"(","kind":"text"},{"text":"GFPAdLoader","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdLoader"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"didReceive"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPNativeAd","text":"GFPNativeAd","kind":"typeIdentifier"},{"text":"!)","kind":"text"}],"url":"\/documentation\/gfpsdk\/gfpadloaderdelegate\/adloader(_:didreceive:)-7shq6","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoaderDelegate\/adLoader(_:didReceive:)-7shq6","navigatorTitle":[{"text":"adLoader:didReceiveNativeAd:","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Protocol","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"GFPAdLoaderDelegate"},{"op":"replace","value":"protocol","path":"\/metadata\/symbolKind"},{"value":[{"text":"GFPAdLoaderDelegate","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"GFPAdLoaderDelegate","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"value":[{"generated":true,"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoaderDelegate\/adLoader(_:didFailWithError:responseInfo:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoaderDelegate\/adLoader(_:didReceive:)-18hky","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoaderDelegate\/adLoader(_:didReceive:)-7shq6","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoaderDelegate\/adLoader(_:didReceiveBannerAd:)"]}],"path":"\/topicSections","op":"replace"},{"op":"replace","path":"\/relationshipsSections","value":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject"]}]},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPAdLoaderDelegate"},{"text":" <","kind":"text"},{"preciseIdentifier":"c:objc(pl)NSObject","text":"NSObject","kind":"typeIdentifier"},{"text":">","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoaderDelegate~1adLoader(_:didReceive:)-18hky\/title","value":"adLoader:didReceiveNativeSimpleAd:"},{"value":[{"text":"- ","kind":"text"},{"text":"adLoader:didReceiveNativeSimpleAd:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoaderDelegate~1adLoader(_:didReceive:)-18hky\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoaderDelegate~1adLoader(_:didFailWithError:responseInfo:)\/title","value":"adLoader:didFailWithError:responseInfo:","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"adLoader:didFailWithError:responseInfo:"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoaderDelegate~1adLoader(_:didFailWithError:responseInfo:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoaderDelegate~1adLoader(_:didReceiveBannerAd:)\/title","value":"adLoader:didReceiveBannerAd:"},{"value":[{"text":"- ","kind":"text"},{"text":"adLoader:didReceiveBannerAd:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoaderDelegate~1adLoader(_:didReceiveBannerAd:)\/fragments"},{"value":"GFPAdLoaderDelegate","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoaderDelegate\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoaderDelegate\/fragments","op":"replace","value":[{"text":"GFPAdLoaderDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoaderDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"GFPAdLoaderDelegate"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoaderDelegate~1adLoader(_:didReceive:)-7shq6\/title","op":"replace","value":"adLoader:didReceiveNativeAd:"},{"value":[{"kind":"text","text":"- "},{"text":"adLoader:didReceiveNativeAd:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoaderDelegate~1adLoader(_:didReceive:)-7shq6\/fragments"}]}]}