{"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/gfpsdk\/gfpadparam"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gfpsdk\/gfpadparam"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdParam"},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"GFPAdParam"}],"externalID":"c:objc(cs)GFPAdParam","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPAdParam","kind":"identifier"}],"symbolKind":"class","title":"GFPAdParam","roleHeading":"Class","modules":[{"name":"GFPSDK"}],"role":"symbol"},"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPAdParam"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"topicSections":[{"generated":true,"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdParam\/apsParam","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdParam\/contentInfo","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdParam\/currentPageUrl","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdParam\/customUserParam","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdParam\/keywords","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdParam\/optOut","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdParam\/prebidHBParam","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdParam\/referrerPageUrl"],"title":"Instance Properties","anchor":"Instance-Properties"},{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdParam\/adCallQuery(with:)"],"anchor":"Instance-Methods"}],"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject"]},{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s7CVarArgP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s23CustomStringConvertibleP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdParam/prebidHBParam":{"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"prebidHBParam","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?"}],"url":"\/documentation\/gfpsdk\/gfpadparam\/prebidhbparam","navigatorTitle":[{"text":"prebidHBParam","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdParam\/prebidHBParam","title":"prebidHBParam","abstract":[{"text":"PrebidMobile 헤더 비딩 파라미터 (주의! Dictionary 의 Key\/Value는 모두 문자열 타입이어야 합니다.)","type":"text"}]},"doc://com.navercorp.da.gfp.GFPSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.navercorp.da.gfp.GFPSDK/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject","title":"NSObject"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdParam/apsParam":{"kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdParam\/apsParam","url":"\/documentation\/gfpsdk\/gfpadparam\/apsparam","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"apsParam"},{"text":": ","kind":"text"},{"text":"GFPAPSAdParam","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAPSAdParam"},{"kind":"text","text":"?"}],"title":"apsParam","role":"symbol","type":"topic","navigatorTitle":[{"text":"apsParam","kind":"identifier"}],"abstract":[{"type":"text","text":"Amazon  헤더 비딩 파라미터."}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdParam/contentInfo":{"abstract":[{"type":"text","text":"Communication Ad 용 Content Info."}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdParam\/contentInfo","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"contentInfo"},{"kind":"text","text":": "},{"text":"GFPContentInfo","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPContentInfo"},{"text":"?","kind":"text"}],"type":"topic","navigatorTitle":[{"text":"contentInfo","kind":"identifier"}],"title":"contentInfo","kind":"symbol","url":"\/documentation\/gfpsdk\/gfpadparam\/contentinfo"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdParam":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdParam","abstract":[],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPAdParam"}],"navigatorTitle":[{"text":"GFPAdParam","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpadparam","type":"topic","kind":"symbol","title":"GFPAdParam"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdParam/keywords":{"abstract":[{"text":"현재 컨텐츠를 설명하는 키워드 목록","type":"text"}],"title":"keywords","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"keywords","kind":"identifier"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"]?"}],"url":"\/documentation\/gfpsdk\/gfpadparam\/keywords","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdParam\/keywords","navigatorTitle":[{"kind":"identifier","text":"keywords"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdParam/currentPageUrl":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"currentPageUrl"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic","title":"currentPageUrl","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"현재 페이지를 나타내는 url"}],"navigatorTitle":[{"text":"currentPageUrl","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpadparam\/currentpageurl","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdParam\/currentPageUrl"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.navercorp.da.gfp.GFPSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH","title":"Swift.Hashable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdParam/adCallQuery(with:)":{"navigatorTitle":[{"text":"adCallQueryWith:","kind":"identifier"}],"title":"adCallQuery(with:)","abstract":[{"type":"text","text":"s2s waterfall skip을 위해 지원하는 queryString."}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdParam\/adCallQuery(with:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"adCallQuery","kind":"identifier"},{"kind":"text","text":"("},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"url":"\/documentation\/gfpsdk\/gfpadparam\/adcallquery(with:)","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdParam/referrerPageUrl":{"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"referrerPageUrl"}],"abstract":[{"text":"referrer url","type":"text"}],"kind":"symbol","title":"referrerPageUrl","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"referrerPageUrl"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdParam\/referrerPageUrl","url":"\/documentation\/gfpsdk\/gfpadparam\/referrerpageurl"},"doc://com.navercorp.da.gfp.GFPSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdParam/customUserParam":{"type":"topic","abstract":[{"text":"추가 파라미터 (주의! 추가 파라미터 사전의 키\/값은 모두 문자열 타입이어야 합니다.)","type":"text"}],"title":"customUserParam","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"customUserParam","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"]?"}],"url":"\/documentation\/gfpsdk\/gfpadparam\/customuserparam","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdParam\/customUserParam","navigatorTitle":[{"text":"customUserParam","kind":"identifier"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdParam/optOut":{"url":"\/documentation\/gfpsdk\/gfpadparam\/optout","navigatorTitle":[{"kind":"identifier","text":"optOut"}],"deprecated":true,"title":"optOut","kind":"symbol","type":"topic","role":"symbol","abstract":[{"text":"opt-out (0: 미설정, 1: 설정)","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"optOut"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdParam\/optOut"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","value":"GFPAdParam","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"GFPAdParam"}]},{"op":"replace","value":[{"text":"GFPAdParam","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","op":"replace","value":[{"generated":true,"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdParam\/apsParam","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdParam\/contentInfo","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdParam\/currentPageUrl","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdParam\/customUserParam","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdParam\/keywords","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdParam\/optOut","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdParam\/prebidHBParam","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdParam\/referrerPageUrl"],"anchor":"Instance-Properties","title":"Instance Properties"},{"generated":true,"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdParam\/adCallQuery(with:)"],"anchor":"Instance-Methods","title":"Instance Methods"}]},{"op":"replace","value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject"],"type":"inheritsFrom"}],"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPAdParam","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdParam~1prebidHBParam\/title","value":"prebidHBParam"},{"value":[{"text":"prebidHBParam","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdParam~1prebidHBParam\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdParam~1apsParam\/title","value":"apsParam","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdParam~1apsParam\/fragments","value":[{"text":"apsParam","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdParam~1contentInfo\/title","value":"contentInfo","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdParam~1contentInfo\/fragments","value":[{"text":"contentInfo","kind":"identifier"}]},{"value":"GFPAdParam","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdParam\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdParam\/fragments","value":[{"kind":"identifier","text":"GFPAdParam"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdParam\/navigatorTitle","value":[{"kind":"identifier","text":"GFPAdParam"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdParam~1keywords\/title","op":"replace","value":"keywords"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdParam~1keywords\/fragments","op":"replace","value":[{"text":"keywords","kind":"identifier"}]},{"value":"currentPageUrl","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdParam~1currentPageUrl\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"currentPageUrl"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdParam~1currentPageUrl\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdParam~1adCallQuery(with:)\/title","value":"adCallQueryWith:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"adCallQueryWith:"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdParam~1adCallQuery(with:)\/fragments"},{"value":"referrerPageUrl","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdParam~1referrerPageUrl\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdParam~1referrerPageUrl\/fragments","value":[{"text":"referrerPageUrl","kind":"identifier"}]},{"value":"customUserParam","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdParam~1customUserParam\/title"},{"value":[{"kind":"identifier","text":"customUserParam"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdParam~1customUserParam\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdParam~1optOut\/title","value":"optOut"},{"op":"replace","value":[{"kind":"identifier","text":"optOut"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdParam~1optOut\/fragments"}]}]}