{"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPAdManager"}],"platforms":["iOS"]}]}],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject"],"type":"inheritsFrom"},{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s7CVarArgP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s23CustomStringConvertibleP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"kind":"symbol","identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdManager","interfaceLanguage":"swift"},"topicSections":[{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdManager\/adConfiguration()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdManager\/appendCookie(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdManager\/clearCookie()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdManager\/clearMemoryCache()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdManager\/cookie()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdManager\/examineWebViewStatus(_:result:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdManager\/isSdkInitialized()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdManager\/register(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdManager\/sdkVersion()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdManager\/setAdConfiguration(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdManager\/setCookie(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdManager\/setUserParam(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdManager\/setup(withPublisherCd:serviceCd:target:completionHandler:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdManager\/setup(withPublisherCd:serviceCd:target:configuration:completionHandler:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdManager\/setup(withPublisherCd:target:completionHandler:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdManager\/setup(withPublisherCd:target:configuration:completionHandler:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdManager\/userParam()"],"title":"Type Methods","generated":true,"anchor":"Type-Methods"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"externalID":"c:objc(cs)GFPAdManager","role":"symbol","modules":[{"name":"GFPSDK"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPAdManager"}],"navigatorTitle":[{"kind":"identifier","text":"GFPAdManager"}],"symbolKind":"class","title":"GFPAdManager","roleHeading":"Class"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpadmanager"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpadmanager"]}],"sections":[],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdManager/setAdConfiguration(_:)":{"type":"topic","url":"\/documentation\/gfpsdk\/gfpadmanager\/setadconfiguration(_:)","kind":"symbol","abstract":[{"type":"text","text":"GFPSDK 설정"}],"navigatorTitle":[{"kind":"identifier","text":"setAdConfiguration:"}],"role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdManager\/setAdConfiguration(_:)","title":"setAdConfiguration(_:)","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setAdConfiguration"},{"text":"(","kind":"text"},{"text":"GFPAdConfiguration","preciseIdentifier":"c:objc(cs)GFPAdConfiguration","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdManager/cookie()":{"type":"topic","url":"\/documentation\/gfpsdk\/gfpadmanager\/cookie()","abstract":[{"text":"GFPSDK Cookie 조회","type":"text"}],"title":"cookie()","kind":"symbol","navigatorTitle":[{"text":"cookie","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdManager\/cookie()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cookie"},{"kind":"text","text":"() -> ["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"]","kind":"text"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/s7CVarArgP":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdManager/clearMemoryCache()":{"type":"topic","url":"\/documentation\/gfpsdk\/gfpadmanager\/clearmemorycache()","abstract":[{"text":"MemoryCache Clear (for memory warning)","type":"text"}],"title":"clearMemoryCache()","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"clearMemoryCache"}],"role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdManager\/clearMemoryCache()","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"clearMemoryCache","kind":"identifier"},{"kind":"text","text":"()"}]},"doc://com.navercorp.da.gfp.GFPSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdManager/isSdkInitialized()":{"type":"topic","url":"\/documentation\/gfpsdk\/gfpadmanager\/issdkinitialized()","abstract":[{"type":"text","text":"GFPSDK 초기화 여부"}],"title":"isSdkInitialized()","kind":"symbol","navigatorTitle":[{"text":"isSdkInitialized","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdManager\/isSdkInitialized()","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isSdkInitialized"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdManager/setup(withPublisherCd:serviceCd:target:completionHandler:)":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setup","kind":"identifier"},{"kind":"text","text":"("},{"text":"withPublisherCd","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"serviceCd"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"target"},{"text":": (any ","kind":"text"},{"text":"GFPAdManagerDelegate","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)GFPAdManagerDelegate"},{"text":")?, ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:GFPAdManager.h@T@GFPAdManagerCompletionHandler","text":"GFPAdManagerCompletionHandler","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","url":"\/documentation\/gfpsdk\/gfpadmanager\/setup(withpublishercd:servicecd:target:completionhandler:)","abstract":[{"text":"광고 매니저를 초기화 합니다.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"GFP를 통해 광고를 받아올 광고 provider 등록할 필요 없이, cocoapods 등록한 provider 별로 초기화가 이루어 집니다."},{"type":"text","text":" "},{"text":"provider에 따라 초기화에 시간이 오래 걸릴 수 있으므로 어플리케이션 로드시점 한번만 호출해주시면 됩니다. (eg. IMA는 구글 문서기준 약 1~2초 소요)","type":"text"},{"type":"text","text":" "},{"type":"text","text":"여기서 초기화되지 않은 provider로 부터의 광고는 이후 서버로부터의 응답결과와 관계없이 처리되지 않습니다."},{"type":"text","text":" "},{"type":"text","text":"오류결과는 completionHandler의 error 에서 확인해 주세요."}],"role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdManager\/setup(withPublisherCd:serviceCd:target:completionHandler:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"setupWithPublisherCd:serviceCd:target:completionHandler:"}],"title":"setup(withPublisherCd:serviceCd:target:completionHandler:)"},"doc://com.navercorp.da.gfp.GFPSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/SQ":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/SH":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdManager/setCookie(_:)":{"type":"topic","url":"\/documentation\/gfpsdk\/gfpadmanager\/setcookie(_:)","abstract":[{"text":"GFPSDK Cookie 세팅","type":"text"}],"title":"setCookie(_:)","kind":"symbol","navigatorTitle":[{"text":"setCookie:","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdManager\/setCookie(_:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setCookie","kind":"identifier"},{"text":"([","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"])","kind":"text"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdManager/sdkVersion()":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sdkVersion","kind":"identifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"url":"\/documentation\/gfpsdk\/gfpadmanager\/sdkversion()","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"GFPSDK Version."}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdManager\/sdkVersion()","role":"symbol","navigatorTitle":[{"text":"sdkVersion","kind":"identifier"}],"title":"sdkVersion()"},"doc://com.navercorp.da.gfp.GFPSDK/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdManager":{"abstract":[],"kind":"symbol","title":"GFPAdManager","navigatorTitle":[{"text":"GFPAdManager","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdManager","url":"\/documentation\/gfpsdk\/gfpadmanager","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPAdManager","kind":"identifier"}],"role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdManager/setUserParam(_:)":{"role":"symbol","title":"setUserParam(_:)","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"setUserParam","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPUserParam","text":"GFPUserParam","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"setUserParam:"}],"abstract":[{"text":"유저 타겟 정보 설정","type":"text"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdManager\/setUserParam(_:)","type":"topic","url":"\/documentation\/gfpsdk\/gfpadmanager\/setuserparam(_:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdManager/appendCookie(_:)":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"appendCookie","kind":"identifier"},{"kind":"text","text":"(["},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"])","kind":"text"}],"url":"\/documentation\/gfpsdk\/gfpadmanager\/appendcookie(_:)","type":"topic","kind":"symbol","abstract":[{"text":"Add GFPSDK cookie","type":"text"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdManager\/appendCookie(_:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"appendCookie:"}],"title":"appendCookie(_:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdManager/setup(withPublisherCd:serviceCd:target:configuration:completionHandler:)":{"type":"topic","url":"\/documentation\/gfpsdk\/gfpadmanager\/setup(withpublishercd:servicecd:target:configuration:completionhandler:)","abstract":[{"text":"광고 매니저를 초기화 합니다.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"GFP를 통해 광고를 받아올 광고 provider 등록할 필요 없이, cocoapods 등록한 provider 별로 초기화가 이루어 집니다."},{"text":" ","type":"text"},{"type":"text","text":"provider에 따라 초기화에 시간이 오래 걸릴 수 있으므로 어플리케이션 로드시점 한번만 호출해주시면 됩니다. (eg. IMA는 구글 문서기준 약 1~2초 소요)"},{"text":" ","type":"text"},{"type":"text","text":"여기서 초기화되지 않은 provider로 부터의 광고는 이후 서버로부터의 응답결과와 관계없이 처리되지 않습니다."},{"type":"text","text":" "},{"text":"오류결과는 completionHandler의 error 에서 확인해 주세요.","type":"text"}],"title":"setup(withPublisherCd:serviceCd:target:configuration:completionHandler:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"setupWithPublisherCd:serviceCd:target:configuration:completionHandler:"}],"role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdManager\/setup(withPublisherCd:serviceCd:target:configuration:completionHandler:)","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setup","kind":"identifier"},{"kind":"text","text":"("},{"text":"withPublisherCd","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"text":"serviceCd","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"target","kind":"externalParam"},{"kind":"text","text":": (any "},{"preciseIdentifier":"c:objc(pl)GFPAdManagerDelegate","text":"GFPAdManagerDelegate","kind":"typeIdentifier"},{"kind":"text","text":")?, "},{"kind":"externalParam","text":"configuration"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"GFPAdConfiguration","preciseIdentifier":"c:objc(cs)GFPAdConfiguration"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GFPAdManagerCompletionHandler","preciseIdentifier":"c:GFPAdManager.h@T@GFPAdManagerCompletionHandler"},{"kind":"text","text":")"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdManager/setup(withPublisherCd:target:completionHandler:)":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setup"},{"text":"(","kind":"text"},{"text":"withPublisherCd","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?, ","kind":"text"},{"text":"target","kind":"externalParam"},{"kind":"text","text":": (any "},{"kind":"typeIdentifier","text":"GFPAdManagerDelegate","preciseIdentifier":"c:objc(pl)GFPAdManagerDelegate"},{"text":")?, ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:GFPAdManager.h@T@GFPAdManagerCompletionHandler","text":"GFPAdManagerCompletionHandler"},{"text":")","kind":"text"}],"url":"\/documentation\/gfpsdk\/gfpadmanager\/setup(withpublishercd:target:completionhandler:)","type":"topic","kind":"symbol","abstract":[{"text":"광고 매니저를 초기화 합니다.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"GFP를 통해 광고를 받아올 광고 provider 등록할 필요 없이, cocoapods 등록한 provider 별로 초기화가 이루어 집니다."},{"text":" ","type":"text"},{"type":"text","text":"provider에 따라 초기화에 시간이 오래 걸릴 수 있으므로 어플리케이션 로드시점 한번만 호출해주시면 됩니다. (eg. IMA는 구글 문서기준 약 1~2초 소요)"},{"text":" ","type":"text"},{"type":"text","text":"여기서 초기화되지 않은 provider로 부터의 광고는 이후 서버로부터의 응답결과와 관계없이 처리되지 않습니다."},{"type":"text","text":" "},{"text":"오류결과는 completionHandler의 error 에서 확인해 주세요.","type":"text"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdManager\/setup(withPublisherCd:target:completionHandler:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"setupWithPublisherCd:target:completionHandler:"}],"title":"setup(withPublisherCd:target:completionHandler:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdManager/examineWebViewStatus(_:result:)":{"url":"\/documentation\/gfpsdk\/gfpadmanager\/examinewebviewstatus(_:result:)","navigatorTitle":[{"kind":"identifier","text":"examineWebViewStatus:result:"}],"title":"examineWebViewStatus(_:result:)","kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"examineWebViewStatus","kind":"identifier"},{"text":"(","kind":"text"},{"text":"WKWebView","preciseIdentifier":"c:objc(cs)WKWebView","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"result"},{"kind":"text","text":": ((any "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":")?, [","kind":"text"},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]) -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":")"}],"abstract":[{"text":"Check for web view registration success  .","type":"text"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdManager\/examineWebViewStatus(_:result:)"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdManager/register(_:)":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"register"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)WKWebView","kind":"typeIdentifier","text":"WKWebView"},{"text":")","kind":"text"}],"url":"\/documentation\/gfpsdk\/gfpadmanager\/register(_:)","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Register web view for interaction with iOS SDK."}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdManager\/register(_:)","role":"symbol","navigatorTitle":[{"text":"registerWebView:","kind":"identifier"}],"title":"register(_:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdManager/clearCookie()":{"type":"topic","url":"\/documentation\/gfpsdk\/gfpadmanager\/clearcookie()","abstract":[{"text":"Remove all oookies.","type":"text"}],"title":"clearCookie()","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"clearCookie"}],"role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdManager\/clearCookie()","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"clearCookie","kind":"identifier"},{"kind":"text","text":"()"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdManager/setup(withPublisherCd:target:configuration:completionHandler:)":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setup"},{"kind":"text","text":"("},{"text":"withPublisherCd","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"target"},{"kind":"text","text":": (any "},{"text":"GFPAdManagerDelegate","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)GFPAdManagerDelegate"},{"kind":"text","text":")?, "},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"text":"GFPAdConfiguration","preciseIdentifier":"c:objc(cs)GFPAdConfiguration","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"completionHandler","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"GFPAdManagerCompletionHandler","kind":"typeIdentifier","preciseIdentifier":"c:GFPAdManager.h@T@GFPAdManagerCompletionHandler"},{"kind":"text","text":")"}],"url":"\/documentation\/gfpsdk\/gfpadmanager\/setup(withpublishercd:target:configuration:completionhandler:)","type":"topic","kind":"symbol","abstract":[{"text":"광고 매니저를 초기화 합니다.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"GFP를 통해 광고를 받아올 광고 provider 등록할 필요 없이, cocoapods 등록한 provider 별로 초기화가 이루어 집니다."},{"type":"text","text":" "},{"type":"text","text":"provider에 따라 초기화에 시간이 오래 걸릴 수 있으므로 어플리케이션 로드시점 한번만 호출해주시면 됩니다. (eg. IMA는 구글 문서기준 약 1~2초 소요)"},{"text":" ","type":"text"},{"type":"text","text":"여기서 초기화되지 않은 provider로 부터의 광고는 이후 서버로부터의 응답결과와 관계없이 처리되지 않습니다."},{"type":"text","text":" "},{"text":"오류결과는 completionHandler의 error 에서 확인해 주세요.","type":"text"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdManager\/setup(withPublisherCd:target:configuration:completionHandler:)","role":"symbol","navigatorTitle":[{"text":"setupWithPublisherCd:target:configuration:completionHandler:","kind":"identifier"}],"title":"setup(withPublisherCd:target:configuration:completionHandler:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdManager/userParam()":{"type":"topic","url":"\/documentation\/gfpsdk\/gfpadmanager\/userparam()","abstract":[{"text":"유저 타겟 정보 조회","type":"text"}],"title":"userParam()","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"userParam"}],"role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdManager\/userParam()","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"userParam"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPUserParam","text":"GFPUserParam"},{"kind":"text","text":"?"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdManager/adConfiguration()":{"type":"topic","abstract":[{"type":"text","text":"GFPSDK 설정 조회"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdManager\/adConfiguration()","role":"symbol","url":"\/documentation\/gfpsdk\/gfpadmanager\/adconfiguration()","title":"adConfiguration()","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"adConfiguration","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"GFPAdConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdConfiguration"}],"kind":"symbol","navigatorTitle":[{"text":"adConfiguration","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"value":"GFPAdManager","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"GFPAdManager","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"GFPAdManager"}]},{"path":"\/topicSections","value":[{"title":"Type Methods","generated":true,"anchor":"Type-Methods","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdManager\/adConfiguration()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdManager\/appendCookie(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdManager\/clearCookie()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdManager\/clearMemoryCache()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdManager\/cookie()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdManager\/examineWebViewStatus(_:result:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdManager\/isSdkInitialized()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdManager\/register(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdManager\/sdkVersion()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdManager\/setAdConfiguration(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdManager\/setCookie(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdManager\/setUserParam(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdManager\/setup(withPublisherCd:serviceCd:target:completionHandler:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdManager\/setup(withPublisherCd:serviceCd:target:configuration:completionHandler:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdManager\/setup(withPublisherCd:target:completionHandler:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdManager\/setup(withPublisherCd:target:configuration:completionHandler:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdManager\/userParam()"]}],"op":"replace"},{"value":[{"title":"Inherits From","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"}],"op":"replace","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPAdManager"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdManager~1setAdConfiguration(_:)\/title","value":"setAdConfiguration:"},{"value":[{"kind":"text","text":"+ "},{"text":"setAdConfiguration:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdManager~1setAdConfiguration(_:)\/fragments","op":"replace"},{"value":"cookie","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdManager~1cookie()\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdManager~1cookie()\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"cookie"}]},{"value":"clearMemoryCache","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdManager~1clearMemoryCache()\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdManager~1clearMemoryCache()\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"clearMemoryCache"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdManager~1isSdkInitialized()\/title","value":"isSdkInitialized","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdManager~1isSdkInitialized()\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"isSdkInitialized","kind":"identifier"}]},{"value":"setupWithPublisherCd:serviceCd:target:completionHandler:","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdManager~1setup(withPublisherCd:serviceCd:target:completionHandler:)\/title","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"setupWithPublisherCd:serviceCd:target:completionHandler:"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdManager~1setup(withPublisherCd:serviceCd:target:completionHandler:)\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdManager~1setCookie(_:)\/title","value":"setCookie:","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"setCookie:"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdManager~1setCookie(_:)\/fragments"},{"value":"sdkVersion","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdManager~1sdkVersion()\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdManager~1sdkVersion()\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"sdkVersion","kind":"identifier"}]},{"op":"replace","value":"GFPAdManager","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdManager\/title"},{"op":"replace","value":[{"text":"GFPAdManager","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdManager\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdManager\/navigatorTitle","op":"replace","value":[{"text":"GFPAdManager","kind":"identifier"}]},{"value":"setUserParam:","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdManager~1setUserParam(_:)\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdManager~1setUserParam(_:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"setUserParam:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdManager~1appendCookie(_:)\/title","value":"appendCookie:"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdManager~1appendCookie(_:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"appendCookie:"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdManager~1setup(withPublisherCd:serviceCd:target:configuration:completionHandler:)\/title","value":"setupWithPublisherCd:serviceCd:target:configuration:completionHandler:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdManager~1setup(withPublisherCd:serviceCd:target:configuration:completionHandler:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"setupWithPublisherCd:serviceCd:target:configuration:completionHandler:"}]},{"value":"setupWithPublisherCd:target:completionHandler:","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdManager~1setup(withPublisherCd:target:completionHandler:)\/title"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"text":"setupWithPublisherCd:target:completionHandler:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdManager~1setup(withPublisherCd:target:completionHandler:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdManager~1examineWebViewStatus(_:result:)\/title","value":"examineWebViewStatus:result:"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdManager~1examineWebViewStatus(_:result:)\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"examineWebViewStatus:result:"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdManager~1register(_:)\/title","op":"replace","value":"registerWebView:"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdManager~1register(_:)\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"registerWebView:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdManager~1clearCookie()\/title","value":"clearCookie"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"clearCookie"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdManager~1clearCookie()\/fragments"},{"value":"setupWithPublisherCd:target:configuration:completionHandler:","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdManager~1setup(withPublisherCd:target:configuration:completionHandler:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdManager~1setup(withPublisherCd:target:configuration:completionHandler:)\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"setupWithPublisherCd:target:configuration:completionHandler:"}]},{"value":"userParam","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdManager~1userParam()\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdManager~1userParam()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"userParam"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdManager~1adConfiguration()\/title","value":"adConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdManager~1adConfiguration()\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"adConfiguration","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}