{"metadata":{"symbolKind":"typealias","role":"symbol","externalID":"c:GFPAdManager.h@T@GFPAdManagerCompletionHandler","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"GFPAdManagerCompletionHandler","kind":"identifier"}],"modules":[{"name":"GFPSDK"}],"roleHeading":"Type Alias","title":"GFPAdManagerCompletionHandler","navigatorTitle":[{"kind":"identifier","text":"GFPAdManagerCompletionHandler"}]},"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/gfpsdk\/gfpadmanagercompletionhandler"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gfpsdk\/gfpadmanagercompletionhandler"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdManagerCompletionHandler","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPAdManagerCompletionHandler"},{"kind":"text","text":" = ("},{"preciseIdentifier":"c:@M@NaverAdsServices@objc(cs)GFPError","kind":"typeIdentifier","text":"GFPError"},{"text":"?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"}]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdManagerCompletionHandler":{"type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdManagerCompletionHandler","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPAdManagerCompletionHandler"}],"abstract":[],"title":"GFPAdManagerCompletionHandler","navigatorTitle":[{"text":"GFPAdManagerCompletionHandler","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/gfpsdk\/gfpadmanagercompletionhandler"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Type Alias","path":"\/metadata\/roleHeading","op":"replace"},{"value":"GFPAdManagerCompletionHandler","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"typealias"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GFPAdManagerCompletionHandler"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"GFPAdManagerCompletionHandler","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"typedef","kind":"keyword"},{"text":" ","kind":"text"},{"text":"void (^)(GFPError *)","preciseIdentifier":"c:BFv(#*$@M@NaverAdsServices@objc(cs)GFPError)","kind":"typeIdentifier"},{"kind":"text","text":" "},{"text":"GFPAdManagerCompletionHandler","kind":"identifier"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"GFPAdManagerCompletionHandler","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdManagerCompletionHandler\/title","op":"replace"},{"value":[{"kind":"identifier","text":"GFPAdManagerCompletionHandler"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdManagerCompletionHandler\/fragments"},{"value":[{"kind":"identifier","text":"GFPAdManagerCompletionHandler"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdManagerCompletionHandler\/navigatorTitle"}]}]}