{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpadinfo"]},{"paths":["\/documentation\/gfpsdk\/gfpadinfo"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"class","navigatorTitle":[{"kind":"identifier","text":"GFPAdInfo"}],"externalID":"c:objc(cs)GFPAdInfo","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPAdInfo"}],"role":"symbol","modules":[{"name":"GFPSDK"}],"title":"GFPAdInfo","roleHeading":"Class"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"abstract":[{"text":"GFPAdInfo","type":"text"}],"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdInfo","interfaceLanguage":"swift"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"GFPAdInfo","kind":"identifier"}],"languages":["swift"]}]}],"topicSections":[{"title":"Instance Properties","generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdInfo\/baseUrl","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdInfo\/bidPrice","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdInfo\/expireTime","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdInfo\/requestSizes","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdInfo\/requestURL","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdInfo\/responseSize","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdInfo\/sdkRequestInfo","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdInfo\/timeout","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdInfo\/videoloadTimeout"]}],"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"},{"title":"Conforms To","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s7CVarArgP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s23CustomStringConvertibleP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH"],"kind":"relationships","type":"conformsTo"}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdInfo/timeout":{"title":"timeout","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"timeout"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"timeout","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdInfo\/timeout","url":"\/documentation\/gfpsdk\/gfpadinfo\/timeout","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdInfo/adHTML":{"role":"symbol","fragments":[{"text":"adHTML","kind":"identifier"}],"title":"adHTML","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdInfo\/adHTML","abstract":[],"url":"\/documentation\/gfpsdk\/gfpadinfo\/adhtml","type":"topic","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdInfo/sdkRequestInfo":{"title":"sdkRequestInfo","role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"sdkRequestInfo"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" : "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"]?"}],"navigatorTitle":[{"kind":"identifier","text":"sdkRequestInfo"}],"abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdInfo\/sdkRequestInfo","url":"\/documentation\/gfpsdk\/gfpadinfo\/sdkrequestinfo","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/objc(cs)NSObject":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdInfo":{"title":"GFPAdInfo","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPAdInfo"}],"navigatorTitle":[{"kind":"identifier","text":"GFPAdInfo"}],"abstract":[{"type":"text","text":"GFPAdInfo"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdInfo","url":"\/documentation\/gfpsdk\/gfpadinfo","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdInfo/expireTime":{"type":"topic","kind":"symbol","role":"symbol","abstract":[],"url":"\/documentation\/gfpsdk\/gfpadinfo\/expiretime","navigatorTitle":[{"kind":"identifier","text":"expireTime"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"expireTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"?","kind":"text"}],"title":"expireTime","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdInfo\/expireTime"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdInfo/bidPrice":{"title":"bidPrice","role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"bidPrice"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"bidPrice"}],"abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdInfo\/bidPrice","url":"\/documentation\/gfpsdk\/gfpadinfo\/bidprice","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdInfo/skAdNetworkInfo":{"type":"topic","kind":"symbol","role":"symbol","abstract":[],"url":"\/documentation\/gfpsdk\/gfpadinfo\/skadnetworkinfo","fragments":[{"kind":"identifier","text":"skAdNetworkInfo"}],"title":"skAdNetworkInfo","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdInfo\/skAdNetworkInfo"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdInfo/rewardedAdInfo":{"title":"rewardedAdInfo","role":"symbol","kind":"symbol","fragments":[{"kind":"identifier","text":"rewardedAdInfo"}],"abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdInfo\/rewardedAdInfo","url":"\/documentation\/gfpsdk\/gfpadinfo\/rewardedadinfo","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/s7CVarArgP":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdInfo/requestSizes":{"title":"requestSizes","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestSizes"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:objc(cs)GFPAdInfoSize","kind":"typeIdentifier","text":"GFPAdInfoSize"},{"kind":"text","text":"]?"}],"navigatorTitle":[{"text":"requestSizes","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdInfo\/requestSizes","url":"\/documentation\/gfpsdk\/gfpadinfo\/requestsizes","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdInfo/responseSize":{"type":"topic","kind":"symbol","role":"symbol","abstract":[],"url":"\/documentation\/gfpsdk\/gfpadinfo\/responsesize","navigatorTitle":[{"kind":"identifier","text":"responseSize"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"responseSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdInfoSize","text":"GFPAdInfoSize"},{"kind":"text","text":"?"}],"title":"responseSize","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdInfo\/responseSize"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdInfo/baseUrl":{"title":"baseUrl","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"baseUrl"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"baseUrl"}],"abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdInfo\/baseUrl","url":"\/documentation\/gfpsdk\/gfpadinfo\/baseurl","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdInfo/videoloadTimeout":{"type":"topic","kind":"symbol","role":"symbol","abstract":[],"url":"\/documentation\/gfpsdk\/gfpadinfo\/videoloadtimeout","navigatorTitle":[{"kind":"identifier","text":"videoloadTimeout"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"videoloadTimeout"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier","text":"NSNumber"},{"kind":"text","text":"?"}],"title":"videoloadTimeout","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdInfo\/videoloadTimeout"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdInfo/initWithDictionary:skipInfo:needAdChoiceForRender:":{"title":"initWithDictionary:skipInfo:needAdChoiceForRender:","role":"symbol","kind":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDictionary:skipInfo:needAdChoiceForRender:"}],"navigatorTitle":[{"kind":"identifier","text":"initWithDictionary:skipInfo:needAdChoiceForRender:"}],"abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdInfo\/initWithDictionary:skipInfo:needAdChoiceForRender:","url":"\/documentation\/gfpsdk\/gfpadinfo\/initwithdictionary:skipinfo:needadchoiceforrender:","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.navercorp.da.gfp.GFPSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","title":"Swift.Equatable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdInfo/requestURL":{"type":"topic","kind":"symbol","role":"symbol","abstract":[],"url":"\/documentation\/gfpsdk\/gfpadinfo\/requesturl","navigatorTitle":[{"kind":"identifier","text":"requestURL"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestURL"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"title":"requestURL","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdInfo\/requestURL"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdInfo/nativeInfo":{"title":"nativeInfo","role":"symbol","kind":"symbol","fragments":[{"kind":"identifier","text":"nativeInfo"}],"abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdInfo\/nativeInfo","url":"\/documentation\/gfpsdk\/gfpadinfo\/nativeinfo","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/SH":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdInfo/adChoiceInfo":{"title":"adChoiceInfo","role":"symbol","kind":"symbol","fragments":[{"kind":"identifier","text":"adChoiceInfo"}],"abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdInfo\/adChoiceInfo","url":"\/documentation\/gfpsdk\/gfpadinfo\/adchoiceinfo","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"path":"\/metadata\/title","value":"GFPAdInfo","op":"replace"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"GFPAdInfo"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"GFPAdInfo"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdInfo\/adChoiceInfo","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdInfo\/adHTML","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdInfo\/baseUrl","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdInfo\/bidPrice","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdInfo\/expireTime","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdInfo\/nativeInfo","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdInfo\/requestSizes","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdInfo\/requestURL","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdInfo\/responseSize","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdInfo\/rewardedAdInfo","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdInfo\/sdkRequestInfo","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdInfo\/skAdNetworkInfo","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdInfo\/timeout","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdInfo\/videoloadTimeout"],"generated":true},{"title":"Instance Methods","generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdInfo\/initWithDictionary:skipInfo:needAdChoiceForRender:"]}]},{"value":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject"]}],"op":"replace","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPAdInfo"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdInfo~1timeout\/title","value":"timeout"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdInfo~1timeout\/fragments","value":[{"text":"timeout","kind":"identifier"}]},{"value":"sdkRequestInfo","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdInfo~1sdkRequestInfo\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdInfo~1sdkRequestInfo\/fragments","op":"replace","value":[{"text":"sdkRequestInfo","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdInfo\/title","value":"GFPAdInfo","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdInfo\/fragments","value":[{"kind":"identifier","text":"GFPAdInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdInfo\/navigatorTitle","value":[{"text":"GFPAdInfo","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdInfo~1expireTime\/title","value":"expireTime","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdInfo~1expireTime\/fragments","op":"replace","value":[{"kind":"identifier","text":"expireTime"}]},{"value":"bidPrice","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdInfo~1bidPrice\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdInfo~1bidPrice\/fragments","value":[{"text":"bidPrice","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdInfo~1requestSizes\/title","value":"requestSizes","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdInfo~1requestSizes\/fragments","value":[{"kind":"identifier","text":"requestSizes"}],"op":"replace"},{"op":"replace","value":"responseSize","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdInfo~1responseSize\/title"},{"value":[{"kind":"identifier","text":"responseSize"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdInfo~1responseSize\/fragments"},{"value":"baseUrl","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdInfo~1baseUrl\/title","op":"replace"},{"value":[{"text":"baseUrl","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdInfo~1baseUrl\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdInfo~1videoloadTimeout\/title","value":"videoloadTimeout","op":"replace"},{"value":[{"kind":"identifier","text":"videoloadTimeout"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdInfo~1videoloadTimeout\/fragments"},{"value":"requestURL","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdInfo~1requestURL\/title"},{"value":[{"kind":"identifier","text":"requestURL"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdInfo~1requestURL\/fragments"}]}]}