{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(GFPAdInitProviderInfo) ","kind":"text"},{"kind":"attribute","text":"@objcMembers"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"GFPAdInitProviderInfo","kind":"identifier"}],"platforms":["iOS"]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject"]},{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPDictPresentable","doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s7CVarArgP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s23CustomStringConvertibleP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH"],"type":"conformsTo"}],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpadinitproviderinfo"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpadinitproviderinfo"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdInitProviderInfo"},"metadata":{"modules":[{"name":"GFPSDK"}],"symbolKind":"class","title":"GFPAdInitProviderInfo","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPAdInitProviderInfo","kind":"identifier"}],"navigatorTitle":[{"text":"GFPAdInitProviderInfo","kind":"identifier"}],"role":"symbol","externalID":"c:@M@GFPSDK@objc(cs)GFPAdInitProviderInfo","roleHeading":"Class"},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"topicSections":[{"title":"Initializers","generated":true,"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdInitProviderInfo\/init(withDictionary:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdInitProviderInfo\/init(withType:testMode:)"],"anchor":"Initializers"},{"anchor":"Instance-Properties","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdInitProviderInfo\/additionalInfo","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdInitProviderInfo\/description","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdInitProviderInfo\/placeId","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdInitProviderInfo\/testMode","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdInitProviderInfo\/type"],"generated":true,"title":"Instance Properties"},{"anchor":"Instance-Methods","title":"Instance Methods","generated":true,"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdInitProviderInfo\/dictionary()"]},{"title":"Type Methods","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdInitProviderInfo\/adProviders(_:)"],"anchor":"Type-Methods","generated":true}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPDictPresentable":{"abstract":[],"title":"GFPDictPresentable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPDictPresentable","navigatorTitle":[{"text":"GFPDictPresentable","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPDictPresentable","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/gfpsdk\/gfpdictpresentable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdInitProviderInfo/type":{"title":"type","kind":"symbol","role":"symbol","abstract":[],"url":"\/documentation\/gfpsdk\/gfpadinitproviderinfo\/type","navigatorTitle":[{"text":"type","kind":"identifier"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdInitProviderInfo\/type"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdInitProviderInfo/testMode":{"type":"topic","url":"\/documentation\/gfpsdk\/gfpadinitproviderinfo\/testmode","title":"testMode","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"testMode","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"testMode"}],"kind":"symbol","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdInitProviderInfo\/testMode"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdInitProviderInfo/additionalInfo":{"url":"\/documentation\/gfpsdk\/gfpadinitproviderinfo\/additionalinfo","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdInitProviderInfo\/additionalInfo","kind":"symbol","type":"topic","navigatorTitle":[{"text":"additionalInfo","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"additionalInfo"},{"text":": ","kind":"text"},{"text":"GFPAdInitProviderAdditionalInfo","kind":"typeIdentifier","preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPAdInitProviderAdditionalInfo"},{"text":"?","kind":"text"}],"abstract":[],"title":"additionalInfo"},"doc://com.navercorp.da.gfp.GFPSDK/objc(cs)NSObject":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)NSObject":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdInitProviderInfo/description":{"type":"topic","url":"\/documentation\/gfpsdk\/gfpadinitproviderinfo\/description","title":"description","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"description"}],"kind":"symbol","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdInitProviderInfo\/description"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdInitProviderInfo/adProviders(_:)":{"url":"\/documentation\/gfpsdk\/gfpadinitproviderinfo\/adproviders(_:)","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdInitProviderInfo\/adProviders(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"text":"adProviders:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"adProviders","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Dictionary","kind":"typeIdentifier","preciseIdentifier":"s:SD"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":">) -> ["},{"preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPAdInitProviderInfo","kind":"typeIdentifier","text":"GFPAdInitProviderInfo"},{"text":"]?","kind":"text"}],"abstract":[],"title":"adProviders(_:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdInitProviderInfo":{"title":"GFPAdInitProviderInfo","url":"\/documentation\/gfpsdk\/gfpadinitproviderinfo","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPAdInitProviderInfo"}],"navigatorTitle":[{"kind":"identifier","text":"GFPAdInitProviderInfo"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdInitProviderInfo","type":"topic","role":"symbol","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH"},"doc://com.navercorp.da.gfp.GFPSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s23CustomStringConvertibleP"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdInitProviderInfo/init(withDictionary:)":{"type":"topic","url":"\/documentation\/gfpsdk\/gfpadinitproviderinfo\/init(withdictionary:)","title":"init(withDictionary:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"withDictionary","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Dictionary","preciseIdentifier":"s:SD","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"Any","kind":"keyword"},{"text":">)","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"initWithDictionary:","kind":"identifier"}],"kind":"symbol","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdInitProviderInfo\/init(withDictionary:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdInitProviderInfo/dictionary()":{"url":"\/documentation\/gfpsdk\/gfpadinitproviderinfo\/dictionary()","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdInitProviderInfo\/dictionary()","kind":"symbol","type":"topic","navigatorTitle":[{"text":"dictionary","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"dictionary"},{"text":"() -> [","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":" : ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"]?"}],"abstract":[],"title":"dictionary()"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdInitProviderInfo/init(withType:testMode:)":{"navigatorTitle":[{"kind":"identifier","text":"initWithType:testMode:"}],"title":"init(withType:testMode:)","abstract":[],"role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdInitProviderInfo\/init(withType:testMode:)","type":"topic","url":"\/documentation\/gfpsdk\/gfpadinitproviderinfo\/init(withtype:testmode:)","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"withType"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"testMode"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdInitProviderInfo/placeId":{"type":"topic","url":"\/documentation\/gfpsdk\/gfpadinitproviderinfo\/placeid","title":"placeId","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"placeId","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"placeId"}],"kind":"symbol","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdInitProviderInfo\/placeId"},"doc://com.navercorp.da.gfp.GFPSDK/SQ":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.navercorp.da.gfp.GFPSDK/s7CVarArgP":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","value":"GFPAdInitProviderInfo","op":"replace"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GFPAdInitProviderInfo"}],"op":"replace"},{"op":"replace","value":[{"text":"GFPAdInitProviderInfo","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"value":[{"generated":true,"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdInitProviderInfo\/additionalInfo","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdInitProviderInfo\/description","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdInitProviderInfo\/placeId","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdInitProviderInfo\/testMode","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdInitProviderInfo\/type"]},{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdInitProviderInfo\/dictionary()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdInitProviderInfo\/init(withDictionary:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdInitProviderInfo\/init(withType:testMode:)"],"anchor":"Instance-Methods"},{"anchor":"Type-Methods","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdInitProviderInfo\/adProviders(_:)"],"title":"Type Methods","generated":true}],"path":"\/topicSections","op":"replace"},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject"]},{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPDictPresentable"]}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPAdInitProviderInfo","kind":"identifier"},{"kind":"text","text":" : "},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"GFPDictPresentable","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPDictPresentable\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPDictPresentable\/fragments","value":[{"text":"GFPDictPresentable","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPDictPresentable\/navigatorTitle","value":[{"kind":"identifier","text":"GFPDictPresentable"}],"op":"replace"},{"op":"replace","value":"type","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdInitProviderInfo~1type\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdInitProviderInfo~1type\/fragments","op":"replace","value":[{"kind":"identifier","text":"type"}]},{"value":"testMode","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdInitProviderInfo~1testMode\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdInitProviderInfo~1testMode\/fragments","value":[{"text":"testMode","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"additionalInfo","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdInitProviderInfo~1additionalInfo\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdInitProviderInfo~1additionalInfo\/fragments","value":[{"kind":"identifier","text":"additionalInfo"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdInitProviderInfo~1description\/title","value":"description"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdInitProviderInfo~1description\/fragments","op":"replace","value":[{"kind":"identifier","text":"description"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdInitProviderInfo~1adProviders(_:)\/title","value":"adProviders:"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdInitProviderInfo~1adProviders(_:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"adProviders:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdInitProviderInfo\/title","value":"GFPAdInitProviderInfo"},{"value":[{"text":"GFPAdInitProviderInfo","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdInitProviderInfo\/fragments","op":"replace"},{"op":"replace","value":[{"text":"GFPAdInitProviderInfo","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdInitProviderInfo\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdInitProviderInfo~1init(withDictionary:)\/title","op":"replace","value":"initWithDictionary:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithDictionary:"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdInitProviderInfo~1init(withDictionary:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdInitProviderInfo~1dictionary()\/title","value":"dictionary"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"dictionary"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdInitProviderInfo~1dictionary()\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdInitProviderInfo~1init(withType:testMode:)\/title","op":"replace","value":"initWithType:testMode:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithType:testMode:"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdInitProviderInfo~1init(withType:testMode:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdInitProviderInfo~1placeId\/title","value":"placeId"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdInitProviderInfo~1placeId\/fragments","value":[{"text":"placeId","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}