{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPAdConfiguration"}]}],"kind":"declarations"}],"topicSections":[{"generated":true,"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdConfiguration\/adInterfaceStyle","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdConfiguration\/adProviderConfigList","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdConfiguration\/bannerAdRequestTimeout","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdConfiguration\/cookie","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdConfiguration\/customParam","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdConfiguration\/disableAdID","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdConfiguration\/disableCrashReport","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdConfiguration\/disableLocationInfo","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdConfiguration\/disableNeloLog","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdConfiguration\/displayAgent","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdConfiguration\/externalUserAgent","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdConfiguration\/interstitialAdRequestTimeout","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdConfiguration\/logLevel","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdConfiguration\/muteAudio","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdConfiguration\/phase","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdConfiguration\/preferredLanguage","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdConfiguration\/privacySetting","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdConfiguration\/rewardedAdRequestTimeout","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdConfiguration\/unifiedAdRequestTimeout","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdConfiguration\/useDefaultSafariBrowser","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdConfiguration\/useDefaultUA","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdConfiguration\/useLoudness","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdConfiguration\/videoAdRequestTimeout"]},{"anchor":"Instance-Methods","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdConfiguration\/adProviderConfig(with:)"],"generated":true,"title":"Instance Methods"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject"]},{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s7CVarArgP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s23CustomStringConvertibleP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH"],"kind":"relationships","type":"conformsTo","title":"Conforms To"}],"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpadconfiguration"]},{"paths":["\/documentation\/gfpsdk\/gfpadconfiguration"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdConfiguration","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"GFPAdConfiguration"}],"externalID":"c:objc(cs)GFPAdConfiguration","symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPAdConfiguration"}],"role":"symbol","modules":[{"name":"GFPSDK"}],"roleHeading":"Class","title":"GFPAdConfiguration"},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdConfiguration/muteAudio":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdConfiguration\/muteAudio","type":"topic","title":"muteAudio","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"muteAudio"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"role":"symbol","kind":"symbol","url":"\/documentation\/gfpsdk\/gfpadconfiguration\/muteaudio","navigatorTitle":[{"text":"muteAudio","kind":"identifier"}],"abstract":[{"text":"광고 오디오 mute 설정 (기본값 YES)","type":"text"},{"text":" ","type":"text"},{"text":"단, C2S 광고 및 S2S 리워드 광고에 한해 적용됩니다. (인스트림, 아웃스트림 제외)","type":"text"}]},"doc://com.navercorp.da.gfp.GFPSDK/objc(cs)NSObject":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdConfiguration/bannerAdRequestTimeout":{"url":"\/documentation\/gfpsdk\/gfpadconfiguration\/banneradrequesttimeout","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bannerAdRequestTimeout"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdConfiguration\/bannerAdRequestTimeout","kind":"symbol","navigatorTitle":[{"text":"bannerAdRequestTimeout","kind":"identifier"}],"role":"symbol","title":"bannerAdRequestTimeout","type":"topic","abstract":[{"type":"text","text":"배너광고 요청 타임아웃 (기본값 60초, kGFPDefaultBannerAdRequestTimeout)"},{"text":" ","type":"text"},{"type":"text","text":"GFPBannerView 를 통한 로드 시 적용됨."}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdConfiguration":{"type":"topic","url":"\/documentation\/gfpsdk\/gfpadconfiguration","role":"symbol","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPAdConfiguration","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdConfiguration","title":"GFPAdConfiguration","navigatorTitle":[{"text":"GFPAdConfiguration","kind":"identifier"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdConfiguration/externalUserAgent":{"url":"\/documentation\/gfpsdk\/gfpadconfiguration\/externaluseragent","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"externalUserAgent","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"kind":"identifier","text":"externalUserAgent"}],"title":"externalUserAgent","role":"symbol","type":"topic","abstract":[{"type":"text","text":"SDK에 UA주입되어 사용할 수 있도록"}],"kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdConfiguration\/externalUserAgent"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdConfiguration/phase":{"navigatorTitle":[{"kind":"identifier","text":"phase"}],"url":"\/documentation\/gfpsdk\/gfpadconfiguration\/phase","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"phase","kind":"identifier"},{"text":": ","kind":"text"},{"text":"GFPPhaseType","kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPPhaseType"}],"role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdConfiguration\/phase","title":"phase"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdConfiguration/disableAdID":{"navigatorTitle":[{"text":"disableAdID","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdConfiguration\/disableAdID","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"disableAdID","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"title":"disableAdID","abstract":[{"type":"text","text":"기기에서의 허용 여부와 상관 없이 앱의 정책 상 IDFA 사용이 불가한 경우 무시하는 옵션 (기본값 NO)"}],"url":"\/documentation\/gfpsdk\/gfpadconfiguration\/disableadid","type":"topic","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdConfiguration/adProviderConfigList":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdConfiguration\/adProviderConfigList","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"adProviderConfigList"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPAdProviderSetting","text":"GFPAdProviderSetting"},{"text":"]","kind":"text"}],"type":"topic","navigatorTitle":[{"text":"adProviderConfigList","kind":"identifier"}],"title":"adProviderConfigList","url":"\/documentation\/gfpsdk\/gfpadconfiguration\/adproviderconfiglist","abstract":[{"type":"text","text":"AdProvider 별 테스트 모드 설정."}],"role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdConfiguration/unifiedAdRequestTimeout":{"type":"topic","navigatorTitle":[{"text":"unifiedAdRequestTimeout","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdConfiguration\/unifiedAdRequestTimeout","abstract":[{"text":"통합광고(배너+네이티브) 요청 타임아웃 (기본값 60초, kGFPDefaultUnifiedAdRequestTimeout)","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"GFPAdLoader를 통한 광고 로드 시 적용됨."}],"kind":"symbol","url":"\/documentation\/gfpsdk\/gfpadconfiguration\/unifiedadrequesttimeout","title":"unifiedAdRequestTimeout","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unifiedAdRequestTimeout"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdConfiguration/cookie":{"role":"symbol","navigatorTitle":[{"text":"cookie","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cookie"},{"kind":"text","text":": ["},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"]"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdConfiguration\/cookie","type":"topic","abstract":[{"type":"text","text":"식별 가능한 Cookie 세팅."}],"kind":"symbol","url":"\/documentation\/gfpsdk\/gfpadconfiguration\/cookie","title":"cookie"},"doc://com.navercorp.da.gfp.GFPSDK/s7CVarArgP":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdConfiguration/disableLocationInfo":{"kind":"symbol","title":"disableLocationInfo","url":"\/documentation\/gfpsdk\/gfpadconfiguration\/disablelocationinfo","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"disableLocationInfo"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdConfiguration\/disableLocationInfo","type":"topic","navigatorTitle":[{"kind":"identifier","text":"disableLocationInfo"}],"abstract":[{"text":"서비스에서 위치정보 권한을 얻었어도 무시하는 옵션  (기본값 NO)","type":"text"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdConfiguration/disableCrashReport":{"url":"\/documentation\/gfpsdk\/gfpadconfiguration\/disablecrashreport","abstract":[{"type":"text","text":"외부 DSP SDK(=DFP)의 CrashReport 기능 사용 여부. (기본값 NO)"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdConfiguration\/disableCrashReport","title":"disableCrashReport","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"disableCrashReport","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"disableCrashReport"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdConfiguration/useLoudness":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"useLoudness","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdConfiguration\/useLoudness","abstract":[{"type":"text","text":"비디오 광고 재생 시, Loudness (볼륨 자동 조절) 사용 여부. (기본값 NO)"}],"kind":"symbol","url":"\/documentation\/gfpsdk\/gfpadconfiguration\/useloudness","title":"useLoudness","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"useLoudness"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdConfiguration/logLevel":{"role":"symbol","abstract":[{"text":"GFPSDK 로그레벨 설정. 설정한 로그레벨 이상의 로그만 콘솔에 출력됩니다. (기본값: GFPSDKLogLevelNone, 로그를 출력하지 않음)","type":"text"}],"title":"logLevel","navigatorTitle":[{"text":"logLevel","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"logLevel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GFPLogLevel","preciseIdentifier":"c:@E@GFPLogLevel"}],"url":"\/documentation\/gfpsdk\/gfpadconfiguration\/loglevel","type":"topic","kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdConfiguration\/logLevel"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdConfiguration/customParam":{"navigatorTitle":[{"text":"customParam","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdConfiguration\/customParam","abstract":[{"text":"전역 추가 파라미터 (주의! 추가 파라미터 사전의 키\/값은 모두 문자열 타입이어야 합니다.)","type":"text"}],"url":"\/documentation\/gfpsdk\/gfpadconfiguration\/customparam","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"customParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"]?","kind":"text"}],"title":"customParam","type":"topic","role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdConfiguration/videoAdRequestTimeout":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"videoAdRequestTimeout"}],"title":"videoAdRequestTimeout","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"videoAdRequestTimeout","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"비디오광고 요청 타임아웃 (기본값 60초, kGFPDefaultVideoAdRequestTimeout)"}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdConfiguration\/videoAdRequestTimeout","url":"\/documentation\/gfpsdk\/gfpadconfiguration\/videoadrequesttimeout"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdConfiguration/privacySetting":{"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"privacySetting"}],"abstract":[{"type":"text","text":"Privacy 설정."}],"title":"privacySetting","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"privacySetting","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"GFPPrivacySetting","preciseIdentifier":"c:objc(cs)GFPPrivacySetting"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdConfiguration\/privacySetting","url":"\/documentation\/gfpsdk\/gfpadconfiguration\/privacysetting"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdConfiguration/adProviderConfig(with:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"adProviderConfig"},{"kind":"text","text":"("},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@GFPAdProviderSettingType","text":"GFPAdProviderSettingType","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"GFPAdProviderSetting","preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPAdProviderSetting","kind":"typeIdentifier"}],"abstract":[],"url":"\/documentation\/gfpsdk\/gfpadconfiguration\/adproviderconfig(with:)","navigatorTitle":[{"kind":"identifier","text":"adProviderConfigWith:"}],"kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdConfiguration\/adProviderConfig(with:)","type":"topic","title":"adProviderConfig(with:)","role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdConfiguration/preferredLanguage":{"abstract":[{"type":"text","text":"광고 UI 컴포넌트의 언어 설정 (기본값: none)"}],"url":"\/documentation\/gfpsdk\/gfpadconfiguration\/preferredlanguage","title":"preferredLanguage","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"preferredLanguage"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@GFPLanguageType","text":"GFPLanguageType","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"text":"preferredLanguage","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdConfiguration\/preferredLanguage"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdConfiguration/useDefaultUA":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"useDefaultUA"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"url":"\/documentation\/gfpsdk\/gfpadconfiguration\/usedefaultua","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdConfiguration\/useDefaultUA","title":"useDefaultUA","type":"topic","navigatorTitle":[{"text":"useDefaultUA","kind":"identifier"}],"abstract":[{"text":"SDK내에서 정의한 Default UA로 광고 요청하도록 세팅. (기본값 NO)","type":"text"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdConfiguration/adInterfaceStyle":{"navigatorTitle":[{"kind":"identifier","text":"adInterfaceStyle"}],"url":"\/documentation\/gfpsdk\/gfpadconfiguration\/adinterfacestyle","abstract":[{"type":"text","text":"GFP 에서 렌더링 하는 광고의 style. (기본값 Light)"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"adInterfaceStyle"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPAdInterfaceStyle","text":"GFPAdInterfaceStyle"}],"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdConfiguration\/adInterfaceStyle","title":"adInterfaceStyle"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdConfiguration/useDefaultSafariBrowser":{"role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdConfiguration\/useDefaultSafariBrowser","type":"topic","abstract":[{"type":"text","text":"s2s광고 랜딩 시 기본 제공 인앱 브라우저 사용 여부 (기본값 NO)"}],"url":"\/documentation\/gfpsdk\/gfpadconfiguration\/usedefaultsafaribrowser","title":"useDefaultSafariBrowser","navigatorTitle":[{"kind":"identifier","text":"useDefaultSafariBrowser"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"useDefaultSafariBrowser","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)NSObject":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdConfiguration/displayAgent":{"title":"displayAgent","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdConfiguration\/displayAgent","navigatorTitle":[{"text":"displayAgent","kind":"identifier"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"displayAgent"},{"kind":"text","text":": "},{"text":"GFPRenderDisplayAgent","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPRenderDisplayAgent"}],"abstract":[{"text":"광고 클릭 후 렌더링 타입","type":"text"}],"kind":"symbol","role":"symbol","url":"\/documentation\/gfpsdk\/gfpadconfiguration\/displayagent"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdConfiguration/disableNeloLog":{"role":"symbol","abstract":[{"type":"text","text":"sdk 넬로 로그 전송 여부 (기본값 NO)"}],"title":"disableNeloLog","navigatorTitle":[{"text":"disableNeloLog","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"disableNeloLog","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdConfiguration\/disableNeloLog","url":"\/documentation\/gfpsdk\/gfpadconfiguration\/disablenelolog","kind":"symbol","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.navercorp.da.gfp.GFPSDK/SH":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdConfiguration/interstitialAdRequestTimeout":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"interstitialAdRequestTimeout","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"}],"url":"\/documentation\/gfpsdk\/gfpadconfiguration\/interstitialadrequesttimeout","kind":"symbol","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdConfiguration\/interstitialAdRequestTimeout","abstract":[{"type":"text","text":"전면형광고 요청 타임아웃 (기본값 60초, kGFPDefaultInterstitialAdRequestTimeout)"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"interstitialAdRequestTimeout"}],"title":"interstitialAdRequestTimeout"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdConfiguration/rewardedAdRequestTimeout":{"navigatorTitle":[{"kind":"identifier","text":"rewardedAdRequestTimeout"}],"url":"\/documentation\/gfpsdk\/gfpadconfiguration\/rewardedadrequesttimeout","abstract":[{"type":"text","text":"리워드광고 요청 타임아웃 (기본값 60초, kGFPDefaultRewardedAdRequestTimeout)"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rewardedAdRequestTimeout"},{"kind":"text","text":": "},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"}],"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdConfiguration\/rewardedAdRequestTimeout","title":"rewardedAdRequestTimeout"},"doc://com.navercorp.da.gfp.GFPSDK/SQ":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"GFPAdConfiguration","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"GFPAdConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"GFPAdConfiguration"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdConfiguration\/adInterfaceStyle","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdConfiguration\/adProviderConfigList","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdConfiguration\/bannerAdRequestTimeout","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdConfiguration\/cookie","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdConfiguration\/customParam","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdConfiguration\/disableAdID","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdConfiguration\/disableCrashReport","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdConfiguration\/disableLocationInfo","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdConfiguration\/disableNeloLog","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdConfiguration\/displayAgent","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdConfiguration\/externalUserAgent","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdConfiguration\/interstitialAdRequestTimeout","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdConfiguration\/logLevel","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdConfiguration\/muteAudio","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdConfiguration\/phase","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdConfiguration\/preferredLanguage","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdConfiguration\/privacySetting","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdConfiguration\/rewardedAdRequestTimeout","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdConfiguration\/unifiedAdRequestTimeout","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdConfiguration\/useDefaultSafariBrowser","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdConfiguration\/useDefaultUA","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdConfiguration\/useLoudness","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdConfiguration\/videoAdRequestTimeout"],"generated":true,"anchor":"Instance-Properties"},{"title":"Instance Methods","generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdConfiguration\/adProviderConfig(with:)"]}]},{"path":"\/relationshipsSections","value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject"],"type":"inheritsFrom"}],"op":"replace"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPAdConfiguration","kind":"identifier"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdConfiguration~1muteAudio\/title","value":"muteAudio","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdConfiguration~1muteAudio\/fragments","value":[{"kind":"identifier","text":"muteAudio"}]},{"value":"bannerAdRequestTimeout","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdConfiguration~1bannerAdRequestTimeout\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdConfiguration~1bannerAdRequestTimeout\/fragments","value":[{"text":"bannerAdRequestTimeout","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdConfiguration\/title","op":"replace","value":"GFPAdConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdConfiguration\/fragments","value":[{"kind":"identifier","text":"GFPAdConfiguration"}]},{"value":[{"text":"GFPAdConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdConfiguration\/navigatorTitle"},{"value":"externalUserAgent","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdConfiguration~1externalUserAgent\/title"},{"op":"replace","value":[{"kind":"identifier","text":"externalUserAgent"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdConfiguration~1externalUserAgent\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdConfiguration~1phase\/title","value":"phase"},{"op":"replace","value":[{"kind":"identifier","text":"phase"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdConfiguration~1phase\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdConfiguration~1disableAdID\/title","value":"disableAdID","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdConfiguration~1disableAdID\/fragments","value":[{"kind":"identifier","text":"disableAdID"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdConfiguration~1adProviderConfigList\/title","op":"replace","value":"adProviderConfigList"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdConfiguration~1adProviderConfigList\/fragments","op":"replace","value":[{"text":"adProviderConfigList","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdConfiguration~1unifiedAdRequestTimeout\/title","value":"unifiedAdRequestTimeout"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdConfiguration~1unifiedAdRequestTimeout\/fragments","value":[{"kind":"identifier","text":"unifiedAdRequestTimeout"}]},{"value":"cookie","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdConfiguration~1cookie\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdConfiguration~1cookie\/fragments","op":"replace","value":[{"text":"cookie","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdConfiguration~1disableLocationInfo\/title","value":"disableLocationInfo","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdConfiguration~1disableLocationInfo\/fragments","value":[{"text":"disableLocationInfo","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdConfiguration~1disableCrashReport\/title","op":"replace","value":"disableCrashReport"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdConfiguration~1disableCrashReport\/fragments","op":"replace","value":[{"text":"disableCrashReport","kind":"identifier"}]},{"value":"useLoudness","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdConfiguration~1useLoudness\/title"},{"op":"replace","value":[{"text":"useLoudness","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdConfiguration~1useLoudness\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdConfiguration~1logLevel\/title","op":"replace","value":"logLevel"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdConfiguration~1logLevel\/fragments","value":[{"kind":"identifier","text":"logLevel"}],"op":"replace"},{"value":"customParam","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdConfiguration~1customParam\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdConfiguration~1customParam\/fragments","value":[{"text":"customParam","kind":"identifier"}],"op":"replace"},{"value":"videoAdRequestTimeout","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdConfiguration~1videoAdRequestTimeout\/title"},{"op":"replace","value":[{"text":"videoAdRequestTimeout","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdConfiguration~1videoAdRequestTimeout\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdConfiguration~1privacySetting\/title","op":"replace","value":"privacySetting"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdConfiguration~1privacySetting\/fragments","value":[{"kind":"identifier","text":"privacySetting"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdConfiguration~1adProviderConfig(with:)\/title","value":"adProviderConfigWith:"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdConfiguration~1adProviderConfig(with:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"adProviderConfigWith:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdConfiguration~1preferredLanguage\/title","op":"replace","value":"preferredLanguage"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdConfiguration~1preferredLanguage\/fragments","value":[{"kind":"identifier","text":"preferredLanguage"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdConfiguration~1useDefaultUA\/title","value":"useDefaultUA","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdConfiguration~1useDefaultUA\/fragments","value":[{"kind":"identifier","text":"useDefaultUA"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdConfiguration~1adInterfaceStyle\/title","op":"replace","value":"adInterfaceStyle"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdConfiguration~1adInterfaceStyle\/fragments","value":[{"text":"adInterfaceStyle","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdConfiguration~1useDefaultSafariBrowser\/title","value":"useDefaultSafariBrowser"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdConfiguration~1useDefaultSafariBrowser\/fragments","value":[{"kind":"identifier","text":"useDefaultSafariBrowser"}]},{"value":"displayAgent","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdConfiguration~1displayAgent\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdConfiguration~1displayAgent\/fragments","value":[{"text":"displayAgent","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdConfiguration~1disableNeloLog\/title","op":"replace","value":"disableNeloLog"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdConfiguration~1disableNeloLog\/fragments","op":"replace","value":[{"text":"disableNeloLog","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdConfiguration~1interstitialAdRequestTimeout\/title","value":"interstitialAdRequestTimeout","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdConfiguration~1interstitialAdRequestTimeout\/fragments","op":"replace","value":[{"text":"interstitialAdRequestTimeout","kind":"identifier"}]},{"value":"rewardedAdRequestTimeout","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdConfiguration~1rewardedAdRequestTimeout\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdConfiguration~1rewardedAdRequestTimeout\/fragments","op":"replace","value":[{"text":"rewardedAdRequestTimeout","kind":"identifier"}]}]}]}