{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerProviderOption"},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"kind":"symbol","abstract":[{"text":"GFP에서 지원하는 배너광고 제공자 목록","type":"text"}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SY"],"type":"conformsTo","title":"Conforms To"}],"topicSections":[{"title":"Enumeration Cases","generated":true,"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerProviderOption\/APS","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerProviderOption\/BidMachine","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerProviderOption\/DFP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerProviderOption\/DT","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerProviderOption\/FAN","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerProviderOption\/IS","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerProviderOption\/NDA","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerProviderOption\/appLovin","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerProviderOption\/chartBoost","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerProviderOption\/end","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerProviderOption\/inMobi","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerProviderOption\/none","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerProviderOption\/unity"],"anchor":"Enumeration-Cases"},{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerProviderOption\/init(rawValue:)"],"title":"Initializers","anchor":"Initializers","generated":true},{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerProviderOption\/Equatable-Implementations","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerProviderOption\/RawRepresentable-Implementations"],"anchor":"Default-Implementations","generated":true,"title":"Default Implementations"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"GFPBannerProviderOption","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"externalID":"c:@M@GFPSDK@E@GFPBannerProviderOption","roleHeading":"Enumeration","symbolKind":"enum","role":"symbol","modules":[{"name":"GFPSDK"}],"title":"GFPBannerProviderOption","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPBannerProviderOption","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"GFPBannerProviderOption"}]},"variants":[{"paths":["\/documentation\/gfpsdk\/gfpbannerprovideroption"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gfpsdk\/gfpbannerprovideroption"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerProviderOption/BidMachine":{"url":"\/documentation\/gfpsdk\/gfpbannerprovideroption\/bidmachine","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BidMachine"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerProviderOption\/BidMachine","kind":"symbol","navigatorTitle":[{"text":"GFPBannerProviderOptionBidMachine","kind":"identifier"}],"role":"symbol","title":"GFPBannerProviderOption.BidMachine","type":"topic","abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerProviderOption/appLovin":{"navigatorTitle":[{"kind":"identifier","text":"GFPBannerProviderOptionAppLovin"}],"type":"topic","title":"GFPBannerProviderOption.appLovin","kind":"symbol","url":"\/documentation\/gfpsdk\/gfpbannerprovideroption\/applovin","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerProviderOption\/appLovin","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"appLovin"}],"role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/SY":{"title":"Swift.RawRepresentable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SY","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerProviderOption/chartBoost":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerProviderOption\/chartBoost","type":"topic","abstract":[],"url":"\/documentation\/gfpsdk\/gfpbannerprovideroption\/chartboost","navigatorTitle":[{"text":"GFPBannerProviderOptionChartBoost","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"chartBoost"}],"title":"GFPBannerProviderOption.chartBoost","role":"symbol","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerProviderOption/DT":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerProviderOption\/DT","role":"symbol","url":"\/documentation\/gfpsdk\/gfpbannerprovideroption\/dt","type":"topic","title":"GFPBannerProviderOption.DT","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DT"}],"navigatorTitle":[{"text":"GFPBannerProviderOptionDT","kind":"identifier"}],"abstract":[],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerProviderOption/NDA":{"navigatorTitle":[{"text":"GFPBannerProviderOptionNDA","kind":"identifier"}],"kind":"symbol","abstract":[],"title":"GFPBannerProviderOption.NDA","url":"\/documentation\/gfpsdk\/gfpbannerprovideroption\/nda","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"NDA"}],"type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerProviderOption\/NDA","role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerProviderOption/init(rawValue:)":{"kind":"symbol","title":"init(rawValue:)","url":"\/documentation\/gfpsdk\/gfpbannerprovideroption\/init(rawvalue:)","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerProviderOption\/init(rawValue:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerProviderOption/RawRepresentable-Implementations":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerProviderOption\/RawRepresentable-Implementations","url":"\/documentation\/gfpsdk\/gfpbannerprovideroption\/rawrepresentable-implementations","role":"collectionGroup","title":"RawRepresentable Implementations","kind":"article","type":"topic","abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerProviderOption/none":{"title":"GFPBannerProviderOption.none","type":"topic","role":"symbol","abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPBannerProviderOptionNone"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"none"}],"url":"\/documentation\/gfpsdk\/gfpbannerprovideroption\/none","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerProviderOption\/none"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerProviderOption/unity":{"navigatorTitle":[{"text":"GFPBannerProviderOptionUnity","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpbannerprovideroption\/unity","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"unity","kind":"identifier"}],"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerProviderOption\/unity","title":"GFPBannerProviderOption.unity"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerProviderOption/end":{"title":"GFPBannerProviderOption.end","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"end","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"GFPBannerProviderOptionEnd"}],"abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerProviderOption\/end","url":"\/documentation\/gfpsdk\/gfpbannerprovideroption\/end","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerProviderOption/FAN":{"type":"topic","role":"symbol","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerProviderOption\/FAN","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FAN","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"GFPBannerProviderOptionFAN"}],"title":"GFPBannerProviderOption.FAN","url":"\/documentation\/gfpsdk\/gfpbannerprovideroption\/fan"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerProviderOption/DFP":{"title":"GFPBannerProviderOption.DFP","url":"\/documentation\/gfpsdk\/gfpbannerprovideroption\/dfp","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"DFP","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerProviderOption\/DFP","type":"topic","role":"symbol","navigatorTitle":[{"text":"GFPBannerProviderOptionDFP","kind":"identifier"}],"abstract":[],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerProviderOption":{"navigatorTitle":[{"text":"GFPBannerProviderOption","kind":"identifier"}],"role":"symbol","title":"GFPBannerProviderOption","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerProviderOption","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPBannerProviderOption"}],"url":"\/documentation\/gfpsdk\/gfpbannerprovideroption","abstract":[{"text":"GFP에서 지원하는 배너광고 제공자 목록","type":"text"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerProviderOption/inMobi":{"abstract":[],"url":"\/documentation\/gfpsdk\/gfpbannerprovideroption\/inmobi","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPBannerProviderOptionInMobi"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"inMobi","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerProviderOption\/inMobi","kind":"symbol","title":"GFPBannerProviderOption.inMobi","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerProviderOption/IS":{"type":"topic","url":"\/documentation\/gfpsdk\/gfpbannerprovideroption\/is","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"IS","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerProviderOption\/IS","title":"GFPBannerProviderOption.IS","navigatorTitle":[{"text":"GFPBannerProviderOptionIS","kind":"identifier"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerProviderOption/APS":{"abstract":[],"type":"topic","title":"GFPBannerProviderOption.APS","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"APS","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpbannerprovideroption\/aps","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerProviderOption\/APS","navigatorTitle":[{"text":"GFPBannerProviderOptionAPS","kind":"identifier"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerProviderOption/Equatable-Implementations":{"title":"Equatable Implementations","abstract":[],"url":"\/documentation\/gfpsdk\/gfpbannerprovideroption\/equatable-implementations","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerProviderOption\/Equatable-Implementations","type":"topic","kind":"article","role":"collectionGroup"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"value":"GFPBannerProviderOption","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"op":"replace","value":[{"text":"GFPBannerProviderOption","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"GFPBannerProviderOption"}]},{"value":[{"generated":true,"title":"Enumeration Cases","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerProviderOption\/APS","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerProviderOption\/BidMachine","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerProviderOption\/DFP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerProviderOption\/DT","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerProviderOption\/FAN","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerProviderOption\/IS","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerProviderOption\/NDA","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerProviderOption\/appLovin","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerProviderOption\/chartBoost","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerProviderOption\/end","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerProviderOption\/inMobi","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerProviderOption\/none","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerProviderOption\/unity"],"anchor":"Enumeration-Cases"}],"op":"replace","path":"\/topicSections"},{"op":"replace","value":null,"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPBannerProviderOption","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerProviderOption~1BidMachine\/title","value":"GFPBannerProviderOptionBidMachine"},{"value":[{"text":"GFPBannerProviderOptionBidMachine","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerProviderOption~1BidMachine\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerProviderOption~1appLovin\/title","value":"GFPBannerProviderOptionAppLovin","op":"replace"},{"value":[{"kind":"identifier","text":"GFPBannerProviderOptionAppLovin"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerProviderOption~1appLovin\/fragments"},{"op":"replace","value":"GFPBannerProviderOptionChartBoost","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerProviderOption~1chartBoost\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerProviderOption~1chartBoost\/fragments","value":[{"kind":"identifier","text":"GFPBannerProviderOptionChartBoost"}]},{"value":"GFPBannerProviderOptionDT","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerProviderOption~1DT\/title","op":"replace"},{"value":[{"kind":"identifier","text":"GFPBannerProviderOptionDT"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerProviderOption~1DT\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerProviderOption~1NDA\/title","value":"GFPBannerProviderOptionNDA","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerProviderOption~1NDA\/fragments","value":[{"kind":"identifier","text":"GFPBannerProviderOptionNDA"}],"op":"replace"},{"op":"replace","value":"GFPBannerProviderOptionNone","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerProviderOption~1none\/title"},{"value":[{"kind":"identifier","text":"GFPBannerProviderOptionNone"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerProviderOption~1none\/fragments"},{"value":"GFPBannerProviderOptionUnity","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerProviderOption~1unity\/title"},{"op":"replace","value":[{"text":"GFPBannerProviderOptionUnity","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerProviderOption~1unity\/fragments"},{"op":"replace","value":"GFPBannerProviderOptionEnd","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerProviderOption~1end\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerProviderOption~1end\/fragments","op":"replace","value":[{"text":"GFPBannerProviderOptionEnd","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerProviderOption~1FAN\/title","value":"GFPBannerProviderOptionFAN"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerProviderOption~1FAN\/fragments","op":"replace","value":[{"text":"GFPBannerProviderOptionFAN","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerProviderOption~1DFP\/title","value":"GFPBannerProviderOptionDFP"},{"value":[{"text":"GFPBannerProviderOptionDFP","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerProviderOption~1DFP\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerProviderOption\/title","value":"GFPBannerProviderOption","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerProviderOption\/fragments","op":"replace","value":[{"kind":"identifier","text":"GFPBannerProviderOption"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerProviderOption\/navigatorTitle","value":[{"text":"GFPBannerProviderOption","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerProviderOption~1inMobi\/title","op":"replace","value":"GFPBannerProviderOptionInMobi"},{"value":[{"text":"GFPBannerProviderOptionInMobi","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerProviderOption~1inMobi\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerProviderOption~1IS\/title","op":"replace","value":"GFPBannerProviderOptionIS"},{"value":[{"kind":"identifier","text":"GFPBannerProviderOptionIS"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerProviderOption~1IS\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerProviderOption~1APS\/title","op":"replace","value":"GFPBannerProviderOptionAPS"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerProviderOption~1APS\/fragments","op":"replace","value":[{"text":"GFPBannerProviderOptionAPS","kind":"identifier"}]}]}]}