{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"GFPBannerMediator","kind":"identifier"}],"platforms":["iOS"]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediator"]},{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPResponseInfoPresentable","doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s7CVarArgP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s23CustomStringConvertibleP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH"]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpbannermediator"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpbannermediator"]}],"metadata":{"title":"GFPBannerMediator","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPBannerMediator"}],"roleHeading":"Class","role":"symbol","externalID":"c:objc(cs)GFPBannerMediator","symbolKind":"class","navigatorTitle":[{"text":"GFPBannerMediator","kind":"identifier"}],"modules":[{"name":"GFPSDK"}]},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerMediator","interfaceLanguage":"swift"},"topicSections":[{"anchor":"Instance-Properties","generated":true,"title":"Instance Properties","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerMediator\/delegate","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerMediator\/reportDelegate"]},{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerMediator\/loadBannerAdaptor(withAdUnitID:bannerContext:adParam:timeoutInterval:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerMediator\/loadBannerAdaptor(withAdUnitID:bannerContext:nativeContext:adParam:timeoutInterval:)"],"anchor":"Instance-Methods"}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s7CVarArgP","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPResponseInfoPresentable":{"kind":"symbol","title":"GFPResponseInfoPresentable","url":"\/documentation\/gfpsdk\/gfpresponseinfopresentable","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPResponseInfoPresentable"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPResponseInfoPresentable","type":"topic","navigatorTitle":[{"text":"GFPResponseInfoPresentable","kind":"identifier"}],"abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerMediator/loadBannerAdaptor(withAdUnitID:bannerContext:nativeContext:adParam:timeoutInterval:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"loadBannerAdaptor","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withAdUnitID","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"bannerContext"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPBannerContext","kind":"typeIdentifier","text":"GFPBannerContext"},{"text":", ","kind":"text"},{"text":"nativeContext","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"GFPNativeContext","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPNativeContext"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"adParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)GFPAdParam","text":"GFPAdParam","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"timeoutInterval","kind":"externalParam"},{"kind":"text","text":": "},{"text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/gfpsdk\/gfpbannermediator\/loadbanneradaptor(withadunitid:bannercontext:nativecontext:adparam:timeoutinterval:)","kind":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerMediator\/loadBannerAdaptor(withAdUnitID:bannerContext:nativeContext:adParam:timeoutInterval:)","role":"symbol","navigatorTitle":[{"text":"loadBannerAdaptorWithAdUnitID:bannerContext:nativeContext:adParam:timeoutInterval:","kind":"identifier"}],"title":"loadBannerAdaptor(withAdUnitID:bannerContext:nativeContext:adParam:timeoutInterval:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPMediator":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediator","title":"GFPMediator","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPMediator"}],"url":"\/documentation\/gfpsdk\/gfpmediator","type":"topic","abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPMediator"}]},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerMediator/delegate":{"title":"delegate","navigatorTitle":[{"text":"delegate","kind":"identifier"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerMediator\/delegate","url":"\/documentation\/gfpsdk\/gfpbannermediator\/delegate","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"text":": (any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)GFPBannerMediatorDelegate","text":"GFPBannerMediatorDelegate"},{"text":")?","kind":"text"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerMediator/loadBannerAdaptor(withAdUnitID:bannerContext:adParam:timeoutInterval:)":{"title":"loadBannerAdaptor(withAdUnitID:bannerContext:adParam:timeoutInterval:)","type":"topic","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"loadBannerAdaptor","kind":"identifier"},{"kind":"text","text":"("},{"text":"withAdUnitID","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"bannerContext","kind":"externalParam"},{"kind":"text","text":": "},{"text":"GFPBannerContext","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPBannerContext"},{"kind":"text","text":", "},{"text":"adParam","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)GFPAdParam","text":"GFPAdParam","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"timeoutInterval","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"},{"kind":"text","text":")"}],"url":"\/documentation\/gfpsdk\/gfpbannermediator\/loadbanneradaptor(withadunitid:bannercontext:adparam:timeoutinterval:)","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerMediator\/loadBannerAdaptor(withAdUnitID:bannerContext:adParam:timeoutInterval:)","navigatorTitle":[{"text":"loadBannerAdaptorWithAdUnitID:bannerContext:adParam:timeoutInterval:","kind":"identifier"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerMediator":{"type":"topic","navigatorTitle":[{"text":"GFPBannerMediator","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/gfpsdk\/gfpbannermediator","role":"symbol","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPBannerMediator"}],"title":"GFPBannerMediator","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerMediator"},"doc://com.navercorp.da.gfp.GFPSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH"},"doc://com.navercorp.da.gfp.GFPSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s23CustomStringConvertibleP"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerMediator/reportDelegate":{"navigatorTitle":[{"kind":"identifier","text":"reportDelegate"}],"role":"symbol","kind":"symbol","title":"reportDelegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"reportDelegate","kind":"identifier"},{"text":": (any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)GFPEventReportDelegate","text":"GFPEventReportDelegate"},{"text":")?","kind":"text"}],"type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerMediator\/reportDelegate","abstract":[],"url":"\/documentation\/gfpsdk\/gfpbannermediator\/reportdelegate"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"value":"GFPBannerMediator","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"GFPBannerMediator"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"GFPBannerMediator"}]},{"value":[{"title":"Instance Properties","anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerMediator\/delegate","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerMediator\/reportDelegate"]},{"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerMediator\/loadBannerAdaptor(withAdUnitID:bannerContext:adParam:timeoutInterval:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerMediator\/loadBannerAdaptor(withAdUnitID:bannerContext:nativeContext:adParam:timeoutInterval:)"],"generated":true}],"op":"replace","path":"\/topicSections"},{"op":"replace","value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediator"],"type":"inheritsFrom"}],"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPBannerMediator"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediator","text":"GFPMediator","preciseIdentifier":"c:objc(cs)GFPMediator"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"GFPResponseInfoPresentable","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPResponseInfoPresentable\/title"},{"value":[{"text":"GFPResponseInfoPresentable","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPResponseInfoPresentable\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPResponseInfoPresentable\/navigatorTitle","value":[{"kind":"identifier","text":"GFPResponseInfoPresentable"}]},{"value":"loadBannerAdaptorWithAdUnitID:bannerContext:nativeContext:adParam:timeoutInterval:","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerMediator~1loadBannerAdaptor(withAdUnitID:bannerContext:nativeContext:adParam:timeoutInterval:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"loadBannerAdaptorWithAdUnitID:bannerContext:nativeContext:adParam:timeoutInterval:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerMediator~1loadBannerAdaptor(withAdUnitID:bannerContext:nativeContext:adParam:timeoutInterval:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMediator\/title","value":"GFPMediator"},{"op":"replace","value":[{"kind":"identifier","text":"GFPMediator"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMediator\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMediator\/navigatorTitle","value":[{"kind":"identifier","text":"GFPMediator"}]},{"value":"delegate","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerMediator~1delegate\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerMediator~1delegate\/fragments","value":[{"text":"delegate","kind":"identifier"}]},{"op":"replace","value":"loadBannerAdaptorWithAdUnitID:bannerContext:adParam:timeoutInterval:","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerMediator~1loadBannerAdaptor(withAdUnitID:bannerContext:adParam:timeoutInterval:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"loadBannerAdaptorWithAdUnitID:bannerContext:adParam:timeoutInterval:"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerMediator~1loadBannerAdaptor(withAdUnitID:bannerContext:adParam:timeoutInterval:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerMediator\/title","value":"GFPBannerMediator"},{"op":"replace","value":[{"text":"GFPBannerMediator","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerMediator\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerMediator\/navigatorTitle","value":[{"text":"GFPBannerMediator","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerMediator~1reportDelegate\/title","value":"reportDelegate","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerMediator~1reportDelegate\/fragments","op":"replace","value":[{"text":"reportDelegate","kind":"identifier"}]}]}]}