{"sections":[],"relationshipsSections":[{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/s15BitwiseCopyableP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s25ExpressibleByArrayLiteralP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s9OptionSetP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SY","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s8SendableP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s10SetAlgebraP"]}],"topicSections":[{"generated":true,"anchor":"Initializers","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerSizeType\/init(rawValue:)"],"title":"Initializers"},{"generated":true,"anchor":"Type-Properties","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerSizeType\/fixed","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerSizeType\/fluid","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerSizeType\/fluidHeight","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerSizeType\/fluidWidth"],"title":"Type Properties"},{"title":"Default Implementations","generated":true,"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerSizeType\/Equatable-Implementations","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerSizeType\/OptionSet-Implementations","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerSizeType\/SetAlgebra-Implementations"],"anchor":"Default-Implementations"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"GFPBannerSizeType","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpbannersizetype"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpbannersizetype"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerSizeType"},"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"title":"GFPBannerSizeType","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"GFPBannerSizeType","kind":"identifier"}],"roleHeading":"Structure","role":"symbol","externalID":"c:@E@GFPBannerSizeType","symbolKind":"struct","navigatorTitle":[{"kind":"identifier","text":"GFPBannerSizeType"}],"modules":[{"name":"GFPSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerSizeType/fluidWidth":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerSizeType\/fluidWidth","navigatorTitle":[{"kind":"identifier","text":"GFPBannerFluidWidth"}],"title":"fluidWidth","kind":"symbol","type":"topic","abstract":[],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"fluidWidth","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@GFPBannerSizeType","kind":"typeIdentifier","text":"GFPBannerSizeType"}],"url":"\/documentation\/gfpsdk\/gfpbannersizetype\/fluidwidth","role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","title":"Swift.Equatable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerSizeType/fixed":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerSizeType\/fixed","navigatorTitle":[{"kind":"identifier","text":"GFPBannerFixed"}],"title":"fixed","kind":"symbol","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"fixed","kind":"identifier"},{"text":": ","kind":"text"},{"text":"GFPBannerSizeType","preciseIdentifier":"c:@E@GFPBannerSizeType","kind":"typeIdentifier"}],"url":"\/documentation\/gfpsdk\/gfpbannersizetype\/fixed","role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SY"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerSizeType/fluid":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerSizeType\/fluid","navigatorTitle":[{"kind":"identifier","text":"GFPBannerFluid"}],"title":"fluid","kind":"symbol","type":"topic","abstract":[],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"fluid","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@GFPBannerSizeType","kind":"typeIdentifier","text":"GFPBannerSizeType"}],"url":"\/documentation\/gfpsdk\/gfpbannersizetype\/fluid","role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerSizeType/Equatable-Implementations":{"type":"topic","abstract":[],"title":"Equatable Implementations","url":"\/documentation\/gfpsdk\/gfpbannersizetype\/equatable-implementations","role":"collectionGroup","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerSizeType\/Equatable-Implementations","kind":"article"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerSizeType/OptionSet-Implementations":{"title":"OptionSet Implementations","type":"topic","role":"collectionGroup","abstract":[],"kind":"article","url":"\/documentation\/gfpsdk\/gfpbannersizetype\/optionset-implementations","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerSizeType\/OptionSet-Implementations"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerSizeType/fluidHeight":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerSizeType\/fluidHeight","navigatorTitle":[{"kind":"identifier","text":"GFPBannerFluidHeight"}],"title":"fluidHeight","kind":"symbol","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"fluidHeight","kind":"identifier"},{"text":": ","kind":"text"},{"text":"GFPBannerSizeType","preciseIdentifier":"c:@E@GFPBannerSizeType","kind":"typeIdentifier"}],"url":"\/documentation\/gfpsdk\/gfpbannersizetype\/fluidheight","role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerSizeType/init(rawValue:)":{"type":"topic","abstract":[],"title":"init(rawValue:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/gfpsdk\/gfpbannersizetype\/init(rawvalue:)","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerSizeType\/init(rawValue:)","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/s8SendableP":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s8SendableP","title":"Swift.Sendable"},"doc://com.navercorp.da.gfp.GFPSDK/s9OptionSetP":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s9OptionSetP","title":"Swift.OptionSet"},"doc://com.navercorp.da.gfp.GFPSDK/s25ExpressibleByArrayLiteralP":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s25ExpressibleByArrayLiteralP","title":"Swift.ExpressibleByArrayLiteral"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerSizeType":{"role":"symbol","abstract":[],"title":"GFPBannerSizeType","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerSizeType","url":"\/documentation\/gfpsdk\/gfpbannersizetype","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPBannerSizeType"}],"navigatorTitle":[{"text":"GFPBannerSizeType","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/s15BitwiseCopyableP":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s15BitwiseCopyableP","title":"Swift.BitwiseCopyable"},"doc://com.navercorp.da.gfp.GFPSDK/s10SetAlgebraP":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s10SetAlgebraP","title":"Swift.SetAlgebra"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerSizeType/SetAlgebra-Implementations":{"type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerSizeType\/SetAlgebra-Implementations","abstract":[],"url":"\/documentation\/gfpsdk\/gfpbannersizetype\/setalgebra-implementations","kind":"article","title":"SetAlgebra Implementations","role":"collectionGroup"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"GFPBannerSizeType","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"path":"\/metadata\/fragments","value":[{"text":"GFPBannerSizeType","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"GFPBannerSizeType"}]},{"op":"replace","value":[{"generated":true,"anchor":"Enumeration-Cases","title":"Enumeration Cases","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerSizeType\/fixed","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerSizeType\/fluid","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerSizeType\/fluidHeight","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerSizeType\/fluidWidth"]}],"path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPBannerSizeType","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":"GFPBannerFluidWidth","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerSizeType~1fluidWidth\/title"},{"value":[{"kind":"identifier","text":"GFPBannerFluidWidth"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerSizeType~1fluidWidth\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerSizeType~1fixed\/title","op":"replace","value":"GFPBannerFixed"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerSizeType~1fixed\/fragments","value":[{"text":"GFPBannerFixed","kind":"identifier"}]},{"value":"GFPBannerFluid","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerSizeType~1fluid\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerSizeType~1fluid\/fragments","value":[{"kind":"identifier","text":"GFPBannerFluid"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerSizeType~1fluidHeight\/title","value":"GFPBannerFluidHeight"},{"value":[{"text":"GFPBannerFluidHeight","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerSizeType~1fluidHeight\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerSizeType\/title","value":"GFPBannerSizeType","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerSizeType\/fragments","value":[{"text":"GFPBannerSizeType","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"GFPBannerSizeType"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerSizeType\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}