{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPBannerByLoaderDelegate","kind":"identifier"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier","text":"NSObjectProtocol"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"topicSections":[{"generated":true,"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerByLoaderDelegate\/bannerAdLoader(_:didFailToSizeAdWithError:mediator:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerByLoaderDelegate\/bannerAdLoaderDidReceiveAd(_:)"],"title":"Instance Methods","anchor":"Instance-Methods"}],"metadata":{"externalID":"c:objc(pl)GFPBannerByLoaderDelegate","role":"symbol","navigatorTitle":[{"text":"GFPBannerByLoaderDelegate","kind":"identifier"}],"title":"GFPBannerByLoaderDelegate","symbolKind":"protocol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPBannerByLoaderDelegate"}],"modules":[{"name":"GFPSDK"}],"roleHeading":"Protocol"},"kind":"symbol","relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject"],"title":"Inherits From","kind":"relationships"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpbannerbyloaderdelegate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpbannerbyloaderdelegate"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerByLoaderDelegate"},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerByLoaderDelegate":{"navigatorTitle":[{"text":"GFPBannerByLoaderDelegate","kind":"identifier"}],"type":"topic","title":"GFPBannerByLoaderDelegate","kind":"symbol","url":"\/documentation\/gfpsdk\/gfpbannerbyloaderdelegate","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerByLoaderDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPBannerByLoaderDelegate"}],"role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerByLoaderDelegate/bannerAdLoaderDidReceiveAd(_:)":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerByLoaderDelegate\/bannerAdLoaderDidReceiveAd(_:)","url":"\/documentation\/gfpsdk\/gfpbannerbyloaderdelegate\/banneradloaderdidreceivead(_:)","title":"bannerAdLoaderDidReceiveAd(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"bannerAdLoaderDidReceiveAd"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPBannerView","kind":"typeIdentifier","text":"GFPBannerView"},{"text":")","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"bannerAdLoaderDidReceiveAd:","kind":"identifier"}],"kind":"symbol","required":true,"type":"topic","abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerByLoaderDelegate/bannerAdLoader(_:didFailToSizeAdWithError:mediator:)":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerByLoaderDelegate\/bannerAdLoader(_:didFailToSizeAdWithError:mediator:)","url":"\/documentation\/gfpsdk\/gfpbannerbyloaderdelegate\/banneradloader(_:didfailtosizeadwitherror:mediator:)","navigatorTitle":[{"kind":"identifier","text":"bannerAdLoader:didFailToSizeAdWithError:mediator:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bannerAdLoader"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPBannerView","kind":"typeIdentifier","text":"GFPBannerView"},{"text":", ","kind":"text"},{"text":"didFailToSizeAdWithError","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"GFPError","kind":"typeIdentifier","preciseIdentifier":"c:@M@NaverAdsServices@objc(cs)GFPError"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mediator"},{"kind":"text","text":": "},{"text":"GFPUnifiedMediator","preciseIdentifier":"c:objc(cs)GFPUnifiedMediator","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","abstract":[],"type":"topic","required":true,"title":"bannerAdLoader(_:didFailToSizeAdWithError:mediator:)","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Protocol","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"GFPBannerByLoaderDelegate"},{"value":"protocol","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"GFPBannerByLoaderDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"GFPBannerByLoaderDelegate","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"anchor":"Instance-Methods","title":"Instance Methods","generated":true,"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerByLoaderDelegate\/bannerAdLoader(_:didFailToSizeAdWithError:mediator:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerByLoaderDelegate\/bannerAdLoaderDidReceiveAd(_:)"]}]},{"value":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject"]}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPBannerByLoaderDelegate"},{"kind":"text","text":" <"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"},{"text":">","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerByLoaderDelegate\/title","value":"GFPBannerByLoaderDelegate","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerByLoaderDelegate\/fragments","value":[{"kind":"identifier","text":"GFPBannerByLoaderDelegate"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerByLoaderDelegate\/navigatorTitle","value":[{"text":"GFPBannerByLoaderDelegate","kind":"identifier"}]},{"value":"bannerAdLoaderDidReceiveAd:","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerByLoaderDelegate~1bannerAdLoaderDidReceiveAd(_:)\/title","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"bannerAdLoaderDidReceiveAd:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerByLoaderDelegate~1bannerAdLoaderDidReceiveAd(_:)\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerByLoaderDelegate~1bannerAdLoader(_:didFailToSizeAdWithError:mediator:)\/title","value":"bannerAdLoader:didFailToSizeAdWithError:mediator:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"bannerAdLoader:didFailToSizeAdWithError:mediator:"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerByLoaderDelegate~1bannerAdLoader(_:didFailToSizeAdWithError:mediator:)\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}