{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPBaseEventReporter","kind":"identifier"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"relationshipsSections":[{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"},{"type":"inheritedBy","kind":"relationships","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPEventReporter"],"title":"Inherited By"},{"title":"Conforms To","kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s7CVarArgP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s23CustomStringConvertibleP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH"]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpbaseeventreporter"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpbaseeventreporter"]}],"metadata":{"title":"GFPBaseEventReporter","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPBaseEventReporter","kind":"identifier"}],"roleHeading":"Class","role":"symbol","externalID":"c:objc(cs)GFPBaseEventReporter","symbolKind":"class","navigatorTitle":[{"text":"GFPBaseEventReporter","kind":"identifier"}],"modules":[{"name":"GFPSDK"}]},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBaseEventReporter","interfaceLanguage":"swift"},"topicSections":[{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBaseEventReporter\/init(providerEvent:)"],"title":"Initializers","generated":true,"anchor":"Initializers"},{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBaseEventReporter\/providerEvent"],"anchor":"Instance-Properties"},{"anchor":"Instance-Methods","generated":true,"title":"Instance Methods","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBaseEventReporter\/reportProviderEvent(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBaseEventReporter\/reportProviderEvent(_:queryItems:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBaseEventReporter\/reportVImp100()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBaseEventReporter\/reportVImp100p()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBaseEventReporter\/reportVImp1px()"]}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBaseEventReporter/init(providerEvent:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"providerEvent","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"GFPAdInfoEvent","preciseIdentifier":"c:objc(cs)GFPAdInfoEvent"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"initWithProviderEvent:"}],"kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBaseEventReporter\/init(providerEvent:)","type":"topic","title":"init(providerEvent:)","url":"\/documentation\/gfpsdk\/gfpbaseeventreporter\/init(providerevent:)","role":"symbol","abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBaseEventReporter/reportProviderEvent(_:queryItems:)":{"type":"topic","title":"reportProviderEvent(_:queryItems:)","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"reportProviderEvent","kind":"identifier"},{"text":"([","kind":"text"},{"text":"GFPAdEventObject","preciseIdentifier":"c:objc(cs)GFPAdEventObject","kind":"typeIdentifier"},{"kind":"text","text":"], "},{"text":"queryItems","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"URLQueryItem","preciseIdentifier":"s:10Foundation12URLQueryItemV"},{"text":"]?)","kind":"text"}],"url":"\/documentation\/gfpsdk\/gfpbaseeventreporter\/reportproviderevent(_:queryitems:)","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBaseEventReporter\/reportProviderEvent(_:queryItems:)","navigatorTitle":[{"text":"reportProviderEvent:queryItems:","kind":"identifier"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBaseEventReporter/reportVImp100p()":{"title":"reportVImp100p()","type":"topic","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"reportVImp100p"},{"text":"()","kind":"text"}],"url":"\/documentation\/gfpsdk\/gfpbaseeventreporter\/reportvimp100p()","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBaseEventReporter\/reportVImp100p()","navigatorTitle":[{"text":"reportVImp100p","kind":"identifier"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/SQ":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBaseEventReporter/reportProviderEvent(_:)":{"type":"topic","title":"reportProviderEvent(_:)","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"reportProviderEvent"},{"text":"([","kind":"text"},{"text":"GFPAdEventObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdEventObject"},{"kind":"text","text":"])"}],"url":"\/documentation\/gfpsdk\/gfpbaseeventreporter\/reportproviderevent(_:)","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBaseEventReporter\/reportProviderEvent(_:)","navigatorTitle":[{"text":"reportProviderEvent:","kind":"identifier"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBaseEventReporter":{"title":"GFPBaseEventReporter","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPBaseEventReporter","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpbaseeventreporter","navigatorTitle":[{"text":"GFPBaseEventReporter","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBaseEventReporter"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBaseEventReporter/reportVImp1px()":{"url":"\/documentation\/gfpsdk\/gfpbaseeventreporter\/reportvimp1px()","abstract":[],"type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBaseEventReporter\/reportVImp1px()","title":"reportVImp1px()","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"reportVImp1px"},{"kind":"text","text":"()"}],"navigatorTitle":[{"text":"reportVImp1px","kind":"identifier"}],"role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBaseEventReporter/providerEvent":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"providerEvent","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"GFPAdInfoEvent","preciseIdentifier":"c:objc(cs)GFPAdInfoEvent"}],"abstract":[],"navigatorTitle":[{"text":"providerEvent","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpbaseeventreporter\/providerevent","kind":"symbol","type":"topic","role":"symbol","title":"providerEvent","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBaseEventReporter\/providerEvent"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBaseEventReporter/reportVImp100()":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"reportVImp100"},{"text":"()","kind":"text"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"reportVImp100"}],"url":"\/documentation\/gfpsdk\/gfpbaseeventreporter\/reportvimp100()","kind":"symbol","type":"topic","role":"symbol","title":"reportVImp100()","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBaseEventReporter\/reportVImp100()"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.navercorp.da.gfp.GFPSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH","title":"Swift.Hashable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPEventReporter":{"url":"\/documentation\/gfpsdk\/gfpeventreporter","navigatorTitle":[{"text":"GFPEventReporter","kind":"identifier"}],"title":"GFPEventReporter","kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPEventReporter","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPEventReporter"},"doc://com.navercorp.da.gfp.GFPSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.navercorp.da.gfp.GFPSDK/s7CVarArgP":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/objc(cs)NSObject":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"value":"GFPBaseEventReporter","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GFPBaseEventReporter"}]},{"op":"replace","value":[{"kind":"identifier","text":"GFPBaseEventReporter"}],"path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","value":[{"generated":true,"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBaseEventReporter\/providerEvent"]},{"anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBaseEventReporter\/init(providerEvent:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBaseEventReporter\/reportProviderEvent(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBaseEventReporter\/reportProviderEvent(_:queryItems:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBaseEventReporter\/reportVImp100()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBaseEventReporter\/reportVImp100p()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBaseEventReporter\/reportVImp1px()"],"title":"Instance Methods"}],"op":"replace"},{"value":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject"]},{"title":"Inherited By","kind":"relationships","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPEventReporter"],"type":"inheritedBy"}],"path":"\/relationshipsSections","op":"replace"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPBaseEventReporter"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBaseEventReporter~1init(providerEvent:)\/title","value":"initWithProviderEvent:","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBaseEventReporter~1init(providerEvent:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithProviderEvent:"}]},{"value":"reportProviderEvent:queryItems:","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBaseEventReporter~1reportProviderEvent(_:queryItems:)\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBaseEventReporter~1reportProviderEvent(_:queryItems:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"reportProviderEvent:queryItems:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBaseEventReporter~1reportVImp100p()\/title","value":"reportVImp100p"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBaseEventReporter~1reportVImp100p()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"reportVImp100p","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBaseEventReporter~1reportProviderEvent(_:)\/title","value":"reportProviderEvent:"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBaseEventReporter~1reportProviderEvent(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"reportProviderEvent:"}],"op":"replace"},{"value":"GFPBaseEventReporter","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBaseEventReporter\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBaseEventReporter\/fragments","op":"replace","value":[{"kind":"identifier","text":"GFPBaseEventReporter"}]},{"op":"replace","value":[{"kind":"identifier","text":"GFPBaseEventReporter"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBaseEventReporter\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBaseEventReporter~1reportVImp1px()\/title","value":"reportVImp1px","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBaseEventReporter~1reportVImp1px()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"reportVImp1px","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBaseEventReporter~1providerEvent\/title","op":"replace","value":"providerEvent"},{"value":[{"text":"providerEvent","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBaseEventReporter~1providerEvent\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBaseEventReporter~1reportVImp100()\/title","value":"reportVImp100","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBaseEventReporter~1reportVImp100()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"reportVImp100","kind":"identifier"}]},{"value":"GFPEventReporter","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPEventReporter\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPEventReporter\/fragments","value":[{"kind":"identifier","text":"GFPEventReporter"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPEventReporter\/navigatorTitle","value":[{"text":"GFPEventReporter","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}