{"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPBannerProviderBidMachineErrorKey"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerProviderBidMachineErrorKey","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"GFPSDK"}],"role":"symbol","roleHeading":"Global Variable","title":"GFPBannerProviderBidMachineErrorKey","externalID":"c:@GFPBannerProviderBidMachineErrorKey","symbolKind":"var","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"GFPBannerProviderBidMachineErrorKey","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"GFPBannerProviderBidMachineErrorKey"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpbannerproviderbidmachineerrorkey"]},{"paths":["\/documentation\/gfpsdk\/gfpbannerproviderbidmachineerrorkey"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerProviderBidMachineErrorKey":{"kind":"symbol","navigatorTitle":[{"text":"GFPBannerProviderBidMachineErrorKey","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerProviderBidMachineErrorKey","title":"GFPBannerProviderBidMachineErrorKey","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"GFPBannerProviderBidMachineErrorKey","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"type":"topic","url":"\/documentation\/gfpsdk\/gfpbannerproviderbidmachineerrorkey","abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Global Variable"},{"op":"replace","path":"\/metadata\/title","value":"GFPBannerProviderBidMachineErrorKey"},{"path":"\/metadata\/symbolKind","value":"var","op":"replace"},{"op":"replace","value":[{"text":"GFPBannerProviderBidMachineErrorKey","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"extern","kind":"keyword"},{"kind":"text","text":" "},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"GFPBannerProviderBidMachineErrorKey"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerProviderBidMachineErrorKey\/title","op":"replace","value":"GFPBannerProviderBidMachineErrorKey"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerProviderBidMachineErrorKey\/fragments","op":"replace","value":[{"kind":"identifier","text":"GFPBannerProviderBidMachineErrorKey"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}