{"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"sections":[],"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpbanneradaptordelegate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpbanneradaptordelegate"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPBannerAdaptorDelegate","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject","text":"NSObjectProtocol"}],"languages":["swift"]}],"kind":"declarations"}],"topicSections":[{"title":"Instance Methods","anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerAdaptorDelegate\/bannerAdDidFailed(toRendering:error:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerAdaptorDelegate\/bannerAdWas(onActiveImpression:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerAdaptorDelegate\/bannerAdWasClicked(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerAdaptorDelegate\/bannerAdWasMuted(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerAdaptorDelegate\/bannerAdaptor(_:didChangeWith:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerAdaptorDelegate\/bannerAdaptor(_:didChangeWith:type:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerAdaptorDelegate\/bannerAdaptorDidDismissDefault(inAppBrowser:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerAdaptorDelegate\/bannerAdaptorDidPresentDefault(inAppBrowser:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerAdaptorDelegate\/bannerShouldUnload(_:)"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"externalID":"c:objc(pl)GFPBannerAdaptorDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPBannerAdaptorDelegate"}],"navigatorTitle":[{"text":"GFPBannerAdaptorDelegate","kind":"identifier"}],"modules":[{"name":"GFPSDK"}],"symbolKind":"protocol","role":"symbol","roleHeading":"Protocol","title":"GFPBannerAdaptorDelegate"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerAdaptorDelegate"},"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerAdaptorDelegate/bannerAdWasMuted(_:)":{"required":true,"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"bannerAdWasMuted"},{"text":"(any ","kind":"text"},{"text":"GFPAdAdaptor","preciseIdentifier":"c:objc(cs)GFPAdAdaptor","kind":"typeIdentifier"},{"text":" & ","kind":"text"},{"preciseIdentifier":"c:objc(pl)GFPBannerAdapting","kind":"typeIdentifier","text":"GFPBannerAdapting"},{"text":")","kind":"text"}],"abstract":[],"navigatorTitle":[{"text":"bannerAdWasMuted:","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpbanneradaptordelegate\/banneradwasmuted(_:)","kind":"symbol","type":"topic","role":"symbol","title":"bannerAdWasMuted(_:)","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerAdaptorDelegate\/bannerAdWasMuted(_:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerAdaptorDelegate/bannerAdWas(onActiveImpression:)":{"abstract":[],"title":"bannerAdWas(onActiveImpression:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bannerAdWas"},{"text":"(","kind":"text"},{"text":"onActiveImpression","kind":"externalParam"},{"text":": any ","kind":"text"},{"kind":"typeIdentifier","text":"GFPAdAdaptor","preciseIdentifier":"c:objc(cs)GFPAdAdaptor"},{"kind":"text","text":" & "},{"text":"GFPBannerAdapting","preciseIdentifier":"c:objc(pl)GFPBannerAdapting","kind":"typeIdentifier"},{"kind":"text","text":")"}],"url":"\/documentation\/gfpsdk\/gfpbanneradaptordelegate\/banneradwas(onactiveimpression:)","role":"symbol","required":true,"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerAdaptorDelegate\/bannerAdWas(onActiveImpression:)","navigatorTitle":[{"kind":"identifier","text":"bannerAdWasOnActiveImpression:"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerAdaptorDelegate/bannerAdaptor(_:didChangeWith:)":{"required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"bannerAdaptor"},{"text":"(any ","kind":"text"},{"text":"GFPAdAdaptor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdAdaptor"},{"text":" & ","kind":"text"},{"preciseIdentifier":"c:objc(pl)GFPBannerAdapting","text":"GFPBannerAdapting","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didChangeWith","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"])","kind":"text"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"bannerAdaptor:didChangeWith:"}],"url":"\/documentation\/gfpsdk\/gfpbanneradaptordelegate\/banneradaptor(_:didchangewith:)","kind":"symbol","type":"topic","role":"symbol","title":"bannerAdaptor(_:didChangeWith:)","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerAdaptorDelegate\/bannerAdaptor(_:didChangeWith:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerAdaptorDelegate/bannerAdWasClicked(_:)":{"required":true,"url":"\/documentation\/gfpsdk\/gfpbanneradaptordelegate\/banneradwasclicked(_:)","navigatorTitle":[{"text":"bannerAdWasClicked:","kind":"identifier"}],"abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"bannerAdWasClicked","kind":"identifier"},{"kind":"text","text":"(any "},{"text":"GFPAdAdaptor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdAdaptor"},{"text":" & ","kind":"text"},{"text":"GFPBannerAdapting","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)GFPBannerAdapting"},{"kind":"text","text":")"}],"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerAdaptorDelegate\/bannerAdWasClicked(_:)","title":"bannerAdWasClicked(_:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerAdaptorDelegate/bannerAdaptorDidDismissDefault(inAppBrowser:)":{"kind":"symbol","type":"topic","url":"\/documentation\/gfpsdk\/gfpbanneradaptordelegate\/banneradaptordiddismissdefault(inappbrowser:)","abstract":[],"required":true,"navigatorTitle":[{"text":"bannerAdaptorDidDismissDefaultInAppBrowser:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bannerAdaptorDidDismissDefault"},{"kind":"text","text":"("},{"kind":"externalParam","text":"inAppBrowser"},{"text":": any ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPAdAdaptor","kind":"typeIdentifier","text":"GFPAdAdaptor"},{"text":" & ","kind":"text"},{"text":"GFPBannerAdapting","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)GFPBannerAdapting"},{"text":")","kind":"text"}],"title":"bannerAdaptorDidDismissDefault(inAppBrowser:)","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerAdaptorDelegate\/bannerAdaptorDidDismissDefault(inAppBrowser:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerAdaptorDelegate/bannerAdaptorDidPresentDefault(inAppBrowser:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bannerAdaptorDidPresentDefault","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"inAppBrowser"},{"kind":"text","text":": any "},{"preciseIdentifier":"c:objc(cs)GFPAdAdaptor","kind":"typeIdentifier","text":"GFPAdAdaptor"},{"text":" & ","kind":"text"},{"text":"GFPBannerAdapting","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)GFPBannerAdapting"},{"text":")","kind":"text"}],"role":"symbol","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerAdaptorDelegate\/bannerAdaptorDidPresentDefault(inAppBrowser:)","kind":"symbol","type":"topic","url":"\/documentation\/gfpsdk\/gfpbanneradaptordelegate\/banneradaptordidpresentdefault(inappbrowser:)","title":"bannerAdaptorDidPresentDefault(inAppBrowser:)","navigatorTitle":[{"kind":"identifier","text":"bannerAdaptorDidPresentDefaultInAppBrowser:"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerAdaptorDelegate/bannerAdaptor(_:didChangeWith:type:)":{"abstract":[],"type":"topic","title":"bannerAdaptor(_:didChangeWith:type:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bannerAdaptor"},{"kind":"text","text":"(any "},{"preciseIdentifier":"c:objc(cs)GFPAdAdaptor","text":"GFPAdAdaptor","kind":"typeIdentifier"},{"text":" & ","kind":"text"},{"text":"GFPBannerAdapting","preciseIdentifier":"c:objc(pl)GFPBannerAdapting","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"didChangeWith","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPBannerAdSize","kind":"typeIdentifier","text":"GFPBannerAdSize"},{"kind":"text","text":", "},{"text":"type","kind":"externalParam"},{"kind":"text","text":": "},{"text":"GFPBannerSizeChangeType","kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPBannerSizeChangeType"},{"text":")","kind":"text"}],"url":"\/documentation\/gfpsdk\/gfpbanneradaptordelegate\/banneradaptor(_:didchangewith:type:)","role":"symbol","required":true,"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerAdaptorDelegate\/bannerAdaptor(_:didChangeWith:type:)","navigatorTitle":[{"text":"bannerAdaptor:didChangeWith:type:","kind":"identifier"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerAdaptorDelegate/bannerShouldUnload(_:)":{"navigatorTitle":[{"text":"bannerShouldUnload:","kind":"identifier"}],"title":"bannerShouldUnload(_:)","url":"\/documentation\/gfpsdk\/gfpbanneradaptordelegate\/bannershouldunload(_:)","required":true,"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerAdaptorDelegate\/bannerShouldUnload(_:)","abstract":[],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"bannerShouldUnload"},{"text":"(any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdAdaptor","text":"GFPAdAdaptor"},{"kind":"text","text":" & "},{"preciseIdentifier":"c:objc(pl)GFPBannerAdapting","kind":"typeIdentifier","text":"GFPBannerAdapting"},{"kind":"text","text":")"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerAdaptorDelegate/bannerAdDidFailed(toRendering:error:)":{"type":"topic","abstract":[],"url":"\/documentation\/gfpsdk\/gfpbanneradaptordelegate\/banneraddidfailed(torendering:error:)","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerAdaptorDelegate\/bannerAdDidFailed(toRendering:error:)","kind":"symbol","required":true,"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"bannerAdDidFailed","kind":"identifier"},{"text":"(","kind":"text"},{"text":"toRendering","kind":"externalParam"},{"kind":"text","text":": any "},{"text":"GFPAdAdaptor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdAdaptor"},{"text":" & ","kind":"text"},{"preciseIdentifier":"c:objc(pl)GFPBannerAdapting","kind":"typeIdentifier","text":"GFPBannerAdapting"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"error"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"GFPError","preciseIdentifier":"c:@M@NaverAdsServices@objc(cs)GFPError"},{"kind":"text","text":")"}],"title":"bannerAdDidFailed(toRendering:error:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"bannerAdDidFailedToRendering:error:"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerAdaptorDelegate":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPBannerAdaptorDelegate"}],"abstract":[],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPBannerAdaptorDelegate"}],"url":"\/documentation\/gfpsdk\/gfpbanneradaptordelegate","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerAdaptorDelegate","role":"symbol","title":"GFPBannerAdaptorDelegate","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Protocol","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"GFPBannerAdaptorDelegate"},{"value":"protocol","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"GFPBannerAdaptorDelegate","kind":"identifier"}],"op":"replace"},{"value":[{"text":"GFPBannerAdaptorDelegate","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerAdaptorDelegate\/bannerAdDidFailed(toRendering:error:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerAdaptorDelegate\/bannerAdWas(onActiveImpression:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerAdaptorDelegate\/bannerAdWasClicked(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerAdaptorDelegate\/bannerAdWasMuted(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerAdaptorDelegate\/bannerAdaptor(_:didChangeWith:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerAdaptorDelegate\/bannerAdaptor(_:didChangeWith:type:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerAdaptorDelegate\/bannerAdaptorDidDismissDefault(inAppBrowser:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerAdaptorDelegate\/bannerAdaptorDidPresentDefault(inAppBrowser:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerAdaptorDelegate\/bannerShouldUnload(_:)"],"anchor":"Instance-Methods"}],"op":"replace","path":"\/topicSections"},{"value":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject"]}],"path":"\/relationshipsSections","op":"replace"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPBannerAdaptorDelegate"},{"text":" <","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier"},{"text":">","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"bannerAdWasMuted:","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerAdaptorDelegate~1bannerAdWasMuted(_:)\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerAdaptorDelegate~1bannerAdWasMuted(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"bannerAdWasMuted:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerAdaptorDelegate~1bannerAdWas(onActiveImpression:)\/title","value":"bannerAdWasOnActiveImpression:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerAdaptorDelegate~1bannerAdWas(onActiveImpression:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"bannerAdWasOnActiveImpression:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerAdaptorDelegate~1bannerAdaptor(_:didChangeWith:)\/title","op":"replace","value":"bannerAdaptor:didChangeWith:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"bannerAdaptor:didChangeWith:"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerAdaptorDelegate~1bannerAdaptor(_:didChangeWith:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerAdaptorDelegate~1bannerAdWasClicked(_:)\/title","value":"bannerAdWasClicked:","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"bannerAdWasClicked:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerAdaptorDelegate~1bannerAdWasClicked(_:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerAdaptorDelegate~1bannerAdaptorDidDismissDefault(inAppBrowser:)\/title","value":"bannerAdaptorDidDismissDefaultInAppBrowser:"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerAdaptorDelegate~1bannerAdaptorDidDismissDefault(inAppBrowser:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"bannerAdaptorDidDismissDefaultInAppBrowser:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerAdaptorDelegate~1bannerAdaptorDidPresentDefault(inAppBrowser:)\/title","value":"bannerAdaptorDidPresentDefaultInAppBrowser:"},{"value":[{"text":"- ","kind":"text"},{"text":"bannerAdaptorDidPresentDefaultInAppBrowser:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerAdaptorDelegate~1bannerAdaptorDidPresentDefault(inAppBrowser:)\/fragments","op":"replace"},{"value":"bannerAdaptor:didChangeWith:type:","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerAdaptorDelegate~1bannerAdaptor(_:didChangeWith:type:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerAdaptorDelegate~1bannerAdaptor(_:didChangeWith:type:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"bannerAdaptor:didChangeWith:type:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerAdaptorDelegate~1bannerShouldUnload(_:)\/title","value":"bannerShouldUnload:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"bannerShouldUnload:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerAdaptorDelegate~1bannerShouldUnload(_:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerAdaptorDelegate~1bannerAdDidFailed(toRendering:error:)\/title","value":"bannerAdDidFailedToRendering:error:"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerAdaptorDelegate~1bannerAdDidFailed(toRendering:error:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"bannerAdDidFailedToRendering:error:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerAdaptorDelegate\/title","value":"GFPBannerAdaptorDelegate"},{"value":[{"text":"GFPBannerAdaptorDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerAdaptorDelegate\/fragments","op":"replace"},{"value":[{"text":"GFPBannerAdaptorDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerAdaptorDelegate\/navigatorTitle"}]}]}