{"metadata":{"symbolKind":"protocol","title":"GFPBannerMediatorDelegate","modules":[{"name":"GFPSDK"}],"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"GFPBannerMediatorDelegate","kind":"identifier"}],"roleHeading":"Protocol","navigatorTitle":[{"text":"GFPBannerMediatorDelegate","kind":"identifier"}],"externalID":"c:objc(pl)GFPBannerMediatorDelegate"},"sections":[],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerMediatorDelegate"},"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject"],"type":"inheritsFrom","kind":"relationships"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"GFPBannerMediatorDelegate","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpbannermediatordelegate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpbannermediatordelegate"]}],"topicSections":[{"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerMediatorDelegate\/bannerMediator(_:didFailToLoadBannerAdaptorWithError:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerMediatorDelegate\/bannerMediator(_:didLoad:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerMediatorDelegate\/bannerMediator(_:didLoadBannerAdaptor:)"],"generated":true}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerMediatorDelegate/bannerMediator(_:didLoad:)":{"navigatorTitle":[{"kind":"identifier","text":"bannerMediator:didLoadNativeAd:"}],"role":"symbol","kind":"symbol","title":"bannerMediator(_:didLoad:)","required":true,"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"bannerMediator","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)GFPBannerMediator","text":"GFPBannerMediator","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didLoad"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)GFPNativeAd","kind":"typeIdentifier","text":"GFPNativeAd"},{"text":")","kind":"text"}],"type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerMediatorDelegate\/bannerMediator(_:didLoad:)","abstract":[],"url":"\/documentation\/gfpsdk\/gfpbannermediatordelegate\/bannermediator(_:didload:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerMediatorDelegate/bannerMediator(_:didLoadBannerAdaptor:)":{"abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerMediatorDelegate\/bannerMediator(_:didLoadBannerAdaptor:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bannerMediator"},{"text":"(","kind":"text"},{"text":"GFPBannerMediator","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPBannerMediator"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didLoadBannerAdaptor"},{"kind":"text","text":": any "},{"preciseIdentifier":"c:objc(cs)GFPAdAdaptor","text":"GFPAdAdaptor","kind":"typeIdentifier"},{"text":" & ","kind":"text"},{"preciseIdentifier":"c:objc(pl)GFPBannerAdapting","kind":"typeIdentifier","text":"GFPBannerAdapting"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"bannerMediator:didLoadBannerAdaptor:"}],"required":true,"url":"\/documentation\/gfpsdk\/gfpbannermediatordelegate\/bannermediator(_:didloadbanneradaptor:)","type":"topic","title":"bannerMediator(_:didLoadBannerAdaptor:)","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerMediatorDelegate/bannerMediator(_:didFailToLoadBannerAdaptorWithError:)":{"title":"bannerMediator(_:didFailToLoadBannerAdaptorWithError:)","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerMediatorDelegate\/bannerMediator(_:didFailToLoadBannerAdaptorWithError:)","role":"symbol","url":"\/documentation\/gfpsdk\/gfpbannermediatordelegate\/bannermediator(_:didfailtoloadbanneradaptorwitherror:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"bannerMediator:didFailToLoadBannerAdaptorWithError:"}],"type":"topic","required":true,"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bannerMediator"},{"text":"(","kind":"text"},{"text":"GFPBannerMediator","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPBannerMediator"},{"text":", ","kind":"text"},{"text":"didFailToLoadBannerAdaptorWithError","kind":"externalParam"},{"kind":"text","text":": "},{"text":"GFPError","kind":"typeIdentifier","preciseIdentifier":"c:@M@NaverAdsServices@objc(cs)GFPError"},{"kind":"text","text":")"}],"abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)NSObject":{"title":"NSObject","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerMediatorDelegate":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"GFPBannerMediatorDelegate"}],"kind":"symbol","url":"\/documentation\/gfpsdk\/gfpbannermediatordelegate","role":"symbol","abstract":[],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPBannerMediatorDelegate"}],"title":"GFPBannerMediatorDelegate","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerMediatorDelegate"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Protocol","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"GFPBannerMediatorDelegate"},{"op":"replace","value":"protocol","path":"\/metadata\/symbolKind"},{"value":[{"text":"GFPBannerMediatorDelegate","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"GFPBannerMediatorDelegate"}]},{"value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerMediatorDelegate\/bannerMediator(_:didFailToLoadBannerAdaptorWithError:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerMediatorDelegate\/bannerMediator(_:didLoad:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerMediatorDelegate\/bannerMediator(_:didLoadBannerAdaptor:)"],"generated":true,"anchor":"Instance-Methods"}],"path":"\/topicSections","op":"replace"},{"value":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From"}],"path":"\/relationshipsSections","op":"replace"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPBannerMediatorDelegate"},{"text":" <","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject","text":"NSObject"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerMediatorDelegate~1bannerMediator(_:didLoad:)\/title","value":"bannerMediator:didLoadNativeAd:","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerMediatorDelegate~1bannerMediator(_:didLoad:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"bannerMediator:didLoadNativeAd:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerMediatorDelegate~1bannerMediator(_:didLoadBannerAdaptor:)\/title","value":"bannerMediator:didLoadBannerAdaptor:"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerMediatorDelegate~1bannerMediator(_:didLoadBannerAdaptor:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"bannerMediator:didLoadBannerAdaptor:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerMediatorDelegate~1bannerMediator(_:didFailToLoadBannerAdaptorWithError:)\/title","value":"bannerMediator:didFailToLoadBannerAdaptorWithError:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerMediatorDelegate~1bannerMediator(_:didFailToLoadBannerAdaptorWithError:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"bannerMediator:didFailToLoadBannerAdaptorWithError:"}]},{"value":"GFPBannerMediatorDelegate","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerMediatorDelegate\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerMediatorDelegate\/fragments","value":[{"text":"GFPBannerMediatorDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerMediatorDelegate\/navigatorTitle","value":[{"text":"GFPBannerMediatorDelegate","kind":"identifier"}],"op":"replace"}]}]}