{"kind":"symbol","variants":[{"paths":["\/documentation\/gfpsdk\/gfpbannerprovideriserrorkey"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gfpsdk\/gfpbannerprovideriserrorkey"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"GFPBannerProviderISErrorKey","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPBannerProviderISErrorKey","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"roleHeading":"Global Variable","role":"symbol","externalID":"c:@GFPBannerProviderISErrorKey","symbolKind":"var","navigatorTitle":[{"text":"GFPBannerProviderISErrorKey","kind":"identifier"}],"modules":[{"name":"GFPSDK"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPBannerProviderISErrorKey","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerProviderISErrorKey","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerProviderISErrorKey":{"url":"\/documentation\/gfpsdk\/gfpbannerprovideriserrorkey","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPBannerProviderISErrorKey","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"title":"GFPBannerProviderISErrorKey","kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerProviderISErrorKey","role":"symbol","abstract":[],"type":"topic","navigatorTitle":[{"text":"GFPBannerProviderISErrorKey","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Global Variable","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"GFPBannerProviderISErrorKey","op":"replace"},{"value":"var","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"GFPBannerProviderISErrorKey","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"extern","kind":"keyword"},{"kind":"text","text":" "},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"GFPBannerProviderISErrorKey","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerProviderISErrorKey\/title","value":"GFPBannerProviderISErrorKey"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerProviderISErrorKey\/fragments","value":[{"text":"GFPBannerProviderISErrorKey","kind":"identifier"}],"op":"replace"}]}]}