{"metadata":{"role":"symbol","modules":[{"name":"GFPSDK"}],"externalID":"c:@GFPBannerProviderNDAErrorKey","symbolKind":"var","title":"GFPBannerProviderNDAErrorKey","navigatorTitle":[{"kind":"identifier","text":"GFPBannerProviderNDAErrorKey"}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPBannerProviderNDAErrorKey"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"roleHeading":"Global Variable"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPBannerProviderNDAErrorKey","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpbannerproviderndaerrorkey"]},{"paths":["\/documentation\/gfpsdk\/gfpbannerproviderndaerrorkey"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerProviderNDAErrorKey"},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerProviderNDAErrorKey":{"title":"GFPBannerProviderNDAErrorKey","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"GFPBannerProviderNDAErrorKey","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"type":"topic","abstract":[],"role":"symbol","navigatorTitle":[{"text":"GFPBannerProviderNDAErrorKey","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpbannerproviderndaerrorkey","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerProviderNDAErrorKey"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Global Variable"},{"op":"replace","path":"\/metadata\/title","value":"GFPBannerProviderNDAErrorKey"},{"path":"\/metadata\/symbolKind","value":"var","op":"replace"},{"value":[{"text":"GFPBannerProviderNDAErrorKey","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"GFPBannerProviderNDAErrorKey"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"GFPBannerProviderNDAErrorKey","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerProviderNDAErrorKey\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerProviderNDAErrorKey\/fragments","value":[{"kind":"identifier","text":"GFPBannerProviderNDAErrorKey"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}