{"topicSections":[{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBadgeOption\/init(borderColor:borderAlpha:borderWidth:badgeBgColor:badgeBgAlpha:)"],"anchor":"Initializers","generated":true,"title":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBadgeOption\/badgeBgAlpha","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBadgeOption\/badgeBgColor","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBadgeOption\/borderAlpha","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBadgeOption\/borderColor","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBadgeOption\/borderWidth"],"anchor":"Instance-Properties","generated":true}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objcMembers","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"GFPBadgeOption","kind":"identifier"}]}],"kind":"declarations"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"metadata":{"modules":[{"name":"GFPSDK"}],"title":"GFPBadgeOption","roleHeading":"Class","symbolKind":"class","externalID":"c:@M@GFPSDK@objc(cs)GFPBadgeOption","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPBadgeOption"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPBadgeOption"}]},"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject"]},{"kind":"relationships","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s7CVarArgP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s23CustomStringConvertibleP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH"],"title":"Conforms To","type":"conformsTo"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpbadgeoption"]},{"paths":["\/documentation\/gfpsdk\/gfpbadgeoption"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBadgeOption"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBadgeOption/borderAlpha":{"title":"borderAlpha","role":"symbol","abstract":[{"type":"text","text":"Badge의 Border Alpha"}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"borderAlpha","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"borderAlpha","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBadgeOption\/borderAlpha","type":"topic","url":"\/documentation\/gfpsdk\/gfpbadgeoption\/borderalpha","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBadgeOption/badgeBgColor":{"role":"symbol","abstract":[{"type":"text","text":"Badge의 배경 색상"}],"title":"badgeBgColor","navigatorTitle":[{"kind":"identifier","text":"badgeBgColor"}],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"badgeBgColor"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBadgeOption\/badgeBgColor","type":"topic","kind":"symbol","url":"\/documentation\/gfpsdk\/gfpbadgeoption\/badgebgcolor"},"doc://com.navercorp.da.gfp.GFPSDK/SH":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBadgeOption/borderColor":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBadgeOption\/borderColor","role":"symbol","url":"\/documentation\/gfpsdk\/gfpbadgeoption\/bordercolor","navigatorTitle":[{"text":"borderColor","kind":"identifier"}],"type":"topic","title":"borderColor","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"borderColor"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"Badge의 Border 색상"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBadgeOption/init(borderColor:borderAlpha:borderWidth:badgeBgColor:badgeBgAlpha:)":{"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"borderColor"},{"text":": ","kind":"text"},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"borderAlpha","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"borderWidth"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier","text":"CGFloat"},{"kind":"text","text":", "},{"kind":"externalParam","text":"badgeBgColor"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"?, "},{"text":"badgeBgAlpha","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":")"}],"abstract":[],"navigatorTitle":[{"text":"initWithBorderColor:borderAlpha:borderWidth:badgeBgColor:badgeBgAlpha:","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpbadgeoption\/init(bordercolor:borderalpha:borderwidth:badgebgcolor:badgebgalpha:)","kind":"symbol","type":"topic","role":"symbol","title":"init(borderColor:borderAlpha:borderWidth:badgeBgColor:badgeBgAlpha:)","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBadgeOption\/init(borderColor:borderAlpha:borderWidth:badgeBgColor:badgeBgAlpha:)"},"doc://com.navercorp.da.gfp.GFPSDK/SQ":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBadgeOption/badgeBgAlpha":{"type":"topic","title":"badgeBgAlpha","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"badgeBgAlpha","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"}],"abstract":[{"text":"Badge의 배경 Alpha","type":"text"}],"url":"\/documentation\/gfpsdk\/gfpbadgeoption\/badgebgalpha","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"badgeBgAlpha"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBadgeOption\/badgeBgAlpha"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.navercorp.da.gfp.GFPSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBadgeOption/borderWidth":{"kind":"symbol","role":"symbol","type":"topic","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"borderWidth","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier"}],"url":"\/documentation\/gfpsdk\/gfpbadgeoption\/borderwidth","title":"borderWidth","abstract":[{"text":"Badge의 BorderWidth","type":"text"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBadgeOption\/borderWidth","navigatorTitle":[{"kind":"identifier","text":"borderWidth"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBadgeOption":{"title":"GFPBadgeOption","abstract":[],"url":"\/documentation\/gfpsdk\/gfpbadgeoption","role":"symbol","navigatorTitle":[{"text":"GFPBadgeOption","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBadgeOption","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"GFPBadgeOption","kind":"identifier"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject","title":"NSObject"},"doc://com.navercorp.da.gfp.GFPSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","value":"GFPBadgeOption","op":"replace"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"GFPBadgeOption"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"GFPBadgeOption"}]},{"path":"\/topicSections","op":"replace","value":[{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBadgeOption\/badgeBgAlpha","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBadgeOption\/badgeBgColor","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBadgeOption\/borderAlpha","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBadgeOption\/borderColor","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBadgeOption\/borderWidth"],"anchor":"Instance-Properties"},{"anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBadgeOption\/init(borderColor:borderAlpha:borderWidth:badgeBgColor:badgeBgAlpha:)"],"title":"Instance Methods"}]},{"value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject"],"type":"inheritsFrom"}],"path":"\/relationshipsSections","op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPBadgeOption","kind":"identifier"},{"kind":"text","text":" : "},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBadgeOption~1borderAlpha\/title","value":"borderAlpha","op":"replace"},{"op":"replace","value":[{"text":"borderAlpha","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBadgeOption~1borderAlpha\/fragments"},{"value":"badgeBgColor","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBadgeOption~1badgeBgColor\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBadgeOption~1badgeBgColor\/fragments","value":[{"kind":"identifier","text":"badgeBgColor"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBadgeOption~1borderColor\/title","value":"borderColor","op":"replace"},{"value":[{"kind":"identifier","text":"borderColor"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBadgeOption~1borderColor\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBadgeOption~1init(borderColor:borderAlpha:borderWidth:badgeBgColor:badgeBgAlpha:)\/title","op":"replace","value":"initWithBorderColor:borderAlpha:borderWidth:badgeBgColor:badgeBgAlpha:"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithBorderColor:borderAlpha:borderWidth:badgeBgColor:badgeBgAlpha:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBadgeOption~1init(borderColor:borderAlpha:borderWidth:badgeBgColor:badgeBgAlpha:)\/fragments"},{"op":"replace","value":"badgeBgAlpha","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBadgeOption~1badgeBgAlpha\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBadgeOption~1badgeBgAlpha\/fragments","op":"replace","value":[{"kind":"identifier","text":"badgeBgAlpha"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBadgeOption~1borderWidth\/title","value":"borderWidth","op":"replace"},{"value":[{"kind":"identifier","text":"borderWidth"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBadgeOption~1borderWidth\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBadgeOption\/title","op":"replace","value":"GFPBadgeOption"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBadgeOption\/fragments","op":"replace","value":[{"text":"GFPBadgeOption","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBadgeOption\/navigatorTitle","op":"replace","value":[{"text":"GFPBadgeOption","kind":"identifier"}]}]}]}