{"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"kind":"symbol","relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject"]}],"topicSections":[{"anchor":"Instance-Methods","generated":true,"title":"Instance Methods","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerViewDelegate\/bannerAdDidDismissDefault(inAppBrowser:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerViewDelegate\/bannerAdDidPresentDefault(inAppBrowser:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerViewDelegate\/bannerAdWasClicked(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerViewDelegate\/bannerAdWasMuted(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerViewDelegate\/bannerAdWasSeen(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerViewDelegate\/bannerShouldUnload(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerViewDelegate\/bannerView(_:didChangeAdMeta:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerViewDelegate\/bannerView(_:didChangeWith:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerViewDelegate\/bannerView(_:didFailToReceiveAdWithError:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerViewDelegate\/bannerView(_:didLoad:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerViewDelegate\/bannerViewDidReceiveAd(_:)"]}],"sections":[],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpbannerviewdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gfpsdk\/gfpbannerviewdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"GFPBannerViewDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPBannerViewDelegate"}],"roleHeading":"Protocol","role":"symbol","externalID":"c:objc(pl)GFPBannerViewDelegate","symbolKind":"protocol","navigatorTitle":[{"text":"GFPBannerViewDelegate","kind":"identifier"}],"modules":[{"name":"GFPSDK"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"GFPBannerViewDelegate","kind":"identifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerViewDelegate","interfaceLanguage":"swift"},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerViewDelegate/bannerView(_:didChangeWith:)":{"role":"symbol","abstract":[{"type":"text","text":"배너 사이즈 변경 시 호출됩니다."}],"title":"bannerView(_:didChangeWith:)","navigatorTitle":[{"text":"bannerView:didChangeWith:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bannerView"},{"kind":"text","text":"("},{"text":"GFPBannerView","preciseIdentifier":"c:objc(cs)GFPBannerView","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didChangeWith"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"GFPBannerAdSize","preciseIdentifier":"c:objc(cs)GFPBannerAdSize"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerViewDelegate\/bannerView(_:didChangeWith:)","url":"\/documentation\/gfpsdk\/gfpbannerviewdelegate\/bannerview(_:didchangewith:)","kind":"symbol","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerViewDelegate/bannerAdWasSeen(_:)":{"url":"\/documentation\/gfpsdk\/gfpbannerviewdelegate\/banneradwasseen(_:)","title":"bannerAdWasSeen(_:)","type":"topic","required":true,"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"bannerAdWasSeen","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPBannerView","text":"GFPBannerView"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"bannerAdWasSeen:"}],"abstract":[{"type":"text","text":"배너 광고가 사용자에게 보여진 경우 호출됩니다.(viewable impression)"}],"kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerViewDelegate\/bannerAdWasSeen(_:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerViewDelegate/bannerView(_:didLoad:)":{"navigatorTitle":[{"kind":"identifier","text":"bannerView:didLoadNativeAd:"}],"url":"\/documentation\/gfpsdk\/gfpbannerviewdelegate\/bannerview(_:didload:)","title":"bannerView(_:didLoad:)","role":"symbol","abstract":[{"type":"text","text":"GFPBannerView 의 네이티브 광고 로드가 허용(nativeAdEnabled = YES)되어 있을 때, 네이티브 광고가 정상적으로 로드되면 호출됩니다."}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"bannerView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GFPBannerView","preciseIdentifier":"c:objc(cs)GFPBannerView"},{"text":", ","kind":"text"},{"text":"didLoad","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GFPNativeAd","preciseIdentifier":"c:objc(cs)GFPNativeAd"},{"kind":"text","text":")"}],"type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerViewDelegate\/bannerView(_:didLoad:)","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerViewDelegate/bannerAdWasClicked(_:)":{"title":"bannerAdWasClicked(_:)","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerViewDelegate\/bannerAdWasClicked(_:)","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"배너 광고 클릭 시 호출됩니다."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"bannerAdWasClicked"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPBannerView","text":"GFPBannerView"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"bannerAdWasClicked:"}],"type":"topic","url":"\/documentation\/gfpsdk\/gfpbannerviewdelegate\/banneradwasclicked(_:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerViewDelegate/bannerAdWasMuted(_:)":{"role":"symbol","navigatorTitle":[{"text":"bannerAdWasMuted:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"bannerAdWasMuted","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPBannerView","text":"GFPBannerView","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerViewDelegate\/bannerAdWasMuted(_:)","type":"topic","kind":"symbol","url":"\/documentation\/gfpsdk\/gfpbannerviewdelegate\/banneradwasmuted(_:)","abstract":[{"type":"text","text":"배너 광고 뮤트 시 호출됩니다."}],"title":"bannerAdWasMuted(_:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerViewDelegate":{"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPBannerViewDelegate","kind":"identifier"}],"kind":"symbol","abstract":[],"url":"\/documentation\/gfpsdk\/gfpbannerviewdelegate","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerViewDelegate","title":"GFPBannerViewDelegate","type":"topic","navigatorTitle":[{"text":"GFPBannerViewDelegate","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerViewDelegate/bannerShouldUnload(_:)":{"navigatorTitle":[{"text":"bannerShouldUnload:","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerViewDelegate\/bannerShouldUnload(_:)","title":"bannerShouldUnload(_:)","role":"symbol","url":"\/documentation\/gfpsdk\/gfpbannerviewdelegate\/bannershouldunload(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"bannerShouldUnload","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPBannerView","text":"GFPBannerView","kind":"typeIdentifier"},{"kind":"text","text":")"}],"type":"topic","kind":"symbol","abstract":[{"text":"배너 뷰가 Mraid 3.0 스펙의 Unload로 인해 뷰가 제거되기 전에 호출됩니다.","type":"text"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerViewDelegate/bannerView(_:didFailToReceiveAdWithError:)":{"role":"symbol","abstract":[{"type":"text","text":"광고 로드 및 렌더링에 실패한 경우 호출됩니다."}],"title":"bannerView(_:didFailToReceiveAdWithError:)","navigatorTitle":[{"kind":"identifier","text":"bannerView:didFailToReceiveAdWithError:"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"bannerView"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPBannerView","kind":"typeIdentifier","text":"GFPBannerView"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didFailToReceiveAdWithError"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@NaverAdsServices@objc(cs)GFPError","kind":"typeIdentifier","text":"GFPError"},{"text":")","kind":"text"}],"url":"\/documentation\/gfpsdk\/gfpbannerviewdelegate\/bannerview(_:didfailtoreceiveadwitherror:)","type":"topic","kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerViewDelegate\/bannerView(_:didFailToReceiveAdWithError:)"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","title":"NSObject"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerViewDelegate/bannerViewDidReceiveAd(_:)":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerViewDelegate\/bannerViewDidReceiveAd(_:)","title":"bannerViewDidReceiveAd(_:)","role":"symbol","url":"\/documentation\/gfpsdk\/gfpbannerviewdelegate\/bannerviewdidreceivead(_:)","kind":"symbol","navigatorTitle":[{"text":"bannerViewDidReceiveAd:","kind":"identifier"}],"type":"topic","required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"bannerViewDidReceiveAd","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPBannerView","text":"GFPBannerView"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"배너 광고가 정상적으로 로드된 경우 호출됩니다."}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerViewDelegate/bannerView(_:didChangeAdMeta:)":{"url":"\/documentation\/gfpsdk\/gfpbannerviewdelegate\/bannerview(_:didchangeadmeta:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"bannerView","kind":"identifier"},{"kind":"text","text":"("},{"text":"GFPBannerView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPBannerView"},{"text":", ","kind":"text"},{"text":"didChangeAdMeta","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"])","kind":"text"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerViewDelegate\/bannerView(_:didChangeAdMeta:)","kind":"symbol","navigatorTitle":[{"text":"bannerView:didChangeAdMeta:","kind":"identifier"}],"role":"symbol","title":"bannerView(_:didChangeAdMeta:)","type":"topic","abstract":[{"type":"text","text":"배너 광고 소재에서 MetaData 변경 시 호출됩니다."}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerViewDelegate/bannerAdDidPresentDefault(inAppBrowser:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"bannerAdDidPresentDefault","kind":"identifier"},{"text":"(","kind":"text"},{"text":"inAppBrowser","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPBannerView","text":"GFPBannerView"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Default In App Browser 사용 시, 클릭이 이루어져서 SFSafariViewController가 정상적으로 Present 시 호출됩니다."}],"navigatorTitle":[{"kind":"identifier","text":"bannerAdDidPresentDefaultInAppBrowser:"}],"url":"\/documentation\/gfpsdk\/gfpbannerviewdelegate\/banneraddidpresentdefault(inappbrowser:)","kind":"symbol","type":"topic","role":"symbol","title":"bannerAdDidPresentDefault(inAppBrowser:)","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerViewDelegate\/bannerAdDidPresentDefault(inAppBrowser:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerViewDelegate/bannerAdDidDismissDefault(inAppBrowser:)":{"url":"\/documentation\/gfpsdk\/gfpbannerviewdelegate\/banneraddiddismissdefault(inappbrowser:)","required":true,"abstract":[{"type":"text","text":"Default In App Browser 사용 시, 클릭이 이루어져서 SFSafariViewController가 정상적으로 Dismiss 시 호출됩니다."}],"role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerViewDelegate\/bannerAdDidDismissDefault(inAppBrowser:)","navigatorTitle":[{"kind":"identifier","text":"bannerAdDidDismissDefaultInAppBrowser:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bannerAdDidDismissDefault"},{"kind":"text","text":"("},{"kind":"externalParam","text":"inAppBrowser"},{"text":": ","kind":"text"},{"text":"GFPBannerView","preciseIdentifier":"c:objc(cs)GFPBannerView","kind":"typeIdentifier"},{"kind":"text","text":")"}],"type":"topic","title":"bannerAdDidDismissDefault(inAppBrowser:)","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Protocol","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"GFPBannerViewDelegate"},{"op":"replace","value":"protocol","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"GFPBannerViewDelegate","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"GFPBannerViewDelegate"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerViewDelegate\/bannerAdDidDismissDefault(inAppBrowser:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerViewDelegate\/bannerAdDidPresentDefault(inAppBrowser:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerViewDelegate\/bannerAdWasClicked(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerViewDelegate\/bannerAdWasMuted(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerViewDelegate\/bannerAdWasSeen(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerViewDelegate\/bannerShouldUnload(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerViewDelegate\/bannerView(_:didChangeAdMeta:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerViewDelegate\/bannerView(_:didChangeWith:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerViewDelegate\/bannerView(_:didFailToReceiveAdWithError:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerViewDelegate\/bannerView(_:didLoad:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerViewDelegate\/bannerViewDidReceiveAd(_:)"],"generated":true}]},{"op":"replace","value":[{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"}],"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPBannerViewDelegate","kind":"identifier"},{"text":" <","kind":"text"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(pl)NSObject"},{"text":">","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerViewDelegate~1bannerView(_:didChangeWith:)\/title","value":"bannerView:didChangeWith:"},{"value":[{"text":"- ","kind":"text"},{"text":"bannerView:didChangeWith:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerViewDelegate~1bannerView(_:didChangeWith:)\/fragments","op":"replace"},{"value":"bannerAdWasSeen:","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerViewDelegate~1bannerAdWasSeen(_:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerViewDelegate~1bannerAdWasSeen(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"bannerAdWasSeen:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerViewDelegate~1bannerView(_:didLoad:)\/title","value":"bannerView:didLoadNativeAd:"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerViewDelegate~1bannerView(_:didLoad:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"bannerView:didLoadNativeAd:","kind":"identifier"}]},{"value":"bannerAdWasClicked:","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerViewDelegate~1bannerAdWasClicked(_:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"bannerAdWasClicked:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerViewDelegate~1bannerAdWasClicked(_:)\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerViewDelegate~1bannerAdWasMuted(_:)\/title","op":"replace","value":"bannerAdWasMuted:"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerViewDelegate~1bannerAdWasMuted(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"bannerAdWasMuted:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerViewDelegate\/title","op":"replace","value":"GFPBannerViewDelegate"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerViewDelegate\/fragments","op":"replace","value":[{"text":"GFPBannerViewDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerViewDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"GFPBannerViewDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerViewDelegate~1bannerShouldUnload(_:)\/title","value":"bannerShouldUnload:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"bannerShouldUnload:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerViewDelegate~1bannerShouldUnload(_:)\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerViewDelegate~1bannerView(_:didFailToReceiveAdWithError:)\/title","value":"bannerView:didFailToReceiveAdWithError:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"bannerView:didFailToReceiveAdWithError:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerViewDelegate~1bannerView(_:didFailToReceiveAdWithError:)\/fragments","op":"replace"},{"value":"bannerViewDidReceiveAd:","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerViewDelegate~1bannerViewDidReceiveAd(_:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"bannerViewDidReceiveAd:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerViewDelegate~1bannerViewDidReceiveAd(_:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerViewDelegate~1bannerView(_:didChangeAdMeta:)\/title","value":"bannerView:didChangeAdMeta:"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerViewDelegate~1bannerView(_:didChangeAdMeta:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"bannerView:didChangeAdMeta:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerViewDelegate~1bannerAdDidPresentDefault(inAppBrowser:)\/title","value":"bannerAdDidPresentDefaultInAppBrowser:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"bannerAdDidPresentDefaultInAppBrowser:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerViewDelegate~1bannerAdDidPresentDefault(inAppBrowser:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerViewDelegate~1bannerAdDidDismissDefault(inAppBrowser:)\/title","op":"replace","value":"bannerAdDidDismissDefaultInAppBrowser:"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerViewDelegate~1bannerAdDidDismissDefault(inAppBrowser:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"bannerAdDidDismissDefaultInAppBrowser:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}