{"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"relationshipsSections":[{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SY"]}],"metadata":{"symbolKind":"enum","externalID":"c:@M@GFPSDK@E@GFPCombinedProviderOption","modules":[{"name":"GFPSDK"}],"navigatorTitle":[{"text":"GFPCombinedProviderOption","kind":"identifier"}],"title":"GFPCombinedProviderOption","roleHeading":"Enumeration","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPCombinedProviderOption"}],"role":"symbol"},"topicSections":[{"generated":true,"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPCombinedProviderOption\/DFP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPCombinedProviderOption\/end","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPCombinedProviderOption\/none"],"title":"Enumeration Cases","anchor":"Enumeration-Cases"},{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPCombinedProviderOption\/init(rawValue:)"],"generated":true,"title":"Initializers","anchor":"Initializers"},{"generated":true,"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPCombinedProviderOption\/Equatable-Implementations","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPCombinedProviderOption\/RawRepresentable-Implementations"],"title":"Default Implementations","anchor":"Default-Implementations"}],"abstract":[{"type":"text","text":"GFP에서 지원하는 Combined (배너, 네이티브)광고 제공자 목록"}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"GFPCombinedProviderOption","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpcombinedprovideroption"]},{"paths":["\/documentation\/gfpsdk\/gfpcombinedprovideroption"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPCombinedProviderOption"},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPCombinedProviderOption":{"navigatorTitle":[{"text":"GFPCombinedProviderOption","kind":"identifier"}],"type":"topic","title":"GFPCombinedProviderOption","kind":"symbol","url":"\/documentation\/gfpsdk\/gfpcombinedprovideroption","abstract":[{"type":"text","text":"GFP에서 지원하는 Combined (배너, 네이티브)광고 제공자 목록"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPCombinedProviderOption","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPCombinedProviderOption"}],"role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SY"},"doc://com.navercorp.da.gfp.GFPSDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPCombinedProviderOption/none":{"url":"\/documentation\/gfpsdk\/gfpcombinedprovideroption\/none","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPCombinedProviderOption\/none","title":"GFPCombinedProviderOption.none","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"GFPCombinedProviderOptionNone","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"none","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPCombinedProviderOption/RawRepresentable-Implementations":{"role":"collectionGroup","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPCombinedProviderOption\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/gfpsdk\/gfpcombinedprovideroption\/rawrepresentable-implementations","title":"RawRepresentable Implementations"},"doc://com.navercorp.da.gfp.GFPSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPCombinedProviderOption/DFP":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DFP"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"GFPCombinedProviderOptionDFP"}],"url":"\/documentation\/gfpsdk\/gfpcombinedprovideroption\/dfp","kind":"symbol","type":"topic","role":"symbol","title":"GFPCombinedProviderOption.DFP","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPCombinedProviderOption\/DFP"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPCombinedProviderOption/Equatable-Implementations":{"kind":"article","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPCombinedProviderOption\/Equatable-Implementations","url":"\/documentation\/gfpsdk\/gfpcombinedprovideroption\/equatable-implementations","type":"topic","role":"collectionGroup"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPCombinedProviderOption/init(rawValue:)":{"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPCombinedProviderOption\/init(rawValue:)","type":"topic","role":"symbol","abstract":[],"url":"\/documentation\/gfpsdk\/gfpcombinedprovideroption\/init(rawvalue:)","title":"init(rawValue:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPCombinedProviderOption/end":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPCombinedProviderOption\/end","url":"\/documentation\/gfpsdk\/gfpcombinedprovideroption\/end","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"end","kind":"identifier"}],"abstract":[],"title":"GFPCombinedProviderOption.end","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"GFPCombinedProviderOptionEnd","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"path":"\/metadata\/title","op":"replace","value":"GFPCombinedProviderOption"},{"op":"replace","value":"enum","path":"\/metadata\/symbolKind"},{"value":[{"text":"GFPCombinedProviderOption","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"GFPCombinedProviderOption"}]},{"path":"\/topicSections","op":"replace","value":[{"title":"Enumeration Cases","generated":true,"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPCombinedProviderOption\/DFP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPCombinedProviderOption\/end","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPCombinedProviderOption\/none"],"anchor":"Enumeration-Cases"}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"GFPCombinedProviderOption","kind":"identifier"},{"kind":"text","text":": "},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPCombinedProviderOption\/title","value":"GFPCombinedProviderOption"},{"op":"replace","value":[{"text":"GFPCombinedProviderOption","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPCombinedProviderOption\/fragments"},{"value":[{"kind":"identifier","text":"GFPCombinedProviderOption"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPCombinedProviderOption\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPCombinedProviderOption~1none\/title","value":"GFPCombinedProviderOptionNone","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPCombinedProviderOption~1none\/fragments","value":[{"text":"GFPCombinedProviderOptionNone","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPCombinedProviderOption~1DFP\/title","value":"GFPCombinedProviderOptionDFP","op":"replace"},{"value":[{"text":"GFPCombinedProviderOptionDFP","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPCombinedProviderOption~1DFP\/fragments"},{"value":"GFPCombinedProviderOptionEnd","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPCombinedProviderOption~1end\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPCombinedProviderOption~1end\/fragments","value":[{"kind":"identifier","text":"GFPCombinedProviderOptionEnd"}]}]}]}