{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"GFPCombinedAdapting","kind":"identifier"},{"text":" : ","kind":"text"},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAdapting","preciseIdentifier":"c:objc(pl)GFPAdAdapting","text":"GFPAdAdapting","kind":"typeIdentifier"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpcombinedadapting"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gfpsdk\/gfpcombinedadapting"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAdapting","doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject"],"kind":"relationships"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPCombinedAdapting"},"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"navigatorTitle":[{"text":"GFPCombinedAdapting","kind":"identifier"}],"externalID":"c:objc(pl)GFPCombinedAdapting","modules":[{"name":"GFPSDK"}],"roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","title":"GFPCombinedAdapting","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"GFPCombinedAdapting","kind":"identifier"}]},"sections":[],"topicSections":[{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPCombinedAdapting\/bannerAdaptor","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPCombinedAdapting\/nativeAdaptor","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPCombinedAdapting\/nativeLoaded"],"anchor":"Instance-Properties"}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdAdapting":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"GFPAdAdapting","kind":"identifier"}],"abstract":[],"url":"\/documentation\/gfpsdk\/gfpadadapting","kind":"symbol","role":"symbol","title":"GFPAdAdapting","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAdapting","type":"topic","navigatorTitle":[{"text":"GFPAdAdapting","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPCombinedAdapting/nativeLoaded":{"navigatorTitle":[{"text":"nativeLoaded","kind":"identifier"}],"type":"topic","url":"\/documentation\/gfpsdk\/gfpcombinedadapting\/nativeloaded","kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPCombinedAdapting\/nativeLoaded","abstract":[],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nativeLoaded","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"title":"nativeLoaded","required":true},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPCombinedAdapting/bannerAdaptor":{"navigatorTitle":[{"text":"bannerAdaptor","kind":"identifier"}],"type":"topic","url":"\/documentation\/gfpsdk\/gfpcombinedadapting\/banneradaptor","kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPCombinedAdapting\/bannerAdaptor","abstract":[],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"bannerAdaptor","kind":"identifier"},{"text":": (any ","kind":"text"},{"text":"GFPAdAdaptor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdAdaptor"},{"text":" & ","kind":"text"},{"text":"GFPBannerAdapting","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)GFPBannerAdapting"},{"text":")?","kind":"text"}],"title":"bannerAdaptor","required":true},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)NSObject":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPCombinedAdapting/nativeAdaptor":{"navigatorTitle":[{"kind":"identifier","text":"nativeAdaptor"}],"type":"topic","url":"\/documentation\/gfpsdk\/gfpcombinedadapting\/nativeadaptor","kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPCombinedAdapting\/nativeAdaptor","abstract":[],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nativeAdaptor","kind":"identifier"},{"kind":"text","text":": (any "},{"text":"GFPAdAdaptor","preciseIdentifier":"c:objc(cs)GFPAdAdaptor","kind":"typeIdentifier"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)GFPNativeAdapting","text":"GFPNativeAdapting"},{"kind":"text","text":")?"}],"title":"nativeAdaptor","required":true},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPCombinedAdapting":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPCombinedAdapting","title":"GFPCombinedAdapting","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GFPCombinedAdapting"}],"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPCombinedAdapting"}],"abstract":[],"kind":"symbol","url":"\/documentation\/gfpsdk\/gfpcombinedadapting"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"GFPCombinedAdapting"},{"path":"\/metadata\/symbolKind","op":"replace","value":"protocol"},{"op":"replace","value":[{"kind":"identifier","text":"GFPCombinedAdapting"}],"path":"\/metadata\/fragments"},{"value":[{"text":"GFPCombinedAdapting","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPCombinedAdapting\/bannerAdaptor","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPCombinedAdapting\/nativeAdaptor","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPCombinedAdapting\/nativeLoaded"],"generated":true,"anchor":"Instance-Properties"}]},{"value":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAdapting"]}],"op":"replace","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"text":" ","kind":"text"},{"text":"GFPCombinedAdapting","kind":"identifier"},{"kind":"text","text":" <"},{"text":"GFPAdAdapting","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAdapting","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)GFPAdAdapting"},{"text":">","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdapting\/title","value":"GFPAdAdapting","op":"replace"},{"value":[{"text":"GFPAdAdapting","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdapting\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdapting\/navigatorTitle","value":[{"kind":"identifier","text":"GFPAdAdapting"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPCombinedAdapting~1nativeLoaded\/title","value":"nativeLoaded","op":"replace"},{"value":[{"text":"nativeLoaded","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPCombinedAdapting~1nativeLoaded\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPCombinedAdapting~1bannerAdaptor\/title","value":"bannerAdaptor"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPCombinedAdapting~1bannerAdaptor\/fragments","value":[{"text":"bannerAdaptor","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPCombinedAdapting~1nativeAdaptor\/title","op":"replace","value":"nativeAdaptor"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPCombinedAdapting~1nativeAdaptor\/fragments","value":[{"text":"nativeAdaptor","kind":"identifier"}],"op":"replace"},{"value":"GFPCombinedAdapting","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPCombinedAdapting\/title","op":"replace"},{"value":[{"text":"GFPCombinedAdapting","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPCombinedAdapting\/fragments"},{"op":"replace","value":[{"text":"GFPCombinedAdapting","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPCombinedAdapting\/navigatorTitle"}]}]}