{"relationshipsSections":[{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/s15BitwiseCopyableP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s25ExpressibleByArrayLiteralP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s9OptionSetP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SY","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s8SendableP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s10SetAlgebraP"],"type":"conformsTo"}],"topicSections":[{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPCreativeType\/init(rawValue:)"],"generated":true,"title":"Initializers","anchor":"Initializers"},{"anchor":"Type-Properties","title":"Type Properties","generated":true,"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPCreativeType\/loudness","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPCreativeType\/nonLinear"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPCreativeType\/Equatable-Implementations","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPCreativeType\/OptionSet-Implementations","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPCreativeType\/SetAlgebra-Implementations"],"generated":true,"anchor":"Default-Implementations"}],"metadata":{"title":"GFPCreativeType","externalID":"c:@E@GFPCreativeType","role":"symbol","symbolKind":"struct","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPCreativeType","kind":"identifier"}],"modules":[{"name":"GFPSDK"}],"navigatorTitle":[{"text":"GFPCreativeType","kind":"identifier"}],"roleHeading":"Structure"},"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPCreativeType"},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"GFPCreativeType","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpcreativetype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gfpsdk\/gfpcreativetype"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/s10SetAlgebraP":{"title":"Swift.SetAlgebra","type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s10SetAlgebraP"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPCreativeType":{"kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPCreativeType","url":"\/documentation\/gfpsdk\/gfpcreativetype","abstract":[],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPCreativeType","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"GFPCreativeType"}],"role":"symbol","type":"topic","title":"GFPCreativeType"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPCreativeType/Equatable-Implementations":{"abstract":[],"url":"\/documentation\/gfpsdk\/gfpcreativetype\/equatable-implementations","role":"collectionGroup","title":"Equatable Implementations","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPCreativeType\/Equatable-Implementations","type":"topic","kind":"article"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPCreativeType/loudness":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"loudness","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GFPCreativeType","preciseIdentifier":"c:@E@GFPCreativeType"}],"abstract":[],"url":"\/documentation\/gfpsdk\/gfpcreativetype\/loudness","navigatorTitle":[{"kind":"identifier","text":"GFPCreativeLoudness"}],"kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPCreativeType\/loudness","type":"topic","title":"loudness","role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPCreativeType/SetAlgebra-Implementations":{"type":"topic","title":"SetAlgebra Implementations","kind":"article","url":"\/documentation\/gfpsdk\/gfpcreativetype\/setalgebra-implementations","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPCreativeType\/SetAlgebra-Implementations","role":"collectionGroup"},"doc://com.navercorp.da.gfp.GFPSDK/s9OptionSetP":{"title":"Swift.OptionSet","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s9OptionSetP","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/s8SendableP":{"title":"Swift.Sendable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s8SendableP","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPCreativeType/nonLinear":{"abstract":[],"url":"\/documentation\/gfpsdk\/gfpcreativetype\/nonlinear","role":"symbol","title":"nonLinear","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPCreativeType\/nonLinear","type":"topic","navigatorTitle":[{"text":"GFPCreativeNonLinear","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"nonLinear"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@GFPCreativeType","text":"GFPCreativeType","kind":"typeIdentifier"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPCreativeType/OptionSet-Implementations":{"title":"OptionSet Implementations","type":"topic","kind":"article","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPCreativeType\/OptionSet-Implementations","role":"collectionGroup","url":"\/documentation\/gfpsdk\/gfpcreativetype\/optionset-implementations","abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPCreativeType/GFPCreativeNone":{"fragments":[{"kind":"identifier","text":"GFPCreativeNone"}],"abstract":[],"url":"\/documentation\/gfpsdk\/gfpcreativetype\/gfpcreativenone","kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPCreativeType\/GFPCreativeNone","type":"topic","title":"GFPCreativeNone","role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/SY":{"title":"Swift.RawRepresentable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SY","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/s15BitwiseCopyableP":{"title":"Swift.BitwiseCopyable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s15BitwiseCopyableP","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPCreativeType/init(rawValue:)":{"title":"init(rawValue:)","role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPCreativeType\/init(rawValue:)","url":"\/documentation\/gfpsdk\/gfpcreativetype\/init(rawvalue:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":")","kind":"text"}],"abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/s25ExpressibleByArrayLiteralP":{"title":"Swift.ExpressibleByArrayLiteral","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s25ExpressibleByArrayLiteralP","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Enumeration","path":"\/metadata\/roleHeading"},{"op":"replace","value":"GFPCreativeType","path":"\/metadata\/title"},{"op":"replace","value":"enum","path":"\/metadata\/symbolKind"},{"value":[{"text":"GFPCreativeType","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"GFPCreativeType"}],"op":"replace"},{"path":"\/topicSections","op":"replace","value":[{"generated":true,"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPCreativeType\/GFPCreativeNone","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPCreativeType\/loudness","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPCreativeType\/nonLinear"],"title":"Enumeration Cases","anchor":"Enumeration-Cases"}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPCreativeType"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":";"}]}]},"op":"replace"},{"value":"GFPCreativeType","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPCreativeType\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPCreativeType\/fragments","op":"replace","value":[{"kind":"identifier","text":"GFPCreativeType"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPCreativeType\/navigatorTitle","value":[{"text":"GFPCreativeType","kind":"identifier"}],"op":"replace"},{"value":"GFPCreativeLoudness","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPCreativeType~1loudness\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPCreativeType~1loudness\/fragments","op":"replace","value":[{"kind":"identifier","text":"GFPCreativeLoudness"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPCreativeType~1nonLinear\/title","value":"GFPCreativeNonLinear","op":"replace"},{"value":[{"kind":"identifier","text":"GFPCreativeNonLinear"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPCreativeType~1nonLinear\/fragments","op":"replace"}]}]}