{"topicSections":[{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPClickLandingUtilDelegate\/didDissmissDefault(inAppBrowse:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPClickLandingUtilDelegate\/didPresentDefault(inAppBrowse:)"],"title":"Instance Methods","anchor":"Instance-Methods","generated":true}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPClickLandingUtilDelegate","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObjectProtocol","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"metadata":{"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPClickLandingUtilDelegate"}],"navigatorTitle":[{"text":"GFPClickLandingUtilDelegate","kind":"identifier"}],"symbolKind":"protocol","roleHeading":"Protocol","externalID":"c:objc(pl)GFPClickLandingUtilDelegate","title":"GFPClickLandingUtilDelegate","modules":[{"name":"GFPSDK"}]},"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject"]}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpclicklandingutildelegate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpclicklandingutildelegate"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPClickLandingUtilDelegate"},"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPClickLandingUtilDelegate/didPresentDefault(inAppBrowse:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didPresentDefault","kind":"identifier"},{"kind":"text","text":"("},{"text":"inAppBrowse","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"GFPClickLandingUtil","preciseIdentifier":"c:objc(cs)GFPClickLandingUtil","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[],"url":"\/documentation\/gfpsdk\/gfpclicklandingutildelegate\/didpresentdefault(inappbrowse:)","navigatorTitle":[{"kind":"identifier","text":"didPresentDefaultInAppBrowse:"}],"required":true,"kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPClickLandingUtilDelegate\/didPresentDefault(inAppBrowse:)","type":"topic","title":"didPresentDefault(inAppBrowse:)","role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPClickLandingUtilDelegate":{"navigatorTitle":[{"kind":"identifier","text":"GFPClickLandingUtilDelegate"}],"url":"\/documentation\/gfpsdk\/gfpclicklandingutildelegate","abstract":[],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPClickLandingUtilDelegate","kind":"identifier"}],"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPClickLandingUtilDelegate","title":"GFPClickLandingUtilDelegate"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)NSObject":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPClickLandingUtilDelegate/didDissmissDefault(inAppBrowse:)":{"required":true,"role":"symbol","abstract":[],"title":"didDissmissDefault(inAppBrowse:)","navigatorTitle":[{"text":"didDissmissDefaultInAppBrowse:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"didDissmissDefault","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"inAppBrowse"},{"text":": ","kind":"text"},{"text":"GFPClickLandingUtil","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPClickLandingUtil"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPClickLandingUtilDelegate\/didDissmissDefault(inAppBrowse:)","type":"topic","kind":"symbol","url":"\/documentation\/gfpsdk\/gfpclicklandingutildelegate\/diddissmissdefault(inappbrowse:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Protocol","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"GFPClickLandingUtilDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","value":[{"kind":"identifier","text":"GFPClickLandingUtilDelegate"}],"path":"\/metadata\/fragments"},{"value":[{"text":"GFPClickLandingUtilDelegate","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPClickLandingUtilDelegate\/didDissmissDefault(inAppBrowse:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPClickLandingUtilDelegate\/didPresentDefault(inAppBrowse:)"]}]},{"path":"\/relationshipsSections","op":"replace","value":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject"],"title":"Inherits From"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"text":"GFPClickLandingUtilDelegate","kind":"identifier"},{"text":" <","kind":"text"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(pl)NSObject"},{"text":">","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPClickLandingUtilDelegate~1didPresentDefault(inAppBrowse:)\/title","op":"replace","value":"didPresentDefaultInAppBrowse:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"didPresentDefaultInAppBrowse:"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPClickLandingUtilDelegate~1didPresentDefault(inAppBrowse:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPClickLandingUtilDelegate\/title","value":"GFPClickLandingUtilDelegate","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPClickLandingUtilDelegate\/fragments","value":[{"kind":"identifier","text":"GFPClickLandingUtilDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPClickLandingUtilDelegate\/navigatorTitle","value":[{"text":"GFPClickLandingUtilDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPClickLandingUtilDelegate~1didDissmissDefault(inAppBrowse:)\/title","value":"didDissmissDefaultInAppBrowse:"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPClickLandingUtilDelegate~1didDissmissDefault(inAppBrowse:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"didDissmissDefaultInAppBrowse:","kind":"identifier"}],"op":"replace"}]}]}