{"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject"],"type":"inheritsFrom"},{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s7CVarArgP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s23CustomStringConvertibleP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPContentInfo\/init(sourceType:subtype:sourceId:)"],"anchor":"Initializers","generated":true},{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPContentInfo\/dict","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPContentInfo\/isValid","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPContentInfo\/si","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPContentInfo\/sst","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPContentInfo\/st"],"anchor":"Instance-Properties","title":"Instance Properties","generated":true}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"metadata":{"modules":[{"name":"GFPSDK"}],"role":"symbol","title":"GFPContentInfo","externalID":"c:objc(cs)GFPContentInfo","roleHeading":"Class","symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPContentInfo","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"GFPContentInfo"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"GFPContentInfo","kind":"identifier"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpcontentinfo"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpcontentinfo"]}],"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPContentInfo","interfaceLanguage":"swift"},"sections":[],"references":{"doc://com.navercorp.da.gfp.GFPSDK/objc(cs)NSObject":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPContentInfo/dict":{"kind":"symbol","title":"dict","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPContentInfo\/dict","url":"\/documentation\/gfpsdk\/gfpcontentinfo\/dict","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"dict"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":" : ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"]?","kind":"text"}],"navigatorTitle":[{"text":"dict","kind":"identifier"}],"abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)NSObject":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPContentInfo":{"type":"topic","abstract":[],"kind":"symbol","navigatorTitle":[{"text":"GFPContentInfo","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPContentInfo","url":"\/documentation\/gfpsdk\/gfpcontentinfo","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPContentInfo","kind":"identifier"}],"title":"GFPContentInfo"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPContentInfo/init(sourceType:subtype:sourceId:)":{"type":"topic","title":"init(sourceType:subtype:sourceId:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"sourceType","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"subtype","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sourceId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"abstract":[],"url":"\/documentation\/gfpsdk\/gfpcontentinfo\/init(sourcetype:subtype:sourceid:)","kind":"symbol","navigatorTitle":[{"text":"initWithSourceType:subtype:sourceId:","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPContentInfo\/init(sourceType:subtype:sourceId:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPContentInfo/isValid":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isValid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"navigatorTitle":[{"text":"isValid","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPContentInfo\/isValid","abstract":[],"title":"isValid","type":"topic","url":"\/documentation\/gfpsdk\/gfpcontentinfo\/isvalid","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPContentInfo/si":{"role":"symbol","title":"si","url":"\/documentation\/gfpsdk\/gfpcontentinfo\/si","abstract":[{"type":"text","text":"Communication Ad - Source ID"}],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"si","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"si","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPContentInfo\/si","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPContentInfo/st":{"title":"st","abstract":[{"type":"text","text":"Communication Ad - Source Type"}],"role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"st"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"st"}],"url":"\/documentation\/gfpsdk\/gfpcontentinfo\/st","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPContentInfo\/st"},"doc://com.navercorp.da.gfp.GFPSDK/s7CVarArgP":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.navercorp.da.gfp.GFPSDK/SQ":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.navercorp.da.gfp.GFPSDK/SH":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.navercorp.da.gfp.GFPSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPContentInfo/sst":{"url":"\/documentation\/gfpsdk\/gfpcontentinfo\/sst","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sst"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPContentInfo\/sst","kind":"symbol","navigatorTitle":[{"text":"sst","kind":"identifier"}],"role":"symbol","title":"sst","type":"topic","abstract":[{"type":"text","text":"Communication Ad - Source Subtype"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"value":"GFPContentInfo","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"value":[{"text":"GFPContentInfo","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"GFPContentInfo"}]},{"op":"replace","value":[{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPContentInfo\/dict","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPContentInfo\/isValid","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPContentInfo\/si","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPContentInfo\/sst","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPContentInfo\/st"],"anchor":"Instance-Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPContentInfo\/init(sourceType:subtype:sourceId:)"],"anchor":"Instance-Methods","generated":true}],"path":"\/topicSections"},{"value":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject"]}],"op":"replace","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"GFPContentInfo","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPContentInfo~1dict\/title","value":"dict","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPContentInfo~1dict\/fragments","value":[{"text":"dict","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"GFPContentInfo","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPContentInfo\/title"},{"value":[{"kind":"identifier","text":"GFPContentInfo"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPContentInfo\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPContentInfo\/navigatorTitle","value":[{"text":"GFPContentInfo","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"initWithSourceType:subtype:sourceId:","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPContentInfo~1init(sourceType:subtype:sourceId:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPContentInfo~1init(sourceType:subtype:sourceId:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithSourceType:subtype:sourceId:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPContentInfo~1isValid\/title","value":"isValid","op":"replace"},{"value":[{"kind":"identifier","text":"isValid"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPContentInfo~1isValid\/fragments","op":"replace"},{"op":"replace","value":"si","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPContentInfo~1si\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPContentInfo~1si\/fragments","value":[{"text":"si","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPContentInfo~1st\/title","value":"st"},{"value":[{"kind":"identifier","text":"st"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPContentInfo~1st\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPContentInfo~1sst\/title","value":"sst","op":"replace"},{"value":[{"kind":"identifier","text":"sst"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPContentInfo~1sst\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}