{"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPProviding","doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject"],"kind":"relationships"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"GFPCombinedProviding","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"GFPProviding","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPProviding","preciseIdentifier":"c:objc(pl)GFPProviding"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPCombinedProviding","interfaceLanguage":"swift"},"sections":[],"metadata":{"symbolKind":"protocol","externalID":"c:objc(pl)GFPCombinedProviding","modules":[{"name":"GFPSDK"}],"navigatorTitle":[{"text":"GFPCombinedProviding","kind":"identifier"}],"title":"GFPCombinedProviding","roleHeading":"Protocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPCombinedProviding","kind":"identifier"}],"role":"symbol"},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/gfpsdk\/gfpcombinedproviding"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpcombinedproviding"]}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPProviding":{"title":"GFPProviding","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPProviding","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPProviding","kind":"identifier"}],"abstract":[],"navigatorTitle":[{"text":"GFPProviding","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpproviding","type":"topic","role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPCombinedProviding":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPCombinedProviding"}],"url":"\/documentation\/gfpsdk\/gfpcombinedproviding","title":"GFPCombinedProviding","abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPCombinedProviding","navigatorTitle":[{"text":"GFPCombinedProviding","kind":"identifier"}],"role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Protocol","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"GFPCombinedProviding"},{"value":"protocol","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GFPCombinedProviding"}],"op":"replace"},{"value":[{"text":"GFPCombinedProviding","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPProviding"],"type":"inheritsFrom"}]},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"text":" ","kind":"text"},{"text":"GFPCombinedProviding","kind":"identifier"},{"text":" <","kind":"text"},{"text":"GFPProviding","preciseIdentifier":"c:objc(pl)GFPProviding","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPProviding","kind":"typeIdentifier"},{"text":">","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPProviding\/title","value":"GFPProviding"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPProviding\/fragments","value":[{"text":"GFPProviding","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPProviding\/navigatorTitle","value":[{"text":"GFPProviding","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPCombinedProviding\/title","op":"replace","value":"GFPCombinedProviding"},{"value":[{"kind":"identifier","text":"GFPCombinedProviding"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPCombinedProviding\/fragments"},{"op":"replace","value":[{"text":"GFPCombinedProviding","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPCombinedProviding\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}