{"metadata":{"externalID":"c:@GFPErrorSubcodeIMAWrongRequest","role":"symbol","title":"GFPErrorSubcodeIMAWrongRequest","navigatorTitle":[{"kind":"identifier","text":"GFPErrorSubcodeIMAWrongRequest"}],"symbolKind":"var","roleHeading":"Global Variable","modules":[{"name":"GFPSDK"}],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPErrorSubcodeIMAWrongRequest"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"GFPErrorSubcodeIMAWrongRequest","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorSubcodeIMAWrongRequest"},"sections":[],"variants":[{"paths":["\/documentation\/gfpsdk\/gfperrorsubcodeimawrongrequest"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfperrorsubcodeimawrongrequest"]}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPErrorSubcodeIMAWrongRequest":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"GFPErrorSubcodeIMAWrongRequest","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"url":"\/documentation\/gfpsdk\/gfperrorsubcodeimawrongrequest","title":"GFPErrorSubcodeIMAWrongRequest","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorSubcodeIMAWrongRequest","type":"topic","kind":"symbol","navigatorTitle":[{"text":"GFPErrorSubcodeIMAWrongRequest","kind":"identifier"}],"role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Global Variable","op":"replace","path":"\/metadata\/roleHeading"},{"value":"GFPErrorSubcodeIMAWrongRequest","path":"\/metadata\/title","op":"replace"},{"value":"var","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"GFPErrorSubcodeIMAWrongRequest","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"extern"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"text":"GFPErrorSubcodeIMAWrongRequest","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"GFPErrorSubcodeIMAWrongRequest","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorSubcodeIMAWrongRequest\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorSubcodeIMAWrongRequest\/fragments","value":[{"kind":"identifier","text":"GFPErrorSubcodeIMAWrongRequest"}],"op":"replace"}]}]}