{"topicSections":[{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/bannerInvalidSize","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/bannerProviderLoadFailed","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/cancelInternal","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/initBannerProvider","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/initCombinedProvider","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/initNativeProvider","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/initProvider","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/initUnknownProvider","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/initVideoProvider","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/internal","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/interstitialAd","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/interstitialAdRendering","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/invalidAdParam","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/invalidAdSize","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/invalidAdUnit","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/invalidScheduleInValidParam","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/invalidScheduleParam","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/invalidScheduleUnit","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/jsTagInternal","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/load","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/mraidResizeAdSizeError","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/mraidSDKInternal","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/mraidUnloadCalled","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/nativeAdRendering","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/nativeImageLoadFailed","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/nativeProviderLoadFailed","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/nativeVideoLoadFailed","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/noFill","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/noValidProvider","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/paramInitInfo","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/parseAdList","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/parseInitInfo","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/parseScheduleList","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/renderingNotSupported","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/requestAdList","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/requestInitInfo","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/requestScheduleList","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/requestTimeout","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/rewardedAd","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/rewardedAdRendering","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/schedule","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/scheduleVideoLoadFailed","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/videoAdBreakWrongFormat","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/videoAdNotYetLoaded","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/videoAdStartFailed","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/videoBufferingTimeout","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/videoLoudnessWrongFormat","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/videoNonLinearWrongFormat","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/videoProviderLoadFailed","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/videoStartTimeout","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/videoVastEmpty","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/videoVastWrongFormat","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/wrongCommand","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/wrongFormatAdList","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/wrongFormatInitInfo"],"generated":true,"anchor":"Enumeration-Cases","title":"Enumeration Cases"},{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/init(rawValue:)"],"anchor":"Initializers","generated":true,"title":"Initializers"},{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/Equatable-Implementations","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/RawRepresentable-Implementations"],"generated":true,"title":"Default Implementations","anchor":"Default-Implementations"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"relationshipsSections":[{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/s15BitwiseCopyableP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SY","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s8SendableP"],"title":"Conforms To","type":"conformsTo","kind":"relationships"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPErrorCode"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfperrorcode"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfperrorcode"]}],"sections":[],"metadata":{"symbolKind":"enum","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPErrorCode","kind":"identifier"}],"title":"GFPErrorCode","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPErrorCode"}],"externalID":"c:@E@GFPErrorCode","roleHeading":"Enumeration","modules":[{"name":"GFPSDK"}]},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPErrorCode/parseScheduleList":{"url":"\/documentation\/gfpsdk\/gfperrorcode\/parseschedulelist","title":"GFPErrorCode.parseScheduleList","abstract":[],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"parseScheduleList","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/parseScheduleList","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GFPErrorParseScheduleList"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPErrorCode/wrongFormatInitInfo":{"navigatorTitle":[{"text":"GFPErrorWrongFormatInitInfo","kind":"identifier"}],"type":"topic","title":"GFPErrorCode.wrongFormatInitInfo","kind":"symbol","url":"\/documentation\/gfpsdk\/gfperrorcode\/wrongformatinitinfo","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/wrongFormatInitInfo","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"wrongFormatInitInfo","kind":"identifier"}],"role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPErrorCode/initNativeProvider":{"url":"\/documentation\/gfpsdk\/gfperrorcode\/initnativeprovider","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/initNativeProvider","navigatorTitle":[{"text":"GFPErrorInitNativeProvider","kind":"identifier"}],"kind":"symbol","title":"GFPErrorCode.initNativeProvider","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"initNativeProvider","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPErrorCode/nativeProviderLoadFailed":{"abstract":[],"url":"\/documentation\/gfpsdk\/gfperrorcode\/nativeproviderloadfailed","navigatorTitle":[{"kind":"identifier","text":"GFPErrorNativeProviderLoadFailed"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/nativeProviderLoadFailed","title":"GFPErrorCode.nativeProviderLoadFailed","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"nativeProviderLoadFailed"}],"kind":"symbol","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPErrorCode/requestAdList":{"kind":"symbol","url":"\/documentation\/gfpsdk\/gfperrorcode\/requestadlist","navigatorTitle":[{"text":"GFPErrorRequestAdList","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/requestAdList","title":"GFPErrorCode.requestAdList","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"requestAdList","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPErrorCode/rewardedAd":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/rewardedAd","abstract":[],"kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"rewardedAd"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"GFPErrorRewardedAd"}],"title":"GFPErrorCode.rewardedAd","url":"\/documentation\/gfpsdk\/gfperrorcode\/rewardedad"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","title":"Swift.Equatable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPErrorCode/interstitialAdRendering":{"url":"\/documentation\/gfpsdk\/gfperrorcode\/interstitialadrendering","role":"symbol","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"interstitialAdRendering"}],"title":"GFPErrorCode.interstitialAdRendering","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/interstitialAdRendering","navigatorTitle":[{"text":"GFPErrorInterstitialAdRendering","kind":"identifier"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPErrorCode/noFill":{"url":"\/documentation\/gfpsdk\/gfperrorcode\/nofill","title":"GFPErrorCode.noFill","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/noFill","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPErrorNoFill"}],"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"noFill"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPErrorCode/interstitialAd":{"url":"\/documentation\/gfpsdk\/gfperrorcode\/interstitialad","title":"GFPErrorCode.interstitialAd","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"interstitialAd"}],"type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/interstitialAd","navigatorTitle":[{"kind":"identifier","text":"GFPErrorInterstitialAd"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPErrorCode/nativeImageLoadFailed":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"nativeImageLoadFailed","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"GFPErrorNativeImageLoadFailed"}],"url":"\/documentation\/gfpsdk\/gfperrorcode\/nativeimageloadfailed","abstract":[],"kind":"symbol","role":"symbol","title":"GFPErrorCode.nativeImageLoadFailed","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/nativeImageLoadFailed","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPErrorCode/invalidScheduleUnit":{"url":"\/documentation\/gfpsdk\/gfperrorcode\/invalidscheduleunit","kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/invalidScheduleUnit","title":"GFPErrorCode.invalidScheduleUnit","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"invalidScheduleUnit","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"GFPErrorInvalidScheduleUnit"}],"abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPErrorCode/initProvider":{"role":"symbol","url":"\/documentation\/gfpsdk\/gfperrorcode\/initprovider","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/initProvider","abstract":[],"title":"GFPErrorCode.initProvider","navigatorTitle":[{"kind":"identifier","text":"GFPErrorInitProvider"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"initProvider"}],"type":"topic","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPErrorCode/invalidScheduleParam":{"title":"GFPErrorCode.invalidScheduleParam","url":"\/documentation\/gfpsdk\/gfperrorcode\/invalidscheduleparam","abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalidScheduleParam","kind":"identifier"}],"navigatorTitle":[{"text":"GFPErrorInvalidScheduleParam","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/invalidScheduleParam","type":"topic","role":"symbol","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH","title":"Swift.Hashable"},"doc://com.navercorp.da.gfp.GFPSDK/SY":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SY","title":"Swift.RawRepresentable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPErrorCode/initVideoProvider":{"type":"topic","url":"\/documentation\/gfpsdk\/gfperrorcode\/initvideoprovider","title":"GFPErrorCode.initVideoProvider","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"initVideoProvider"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPErrorInitVideoProvider"}],"kind":"symbol","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/initVideoProvider"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPErrorCode/invalidAdUnit":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"invalidAdUnit"}],"kind":"symbol","navigatorTitle":[{"text":"GFPErrorInvalidAdUnit","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/invalidAdUnit","abstract":[],"role":"symbol","url":"\/documentation\/gfpsdk\/gfperrorcode\/invalidadunit","title":"GFPErrorCode.invalidAdUnit","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPErrorCode/schedule":{"navigatorTitle":[{"text":"GFPErrorSchedule","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfperrorcode\/schedule","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"schedule","kind":"identifier"}],"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/schedule","title":"GFPErrorCode.schedule"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPErrorCode/videoNonLinearWrongFormat":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"videoNonLinearWrongFormat","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"GFPErrorVideoNonLinearWrongFormat"}],"url":"\/documentation\/gfpsdk\/gfperrorcode\/videononlinearwrongformat","abstract":[],"kind":"symbol","role":"symbol","title":"GFPErrorCode.videoNonLinearWrongFormat","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/videoNonLinearWrongFormat","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPErrorCode/requestInitInfo":{"url":"\/documentation\/gfpsdk\/gfperrorcode\/requestinitinfo","kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/requestInitInfo","title":"GFPErrorCode.requestInitInfo","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"requestInitInfo","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"GFPErrorRequestInitInfo"}],"abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPErrorCode/invalidScheduleInValidParam":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"invalidScheduleInValidParam","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"GFPErrorInvalidScheduleInValidParam"}],"url":"\/documentation\/gfpsdk\/gfperrorcode\/invalidscheduleinvalidparam","abstract":[],"kind":"symbol","role":"symbol","title":"GFPErrorCode.invalidScheduleInValidParam","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/invalidScheduleInValidParam","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPErrorCode/parseInitInfo":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/parseInitInfo","kind":"symbol","type":"topic","title":"GFPErrorCode.parseInitInfo","url":"\/documentation\/gfpsdk\/gfperrorcode\/parseinitinfo","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"parseInitInfo"}],"navigatorTitle":[{"text":"GFPErrorParseInitInfo","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPErrorCode/videoAdStartFailed":{"url":"\/documentation\/gfpsdk\/gfperrorcode\/videoadstartfailed","kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/videoAdStartFailed","title":"GFPErrorCode.videoAdStartFailed","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"videoAdStartFailed","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"GFPErrorVideoAdStartFailed"}],"abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPErrorCode/initBannerProvider":{"type":"topic","url":"\/documentation\/gfpsdk\/gfperrorcode\/initbannerprovider","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"initBannerProvider","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/initBannerProvider","title":"GFPErrorCode.initBannerProvider","navigatorTitle":[{"kind":"identifier","text":"GFPErrorInitBannerProvider"}],"abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPErrorCode/renderingNotSupported":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/renderingNotSupported","kind":"symbol","title":"GFPErrorCode.renderingNotSupported","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPErrorRenderingNotSupported"}],"url":"\/documentation\/gfpsdk\/gfperrorcode\/renderingnotsupported","abstract":[],"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"renderingNotSupported","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/s8SendableP":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s8SendableP","title":"Swift.Sendable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPErrorCode/init(rawValue:)":{"url":"\/documentation\/gfpsdk\/gfperrorcode\/init(rawvalue:)","kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/init(rawValue:)","title":"init(rawValue:)","role":"symbol","type":"topic","fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"kind":"text","text":")"}],"abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPErrorCode/requestScheduleList":{"navigatorTitle":[{"text":"GFPErrorRequestScheduleList","kind":"identifier"}],"type":"topic","title":"GFPErrorCode.requestScheduleList","kind":"symbol","url":"\/documentation\/gfpsdk\/gfperrorcode\/requestschedulelist","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/requestScheduleList","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestScheduleList"}],"role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPErrorCode/mraidResizeAdSizeError":{"navigatorTitle":[{"text":"GFPErrorMraidResizeAdSizeError","kind":"identifier"}],"role":"symbol","title":"GFPErrorCode.mraidResizeAdSizeError","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"mraidResizeAdSizeError","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/mraidResizeAdSizeError","abstract":[],"url":"\/documentation\/gfpsdk\/gfperrorcode\/mraidresizeadsizeerror"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPErrorCode/videoLoudnessWrongFormat":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"videoLoudnessWrongFormat"}],"navigatorTitle":[{"text":"GFPErrorVideoLoudnessWrongFormat","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfperrorcode\/videoloudnesswrongformat","abstract":[],"kind":"symbol","role":"symbol","title":"GFPErrorCode.videoLoudnessWrongFormat","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/videoLoudnessWrongFormat","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPErrorCode/mraidSDKInternal":{"abstract":[],"url":"\/documentation\/gfpsdk\/gfperrorcode\/mraidsdkinternal","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPErrorMraidSDKInternal"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"mraidSDKInternal","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/mraidSDKInternal","kind":"symbol","title":"GFPErrorCode.mraidSDKInternal","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPErrorCode/noValidProvider":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"noValidProvider"}],"navigatorTitle":[{"kind":"identifier","text":"GFPErrorNoValidProvider"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/noValidProvider","url":"\/documentation\/gfpsdk\/gfperrorcode\/novalidprovider","kind":"symbol","role":"symbol","abstract":[],"title":"GFPErrorCode.noValidProvider","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPErrorCode/rewardedAdRendering":{"type":"topic","navigatorTitle":[{"text":"GFPErrorRewardedAdRendering","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/gfpsdk\/gfperrorcode\/rewardedadrendering","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"rewardedAdRendering","kind":"identifier"}],"title":"GFPErrorCode.rewardedAdRendering","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/rewardedAdRendering"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPErrorCode/internal":{"role":"symbol","abstract":[],"title":"GFPErrorCode.internal","navigatorTitle":[{"kind":"identifier","text":"GFPErrorInternal"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"`internal`","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/internal","type":"topic","kind":"symbol","url":"\/documentation\/gfpsdk\/gfperrorcode\/internal"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPErrorCode/videoProviderLoadFailed":{"url":"\/documentation\/gfpsdk\/gfperrorcode\/videoproviderloadfailed","kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/videoProviderLoadFailed","title":"GFPErrorCode.videoProviderLoadFailed","role":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"videoProviderLoadFailed","kind":"identifier"}],"navigatorTitle":[{"text":"GFPErrorVideoProviderLoadFailed","kind":"identifier"}],"abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPErrorCode/invalidAdSize":{"abstract":[],"url":"\/documentation\/gfpsdk\/gfperrorcode\/invalidadsize","role":"symbol","title":"GFPErrorCode.invalidAdSize","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/invalidAdSize","type":"topic","navigatorTitle":[{"text":"GFPErrorInvalidAdSize","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"invalidAdSize","kind":"identifier"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPErrorCode/nativeVideoLoadFailed":{"kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/nativeVideoLoadFailed","url":"\/documentation\/gfpsdk\/gfperrorcode\/nativevideoloadfailed","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"nativeVideoLoadFailed"}],"title":"GFPErrorCode.nativeVideoLoadFailed","role":"symbol","type":"topic","navigatorTitle":[{"text":"GFPErrorNativeVideoLoadFailed","kind":"identifier"}],"abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPErrorCode":{"abstract":[],"url":"\/documentation\/gfpsdk\/gfperrorcode","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode","role":"symbol","title":"GFPErrorCode","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPErrorCode","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"GFPErrorCode"}],"kind":"symbol","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPErrorCode/nativeAdRendering":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"nativeAdRendering","kind":"identifier"}],"navigatorTitle":[{"text":"GFPErrorNativeAdRendering","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfperrorcode\/nativeadrendering","abstract":[],"kind":"symbol","role":"symbol","title":"GFPErrorCode.nativeAdRendering","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/nativeAdRendering"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPErrorCode/initCombinedProvider":{"navigatorTitle":[{"text":"GFPErrorInitCombinedProvider","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfperrorcode\/initcombinedprovider","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"initCombinedProvider","kind":"identifier"}],"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/initCombinedProvider","title":"GFPErrorCode.initCombinedProvider"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPErrorCode/paramInitInfo":{"title":"GFPErrorCode.paramInitInfo","navigatorTitle":[{"kind":"identifier","text":"GFPErrorParamInitInfo"}],"url":"\/documentation\/gfpsdk\/gfperrorcode\/paraminitinfo","role":"symbol","kind":"symbol","abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"paramInitInfo","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/paramInitInfo","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPErrorCode/videoBufferingTimeout":{"navigatorTitle":[{"text":"GFPErrorVideoBufferingTimeout","kind":"identifier"}],"title":"GFPErrorCode.videoBufferingTimeout","url":"\/documentation\/gfpsdk\/gfperrorcode\/videobufferingtimeout","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/videoBufferingTimeout","role":"symbol","type":"topic","kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoBufferingTimeout"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPErrorCode/invalidAdParam":{"title":"GFPErrorCode.invalidAdParam","role":"symbol","abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"invalidAdParam","kind":"identifier"}],"navigatorTitle":[{"text":"GFPErrorInvalidAdParam","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/invalidAdParam","type":"topic","kind":"symbol","url":"\/documentation\/gfpsdk\/gfperrorcode\/invalidadparam"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPErrorCode/Equatable-Implementations":{"abstract":[],"url":"\/documentation\/gfpsdk\/gfperrorcode\/equatable-implementations","role":"collectionGroup","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/Equatable-Implementations","kind":"article","title":"Equatable Implementations","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPErrorCode/videoAdBreakWrongFormat":{"type":"topic","title":"GFPErrorCode.videoAdBreakWrongFormat","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoAdBreakWrongFormat"}],"abstract":[],"url":"\/documentation\/gfpsdk\/gfperrorcode\/videoadbreakwrongformat","kind":"symbol","navigatorTitle":[{"text":"GFPErrorVideoAdBreakWrongFormat","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/videoAdBreakWrongFormat"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPErrorCode/requestTimeout":{"kind":"symbol","title":"GFPErrorCode.requestTimeout","url":"\/documentation\/gfpsdk\/gfperrorcode\/requesttimeout","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"requestTimeout","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/requestTimeout","navigatorTitle":[{"text":"GFPErrorRequestTimeout","kind":"identifier"}],"abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPErrorCode/jsTagInternal":{"abstract":[],"type":"topic","title":"GFPErrorCode.jsTagInternal","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"jsTagInternal","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfperrorcode\/jstaginternal","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/jsTagInternal","navigatorTitle":[{"kind":"identifier","text":"GFPErrorJSTagInternal"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPErrorCode/cancelInternal":{"navigatorTitle":[{"kind":"identifier","text":"GFPErrorCancelInternal"}],"title":"GFPErrorCode.cancelInternal","url":"\/documentation\/gfpsdk\/gfperrorcode\/cancelinternal","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/cancelInternal","role":"symbol","type":"topic","kind":"symbol","abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancelInternal"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPErrorCode/load":{"type":"topic","title":"GFPErrorCode.load","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"load","kind":"identifier"}],"abstract":[],"url":"\/documentation\/gfpsdk\/gfperrorcode\/load","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPErrorLoad"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/load"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPErrorCode/bannerProviderLoadFailed":{"navigatorTitle":[{"text":"GFPErrorBannerProviderLoadFailed","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfperrorcode\/bannerproviderloadfailed","abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bannerProviderLoadFailed","kind":"identifier"}],"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/bannerProviderLoadFailed","title":"GFPErrorCode.bannerProviderLoadFailed"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPErrorCode/scheduleVideoLoadFailed":{"kind":"symbol","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/scheduleVideoLoadFailed","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"scheduleVideoLoadFailed","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"GFPErrorScheduleVideoLoadFailed","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfperrorcode\/schedulevideoloadfailed","title":"GFPErrorCode.scheduleVideoLoadFailed"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPErrorCode/parseAdList":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/parseAdList","abstract":[],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"parseAdList","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"GFPErrorParseAdList"}],"url":"\/documentation\/gfpsdk\/gfperrorcode\/parseadlist","type":"topic","kind":"symbol","title":"GFPErrorCode.parseAdList"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPErrorCode/videoVastEmpty":{"navigatorTitle":[{"kind":"identifier","text":"GFPErrorVideoVastEmpty"}],"title":"GFPErrorCode.videoVastEmpty","url":"\/documentation\/gfpsdk\/gfperrorcode\/videovastempty","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/videoVastEmpty","role":"symbol","type":"topic","kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"videoVastEmpty"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPErrorCode/wrongCommand":{"type":"topic","title":"GFPErrorCode.wrongCommand","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"wrongCommand"}],"abstract":[],"url":"\/documentation\/gfpsdk\/gfperrorcode\/wrongcommand","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPErrorWrongCommand"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/wrongCommand"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPErrorCode/videoAdNotYetLoaded":{"navigatorTitle":[{"kind":"identifier","text":"GFPErrorVideoAdNotYetLoaded"}],"title":"GFPErrorCode.videoAdNotYetLoaded","url":"\/documentation\/gfpsdk\/gfperrorcode\/videoadnotyetloaded","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/videoAdNotYetLoaded","role":"symbol","type":"topic","kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"videoAdNotYetLoaded","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPErrorCode/initUnknownProvider":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/initUnknownProvider","type":"topic","title":"GFPErrorCode.initUnknownProvider","url":"\/documentation\/gfpsdk\/gfperrorcode\/initunknownprovider","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"initUnknownProvider","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"GFPErrorInitUnknownProvider"}],"kind":"symbol","abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPErrorCode/videoVastWrongFormat":{"title":"GFPErrorCode.videoVastWrongFormat","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/videoVastWrongFormat","role":"symbol","kind":"symbol","abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"videoVastWrongFormat"}],"navigatorTitle":[{"kind":"identifier","text":"GFPErrorVideoVastWrongFormat"}],"type":"topic","url":"\/documentation\/gfpsdk\/gfperrorcode\/videovastwrongformat"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPErrorCode/RawRepresentable-Implementations":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/RawRepresentable-Implementations","title":"RawRepresentable Implementations","abstract":[],"url":"\/documentation\/gfpsdk\/gfperrorcode\/rawrepresentable-implementations","role":"collectionGroup","kind":"article","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/s15BitwiseCopyableP":{"type":"unresolvable","title":"Swift.BitwiseCopyable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s15BitwiseCopyableP"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPErrorCode/wrongFormatAdList":{"type":"topic","title":"GFPErrorCode.wrongFormatAdList","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"wrongFormatAdList"}],"abstract":[],"url":"\/documentation\/gfpsdk\/gfperrorcode\/wrongformatadlist","kind":"symbol","navigatorTitle":[{"text":"GFPErrorWrongFormatAdList","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/wrongFormatAdList"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPErrorCode/videoStartTimeout":{"abstract":[],"url":"\/documentation\/gfpsdk\/gfperrorcode\/videostarttimeout","role":"symbol","title":"GFPErrorCode.videoStartTimeout","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/videoStartTimeout","navigatorTitle":[{"text":"GFPErrorVideoStartTimeout","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"videoStartTimeout","kind":"identifier"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPErrorCode/mraidUnloadCalled":{"url":"\/documentation\/gfpsdk\/gfperrorcode\/mraidunloadcalled","abstract":[],"title":"GFPErrorCode.mraidUnloadCalled","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/mraidUnloadCalled","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"GFPErrorMraidUnloadCalled","kind":"identifier"}],"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"mraidUnloadCalled","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPErrorCode/bannerInvalidSize":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"bannerInvalidSize","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfperrorcode\/bannerinvalidsize","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/bannerInvalidSize","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPErrorBannerInvalidSize"}],"title":"GFPErrorCode.bannerInvalidSize"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration"},{"path":"\/metadata\/title","value":"GFPErrorCode","op":"replace"},{"op":"replace","value":"enum","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"GFPErrorCode","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"GFPErrorCode","kind":"identifier"}]},{"value":[{"generated":true,"title":"Enumeration Cases","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/bannerInvalidSize","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/bannerProviderLoadFailed","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/cancelInternal","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/initBannerProvider","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/initCombinedProvider","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/initNativeProvider","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/initProvider","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/initUnknownProvider","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/initVideoProvider","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/internal","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/interstitialAd","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/interstitialAdRendering","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/invalidAdParam","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/invalidAdSize","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/invalidAdUnit","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/invalidScheduleInValidParam","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/invalidScheduleParam","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/invalidScheduleUnit","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/jsTagInternal","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/load","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/mraidResizeAdSizeError","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/mraidSDKInternal","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/mraidUnloadCalled","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/nativeAdRendering","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/nativeImageLoadFailed","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/nativeProviderLoadFailed","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/nativeVideoLoadFailed","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/noFill","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/noValidProvider","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/paramInitInfo","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/parseAdList","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/parseInitInfo","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/parseScheduleList","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/renderingNotSupported","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/requestAdList","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/requestInitInfo","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/requestScheduleList","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/requestTimeout","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/rewardedAd","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/rewardedAdRendering","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/schedule","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/scheduleVideoLoadFailed","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/videoAdBreakWrongFormat","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/videoAdNotYetLoaded","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/videoAdStartFailed","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/videoBufferingTimeout","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/videoLoudnessWrongFormat","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/videoNonLinearWrongFormat","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/videoProviderLoadFailed","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/videoStartTimeout","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/videoVastEmpty","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/videoVastWrongFormat","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/wrongCommand","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/wrongFormatAdList","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/wrongFormatInitInfo"],"anchor":"Enumeration-Cases"}],"op":"replace","path":"\/topicSections"},{"op":"replace","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPErrorCode"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1parseScheduleList\/title","value":"GFPErrorParseScheduleList"},{"op":"replace","value":[{"text":"GFPErrorParseScheduleList","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1parseScheduleList\/fragments"},{"value":"GFPErrorWrongFormatInitInfo","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1wrongFormatInitInfo\/title"},{"value":[{"kind":"identifier","text":"GFPErrorWrongFormatInitInfo"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1wrongFormatInitInfo\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1initNativeProvider\/title","value":"GFPErrorInitNativeProvider"},{"op":"replace","value":[{"kind":"identifier","text":"GFPErrorInitNativeProvider"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1initNativeProvider\/fragments"},{"value":"GFPErrorNativeProviderLoadFailed","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1nativeProviderLoadFailed\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1nativeProviderLoadFailed\/fragments","value":[{"text":"GFPErrorNativeProviderLoadFailed","kind":"identifier"}]},{"op":"replace","value":"GFPErrorRequestAdList","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1requestAdList\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1requestAdList\/fragments","value":[{"text":"GFPErrorRequestAdList","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1rewardedAd\/title","value":"GFPErrorRewardedAd"},{"value":[{"kind":"identifier","text":"GFPErrorRewardedAd"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1rewardedAd\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1interstitialAdRendering\/title","value":"GFPErrorInterstitialAdRendering"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1interstitialAdRendering\/fragments","value":[{"text":"GFPErrorInterstitialAdRendering","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1noFill\/title","value":"GFPErrorNoFill"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1noFill\/fragments","op":"replace","value":[{"kind":"identifier","text":"GFPErrorNoFill"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1interstitialAd\/title","value":"GFPErrorInterstitialAd"},{"value":[{"text":"GFPErrorInterstitialAd","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1interstitialAd\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1nativeImageLoadFailed\/title","op":"replace","value":"GFPErrorNativeImageLoadFailed"},{"op":"replace","value":[{"text":"GFPErrorNativeImageLoadFailed","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1nativeImageLoadFailed\/fragments"},{"value":"GFPErrorInvalidScheduleUnit","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1invalidScheduleUnit\/title","op":"replace"},{"value":[{"text":"GFPErrorInvalidScheduleUnit","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1invalidScheduleUnit\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1initProvider\/title","op":"replace","value":"GFPErrorInitProvider"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1initProvider\/fragments","value":[{"text":"GFPErrorInitProvider","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1invalidScheduleParam\/title","value":"GFPErrorInvalidScheduleParam"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1invalidScheduleParam\/fragments","value":[{"text":"GFPErrorInvalidScheduleParam","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1initVideoProvider\/title","op":"replace","value":"GFPErrorInitVideoProvider"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1initVideoProvider\/fragments","value":[{"text":"GFPErrorInitVideoProvider","kind":"identifier"}],"op":"replace"},{"value":"GFPErrorInvalidAdUnit","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1invalidAdUnit\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1invalidAdUnit\/fragments","value":[{"text":"GFPErrorInvalidAdUnit","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1schedule\/title","value":"GFPErrorSchedule"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1schedule\/fragments","value":[{"text":"GFPErrorSchedule","kind":"identifier"}]},{"value":"GFPErrorVideoNonLinearWrongFormat","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1videoNonLinearWrongFormat\/title"},{"value":[{"text":"GFPErrorVideoNonLinearWrongFormat","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1videoNonLinearWrongFormat\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1requestInitInfo\/title","value":"GFPErrorRequestInitInfo","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1requestInitInfo\/fragments","op":"replace","value":[{"text":"GFPErrorRequestInitInfo","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1invalidScheduleInValidParam\/title","value":"GFPErrorInvalidScheduleInValidParam"},{"op":"replace","value":[{"kind":"identifier","text":"GFPErrorInvalidScheduleInValidParam"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1invalidScheduleInValidParam\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1parseInitInfo\/title","value":"GFPErrorParseInitInfo","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1parseInitInfo\/fragments","value":[{"kind":"identifier","text":"GFPErrorParseInitInfo"}]},{"value":"GFPErrorVideoAdStartFailed","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1videoAdStartFailed\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1videoAdStartFailed\/fragments","value":[{"text":"GFPErrorVideoAdStartFailed","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1initBannerProvider\/title","value":"GFPErrorInitBannerProvider"},{"value":[{"kind":"identifier","text":"GFPErrorInitBannerProvider"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1initBannerProvider\/fragments"},{"op":"replace","value":"GFPErrorRenderingNotSupported","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1renderingNotSupported\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1renderingNotSupported\/fragments","value":[{"kind":"identifier","text":"GFPErrorRenderingNotSupported"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1requestScheduleList\/title","value":"GFPErrorRequestScheduleList","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1requestScheduleList\/fragments","value":[{"text":"GFPErrorRequestScheduleList","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1mraidResizeAdSizeError\/title","value":"GFPErrorMraidResizeAdSizeError"},{"op":"replace","value":[{"text":"GFPErrorMraidResizeAdSizeError","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1mraidResizeAdSizeError\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1videoLoudnessWrongFormat\/title","op":"replace","value":"GFPErrorVideoLoudnessWrongFormat"},{"value":[{"text":"GFPErrorVideoLoudnessWrongFormat","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1videoLoudnessWrongFormat\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1mraidSDKInternal\/title","value":"GFPErrorMraidSDKInternal","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1mraidSDKInternal\/fragments","value":[{"kind":"identifier","text":"GFPErrorMraidSDKInternal"}],"op":"replace"},{"op":"replace","value":"GFPErrorNoValidProvider","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1noValidProvider\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1noValidProvider\/fragments","value":[{"kind":"identifier","text":"GFPErrorNoValidProvider"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1rewardedAdRendering\/title","op":"replace","value":"GFPErrorRewardedAdRendering"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1rewardedAdRendering\/fragments","op":"replace","value":[{"kind":"identifier","text":"GFPErrorRewardedAdRendering"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1internal\/title","value":"GFPErrorInternal","op":"replace"},{"value":[{"kind":"identifier","text":"GFPErrorInternal"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1internal\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1videoProviderLoadFailed\/title","op":"replace","value":"GFPErrorVideoProviderLoadFailed"},{"value":[{"text":"GFPErrorVideoProviderLoadFailed","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1videoProviderLoadFailed\/fragments"},{"value":"GFPErrorInvalidAdSize","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1invalidAdSize\/title"},{"value":[{"text":"GFPErrorInvalidAdSize","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1invalidAdSize\/fragments"},{"value":"GFPErrorNativeVideoLoadFailed","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1nativeVideoLoadFailed\/title","op":"replace"},{"value":[{"kind":"identifier","text":"GFPErrorNativeVideoLoadFailed"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1nativeVideoLoadFailed\/fragments"},{"op":"replace","value":"GFPErrorCode","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode\/fragments","value":[{"text":"GFPErrorCode","kind":"identifier"}]},{"value":[{"text":"GFPErrorCode","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1nativeAdRendering\/title","op":"replace","value":"GFPErrorNativeAdRendering"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1nativeAdRendering\/fragments","value":[{"kind":"identifier","text":"GFPErrorNativeAdRendering"}]},{"value":"GFPErrorInitCombinedProvider","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1initCombinedProvider\/title"},{"value":[{"kind":"identifier","text":"GFPErrorInitCombinedProvider"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1initCombinedProvider\/fragments","op":"replace"},{"op":"replace","value":"GFPErrorParamInitInfo","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1paramInitInfo\/title"},{"value":[{"text":"GFPErrorParamInitInfo","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1paramInitInfo\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1videoBufferingTimeout\/title","value":"GFPErrorVideoBufferingTimeout","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1videoBufferingTimeout\/fragments","value":[{"text":"GFPErrorVideoBufferingTimeout","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1invalidAdParam\/title","value":"GFPErrorInvalidAdParam","op":"replace"},{"value":[{"kind":"identifier","text":"GFPErrorInvalidAdParam"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1invalidAdParam\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1videoAdBreakWrongFormat\/title","value":"GFPErrorVideoAdBreakWrongFormat"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1videoAdBreakWrongFormat\/fragments","value":[{"kind":"identifier","text":"GFPErrorVideoAdBreakWrongFormat"}]},{"op":"replace","value":"GFPErrorRequestTimeout","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1requestTimeout\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1requestTimeout\/fragments","value":[{"kind":"identifier","text":"GFPErrorRequestTimeout"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1jsTagInternal\/title","value":"GFPErrorJSTagInternal","op":"replace"},{"op":"replace","value":[{"text":"GFPErrorJSTagInternal","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1jsTagInternal\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1cancelInternal\/title","op":"replace","value":"GFPErrorCancelInternal"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1cancelInternal\/fragments","value":[{"kind":"identifier","text":"GFPErrorCancelInternal"}]},{"op":"replace","value":"GFPErrorLoad","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1load\/title"},{"value":[{"text":"GFPErrorLoad","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1load\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1bannerProviderLoadFailed\/title","value":"GFPErrorBannerProviderLoadFailed"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1bannerProviderLoadFailed\/fragments","value":[{"text":"GFPErrorBannerProviderLoadFailed","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1scheduleVideoLoadFailed\/title","op":"replace","value":"GFPErrorScheduleVideoLoadFailed"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1scheduleVideoLoadFailed\/fragments","value":[{"kind":"identifier","text":"GFPErrorScheduleVideoLoadFailed"}]},{"op":"replace","value":"GFPErrorParseAdList","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1parseAdList\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1parseAdList\/fragments","op":"replace","value":[{"text":"GFPErrorParseAdList","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1videoVastEmpty\/title","value":"GFPErrorVideoVastEmpty"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1videoVastEmpty\/fragments","op":"replace","value":[{"text":"GFPErrorVideoVastEmpty","kind":"identifier"}]},{"value":"GFPErrorWrongCommand","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1wrongCommand\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1wrongCommand\/fragments","value":[{"text":"GFPErrorWrongCommand","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1videoAdNotYetLoaded\/title","value":"GFPErrorVideoAdNotYetLoaded"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1videoAdNotYetLoaded\/fragments","value":[{"kind":"identifier","text":"GFPErrorVideoAdNotYetLoaded"}]},{"value":"GFPErrorInitUnknownProvider","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1initUnknownProvider\/title"},{"op":"replace","value":[{"kind":"identifier","text":"GFPErrorInitUnknownProvider"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1initUnknownProvider\/fragments"},{"op":"replace","value":"GFPErrorVideoVastWrongFormat","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1videoVastWrongFormat\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1videoVastWrongFormat\/fragments","value":[{"kind":"identifier","text":"GFPErrorVideoVastWrongFormat"}]},{"value":"GFPErrorWrongFormatAdList","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1wrongFormatAdList\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1wrongFormatAdList\/fragments","value":[{"kind":"identifier","text":"GFPErrorWrongFormatAdList"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1videoStartTimeout\/title","op":"replace","value":"GFPErrorVideoStartTimeout"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1videoStartTimeout\/fragments","op":"replace","value":[{"kind":"identifier","text":"GFPErrorVideoStartTimeout"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1mraidUnloadCalled\/title","value":"GFPErrorMraidUnloadCalled"},{"value":[{"text":"GFPErrorMraidUnloadCalled","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1mraidUnloadCalled\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1bannerInvalidSize\/title","value":"GFPErrorBannerInvalidSize"},{"value":[{"text":"GFPErrorBannerInvalidSize","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1bannerInvalidSize\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}