{"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorSubcodeIMANoFillWithAdRule"},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPErrorSubcodeIMANoFillWithAdRule"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/gfpsdk\/gfperrorsubcodeimanofillwithadrule"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfperrorsubcodeimanofillwithadrule"]}],"sections":[],"metadata":{"roleHeading":"Global Variable","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPErrorSubcodeIMANoFillWithAdRule"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"symbolKind":"var","title":"GFPErrorSubcodeIMANoFillWithAdRule","externalID":"c:@GFPErrorSubcodeIMANoFillWithAdRule","navigatorTitle":[{"text":"GFPErrorSubcodeIMANoFillWithAdRule","kind":"identifier"}],"role":"symbol","modules":[{"name":"GFPSDK"}]},"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPErrorSubcodeIMANoFillWithAdRule":{"kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorSubcodeIMANoFillWithAdRule","role":"symbol","title":"GFPErrorSubcodeIMANoFillWithAdRule","type":"topic","abstract":[],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPErrorSubcodeIMANoFillWithAdRule"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"GFPErrorSubcodeIMANoFillWithAdRule","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfperrorsubcodeimanofillwithadrule"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Global Variable","op":"replace"},{"value":"GFPErrorSubcodeIMANoFillWithAdRule","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"var","op":"replace"},{"value":[{"text":"GFPErrorSubcodeIMANoFillWithAdRule","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"extern","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" * "},{"text":"GFPErrorSubcodeIMANoFillWithAdRule","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorSubcodeIMANoFillWithAdRule\/title","op":"replace","value":"GFPErrorSubcodeIMANoFillWithAdRule"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorSubcodeIMANoFillWithAdRule\/fragments","op":"replace","value":[{"text":"GFPErrorSubcodeIMANoFillWithAdRule","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}