{"sections":[],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorSubcodeKey","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"GFPErrorSubcodeKey"}],"roleHeading":"Global Variable","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"GFPErrorSubcodeKey","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"externalID":"c:@GFPErrorSubcodeKey","role":"symbol","title":"GFPErrorSubcodeKey","symbolKind":"var","modules":[{"name":"GFPSDK"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfperrorsubcodekey"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfperrorsubcodekey"]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPErrorSubcodeKey","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPErrorSubcodeKey":{"title":"GFPErrorSubcodeKey","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorSubcodeKey","kind":"symbol","type":"topic","role":"symbol","abstract":[],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPErrorSubcodeKey","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"url":"\/documentation\/gfpsdk\/gfperrorsubcodekey","navigatorTitle":[{"kind":"identifier","text":"GFPErrorSubcodeKey"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Global Variable"},{"path":"\/metadata\/title","op":"replace","value":"GFPErrorSubcodeKey"},{"op":"replace","path":"\/metadata\/symbolKind","value":"var"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"GFPErrorSubcodeKey","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"GFPErrorSubcodeKey"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorSubcodeKey\/title","value":"GFPErrorSubcodeKey","op":"replace"},{"value":[{"text":"GFPErrorSubcodeKey","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorSubcodeKey\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}