{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPErrorUtils","kind":"identifier"}],"languages":["swift"]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"relationshipsSections":[{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s7CVarArgP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s23CustomStringConvertibleP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH"],"title":"Conforms To","type":"conformsTo","kind":"relationships"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorUtils"},"topicSections":[{"anchor":"Type-Methods","generated":true,"title":"Type Methods","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorUtils\/adSizeError(withRequest:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorUtils\/adSizeError(withResponseSize:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorUtils\/loadError(message:errorKey:errorCode:loadEventStat:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorUtils\/nativeAdRenderingError(withMediaViewSetting:adViewHasMediaView:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorUtils\/nativeAdRenderingError(withMessage:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorUtils\/noFillError()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorUtils\/noFillError(withDesc:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorUtils\/providerInitlizeError(with:message:)"]}],"variants":[{"paths":["\/documentation\/gfpsdk\/gfperrorutils"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfperrorutils"]}],"metadata":{"role":"symbol","symbolKind":"class","modules":[{"name":"GFPSDK"}],"roleHeading":"Class","externalID":"c:objc(cs)GFPErrorUtils","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPErrorUtils"}],"navigatorTitle":[{"text":"GFPErrorUtils","kind":"identifier"}],"title":"GFPErrorUtils"},"references":{"doc://com.navercorp.da.gfp.GFPSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s7CVarArgP","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPErrorUtils/providerInitlizeError(with:message:)":{"kind":"symbol","url":"\/documentation\/gfpsdk\/gfperrorutils\/providerinitlizeerror(with:message:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"providerInitlizeError"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"preciseIdentifier":"c:GFPProvider.h@T@GFPProviderCreativeType","text":"GFPProviderCreativeType","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"message","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@NaverAdsServices@objc(cs)GFPError","text":"GFPError","kind":"typeIdentifier"}],"type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"providerInitlizeErrorWith:message:"}],"role":"symbol","title":"providerInitlizeError(with:message:)","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorUtils\/providerInitlizeError(with:message:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPErrorUtils":{"kind":"symbol","title":"GFPErrorUtils","url":"\/documentation\/gfpsdk\/gfperrorutils","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPErrorUtils","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorUtils","navigatorTitle":[{"text":"GFPErrorUtils","kind":"identifier"}],"abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPErrorUtils/adSizeError(withRequest:)":{"navigatorTitle":[{"kind":"identifier","text":"adSizeErrorWithRequestSizes:"}],"role":"symbol","abstract":[],"url":"\/documentation\/gfpsdk\/gfperrorutils\/adsizeerror(withrequest:)","title":"adSizeError(withRequest:)","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorUtils\/adSizeError(withRequest:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"adSizeError","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"withRequest"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdInfoSize","text":"GFPAdInfoSize"},{"text":"]) -> ","kind":"text"},{"preciseIdentifier":"c:@M@NaverAdsServices@objc(cs)GFPError","text":"GFPError","kind":"typeIdentifier"}],"type":"topic","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPErrorUtils/noFillError(withDesc:)":{"type":"topic","role":"symbol","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorUtils\/noFillError(withDesc:)","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"noFillError","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withDesc"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"c:@M@NaverAdsServices@objc(cs)GFPError","kind":"typeIdentifier","text":"GFPError"}],"navigatorTitle":[{"kind":"identifier","text":"noFillErrorWithDesc:"}],"title":"noFillError(withDesc:)","url":"\/documentation\/gfpsdk\/gfperrorutils\/nofillerror(withdesc:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPErrorUtils/noFillError()":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"noFillError","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","text":"GFPError","preciseIdentifier":"c:@M@NaverAdsServices@objc(cs)GFPError"}],"url":"\/documentation\/gfpsdk\/gfperrorutils\/nofillerror()","navigatorTitle":[{"kind":"identifier","text":"noFillError"}],"kind":"symbol","role":"symbol","title":"noFillError()","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorUtils\/noFillError()","abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPErrorUtils/loadError(message:errorKey:errorCode:loadEventStat:)":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorUtils\/loadError(message:errorKey:errorCode:loadEventStat:)","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"loadError","kind":"identifier"},{"text":"(","kind":"text"},{"text":"message","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"errorKey","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"errorCode"},{"text":": ","kind":"text"},{"text":"GFPErrorCode","kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPErrorCode"},{"kind":"text","text":", "},{"kind":"externalParam","text":"loadEventStat"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPLoadEventStat","text":"GFPLoadEventStat"},{"kind":"text","text":") -> ("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@NaverAdsServices@objc(cs)GFPError","text":"GFPError"},{"text":", ","kind":"text"},{"text":"GFPLoadEvent","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPLoadEvent"},{"text":")","kind":"text"}],"url":"\/documentation\/gfpsdk\/gfperrorutils\/loaderror(message:errorkey:errorcode:loadeventstat:)","abstract":[],"type":"topic","title":"loadError(message:errorKey:errorCode:loadEventStat:)","role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPErrorUtils/nativeAdRenderingError(withMediaViewSetting:adViewHasMediaView:)":{"title":"nativeAdRenderingError(withMediaViewSetting:adViewHasMediaView:)","navigatorTitle":[{"text":"nativeAdRenderingErrorWithMediaViewSetting:adViewHasMediaView:","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfperrorutils\/nativeadrenderingerror(withmediaviewsetting:adviewhasmediaview:)","role":"symbol","kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"nativeAdRenderingError","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withMediaViewSetting"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"adViewHasMediaView","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@NaverAdsServices@objc(cs)GFPError","text":"GFPError"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorUtils\/nativeAdRenderingError(withMediaViewSetting:adViewHasMediaView:)","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPErrorUtils/adSizeError(withResponseSize:)":{"title":"adSizeError(withResponseSize:)","navigatorTitle":[{"kind":"identifier","text":"adSizeErrorWithResponseSize:"}],"url":"\/documentation\/gfpsdk\/gfperrorutils\/adsizeerror(withresponsesize:)","role":"symbol","kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"adSizeError","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"withResponseSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdInfoSize","text":"GFPAdInfoSize"},{"kind":"text","text":") -> "},{"text":"GFPError","kind":"typeIdentifier","preciseIdentifier":"c:@M@NaverAdsServices@objc(cs)GFPError"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorUtils\/adSizeError(withResponseSize:)","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPErrorUtils/nativeAdRenderingError(withMessage:)":{"title":"nativeAdRenderingError(withMessage:)","navigatorTitle":[{"kind":"identifier","text":"nativeAdRenderingErrorWithMessage:"}],"url":"\/documentation\/gfpsdk\/gfperrorutils\/nativeadrenderingerror(withmessage:)","role":"symbol","kind":"symbol","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"nativeAdRenderingError"},{"text":"(","kind":"text"},{"text":"withMessage","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@NaverAdsServices@objc(cs)GFPError","text":"GFPError"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorUtils\/nativeAdRenderingError(withMessage:)","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","value":"GFPErrorUtils","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","value":[{"text":"GFPErrorUtils","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"GFPErrorUtils"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Type Methods","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorUtils\/adSizeError(withRequest:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorUtils\/adSizeError(withResponseSize:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorUtils\/nativeAdRenderingError(withMediaViewSetting:adViewHasMediaView:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorUtils\/nativeAdRenderingError(withMessage:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorUtils\/noFillError()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorUtils\/noFillError(withDesc:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorUtils\/providerInitlizeError(with:message:)"],"generated":true,"anchor":"Type-Methods"}]},{"value":[{"title":"Inherits From","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPErrorUtils"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorUtils~1providerInitlizeError(with:message:)\/title","op":"replace","value":"providerInitlizeErrorWith:message:"},{"value":[{"kind":"text","text":"+ "},{"text":"providerInitlizeErrorWith:message:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorUtils~1providerInitlizeError(with:message:)\/fragments","op":"replace"},{"value":"GFPErrorUtils","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorUtils\/title","op":"replace"},{"value":[{"text":"GFPErrorUtils","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorUtils\/fragments","op":"replace"},{"op":"replace","value":[{"text":"GFPErrorUtils","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorUtils\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorUtils~1adSizeError(withRequest:)\/title","value":"adSizeErrorWithRequestSizes:","op":"replace"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"adSizeErrorWithRequestSizes:"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorUtils~1adSizeError(withRequest:)\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorUtils~1noFillError(withDesc:)\/title","value":"noFillErrorWithDesc:","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"noFillErrorWithDesc:"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorUtils~1noFillError(withDesc:)\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorUtils~1noFillError()\/title","op":"replace","value":"noFillError"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorUtils~1noFillError()\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"noFillError","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorUtils~1nativeAdRenderingError(withMediaViewSetting:adViewHasMediaView:)\/title","op":"replace","value":"nativeAdRenderingErrorWithMediaViewSetting:adViewHasMediaView:"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorUtils~1nativeAdRenderingError(withMediaViewSetting:adViewHasMediaView:)\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"nativeAdRenderingErrorWithMediaViewSetting:adViewHasMediaView:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorUtils~1adSizeError(withResponseSize:)\/title","value":"adSizeErrorWithResponseSize:"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorUtils~1adSizeError(withResponseSize:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"adSizeErrorWithResponseSize:"}],"op":"replace"},{"op":"replace","value":"nativeAdRenderingErrorWithMessage:","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorUtils~1nativeAdRenderingError(withMessage:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorUtils~1nativeAdRenderingError(withMessage:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"nativeAdRenderingErrorWithMessage:"}]}]}]}