{"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfperrorsubcodeadaptorinitfailed"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfperrorsubcodeadaptorinitfailed"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPErrorSubcodeAdaptorInitFailed"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorSubcodeAdaptorInitFailed","interfaceLanguage":"swift"},"metadata":{"externalID":"c:@GFPErrorSubcodeAdaptorInitFailed","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPErrorSubcodeAdaptorInitFailed","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"navigatorTitle":[{"kind":"identifier","text":"GFPErrorSubcodeAdaptorInitFailed"}],"modules":[{"name":"GFPSDK"}],"symbolKind":"var","role":"symbol","roleHeading":"Global Variable","title":"GFPErrorSubcodeAdaptorInitFailed"},"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPErrorSubcodeAdaptorInitFailed":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPErrorSubcodeAdaptorInitFailed"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"abstract":[],"navigatorTitle":[{"text":"GFPErrorSubcodeAdaptorInitFailed","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfperrorsubcodeadaptorinitfailed","kind":"symbol","type":"topic","role":"symbol","title":"GFPErrorSubcodeAdaptorInitFailed","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorSubcodeAdaptorInitFailed"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Global Variable","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"GFPErrorSubcodeAdaptorInitFailed"},{"op":"replace","value":"var","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"GFPErrorSubcodeAdaptorInitFailed"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"extern"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" * ","kind":"text"},{"text":"GFPErrorSubcodeAdaptorInitFailed","kind":"identifier"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"value":"GFPErrorSubcodeAdaptorInitFailed","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorSubcodeAdaptorInitFailed\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorSubcodeAdaptorInitFailed\/fragments","value":[{"text":"GFPErrorSubcodeAdaptorInitFailed","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}