{"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfperrorsubcodendavnomediaurl"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfperrorsubcodendavnomediaurl"]}],"metadata":{"externalID":"c:@GFPErrorSubcodeNDAVNoMediaUrl","modules":[{"name":"GFPSDK"}],"role":"symbol","roleHeading":"Global Variable","navigatorTitle":[{"text":"GFPErrorSubcodeNDAVNoMediaUrl","kind":"identifier"}],"title":"GFPErrorSubcodeNDAVNoMediaUrl","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"GFPErrorSubcodeNDAVNoMediaUrl","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"symbolKind":"var"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPErrorSubcodeNDAVNoMediaUrl"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorSubcodeNDAVNoMediaUrl","interfaceLanguage":"swift"},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPErrorSubcodeNDAVNoMediaUrl":{"navigatorTitle":[{"kind":"identifier","text":"GFPErrorSubcodeNDAVNoMediaUrl"}],"role":"symbol","abstract":[],"url":"\/documentation\/gfpsdk\/gfperrorsubcodendavnomediaurl","title":"GFPErrorSubcodeNDAVNoMediaUrl","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorSubcodeNDAVNoMediaUrl","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"GFPErrorSubcodeNDAVNoMediaUrl","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"type":"topic","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Global Variable","path":"\/metadata\/roleHeading","op":"replace"},{"value":"GFPErrorSubcodeNDAVNoMediaUrl","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"var"},{"path":"\/metadata\/fragments","value":[{"text":"GFPErrorSubcodeNDAVNoMediaUrl","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"extern"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"GFPErrorSubcodeNDAVNoMediaUrl"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorSubcodeNDAVNoMediaUrl\/title","value":"GFPErrorSubcodeNDAVNoMediaUrl","op":"replace"},{"value":[{"kind":"identifier","text":"GFPErrorSubcodeNDAVNoMediaUrl"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorSubcodeNDAVNoMediaUrl\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}