{"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionTrackingTarget","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionTrackingTarget\/init(trackView:trackThreshold:completionHandler:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionTrackingTarget\/init(trackView:trackThreshold:completionHandler:completeCheckHandler:)"],"title":"Initializers","generated":true,"anchor":"Initializers"},{"anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionTrackingTarget\/completionHandler","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionTrackingTarget\/customCompleteCheckHandler","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionTrackingTarget\/trackThreshold","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionTrackingTarget\/trackView"],"title":"Instance Properties"}],"metadata":{"externalID":"c:objc(cs)GFPImpressionTrackingTarget","roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPImpressionTrackingTarget"}],"navigatorTitle":[{"kind":"identifier","text":"GFPImpressionTrackingTarget"}],"role":"symbol","title":"GFPImpressionTrackingTarget","symbolKind":"class","modules":[{"name":"GFPSDK"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"GFPImpressionTrackingTarget","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s7CVarArgP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s23CustomStringConvertibleP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpimpressiontrackingtarget"]},{"paths":["\/documentation\/gfpsdk\/gfpimpressiontrackingtarget"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPImpressionTrackingTarget":{"navigatorTitle":[{"text":"GFPImpressionTrackingTarget","kind":"identifier"}],"title":"GFPImpressionTrackingTarget","url":"\/documentation\/gfpsdk\/gfpimpressiontrackingtarget","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionTrackingTarget","role":"symbol","type":"topic","kind":"symbol","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPImpressionTrackingTarget","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPImpressionTrackingTarget/trackThreshold":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionTrackingTarget\/trackThreshold","type":"topic","abstract":[],"url":"\/documentation\/gfpsdk\/gfpimpressiontrackingtarget\/trackthreshold","navigatorTitle":[{"kind":"identifier","text":"trackThreshold"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"trackThreshold","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)GFPImpressionTrackThreshold","text":"GFPImpressionTrackThreshold","kind":"typeIdentifier"}],"title":"trackThreshold","role":"symbol","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPImpressionTrackingTarget/customCompleteCheckHandler":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionTrackingTarget\/customCompleteCheckHandler","type":"topic","abstract":[],"url":"\/documentation\/gfpsdk\/gfpimpressiontrackingtarget\/customcompletecheckhandler","navigatorTitle":[{"kind":"identifier","text":"customCompleteCheckHandler"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"customCompleteCheckHandler","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:GFPImpressionTracker.h@T@GFPImpressionTrackCustomCompleteCheckHandler","text":"GFPImpressionTrackCustomCompleteCheckHandler"}],"title":"customCompleteCheckHandler","role":"symbol","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPImpressionTrackingTarget/trackView":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"trackView"}],"title":"trackView","url":"\/documentation\/gfpsdk\/gfpimpressiontrackingtarget\/trackview","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionTrackingTarget\/trackView","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"trackView","kind":"identifier"},{"text":": ","kind":"text"},{"text":"GFPImpressionTrackView","preciseIdentifier":"c:objc(cs)GFPImpressionTrackView","kind":"typeIdentifier"}],"abstract":[],"type":"topic","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s7CVarArgP","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPImpressionTrackingTarget/init(trackView:trackThreshold:completionHandler:completeCheckHandler:)":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionTrackingTarget\/init(trackView:trackThreshold:completionHandler:completeCheckHandler:)","fragments":[{"kind":"keyword","text":"convenience"},{"text":" ","kind":"text"},{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"trackView","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GFPImpressionTrackView","preciseIdentifier":"c:objc(cs)GFPImpressionTrackView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"trackThreshold"},{"text":": ","kind":"text"},{"text":"GFPImpressionTrackThreshold","preciseIdentifier":"c:objc(cs)GFPImpressionTrackThreshold","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completionHandler"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:GFPImpressionTracker.h@T@GFPImpressionTrackCompletionHandler","text":"GFPImpressionTrackCompletionHandler","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completeCheckHandler"},{"kind":"text","text":": "},{"preciseIdentifier":"c:GFPImpressionTracker.h@T@GFPImpressionTrackCustomCompleteCheckHandler","kind":"typeIdentifier","text":"GFPImpressionTrackCustomCompleteCheckHandler"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"initWithTrackView:trackThreshold:completionHandler:completeCheckHandler:","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/gfpsdk\/gfpimpressiontrackingtarget\/init(trackview:trackthreshold:completionhandler:completecheckhandler:)","title":"init(trackView:trackThreshold:completionHandler:completeCheckHandler:)","kind":"symbol","abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)NSObject":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPImpressionTrackingTarget/init(trackView:trackThreshold:completionHandler:)":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionTrackingTarget\/init(trackView:trackThreshold:completionHandler:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"trackView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPImpressionTrackView","text":"GFPImpressionTrackView"},{"kind":"text","text":", "},{"text":"trackThreshold","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)GFPImpressionTrackThreshold","kind":"typeIdentifier","text":"GFPImpressionTrackThreshold"},{"text":", ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"GFPImpressionTrackCompletionHandler","kind":"typeIdentifier","preciseIdentifier":"c:GFPImpressionTracker.h@T@GFPImpressionTrackCompletionHandler"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"initWithTrackView:trackThreshold:completionHandler:"}],"type":"topic","role":"symbol","url":"\/documentation\/gfpsdk\/gfpimpressiontrackingtarget\/init(trackview:trackthreshold:completionhandler:)","title":"init(trackView:trackThreshold:completionHandler:)","kind":"symbol","abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/SH":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPImpressionTrackingTarget/completionHandler":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionTrackingTarget\/completionHandler","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"completionHandler","kind":"identifier"},{"kind":"text","text":": "},{"text":"GFPImpressionTrackCompletionHandler","kind":"typeIdentifier","preciseIdentifier":"c:GFPImpressionTracker.h@T@GFPImpressionTrackCompletionHandler"}],"navigatorTitle":[{"text":"completionHandler","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/gfpsdk\/gfpimpressiontrackingtarget\/completionhandler","title":"completionHandler","kind":"symbol","abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"GFPImpressionTrackingTarget"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"op":"replace","value":[{"text":"GFPImpressionTrackingTarget","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"GFPImpressionTrackingTarget"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionTrackingTarget\/completionHandler","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionTrackingTarget\/customCompleteCheckHandler","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionTrackingTarget\/trackThreshold","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionTrackingTarget\/trackView"]},{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionTrackingTarget\/init(trackView:trackThreshold:completionHandler:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionTrackingTarget\/init(trackView:trackThreshold:completionHandler:completeCheckHandler:)"],"anchor":"Instance-Methods"}]},{"path":"\/relationshipsSections","value":[{"kind":"relationships","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"}],"op":"replace"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"GFPImpressionTrackingTarget","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"GFPImpressionTrackingTarget","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTrackingTarget\/title"},{"value":[{"text":"GFPImpressionTrackingTarget","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTrackingTarget\/fragments"},{"op":"replace","value":[{"text":"GFPImpressionTrackingTarget","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTrackingTarget\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTrackingTarget~1trackThreshold\/title","value":"trackThreshold"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTrackingTarget~1trackThreshold\/fragments","op":"replace","value":[{"kind":"identifier","text":"trackThreshold"}]},{"value":"customCompleteCheckHandler","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTrackingTarget~1customCompleteCheckHandler\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTrackingTarget~1customCompleteCheckHandler\/fragments","value":[{"kind":"identifier","text":"customCompleteCheckHandler"}]},{"value":"trackView","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTrackingTarget~1trackView\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTrackingTarget~1trackView\/fragments","value":[{"text":"trackView","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTrackingTarget~1init(trackView:trackThreshold:completionHandler:completeCheckHandler:)\/title","value":"initWithTrackView:trackThreshold:completionHandler:completeCheckHandler:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTrackingTarget~1init(trackView:trackThreshold:completionHandler:completeCheckHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithTrackView:trackThreshold:completionHandler:completeCheckHandler:"}]},{"value":"initWithTrackView:trackThreshold:completionHandler:","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTrackingTarget~1init(trackView:trackThreshold:completionHandler:)\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTrackingTarget~1init(trackView:trackThreshold:completionHandler:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithTrackView:trackThreshold:completionHandler:"}]},{"value":"completionHandler","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTrackingTarget~1completionHandler\/title","op":"replace"},{"value":[{"text":"completionHandler","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTrackingTarget~1completionHandler\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}