{"metadata":{"navigatorTitle":[{"text":"GFPImpressionTrackCustomCheckHandler","kind":"identifier"}],"externalID":"c:GFPImpressionTracker.h@T@GFPImpressionTrackCustomCheckHandler","symbolKind":"typealias","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPImpressionTrackCustomCheckHandler"}],"role":"symbol","roleHeading":"Type Alias","modules":[{"name":"GFPSDK"}],"title":"GFPImpressionTrackCustomCheckHandler"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"GFPImpressionTrackCustomCheckHandler","kind":"identifier"},{"text":" = (","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPImpressionTrackingTarget","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionTrackingTarget","kind":"typeIdentifier","text":"GFPImpressionTrackingTarget"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpimpressiontrackcustomcheckhandler"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpimpressiontrackcustomcheckhandler"]}],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionTrackCustomCheckHandler"},"sections":[],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPImpressionTrackCustomCheckHandler":{"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPImpressionTrackCustomCheckHandler","kind":"identifier"}],"abstract":[],"navigatorTitle":[{"text":"GFPImpressionTrackCustomCheckHandler","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpimpressiontrackcustomcheckhandler","kind":"symbol","type":"topic","role":"symbol","title":"GFPImpressionTrackCustomCheckHandler","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionTrackCustomCheckHandler"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPImpressionTrackingTarget":{"navigatorTitle":[{"text":"GFPImpressionTrackingTarget","kind":"identifier"}],"title":"GFPImpressionTrackingTarget","url":"\/documentation\/gfpsdk\/gfpimpressiontrackingtarget","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionTrackingTarget","role":"symbol","type":"topic","kind":"symbol","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPImpressionTrackingTarget","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Alias"},{"op":"replace","value":"GFPImpressionTrackCustomCheckHandler","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"typealias","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"GFPImpressionTrackCustomCheckHandler","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"GFPImpressionTrackCustomCheckHandler"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"typedef"},{"text":" ","kind":"text"},{"text":"void (^)(GFPImpressionTrackingTarget *)","kind":"typeIdentifier","preciseIdentifier":"c:BFv(#*$objc(cs)GFPImpressionTrackingTarget)"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPImpressionTrackCustomCheckHandler"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"GFPImpressionTrackCustomCheckHandler","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTrackCustomCheckHandler\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTrackCustomCheckHandler\/fragments","op":"replace","value":[{"text":"GFPImpressionTrackCustomCheckHandler","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTrackCustomCheckHandler\/navigatorTitle","op":"replace","value":[{"text":"GFPImpressionTrackCustomCheckHandler","kind":"identifier"}]},{"op":"replace","value":"GFPImpressionTrackingTarget","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTrackingTarget\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTrackingTarget\/fragments","value":[{"text":"GFPImpressionTrackingTarget","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTrackingTarget\/navigatorTitle","value":[{"kind":"identifier","text":"GFPImpressionTrackingTarget"}],"op":"replace"}]}]}