{"sections":[],"metadata":{"modules":[{"name":"GFPSDK"}],"role":"symbol","roleHeading":"Global Variable","externalID":"c:@GFPInterstitialProviderBidMachineErrorKey","title":"GFPInterstitialProviderBidMachineErrorKey","symbolKind":"var","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPInterstitialProviderBidMachineErrorKey"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"GFPInterstitialProviderBidMachineErrorKey"}]},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialProviderBidMachineErrorKey","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpinterstitialproviderbidmachineerrorkey"]},{"paths":["\/documentation\/gfpsdk\/gfpinterstitialproviderbidmachineerrorkey"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPInterstitialProviderBidMachineErrorKey","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPInterstitialProviderBidMachineErrorKey":{"abstract":[],"url":"\/documentation\/gfpsdk\/gfpinterstitialproviderbidmachineerrorkey","role":"symbol","title":"GFPInterstitialProviderBidMachineErrorKey","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialProviderBidMachineErrorKey","type":"topic","navigatorTitle":[{"text":"GFPInterstitialProviderBidMachineErrorKey","kind":"identifier"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPInterstitialProviderBidMachineErrorKey","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Global Variable","op":"replace"},{"op":"replace","value":"GFPInterstitialProviderBidMachineErrorKey","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"var","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"GFPInterstitialProviderBidMachineErrorKey","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"text":"extern","kind":"keyword"},{"kind":"text","text":" "},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"GFPInterstitialProviderBidMachineErrorKey"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialProviderBidMachineErrorKey\/title","op":"replace","value":"GFPInterstitialProviderBidMachineErrorKey"},{"op":"replace","value":[{"text":"GFPInterstitialProviderBidMachineErrorKey","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialProviderBidMachineErrorKey\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}