{"kind":"symbol","abstract":[{"type":"text","text":"GFP에서 지원하는 Interstitial 광고 제공자 목록"}],"sections":[],"topicSections":[{"anchor":"Enumeration-Cases","generated":true,"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdProviderOption\/APS","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdProviderOption\/BidMachine","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdProviderOption\/DFP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdProviderOption\/DT","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdProviderOption\/FAN","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdProviderOption\/IS","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdProviderOption\/LAN","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdProviderOption\/appLovin","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdProviderOption\/chartBoost","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdProviderOption\/end","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdProviderOption\/inMobi","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdProviderOption\/none","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdProviderOption\/unity","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdProviderOption\/vungle"],"title":"Enumeration Cases"},{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdProviderOption\/init(rawValue:)"],"generated":true,"title":"Initializers","anchor":"Initializers"},{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdProviderOption\/Equatable-Implementations","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdProviderOption\/RawRepresentable-Implementations"],"title":"Default Implementations","anchor":"Default-Implementations","generated":true}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"relationshipsSections":[{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SY"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpinterstitialadprovideroption"]},{"paths":["\/documentation\/gfpsdk\/gfpinterstitialadprovideroption"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdProviderOption","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"symbolKind":"enum","title":"GFPInterstitialAdProviderOption","role":"symbol","roleHeading":"Enumeration","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPInterstitialAdProviderOption"}],"navigatorTitle":[{"text":"GFPInterstitialAdProviderOption","kind":"identifier"}],"externalID":"c:@M@GFPSDK@E@GFPInterstitialAdProviderOption","modules":[{"name":"GFPSDK"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPInterstitialAdProviderOption"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPInterstitialAdProviderOption/APS":{"abstract":[],"role":"symbol","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"APS"}],"url":"\/documentation\/gfpsdk\/gfpinterstitialadprovideroption\/aps","navigatorTitle":[{"kind":"identifier","text":"GFPInterstitialAdProviderOptionAPS"}],"type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdProviderOption\/APS","title":"GFPInterstitialAdProviderOption.APS"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPInterstitialAdProviderOption/appLovin":{"kind":"symbol","type":"topic","role":"symbol","title":"GFPInterstitialAdProviderOption.appLovin","abstract":[],"url":"\/documentation\/gfpsdk\/gfpinterstitialadprovideroption\/applovin","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"appLovin"}],"navigatorTitle":[{"text":"GFPInterstitialAdProviderOptionAppLovin","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdProviderOption\/appLovin"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPInterstitialAdProviderOption/chartBoost":{"type":"topic","url":"\/documentation\/gfpsdk\/gfpinterstitialadprovideroption\/chartboost","abstract":[],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"chartBoost","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"GFPInterstitialAdProviderOptionChartBoost","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdProviderOption\/chartBoost","title":"GFPInterstitialAdProviderOption.chartBoost"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPInterstitialAdProviderOption/IS":{"abstract":[],"url":"\/documentation\/gfpsdk\/gfpinterstitialadprovideroption\/is","title":"GFPInterstitialAdProviderOption.IS","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"IS","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPInterstitialAdProviderOptionIS"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdProviderOption\/IS"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPInterstitialAdProviderOption/Equatable-Implementations":{"kind":"article","type":"topic","role":"collectionGroup","title":"Equatable Implementations","abstract":[],"url":"\/documentation\/gfpsdk\/gfpinterstitialadprovideroption\/equatable-implementations","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdProviderOption\/Equatable-Implementations"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPInterstitialAdProviderOption/RawRepresentable-Implementations":{"url":"\/documentation\/gfpsdk\/gfpinterstitialadprovideroption\/rawrepresentable-implementations","title":"RawRepresentable Implementations","abstract":[],"role":"collectionGroup","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdProviderOption\/RawRepresentable-Implementations","type":"topic","kind":"article"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPInterstitialAdProviderOption/BidMachine":{"type":"topic","url":"\/documentation\/gfpsdk\/gfpinterstitialadprovideroption\/bidmachine","abstract":[],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BidMachine"}],"kind":"symbol","navigatorTitle":[{"text":"GFPInterstitialAdProviderOptionBidMachine","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdProviderOption\/BidMachine","title":"GFPInterstitialAdProviderOption.BidMachine"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPInterstitialAdProviderOption":{"navigatorTitle":[{"text":"GFPInterstitialAdProviderOption","kind":"identifier"}],"abstract":[{"type":"text","text":"GFP에서 지원하는 Interstitial 광고 제공자 목록"}],"title":"GFPInterstitialAdProviderOption","url":"\/documentation\/gfpsdk\/gfpinterstitialadprovideroption","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdProviderOption","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPInterstitialAdProviderOption"}],"type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","title":"Swift.Equatable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPInterstitialAdProviderOption/DFP":{"type":"topic","url":"\/documentation\/gfpsdk\/gfpinterstitialadprovideroption\/dfp","abstract":[],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"DFP","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"GFPInterstitialAdProviderOptionDFP","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdProviderOption\/DFP","title":"GFPInterstitialAdProviderOption.DFP"},"doc://com.navercorp.da.gfp.GFPSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH","title":"Swift.Hashable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPInterstitialAdProviderOption/end":{"type":"topic","url":"\/documentation\/gfpsdk\/gfpinterstitialadprovideroption\/end","abstract":[],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"end"}],"kind":"symbol","navigatorTitle":[{"text":"GFPInterstitialAdProviderOptionEnd","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdProviderOption\/end","title":"GFPInterstitialAdProviderOption.end"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPInterstitialAdProviderOption/LAN":{"kind":"symbol","type":"topic","role":"symbol","title":"GFPInterstitialAdProviderOption.LAN","abstract":[],"url":"\/documentation\/gfpsdk\/gfpinterstitialadprovideroption\/lan","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"LAN","kind":"identifier"}],"navigatorTitle":[{"text":"GFPInterstitialAdProviderOptionLAN","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdProviderOption\/LAN"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPInterstitialAdProviderOption/vungle":{"type":"topic","url":"\/documentation\/gfpsdk\/gfpinterstitialadprovideroption\/vungle","abstract":[],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"vungle"}],"kind":"symbol","navigatorTitle":[{"text":"GFPInterstitialAdProviderOptionVungle","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdProviderOption\/vungle","title":"GFPInterstitialAdProviderOption.vungle"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPInterstitialAdProviderOption/FAN":{"kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdProviderOption\/FAN","abstract":[],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"FAN","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"GFPInterstitialAdProviderOptionFAN"}],"title":"GFPInterstitialAdProviderOption.FAN","url":"\/documentation\/gfpsdk\/gfpinterstitialadprovideroption\/fan"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPInterstitialAdProviderOption/init(rawValue:)":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdProviderOption\/init(rawValue:)","title":"init(rawValue:)","abstract":[],"url":"\/documentation\/gfpsdk\/gfpinterstitialadprovideroption\/init(rawvalue:)","role":"symbol","kind":"symbol","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPInterstitialAdProviderOption/unity":{"navigatorTitle":[{"text":"GFPInterstitialAdProviderOptionUnity","kind":"identifier"}],"type":"topic","title":"GFPInterstitialAdProviderOption.unity","kind":"symbol","url":"\/documentation\/gfpsdk\/gfpinterstitialadprovideroption\/unity","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdProviderOption\/unity","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"unity","kind":"identifier"}],"role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPInterstitialAdProviderOption/none":{"kind":"symbol","type":"topic","role":"symbol","title":"GFPInterstitialAdProviderOption.none","abstract":[],"url":"\/documentation\/gfpsdk\/gfpinterstitialadprovideroption\/none","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"none","kind":"identifier"}],"navigatorTitle":[{"text":"GFPInterstitialAdProviderOptionNone","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdProviderOption\/none"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPInterstitialAdProviderOption/inMobi":{"abstract":[],"url":"\/documentation\/gfpsdk\/gfpinterstitialadprovideroption\/inmobi","role":"symbol","kind":"symbol","title":"GFPInterstitialAdProviderOption.inMobi","navigatorTitle":[{"text":"GFPInterstitialAdProviderOptionInMobi","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdProviderOption\/inMobi","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"inMobi","kind":"identifier"}],"type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/SY":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SY","title":"Swift.RawRepresentable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPInterstitialAdProviderOption/DT":{"kind":"symbol","type":"topic","role":"symbol","title":"GFPInterstitialAdProviderOption.DT","abstract":[],"url":"\/documentation\/gfpsdk\/gfpinterstitialadprovideroption\/dt","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DT"}],"navigatorTitle":[{"text":"GFPInterstitialAdProviderOptionDT","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdProviderOption\/DT"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"GFPInterstitialAdProviderOption"},{"path":"\/metadata\/symbolKind","op":"replace","value":"enum"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"GFPInterstitialAdProviderOption","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"GFPInterstitialAdProviderOption","kind":"identifier"}]},{"path":"\/topicSections","value":[{"anchor":"Enumeration-Cases","generated":true,"title":"Enumeration Cases","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdProviderOption\/APS","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdProviderOption\/BidMachine","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdProviderOption\/DFP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdProviderOption\/DT","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdProviderOption\/FAN","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdProviderOption\/IS","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdProviderOption\/LAN","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdProviderOption\/appLovin","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdProviderOption\/chartBoost","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdProviderOption\/end","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdProviderOption\/inMobi","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdProviderOption\/none","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdProviderOption\/unity","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdProviderOption\/vungle"]}],"op":"replace"},{"value":null,"path":"\/relationshipsSections","op":"replace"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPInterstitialAdProviderOption"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdProviderOption~1APS\/title","value":"GFPInterstitialAdProviderOptionAPS","op":"replace"},{"value":[{"text":"GFPInterstitialAdProviderOptionAPS","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdProviderOption~1APS\/fragments","op":"replace"},{"value":"GFPInterstitialAdProviderOptionAppLovin","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdProviderOption~1appLovin\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdProviderOption~1appLovin\/fragments","value":[{"kind":"identifier","text":"GFPInterstitialAdProviderOptionAppLovin"}]},{"value":"GFPInterstitialAdProviderOptionChartBoost","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdProviderOption~1chartBoost\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"GFPInterstitialAdProviderOptionChartBoost"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdProviderOption~1chartBoost\/fragments"},{"op":"replace","value":"GFPInterstitialAdProviderOptionIS","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdProviderOption~1IS\/title"},{"value":[{"kind":"identifier","text":"GFPInterstitialAdProviderOptionIS"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdProviderOption~1IS\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdProviderOption~1BidMachine\/title","value":"GFPInterstitialAdProviderOptionBidMachine","op":"replace"},{"value":[{"kind":"identifier","text":"GFPInterstitialAdProviderOptionBidMachine"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdProviderOption~1BidMachine\/fragments"},{"value":"GFPInterstitialAdProviderOption","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdProviderOption\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdProviderOption\/fragments","op":"replace","value":[{"kind":"identifier","text":"GFPInterstitialAdProviderOption"}]},{"value":[{"text":"GFPInterstitialAdProviderOption","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdProviderOption\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdProviderOption~1DFP\/title","value":"GFPInterstitialAdProviderOptionDFP","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdProviderOption~1DFP\/fragments","op":"replace","value":[{"text":"GFPInterstitialAdProviderOptionDFP","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdProviderOption~1end\/title","value":"GFPInterstitialAdProviderOptionEnd","op":"replace"},{"value":[{"kind":"identifier","text":"GFPInterstitialAdProviderOptionEnd"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdProviderOption~1end\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdProviderOption~1LAN\/title","value":"GFPInterstitialAdProviderOptionLAN","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdProviderOption~1LAN\/fragments","value":[{"kind":"identifier","text":"GFPInterstitialAdProviderOptionLAN"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdProviderOption~1vungle\/title","op":"replace","value":"GFPInterstitialAdProviderOptionVungle"},{"value":[{"text":"GFPInterstitialAdProviderOptionVungle","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdProviderOption~1vungle\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdProviderOption~1FAN\/title","value":"GFPInterstitialAdProviderOptionFAN"},{"value":[{"text":"GFPInterstitialAdProviderOptionFAN","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdProviderOption~1FAN\/fragments"},{"value":"GFPInterstitialAdProviderOptionUnity","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdProviderOption~1unity\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdProviderOption~1unity\/fragments","value":[{"text":"GFPInterstitialAdProviderOptionUnity","kind":"identifier"}]},{"value":"GFPInterstitialAdProviderOptionNone","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdProviderOption~1none\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"GFPInterstitialAdProviderOptionNone"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdProviderOption~1none\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdProviderOption~1inMobi\/title","op":"replace","value":"GFPInterstitialAdProviderOptionInMobi"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdProviderOption~1inMobi\/fragments","value":[{"text":"GFPInterstitialAdProviderOptionInMobi","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdProviderOption~1DT\/title","value":"GFPInterstitialAdProviderOptionDT","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdProviderOption~1DT\/fragments","value":[{"text":"GFPInterstitialAdProviderOptionDT","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}