{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPInternalResponseInfo"}],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpinternalresponseinfo"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gfpsdk\/gfpinternalresponseinfo"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject"],"type":"inheritsFrom"},{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s7CVarArgP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s23CustomStringConvertibleP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH"],"kind":"relationships"}],"metadata":{"modules":[{"name":"GFPSDK"}],"role":"symbol","navigatorTitle":[{"text":"GFPInternalResponseInfo","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPInternalResponseInfo","kind":"identifier"}],"roleHeading":"Class","symbolKind":"class","title":"GFPInternalResponseInfo","externalID":"c:objc(cs)GFPInternalResponseInfo"},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInternalResponseInfo\/adaptorName","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInternalResponseInfo\/errorMesage","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInternalResponseInfo\/loadErrorLatency","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInternalResponseInfo\/loadLatency"],"generated":true,"anchor":"Instance-Properties"},{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInternalResponseInfo\/recordAdaptorName(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInternalResponseInfo\/recordLoadEmptyTime()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInternalResponseInfo\/recordLoadEndTime(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInternalResponseInfo\/updateLoadErrorMessage(_:errorTime:)"],"title":"Instance Methods","anchor":"Instance-Methods","generated":true}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInternalResponseInfo","interfaceLanguage":"swift"},"references":{"doc://com.navercorp.da.gfp.GFPSDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s23CustomStringConvertibleP"},"doc://com.navercorp.da.gfp.GFPSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s7CVarArgP"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPInternalResponseInfo/loadLatency":{"role":"symbol","navigatorTitle":[{"text":"loadLatency","kind":"identifier"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"loadLatency","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInternalResponseInfo\/loadLatency","abstract":[],"kind":"symbol","title":"loadLatency","url":"\/documentation\/gfpsdk\/gfpinternalresponseinfo\/loadlatency"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)NSObject":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPInternalResponseInfo/recordAdaptorName(_:)":{"abstract":[],"title":"recordAdaptorName(_:)","role":"symbol","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInternalResponseInfo\/recordAdaptorName(_:)","navigatorTitle":[{"kind":"identifier","text":"recordAdaptorName:"}],"url":"\/documentation\/gfpsdk\/gfpinternalresponseinfo\/recordadaptorname(_:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"recordAdaptorName","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}]},"doc://com.navercorp.da.gfp.GFPSDK/objc(cs)NSObject":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPInternalResponseInfo/adaptorName":{"url":"\/documentation\/gfpsdk\/gfpinternalresponseinfo\/adaptorname","title":"adaptorName","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInternalResponseInfo\/adaptorName","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"adaptorName","kind":"identifier"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"adaptorName","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]},"doc://com.navercorp.da.gfp.GFPSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s28CustomDebugStringConvertibleP"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPInternalResponseInfo/updateLoadErrorMessage(_:errorTime:)":{"url":"\/documentation\/gfpsdk\/gfpinternalresponseinfo\/updateloaderrormessage(_:errortime:)","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInternalResponseInfo\/updateLoadErrorMessage(_:errorTime:)","title":"updateLoadErrorMessage(_:errorTime:)","abstract":[],"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"updateLoadErrorMessage:errorTime:"}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"updateLoadErrorMessage","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"errorTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":")","kind":"text"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPInternalResponseInfo":{"abstract":[],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInternalResponseInfo","url":"\/documentation\/gfpsdk\/gfpinternalresponseinfo","navigatorTitle":[{"text":"GFPInternalResponseInfo","kind":"identifier"}],"title":"GFPInternalResponseInfo","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPInternalResponseInfo","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPInternalResponseInfo/errorMesage":{"role":"symbol","navigatorTitle":[{"text":"errorMesage","kind":"identifier"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorMesage"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInternalResponseInfo\/errorMesage","kind":"symbol","title":"errorMesage","url":"\/documentation\/gfpsdk\/gfpinternalresponseinfo\/errormesage"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPInternalResponseInfo/recordLoadEmptyTime()":{"url":"\/documentation\/gfpsdk\/gfpinternalresponseinfo\/recordloademptytime()","title":"recordLoadEmptyTime()","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInternalResponseInfo\/recordLoadEmptyTime()","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"recordLoadEmptyTime","kind":"identifier"}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"recordLoadEmptyTime"},{"kind":"text","text":"()"}]},"doc://com.navercorp.da.gfp.GFPSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPInternalResponseInfo/recordLoadEndTime(_:)":{"url":"\/documentation\/gfpsdk\/gfpinternalresponseinfo\/recordloadendtime(_:)","title":"recordLoadEndTime(_:)","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInternalResponseInfo\/recordLoadEndTime(_:)","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"recordLoadEndTime:"}],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"recordLoadEndTime"},{"text":"(","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":")","kind":"text"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPInternalResponseInfo/loadErrorLatency":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"loadErrorLatency"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"loadErrorLatency","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"}],"abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInternalResponseInfo\/loadErrorLatency","kind":"symbol","title":"loadErrorLatency","url":"\/documentation\/gfpsdk\/gfpinternalresponseinfo\/loaderrorlatency"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"value":"GFPInternalResponseInfo","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GFPInternalResponseInfo"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"GFPInternalResponseInfo","kind":"identifier"}]},{"value":[{"anchor":"Instance-Properties","generated":true,"title":"Instance Properties","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInternalResponseInfo\/adaptorName","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInternalResponseInfo\/errorMesage","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInternalResponseInfo\/loadErrorLatency","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInternalResponseInfo\/loadLatency"]},{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInternalResponseInfo\/recordAdaptorName(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInternalResponseInfo\/recordLoadEmptyTime()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInternalResponseInfo\/recordLoadEndTime(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInternalResponseInfo\/updateLoadErrorMessage(_:errorTime:)"],"anchor":"Instance-Methods","title":"Instance Methods","generated":true}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"replace","value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject"],"type":"inheritsFrom"}]},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"GFPInternalResponseInfo","kind":"identifier"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInternalResponseInfo~1loadLatency\/title","value":"loadLatency","op":"replace"},{"op":"replace","value":[{"text":"loadLatency","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInternalResponseInfo~1loadLatency\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInternalResponseInfo~1recordAdaptorName(_:)\/title","value":"recordAdaptorName:","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"recordAdaptorName:"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInternalResponseInfo~1recordAdaptorName(_:)\/fragments"},{"value":"adaptorName","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInternalResponseInfo~1adaptorName\/title","op":"replace"},{"value":[{"kind":"identifier","text":"adaptorName"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInternalResponseInfo~1adaptorName\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInternalResponseInfo~1updateLoadErrorMessage(_:errorTime:)\/title","value":"updateLoadErrorMessage:errorTime:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInternalResponseInfo~1updateLoadErrorMessage(_:errorTime:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"updateLoadErrorMessage:errorTime:"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInternalResponseInfo\/title","value":"GFPInternalResponseInfo","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInternalResponseInfo\/fragments","value":[{"text":"GFPInternalResponseInfo","kind":"identifier"}]},{"op":"replace","value":[{"text":"GFPInternalResponseInfo","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInternalResponseInfo\/navigatorTitle"},{"value":"errorMesage","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInternalResponseInfo~1errorMesage\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInternalResponseInfo~1errorMesage\/fragments","value":[{"kind":"identifier","text":"errorMesage"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInternalResponseInfo~1recordLoadEmptyTime()\/title","value":"recordLoadEmptyTime"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInternalResponseInfo~1recordLoadEmptyTime()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"recordLoadEmptyTime"}]},{"value":"recordLoadEndTime:","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInternalResponseInfo~1recordLoadEndTime(_:)\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInternalResponseInfo~1recordLoadEndTime(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"recordLoadEndTime:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInternalResponseInfo~1loadErrorLatency\/title","value":"loadErrorLatency"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInternalResponseInfo~1loadErrorLatency\/fragments","value":[{"text":"loadErrorLatency","kind":"identifier"}]}]}]}