{"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject"],"kind":"relationships","type":"inheritsFrom"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPInterstitialAdManagerDelegate"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier","text":"NSObjectProtocol"}]}]}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpinterstitialadmanagerdelegate"]},{"paths":["\/documentation\/gfpsdk\/gfpinterstitialadmanagerdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdManagerDelegate\/interstitialAdManager(_:didClose:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdManagerDelegate\/interstitialAdManager(_:didComplete:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdManagerDelegate\/interstitialAdManager(_:didFailWithError:responseInfo:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdManagerDelegate\/interstitialAdManager(_:didLoad:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdManagerDelegate\/interstitialAdManager(_:didStart:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdManagerDelegate\/interstitialAdManager(_:wasClickedAd:)"],"anchor":"Instance-Methods"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdManagerDelegate"},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"GFPInterstitialAdManagerDelegate","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"GFPInterstitialAdManagerDelegate"}],"roleHeading":"Protocol","modules":[{"name":"GFPSDK"}],"externalID":"c:objc(pl)GFPInterstitialAdManagerDelegate","role":"symbol","title":"GFPInterstitialAdManagerDelegate","symbolKind":"protocol"},"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPInterstitialAdManagerDelegate/interstitialAdManager(_:didClose:)":{"type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdManagerDelegate\/interstitialAdManager(_:didClose:)","required":true,"role":"symbol","abstract":[],"navigatorTitle":[{"text":"interstitialAdManager:didCloseAd:","kind":"identifier"}],"title":"interstitialAdManager(_:didClose:)","kind":"symbol","url":"\/documentation\/gfpsdk\/gfpinterstitialadmanagerdelegate\/interstitialadmanager(_:didclose:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"interstitialAdManager","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPInterstitialAdManager","text":"GFPInterstitialAdManager"},{"kind":"text","text":", "},{"text":"didClose","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPInterstitialAd","text":"GFPInterstitialAd","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPInterstitialAdManagerDelegate":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPInterstitialAdManagerDelegate","kind":"identifier"}],"role":"symbol","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdManagerDelegate","kind":"symbol","type":"topic","url":"\/documentation\/gfpsdk\/gfpinterstitialadmanagerdelegate","title":"GFPInterstitialAdManagerDelegate","navigatorTitle":[{"kind":"identifier","text":"GFPInterstitialAdManagerDelegate"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPInterstitialAdManagerDelegate/interstitialAdManager(_:didFailWithError:responseInfo:)":{"navigatorTitle":[{"text":"interstitialAdManager:didFailWithError:responseInfo:","kind":"identifier"}],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"interstitialAdManager","kind":"identifier"},{"text":"(","kind":"text"},{"text":"GFPInterstitialAdManager","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPInterstitialAdManager"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFailWithError"},{"kind":"text","text":": "},{"text":"GFPError","kind":"typeIdentifier","preciseIdentifier":"c:@M@NaverAdsServices@objc(cs)GFPError"},{"text":", ","kind":"text"},{"text":"responseInfo","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPLoadResponseInfo","kind":"typeIdentifier","text":"GFPLoadResponseInfo"},{"kind":"text","text":"?)"}],"url":"\/documentation\/gfpsdk\/gfpinterstitialadmanagerdelegate\/interstitialadmanager(_:didfailwitherror:responseinfo:)","title":"interstitialAdManager(_:didFailWithError:responseInfo:)","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdManagerDelegate\/interstitialAdManager(_:didFailWithError:responseInfo:)","required":true,"role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPInterstitialAdManagerDelegate/interstitialAdManager(_:didLoad:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"interstitialAdManager"},{"kind":"text","text":"("},{"text":"GFPInterstitialAdManager","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPInterstitialAdManager"},{"text":", ","kind":"text"},{"text":"didLoad","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"GFPInterstitialAd","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPInterstitialAd"},{"text":")","kind":"text"}],"title":"interstitialAdManager(_:didLoad:)","navigatorTitle":[{"text":"interstitialAdManager:didLoadAd:","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpinterstitialadmanagerdelegate\/interstitialadmanager(_:didload:)","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdManagerDelegate\/interstitialAdManager(_:didLoad:)","role":"symbol","type":"topic","kind":"symbol","abstract":[],"required":true},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPInterstitialAdManagerDelegate/interstitialAdManager(_:didComplete:)":{"kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdManagerDelegate\/interstitialAdManager(_:didComplete:)","url":"\/documentation\/gfpsdk\/gfpinterstitialadmanagerdelegate\/interstitialadmanager(_:didcomplete:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"interstitialAdManager"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPInterstitialAdManager","text":"GFPInterstitialAdManager"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didComplete"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)GFPInterstitialAd","kind":"typeIdentifier","text":"GFPInterstitialAd"},{"text":")","kind":"text"}],"title":"interstitialAdManager(_:didComplete:)","role":"symbol","type":"topic","required":true,"navigatorTitle":[{"text":"interstitialAdManager:didCompleteAd:","kind":"identifier"}],"abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPInterstitialAdManagerDelegate/interstitialAdManager(_:wasClickedAd:)":{"url":"\/documentation\/gfpsdk\/gfpinterstitialadmanagerdelegate\/interstitialadmanager(_:wasclickedad:)","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdManagerDelegate\/interstitialAdManager(_:wasClickedAd:)","kind":"symbol","title":"interstitialAdManager(_:wasClickedAd:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"interstitialAdManager","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPInterstitialAdManager","kind":"typeIdentifier","text":"GFPInterstitialAdManager"},{"text":", ","kind":"text"},{"text":"wasClickedAd","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)GFPInterstitialAd","text":"GFPInterstitialAd","kind":"typeIdentifier"},{"kind":"text","text":")"}],"abstract":[],"navigatorTitle":[{"text":"interstitialAdManager:wasClickedAd:","kind":"identifier"}],"required":true,"role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPInterstitialAdManagerDelegate/interstitialAdManager(_:didStart:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"interstitialAdManager"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPInterstitialAdManager","text":"GFPInterstitialAdManager"},{"kind":"text","text":", "},{"text":"didStart","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GFPInterstitialAd","preciseIdentifier":"c:objc(cs)GFPInterstitialAd"},{"text":")","kind":"text"}],"title":"interstitialAdManager(_:didStart:)","navigatorTitle":[{"kind":"identifier","text":"interstitialAdManager:didStartAd:"}],"url":"\/documentation\/gfpsdk\/gfpinterstitialadmanagerdelegate\/interstitialadmanager(_:didstart:)","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdManagerDelegate\/interstitialAdManager(_:didStart:)","role":"symbol","type":"topic","kind":"symbol","abstract":[],"required":true}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"GFPInterstitialAdManagerDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GFPInterstitialAdManagerDelegate"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"GFPInterstitialAdManagerDelegate"}]},{"path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdManagerDelegate\/interstitialAdManager(_:didClose:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdManagerDelegate\/interstitialAdManager(_:didComplete:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdManagerDelegate\/interstitialAdManager(_:didFailWithError:responseInfo:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdManagerDelegate\/interstitialAdManager(_:didLoad:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdManagerDelegate\/interstitialAdManager(_:didStart:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdManagerDelegate\/interstitialAdManager(_:wasClickedAd:)"],"anchor":"Instance-Methods","generated":true}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject"],"type":"inheritsFrom"}],"op":"replace"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPInterstitialAdManagerDelegate"},{"text":" <","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier"},{"text":">","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdManagerDelegate~1interstitialAdManager(_:didClose:)\/title","value":"interstitialAdManager:didCloseAd:","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdManagerDelegate~1interstitialAdManager(_:didClose:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"interstitialAdManager:didCloseAd:","kind":"identifier"}]},{"op":"replace","value":"GFPInterstitialAdManagerDelegate","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdManagerDelegate\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdManagerDelegate\/fragments","value":[{"text":"GFPInterstitialAdManagerDelegate","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdManagerDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"GFPInterstitialAdManagerDelegate"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdManagerDelegate~1interstitialAdManager(_:didFailWithError:responseInfo:)\/title","value":"interstitialAdManager:didFailWithError:responseInfo:","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdManagerDelegate~1interstitialAdManager(_:didFailWithError:responseInfo:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"interstitialAdManager:didFailWithError:responseInfo:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdManagerDelegate~1interstitialAdManager(_:didLoad:)\/title","value":"interstitialAdManager:didLoadAd:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"interstitialAdManager:didLoadAd:"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdManagerDelegate~1interstitialAdManager(_:didLoad:)\/fragments"},{"value":"interstitialAdManager:didCompleteAd:","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdManagerDelegate~1interstitialAdManager(_:didComplete:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"interstitialAdManager:didCompleteAd:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdManagerDelegate~1interstitialAdManager(_:didComplete:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdManagerDelegate~1interstitialAdManager(_:wasClickedAd:)\/title","value":"interstitialAdManager:wasClickedAd:"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdManagerDelegate~1interstitialAdManager(_:wasClickedAd:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"interstitialAdManager:wasClickedAd:","kind":"identifier"}],"op":"replace"},{"value":"interstitialAdManager:didStartAd:","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdManagerDelegate~1interstitialAdManager(_:didStart:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"interstitialAdManager:didStartAd:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdManagerDelegate~1interstitialAdManager(_:didStart:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}