{"metadata":{"externalID":"c:objc(pl)GFPInterstitialAdAdaptorDelegate","modules":[{"name":"GFPSDK"}],"roleHeading":"Protocol","title":"GFPInterstitialAdAdaptorDelegate","role":"symbol","symbolKind":"protocol","navigatorTitle":[{"kind":"identifier","text":"GFPInterstitialAdAdaptorDelegate"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPInterstitialAdAdaptorDelegate"}]},"topicSections":[{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdAdaptorDelegate\/interstitialAdAdaptor(_:didFailWithError:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdAdaptorDelegate\/interstitialAdAdaptorRecieveImpression(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdAdaptorDelegate\/interstitialAdDidClose(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdAdaptorDelegate\/interstitialAdDidComplete(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdAdaptorDelegate\/interstitialAdDidStart(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdAdaptorDelegate\/interstitialAdWasClicked(_:)"],"anchor":"Instance-Methods","generated":true,"title":"Instance Methods"}],"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdAdaptorDelegate","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpinterstitialadadaptordelegate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpinterstitialadadaptordelegate"]}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"GFPInterstitialAdAdaptorDelegate","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject","text":"NSObjectProtocol"}]}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPInterstitialAdAdaptorDelegate":{"url":"\/documentation\/gfpsdk\/gfpinterstitialadadaptordelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPInterstitialAdAdaptorDelegate","kind":"identifier"}],"role":"symbol","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdAdaptorDelegate","title":"GFPInterstitialAdAdaptorDelegate","navigatorTitle":[{"text":"GFPInterstitialAdAdaptorDelegate","kind":"identifier"}],"type":"topic","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPInterstitialAdAdaptorDelegate/interstitialAdDidStart(_:)":{"title":"interstitialAdDidStart(_:)","type":"topic","abstract":[],"url":"\/documentation\/gfpsdk\/gfpinterstitialadadaptordelegate\/interstitialaddidstart(_:)","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdAdaptorDelegate\/interstitialAdDidStart(_:)","required":true,"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"interstitialAdDidStart:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"interstitialAdDidStart"},{"text":"(any ","kind":"text"},{"text":"GFPAdAdaptor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdAdaptor"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)GFPInterstitialAdAdapting","text":"GFPInterstitialAdAdapting"},{"text":")","kind":"text"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPInterstitialAdAdaptorDelegate/interstitialAdWasClicked(_:)":{"url":"\/documentation\/gfpsdk\/gfpinterstitialadadaptordelegate\/interstitialadwasclicked(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"interstitialAdWasClicked"},{"text":"(any ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPAdAdaptor","text":"GFPAdAdaptor","kind":"typeIdentifier"},{"kind":"text","text":" & "},{"text":"GFPInterstitialAdAdapting","preciseIdentifier":"c:objc(pl)GFPInterstitialAdAdapting","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdAdaptorDelegate\/interstitialAdWasClicked(_:)","title":"interstitialAdWasClicked(_:)","navigatorTitle":[{"text":"interstitialAdWasClicked:","kind":"identifier"}],"type":"topic","kind":"symbol","required":true},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPInterstitialAdAdaptorDelegate/interstitialAdAdaptorRecieveImpression(_:)":{"url":"\/documentation\/gfpsdk\/gfpinterstitialadadaptordelegate\/interstitialadadaptorrecieveimpression(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"interstitialAdAdaptorRecieveImpression","kind":"identifier"},{"kind":"text","text":"(any "},{"preciseIdentifier":"c:objc(cs)GFPAdAdaptor","text":"GFPAdAdaptor","kind":"typeIdentifier"},{"text":" & ","kind":"text"},{"preciseIdentifier":"c:objc(pl)GFPInterstitialAdAdapting","kind":"typeIdentifier","text":"GFPInterstitialAdAdapting"},{"kind":"text","text":")"}],"role":"symbol","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdAdaptorDelegate\/interstitialAdAdaptorRecieveImpression(_:)","title":"interstitialAdAdaptorRecieveImpression(_:)","navigatorTitle":[{"text":"interstitialAdAdaptorRecieveImpression:","kind":"identifier"}],"type":"topic","kind":"symbol","required":true},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPInterstitialAdAdaptorDelegate/interstitialAdAdaptor(_:didFailWithError:)":{"role":"symbol","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"interstitialAdAdaptor","kind":"identifier"},{"text":"(any ","kind":"text"},{"text":"GFPAdAdaptor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdAdaptor"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"GFPInterstitialAdAdapting","preciseIdentifier":"c:objc(pl)GFPInterstitialAdAdapting"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didFailWithError"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@NaverAdsServices@objc(cs)GFPError","text":"GFPError","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdAdaptorDelegate\/interstitialAdAdaptor(_:didFailWithError:)","url":"\/documentation\/gfpsdk\/gfpinterstitialadadaptordelegate\/interstitialadadaptor(_:didfailwitherror:)","required":true,"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"interstitialAdAdaptor:didFailWithError:"}],"title":"interstitialAdAdaptor(_:didFailWithError:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPInterstitialAdAdaptorDelegate/interstitialAdDidComplete(_:)":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdAdaptorDelegate\/interstitialAdDidComplete(_:)","kind":"symbol","abstract":[],"type":"topic","navigatorTitle":[{"text":"interstitialAdDidComplete:","kind":"identifier"}],"required":true,"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"interstitialAdDidComplete","kind":"identifier"},{"kind":"text","text":"(any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdAdaptor","text":"GFPAdAdaptor"},{"text":" & ","kind":"text"},{"kind":"typeIdentifier","text":"GFPInterstitialAdAdapting","preciseIdentifier":"c:objc(pl)GFPInterstitialAdAdapting"},{"kind":"text","text":")"}],"role":"symbol","title":"interstitialAdDidComplete(_:)","url":"\/documentation\/gfpsdk\/gfpinterstitialadadaptordelegate\/interstitialaddidcomplete(_:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPInterstitialAdAdaptorDelegate/interstitialAdDidClose(_:)":{"role":"symbol","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"interstitialAdDidClose","kind":"identifier"},{"kind":"text","text":"(any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdAdaptor","text":"GFPAdAdaptor"},{"text":" & ","kind":"text"},{"text":"GFPInterstitialAdAdapting","preciseIdentifier":"c:objc(pl)GFPInterstitialAdAdapting","kind":"typeIdentifier"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdAdaptorDelegate\/interstitialAdDidClose(_:)","url":"\/documentation\/gfpsdk\/gfpinterstitialadadaptordelegate\/interstitialaddidclose(_:)","required":true,"abstract":[],"navigatorTitle":[{"text":"interstitialAdDidClose:","kind":"identifier"}],"title":"interstitialAdDidClose(_:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Protocol","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"GFPInterstitialAdAdaptorDelegate"},{"path":"\/metadata\/symbolKind","value":"protocol","op":"replace"},{"value":[{"kind":"identifier","text":"GFPInterstitialAdAdaptorDelegate"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"GFPInterstitialAdAdaptorDelegate"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdAdaptorDelegate\/interstitialAdAdaptor(_:didFailWithError:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdAdaptorDelegate\/interstitialAdAdaptorRecieveImpression(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdAdaptorDelegate\/interstitialAdDidClose(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdAdaptorDelegate\/interstitialAdDidComplete(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdAdaptorDelegate\/interstitialAdDidStart(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdAdaptorDelegate\/interstitialAdWasClicked(_:)"],"generated":true}]},{"op":"replace","value":[{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@protocol"},{"text":" ","kind":"text"},{"text":"GFPInterstitialAdAdaptorDelegate","kind":"identifier"},{"kind":"text","text":" <"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(pl)NSObject"},{"kind":"text","text":">"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdAdaptorDelegate\/title","value":"GFPInterstitialAdAdaptorDelegate"},{"value":[{"kind":"identifier","text":"GFPInterstitialAdAdaptorDelegate"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdAdaptorDelegate\/fragments","op":"replace"},{"value":[{"text":"GFPInterstitialAdAdaptorDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdAdaptorDelegate\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdAdaptorDelegate~1interstitialAdDidStart(_:)\/title","value":"interstitialAdDidStart:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdAdaptorDelegate~1interstitialAdDidStart(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"interstitialAdDidStart:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdAdaptorDelegate~1interstitialAdWasClicked(_:)\/title","value":"interstitialAdWasClicked:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"interstitialAdWasClicked:"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdAdaptorDelegate~1interstitialAdWasClicked(_:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdAdaptorDelegate~1interstitialAdAdaptorRecieveImpression(_:)\/title","value":"interstitialAdAdaptorRecieveImpression:"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdAdaptorDelegate~1interstitialAdAdaptorRecieveImpression(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"interstitialAdAdaptorRecieveImpression:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdAdaptorDelegate~1interstitialAdAdaptor(_:didFailWithError:)\/title","op":"replace","value":"interstitialAdAdaptor:didFailWithError:"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdAdaptorDelegate~1interstitialAdAdaptor(_:didFailWithError:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"interstitialAdAdaptor:didFailWithError:","kind":"identifier"}]},{"op":"replace","value":"interstitialAdDidComplete:","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdAdaptorDelegate~1interstitialAdDidComplete(_:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"interstitialAdDidComplete:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdAdaptorDelegate~1interstitialAdDidComplete(_:)\/fragments"},{"value":"interstitialAdDidClose:","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdAdaptorDelegate~1interstitialAdDidClose(_:)\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdAdaptorDelegate~1interstitialAdDidClose(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"interstitialAdDidClose:","kind":"identifier"}],"op":"replace"}]}]}