{"kind":"symbol","topicSections":[{"generated":true,"title":"Initializers","anchor":"Initializers","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionType\/init(rawValue:)"]},{"title":"Type Properties","generated":true,"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionType\/bounce","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionType\/custom","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionType\/render","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionType\/slot","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionType\/viewable"],"anchor":"Type-Properties"},{"generated":true,"title":"Default Implementations","anchor":"Default-Implementations","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionType\/Equatable-Implementations","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionType\/OptionSet-Implementations","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionType\/SetAlgebra-Implementations"]}],"relationshipsSections":[{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/s15BitwiseCopyableP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s25ExpressibleByArrayLiteralP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s9OptionSetP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SY","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s8SendableP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s10SetAlgebraP"]}],"metadata":{"roleHeading":"Structure","symbolKind":"struct","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPImpressionType","kind":"identifier"}],"externalID":"c:@E@GFPImpressionType","title":"GFPImpressionType","navigatorTitle":[{"kind":"identifier","text":"GFPImpressionType"}],"modules":[{"name":"GFPSDK"}],"role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"GFPImpressionType","kind":"identifier"}],"platforms":["iOS"]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionType","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"variants":[{"paths":["\/documentation\/gfpsdk\/gfpimpressiontype"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpimpressiontype"]}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPImpressionType":{"url":"\/documentation\/gfpsdk\/gfpimpressiontype","navigatorTitle":[{"text":"GFPImpressionType","kind":"identifier"}],"type":"topic","title":"GFPImpressionType","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionType","role":"symbol","abstract":[],"kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPImpressionType"}]},"doc://com.navercorp.da.gfp.GFPSDK/s8SendableP":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s8SendableP","title":"Swift.Sendable"},"doc://com.navercorp.da.gfp.GFPSDK/s10SetAlgebraP":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s10SetAlgebraP","title":"Swift.SetAlgebra"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPImpressionType/custom":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"custom"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GFPImpressionType","preciseIdentifier":"c:@E@GFPImpressionType"}],"abstract":[],"url":"\/documentation\/gfpsdk\/gfpimpressiontype\/custom","navigatorTitle":[{"text":"GFPImpressionTypeCustom","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionType\/custom","type":"topic","title":"custom","role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPImpressionType/Equatable-Implementations":{"title":"Equatable Implementations","abstract":[],"type":"topic","role":"collectionGroup","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionType\/Equatable-Implementations","url":"\/documentation\/gfpsdk\/gfpimpressiontype\/equatable-implementations","kind":"article"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPImpressionType/viewable":{"navigatorTitle":[{"text":"GFPImpressionTypeViewable","kind":"identifier"}],"title":"viewable","url":"\/documentation\/gfpsdk\/gfpimpressiontype\/viewable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionType\/viewable","role":"symbol","type":"topic","kind":"symbol","abstract":[],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewable"},{"kind":"text","text":": "},{"text":"GFPImpressionType","kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPImpressionType"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPImpressionType/render":{"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"render"},{"kind":"text","text":": "},{"text":"GFPImpressionType","kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPImpressionType"}],"abstract":[],"url":"\/documentation\/gfpsdk\/gfpimpressiontype\/render","navigatorTitle":[{"text":"GFPImpressionTypeRender","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionType\/render","type":"topic","title":"render","role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/SQ":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPImpressionType/slot":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"slot"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPImpressionType","text":"GFPImpressionType"}],"abstract":[],"url":"\/documentation\/gfpsdk\/gfpimpressiontype\/slot","navigatorTitle":[{"text":"GFPImpressionTypeSlot","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionType\/slot","type":"topic","title":"slot","role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPImpressionType/SetAlgebra-Implementations":{"title":"SetAlgebra Implementations","role":"collectionGroup","url":"\/documentation\/gfpsdk\/gfpimpressiontype\/setalgebra-implementations","kind":"article","type":"topic","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionType\/SetAlgebra-Implementations"},"doc://com.navercorp.da.gfp.GFPSDK/s15BitwiseCopyableP":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s15BitwiseCopyableP","title":"Swift.BitwiseCopyable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPImpressionType/OptionSet-Implementations":{"title":"OptionSet Implementations","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionType\/OptionSet-Implementations","kind":"article","abstract":[],"url":"\/documentation\/gfpsdk\/gfpimpressiontype\/optionset-implementations","type":"topic","role":"collectionGroup"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPImpressionType/bounce":{"abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionType\/bounce","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"bounce","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@GFPImpressionType","kind":"typeIdentifier","text":"GFPImpressionType"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"GFPImpressionTypeBounce"}],"title":"bounce","url":"\/documentation\/gfpsdk\/gfpimpressiontype\/bounce"},"doc://com.navercorp.da.gfp.GFPSDK/s25ExpressibleByArrayLiteralP":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s25ExpressibleByArrayLiteralP","title":"Swift.ExpressibleByArrayLiteral"},"doc://com.navercorp.da.gfp.GFPSDK/SY":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/s9OptionSetP":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s9OptionSetP","title":"Swift.OptionSet","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPImpressionType/init(rawValue:)":{"title":"init(rawValue:)","kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"text":")","kind":"text"}],"url":"\/documentation\/gfpsdk\/gfpimpressiontype\/init(rawvalue:)","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionType\/init(rawValue:)"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Enumeration","path":"\/metadata\/roleHeading"},{"op":"replace","value":"GFPImpressionType","path":"\/metadata\/title"},{"op":"replace","value":"enum","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GFPImpressionType"}],"op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"GFPImpressionType","kind":"identifier"}]},{"path":"\/topicSections","value":[{"title":"Enumeration Cases","anchor":"Enumeration-Cases","generated":true,"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionType\/bounce","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionType\/custom","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionType\/render","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionType\/slot","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionType\/viewable"]}],"op":"replace"},{"path":"\/relationshipsSections","op":"replace","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPImpressionType"},{"text":": ","kind":"text"},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionType\/title","value":"GFPImpressionType"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionType\/fragments","value":[{"kind":"identifier","text":"GFPImpressionType"}],"op":"replace"},{"value":[{"text":"GFPImpressionType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionType\/navigatorTitle","op":"replace"},{"value":"GFPImpressionTypeCustom","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionType~1custom\/title","op":"replace"},{"value":[{"text":"GFPImpressionTypeCustom","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionType~1custom\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionType~1viewable\/title","value":"GFPImpressionTypeViewable","op":"replace"},{"value":[{"kind":"identifier","text":"GFPImpressionTypeViewable"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionType~1viewable\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionType~1render\/title","value":"GFPImpressionTypeRender"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionType~1render\/fragments","op":"replace","value":[{"text":"GFPImpressionTypeRender","kind":"identifier"}]},{"op":"replace","value":"GFPImpressionTypeSlot","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionType~1slot\/title"},{"value":[{"kind":"identifier","text":"GFPImpressionTypeSlot"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionType~1slot\/fragments"},{"op":"replace","value":"GFPImpressionTypeBounce","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionType~1bounce\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionType~1bounce\/fragments","value":[{"text":"GFPImpressionTypeBounce","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}