{"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpimpressiontrackcompletionhandler"]},{"paths":["\/documentation\/gfpsdk\/gfpimpressiontrackcompletionhandler"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPImpressionTrackCompletionHandler"},{"text":" = (","kind":"text"},{"text":"GFPImpressionTrackingTarget","preciseIdentifier":"c:objc(cs)GFPImpressionTrackingTarget","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionTrackingTarget"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"}],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionTrackCompletionHandler","interfaceLanguage":"swift"},"metadata":{"externalID":"c:GFPImpressionTracker.h@T@GFPImpressionTrackCompletionHandler","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPImpressionTrackCompletionHandler","kind":"identifier"}],"navigatorTitle":[{"text":"GFPImpressionTrackCompletionHandler","kind":"identifier"}],"modules":[{"name":"GFPSDK"}],"symbolKind":"typealias","role":"symbol","roleHeading":"Type Alias","title":"GFPImpressionTrackCompletionHandler"},"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPImpressionTrackCompletionHandler":{"type":"topic","url":"\/documentation\/gfpsdk\/gfpimpressiontrackcompletionhandler","title":"GFPImpressionTrackCompletionHandler","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPImpressionTrackCompletionHandler","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"GFPImpressionTrackCompletionHandler","kind":"identifier"}],"kind":"symbol","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionTrackCompletionHandler"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPImpressionTrackingTarget":{"navigatorTitle":[{"text":"GFPImpressionTrackingTarget","kind":"identifier"}],"title":"GFPImpressionTrackingTarget","url":"\/documentation\/gfpsdk\/gfpimpressiontrackingtarget","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionTrackingTarget","role":"symbol","type":"topic","kind":"symbol","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPImpressionTrackingTarget","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Alias"},{"value":"GFPImpressionTrackCompletionHandler","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"typealias"},{"path":"\/metadata\/fragments","value":[{"text":"GFPImpressionTrackCompletionHandler","kind":"identifier"}],"op":"replace"},{"value":[{"text":"GFPImpressionTrackCompletionHandler","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"typedef"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","text":"void (^)(GFPImpressionTrackingTarget *)","preciseIdentifier":"c:BFv(#*$objc(cs)GFPImpressionTrackingTarget)"},{"text":" ","kind":"text"},{"text":"GFPImpressionTrackCompletionHandler","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTrackCompletionHandler\/title","op":"replace","value":"GFPImpressionTrackCompletionHandler"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTrackCompletionHandler\/fragments","value":[{"text":"GFPImpressionTrackCompletionHandler","kind":"identifier"}]},{"op":"replace","value":[{"text":"GFPImpressionTrackCompletionHandler","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTrackCompletionHandler\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTrackingTarget\/title","value":"GFPImpressionTrackingTarget"},{"value":[{"text":"GFPImpressionTrackingTarget","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTrackingTarget\/fragments"},{"op":"replace","value":[{"text":"GFPImpressionTrackingTarget","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTrackingTarget\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}