{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPImpressionTrackCustomViews","kind":"identifier"},{"kind":"text","text":" = () -> ["},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"},{"text":"]?","kind":"text"}],"languages":["swift"]}]}],"metadata":{"externalID":"c:GFPImpressionTracker.h@T@GFPImpressionTrackCustomViews","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"GFPImpressionTrackCustomViews","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"GFPImpressionTrackCustomViews"}],"modules":[{"name":"GFPSDK"}],"symbolKind":"typealias","role":"symbol","roleHeading":"Type Alias","title":"GFPImpressionTrackCustomViews"},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionTrackCustomViews"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","variants":[{"paths":["\/documentation\/gfpsdk\/gfpimpressiontrackcustomviews"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpimpressiontrackcustomviews"]}],"sections":[],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPImpressionTrackCustomViews":{"fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"GFPImpressionTrackCustomViews","kind":"identifier"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"GFPImpressionTrackCustomViews"}],"url":"\/documentation\/gfpsdk\/gfpimpressiontrackcustomviews","kind":"symbol","type":"topic","role":"symbol","title":"GFPImpressionTrackCustomViews","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionTrackCustomViews"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Type Alias","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"GFPImpressionTrackCustomViews"},{"value":"typealias","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"GFPImpressionTrackCustomViews","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"GFPImpressionTrackCustomViews"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"typedef","kind":"keyword"},{"kind":"text","text":" "},{"text":"NSArray<UIView *> *(^)(void)","kind":"typeIdentifier","preciseIdentifier":"c:BF*Q$objc(cs)NSArray()"},{"text":" ","kind":"text"},{"text":"GFPImpressionTrackCustomViews","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"value":"GFPImpressionTrackCustomViews","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTrackCustomViews\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTrackCustomViews\/fragments","value":[{"kind":"identifier","text":"GFPImpressionTrackCustomViews"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTrackCustomViews\/navigatorTitle","value":[{"kind":"identifier","text":"GFPImpressionTrackCustomViews"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}