{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpinterstitialadadapting"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpinterstitialadadapting"]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdAdapting","interfaceLanguage":"swift"},"kind":"symbol","topicSections":[{"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdAdapting\/delegate","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdAdapting\/isExpired","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdAdapting\/status"],"generated":true},{"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdAdapting\/isAdInvalidate()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdAdapting\/isAdLoaded()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdAdapting\/requestPresentInterstitialAd(_:)"],"generated":true}],"metadata":{"navigatorTitle":[{"text":"GFPInterstitialAdAdapting","kind":"identifier"}],"role":"symbol","symbolKind":"protocol","roleHeading":"Protocol","externalID":"c:objc(pl)GFPInterstitialAdAdapting","modules":[{"name":"GFPSDK"}],"title":"GFPInterstitialAdAdapting","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"GFPInterstitialAdAdapting","kind":"identifier"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAdapting","doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject"],"type":"inheritsFrom","kind":"relationships"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPInterstitialAdAdapting"},{"text":" : ","kind":"text"},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAdapting","text":"GFPAdAdapting","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)GFPAdAdapting"}],"languages":["swift"]}]}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPInterstitialAdAdapting/isAdInvalidate()":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"isAdInvalidate","kind":"identifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"url":"\/documentation\/gfpsdk\/gfpinterstitialadadapting\/isadinvalidate()","navigatorTitle":[{"kind":"identifier","text":"isAdInvalidate"}],"required":true,"kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdAdapting\/isAdInvalidate()","type":"topic","title":"isAdInvalidate()","role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPInterstitialAdAdapting/isAdLoaded()":{"type":"topic","title":"isAdLoaded()","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isAdLoaded"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"abstract":[],"url":"\/documentation\/gfpsdk\/gfpinterstitialadadapting\/isadloaded()","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"isAdLoaded"}],"required":true,"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdAdapting\/isAdLoaded()"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdAdapting":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"GFPAdAdapting","kind":"identifier"}],"abstract":[],"url":"\/documentation\/gfpsdk\/gfpadadapting","kind":"symbol","role":"symbol","title":"GFPAdAdapting","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAdapting","type":"topic","navigatorTitle":[{"text":"GFPAdAdapting","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPInterstitialAdAdapting/status":{"abstract":[],"url":"\/documentation\/gfpsdk\/gfpinterstitialadadapting\/status","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdAdapting\/status","required":true,"role":"symbol","title":"status","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"status"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@GFPInterstitialStatus","text":"GFPInterstitialStatus","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"status","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPInterstitialAdAdapting/isExpired":{"required":true,"url":"\/documentation\/gfpsdk\/gfpinterstitialadadapting\/isexpired","navigatorTitle":[{"kind":"identifier","text":"isExpired"}],"abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"isExpired","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdAdapting\/isExpired","title":"isExpired"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPInterstitialAdAdapting/requestPresentInterstitialAd(_:)":{"required":true,"role":"symbol","type":"topic","navigatorTitle":[{"text":"requestPresentInterstitialAd:","kind":"identifier"}],"abstract":[],"title":"requestPresentInterstitialAd(_:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"requestPresentInterstitialAd","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier","text":"UIViewController"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdAdapting\/requestPresentInterstitialAd(_:)","url":"\/documentation\/gfpsdk\/gfpinterstitialadadapting\/requestpresentinterstitialad(_:)"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPInterstitialAdAdapting":{"title":"GFPInterstitialAdAdapting","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdAdapting","url":"\/documentation\/gfpsdk\/gfpinterstitialadadapting","abstract":[],"kind":"symbol","navigatorTitle":[{"text":"GFPInterstitialAdAdapting","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"GFPInterstitialAdAdapting","kind":"identifier"}],"type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPInterstitialAdAdapting/delegate":{"navigatorTitle":[{"text":"delegate","kind":"identifier"}],"title":"delegate","type":"topic","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdAdapting\/delegate","url":"\/documentation\/gfpsdk\/gfpinterstitialadadapting\/delegate","abstract":[],"required":true,"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"delegate","kind":"identifier"},{"kind":"text","text":": (any "},{"text":"GFPInterstitialAdAdaptorDelegate","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)GFPInterstitialAdAdaptorDelegate"},{"kind":"text","text":")?"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Protocol","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"GFPInterstitialAdAdapting"},{"value":"protocol","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GFPInterstitialAdAdapting"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"GFPInterstitialAdAdapting"}]},{"value":[{"anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdAdapting\/delegate","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdAdapting\/isExpired","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdAdapting\/status"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdAdapting\/isAdInvalidate()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdAdapting\/isAdLoaded()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdAdapting\/requestPresentInterstitialAd(_:)"],"generated":true,"anchor":"Instance-Methods"}],"op":"replace","path":"\/topicSections"},{"value":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAdapting"]}],"path":"\/relationshipsSections","op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPInterstitialAdAdapting"},{"text":" <","kind":"text"},{"preciseIdentifier":"c:objc(pl)GFPAdAdapting","text":"GFPAdAdapting","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAdapting","kind":"typeIdentifier"},{"text":">","kind":"text"}],"languages":["occ"]}]}},{"value":"isAdInvalidate","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdAdapting~1isAdInvalidate()\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"isAdInvalidate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdAdapting~1isAdInvalidate()\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdAdapting~1isAdLoaded()\/title","op":"replace","value":"isAdLoaded"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdAdapting~1isAdLoaded()\/fragments","value":[{"kind":"text","text":"- "},{"text":"isAdLoaded","kind":"identifier"}]},{"op":"replace","value":"GFPAdAdapting","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdapting\/title"},{"value":[{"kind":"identifier","text":"GFPAdAdapting"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdapting\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdapting\/navigatorTitle","value":[{"kind":"identifier","text":"GFPAdAdapting"}]},{"op":"replace","value":"status","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdAdapting~1status\/title"},{"value":[{"kind":"identifier","text":"status"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdAdapting~1status\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdAdapting~1isExpired\/title","op":"replace","value":"isExpired"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdAdapting~1isExpired\/fragments","value":[{"kind":"identifier","text":"isExpired"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdAdapting~1requestPresentInterstitialAd(_:)\/title","value":"requestPresentInterstitialAd:"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdAdapting~1requestPresentInterstitialAd(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"requestPresentInterstitialAd:","kind":"identifier"}],"op":"replace"},{"value":"GFPInterstitialAdAdapting","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdAdapting\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdAdapting\/fragments","value":[{"kind":"identifier","text":"GFPInterstitialAdAdapting"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdAdapting\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"GFPInterstitialAdAdapting"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdAdapting~1delegate\/title","value":"delegate"},{"value":[{"kind":"identifier","text":"delegate"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdAdapting~1delegate\/fragments"}]}]}