{"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpimpressiontrackcustomcompletecheckhandler"]},{"paths":["\/documentation\/gfpsdk\/gfpimpressiontrackcustomcompletecheckhandler"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"role":"symbol","title":"GFPImpressionTrackCustomCompleteCheckHandler","modules":[{"name":"GFPSDK"}],"fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPImpressionTrackCustomCompleteCheckHandler"}],"symbolKind":"typealias","externalID":"c:GFPImpressionTracker.h@T@GFPImpressionTrackCustomCompleteCheckHandler","roleHeading":"Type Alias","navigatorTitle":[{"text":"GFPImpressionTrackCustomCompleteCheckHandler","kind":"identifier"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionTrackCustomCompleteCheckHandler"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPImpressionTrackCustomCompleteCheckHandler"},{"text":" = () -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"platforms":["iOS"]}]}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPImpressionTrackCustomCompleteCheckHandler":{"navigatorTitle":[{"text":"GFPImpressionTrackCustomCompleteCheckHandler","kind":"identifier"}],"title":"GFPImpressionTrackCustomCompleteCheckHandler","abstract":[],"type":"topic","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionTrackCustomCompleteCheckHandler","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPImpressionTrackCustomCompleteCheckHandler"}],"url":"\/documentation\/gfpsdk\/gfpimpressiontrackcustomcompletecheckhandler","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Alias"},{"op":"replace","value":"GFPImpressionTrackCustomCompleteCheckHandler","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"typealias"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"GFPImpressionTrackCustomCompleteCheckHandler","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"GFPImpressionTrackCustomCompleteCheckHandler"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"typedef"},{"text":" ","kind":"text"},{"text":"_Bool (^)(void)","kind":"typeIdentifier","preciseIdentifier":"c:BFb()"},{"text":" ","kind":"text"},{"text":"GFPImpressionTrackCustomCompleteCheckHandler","kind":"identifier"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTrackCustomCompleteCheckHandler\/title","op":"replace","value":"GFPImpressionTrackCustomCompleteCheckHandler"},{"value":[{"kind":"identifier","text":"GFPImpressionTrackCustomCompleteCheckHandler"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTrackCustomCompleteCheckHandler\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTrackCustomCompleteCheckHandler\/navigatorTitle","op":"replace","value":[{"text":"GFPImpressionTrackCustomCompleteCheckHandler","kind":"identifier"}]}]}]}