{"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"topicSections":[{"title":"Enumeration Cases","anchor":"Enumeration-Cases","generated":true,"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLanguageType\/de","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLanguageType\/en","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLanguageType\/es","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLanguageType\/fr","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLanguageType\/id","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLanguageType\/ja","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLanguageType\/ko","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLanguageType\/none","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLanguageType\/th","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLanguageType\/zh_Hans","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLanguageType\/zh_Hant"]},{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLanguageType\/init(rawValue:)"],"anchor":"Initializers","title":"Initializers","generated":true},{"title":"Default Implementations","generated":true,"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLanguageType\/Equatable-Implementations","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLanguageType\/RawRepresentable-Implementations"],"anchor":"Default-Implementations"}],"metadata":{"roleHeading":"Enumeration","role":"symbol","navigatorTitle":[{"text":"GFPLanguageType","kind":"identifier"}],"externalID":"c:@E@GFPLanguageType","symbolKind":"enum","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPLanguageType"}],"title":"GFPLanguageType","modules":[{"name":"GFPSDK"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPLanguageType","kind":"identifier"}]}]}],"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLanguageType","interfaceLanguage":"swift"},"relationshipsSections":[{"title":"Conforms To","type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/s15BitwiseCopyableP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SY","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s8SendableP"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfplanguagetype"]},{"paths":["\/documentation\/gfpsdk\/gfplanguagetype"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/SH":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.navercorp.da.gfp.GFPSDK/SY":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SY","type":"unresolvable","title":"Swift.RawRepresentable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPLanguageType/zh_Hans":{"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"zh_Hans","kind":"identifier"}],"kind":"symbol","title":"GFPLanguageType.zh_Hans","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLanguageType\/zh_Hans","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"GFPLanguageType_zh_Hans"}],"url":"\/documentation\/gfpsdk\/gfplanguagetype\/zh_hans"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPLanguageType/id":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLanguageType\/id","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"id","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"GFPLanguageType_id","kind":"identifier"}],"title":"GFPLanguageType.id","type":"topic","url":"\/documentation\/gfpsdk\/gfplanguagetype\/id","abstract":[],"role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPLanguageType/init(rawValue:)":{"type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"kind":"symbol","title":"init(rawValue:)","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLanguageType\/init(rawValue:)","abstract":[],"url":"\/documentation\/gfpsdk\/gfplanguagetype\/init(rawvalue:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPLanguageType/de":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLanguageType\/de","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"de"}],"kind":"symbol","navigatorTitle":[{"text":"GFPLanguageType_de","kind":"identifier"}],"title":"GFPLanguageType.de","type":"topic","url":"\/documentation\/gfpsdk\/gfplanguagetype\/de","abstract":[],"role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPLanguageType/none":{"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"none"}],"kind":"symbol","title":"GFPLanguageType.none","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLanguageType\/none","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"GFPLanguageType_none"}],"url":"\/documentation\/gfpsdk\/gfplanguagetype\/none"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPLanguageType/en":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLanguageType\/en","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"en"}],"kind":"symbol","navigatorTitle":[{"text":"GFPLanguageType_en","kind":"identifier"}],"title":"GFPLanguageType.en","type":"topic","url":"\/documentation\/gfpsdk\/gfplanguagetype\/en","abstract":[],"role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/s8SendableP":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s8SendableP","title":"Swift.Sendable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPLanguageType/zh_Hant":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLanguageType\/zh_Hant","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"zh_Hant"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPLanguageType_zh_Hant"}],"title":"GFPLanguageType.zh_Hant","type":"topic","url":"\/documentation\/gfpsdk\/gfplanguagetype\/zh_hant","abstract":[],"role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPLanguageType/fr":{"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"fr"}],"kind":"symbol","title":"GFPLanguageType.fr","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLanguageType\/fr","abstract":[],"navigatorTitle":[{"text":"GFPLanguageType_fr","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfplanguagetype\/fr"},"doc://com.navercorp.da.gfp.GFPSDK/s15BitwiseCopyableP":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s15BitwiseCopyableP","title":"Swift.BitwiseCopyable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPLanguageType/Equatable-Implementations":{"type":"topic","kind":"article","title":"Equatable Implementations","role":"collectionGroup","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLanguageType\/Equatable-Implementations","abstract":[],"url":"\/documentation\/gfpsdk\/gfplanguagetype\/equatable-implementations"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPLanguageType/es":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLanguageType\/es","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"es"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPLanguageType_es"}],"title":"GFPLanguageType.es","type":"topic","url":"\/documentation\/gfpsdk\/gfplanguagetype\/es","abstract":[],"role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPLanguageType/ja":{"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"ja"}],"kind":"symbol","title":"GFPLanguageType.ja","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLanguageType\/ja","abstract":[],"navigatorTitle":[{"text":"GFPLanguageType_ja","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfplanguagetype\/ja"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPLanguageType/RawRepresentable-Implementations":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLanguageType\/RawRepresentable-Implementations","kind":"article","title":"RawRepresentable Implementations","type":"topic","url":"\/documentation\/gfpsdk\/gfplanguagetype\/rawrepresentable-implementations","abstract":[],"role":"collectionGroup"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPLanguageType/ko":{"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ko"}],"kind":"symbol","title":"GFPLanguageType.ko","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLanguageType\/ko","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"GFPLanguageType_ko"}],"url":"\/documentation\/gfpsdk\/gfplanguagetype\/ko"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPLanguageType":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLanguageType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPLanguageType"}],"kind":"symbol","navigatorTitle":[{"text":"GFPLanguageType","kind":"identifier"}],"title":"GFPLanguageType","type":"topic","url":"\/documentation\/gfpsdk\/gfplanguagetype","abstract":[],"role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPLanguageType/th":{"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"th"}],"kind":"symbol","title":"GFPLanguageType.th","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLanguageType\/th","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"GFPLanguageType_th"}],"url":"\/documentation\/gfpsdk\/gfplanguagetype\/th"},"doc://com.navercorp.da.gfp.GFPSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","title":"Swift.Equatable"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"path":"\/metadata\/title","value":"GFPLanguageType","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"GFPLanguageType","kind":"identifier"}]},{"value":[{"text":"GFPLanguageType","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","generated":true,"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLanguageType\/de","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLanguageType\/en","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLanguageType\/es","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLanguageType\/fr","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLanguageType\/id","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLanguageType\/ja","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLanguageType\/ko","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLanguageType\/none","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLanguageType\/th","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLanguageType\/zh_Hans","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLanguageType\/zh_Hant"],"anchor":"Enumeration-Cases"}]},{"value":null,"op":"replace","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPLanguageType"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"GFPLanguageType_zh_Hans","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLanguageType~1zh_Hans\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLanguageType~1zh_Hans\/fragments","op":"replace","value":[{"kind":"identifier","text":"GFPLanguageType_zh_Hans"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLanguageType~1id\/title","op":"replace","value":"GFPLanguageType_id"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLanguageType~1id\/fragments","op":"replace","value":[{"kind":"identifier","text":"GFPLanguageType_id"}]},{"op":"replace","value":"GFPLanguageType_de","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLanguageType~1de\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLanguageType~1de\/fragments","value":[{"text":"GFPLanguageType_de","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLanguageType~1none\/title","value":"GFPLanguageType_none"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLanguageType~1none\/fragments","op":"replace","value":[{"kind":"identifier","text":"GFPLanguageType_none"}]},{"value":"GFPLanguageType_en","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLanguageType~1en\/title","op":"replace"},{"value":[{"text":"GFPLanguageType_en","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLanguageType~1en\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLanguageType~1zh_Hant\/title","value":"GFPLanguageType_zh_Hant","op":"replace"},{"value":[{"text":"GFPLanguageType_zh_Hant","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLanguageType~1zh_Hant\/fragments"},{"value":"GFPLanguageType_fr","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLanguageType~1fr\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"GFPLanguageType_fr"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLanguageType~1fr\/fragments"},{"value":"GFPLanguageType_es","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLanguageType~1es\/title"},{"op":"replace","value":[{"kind":"identifier","text":"GFPLanguageType_es"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLanguageType~1es\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLanguageType~1ja\/title","value":"GFPLanguageType_ja","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLanguageType~1ja\/fragments","value":[{"text":"GFPLanguageType_ja","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"GFPLanguageType_ko","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLanguageType~1ko\/title"},{"value":[{"kind":"identifier","text":"GFPLanguageType_ko"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLanguageType~1ko\/fragments"},{"value":"GFPLanguageType","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLanguageType\/title"},{"value":[{"text":"GFPLanguageType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLanguageType\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLanguageType\/navigatorTitle","value":[{"kind":"identifier","text":"GFPLanguageType"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLanguageType~1th\/title","op":"replace","value":"GFPLanguageType_th"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLanguageType~1th\/fragments","value":[{"text":"GFPLanguageType_th","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}