{"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfploudnessnormalization"]},{"paths":["\/documentation\/gfpsdk\/gfploudnessnormalization"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPCreativeExtension"]},{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s7CVarArgP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s23CustomStringConvertibleP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"GFPLoudnessNormalization","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"externalID":"c:objc(cs)GFPLoudnessNormalization","navigatorTitle":[{"text":"GFPLoudnessNormalization","kind":"identifier"}],"title":"GFPLoudnessNormalization","role":"symbol","symbolKind":"class","roleHeading":"Class","modules":[{"name":"GFPSDK"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPLoudnessNormalization","kind":"identifier"}]},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLoudnessNormalization","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","topicSections":[{"generated":true,"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLoudnessNormalization\/contentEncoding","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLoudnessNormalization\/contentType","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLoudnessNormalization\/dataString","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLoudnessNormalization\/enabled","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLoudnessNormalization\/properties","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLoudnessNormalization\/referDict","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLoudnessNormalization\/version"],"anchor":"Instance-Properties","title":"Instance Properties"}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPLoudnessNormalization/contentType":{"abstract":[],"url":"\/documentation\/gfpsdk\/gfploudnessnormalization\/contenttype","role":"symbol","title":"contentType","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLoudnessNormalization\/contentType","type":"topic","navigatorTitle":[{"kind":"identifier","text":"contentType"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"contentType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPLoudnessNormalization/initWithDomElement:error:":{"fragments":[{"kind":"text","text":"- "},{"text":"initWithDomElement:error:","kind":"identifier"}],"navigatorTitle":[{"text":"initWithDomElement:error:","kind":"identifier"}],"abstract":[],"url":"\/documentation\/gfpsdk\/gfploudnessnormalization\/initwithdomelement:error:","type":"topic","kind":"symbol","role":"symbol","title":"initWithDomElement:error:","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLoudnessNormalization\/initWithDomElement:error:"},"doc://com.navercorp.da.gfp.GFPSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPLoudnessNormalization/referDict":{"role":"symbol","abstract":[],"title":"referDict","navigatorTitle":[{"text":"referDict","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"referDict"},{"text":": [","kind":"text"},{"text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"text":"]","kind":"text"}],"url":"\/documentation\/gfpsdk\/gfploudnessnormalization\/referdict","type":"topic","kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLoudnessNormalization\/referDict"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPLoudnessNormalization/enabled":{"navigatorTitle":[{"kind":"identifier","text":"enabled"}],"url":"\/documentation\/gfpsdk\/gfploudnessnormalization\/enabled","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"enabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLoudnessNormalization\/enabled","title":"enabled"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPLoudnessNormalization/properties":{"abstract":[],"type":"topic","title":"properties","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"properties"},{"text":": ","kind":"text"},{"text":"GFPProperties","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPProperties"},{"text":"?","kind":"text"}],"url":"\/documentation\/gfpsdk\/gfploudnessnormalization\/properties","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLoudnessNormalization\/properties","navigatorTitle":[{"kind":"identifier","text":"properties"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPLoudnessNormalization/contentEncoding":{"type":"topic","url":"\/documentation\/gfpsdk\/gfploudnessnormalization\/contentencoding","role":"symbol","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"contentEncoding","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLoudnessNormalization\/contentEncoding","title":"contentEncoding","navigatorTitle":[{"text":"contentEncoding","kind":"identifier"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPCreativeExtension":{"abstract":[],"kind":"symbol","role":"symbol","title":"GFPCreativeExtension","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GFPCreativeExtension"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPCreativeExtension"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPCreativeExtension","url":"\/documentation\/gfpsdk\/gfpcreativeextension"},"doc://com.navercorp.da.gfp.GFPSDK/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s7CVarArgP","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPLoudnessNormalization/version":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"version"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLoudnessNormalization\/version","url":"\/documentation\/gfpsdk\/gfploudnessnormalization\/version","abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"version"}],"title":"version","type":"topic","role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPLoudnessNormalization":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPLoudnessNormalization","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"GFPLoudnessNormalization"}],"kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLoudnessNormalization","type":"topic","role":"symbol","abstract":[],"url":"\/documentation\/gfpsdk\/gfploudnessnormalization","title":"GFPLoudnessNormalization"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPLoudnessNormalization/dataString":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"dataString","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLoudnessNormalization\/dataString","url":"\/documentation\/gfpsdk\/gfploudnessnormalization\/datastring","abstract":[],"kind":"symbol","navigatorTitle":[{"text":"dataString","kind":"identifier"}],"title":"dataString","type":"topic","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"GFPLoudnessNormalization"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GFPLoudnessNormalization"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"GFPLoudnessNormalization","kind":"identifier"}],"op":"replace"},{"value":[{"generated":true,"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLoudnessNormalization\/contentEncoding","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLoudnessNormalization\/contentType","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLoudnessNormalization\/dataString","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLoudnessNormalization\/enabled","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLoudnessNormalization\/properties","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLoudnessNormalization\/referDict","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLoudnessNormalization\/version"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLoudnessNormalization\/initWithDomElement:error:"],"generated":true,"anchor":"Instance-Methods"}],"op":"replace","path":"\/topicSections"},{"value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPCreativeExtension"],"type":"inheritsFrom"}],"op":"replace","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"GFPLoudnessNormalization","kind":"identifier"},{"kind":"text","text":" : "},{"text":"GFPCreativeExtension","preciseIdentifier":"c:objc(cs)GFPCreativeExtension","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPCreativeExtension"}]}]}},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLoudnessNormalization~1contentType\/title","value":"contentType","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLoudnessNormalization~1contentType\/fragments","value":[{"kind":"identifier","text":"contentType"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLoudnessNormalization~1referDict\/title","value":"referDict","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"referDict"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLoudnessNormalization~1referDict\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLoudnessNormalization~1enabled\/title","op":"replace","value":"enabled"},{"value":[{"kind":"identifier","text":"enabled"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLoudnessNormalization~1enabled\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLoudnessNormalization~1properties\/title","value":"properties","op":"replace"},{"op":"replace","value":[{"text":"properties","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLoudnessNormalization~1properties\/fragments"},{"op":"replace","value":"contentEncoding","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLoudnessNormalization~1contentEncoding\/title"},{"value":[{"kind":"identifier","text":"contentEncoding"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLoudnessNormalization~1contentEncoding\/fragments","op":"replace"},{"value":"GFPCreativeExtension","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPCreativeExtension\/title","op":"replace"},{"value":[{"kind":"identifier","text":"GFPCreativeExtension"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPCreativeExtension\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPCreativeExtension\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"GFPCreativeExtension"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLoudnessNormalization~1version\/title","value":"version","op":"replace"},{"op":"replace","value":[{"text":"version","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLoudnessNormalization~1version\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLoudnessNormalization\/title","value":"GFPLoudnessNormalization"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLoudnessNormalization\/fragments","value":[{"kind":"identifier","text":"GFPLoudnessNormalization"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLoudnessNormalization\/navigatorTitle","value":[{"kind":"identifier","text":"GFPLoudnessNormalization"}]},{"op":"replace","value":"dataString","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLoudnessNormalization~1dataString\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLoudnessNormalization~1dataString\/fragments","op":"replace","value":[{"kind":"identifier","text":"dataString"}]}]}]}