{"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLoadEventStat"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfploadeventstat"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfploadeventstat"]}],"topicSections":[{"title":"Enumeration Cases","generated":true,"anchor":"Enumeration-Cases","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLoadEventStat\/adSelected","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLoadEventStat\/error","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLoadEventStat\/noFill","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLoadEventStat\/timeout"]},{"anchor":"Initializers","generated":true,"title":"Initializers","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLoadEventStat\/init(rawValue:)"]},{"anchor":"Default-Implementations","title":"Default Implementations","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLoadEventStat\/Equatable-Implementations","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLoadEventStat\/RawRepresentable-Implementations"],"generated":true}],"kind":"symbol","relationshipsSections":[{"title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/s15BitwiseCopyableP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SY","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s8SendableP"],"kind":"relationships"}],"metadata":{"modules":[{"name":"GFPSDK"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPLoadEventStat","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"GFPLoadEventStat"}],"role":"symbol","roleHeading":"Enumeration","title":"GFPLoadEventStat","symbolKind":"enum","externalID":"c:@E@GFPLoadEventStat"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPLoadEventStat","kind":"identifier"}]}]}],"sections":[],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPLoadEventStat/error":{"kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLoadEventStat\/error","navigatorTitle":[{"text":"GFPLoadEventStatError","kind":"identifier"}],"type":"topic","abstract":[{"text":"Don’t change the value. This is the value defined in the specification.","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"error"}],"role":"symbol","url":"\/documentation\/gfpsdk\/gfploadeventstat\/error","title":"GFPLoadEventStat.error"},"doc://com.navercorp.da.gfp.GFPSDK/s15BitwiseCopyableP":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s15BitwiseCopyableP","title":"Swift.BitwiseCopyable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPLoadEventStat":{"url":"\/documentation\/gfpsdk\/gfploadeventstat","title":"GFPLoadEventStat","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLoadEventStat","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"GFPLoadEventStat","kind":"identifier"}],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPLoadEventStat"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPLoadEventStat/Equatable-Implementations":{"role":"collectionGroup","abstract":[],"title":"Equatable Implementations","url":"\/documentation\/gfpsdk\/gfploadeventstat\/equatable-implementations","type":"topic","kind":"article","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLoadEventStat\/Equatable-Implementations"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPLoadEventStat/init(rawValue:)":{"title":"init(rawValue:)","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLoadEventStat\/init(rawValue:)","role":"symbol","kind":"symbol","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":")"}],"type":"topic","url":"\/documentation\/gfpsdk\/gfploadeventstat\/init(rawvalue:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPLoadEventStat/adSelected":{"role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLoadEventStat\/adSelected","type":"topic","abstract":[{"text":"Don’t change the value. This is the value defined in the specification.","type":"text"}],"url":"\/documentation\/gfpsdk\/gfploadeventstat\/adselected","title":"GFPLoadEventStat.adSelected","navigatorTitle":[{"text":"GFPLoadEventStatAdSelected","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"adSelected"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/SY":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/SH":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPLoadEventStat/timeout":{"navigatorTitle":[{"kind":"identifier","text":"GFPLoadEventStatTimeout"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"timeout"}],"title":"GFPLoadEventStat.timeout","abstract":[{"text":"Don’t change the value. This is the value defined in the specification.","type":"text"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLoadEventStat\/timeout","url":"\/documentation\/gfpsdk\/gfploadeventstat\/timeout","type":"topic","role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPLoadEventStat/RawRepresentable-Implementations":{"type":"topic","url":"\/documentation\/gfpsdk\/gfploadeventstat\/rawrepresentable-implementations","role":"collectionGroup","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLoadEventStat\/RawRepresentable-Implementations","kind":"article","title":"RawRepresentable Implementations","abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPLoadEventStat/noFill":{"type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLoadEventStat\/noFill","navigatorTitle":[{"kind":"identifier","text":"GFPLoadEventStatNoFill"}],"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Don’t change the value. This is the value defined in the specification."}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"noFill","kind":"identifier"}],"title":"GFPLoadEventStat.noFill","url":"\/documentation\/gfpsdk\/gfploadeventstat\/nofill"},"doc://com.navercorp.da.gfp.GFPSDK/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s8SendableP"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"path":"\/metadata\/title","op":"replace","value":"GFPLoadEventStat"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GFPLoadEventStat"}],"op":"replace"},{"value":[{"text":"GFPLoadEventStat","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","op":"replace","value":[{"title":"Enumeration Cases","generated":true,"anchor":"Enumeration-Cases","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLoadEventStat\/adSelected","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLoadEventStat\/error","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLoadEventStat\/noFill","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLoadEventStat\/timeout"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPLoadEventStat","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLoadEventStat~1error\/title","value":"GFPLoadEventStatError"},{"op":"replace","value":[{"text":"GFPLoadEventStatError","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLoadEventStat~1error\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLoadEventStat\/title","op":"replace","value":"GFPLoadEventStat"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLoadEventStat\/fragments","value":[{"kind":"identifier","text":"GFPLoadEventStat"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLoadEventStat\/navigatorTitle","value":[{"text":"GFPLoadEventStat","kind":"identifier"}]},{"op":"replace","value":"GFPLoadEventStatAdSelected","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLoadEventStat~1adSelected\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLoadEventStat~1adSelected\/fragments","value":[{"text":"GFPLoadEventStatAdSelected","kind":"identifier"}],"op":"replace"},{"value":"GFPLoadEventStatTimeout","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLoadEventStat~1timeout\/title"},{"value":[{"text":"GFPLoadEventStatTimeout","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLoadEventStat~1timeout\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLoadEventStat~1noFill\/title","value":"GFPLoadEventStatNoFill"},{"op":"replace","value":[{"text":"GFPLoadEventStatNoFill","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLoadEventStat~1noFill\/fragments"}]}]}