{"sections":[],"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLoadEvent","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPLoadEvent","kind":"identifier"}]}],"kind":"declarations"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/gfpsdk\/gfploadevent"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfploadevent"]}],"metadata":{"role":"symbol","externalID":"c:objc(cs)GFPLoadEvent","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPLoadEvent","kind":"identifier"}],"modules":[{"name":"GFPSDK"}],"symbolKind":"class","roleHeading":"Class","title":"GFPLoadEvent","navigatorTitle":[{"kind":"identifier","text":"GFPLoadEvent"}]},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"kind":"symbol","topicSections":[{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLoadEvent\/errorEventInfo","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLoadEvent\/loadEventStat"],"anchor":"Instance-Properties"},{"title":"Type Methods","generated":true,"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLoadEvent\/errorEvent(with:errorInfo:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLoadEvent\/success()"],"anchor":"Type-Methods"}],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPEvent"],"type":"inheritsFrom"},{"type":"conformsTo","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s7CVarArgP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s23CustomStringConvertibleP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH"],"kind":"relationships","title":"Conforms To"}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s28CustomDebugStringConvertibleP"},"doc://com.navercorp.da.gfp.GFPSDK/s7CVarArgP":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPLoadEvent/errorEvent(with:errorInfo:)":{"role":"symbol","title":"errorEvent(with:errorInfo:)","url":"\/documentation\/gfpsdk\/gfploadevent\/errorevent(with:errorinfo:)","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLoadEvent\/errorEvent(with:errorInfo:)","navigatorTitle":[{"text":"errorEventWithStat:errorInfo:","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"errorEvent"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@GFPLoadEventStat","text":"GFPLoadEventStat","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"errorInfo"},{"text":": ","kind":"text"},{"text":"GFPErrorEventInfo","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPErrorEventInfo"},{"text":") -> ","kind":"text"},{"text":"GFPLoadEvent","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPLoadEvent"}],"abstract":[],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)NSObject":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPLoadEvent/success()":{"type":"topic","url":"\/documentation\/gfpsdk\/gfploadevent\/success()","role":"symbol","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"success"},{"text":"() -> ","kind":"text"},{"text":"GFPLoadEvent","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPLoadEvent"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLoadEvent\/success()","title":"success()","navigatorTitle":[{"kind":"identifier","text":"successEvent"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPEvent":{"type":"topic","navigatorTitle":[{"text":"GFPEvent","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPEvent"}],"title":"GFPEvent","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPEvent","role":"symbol","url":"\/documentation\/gfpsdk\/gfpevent"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPLoadEvent/loadEventStat":{"navigatorTitle":[{"kind":"identifier","text":"loadEventStat"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLoadEvent\/loadEventStat","type":"topic","title":"loadEventStat","url":"\/documentation\/gfpsdk\/gfploadevent\/loadeventstat","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"loadEventStat","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GFPLoadEventStat","preciseIdentifier":"c:@E@GFPLoadEventStat"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPLoadEvent":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPLoadEvent","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"GFPLoadEvent","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLoadEvent","abstract":[],"role":"symbol","url":"\/documentation\/gfpsdk\/gfploadevent","title":"GFPLoadEvent","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPLoadEvent/errorEventInfo":{"type":"topic","url":"\/documentation\/gfpsdk\/gfploadevent\/erroreventinfo","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"errorEventInfo","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GFPErrorEventInfo","preciseIdentifier":"c:objc(cs)GFPErrorEventInfo"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLoadEvent\/errorEventInfo","title":"errorEventInfo","navigatorTitle":[{"text":"errorEventInfo","kind":"identifier"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/SQ":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/SH":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.navercorp.da.gfp.GFPSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"path":"\/metadata\/title","value":"GFPLoadEvent","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"GFPLoadEvent"}],"path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"GFPLoadEvent","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLoadEvent\/errorEventInfo","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLoadEvent\/loadEventStat"],"anchor":"Instance-Properties"},{"generated":true,"title":"Type Methods","anchor":"Type-Methods","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLoadEvent\/errorEvent(with:errorInfo:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLoadEvent\/success()"]}]},{"op":"replace","value":[{"title":"Inherits From","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPEvent"],"type":"inheritsFrom","kind":"relationships"}],"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPLoadEvent"},{"kind":"text","text":" : "},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPEvent","preciseIdentifier":"c:objc(cs)GFPEvent","text":"GFPEvent","kind":"typeIdentifier"}]}]}},{"value":"errorEventWithStat:errorInfo:","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLoadEvent~1errorEvent(with:errorInfo:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLoadEvent~1errorEvent(with:errorInfo:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"errorEventWithStat:errorInfo:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLoadEvent~1success()\/title","value":"successEvent","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"text":"successEvent","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLoadEvent~1success()\/fragments"},{"op":"replace","value":"GFPEvent","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPEvent\/title"},{"op":"replace","value":[{"text":"GFPEvent","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPEvent\/fragments"},{"value":[{"text":"GFPEvent","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPEvent\/navigatorTitle"},{"value":"loadEventStat","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLoadEvent~1loadEventStat\/title"},{"value":[{"text":"loadEventStat","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLoadEvent~1loadEventStat\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLoadEvent\/title","value":"GFPLoadEvent"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLoadEvent\/fragments","value":[{"text":"GFPLoadEvent","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLoadEvent\/navigatorTitle","op":"replace","value":[{"text":"GFPLoadEvent","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLoadEvent~1errorEventInfo\/title","value":"errorEventInfo"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLoadEvent~1errorEventInfo\/fragments","op":"replace","value":[{"text":"errorEventInfo","kind":"identifier"}]}]}]}