{"topicSections":[{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLimitQueue\/init(size:)"],"generated":true,"title":"Initializers","anchor":"Initializers"},{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLimitQueue\/isEmpty","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLimitQueue\/isFull","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLimitQueue\/queue","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLimitQueue\/size"],"anchor":"Instance-Properties","generated":true,"title":"Instance Properties"},{"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLimitQueue\/dequeue()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLimitQueue\/enqueue(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLimitQueue\/enqueueAndReplace(_:)"],"generated":true},{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLimitQueue\/sizeWith(_:)"],"title":"Type Methods","generated":true,"anchor":"Type-Methods"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objcMembers","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPLimitQueue"}]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLimitQueue"},"relationshipsSections":[{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"},{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s7CVarArgP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s23CustomStringConvertibleP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH"],"kind":"relationships","type":"conformsTo","title":"Conforms To"}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"sections":[],"kind":"symbol","metadata":{"externalID":"c:@M@GFPSDK@objc(cs)GFPLimitQueue","symbolKind":"class","navigatorTitle":[{"text":"GFPLimitQueue","kind":"identifier"}],"roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"GFPLimitQueue","kind":"identifier"}],"role":"symbol","modules":[{"name":"GFPSDK"}],"title":"GFPLimitQueue"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfplimitqueue"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfplimitqueue"]}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPLimitQueue/queue":{"title":"queue","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"queue","kind":"identifier"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@GFPSDK@objc(pl)GFPQueueObject","kind":"typeIdentifier","text":"GFPQueueObject"},{"text":"]","kind":"text"}],"navigatorTitle":[{"text":"queue","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[],"url":"\/documentation\/gfpsdk\/gfplimitqueue\/queue","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLimitQueue\/queue"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPLimitQueue/dequeue()":{"title":"dequeue()","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dequeue"},{"kind":"text","text":"() -> "},{"text":"GFPQueueObject","kind":"typeIdentifier","preciseIdentifier":"c:@M@GFPSDK@objc(pl)GFPQueueObject"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"dequeue","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLimitQueue\/dequeue()","url":"\/documentation\/gfpsdk\/gfplimitqueue\/dequeue()"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPLimitQueue/sizeWith(_:)":{"title":"sizeWith(_:)","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"sizeWith"},{"text":"(","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":") -> ","kind":"text"},{"text":"GFPLimitQueue","kind":"typeIdentifier","preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPLimitQueue"}],"navigatorTitle":[{"kind":"identifier","text":"sizeWith:"}],"type":"topic","role":"symbol","abstract":[],"url":"\/documentation\/gfpsdk\/gfplimitqueue\/sizewith(_:)","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLimitQueue\/sizeWith(_:)"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject"},"doc://com.navercorp.da.gfp.GFPSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.navercorp.da.gfp.GFPSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPLimitQueue/isEmpty":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEmpty"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"url":"\/documentation\/gfpsdk\/gfplimitqueue\/isempty","kind":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLimitQueue\/isEmpty","role":"symbol","navigatorTitle":[{"text":"isEmpty","kind":"identifier"}],"title":"isEmpty"},"doc://com.navercorp.da.gfp.GFPSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s7CVarArgP"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPLimitQueue/size":{"title":"size","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"size","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"size"}],"type":"topic","role":"symbol","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLimitQueue\/size","url":"\/documentation\/gfpsdk\/gfplimitqueue\/size"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPLimitQueue/init(size:)":{"title":"init(size:)","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"size","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"initWithSize:"}],"type":"topic","role":"symbol","abstract":[],"url":"\/documentation\/gfpsdk\/gfplimitqueue\/init(size:)","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLimitQueue\/init(size:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPLimitQueue/enqueue(_:)":{"abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLimitQueue\/enqueue(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"enqueue"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@GFPSDK@objc(pl)GFPQueueObject","text":"GFPQueueObject","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"kind":"symbol","type":"topic","title":"enqueue(_:)","url":"\/documentation\/gfpsdk\/gfplimitqueue\/enqueue(_:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"enqueue:"}]},"doc://com.navercorp.da.gfp.GFPSDK/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject","title":"NSObject"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPLimitQueue":{"abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLimitQueue","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"GFPLimitQueue","kind":"identifier"}],"kind":"symbol","type":"topic","title":"GFPLimitQueue","url":"\/documentation\/gfpsdk\/gfplimitqueue","role":"symbol","navigatorTitle":[{"text":"GFPLimitQueue","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPLimitQueue/enqueueAndReplace(_:)":{"abstract":[],"url":"\/documentation\/gfpsdk\/gfplimitqueue\/enqueueandreplace(_:)","role":"symbol","title":"enqueueAndReplace(_:)","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLimitQueue\/enqueueAndReplace(_:)","type":"topic","navigatorTitle":[{"text":"enqueueAndReplace:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"enqueueAndReplace"},{"kind":"text","text":"("},{"text":"GFPQueueObject","kind":"typeIdentifier","preciseIdentifier":"c:@M@GFPSDK@objc(pl)GFPQueueObject"},{"kind":"text","text":"?)"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPLimitQueue/isFull":{"title":"isFull","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"isFull","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"text":"isFull","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[],"url":"\/documentation\/gfpsdk\/gfplimitqueue\/isfull","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLimitQueue\/isFull"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/SH":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.navercorp.da.gfp.GFPSDK/SQ":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","type":"unresolvable","title":"Swift.Equatable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"GFPLimitQueue","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"GFPLimitQueue"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"GFPLimitQueue","kind":"identifier"}]},{"op":"replace","value":[{"generated":true,"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLimitQueue\/isEmpty","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLimitQueue\/isFull","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLimitQueue\/queue","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLimitQueue\/size"],"title":"Instance Properties","anchor":"Instance-Properties"},{"anchor":"Instance-Methods","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLimitQueue\/dequeue()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLimitQueue\/enqueue(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLimitQueue\/enqueueAndReplace(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLimitQueue\/init(size:)"],"generated":true,"title":"Instance Methods"},{"anchor":"Type-Methods","title":"Type Methods","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLimitQueue\/sizeWith(_:)"],"generated":true}],"path":"\/topicSections"},{"value":[{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"}],"path":"\/relationshipsSections","op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPLimitQueue","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLimitQueue~1queue\/title","value":"queue","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLimitQueue~1queue\/fragments","value":[{"text":"queue","kind":"identifier"}],"op":"replace"},{"value":"dequeue","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLimitQueue~1dequeue()\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLimitQueue~1dequeue()\/fragments","value":[{"kind":"text","text":"- "},{"text":"dequeue","kind":"identifier"}]},{"value":"sizeWith:","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLimitQueue~1sizeWith(_:)\/title"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"sizeWith:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLimitQueue~1sizeWith(_:)\/fragments"},{"value":"isEmpty","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLimitQueue~1isEmpty\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLimitQueue~1isEmpty\/fragments","value":[{"text":"isEmpty","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLimitQueue~1size\/title","value":"size","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLimitQueue~1size\/fragments","value":[{"text":"size","kind":"identifier"}]},{"op":"replace","value":"initWithSize:","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLimitQueue~1init(size:)\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLimitQueue~1init(size:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithSize:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLimitQueue~1enqueue(_:)\/title","value":"enqueue:","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLimitQueue~1enqueue(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"enqueue:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLimitQueue\/title","value":"GFPLimitQueue"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLimitQueue\/fragments","value":[{"kind":"identifier","text":"GFPLimitQueue"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLimitQueue\/navigatorTitle","value":[{"kind":"identifier","text":"GFPLimitQueue"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLimitQueue~1enqueueAndReplace(_:)\/title","op":"replace","value":"enqueueAndReplace:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"enqueueAndReplace:"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLimitQueue~1enqueueAndReplace(_:)\/fragments"},{"op":"replace","value":"isFull","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLimitQueue~1isFull\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLimitQueue~1isFull\/fragments","value":[{"text":"isFull","kind":"identifier"}],"op":"replace"}]}]}