{"relationshipsSections":[{"title":"Conforms To","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SY"],"type":"conformsTo","kind":"relationships"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"metadata":{"navigatorTitle":[{"text":"GFPMediaType","kind":"identifier"}],"role":"symbol","title":"GFPMediaType","symbolKind":"enum","roleHeading":"Enumeration","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPMediaType","kind":"identifier"}],"externalID":"c:@M@GFPSDK@E@GFPMediaType","modules":[{"name":"GFPSDK"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPMediaType"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpmediatype"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpmediatype"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaType"},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"kind":"symbol","topicSections":[{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaType\/c2s_image","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaType\/c2s_video","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaType\/carousel","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaType\/image","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaType\/richMedia","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaType\/unknown","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaType\/video"],"generated":true,"title":"Enumeration Cases","anchor":"Enumeration-Cases"},{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaType\/init(rawValue:)"],"anchor":"Initializers","title":"Initializers","generated":true},{"anchor":"Default-Implementations","title":"Default Implementations","generated":true,"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaType\/Equatable-Implementations","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaType\/RawRepresentable-Implementations"]}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPMediaType/init(rawValue:)":{"kind":"symbol","url":"\/documentation\/gfpsdk\/gfpmediatype\/init(rawvalue:)","title":"init(rawValue:)","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaType\/init(rawValue:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPMediaType":{"url":"\/documentation\/gfpsdk\/gfpmediatype","title":"GFPMediaType","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaType","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPMediaType"}],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPMediaType"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPMediaType/carousel":{"role":"symbol","abstract":[],"url":"\/documentation\/gfpsdk\/gfpmediatype\/carousel","title":"GFPMediaType.carousel","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"carousel","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"GFPMediaTypeCarousel"}],"kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaType\/carousel"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPMediaType/c2s_image":{"navigatorTitle":[{"kind":"identifier","text":"GFPMediaTypeC2s_image"}],"kind":"symbol","url":"\/documentation\/gfpsdk\/gfpmediatype\/c2s_image","title":"GFPMediaType.c2s_image","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaType\/c2s_image","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"c2s_image","kind":"identifier"}],"type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPMediaType/Equatable-Implementations":{"role":"collectionGroup","abstract":[],"url":"\/documentation\/gfpsdk\/gfpmediatype\/equatable-implementations","title":"Equatable Implementations","type":"topic","kind":"article","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaType\/Equatable-Implementations"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPMediaType/unknown":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"unknown","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpmediatype\/unknown","kind":"symbol","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaType\/unknown","abstract":[],"role":"symbol","navigatorTitle":[{"text":"GFPMediaTypeUnknown","kind":"identifier"}],"title":"GFPMediaType.unknown"},"doc://com.navercorp.da.gfp.GFPSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH","title":"Swift.Hashable"},"doc://com.navercorp.da.gfp.GFPSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","title":"Swift.Equatable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPMediaType/image":{"navigatorTitle":[{"kind":"identifier","text":"GFPMediaTypeImage"}],"kind":"symbol","url":"\/documentation\/gfpsdk\/gfpmediatype\/image","title":"GFPMediaType.image","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaType\/image","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"image"}],"type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPMediaType/richMedia":{"url":"\/documentation\/gfpsdk\/gfpmediatype\/richmedia","abstract":[],"title":"GFPMediaType.richMedia","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaType\/richMedia","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPMediaTypeRichMedia"}],"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"richMedia","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPMediaType/c2s_video":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"c2s_video"}],"navigatorTitle":[{"kind":"identifier","text":"GFPMediaTypeC2s_video"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaType\/c2s_video","url":"\/documentation\/gfpsdk\/gfpmediatype\/c2s_video","kind":"symbol","role":"symbol","abstract":[],"type":"topic","title":"GFPMediaType.c2s_video"},"doc://com.navercorp.da.gfp.GFPSDK/SY":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPMediaType/RawRepresentable-Implementations":{"abstract":[],"url":"\/documentation\/gfpsdk\/gfpmediatype\/rawrepresentable-implementations","kind":"article","type":"topic","role":"collectionGroup","title":"RawRepresentable Implementations","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaType\/RawRepresentable-Implementations"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPMediaType/video":{"navigatorTitle":[{"text":"GFPMediaTypeVideo","kind":"identifier"}],"type":"topic","title":"GFPMediaType.video","kind":"symbol","url":"\/documentation\/gfpsdk\/gfpmediatype\/video","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaType\/video","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"video"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"GFPMediaType"},{"value":"enum","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"GFPMediaType","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"GFPMediaType"}],"path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","value":[{"title":"Enumeration Cases","anchor":"Enumeration-Cases","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaType\/c2s_image","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaType\/c2s_video","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaType\/carousel","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaType\/image","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaType\/richMedia","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaType\/unknown","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaType\/video"],"generated":true}],"op":"replace"},{"value":null,"op":"replace","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPMediaType","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMediaType\/title","value":"GFPMediaType"},{"op":"replace","value":[{"kind":"identifier","text":"GFPMediaType"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMediaType\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMediaType\/navigatorTitle","value":[{"kind":"identifier","text":"GFPMediaType"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMediaType~1carousel\/title","op":"replace","value":"GFPMediaTypeCarousel"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMediaType~1carousel\/fragments","value":[{"text":"GFPMediaTypeCarousel","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMediaType~1c2s_image\/title","value":"GFPMediaTypeC2s_image","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMediaType~1c2s_image\/fragments","value":[{"text":"GFPMediaTypeC2s_image","kind":"identifier"}]},{"value":"GFPMediaTypeUnknown","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMediaType~1unknown\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMediaType~1unknown\/fragments","value":[{"kind":"identifier","text":"GFPMediaTypeUnknown"}],"op":"replace"},{"value":"GFPMediaTypeImage","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMediaType~1image\/title"},{"value":[{"kind":"identifier","text":"GFPMediaTypeImage"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMediaType~1image\/fragments"},{"op":"replace","value":"GFPMediaTypeRichMedia","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMediaType~1richMedia\/title"},{"value":[{"text":"GFPMediaTypeRichMedia","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMediaType~1richMedia\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMediaType~1c2s_video\/title","value":"GFPMediaTypeC2s_video"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMediaType~1c2s_video\/fragments","value":[{"text":"GFPMediaTypeC2s_video","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMediaType~1video\/title","value":"GFPMediaTypeVideo"},{"op":"replace","value":[{"text":"GFPMediaTypeVideo","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMediaType~1video\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}