{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPMaxExtendingHeightSetter","kind":"identifier"},{"text":" = () -> ","kind":"text"},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpmaxextendingheightsetter"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gfpsdk\/gfpmaxextendingheightsetter"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"typealias","title":"GFPMaxExtendingHeightSetter","modules":[{"name":"GFPSDK"}],"role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPMaxExtendingHeightSetter","kind":"identifier"}],"roleHeading":"Type Alias","navigatorTitle":[{"kind":"identifier","text":"GFPMaxExtendingHeightSetter"}],"externalID":"c:GFPNativeAdRenderingSetting.h@T@GFPMaxExtendingHeightSetter"},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMaxExtendingHeightSetter"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPMaxExtendingHeightSetter":{"abstract":[],"kind":"symbol","title":"GFPMaxExtendingHeightSetter","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"GFPMaxExtendingHeightSetter","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMaxExtendingHeightSetter","type":"topic","role":"symbol","url":"\/documentation\/gfpsdk\/gfpmaxextendingheightsetter","navigatorTitle":[{"text":"GFPMaxExtendingHeightSetter","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Type Alias","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"GFPMaxExtendingHeightSetter"},{"op":"replace","path":"\/metadata\/symbolKind","value":"typealias"},{"value":[{"text":"GFPMaxExtendingHeightSetter","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"GFPMaxExtendingHeightSetter"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"typedef"},{"text":" ","kind":"text"},{"text":"double (^)(void)","kind":"typeIdentifier","preciseIdentifier":"c:BFd()"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPMaxExtendingHeightSetter"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMaxExtendingHeightSetter\/title","op":"replace","value":"GFPMaxExtendingHeightSetter"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMaxExtendingHeightSetter\/fragments","value":[{"text":"GFPMaxExtendingHeightSetter","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMaxExtendingHeightSetter\/navigatorTitle","value":[{"kind":"identifier","text":"GFPMaxExtendingHeightSetter"}]}]}]}