{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPMRAIDSupportSetting","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpmraidsupportsetting"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpmraidsupportsetting"]}],"topicSections":[{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMRAIDSupportSetting\/supportsCalendar()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMRAIDSupportSetting\/supportsInlineVideo()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMRAIDSupportSetting\/supportsLocation()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMRAIDSupportSetting\/supportsSMS()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMRAIDSupportSetting\/supportsStorePicture()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMRAIDSupportSetting\/supportsTel()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMRAIDSupportSetting\/supportsVPAID()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMRAIDSupportSetting\/updateTypes(_:)"],"generated":true,"title":"Type Methods","anchor":"Type-Methods"}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMRAIDSupportSetting","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"kind":"symbol","metadata":{"roleHeading":"Class","modules":[{"name":"GFPSDK"}],"externalID":"c:objc(cs)GFPMRAIDSupportSetting","role":"symbol","symbolKind":"class","title":"GFPMRAIDSupportSetting","navigatorTitle":[{"text":"GFPMRAIDSupportSetting","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPMRAIDSupportSetting","kind":"identifier"}]},"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject"],"title":"Inherits From"},{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s7CVarArgP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s23CustomStringConvertibleP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPMRAIDSupportSetting/supportsInlineVideo()":{"url":"\/documentation\/gfpsdk\/gfpmraidsupportsetting\/supportsinlinevideo()","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMRAIDSupportSetting\/supportsInlineVideo()","abstract":[],"title":"supportsInlineVideo()","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"supportsInlineVideo","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"supportsInlineVideo"},{"kind":"text","text":"() -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPMRAIDSupportSetting/supportsTel()":{"navigatorTitle":[{"text":"supportsTel","kind":"identifier"}],"title":"supportsTel()","url":"\/documentation\/gfpsdk\/gfpmraidsupportsetting\/supportstel()","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMRAIDSupportSetting\/supportsTel()","role":"symbol","type":"topic","kind":"symbol","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"supportsTel","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s28CustomDebugStringConvertibleP"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPMRAIDSupportSetting/updateTypes(_:)":{"role":"symbol","navigatorTitle":[{"text":"updateTypes:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"updateTypes","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@E@GFPMraidSupportType","kind":"typeIdentifier","text":"GFPMraidSupportType"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMRAIDSupportSetting\/updateTypes(_:)","type":"topic","kind":"symbol","url":"\/documentation\/gfpsdk\/gfpmraidsupportsetting\/updatetypes(_:)","abstract":[],"title":"updateTypes(_:)"},"doc://com.navercorp.da.gfp.GFPSDK/SH":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/objc(cs)NSObject":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPMRAIDSupportSetting/supportsCalendar()":{"url":"\/documentation\/gfpsdk\/gfpmraidsupportsetting\/supportscalendar()","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMRAIDSupportSetting\/supportsCalendar()","abstract":[],"title":"supportsCalendar()","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"supportsCalendar"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"supportsCalendar","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPMRAIDSupportSetting":{"abstract":[],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"GFPMRAIDSupportSetting","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpmraidsupportsetting","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMRAIDSupportSetting","title":"GFPMRAIDSupportSetting","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPMRAIDSupportSetting"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPMRAIDSupportSetting/supportsLocation()":{"url":"\/documentation\/gfpsdk\/gfpmraidsupportsetting\/supportslocation()","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMRAIDSupportSetting\/supportsLocation()","abstract":[],"title":"supportsLocation()","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"supportsLocation"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"supportsLocation"},{"kind":"text","text":"() -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPMRAIDSupportSetting/supportsSMS()":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"supportsSMS"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"supportsSMS","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMRAIDSupportSetting\/supportsSMS()","type":"topic","kind":"symbol","url":"\/documentation\/gfpsdk\/gfpmraidsupportsetting\/supportssms()","abstract":[],"title":"supportsSMS()"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPMRAIDSupportSetting/supportsVPAID()":{"url":"\/documentation\/gfpsdk\/gfpmraidsupportsetting\/supportsvpaid()","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMRAIDSupportSetting\/supportsVPAID()","abstract":[],"title":"supportsVPAID()","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"supportsVPAID"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"supportsVPAID"},{"kind":"text","text":"() -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"doc://com.navercorp.da.gfp.GFPSDK/SQ":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/s7CVarArgP":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)NSObject":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPMRAIDSupportSetting/supportsStorePicture()":{"navigatorTitle":[{"kind":"identifier","text":"supportsStorePicture"}],"url":"\/documentation\/gfpsdk\/gfpmraidsupportsetting\/supportsstorepicture()","kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMRAIDSupportSetting\/supportsStorePicture()","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"supportsStorePicture","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"role":"symbol","type":"topic","title":"supportsStorePicture()"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"GFPMRAIDSupportSetting"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"GFPMRAIDSupportSetting","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"GFPMRAIDSupportSetting"}]},{"value":[{"anchor":"Type-Methods","generated":true,"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMRAIDSupportSetting\/supportsCalendar()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMRAIDSupportSetting\/supportsInlineVideo()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMRAIDSupportSetting\/supportsLocation()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMRAIDSupportSetting\/supportsSMS()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMRAIDSupportSetting\/supportsStorePicture()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMRAIDSupportSetting\/supportsTel()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMRAIDSupportSetting\/supportsVPAID()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMRAIDSupportSetting\/updateTypes(_:)"],"title":"Type Methods"}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"op":"replace"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPMRAIDSupportSetting"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"languages":["occ"]}]}},{"value":"supportsInlineVideo","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMRAIDSupportSetting~1supportsInlineVideo()\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMRAIDSupportSetting~1supportsInlineVideo()\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"supportsInlineVideo"}]},{"value":"supportsTel","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMRAIDSupportSetting~1supportsTel()\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMRAIDSupportSetting~1supportsTel()\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"supportsTel","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMRAIDSupportSetting~1updateTypes(_:)\/title","value":"updateTypes:"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"updateTypes:"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMRAIDSupportSetting~1updateTypes(_:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMRAIDSupportSetting~1supportsCalendar()\/title","value":"supportsCalendar"},{"value":[{"text":"+ ","kind":"text"},{"text":"supportsCalendar","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMRAIDSupportSetting~1supportsCalendar()\/fragments","op":"replace"},{"op":"replace","value":"GFPMRAIDSupportSetting","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMRAIDSupportSetting\/title"},{"value":[{"kind":"identifier","text":"GFPMRAIDSupportSetting"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMRAIDSupportSetting\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMRAIDSupportSetting\/navigatorTitle","value":[{"kind":"identifier","text":"GFPMRAIDSupportSetting"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMRAIDSupportSetting~1supportsLocation()\/title","value":"supportsLocation"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"supportsLocation"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMRAIDSupportSetting~1supportsLocation()\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMRAIDSupportSetting~1supportsSMS()\/title","value":"supportsSMS"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMRAIDSupportSetting~1supportsSMS()\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"supportsSMS"}],"op":"replace"},{"value":"supportsVPAID","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMRAIDSupportSetting~1supportsVPAID()\/title","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"supportsVPAID"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMRAIDSupportSetting~1supportsVPAID()\/fragments"},{"op":"replace","value":"supportsStorePicture","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMRAIDSupportSetting~1supportsStorePicture()\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMRAIDSupportSetting~1supportsStorePicture()\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"supportsStorePicture","kind":"identifier"}],"op":"replace"}]}]}