{"schemaVersion":{"minor":3,"patch":0,"major":0},"relationshipsSections":[{"type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/s15BitwiseCopyableP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s25ExpressibleByArrayLiteralP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s9OptionSetP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SY","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s8SendableP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s10SetAlgebraP"],"title":"Conforms To"}],"metadata":{"role":"symbol","symbolKind":"struct","modules":[{"name":"GFPSDK"}],"roleHeading":"Structure","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPMraidSupportType"}],"navigatorTitle":[{"kind":"identifier","text":"GFPMraidSupportType"}],"title":"GFPMraidSupportType","externalID":"c:@E@GFPMraidSupportType"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMraidSupportType"},"sections":[],"topicSections":[{"generated":true,"title":"Initializers","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMraidSupportType\/init(rawValue:)"],"anchor":"Initializers"},{"generated":true,"anchor":"Type-Properties","title":"Type Properties","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMraidSupportType\/SMS","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMraidSupportType\/VPAID","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMraidSupportType\/calendar","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMraidSupportType\/default","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMraidSupportType\/inlineVideo","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMraidSupportType\/location","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMraidSupportType\/picture","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMraidSupportType\/tel"]},{"title":"Default Implementations","anchor":"Default-Implementations","generated":true,"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMraidSupportType\/Equatable-Implementations","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMraidSupportType\/OptionSet-Implementations","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMraidSupportType\/SetAlgebra-Implementations"]}],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpmraidsupporttype"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpmraidsupporttype"]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPMraidSupportType"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPMraidSupportType/picture":{"type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMraidSupportType\/picture","url":"\/documentation\/gfpsdk\/gfpmraidsupporttype\/picture","kind":"symbol","title":"picture","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"picture","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPMraidSupportType","text":"GFPMraidSupportType"}],"role":"symbol","abstract":[],"navigatorTitle":[{"text":"GFPMraidSupportPicture","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPMraidSupportType/SMS":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMraidSupportType\/SMS","kind":"symbol","title":"SMS","url":"\/documentation\/gfpsdk\/gfpmraidsupporttype\/sms","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SMS"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPMraidSupportType","text":"GFPMraidSupportType"}],"navigatorTitle":[{"kind":"identifier","text":"GFPMraidSupportSMS"}],"abstract":[],"type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPMraidSupportType/inlineVideo":{"type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMraidSupportType\/inlineVideo","url":"\/documentation\/gfpsdk\/gfpmraidsupporttype\/inlinevideo","kind":"symbol","title":"inlineVideo","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"inlineVideo","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPMraidSupportType","text":"GFPMraidSupportType"}],"role":"symbol","abstract":[],"navigatorTitle":[{"text":"GFPMraidSupportInlineVideo","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPMraidSupportType/Equatable-Implementations":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMraidSupportType\/Equatable-Implementations","kind":"article","title":"Equatable Implementations","url":"\/documentation\/gfpsdk\/gfpmraidsupporttype\/equatable-implementations","role":"collectionGroup","abstract":[],"type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ"},"doc://com.navercorp.da.gfp.GFPSDK/s10SetAlgebraP":{"type":"unresolvable","title":"Swift.SetAlgebra","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s10SetAlgebraP"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPMraidSupportType/GFPMraidSupportNone":{"role":"symbol","abstract":[],"fragments":[{"text":"GFPMraidSupportNone","kind":"identifier"}],"kind":"symbol","type":"topic","title":"GFPMraidSupportNone","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMraidSupportType\/GFPMraidSupportNone","url":"\/documentation\/gfpsdk\/gfpmraidsupporttype\/gfpmraidsupportnone"},"doc://com.navercorp.da.gfp.GFPSDK/s9OptionSetP":{"type":"unresolvable","title":"Swift.OptionSet","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s9OptionSetP"},"doc://com.navercorp.da.gfp.GFPSDK/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s8SendableP"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPMraidSupportType/tel":{"type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMraidSupportType\/tel","url":"\/documentation\/gfpsdk\/gfpmraidsupporttype\/tel","kind":"symbol","title":"tel","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"tel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPMraidSupportType","text":"GFPMraidSupportType"}],"role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"GFPMraidSupportTel"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPMraidSupportType/init(rawValue:)":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMraidSupportType\/init(rawValue:)","kind":"symbol","title":"init(rawValue:)","url":"\/documentation\/gfpsdk\/gfpmraidsupporttype\/init(rawvalue:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"text":")","kind":"text"}],"abstract":[],"type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPMraidSupportType/calendar":{"type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMraidSupportType\/calendar","url":"\/documentation\/gfpsdk\/gfpmraidsupporttype\/calendar","kind":"symbol","title":"calendar","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"calendar"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPMraidSupportType","text":"GFPMraidSupportType"}],"role":"symbol","abstract":[],"navigatorTitle":[{"text":"GFPMraidSupportCalendar","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPMraidSupportType/location":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMraidSupportType\/location","kind":"symbol","title":"location","url":"\/documentation\/gfpsdk\/gfpmraidsupporttype\/location","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"location"},{"kind":"text","text":": "},{"text":"GFPMraidSupportType","kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPMraidSupportType"}],"navigatorTitle":[{"text":"GFPMraidSupportLocation","kind":"identifier"}],"abstract":[],"type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/s25ExpressibleByArrayLiteralP":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s25ExpressibleByArrayLiteralP","title":"Swift.ExpressibleByArrayLiteral","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPMraidSupportType/default":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMraidSupportType\/default","kind":"symbol","title":"default","url":"\/documentation\/gfpsdk\/gfpmraidsupporttype\/default","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"`default`"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPMraidSupportType","text":"GFPMraidSupportType"}],"navigatorTitle":[{"text":"GFPMraidSupportDefault","kind":"identifier"}],"abstract":[],"type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPMraidSupportType/OptionSet-Implementations":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMraidSupportType\/OptionSet-Implementations","role":"collectionGroup","abstract":[],"url":"\/documentation\/gfpsdk\/gfpmraidsupporttype\/optionset-implementations","kind":"article","type":"topic","title":"OptionSet Implementations"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPMraidSupportType/VPAID":{"type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMraidSupportType\/VPAID","url":"\/documentation\/gfpsdk\/gfpmraidsupporttype\/vpaid","kind":"symbol","title":"VPAID","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"VPAID"},{"kind":"text","text":": "},{"text":"GFPMraidSupportType","kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPMraidSupportType"}],"role":"symbol","abstract":[],"navigatorTitle":[{"text":"GFPMraidSupportVPAID","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPMraidSupportType":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPMraidSupportType"}],"kind":"symbol","navigatorTitle":[{"text":"GFPMraidSupportType","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMraidSupportType","abstract":[],"role":"symbol","url":"\/documentation\/gfpsdk\/gfpmraidsupporttype","title":"GFPMraidSupportType","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/s15BitwiseCopyableP":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s15BitwiseCopyableP","title":"Swift.BitwiseCopyable","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/SY":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPMraidSupportType/SetAlgebra-Implementations":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMraidSupportType\/SetAlgebra-Implementations","kind":"article","title":"SetAlgebra Implementations","url":"\/documentation\/gfpsdk\/gfpmraidsupporttype\/setalgebra-implementations","role":"collectionGroup","abstract":[],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"path":"\/metadata\/title","value":"GFPMraidSupportType","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"value":[{"kind":"identifier","text":"GFPMraidSupportType"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"GFPMraidSupportType","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"anchor":"Enumeration-Cases","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMraidSupportType\/GFPMraidSupportNone","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMraidSupportType\/SMS","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMraidSupportType\/VPAID","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMraidSupportType\/calendar","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMraidSupportType\/default","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMraidSupportType\/inlineVideo","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMraidSupportType\/location","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMraidSupportType\/picture","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMraidSupportType\/tel"],"title":"Enumeration Cases","generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"GFPMraidSupportType","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMraidSupportType~1picture\/title","value":"GFPMraidSupportPicture"},{"value":[{"text":"GFPMraidSupportPicture","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMraidSupportType~1picture\/fragments","op":"replace"},{"op":"replace","value":"GFPMraidSupportSMS","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMraidSupportType~1SMS\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMraidSupportType~1SMS\/fragments","value":[{"kind":"identifier","text":"GFPMraidSupportSMS"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMraidSupportType~1inlineVideo\/title","value":"GFPMraidSupportInlineVideo","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMraidSupportType~1inlineVideo\/fragments","value":[{"text":"GFPMraidSupportInlineVideo","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMraidSupportType~1tel\/title","op":"replace","value":"GFPMraidSupportTel"},{"value":[{"kind":"identifier","text":"GFPMraidSupportTel"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMraidSupportType~1tel\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMraidSupportType~1calendar\/title","value":"GFPMraidSupportCalendar"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMraidSupportType~1calendar\/fragments","value":[{"text":"GFPMraidSupportCalendar","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMraidSupportType~1location\/title","value":"GFPMraidSupportLocation"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMraidSupportType~1location\/fragments","value":[{"kind":"identifier","text":"GFPMraidSupportLocation"}]},{"value":"GFPMraidSupportDefault","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMraidSupportType~1default\/title","op":"replace"},{"value":[{"text":"GFPMraidSupportDefault","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMraidSupportType~1default\/fragments","op":"replace"},{"value":"GFPMraidSupportVPAID","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMraidSupportType~1VPAID\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMraidSupportType~1VPAID\/fragments","op":"replace","value":[{"text":"GFPMraidSupportVPAID","kind":"identifier"}]},{"op":"replace","value":"GFPMraidSupportType","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMraidSupportType\/title"},{"value":[{"text":"GFPMraidSupportType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMraidSupportType\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMraidSupportType\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"GFPMraidSupportType"}]}]}]}