{"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject"]},{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s7CVarArgP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s23CustomStringConvertibleP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objcMembers","kind":"attribute"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPMediaData"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaData"},"metadata":{"title":"GFPMediaData","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"GFPMediaData","kind":"identifier"}],"roleHeading":"Class","role":"symbol","externalID":"c:@M@GFPSDK@objc(cs)GFPMediaData","symbolKind":"class","navigatorTitle":[{"text":"GFPMediaData","kind":"identifier"}],"modules":[{"name":"GFPSDK"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpmediadata"]},{"paths":["\/documentation\/gfpsdk\/gfpmediadata"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaData\/aspectRatio","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaData\/carouselHeightDelegate","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaData\/description","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaData\/image","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaData\/mediaType","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaData\/preferredMediaHeight","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaData\/preferredMediaWidth","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaData\/richMediaData","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaData\/videoController"],"generated":true,"title":"Instance Properties","anchor":"Instance-Properties"},{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaData\/preferredHeightWithFixedWidth(_:)"],"anchor":"Instance-Methods"},{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaData\/unknwonAspectRatio"],"anchor":"Type-Properties","title":"Type Properties","generated":true},{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaData\/createC2SInfo(type:c2sAspectRatio:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaData\/createCarouselMediaInfo()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaData\/createComplexMediaInfo(image:videoController:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaData\/createImageInfo(image:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaData\/createRichMediaInfo()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaData\/createRichMediaInfo(richMediaInfo:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaData\/createVideoInfo(videoController:)"],"anchor":"Type-Methods","title":"Type Methods","generated":true}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPMediaData/createImageInfo(image:)":{"type":"topic","title":"createImageInfo(image:)","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaData\/createImageInfo(image:)","role":"symbol","url":"\/documentation\/gfpsdk\/gfpmediadata\/createimageinfo(image:)","kind":"symbol","navigatorTitle":[{"text":"createImageInfoWith:","kind":"identifier"}],"abstract":[],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"createImageInfo","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"image"},{"kind":"text","text":": "},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPMediaData","text":"GFPMediaData"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPMediaData/preferredMediaWidth":{"title":"preferredMediaWidth","abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"preferredMediaWidth"}],"type":"topic","url":"\/documentation\/gfpsdk\/gfpmediadata\/preferredmediawidth","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"preferredMediaWidth","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaData\/preferredMediaWidth","role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPMediaData/createC2SInfo(type:c2sAspectRatio:)":{"kind":"symbol","type":"topic","abstract":[],"url":"\/documentation\/gfpsdk\/gfpmediadata\/createc2sinfo(type:c2saspectratio:)","navigatorTitle":[{"kind":"identifier","text":"createC2SInfoWith:aspectRatio:"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"createC2SInfo","kind":"identifier"},{"kind":"text","text":"("},{"text":"type","kind":"externalParam"},{"kind":"text","text":": "},{"text":"GFPMediaType","preciseIdentifier":"c:@M@GFPSDK@E@GFPMediaType","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"c2sAspectRatio"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":") -> "},{"text":"GFPMediaData","kind":"typeIdentifier","preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPMediaData"}],"title":"createC2SInfo(type:c2sAspectRatio:)","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaData\/createC2SInfo(type:c2sAspectRatio:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPMediaData/aspectRatio":{"kind":"symbol","url":"\/documentation\/gfpsdk\/gfpmediadata\/aspectratio","role":"symbol","navigatorTitle":[{"text":"aspectRatio","kind":"identifier"}],"abstract":[{"text":"미디어의 aspectRatio. 값이 없을 경우 -1 을 반환.","type":"text"}],"title":"aspectRatio","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaData\/aspectRatio","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"aspectRatio"},{"text":": ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}]},"doc://com.navercorp.da.gfp.GFPSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPMediaData/createComplexMediaInfo(image:videoController:)":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"createComplexMediaInfo"},{"kind":"text","text":"("},{"text":"image","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"kind":"text","text":"?, "},{"text":"videoController","kind":"externalParam"},{"kind":"text","text":": "},{"text":"GFPVideoController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoController"},{"kind":"text","text":"?) -> "},{"text":"GFPMediaData","kind":"typeIdentifier","preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPMediaData"}],"navigatorTitle":[{"kind":"identifier","text":"createComplexMediaInfo:videoController:"}],"url":"\/documentation\/gfpsdk\/gfpmediadata\/createcomplexmediainfo(image:videocontroller:)","abstract":[],"kind":"symbol","role":"symbol","title":"createComplexMediaInfo(image:videoController:)","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaData\/createComplexMediaInfo(image:videoController:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPMediaData/richMediaData":{"role":"symbol","title":"richMediaData","url":"\/documentation\/gfpsdk\/gfpmediadata\/richmediadata","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"richMediaData","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPRichMediaData","text":"GFPRichMediaData","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"richMediaData"}],"type":"topic","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaData\/richMediaData"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPMediaData/preferredHeightWithFixedWidth(_:)":{"role":"symbol","abstract":[],"url":"\/documentation\/gfpsdk\/gfpmediadata\/preferredheightwithfixedwidth(_:)","title":"preferredHeightWithFixedWidth(_:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"preferredHeightWithFixedWidth"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier","text":"CGFloat"},{"text":") -> ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"navigatorTitle":[{"kind":"identifier","text":"preferredHeightWithFixedWidth:"}],"kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaData\/preferredHeightWithFixedWidth(_:)"},"doc://com.navercorp.da.gfp.GFPSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","title":"Swift.Equatable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPMediaData/createRichMediaInfo()":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"createRichMediaInfo"},{"kind":"text","text":"() -> "},{"text":"GFPMediaData","kind":"typeIdentifier","preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPMediaData"}],"navigatorTitle":[{"text":"createRichMediaInfo","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaData\/createRichMediaInfo()","kind":"symbol","type":"topic","role":"symbol","abstract":[],"url":"\/documentation\/gfpsdk\/gfpmediadata\/createrichmediainfo()","title":"createRichMediaInfo()"},"doc://com.navercorp.da.gfp.GFPSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPMediaData/mediaType":{"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"mediaType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"GFPMediaType","kind":"typeIdentifier","preciseIdentifier":"c:@M@GFPSDK@E@GFPMediaType"}],"abstract":[],"navigatorTitle":[{"text":"mediaType","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpmediadata\/mediatype","kind":"symbol","type":"topic","role":"symbol","title":"mediaType","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaData\/mediaType"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.navercorp.da.gfp.GFPSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPMediaData/createRichMediaInfo(richMediaInfo:)":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaData\/createRichMediaInfo(richMediaInfo:)","type":"topic","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"createRichMediaInfo","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"richMediaInfo"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPRichMediaData","text":"GFPRichMediaData","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"GFPMediaData","kind":"typeIdentifier","preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPMediaData"}],"abstract":[],"navigatorTitle":[{"text":"createRichMediaInfo:","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpmediadata\/createrichmediainfo(richmediainfo:)","title":"createRichMediaInfo(richMediaInfo:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPMediaData/preferredMediaHeight":{"abstract":[],"kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"preferredMediaHeight","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaData\/preferredMediaHeight","title":"preferredMediaHeight","url":"\/documentation\/gfpsdk\/gfpmediadata\/preferredmediaheight","type":"topic","navigatorTitle":[{"kind":"identifier","text":"preferredMediaHeight"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPMediaData/carouselHeightDelegate":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaData\/carouselHeightDelegate","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"carouselHeightDelegate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"GFPCarouselHeightDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@GFPSDK@objc(pl)GFPCarouselHeightDelegate"},{"text":"?","kind":"text"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"carouselHeightDelegate"}],"url":"\/documentation\/gfpsdk\/gfpmediadata\/carouselheightdelegate","title":"carouselHeightDelegate"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPMediaData/description":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaData\/description","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"type":"topic","navigatorTitle":[{"text":"description","kind":"identifier"}],"title":"description","url":"\/documentation\/gfpsdk\/gfpmediadata\/description","abstract":[],"role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPMediaData/createVideoInfo(videoController:)":{"abstract":[],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createVideoInfo","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"videoController"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)GFPVideoController","text":"GFPVideoController","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPMediaData","kind":"typeIdentifier","text":"GFPMediaData"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaData\/createVideoInfo(videoController:)","title":"createVideoInfo(videoController:)","url":"\/documentation\/gfpsdk\/gfpmediadata\/createvideoinfo(videocontroller:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"createVideoInfoWith:"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPMediaData":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaData","url":"\/documentation\/gfpsdk\/gfpmediadata","abstract":[],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"GFPMediaData","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"GFPMediaData"}],"title":"GFPMediaData"},"doc://com.navercorp.da.gfp.GFPSDK/objc(cs)NSObject":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPMediaData/image":{"type":"topic","title":"image","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"image","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"abstract":[],"url":"\/documentation\/gfpsdk\/gfpmediadata\/image","kind":"symbol","navigatorTitle":[{"text":"image","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaData\/image"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPMediaData/createCarouselMediaInfo()":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"createCarouselMediaInfo"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPMediaData","text":"GFPMediaData"}],"navigatorTitle":[{"text":"createCarouseMedialInfo","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpmediadata\/createcarouselmediainfo()","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaData\/createCarouselMediaInfo()","kind":"symbol","role":"symbol","abstract":[],"type":"topic","title":"createCarouselMediaInfo()"},"doc://com.navercorp.da.gfp.GFPSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPMediaData/unknwonAspectRatio":{"navigatorTitle":[{"kind":"identifier","text":"unknwonAspectRatio"}],"kind":"symbol","url":"\/documentation\/gfpsdk\/gfpmediadata\/unknwonaspectratio","title":"unknwonAspectRatio","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaData\/unknwonAspectRatio","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unknwonAspectRatio","kind":"identifier"},{"kind":"text","text":": "},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPMediaData/videoController":{"type":"topic","url":"\/documentation\/gfpsdk\/gfpmediadata\/videocontroller","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"videoController","kind":"identifier"},{"text":": ","kind":"text"},{"text":"GFPVideoController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoController"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaData\/videoController","title":"videoController","navigatorTitle":[{"text":"videoController","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","value":"GFPMediaData","path":"\/metadata\/title"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GFPMediaData"}]},{"op":"replace","value":[{"text":"GFPMediaData","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaData\/aspectRatio","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaData\/carouselHeightDelegate","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaData\/description","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaData\/image","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaData\/mediaType","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaData\/preferredMediaHeight","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaData\/preferredMediaWidth","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaData\/richMediaData","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaData\/videoController"],"generated":true,"anchor":"Instance-Properties"},{"anchor":"Instance-Methods","title":"Instance Methods","generated":true,"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaData\/preferredHeightWithFixedWidth(_:)"]},{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaData\/unknwonAspectRatio"],"generated":true,"title":"Type Properties","anchor":"Type-Properties"},{"generated":true,"anchor":"Type-Methods","title":"Type Methods","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaData\/createC2SInfo(type:c2sAspectRatio:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaData\/createCarouselMediaInfo()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaData\/createComplexMediaInfo(image:videoController:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaData\/createImageInfo(image:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaData\/createRichMediaInfo()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaData\/createRichMediaInfo(richMediaInfo:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaData\/createVideoInfo(videoController:)"]}],"op":"replace","path":"\/topicSections"},{"value":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject"]}],"op":"replace","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"GFPMediaData","kind":"identifier"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"languages":["occ"]}]},"op":"replace"},{"value":"createImageInfoWith:","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMediaData~1createImageInfo(image:)\/title"},{"value":[{"text":"+ ","kind":"text"},{"text":"createImageInfoWith:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMediaData~1createImageInfo(image:)\/fragments","op":"replace"},{"value":"preferredMediaWidth","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMediaData~1preferredMediaWidth\/title"},{"value":[{"text":"preferredMediaWidth","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMediaData~1preferredMediaWidth\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMediaData~1createC2SInfo(type:c2sAspectRatio:)\/title","value":"createC2SInfoWith:aspectRatio:"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMediaData~1createC2SInfo(type:c2sAspectRatio:)\/fragments","value":[{"kind":"text","text":"+ "},{"text":"createC2SInfoWith:aspectRatio:","kind":"identifier"}]},{"op":"replace","value":"aspectRatio","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMediaData~1aspectRatio\/title"},{"op":"replace","value":[{"kind":"identifier","text":"aspectRatio"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMediaData~1aspectRatio\/fragments"},{"op":"replace","value":"createComplexMediaInfo:videoController:","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMediaData~1createComplexMediaInfo(image:videoController:)\/title"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createComplexMediaInfo:videoController:"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMediaData~1createComplexMediaInfo(image:videoController:)\/fragments"},{"value":"richMediaData","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMediaData~1richMediaData\/title"},{"value":[{"text":"richMediaData","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMediaData~1richMediaData\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMediaData~1preferredHeightWithFixedWidth(_:)\/title","value":"preferredHeightWithFixedWidth:"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMediaData~1preferredHeightWithFixedWidth(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"preferredHeightWithFixedWidth:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMediaData~1createRichMediaInfo()\/title","op":"replace","value":"createRichMediaInfo"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createRichMediaInfo"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMediaData~1createRichMediaInfo()\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMediaData~1mediaType\/title","value":"mediaType"},{"op":"replace","value":[{"kind":"identifier","text":"mediaType"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMediaData~1mediaType\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMediaData~1createRichMediaInfo(richMediaInfo:)\/title","value":"createRichMediaInfo:","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMediaData~1createRichMediaInfo(richMediaInfo:)\/fragments","value":[{"kind":"text","text":"+ "},{"text":"createRichMediaInfo:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMediaData~1preferredMediaHeight\/title","value":"preferredMediaHeight"},{"value":[{"kind":"identifier","text":"preferredMediaHeight"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMediaData~1preferredMediaHeight\/fragments"},{"value":"carouselHeightDelegate","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMediaData~1carouselHeightDelegate\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMediaData~1carouselHeightDelegate\/fragments","value":[{"text":"carouselHeightDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMediaData~1description\/title","value":"description"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMediaData~1description\/fragments","value":[{"text":"description","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMediaData~1createVideoInfo(videoController:)\/title","value":"createVideoInfoWith:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMediaData~1createVideoInfo(videoController:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createVideoInfoWith:"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMediaData\/title","value":"GFPMediaData","op":"replace"},{"value":[{"text":"GFPMediaData","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMediaData\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMediaData\/navigatorTitle","value":[{"kind":"identifier","text":"GFPMediaData"}]},{"value":"image","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMediaData~1image\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMediaData~1image\/fragments","value":[{"kind":"identifier","text":"image"}]},{"op":"replace","value":"createCarouseMedialInfo","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMediaData~1createCarouselMediaInfo()\/title"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"createCarouseMedialInfo"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMediaData~1createCarouselMediaInfo()\/fragments"},{"op":"replace","value":"unknwonAspectRatio","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMediaData~1unknwonAspectRatio\/title"},{"value":[{"text":"unknwonAspectRatio","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMediaData~1unknwonAspectRatio\/fragments"},{"op":"replace","value":"videoController","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMediaData~1videoController\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMediaData~1videoController\/fragments","value":[{"text":"videoController","kind":"identifier"}]}]}]}