{"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpnativesimpleadview"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpnativesimpleadview"]}],"metadata":{"navigatorTitle":[{"text":"GFPNativeSimpleAdView","kind":"identifier"}],"externalID":"c:objc(cs)GFPNativeSimpleAdView","symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPNativeSimpleAdView"}],"role":"symbol","roleHeading":"Class","modules":[{"name":"GFPSDK"}],"title":"GFPNativeSimpleAdView"},"topicSections":[{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdView\/nativeAd"],"anchor":"Instance-Properties"}],"relationshipsSections":[{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeBaseView"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"},{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSCoding","doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)CALayerDelegate","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s7CVarArgP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s23CustomStringConvertibleP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s8SendableP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UIAccessibilityIdentification","doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UIAppearance","doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UIAppearanceContainer","doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UICoordinateSpace","doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UIDynamicItem","doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UIFocusEnvironment","doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UIFocusItem","doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UIFocusItemContainer","doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UILargeContentViewerItem","doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.navercorp.da.gfp.GFPSDK\/5UIKit23UITraitChangeObservableP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UITraitEnvironment","doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","type":"conformsTo","title":"Conforms To"}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPNativeSimpleAdView"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdView","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)UILargeContentViewerItem":{"title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UILargeContentViewerItem","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)UIPasteConfigurationSupporting":{"title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UIPasteConfigurationSupporting","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)UIResponderStandardEditActions":{"title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UIResponderStandardEditActions","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeSimpleAdView":{"kind":"symbol","navigatorTitle":[{"text":"GFPNativeSimpleAdView","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdView","title":"GFPNativeSimpleAdView","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPNativeSimpleAdView","kind":"identifier"}],"type":"topic","url":"\/documentation\/gfpsdk\/gfpnativesimpleadview","abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)UIPopoverPresentationControllerSourceItem":{"title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UIPopoverPresentationControllerSourceItem","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/s8SendableP":{"title":"Swift.Sendable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s8SendableP","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s7CVarArgP","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)UIFocusItemContainer":{"title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UIFocusItemContainer","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)UIFocusItem":{"title":"UIKit.UIFocusItem","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UIFocusItem","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)UITraitEnvironment":{"title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UITraitEnvironment","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeSimpleAdView/nativeAd":{"kind":"symbol","title":"nativeAd","url":"\/documentation\/gfpsdk\/gfpnativesimpleadview\/nativead","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"nativeAd","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPNativeSimpleAd","text":"GFPNativeSimpleAd"},{"text":"?","kind":"text"}],"type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdView\/nativeAd","navigatorTitle":[{"kind":"identifier","text":"nativeAd"}],"abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeBaseView":{"kind":"symbol","type":"topic","abstract":[],"url":"\/documentation\/gfpsdk\/gfpnativebaseview","navigatorTitle":[{"text":"GFPNativeBaseView","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPNativeBaseView"}],"title":"GFPNativeBaseView","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeBaseView"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)UIActivityItemsConfigurationProviding":{"title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UIActivityItemsConfigurationProviding","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)UIAppearanceContainer":{"title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UIAppearanceContainer","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/5UIKit23UITraitChangeObservableP":{"title":"UIKit.UITraitChangeObservable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/5UIKit23UITraitChangeObservableP","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)UIAccessibilityIdentification":{"title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UIAccessibilityIdentification","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)UICoordinateSpace":{"title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UICoordinateSpace","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)NSCoding":{"title":"Foundation.NSCoding","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSCoding","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)UIFocusEnvironment":{"title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UIFocusEnvironment","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)UIAppearance":{"title":"UIKit.UIAppearance","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UIAppearance","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)CALayerDelegate":{"title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)CALayerDelegate","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)UIDynamicItem":{"title":"UIKit.UIDynamicItem","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UIDynamicItem","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)UIUserActivityRestoring":{"title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UIUserActivityRestoring","type":"unresolvable"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"GFPNativeSimpleAdView"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","value":[{"text":"GFPNativeSimpleAdView","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"GFPNativeSimpleAdView"}]},{"op":"replace","value":[{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdView\/nativeAd"],"anchor":"Instance-Properties","title":"Instance Properties","generated":true}],"path":"\/topicSections"},{"value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeBaseView"],"type":"inheritsFrom"}],"path":"\/relationshipsSections","op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPNativeSimpleAdView","kind":"identifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPNativeBaseView","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeBaseView","text":"GFPNativeBaseView"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdView\/title","op":"replace","value":"GFPNativeSimpleAdView"},{"value":[{"kind":"identifier","text":"GFPNativeSimpleAdView"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdView\/fragments"},{"op":"replace","value":[{"text":"GFPNativeSimpleAdView","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdView\/navigatorTitle"},{"value":"nativeAd","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdView~1nativeAd\/title"},{"value":[{"text":"nativeAd","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdView~1nativeAd\/fragments"},{"value":"GFPNativeBaseView","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeBaseView\/title"},{"value":[{"text":"GFPNativeBaseView","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeBaseView\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"GFPNativeBaseView"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeBaseView\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}