{"topicSections":[{"generated":true,"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdaptorDelegate\/nativeAdAdaptor(_:didChangeMediaViewSizeWith:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdaptorDelegate\/nativeAdAdaptor(_:didChangeUserInterest:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdaptorDelegate\/nativeAdAdaptor(_:didFailWithError:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdaptorDelegate\/nativeAdAdaptor(_:didReloadFailWithError:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdaptorDelegate\/nativeAdAdaptor(_:richAdExtendSizeChanged:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdaptorDelegate\/nativeAdAdaptorDidDismissDefault(inAppBrowser:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdaptorDelegate\/nativeAdAdaptorDidPresentDefault(inAppBrowser:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdaptorDelegate\/nativeAdAdaptorDidReloadMedia(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdaptorDelegate\/nativeAdWas(onActiveImpression:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdaptorDelegate\/nativeAdWasCanceledMute(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdaptorDelegate\/nativeAdWasClicked(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdaptorDelegate\/nativeAdWasMuted(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdaptorDelegate\/nativeRichAdExtendComplete(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdaptorDelegate\/nativeRichAdExtendStart(_:to:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdaptorDelegate\/nativeRichAdShrinkComplete(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdaptorDelegate\/nativeRichAdShrinkStart(_:to:)"]}],"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdaptorDelegate","interfaceLanguage":"swift"},"metadata":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPNativeAdaptorDelegate","kind":"identifier"}],"externalID":"c:objc(pl)GFPNativeAdaptorDelegate","roleHeading":"Protocol","navigatorTitle":[{"kind":"identifier","text":"GFPNativeAdaptorDelegate"}],"role":"symbol","symbolKind":"protocol","modules":[{"name":"GFPSDK"}],"title":"GFPNativeAdaptorDelegate"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPNativeAdaptorDelegate"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier","text":"NSObjectProtocol"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpnativeadaptordelegate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpnativeadaptordelegate"]}],"kind":"symbol","relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject"],"type":"inheritsFrom","kind":"relationships"}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdaptorDelegate/nativeAdAdaptor(_:richAdExtendSizeChanged:)":{"abstract":[],"type":"topic","title":"nativeAdAdaptor(_:richAdExtendSizeChanged:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nativeAdAdaptor","kind":"identifier"},{"kind":"text","text":"(any "},{"text":"GFPAdAdaptor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdAdaptor"},{"kind":"text","text":" & "},{"preciseIdentifier":"c:objc(pl)GFPNativeAdapting","kind":"typeIdentifier","text":"GFPNativeAdapting"},{"text":", ","kind":"text"},{"text":"richAdExtendSizeChanged","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize","text":"CGSize"},{"kind":"text","text":")"}],"url":"\/documentation\/gfpsdk\/gfpnativeadaptordelegate\/nativeadadaptor(_:richadextendsizechanged:)","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdaptorDelegate\/nativeAdAdaptor(_:richAdExtendSizeChanged:)","navigatorTitle":[{"kind":"identifier","text":"nativeAdAdaptor:richAdExtendSizeChanged:"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdaptorDelegate/nativeAdAdaptor(_:didChangeMediaViewSizeWith:)":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"nativeAdAdaptor:didChangeMediaViewSizeWith:"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdaptorDelegate\/nativeAdAdaptor(_:didChangeMediaViewSizeWith:)","type":"topic","title":"nativeAdAdaptor(_:didChangeMediaViewSizeWith:)","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"nativeAdAdaptor"},{"text":"(any ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPAdAdaptor","kind":"typeIdentifier","text":"GFPAdAdaptor"},{"text":" & ","kind":"text"},{"kind":"typeIdentifier","text":"GFPNativeAdapting","preciseIdentifier":"c:objc(pl)GFPNativeAdapting"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didChangeMediaViewSizeWith"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"text":")","kind":"text"}],"url":"\/documentation\/gfpsdk\/gfpnativeadaptordelegate\/nativeadadaptor(_:didchangemediaviewsizewith:)","role":"symbol","required":true},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdaptorDelegate/nativeAdAdaptorDidDismissDefault(inAppBrowser:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"nativeAdAdaptorDidDismissDefault","kind":"identifier"},{"kind":"text","text":"("},{"text":"inAppBrowser","kind":"externalParam"},{"kind":"text","text":": any "},{"text":"GFPAdAdaptor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdAdaptor"},{"kind":"text","text":" & "},{"text":"GFPNativeAdapting","preciseIdentifier":"c:objc(pl)GFPNativeAdapting","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"nativeAdAdaptorDidDismissDefaultInAppBrowser:"}],"url":"\/documentation\/gfpsdk\/gfpnativeadaptordelegate\/nativeadadaptordiddismissdefault(inappbrowser:)","type":"topic","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdaptorDelegate\/nativeAdAdaptorDidDismissDefault(inAppBrowser:)","abstract":[],"title":"nativeAdAdaptorDidDismissDefault(inAppBrowser:)","kind":"symbol","required":true},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdaptorDelegate":{"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"GFPNativeAdaptorDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"GFPNativeAdaptorDelegate","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdaptorDelegate","role":"symbol","url":"\/documentation\/gfpsdk\/gfpnativeadaptordelegate","title":"GFPNativeAdaptorDelegate","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdaptorDelegate/nativeAdAdaptorDidReloadMedia(_:)":{"abstract":[],"required":true,"url":"\/documentation\/gfpsdk\/gfpnativeadaptordelegate\/nativeadadaptordidreloadmedia(_:)","role":"symbol","title":"nativeAdAdaptorDidReloadMedia(_:)","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdaptorDelegate\/nativeAdAdaptorDidReloadMedia(_:)","navigatorTitle":[{"text":"nativeAdAdaptorDidReloadMedia:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"nativeAdAdaptorDidReloadMedia","kind":"identifier"},{"kind":"text","text":"(any "},{"kind":"typeIdentifier","text":"GFPAdAdaptor","preciseIdentifier":"c:objc(cs)GFPAdAdaptor"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)GFPNativeAdapting","text":"GFPNativeAdapting"},{"text":")","kind":"text"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdaptorDelegate/nativeRichAdExtendComplete(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"nativeRichAdExtendComplete","kind":"identifier"},{"kind":"text","text":"(any "},{"text":"GFPAdAdaptor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdAdaptor"},{"kind":"text","text":" & "},{"text":"GFPNativeAdapting","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)GFPNativeAdapting"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"nativeRichAdExtendComplete:","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpnativeadaptordelegate\/nativerichadextendcomplete(_:)","type":"topic","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdaptorDelegate\/nativeRichAdExtendComplete(_:)","abstract":[],"title":"nativeRichAdExtendComplete(_:)","kind":"symbol","required":true},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdaptorDelegate/nativeAdWas(onActiveImpression:)":{"navigatorTitle":[{"kind":"identifier","text":"nativeAdWasOnActiveImpression:"}],"type":"topic","title":"nativeAdWas(onActiveImpression:)","kind":"symbol","url":"\/documentation\/gfpsdk\/gfpnativeadaptordelegate\/nativeadwas(onactiveimpression:)","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdaptorDelegate\/nativeAdWas(onActiveImpression:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"nativeAdWas","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"onActiveImpression"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","text":"GFPAdAdaptor","preciseIdentifier":"c:objc(cs)GFPAdAdaptor"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"GFPNativeAdapting","preciseIdentifier":"c:objc(pl)GFPNativeAdapting"},{"kind":"text","text":")"}],"required":true,"role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdaptorDelegate/nativeAdAdaptorDidPresentDefault(inAppBrowser:)":{"type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdaptorDelegate\/nativeAdAdaptorDidPresentDefault(inAppBrowser:)","abstract":[],"title":"nativeAdAdaptorDidPresentDefault(inAppBrowser:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"nativeAdAdaptorDidPresentDefault","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"inAppBrowser"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","text":"GFPAdAdaptor","preciseIdentifier":"c:objc(cs)GFPAdAdaptor"},{"text":" & ","kind":"text"},{"preciseIdentifier":"c:objc(pl)GFPNativeAdapting","kind":"typeIdentifier","text":"GFPNativeAdapting"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"nativeAdAdaptorDidPresentDefaultInAppBrowser:","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpnativeadaptordelegate\/nativeadadaptordidpresentdefault(inappbrowser:)","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdaptorDelegate/nativeRichAdExtendStart(_:to:)":{"type":"topic","role":"symbol","required":true,"kind":"symbol","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdaptorDelegate\/nativeRichAdExtendStart(_:to:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"nativeRichAdExtendStart"},{"text":"(any ","kind":"text"},{"kind":"typeIdentifier","text":"GFPAdAdaptor","preciseIdentifier":"c:objc(cs)GFPAdAdaptor"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"GFPNativeAdapting","preciseIdentifier":"c:objc(pl)GFPNativeAdapting"},{"text":", ","kind":"text"},{"text":"to","kind":"externalParam"},{"kind":"text","text":": "},{"text":"CGSize","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"nativeRichAdExtendStart:toSize:"}],"title":"nativeRichAdExtendStart(_:to:)","url":"\/documentation\/gfpsdk\/gfpnativeadaptordelegate\/nativerichadextendstart(_:to:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdaptorDelegate/nativeAdWasCanceledMute(_:)":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdaptorDelegate\/nativeAdWasCanceledMute(_:)","abstract":[],"kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"nativeAdWasCanceledMute","kind":"identifier"},{"text":"(any ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPAdAdaptor","text":"GFPAdAdaptor","kind":"typeIdentifier"},{"kind":"text","text":" & "},{"preciseIdentifier":"c:objc(pl)GFPNativeAdapting","kind":"typeIdentifier","text":"GFPNativeAdapting"},{"kind":"text","text":")"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"nativeAdWasCanceledMute:"}],"required":true,"title":"nativeAdWasCanceledMute(_:)","url":"\/documentation\/gfpsdk\/gfpnativeadaptordelegate\/nativeadwascanceledmute(_:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdaptorDelegate/nativeRichAdShrinkStart(_:to:)":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdaptorDelegate\/nativeRichAdShrinkStart(_:to:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"nativeRichAdShrinkStart","kind":"identifier"},{"kind":"text","text":"(any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdAdaptor","text":"GFPAdAdaptor"},{"text":" & ","kind":"text"},{"text":"GFPNativeAdapting","preciseIdentifier":"c:objc(pl)GFPNativeAdapting","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"to"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier","text":"CGSize"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"nativeRichAdShrinkStart:toSize:","kind":"identifier"}],"required":true,"abstract":[],"type":"topic","url":"\/documentation\/gfpsdk\/gfpnativeadaptordelegate\/nativerichadshrinkstart(_:to:)","title":"nativeRichAdShrinkStart(_:to:)","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdaptorDelegate/nativeAdWasMuted(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"nativeAdWasMuted","kind":"identifier"},{"text":"(any ","kind":"text"},{"kind":"typeIdentifier","text":"GFPAdAdaptor","preciseIdentifier":"c:objc(cs)GFPAdAdaptor"},{"text":" & ","kind":"text"},{"kind":"typeIdentifier","text":"GFPNativeAdapting","preciseIdentifier":"c:objc(pl)GFPNativeAdapting"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"nativeAdWasMuted:"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdaptorDelegate\/nativeAdWasMuted(_:)","url":"\/documentation\/gfpsdk\/gfpnativeadaptordelegate\/nativeadwasmuted(_:)","kind":"symbol","role":"symbol","required":true,"abstract":[],"type":"topic","title":"nativeAdWasMuted(_:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdaptorDelegate/nativeAdAdaptor(_:didFailWithError:)":{"abstract":[],"title":"nativeAdAdaptor(_:didFailWithError:)","kind":"symbol","required":true,"role":"symbol","navigatorTitle":[{"text":"nativeAdAdaptor:didFailWithError:","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdaptorDelegate\/nativeAdAdaptor(_:didFailWithError:)","url":"\/documentation\/gfpsdk\/gfpnativeadaptordelegate\/nativeadadaptor(_:didfailwitherror:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"nativeAdAdaptor","kind":"identifier"},{"text":"(any ","kind":"text"},{"text":"GFPAdAdaptor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdAdaptor"},{"text":" & ","kind":"text"},{"text":"GFPNativeAdapting","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)GFPNativeAdapting"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didFailWithError"},{"kind":"text","text":": "},{"text":"GFPError","kind":"typeIdentifier","preciseIdentifier":"c:@M@NaverAdsServices@objc(cs)GFPError"},{"kind":"text","text":")"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdaptorDelegate/nativeAdWasClicked(_:)":{"title":"nativeAdWasClicked(_:)","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdaptorDelegate\/nativeAdWasClicked(_:)","type":"topic","url":"\/documentation\/gfpsdk\/gfpnativeadaptordelegate\/nativeadwasclicked(_:)","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"nativeAdWasClicked"},{"kind":"text","text":"(any "},{"kind":"typeIdentifier","text":"GFPAdAdaptor","preciseIdentifier":"c:objc(cs)GFPAdAdaptor"},{"kind":"text","text":" & "},{"preciseIdentifier":"c:objc(pl)GFPNativeAdapting","kind":"typeIdentifier","text":"GFPNativeAdapting"},{"text":")","kind":"text"}],"kind":"symbol","navigatorTitle":[{"text":"nativeAdWasClicked:","kind":"identifier"}],"required":true,"role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdaptorDelegate/nativeAdAdaptor(_:didReloadFailWithError:)":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdaptorDelegate\/nativeAdAdaptor(_:didReloadFailWithError:)","abstract":[],"title":"nativeAdAdaptor(_:didReloadFailWithError:)","url":"\/documentation\/gfpsdk\/gfpnativeadaptordelegate\/nativeadadaptor(_:didreloadfailwitherror:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"nativeAdAdaptor","kind":"identifier"},{"kind":"text","text":"(any "},{"preciseIdentifier":"c:objc(cs)GFPAdAdaptor","kind":"typeIdentifier","text":"GFPAdAdaptor"},{"text":" & ","kind":"text"},{"text":"GFPNativeAdapting","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)GFPNativeAdapting"},{"text":", ","kind":"text"},{"text":"didReloadFailWithError","kind":"externalParam"},{"kind":"text","text":": "},{"text":"GFPError","preciseIdentifier":"c:@M@NaverAdsServices@objc(cs)GFPError","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"nativeAdAdaptor:didReloadFailWithError:","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdaptorDelegate/nativeRichAdShrinkComplete(_:)":{"url":"\/documentation\/gfpsdk\/gfpnativeadaptordelegate\/nativerichadshrinkcomplete(_:)","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdaptorDelegate\/nativeRichAdShrinkComplete(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"nativeRichAdShrinkComplete"},{"kind":"text","text":"(any "},{"text":"GFPAdAdaptor","preciseIdentifier":"c:objc(cs)GFPAdAdaptor","kind":"typeIdentifier"},{"text":" & ","kind":"text"},{"text":"GFPNativeAdapting","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)GFPNativeAdapting"},{"text":")","kind":"text"}],"title":"nativeRichAdShrinkComplete(_:)","type":"topic","kind":"symbol","abstract":[],"navigatorTitle":[{"text":"nativeRichAdShrinkComplete:","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdaptorDelegate/nativeAdAdaptor(_:didChangeUserInterest:)":{"type":"topic","abstract":[],"required":true,"role":"symbol","title":"nativeAdAdaptor(_:didChangeUserInterest:)","kind":"symbol","url":"\/documentation\/gfpsdk\/gfpnativeadaptordelegate\/nativeadadaptor(_:didchangeuserinterest:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"nativeAdAdaptor","kind":"identifier"},{"text":"(any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdAdaptor","text":"GFPAdAdaptor"},{"text":" & ","kind":"text"},{"preciseIdentifier":"c:objc(pl)GFPNativeAdapting","kind":"typeIdentifier","text":"GFPNativeAdapting"},{"kind":"text","text":", "},{"text":"didChangeUserInterest","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"nativeAdAdaptor:didChangeUserInterest:","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdaptorDelegate\/nativeAdAdaptor(_:didChangeUserInterest:)"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"value":"GFPNativeAdaptorDelegate","op":"replace","path":"\/metadata\/title"},{"value":"protocol","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GFPNativeAdaptorDelegate"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"GFPNativeAdaptorDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"replace","value":[{"anchor":"Instance-Methods","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdaptorDelegate\/nativeAdAdaptor(_:didChangeMediaViewSizeWith:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdaptorDelegate\/nativeAdAdaptor(_:didChangeUserInterest:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdaptorDelegate\/nativeAdAdaptor(_:didFailWithError:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdaptorDelegate\/nativeAdAdaptor(_:didReloadFailWithError:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdaptorDelegate\/nativeAdAdaptor(_:richAdExtendSizeChanged:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdaptorDelegate\/nativeAdAdaptorDidDismissDefault(inAppBrowser:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdaptorDelegate\/nativeAdAdaptorDidPresentDefault(inAppBrowser:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdaptorDelegate\/nativeAdAdaptorDidReloadMedia(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdaptorDelegate\/nativeAdWas(onActiveImpression:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdaptorDelegate\/nativeAdWasCanceledMute(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdaptorDelegate\/nativeAdWasClicked(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdaptorDelegate\/nativeAdWasMuted(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdaptorDelegate\/nativeRichAdExtendComplete(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdaptorDelegate\/nativeRichAdExtendStart(_:to:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdaptorDelegate\/nativeRichAdShrinkComplete(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdaptorDelegate\/nativeRichAdShrinkStart(_:to:)"],"generated":true,"title":"Instance Methods"}]},{"value":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject"]}],"op":"replace","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPNativeAdaptorDelegate"},{"kind":"text","text":" <"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject","text":"NSObject"},{"text":">","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdaptorDelegate~1nativeAdAdaptor(_:richAdExtendSizeChanged:)\/title","value":"nativeAdAdaptor:richAdExtendSizeChanged:","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"nativeAdAdaptor:richAdExtendSizeChanged:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdaptorDelegate~1nativeAdAdaptor(_:richAdExtendSizeChanged:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdaptorDelegate~1nativeAdAdaptor(_:didChangeMediaViewSizeWith:)\/title","value":"nativeAdAdaptor:didChangeMediaViewSizeWith:"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdaptorDelegate~1nativeAdAdaptor(_:didChangeMediaViewSizeWith:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"nativeAdAdaptor:didChangeMediaViewSizeWith:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdaptorDelegate~1nativeAdAdaptorDidDismissDefault(inAppBrowser:)\/title","value":"nativeAdAdaptorDidDismissDefaultInAppBrowser:"},{"value":[{"text":"- ","kind":"text"},{"text":"nativeAdAdaptorDidDismissDefaultInAppBrowser:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdaptorDelegate~1nativeAdAdaptorDidDismissDefault(inAppBrowser:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdaptorDelegate\/title","op":"replace","value":"GFPNativeAdaptorDelegate"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdaptorDelegate\/fragments","value":[{"kind":"identifier","text":"GFPNativeAdaptorDelegate"}],"op":"replace"},{"value":[{"text":"GFPNativeAdaptorDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdaptorDelegate\/navigatorTitle","op":"replace"},{"value":"nativeAdAdaptorDidReloadMedia:","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdaptorDelegate~1nativeAdAdaptorDidReloadMedia(_:)\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdaptorDelegate~1nativeAdAdaptorDidReloadMedia(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"nativeAdAdaptorDidReloadMedia:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdaptorDelegate~1nativeRichAdExtendComplete(_:)\/title","op":"replace","value":"nativeRichAdExtendComplete:"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdaptorDelegate~1nativeRichAdExtendComplete(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"nativeRichAdExtendComplete:","kind":"identifier"}]},{"value":"nativeAdWasOnActiveImpression:","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdaptorDelegate~1nativeAdWas(onActiveImpression:)\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdaptorDelegate~1nativeAdWas(onActiveImpression:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"nativeAdWasOnActiveImpression:","kind":"identifier"}],"op":"replace"},{"value":"nativeAdAdaptorDidPresentDefaultInAppBrowser:","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdaptorDelegate~1nativeAdAdaptorDidPresentDefault(inAppBrowser:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"nativeAdAdaptorDidPresentDefaultInAppBrowser:"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdaptorDelegate~1nativeAdAdaptorDidPresentDefault(inAppBrowser:)\/fragments"},{"op":"replace","value":"nativeRichAdExtendStart:toSize:","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdaptorDelegate~1nativeRichAdExtendStart(_:to:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdaptorDelegate~1nativeRichAdExtendStart(_:to:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"nativeRichAdExtendStart:toSize:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdaptorDelegate~1nativeAdWasCanceledMute(_:)\/title","value":"nativeAdWasCanceledMute:"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdaptorDelegate~1nativeAdWasCanceledMute(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"nativeAdWasCanceledMute:"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdaptorDelegate~1nativeRichAdShrinkStart(_:to:)\/title","value":"nativeRichAdShrinkStart:toSize:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdaptorDelegate~1nativeRichAdShrinkStart(_:to:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"nativeRichAdShrinkStart:toSize:","kind":"identifier"}]},{"value":"nativeAdWasMuted:","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdaptorDelegate~1nativeAdWasMuted(_:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"nativeAdWasMuted:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdaptorDelegate~1nativeAdWasMuted(_:)\/fragments"},{"op":"replace","value":"nativeAdAdaptor:didFailWithError:","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdaptorDelegate~1nativeAdAdaptor(_:didFailWithError:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdaptorDelegate~1nativeAdAdaptor(_:didFailWithError:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"nativeAdAdaptor:didFailWithError:"}]},{"value":"nativeAdWasClicked:","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdaptorDelegate~1nativeAdWasClicked(_:)\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdaptorDelegate~1nativeAdWasClicked(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"nativeAdWasClicked:"}]},{"value":"nativeAdAdaptor:didReloadFailWithError:","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdaptorDelegate~1nativeAdAdaptor(_:didReloadFailWithError:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"nativeAdAdaptor:didReloadFailWithError:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdaptorDelegate~1nativeAdAdaptor(_:didReloadFailWithError:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdaptorDelegate~1nativeRichAdShrinkComplete(_:)\/title","value":"nativeRichAdShrinkComplete:"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdaptorDelegate~1nativeRichAdShrinkComplete(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"nativeRichAdShrinkComplete:","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"nativeAdAdaptor:didChangeUserInterest:","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdaptorDelegate~1nativeAdAdaptor(_:didChangeUserInterest:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdaptorDelegate~1nativeAdAdaptor(_:didChangeUserInterest:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"nativeAdAdaptor:didChangeUserInterest:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}