{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpnativecarouselnotsupportedslotvisualsuberrorcodekey"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpnativecarouselnotsupportedslotvisualsuberrorcodekey"]}],"metadata":{"modules":[{"name":"GFPSDK"}],"symbolKind":"var","title":"GFPNativeCarouselNotSupportedSlotVisualSubErrorCodeKey","roleHeading":"Global Variable","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPNativeCarouselNotSupportedSlotVisualSubErrorCodeKey","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"GFPNativeCarouselNotSupportedSlotVisualSubErrorCodeKey"}],"role":"symbol","externalID":"c:@GFPNativeCarouselNotSupportedSlotVisualSubErrorCodeKey"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeCarouselNotSupportedSlotVisualSubErrorCodeKey"},"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPNativeCarouselNotSupportedSlotVisualSubErrorCodeKey"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeCarouselNotSupportedSlotVisualSubErrorCodeKey":{"kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeCarouselNotSupportedSlotVisualSubErrorCodeKey","role":"symbol","title":"GFPNativeCarouselNotSupportedSlotVisualSubErrorCodeKey","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPNativeCarouselNotSupportedSlotVisualSubErrorCodeKey"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"navigatorTitle":[{"kind":"identifier","text":"GFPNativeCarouselNotSupportedSlotVisualSubErrorCodeKey"}],"url":"\/documentation\/gfpsdk\/gfpnativecarouselnotsupportedslotvisualsuberrorcodekey"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Global Variable"},{"op":"replace","path":"\/metadata\/title","value":"GFPNativeCarouselNotSupportedSlotVisualSubErrorCodeKey"},{"value":"var","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GFPNativeCarouselNotSupportedSlotVisualSubErrorCodeKey"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"GFPNativeCarouselNotSupportedSlotVisualSubErrorCodeKey"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"GFPNativeCarouselNotSupportedSlotVisualSubErrorCodeKey","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeCarouselNotSupportedSlotVisualSubErrorCodeKey\/title"},{"value":[{"kind":"identifier","text":"GFPNativeCarouselNotSupportedSlotVisualSubErrorCodeKey"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeCarouselNotSupportedSlotVisualSubErrorCodeKey\/fragments","op":"replace"}]}]}