{"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeExtraTextInfo","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"GFPNativeExtraTextInfo","kind":"identifier"}]}]}],"topicSections":[{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeExtraTextInfo\/init(dict:link:)"],"title":"Initializers","generated":true,"anchor":"Initializers"}],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpnativeextratextinfo"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gfpsdk\/gfpnativeextratextinfo"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"GFPNativeExtraTextInfo","kind":"identifier"}],"roleHeading":"Class","modules":[{"name":"GFPSDK"}],"role":"symbol","symbolKind":"class","navigatorTitle":[{"text":"GFPNativeExtraTextInfo","kind":"identifier"}],"title":"GFPNativeExtraTextInfo","externalID":"c:objc(cs)GFPNativeExtraTextInfo"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"relationshipsSections":[{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"},{"kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdInfoExtStylePresentable","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdInfoLabelPresentable","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdInfoLinkPresentable","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdLabelOptionPresentable","doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s7CVarArgP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s23CustomStringConvertibleP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH"],"title":"Conforms To"}],"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject"},"doc://com.navercorp.da.gfp.GFPSDK/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeExtraTextInfo/init(dict:link:)":{"type":"topic","title":"init(dict:link:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"dict","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"], "},{"text":"link","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"GFPNativeLinkInfo","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPNativeLinkInfo"},{"text":")","kind":"text"}],"abstract":[],"url":"\/documentation\/gfpsdk\/gfpnativeextratextinfo\/init(dict:link:)","kind":"symbol","navigatorTitle":[{"text":"initWithDict:link:","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeExtraTextInfo\/init(dict:link:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeExtraTextInfo":{"navigatorTitle":[{"text":"GFPNativeExtraTextInfo","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeExtraTextInfo","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPNativeExtraTextInfo","kind":"identifier"}],"title":"GFPNativeExtraTextInfo","abstract":[],"kind":"symbol","type":"topic","url":"\/documentation\/gfpsdk\/gfpnativeextratextinfo"},"doc://com.navercorp.da.gfp.GFPSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s23CustomStringConvertibleP"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdInfoExtStylePresentable":{"navigatorTitle":[{"kind":"identifier","text":"GFPNativeAdInfoExtStylePresentable"}],"title":"GFPNativeAdInfoExtStylePresentable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdInfoExtStylePresentable","type":"topic","url":"\/documentation\/gfpsdk\/gfpnativeadinfoextstylepresentable","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPNativeAdInfoExtStylePresentable","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdInfoLinkPresentable":{"kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdInfoLinkPresentable","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GFPNativeAdInfoLinkPresentable"}],"abstract":[],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPNativeAdInfoLinkPresentable","kind":"identifier"}],"title":"GFPNativeAdInfoLinkPresentable","url":"\/documentation\/gfpsdk\/gfpnativeadinfolinkpresentable","role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s7CVarArgP"},"doc://com.navercorp.da.gfp.GFPSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ"},"doc://com.navercorp.da.gfp.GFPSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdInfoLabelPresentable":{"abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdInfoLabelPresentable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GFPNativeAdInfoLabelPresentable"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPNativeAdInfoLabelPresentable"}],"role":"symbol","title":"GFPNativeAdInfoLabelPresentable","url":"\/documentation\/gfpsdk\/gfpnativeadinfolabelpresentable"},"doc://com.navercorp.da.gfp.GFPSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s28CustomDebugStringConvertibleP"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdLabelOptionPresentable":{"title":"GFPNativeAdLabelOptionPresentable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdLabelOptionPresentable","role":"symbol","url":"\/documentation\/gfpsdk\/gfpnativeadlabeloptionpresentable","kind":"symbol","navigatorTitle":[{"text":"GFPNativeAdLabelOptionPresentable","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"GFPNativeAdLabelOptionPresentable","kind":"identifier"}],"abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"GFPNativeExtraTextInfo"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"GFPNativeExtraTextInfo","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","value":[{"text":"GFPNativeExtraTextInfo","kind":"identifier"}],"op":"replace"},{"value":[{"anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeExtraTextInfo\/init(dict:link:)"],"title":"Instance Methods"}],"path":"\/topicSections","op":"replace"},{"value":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject"]},{"kind":"relationships","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdInfoLabelPresentable","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdInfoLinkPresentable","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdLabelOptionPresentable"],"title":"Conforms To","type":"conformsTo"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"GFPNativeExtraTextInfo","kind":"identifier"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}]}],"kind":"declarations"},"op":"replace"},{"value":"initWithDict:link:","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeExtraTextInfo~1init(dict:link:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeExtraTextInfo~1init(dict:link:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithDict:link:","kind":"identifier"}],"op":"replace"},{"value":"GFPNativeExtraTextInfo","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeExtraTextInfo\/title"},{"value":[{"text":"GFPNativeExtraTextInfo","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeExtraTextInfo\/fragments"},{"value":[{"text":"GFPNativeExtraTextInfo","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeExtraTextInfo\/navigatorTitle"},{"op":"replace","value":"GFPNativeAdInfoExtStylePresentable","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdInfoExtStylePresentable\/title"},{"value":[{"text":"GFPNativeAdInfoExtStylePresentable","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdInfoExtStylePresentable\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdInfoExtStylePresentable\/navigatorTitle","value":[{"text":"GFPNativeAdInfoExtStylePresentable","kind":"identifier"}]},{"value":"GFPNativeAdInfoLinkPresentable","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdInfoLinkPresentable\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdInfoLinkPresentable\/fragments","op":"replace","value":[{"kind":"identifier","text":"GFPNativeAdInfoLinkPresentable"}]},{"value":[{"text":"GFPNativeAdInfoLinkPresentable","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdInfoLinkPresentable\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdInfoLabelPresentable\/title","value":"GFPNativeAdInfoLabelPresentable"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdInfoLabelPresentable\/fragments","value":[{"text":"GFPNativeAdInfoLabelPresentable","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdInfoLabelPresentable\/navigatorTitle","value":[{"kind":"identifier","text":"GFPNativeAdInfoLabelPresentable"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdLabelOptionPresentable\/title","value":"GFPNativeAdLabelOptionPresentable"},{"op":"replace","value":[{"kind":"identifier","text":"GFPNativeAdLabelOptionPresentable"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdLabelOptionPresentable\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdLabelOptionPresentable\/navigatorTitle","op":"replace","value":[{"text":"GFPNativeAdLabelOptionPresentable","kind":"identifier"}]}]}]}