{"metadata":{"role":"symbol","modules":[{"name":"GFPSDK"}],"externalID":"c:@E@GFPNonLinearContainerType","roleHeading":"Structure","symbolKind":"struct","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPNonLinearContainerType"}],"navigatorTitle":[{"kind":"identifier","text":"GFPNonLinearContainerType"}],"title":"GFPNonLinearContainerType"},"sections":[],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearContainerType","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"RemindText 노출 위치에 따른 Type"},{"type":"text","text":" "},{"text":"Container Inner : Content Player 영역 내부 노출.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Container Outer : Content Player 영역 외l부 노출."}],"relationshipsSections":[{"type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/s15BitwiseCopyableP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s25ExpressibleByArrayLiteralP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s9OptionSetP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SY","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s8SendableP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s10SetAlgebraP"],"title":"Conforms To"}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPNonLinearContainerType","kind":"identifier"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpnonlinearcontainertype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gfpsdk\/gfpnonlinearcontainertype"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"anchor":"Initializers","generated":true,"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearContainerType\/init(rawValue:)"],"title":"Initializers"},{"generated":true,"anchor":"Type-Properties","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearContainerType\/inner","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearContainerType\/outer"],"title":"Type Properties"},{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearContainerType\/Equatable-Implementations","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearContainerType\/OptionSet-Implementations","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearContainerType\/SetAlgebra-Implementations"],"anchor":"Default-Implementations","generated":true,"title":"Default Implementations"}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/s10SetAlgebraP":{"type":"unresolvable","title":"Swift.SetAlgebra","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s10SetAlgebraP"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNonLinearContainerType/init(rawValue:)":{"title":"init(rawValue:)","url":"\/documentation\/gfpsdk\/gfpnonlinearcontainertype\/init(rawvalue:)","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearContainerType\/init(rawValue:)","role":"symbol","type":"topic","kind":"symbol","abstract":[],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNonLinearContainerType/outer":{"type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearContainerType\/outer","abstract":[],"title":"outer","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"outer"},{"kind":"text","text":": "},{"text":"GFPNonLinearContainerType","kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPNonLinearContainerType"}],"navigatorTitle":[{"kind":"identifier","text":"GFPNonLinearContainerTypeOuter"}],"url":"\/documentation\/gfpsdk\/gfpnonlinearcontainertype\/outer","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNonLinearContainerType/SetAlgebra-Implementations":{"type":"topic","url":"\/documentation\/gfpsdk\/gfpnonlinearcontainertype\/setalgebra-implementations","title":"SetAlgebra Implementations","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearContainerType\/SetAlgebra-Implementations","kind":"article","abstract":[],"role":"collectionGroup"},"doc://com.navercorp.da.gfp.GFPSDK/s15BitwiseCopyableP":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s15BitwiseCopyableP","title":"Swift.BitwiseCopyable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNonLinearContainerType/Equatable-Implementations":{"title":"Equatable Implementations","url":"\/documentation\/gfpsdk\/gfpnonlinearcontainertype\/equatable-implementations","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearContainerType\/Equatable-Implementations","role":"collectionGroup","type":"topic","kind":"article","abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNonLinearContainerType":{"abstract":[{"text":"RemindText 노출 위치에 따른 Type","type":"text"},{"type":"text","text":" "},{"text":"Container Inner : Content Player 영역 내부 노출.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Container Outer : Content Player 영역 외l부 노출."}],"kind":"symbol","title":"GFPNonLinearContainerType","navigatorTitle":[{"kind":"identifier","text":"GFPNonLinearContainerType"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearContainerType","url":"\/documentation\/gfpsdk\/gfpnonlinearcontainertype","type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPNonLinearContainerType"}],"role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","title":"Swift.Equatable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNonLinearContainerType/OptionSet-Implementations":{"title":"OptionSet Implementations","url":"\/documentation\/gfpsdk\/gfpnonlinearcontainertype\/optionset-implementations","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearContainerType\/OptionSet-Implementations","role":"collectionGroup","type":"topic","kind":"article","abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/SY":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SY","title":"Swift.RawRepresentable"},"doc://com.navercorp.da.gfp.GFPSDK/s9OptionSetP":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s9OptionSetP","title":"Swift.OptionSet"},"doc://com.navercorp.da.gfp.GFPSDK/s8SendableP":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s8SendableP","title":"Swift.Sendable","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNonLinearContainerType/inner":{"navigatorTitle":[{"text":"GFPNonLinearContainerTypeInner","kind":"identifier"}],"title":"inner","url":"\/documentation\/gfpsdk\/gfpnonlinearcontainertype\/inner","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearContainerType\/inner","role":"symbol","type":"topic","kind":"symbol","abstract":[],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"inner"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@GFPNonLinearContainerType","text":"GFPNonLinearContainerType","kind":"typeIdentifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/s25ExpressibleByArrayLiteralP":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s25ExpressibleByArrayLiteralP","title":"Swift.ExpressibleByArrayLiteral","type":"unresolvable"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration"},{"op":"replace","value":"GFPNonLinearContainerType","path":"\/metadata\/title"},{"value":"enum","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"GFPNonLinearContainerType","kind":"identifier"}]},{"value":[{"text":"GFPNonLinearContainerType","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"anchor":"Enumeration-Cases","title":"Enumeration Cases","generated":true,"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearContainerType\/inner","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearContainerType\/outer"]}]},{"value":null,"op":"replace","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPNonLinearContainerType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearContainerType~1outer\/title","value":"GFPNonLinearContainerTypeOuter"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearContainerType~1outer\/fragments","value":[{"kind":"identifier","text":"GFPNonLinearContainerTypeOuter"}]},{"value":"GFPNonLinearContainerType","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearContainerType\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearContainerType\/fragments","op":"replace","value":[{"kind":"identifier","text":"GFPNonLinearContainerType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearContainerType\/navigatorTitle","value":[{"kind":"identifier","text":"GFPNonLinearContainerType"}]},{"value":"GFPNonLinearContainerTypeInner","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearContainerType~1inner\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearContainerType~1inner\/fragments","value":[{"kind":"identifier","text":"GFPNonLinearContainerTypeInner"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}