{"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpnativeprovideroption"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpnativeprovideroption"]}],"abstract":[{"type":"text","text":"GFP에서 지원하는 네이티브광고 제공자 목록"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPNativeProviderOption"}],"languages":["swift"]}]}],"topicSections":[{"title":"Enumeration Cases","generated":true,"anchor":"Enumeration-Cases","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeProviderOption\/DFP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeProviderOption\/FAN","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeProviderOption\/LAN","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeProviderOption\/NDA","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeProviderOption\/bidMachine","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeProviderOption\/end","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeProviderOption\/inMobi","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeProviderOption\/none"]},{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeProviderOption\/init(rawValue:)"],"title":"Initializers","generated":true,"anchor":"Initializers"},{"title":"Default Implementations","anchor":"Default-Implementations","generated":true,"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeProviderOption\/Equatable-Implementations","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeProviderOption\/RawRepresentable-Implementations"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeProviderOption"},"relationshipsSections":[{"title":"Conforms To","type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SY"]}],"metadata":{"externalID":"c:@M@GFPSDK@E@GFPNativeProviderOption","navigatorTitle":[{"kind":"identifier","text":"GFPNativeProviderOption"}],"title":"GFPNativeProviderOption","modules":[{"name":"GFPSDK"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPNativeProviderOption"}],"roleHeading":"Enumeration","symbolKind":"enum","role":"symbol"},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeProviderOption/RawRepresentable-Implementations":{"kind":"article","type":"topic","abstract":[],"title":"RawRepresentable Implementations","url":"\/documentation\/gfpsdk\/gfpnativeprovideroption\/rawrepresentable-implementations","role":"collectionGroup","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeProviderOption\/RawRepresentable-Implementations"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeProviderOption/none":{"abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeProviderOption\/none","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPNativeProviderOptionNone"}],"role":"symbol","type":"topic","title":"GFPNativeProviderOption.none","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"none","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpnativeprovideroption\/none"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeProviderOption/bidMachine":{"navigatorTitle":[{"kind":"identifier","text":"GFPNativeProviderOptionBidMachine"}],"title":"GFPNativeProviderOption.bidMachine","url":"\/documentation\/gfpsdk\/gfpnativeprovideroption\/bidmachine","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeProviderOption\/bidMachine","role":"symbol","type":"topic","kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"bidMachine","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeProviderOption/init(rawValue:)":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeProviderOption\/init(rawValue:)","type":"topic","abstract":[],"url":"\/documentation\/gfpsdk\/gfpnativeprovideroption\/init(rawvalue:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"init(rawValue:)","role":"symbol","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/SQ":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeProviderOption":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPNativeProviderOption"}],"title":"GFPNativeProviderOption","type":"topic","kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeProviderOption","url":"\/documentation\/gfpsdk\/gfpnativeprovideroption","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPNativeProviderOption","kind":"identifier"}],"abstract":[{"type":"text","text":"GFP에서 지원하는 네이티브광고 제공자 목록"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeProviderOption/FAN":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeProviderOption\/FAN","type":"topic","abstract":[],"url":"\/documentation\/gfpsdk\/gfpnativeprovideroption\/fan","navigatorTitle":[{"kind":"identifier","text":"GFPNativeProviderOptionFAN"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FAN"}],"title":"GFPNativeProviderOption.FAN","role":"symbol","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/SY":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SY","title":"Swift.RawRepresentable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeProviderOption/LAN":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeProviderOption\/LAN","type":"topic","abstract":[],"url":"\/documentation\/gfpsdk\/gfpnativeprovideroption\/lan","navigatorTitle":[{"kind":"identifier","text":"GFPNativeProviderOptionLAN"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"LAN","kind":"identifier"}],"title":"GFPNativeProviderOption.LAN","role":"symbol","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeProviderOption/inMobi":{"navigatorTitle":[{"kind":"identifier","text":"GFPNativeProviderOptionInMobi"}],"title":"GFPNativeProviderOption.inMobi","url":"\/documentation\/gfpsdk\/gfpnativeprovideroption\/inmobi","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeProviderOption\/inMobi","role":"symbol","type":"topic","kind":"symbol","abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"inMobi"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH","title":"Swift.Hashable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeProviderOption/DFP":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DFP"}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"GFPNativeProviderOptionDFP","kind":"identifier"}],"abstract":[],"role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeProviderOption\/DFP","title":"GFPNativeProviderOption.DFP","url":"\/documentation\/gfpsdk\/gfpnativeprovideroption\/dfp"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeProviderOption/NDA":{"navigatorTitle":[{"kind":"identifier","text":"GFPNativeProviderOptionNDA"}],"title":"GFPNativeProviderOption.NDA","url":"\/documentation\/gfpsdk\/gfpnativeprovideroption\/nda","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeProviderOption\/NDA","role":"symbol","type":"topic","kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"NDA","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeProviderOption/Equatable-Implementations":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeProviderOption\/Equatable-Implementations","type":"topic","abstract":[],"url":"\/documentation\/gfpsdk\/gfpnativeprovideroption\/equatable-implementations","title":"Equatable Implementations","role":"collectionGroup","kind":"article"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeProviderOption/end":{"navigatorTitle":[{"kind":"identifier","text":"GFPNativeProviderOptionEnd"}],"title":"GFPNativeProviderOption.end","url":"\/documentation\/gfpsdk\/gfpnativeprovideroption\/end","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeProviderOption\/end","role":"symbol","type":"topic","kind":"symbol","abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"end"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration","path":"\/metadata\/roleHeading"},{"value":"GFPNativeProviderOption","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"enum"},{"value":[{"text":"GFPNativeProviderOption","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"GFPNativeProviderOption","kind":"identifier"}]},{"path":"\/topicSections","value":[{"generated":true,"anchor":"Enumeration-Cases","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeProviderOption\/DFP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeProviderOption\/FAN","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeProviderOption\/LAN","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeProviderOption\/NDA","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeProviderOption\/bidMachine","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeProviderOption\/end","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeProviderOption\/inMobi","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeProviderOption\/none"],"title":"Enumeration Cases"}],"op":"replace"},{"path":"\/relationshipsSections","op":"replace","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPNativeProviderOption"},{"text":": ","kind":"text"},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"GFPNativeProviderOptionNone","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeProviderOption~1none\/title"},{"value":[{"text":"GFPNativeProviderOptionNone","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeProviderOption~1none\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeProviderOption~1bidMachine\/title","op":"replace","value":"GFPNativeProviderOptionBidMachine"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeProviderOption~1bidMachine\/fragments","value":[{"text":"GFPNativeProviderOptionBidMachine","kind":"identifier"}]},{"value":"GFPNativeProviderOption","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeProviderOption\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeProviderOption\/fragments","op":"replace","value":[{"text":"GFPNativeProviderOption","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeProviderOption\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"GFPNativeProviderOption"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeProviderOption~1FAN\/title","value":"GFPNativeProviderOptionFAN"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeProviderOption~1FAN\/fragments","value":[{"text":"GFPNativeProviderOptionFAN","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeProviderOption~1LAN\/title","op":"replace","value":"GFPNativeProviderOptionLAN"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeProviderOption~1LAN\/fragments","value":[{"kind":"identifier","text":"GFPNativeProviderOptionLAN"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeProviderOption~1inMobi\/title","op":"replace","value":"GFPNativeProviderOptionInMobi"},{"op":"replace","value":[{"kind":"identifier","text":"GFPNativeProviderOptionInMobi"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeProviderOption~1inMobi\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeProviderOption~1DFP\/title","value":"GFPNativeProviderOptionDFP"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeProviderOption~1DFP\/fragments","op":"replace","value":[{"kind":"identifier","text":"GFPNativeProviderOptionDFP"}]},{"value":"GFPNativeProviderOptionNDA","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeProviderOption~1NDA\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeProviderOption~1NDA\/fragments","value":[{"kind":"identifier","text":"GFPNativeProviderOptionNDA"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeProviderOption~1end\/title","value":"GFPNativeProviderOptionEnd","op":"replace"},{"op":"replace","value":[{"text":"GFPNativeProviderOptionEnd","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeProviderOption~1end\/fragments"}]}]}