{"topicSections":[{"anchor":"Instance-Methods","title":"Instance Methods","generated":true,"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdAdaptor\/notifyDidChangeUserInterest(with:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdAdaptor\/updateExistUserDelegate(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdAdaptor\/updateRegisterStatus(_:adView:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdAdaptor"},"metadata":{"title":"GFPNativeAdAdaptor","symbolKind":"class","modules":[{"name":"GFPSDK"}],"role":"symbol","externalID":"c:objc(cs)GFPNativeAdAdaptor","roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPNativeAdAdaptor"}],"navigatorTitle":[{"text":"GFPNativeAdAdaptor","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPNativeAdAdaptor","kind":"identifier"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpnativeadadaptor"]},{"paths":["\/documentation\/gfpsdk\/gfpnativeadadaptor"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"kind":"symbol","relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAdaptor"],"kind":"relationships"},{"title":"Conforms To","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAdapting","doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s7CVarArgP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s23CustomStringConvertibleP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH"],"kind":"relationships","type":"conformsTo"}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdAdaptor/updateExistUserDelegate(_:)":{"navigatorTitle":[{"text":"updateExistUserDelegate:","kind":"identifier"}],"title":"updateExistUserDelegate(_:)","url":"\/documentation\/gfpsdk\/gfpnativeadadaptor\/updateexistuserdelegate(_:)","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdAdaptor\/updateExistUserDelegate(_:)","role":"symbol","type":"topic","kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateExistUserDelegate"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":")","kind":"text"}]},"doc://com.navercorp.da.gfp.GFPSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s28CustomDebugStringConvertibleP"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdAdaptor":{"navigatorTitle":[{"kind":"identifier","text":"GFPAdAdaptor"}],"title":"GFPAdAdaptor","url":"\/documentation\/gfpsdk\/gfpadadaptor","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAdaptor","abstract":[],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPAdAdaptor"}]},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdAdaptor/notifyDidChangeUserInterest(with:)":{"url":"\/documentation\/gfpsdk\/gfpnativeadadaptor\/notifydidchangeuserinterest(with:)","abstract":[],"title":"notifyDidChangeUserInterest(with:)","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdAdaptor\/notifyDidChangeUserInterest(with:)","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"notifyDidChangeUserInterestWith:","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"notifyDidChangeUserInterest","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":")","kind":"text"}]},"doc://com.navercorp.da.gfp.GFPSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH","title":"Swift.Hashable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdAdapting":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"GFPAdAdapting","kind":"identifier"}],"abstract":[],"url":"\/documentation\/gfpsdk\/gfpadadapting","kind":"symbol","role":"symbol","title":"GFPAdAdapting","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAdapting","type":"topic","navigatorTitle":[{"text":"GFPAdAdapting","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdAdaptor/updateRegisterStatus(_:adView:)":{"navigatorTitle":[{"text":"updateRegisterStatus:adView:","kind":"identifier"}],"title":"updateRegisterStatus(_:adView:)","url":"\/documentation\/gfpsdk\/gfpnativeadadaptor\/updateregisterstatus(_:adview:)","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdAdaptor\/updateRegisterStatus(_:adView:)","role":"symbol","type":"topic","kind":"symbol","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateRegisterStatus"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"adView","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UIView","preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier"},{"text":"?)","kind":"text"}]},"doc://com.navercorp.da.gfp.GFPSDK/SQ":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdAdaptor":{"url":"\/documentation\/gfpsdk\/gfpnativeadadaptor","title":"GFPNativeAdAdaptor","role":"symbol","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdAdaptor","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPNativeAdAdaptor"}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"GFPNativeAdAdaptor","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/s7CVarArgP":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"value":"GFPNativeAdAdaptor","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"GFPNativeAdAdaptor"}],"path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"GFPNativeAdAdaptor","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdAdaptor\/notifyDidChangeUserInterest(with:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdAdaptor\/updateExistUserDelegate(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdAdaptor\/updateRegisterStatus(_:adView:)"]}]},{"value":[{"title":"Inherits From","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAdaptor"],"kind":"relationships","type":"inheritsFrom"}],"op":"replace","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPNativeAdAdaptor"},{"kind":"text","text":" : "},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAdaptor","preciseIdentifier":"c:objc(cs)GFPAdAdaptor","kind":"typeIdentifier","text":"GFPAdAdaptor"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdAdaptor~1updateExistUserDelegate(_:)\/title","value":"updateExistUserDelegate:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"updateExistUserDelegate:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdAdaptor~1updateExistUserDelegate(_:)\/fragments","op":"replace"},{"value":"GFPAdAdaptor","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdaptor\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdaptor\/fragments","value":[{"text":"GFPAdAdaptor","kind":"identifier"}],"op":"replace"},{"value":[{"text":"GFPAdAdaptor","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdaptor\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdAdaptor~1notifyDidChangeUserInterest(with:)\/title","value":"notifyDidChangeUserInterestWith:"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdAdaptor~1notifyDidChangeUserInterest(with:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"notifyDidChangeUserInterestWith:"}]},{"value":"GFPAdAdapting","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdapting\/title"},{"value":[{"kind":"identifier","text":"GFPAdAdapting"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdapting\/fragments"},{"value":[{"text":"GFPAdAdapting","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdapting\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdAdaptor~1updateRegisterStatus(_:adView:)\/title","value":"updateRegisterStatus:adView:"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdAdaptor~1updateRegisterStatus(_:adView:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"updateRegisterStatus:adView:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdAdaptor\/title","value":"GFPNativeAdAdaptor","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdAdaptor\/fragments","op":"replace","value":[{"kind":"identifier","text":"GFPNativeAdAdaptor"}]},{"op":"replace","value":[{"kind":"identifier","text":"GFPNativeAdAdaptor"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdAdaptor\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}