{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeCarouselNotEnoughSlotCountSubErrorCodeKey"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPNativeCarouselNotEnoughSlotCountSubErrorCodeKey"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]}]}],"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpnativecarouselnotenoughslotcountsuberrorcodekey"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpnativecarouselnotenoughslotcountsuberrorcodekey"]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"metadata":{"symbolKind":"var","externalID":"c:@GFPNativeCarouselNotEnoughSlotCountSubErrorCodeKey","role":"symbol","modules":[{"name":"GFPSDK"}],"navigatorTitle":[{"text":"GFPNativeCarouselNotEnoughSlotCountSubErrorCodeKey","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"GFPNativeCarouselNotEnoughSlotCountSubErrorCodeKey","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"title":"GFPNativeCarouselNotEnoughSlotCountSubErrorCodeKey","roleHeading":"Global Variable"},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeCarouselNotEnoughSlotCountSubErrorCodeKey":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPNativeCarouselNotEnoughSlotCountSubErrorCodeKey"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeCarouselNotEnoughSlotCountSubErrorCodeKey","title":"GFPNativeCarouselNotEnoughSlotCountSubErrorCodeKey","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPNativeCarouselNotEnoughSlotCountSubErrorCodeKey","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"type":"topic","url":"\/documentation\/gfpsdk\/gfpnativecarouselnotenoughslotcountsuberrorcodekey","abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Global Variable"},{"path":"\/metadata\/title","op":"replace","value":"GFPNativeCarouselNotEnoughSlotCountSubErrorCodeKey"},{"value":"var","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"GFPNativeCarouselNotEnoughSlotCountSubErrorCodeKey","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"extern","kind":"keyword"},{"kind":"text","text":" "},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"kind":"identifier","text":"GFPNativeCarouselNotEnoughSlotCountSubErrorCodeKey"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"GFPNativeCarouselNotEnoughSlotCountSubErrorCodeKey","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeCarouselNotEnoughSlotCountSubErrorCodeKey\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeCarouselNotEnoughSlotCountSubErrorCodeKey\/fragments","op":"replace","value":[{"kind":"identifier","text":"GFPNativeCarouselNotEnoughSlotCountSubErrorCodeKey"}]}]}]}