{"topicSections":[{"generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdRenderingSetting\/enableMediaBackgroundBlur","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdRenderingSetting\/hasMediaView","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdRenderingSetting\/useInternalCache"],"title":"Instance Properties"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPNativeAdRenderingSetting","kind":"identifier"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpnativeadrenderingsetting"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gfpsdk\/gfpnativeadrenderingsetting"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeBaseRenderingSetting"],"title":"Inherits From","kind":"relationships"},{"title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s7CVarArgP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s23CustomStringConvertibleP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH"],"kind":"relationships"}],"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPNativeAdRenderingSetting"}],"navigatorTitle":[{"text":"GFPNativeAdRenderingSetting","kind":"identifier"}],"roleHeading":"Class","externalID":"c:objc(cs)GFPNativeAdRenderingSetting","role":"symbol","modules":[{"name":"GFPSDK"}],"title":"GFPNativeAdRenderingSetting","symbolKind":"class"},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdRenderingSetting","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdRenderingSetting":{"abstract":[],"kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdRenderingSetting","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPNativeAdRenderingSetting"}],"url":"\/documentation\/gfpsdk\/gfpnativeadrenderingsetting","title":"GFPNativeAdRenderingSetting","navigatorTitle":[{"kind":"identifier","text":"GFPNativeAdRenderingSetting"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdRenderingSetting/enableMediaBackgroundBlur":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"enableMediaBackgroundBlur","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"kind":"symbol","navigatorTitle":[{"text":"enableMediaBackgroundBlur","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdRenderingSetting\/enableMediaBackgroundBlur","abstract":[{"type":"text","text":"네이티브 광고 미디어뷰 여백의 블러처리 여부를 설정합니다."},{"type":"text","text":" "},{"type":"text","text":"(기본값은 NO)"}],"role":"symbol","url":"\/documentation\/gfpsdk\/gfpnativeadrenderingsetting\/enablemediabackgroundblur","title":"enableMediaBackgroundBlur","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdRenderingSetting/hasMediaView":{"abstract":[{"text":"네이티브 광고 레이아웃에 미디어 뷰가 포함되는지 여부에 따라 설정합니다.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"(기본값은 YES)"}],"url":"\/documentation\/gfpsdk\/gfpnativeadrenderingsetting\/hasmediaview","role":"symbol","navigatorTitle":[{"text":"hasMediaView","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"hasMediaView","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"title":"hasMediaView","kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdRenderingSetting\/hasMediaView","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/s7CVarArgP":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/SH":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/SQ":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeBaseRenderingSetting":{"url":"\/documentation\/gfpsdk\/gfpnativebaserenderingsetting","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeBaseRenderingSetting","kind":"symbol","type":"topic","navigatorTitle":[{"text":"GFPNativeBaseRenderingSetting","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"GFPNativeBaseRenderingSetting","kind":"identifier"}],"abstract":[],"title":"GFPNativeBaseRenderingSetting"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdRenderingSetting/useInternalCache":{"type":"topic","abstract":[{"text":"네이티브 광고 성능을 위해 Internal Cache를 사용할 지 결정합니다.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"(기본값은 NO)"}],"title":"useInternalCache","role":"symbol","url":"\/documentation\/gfpsdk\/gfpnativeadrenderingsetting\/useinternalcache","navigatorTitle":[{"text":"useInternalCache","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdRenderingSetting\/useInternalCache","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"useInternalCache","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"GFPNativeAdRenderingSetting"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"value":[{"text":"GFPNativeAdRenderingSetting","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"GFPNativeAdRenderingSetting"}],"path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdRenderingSetting\/enableMediaBackgroundBlur","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdRenderingSetting\/hasMediaView","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdRenderingSetting\/useInternalCache"],"anchor":"Instance-Properties","generated":true,"title":"Instance Properties"}]},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeBaseRenderingSetting"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"}],"op":"replace"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPNativeAdRenderingSetting","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"GFPNativeBaseRenderingSetting","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeBaseRenderingSetting","preciseIdentifier":"c:objc(cs)GFPNativeBaseRenderingSetting","kind":"typeIdentifier"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"GFPNativeAdRenderingSetting","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdRenderingSetting\/title"},{"value":[{"text":"GFPNativeAdRenderingSetting","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdRenderingSetting\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdRenderingSetting\/navigatorTitle","value":[{"kind":"identifier","text":"GFPNativeAdRenderingSetting"}],"op":"replace"},{"value":"enableMediaBackgroundBlur","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdRenderingSetting~1enableMediaBackgroundBlur\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdRenderingSetting~1enableMediaBackgroundBlur\/fragments","value":[{"text":"enableMediaBackgroundBlur","kind":"identifier"}]},{"op":"replace","value":"hasMediaView","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdRenderingSetting~1hasMediaView\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdRenderingSetting~1hasMediaView\/fragments","op":"replace","value":[{"kind":"identifier","text":"hasMediaView"}]},{"value":"GFPNativeBaseRenderingSetting","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeBaseRenderingSetting\/title"},{"op":"replace","value":[{"kind":"identifier","text":"GFPNativeBaseRenderingSetting"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeBaseRenderingSetting\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeBaseRenderingSetting\/navigatorTitle","value":[{"kind":"identifier","text":"GFPNativeBaseRenderingSetting"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdRenderingSetting~1useInternalCache\/title","op":"replace","value":"useInternalCache"},{"op":"replace","value":[{"text":"useInternalCache","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdRenderingSetting~1useInternalCache\/fragments"}]}]}