{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPNativeAdapting"},{"text":" : ","kind":"text"},{"text":"GFPAdAdapting","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)GFPAdAdapting","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAdapting"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpnativeadapting"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpnativeadapting"]}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAdapting","doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject"],"title":"Inherits From","type":"inheritsFrom"}],"metadata":{"title":"GFPNativeAdapting","modules":[{"name":"GFPSDK"}],"navigatorTitle":[{"text":"GFPNativeAdapting","kind":"identifier"}],"externalID":"c:objc(pl)GFPNativeAdapting","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPNativeAdapting"}]},"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"topicSections":[{"generated":true,"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/delegate"],"title":"Instance Properties","anchor":"Instance-Properties"},{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/adChoicesData()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/adProviderNativeAd()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/adProviderType()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/adStyleOption()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/adStyleType()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/advertiser()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/advertiserOption()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/applyExtraViewLink(_:with:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/badge()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/body()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/bodyOption()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/c2sSubRenderType()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/callToAction()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/callToActionOption()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/clearResource()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/estimateHeight(with:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/existUserInterestDelegate(with:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/extraImage(with:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/extraImageAccessibility(with:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/extraLabelOption(with:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/extraText(with:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/hasIconImage()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/iconData()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/image()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/isInvalid()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/isRegistered()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/isReloadRequired()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/mediaData()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/nativeExtraInfo()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/notice()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/noticeOption()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/register(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/reloadMediaResource()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/socialContext()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/title()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/titleOption()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/unregisterView()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/updateMediaViewLayout()"],"generated":true,"title":"Instance Methods","anchor":"Instance-Methods"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting"},"kind":"symbol","sections":[],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdapting/noticeOption()":{"role":"symbol","title":"noticeOption()","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/noticeOption()","url":"\/documentation\/gfpsdk\/gfpnativeadapting\/noticeoption()","type":"topic","required":true,"navigatorTitle":[{"text":"noticeOption","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"noticeOption"},{"text":"() -> ","kind":"text"},{"text":"GFPLabelOption","preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPLabelOption","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdapting/extraImageAccessibility(with:)":{"abstract":[],"kind":"symbol","title":"extraImageAccessibility(with:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"extraImageAccessibility"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"url":"\/documentation\/gfpsdk\/gfpnativeadapting\/extraimageaccessibility(with:)","type":"topic","navigatorTitle":[{"text":"extraImageAccessibilityWith:","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/extraImageAccessibility(with:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdapting/clearResource()":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/clearResource()","role":"symbol","url":"\/documentation\/gfpsdk\/gfpnativeadapting\/clearresource()","navigatorTitle":[{"text":"clearResource","kind":"identifier"}],"title":"clearResource()","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"clearResource","kind":"identifier"},{"text":"()","kind":"text"}],"abstract":[],"kind":"symbol","required":true},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdapting/updateMediaViewLayout()":{"url":"\/documentation\/gfpsdk\/gfpnativeadapting\/updatemediaviewlayout()","title":"updateMediaViewLayout()","abstract":[],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"updateMediaViewLayout"},{"kind":"text","text":"()"}],"type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/updateMediaViewLayout()","navigatorTitle":[{"kind":"identifier","text":"updateMediaViewLayout"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdapting/notice()":{"required":true,"navigatorTitle":[{"text":"notice","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpnativeadapting\/notice()","title":"notice()","kind":"symbol","role":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/notice()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"notice","kind":"identifier"},{"kind":"text","text":"() -> "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdapting/bodyOption()":{"kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/bodyOption()","url":"\/documentation\/gfpsdk\/gfpnativeadapting\/bodyoption()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bodyOption"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"GFPLabelOption","preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPLabelOption"},{"text":"?","kind":"text"}],"title":"bodyOption()","role":"symbol","type":"topic","required":true,"navigatorTitle":[{"kind":"identifier","text":"bodyOption"}],"abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdapting/socialContext()":{"kind":"symbol","role":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"socialContext","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?","kind":"text"}],"url":"\/documentation\/gfpsdk\/gfpnativeadapting\/socialcontext()","title":"socialContext()","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/socialContext()","required":true,"navigatorTitle":[{"text":"socialContext","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdapting/extraImage(with:)":{"kind":"symbol","type":"topic","abstract":[],"url":"\/documentation\/gfpsdk\/gfpnativeadapting\/extraimage(with:)","required":true,"navigatorTitle":[{"text":"extraImageWith:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"extraImage","kind":"identifier"},{"kind":"text","text":"("},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":") -> ","kind":"text"},{"text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"title":"extraImage(with:)","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/extraImage(with:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdAdapting":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"GFPAdAdapting","kind":"identifier"}],"abstract":[],"url":"\/documentation\/gfpsdk\/gfpadadapting","kind":"symbol","role":"symbol","title":"GFPAdAdapting","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAdapting","type":"topic","navigatorTitle":[{"text":"GFPAdAdapting","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdapting/applyExtraViewLink(_:with:)":{"role":"symbol","title":"applyExtraViewLink(_:with:)","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/applyExtraViewLink(_:with:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"applyExtraViewLink"},{"kind":"text","text":"("},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"with","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UIView","preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier"},{"kind":"text","text":")"}],"abstract":[],"navigatorTitle":[{"text":"applyExtraViewLink:withView:","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpnativeadapting\/applyextraviewlink(_:with:)","type":"topic","required":true},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdapting/isReloadRequired()":{"url":"\/documentation\/gfpsdk\/gfpnativeadapting\/isreloadrequired()","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/isReloadRequired()","title":"isReloadRequired()","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"isReloadRequired","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isReloadRequired"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdapting/adStyleOption()":{"abstract":[],"title":"adStyleOption()","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"adStyleOption"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","text":"GFPAdStyleOption","preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPAdStyleOption"},{"kind":"text","text":"?"}],"url":"\/documentation\/gfpsdk\/gfpnativeadapting\/adstyleoption()","role":"symbol","required":true,"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/adStyleOption()","navigatorTitle":[{"kind":"identifier","text":"adStyleOption"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdapting/badge()":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/badge()","abstract":[],"title":"badge()","navigatorTitle":[{"text":"badge","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpnativeadapting\/badge()","role":"symbol","kind":"symbol","type":"topic","required":true,"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"badge"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}]},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)NSObject":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdapting/body()":{"abstract":[],"title":"body()","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"body"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"type":"topic","url":"\/documentation\/gfpsdk\/gfpnativeadapting\/body()","navigatorTitle":[{"text":"body","kind":"identifier"}],"required":true,"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/body()"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdapting/reloadMediaResource()":{"role":"symbol","title":"reloadMediaResource()","abstract":[],"url":"\/documentation\/gfpsdk\/gfpnativeadapting\/reloadmediaresource()","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"reloadMediaResource","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"reloadMediaResource","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/reloadMediaResource()","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdapting/isRegistered()":{"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isRegistered"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"kind":"symbol","abstract":[],"url":"\/documentation\/gfpsdk\/gfpnativeadapting\/isregistered()","required":true,"navigatorTitle":[{"text":"isRegistered","kind":"identifier"}],"title":"isRegistered()","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/isRegistered()","role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdapting/hasIconImage()":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/hasIconImage()","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"hasIconImage","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"required":true,"navigatorTitle":[{"kind":"identifier","text":"hasIconImage"}],"kind":"symbol","url":"\/documentation\/gfpsdk\/gfpnativeadapting\/hasiconimage()","role":"symbol","title":"hasIconImage()"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdapting/extraLabelOption(with:)":{"kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/extraLabelOption(with:)","url":"\/documentation\/gfpsdk\/gfpnativeadapting\/extralabeloption(with:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"extraLabelOption","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPLabelOption","text":"GFPLabelOption"},{"text":"?","kind":"text"}],"title":"extraLabelOption(with:)","role":"symbol","type":"topic","navigatorTitle":[{"text":"extraLabelOptionWith:","kind":"identifier"}],"abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdapting/unregisterView()":{"abstract":[],"title":"unregisterView()","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unregisterView"},{"kind":"text","text":"()"}],"type":"topic","url":"\/documentation\/gfpsdk\/gfpnativeadapting\/unregisterview()","navigatorTitle":[{"text":"unregisterView","kind":"identifier"}],"required":true,"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/unregisterView()"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdapting/title()":{"kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/title()","url":"\/documentation\/gfpsdk\/gfpnativeadapting\/title()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"title"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"title()","role":"symbol","type":"topic","required":true,"navigatorTitle":[{"text":"title","kind":"identifier"}],"abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdapting/adStyleType()":{"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"adStyleType","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","text":"GFPAdStyleType","preciseIdentifier":"c:@E@GFPAdStyleType"}],"url":"\/documentation\/gfpsdk\/gfpnativeadapting\/adstyletype()","navigatorTitle":[{"kind":"identifier","text":"adStyleType"}],"role":"symbol","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/adStyleType()","kind":"symbol","title":"adStyleType()"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdapting/advertiser()":{"title":"advertiser()","kind":"symbol","required":true,"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"advertiser","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"type":"topic","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/advertiser()","url":"\/documentation\/gfpsdk\/gfpnativeadapting\/advertiser()","role":"symbol","navigatorTitle":[{"text":"advertiser","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdapting/extraText(with:)":{"kind":"symbol","role":"symbol","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/extraText(with:)","url":"\/documentation\/gfpsdk\/gfpnativeadapting\/extratext(with:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"extraText","kind":"identifier"},{"kind":"text","text":"("},{"text":"with","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"title":"extraText(with:)","navigatorTitle":[{"kind":"identifier","text":"extraTextWith:"}],"type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdapting/mediaData()":{"required":true,"url":"\/documentation\/gfpsdk\/gfpnativeadapting\/mediadata()","title":"mediaData()","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/mediaData()","kind":"symbol","role":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mediaData"},{"kind":"text","text":"() -> "},{"text":"GFPMediaData","preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPMediaData","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"mediaData"}],"abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdapting/advertiserOption()":{"type":"topic","title":"advertiserOption()","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"advertiserOption"},{"text":"() -> ","kind":"text"},{"text":"GFPLabelOption","kind":"typeIdentifier","preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPLabelOption"},{"text":"?","kind":"text"}],"abstract":[],"url":"\/documentation\/gfpsdk\/gfpnativeadapting\/advertiseroption()","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"advertiserOption"}],"required":true,"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/advertiserOption()"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdapting/iconData()":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"iconData","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPIconData","text":"GFPIconData"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"iconData"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/iconData()","kind":"symbol","abstract":[],"type":"topic","role":"symbol","url":"\/documentation\/gfpsdk\/gfpnativeadapting\/icondata()","title":"iconData()"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdapting/estimateHeight(with:)":{"type":"topic","title":"estimateHeight(with:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"estimateHeight"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"}],"abstract":[],"url":"\/documentation\/gfpsdk\/gfpnativeadapting\/estimateheight(with:)","kind":"symbol","navigatorTitle":[{"text":"estimateHeightWith:","kind":"identifier"}],"required":true,"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/estimateHeight(with:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdapting/callToAction()":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"callToAction","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"abstract":[],"url":"\/documentation\/gfpsdk\/gfpnativeadapting\/calltoaction()","navigatorTitle":[{"text":"callToAction","kind":"identifier"}],"required":true,"kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/callToAction()","type":"topic","title":"callToAction()","role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdapting/isInvalid()":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/isInvalid()","navigatorTitle":[{"text":"isInvalid","kind":"identifier"}],"required":true,"kind":"symbol","url":"\/documentation\/gfpsdk\/gfpnativeadapting\/isinvalid()","type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isInvalid","kind":"identifier"},{"kind":"text","text":"() -> "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"title":"isInvalid()","abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdapting/register(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"register","kind":"identifier"},{"text":"(","kind":"text"},{"text":"GFPNativeBaseView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPNativeBaseView"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"registerView:"}],"url":"\/documentation\/gfpsdk\/gfpnativeadapting\/register(_:)","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/register(_:)","kind":"symbol","role":"symbol","required":true,"abstract":[],"type":"topic","title":"register(_:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdapting/existUserInterestDelegate(with:)":{"type":"topic","title":"existUserInterestDelegate(with:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"existUserInterestDelegate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"url":"\/documentation\/gfpsdk\/gfpnativeadapting\/existuserinterestdelegate(with:)","kind":"symbol","navigatorTitle":[{"text":"existUserInterestDelegateWith:","kind":"identifier"}],"required":true,"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/existUserInterestDelegate(with:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdapting/titleOption()":{"abstract":[],"type":"topic","title":"titleOption()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"titleOption","kind":"identifier"},{"kind":"text","text":"() -> "},{"text":"GFPLabelOption","kind":"typeIdentifier","preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPLabelOption"},{"text":"?","kind":"text"}],"url":"\/documentation\/gfpsdk\/gfpnativeadapting\/titleoption()","role":"symbol","required":true,"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/titleOption()","navigatorTitle":[{"kind":"identifier","text":"titleOption"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdapting/adChoicesData()":{"type":"topic","title":"adChoicesData()","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/adChoicesData()","url":"\/documentation\/gfpsdk\/gfpnativeadapting\/adchoicesdata()","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"adChoicesData"},{"kind":"text","text":"() -> "},{"text":"GFPAdChoicesData","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdChoicesData"},{"kind":"text","text":"?"}],"abstract":[],"navigatorTitle":[{"text":"adChoicesData","kind":"identifier"}],"role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdapting/delegate":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/delegate","navigatorTitle":[{"text":"delegate","kind":"identifier"}],"required":true,"kind":"symbol","url":"\/documentation\/gfpsdk\/gfpnativeadapting\/delegate","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"delegate","kind":"identifier"},{"text":": (any ","kind":"text"},{"kind":"typeIdentifier","text":"GFPNativeAdaptorDelegate","preciseIdentifier":"c:objc(pl)GFPNativeAdaptorDelegate"},{"text":")?","kind":"text"}],"title":"delegate","abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdapting/nativeExtraInfo()":{"role":"symbol","type":"topic","navigatorTitle":[{"text":"nativeExtraInfo","kind":"identifier"}],"abstract":[],"title":"nativeExtraInfo()","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"nativeExtraInfo","kind":"identifier"},{"text":"() -> [","kind":"text"},{"preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/nativeExtraInfo()","url":"\/documentation\/gfpsdk\/gfpnativeadapting\/nativeextrainfo()"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdapting/adProviderNativeAd()":{"kind":"symbol","required":true,"abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"adProviderNativeAd","kind":"identifier"},{"kind":"text","text":"() -> "},{"text":"Any","kind":"keyword"},{"kind":"text","text":"?"}],"title":"adProviderNativeAd()","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/adProviderNativeAd()","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"adProviderNativeAd"}],"url":"\/documentation\/gfpsdk\/gfpnativeadapting\/adprovidernativead()"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdapting/image()":{"title":"image()","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/image()","url":"\/documentation\/gfpsdk\/gfpnativeadapting\/image()","required":true,"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"image"},{"text":"() -> ","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":"?","kind":"text"}],"kind":"symbol","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"image"}],"type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdapting/c2sSubRenderType()":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/c2sSubRenderType()","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"c2sSubRenderType"}],"role":"symbol","url":"\/documentation\/gfpsdk\/gfpnativeadapting\/c2ssubrendertype()","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"c2sSubRenderType","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"title":"c2sSubRenderType()"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdapting":{"abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPNativeAdapting"}],"kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting","navigatorTitle":[{"kind":"identifier","text":"GFPNativeAdapting"}],"title":"GFPNativeAdapting","role":"symbol","url":"\/documentation\/gfpsdk\/gfpnativeadapting"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdapting/callToActionOption()":{"role":"symbol","abstract":[],"url":"\/documentation\/gfpsdk\/gfpnativeadapting\/calltoactionoption()","title":"callToActionOption()","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"callToActionOption","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"GFPLabelOption","preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPLabelOption","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"callToActionOption"}],"required":true,"kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/callToActionOption()"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdapting/adProviderType()":{"type":"topic","title":"adProviderType()","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"adProviderType","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPNativeAdProviderType","text":"GFPNativeAdProviderType"}],"abstract":[],"url":"\/documentation\/gfpsdk\/gfpnativeadapting\/adprovidertype()","kind":"symbol","navigatorTitle":[{"text":"adProviderType","kind":"identifier"}],"required":true,"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/adProviderType()"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdapting/dedup":{"role":"symbol","kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"dedup","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpnativeadapting\/dedup","navigatorTitle":[{"kind":"identifier","text":"dedup"}],"abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/dedup","title":"dedup","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Protocol","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"GFPNativeAdapting"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"path":"\/metadata\/fragments","value":[{"text":"GFPNativeAdapting","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"GFPNativeAdapting","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/delegate"],"anchor":"Instance-Properties"},{"generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/adChoicesData()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/adProviderNativeAd()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/adProviderType()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/adStyleOption()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/adStyleType()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/advertiser()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/advertiserOption()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/applyExtraViewLink(_:with:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/badge()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/body()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/bodyOption()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/c2sSubRenderType()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/callToAction()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/callToActionOption()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/clearResource()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/dedup","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/estimateHeight(with:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/existUserInterestDelegate(with:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/extraImage(with:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/extraImageAccessibility(with:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/extraLabelOption(with:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/extraText(with:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/hasIconImage()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/iconData()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/image()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/isInvalid()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/isRegistered()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/isReloadRequired()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/mediaData()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/nativeExtraInfo()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/notice()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/noticeOption()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/register(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/reloadMediaResource()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/socialContext()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/title()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/titleOption()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/unregisterView()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdapting\/updateMediaViewLayout()"],"title":"Instance Methods"}]},{"path":"\/relationshipsSections","op":"replace","value":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAdapting"]}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPNativeAdapting"},{"text":" <","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)GFPAdAdapting","text":"GFPAdAdapting","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAdapting"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"noticeOption","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdapting~1noticeOption()\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"noticeOption","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdapting~1noticeOption()\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdapting~1extraImageAccessibility(with:)\/title","value":"extraImageAccessibilityWith:","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdapting~1extraImageAccessibility(with:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"extraImageAccessibilityWith:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdapting~1clearResource()\/title","value":"clearResource"},{"value":[{"text":"- ","kind":"text"},{"text":"clearResource","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdapting~1clearResource()\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdapting~1updateMediaViewLayout()\/title","value":"updateMediaViewLayout"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdapting~1updateMediaViewLayout()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"updateMediaViewLayout"}]},{"value":"notice","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdapting~1notice()\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdapting~1notice()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"notice","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdapting~1bodyOption()\/title","op":"replace","value":"bodyOption"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"bodyOption","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdapting~1bodyOption()\/fragments"},{"value":"socialContext","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdapting~1socialContext()\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdapting~1socialContext()\/fragments","value":[{"kind":"text","text":"- "},{"text":"socialContext","kind":"identifier"}]},{"value":"extraImageWith:","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdapting~1extraImage(with:)\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdapting~1extraImage(with:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"extraImageWith:"}]},{"value":"GFPAdAdapting","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdapting\/title"},{"op":"replace","value":[{"text":"GFPAdAdapting","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdapting\/fragments"},{"value":[{"text":"GFPAdAdapting","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdapting\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdapting~1applyExtraViewLink(_:with:)\/title","value":"applyExtraViewLink:withView:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"applyExtraViewLink:withView:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdapting~1applyExtraViewLink(_:with:)\/fragments"},{"value":"isReloadRequired","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdapting~1isReloadRequired()\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isReloadRequired"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdapting~1isReloadRequired()\/fragments"},{"value":"adStyleOption","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdapting~1adStyleOption()\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdapting~1adStyleOption()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"adStyleOption"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdapting~1badge()\/title","value":"badge","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdapting~1badge()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"badge"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdapting~1body()\/title","value":"body","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdapting~1body()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"body","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"reloadMediaResource","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdapting~1reloadMediaResource()\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdapting~1reloadMediaResource()\/fragments","value":[{"kind":"text","text":"- "},{"text":"reloadMediaResource","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdapting~1isRegistered()\/title","value":"isRegistered"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdapting~1isRegistered()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"isRegistered","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdapting~1hasIconImage()\/title","value":"hasIconImage"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdapting~1hasIconImage()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"hasIconImage"}]},{"value":"extraLabelOptionWith:","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdapting~1extraLabelOption(with:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdapting~1extraLabelOption(with:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"extraLabelOptionWith:"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdapting~1unregisterView()\/title","value":"unregisterView","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"unregisterView"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdapting~1unregisterView()\/fragments"},{"value":"title","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdapting~1title()\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdapting~1title()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"title"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdapting~1adStyleType()\/title","op":"replace","value":"adStyleType"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdapting~1adStyleType()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"adStyleType"}],"op":"replace"},{"value":"advertiser","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdapting~1advertiser()\/title"},{"value":[{"kind":"text","text":"- "},{"text":"advertiser","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdapting~1advertiser()\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdapting~1extraText(with:)\/title","value":"extraTextWith:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"extraTextWith:"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdapting~1extraText(with:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdapting~1mediaData()\/title","op":"replace","value":"mediaData"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdapting~1mediaData()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"mediaData"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdapting~1advertiserOption()\/title","value":"advertiserOption"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"advertiserOption"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdapting~1advertiserOption()\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdapting~1iconData()\/title","value":"iconData","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdapting~1iconData()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"iconData"}]},{"value":"estimateHeightWith:","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdapting~1estimateHeight(with:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"estimateHeightWith:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdapting~1estimateHeight(with:)\/fragments"},{"op":"replace","value":"callToAction","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdapting~1callToAction()\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"callToAction"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdapting~1callToAction()\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdapting~1isInvalid()\/title","op":"replace","value":"isInvalid"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"isInvalid","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdapting~1isInvalid()\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdapting~1register(_:)\/title","op":"replace","value":"registerView:"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdapting~1register(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"registerView:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdapting~1existUserInterestDelegate(with:)\/title","value":"existUserInterestDelegateWith:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"existUserInterestDelegateWith:"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdapting~1existUserInterestDelegate(with:)\/fragments"},{"op":"replace","value":"titleOption","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdapting~1titleOption()\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdapting~1titleOption()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"titleOption"}],"op":"replace"},{"op":"replace","value":"adChoicesData","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdapting~1adChoicesData()\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdapting~1adChoicesData()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"adChoicesData","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdapting~1delegate\/title","value":"delegate","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdapting~1delegate\/fragments","value":[{"kind":"identifier","text":"delegate"}]},{"value":"nativeExtraInfo","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdapting~1nativeExtraInfo()\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"nativeExtraInfo"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdapting~1nativeExtraInfo()\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdapting~1adProviderNativeAd()\/title","op":"replace","value":"adProviderNativeAd"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdapting~1adProviderNativeAd()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"adProviderNativeAd"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdapting~1image()\/title","op":"replace","value":"image"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdapting~1image()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"image","kind":"identifier"}]},{"value":"c2sSubRenderType","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdapting~1c2sSubRenderType()\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"c2sSubRenderType"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdapting~1c2sSubRenderType()\/fragments"},{"value":"GFPNativeAdapting","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdapting\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdapting\/fragments","value":[{"text":"GFPNativeAdapting","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdapting\/navigatorTitle","value":[{"text":"GFPNativeAdapting","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdapting~1callToActionOption()\/title","value":"callToActionOption"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdapting~1callToActionOption()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"callToActionOption"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdapting~1adProviderType()\/title","value":"adProviderType"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdapting~1adProviderType()\/fragments","value":[{"kind":"text","text":"- "},{"text":"adProviderType","kind":"identifier"}]}]}]}