{"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"metadata":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPNonLinearAdView","kind":"identifier"}],"title":"GFPNonLinearAdView","modules":[{"name":"GFPSDK"}],"symbolKind":"class","roleHeading":"Class","externalID":"c:objc(cs)GFPNonLinearAdView","navigatorTitle":[{"kind":"identifier","text":"GFPNonLinearAdView"}]},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearAdView","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","topicSections":[{"generated":true,"anchor":"Initializers","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearAdView\/init(frame:remindAd:)"],"title":"Initializers"},{"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearAdView\/attribute","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearAdView\/containerType","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearAdView\/delegate","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearAdView\/isBanner","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearAdView\/isRemindLoaded","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearAdView\/landingUtil","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearAdView\/remindAd","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearAdView\/wasShown"],"generated":true},{"title":"Instance Methods","generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearAdView\/close(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearAdView\/reportTracking()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearAdView\/update(_:targetController:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearAdView\/updateRemindAd()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearAdView\/wasClicked(_:)"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPNonLinearAdView"}]}],"kind":"declarations"}],"relationshipsSections":[{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)UIView"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSCoding","doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)CALayerDelegate","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s7CVarArgP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s23CustomStringConvertibleP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s8SendableP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UIAccessibilityIdentification","doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UIAppearance","doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UIAppearanceContainer","doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UICoordinateSpace","doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UIDynamicItem","doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UIFocusEnvironment","doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UIFocusItem","doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UIFocusItemContainer","doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UILargeContentViewerItem","doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.navercorp.da.gfp.GFPSDK\/5UIKit23UITraitChangeObservableP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UITraitEnvironment","doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UIUserActivityRestoring"],"type":"conformsTo"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpnonlinearadview"]},{"paths":["\/documentation\/gfpsdk\/gfpnonlinearadview"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNonLinearAdView/wasClicked(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"wasClicked","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":")"}],"kind":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearAdView\/wasClicked(_:)","url":"\/documentation\/gfpsdk\/gfpnonlinearadview\/wasclicked(_:)","title":"wasClicked(_:)","role":"symbol","navigatorTitle":[{"text":"wasClicked:","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/SQ":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)NSCoding":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSCoding","type":"unresolvable","title":"Foundation.NSCoding"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNonLinearAdView/containerType":{"url":"\/documentation\/gfpsdk\/gfpnonlinearadview\/containertype","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearAdView\/containerType","kind":"symbol","abstract":[],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"containerType"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@GFPNonLinearContainerType","text":"GFPNonLinearContainerType","kind":"typeIdentifier"}],"title":"containerType","navigatorTitle":[{"kind":"identifier","text":"containerType"}],"type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)UICoordinateSpace":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UICoordinateSpace","type":"unresolvable","title":"UIKit.UICoordinateSpace"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNonLinearAdView/remindAd":{"navigatorTitle":[{"text":"remindAd","kind":"identifier"}],"abstract":[],"url":"\/documentation\/gfpsdk\/gfpnonlinearadview\/remindad","kind":"symbol","type":"topic","title":"remindAd","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"remindAd","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPRemindAd","text":"GFPRemindAd","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearAdView\/remindAd"},"doc://com.navercorp.da.gfp.GFPSDK/5UIKit23UITraitChangeObservableP":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/5UIKit23UITraitChangeObservableP","type":"unresolvable","title":"UIKit.UITraitChangeObservable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNonLinearAdView/landingUtil":{"navigatorTitle":[{"kind":"identifier","text":"landingUtil"}],"abstract":[],"kind":"symbol","title":"landingUtil","url":"\/documentation\/gfpsdk\/gfpnonlinearadview\/landingutil","role":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"landingUtil","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPClickLandingUtil","text":"GFPClickLandingUtil","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearAdView\/landingUtil"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UIUserActivityRestoring"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNonLinearAdView/isRemindLoaded":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isRemindLoaded","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"kind":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearAdView\/isRemindLoaded","url":"\/documentation\/gfpsdk\/gfpnonlinearadview\/isremindloaded","title":"isRemindLoaded","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"isRemindLoaded"}]},"doc://com.navercorp.da.gfp.GFPSDK/SH":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)UIFocusItem":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UIFocusItem","title":"UIKit.UIFocusItem","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/s8SendableP":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s8SendableP","title":"Swift.Sendable","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNonLinearAdView/init(frame:remindAd:)":{"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"frame"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"remindAd","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPRemindAd","kind":"typeIdentifier","text":"GFPRemindAd"},{"text":")","kind":"text"}],"kind":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearAdView\/init(frame:remindAd:)","url":"\/documentation\/gfpsdk\/gfpnonlinearadview\/init(frame:remindad:)","title":"init(frame:remindAd:)","role":"symbol","navigatorTitle":[{"text":"initWithFrame:remindAd:","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNonLinearAdView/attribute":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"attribute"},{"kind":"text","text":": "},{"text":"GFPTextAdViewAttribute","kind":"typeIdentifier","preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPTextAdViewAttribute"}],"kind":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearAdView\/attribute","url":"\/documentation\/gfpsdk\/gfpnonlinearadview\/attribute","title":"attribute","role":"symbol","navigatorTitle":[{"text":"attribute","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)UIDynamicItem":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UIDynamicItem","type":"unresolvable","title":"UIKit.UIDynamicItem"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNonLinearAdView/reportTracking()":{"abstract":[],"url":"\/documentation\/gfpsdk\/gfpnonlinearadview\/reporttracking()","role":"symbol","title":"reportTracking()","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearAdView\/reportTracking()","navigatorTitle":[{"kind":"identifier","text":"reportViewTracking"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"reportTracking"},{"text":"()","kind":"text"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)UIAccessibilityIdentification":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UIAccessibilityIdentification","type":"unresolvable","title":"UIKit.UIAccessibilityIdentification"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNonLinearAdView/isBanner":{"kind":"symbol","title":"isBanner","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearAdView\/isBanner","url":"\/documentation\/gfpsdk\/gfpnonlinearadview\/isbanner","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"isBanner","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"isBanner","kind":"identifier"}],"abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)UIResponderStandardEditActions":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UIResponderStandardEditActions","type":"unresolvable","title":"UIKit.UIResponderStandardEditActions"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNonLinearAdView/update(_:targetController:)":{"navigatorTitle":[{"text":"updateClickDelegate:targetController:","kind":"identifier"}],"abstract":[],"kind":"symbol","url":"\/documentation\/gfpsdk\/gfpnonlinearadview\/update(_:targetcontroller:)","title":"update(_:targetController:)","role":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"update"},{"kind":"text","text":"(any "},{"text":"GFPS2SAdClickDelegate","preciseIdentifier":"c:@M@GFPSDK@objc(pl)GFPS2SAdClickDelegate","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"targetController"},{"text":": ","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":"?)"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearAdView\/update(_:targetController:)"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)UIFocusItemContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UIFocusItemContainer"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNonLinearAdView":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearAdView","title":"GFPNonLinearAdView","type":"topic","url":"\/documentation\/gfpsdk\/gfpnonlinearadview","abstract":[],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPNonLinearAdView"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPNonLinearAdView","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNonLinearAdView/updateRemindAd()":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"updateRemindAd","kind":"identifier"},{"kind":"text","text":"()"}],"kind":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearAdView\/updateRemindAd()","url":"\/documentation\/gfpsdk\/gfpnonlinearadview\/updateremindad()","title":"updateRemindAd()","role":"symbol","navigatorTitle":[{"text":"updateRemindAd","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)UIPasteConfigurationSupporting":{"title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UIPasteConfigurationSupporting","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)UIFocusEnvironment":{"title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UIFocusEnvironment","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/objc(cs)UIView":{"title":"UIView","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)UIView","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)CALayerDelegate":{"title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)CALayerDelegate","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)UIAppearance":{"title":"UIKit.UIAppearance","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UIAppearance","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNonLinearAdView/delegate":{"url":"\/documentation\/gfpsdk\/gfpnonlinearadview\/delegate","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"kind":"text","text":": (any "},{"preciseIdentifier":"c:objc(pl)NonLinearViewDelegate","text":"NonLinearViewDelegate","kind":"typeIdentifier"},{"text":")?","kind":"text"}],"role":"symbol","abstract":[],"title":"delegate","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearAdView\/delegate","navigatorTitle":[{"text":"delegate","kind":"identifier"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)UIAppearanceContainer":{"title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UIAppearanceContainer","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)UILargeContentViewerItem":{"title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UILargeContentViewerItem","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNonLinearAdView/close(_:)":{"navigatorTitle":[{"text":"close:","kind":"identifier"}],"kind":"symbol","title":"close(_:)","url":"\/documentation\/gfpsdk\/gfpnonlinearadview\/close(_:)","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearAdView\/close(_:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"close","kind":"identifier"},{"kind":"text","text":"("},{"text":"Any","kind":"keyword"},{"kind":"text","text":")"}],"type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNonLinearAdView/wasShown":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearAdView\/wasShown","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"wasShown","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"kind":"identifier","text":"wasShown"}],"type":"topic","role":"symbol","kind":"symbol","title":"wasShown","url":"\/documentation\/gfpsdk\/gfpnonlinearadview\/wasshown","abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/s7CVarArgP":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)UIActivityItemsConfigurationProviding":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UIActivityItemsConfigurationProviding","title":"UIKit.UIActivityItemsConfigurationProviding","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)UITraitEnvironment":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UITraitEnvironment","title":"UIKit.UITraitEnvironment","type":"unresolvable"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"GFPNonLinearAdView"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"GFPNonLinearAdView","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"GFPNonLinearAdView","kind":"identifier"}]},{"path":"\/topicSections","value":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearAdView\/attribute","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearAdView\/containerType","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearAdView\/delegate","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearAdView\/isBanner","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearAdView\/isRemindLoaded","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearAdView\/landingUtil","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearAdView\/remindAd","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearAdView\/wasShown"],"title":"Instance Properties","generated":true},{"generated":true,"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearAdView\/close(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearAdView\/init(frame:remindAd:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearAdView\/reportTracking()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearAdView\/update(_:targetController:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearAdView\/updateRemindAd()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearAdView\/wasClicked(_:)"],"title":"Instance Methods","anchor":"Instance-Methods"}],"op":"replace"},{"value":[{"type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)UIView"],"title":"Inherits From"}],"path":"\/relationshipsSections","op":"replace"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPNonLinearAdView"},{"text":" : ","kind":"text"},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"wasClicked:","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearAdView~1wasClicked(_:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearAdView~1wasClicked(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"wasClicked:"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearAdView~1containerType\/title","value":"containerType","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearAdView~1containerType\/fragments","op":"replace","value":[{"text":"containerType","kind":"identifier"}]},{"value":"remindAd","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearAdView~1remindAd\/title"},{"value":[{"text":"remindAd","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearAdView~1remindAd\/fragments"},{"value":"landingUtil","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearAdView~1landingUtil\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearAdView~1landingUtil\/fragments","value":[{"kind":"identifier","text":"landingUtil"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearAdView~1isRemindLoaded\/title","op":"replace","value":"isRemindLoaded"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearAdView~1isRemindLoaded\/fragments","value":[{"text":"isRemindLoaded","kind":"identifier"}],"op":"replace"},{"value":"initWithFrame:remindAd:","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearAdView~1init(frame:remindAd:)\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearAdView~1init(frame:remindAd:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFrame:remindAd:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearAdView~1attribute\/title","value":"attribute"},{"value":[{"text":"attribute","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearAdView~1attribute\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearAdView~1reportTracking()\/title","op":"replace","value":"reportViewTracking"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"reportViewTracking"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearAdView~1reportTracking()\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearAdView~1isBanner\/title","value":"isBanner","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"isBanner"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearAdView~1isBanner\/fragments"},{"value":"updateClickDelegate:targetController:","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearAdView~1update(_:targetController:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"updateClickDelegate:targetController:"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearAdView~1update(_:targetController:)\/fragments"},{"op":"replace","value":"GFPNonLinearAdView","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearAdView\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearAdView\/fragments","op":"replace","value":[{"kind":"identifier","text":"GFPNonLinearAdView"}]},{"value":[{"kind":"identifier","text":"GFPNonLinearAdView"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearAdView\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearAdView~1updateRemindAd()\/title","value":"updateRemindAd"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateRemindAd"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearAdView~1updateRemindAd()\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearAdView~1delegate\/title","value":"delegate"},{"value":[{"text":"delegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearAdView~1delegate\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearAdView~1close(_:)\/title","op":"replace","value":"close:"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearAdView~1close(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"close:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearAdView~1wasShown\/title","op":"replace","value":"wasShown"},{"value":[{"text":"wasShown","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearAdView~1wasShown\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}