{"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"topicSections":[{"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdDelegate\/nativeSimpleAd(_:didChangeMediaViewSizeWith:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdDelegate\/nativeSimpleAd(_:didChangeRichAdSizeWith:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdDelegate\/nativeSimpleAd(_:didFailWithError:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdDelegate\/nativeSimpleAdDidDismissDefault(inAppBrowser:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdDelegate\/nativeSimpleAdDidPresentDefault(inAppBrowser:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdDelegate\/nativeSimpleAdWasCanceledMute(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdDelegate\/nativeSimpleAdWasClicked(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdDelegate\/nativeSimpleAdWasMuted(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdDelegate\/nativeSimpleAdWasSeen(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdDelegate\/nativeSimpleRichAdExtendComplete(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdDelegate\/nativeSimpleRichAdExtendStart(_:to:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdDelegate\/nativeSimpleRichAdShrinkComplete(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdDelegate\/nativeSimpleRichAdShrinkStart(_:to:)"],"generated":true}],"metadata":{"symbolKind":"protocol","navigatorTitle":[{"kind":"identifier","text":"GFPNativeSimpleAdDelegate"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"GFPNativeSimpleAdDelegate","kind":"identifier"}],"title":"GFPNativeSimpleAdDelegate","externalID":"c:objc(pl)GFPNativeSimpleAdDelegate","modules":[{"name":"GFPSDK"}],"role":"symbol","roleHeading":"Protocol"},"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject"],"kind":"relationships"}],"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdDelegate","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPNativeSimpleAdDelegate"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(pl)NSObject","text":"NSObjectProtocol","kind":"typeIdentifier"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpnativesimpleaddelegate"]},{"paths":["\/documentation\/gfpsdk\/gfpnativesimpleaddelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeSimpleAdDelegate/nativeSimpleAdWasClicked(_:)":{"navigatorTitle":[{"kind":"identifier","text":"nativeSimpleAdWasClicked:"}],"title":"nativeSimpleAdWasClicked(_:)","abstract":[{"type":"text","text":"광고 클릭 시 호출됩니다."}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdDelegate\/nativeSimpleAdWasClicked(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"nativeSimpleAdWasClicked","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"GFPNativeSimpleAd","preciseIdentifier":"c:objc(cs)GFPNativeSimpleAd"},{"kind":"text","text":")"}],"url":"\/documentation\/gfpsdk\/gfpnativesimpleaddelegate\/nativesimpleadwasclicked(_:)","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeSimpleAdDelegate/nativeSimpleAdWasMuted(_:)":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdDelegate\/nativeSimpleAdWasMuted(_:)","url":"\/documentation\/gfpsdk\/gfpnativesimpleaddelegate\/nativesimpleadwasmuted(_:)","title":"nativeSimpleAdWasMuted(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"nativeSimpleAdWasMuted","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GFPNativeSimpleAd","preciseIdentifier":"c:objc(cs)GFPNativeSimpleAd"},{"kind":"text","text":")"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"nativeSimpleAdWasMuted:"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"광고 뮤트 시 호출됩니다."}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeSimpleAdDelegate/nativeSimpleAdDidDismissDefault(inAppBrowser:)":{"navigatorTitle":[{"kind":"identifier","text":"nativeSimpleAdDidDismissDefaultInAppBrowser:"}],"title":"nativeSimpleAdDidDismissDefault(inAppBrowser:)","abstract":[{"type":"text","text":"Default In App Browser 사용 시, 클릭이 이루어져서 SFSafariViewController가 정상적으로 Dismiss 시 호출됩니다."}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdDelegate\/nativeSimpleAdDidDismissDefault(inAppBrowser:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"nativeSimpleAdDidDismissDefault"},{"kind":"text","text":"("},{"text":"inAppBrowser","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"GFPNativeSimpleAd","preciseIdentifier":"c:objc(cs)GFPNativeSimpleAd"},{"text":")","kind":"text"}],"url":"\/documentation\/gfpsdk\/gfpnativesimpleaddelegate\/nativesimpleaddiddismissdefault(inappbrowser:)","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeSimpleAdDelegate/nativeSimpleRichAdExtendComplete(_:)":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdDelegate\/nativeSimpleRichAdExtendComplete(_:)","url":"\/documentation\/gfpsdk\/gfpnativesimpleaddelegate\/nativesimplerichadextendcomplete(_:)","title":"nativeSimpleRichAdExtendComplete(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"nativeSimpleRichAdExtendComplete","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)GFPNativeSimpleAd","kind":"typeIdentifier","text":"GFPNativeSimpleAd"},{"kind":"text","text":")"}],"role":"symbol","navigatorTitle":[{"text":"nativeSimpleRichAdExtendComplete:","kind":"identifier"}],"kind":"symbol","required":true,"abstract":[{"text":"Rich  Extend 광고에서 미디어뷰 사이즈 확장 완료 시 호출됩니다.","type":"text"}],"type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeSimpleAdDelegate/nativeSimpleRichAdExtendStart(_:to:)":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdDelegate\/nativeSimpleRichAdExtendStart(_:to:)","url":"\/documentation\/gfpsdk\/gfpnativesimpleaddelegate\/nativesimplerichadextendstart(_:to:)","title":"nativeSimpleRichAdExtendStart(_:to:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"nativeSimpleRichAdExtendStart","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GFPNativeSimpleAd","preciseIdentifier":"c:objc(cs)GFPNativeSimpleAd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":")"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"nativeSimpleRichAdExtendStart:toSize:"}],"kind":"symbol","required":true,"type":"topic","abstract":[{"text":"Rich  Extend 광고에서 미디어뷰 사이즈 확장 시작 시 호출됩니다.","type":"text"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeSimpleAdDelegate/nativeSimpleAd(_:didChangeMediaViewSizeWith:)":{"kind":"symbol","type":"topic","url":"\/documentation\/gfpsdk\/gfpnativesimpleaddelegate\/nativesimplead(_:didchangemediaviewsizewith:)","abstract":[{"text":"미디어뷰 사이즈 변경 시 호출됩니다.","type":"text"}],"navigatorTitle":[{"text":"nativeSimpleAd:didChangeMediaViewSizeWith:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"nativeSimpleAd"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GFPNativeSimpleAd","preciseIdentifier":"c:objc(cs)GFPNativeSimpleAd"},{"text":", ","kind":"text"},{"text":"didChangeMediaViewSizeWith","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier","text":"CGSize"},{"text":")","kind":"text"}],"title":"nativeSimpleAd(_:didChangeMediaViewSizeWith:)","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdDelegate\/nativeSimpleAd(_:didChangeMediaViewSizeWith:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeSimpleAdDelegate/nativeSimpleAdWasCanceledMute(_:)":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdDelegate\/nativeSimpleAdWasCanceledMute(_:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"nativeSimpleAdWasCanceledMute:"}],"title":"nativeSimpleAdWasCanceledMute(_:)","url":"\/documentation\/gfpsdk\/gfpnativesimpleaddelegate\/nativesimpleadwascanceledmute(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"nativeSimpleAdWasCanceledMute","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPNativeSimpleAd","text":"GFPNativeSimpleAd"},{"text":")","kind":"text"}],"type":"topic","abstract":[{"type":"text","text":"광고 뮤트 취소 시 호출됩니다."}],"role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeSimpleAdDelegate/nativeSimpleAd(_:didFailWithError:)":{"title":"nativeSimpleAd(_:didFailWithError:)","abstract":[{"text":"에러 발생 시 호출됩니다.","type":"text"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdDelegate\/nativeSimpleAd(_:didFailWithError:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"nativeSimpleAd","kind":"identifier"},{"kind":"text","text":"("},{"text":"GFPNativeSimpleAd","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPNativeSimpleAd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFailWithError"},{"text":": ","kind":"text"},{"text":"GFPError","preciseIdentifier":"c:@M@NaverAdsServices@objc(cs)GFPError","kind":"typeIdentifier"},{"kind":"text","text":")"}],"role":"symbol","type":"topic","url":"\/documentation\/gfpsdk\/gfpnativesimpleaddelegate\/nativesimplead(_:didfailwitherror:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"nativeSimpleAd:didFailWithError:"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeSimpleAdDelegate/nativeSimpleAd(_:didChangeRichAdSizeWith:)":{"title":"nativeSimpleAd(_:didChangeRichAdSizeWith:)","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdDelegate\/nativeSimpleAd(_:didChangeRichAdSizeWith:)","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Rich  Extend 광고에서 미디어뷰 사이즈 변경 시마다 호출됩니다."}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"nativeSimpleAd"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"GFPNativeSimpleAd","preciseIdentifier":"c:objc(cs)GFPNativeSimpleAd"},{"kind":"text","text":", "},{"text":"didChangeRichAdSizeWith","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGSize","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"nativeSimpleAd:didChangeRichAdSizeWith:","kind":"identifier"}],"required":true,"type":"topic","url":"\/documentation\/gfpsdk\/gfpnativesimpleaddelegate\/nativesimplead(_:didchangerichadsizewith:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeSimpleAdDelegate/nativeSimpleAdDidPresentDefault(inAppBrowser:)":{"navigatorTitle":[{"text":"nativeSimpleAdDidPresentDefaultInAppBrowser:","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"nativeSimpleAdDidPresentDefault(inAppBrowser:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"nativeSimpleAdDidPresentDefault","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"inAppBrowser"},{"text":": ","kind":"text"},{"text":"GFPNativeSimpleAd","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPNativeSimpleAd"},{"text":")","kind":"text"}],"type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdDelegate\/nativeSimpleAdDidPresentDefault(inAppBrowser:)","abstract":[{"type":"text","text":"Default In App Browser 사용 시, 클릭이 이루어져서 SFSafariViewController가 정상적으로 Present 시 호출됩니다."}],"url":"\/documentation\/gfpsdk\/gfpnativesimpleaddelegate\/nativesimpleaddidpresentdefault(inappbrowser:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeSimpleAdDelegate/nativeSimpleRichAdShrinkComplete(_:)":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"nativeSimpleRichAdShrinkComplete:"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"nativeSimpleRichAdShrinkComplete","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPNativeSimpleAd","text":"GFPNativeSimpleAd"},{"text":")","kind":"text"}],"title":"nativeSimpleRichAdShrinkComplete(_:)","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdDelegate\/nativeSimpleRichAdShrinkComplete(_:)","url":"\/documentation\/gfpsdk\/gfpnativesimpleaddelegate\/nativesimplerichadshrinkcomplete(_:)","abstract":[{"text":"Rich  Extend 광고에서 미디어뷰 사이즈 축소 완료 시 호출됩니다.","type":"text"}],"kind":"symbol","required":true},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)NSObject":{"title":"NSObject","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeSimpleAdDelegate/nativeSimpleRichAdShrinkStart(_:to:)":{"url":"\/documentation\/gfpsdk\/gfpnativesimpleaddelegate\/nativesimplerichadshrinkstart(_:to:)","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdDelegate\/nativeSimpleRichAdShrinkStart(_:to:)","navigatorTitle":[{"text":"nativeSimpleRichAdShrinkStart:toSize:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"nativeSimpleRichAdShrinkStart","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPNativeSimpleAd","text":"GFPNativeSimpleAd"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"to"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGSize","text":"CGSize","kind":"typeIdentifier"},{"kind":"text","text":")"}],"kind":"symbol","abstract":[{"text":"Rich  Extend 광고에서 미디어뷰 사이즈 축소 시작 시 호출됩니다.","type":"text"}],"type":"topic","required":true,"title":"nativeSimpleRichAdShrinkStart(_:to:)","role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeSimpleAdDelegate":{"kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdDelegate","role":"symbol","navigatorTitle":[{"text":"GFPNativeSimpleAdDelegate","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpnativesimpleaddelegate","title":"GFPNativeSimpleAdDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPNativeSimpleAdDelegate"}],"type":"topic","abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeSimpleAdDelegate/nativeSimpleAdWasSeen(_:)":{"title":"nativeSimpleAdWasSeen(_:)","abstract":[{"text":"광고가 사용자에게 보여진 경우 호출됩니다.","type":"text"}],"kind":"symbol","required":true,"navigatorTitle":[{"text":"nativeSimpleAdWasSeen:","kind":"identifier"}],"type":"topic","url":"\/documentation\/gfpsdk\/gfpnativesimpleaddelegate\/nativesimpleadwasseen(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"nativeSimpleAdWasSeen","kind":"identifier"},{"text":"(","kind":"text"},{"text":"GFPNativeSimpleAd","preciseIdentifier":"c:objc(cs)GFPNativeSimpleAd","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdDelegate\/nativeSimpleAdWasSeen(_:)","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Protocol","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"GFPNativeSimpleAdDelegate","path":"\/metadata\/title"},{"value":"protocol","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GFPNativeSimpleAdDelegate"}],"op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"GFPNativeSimpleAdDelegate","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdDelegate\/nativeSimpleAd(_:didChangeMediaViewSizeWith:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdDelegate\/nativeSimpleAd(_:didChangeRichAdSizeWith:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdDelegate\/nativeSimpleAd(_:didFailWithError:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdDelegate\/nativeSimpleAdDidDismissDefault(inAppBrowser:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdDelegate\/nativeSimpleAdDidPresentDefault(inAppBrowser:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdDelegate\/nativeSimpleAdWasCanceledMute(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdDelegate\/nativeSimpleAdWasClicked(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdDelegate\/nativeSimpleAdWasMuted(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdDelegate\/nativeSimpleAdWasSeen(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdDelegate\/nativeSimpleRichAdExtendComplete(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdDelegate\/nativeSimpleRichAdExtendStart(_:to:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdDelegate\/nativeSimpleRichAdShrinkComplete(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdDelegate\/nativeSimpleRichAdShrinkStart(_:to:)"]}]},{"path":"\/relationshipsSections","value":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject"]}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@protocol"},{"text":" ","kind":"text"},{"text":"GFPNativeSimpleAdDelegate","kind":"identifier"},{"text":" <","kind":"text"},{"preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier","text":"NSObject"},{"kind":"text","text":">"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdDelegate~1nativeSimpleAdWasClicked(_:)\/title","value":"nativeSimpleAdWasClicked:","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdDelegate~1nativeSimpleAdWasClicked(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"nativeSimpleAdWasClicked:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdDelegate~1nativeSimpleAdWasMuted(_:)\/title","value":"nativeSimpleAdWasMuted:"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdDelegate~1nativeSimpleAdWasMuted(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"nativeSimpleAdWasMuted:","kind":"identifier"}]},{"value":"nativeSimpleAdDidDismissDefaultInAppBrowser:","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdDelegate~1nativeSimpleAdDidDismissDefault(inAppBrowser:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"nativeSimpleAdDidDismissDefaultInAppBrowser:"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdDelegate~1nativeSimpleAdDidDismissDefault(inAppBrowser:)\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdDelegate~1nativeSimpleRichAdExtendComplete(_:)\/title","op":"replace","value":"nativeSimpleRichAdExtendComplete:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"nativeSimpleRichAdExtendComplete:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdDelegate~1nativeSimpleRichAdExtendComplete(_:)\/fragments"},{"op":"replace","value":"nativeSimpleRichAdExtendStart:toSize:","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdDelegate~1nativeSimpleRichAdExtendStart(_:to:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdDelegate~1nativeSimpleRichAdExtendStart(_:to:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"nativeSimpleRichAdExtendStart:toSize:"}]},{"value":"nativeSimpleAd:didChangeMediaViewSizeWith:","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdDelegate~1nativeSimpleAd(_:didChangeMediaViewSizeWith:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdDelegate~1nativeSimpleAd(_:didChangeMediaViewSizeWith:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"nativeSimpleAd:didChangeMediaViewSizeWith:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdDelegate~1nativeSimpleAdWasCanceledMute(_:)\/title","value":"nativeSimpleAdWasCanceledMute:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"nativeSimpleAdWasCanceledMute:"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdDelegate~1nativeSimpleAdWasCanceledMute(_:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdDelegate~1nativeSimpleAd(_:didFailWithError:)\/title","value":"nativeSimpleAd:didFailWithError:"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdDelegate~1nativeSimpleAd(_:didFailWithError:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"nativeSimpleAd:didFailWithError:"}]},{"value":"nativeSimpleAd:didChangeRichAdSizeWith:","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdDelegate~1nativeSimpleAd(_:didChangeRichAdSizeWith:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdDelegate~1nativeSimpleAd(_:didChangeRichAdSizeWith:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"nativeSimpleAd:didChangeRichAdSizeWith:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdDelegate~1nativeSimpleAdDidPresentDefault(inAppBrowser:)\/title","value":"nativeSimpleAdDidPresentDefaultInAppBrowser:"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdDelegate~1nativeSimpleAdDidPresentDefault(inAppBrowser:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"nativeSimpleAdDidPresentDefaultInAppBrowser:"}]},{"value":"nativeSimpleRichAdShrinkComplete:","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdDelegate~1nativeSimpleRichAdShrinkComplete(_:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"nativeSimpleRichAdShrinkComplete:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdDelegate~1nativeSimpleRichAdShrinkComplete(_:)\/fragments"},{"value":"nativeSimpleRichAdShrinkStart:toSize:","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdDelegate~1nativeSimpleRichAdShrinkStart(_:to:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdDelegate~1nativeSimpleRichAdShrinkStart(_:to:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"nativeSimpleRichAdShrinkStart:toSize:","kind":"identifier"}]},{"op":"replace","value":"GFPNativeSimpleAdDelegate","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdDelegate\/title"},{"value":[{"kind":"identifier","text":"GFPNativeSimpleAdDelegate"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdDelegate\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdDelegate\/navigatorTitle","op":"replace","value":[{"text":"GFPNativeSimpleAdDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdDelegate~1nativeSimpleAdWasSeen(_:)\/title","value":"nativeSimpleAdWasSeen:"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdDelegate~1nativeSimpleAdWasSeen(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"nativeSimpleAdWasSeen:","kind":"identifier"}],"op":"replace"}]}]}