{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpnativecontextpresentable"]},{"paths":["\/documentation\/gfpsdk\/gfpnativecontextpresentable"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"metadata":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPNativeContextPresentable"}],"roleHeading":"Protocol","modules":[{"name":"GFPSDK"}],"role":"symbol","symbolKind":"protocol","navigatorTitle":[{"kind":"identifier","text":"GFPNativeContextPresentable"}],"title":"GFPNativeContextPresentable","externalID":"c:objc(pl)GFPNativeContextPresentable"},"relationshipsSections":[{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"},{"kind":"relationships","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPCombinedContext","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeContext"],"title":"Conforming Types","type":"conformingTypes"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeContextPresentable"},"topicSections":[{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeContextPresentable\/renderingSetting","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeContextPresentable\/rootViewController","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeContextPresentable\/simpleAdRenderingSetting","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeContextPresentable\/videoOptions"],"anchor":"Instance-Properties","generated":true,"title":"Instance Properties"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"GFPNativeContextPresentable","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier"}],"platforms":["iOS"]}]}],"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeContext":{"role":"symbol","title":"GFPNativeContext","url":"\/documentation\/gfpsdk\/gfpnativecontext","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeContext","navigatorTitle":[{"text":"GFPNativeContext","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"GFPNativeContext","kind":"identifier"}],"abstract":[],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeContextPresentable":{"role":"symbol","title":"GFPNativeContextPresentable","url":"\/documentation\/gfpsdk\/gfpnativecontextpresentable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeContextPresentable","navigatorTitle":[{"text":"GFPNativeContextPresentable","kind":"identifier"}],"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPNativeContextPresentable","kind":"identifier"}],"abstract":[],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPCombinedContext":{"role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPCombinedContext","type":"topic","abstract":[],"url":"\/documentation\/gfpsdk\/gfpcombinedcontext","title":"GFPCombinedContext","navigatorTitle":[{"text":"GFPCombinedContext","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPCombinedContext"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeContextPresentable/rootViewController":{"type":"topic","url":"\/documentation\/gfpsdk\/gfpnativecontextpresentable\/rootviewcontroller","required":true,"abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"rootViewController","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeContextPresentable\/rootViewController","title":"rootViewController","navigatorTitle":[{"kind":"identifier","text":"rootViewController"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeContextPresentable/renderingSetting":{"url":"\/documentation\/gfpsdk\/gfpnativecontextpresentable\/renderingsetting","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"renderingSetting","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPNativeAdRenderingSetting","text":"GFPNativeAdRenderingSetting","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeContextPresentable\/renderingSetting","kind":"symbol","navigatorTitle":[{"text":"renderingSetting","kind":"identifier"}],"required":true,"role":"symbol","title":"renderingSetting","type":"topic","abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeContextPresentable/simpleAdRenderingSetting":{"type":"topic","url":"\/documentation\/gfpsdk\/gfpnativecontextpresentable\/simpleadrenderingsetting","required":true,"abstract":[],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"simpleAdRenderingSetting","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"GFPNativeSimpleAdRenderingSetting","preciseIdentifier":"c:objc(cs)GFPNativeSimpleAdRenderingSetting"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeContextPresentable\/simpleAdRenderingSetting","title":"simpleAdRenderingSetting","navigatorTitle":[{"text":"simpleAdRenderingSetting","kind":"identifier"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeContextPresentable/videoOptions":{"url":"\/documentation\/gfpsdk\/gfpnativecontextpresentable\/videooptions","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"videoOptions","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)GFPVideoOptions","text":"GFPVideoOptions","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeContextPresentable\/videoOptions","kind":"symbol","navigatorTitle":[{"text":"videoOptions","kind":"identifier"}],"required":true,"role":"symbol","title":"videoOptions","type":"topic","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Protocol","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"GFPNativeContextPresentable","op":"replace"},{"path":"\/metadata\/symbolKind","value":"protocol","op":"replace"},{"value":[{"kind":"identifier","text":"GFPNativeContextPresentable"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"GFPNativeContextPresentable","kind":"identifier"}]},{"op":"replace","value":[{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeContextPresentable\/renderingSetting","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeContextPresentable\/rootViewController","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeContextPresentable\/simpleAdRenderingSetting","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeContextPresentable\/videoOptions"]}],"path":"\/topicSections"},{"value":[{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"},{"title":"Conforming Types","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeContext"],"type":"conformingTypes","kind":"relationships"}],"path":"\/relationshipsSections","op":"replace"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPNativeContextPresentable"},{"text":" <","kind":"text"},{"preciseIdentifier":"c:objc(pl)NSObject","text":"NSObject","kind":"typeIdentifier"},{"text":">","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeContext\/title","op":"replace","value":"GFPNativeContext"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeContext\/fragments","op":"replace","value":[{"kind":"identifier","text":"GFPNativeContext"}]},{"value":[{"kind":"identifier","text":"GFPNativeContext"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeContext\/navigatorTitle"},{"value":"GFPNativeContextPresentable","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeContextPresentable\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeContextPresentable\/fragments","value":[{"text":"GFPNativeContextPresentable","kind":"identifier"}]},{"value":[{"text":"GFPNativeContextPresentable","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeContextPresentable\/navigatorTitle","op":"replace"},{"value":"GFPCombinedContext","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPCombinedContext\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPCombinedContext\/fragments","op":"replace","value":[{"kind":"identifier","text":"GFPCombinedContext"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPCombinedContext\/navigatorTitle","value":[{"text":"GFPCombinedContext","kind":"identifier"}]},{"value":"rootViewController","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeContextPresentable~1rootViewController\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeContextPresentable~1rootViewController\/fragments","op":"replace","value":[{"kind":"identifier","text":"rootViewController"}]},{"value":"renderingSetting","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeContextPresentable~1renderingSetting\/title","op":"replace"},{"value":[{"kind":"identifier","text":"renderingSetting"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeContextPresentable~1renderingSetting\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeContextPresentable~1simpleAdRenderingSetting\/title","value":"simpleAdRenderingSetting"},{"op":"replace","value":[{"text":"simpleAdRenderingSetting","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeContextPresentable~1simpleAdRenderingSetting\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeContextPresentable~1videoOptions\/title","value":"videoOptions","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeContextPresentable~1videoOptions\/fragments","op":"replace","value":[{"kind":"identifier","text":"videoOptions"}]}]}]}