{"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdView","interfaceLanguage":"swift"},"metadata":{"role":"symbol","title":"GFPNativeAdView","roleHeading":"Class","navigatorTitle":[{"kind":"identifier","text":"GFPNativeAdView"}],"symbolKind":"class","externalID":"c:objc(cs)GFPNativeAdView","modules":[{"name":"GFPSDK"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPNativeAdView","kind":"identifier"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeBaseView"],"title":"Inherits From"},{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSCoding","doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)CALayerDelegate","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s7CVarArgP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s23CustomStringConvertibleP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s8SendableP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UIAccessibilityIdentification","doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UIAppearance","doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UIAppearanceContainer","doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UICoordinateSpace","doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UIDynamicItem","doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UIFocusEnvironment","doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UIFocusItem","doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UIFocusItemContainer","doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UILargeContentViewerItem","doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.navercorp.da.gfp.GFPSDK\/5UIKit23UITraitChangeObservableP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UITraitEnvironment","doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UIUserActivityRestoring"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpnativeadview"]},{"paths":["\/documentation\/gfpsdk\/gfpnativeadview"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"topicSections":[{"anchor":"Instance-Properties","generated":true,"title":"Instance Properties","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdView\/adBadgeLabel","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdView\/adChoicesView","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdView\/advertiserLabel","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdView\/bodyLabel","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdView\/callToActionLabel","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdView\/iconView","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdView\/nativeAd","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdView\/noticeLabel","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdView\/serviceAdBadgeView","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdView\/socialContextLabel","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdView\/titleLabel"]},{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdView\/extraLabel(with:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdView\/getAllExtraLabel()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdView\/labels()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdView\/setExtraLabelWith(_:label:)"],"anchor":"Instance-Methods","title":"Instance Methods","generated":true}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPNativeAdView"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)UIPasteConfigurationSupporting":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UIPasteConfigurationSupporting","type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting"},"doc://com.navercorp.da.gfp.GFPSDK/SQ":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeBaseView":{"kind":"symbol","type":"topic","abstract":[],"url":"\/documentation\/gfpsdk\/gfpnativebaseview","navigatorTitle":[{"text":"GFPNativeBaseView","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPNativeBaseView"}],"title":"GFPNativeBaseView","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeBaseView"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)UIAppearanceContainer":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UIAppearanceContainer","type":"unresolvable","title":"UIKit.UIAppearanceContainer"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)UIAppearance":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UIAppearance","type":"unresolvable","title":"UIKit.UIAppearance"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdView/getAllExtraLabel()":{"url":"\/documentation\/gfpsdk\/gfpnativeadview\/getallextralabel()","role":"symbol","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdView\/getAllExtraLabel()","navigatorTitle":[{"kind":"identifier","text":"getAllExtraLabel"}],"kind":"symbol","abstract":[],"title":"getAllExtraLabel()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"getAllExtraLabel","kind":"identifier"},{"kind":"text","text":"() -> ["},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]"}]},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)UITraitEnvironment":{"title":"UIKit.UITraitEnvironment","type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UITraitEnvironment"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdView/setExtraLabelWith(_:label:)":{"url":"\/documentation\/gfpsdk\/gfpnativeadview\/setextralabelwith(_:label:)","role":"symbol","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdView\/setExtraLabelWith(_:label:)","navigatorTitle":[{"kind":"identifier","text":"setExtraLabelWith:label:"}],"kind":"symbol","abstract":[],"title":"setExtraLabelWith(_:label:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setExtraLabelWith"},{"text":"(","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"label"},{"text":": ","kind":"text"},{"text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)UIPopoverPresentationControllerSourceItem":{"title":"UIKit.UIPopoverPresentationControllerSourceItem","type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://com.navercorp.da.gfp.GFPSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s28CustomDebugStringConvertibleP"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)UILargeContentViewerItem":{"title":"UIKit.UILargeContentViewerItem","type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UILargeContentViewerItem"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdView/nativeAd":{"url":"\/documentation\/gfpsdk\/gfpnativeadview\/nativead","role":"symbol","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdView\/nativeAd","navigatorTitle":[{"text":"nativeAd","kind":"identifier"}],"abstract":[],"kind":"symbol","title":"nativeAd","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nativeAd","kind":"identifier"},{"kind":"text","text":": "},{"text":"GFPNativeAd","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPNativeAd"},{"text":"?","kind":"text"}]},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)UIFocusItem":{"type":"unresolvable","title":"UIKit.UIFocusItem","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UIFocusItem"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdView/adBadgeLabel":{"navigatorTitle":[{"kind":"identifier","text":"adBadgeLabel"}],"type":"topic","title":"adBadgeLabel","kind":"symbol","url":"\/documentation\/gfpsdk\/gfpnativeadview\/adbadgelabel","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdView\/adBadgeLabel","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"adBadgeLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"?"}],"role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)UICoordinateSpace":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UICoordinateSpace","title":"UIKit.UICoordinateSpace","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)NSObject":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)UIResponderStandardEditActions":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UIResponderStandardEditActions","title":"UIKit.UIResponderStandardEditActions","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdView/callToActionLabel":{"navigatorTitle":[{"text":"callToActionLabel","kind":"identifier"}],"type":"topic","title":"callToActionLabel","kind":"symbol","url":"\/documentation\/gfpsdk\/gfpnativeadview\/calltoactionlabel","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdView\/callToActionLabel","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"callToActionLabel","kind":"identifier"},{"kind":"text","text":": "},{"text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)UIActivityItemsConfigurationProviding":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UIActivityItemsConfigurationProviding","type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)UIDynamicItem":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UIDynamicItem","type":"unresolvable","title":"UIKit.UIDynamicItem"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdView/socialContextLabel":{"abstract":[],"url":"\/documentation\/gfpsdk\/gfpnativeadview\/socialcontextlabel","role":"symbol","title":"socialContextLabel","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdView\/socialContextLabel","navigatorTitle":[{"text":"socialContextLabel","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"socialContextLabel","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"text":"?","kind":"text"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/5UIKit23UITraitChangeObservableP":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/5UIKit23UITraitChangeObservableP","title":"UIKit.UITraitChangeObservable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdView/adChoicesView":{"abstract":[],"url":"\/documentation\/gfpsdk\/gfpnativeadview\/adchoicesview","role":"symbol","title":"adChoicesView","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdView\/adChoicesView","navigatorTitle":[{"kind":"identifier","text":"adChoicesView"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"adChoicesView","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIView","text":"UIView","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdView/iconView":{"navigatorTitle":[{"kind":"identifier","text":"iconView"}],"type":"topic","title":"iconView","kind":"symbol","url":"\/documentation\/gfpsdk\/gfpnativeadview\/iconview","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdView\/iconView","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"iconView","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIImageView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImageView"},{"text":"?","kind":"text"}],"role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)UIFocusItemContainer":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UIFocusItemContainer","title":"UIKit.UIFocusItemContainer"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)NSCoding":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSCoding","type":"unresolvable","title":"Foundation.NSCoding"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdView/bodyLabel":{"abstract":[],"url":"\/documentation\/gfpsdk\/gfpnativeadview\/bodylabel","role":"symbol","title":"bodyLabel","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdView\/bodyLabel","navigatorTitle":[{"kind":"identifier","text":"bodyLabel"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bodyLabel","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UILabel","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"?"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdView/extraLabel(with:)":{"url":"\/documentation\/gfpsdk\/gfpnativeadview\/extralabel(with:)","title":"extraLabel(with:)","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdView\/extraLabel(with:)","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"extraLabelWith:","kind":"identifier"}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"extraLabel","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UILabel","text":"UILabel"},{"kind":"text","text":"?"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdView/titleLabel":{"title":"titleLabel","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdView\/titleLabel","role":"symbol","kind":"symbol","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"titleLabel"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UILabel","text":"UILabel","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"titleLabel"}],"type":"topic","url":"\/documentation\/gfpsdk\/gfpnativeadview\/titlelabel"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdView/serviceAdBadgeView":{"navigatorTitle":[{"kind":"identifier","text":"serviceAdBadgeView"}],"type":"topic","title":"serviceAdBadgeView","kind":"symbol","url":"\/documentation\/gfpsdk\/gfpnativeadview\/serviceadbadgeview","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdView\/serviceAdBadgeView","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"serviceAdBadgeView","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIView","preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdView/noticeLabel":{"abstract":[],"url":"\/documentation\/gfpsdk\/gfpnativeadview\/noticelabel","role":"symbol","title":"noticeLabel","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdView\/noticeLabel","navigatorTitle":[{"kind":"identifier","text":"noticeLabel"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"noticeLabel","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UILabel","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"?"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdView/labels()":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdView\/labels()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"labels"},{"text":"() -> [","kind":"text"},{"text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"labels"}],"type":"topic","role":"symbol","url":"\/documentation\/gfpsdk\/gfpnativeadview\/labels()","title":"labels()","kind":"symbol","abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)UIFocusEnvironment":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UIFocusEnvironment","title":"UIKit.UIFocusEnvironment","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdView/advertiserLabel":{"navigatorTitle":[{"kind":"identifier","text":"advertiserLabel"}],"type":"topic","title":"advertiserLabel","kind":"symbol","url":"\/documentation\/gfpsdk\/gfpnativeadview\/advertiserlabel","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdView\/advertiserLabel","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"advertiserLabel","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/s7CVarArgP":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.navercorp.da.gfp.GFPSDK/s8SendableP":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s8SendableP","type":"unresolvable","title":"Swift.Sendable"},"doc://com.navercorp.da.gfp.GFPSDK/SH":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdView":{"navigatorTitle":[{"text":"GFPNativeAdView","kind":"identifier"}],"title":"GFPNativeAdView","url":"\/documentation\/gfpsdk\/gfpnativeadview","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdView","role":"symbol","type":"topic","kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"GFPNativeAdView","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)CALayerDelegate":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)CALayerDelegate","type":"unresolvable","title":"QuartzCore.CALayerDelegate"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)UIUserActivityRestoring":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UIUserActivityRestoring","type":"unresolvable","title":"UIKit.UIUserActivityRestoring"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)UIAccessibilityIdentification":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UIAccessibilityIdentification","type":"unresolvable","title":"UIKit.UIAccessibilityIdentification"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"value":"GFPNativeAdView","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"GFPNativeAdView"}]},{"value":[{"kind":"identifier","text":"GFPNativeAdView"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdView\/adBadgeLabel","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdView\/adChoicesView","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdView\/advertiserLabel","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdView\/bodyLabel","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdView\/callToActionLabel","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdView\/iconView","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdView\/nativeAd","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdView\/noticeLabel","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdView\/serviceAdBadgeView","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdView\/socialContextLabel","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdView\/titleLabel"],"generated":true,"anchor":"Instance-Properties"},{"generated":true,"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdView\/extraLabel(with:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdView\/getAllExtraLabel()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdView\/labels()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdView\/setExtraLabelWith(_:label:)"]}],"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"replace","value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeBaseView"],"type":"inheritsFrom"}]},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPNativeAdView","kind":"identifier"},{"text":" : ","kind":"text"},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeBaseView","kind":"typeIdentifier","text":"GFPNativeBaseView","preciseIdentifier":"c:objc(cs)GFPNativeBaseView"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeBaseView\/title","op":"replace","value":"GFPNativeBaseView"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeBaseView\/fragments","value":[{"kind":"identifier","text":"GFPNativeBaseView"}]},{"value":[{"kind":"identifier","text":"GFPNativeBaseView"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeBaseView\/navigatorTitle"},{"op":"replace","value":"getAllExtraLabel","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdView~1getAllExtraLabel()\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"getAllExtraLabel","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdView~1getAllExtraLabel()\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdView~1setExtraLabelWith(_:label:)\/title","value":"setExtraLabelWith:label:"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdView~1setExtraLabelWith(_:label:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"setExtraLabelWith:label:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdView~1nativeAd\/title","value":"nativeAd","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdView~1nativeAd\/fragments","value":[{"text":"nativeAd","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdView~1adBadgeLabel\/title","op":"replace","value":"adBadgeLabel"},{"value":[{"text":"adBadgeLabel","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdView~1adBadgeLabel\/fragments","op":"replace"},{"op":"replace","value":"callToActionLabel","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdView~1callToActionLabel\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdView~1callToActionLabel\/fragments","value":[{"text":"callToActionLabel","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdView~1socialContextLabel\/title","value":"socialContextLabel","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdView~1socialContextLabel\/fragments","value":[{"kind":"identifier","text":"socialContextLabel"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdView~1adChoicesView\/title","value":"adChoicesView","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdView~1adChoicesView\/fragments","value":[{"text":"adChoicesView","kind":"identifier"}]},{"value":"iconView","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdView~1iconView\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdView~1iconView\/fragments","op":"replace","value":[{"text":"iconView","kind":"identifier"}]},{"op":"replace","value":"bodyLabel","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdView~1bodyLabel\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdView~1bodyLabel\/fragments","value":[{"kind":"identifier","text":"bodyLabel"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdView~1extraLabel(with:)\/title","op":"replace","value":"extraLabelWith:"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdView~1extraLabel(with:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"extraLabelWith:"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdView~1titleLabel\/title","value":"titleLabel","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdView~1titleLabel\/fragments","value":[{"kind":"identifier","text":"titleLabel"}]},{"value":"serviceAdBadgeView","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdView~1serviceAdBadgeView\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdView~1serviceAdBadgeView\/fragments","value":[{"kind":"identifier","text":"serviceAdBadgeView"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdView~1noticeLabel\/title","value":"noticeLabel","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdView~1noticeLabel\/fragments","op":"replace","value":[{"text":"noticeLabel","kind":"identifier"}]},{"value":"labels","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdView~1labels()\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdView~1labels()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"labels"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdView~1advertiserLabel\/title","value":"advertiserLabel","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdView~1advertiserLabel\/fragments","value":[{"kind":"identifier","text":"advertiserLabel"}],"op":"replace"},{"value":"GFPNativeAdView","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdView\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdView\/fragments","value":[{"text":"GFPNativeAdView","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdView\/navigatorTitle","value":[{"text":"GFPNativeAdView","kind":"identifier"}],"op":"replace"}]}]}