{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpnativeadstyleoptionpresentable"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpnativeadstyleoptionpresentable"]}],"metadata":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPNativeAdStyleOptionPresentable","kind":"identifier"}],"roleHeading":"Protocol","symbolKind":"protocol","role":"symbol","modules":[{"name":"GFPSDK"}],"navigatorTitle":[{"kind":"identifier","text":"GFPNativeAdStyleOptionPresentable"}],"title":"GFPNativeAdStyleOptionPresentable","externalID":"c:objc(pl)GFPNativeAdStyleOptionPresentable"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdStyleOptionPresentable","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"topicSections":[{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdStyleOptionPresentable\/adStyleOption(with:)"],"anchor":"Instance-Methods","generated":true,"title":"Instance Methods"}],"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdInfoExtStylePresentable","doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject"],"kind":"relationships"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"GFPNativeAdStyleOptionPresentable","kind":"identifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdInfoExtStylePresentable","preciseIdentifier":"c:objc(pl)GFPNativeAdInfoExtStylePresentable","text":"GFPNativeAdInfoExtStylePresentable"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdInfoExtStylePresentable":{"navigatorTitle":[{"kind":"identifier","text":"GFPNativeAdInfoExtStylePresentable"}],"title":"GFPNativeAdInfoExtStylePresentable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdInfoExtStylePresentable","type":"topic","url":"\/documentation\/gfpsdk\/gfpnativeadinfoextstylepresentable","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPNativeAdInfoExtStylePresentable","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdStyleOptionPresentable/adStyleOption(with:)":{"required":true,"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"adStyleOption"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"GFPAdStyleOption","preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPAdStyleOption"}],"navigatorTitle":[{"text":"adStyleOptionWith:","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpnativeadstyleoptionpresentable\/adstyleoption(with:)","abstract":[],"kind":"symbol","role":"symbol","title":"adStyleOption(with:)","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdStyleOptionPresentable\/adStyleOption(with:)"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdStyleOptionPresentable":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPNativeAdStyleOptionPresentable","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"GFPNativeAdStyleOptionPresentable","kind":"identifier"}],"title":"GFPNativeAdStyleOptionPresentable","abstract":[],"role":"symbol","url":"\/documentation\/gfpsdk\/gfpnativeadstyleoptionpresentable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdStyleOptionPresentable","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Protocol","op":"replace"},{"value":"GFPNativeAdStyleOptionPresentable","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"protocol","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"GFPNativeAdStyleOptionPresentable"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"GFPNativeAdStyleOptionPresentable","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"generated":true,"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdStyleOptionPresentable\/adStyleOption(with:)"],"title":"Instance Methods","anchor":"Instance-Methods"}]},{"op":"replace","value":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdInfoExtStylePresentable"],"title":"Inherits From","kind":"relationships"}],"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"text":"GFPNativeAdStyleOptionPresentable","kind":"identifier"},{"text":" <","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)GFPNativeAdInfoExtStylePresentable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdInfoExtStylePresentable","text":"GFPNativeAdInfoExtStylePresentable"},{"text":">","kind":"text"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdInfoExtStylePresentable\/title","value":"GFPNativeAdInfoExtStylePresentable","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdInfoExtStylePresentable\/fragments","value":[{"kind":"identifier","text":"GFPNativeAdInfoExtStylePresentable"}]},{"value":[{"text":"GFPNativeAdInfoExtStylePresentable","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdInfoExtStylePresentable\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdStyleOptionPresentable~1adStyleOption(with:)\/title","value":"adStyleOptionWith:"},{"value":[{"kind":"text","text":"- "},{"text":"adStyleOptionWith:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdStyleOptionPresentable~1adStyleOption(with:)\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdStyleOptionPresentable\/title","op":"replace","value":"GFPNativeAdStyleOptionPresentable"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdStyleOptionPresentable\/fragments","value":[{"text":"GFPNativeAdStyleOptionPresentable","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdStyleOptionPresentable\/navigatorTitle","value":[{"kind":"identifier","text":"GFPNativeAdStyleOptionPresentable"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}