{"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships"},{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s7CVarArgP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s23CustomStringConvertibleP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"topicSections":[{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeMediaExtensionInfo\/init(dictionary:link:)"],"title":"Initializers","generated":true,"anchor":"Initializers"},{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeMediaExtensionInfo\/alternativeText","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeMediaExtensionInfo\/badges","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeMediaExtensionInfo\/isExistRichAssets","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeMediaExtensionInfo\/richInfo"],"anchor":"Instance-Properties"},{"anchor":"Instance-Methods","generated":true,"title":"Instance Methods","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeMediaExtensionInfo\/removeRichInfo()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeMediaExtensionInfo\/updateAccessibilityText(with:)"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpnativemediaextensioninfo"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpnativemediaextensioninfo"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"GFPNativeMediaExtensionInfo","kind":"identifier"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeMediaExtensionInfo"},"kind":"symbol","metadata":{"externalID":"c:objc(cs)GFPNativeMediaExtensionInfo","navigatorTitle":[{"kind":"identifier","text":"GFPNativeMediaExtensionInfo"}],"title":"GFPNativeMediaExtensionInfo","role":"symbol","symbolKind":"class","roleHeading":"Class","modules":[{"name":"GFPSDK"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPNativeMediaExtensionInfo"}]},"sections":[],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeMediaExtensionInfo/alternativeText":{"type":"topic","title":"alternativeText","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"alternativeText"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"url":"\/documentation\/gfpsdk\/gfpnativemediaextensioninfo\/alternativetext","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"alternativeText"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeMediaExtensionInfo\/alternativeText"},"doc://com.navercorp.da.gfp.GFPSDK/SH":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeMediaExtensionInfo/badges":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeMediaExtensionInfo\/badges","role":"symbol","url":"\/documentation\/gfpsdk\/gfpnativemediaextensioninfo\/badges","title":"badges","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"badges"}],"abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"badges","kind":"identifier"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"text":"GFPNativeMediaBadgeInfo","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPNativeMediaBadgeInfo"},{"kind":"text","text":"]"}],"type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)NSObject":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/objc(cs)NSObject":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeMediaExtensionInfo/isExistRichAssets":{"url":"\/documentation\/gfpsdk\/gfpnativemediaextensioninfo\/isexistrichassets","title":"isExistRichAssets","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeMediaExtensionInfo\/isExistRichAssets","abstract":[],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"isExistRichAssets","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isExistRichAssets"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}]},"doc://com.navercorp.da.gfp.GFPSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeMediaExtensionInfo/richInfo":{"navigatorTitle":[{"kind":"identifier","text":"richInfo"}],"type":"topic","title":"richInfo","kind":"symbol","url":"\/documentation\/gfpsdk\/gfpnativemediaextensioninfo\/richinfo","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeMediaExtensionInfo\/richInfo","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"richInfo"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPNativeRichInfo","kind":"typeIdentifier","text":"GFPNativeRichInfo"},{"text":"?","kind":"text"}],"role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeMediaExtensionInfo":{"url":"\/documentation\/gfpsdk\/gfpnativemediaextensioninfo","abstract":[],"title":"GFPNativeMediaExtensionInfo","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeMediaExtensionInfo","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPNativeMediaExtensionInfo"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPNativeMediaExtensionInfo","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/s7CVarArgP":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeMediaExtensionInfo/removeRichInfo()":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeMediaExtensionInfo\/removeRichInfo()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"removeRichInfo","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"removeRichInfo"}],"type":"topic","role":"symbol","url":"\/documentation\/gfpsdk\/gfpnativemediaextensioninfo\/removerichinfo()","title":"removeRichInfo()","kind":"symbol","abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeMediaExtensionInfo/init(dictionary:link:)":{"role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeMediaExtensionInfo\/init(dictionary:link:)","type":"topic","abstract":[],"url":"\/documentation\/gfpsdk\/gfpnativemediaextensioninfo\/init(dictionary:link:)","title":"init(dictionary:link:)","navigatorTitle":[{"text":"initWithDictionary:link:","kind":"identifier"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"dictionary","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier","text":"AnyHashable"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"]?, ","kind":"text"},{"kind":"externalParam","text":"link"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPNativeLinkInfo","text":"GFPNativeLinkInfo"},{"kind":"text","text":")"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/SQ":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeMediaExtensionInfo/updateAccessibilityText(with:)":{"type":"topic","url":"\/documentation\/gfpsdk\/gfpnativemediaextensioninfo\/updateaccessibilitytext(with:)","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"updateAccessibilityText","kind":"identifier"},{"kind":"text","text":"("},{"text":"with","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeMediaExtensionInfo\/updateAccessibilityText(with:)","title":"updateAccessibilityText(with:)","navigatorTitle":[{"text":"updateAccessibilityTextWith:","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"GFPNativeMediaExtensionInfo","op":"replace"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GFPNativeMediaExtensionInfo"}],"op":"replace"},{"value":[{"text":"GFPNativeMediaExtensionInfo","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"anchor":"Instance-Properties","generated":true,"title":"Instance Properties","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeMediaExtensionInfo\/alternativeText","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeMediaExtensionInfo\/badges","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeMediaExtensionInfo\/isExistRichAssets","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeMediaExtensionInfo\/richInfo"]},{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeMediaExtensionInfo\/init(dictionary:link:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeMediaExtensionInfo\/removeRichInfo()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeMediaExtensionInfo\/updateAccessibilityText(with:)"],"anchor":"Instance-Methods"}],"path":"\/topicSections"},{"op":"replace","value":[{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"}],"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPNativeMediaExtensionInfo"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeMediaExtensionInfo~1alternativeText\/title","op":"replace","value":"alternativeText"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeMediaExtensionInfo~1alternativeText\/fragments","value":[{"kind":"identifier","text":"alternativeText"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeMediaExtensionInfo~1badges\/title","value":"badges","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeMediaExtensionInfo~1badges\/fragments","value":[{"text":"badges","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"isExistRichAssets","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeMediaExtensionInfo~1isExistRichAssets\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeMediaExtensionInfo~1isExistRichAssets\/fragments","value":[{"text":"isExistRichAssets","kind":"identifier"}]},{"op":"replace","value":"richInfo","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeMediaExtensionInfo~1richInfo\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeMediaExtensionInfo~1richInfo\/fragments","value":[{"kind":"identifier","text":"richInfo"}],"op":"replace"},{"op":"replace","value":"GFPNativeMediaExtensionInfo","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeMediaExtensionInfo\/title"},{"value":[{"kind":"identifier","text":"GFPNativeMediaExtensionInfo"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeMediaExtensionInfo\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeMediaExtensionInfo\/navigatorTitle","value":[{"text":"GFPNativeMediaExtensionInfo","kind":"identifier"}]},{"op":"replace","value":"removeRichInfo","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeMediaExtensionInfo~1removeRichInfo()\/title"},{"value":[{"kind":"text","text":"- "},{"text":"removeRichInfo","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeMediaExtensionInfo~1removeRichInfo()\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeMediaExtensionInfo~1init(dictionary:link:)\/title","value":"initWithDictionary:link:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDictionary:link:"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeMediaExtensionInfo~1init(dictionary:link:)\/fragments"},{"value":"updateAccessibilityTextWith:","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeMediaExtensionInfo~1updateAccessibilityText(with:)\/title","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"updateAccessibilityTextWith:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeMediaExtensionInfo~1updateAccessibilityText(with:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}