{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPNativeVideoEventDelegate"},{"text":" : ","kind":"text"},{"text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpnativevideoeventdelegate"]},{"paths":["\/documentation\/gfpsdk\/gfpnativevideoeventdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeVideoEventDelegate\/nativeAd(_:richVideoDidPlayWith:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeVideoEventDelegate\/nativeAd(_:richVideoDidStopWith:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeVideoEventDelegate\/nativeAd(_:richVideoMuteChanged:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeVideoEventDelegate\/nativeAd(_:richVideoWillPlayWith:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeVideoEventDelegate\/nativeAd(_:richVideoWillStopWith:)"],"title":"Instance Methods"}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeVideoEventDelegate"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"kind":"symbol","metadata":{"roleHeading":"Protocol","role":"symbol","navigatorTitle":[{"text":"GFPNativeVideoEventDelegate","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPNativeVideoEventDelegate","kind":"identifier"}],"modules":[{"name":"GFPSDK"}],"symbolKind":"protocol","externalID":"c:objc(pl)GFPNativeVideoEventDelegate","title":"GFPNativeVideoEventDelegate"},"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject"],"type":"inheritsFrom","kind":"relationships"}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)NSObject":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","type":"unresolvable","title":"NSObject"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeVideoEventDelegate/nativeAd(_:richVideoWillStopWith:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"nativeAd","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"},{"kind":"text","text":", "},{"text":"richVideoWillStopWith","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"title":"nativeAd(_:richVideoWillStopWith:)","navigatorTitle":[{"text":"nativeAd:richVideoWillStopWith:","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpnativevideoeventdelegate\/nativead(_:richvideowillstopwith:)","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeVideoEventDelegate\/nativeAd(_:richVideoWillStopWith:)","role":"symbol","type":"topic","kind":"symbol","abstract":[{"text":"Rich광고 비디오 정지 시 호출됩니다. player pause 직전에 호출됩니다.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"재생 중 메모리 해제 시에는 호출되지 않습니다."}],"required":true},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeVideoEventDelegate/nativeAd(_:richVideoWillPlayWith:)":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"nativeAd:richVideoWillPlayWith:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nativeAd","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"richVideoWillPlayWith"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeVideoEventDelegate\/nativeAd(_:richVideoWillPlayWith:)","type":"topic","abstract":[{"type":"text","text":"Rich광고 비디오 재생 시 호출됩니다. player start 직전에 호출됩니다."}],"url":"\/documentation\/gfpsdk\/gfpnativevideoeventdelegate\/nativead(_:richvideowillplaywith:)","kind":"symbol","title":"nativeAd(_:richVideoWillPlayWith:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeVideoEventDelegate/nativeAd(_:richVideoMuteChanged:)":{"url":"\/documentation\/gfpsdk\/gfpnativevideoeventdelegate\/nativead(_:richvideomutechanged:)","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeVideoEventDelegate\/nativeAd(_:richVideoMuteChanged:)","type":"topic","required":true,"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"nativeAd"},{"kind":"text","text":"("},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"richVideoMuteChanged"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"abstract":[{"text":"Rich광고 비디오 플레이어에 mute 셋팅 시 호출됩니다.","type":"text"}],"navigatorTitle":[{"text":"nativeAd:richVideoMuteChanged:","kind":"identifier"}],"kind":"symbol","title":"nativeAd(_:richVideoMuteChanged:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeVideoEventDelegate/nativeAd(_:richVideoDidStopWith:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"nativeAd"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"},{"text":", ","kind":"text"},{"text":"richVideoDidStopWith","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":")"}],"title":"nativeAd(_:richVideoDidStopWith:)","navigatorTitle":[{"text":"nativeAd:richVideoDidStopWith:","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpnativevideoeventdelegate\/nativead(_:richvideodidstopwith:)","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeVideoEventDelegate\/nativeAd(_:richVideoDidStopWith:)","role":"symbol","type":"topic","kind":"symbol","abstract":[{"text":"Rich광고 비디오 정지 시 호출됩니다. player pause 후 스테이터스 변경 시, 메모리 해제 시 호출됩니다.","type":"text"}],"required":true},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeVideoEventDelegate":{"role":"symbol","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeVideoEventDelegate","type":"topic","kind":"symbol","url":"\/documentation\/gfpsdk\/gfpnativevideoeventdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPNativeVideoEventDelegate","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"GFPNativeVideoEventDelegate"}],"title":"GFPNativeVideoEventDelegate"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeVideoEventDelegate/nativeAd(_:richVideoDidPlayWith:)":{"kind":"symbol","title":"nativeAd(_:richVideoDidPlayWith:)","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeVideoEventDelegate\/nativeAd(_:richVideoDidPlayWith:)","url":"\/documentation\/gfpsdk\/gfpnativevideoeventdelegate\/nativead(_:richvideodidplaywith:)","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"nativeAd"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"},{"text":", ","kind":"text"},{"text":"richVideoDidPlayWith","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"nativeAd:richVideoDidPlayWith:","kind":"identifier"}],"abstract":[{"type":"text","text":"Rich광고 비디오 재생 시 호출됩니다. player start 후 스테이터스 변경 시 호출됩니다."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Protocol","path":"\/metadata\/roleHeading","op":"replace"},{"value":"GFPNativeVideoEventDelegate","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"protocol","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"GFPNativeVideoEventDelegate","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"GFPNativeVideoEventDelegate","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"generated":true,"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeVideoEventDelegate\/nativeAd(_:richVideoDidPlayWith:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeVideoEventDelegate\/nativeAd(_:richVideoDidStopWith:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeVideoEventDelegate\/nativeAd(_:richVideoMuteChanged:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeVideoEventDelegate\/nativeAd(_:richVideoWillPlayWith:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeVideoEventDelegate\/nativeAd(_:richVideoWillStopWith:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"title":"Inherits From","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject"],"type":"inheritsFrom","kind":"relationships"}]},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPNativeVideoEventDelegate"},{"text":" <","kind":"text"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(pl)NSObject"},{"text":">","kind":"text"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeVideoEventDelegate~1nativeAd(_:richVideoWillStopWith:)\/title","op":"replace","value":"nativeAd:richVideoWillStopWith:"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeVideoEventDelegate~1nativeAd(_:richVideoWillStopWith:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"nativeAd:richVideoWillStopWith:"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeVideoEventDelegate~1nativeAd(_:richVideoWillPlayWith:)\/title","value":"nativeAd:richVideoWillPlayWith:","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeVideoEventDelegate~1nativeAd(_:richVideoWillPlayWith:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"nativeAd:richVideoWillPlayWith:","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"nativeAd:richVideoMuteChanged:","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeVideoEventDelegate~1nativeAd(_:richVideoMuteChanged:)\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeVideoEventDelegate~1nativeAd(_:richVideoMuteChanged:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"nativeAd:richVideoMuteChanged:","kind":"identifier"}],"op":"replace"},{"value":"nativeAd:richVideoDidStopWith:","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeVideoEventDelegate~1nativeAd(_:richVideoDidStopWith:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"nativeAd:richVideoDidStopWith:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeVideoEventDelegate~1nativeAd(_:richVideoDidStopWith:)\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeVideoEventDelegate\/title","value":"GFPNativeVideoEventDelegate","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeVideoEventDelegate\/fragments","value":[{"kind":"identifier","text":"GFPNativeVideoEventDelegate"}]},{"value":[{"text":"GFPNativeVideoEventDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeVideoEventDelegate\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeVideoEventDelegate~1nativeAd(_:richVideoDidPlayWith:)\/title","op":"replace","value":"nativeAd:richVideoDidPlayWith:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"nativeAd:richVideoDidPlayWith:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeVideoEventDelegate~1nativeAd(_:richVideoDidPlayWith:)\/fragments"}]}]}