{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"topicSections":[{"title":"Instance Properties","generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdRenderingSetting\/isImageSizePreferred","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdRenderingSetting\/maxExtendingHeight","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdRenderingSetting\/renderers","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdRenderingSetting\/videoEventDelegate"]},{"generated":true,"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdRenderingSetting\/addRenderer(with:rendererView:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdRenderingSetting\/removeRenderer(with:)"]}],"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPNativeSimpleAdRenderingSetting"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"modules":[{"name":"GFPSDK"}],"role":"symbol","navigatorTitle":[{"text":"GFPNativeSimpleAdRenderingSetting","kind":"identifier"}],"externalID":"c:objc(cs)GFPNativeSimpleAdRenderingSetting","roleHeading":"Class","symbolKind":"class","title":"GFPNativeSimpleAdRenderingSetting","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPNativeSimpleAdRenderingSetting"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpnativesimpleadrenderingsetting"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpnativesimpleadrenderingsetting"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdRenderingSetting","interfaceLanguage":"swift"},"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeBaseRenderingSetting"]},{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s7CVarArgP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s23CustomStringConvertibleP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH"],"kind":"relationships"}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeSimpleAdRenderingSetting/videoEventDelegate":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"videoEventDelegate"},{"kind":"text","text":": (any "},{"kind":"typeIdentifier","text":"GFPNativeVideoEventDelegate","preciseIdentifier":"c:objc(pl)GFPNativeVideoEventDelegate"},{"kind":"text","text":")?"}],"navigatorTitle":[{"text":"videoEventDelegate","kind":"identifier"}],"title":"videoEventDelegate","url":"\/documentation\/gfpsdk\/gfpnativesimpleadrenderingsetting\/videoeventdelegate","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdRenderingSetting\/videoEventDelegate","type":"topic","role":"symbol","abstract":[{"type":"text","text":"네이티브 심플에 기반한  리치형 광고 비디오 플레이어 이벤트를 위한 델리게이트 설정"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeSimpleAdRenderingSetting/isImageSizePreferred":{"navigatorTitle":[{"kind":"identifier","text":"isImageSizePreferred"}],"title":"isImageSizePreferred","abstract":[{"text":"네이티브 Media 이미지 적용 시 이미지 사이즈를 우선 할 지 여부입니다.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"(기본값은  NO)"},{"type":"text","text":" "},{"text":"해당 기능을 YES로 셋팅 시, 셋팅된 광고 영역보다 이미지 사이즈가 우선되며 하단에 배치됩니다.","type":"text"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdRenderingSetting\/isImageSizePreferred","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isImageSizePreferred","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"url":"\/documentation\/gfpsdk\/gfpnativesimpleadrenderingsetting\/isimagesizepreferred","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeSimpleAdRenderingSetting/addRenderer(with:rendererView:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"addRenderer"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"rendererView","kind":"externalParam"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"},{"text":" & ","kind":"text"},{"text":"GFPNativeRendererViewProtocol","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)GFPNativeRendererViewProtocol"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"addRendererWith:rendererView:","kind":"identifier"}],"title":"addRenderer(with:rendererView:)","url":"\/documentation\/gfpsdk\/gfpnativesimpleadrenderingsetting\/addrenderer(with:rendererview:)","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdRenderingSetting\/addRenderer(with:rendererView:)","type":"topic","role":"symbol","abstract":[],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)NSObject":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeSimpleAdRenderingSetting/maxExtendingHeight":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"maxExtendingHeight","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:GFPNativeAdRenderingSetting.h@T@GFPMaxExtendingHeightSetter","text":"GFPMaxExtendingHeightSetter"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"maxExtendingHeight"}],"title":"maxExtendingHeight","url":"\/documentation\/gfpsdk\/gfpnativesimpleadrenderingsetting\/maxextendingheight","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdRenderingSetting\/maxExtendingHeight","type":"topic","role":"symbol","abstract":[{"text":"확장형 리치형 광고의 최대 확장 높이를 제한합니다.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"광고가 호출된 이후에도 동적으로 관리할 수 있습니다."},{"type":"text","text":" "},{"text":"9:16 비율의 동영상도 제공하는 스페셜 DA 프리미엄형 “뉴” 동영상 확장형 이후로 부터 출시된 일부 광고 상품 부터 적용됩니다.","type":"text"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeBaseRenderingSetting":{"url":"\/documentation\/gfpsdk\/gfpnativebaserenderingsetting","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeBaseRenderingSetting","kind":"symbol","type":"topic","navigatorTitle":[{"text":"GFPNativeBaseRenderingSetting","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"GFPNativeBaseRenderingSetting","kind":"identifier"}],"abstract":[],"title":"GFPNativeBaseRenderingSetting"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.navercorp.da.gfp.GFPSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH","title":"Swift.Hashable"},"doc://com.navercorp.da.gfp.GFPSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s28CustomDebugStringConvertibleP"},"doc://com.navercorp.da.gfp.GFPSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeSimpleAdRenderingSetting":{"type":"topic","url":"\/documentation\/gfpsdk\/gfpnativesimpleadrenderingsetting","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPNativeSimpleAdRenderingSetting"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdRenderingSetting","title":"GFPNativeSimpleAdRenderingSetting","navigatorTitle":[{"text":"GFPNativeSimpleAdRenderingSetting","kind":"identifier"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeSimpleAdRenderingSetting/renderers":{"title":"renderers","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"renderers","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":" : any ","kind":"text"},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"},{"text":" & ","kind":"text"},{"text":"GFPNativeRendererViewProtocol","preciseIdentifier":"c:objc(pl)GFPNativeRendererViewProtocol","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"renderers"}],"type":"topic","url":"\/documentation\/gfpsdk\/gfpnativesimpleadrenderingsetting\/renderers","kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdRenderingSetting\/renderers","role":"symbol","abstract":[{"type":"text","text":"네이티브 심플의 custom renderer 사용 시 설정"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeSimpleAdRenderingSetting/removeRenderer(with:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"removeRenderer","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"removeRendererWith:","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdRenderingSetting\/removeRenderer(with:)","url":"\/documentation\/gfpsdk\/gfpnativesimpleadrenderingsetting\/removerenderer(with:)","kind":"symbol","role":"symbol","abstract":[],"type":"topic","title":"removeRenderer(with:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"GFPNativeSimpleAdRenderingSetting"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"text":"GFPNativeSimpleAdRenderingSetting","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"GFPNativeSimpleAdRenderingSetting","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdRenderingSetting\/isImageSizePreferred","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdRenderingSetting\/maxExtendingHeight","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdRenderingSetting\/renderers","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdRenderingSetting\/videoEventDelegate"],"generated":true},{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdRenderingSetting\/addRenderer(with:rendererView:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdRenderingSetting\/removeRenderer(with:)"],"generated":true,"title":"Instance Methods","anchor":"Instance-Methods"}]},{"value":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeBaseRenderingSetting"],"title":"Inherits From","kind":"relationships"}],"path":"\/relationshipsSections","op":"replace"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"GFPNativeSimpleAdRenderingSetting","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeBaseRenderingSetting","preciseIdentifier":"c:objc(cs)GFPNativeBaseRenderingSetting","text":"GFPNativeBaseRenderingSetting"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdRenderingSetting~1videoEventDelegate\/title","op":"replace","value":"videoEventDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdRenderingSetting~1videoEventDelegate\/fragments","value":[{"text":"videoEventDelegate","kind":"identifier"}]},{"value":"isImageSizePreferred","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdRenderingSetting~1isImageSizePreferred\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdRenderingSetting~1isImageSizePreferred\/fragments","op":"replace","value":[{"text":"isImageSizePreferred","kind":"identifier"}]},{"value":"addRendererWith:rendererView:","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdRenderingSetting~1addRenderer(with:rendererView:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"addRendererWith:rendererView:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdRenderingSetting~1addRenderer(with:rendererView:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdRenderingSetting~1maxExtendingHeight\/title","value":"maxExtendingHeight"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdRenderingSetting~1maxExtendingHeight\/fragments","value":[{"text":"maxExtendingHeight","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeBaseRenderingSetting\/title","value":"GFPNativeBaseRenderingSetting"},{"value":[{"kind":"identifier","text":"GFPNativeBaseRenderingSetting"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeBaseRenderingSetting\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeBaseRenderingSetting\/navigatorTitle","value":[{"text":"GFPNativeBaseRenderingSetting","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdRenderingSetting\/title","value":"GFPNativeSimpleAdRenderingSetting","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdRenderingSetting\/fragments","value":[{"text":"GFPNativeSimpleAdRenderingSetting","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdRenderingSetting\/navigatorTitle","value":[{"text":"GFPNativeSimpleAdRenderingSetting","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"renderers","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdRenderingSetting~1renderers\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdRenderingSetting~1renderers\/fragments","value":[{"kind":"identifier","text":"renderers"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdRenderingSetting~1removeRenderer(with:)\/title","op":"replace","value":"removeRendererWith:"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdRenderingSetting~1removeRenderer(with:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"removeRendererWith:","kind":"identifier"}]}]}]}