{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPNonLinearDelegate"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject","text":"NSObjectProtocol"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"metadata":{"title":"GFPNonLinearDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPNonLinearDelegate"}],"roleHeading":"Protocol","role":"symbol","externalID":"c:objc(pl)GFPNonLinearDelegate","symbolKind":"protocol","navigatorTitle":[{"text":"GFPNonLinearDelegate","kind":"identifier"}],"modules":[{"name":"GFPSDK"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearDelegate"},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","variants":[{"paths":["\/documentation\/gfpsdk\/gfpnonlineardelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gfpsdk\/gfpnonlineardelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject"]}],"topicSections":[{"generated":true,"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearDelegate\/nonLinear(onActiveImpression:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearDelegate\/nonLinearDidHide(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearDelegate\/nonLinearWasClicked(_:)"]}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNonLinearDelegate/nonLinear(onActiveImpression:)":{"type":"topic","abstract":[{"text":"Remind 광고가 사용자에게 보여질 경우 호출됩니다..","type":"text"}],"title":"nonLinear(onActiveImpression:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"nonLinear"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"onActiveImpression"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPRemindType","text":"GFPRemindType"},{"text":")","kind":"text"}],"url":"\/documentation\/gfpsdk\/gfpnonlineardelegate\/nonlinear(onactiveimpression:)","role":"symbol","required":true,"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearDelegate\/nonLinear(onActiveImpression:)","navigatorTitle":[{"text":"nonLinearOnActiveImpression:","kind":"identifier"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)NSObject":{"title":"NSObject","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNonLinearDelegate/nonLinearWasClicked(_:)":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearDelegate\/nonLinearWasClicked(_:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"nonLinearWasClicked:"}],"title":"nonLinearWasClicked(_:)","required":true,"url":"\/documentation\/gfpsdk\/gfpnonlineardelegate\/nonlinearwasclicked(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nonLinearWasClicked","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@E@GFPRemindType","kind":"typeIdentifier","text":"GFPRemindType"},{"kind":"text","text":")"}],"type":"topic","abstract":[{"type":"text","text":"Remind 광고 클릭시 호출됩니다."}],"role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNonLinearDelegate":{"url":"\/documentation\/gfpsdk\/gfpnonlineardelegate","abstract":[],"title":"GFPNonLinearDelegate","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearDelegate","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPNonLinearDelegate"}],"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPNonLinearDelegate"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNonLinearDelegate/nonLinearDidHide(_:)":{"type":"topic","abstract":[{"text":"Remind 광고가 사라지면 호출됩니다. (상황 : Duration 시간이 지난 이후,  가로 세로 화면 전환시, Close 버튼 클릭 시).","type":"text"}],"title":"nonLinearDidHide(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"nonLinearDidHide","kind":"identifier"},{"text":"(","kind":"text"},{"text":"GFPRemindType","preciseIdentifier":"c:@E@GFPRemindType","kind":"typeIdentifier"},{"kind":"text","text":")"}],"url":"\/documentation\/gfpsdk\/gfpnonlineardelegate\/nonlineardidhide(_:)","role":"symbol","required":true,"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearDelegate\/nonLinearDidHide(_:)","navigatorTitle":[{"kind":"identifier","text":"nonLinearDidHide:"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Protocol","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"GFPNonLinearDelegate"},{"path":"\/metadata\/symbolKind","value":"protocol","op":"replace"},{"value":[{"kind":"identifier","text":"GFPNonLinearDelegate"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"GFPNonLinearDelegate"}]},{"path":"\/topicSections","value":[{"generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearDelegate\/nonLinear(onActiveImpression:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearDelegate\/nonLinearDidHide(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearDelegate\/nonLinearWasClicked(_:)"],"title":"Instance Methods"}],"op":"replace"},{"value":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject"]}],"op":"replace","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPNonLinearDelegate","kind":"identifier"},{"text":" <","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"},{"text":">","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearDelegate~1nonLinear(onActiveImpression:)\/title","value":"nonLinearOnActiveImpression:"},{"value":[{"text":"- ","kind":"text"},{"text":"nonLinearOnActiveImpression:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearDelegate~1nonLinear(onActiveImpression:)\/fragments","op":"replace"},{"op":"replace","value":"nonLinearWasClicked:","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearDelegate~1nonLinearWasClicked(_:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"nonLinearWasClicked:"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearDelegate~1nonLinearWasClicked(_:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearDelegate\/title","value":"GFPNonLinearDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearDelegate\/fragments","value":[{"kind":"identifier","text":"GFPNonLinearDelegate"}]},{"value":[{"text":"GFPNonLinearDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearDelegate\/navigatorTitle"},{"value":"nonLinearDidHide:","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearDelegate~1nonLinearDidHide(_:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"nonLinearDidHide:"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearDelegate~1nonLinearDidHide(_:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}