{"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpnativeadbase"]},{"paths":["\/documentation\/gfpsdk\/gfpnativeadbase"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPNativeAdBase"}],"symbolKind":"class","role":"symbol","externalID":"c:objc(cs)GFPNativeAdBase","roleHeading":"Class","title":"GFPNativeAdBase","modules":[{"name":"GFPSDK"}],"navigatorTitle":[{"text":"GFPNativeAdBase","kind":"identifier"}]},"topicSections":[{"generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdBase\/adProviderName","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdBase\/adProviderNativeAd","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdBase\/adProviderType","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdBase\/adStyleOption","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdBase\/adStyleType","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdBase\/isAdInvalidate","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdBase\/responseInfo"],"title":"Instance Properties"}],"relationshipsSections":[{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"},{"type":"inheritedBy","title":"Inherited By","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAd","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAd"],"kind":"relationships"},{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s7CVarArgP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s23CustomStringConvertibleP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH"],"kind":"relationships","type":"conformsTo","title":"Conforms To"}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPNativeAdBase","kind":"identifier"}]}]}],"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdBase","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)NSObject":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdBase/adStyleOption":{"role":"symbol","abstract":[{"text":"광고 배경 정보","type":"text"}],"title":"adStyleOption","navigatorTitle":[{"kind":"identifier","text":"adStyleOption"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"adStyleOption","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPAdStyleOption","text":"GFPAdStyleOption","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdBase\/adStyleOption","type":"topic","kind":"symbol","url":"\/documentation\/gfpsdk\/gfpnativeadbase\/adstyleoption"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdBase/responseInfo":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"responseInfo","kind":"identifier"},{"text":": ","kind":"text"},{"text":"GFPLoadResponseInfo","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPLoadResponseInfo"}],"url":"\/documentation\/gfpsdk\/gfpnativeadbase\/responseinfo","kind":"symbol","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdBase\/responseInfo","abstract":[{"type":"text","text":"광고 응답 객체"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"responseInfo"}],"title":"responseInfo"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdBase/adProviderNativeAd":{"role":"symbol","abstract":[{"type":"text","text":"광고 제공자의 네이티브 광고 객체"}],"title":"adProviderNativeAd","navigatorTitle":[{"text":"adProviderNativeAd","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"adProviderNativeAd","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdBase\/adProviderNativeAd","url":"\/documentation\/gfpsdk\/gfpnativeadbase\/adprovidernativead","kind":"symbol","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdBase/adStyleType":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"adStyleType","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@GFPAdStyleType","text":"GFPAdStyleType","kind":"typeIdentifier"}],"url":"\/documentation\/gfpsdk\/gfpnativeadbase\/adstyletype","kind":"symbol","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdBase\/adStyleType","abstract":[{"text":"AdStyle","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"adStyleType"}],"title":"adStyleType"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdBase/isAdInvalidate":{"navigatorTitle":[{"text":"isAdInvalidate","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","abstract":[{"text":"광고 유효성 여부","type":"text"}],"url":"\/documentation\/gfpsdk\/gfpnativeadbase\/isadinvalidate","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdBase\/isAdInvalidate","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"isAdInvalidate","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"title":"isAdInvalidate"},"doc://com.navercorp.da.gfp.GFPSDK/s7CVarArgP":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAd":{"abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAd","url":"\/documentation\/gfpsdk\/gfpnativead","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPNativeAd"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPNativeAd"}],"type":"topic","kind":"symbol","title":"GFPNativeAd"},"doc://com.navercorp.da.gfp.GFPSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdBase/adProviderType":{"role":"symbol","abstract":[{"type":"text","text":"네이티브 응답의 광고 제공자 타입"}],"title":"adProviderType","navigatorTitle":[{"text":"adProviderType","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"adProviderType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"GFPNativeAdProviderType","kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPNativeAdProviderType"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdBase\/adProviderType","url":"\/documentation\/gfpsdk\/gfpnativeadbase\/adprovidertype","kind":"symbol","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/SH":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.navercorp.da.gfp.GFPSDK/objc(cs)NSObject":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://com.navercorp.da.gfp.GFPSDK/SQ":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdBase/adProviderName":{"role":"symbol","abstract":[{"type":"text","text":"광고 제공자 이름"}],"title":"adProviderName","navigatorTitle":[{"kind":"identifier","text":"adProviderName"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"adProviderName","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdBase\/adProviderName","url":"\/documentation\/gfpsdk\/gfpnativeadbase\/adprovidername","kind":"symbol","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdBase":{"kind":"symbol","role":"symbol","title":"GFPNativeAdBase","navigatorTitle":[{"kind":"identifier","text":"GFPNativeAdBase"}],"type":"topic","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPNativeAdBase","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpnativeadbase","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdBase"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeSimpleAd":{"type":"topic","navigatorTitle":[{"text":"GFPNativeSimpleAd","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPNativeSimpleAd"}],"title":"GFPNativeSimpleAd","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAd","url":"\/documentation\/gfpsdk\/gfpnativesimplead","abstract":[],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"GFPNativeAdBase"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"value":[{"kind":"identifier","text":"GFPNativeAdBase"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"GFPNativeAdBase"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdBase\/adProviderName","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdBase\/adProviderNativeAd","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdBase\/adProviderType","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdBase\/adStyleOption","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdBase\/adStyleType","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdBase\/isAdInvalidate","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdBase\/responseInfo"],"generated":true,"anchor":"Instance-Properties"}],"op":"replace"},{"value":[{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"},{"title":"Inherited By","type":"inheritedBy","kind":"relationships","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAd","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAd"]}],"op":"replace","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPNativeAdBase","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"adStyleOption","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdBase~1adStyleOption\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdBase~1adStyleOption\/fragments","value":[{"kind":"identifier","text":"adStyleOption"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdBase~1responseInfo\/title","value":"responseInfo"},{"value":[{"text":"responseInfo","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdBase~1responseInfo\/fragments","op":"replace"},{"value":"adProviderNativeAd","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdBase~1adProviderNativeAd\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdBase~1adProviderNativeAd\/fragments","value":[{"text":"adProviderNativeAd","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdBase~1adStyleType\/title","value":"adStyleType","op":"replace"},{"value":[{"text":"adStyleType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdBase~1adStyleType\/fragments","op":"replace"},{"op":"replace","value":"isAdInvalidate","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdBase~1isAdInvalidate\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdBase~1isAdInvalidate\/fragments","value":[{"kind":"identifier","text":"isAdInvalidate"}],"op":"replace"},{"value":"GFPNativeAd","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAd\/title"},{"op":"replace","value":[{"text":"GFPNativeAd","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAd\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAd\/navigatorTitle","value":[{"kind":"identifier","text":"GFPNativeAd"}],"op":"replace"},{"value":"adProviderType","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdBase~1adProviderType\/title"},{"op":"replace","value":[{"text":"adProviderType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdBase~1adProviderType\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdBase~1adProviderName\/title","value":"adProviderName"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdBase~1adProviderName\/fragments","value":[{"text":"adProviderName","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdBase\/title","value":"GFPNativeAdBase"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdBase\/fragments","value":[{"text":"GFPNativeAdBase","kind":"identifier"}]},{"value":[{"text":"GFPNativeAdBase","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdBase\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAd\/title","value":"GFPNativeSimpleAd"},{"value":[{"kind":"identifier","text":"GFPNativeSimpleAd"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAd\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAd\/navigatorTitle","value":[{"kind":"identifier","text":"GFPNativeSimpleAd"}],"op":"replace"}]}]}