{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeCarouselNotSupportedSlotTypeSubErrorCodeKey"},"metadata":{"roleHeading":"Global Variable","externalID":"c:@GFPNativeCarouselNotSupportedSlotTypeSubErrorCodeKey","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPNativeCarouselNotSupportedSlotTypeSubErrorCodeKey"}],"symbolKind":"var","modules":[{"name":"GFPSDK"}],"title":"GFPNativeCarouselNotSupportedSlotTypeSubErrorCodeKey","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPNativeCarouselNotSupportedSlotTypeSubErrorCodeKey"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPNativeCarouselNotSupportedSlotTypeSubErrorCodeKey"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"languages":["swift"],"platforms":["iOS"]}]}],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/gfpsdk\/gfpnativecarouselnotsupportedslottypesuberrorcodekey"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gfpsdk\/gfpnativecarouselnotsupportedslottypesuberrorcodekey"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeCarouselNotSupportedSlotTypeSubErrorCodeKey":{"navigatorTitle":[{"text":"GFPNativeCarouselNotSupportedSlotTypeSubErrorCodeKey","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpnativecarouselnotsupportedslottypesuberrorcodekey","role":"symbol","type":"topic","abstract":[],"title":"GFPNativeCarouselNotSupportedSlotTypeSubErrorCodeKey","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPNativeCarouselNotSupportedSlotTypeSubErrorCodeKey"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeCarouselNotSupportedSlotTypeSubErrorCodeKey"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Global Variable","op":"replace","path":"\/metadata\/roleHeading"},{"value":"GFPNativeCarouselNotSupportedSlotTypeSubErrorCodeKey","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"var"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"GFPNativeCarouselNotSupportedSlotTypeSubErrorCodeKey","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" * "},{"text":"GFPNativeCarouselNotSupportedSlotTypeSubErrorCodeKey","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeCarouselNotSupportedSlotTypeSubErrorCodeKey\/title","value":"GFPNativeCarouselNotSupportedSlotTypeSubErrorCodeKey","op":"replace"},{"value":[{"text":"GFPNativeCarouselNotSupportedSlotTypeSubErrorCodeKey","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeCarouselNotSupportedSlotTypeSubErrorCodeKey\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}