{"kind":"symbol","metadata":{"modules":[{"name":"GFPSDK"}],"title":"GFPNativeCarouselNotSupportedVisualKeySubErrorCodeKey","roleHeading":"Global Variable","externalID":"c:@GFPNativeCarouselNotSupportedVisualKeySubErrorCodeKey","navigatorTitle":[{"kind":"identifier","text":"GFPNativeCarouselNotSupportedVisualKeySubErrorCodeKey"}],"symbolKind":"var","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPNativeCarouselNotSupportedVisualKeySubErrorCodeKey"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"role":"symbol"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPNativeCarouselNotSupportedVisualKeySubErrorCodeKey","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpnativecarouselnotsupportedvisualkeysuberrorcodekey"]},{"paths":["\/documentation\/gfpsdk\/gfpnativecarouselnotsupportedvisualkeysuberrorcodekey"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeCarouselNotSupportedVisualKeySubErrorCodeKey","interfaceLanguage":"swift"},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeCarouselNotSupportedVisualKeySubErrorCodeKey":{"navigatorTitle":[{"kind":"identifier","text":"GFPNativeCarouselNotSupportedVisualKeySubErrorCodeKey"}],"type":"topic","title":"GFPNativeCarouselNotSupportedVisualKeySubErrorCodeKey","kind":"symbol","url":"\/documentation\/gfpsdk\/gfpnativecarouselnotsupportedvisualkeysuberrorcodekey","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeCarouselNotSupportedVisualKeySubErrorCodeKey","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPNativeCarouselNotSupportedVisualKeySubErrorCodeKey","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Global Variable","op":"replace"},{"path":"\/metadata\/title","value":"GFPNativeCarouselNotSupportedVisualKeySubErrorCodeKey","op":"replace"},{"path":"\/metadata\/symbolKind","value":"var","op":"replace"},{"value":[{"text":"GFPNativeCarouselNotSupportedVisualKeySubErrorCodeKey","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"kind":"identifier","text":"GFPNativeCarouselNotSupportedVisualKeySubErrorCodeKey"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":"GFPNativeCarouselNotSupportedVisualKeySubErrorCodeKey","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeCarouselNotSupportedVisualKeySubErrorCodeKey\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeCarouselNotSupportedVisualKeySubErrorCodeKey\/fragments","value":[{"text":"GFPNativeCarouselNotSupportedVisualKeySubErrorCodeKey","kind":"identifier"}],"op":"replace"}]}]}