{"metadata":{"role":"symbol","modules":[{"name":"GFPSDK"}],"externalID":"c:objc(cs)GFPNativeBaseRenderingSetting","symbolKind":"class","title":"GFPNativeBaseRenderingSetting","navigatorTitle":[{"kind":"identifier","text":"GFPNativeBaseRenderingSetting"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPNativeBaseRenderingSetting"}],"roleHeading":"Class"},"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject"],"type":"inheritsFrom"},{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdRenderingSetting","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdRenderingSetting"],"type":"inheritedBy","kind":"relationships","title":"Inherited By"},{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s7CVarArgP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s23CustomStringConvertibleP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH"],"title":"Conforms To","type":"conformsTo","kind":"relationships"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPNativeBaseRenderingSetting","kind":"identifier"}]}]}],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpnativebaserenderingsetting"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpnativebaserenderingsetting"]}],"topicSections":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeBaseRenderingSetting\/adChoicesPositionInFullAdView","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeBaseRenderingSetting\/adInterfaceStyle","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeBaseRenderingSetting\/enableCustomAdChoices","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeBaseRenderingSetting\/enableSpecialDABottomExtend","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeBaseRenderingSetting\/mediaBoldFont","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeBaseRenderingSetting\/mediaRegularFont","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeBaseRenderingSetting\/preferredAdChoicesViewPosition","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeBaseRenderingSetting\/richMediaInsets","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeBaseRenderingSetting\/useMediaDimmed"],"title":"Instance Properties","generated":true}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"kind":"symbol","identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeBaseRenderingSetting","interfaceLanguage":"swift"},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeBaseRenderingSetting/enableSpecialDABottomExtend":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableSpecialDABottomExtend"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"text":"enableSpecialDABottomExtend","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeBaseRenderingSetting\/enableSpecialDABottomExtend","role":"symbol","abstract":[{"type":"text","text":"Special DA의 기본 탑 마진을 사용하지 않고 아래 확장만 사용할 시에 사용합니다."},{"type":"text","text":" "},{"text":"(기본값은 NO)","type":"text"}],"url":"\/documentation\/gfpsdk\/gfpnativebaserenderingsetting\/enablespecialdabottomextend","title":"enableSpecialDABottomExtend"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeBaseRenderingSetting/mediaRegularFont":{"title":"mediaRegularFont","navigatorTitle":[{"kind":"identifier","text":"mediaRegularFont"}],"url":"\/documentation\/gfpsdk\/gfpnativebaserenderingsetting\/mediaregularfont","abstract":[{"type":"text","text":"캐러셀 광고의 MediaView 내부 폰트를 설정하고 싶을 때 전달합니다."},{"type":"text","text":" "},{"text":"(기본값은 nil)","type":"text"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeBaseRenderingSetting\/mediaRegularFont","type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mediaRegularFont"},{"text":": ","kind":"text"},{"text":"UIFont","preciseIdentifier":"c:objc(cs)UIFont","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeBaseRenderingSetting/richMediaInsets":{"role":"symbol","abstract":[{"type":"text","text":"캐러셀 광고 시 슬롯의 여백 값 입니다."},{"type":"text","text":" "},{"text":"해당 값을 통해 캐로셀 콜렉션뷰의 inset을 지원합니다.","type":"text"}],"title":"richMediaInsets","navigatorTitle":[{"kind":"identifier","text":"richMediaInsets"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"richMediaInsets"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@UIEdgeInsets","text":"UIEdgeInsets"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeBaseRenderingSetting\/richMediaInsets","url":"\/documentation\/gfpsdk\/gfpnativebaserenderingsetting\/richmediainsets","kind":"symbol","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeBaseRenderingSetting/adInterfaceStyle":{"type":"topic","title":"adInterfaceStyle","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"adInterfaceStyle"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"GFPAdInterfaceStyle","preciseIdentifier":"c:@E@GFPAdInterfaceStyle"}],"abstract":[{"type":"text","text":"네이티브 광고의 스타일을 설정합니다. (ex. adChoicesView 색상, rich media 광고 배경색 등)"},{"text":" ","type":"text"},{"type":"text","text":"네이버 광고에서 제공하는 광고에 한해 동작하며 그 외 DSP들은 해당 기능을 제공하지 않습니다."},{"type":"text","text":" "},{"type":"text","text":"기본값은 시스템의 mode를 따라갑니다."}],"url":"\/documentation\/gfpsdk\/gfpnativebaserenderingsetting\/adinterfacestyle","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"adInterfaceStyle"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeBaseRenderingSetting\/adInterfaceStyle"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeBaseRenderingSetting/enableCustomAdChoices":{"abstract":[{"text":"네이티브 광고의 adChoices 를 Custom 하게 사용할 경우 활성화 합니다.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"해당 옵션을 활성할 경우 GFP는 adChoicesView 를 그리지 않습니다."},{"text":" ","type":"text"},{"text":"단, s2s 광고에 한해 제공합니다. (c2s의 경우 옵션과 관계 없이 처리)","type":"text"},{"text":" ","type":"text"},{"text":"기본값은 NO 입니다.","type":"text"}],"title":"enableCustomAdChoices","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"enableCustomAdChoices","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"url":"\/documentation\/gfpsdk\/gfpnativebaserenderingsetting\/enablecustomadchoices","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeBaseRenderingSetting\/enableCustomAdChoices","navigatorTitle":[{"kind":"identifier","text":"enableCustomAdChoices"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdRenderingSetting":{"abstract":[],"kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdRenderingSetting","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPNativeAdRenderingSetting"}],"url":"\/documentation\/gfpsdk\/gfpnativeadrenderingsetting","title":"GFPNativeAdRenderingSetting","navigatorTitle":[{"kind":"identifier","text":"GFPNativeAdRenderingSetting"}]},"doc://com.navercorp.da.gfp.GFPSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject"},"doc://com.navercorp.da.gfp.GFPSDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ"},"doc://com.navercorp.da.gfp.GFPSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s28CustomDebugStringConvertibleP"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeSimpleAdRenderingSetting":{"type":"topic","url":"\/documentation\/gfpsdk\/gfpnativesimpleadrenderingsetting","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPNativeSimpleAdRenderingSetting"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdRenderingSetting","title":"GFPNativeSimpleAdRenderingSetting","navigatorTitle":[{"text":"GFPNativeSimpleAdRenderingSetting","kind":"identifier"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s7CVarArgP"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeBaseRenderingSetting/adChoicesPositionInFullAdView":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"adChoicesPositionInFullAdView","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"abstract":[{"text":"네이티브 광고에 adChoicesView 위치를 미디어 크기로 정할 지","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"전체 광고뷰로 정할 지 설정하는 옵션입니다."},{"type":"text","text":" "},{"text":"s2s 광고에 한해 지원되며, YES인 경우 전체 광고뷰로 설정합니다.","type":"text"},{"type":"text","text":" "},{"text":"기본값은 NO입니다.","type":"text"}],"navigatorTitle":[{"text":"adChoicesPositionInFullAdView","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpnativebaserenderingsetting\/adchoicespositioninfulladview","kind":"symbol","type":"topic","role":"symbol","title":"adChoicesPositionInFullAdView","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeBaseRenderingSetting\/adChoicesPositionInFullAdView"},"doc://com.navercorp.da.gfp.GFPSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s23CustomStringConvertibleP"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeBaseRenderingSetting/preferredAdChoicesViewPosition":{"title":"preferredAdChoicesViewPosition","abstract":[{"type":"text","text":"네이티브 광고에 adChoicesView 위치를 설정합니다."},{"text":" ","type":"text"},{"type":"text","text":"NN의 경우 Google DFP adChoiceView 의 위치를 설정하며, Overlay 형식으로 네이티브 뷰의 네 귀퉁이중 한 곳에 그려집니다."},{"type":"text","text":" "},{"type":"text","text":"NS의 경우 adChoicesView 내부에 마크가 그려집니다."},{"text":" ","type":"text"},{"text":"기본값은 우측상단입니다.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"preferredAdChoicesViewPosition","kind":"identifier"}],"type":"topic","url":"\/documentation\/gfpsdk\/gfpnativebaserenderingsetting\/preferredadchoicesviewposition","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"preferredAdChoicesViewPosition"},{"kind":"text","text":": "},{"text":"GFPAdChoicesViewPosition","kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPAdChoicesViewPosition"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeBaseRenderingSetting\/preferredAdChoicesViewPosition","role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeBaseRenderingSetting":{"url":"\/documentation\/gfpsdk\/gfpnativebaserenderingsetting","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeBaseRenderingSetting","kind":"symbol","type":"topic","navigatorTitle":[{"text":"GFPNativeBaseRenderingSetting","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"GFPNativeBaseRenderingSetting","kind":"identifier"}],"abstract":[],"title":"GFPNativeBaseRenderingSetting"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeBaseRenderingSetting/mediaBoldFont":{"url":"\/documentation\/gfpsdk\/gfpnativebaserenderingsetting\/mediaboldfont","title":"mediaBoldFont","abstract":[{"text":"캐러셀 광고의 MediaView 내부 폰트를 설정하고 싶을 때 전달합니다.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"(기본값은 nil)"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"mediaBoldFont"},{"text":": ","kind":"text"},{"text":"UIFont","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIFont"},{"text":"?","kind":"text"}],"type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeBaseRenderingSetting\/mediaBoldFont","navigatorTitle":[{"kind":"identifier","text":"mediaBoldFont"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/objc(cs)NSObject":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeBaseRenderingSetting/useMediaDimmed":{"type":"topic","title":"useMediaDimmed","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"useMediaDimmed","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"광고의 MediaView에 Dimmed를 설정하고 싶을 때 설정합니다."},{"type":"text","text":" "},{"type":"text","text":"옵션 사용 시 2%의 Dimmed가 적용됩니다. \/ 아웃스트림 동영상은 8%의 Dimmed가 적용됩니다."},{"type":"text","text":" "},{"type":"text","text":"(기본값은 NO)"}],"url":"\/documentation\/gfpsdk\/gfpnativebaserenderingsetting\/usemediadimmed","kind":"symbol","navigatorTitle":[{"text":"useMediaDimmed","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeBaseRenderingSetting\/useMediaDimmed"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"GFPNativeBaseRenderingSetting"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"GFPNativeBaseRenderingSetting"}]},{"op":"replace","value":[{"text":"GFPNativeBaseRenderingSetting","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeBaseRenderingSetting\/adChoicesPositionInFullAdView","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeBaseRenderingSetting\/adInterfaceStyle","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeBaseRenderingSetting\/enableCustomAdChoices","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeBaseRenderingSetting\/enableSpecialDABottomExtend","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeBaseRenderingSetting\/mediaBoldFont","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeBaseRenderingSetting\/mediaRegularFont","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeBaseRenderingSetting\/preferredAdChoicesViewPosition","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeBaseRenderingSetting\/richMediaInsets","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeBaseRenderingSetting\/useMediaDimmed"],"generated":true,"anchor":"Instance-Properties"}]},{"op":"replace","value":[{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"},{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdRenderingSetting","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdRenderingSetting"],"type":"inheritedBy","kind":"relationships","title":"Inherited By"}],"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPNativeBaseRenderingSetting","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeBaseRenderingSetting~1enableSpecialDABottomExtend\/title","value":"enableSpecialDABottomExtend"},{"value":[{"kind":"identifier","text":"enableSpecialDABottomExtend"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeBaseRenderingSetting~1enableSpecialDABottomExtend\/fragments"},{"value":"mediaRegularFont","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeBaseRenderingSetting~1mediaRegularFont\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeBaseRenderingSetting~1mediaRegularFont\/fragments","op":"replace","value":[{"text":"mediaRegularFont","kind":"identifier"}]},{"value":"richMediaInsets","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeBaseRenderingSetting~1richMediaInsets\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeBaseRenderingSetting~1richMediaInsets\/fragments","value":[{"text":"richMediaInsets","kind":"identifier"}],"op":"replace"},{"value":"adInterfaceStyle","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeBaseRenderingSetting~1adInterfaceStyle\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeBaseRenderingSetting~1adInterfaceStyle\/fragments","value":[{"kind":"identifier","text":"adInterfaceStyle"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeBaseRenderingSetting~1enableCustomAdChoices\/title","value":"enableCustomAdChoices"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeBaseRenderingSetting~1enableCustomAdChoices\/fragments","value":[{"kind":"identifier","text":"enableCustomAdChoices"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdRenderingSetting\/title","value":"GFPNativeAdRenderingSetting"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdRenderingSetting\/fragments","value":[{"text":"GFPNativeAdRenderingSetting","kind":"identifier"}]},{"value":[{"text":"GFPNativeAdRenderingSetting","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdRenderingSetting\/navigatorTitle"},{"op":"replace","value":"GFPNativeSimpleAdRenderingSetting","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdRenderingSetting\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdRenderingSetting\/fragments","value":[{"kind":"identifier","text":"GFPNativeSimpleAdRenderingSetting"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdRenderingSetting\/navigatorTitle","op":"replace","value":[{"text":"GFPNativeSimpleAdRenderingSetting","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeBaseRenderingSetting~1adChoicesPositionInFullAdView\/title","value":"adChoicesPositionInFullAdView","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeBaseRenderingSetting~1adChoicesPositionInFullAdView\/fragments","op":"replace","value":[{"kind":"identifier","text":"adChoicesPositionInFullAdView"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeBaseRenderingSetting~1preferredAdChoicesViewPosition\/title","value":"preferredAdChoicesViewPosition","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeBaseRenderingSetting~1preferredAdChoicesViewPosition\/fragments","op":"replace","value":[{"text":"preferredAdChoicesViewPosition","kind":"identifier"}]},{"op":"replace","value":"GFPNativeBaseRenderingSetting","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeBaseRenderingSetting\/title"},{"value":[{"text":"GFPNativeBaseRenderingSetting","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeBaseRenderingSetting\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeBaseRenderingSetting\/navigatorTitle","op":"replace","value":[{"text":"GFPNativeBaseRenderingSetting","kind":"identifier"}]},{"value":"mediaBoldFont","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeBaseRenderingSetting~1mediaBoldFont\/title"},{"value":[{"kind":"identifier","text":"mediaBoldFont"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeBaseRenderingSetting~1mediaBoldFont\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeBaseRenderingSetting~1useMediaDimmed\/title","value":"useMediaDimmed"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeBaseRenderingSetting~1useMediaDimmed\/fragments","value":[{"text":"useMediaDimmed","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}