{"kind":"symbol","topicSections":[{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeBaseView\/mediaView"],"anchor":"Instance-Properties"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"paths":["\/documentation\/gfpsdk\/gfpnativebaseview"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpnativebaseview"]}],"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)UIView"],"title":"Inherits From","kind":"relationships"},{"title":"Inherited By","kind":"relationships","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdView","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdView"],"type":"inheritedBy"},{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSCoding","doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)CALayerDelegate","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s7CVarArgP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s23CustomStringConvertibleP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s8SendableP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UIAccessibilityIdentification","doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UIAppearance","doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UIAppearanceContainer","doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UICoordinateSpace","doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UIDynamicItem","doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UIFocusEnvironment","doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UIFocusItem","doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UIFocusItemContainer","doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UILargeContentViewerItem","doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.navercorp.da.gfp.GFPSDK\/5UIKit23UITraitChangeObservableP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UITraitEnvironment","doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UIUserActivityRestoring"]}],"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeBaseView","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPNativeBaseView"}]}],"kind":"declarations"}],"metadata":{"symbolKind":"class","modules":[{"name":"GFPSDK"}],"roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPNativeBaseView","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"GFPNativeBaseView","kind":"identifier"}],"externalID":"c:objc(cs)GFPNativeBaseView","title":"GFPNativeBaseView"},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"sections":[],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeBaseView/mediaView":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeBaseView\/mediaView","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"mediaView","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPMediaView","text":"GFPMediaView"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"mediaView"}],"type":"topic","role":"symbol","url":"\/documentation\/gfpsdk\/gfpnativebaseview\/mediaview","title":"mediaView","kind":"symbol","abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)UIFocusItem":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UIFocusItem","title":"UIKit.UIFocusItem","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/objc(cs)UIView":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)UIView","title":"UIView","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/SQ":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)UIPasteConfigurationSupporting":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UIPasteConfigurationSupporting","title":"UIKit.UIPasteConfigurationSupporting","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)UIFocusItemContainer":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UIFocusItemContainer","title":"UIKit.UIFocusItemContainer","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)UIAccessibilityIdentification":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UIAccessibilityIdentification","title":"UIKit.UIAccessibilityIdentification","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)UIAppearanceContainer":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UIAppearanceContainer","title":"UIKit.UIAppearanceContainer","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeSimpleAdView":{"kind":"symbol","navigatorTitle":[{"text":"GFPNativeSimpleAdView","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdView","title":"GFPNativeSimpleAdView","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPNativeSimpleAdView","kind":"identifier"}],"type":"topic","url":"\/documentation\/gfpsdk\/gfpnativesimpleadview","abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)UIResponderStandardEditActions":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UIResponderStandardEditActions","title":"UIKit.UIResponderStandardEditActions","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)UICoordinateSpace":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UICoordinateSpace","title":"UIKit.UICoordinateSpace","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/s8SendableP":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s8SendableP","title":"Swift.Sendable","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)UIActivityItemsConfigurationProviding":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UIActivityItemsConfigurationProviding","title":"UIKit.UIActivityItemsConfigurationProviding","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdView":{"navigatorTitle":[{"text":"GFPNativeAdView","kind":"identifier"}],"title":"GFPNativeAdView","url":"\/documentation\/gfpsdk\/gfpnativeadview","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdView","role":"symbol","type":"topic","kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"GFPNativeAdView","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)UILargeContentViewerItem":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UILargeContentViewerItem","title":"UIKit.UILargeContentViewerItem","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)NSObject":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)UIPopoverPresentationControllerSourceItem":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UIPopoverPresentationControllerSourceItem","title":"UIKit.UIPopoverPresentationControllerSourceItem","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeBaseView":{"kind":"symbol","type":"topic","abstract":[],"url":"\/documentation\/gfpsdk\/gfpnativebaseview","navigatorTitle":[{"text":"GFPNativeBaseView","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPNativeBaseView"}],"title":"GFPNativeBaseView","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeBaseView"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)UIDynamicItem":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UIDynamicItem","title":"UIKit.UIDynamicItem","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/SH":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)UIFocusEnvironment":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UIFocusEnvironment","title":"UIKit.UIFocusEnvironment","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)UITraitEnvironment":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UITraitEnvironment","title":"UIKit.UITraitEnvironment","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/s7CVarArgP":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)CALayerDelegate":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)CALayerDelegate","title":"QuartzCore.CALayerDelegate","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/5UIKit23UITraitChangeObservableP":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/5UIKit23UITraitChangeObservableP","title":"UIKit.UITraitChangeObservable","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)UIAppearance":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UIAppearance","title":"UIKit.UIAppearance","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)UIUserActivityRestoring":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)UIUserActivityRestoring","title":"UIKit.UIUserActivityRestoring","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)NSCoding":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSCoding","title":"Foundation.NSCoding","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"GFPNativeBaseView"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"op":"replace","value":[{"text":"GFPNativeBaseView","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"GFPNativeBaseView","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"generated":true,"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeBaseView\/mediaView"],"anchor":"Instance-Properties","title":"Instance Properties"}]},{"value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)UIView"],"type":"inheritsFrom"},{"type":"inheritedBy","title":"Inherited By","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdView","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdView"],"kind":"relationships"}],"op":"replace","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPNativeBaseView","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":"mediaView","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeBaseView~1mediaView\/title"},{"value":[{"text":"mediaView","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeBaseView~1mediaView\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdView\/title","value":"GFPNativeSimpleAdView","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdView\/fragments","op":"replace","value":[{"kind":"identifier","text":"GFPNativeSimpleAdView"}]},{"value":[{"kind":"identifier","text":"GFPNativeSimpleAdView"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdView\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdView\/title","value":"GFPNativeAdView","op":"replace"},{"value":[{"text":"GFPNativeAdView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdView\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdView\/navigatorTitle","value":[{"text":"GFPNativeAdView","kind":"identifier"}]},{"op":"replace","value":"GFPNativeBaseView","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeBaseView\/title"},{"value":[{"kind":"identifier","text":"GFPNativeBaseView"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeBaseView\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeBaseView\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"GFPNativeBaseView"}]}]}]}