{"relationshipsSections":[{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/s15BitwiseCopyableP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s25ExpressibleByArrayLiteralP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s9OptionSetP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SY","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s8SendableP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s10SetAlgebraP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpomcontantstype"]},{"paths":["\/documentation\/gfpsdk\/gfpomcontantstype"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"generated":true,"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPOMContantsType\/init(rawValue:)"],"anchor":"Initializers","title":"Initializers"},{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPOMContantsType\/HTML","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPOMContantsType\/audio","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPOMContantsType\/htmlVideo","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPOMContantsType\/image","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPOMContantsType\/video"],"anchor":"Type-Properties","generated":true,"title":"Type Properties"},{"anchor":"Default-Implementations","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPOMContantsType\/Equatable-Implementations","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPOMContantsType\/OptionSet-Implementations","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPOMContantsType\/SetAlgebra-Implementations"],"generated":true,"title":"Default Implementations"}],"sections":[],"kind":"symbol","metadata":{"modules":[{"name":"GFPSDK"}],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPOMContantsType"}],"navigatorTitle":[{"text":"GFPOMContantsType","kind":"identifier"}],"role":"symbol","roleHeading":"Structure","title":"GFPOMContantsType","symbolKind":"struct","externalID":"c:@E@GFPOMContantsType"},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPOMContantsType","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPOMContantsType"}],"platforms":["iOS"]}]}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPOMContantsType/htmlVideo":{"kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPOMContantsType\/htmlVideo","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"htmlVideo","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GFPOMContantsType","preciseIdentifier":"c:@E@GFPOMContantsType"}],"abstract":[],"title":"htmlVideo","type":"topic","url":"\/documentation\/gfpsdk\/gfpomcontantstype\/htmlvideo","navigatorTitle":[{"text":"GFPOMContantsTypeHTMLVideo","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPOMContantsType/SetAlgebra-Implementations":{"abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPOMContantsType\/SetAlgebra-Implementations","type":"topic","title":"SetAlgebra Implementations","url":"\/documentation\/gfpsdk\/gfpomcontantstype\/setalgebra-implementations","kind":"article","role":"collectionGroup"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPOMContantsType/audio":{"url":"\/documentation\/gfpsdk\/gfpomcontantstype\/audio","title":"audio","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPOMContantsType\/audio","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPOMContantsTypeAudio"}],"type":"topic","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"audio","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPOMContantsType","text":"GFPOMContantsType"}]},"doc://com.navercorp.da.gfp.GFPSDK/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s8SendableP"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPOMContantsType/HTML":{"url":"\/documentation\/gfpsdk\/gfpomcontantstype\/html","title":"HTML","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPOMContantsType\/HTML","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPOMContantsTypeHTML"}],"type":"topic","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HTML"},{"kind":"text","text":": "},{"text":"GFPOMContantsType","kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPOMContantsType"}]},"doc://com.navercorp.da.gfp.GFPSDK/s25ExpressibleByArrayLiteralP":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s25ExpressibleByArrayLiteralP","title":"Swift.ExpressibleByArrayLiteral","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPOMContantsType/video":{"url":"\/documentation\/gfpsdk\/gfpomcontantstype\/video","title":"video","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPOMContantsType\/video","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPOMContantsTypeVideo"}],"type":"topic","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"video","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPOMContantsType","text":"GFPOMContantsType"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPOMContantsType/image":{"kind":"symbol","type":"topic","abstract":[],"url":"\/documentation\/gfpsdk\/gfpomcontantstype\/image","navigatorTitle":[{"kind":"identifier","text":"GFPOMContantsTypeImage"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"image"},{"kind":"text","text":": "},{"text":"GFPOMContantsType","kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPOMContantsType"}],"title":"image","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPOMContantsType\/image"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPOMContantsType":{"abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPOMContantsType","navigatorTitle":[{"text":"GFPOMContantsType","kind":"identifier"}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"GFPOMContantsType","kind":"identifier"}],"kind":"symbol","title":"GFPOMContantsType","url":"\/documentation\/gfpsdk\/gfpomcontantstype"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPOMContantsType/OptionSet-Implementations":{"url":"\/documentation\/gfpsdk\/gfpomcontantstype\/optionset-implementations","title":"OptionSet Implementations","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPOMContantsType\/OptionSet-Implementations","role":"collectionGroup","kind":"article","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPOMContantsType/init(rawValue:)":{"kind":"symbol","type":"topic","abstract":[],"url":"\/documentation\/gfpsdk\/gfpomcontantstype\/init(rawvalue:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"init(rawValue:)","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPOMContantsType\/init(rawValue:)"},"doc://com.navercorp.da.gfp.GFPSDK/s9OptionSetP":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s9OptionSetP","title":"Swift.OptionSet"},"doc://com.navercorp.da.gfp.GFPSDK/s15BitwiseCopyableP":{"title":"Swift.BitwiseCopyable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s15BitwiseCopyableP","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPOMContantsType/Equatable-Implementations":{"url":"\/documentation\/gfpsdk\/gfpomcontantstype\/equatable-implementations","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPOMContantsType\/Equatable-Implementations","role":"collectionGroup","kind":"article","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/SY":{"title":"Swift.RawRepresentable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SY","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/s10SetAlgebraP":{"title":"Swift.SetAlgebra","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s10SetAlgebraP","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","type":"unresolvable"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"GFPOMContantsType"},{"value":"enum","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"text":"GFPOMContantsType","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"GFPOMContantsType"}]},{"path":"\/topicSections","value":[{"anchor":"Enumeration-Cases","generated":true,"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPOMContantsType\/HTML","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPOMContantsType\/audio","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPOMContantsType\/htmlVideo","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPOMContantsType\/image","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPOMContantsType\/video"],"title":"Enumeration Cases"}],"op":"replace"},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPOMContantsType"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPOMContantsType~1htmlVideo\/title","value":"GFPOMContantsTypeHTMLVideo","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPOMContantsType~1htmlVideo\/fragments","value":[{"kind":"identifier","text":"GFPOMContantsTypeHTMLVideo"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPOMContantsType~1audio\/title","value":"GFPOMContantsTypeAudio","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPOMContantsType~1audio\/fragments","value":[{"text":"GFPOMContantsTypeAudio","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPOMContantsType~1HTML\/title","value":"GFPOMContantsTypeHTML"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPOMContantsType~1HTML\/fragments","value":[{"kind":"identifier","text":"GFPOMContantsTypeHTML"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPOMContantsType~1video\/title","value":"GFPOMContantsTypeVideo","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPOMContantsType~1video\/fragments","op":"replace","value":[{"text":"GFPOMContantsTypeVideo","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPOMContantsType~1image\/title","op":"replace","value":"GFPOMContantsTypeImage"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPOMContantsType~1image\/fragments","op":"replace","value":[{"kind":"identifier","text":"GFPOMContantsTypeImage"}]},{"value":"GFPOMContantsType","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPOMContantsType\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPOMContantsType\/fragments","op":"replace","value":[{"text":"GFPOMContantsType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPOMContantsType\/navigatorTitle","value":[{"kind":"identifier","text":"GFPOMContantsType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}