{"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"externalID":"c:@GFPProviderRenderTypeChartBoost","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPProviderRenderTypeChartBoost"}],"title":"GFPProviderRenderTypeChartBoost","roleHeading":"Global Variable","modules":[{"name":"GFPSDK"}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPProviderRenderTypeChartBoost","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"symbolKind":"var"},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"variants":[{"paths":["\/documentation\/gfpsdk\/gfpproviderrendertypechartboost"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpproviderrendertypechartboost"]}],"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPProviderRenderTypeChartBoost","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPProviderRenderTypeChartBoost"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPProviderRenderTypeChartBoost":{"type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPProviderRenderTypeChartBoost","title":"GFPProviderRenderTypeChartBoost","abstract":[],"kind":"symbol","url":"\/documentation\/gfpsdk\/gfpproviderrendertypechartboost","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPProviderRenderTypeChartBoost","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPProviderRenderTypeChartBoost"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Global Variable","path":"\/metadata\/roleHeading"},{"op":"replace","value":"GFPProviderRenderTypeChartBoost","path":"\/metadata\/title"},{"value":"var","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"GFPProviderRenderTypeChartBoost","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"extern","kind":"keyword"},{"kind":"text","text":" "},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"GFPProviderRenderTypeChartBoost","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPProviderRenderTypeChartBoost\/title","value":"GFPProviderRenderTypeChartBoost"},{"op":"replace","value":[{"text":"GFPProviderRenderTypeChartBoost","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPProviderRenderTypeChartBoost\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}