{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"GFPProviderProductType","kind":"identifier"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpproviderproducttype"]},{"paths":["\/documentation\/gfpsdk\/gfpproviderproducttype"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPProviderProductType"},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"kind":"symbol","topicSections":[{"anchor":"Initializers","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPProviderProductType\/init(rawValue:)"],"title":"Initializers","generated":true},{"anchor":"Default-Implementations","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPProviderProductType\/Equatable-Implementations","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPProviderProductType\/_SwiftNewtypeWrapper-Implementations"],"title":"Default Implementations","generated":true}],"relationshipsSections":[{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SY","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s8SendableP"],"kind":"relationships"}],"metadata":{"modules":[{"name":"GFPSDK"}],"navigatorTitle":[{"kind":"identifier","text":"GFPProviderProductType"}],"symbolKind":"struct","role":"symbol","roleHeading":"Structure","externalID":"c:GFPProvider.h@T@GFPProviderProductType","title":"GFPProviderProductType","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"GFPProviderProductType","kind":"identifier"}]},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPProviderProductType/_SwiftNewtypeWrapper-Implementations":{"abstract":[],"kind":"article","role":"collectionGroup","type":"topic","title":"_SwiftNewtypeWrapper Implementations","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPProviderProductType\/_SwiftNewtypeWrapper-Implementations","url":"\/documentation\/gfpsdk\/gfpproviderproducttype\/_swiftnewtypewrapper-implementations"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPProviderProductType/init(rawValue:)":{"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPProviderProductType\/init(rawValue:)","url":"\/documentation\/gfpsdk\/gfpproviderproducttype\/init(rawvalue:)","kind":"symbol","role":"symbol","abstract":[],"type":"topic","title":"init(rawValue:)"},"doc://com.navercorp.da.gfp.GFPSDK/SY":{"title":"Swift.RawRepresentable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SY","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPProviderProductType/Equatable-Implementations":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPProviderProductType\/Equatable-Implementations","url":"\/documentation\/gfpsdk\/gfpproviderproducttype\/equatable-implementations","kind":"article","role":"collectionGroup","abstract":[],"type":"topic","title":"Equatable Implementations"},"doc://com.navercorp.da.gfp.GFPSDK/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPProviderProductType":{"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPProviderProductType","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"GFPProviderProductType"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPProviderProductType","url":"\/documentation\/gfpsdk\/gfpproviderproducttype","kind":"symbol","role":"symbol","abstract":[],"type":"topic","title":"GFPProviderProductType"},"doc://com.navercorp.da.gfp.GFPSDK/s8SendableP":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s8SendableP","title":"Swift.Sendable","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/SQ":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Alias"},{"op":"replace","path":"\/metadata\/title","value":"GFPProviderProductType"},{"path":"\/metadata\/symbolKind","value":"typealias","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GFPProviderProductType"}]},{"value":[{"text":"GFPProviderProductType","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","value":null,"op":"replace"},{"op":"replace","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"typedef"},{"text":" ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"GFPProviderProductType"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"GFPProviderProductType","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPProviderProductType\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPProviderProductType\/fragments","value":[{"text":"GFPProviderProductType","kind":"identifier"}],"op":"replace"},{"value":[{"text":"GFPProviderProductType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPProviderProductType\/navigatorTitle","op":"replace"}]}]}