{"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"variants":[{"paths":["\/documentation\/gfpsdk\/gfpproviderproducttyperewarded"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gfpsdk\/gfpproviderproducttyperewarded"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"var","role":"symbol","modules":[{"name":"GFPSDK"}],"title":"GFPProviderProductTypeRewarded","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPProviderProductTypeRewarded","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"externalID":"c:@GFPProviderProductTypeRewarded","navigatorTitle":[{"text":"GFPProviderProductTypeRewarded","kind":"identifier"}],"roleHeading":"Global Variable"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPProviderProductTypeRewarded"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"GFPProviderProductTypeRewarded","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}]}],"kind":"declarations"}],"sections":[],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPProviderProductTypeRewarded":{"abstract":[],"type":"topic","title":"GFPProviderProductTypeRewarded","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPProviderProductTypeRewarded","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"url":"\/documentation\/gfpsdk\/gfpproviderproducttyperewarded","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPProviderProductTypeRewarded","navigatorTitle":[{"kind":"identifier","text":"GFPProviderProductTypeRewarded"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Global Variable","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"GFPProviderProductTypeRewarded"},{"op":"replace","path":"\/metadata\/symbolKind","value":"var"},{"op":"replace","value":[{"text":"GFPProviderProductTypeRewarded","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"extern","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" * ","kind":"text"},{"text":"GFPProviderProductTypeRewarded","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPProviderProductTypeRewarded\/title","op":"replace","value":"GFPProviderProductTypeRewarded"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPProviderProductTypeRewarded\/fragments","value":[{"text":"GFPProviderProductTypeRewarded","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}