{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPProviderRenderTypeRewarded"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPProviderRenderTypeRewarded"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"platforms":["iOS"]}]}],"kind":"symbol","metadata":{"title":"GFPProviderRenderTypeRewarded","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"GFPProviderRenderTypeRewarded","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"roleHeading":"Global Variable","role":"symbol","symbolKind":"var","externalID":"c:@GFPProviderRenderTypeRewarded","navigatorTitle":[{"text":"GFPProviderRenderTypeRewarded","kind":"identifier"}],"modules":[{"name":"GFPSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpproviderrendertyperewarded"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpproviderrendertyperewarded"]}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPProviderRenderTypeRewarded":{"abstract":[],"url":"\/documentation\/gfpsdk\/gfpproviderrendertyperewarded","role":"symbol","title":"GFPProviderRenderTypeRewarded","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPProviderRenderTypeRewarded","type":"topic","navigatorTitle":[{"text":"GFPProviderRenderTypeRewarded","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"GFPProviderRenderTypeRewarded","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Global Variable","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"GFPProviderRenderTypeRewarded","op":"replace"},{"value":"var","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"GFPProviderRenderTypeRewarded","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" * ","kind":"text"},{"text":"GFPProviderRenderTypeRewarded","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPProviderRenderTypeRewarded\/title","value":"GFPProviderRenderTypeRewarded"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPProviderRenderTypeRewarded\/fragments","op":"replace","value":[{"text":"GFPProviderRenderTypeRewarded","kind":"identifier"}]}]}]}