{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPProviderRenderTypeBidMachine","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpproviderrendertypebidmachine"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gfpsdk\/gfpproviderrendertypebidmachine"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"var","externalID":"c:@GFPProviderRenderTypeBidMachine","modules":[{"name":"GFPSDK"}],"navigatorTitle":[{"text":"GFPProviderRenderTypeBidMachine","kind":"identifier"}],"title":"GFPProviderRenderTypeBidMachine","roleHeading":"Global Variable","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"GFPProviderRenderTypeBidMachine","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"role":"symbol"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPProviderRenderTypeBidMachine","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPProviderRenderTypeBidMachine":{"navigatorTitle":[{"kind":"identifier","text":"GFPProviderRenderTypeBidMachine"}],"role":"symbol","kind":"symbol","abstract":[],"url":"\/documentation\/gfpsdk\/gfpproviderrendertypebidmachine","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPProviderRenderTypeBidMachine","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"GFPProviderRenderTypeBidMachine","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"title":"GFPProviderRenderTypeBidMachine"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Global Variable","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"GFPProviderRenderTypeBidMachine"},{"op":"replace","value":"var","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"GFPProviderRenderTypeBidMachine"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"extern"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"GFPProviderRenderTypeBidMachine","kind":"identifier"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPProviderRenderTypeBidMachine\/title","value":"GFPProviderRenderTypeBidMachine"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPProviderRenderTypeBidMachine\/fragments","value":[{"text":"GFPProviderRenderTypeBidMachine","kind":"identifier"}],"op":"replace"}]}]}