{"metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"GFPProviderRenderTypeSIMPLE","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"symbolKind":"var","navigatorTitle":[{"kind":"identifier","text":"GFPProviderRenderTypeSIMPLE"}],"modules":[{"name":"GFPSDK"}],"title":"GFPProviderRenderTypeSIMPLE","externalID":"c:@GFPProviderRenderTypeSIMPLE","roleHeading":"Global Variable"},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPProviderRenderTypeSIMPLE"},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPProviderRenderTypeSIMPLE"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"variants":[{"paths":["\/documentation\/gfpsdk\/gfpproviderrendertypesimple"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gfpsdk\/gfpproviderrendertypesimple"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPProviderRenderTypeSIMPLE":{"type":"topic","url":"\/documentation\/gfpsdk\/gfpproviderrendertypesimple","role":"symbol","abstract":[],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPProviderRenderTypeSIMPLE","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPProviderRenderTypeSIMPLE","title":"GFPProviderRenderTypeSIMPLE","navigatorTitle":[{"kind":"identifier","text":"GFPProviderRenderTypeSIMPLE"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Global Variable","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"GFPProviderRenderTypeSIMPLE","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"var"},{"path":"\/metadata\/fragments","value":[{"text":"GFPProviderRenderTypeSIMPLE","kind":"identifier"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"extern","kind":"keyword"},{"kind":"text","text":" "},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"GFPProviderRenderTypeSIMPLE"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPProviderRenderTypeSIMPLE\/title","op":"replace","value":"GFPProviderRenderTypeSIMPLE"},{"value":[{"kind":"identifier","text":"GFPProviderRenderTypeSIMPLE"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPProviderRenderTypeSIMPLE\/fragments","op":"replace"}]}]}