{"sections":[],"metadata":{"externalID":"c:@M@GFPSDK@objc(cs)GFPQoeTrackingInfo","navigatorTitle":[{"kind":"identifier","text":"GFPQoeTrackingInfo"}],"title":"GFPQoeTrackingInfo","role":"symbol","symbolKind":"class","roleHeading":"Class","modules":[{"name":"GFPSDK"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPQoeTrackingInfo","kind":"identifier"}]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPQoeTrackingInfo\/appId","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPQoeTrackingInfo\/isValid","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPQoeTrackingInfo\/ownerServiceId","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPQoeTrackingInfo\/serviceId","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPQoeTrackingInfo\/timeTable","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPQoeTrackingInfo\/urlString","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPQoeTrackingInfo\/viewerInfo"],"generated":true,"anchor":"Instance-Properties"},{"generated":true,"title":"Type Methods","anchor":"Type-Methods","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPQoeTrackingInfo\/createQoeTrackingInfo(host:path:timeTable:serviceId:ownerServiceId:appId:viewerInfo:)"]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objcMembers","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPQoeTrackingInfo","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject"]},{"title":"Conforms To","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s7CVarArgP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s23CustomStringConvertibleP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH"],"type":"conformsTo","kind":"relationships"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpqoetrackinginfo"]},{"paths":["\/documentation\/gfpsdk\/gfpqoetrackinginfo"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPQoeTrackingInfo","interfaceLanguage":"swift"},"references":{"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)NSObject":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPQoeTrackingInfo/urlString":{"navigatorTitle":[{"kind":"identifier","text":"urlString"}],"type":"topic","title":"urlString","kind":"symbol","url":"\/documentation\/gfpsdk\/gfpqoetrackinginfo\/urlstring","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPQoeTrackingInfo\/urlString","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"urlString","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPQoeTrackingInfo/ownerServiceId":{"abstract":[],"title":"ownerServiceId","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"ownerServiceId","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPQoeTrackingInfo\/ownerServiceId","url":"\/documentation\/gfpsdk\/gfpqoetrackinginfo\/ownerserviceid","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"ownerServiceId","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}]},"doc://com.navercorp.da.gfp.GFPSDK/objc(cs)NSObject":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPQoeTrackingInfo/appId":{"abstract":[],"url":"\/documentation\/gfpsdk\/gfpqoetrackinginfo\/appid","role":"symbol","title":"appId","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPQoeTrackingInfo\/appId","type":"topic","navigatorTitle":[{"kind":"identifier","text":"appId"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"appId","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPQoeTrackingInfo/timeTable":{"abstract":[],"url":"\/documentation\/gfpsdk\/gfpqoetrackinginfo\/timetable","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"timeTable"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":"]","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"timeTable"}],"kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPQoeTrackingInfo\/timeTable","title":"timeTable","role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/SH":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/s7CVarArgP":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPQoeTrackingInfo/serviceId":{"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"serviceId"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"serviceId","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPQoeTrackingInfo\/serviceId","type":"topic","kind":"symbol","title":"serviceId","url":"\/documentation\/gfpsdk\/gfpqoetrackinginfo\/serviceid","role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPQoeTrackingInfo/createQoeTrackingInfo(host:path:timeTable:serviceId:ownerServiceId:appId:viewerInfo:)":{"navigatorTitle":[{"kind":"identifier","text":"createQoeTrackingInfoWith:path:timeTable:serviceId:ownerServiceId:appId:viewerInfo:"}],"type":"topic","title":"createQoeTrackingInfo(host:path:timeTable:serviceId:ownerServiceId:appId:viewerInfo:)","kind":"symbol","url":"\/documentation\/gfpsdk\/gfpqoetrackinginfo\/createqoetrackinginfo(host:path:timetable:serviceid:ownerserviceid:appid:viewerinfo:)","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPQoeTrackingInfo\/createQoeTrackingInfo(host:path:timeTable:serviceId:ownerServiceId:appId:viewerInfo:)","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createQoeTrackingInfo","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"host"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"path","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"timeTable","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"serviceId"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"ownerServiceId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"appId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"viewerInfo","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"text":"GFPQoeTrackingInfo","preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPQoeTrackingInfo","kind":"typeIdentifier"}],"role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPQoeTrackingInfo":{"role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"GFPQoeTrackingInfo"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPQoeTrackingInfo"}],"kind":"symbol","type":"topic","title":"GFPQoeTrackingInfo","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPQoeTrackingInfo","url":"\/documentation\/gfpsdk\/gfpqoetrackinginfo"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPQoeTrackingInfo/isValid":{"title":"isValid","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPQoeTrackingInfo\/isValid","role":"symbol","url":"\/documentation\/gfpsdk\/gfpqoetrackinginfo\/isvalid","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"isValid"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"isValid","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPQoeTrackingInfo/viewerInfo":{"type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"viewerInfo","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPQoeTrackingInfo\/viewerInfo","title":"viewerInfo","url":"\/documentation\/gfpsdk\/gfpqoetrackinginfo\/viewerinfo","navigatorTitle":[{"text":"viewerInfo","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/SQ":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","value":"GFPQoeTrackingInfo","path":"\/metadata\/title"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GFPQoeTrackingInfo"}],"op":"replace"},{"value":[{"text":"GFPQoeTrackingInfo","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPQoeTrackingInfo\/appId","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPQoeTrackingInfo\/isValid","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPQoeTrackingInfo\/ownerServiceId","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPQoeTrackingInfo\/serviceId","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPQoeTrackingInfo\/timeTable","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPQoeTrackingInfo\/urlString","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPQoeTrackingInfo\/viewerInfo"],"generated":true},{"title":"Type Methods","generated":true,"anchor":"Type-Methods","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPQoeTrackingInfo\/createQoeTrackingInfo(host:path:timeTable:serviceId:ownerServiceId:appId:viewerInfo:)"]}],"path":"\/topicSections"},{"path":"\/relationshipsSections","value":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject"],"title":"Inherits From"}],"op":"replace"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"GFPQoeTrackingInfo","kind":"identifier"},{"kind":"text","text":" : "},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}]}]}},{"value":"urlString","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPQoeTrackingInfo~1urlString\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPQoeTrackingInfo~1urlString\/fragments","value":[{"kind":"identifier","text":"urlString"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPQoeTrackingInfo~1ownerServiceId\/title","value":"ownerServiceId","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPQoeTrackingInfo~1ownerServiceId\/fragments","value":[{"text":"ownerServiceId","kind":"identifier"}]},{"value":"appId","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPQoeTrackingInfo~1appId\/title","op":"replace"},{"value":[{"text":"appId","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPQoeTrackingInfo~1appId\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPQoeTrackingInfo~1timeTable\/title","op":"replace","value":"timeTable"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPQoeTrackingInfo~1timeTable\/fragments","value":[{"kind":"identifier","text":"timeTable"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPQoeTrackingInfo~1serviceId\/title","value":"serviceId"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPQoeTrackingInfo~1serviceId\/fragments","value":[{"text":"serviceId","kind":"identifier"}],"op":"replace"},{"value":"createQoeTrackingInfoWith:path:timeTable:serviceId:ownerServiceId:appId:viewerInfo:","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPQoeTrackingInfo~1createQoeTrackingInfo(host:path:timeTable:serviceId:ownerServiceId:appId:viewerInfo:)\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPQoeTrackingInfo~1createQoeTrackingInfo(host:path:timeTable:serviceId:ownerServiceId:appId:viewerInfo:)\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"createQoeTrackingInfoWith:path:timeTable:serviceId:ownerServiceId:appId:viewerInfo:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPQoeTrackingInfo\/title","value":"GFPQoeTrackingInfo"},{"value":[{"text":"GFPQoeTrackingInfo","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPQoeTrackingInfo\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPQoeTrackingInfo\/navigatorTitle","op":"replace","value":[{"text":"GFPQoeTrackingInfo","kind":"identifier"}]},{"value":"isValid","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPQoeTrackingInfo~1isValid\/title"},{"op":"replace","value":[{"text":"isValid","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPQoeTrackingInfo~1isValid\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPQoeTrackingInfo~1viewerInfo\/title","op":"replace","value":"viewerInfo"},{"value":[{"text":"viewerInfo","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPQoeTrackingInfo~1viewerInfo\/fragments","op":"replace"}]}]}