{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"GFPRenderDisplayAgentType","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfprenderdisplayagenttype"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfprenderdisplayagenttype"]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"kind":"symbol","topicSections":[{"title":"Initializers","generated":true,"anchor":"Initializers","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRenderDisplayAgentType\/init(rawValue:)"]},{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRenderDisplayAgentType\/displayAgentTypeInApp","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRenderDisplayAgentType\/displayAgentTypeNativeSafari","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRenderDisplayAgentType\/displayAgentTypeScheme"],"anchor":"Type-Properties","title":"Type Properties","generated":true},{"title":"Default Implementations","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRenderDisplayAgentType\/Equatable-Implementations","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRenderDisplayAgentType\/OptionSet-Implementations","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRenderDisplayAgentType\/SetAlgebra-Implementations"],"anchor":"Default-Implementations","generated":true}],"relationshipsSections":[{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/s15BitwiseCopyableP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s25ExpressibleByArrayLiteralP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s9OptionSetP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SY","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s8SendableP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s10SetAlgebraP"],"type":"conformsTo"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRenderDisplayAgentType"},"metadata":{"modules":[{"name":"GFPSDK"}],"role":"symbol","title":"GFPRenderDisplayAgentType","externalID":"c:@E@GFPRenderDisplayAgentType","roleHeading":"Structure","symbolKind":"struct","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPRenderDisplayAgentType","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"GFPRenderDisplayAgentType"}]},"references":{"doc://com.navercorp.da.gfp.GFPSDK/s9OptionSetP":{"title":"Swift.OptionSet","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s9OptionSetP","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRenderDisplayAgentType/displayAgentTypeNativeSafari":{"abstract":[],"url":"\/documentation\/gfpsdk\/gfprenderdisplayagenttype\/displayagenttypenativesafari","role":"symbol","title":"displayAgentTypeNativeSafari","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRenderDisplayAgentType\/displayAgentTypeNativeSafari","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GFPDisplayAgentTypeNativeSafari"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"displayAgentTypeNativeSafari"},{"kind":"text","text":": "},{"text":"GFPRenderDisplayAgentType","kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPRenderDisplayAgentType"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRenderDisplayAgentType/SetAlgebra-Implementations":{"role":"collectionGroup","abstract":[],"kind":"article","type":"topic","title":"SetAlgebra Implementations","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRenderDisplayAgentType\/SetAlgebra-Implementations","url":"\/documentation\/gfpsdk\/gfprenderdisplayagenttype\/setalgebra-implementations"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRenderDisplayAgentType/displayAgentTypeScheme":{"abstract":[],"kind":"symbol","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"displayAgentTypeScheme","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"GFPRenderDisplayAgentType","preciseIdentifier":"c:@E@GFPRenderDisplayAgentType"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRenderDisplayAgentType\/displayAgentTypeScheme","title":"displayAgentTypeScheme","url":"\/documentation\/gfpsdk\/gfprenderdisplayagenttype\/displayagenttypescheme","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GFPDisplayAgentTypeScheme"}]},"doc://com.navercorp.da.gfp.GFPSDK/s10SetAlgebraP":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s10SetAlgebraP","title":"Swift.SetAlgebra","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/SY":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/s8SendableP":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s8SendableP","title":"Swift.Sendable","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRenderDisplayAgentType/displayAgentTypeInApp":{"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"displayAgentTypeInApp","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"GFPRenderDisplayAgentType","preciseIdentifier":"c:@E@GFPRenderDisplayAgentType"}],"navigatorTitle":[{"text":"GFPDisplayAgentTypeInApp","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfprenderdisplayagenttype\/displayagenttypeinapp","abstract":[],"kind":"symbol","role":"symbol","title":"displayAgentTypeInApp","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRenderDisplayAgentType\/displayAgentTypeInApp","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRenderDisplayAgentType/init(rawValue:)":{"url":"\/documentation\/gfpsdk\/gfprenderdisplayagenttype\/init(rawvalue:)","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"title":"init(rawValue:)","abstract":[],"type":"topic","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRenderDisplayAgentType\/init(rawValue:)"},"doc://com.navercorp.da.gfp.GFPSDK/s25ExpressibleByArrayLiteralP":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s25ExpressibleByArrayLiteralP","title":"Swift.ExpressibleByArrayLiteral","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/s15BitwiseCopyableP":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s15BitwiseCopyableP","title":"Swift.BitwiseCopyable","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRenderDisplayAgentType/Equatable-Implementations":{"kind":"article","title":"Equatable Implementations","abstract":[],"role":"collectionGroup","url":"\/documentation\/gfpsdk\/gfprenderdisplayagenttype\/equatable-implementations","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRenderDisplayAgentType\/Equatable-Implementations"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRenderDisplayAgentType/OptionSet-Implementations":{"kind":"article","abstract":[],"title":"OptionSet Implementations","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRenderDisplayAgentType\/OptionSet-Implementations","role":"collectionGroup","url":"\/documentation\/gfpsdk\/gfprenderdisplayagenttype\/optionset-implementations","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/SQ":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRenderDisplayAgentType":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPRenderDisplayAgentType","kind":"identifier"}],"kind":"symbol","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRenderDisplayAgentType","type":"topic","title":"GFPRenderDisplayAgentType","role":"symbol","url":"\/documentation\/gfpsdk\/gfprenderdisplayagenttype","navigatorTitle":[{"kind":"identifier","text":"GFPRenderDisplayAgentType"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"GFPRenderDisplayAgentType","path":"\/metadata\/title"},{"value":"enum","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GFPRenderDisplayAgentType"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"GFPRenderDisplayAgentType","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"generated":true,"title":"Enumeration Cases","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRenderDisplayAgentType\/displayAgentTypeInApp","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRenderDisplayAgentType\/displayAgentTypeNativeSafari","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRenderDisplayAgentType\/displayAgentTypeScheme"],"anchor":"Enumeration-Cases"}]},{"value":null,"op":"replace","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"GFPRenderDisplayAgentType","kind":"identifier"},{"kind":"text","text":": "},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0"},{"value":"GFPDisplayAgentTypeNativeSafari","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRenderDisplayAgentType~1displayAgentTypeNativeSafari\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRenderDisplayAgentType~1displayAgentTypeNativeSafari\/fragments","value":[{"kind":"identifier","text":"GFPDisplayAgentTypeNativeSafari"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRenderDisplayAgentType~1displayAgentTypeScheme\/title","value":"GFPDisplayAgentTypeScheme","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"GFPDisplayAgentTypeScheme"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRenderDisplayAgentType~1displayAgentTypeScheme\/fragments"},{"value":"GFPDisplayAgentTypeInApp","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRenderDisplayAgentType~1displayAgentTypeInApp\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRenderDisplayAgentType~1displayAgentTypeInApp\/fragments","value":[{"text":"GFPDisplayAgentTypeInApp","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"GFPRenderDisplayAgentType","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRenderDisplayAgentType\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRenderDisplayAgentType\/fragments","value":[{"text":"GFPRenderDisplayAgentType","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"GFPRenderDisplayAgentType"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRenderDisplayAgentType\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}