{"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardProviderFANErrorKey"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfprewardproviderfanerrorkey"]},{"paths":["\/documentation\/gfpsdk\/gfprewardproviderfanerrorkey"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPRewardProviderFANErrorKey","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","metadata":{"title":"GFPRewardProviderFANErrorKey","role":"symbol","externalID":"c:@GFPRewardProviderFANErrorKey","modules":[{"name":"GFPSDK"}],"navigatorTitle":[{"text":"GFPRewardProviderFANErrorKey","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"GFPRewardProviderFANErrorKey","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"roleHeading":"Global Variable","symbolKind":"var"},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRewardProviderFANErrorKey":{"navigatorTitle":[{"kind":"identifier","text":"GFPRewardProviderFANErrorKey"}],"title":"GFPRewardProviderFANErrorKey","abstract":[],"role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardProviderFANErrorKey","type":"topic","url":"\/documentation\/gfpsdk\/gfprewardproviderfanerrorkey","kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPRewardProviderFANErrorKey","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Global Variable","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"GFPRewardProviderFANErrorKey"},{"op":"replace","value":"var","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"GFPRewardProviderFANErrorKey"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"kind":"identifier","text":"GFPRewardProviderFANErrorKey"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardProviderFANErrorKey\/title","value":"GFPRewardProviderFANErrorKey"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardProviderFANErrorKey\/fragments","op":"replace","value":[{"kind":"identifier","text":"GFPRewardProviderFANErrorKey"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}