{"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/gfpsdk\/gfprewardproviderdfperrorkey"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gfpsdk\/gfprewardproviderdfperrorkey"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"GFPRewardProviderDFPErrorKey","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPRewardProviderDFPErrorKey","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"roleHeading":"Global Variable","role":"symbol","externalID":"c:@GFPRewardProviderDFPErrorKey","symbolKind":"var","navigatorTitle":[{"kind":"identifier","text":"GFPRewardProviderDFPErrorKey"}],"modules":[{"name":"GFPSDK"}]},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardProviderDFPErrorKey","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPRewardProviderDFPErrorKey"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRewardProviderDFPErrorKey":{"type":"topic","abstract":[],"title":"GFPRewardProviderDFPErrorKey","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPRewardProviderDFPErrorKey","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"url":"\/documentation\/gfpsdk\/gfprewardproviderdfperrorkey","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardProviderDFPErrorKey","navigatorTitle":[{"text":"GFPRewardProviderDFPErrorKey","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Global Variable"},{"value":"GFPRewardProviderDFPErrorKey","path":"\/metadata\/title","op":"replace"},{"value":"var","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"GFPRewardProviderDFPErrorKey"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" * "},{"text":"GFPRewardProviderDFPErrorKey","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardProviderDFPErrorKey\/title","value":"GFPRewardProviderDFPErrorKey","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardProviderDFPErrorKey\/fragments","value":[{"text":"GFPRewardProviderDFPErrorKey","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}