{"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject"],"type":"inheritsFrom"},{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s7CVarArgP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s23CustomStringConvertibleP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH"]}],"topicSections":[{"generated":true,"title":"Initializers","anchor":"Initializers","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRichMediaData\/init(adType:videoRatioType:mediaSize:)"]},{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRichMediaData\/adType","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRichMediaData\/extendMediaAspectRatioType","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRichMediaData\/extendMediaSize"],"anchor":"Instance-Properties"},{"title":"Type Methods","generated":true,"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRichMediaData\/create(adType:mediaSize:)"],"anchor":"Type-Methods"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfprichmediadata"]},{"paths":["\/documentation\/gfpsdk\/gfprichmediadata"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPRichMediaData"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRichMediaData"},"kind":"symbol","metadata":{"modules":[{"name":"GFPSDK"}],"role":"symbol","title":"GFPRichMediaData","externalID":"c:@M@GFPSDK@objc(cs)GFPRichMediaData","roleHeading":"Class","symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPRichMediaData","kind":"identifier"}],"navigatorTitle":[{"text":"GFPRichMediaData","kind":"identifier"}]},"sections":[],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRichMediaData/create(adType:mediaSize:)":{"url":"\/documentation\/gfpsdk\/gfprichmediadata\/create(adtype:mediasize:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"create"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"adType"},{"kind":"text","text":": "},{"text":"GFPRichMediaDataAdType","kind":"typeIdentifier","preciseIdentifier":"c:@M@GFPSDK@E@GFPRichMediaDataAdType"},{"text":", ","kind":"text"},{"text":"mediaSize","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize","text":"CGSize"},{"kind":"text","text":") -> "},{"text":"GFPRichMediaData","preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPRichMediaData","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"createWithAdType:mediaSize:","kind":"identifier"}],"title":"create(adType:mediaSize:)","role":"symbol","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRichMediaData\/create(adType:mediaSize:)"},"doc://com.navercorp.da.gfp.GFPSDK/SQ":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRichMediaData":{"url":"\/documentation\/gfpsdk\/gfprichmediadata","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPRichMediaData","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRichMediaData","navigatorTitle":[{"text":"GFPRichMediaData","kind":"identifier"}],"abstract":[],"kind":"symbol","title":"GFPRichMediaData","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRichMediaData/init(adType:videoRatioType:mediaSize:)":{"role":"symbol","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRichMediaData\/init(adType:videoRatioType:mediaSize:)","abstract":[],"kind":"symbol","url":"\/documentation\/gfpsdk\/gfprichmediadata\/init(adtype:videoratiotype:mediasize:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"adType","kind":"externalParam"},{"kind":"text","text":": "},{"text":"GFPRichMediaDataAdType","preciseIdentifier":"c:@M@GFPSDK@E@GFPRichMediaDataAdType","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"videoRatioType","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:GFPNativeDetailInfo.h@T@GFPRichExtendMediaRatioType","text":"GFPRichExtendMediaRatioType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mediaSize"},{"kind":"text","text":": "},{"text":"CGSize","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"initWithAdType:videoRatioType:mediaSize:"}],"title":"init(adType:videoRatioType:mediaSize:)"},"doc://com.navercorp.da.gfp.GFPSDK/s7CVarArgP":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRichMediaData/extendMediaAspectRatioType":{"role":"symbol","title":"extendMediaAspectRatioType","navigatorTitle":[{"text":"extendMediaAspectRatioType","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRichMediaData\/extendMediaAspectRatioType","type":"topic","abstract":[],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"extendMediaAspectRatioType","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:GFPNativeDetailInfo.h@T@GFPRichExtendMediaRatioType","text":"GFPRichExtendMediaRatioType","kind":"typeIdentifier"}],"url":"\/documentation\/gfpsdk\/gfprichmediadata\/extendmediaaspectratiotype"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRichMediaData/extendMediaSize":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRichMediaData\/extendMediaSize","title":"extendMediaSize","role":"symbol","url":"\/documentation\/gfpsdk\/gfprichmediadata\/extendmediasize","kind":"symbol","navigatorTitle":[{"text":"extendMediaSize","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"extendMediaSize","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier","text":"CGSize"}],"abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/objc(cs)NSObject":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://com.navercorp.da.gfp.GFPSDK/SH":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)NSObject":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.navercorp.da.gfp.GFPSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRichMediaData/adType":{"navigatorTitle":[{"text":"adType","kind":"identifier"}],"title":"adType","url":"\/documentation\/gfpsdk\/gfprichmediadata\/adtype","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRichMediaData\/adType","role":"symbol","type":"topic","kind":"symbol","abstract":[],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"adType"},{"text":": ","kind":"text"},{"text":"GFPRichMediaDataAdType","kind":"typeIdentifier","preciseIdentifier":"c:@M@GFPSDK@E@GFPRichMediaDataAdType"}]},"doc://com.navercorp.da.gfp.GFPSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"value":"GFPRichMediaData","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"value":[{"text":"GFPRichMediaData","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"GFPRichMediaData"}]},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRichMediaData\/adType","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRichMediaData\/extendMediaAspectRatioType","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRichMediaData\/extendMediaSize"],"title":"Instance Properties","anchor":"Instance-Properties","generated":true},{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRichMediaData\/init(adType:videoRatioType:mediaSize:)"],"anchor":"Instance-Methods"},{"generated":true,"title":"Type Methods","anchor":"Type-Methods","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRichMediaData\/create(adType:mediaSize:)"]}]},{"path":"\/relationshipsSections","value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject"],"type":"inheritsFrom"}],"op":"replace"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPRichMediaData"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRichMediaData~1create(adType:mediaSize:)\/title","value":"createWithAdType:mediaSize:"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRichMediaData~1create(adType:mediaSize:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"createWithAdType:mediaSize:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRichMediaData\/title","value":"GFPRichMediaData","op":"replace"},{"op":"replace","value":[{"text":"GFPRichMediaData","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRichMediaData\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRichMediaData\/navigatorTitle","value":[{"kind":"identifier","text":"GFPRichMediaData"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRichMediaData~1init(adType:videoRatioType:mediaSize:)\/title","op":"replace","value":"initWithAdType:videoRatioType:mediaSize:"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithAdType:videoRatioType:mediaSize:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRichMediaData~1init(adType:videoRatioType:mediaSize:)\/fragments","op":"replace"},{"value":"extendMediaAspectRatioType","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRichMediaData~1extendMediaAspectRatioType\/title"},{"value":[{"text":"extendMediaAspectRatioType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRichMediaData~1extendMediaAspectRatioType\/fragments"},{"op":"replace","value":"extendMediaSize","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRichMediaData~1extendMediaSize\/title"},{"op":"replace","value":[{"kind":"identifier","text":"extendMediaSize"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRichMediaData~1extendMediaSize\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRichMediaData~1adType\/title","value":"adType","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRichMediaData~1adType\/fragments","op":"replace","value":[{"kind":"identifier","text":"adType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}