{"metadata":{"role":"symbol","modules":[{"name":"GFPSDK"}],"externalID":"c:@GFPRewardProviderAPSErrorKey","symbolKind":"var","title":"GFPRewardProviderAPSErrorKey","navigatorTitle":[{"kind":"identifier","text":"GFPRewardProviderAPSErrorKey"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPRewardProviderAPSErrorKey"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"roleHeading":"Global Variable"},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardProviderAPSErrorKey"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"GFPRewardProviderAPSErrorKey","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/gfpsdk\/gfprewardproviderapserrorkey"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfprewardproviderapserrorkey"]}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRewardProviderAPSErrorKey":{"url":"\/documentation\/gfpsdk\/gfprewardproviderapserrorkey","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardProviderAPSErrorKey","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPRewardProviderAPSErrorKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"title":"GFPRewardProviderAPSErrorKey","abstract":[],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GFPRewardProviderAPSErrorKey"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Global Variable","path":"\/metadata\/roleHeading","op":"replace"},{"value":"GFPRewardProviderAPSErrorKey","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"var","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"GFPRewardProviderAPSErrorKey","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"extern","kind":"keyword"},{"kind":"text","text":" "},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"GFPRewardProviderAPSErrorKey"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"value":"GFPRewardProviderAPSErrorKey","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardProviderAPSErrorKey\/title","op":"replace"},{"value":[{"kind":"identifier","text":"GFPRewardProviderAPSErrorKey"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardProviderAPSErrorKey\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}