{"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"metadata":{"externalID":"c:@E@GFPRequestType","modules":[{"name":"GFPSDK"}],"symbolKind":"struct","navigatorTitle":[{"kind":"identifier","text":"GFPRequestType"}],"roleHeading":"Structure","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPRequestType","kind":"identifier"}],"title":"GFPRequestType"},"topicSections":[{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRequestType\/init(rawValue:)"],"generated":true,"title":"Initializers","anchor":"Initializers"},{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRequestType\/URL","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRequestType\/nelo","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRequestType\/schedule","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRequestType\/skadnRegister","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRequestType\/waterfall"],"anchor":"Type-Properties","generated":true,"title":"Type Properties"},{"generated":true,"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRequestType\/Equatable-Implementations","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRequestType\/OptionSet-Implementations","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRequestType\/SetAlgebra-Implementations"],"title":"Default Implementations","anchor":"Default-Implementations"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPRequestType"}],"languages":["swift"]}]}],"relationshipsSections":[{"title":"Conforms To","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/s15BitwiseCopyableP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s25ExpressibleByArrayLiteralP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s9OptionSetP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SY","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s8SendableP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s10SetAlgebraP"],"type":"conformsTo","kind":"relationships"}],"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRequestType"},"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/gfpsdk\/gfprequesttype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gfpsdk\/gfprequesttype"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRequestType/GFPRequestInitializer":{"fragments":[{"text":"GFPRequestInitializer","kind":"identifier"}],"role":"symbol","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRequestType\/GFPRequestInitializer","url":"\/documentation\/gfpsdk\/gfprequesttype\/gfprequestinitializer","type":"topic","title":"GFPRequestInitializer"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRequestType/OptionSet-Implementations":{"type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRequestType\/OptionSet-Implementations","abstract":[],"kind":"article","title":"OptionSet Implementations","url":"\/documentation\/gfpsdk\/gfprequesttype\/optionset-implementations","role":"collectionGroup"},"doc://com.navercorp.da.gfp.GFPSDK/SY":{"title":"Swift.RawRepresentable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SY","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/s10SetAlgebraP":{"title":"Swift.SetAlgebra","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s10SetAlgebraP","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRequestType/SetAlgebra-Implementations":{"role":"collectionGroup","abstract":[],"kind":"article","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRequestType\/SetAlgebra-Implementations","url":"\/documentation\/gfpsdk\/gfprequesttype\/setalgebra-implementations","type":"topic","title":"SetAlgebra Implementations"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRequestType/schedule":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"schedule"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@GFPRequestType","kind":"typeIdentifier","text":"GFPRequestType"}],"type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRequestType\/schedule","abstract":[],"navigatorTitle":[{"text":"GFPRequestSchedule","kind":"identifier"}],"kind":"symbol","title":"schedule","url":"\/documentation\/gfpsdk\/gfprequesttype\/schedule","role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRequestType/Equatable-Implementations":{"role":"collectionGroup","abstract":[],"kind":"article","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRequestType\/Equatable-Implementations","url":"\/documentation\/gfpsdk\/gfprequesttype\/equatable-implementations","type":"topic","title":"Equatable Implementations"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRequestType":{"abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRequestType","type":"topic","title":"GFPRequestType","navigatorTitle":[{"text":"GFPRequestType","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/gfpsdk\/gfprequesttype","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPRequestType"}]},"doc://com.navercorp.da.gfp.GFPSDK/s8SendableP":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s8SendableP","title":"Swift.Sendable","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/s9OptionSetP":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s9OptionSetP","title":"Swift.OptionSet","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/s15BitwiseCopyableP":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s15BitwiseCopyableP","title":"Swift.BitwiseCopyable","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRequestType/waterfall":{"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"waterfall","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@GFPRequestType","text":"GFPRequestType","kind":"typeIdentifier"}],"role":"symbol","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRequestType\/waterfall","kind":"symbol","type":"topic","url":"\/documentation\/gfpsdk\/gfprequesttype\/waterfall","title":"waterfall","navigatorTitle":[{"text":"GFPRequestWaterfall","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRequestType/URL":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRequestType\/URL","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"URL"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@GFPRequestType","kind":"typeIdentifier","text":"GFPRequestType"}],"navigatorTitle":[{"text":"GFPRequestURL","kind":"identifier"}],"abstract":[],"kind":"symbol","url":"\/documentation\/gfpsdk\/gfprequesttype\/url","type":"topic","title":"URL"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRequestType/skadnRegister":{"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"skadnRegister","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@GFPRequestType","text":"GFPRequestType","kind":"typeIdentifier"}],"role":"symbol","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRequestType\/skadnRegister","kind":"symbol","type":"topic","url":"\/documentation\/gfpsdk\/gfprequesttype\/skadnregister","title":"skadnRegister","navigatorTitle":[{"text":"GFPRequestSKADNRegister","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRequestType/init(rawValue:)":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRequestType\/init(rawValue:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":")","kind":"text"}],"abstract":[],"kind":"symbol","url":"\/documentation\/gfpsdk\/gfprequesttype\/init(rawvalue:)","type":"topic","title":"init(rawValue:)"},"doc://com.navercorp.da.gfp.GFPSDK/s25ExpressibleByArrayLiteralP":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s25ExpressibleByArrayLiteralP","type":"unresolvable","title":"Swift.ExpressibleByArrayLiteral"},"doc://com.navercorp.da.gfp.GFPSDK/SQ":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRequestType/nelo":{"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"nelo","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@GFPRequestType","kind":"typeIdentifier","text":"GFPRequestType"}],"role":"symbol","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRequestType\/nelo","kind":"symbol","type":"topic","url":"\/documentation\/gfpsdk\/gfprequesttype\/nelo","title":"nelo","navigatorTitle":[{"text":"GFPRequestNelo","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration"},{"value":"GFPRequestType","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"enum","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"GFPRequestType","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","value":[{"text":"GFPRequestType","kind":"identifier"}],"op":"replace"},{"value":[{"generated":true,"title":"Enumeration Cases","anchor":"Enumeration-Cases","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRequestType\/GFPRequestInitializer","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRequestType\/URL","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRequestType\/nelo","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRequestType\/schedule","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRequestType\/skadnRegister","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRequestType\/waterfall"]}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPRequestType"},{"text":": ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","value":"GFPRequestSchedule","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRequestType~1schedule\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRequestType~1schedule\/fragments","op":"replace","value":[{"text":"GFPRequestSchedule","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRequestType\/title","value":"GFPRequestType"},{"op":"replace","value":[{"text":"GFPRequestType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRequestType\/fragments"},{"op":"replace","value":[{"text":"GFPRequestType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRequestType\/navigatorTitle"},{"value":"GFPRequestWaterfall","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRequestType~1waterfall\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRequestType~1waterfall\/fragments","value":[{"text":"GFPRequestWaterfall","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRequestType~1URL\/title","value":"GFPRequestURL"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRequestType~1URL\/fragments","op":"replace","value":[{"text":"GFPRequestURL","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRequestType~1skadnRegister\/title","op":"replace","value":"GFPRequestSKADNRegister"},{"value":[{"text":"GFPRequestSKADNRegister","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRequestType~1skadnRegister\/fragments"},{"op":"replace","value":"GFPRequestNelo","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRequestType~1nelo\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRequestType~1nelo\/fragments","value":[{"text":"GFPRequestNelo","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}