{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfprenderdisplayagent"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfprenderdisplayagent"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRenderDisplayAgent"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"GFPRenderDisplayAgent","kind":"identifier"}]}]}],"sections":[],"metadata":{"symbolKind":"class","externalID":"c:objc(cs)GFPRenderDisplayAgent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"GFPRenderDisplayAgent","kind":"identifier"}],"roleHeading":"Class","title":"GFPRenderDisplayAgent","navigatorTitle":[{"text":"GFPRenderDisplayAgent","kind":"identifier"}],"role":"symbol","modules":[{"name":"GFPSDK"}]},"kind":"symbol","topicSections":[{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRenderDisplayAgent\/init(type:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRenderDisplayAgent\/init(type:scheme:)"],"anchor":"Initializers","generated":true,"title":"Initializers"},{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRenderDisplayAgent\/scheme","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRenderDisplayAgent\/shouldEncoding","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRenderDisplayAgent\/type","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRenderDisplayAgent\/typeRawValue"],"anchor":"Instance-Properties","generated":true,"title":"Instance Properties"},{"anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRenderDisplayAgent\/landingURL(with:)"],"title":"Instance Methods"}],"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject"]},{"kind":"relationships","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s7CVarArgP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s23CustomStringConvertibleP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH"],"type":"conformsTo","title":"Conforms To"}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRenderDisplayAgent/scheme":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRenderDisplayAgent\/scheme","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"scheme","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"abstract":[],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"scheme"}],"url":"\/documentation\/gfpsdk\/gfprenderdisplayagent\/scheme","deprecated":true,"title":"scheme","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRenderDisplayAgent":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPRenderDisplayAgent"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPRenderDisplayAgent"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRenderDisplayAgent","abstract":[],"role":"symbol","url":"\/documentation\/gfpsdk\/gfprenderdisplayagent","title":"GFPRenderDisplayAgent","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject","title":"NSObject"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRenderDisplayAgent/init(type:scheme:)":{"abstract":[],"type":"topic","title":"init(type:scheme:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"type"},{"text":": ","kind":"text"},{"text":"GFPRenderDisplayAgentType","kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPRenderDisplayAgentType"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"scheme"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":")"}],"deprecated":true,"url":"\/documentation\/gfpsdk\/gfprenderdisplayagent\/init(type:scheme:)","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRenderDisplayAgent\/init(type:scheme:)","navigatorTitle":[{"text":"initWithType:scheme:","kind":"identifier"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRenderDisplayAgent/shouldEncoding":{"title":"shouldEncoding","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRenderDisplayAgent\/shouldEncoding","role":"symbol","kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"shouldEncoding","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"kind":"identifier","text":"shouldEncoding"}],"type":"topic","url":"\/documentation\/gfpsdk\/gfprenderdisplayagent\/shouldencoding"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRenderDisplayAgent/type":{"abstract":[],"url":"\/documentation\/gfpsdk\/gfprenderdisplayagent\/type","role":"symbol","title":"type","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRenderDisplayAgent\/type","navigatorTitle":[{"kind":"identifier","text":"type"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"type"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@GFPRenderDisplayAgentType","kind":"typeIdentifier","text":"GFPRenderDisplayAgentType"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/SQ":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRenderDisplayAgent/typeRawValue":{"abstract":[],"url":"\/documentation\/gfpsdk\/gfprenderdisplayagent\/typerawvalue","role":"symbol","title":"typeRawValue","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRenderDisplayAgent\/typeRawValue","navigatorTitle":[{"kind":"identifier","text":"typeRawValue"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"typeRawValue"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRenderDisplayAgent/init(type:)":{"navigatorTitle":[{"text":"initWithType:","kind":"identifier"}],"type":"topic","title":"init(type:)","kind":"symbol","url":"\/documentation\/gfpsdk\/gfprenderdisplayagent\/init(type:)","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRenderDisplayAgent\/init(type:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"type"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@GFPRenderDisplayAgentType","kind":"typeIdentifier","text":"GFPRenderDisplayAgentType"},{"kind":"text","text":")"}],"role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRenderDisplayAgent/landingURL(with:)":{"abstract":[],"url":"\/documentation\/gfpsdk\/gfprenderdisplayagent\/landingurl(with:)","role":"symbol","title":"landingURL(with:)","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRenderDisplayAgent\/landingURL(with:)","navigatorTitle":[{"text":"landingURLWith:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"landingURL","kind":"identifier"},{"kind":"text","text":"("},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"text":"?","kind":"text"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH"},"doc://com.navercorp.da.gfp.GFPSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s23CustomStringConvertibleP"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"GFPRenderDisplayAgent","op":"replace"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"GFPRenderDisplayAgent"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"GFPRenderDisplayAgent","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRenderDisplayAgent\/scheme","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRenderDisplayAgent\/shouldEncoding","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRenderDisplayAgent\/type","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRenderDisplayAgent\/typeRawValue"]},{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRenderDisplayAgent\/init(type:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRenderDisplayAgent\/init(type:scheme:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRenderDisplayAgent\/landingURL(with:)"],"anchor":"Instance-Methods"}]},{"value":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From"}],"op":"replace","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPRenderDisplayAgent"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRenderDisplayAgent~1scheme\/title","op":"replace","value":"scheme"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRenderDisplayAgent~1scheme\/fragments","op":"replace","value":[{"kind":"identifier","text":"scheme"}]},{"value":"GFPRenderDisplayAgent","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRenderDisplayAgent\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRenderDisplayAgent\/fragments","value":[{"kind":"identifier","text":"GFPRenderDisplayAgent"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRenderDisplayAgent\/navigatorTitle","value":[{"kind":"identifier","text":"GFPRenderDisplayAgent"}],"op":"replace"},{"value":"initWithType:scheme:","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRenderDisplayAgent~1init(type:scheme:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithType:scheme:"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRenderDisplayAgent~1init(type:scheme:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRenderDisplayAgent~1shouldEncoding\/title","value":"shouldEncoding"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRenderDisplayAgent~1shouldEncoding\/fragments","value":[{"text":"shouldEncoding","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRenderDisplayAgent~1type\/title","value":"type","op":"replace"},{"value":[{"text":"type","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRenderDisplayAgent~1type\/fragments","op":"replace"},{"value":"typeRawValue","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRenderDisplayAgent~1typeRawValue\/title"},{"value":[{"text":"typeRawValue","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRenderDisplayAgent~1typeRawValue\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRenderDisplayAgent~1init(type:)\/title","value":"initWithType:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"initWithType:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRenderDisplayAgent~1init(type:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRenderDisplayAgent~1landingURL(with:)\/title","value":"landingURLWith:"},{"value":[{"text":"- ","kind":"text"},{"text":"landingURLWith:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRenderDisplayAgent~1landingURL(with:)\/fragments","op":"replace"}]}]}