{"topicSections":[{"title":"Initializers","generated":true,"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRichExtendMediaRatioType\/init(rawValue:)"],"anchor":"Initializers"},{"title":"Default Implementations","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRichExtendMediaRatioType\/Equatable-Implementations","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRichExtendMediaRatioType\/_SwiftNewtypeWrapper-Implementations"],"anchor":"Default-Implementations","generated":true}],"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPRichExtendMediaRatioType","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPRichExtendMediaRatioType"}],"symbolKind":"struct","navigatorTitle":[{"text":"GFPRichExtendMediaRatioType","kind":"identifier"}],"role":"symbol","modules":[{"name":"GFPSDK"}],"title":"GFPRichExtendMediaRatioType","externalID":"c:GFPNativeDetailInfo.h@T@GFPRichExtendMediaRatioType","roleHeading":"Structure"},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"relationshipsSections":[{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SY","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s8SendableP"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfprichextendmediaratiotype"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfprichextendmediaratiotype"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRichExtendMediaRatioType"},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRichExtendMediaRatioType/_SwiftNewtypeWrapper-Implementations":{"title":"_SwiftNewtypeWrapper Implementations","type":"topic","role":"collectionGroup","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRichExtendMediaRatioType\/_SwiftNewtypeWrapper-Implementations","url":"\/documentation\/gfpsdk\/gfprichextendmediaratiotype\/_swiftnewtypewrapper-implementations","abstract":[],"kind":"article"},"doc://com.navercorp.da.gfp.GFPSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH"},"doc://com.navercorp.da.gfp.GFPSDK/s8SendableP":{"title":"Swift.Sendable","type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s8SendableP"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRichExtendMediaRatioType/Equatable-Implementations":{"type":"topic","url":"\/documentation\/gfpsdk\/gfprichextendmediaratiotype\/equatable-implementations","abstract":[],"role":"collectionGroup","title":"Equatable Implementations","kind":"article","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRichExtendMediaRatioType\/Equatable-Implementations"},"doc://com.navercorp.da.gfp.GFPSDK/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SY"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRichExtendMediaRatioType":{"type":"topic","url":"\/documentation\/gfpsdk\/gfprichextendmediaratiotype","abstract":[],"navigatorTitle":[{"text":"GFPRichExtendMediaRatioType","kind":"identifier"}],"role":"symbol","title":"GFPRichExtendMediaRatioType","kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRichExtendMediaRatioType","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"GFPRichExtendMediaRatioType","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRichExtendMediaRatioType/init(rawValue:)":{"kind":"symbol","title":"init(rawValue:)","url":"\/documentation\/gfpsdk\/gfprichextendmediaratiotype\/init(rawvalue:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRichExtendMediaRatioType\/init(rawValue:)","type":"topic","abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Alias"},{"path":"\/metadata\/title","value":"GFPRichExtendMediaRatioType","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"typealias"},{"op":"replace","value":[{"kind":"identifier","text":"GFPRichExtendMediaRatioType"}],"path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"GFPRichExtendMediaRatioType"}]},{"path":"\/topicSections","value":null,"op":"replace"},{"value":null,"op":"replace","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"typedef","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"kind":"identifier","text":"GFPRichExtendMediaRatioType"},{"kind":"text","text":";"}]}]},"op":"replace"},{"op":"replace","value":"GFPRichExtendMediaRatioType","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRichExtendMediaRatioType\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRichExtendMediaRatioType\/fragments","value":[{"text":"GFPRichExtendMediaRatioType","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"GFPRichExtendMediaRatioType"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRichExtendMediaRatioType\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}