{"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/gfpsdk\/gfprewardedaddelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gfpsdk\/gfprewardedaddelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"kind":"symbol","topicSections":[{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdDelegate\/rewardedAd(_:didChangedMute:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdDelegate\/rewardedAd(_:didCompleteWith:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdDelegate\/rewardedAd(_:didFaileWithError:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdDelegate\/rewardedAdClosed(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdDelegate\/rewardedAdDidDismissDefault(inAppBrowser:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdDelegate\/rewardedAdDidPresentDefault(inAppBrowser:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdDelegate\/rewardedAdRecieveImpression(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdDelegate\/rewardedAdStarted(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdDelegate\/rewardedAdWasClicked(_:)"],"anchor":"Instance-Methods","generated":true,"title":"Instance Methods"}],"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject"],"kind":"relationships"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"GFPRewardedAdDelegate","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject","text":"NSObjectProtocol"}]}]}],"metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"GFPRewardedAdDelegate","kind":"identifier"}],"externalID":"c:objc(pl)GFPRewardedAdDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","title":"GFPRewardedAdDelegate","modules":[{"name":"GFPSDK"}],"navigatorTitle":[{"kind":"identifier","text":"GFPRewardedAdDelegate"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdDelegate"},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRewardedAdDelegate/rewardedAdStarted(_:)":{"type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdDelegate\/rewardedAdStarted(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"rewardedAdStarted","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPRewardedAd","text":"GFPRewardedAd"},{"text":"!)","kind":"text"}],"abstract":[],"url":"\/documentation\/gfpsdk\/gfprewardedaddelegate\/rewardedadstarted(_:)","title":"rewardedAdStarted(_:)","kind":"symbol","required":true,"navigatorTitle":[{"text":"rewardedAdStarted:","kind":"identifier"}],"role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRewardedAdDelegate/rewardedAdWasClicked(_:)":{"required":true,"url":"\/documentation\/gfpsdk\/gfprewardedaddelegate\/rewardedadwasclicked(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rewardedAdWasClicked"},{"kind":"text","text":"("},{"text":"GFPRewardedAd","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPRewardedAd"},{"text":"!)","kind":"text"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdDelegate\/rewardedAdWasClicked(_:)","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"rewardedAdWasClicked:"}],"title":"rewardedAdWasClicked(_:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRewardedAdDelegate/rewardedAd(_:didChangedMute:)":{"required":true,"url":"\/documentation\/gfpsdk\/gfprewardedaddelegate\/rewardedad(_:didchangedmute:)","kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdDelegate\/rewardedAd(_:didChangedMute:)","title":"rewardedAd(_:didChangedMute:)","role":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rewardedAd"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPRewardedAd","text":"GFPRewardedAd"},{"text":"!, ","kind":"text"},{"text":"didChangedMute","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"rewardedAd:didChangedMute:","kind":"identifier"}],"abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRewardedAdDelegate/rewardedAdDidPresentDefault(inAppBrowser:)":{"url":"\/documentation\/gfpsdk\/gfprewardedaddelegate\/rewardedaddidpresentdefault(inappbrowser:)","title":"rewardedAdDidPresentDefault(inAppBrowser:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"rewardedAdDidPresentDefault","kind":"identifier"},{"text":"(","kind":"text"},{"text":"inAppBrowser","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPRewardedAd","text":"GFPRewardedAd"},{"kind":"text","text":"!)"}],"navigatorTitle":[{"kind":"identifier","text":"rewardedAdDidPresentDefaultInAppBrowser:"}],"abstract":[],"kind":"symbol","type":"topic","required":true,"role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdDelegate\/rewardedAdDidPresentDefault(inAppBrowser:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRewardedAdDelegate/rewardedAd(_:didFaileWithError:)":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rewardedAd"},{"text":"(","kind":"text"},{"text":"GFPRewardedAd","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPRewardedAd"},{"kind":"text","text":"!, "},{"text":"didFaileWithError","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"GFPError","preciseIdentifier":"c:@M@NaverAdsServices@objc(cs)GFPError"},{"kind":"text","text":"!)"}],"type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdDelegate\/rewardedAd(_:didFaileWithError:)","title":"rewardedAd(_:didFaileWithError:)","abstract":[],"kind":"symbol","required":true,"navigatorTitle":[{"kind":"identifier","text":"rewardedAd:didFaileWithError:"}],"url":"\/documentation\/gfpsdk\/gfprewardedaddelegate\/rewardedad(_:didfailewitherror:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRewardedAdDelegate/rewardedAdClosed(_:)":{"navigatorTitle":[{"kind":"identifier","text":"rewardedAdClosed:"}],"url":"\/documentation\/gfpsdk\/gfprewardedaddelegate\/rewardedadclosed(_:)","title":"rewardedAdClosed(_:)","required":true,"role":"symbol","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdDelegate\/rewardedAdClosed(_:)","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rewardedAdClosed"},{"text":"(","kind":"text"},{"text":"GFPRewardedAd","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPRewardedAd"},{"kind":"text","text":"!)"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRewardedAdDelegate":{"kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"GFPRewardedAdDelegate","kind":"identifier"}],"title":"GFPRewardedAdDelegate","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdDelegate","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPRewardedAdDelegate"}],"url":"\/documentation\/gfpsdk\/gfprewardedaddelegate"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRewardedAdDelegate/rewardedAdDidDismissDefault(inAppBrowser:)":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"rewardedAdDidDismissDefault","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"inAppBrowser"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPRewardedAd","text":"GFPRewardedAd"},{"text":"!)","kind":"text"}],"type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdDelegate\/rewardedAdDidDismissDefault(inAppBrowser:)","title":"rewardedAdDidDismissDefault(inAppBrowser:)","abstract":[],"kind":"symbol","required":true,"navigatorTitle":[{"kind":"identifier","text":"rewardedAdDidDismissDefaultInAppBrowser:"}],"url":"\/documentation\/gfpsdk\/gfprewardedaddelegate\/rewardedaddiddismissdefault(inappbrowser:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRewardedAdDelegate/rewardedAd(_:didCompleteWith:)":{"required":true,"url":"\/documentation\/gfpsdk\/gfprewardedaddelegate\/rewardedad(_:didcompletewith:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"rewardedAd","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GFPRewardedAd","preciseIdentifier":"c:objc(cs)GFPRewardedAd"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"didCompleteWith"},{"kind":"text","text":": "},{"text":"GFPReward","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPReward"},{"kind":"text","text":"!)"}],"type":"topic","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdDelegate\/rewardedAd(_:didCompleteWith:)","role":"symbol","navigatorTitle":[{"text":"rewardedAd:didCompleteWithReward:","kind":"identifier"}],"title":"rewardedAd(_:didCompleteWith:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRewardedAdDelegate/rewardedAdRecieveImpression(_:)":{"abstract":[],"url":"\/documentation\/gfpsdk\/gfprewardedaddelegate\/rewardedadrecieveimpression(_:)","title":"rewardedAdRecieveImpression(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"rewardedAdRecieveImpression","kind":"identifier"},{"text":"(","kind":"text"},{"text":"GFPRewardedAd","preciseIdentifier":"c:objc(cs)GFPRewardedAd","kind":"typeIdentifier"},{"kind":"text","text":"!)"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"rewardedAdRecieveImpression:"}],"kind":"symbol","required":true,"type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdDelegate\/rewardedAdRecieveImpression(_:)"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Protocol","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"GFPRewardedAdDelegate"},{"path":"\/metadata\/symbolKind","op":"replace","value":"protocol"},{"value":[{"text":"GFPRewardedAdDelegate","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"GFPRewardedAdDelegate","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","value":[{"generated":true,"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdDelegate\/rewardedAd(_:didChangedMute:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdDelegate\/rewardedAd(_:didCompleteWith:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdDelegate\/rewardedAd(_:didFaileWithError:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdDelegate\/rewardedAdClosed(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdDelegate\/rewardedAdDidDismissDefault(inAppBrowser:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdDelegate\/rewardedAdDidPresentDefault(inAppBrowser:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdDelegate\/rewardedAdRecieveImpression(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdDelegate\/rewardedAdStarted(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdDelegate\/rewardedAdWasClicked(_:)"]}],"op":"replace"},{"op":"replace","value":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject"]}],"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPRewardedAdDelegate","kind":"identifier"},{"kind":"text","text":" <"},{"preciseIdentifier":"c:objc(pl)NSObject","text":"NSObject","kind":"typeIdentifier"},{"kind":"text","text":">"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdDelegate~1rewardedAdStarted(_:)\/title","op":"replace","value":"rewardedAdStarted:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"rewardedAdStarted:"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdDelegate~1rewardedAdStarted(_:)\/fragments"},{"value":"rewardedAdWasClicked:","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdDelegate~1rewardedAdWasClicked(_:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdDelegate~1rewardedAdWasClicked(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"rewardedAdWasClicked:"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdDelegate~1rewardedAd(_:didChangedMute:)\/title","value":"rewardedAd:didChangedMute:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdDelegate~1rewardedAd(_:didChangedMute:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"rewardedAd:didChangedMute:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdDelegate~1rewardedAdDidPresentDefault(inAppBrowser:)\/title","value":"rewardedAdDidPresentDefaultInAppBrowser:"},{"value":[{"text":"- ","kind":"text"},{"text":"rewardedAdDidPresentDefaultInAppBrowser:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdDelegate~1rewardedAdDidPresentDefault(inAppBrowser:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdDelegate~1rewardedAd(_:didFaileWithError:)\/title","value":"rewardedAd:didFaileWithError:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"rewardedAd:didFaileWithError:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdDelegate~1rewardedAd(_:didFaileWithError:)\/fragments"},{"value":"rewardedAdClosed:","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdDelegate~1rewardedAdClosed(_:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdDelegate~1rewardedAdClosed(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"rewardedAdClosed:","kind":"identifier"}]},{"value":"GFPRewardedAdDelegate","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdDelegate\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdDelegate\/fragments","value":[{"text":"GFPRewardedAdDelegate","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdDelegate\/navigatorTitle","value":[{"text":"GFPRewardedAdDelegate","kind":"identifier"}]},{"value":"rewardedAdDidDismissDefaultInAppBrowser:","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdDelegate~1rewardedAdDidDismissDefault(inAppBrowser:)\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdDelegate~1rewardedAdDidDismissDefault(inAppBrowser:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"rewardedAdDidDismissDefaultInAppBrowser:","kind":"identifier"}],"op":"replace"},{"value":"rewardedAd:didCompleteWithReward:","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdDelegate~1rewardedAd(_:didCompleteWith:)\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdDelegate~1rewardedAd(_:didCompleteWith:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rewardedAd:didCompleteWithReward:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdDelegate~1rewardedAdRecieveImpression(_:)\/title","op":"replace","value":"rewardedAdRecieveImpression:"},{"value":[{"text":"- ","kind":"text"},{"text":"rewardedAdRecieveImpression:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdDelegate~1rewardedAdRecieveImpression(_:)\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}