{"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRichExtendMediaRatioType9_16","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"variants":[{"paths":["\/documentation\/gfpsdk\/gfprichextendmediaratiotype9_16"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfprichextendmediaratiotype9_16"]}],"metadata":{"title":"GFPRichExtendMediaRatioType9_16","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPRichExtendMediaRatioType9_16","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"role":"symbol","roleHeading":"Global Variable","symbolKind":"var","modules":[{"name":"GFPSDK"}],"navigatorTitle":[{"kind":"identifier","text":"GFPRichExtendMediaRatioType9_16"}],"externalID":"c:@GFPRichExtendMediaRatioType9_16"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPRichExtendMediaRatioType9_16","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"languages":["swift"]}]}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRichExtendMediaRatioType9_16":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"GFPRichExtendMediaRatioType9_16","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"title":"GFPRichExtendMediaRatioType9_16","abstract":[],"navigatorTitle":[{"text":"GFPRichExtendMediaRatioType9_16","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRichExtendMediaRatioType9_16","role":"symbol","url":"\/documentation\/gfpsdk\/gfprichextendmediaratiotype9_16","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Global Variable","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"GFPRichExtendMediaRatioType9_16"},{"op":"replace","value":"var","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GFPRichExtendMediaRatioType9_16"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"extern"},{"text":" ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"text":"GFPRichExtendMediaRatioType9_16","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"GFPRichExtendMediaRatioType9_16","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRichExtendMediaRatioType9_16\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRichExtendMediaRatioType9_16\/fragments","value":[{"kind":"identifier","text":"GFPRichExtendMediaRatioType9_16"}],"op":"replace"}]}]}