{"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPResponseInfoPresentable","interfaceLanguage":"swift"},"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject"],"title":"Inherits From","type":"inheritsFrom"},{"kind":"relationships","title":"Conforming Types","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerMediator","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediator","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUnifiedMediator","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoMediator"],"type":"conformingTypes"}],"kind":"symbol","topicSections":[{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPResponseInfoPresentable\/responseInfo"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"GFPResponseInfoPresentable","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(pl)NSObject","text":"NSObjectProtocol","kind":"typeIdentifier"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpresponseinfopresentable"]},{"paths":["\/documentation\/gfpsdk\/gfpresponseinfopresentable"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"GFPResponseInfoPresentable","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPResponseInfoPresentable","kind":"identifier"}],"roleHeading":"Protocol","role":"symbol","externalID":"c:objc(pl)GFPResponseInfoPresentable","symbolKind":"protocol","navigatorTitle":[{"text":"GFPResponseInfoPresentable","kind":"identifier"}],"modules":[{"name":"GFPSDK"}]},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerMediator":{"type":"topic","navigatorTitle":[{"text":"GFPBannerMediator","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/gfpsdk\/gfpbannermediator","role":"symbol","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPBannerMediator"}],"title":"GFPBannerMediator","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerMediator"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPUnifiedMediator":{"abstract":[],"type":"topic","title":"GFPUnifiedMediator","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPUnifiedMediator","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpunifiedmediator","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUnifiedMediator","navigatorTitle":[{"text":"GFPUnifiedMediator","kind":"identifier"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoMediator":{"title":"GFPVideoMediator","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoMediator","role":"symbol","kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPVideoMediator"}],"navigatorTitle":[{"kind":"identifier","text":"GFPVideoMediator"}],"type":"topic","url":"\/documentation\/gfpsdk\/gfpvideomediator"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPResponseInfoPresentable/responseInfo":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"responseInfo","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)GFPLoadResponseInfo","text":"GFPLoadResponseInfo","kind":"typeIdentifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"responseInfo"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPResponseInfoPresentable\/responseInfo","abstract":[],"role":"symbol","url":"\/documentation\/gfpsdk\/gfpresponseinfopresentable\/responseinfo","title":"responseInfo","required":true,"type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPMediator":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediator","title":"GFPMediator","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPMediator"}],"url":"\/documentation\/gfpsdk\/gfpmediator","type":"topic","abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPMediator"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPResponseInfoPresentable":{"kind":"symbol","title":"GFPResponseInfoPresentable","url":"\/documentation\/gfpsdk\/gfpresponseinfopresentable","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPResponseInfoPresentable"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPResponseInfoPresentable","type":"topic","navigatorTitle":[{"text":"GFPResponseInfoPresentable","kind":"identifier"}],"abstract":[]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Protocol","op":"replace"},{"path":"\/metadata\/title","value":"GFPResponseInfoPresentable","op":"replace"},{"path":"\/metadata\/symbolKind","value":"protocol","op":"replace"},{"value":[{"text":"GFPResponseInfoPresentable","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"GFPResponseInfoPresentable","kind":"identifier"}]},{"value":[{"title":"Instance Properties","anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPResponseInfoPresentable\/responseInfo"]}],"op":"replace","path":"\/topicSections"},{"op":"replace","value":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject"]},{"type":"conformingTypes","title":"Conforming Types","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediator"],"kind":"relationships"}],"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"text":" ","kind":"text"},{"text":"GFPResponseInfoPresentable","kind":"identifier"},{"kind":"text","text":" <"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"},{"kind":"text","text":">"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerMediator\/title","value":"GFPBannerMediator"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerMediator\/fragments","value":[{"text":"GFPBannerMediator","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerMediator\/navigatorTitle","op":"replace","value":[{"text":"GFPBannerMediator","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPUnifiedMediator\/title","op":"replace","value":"GFPUnifiedMediator"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPUnifiedMediator\/fragments","value":[{"kind":"identifier","text":"GFPUnifiedMediator"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPUnifiedMediator\/navigatorTitle","value":[{"kind":"identifier","text":"GFPUnifiedMediator"}],"op":"replace"},{"value":"GFPVideoMediator","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoMediator\/title"},{"value":[{"text":"GFPVideoMediator","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoMediator\/fragments"},{"value":[{"kind":"identifier","text":"GFPVideoMediator"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoMediator\/navigatorTitle"},{"value":"responseInfo","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPResponseInfoPresentable~1responseInfo\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"responseInfo"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPResponseInfoPresentable~1responseInfo\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMediator\/title","value":"GFPMediator"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMediator\/fragments","value":[{"kind":"identifier","text":"GFPMediator"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMediator\/navigatorTitle","op":"replace","value":[{"text":"GFPMediator","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPResponseInfoPresentable\/title","value":"GFPResponseInfoPresentable"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPResponseInfoPresentable\/fragments","value":[{"text":"GFPResponseInfoPresentable","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPResponseInfoPresentable\/navigatorTitle","op":"replace","value":[{"text":"GFPResponseInfoPresentable","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}