{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfps2sadlandinghandler-1jl2l"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfps2sadlandinghandler-1jl2l"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"GFPS2SAdLandingHandler","kind":"identifier"},{"kind":"text","text":" = ("},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"title":"GFPS2SAdLandingHandler","roleHeading":"Type Alias","role":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"GFPS2SAdLandingHandler","kind":"identifier"}],"navigatorTitle":[{"text":"GFPS2SAdLandingHandler","kind":"identifier"}],"symbolKind":"typealias","modules":[{"name":"GFPSDK"}],"externalID":"c:GFPS2SAdClickDelegate.h@T@GFPS2SAdLandingHandler"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPS2SAdLandingHandler-1jl2l"},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"sections":[],"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPS2SAdLandingHandler-1jl2l":{"abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPS2SAdLandingHandler-1jl2l","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPS2SAdLandingHandler","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"GFPS2SAdLandingHandler"}],"url":"\/documentation\/gfpsdk\/gfps2sadlandinghandler-1jl2l","type":"topic","title":"GFPS2SAdLandingHandler","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Type Alias","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"GFPS2SAdLandingHandler"},{"op":"replace","path":"\/metadata\/symbolKind","value":"typealias"},{"op":"replace","value":[{"kind":"identifier","text":"GFPS2SAdLandingHandler"}],"path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"GFPS2SAdLandingHandler"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"typedef","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","text":"void (^)(_Bool)","preciseIdentifier":"c:BFv(#b)"},{"text":" ","kind":"text"},{"text":"GFPS2SAdLandingHandler","kind":"identifier"},{"kind":"text","text":";"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPS2SAdLandingHandler-1jl2l\/title","value":"GFPS2SAdLandingHandler"},{"op":"replace","value":[{"text":"GFPS2SAdLandingHandler","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPS2SAdLandingHandler-1jl2l\/fragments"},{"value":[{"text":"GFPS2SAdLandingHandler","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPS2SAdLandingHandler-1jl2l\/navigatorTitle"}]}]}