{"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"sections":[],"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject"]},{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s7CVarArgP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s23CustomStringConvertibleP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH"],"kind":"relationships"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpspannableoption"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpspannableoption"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objcMembers","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPSpannableOption"}],"platforms":["iOS"],"languages":["swift"]}]}],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPSpannableOption\/init(textColor:startPos:endPos:isBold:)"],"anchor":"Initializers","generated":true},{"anchor":"Instance-Properties","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPSpannableOption\/endPos","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPSpannableOption\/isBold","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPSpannableOption\/startPos","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPSpannableOption\/textColor"],"generated":true,"title":"Instance Properties"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPSpannableOption"},"metadata":{"role":"symbol","externalID":"c:@M@GFPSDK@objc(cs)GFPSpannableOption","modules":[{"name":"GFPSDK"}],"symbolKind":"class","title":"GFPSpannableOption","roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPSpannableOption","kind":"identifier"}],"navigatorTitle":[{"text":"GFPSpannableOption","kind":"identifier"}]},"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPSpannableOption/init(textColor:startPos:endPos:isBold:)":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPSpannableOption\/init(textColor:startPos:endPos:isBold:)","role":"symbol","url":"\/documentation\/gfpsdk\/gfpspannableoption\/init(textcolor:startpos:endpos:isbold:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"textColor"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"},{"text":"?, ","kind":"text"},{"text":"startPos","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"endPos","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"text":"isBold","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"initWithTextColor:startPos:endPos:isBold:"}],"abstract":[],"kind":"symbol","type":"topic","title":"init(textColor:startPos:endPos:isBold:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPSpannableOption/textColor":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"textColor","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"?"}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"textColor"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPSpannableOption\/textColor","title":"textColor","kind":"symbol","abstract":[{"text":"변경 Text Color","type":"text"}],"url":"\/documentation\/gfpsdk\/gfpspannableoption\/textcolor"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPSpannableOption":{"title":"GFPSpannableOption","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPSpannableOption","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"GFPSpannableOption","kind":"identifier"}],"type":"topic","url":"\/documentation\/gfpsdk\/gfpspannableoption","kind":"symbol","navigatorTitle":[{"text":"GFPSpannableOption","kind":"identifier"}],"role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.navercorp.da.gfp.GFPSDK/SH":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPSpannableOption/startPos":{"title":"startPos","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"startPos","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"abstract":[{"type":"text","text":"강조 Text 시작 위치 - 시작 Position은 1입니다."}],"kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPSpannableOption\/startPos","role":"symbol","url":"\/documentation\/gfpsdk\/gfpspannableoption\/startpos","type":"topic","navigatorTitle":[{"text":"startPos","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPSpannableOption/endPos":{"type":"topic","abstract":[{"type":"text","text":"강조 Text 끝 위치"}],"title":"endPos","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"endPos","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"url":"\/documentation\/gfpsdk\/gfpspannableoption\/endpos","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPSpannableOption\/endPos","navigatorTitle":[{"text":"endPos","kind":"identifier"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPSpannableOption/isBold":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPSpannableOption\/isBold","role":"symbol","url":"\/documentation\/gfpsdk\/gfpspannableoption\/isbold","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"isBold","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"kind":"identifier","text":"isBold"}],"abstract":[{"type":"text","text":"볼드 여부"}],"kind":"symbol","type":"topic","title":"isBold"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.navercorp.da.gfp.GFPSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","title":"Swift.Equatable"},"doc://com.navercorp.da.gfp.GFPSDK/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject","title":"NSObject"},"doc://com.navercorp.da.gfp.GFPSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.navercorp.da.gfp.GFPSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"GFPSpannableOption","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"value":[{"text":"GFPSpannableOption","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"GFPSpannableOption","kind":"identifier"}]},{"op":"replace","value":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPSpannableOption\/endPos","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPSpannableOption\/isBold","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPSpannableOption\/startPos","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPSpannableOption\/textColor"],"generated":true,"title":"Instance Properties"},{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPSpannableOption\/init(textColor:startPos:endPos:isBold:)"],"anchor":"Instance-Methods"}],"path":"\/topicSections"},{"path":"\/relationshipsSections","value":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject"]}],"op":"replace"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPSpannableOption","kind":"identifier"},{"kind":"text","text":" : "},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPSpannableOption~1init(textColor:startPos:endPos:isBold:)\/title","value":"initWithTextColor:startPos:endPos:isBold:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithTextColor:startPos:endPos:isBold:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPSpannableOption~1init(textColor:startPos:endPos:isBold:)\/fragments","op":"replace"},{"value":"textColor","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPSpannableOption~1textColor\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPSpannableOption~1textColor\/fragments","value":[{"kind":"identifier","text":"textColor"}],"op":"replace"},{"value":"GFPSpannableOption","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPSpannableOption\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPSpannableOption\/fragments","value":[{"kind":"identifier","text":"GFPSpannableOption"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPSpannableOption\/navigatorTitle","op":"replace","value":[{"text":"GFPSpannableOption","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPSpannableOption~1startPos\/title","op":"replace","value":"startPos"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPSpannableOption~1startPos\/fragments","value":[{"text":"startPos","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPSpannableOption~1endPos\/title","op":"replace","value":"endPos"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPSpannableOption~1endPos\/fragments","op":"replace","value":[{"kind":"identifier","text":"endPos"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPSpannableOption~1isBold\/title","value":"isBold"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPSpannableOption~1isBold\/fragments","value":[{"kind":"identifier","text":"isBold"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}