{"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"GFPS2SAdClickDelegate","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"platforms":["iOS"]}]}],"topicSections":[{"anchor":"Instance-Methods","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPS2SAdClickDelegate\/openURLWith(_:landingHandler:)"],"generated":true,"title":"Instance Methods"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfps2sadclickdelegate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfps2sadclickdelegate"]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPS2SAdClickDelegate"},"kind":"symbol","metadata":{"title":"GFPS2SAdClickDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"GFPS2SAdClickDelegate","kind":"identifier"}],"roleHeading":"Protocol","role":"symbol","externalID":"c:@M@GFPSDK@objc(pl)GFPS2SAdClickDelegate","symbolKind":"protocol","navigatorTitle":[{"kind":"identifier","text":"GFPS2SAdClickDelegate"}],"modules":[{"name":"GFPSDK"}]},"relationshipsSections":[{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPS2SAdClickDelegate/openURLWith(_:landingHandler:)":{"type":"topic","abstract":[],"title":"openURLWith(_:landingHandler:)","role":"symbol","url":"\/documentation\/gfpsdk\/gfps2sadclickdelegate\/openurlwith(_:landinghandler:)","navigatorTitle":[{"text":"openURLWith:landingHandler:","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPS2SAdClickDelegate\/openURLWith(_:landingHandler:)","required":true,"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"openURLWith"},{"kind":"text","text":"("},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"landingHandler","kind":"externalParam"},{"kind":"text","text":": "},{"text":"GFPS2SAdLandingHandler","kind":"typeIdentifier","preciseIdentifier":"s:6GFPSDK22GFPS2SAdLandingHandlera"},{"kind":"text","text":")"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPS2SAdClickDelegate":{"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPS2SAdClickDelegate"}],"kind":"symbol","navigatorTitle":[{"text":"GFPS2SAdClickDelegate","kind":"identifier"}],"abstract":[],"title":"GFPS2SAdClickDelegate","role":"symbol","url":"\/documentation\/gfpsdk\/gfps2sadclickdelegate","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPS2SAdClickDelegate","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)NSObject":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","title":"NSObject","type":"unresolvable"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"path":"\/metadata\/title","value":"GFPS2SAdClickDelegate","op":"replace"},{"value":"protocol","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"GFPS2SAdClickDelegate","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"GFPS2SAdClickDelegate"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPS2SAdClickDelegate\/openURLWith(_:landingHandler:)"],"anchor":"Instance-Methods"}]},{"value":[{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"}],"op":"replace","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPS2SAdClickDelegate","kind":"identifier"},{"text":" <","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier"},{"text":">","kind":"text"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPS2SAdClickDelegate~1openURLWith(_:landingHandler:)\/title","value":"openURLWith:landingHandler:"},{"value":[{"text":"- ","kind":"text"},{"text":"openURLWith:landingHandler:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPS2SAdClickDelegate~1openURLWith(_:landingHandler:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPS2SAdClickDelegate\/title","value":"GFPS2SAdClickDelegate","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPS2SAdClickDelegate\/fragments","value":[{"kind":"identifier","text":"GFPS2SAdClickDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPS2SAdClickDelegate\/navigatorTitle","value":[{"text":"GFPS2SAdClickDelegate","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}