{"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject"]},{"type":"inheritedBy","kind":"relationships","title":"Inherited By","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRemindAd","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/Icon"]},{"title":"Conforms To","kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSCopying","doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s7CVarArgP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s23CustomStringConvertibleP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPTrackingPresentable"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPTrackingPresentable","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfptrackingpresentable"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfptrackingpresentable"]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"topicSections":[{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPTrackingPresentable\/trackingURLs"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"}],"kind":"symbol","sections":[],"metadata":{"externalID":"c:objc(cs)GFPTrackingPresentable","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"GFPTrackingPresentable","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"GFPTrackingPresentable"}],"modules":[{"name":"GFPSDK"}],"symbolKind":"class","role":"symbol","title":"GFPTrackingPresentable","roleHeading":"Class"},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPTrackingPresentable/trackingURLs":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPTrackingPresentable\/trackingURLs","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"trackingURLs","kind":"identifier"},{"kind":"text","text":": "},{"text":"GFPTrackingURLs","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPTrackingURLs"}],"url":"\/documentation\/gfpsdk\/gfptrackingpresentable\/trackingurls","title":"trackingURLs","navigatorTitle":[{"text":"trackingURLs","kind":"identifier"}],"abstract":[],"role":"symbol","type":"topic","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRemindAd":{"role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRemindAd","navigatorTitle":[{"text":"GFPRemindAd","kind":"identifier"}],"type":"topic","url":"\/documentation\/gfpsdk\/gfpremindad","title":"GFPRemindAd","abstract":[],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPRemindAd","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s23CustomStringConvertibleP"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s28CustomDebugStringConvertibleP"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPTrackingPresentable":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPTrackingPresentable","abstract":[],"role":"symbol","title":"GFPTrackingPresentable","kind":"symbol","url":"\/documentation\/gfpsdk\/gfptrackingpresentable","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPTrackingPresentable"}],"navigatorTitle":[{"text":"GFPTrackingPresentable","kind":"identifier"}],"type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/Icon":{"url":"\/documentation\/gfpsdk\/icon","title":"Icon","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/Icon","kind":"symbol","role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Icon","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"Icon"}],"abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)NSCopying":{"type":"unresolvable","title":"NSCopying","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSCopying"},"doc://com.navercorp.da.gfp.GFPSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH"},"doc://com.navercorp.da.gfp.GFPSDK/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject"},"doc://com.navercorp.da.gfp.GFPSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s7CVarArgP"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"GFPTrackingPresentable","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"value":[{"kind":"identifier","text":"GFPTrackingPresentable"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"text":"GFPTrackingPresentable","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"path":"\/topicSections","value":[{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPTrackingPresentable\/trackingURLs"],"anchor":"Instance-Properties"}],"op":"replace"},{"op":"replace","value":[{"kind":"relationships","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRemindAd","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/Icon"],"title":"Inherited By","kind":"relationships","type":"inheritedBy"},{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSCopying"]}],"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"GFPTrackingPresentable","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"trackingURLs","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPTrackingPresentable~1trackingURLs\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPTrackingPresentable~1trackingURLs\/fragments","op":"replace","value":[{"kind":"identifier","text":"trackingURLs"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRemindAd\/title","op":"replace","value":"GFPRemindAd"},{"value":[{"kind":"identifier","text":"GFPRemindAd"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRemindAd\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRemindAd\/navigatorTitle","value":[{"text":"GFPRemindAd","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPTrackingPresentable\/title","value":"GFPTrackingPresentable"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPTrackingPresentable\/fragments","op":"replace","value":[{"text":"GFPTrackingPresentable","kind":"identifier"}]},{"op":"replace","value":[{"text":"GFPTrackingPresentable","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPTrackingPresentable\/navigatorTitle"},{"value":"Icon","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1Icon\/title","op":"replace"},{"value":[{"kind":"identifier","text":"Icon"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1Icon\/fragments"},{"op":"replace","value":[{"text":"Icon","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1Icon\/navigatorTitle"}]}]}