{"metadata":{"title":"GFPUserInterestDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"GFPUserInterestDelegate","kind":"identifier"}],"modules":[{"name":"GFPSDK"}],"role":"symbol","externalID":"c:objc(pl)GFPUserInterestDelegate","roleHeading":"Protocol","symbolKind":"protocol","navigatorTitle":[{"text":"GFPUserInterestDelegate","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"topicSections":[{"anchor":"Instance-Methods","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUserInterestDelegate\/ad(_:didChangeUserInterest:)"],"generated":true,"title":"Instance Methods"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUserInterestDelegate"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPUserInterestDelegate"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpuserinterestdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gfpsdk\/gfpuserinterestdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject"],"title":"Inherits From","type":"inheritsFrom"}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPUserInterestDelegate/ad(_:didChangeUserInterest:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"ad","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"},{"text":"!, ","kind":"text"},{"text":"didChangeUserInterest","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"ad(_:didChangeUserInterest:)","navigatorTitle":[{"kind":"identifier","text":"ad:didChangeUserInterest:"}],"url":"\/documentation\/gfpsdk\/gfpuserinterestdelegate\/ad(_:didchangeuserinterest:)","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUserInterestDelegate\/ad(_:didChangeUserInterest:)","role":"symbol","type":"topic","kind":"symbol","abstract":[],"required":true},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPUserInterestDelegate":{"abstract":[],"url":"\/documentation\/gfpsdk\/gfpuserinterestdelegate","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUserInterestDelegate","role":"symbol","title":"GFPUserInterestDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"GFPUserInterestDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"GFPUserInterestDelegate","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Protocol","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"GFPUserInterestDelegate","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"protocol","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"GFPUserInterestDelegate","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"text":"GFPUserInterestDelegate","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUserInterestDelegate\/ad(_:didChangeUserInterest:)"],"anchor":"Instance-Methods"}],"path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject"],"type":"inheritsFrom","title":"Inherits From"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"text":" ","kind":"text"},{"text":"GFPUserInterestDelegate","kind":"identifier"},{"text":" <","kind":"text"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(pl)NSObject"},{"kind":"text","text":">"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPUserInterestDelegate~1ad(_:didChangeUserInterest:)\/title","value":"ad:didChangeUserInterest:"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPUserInterestDelegate~1ad(_:didChangeUserInterest:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"ad:didChangeUserInterest:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPUserInterestDelegate\/title","value":"GFPUserInterestDelegate"},{"op":"replace","value":[{"kind":"identifier","text":"GFPUserInterestDelegate"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPUserInterestDelegate\/fragments"},{"value":[{"text":"GFPUserInterestDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPUserInterestDelegate\/navigatorTitle"}]}]}