{"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpunifiedmediator"]},{"paths":["\/documentation\/gfpsdk\/gfpunifiedmediator"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediator"]},{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPResponseInfoPresentable","doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s7CVarArgP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s23CustomStringConvertibleP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH"],"kind":"relationships"}],"metadata":{"modules":[{"name":"GFPSDK"}],"externalID":"c:objc(cs)GFPUnifiedMediator","roleHeading":"Class","title":"GFPUnifiedMediator","role":"symbol","symbolKind":"class","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPUnifiedMediator"}],"navigatorTitle":[{"text":"GFPUnifiedMediator","kind":"identifier"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"topicSections":[{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUnifiedMediator\/delegate","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUnifiedMediator\/reportDelegate"],"anchor":"Instance-Properties"},{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUnifiedMediator\/loadAdaptor(withAdUnitID:bannerContext:nativeContext:adParam:timeoutInterval:)"],"anchor":"Instance-Methods"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPUnifiedMediator","kind":"identifier"}]}]}],"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUnifiedMediator","interfaceLanguage":"swift"},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPUnifiedMediator/reportDelegate":{"url":"\/documentation\/gfpsdk\/gfpunifiedmediator\/reportdelegate","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"reportDelegate"},{"text":": (any ","kind":"text"},{"text":"GFPEventReportDelegate","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)GFPEventReportDelegate"},{"text":")?","kind":"text"}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"reportDelegate","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUnifiedMediator\/reportDelegate","title":"reportDelegate"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPResponseInfoPresentable":{"kind":"symbol","title":"GFPResponseInfoPresentable","url":"\/documentation\/gfpsdk\/gfpresponseinfopresentable","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPResponseInfoPresentable"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPResponseInfoPresentable","type":"topic","navigatorTitle":[{"text":"GFPResponseInfoPresentable","kind":"identifier"}],"abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPUnifiedMediator/loadAdaptor(withAdUnitID:bannerContext:nativeContext:adParam:timeoutInterval:)":{"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"loadAdaptorWithAdUnitID:bannerContext:nativeContext:adParam:timeoutInterval:"}],"abstract":[],"title":"loadAdaptor(withAdUnitID:bannerContext:nativeContext:adParam:timeoutInterval:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"loadAdaptor","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withAdUnitID","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"bannerContext"},{"kind":"text","text":": "},{"text":"GFPBannerContext","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPBannerContext"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"nativeContext"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPNativeContext","text":"GFPNativeContext"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"adParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPAdParam","text":"GFPAdParam","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"timeoutInterval"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUnifiedMediator\/loadAdaptor(withAdUnitID:bannerContext:nativeContext:adParam:timeoutInterval:)","url":"\/documentation\/gfpsdk\/gfpunifiedmediator\/loadadaptor(withadunitid:bannercontext:nativecontext:adparam:timeoutinterval:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPUnifiedMediator":{"abstract":[],"type":"topic","title":"GFPUnifiedMediator","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPUnifiedMediator","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpunifiedmediator","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUnifiedMediator","navigatorTitle":[{"text":"GFPUnifiedMediator","kind":"identifier"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPMediator":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediator","title":"GFPMediator","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPMediator"}],"url":"\/documentation\/gfpsdk\/gfpmediator","type":"topic","abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPMediator"}]},"doc://com.navercorp.da.gfp.GFPSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH","title":"Swift.Hashable"},"doc://com.navercorp.da.gfp.GFPSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.navercorp.da.gfp.GFPSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","title":"Swift.Equatable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPUnifiedMediator/delegate":{"title":"delegate","role":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"kind":"text","text":": (any "},{"preciseIdentifier":"c:objc(pl)GFPUnifiedMediatorDelegate","text":"GFPUnifiedMediatorDelegate","kind":"typeIdentifier"},{"text":")?","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUnifiedMediator\/delegate","navigatorTitle":[{"text":"delegate","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpunifiedmediator\/delegate","abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","value":"GFPUnifiedMediator","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"GFPUnifiedMediator","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"GFPUnifiedMediator"}]},{"path":"\/topicSections","value":[{"title":"Instance Properties","generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUnifiedMediator\/delegate","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUnifiedMediator\/reportDelegate"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUnifiedMediator\/loadAdaptor(withAdUnitID:bannerContext:nativeContext:adParam:timeoutInterval:)"],"generated":true,"anchor":"Instance-Methods"}],"op":"replace"},{"path":"\/relationshipsSections","op":"replace","value":[{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediator"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"GFPUnifiedMediator","kind":"identifier"},{"kind":"text","text":" : "},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediator","kind":"typeIdentifier","text":"GFPMediator","preciseIdentifier":"c:objc(cs)GFPMediator"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPUnifiedMediator~1reportDelegate\/title","op":"replace","value":"reportDelegate"},{"value":[{"kind":"identifier","text":"reportDelegate"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPUnifiedMediator~1reportDelegate\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPResponseInfoPresentable\/title","value":"GFPResponseInfoPresentable"},{"op":"replace","value":[{"text":"GFPResponseInfoPresentable","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPResponseInfoPresentable\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPResponseInfoPresentable\/navigatorTitle","value":[{"text":"GFPResponseInfoPresentable","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPUnifiedMediator~1loadAdaptor(withAdUnitID:bannerContext:nativeContext:adParam:timeoutInterval:)\/title","value":"loadAdaptorWithAdUnitID:bannerContext:nativeContext:adParam:timeoutInterval:"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPUnifiedMediator~1loadAdaptor(withAdUnitID:bannerContext:nativeContext:adParam:timeoutInterval:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"loadAdaptorWithAdUnitID:bannerContext:nativeContext:adParam:timeoutInterval:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPUnifiedMediator\/title","value":"GFPUnifiedMediator"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPUnifiedMediator\/fragments","value":[{"text":"GFPUnifiedMediator","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPUnifiedMediator\/navigatorTitle","value":[{"kind":"identifier","text":"GFPUnifiedMediator"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMediator\/title","value":"GFPMediator","op":"replace"},{"value":[{"text":"GFPMediator","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMediator\/fragments"},{"value":[{"text":"GFPMediator","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMediator\/navigatorTitle"},{"value":"delegate","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPUnifiedMediator~1delegate\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPUnifiedMediator~1delegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"delegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}