{"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"sections":[],"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUnifiedMediatorDelegate\/unifiedMediator(_:didFailToLoadAdaptorWithError:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUnifiedMediatorDelegate\/unifiedMediator(_:didLoad:)-3koln","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUnifiedMediatorDelegate\/unifiedMediator(_:didLoad:)-5jg9a","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUnifiedMediatorDelegate\/unifiedMediator(_:didLoadBannerAdaptor:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUnifiedMediatorDelegate\/unifiedMediator(_:didReceivedWaterfallResponse:)"],"anchor":"Instance-Methods","generated":true}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"GFPUnifiedMediatorDelegate","kind":"identifier"},{"kind":"text","text":" : "},{"text":"NSObjectProtocol","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpunifiedmediatordelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gfpsdk\/gfpunifiedmediatordelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject"],"title":"Inherits From"}],"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUnifiedMediatorDelegate","interfaceLanguage":"swift"},"metadata":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPUnifiedMediatorDelegate","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"GFPUnifiedMediatorDelegate"}],"roleHeading":"Protocol","role":"symbol","externalID":"c:objc(pl)GFPUnifiedMediatorDelegate","modules":[{"name":"GFPSDK"}],"title":"GFPUnifiedMediatorDelegate","symbolKind":"protocol"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPUnifiedMediatorDelegate/unifiedMediator(_:didLoad:)-3koln":{"type":"topic","required":true,"navigatorTitle":[{"text":"unifiedMediator:didLoadNativeAd:","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/gfpsdk\/gfpunifiedmediatordelegate\/unifiedmediator(_:didload:)-3koln","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"unifiedMediator","kind":"identifier"},{"text":"(","kind":"text"},{"text":"GFPUnifiedMediator","preciseIdentifier":"c:objc(cs)GFPUnifiedMediator","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didLoad","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)GFPNativeAd","kind":"typeIdentifier","text":"GFPNativeAd"},{"text":")","kind":"text"}],"title":"unifiedMediator(_:didLoad:)","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUnifiedMediatorDelegate\/unifiedMediator(_:didLoad:)-3koln"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPUnifiedMediatorDelegate/unifiedMediator(_:didReceivedWaterfallResponse:)":{"required":true,"url":"\/documentation\/gfpsdk\/gfpunifiedmediatordelegate\/unifiedmediator(_:didreceivedwaterfallresponse:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"unifiedMediator"},{"text":"(","kind":"text"},{"text":"GFPUnifiedMediator","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPUnifiedMediator"},{"text":", ","kind":"text"},{"text":"didReceivedWaterfallResponse","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPWaterfallExtra","text":"GFPWaterfallExtra"},{"kind":"text","text":")"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUnifiedMediatorDelegate\/unifiedMediator(_:didReceivedWaterfallResponse:)","abstract":[],"role":"symbol","navigatorTitle":[{"text":"unifiedMediator:didReceivedWaterfallResponse:","kind":"identifier"}],"title":"unifiedMediator(_:didReceivedWaterfallResponse:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPUnifiedMediatorDelegate/unifiedMediator(_:didFailToLoadAdaptorWithError:)":{"type":"topic","required":true,"navigatorTitle":[{"text":"unifiedMediator:didFailToLoadAdaptorWithError:","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/gfpsdk\/gfpunifiedmediatordelegate\/unifiedmediator(_:didfailtoloadadaptorwitherror:)","role":"symbol","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"unifiedMediator"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPUnifiedMediator","text":"GFPUnifiedMediator","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didFailToLoadAdaptorWithError","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@NaverAdsServices@objc(cs)GFPError","kind":"typeIdentifier","text":"GFPError"},{"kind":"text","text":")"}],"title":"unifiedMediator(_:didFailToLoadAdaptorWithError:)","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUnifiedMediatorDelegate\/unifiedMediator(_:didFailToLoadAdaptorWithError:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPUnifiedMediatorDelegate/unifiedMediator(_:didLoad:)-5jg9a":{"required":true,"url":"\/documentation\/gfpsdk\/gfpunifiedmediatordelegate\/unifiedmediator(_:didload:)-5jg9a","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"unifiedMediator","kind":"identifier"},{"text":"(","kind":"text"},{"text":"GFPUnifiedMediator","preciseIdentifier":"c:objc(cs)GFPUnifiedMediator","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didLoad","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPNativeSimpleAd","text":"GFPNativeSimpleAd"},{"text":")","kind":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUnifiedMediatorDelegate\/unifiedMediator(_:didLoad:)-5jg9a","abstract":[],"role":"symbol","navigatorTitle":[{"text":"unifiedMediator:didLoadNativeSimpleAd:","kind":"identifier"}],"title":"unifiedMediator(_:didLoad:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPUnifiedMediatorDelegate/unifiedMediator(_:didLoadBannerAdaptor:)":{"type":"topic","required":true,"navigatorTitle":[{"text":"unifiedMediator:didLoadBannerAdaptor:","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/gfpsdk\/gfpunifiedmediatordelegate\/unifiedmediator(_:didloadbanneradaptor:)","role":"symbol","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unifiedMediator"},{"kind":"text","text":"("},{"text":"GFPUnifiedMediator","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPUnifiedMediator"},{"text":", ","kind":"text"},{"text":"didLoadBannerAdaptor","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"GFPAdAdaptor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdAdaptor"},{"kind":"text","text":" & "},{"preciseIdentifier":"c:objc(pl)GFPBannerAdapting","kind":"typeIdentifier","text":"GFPBannerAdapting"},{"kind":"text","text":")"}],"title":"unifiedMediator(_:didLoadBannerAdaptor:)","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUnifiedMediatorDelegate\/unifiedMediator(_:didLoadBannerAdaptor:)"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","title":"NSObject"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPUnifiedMediatorDelegate":{"type":"topic","navigatorTitle":[{"text":"GFPUnifiedMediatorDelegate","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/gfpsdk\/gfpunifiedmediatordelegate","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPUnifiedMediatorDelegate"}],"title":"GFPUnifiedMediatorDelegate","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUnifiedMediatorDelegate"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Protocol"},{"path":"\/metadata\/title","value":"GFPUnifiedMediatorDelegate","op":"replace"},{"value":"protocol","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"GFPUnifiedMediatorDelegate","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"GFPUnifiedMediatorDelegate","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUnifiedMediatorDelegate\/unifiedMediator(_:didFailToLoadAdaptorWithError:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUnifiedMediatorDelegate\/unifiedMediator(_:didLoad:)-3koln","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUnifiedMediatorDelegate\/unifiedMediator(_:didLoad:)-5jg9a","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUnifiedMediatorDelegate\/unifiedMediator(_:didLoadBannerAdaptor:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUnifiedMediatorDelegate\/unifiedMediator(_:didReceivedWaterfallResponse:)"],"generated":true,"anchor":"Instance-Methods","title":"Instance Methods"}]},{"path":"\/relationshipsSections","value":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject"],"title":"Inherits From"}],"op":"replace"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPUnifiedMediatorDelegate"},{"text":" <","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"},{"kind":"text","text":">"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPUnifiedMediatorDelegate~1unifiedMediator(_:didLoad:)-3koln\/title","value":"unifiedMediator:didLoadNativeAd:"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPUnifiedMediatorDelegate~1unifiedMediator(_:didLoad:)-3koln\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"unifiedMediator:didLoadNativeAd:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPUnifiedMediatorDelegate~1unifiedMediator(_:didReceivedWaterfallResponse:)\/title","value":"unifiedMediator:didReceivedWaterfallResponse:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"unifiedMediator:didReceivedWaterfallResponse:"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPUnifiedMediatorDelegate~1unifiedMediator(_:didReceivedWaterfallResponse:)\/fragments"},{"value":"unifiedMediator:didFailToLoadAdaptorWithError:","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPUnifiedMediatorDelegate~1unifiedMediator(_:didFailToLoadAdaptorWithError:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"unifiedMediator:didFailToLoadAdaptorWithError:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPUnifiedMediatorDelegate~1unifiedMediator(_:didFailToLoadAdaptorWithError:)\/fragments"},{"op":"replace","value":"unifiedMediator:didLoadNativeSimpleAd:","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPUnifiedMediatorDelegate~1unifiedMediator(_:didLoad:)-5jg9a\/title"},{"value":[{"kind":"text","text":"- "},{"text":"unifiedMediator:didLoadNativeSimpleAd:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPUnifiedMediatorDelegate~1unifiedMediator(_:didLoad:)-5jg9a\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPUnifiedMediatorDelegate~1unifiedMediator(_:didLoadBannerAdaptor:)\/title","value":"unifiedMediator:didLoadBannerAdaptor:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPUnifiedMediatorDelegate~1unifiedMediator(_:didLoadBannerAdaptor:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"unifiedMediator:didLoadBannerAdaptor:","kind":"identifier"}]},{"value":"GFPUnifiedMediatorDelegate","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPUnifiedMediatorDelegate\/title"},{"op":"replace","value":[{"kind":"identifier","text":"GFPUnifiedMediatorDelegate"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPUnifiedMediatorDelegate\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPUnifiedMediatorDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"GFPUnifiedMediatorDelegate"}]}]}]}