{"topicSections":[{"anchor":"Initializers","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdRenderingSetting\/init()"],"generated":true,"title":"Initializers"},{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdRenderingSetting\/bitrateKbps","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdRenderingSetting\/bufferingTimeoutInterval","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdRenderingSetting\/isPreferContentWidthUI","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdRenderingSetting\/mimeTypes","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdRenderingSetting\/startTimeoutInterval"]},{"generated":true,"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdRenderingSetting\/GFPVideoAdRenderingSettingAutodetectBitrate","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdRenderingSetting\/GFPVideoAdRenderingSettingDefaultBufferingTimeout","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdRenderingSetting\/GFPVideoAdRenderingSettingDefaultStartTimeout"],"anchor":"Type-Properties","title":"Type Properties"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objcMembers"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"GFPVideoAdRenderingSetting","kind":"identifier"}]}],"kind":"declarations"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"metadata":{"title":"GFPVideoAdRenderingSetting","symbolKind":"class","modules":[{"name":"GFPSDK"}],"role":"symbol","externalID":"c:@M@GFPSDK@objc(cs)GFPVideoAdRenderingSetting","roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"GFPVideoAdRenderingSetting","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"GFPVideoAdRenderingSetting"}]},"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject"],"type":"inheritsFrom"},{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s7CVarArgP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s23CustomStringConvertibleP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH"]}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpvideoadrenderingsetting"]},{"paths":["\/documentation\/gfpsdk\/gfpvideoadrenderingsetting"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdRenderingSetting","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://com.navercorp.da.gfp.GFPSDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdRenderingSetting":{"type":"topic","abstract":[],"kind":"symbol","navigatorTitle":[{"text":"GFPVideoAdRenderingSetting","kind":"identifier"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPVideoAdRenderingSetting"}],"title":"GFPVideoAdRenderingSetting","url":"\/documentation\/gfpsdk\/gfpvideoadrenderingsetting","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdRenderingSetting"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdRenderingSetting/bufferingTimeoutInterval":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdRenderingSetting\/bufferingTimeoutInterval","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bufferingTimeoutInterval"},{"kind":"text","text":": "},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"}],"navigatorTitle":[{"kind":"identifier","text":"bufferingTimeoutInterval"}],"type":"topic","role":"symbol","url":"\/documentation\/gfpsdk\/gfpvideoadrenderingsetting\/bufferingtimeoutinterval","title":"bufferingTimeoutInterval","kind":"symbol","abstract":[{"text":"재생도중 버퍼링이 발생한 경우, 설정된 시간을 초과하면 타임아웃 에러가 발생합니다. (기본값은 -1 이며, 이 경우 타임아웃이 적용되지 않습니다.)","type":"text"}]},"doc://com.navercorp.da.gfp.GFPSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s23CustomStringConvertibleP"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdRenderingSetting/init()":{"abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"init"}],"type":"topic","url":"\/documentation\/gfpsdk\/gfpvideoadrenderingsetting\/init()","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdRenderingSetting\/init()","title":"init()","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdRenderingSetting/isPreferContentWidthUI":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"isPreferContentWidthUI","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"kind":"identifier","text":"isPreferContentWidthUI"}],"type":"topic","url":"\/documentation\/gfpsdk\/gfpvideoadrenderingsetting\/isprefercontentwidthui","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdRenderingSetting\/isPreferContentWidthUI","abstract":[{"text":"광고 UI 컴포넌트를 그릴 때 기준을 설정합니다. (기본값은 false)","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"false: GFPVideoAdScheduleManager.videoView 혹은 GFPVideoAdmanager.videoView 의 너비에 따라 컴포넌트를 그림."},{"type":"text","text":" "},{"type":"text","text":"true: 광고 영상의 실제 width 에 따라 컴포넌트를 그림."}],"title":"isPreferContentWidthUI","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdRenderingSetting/GFPVideoAdRenderingSettingAutodetectBitrate":{"navigatorTitle":[{"text":"GFPVideoAdRenderingSettingAutodetectBitrate","kind":"identifier"}],"title":"GFPVideoAdRenderingSettingAutodetectBitrate","url":"\/documentation\/gfpsdk\/gfpvideoadrenderingsetting\/gfpvideoadrenderingsettingautodetectbitrate","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdRenderingSetting\/GFPVideoAdRenderingSettingAutodetectBitrate","role":"symbol","type":"topic","kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPVideoAdRenderingSettingAutodetectBitrate","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}]},"doc://com.navercorp.da.gfp.GFPSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s28CustomDebugStringConvertibleP"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdRenderingSetting/GFPVideoAdRenderingSettingDefaultBufferingTimeout":{"navigatorTitle":[{"text":"GFPVideoAdRenderingSettingDefaultBufferingTimeout","kind":"identifier"}],"title":"GFPVideoAdRenderingSettingDefaultBufferingTimeout","url":"\/documentation\/gfpsdk\/gfpvideoadrenderingsetting\/gfpvideoadrenderingsettingdefaultbufferingtimeout","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdRenderingSetting\/GFPVideoAdRenderingSettingDefaultBufferingTimeout","role":"symbol","type":"topic","kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPVideoAdRenderingSettingDefaultBufferingTimeout","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"}]},"doc://com.navercorp.da.gfp.GFPSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdRenderingSetting/startTimeoutInterval":{"navigatorTitle":[{"kind":"identifier","text":"startTimeoutInterval"}],"title":"startTimeoutInterval","url":"\/documentation\/gfpsdk\/gfpvideoadrenderingsetting\/starttimeoutinterval","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdRenderingSetting\/startTimeoutInterval","role":"symbol","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"광고 시작요청 이후 실제 시작 시점까지 타임아웃 (기본값은 -1 이며, 이 경우 타임아웃 8초가 적용 됩니다.)"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"startTimeoutInterval"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdRenderingSetting/mimeTypes":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mimeTypes","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"]?","kind":"text"}],"abstract":[{"text":"광고영상의 MIME type 목록","type":"text"},{"type":"text","text":" "},{"type":"text","text":"기본값(=nil or Empty)은, AVPlayer 에서 지원하는 모든 타입이 허용됩니다."},{"type":"text","text":" "},{"text":"명시한 MIME type에 해당하는 영상 URL이 서버로부터 제공되지 않으면, 광고로드시 Error 가 송출됩니다.","type":"text"}],"navigatorTitle":[{"text":"mimeTypes","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpvideoadrenderingsetting\/mimetypes","kind":"symbol","type":"topic","role":"symbol","title":"mimeTypes","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdRenderingSetting\/mimeTypes"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdRenderingSetting/bitrateKbps":{"role":"symbol","abstract":[{"text":"광고영상의 최대 bitrate (kbit\/sec)","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"입력값 보다 낮은 bitrate 광고영상 중 가장 높은 bitrate 영샹이 채택되며,"},{"text":" ","type":"text"},{"type":"text","text":"입력값 보다 낮은 bitrate 영상이 없는 경우 가장 가까운 bitrate 영샹이 재생됩니다."}],"title":"bitrateKbps","navigatorTitle":[{"text":"bitrateKbps","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bitrateKbps","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"url":"\/documentation\/gfpsdk\/gfpvideoadrenderingsetting\/bitratekbps","type":"topic","kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdRenderingSetting\/bitrateKbps"},"doc://com.navercorp.da.gfp.GFPSDK/SH":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)NSObject":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.navercorp.da.gfp.GFPSDK/objc(cs)NSObject":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdRenderingSetting/GFPVideoAdRenderingSettingDefaultStartTimeout":{"navigatorTitle":[{"kind":"identifier","text":"GFPVideoAdRenderingSettingDefaultStartTimeout"}],"type":"topic","title":"GFPVideoAdRenderingSettingDefaultStartTimeout","kind":"symbol","url":"\/documentation\/gfpsdk\/gfpvideoadrenderingsetting\/gfpvideoadrenderingsettingdefaultstarttimeout","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdRenderingSetting\/GFPVideoAdRenderingSettingDefaultStartTimeout","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPVideoAdRenderingSettingDefaultStartTimeout","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"TimeInterval"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"GFPVideoAdRenderingSetting"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"GFPVideoAdRenderingSetting"}]},{"path":"\/metadata\/navigatorTitle","value":[{"text":"GFPVideoAdRenderingSetting","kind":"identifier"}],"op":"replace"},{"value":[{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdRenderingSetting\/bitrateKbps","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdRenderingSetting\/bufferingTimeoutInterval","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdRenderingSetting\/isPreferContentWidthUI","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdRenderingSetting\/mimeTypes","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdRenderingSetting\/startTimeoutInterval"]},{"anchor":"Instance-Methods","title":"Instance Methods","generated":true,"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdRenderingSetting\/init()"]},{"anchor":"Type-Properties","generated":true,"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdRenderingSetting\/GFPVideoAdRenderingSettingAutodetectBitrate","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdRenderingSetting\/GFPVideoAdRenderingSettingDefaultBufferingTimeout","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdRenderingSetting\/GFPVideoAdRenderingSettingDefaultStartTimeout"],"title":"Type Properties"}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"replace","value":[{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"GFPVideoAdRenderingSetting","kind":"identifier"},{"kind":"text","text":" : "},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdRenderingSetting\/title","value":"GFPVideoAdRenderingSetting"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdRenderingSetting\/fragments","value":[{"text":"GFPVideoAdRenderingSetting","kind":"identifier"}],"op":"replace"},{"value":[{"text":"GFPVideoAdRenderingSetting","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdRenderingSetting\/navigatorTitle"},{"op":"replace","value":"bufferingTimeoutInterval","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdRenderingSetting~1bufferingTimeoutInterval\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdRenderingSetting~1bufferingTimeoutInterval\/fragments","value":[{"kind":"identifier","text":"bufferingTimeoutInterval"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdRenderingSetting~1init()\/title","value":"init","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdRenderingSetting~1init()\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdRenderingSetting~1isPreferContentWidthUI\/title","op":"replace","value":"isPreferContentWidthUI"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdRenderingSetting~1isPreferContentWidthUI\/fragments","value":[{"kind":"identifier","text":"isPreferContentWidthUI"}],"op":"replace"},{"value":"GFPVideoAdRenderingSettingAutodetectBitrate","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdRenderingSetting~1GFPVideoAdRenderingSettingAutodetectBitrate\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdRenderingSetting~1GFPVideoAdRenderingSettingAutodetectBitrate\/fragments","value":[{"kind":"identifier","text":"GFPVideoAdRenderingSettingAutodetectBitrate"}]},{"op":"replace","value":"GFPVideoAdRenderingSettingDefaultBufferingTimeout","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdRenderingSetting~1GFPVideoAdRenderingSettingDefaultBufferingTimeout\/title"},{"value":[{"kind":"identifier","text":"GFPVideoAdRenderingSettingDefaultBufferingTimeout"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdRenderingSetting~1GFPVideoAdRenderingSettingDefaultBufferingTimeout\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdRenderingSetting~1startTimeoutInterval\/title","value":"startTimeoutInterval"},{"op":"replace","value":[{"text":"startTimeoutInterval","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdRenderingSetting~1startTimeoutInterval\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdRenderingSetting~1mimeTypes\/title","value":"mimeTypes"},{"value":[{"kind":"identifier","text":"mimeTypes"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdRenderingSetting~1mimeTypes\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdRenderingSetting~1bitrateKbps\/title","value":"bitrateKbps","op":"replace"},{"value":[{"kind":"identifier","text":"bitrateKbps"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdRenderingSetting~1bitrateKbps\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdRenderingSetting~1GFPVideoAdRenderingSettingDefaultStartTimeout\/title","value":"GFPVideoAdRenderingSettingDefaultStartTimeout","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdRenderingSetting~1GFPVideoAdRenderingSettingDefaultStartTimeout\/fragments","value":[{"text":"GFPVideoAdRenderingSettingDefaultStartTimeout","kind":"identifier"}],"op":"replace"}]}]}