{"metadata":{"navigatorTitle":[{"text":"GFPVideoAdScheduleManager","kind":"identifier"}],"externalID":"c:objc(cs)GFPVideoAdScheduleManager","symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPVideoAdScheduleManager","kind":"identifier"}],"modules":[{"name":"GFPSDK"}],"roleHeading":"Class","role":"symbol","title":"GFPVideoAdScheduleManager"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpvideoadschedulemanager"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpvideoadschedulemanager"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject"],"type":"inheritsFrom"},{"type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s7CVarArgP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s23CustomStringConvertibleP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH"],"title":"Conforms To"}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"GFPVideoAdScheduleManager","kind":"identifier"}],"languages":["swift"]}]}],"topicSections":[{"generated":true,"title":"Initializers","anchor":"Initializers","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager\/init(adScheduleID:contentPlayer:videoView:scheduleParam:)"]},{"anchor":"Instance-Properties","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager\/adScheduleID","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager\/advertiseParams","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager\/contentPlayer","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager\/delegate","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager\/displayMode","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager\/nonLinearDelegate","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager\/pipDelegate","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager\/playBufferInterval","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager\/playerSetting","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager\/qoeDelegate","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager\/renderingSetting","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager\/rootViewController","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager\/scheduleParam","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager\/videoView","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager\/volume"],"generated":true,"title":"Instance Properties"},{"generated":true,"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager\/destroy()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager\/hideNonLinearAd()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager\/hideOverlayView()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager\/loadSchedule()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager\/moreButtonTapped(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager\/pause()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager\/replace(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager\/resume()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager\/showNonLinearAd()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager\/showNonLinearAd(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager\/showOverlayView()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager\/skipButtonTapped(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager\/start(with:)"]}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/objc(cs)NSObject":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdScheduleManager/showNonLinearAd(_:)":{"navigatorTitle":[{"text":"showNonLinearAd:","kind":"identifier"}],"type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"showNonLinearAd","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@E@GFPNonLinearContainerType","text":"GFPNonLinearContainerType","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"showNonLinearAd(_:)","url":"\/documentation\/gfpsdk\/gfpvideoadschedulemanager\/shownonlinearad(_:)","abstract":[{"text":"RemindAd(Banner, Text) 광고를 노출합니다.","type":"text"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager\/showNonLinearAd(_:)","role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdScheduleManager/nonLinearDelegate":{"type":"topic","abstract":[],"title":"nonLinearDelegate","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"nonLinearDelegate"},{"kind":"text","text":": (any "},{"text":"GFPNonLinearDelegate","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)GFPNonLinearDelegate"},{"text":")?","kind":"text"}],"url":"\/documentation\/gfpsdk\/gfpvideoadschedulemanager\/nonlineardelegate","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager\/nonLinearDelegate","navigatorTitle":[{"text":"nonLinearDelegate","kind":"identifier"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdScheduleManager/pause()":{"abstract":[],"url":"\/documentation\/gfpsdk\/gfpvideoadschedulemanager\/pause()","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"pause"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pause"},{"text":"()","kind":"text"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager\/pause()","kind":"symbol","title":"pause()","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdScheduleManager/videoView":{"role":"symbol","abstract":[],"title":"videoView","navigatorTitle":[{"text":"videoView","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"videoView","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager\/videoView","type":"topic","kind":"symbol","url":"\/documentation\/gfpsdk\/gfpvideoadschedulemanager\/videoview"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdScheduleManager/playerSetting":{"navigatorTitle":[{"text":"playerSetting","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpvideoadschedulemanager\/playersetting","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playerSetting","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPVideoAdPlayerSetting","text":"GFPVideoAdPlayerSetting"},{"text":"?","kind":"text"}],"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager\/playerSetting","title":"playerSetting"},"doc://com.navercorp.da.gfp.GFPSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdScheduleManager/qoeDelegate":{"role":"symbol","abstract":[],"title":"qoeDelegate","navigatorTitle":[{"kind":"identifier","text":"qoeDelegate"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"qoeDelegate"},{"text":": (any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)GFPVideoAdScheduleManagerQoeDelegate","text":"GFPVideoAdScheduleManagerQoeDelegate"},{"text":")?","kind":"text"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager\/qoeDelegate","type":"topic","kind":"symbol","url":"\/documentation\/gfpsdk\/gfpvideoadschedulemanager\/qoedelegate"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdScheduleManager/volume":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager\/volume","role":"symbol","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"volume"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"}],"navigatorTitle":[{"text":"volume","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpvideoadschedulemanager\/volume","title":"volume","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdScheduleManager/showOverlayView()":{"role":"symbol","abstract":[{"type":"text","text":"광고의 Overlay(Seekbar, Pause, Resume, 선거 광고, 후광고 Text) 영역을 노출합니다."}],"title":"showOverlayView()","navigatorTitle":[{"text":"showOverlayView","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"showOverlayView","kind":"identifier"},{"kind":"text","text":"()"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager\/showOverlayView()","type":"topic","kind":"symbol","url":"\/documentation\/gfpsdk\/gfpvideoadschedulemanager\/showoverlayview()"},"doc://com.navercorp.da.gfp.GFPSDK/s7CVarArgP":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdScheduleManager/hideOverlayView()":{"type":"topic","abstract":[{"type":"text","text":"광고의 Overlay(Seekbar, Pause, Resume, 선거 광고, 후광고 Text) 영역을 사라지게 합니다."}],"title":"hideOverlayView()","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"hideOverlayView","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"hideOverlayView","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpvideoadschedulemanager\/hideoverlayview()","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager\/hideOverlayView()","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdScheduleManager":{"kind":"symbol","type":"topic","url":"\/documentation\/gfpsdk\/gfpvideoadschedulemanager","title":"GFPVideoAdScheduleManager","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager","navigatorTitle":[{"kind":"identifier","text":"GFPVideoAdScheduleManager"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPVideoAdScheduleManager"}],"abstract":[],"role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdScheduleManager/skipButtonTapped(_:)":{"role":"symbol","abstract":[{"type":"text","text":"광고 Skip 버튼 클릭을 원하는 경우, action 연결."}],"title":"skipButtonTapped(_:)","navigatorTitle":[{"kind":"identifier","text":"skipButtonTapped:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"skipButtonTapped","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager\/skipButtonTapped(_:)","type":"topic","kind":"symbol","url":"\/documentation\/gfpsdk\/gfpvideoadschedulemanager\/skipbuttontapped(_:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdScheduleManager/moreButtonTapped(_:)":{"navigatorTitle":[{"kind":"identifier","text":"moreButtonTapped:"}],"url":"\/documentation\/gfpsdk\/gfpvideoadschedulemanager\/morebuttontapped(_:)","abstract":[{"type":"text","text":"광고 더보기 버튼 클릭을 원하는 경우, action 연결."}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"moreButtonTapped","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":")"}],"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager\/moreButtonTapped(_:)","title":"moreButtonTapped(_:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdScheduleManager/adScheduleID":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"adScheduleID","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"navigatorTitle":[{"text":"adScheduleID","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpvideoadschedulemanager\/adscheduleid","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager\/adScheduleID","kind":"symbol","role":"symbol","abstract":[],"type":"topic","title":"adScheduleID"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdScheduleManager/advertiseParams":{"role":"symbol","abstract":[],"title":"advertiseParams","navigatorTitle":[{"kind":"identifier","text":"advertiseParams"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"advertiseParams","kind":"identifier"},{"text":": ","kind":"text"},{"text":"GFPAdvertiseParams","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdvertiseParams"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager\/advertiseParams","type":"topic","kind":"symbol","url":"\/documentation\/gfpsdk\/gfpvideoadschedulemanager\/advertiseparams"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdScheduleManager/contentPlayer":{"role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"contentPlayer","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)AVPlayer","kind":"typeIdentifier","text":"AVPlayer"}],"kind":"symbol","title":"contentPlayer","type":"topic","url":"\/documentation\/gfpsdk\/gfpvideoadschedulemanager\/contentplayer","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager\/contentPlayer","navigatorTitle":[{"kind":"identifier","text":"contentPlayer"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdScheduleManager/start(with:)":{"kind":"symbol","abstract":[],"title":"start(with:)","url":"\/documentation\/gfpsdk\/gfpvideoadschedulemanager\/start(with:)","type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"start","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"with"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager\/start(with:)","navigatorTitle":[{"kind":"identifier","text":"startWith:"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdScheduleManager/showNonLinearAd()":{"navigatorTitle":[{"text":"showNonLinearAd","kind":"identifier"}],"title":"showNonLinearAd()","url":"\/documentation\/gfpsdk\/gfpvideoadschedulemanager\/shownonlinearad()","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager\/showNonLinearAd()","role":"symbol","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"RemindAd(Banner, Text) 광고를 노출합니다."},{"type":"text","text":" "},{"type":"text","text":"ContainerType 없이 기본 위치에 노출. [배너 : Inner, 텍스트 : 가로 방향 (Inner), 세로 방향 (Outer)]"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"showNonLinearAd","kind":"identifier"},{"text":"()","kind":"text"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdScheduleManager/delegate":{"type":"topic","kind":"symbol","url":"\/documentation\/gfpsdk\/gfpvideoadschedulemanager\/delegate","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager\/delegate","title":"delegate","abstract":[],"navigatorTitle":[{"text":"delegate","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": (any "},{"text":"GFPVideoAdScheduleManagerDelegate","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)GFPVideoAdScheduleManagerDelegate"},{"kind":"text","text":")?"}],"role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdScheduleManager/destroy()":{"abstract":[],"role":"symbol","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager\/destroy()","title":"destroy()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"destroy","kind":"identifier"},{"kind":"text","text":"()"}],"navigatorTitle":[{"text":"destroy","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpvideoadschedulemanager\/destroy()","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdScheduleManager/rootViewController":{"kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager\/rootViewController","url":"\/documentation\/gfpsdk\/gfpvideoadschedulemanager\/rootviewcontroller","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"rootViewController","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":"?"}],"title":"rootViewController","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"rootViewController"}],"abstract":[{"type":"text","text":"구글 광고 로드를 위해서는 필수 조건 (View hierachy가 있는 ViewController.)"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdScheduleManager/replace(_:)":{"abstract":[{"text":"RemindAd(Banner, Text) outer 광고 컨테이너를 변경합니다.","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"replace"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"GFPTextAdViewAttribute","preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPTextAdViewAttribute"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager\/replace(_:)","title":"replace(_:)","url":"\/documentation\/gfpsdk\/gfpvideoadschedulemanager\/replace(_:)","type":"topic","navigatorTitle":[{"text":"replaceTextAdViewAttribute:","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdScheduleManager/init(adScheduleID:contentPlayer:videoView:scheduleParam:)":{"navigatorTitle":[{"kind":"identifier","text":"initWithAdScheduleID:contentPlayer:videoView:scheduleParam:"}],"url":"\/documentation\/gfpsdk\/gfpvideoadschedulemanager\/init(adscheduleid:contentplayer:videoview:scheduleparam:)","abstract":[],"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"adScheduleID","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"contentPlayer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVPlayer","text":"AVPlayer"},{"text":", ","kind":"text"},{"text":"videoView","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIView","text":"UIView","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"scheduleParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GFPAdScheduleParam","preciseIdentifier":"c:objc(cs)GFPAdScheduleParam"},{"text":")","kind":"text"}],"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager\/init(adScheduleID:contentPlayer:videoView:scheduleParam:)","title":"init(adScheduleID:contentPlayer:videoView:scheduleParam:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdScheduleManager/renderingSetting":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager\/renderingSetting","url":"\/documentation\/gfpsdk\/gfpvideoadschedulemanager\/renderingsetting","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"renderingSetting"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"renderingSetting","kind":"identifier"},{"kind":"text","text":": "},{"text":"GFPVideoAdRenderingSetting","preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPVideoAdRenderingSetting","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"renderingSetting","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdScheduleManager/playBufferInterval":{"url":"\/documentation\/gfpsdk\/gfpvideoadschedulemanager\/playbufferinterval","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager\/playBufferInterval","abstract":[],"title":"playBufferInterval","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"playBufferInterval"}],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"playBufferInterval"},{"kind":"text","text":": "},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"}]},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdScheduleManager/resume()":{"navigatorTitle":[{"text":"resume","kind":"identifier"}],"title":"resume()","url":"\/documentation\/gfpsdk\/gfpvideoadschedulemanager\/resume()","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager\/resume()","role":"symbol","type":"topic","kind":"symbol","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"resume"},{"kind":"text","text":"()"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdScheduleManager/loadSchedule()":{"type":"topic","abstract":[],"title":"loadSchedule()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"loadSchedule"},{"text":"()","kind":"text"}],"url":"\/documentation\/gfpsdk\/gfpvideoadschedulemanager\/loadschedule()","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager\/loadSchedule()","navigatorTitle":[{"kind":"identifier","text":"loadSchedule"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdScheduleManager/scheduleParam":{"abstract":[],"type":"topic","title":"scheduleParam","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"scheduleParam"},{"kind":"text","text":": "},{"text":"GFPAdScheduleParam","preciseIdentifier":"c:objc(cs)GFPAdScheduleParam","kind":"typeIdentifier"}],"url":"\/documentation\/gfpsdk\/gfpvideoadschedulemanager\/scheduleparam","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager\/scheduleParam","navigatorTitle":[{"kind":"identifier","text":"scheduleParam"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdScheduleManager/hideNonLinearAd()":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager\/hideNonLinearAd()","navigatorTitle":[{"kind":"identifier","text":"hideNonLinearAd"}],"abstract":[{"text":"RemindAd(Banner, Text) 광고를 사라지게 합니다.","type":"text"}],"title":"hideNonLinearAd()","role":"symbol","kind":"symbol","url":"\/documentation\/gfpsdk\/gfpvideoadschedulemanager\/hidenonlinearad()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"hideNonLinearAd"},{"kind":"text","text":"()"}],"type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdScheduleManager/displayMode":{"abstract":[],"url":"\/documentation\/gfpsdk\/gfpvideoadschedulemanager\/displaymode","title":"displayMode","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"displayMode"},{"text":": ","kind":"text"},{"text":"GFPVideoDisplayMode","preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPVideoDisplayMode","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"displayMode","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager\/displayMode"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdScheduleManager/pipDelegate":{"navigatorTitle":[{"kind":"identifier","text":"pipDelegate"}],"url":"\/documentation\/gfpsdk\/gfpvideoadschedulemanager\/pipdelegate","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"pipDelegate"},{"text":": (any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)GFPVideoAdScheduleManagerPIPDelegate","kind":"typeIdentifier","text":"GFPVideoAdScheduleManagerPIPDelegate"},{"kind":"text","text":")?"}],"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager\/pipDelegate","title":"pipDelegate"},"doc://com.navercorp.da.gfp.GFPSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","title":"Swift.Equatable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"value":"GFPVideoAdScheduleManager","op":"replace","path":"\/metadata\/title"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GFPVideoAdScheduleManager"}],"op":"replace"},{"op":"replace","value":[{"text":"GFPVideoAdScheduleManager","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager\/adScheduleID","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager\/advertiseParams","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager\/contentPlayer","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager\/delegate","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager\/displayMode","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager\/nonLinearDelegate","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager\/pipDelegate","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager\/playBufferInterval","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager\/playerSetting","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager\/qoeDelegate","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager\/renderingSetting","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager\/rootViewController","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager\/scheduleParam","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager\/videoView","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager\/volume"],"generated":true},{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager\/destroy()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager\/hideNonLinearAd()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager\/hideOverlayView()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager\/init(adScheduleID:contentPlayer:videoView:scheduleParam:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager\/loadSchedule()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager\/moreButtonTapped(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager\/pause()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager\/replace(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager\/resume()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager\/showNonLinearAd()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager\/showNonLinearAd(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager\/showOverlayView()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager\/skipButtonTapped(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager\/start(with:)"],"anchor":"Instance-Methods"}],"path":"\/topicSections"},{"op":"replace","value":[{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"}],"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"GFPVideoAdScheduleManager","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}]}]}},{"value":"showNonLinearAd:","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager~1showNonLinearAd(_:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"showNonLinearAd:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager~1showNonLinearAd(_:)\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager~1nonLinearDelegate\/title","value":"nonLinearDelegate","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager~1nonLinearDelegate\/fragments","value":[{"kind":"identifier","text":"nonLinearDelegate"}]},{"op":"replace","value":"pause","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager~1pause()\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager~1pause()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"pause","kind":"identifier"}]},{"op":"replace","value":"videoView","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager~1videoView\/title"},{"value":[{"text":"videoView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager~1videoView\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager~1playerSetting\/title","value":"playerSetting"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager~1playerSetting\/fragments","value":[{"kind":"identifier","text":"playerSetting"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager~1qoeDelegate\/title","value":"qoeDelegate"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager~1qoeDelegate\/fragments","op":"replace","value":[{"text":"qoeDelegate","kind":"identifier"}]},{"value":"volume","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager~1volume\/title","op":"replace"},{"value":[{"text":"volume","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager~1volume\/fragments"},{"value":"showOverlayView","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager~1showOverlayView()\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager~1showOverlayView()\/fragments","value":[{"kind":"text","text":"- "},{"text":"showOverlayView","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager~1hideOverlayView()\/title","value":"hideOverlayView"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager~1hideOverlayView()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"hideOverlayView","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager\/title","value":"GFPVideoAdScheduleManager","op":"replace"},{"value":[{"kind":"identifier","text":"GFPVideoAdScheduleManager"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"GFPVideoAdScheduleManager"}]},{"op":"replace","value":"skipButtonTapped:","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager~1skipButtonTapped(_:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"skipButtonTapped:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager~1skipButtonTapped(_:)\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager~1moreButtonTapped(_:)\/title","op":"replace","value":"moreButtonTapped:"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager~1moreButtonTapped(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"moreButtonTapped:"}],"op":"replace"},{"op":"replace","value":"adScheduleID","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager~1adScheduleID\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager~1adScheduleID\/fragments","value":[{"kind":"identifier","text":"adScheduleID"}],"op":"replace"},{"value":"advertiseParams","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager~1advertiseParams\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager~1advertiseParams\/fragments","value":[{"text":"advertiseParams","kind":"identifier"}],"op":"replace"},{"value":"contentPlayer","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager~1contentPlayer\/title"},{"value":[{"text":"contentPlayer","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager~1contentPlayer\/fragments"},{"value":"startWith:","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager~1start(with:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startWith:"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager~1start(with:)\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager~1showNonLinearAd()\/title","value":"showNonLinearAd","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"showNonLinearAd"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager~1showNonLinearAd()\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager~1delegate\/title","value":"delegate"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager~1delegate\/fragments","value":[{"text":"delegate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager~1destroy()\/title","op":"replace","value":"destroy"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager~1destroy()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"destroy"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager~1rootViewController\/title","op":"replace","value":"rootViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager~1rootViewController\/fragments","value":[{"kind":"identifier","text":"rootViewController"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager~1replace(_:)\/title","op":"replace","value":"replaceTextAdViewAttribute:"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager~1replace(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"replaceTextAdViewAttribute:"}]},{"value":"initWithAdScheduleID:contentPlayer:videoView:scheduleParam:","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager~1init(adScheduleID:contentPlayer:videoView:scheduleParam:)\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager~1init(adScheduleID:contentPlayer:videoView:scheduleParam:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithAdScheduleID:contentPlayer:videoView:scheduleParam:","kind":"identifier"}],"op":"replace"},{"value":"renderingSetting","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager~1renderingSetting\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager~1renderingSetting\/fragments","value":[{"text":"renderingSetting","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager~1playBufferInterval\/title","value":"playBufferInterval","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager~1playBufferInterval\/fragments","op":"replace","value":[{"text":"playBufferInterval","kind":"identifier"}]},{"value":"resume","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager~1resume()\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"resume","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager~1resume()\/fragments"},{"value":"loadSchedule","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager~1loadSchedule()\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager~1loadSchedule()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"loadSchedule"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager~1scheduleParam\/title","op":"replace","value":"scheduleParam"},{"value":[{"text":"scheduleParam","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager~1scheduleParam\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager~1hideNonLinearAd()\/title","value":"hideNonLinearAd"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager~1hideNonLinearAd()\/fragments","value":[{"kind":"text","text":"- "},{"text":"hideNonLinearAd","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager~1displayMode\/title","value":"displayMode"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager~1displayMode\/fragments","value":[{"kind":"identifier","text":"displayMode"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager~1pipDelegate\/title","value":"pipDelegate","op":"replace"},{"op":"replace","value":[{"text":"pipDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager~1pipDelegate\/fragments"}]}]}