{"topicSections":[{"title":"Initializers","generated":true,"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoPlacementType\/init(rawValue:)"],"anchor":"Initializers"},{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoPlacementType\/mid","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoPlacementType\/post","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoPlacementType\/pre","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoPlacementType\/unknown"],"title":"Type Properties","anchor":"Type-Properties","generated":true},{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoPlacementType\/Equatable-Implementations","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoPlacementType\/OptionSet-Implementations","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoPlacementType\/SetAlgebra-Implementations"],"generated":true,"title":"Default Implementations","anchor":"Default-Implementations"}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/gfpsdk\/gfpvideoplacementtype"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpvideoplacementtype"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoPlacementType"},"sections":[],"relationshipsSections":[{"title":"Conforms To","type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/s15BitwiseCopyableP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s25ExpressibleByArrayLiteralP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s9OptionSetP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SY","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s8SendableP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s10SetAlgebraP"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"GFPVideoPlacementType","kind":"identifier"}]}]}],"metadata":{"role":"symbol","modules":[{"name":"GFPSDK"}],"externalID":"c:@E@GFPVideoPlacementType","symbolKind":"struct","title":"GFPVideoPlacementType","navigatorTitle":[{"kind":"identifier","text":"GFPVideoPlacementType"}],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPVideoPlacementType"}],"roleHeading":"Structure"},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"references":{"doc://com.navercorp.da.gfp.GFPSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","title":"Swift.Equatable"},"doc://com.navercorp.da.gfp.GFPSDK/s8SendableP":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s8SendableP","title":"Swift.Sendable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoPlacementType/OptionSet-Implementations":{"type":"topic","abstract":[],"title":"OptionSet Implementations","url":"\/documentation\/gfpsdk\/gfpvideoplacementtype\/optionset-implementations","role":"collectionGroup","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoPlacementType\/OptionSet-Implementations","kind":"article"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoPlacementType/post":{"role":"symbol","abstract":[],"title":"post","navigatorTitle":[{"text":"GFPVideoPlacementTypePost","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"post"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@GFPVideoPlacementType","text":"GFPVideoPlacementType","kind":"typeIdentifier"}],"url":"\/documentation\/gfpsdk\/gfpvideoplacementtype\/post","type":"topic","kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoPlacementType\/post"},"doc://com.navercorp.da.gfp.GFPSDK/s15BitwiseCopyableP":{"title":"Swift.BitwiseCopyable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s15BitwiseCopyableP","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoPlacementType/SetAlgebra-Implementations":{"kind":"article","title":"SetAlgebra Implementations","abstract":[],"type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoPlacementType\/SetAlgebra-Implementations","url":"\/documentation\/gfpsdk\/gfpvideoplacementtype\/setalgebra-implementations","role":"collectionGroup"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoPlacementType/init(rawValue:)":{"role":"symbol","abstract":[],"title":"init(rawValue:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":")"}],"url":"\/documentation\/gfpsdk\/gfpvideoplacementtype\/init(rawvalue:)","type":"topic","kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoPlacementType\/init(rawValue:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoPlacementType/pre":{"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"pre","kind":"identifier"},{"text":": ","kind":"text"},{"text":"GFPVideoPlacementType","preciseIdentifier":"c:@E@GFPVideoPlacementType","kind":"typeIdentifier"}],"url":"\/documentation\/gfpsdk\/gfpvideoplacementtype\/pre","navigatorTitle":[{"text":"GFPVideoPlacementTypePre","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoPlacementType\/pre","title":"pre","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoPlacementType/mid":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mid","kind":"identifier"},{"kind":"text","text":": "},{"text":"GFPVideoPlacementType","kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPVideoPlacementType"}],"navigatorTitle":[{"text":"GFPVideoPlacementTypeMid","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpvideoplacementtype\/mid","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoPlacementType\/mid","kind":"symbol","role":"symbol","abstract":[],"type":"topic","title":"mid"},"doc://com.navercorp.da.gfp.GFPSDK/s10SetAlgebraP":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s10SetAlgebraP","title":"Swift.SetAlgebra"},"doc://com.navercorp.da.gfp.GFPSDK/s9OptionSetP":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s9OptionSetP","title":"Swift.OptionSet"},"doc://com.navercorp.da.gfp.GFPSDK/SY":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SY","title":"Swift.RawRepresentable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoPlacementType/unknown":{"role":"symbol","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPVideoPlacementType","text":"GFPVideoPlacementType"}],"url":"\/documentation\/gfpsdk\/gfpvideoplacementtype\/unknown","navigatorTitle":[{"kind":"identifier","text":"GFPVideoPlacementTypeUnknown"}],"abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoPlacementType\/unknown","title":"unknown","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/s25ExpressibleByArrayLiteralP":{"type":"unresolvable","title":"Swift.ExpressibleByArrayLiteral","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s25ExpressibleByArrayLiteralP"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoPlacementType":{"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPVideoPlacementType","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"GFPVideoPlacementType","kind":"identifier"}],"type":"topic","title":"GFPVideoPlacementType","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoPlacementType","kind":"symbol","url":"\/documentation\/gfpsdk\/gfpvideoplacementtype","abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoPlacementType/Equatable-Implementations":{"role":"collectionGroup","kind":"article","url":"\/documentation\/gfpsdk\/gfpvideoplacementtype\/equatable-implementations","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoPlacementType\/Equatable-Implementations","title":"Equatable Implementations","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration"},{"path":"\/metadata\/title","value":"GFPVideoPlacementType","op":"replace"},{"value":"enum","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"GFPVideoPlacementType"}]},{"value":[{"kind":"identifier","text":"GFPVideoPlacementType"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","anchor":"Enumeration-Cases","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoPlacementType\/mid","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoPlacementType\/post","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoPlacementType\/pre","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoPlacementType\/unknown"],"generated":true}]},{"op":"replace","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPVideoPlacementType"},{"kind":"text","text":": "},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"value":"GFPVideoPlacementTypePost","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoPlacementType~1post\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoPlacementType~1post\/fragments","value":[{"text":"GFPVideoPlacementTypePost","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoPlacementType~1pre\/title","value":"GFPVideoPlacementTypePre","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"GFPVideoPlacementTypePre"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoPlacementType~1pre\/fragments"},{"value":"GFPVideoPlacementTypeMid","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoPlacementType~1mid\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoPlacementType~1mid\/fragments","value":[{"kind":"identifier","text":"GFPVideoPlacementTypeMid"}]},{"op":"replace","value":"GFPVideoPlacementTypeUnknown","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoPlacementType~1unknown\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoPlacementType~1unknown\/fragments","value":[{"kind":"identifier","text":"GFPVideoPlacementTypeUnknown"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoPlacementType\/title","value":"GFPVideoPlacementType","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoPlacementType\/fragments","op":"replace","value":[{"kind":"identifier","text":"GFPVideoPlacementType"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoPlacementType\/navigatorTitle","value":[{"text":"GFPVideoPlacementType","kind":"identifier"}],"op":"replace"}]}]}