{"metadata":{"title":"GFPVideoOptions","externalID":"c:objc(cs)GFPVideoOptions","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"GFPVideoOptions","kind":"identifier"}],"roleHeading":"Class","navigatorTitle":[{"kind":"identifier","text":"GFPVideoOptions"}],"symbolKind":"class","modules":[{"name":"GFPSDK"}]},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoOptions","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPVideoOptions"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"kind":"symbol","topicSections":[{"anchor":"Initializers","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoOptions\/init(playPolicy:useCustomControlView:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoOptions\/init(playPolicy:viewType:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoOptions\/init(playPolicy:viewType:useCustomControlView:)"],"title":"Initializers","generated":true},{"generated":true,"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoOptions\/maxBitrateKbps","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoOptions\/playPolicy","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoOptions\/qoeTrackingInfo","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoOptions\/useCustomControlView","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoOptions\/useGlobalOptions","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoOptions\/viewType"],"title":"Instance Properties","anchor":"Instance-Properties"},{"title":"Type Methods","generated":true,"anchor":"Type-Methods","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoOptions\/createGlobalOptions(with:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoOptions\/createGlobalOptions(with:useCustonControlView:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoOptions\/createGlobalOptions(withUseCustomControlView:)"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject"],"type":"inheritsFrom"},{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s7CVarArgP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s23CustomStringConvertibleP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpvideooptions"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpvideooptions"]}],"sections":[],"references":{"doc://com.navercorp.da.gfp.GFPSDK/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject"},"doc://com.navercorp.da.gfp.GFPSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s28CustomDebugStringConvertibleP"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoOptions/init(playPolicy:viewType:)":{"title":"init(playPolicy:viewType:)","url":"\/documentation\/gfpsdk\/gfpvideooptions\/init(playpolicy:viewtype:)","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"playPolicy","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"GFPVideoPlayPolicy","kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPVideoPlayPolicy"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"viewType"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPVideoViewType","text":"GFPVideoViewType"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"initWithPlayPolicy:viewType:"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoOptions\/init(playPolicy:viewType:)","type":"topic","role":"symbol","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoOptions/init(playPolicy:useCustomControlView:)":{"type":"topic","title":"init(playPolicy:useCustomControlView:)","url":"\/documentation\/gfpsdk\/gfpvideooptions\/init(playpolicy:usecustomcontrolview:)","kind":"symbol","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"playPolicy"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"GFPVideoPlayPolicy","preciseIdentifier":"c:@E@GFPVideoPlayPolicy"},{"kind":"text","text":", "},{"text":"useCustomControlView","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoOptions\/init(playPolicy:useCustomControlView:)","navigatorTitle":[{"kind":"identifier","text":"initWithPlayPolicy:useCustomControlView:"}],"abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoOptions/playPolicy":{"title":"playPolicy","url":"\/documentation\/gfpsdk\/gfpvideooptions\/playpolicy","abstract":[{"type":"text","text":"광고 영상의 재생 정책을 설정합니다. (기본값 Auto)"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"playPolicy","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"GFPVideoPlayPolicy","preciseIdentifier":"c:@E@GFPVideoPlayPolicy"}],"navigatorTitle":[{"kind":"identifier","text":"playPolicy"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoOptions\/playPolicy","type":"topic","role":"symbol","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoOptions/createGlobalOptions(with:)":{"title":"createGlobalOptions(with:)","url":"\/documentation\/gfpsdk\/gfpvideooptions\/createglobaloptions(with:)","kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"createGlobalOptions"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"with"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"GFPVideoViewType","preciseIdentifier":"c:@E@GFPVideoViewType"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Self"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoOptions\/createGlobalOptions(with:)","navigatorTitle":[{"text":"createGlobalOptionsWithViewType:","kind":"identifier"}],"abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoOptions/useCustomControlView":{"url":"\/documentation\/gfpsdk\/gfpvideooptions\/usecustomcontrolview","abstract":[{"type":"text","text":"광고 영상의 Custom Control View 사용 여부를 설정합니다. (기본값 false)"},{"text":" ","type":"text"},{"type":"text","text":"true로 설정 시 control 구성 요소를 숨기며, false로 설정 시 sdk 내에서 control 구성 요소를 그려줍니다."}],"title":"useCustomControlView","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoOptions\/useCustomControlView","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"useCustomControlView","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"useCustomControlView"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoOptions/qoeTrackingInfo":{"type":"topic","title":"qoeTrackingInfo","url":"\/documentation\/gfpsdk\/gfpvideooptions\/qoetrackinginfo","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"qoeTrackingInfo","kind":"identifier"},{"kind":"text","text":": "},{"text":"GFPQoeTrackingInfo","kind":"typeIdentifier","preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPQoeTrackingInfo"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoOptions\/qoeTrackingInfo","navigatorTitle":[{"kind":"identifier","text":"qoeTrackingInfo"}],"abstract":[{"type":"text","text":"광고 영상의 qoe 로깅을 위해 정보를 전달합니다."}]},"doc://com.navercorp.da.gfp.GFPSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s7CVarArgP"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoOptions/maxBitrateKbps":{"title":"maxBitrateKbps","url":"\/documentation\/gfpsdk\/gfpvideooptions\/maxbitratekbps","kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"maxBitrateKbps","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoOptions\/maxBitrateKbps","navigatorTitle":[{"kind":"identifier","text":"maxBitrateKbps"}],"abstract":[{"type":"text","text":"광고영상의 최대 bitrate (kbit\/sec) (기본값 800)"},{"text":" ","type":"text"},{"type":"text","text":"입력값 보다 낮은 bitrate 광고영상 중 가장 높은 bitrate 영샹이 채택되며,"},{"type":"text","text":" "},{"type":"text","text":"입력값 보다 낮은 bitrate 영상이 없는 경우 가장 가까운 bitrate 영샹이 재생됩니다."}]},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoOptions/createGlobalOptions(with:useCustonControlView:)":{"title":"createGlobalOptions(with:useCustonControlView:)","url":"\/documentation\/gfpsdk\/gfpvideooptions\/createglobaloptions(with:usecustoncontrolview:)","kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createGlobalOptions"},{"kind":"text","text":"("},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"GFPVideoViewType","preciseIdentifier":"c:@E@GFPVideoViewType","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"useCustonControlView","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Self","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoOptions\/createGlobalOptions(with:useCustonControlView:)","navigatorTitle":[{"text":"createGlobalOptionsWithViewType:useCustonControlView:","kind":"identifier"}],"abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/SH":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoOptions/init(playPolicy:viewType:useCustomControlView:)":{"type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoOptions\/init(playPolicy:viewType:useCustomControlView:)","role":"symbol","abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithPlayPolicy:viewType:useCustomControlView:"}],"url":"\/documentation\/gfpsdk\/gfpvideooptions\/init(playpolicy:viewtype:usecustomcontrolview:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"playPolicy","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPVideoPlayPolicy","text":"GFPVideoPlayPolicy"},{"kind":"text","text":", "},{"text":"viewType","kind":"externalParam"},{"kind":"text","text":": "},{"text":"GFPVideoViewType","kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPVideoViewType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"useCustomControlView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}],"title":"init(playPolicy:viewType:useCustomControlView:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoOptions/viewType":{"url":"\/documentation\/gfpsdk\/gfpvideooptions\/viewtype","title":"viewType","abstract":[{"text":"광고 영상의 view type 을 설정합니다.","type":"text"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoOptions\/viewType","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"viewType","kind":"identifier"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"viewType"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPVideoViewType","text":"GFPVideoViewType"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoOptions/createGlobalOptions(withUseCustomControlView:)":{"title":"createGlobalOptions(withUseCustomControlView:)","url":"\/documentation\/gfpsdk\/gfpvideooptions\/createglobaloptions(withusecustomcontrolview:)","kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"createGlobalOptions","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withUseCustomControlView","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Self"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoOptions\/createGlobalOptions(withUseCustomControlView:)","navigatorTitle":[{"kind":"identifier","text":"createGlobalOptionsWithUseCustomControlView:"}],"abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoOptions":{"type":"topic","url":"\/documentation\/gfpsdk\/gfpvideooptions","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoOptions","role":"symbol","kind":"symbol","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPVideoOptions","kind":"identifier"}],"title":"GFPVideoOptions","navigatorTitle":[{"text":"GFPVideoOptions","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/SQ":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoOptions/useGlobalOptions":{"title":"useGlobalOptions","url":"\/documentation\/gfpsdk\/gfpvideooptions\/useglobaloptions","kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"useGlobalOptions","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoOptions\/useGlobalOptions","navigatorTitle":[{"text":"useGlobalOptions","kind":"identifier"}],"abstract":[{"type":"text","text":"광고 영상의 전역 설정 사용 여부를 조회합니다."}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"GFPVideoOptions"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"GFPVideoOptions","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","value":[{"text":"GFPVideoOptions","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoOptions\/maxBitrateKbps","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoOptions\/playPolicy","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoOptions\/qoeTrackingInfo","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoOptions\/useCustomControlView","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoOptions\/useGlobalOptions","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoOptions\/viewType"],"title":"Instance Properties","anchor":"Instance-Properties"},{"anchor":"Instance-Methods","title":"Instance Methods","generated":true,"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoOptions\/init(playPolicy:useCustomControlView:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoOptions\/init(playPolicy:viewType:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoOptions\/init(playPolicy:viewType:useCustomControlView:)"]},{"title":"Type Methods","anchor":"Type-Methods","generated":true,"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoOptions\/createGlobalOptions(with:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoOptions\/createGlobalOptions(with:useCustonControlView:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoOptions\/createGlobalOptions(withUseCustomControlView:)"]}]},{"op":"replace","value":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject"]}],"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPVideoOptions","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoOptions~1init(playPolicy:viewType:)\/title","value":"initWithPlayPolicy:viewType:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"initWithPlayPolicy:viewType:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoOptions~1init(playPolicy:viewType:)\/fragments"},{"op":"replace","value":"initWithPlayPolicy:useCustomControlView:","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoOptions~1init(playPolicy:useCustomControlView:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoOptions~1init(playPolicy:useCustomControlView:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithPlayPolicy:useCustomControlView:","kind":"identifier"}]},{"value":"playPolicy","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoOptions~1playPolicy\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoOptions~1playPolicy\/fragments","value":[{"kind":"identifier","text":"playPolicy"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoOptions~1createGlobalOptions(with:)\/title","op":"replace","value":"createGlobalOptionsWithViewType:"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoOptions~1createGlobalOptions(with:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"createGlobalOptionsWithViewType:"}],"op":"replace"},{"value":"useCustomControlView","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoOptions~1useCustomControlView\/title"},{"value":[{"kind":"identifier","text":"useCustomControlView"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoOptions~1useCustomControlView\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoOptions~1qoeTrackingInfo\/title","value":"qoeTrackingInfo","op":"replace"},{"value":[{"kind":"identifier","text":"qoeTrackingInfo"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoOptions~1qoeTrackingInfo\/fragments"},{"op":"replace","value":"maxBitrateKbps","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoOptions~1maxBitrateKbps\/title"},{"value":[{"kind":"identifier","text":"maxBitrateKbps"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoOptions~1maxBitrateKbps\/fragments"},{"op":"replace","value":"createGlobalOptionsWithViewType:useCustonControlView:","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoOptions~1createGlobalOptions(with:useCustonControlView:)\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoOptions~1createGlobalOptions(with:useCustonControlView:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"createGlobalOptionsWithViewType:useCustonControlView:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoOptions~1init(playPolicy:viewType:useCustomControlView:)\/title","op":"replace","value":"initWithPlayPolicy:viewType:useCustomControlView:"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoOptions~1init(playPolicy:viewType:useCustomControlView:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithPlayPolicy:viewType:useCustomControlView:","kind":"identifier"}]},{"value":"viewType","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoOptions~1viewType\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoOptions~1viewType\/fragments","op":"replace","value":[{"text":"viewType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoOptions~1createGlobalOptions(withUseCustomControlView:)\/title","value":"createGlobalOptionsWithUseCustomControlView:"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"createGlobalOptionsWithUseCustomControlView:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoOptions~1createGlobalOptions(withUseCustomControlView:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoOptions\/title","value":"GFPVideoOptions"},{"value":[{"text":"GFPVideoOptions","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoOptions\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoOptions\/navigatorTitle","op":"replace","value":[{"text":"GFPVideoOptions","kind":"identifier"}]},{"op":"replace","value":"useGlobalOptions","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoOptions~1useGlobalOptions\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoOptions~1useGlobalOptions\/fragments","op":"replace","value":[{"kind":"identifier","text":"useGlobalOptions"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}