{"metadata":{"role":"symbol","modules":[{"name":"GFPSDK"}],"externalID":"c:objc(cs)GFPVideoAdBreak","symbolKind":"class","title":"GFPVideoAdBreak","navigatorTitle":[{"kind":"identifier","text":"GFPVideoAdBreak"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPVideoAdBreak"}],"roleHeading":"Class"},"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject"]},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSCopying","doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s7CVarArgP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s23CustomStringConvertibleP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH"],"type":"conformsTo"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPVideoAdBreak","kind":"identifier"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpvideoadbreak"]},{"paths":["\/documentation\/gfpsdk\/gfpvideoadbreak"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"anchor":"Initializers","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdBreak\/init(dictionary:withError:)"],"generated":true,"title":"Initializers"},{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdBreak\/adBreakID","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdBreak\/adSources","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdBreak\/adUnitID","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdBreak\/hasLoadedAd","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdBreak\/hasMoreLoaded","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdBreak\/hasNotice","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdBreak\/isAllCompleted","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdBreak\/isAllLoaded","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdBreak\/isPlaying","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdBreak\/isPostRoll","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdBreak\/isPreRoll","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdBreak\/noticeDuration","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdBreak\/noticeOffset","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdBreak\/preFetchSecond","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdBreak\/prefetchOffset","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdBreak\/startDelay","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdBreak\/timeOffset","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdBreak\/type"],"generated":true,"anchor":"Instance-Properties","title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdBreak\/updateDuration(_:)"],"anchor":"Instance-Methods","generated":true},{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdBreak\/adBreaks(withDictionary:noticeDuration:withError:)"],"anchor":"Type-Methods","generated":true,"title":"Type Methods"}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"kind":"symbol","identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdBreak","interfaceLanguage":"swift"},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdBreak/type":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"type","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@GFPVideoPlacementType","text":"GFPVideoPlacementType","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"type","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdBreak\/type","abstract":[],"title":"type","url":"\/documentation\/gfpsdk\/gfpvideoadbreak\/type"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdBreak/isAllCompleted":{"navigatorTitle":[{"kind":"identifier","text":"isAllCompleted"}],"url":"\/documentation\/gfpsdk\/gfpvideoadbreak\/isallcompleted","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"isAllCompleted","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"title":"isAllCompleted","kind":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdBreak\/isAllCompleted","role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdBreak/prefetchOffset":{"abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"prefetchOffset"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"role":"symbol","navigatorTitle":[{"text":"prefetchOffset","kind":"identifier"}],"type":"topic","url":"\/documentation\/gfpsdk\/gfpvideoadbreak\/prefetchoffset","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdBreak\/prefetchOffset","title":"prefetchOffset","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdBreak/init(dictionary:withError:)":{"abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdBreak\/init(dictionary:withError:)","type":"topic","title":"init(dictionary:withError:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"dictionary"},{"text":": [","kind":"text"},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"withError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SA","text":"AutoreleasingUnsafeMutablePointer"},{"text":"<","kind":"text"},{"text":"GFPError","kind":"typeIdentifier","preciseIdentifier":"c:@M@NaverAdsServices@objc(cs)GFPError"},{"kind":"text","text":"?>?)"}],"kind":"symbol","navigatorTitle":[{"text":"initWithDictionary:withError:","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpvideoadbreak\/init(dictionary:witherror:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdBreak":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPVideoAdBreak","kind":"identifier"}],"kind":"symbol","role":"symbol","abstract":[],"type":"topic","url":"\/documentation\/gfpsdk\/gfpvideoadbreak","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdBreak","title":"GFPVideoAdBreak","navigatorTitle":[{"text":"GFPVideoAdBreak","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdBreak/isAllLoaded":{"kind":"symbol","url":"\/documentation\/gfpsdk\/gfpvideoadbreak\/isallloaded","navigatorTitle":[{"text":"isAllLoaded","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"isAllLoaded","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdBreak\/isAllLoaded","type":"topic","abstract":[],"role":"symbol","title":"isAllLoaded"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)NSCopying":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSCopying","title":"NSCopying"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdBreak/adUnitID":{"abstract":[],"title":"adUnitID","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"adUnitID","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"url":"\/documentation\/gfpsdk\/gfpvideoadbreak\/adunitid","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdBreak\/adUnitID","navigatorTitle":[{"text":"adUnitID","kind":"identifier"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.navercorp.da.gfp.GFPSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s7CVarArgP"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdBreak/hasLoadedAd":{"title":"hasLoadedAd","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdBreak\/hasLoadedAd","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"hasLoadedAd","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"text":"hasLoadedAd","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/gfpsdk\/gfpvideoadbreak\/hasloadedad","abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdBreak/isPreRoll":{"title":"isPreRoll","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdBreak\/isPreRoll","role":"symbol","kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"isPreRoll","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"navigatorTitle":[{"kind":"identifier","text":"isPreRoll"}],"type":"topic","url":"\/documentation\/gfpsdk\/gfpvideoadbreak\/ispreroll"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdBreak/noticeDuration":{"abstract":[],"url":"\/documentation\/gfpsdk\/gfpvideoadbreak\/noticeduration","role":"symbol","title":"noticeDuration","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdBreak\/noticeDuration","navigatorTitle":[{"text":"noticeDuration","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"noticeDuration","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdBreak/hasMoreLoaded":{"title":"hasMoreLoaded","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdBreak\/hasMoreLoaded","kind":"symbol","role":"symbol","url":"\/documentation\/gfpsdk\/gfpvideoadbreak\/hasmoreloaded","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"hasMoreLoaded","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"type":"topic","navigatorTitle":[{"text":"hasMoreLoaded","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s23CustomStringConvertibleP"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdBreak/isPlaying":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"isPlaying"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdBreak\/isPlaying","title":"isPlaying","url":"\/documentation\/gfpsdk\/gfpvideoadbreak\/isplaying","abstract":[],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isPlaying"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdBreak/isPostRoll":{"abstract":[],"title":"isPostRoll","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isPostRoll"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"url":"\/documentation\/gfpsdk\/gfpvideoadbreak\/ispostroll","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdBreak\/isPostRoll","navigatorTitle":[{"kind":"identifier","text":"isPostRoll"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdBreak/preFetchSecond":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"preFetchSecond","kind":"identifier"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"preFetchSecond","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdBreak\/preFetchSecond","url":"\/documentation\/gfpsdk\/gfpvideoadbreak\/prefetchsecond","title":"preFetchSecond","type":"topic","abstract":[],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","title":"Swift.Equatable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdBreak/updateDuration(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateDuration"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"updateDuration:","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpvideoadbreak\/updateduration(_:)","abstract":[],"kind":"symbol","role":"symbol","title":"updateDuration(_:)","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdBreak\/updateDuration(_:)","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdBreak/hasNotice":{"navigatorTitle":[{"text":"hasNotice","kind":"identifier"}],"title":"hasNotice","abstract":[],"type":"topic","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdBreak\/hasNotice","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"hasNotice","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"url":"\/documentation\/gfpsdk\/gfpvideoadbreak\/hasnotice","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH","title":"Swift.Hashable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdBreak/startDelay":{"type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdBreak\/startDelay","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"startDelay","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"kind":"symbol","navigatorTitle":[{"text":"startDelay","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpvideoadbreak\/startdelay","title":"startDelay","abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdBreak/noticeOffset":{"navigatorTitle":[{"kind":"identifier","text":"noticeOffset"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdBreak\/noticeOffset","url":"\/documentation\/gfpsdk\/gfpvideoadbreak\/noticeoffset","role":"symbol","abstract":[],"title":"noticeOffset","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"noticeOffset"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdBreak/adBreakID":{"type":"topic","abstract":[],"title":"adBreakID","role":"symbol","url":"\/documentation\/gfpsdk\/gfpvideoadbreak\/adbreakid","navigatorTitle":[{"text":"adBreakID","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdBreak\/adBreakID","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"adBreakID","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject","title":"NSObject"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdBreak/adBreaks(withDictionary:noticeDuration:withError:)":{"role":"symbol","abstract":[],"title":"adBreaks(withDictionary:noticeDuration:withError:)","navigatorTitle":[{"kind":"identifier","text":"adBreaksWithDictionary:noticeDuration:withError:"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"adBreaks","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withDictionary"},{"kind":"text","text":": [["},{"preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"]], ","kind":"text"},{"text":"noticeDuration","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"withError"},{"kind":"text","text":": "},{"text":"AutoreleasingUnsafeMutablePointer","kind":"typeIdentifier","preciseIdentifier":"s:SA"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","text":"GFPError","preciseIdentifier":"c:@M@NaverAdsServices@objc(cs)GFPError"},{"text":"?>?) -> [","kind":"text"},{"kind":"typeIdentifier","text":"GFPVideoAdBreak","preciseIdentifier":"c:objc(cs)GFPVideoAdBreak"},{"text":"]","kind":"text"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdBreak\/adBreaks(withDictionary:noticeDuration:withError:)","type":"topic","kind":"symbol","url":"\/documentation\/gfpsdk\/gfpvideoadbreak\/adbreaks(withdictionary:noticeduration:witherror:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdBreak/timeOffset":{"abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"timeOffset","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"title":"timeOffset","navigatorTitle":[{"text":"timeOffset","kind":"identifier"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdBreak\/timeOffset","url":"\/documentation\/gfpsdk\/gfpvideoadbreak\/timeoffset","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdBreak/adSources":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdBreak\/adSources","abstract":[],"role":"symbol","title":"adSources","kind":"symbol","url":"\/documentation\/gfpsdk\/gfpvideoadbreak\/adsources","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"adSources"},{"kind":"text","text":": ["},{"text":"GFPVideoAdSource","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoAdSource"},{"text":"]","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"adSources"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"GFPVideoAdBreak","op":"replace","path":"\/metadata\/title"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"GFPVideoAdBreak"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"GFPVideoAdBreak","kind":"identifier"}]},{"value":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdBreak\/adBreakID","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdBreak\/adSources","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdBreak\/adUnitID","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdBreak\/hasLoadedAd","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdBreak\/hasMoreLoaded","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdBreak\/hasNotice","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdBreak\/isAllCompleted","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdBreak\/isAllLoaded","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdBreak\/isPlaying","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdBreak\/isPostRoll","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdBreak\/isPreRoll","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdBreak\/noticeDuration","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdBreak\/noticeOffset","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdBreak\/preFetchSecond","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdBreak\/prefetchOffset","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdBreak\/startDelay","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdBreak\/timeOffset","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdBreak\/type"],"generated":true,"title":"Instance Properties"},{"generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdBreak\/init(dictionary:withError:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdBreak\/updateDuration(_:)"],"title":"Instance Methods"},{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdBreak\/adBreaks(withDictionary:noticeDuration:withError:)"],"generated":true,"title":"Type Methods","anchor":"Type-Methods"}],"op":"replace","path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"title":"Conforms To","type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSCopying"]}]},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPVideoAdBreak"},{"kind":"text","text":" : "},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"]}]}},{"op":"replace","value":"type","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdBreak~1type\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdBreak~1type\/fragments","value":[{"text":"type","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdBreak~1isAllCompleted\/title","value":"isAllCompleted"},{"value":[{"kind":"identifier","text":"isAllCompleted"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdBreak~1isAllCompleted\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdBreak~1prefetchOffset\/title","op":"replace","value":"prefetchOffset"},{"value":[{"kind":"identifier","text":"prefetchOffset"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdBreak~1prefetchOffset\/fragments","op":"replace"},{"op":"replace","value":"initWithDictionary:withError:","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdBreak~1init(dictionary:withError:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithDictionary:withError:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdBreak~1init(dictionary:withError:)\/fragments","op":"replace"},{"value":"GFPVideoAdBreak","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdBreak\/title"},{"value":[{"text":"GFPVideoAdBreak","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdBreak\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdBreak\/navigatorTitle","value":[{"kind":"identifier","text":"GFPVideoAdBreak"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdBreak~1isAllLoaded\/title","value":"isAllLoaded"},{"value":[{"kind":"identifier","text":"isAllLoaded"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdBreak~1isAllLoaded\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdBreak~1adUnitID\/title","value":"adUnitID"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdBreak~1adUnitID\/fragments","value":[{"text":"adUnitID","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdBreak~1hasLoadedAd\/title","value":"hasLoadedAd","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdBreak~1hasLoadedAd\/fragments","value":[{"text":"hasLoadedAd","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdBreak~1isPreRoll\/title","value":"isPreRoll"},{"op":"replace","value":[{"text":"isPreRoll","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdBreak~1isPreRoll\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdBreak~1noticeDuration\/title","op":"replace","value":"noticeDuration"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdBreak~1noticeDuration\/fragments","value":[{"kind":"identifier","text":"noticeDuration"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdBreak~1hasMoreLoaded\/title","value":"hasMoreLoaded","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdBreak~1hasMoreLoaded\/fragments","value":[{"kind":"identifier","text":"hasMoreLoaded"}],"op":"replace"},{"value":"isPlaying","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdBreak~1isPlaying\/title"},{"value":[{"kind":"identifier","text":"isPlaying"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdBreak~1isPlaying\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdBreak~1isPostRoll\/title","value":"isPostRoll"},{"value":[{"kind":"identifier","text":"isPostRoll"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdBreak~1isPostRoll\/fragments"},{"op":"replace","value":"preFetchSecond","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdBreak~1preFetchSecond\/title"},{"value":[{"kind":"identifier","text":"preFetchSecond"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdBreak~1preFetchSecond\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdBreak~1updateDuration(_:)\/title","value":"updateDuration:"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdBreak~1updateDuration(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"updateDuration:"}]},{"op":"replace","value":"hasNotice","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdBreak~1hasNotice\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdBreak~1hasNotice\/fragments","value":[{"text":"hasNotice","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdBreak~1startDelay\/title","value":"startDelay"},{"value":[{"text":"startDelay","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdBreak~1startDelay\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdBreak~1noticeOffset\/title","value":"noticeOffset","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdBreak~1noticeOffset\/fragments","value":[{"text":"noticeOffset","kind":"identifier"}],"op":"replace"},{"value":"adBreakID","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdBreak~1adBreakID\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdBreak~1adBreakID\/fragments","value":[{"kind":"identifier","text":"adBreakID"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdBreak~1adBreaks(withDictionary:noticeDuration:withError:)\/title","value":"adBreaksWithDictionary:noticeDuration:withError:"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdBreak~1adBreaks(withDictionary:noticeDuration:withError:)\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"adBreaksWithDictionary:noticeDuration:withError:"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdBreak~1timeOffset\/title","value":"timeOffset","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdBreak~1timeOffset\/fragments","op":"replace","value":[{"kind":"identifier","text":"timeOffset"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdBreak~1adSources\/title","value":"adSources"},{"op":"replace","value":[{"text":"adSources","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdBreak~1adSources\/fragments"}]}]}