{"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/gfpsdk\/gfpvideoproviderndaerrorkey"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gfpsdk\/gfpvideoproviderndaerrorkey"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoProviderNDAErrorKey"},"metadata":{"symbolKind":"var","navigatorTitle":[{"kind":"identifier","text":"GFPVideoProviderNDAErrorKey"}],"roleHeading":"Global Variable","title":"GFPVideoProviderNDAErrorKey","role":"symbol","externalID":"c:@GFPVideoProviderNDAErrorKey","modules":[{"name":"GFPSDK"}],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"GFPVideoProviderNDAErrorKey","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPVideoProviderNDAErrorKey"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoProviderNDAErrorKey":{"navigatorTitle":[{"text":"GFPVideoProviderNDAErrorKey","kind":"identifier"}],"title":"GFPVideoProviderNDAErrorKey","abstract":[],"type":"topic","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoProviderNDAErrorKey","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPVideoProviderNDAErrorKey","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"url":"\/documentation\/gfpsdk\/gfpvideoproviderndaerrorkey","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Global Variable","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"GFPVideoProviderNDAErrorKey","op":"replace"},{"path":"\/metadata\/symbolKind","value":"var","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GFPVideoProviderNDAErrorKey"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"extern"},{"text":" ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"GFPVideoProviderNDAErrorKey"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"op":"replace","value":"GFPVideoProviderNDAErrorKey","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoProviderNDAErrorKey\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoProviderNDAErrorKey\/fragments","value":[{"kind":"identifier","text":"GFPVideoProviderNDAErrorKey"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}