{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"metadata":{"title":"GFPVideoAdManager","externalID":"c:objc(cs)GFPVideoAdManager","role":"symbol","symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPVideoAdManager","kind":"identifier"}],"modules":[{"name":"GFPSDK"}],"navigatorTitle":[{"text":"GFPVideoAdManager","kind":"identifier"}],"roleHeading":"Class"},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"anchor":"Initializers","title":"Initializers","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager\/init(adUnitID:videoView:adParam:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager\/init(adUnitID:videoView:placementType:adParam:videoAdParam:)"],"generated":true},{"title":"Instance Properties","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager\/adInfo","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager\/adParam","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager\/delegate","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager\/displayMode","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager\/pipDelegate","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager\/playerSetting","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager\/qoeDelegate","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager\/renderingSetting","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager\/requestTimeoutInterval","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager\/responseInfo","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager\/rootViewController","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager\/volume"],"generated":true,"anchor":"Instance-Properties"},{"anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager\/destroy()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager\/hideOverlay()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager\/load()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager\/loadAdWith(data:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager\/loadAdWith(dict:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager\/loadAdWith(string:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager\/loadInternal(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager\/moreButtonTapped(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager\/pause()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager\/resume()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager\/showOverlay()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager\/skipButtonTapped(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager\/start()"],"title":"Instance Methods"}],"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject"],"title":"Inherits From"},{"title":"Conforms To","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s7CVarArgP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s23CustomStringConvertibleP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH"],"type":"conformsTo","kind":"relationships"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpvideoadmanager"]},{"paths":["\/documentation\/gfpsdk\/gfpvideoadmanager"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPVideoAdManager","kind":"identifier"}]}]}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdManager/destroy()":{"abstract":[{"type":"text","text":"광고 매니저를 종료 시킵니다."},{"text":" ","type":"text"},{"text":"(재생중 화면 전환이 발생하거나, 어플리케이션 동작과정에서 로드된 광고매니저의 리소스를 해제할 필요가 있는 경우)","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"destroy","kind":"identifier"},{"text":"()","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"destroy","kind":"identifier"}],"type":"topic","url":"\/documentation\/gfpsdk\/gfpvideoadmanager\/destroy()","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager\/destroy()","title":"destroy()","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdManager/init(adUnitID:videoView:placementType:adParam:videoAdParam:)":{"title":"init(adUnitID:videoView:placementType:adParam:videoAdParam:)","url":"\/documentation\/gfpsdk\/gfpvideoadmanager\/init(adunitid:videoview:placementtype:adparam:videoadparam:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithAdUnitID:videoView:placementType:adParam:videoAdParam:"}],"kind":"symbol","type":"topic","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"adUnitID","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"videoView"},{"text":": ","kind":"text"},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"placementType"},{"kind":"text","text":": "},{"text":"GFPVideoPlacementType","kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPVideoPlacementType"},{"kind":"text","text":", "},{"text":"adParam","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPAdParam","text":"GFPAdParam","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"videoAdParam","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPVideoAdParam","text":"GFPVideoAdParam"},{"text":"?)","kind":"text"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager\/init(adUnitID:videoView:placementType:adParam:videoAdParam:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdManager/start()":{"navigatorTitle":[{"text":"start","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"광고를 재생합니다."},{"text":" ","type":"text"},{"type":"text","text":"(광고가 성공적으로 르드된 경우에 호출해주세요.)"}],"url":"\/documentation\/gfpsdk\/gfpvideoadmanager\/start()","title":"start()","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager\/start()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"start","kind":"identifier"},{"text":"()","kind":"text"}],"type":"topic","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdManager":{"type":"topic","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager","role":"symbol","url":"\/documentation\/gfpsdk\/gfpvideoadmanager","title":"GFPVideoAdManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPVideoAdManager"}],"kind":"symbol","navigatorTitle":[{"text":"GFPVideoAdManager","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdManager/responseInfo":{"navigatorTitle":[{"kind":"identifier","text":"responseInfo"}],"title":"responseInfo","url":"\/documentation\/gfpsdk\/gfpvideoadmanager\/responseinfo","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager\/responseInfo","role":"symbol","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"광고 응답 객체"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"responseInfo","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPLoadResponseInfo","text":"GFPLoadResponseInfo"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdManager/pause()":{"url":"\/documentation\/gfpsdk\/gfpvideoadmanager\/pause()","title":"pause()","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager\/pause()","abstract":[{"type":"text","text":"광고 재생을 중지합니다."}],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"pause","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pause"},{"kind":"text","text":"()"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdManager/resume()":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager\/resume()","url":"\/documentation\/gfpsdk\/gfpvideoadmanager\/resume()","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"resume"},{"text":"()","kind":"text"}],"title":"resume()","kind":"symbol","abstract":[{"type":"text","text":"광고 재생을 재개합니다."}],"navigatorTitle":[{"text":"resume","kind":"identifier"}],"role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdManager/hideOverlay()":{"navigatorTitle":[{"text":"hideOverlay","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"hideOverlay()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hideOverlay","kind":"identifier"},{"kind":"text","text":"()"}],"type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager\/hideOverlay()","abstract":[{"text":"광고 영상 위의 Overlay를 숨김니다.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"(광고 재생 중, 광고 영상을 숨겨야 할 경우)"}],"url":"\/documentation\/gfpsdk\/gfpvideoadmanager\/hideoverlay()"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdManager/loadAdWith(dict:)":{"type":"topic","role":"symbol","title":"loadAdWith(dict:)","abstract":[{"type":"text","text":"VideoManager 에 광고 요청, WF 단계를 건너뛰기 위한 요청"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"loadAdWith"},{"kind":"text","text":"("},{"text":"dict","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"])"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager\/loadAdWith(dict:)","url":"\/documentation\/gfpsdk\/gfpvideoadmanager\/loadadwith(dict:)","navigatorTitle":[{"kind":"identifier","text":"loadAdWithDict:"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdManager/init(adUnitID:videoView:adParam:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"adUnitID"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"videoView","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"adParam"},{"kind":"text","text":": "},{"text":"GFPAdParam","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdParam"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"initWithAdUnitID:videoView:adParam:"}],"url":"\/documentation\/gfpsdk\/gfpvideoadmanager\/init(adunitid:videoview:adparam:)","abstract":[],"kind":"symbol","role":"symbol","title":"init(adUnitID:videoView:adParam:)","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager\/init(adUnitID:videoView:adParam:)","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdManager/renderingSetting":{"kind":"symbol","title":"renderingSetting","abstract":[{"type":"text","text":"광고 렌터링 세팅 (Optional)"}],"type":"topic","url":"\/documentation\/gfpsdk\/gfpvideoadmanager\/renderingsetting","navigatorTitle":[{"kind":"identifier","text":"renderingSetting"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager\/renderingSetting","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"renderingSetting"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPVideoAdRenderingSetting","text":"GFPVideoAdRenderingSetting"},{"kind":"text","text":"?"}],"role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdManager/adParam":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"adParam"},{"text":": ","kind":"text"},{"text":"GFPAdParam","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdParam"},{"text":"?","kind":"text"}],"abstract":[{"text":"광고 요청에 사용할 파라미터","type":"text"}],"navigatorTitle":[{"text":"adParam","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpvideoadmanager\/adparam","kind":"symbol","type":"topic","role":"symbol","title":"adParam","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager\/adParam"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdManager/adInfo":{"navigatorTitle":[{"kind":"identifier","text":"adInfo"}],"url":"\/documentation\/gfpsdk\/gfpvideoadmanager\/adinfo","abstract":[{"type":"text","text":"광고 로드 후  광고 정보 (없으면 nil)"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"adInfo","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPVideoAdInfo","text":"GFPVideoAdInfo","kind":"typeIdentifier"}],"role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager\/adInfo","title":"adInfo"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdManager/loadAdWith(string:)":{"title":"loadAdWith(string:)","type":"topic","abstract":[{"type":"text","text":"VideoManager 에 광고 요청, WF 단계를 건너뛰기 위한 요청"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"loadAdWith"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"string"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"url":"\/documentation\/gfpsdk\/gfpvideoadmanager\/loadadwith(string:)","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager\/loadAdWith(string:)","navigatorTitle":[{"kind":"identifier","text":"loadAdWithString:"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdManager/playerSetting":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"playerSetting"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"GFPVideoAdPlayerSetting","preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPVideoAdPlayerSetting"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"playerSetting","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager\/playerSetting","abstract":[{"type":"text","text":"광고 재생 관련 Option. (Audio, Background 관련 Play 동작)"}],"url":"\/documentation\/gfpsdk\/gfpvideoadmanager\/playersetting","type":"topic","title":"playerSetting","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdManager/requestTimeoutInterval":{"abstract":[{"type":"text","text":"광고 요청이후 로드 완료시점까지 타임아웃 (Optional)"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager\/requestTimeoutInterval","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"requestTimeoutInterval"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"}],"type":"topic","navigatorTitle":[{"text":"requestTimeoutInterval","kind":"identifier"}],"title":"requestTimeoutInterval","url":"\/documentation\/gfpsdk\/gfpvideoadmanager\/requesttimeoutinterval"},"doc://com.navercorp.da.gfp.GFPSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s7CVarArgP"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdManager/loadInternal(_:)":{"title":"loadInternal(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"loadInternal","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoMediator","text":"GFPVideoMediator"},{"kind":"text","text":")"}],"url":"\/documentation\/gfpsdk\/gfpvideoadmanager\/loadinternal(_:)","type":"topic","role":"symbol","navigatorTitle":[{"text":"loadInternal:","kind":"identifier"}],"kind":"symbol","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager\/loadInternal(_:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdManager/displayMode":{"title":"displayMode","navigatorTitle":[{"text":"displayMode","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpvideoadmanager\/displaymode","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager\/displayMode","role":"symbol","abstract":[{"text":"광고 재생 전, 재생 도중 관련","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"displayMode","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GFPVideoDisplayMode","preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPVideoDisplayMode"},{"text":"?","kind":"text"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdManager/qoeDelegate":{"abstract":[],"title":"qoeDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"text":"qoeDelegate","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpvideoadmanager\/qoedelegate","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager\/qoeDelegate","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"qoeDelegate","kind":"identifier"},{"kind":"text","text":": (any "},{"preciseIdentifier":"c:objc(pl)GFPVideoAdQoeDelegate","text":"GFPVideoAdQoeDelegate","kind":"typeIdentifier"},{"text":")?","kind":"text"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdManager/skipButtonTapped(_:)":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"skipButtonTapped:"}],"abstract":[{"type":"text","text":"광고 Skip 버튼 클릭을 원하는 경우, action 연결."}],"url":"\/documentation\/gfpsdk\/gfpvideoadmanager\/skipbuttontapped(_:)","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager\/skipButtonTapped(_:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"skipButtonTapped","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":")"}],"title":"skipButtonTapped(_:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdManager/moreButtonTapped(_:)":{"title":"moreButtonTapped(_:)","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager\/moreButtonTapped(_:)","kind":"symbol","type":"topic","role":"symbol","abstract":[{"type":"text","text":"광고 더보기 버튼 클릭을 원하는 경우, action 연결."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"moreButtonTapped","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"keyword","text":"Any"},{"text":")","kind":"text"}],"url":"\/documentation\/gfpsdk\/gfpvideoadmanager\/morebuttontapped(_:)","navigatorTitle":[{"text":"moreButtonTapped:","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdManager/rootViewController":{"abstract":[{"text":"구글 광고 로드를 위해서는 필수 조건 (View hierachy가 있는 ViewController.)","type":"text"}],"type":"topic","title":"rootViewController","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rootViewController","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"url":"\/documentation\/gfpsdk\/gfpvideoadmanager\/rootviewcontroller","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager\/rootViewController","navigatorTitle":[{"kind":"identifier","text":"rootViewController"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdManager/loadAdWith(data:)":{"navigatorTitle":[{"kind":"identifier","text":"loadAdWithData:"}],"type":"topic","title":"loadAdWith(data:)","kind":"symbol","url":"\/documentation\/gfpsdk\/gfpvideoadmanager\/loadadwith(data:)","abstract":[{"text":"VideoManager 에 광고 요청, WF 단계를 건너뛰기 위한 요청","type":"text"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager\/loadAdWith(data:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"loadAdWith","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"data"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":")"}],"role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdManager/volume":{"type":"topic","title":"volume","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"volume","kind":"identifier"},{"kind":"text","text":": "},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"}],"abstract":[{"text":"광고 볼륨  세팅 (Optional)","type":"text"},{"type":"text","text":" "},{"type":"text","text":"From 0 (muted) to 1 (loudest). Default value is 1."}],"url":"\/documentation\/gfpsdk\/gfpvideoadmanager\/volume","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"volume"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager\/volume"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdManager/pipDelegate":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pipDelegate"},{"text":": (any ","kind":"text"},{"kind":"typeIdentifier","text":"GFPVideoAdPIPDelegate","preciseIdentifier":"c:objc(pl)GFPVideoAdPIPDelegate"},{"kind":"text","text":")?"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager\/pipDelegate","type":"topic","abstract":[],"url":"\/documentation\/gfpsdk\/gfpvideoadmanager\/pipdelegate","title":"pipDelegate","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"pipDelegate","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdManager/showOverlay()":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager\/showOverlay()","url":"\/documentation\/gfpsdk\/gfpvideoadmanager\/showoverlay()","role":"symbol","title":"showOverlay()","abstract":[{"type":"text","text":"광고 영상 위의 Overlay를 노출합니다."},{"type":"text","text":" "},{"type":"text","text":"(광고 재생 중, 광고 영상만 노출해야 할 경우)"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"showOverlay"},{"text":"()","kind":"text"}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"showOverlay"}]},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdManager/load()":{"role":"symbol","abstract":[{"type":"text","text":"광고를 요청합니다."},{"text":" ","type":"text"},{"text":"응답결과는 GFPVideoAdManagerDelegate 를 통해 받으실 수 있습니다.","type":"text"}],"title":"load()","navigatorTitle":[{"kind":"identifier","text":"load"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"load","kind":"identifier"},{"kind":"text","text":"()"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager\/load()","type":"topic","kind":"symbol","url":"\/documentation\/gfpsdk\/gfpvideoadmanager\/load()"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdManager/delegate":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": (any "},{"preciseIdentifier":"c:objc(pl)GFPVideoAdManagerDelegate","kind":"typeIdentifier","text":"GFPVideoAdManagerDelegate"},{"text":")?","kind":"text"}],"kind":"symbol","navigatorTitle":[{"text":"delegate","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager\/delegate","abstract":[],"role":"symbol","url":"\/documentation\/gfpsdk\/gfpvideoadmanager\/delegate","title":"delegate","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"GFPVideoAdManager"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GFPVideoAdManager"}]},{"value":[{"text":"GFPVideoAdManager","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager\/adInfo","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager\/adParam","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager\/delegate","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager\/displayMode","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager\/pipDelegate","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager\/playerSetting","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager\/qoeDelegate","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager\/renderingSetting","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager\/requestTimeoutInterval","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager\/responseInfo","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager\/rootViewController","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager\/volume"],"title":"Instance Properties"},{"anchor":"Instance-Methods","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager\/destroy()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager\/hideOverlay()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager\/init(adUnitID:videoView:adParam:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager\/init(adUnitID:videoView:placementType:adParam:videoAdParam:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager\/load()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager\/loadAdWith(data:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager\/loadAdWith(dict:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager\/loadAdWith(string:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager\/loadInternal(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager\/moreButtonTapped(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager\/pause()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager\/resume()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager\/showOverlay()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager\/skipButtonTapped(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager\/start()"],"title":"Instance Methods","generated":true}],"path":"\/topicSections","op":"replace"},{"op":"replace","value":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships"}],"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"GFPVideoAdManager","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManager~1destroy()\/title","op":"replace","value":"destroy"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManager~1destroy()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"destroy"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManager~1init(adUnitID:videoView:placementType:adParam:videoAdParam:)\/title","op":"replace","value":"initWithAdUnitID:videoView:placementType:adParam:videoAdParam:"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManager~1init(adUnitID:videoView:placementType:adParam:videoAdParam:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithAdUnitID:videoView:placementType:adParam:videoAdParam:","kind":"identifier"}]},{"value":"start","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManager~1start()\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManager~1start()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"start"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManager\/title","value":"GFPVideoAdManager"},{"value":[{"text":"GFPVideoAdManager","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManager\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManager\/navigatorTitle","value":[{"text":"GFPVideoAdManager","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManager~1responseInfo\/title","value":"responseInfo","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManager~1responseInfo\/fragments","value":[{"kind":"identifier","text":"responseInfo"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManager~1pause()\/title","value":"pause","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManager~1pause()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"pause"}]},{"op":"replace","value":"resume","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManager~1resume()\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManager~1resume()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"resume","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManager~1hideOverlay()\/title","value":"hideOverlay"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManager~1hideOverlay()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"hideOverlay","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManager~1loadAdWith(dict:)\/title","value":"loadAdWithDict:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"loadAdWithDict:"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManager~1loadAdWith(dict:)\/fragments"},{"value":"initWithAdUnitID:videoView:adParam:","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManager~1init(adUnitID:videoView:adParam:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithAdUnitID:videoView:adParam:"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManager~1init(adUnitID:videoView:adParam:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManager~1renderingSetting\/title","op":"replace","value":"renderingSetting"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManager~1renderingSetting\/fragments","op":"replace","value":[{"text":"renderingSetting","kind":"identifier"}]},{"value":"adParam","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManager~1adParam\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"adParam"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManager~1adParam\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManager~1adInfo\/title","value":"adInfo"},{"value":[{"kind":"identifier","text":"adInfo"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManager~1adInfo\/fragments"},{"op":"replace","value":"loadAdWithString:","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManager~1loadAdWith(string:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"loadAdWithString:"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManager~1loadAdWith(string:)\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManager~1playerSetting\/title","value":"playerSetting","op":"replace"},{"op":"replace","value":[{"text":"playerSetting","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManager~1playerSetting\/fragments"},{"value":"requestTimeoutInterval","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManager~1requestTimeoutInterval\/title"},{"value":[{"kind":"identifier","text":"requestTimeoutInterval"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManager~1requestTimeoutInterval\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManager~1loadInternal(_:)\/title","value":"loadInternal:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManager~1loadInternal(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"loadInternal:"}]},{"op":"replace","value":"displayMode","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManager~1displayMode\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManager~1displayMode\/fragments","op":"replace","value":[{"text":"displayMode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManager~1qoeDelegate\/title","value":"qoeDelegate","op":"replace"},{"value":[{"kind":"identifier","text":"qoeDelegate"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManager~1qoeDelegate\/fragments","op":"replace"},{"op":"replace","value":"skipButtonTapped:","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManager~1skipButtonTapped(_:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"skipButtonTapped:"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManager~1skipButtonTapped(_:)\/fragments"},{"value":"moreButtonTapped:","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManager~1moreButtonTapped(_:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"moreButtonTapped:"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManager~1moreButtonTapped(_:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManager~1rootViewController\/title","value":"rootViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManager~1rootViewController\/fragments","value":[{"text":"rootViewController","kind":"identifier"}]},{"op":"replace","value":"loadAdWithData:","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManager~1loadAdWith(data:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"loadAdWithData:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManager~1loadAdWith(data:)\/fragments"},{"op":"replace","value":"volume","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManager~1volume\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManager~1volume\/fragments","op":"replace","value":[{"kind":"identifier","text":"volume"}]},{"op":"replace","value":"pipDelegate","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManager~1pipDelegate\/title"},{"value":[{"text":"pipDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManager~1pipDelegate\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManager~1showOverlay()\/title","value":"showOverlay"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManager~1showOverlay()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"showOverlay"}]},{"value":"load","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManager~1load()\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"load","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManager~1load()\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManager~1delegate\/title","value":"delegate","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManager~1delegate\/fragments","value":[{"kind":"identifier","text":"delegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}