{"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"role":"symbol","modules":[{"name":"GFPSDK"}],"externalID":"c:@M@GFPSDK@objc(cs)GFPVideoAdParam","symbolKind":"class","title":"GFPVideoAdParam","navigatorTitle":[{"text":"GFPVideoAdParam","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPVideoAdParam","kind":"identifier"}],"roleHeading":"Class"},"relationshipsSections":[{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"},{"title":"Conforms To","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSCopying","doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s7CVarArgP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s23CustomStringConvertibleP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH"],"kind":"relationships","type":"conformsTo"}],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpvideoadparam"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gfpsdk\/gfpvideoadparam"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objcMembers","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPVideoAdParam"}]}],"kind":"declarations"},{"kind":"content","content":[{"anchor":"overview","type":"heading","level":2,"text":"Overview"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Schedule Load 이후 비디오 광고 요청에 필요한 별도 Param 생성.","type":"text"}]}]}],"type":"unorderedList"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdParam"},"topicSections":[{"anchor":"Initializers","generated":true,"title":"Initializers","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdParam\/init(scheduleID:requestID:contentLength:)"]},{"generated":true,"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdParam\/contentLength","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdParam\/hasRemind","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdParam\/remindRequest","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdParam\/requestID","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdParam\/scheduleID","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdParam\/startDelay"],"anchor":"Instance-Properties","title":"Instance Properties"},{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdParam\/copy(with:)"],"anchor":"Instance-Methods"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"references":{"doc://com.navercorp.da.gfp.GFPSDK/objc(cs)NSObject":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdParam/requestID":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdParam\/requestID","title":"requestID","abstract":[],"navigatorTitle":[{"text":"requestID","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpvideoadparam\/requestid","role":"symbol","kind":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"requestID","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdParam/contentLength":{"type":"topic","abstract":[],"kind":"symbol","role":"symbol","title":"contentLength","url":"\/documentation\/gfpsdk\/gfpvideoadparam\/contentlength","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"contentLength","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"}],"navigatorTitle":[{"text":"contentLength","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdParam\/contentLength"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdParam/scheduleID":{"abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"scheduleID","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"scheduleID"}],"type":"topic","url":"\/documentation\/gfpsdk\/gfpvideoadparam\/scheduleid","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdParam\/scheduleID","title":"scheduleID","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdParam":{"abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPVideoAdParam"}],"role":"symbol","navigatorTitle":[{"text":"GFPVideoAdParam","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdParam","url":"\/documentation\/gfpsdk\/gfpvideoadparam","kind":"symbol","title":"GFPVideoAdParam"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdParam/startDelay":{"navigatorTitle":[{"kind":"identifier","text":"startDelay"}],"title":"startDelay","url":"\/documentation\/gfpsdk\/gfpvideoadparam\/startdelay","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdParam\/startDelay","role":"symbol","type":"topic","kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"startDelay","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}]},"doc://com.navercorp.da.gfp.GFPSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)NSObject":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdParam/remindRequest":{"kind":"symbol","title":"remindRequest","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"remindRequest"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"abstract":[],"url":"\/documentation\/gfpsdk\/gfpvideoadparam\/remindrequest","navigatorTitle":[{"kind":"identifier","text":"remindRequest"}],"type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdParam\/remindRequest"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)NSCopying":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSCopying","title":"NSCopying"},"doc://com.navercorp.da.gfp.GFPSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH","title":"Swift.Hashable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdParam/hasRemind":{"role":"symbol","abstract":[],"title":"hasRemind","navigatorTitle":[{"text":"hasRemind","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"hasRemind","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdParam\/hasRemind","url":"\/documentation\/gfpsdk\/gfpvideoadparam\/hasremind","kind":"symbol","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.navercorp.da.gfp.GFPSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdParam/copy(with:)":{"kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdParam\/copy(with:)","title":"copy(with:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"copy","kind":"identifier"},{"kind":"text","text":"("},{"text":"with","kind":"externalParam"},{"kind":"text","text":": "},{"text":"NSZone","kind":"typeIdentifier","preciseIdentifier":"s:10ObjectiveC6NSZoneV"},{"kind":"text","text":"?) -> "},{"text":"Any","kind":"keyword"}],"navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}],"abstract":[],"role":"symbol","type":"topic","url":"\/documentation\/gfpsdk\/gfpvideoadparam\/copy(with:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdParam/init(scheduleID:requestID:contentLength:)":{"url":"\/documentation\/gfpsdk\/gfpvideoadparam\/init(scheduleid:requestid:contentlength:)","title":"init(scheduleID:requestID:contentLength:)","type":"topic","navigatorTitle":[{"text":"initWithScheduleID:requestID:contentLength:","kind":"identifier"}],"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"scheduleID"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"requestID","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"contentLength"},{"kind":"text","text":": "},{"text":"Float","preciseIdentifier":"s:Sf","kind":"typeIdentifier"},{"kind":"text","text":")"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdParam\/init(scheduleID:requestID:contentLength:)"},"doc://com.navercorp.da.gfp.GFPSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","title":"Swift.Equatable"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"GFPVideoAdParam"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","value":[{"text":"GFPVideoAdParam","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"GFPVideoAdParam","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdParam\/contentLength","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdParam\/hasRemind","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdParam\/remindRequest","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdParam\/requestID","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdParam\/scheduleID","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdParam\/startDelay"],"generated":true},{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdParam\/copy(with:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdParam\/init(scheduleID:requestID:contentLength:)"],"anchor":"Instance-Methods","title":"Instance Methods","generated":true}],"path":"\/topicSections"},{"value":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject"]},{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSCopying"],"title":"Conforms To","type":"conformsTo","kind":"relationships"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPVideoAdParam"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","value":"requestID","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdParam~1requestID\/title"},{"op":"replace","value":[{"text":"requestID","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdParam~1requestID\/fragments"},{"op":"replace","value":"contentLength","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdParam~1contentLength\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdParam~1contentLength\/fragments","value":[{"kind":"identifier","text":"contentLength"}],"op":"replace"},{"value":"scheduleID","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdParam~1scheduleID\/title","op":"replace"},{"value":[{"text":"scheduleID","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdParam~1scheduleID\/fragments"},{"value":"GFPVideoAdParam","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdParam\/title","op":"replace"},{"value":[{"text":"GFPVideoAdParam","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdParam\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdParam\/navigatorTitle","value":[{"kind":"identifier","text":"GFPVideoAdParam"}]},{"value":"startDelay","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdParam~1startDelay\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdParam~1startDelay\/fragments","op":"replace","value":[{"text":"startDelay","kind":"identifier"}]},{"op":"replace","value":"remindRequest","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdParam~1remindRequest\/title"},{"value":[{"kind":"identifier","text":"remindRequest"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdParam~1remindRequest\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdParam~1hasRemind\/title","value":"hasRemind"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdParam~1hasRemind\/fragments","value":[{"kind":"identifier","text":"hasRemind"}]},{"op":"replace","value":"copyWithZone:","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdParam~1copy(with:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"copyWithZone:"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdParam~1copy(with:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdParam~1init(scheduleID:requestID:contentLength:)\/title","value":"initWithScheduleID:requestID:contentLength:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"initWithScheduleID:requestID:contentLength:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdParam~1init(scheduleID:requestID:contentLength:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}