{"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"sections":[],"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpvideoadaptordelegate"]},{"paths":["\/documentation\/gfpsdk\/gfpvideoadaptordelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPVideoAdaptorDelegate"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject","text":"NSObjectProtocol"}],"platforms":["iOS"],"languages":["swift"]}]}],"topicSections":[{"generated":true,"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdaptorDelegate\/videoAdAdaptor(_:didChangeCurrentTime:totalTime:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdaptorDelegate\/videoAdAdaptor(_:didReceive:)-m66","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdaptorDelegate\/videoAdAdaptor(_:didReceive:)-sn3r","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdaptorDelegate\/videoAdAdaptor(_:playControlWillHide:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdaptorDelegate\/videoAdAdaptor(_:playControlWillShow:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdaptorDelegate\/videoAdAdaptorDidDismissDefault(inAppBrowser:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdaptorDelegate\/videoAdAdaptorDidPresentDefault(inAppBrowser:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdaptorDelegate\/videoAdCanBeSkipped(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdaptorDelegate\/videoAdCloseBtnTapped(inPIP:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdaptorDelegate\/videoAdReturnBtnTapped(inPIP:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdaptorDelegate\/videoAdWasClicked(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdaptorDelegate\/videoAdWasCompleted(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdaptorDelegate\/videoAdWasPaused(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdaptorDelegate\/videoAdWasResumed(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdaptorDelegate\/videoAdWasSkipped(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdaptorDelegate\/videoAdWasStarted(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdaptorDelegate\/videoAdaptor(_:didFailWithError:)"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"externalID":"c:objc(pl)GFPVideoAdaptorDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"GFPVideoAdaptorDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"GFPVideoAdaptorDelegate","kind":"identifier"}],"modules":[{"name":"GFPSDK"}],"symbolKind":"protocol","role":"symbol","roleHeading":"Protocol","title":"GFPVideoAdaptorDelegate"},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdaptorDelegate","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdaptorDelegate/videoAdaptor(_:didFailWithError:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"videoAdaptor","kind":"identifier"},{"text":"(any ","kind":"text"},{"text":"GFPAdAdaptor","preciseIdentifier":"c:objc(cs)GFPAdAdaptor","kind":"typeIdentifier"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)GFPVideoAdapting","text":"GFPVideoAdapting"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFailWithError"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"GFPError","preciseIdentifier":"c:@M@NaverAdsServices@objc(cs)GFPError"},{"text":")","kind":"text"}],"abstract":[],"url":"\/documentation\/gfpsdk\/gfpvideoadaptordelegate\/videoadaptor(_:didfailwitherror:)","navigatorTitle":[{"kind":"identifier","text":"videoAdaptor:didFailWithError:"}],"required":true,"kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdaptorDelegate\/videoAdaptor(_:didFailWithError:)","type":"topic","title":"videoAdaptor(_:didFailWithError:)","role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdaptorDelegate/videoAdAdaptorDidPresentDefault(inAppBrowser:)":{"type":"topic","title":"videoAdAdaptorDidPresentDefault(inAppBrowser:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"videoAdAdaptorDidPresentDefault","kind":"identifier"},{"kind":"text","text":"("},{"text":"inAppBrowser","kind":"externalParam"},{"kind":"text","text":": any "},{"text":"GFPAdAdaptor","preciseIdentifier":"c:objc(cs)GFPAdAdaptor","kind":"typeIdentifier"},{"text":" & ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)GFPVideoAdapting","text":"GFPVideoAdapting"},{"text":")","kind":"text"}],"abstract":[],"url":"\/documentation\/gfpsdk\/gfpvideoadaptordelegate\/videoadadaptordidpresentdefault(inappbrowser:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"videoAdAdaptorDidPresentDefaultInAppBrowser:"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdaptorDelegate\/videoAdAdaptorDidPresentDefault(inAppBrowser:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdaptorDelegate/videoAdWasSkipped(_:)":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdaptorDelegate\/videoAdWasSkipped(_:)","title":"videoAdWasSkipped(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"videoAdWasSkipped","kind":"identifier"},{"text":"(any ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPAdAdaptor","text":"GFPAdAdaptor","kind":"typeIdentifier"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"GFPVideoAdapting","preciseIdentifier":"c:objc(pl)GFPVideoAdapting"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"videoAdWasSkipped:"}],"url":"\/documentation\/gfpsdk\/gfpvideoadaptordelegate\/videoadwasskipped(_:)","abstract":[],"kind":"symbol","type":"topic","required":true,"role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdaptorDelegate/videoAdReturnBtnTapped(inPIP:)":{"required":true,"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"videoAdReturnBtnTapped","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"inPIP"},{"kind":"text","text":": any "},{"text":"GFPAdAdaptor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdAdaptor"},{"kind":"text","text":" & "},{"text":"GFPVideoAdapting","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)GFPVideoAdapting"},{"kind":"text","text":")"}],"abstract":[],"navigatorTitle":[{"text":"videoAdReturnBtnTappedInPIP:","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpvideoadaptordelegate\/videoadreturnbtntapped(inpip:)","kind":"symbol","type":"topic","role":"symbol","title":"videoAdReturnBtnTapped(inPIP:)","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdaptorDelegate\/videoAdReturnBtnTapped(inPIP:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdaptorDelegate/videoAdCloseBtnTapped(inPIP:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"videoAdCloseBtnTapped","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"inPIP"},{"text":": any ","kind":"text"},{"text":"GFPAdAdaptor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdAdaptor"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)GFPVideoAdapting","text":"GFPVideoAdapting"},{"text":")","kind":"text"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"videoAdCloseBtnTappedInPIP:"}],"url":"\/documentation\/gfpsdk\/gfpvideoadaptordelegate\/videoadclosebtntapped(inpip:)","kind":"symbol","type":"topic","role":"symbol","title":"videoAdCloseBtnTapped(inPIP:)","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdaptorDelegate\/videoAdCloseBtnTapped(inPIP:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdaptorDelegate/videoAdAdaptor(_:didReceive:)-m66":{"navigatorTitle":[{"text":"videoAdAdaptor:didReceiveAccessLog:","kind":"identifier"}],"required":true,"url":"\/documentation\/gfpsdk\/gfpvideoadaptordelegate\/videoadadaptor(_:didreceive:)-m66","kind":"symbol","role":"symbol","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdaptorDelegate\/videoAdAdaptor(_:didReceive:)-m66","type":"topic","title":"videoAdAdaptor(_:didReceive:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"videoAdAdaptor"},{"text":"(any ","kind":"text"},{"kind":"typeIdentifier","text":"GFPAdAdaptor","preciseIdentifier":"c:objc(cs)GFPAdAdaptor"},{"text":" & ","kind":"text"},{"kind":"typeIdentifier","text":"GFPVideoAdapting","preciseIdentifier":"c:objc(pl)GFPVideoAdapting"},{"text":", ","kind":"text"},{"text":"didReceive","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"AVPlayerItemAccessLog","preciseIdentifier":"c:objc(cs)AVPlayerItemAccessLog"},{"kind":"text","text":")"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdaptorDelegate/videoAdWasStarted(_:)":{"required":true,"navigatorTitle":[{"kind":"identifier","text":"videoAdWasStarted:"}],"title":"videoAdWasStarted(_:)","abstract":[],"type":"topic","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdaptorDelegate\/videoAdWasStarted(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"videoAdWasStarted","kind":"identifier"},{"text":"(any ","kind":"text"},{"text":"GFPAdAdaptor","preciseIdentifier":"c:objc(cs)GFPAdAdaptor","kind":"typeIdentifier"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"GFPVideoAdapting","preciseIdentifier":"c:objc(pl)GFPVideoAdapting"},{"text":")","kind":"text"}],"url":"\/documentation\/gfpsdk\/gfpvideoadaptordelegate\/videoadwasstarted(_:)","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdaptorDelegate/videoAdWasResumed(_:)":{"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"videoAdWasResumed","kind":"identifier"},{"kind":"text","text":"(any "},{"text":"GFPAdAdaptor","preciseIdentifier":"c:objc(cs)GFPAdAdaptor","kind":"typeIdentifier"},{"kind":"text","text":" & "},{"preciseIdentifier":"c:objc(pl)GFPVideoAdapting","kind":"typeIdentifier","text":"GFPVideoAdapting"},{"kind":"text","text":")"}],"role":"symbol","navigatorTitle":[{"text":"videoAdWasResumed:","kind":"identifier"}],"abstract":[],"title":"videoAdWasResumed(_:)","type":"topic","url":"\/documentation\/gfpsdk\/gfpvideoadaptordelegate\/videoadwasresumed(_:)","required":true,"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdaptorDelegate\/videoAdWasResumed(_:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdaptorDelegate/videoAdAdaptor(_:didReceive:)-sn3r":{"abstract":[],"title":"videoAdAdaptor(_:didReceive:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"videoAdAdaptor","kind":"identifier"},{"text":"(any ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPAdAdaptor","kind":"typeIdentifier","text":"GFPAdAdaptor"},{"kind":"text","text":" & "},{"preciseIdentifier":"c:objc(pl)GFPVideoAdapting","text":"GFPVideoAdapting","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"didReceive","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:objc(cs)AVPlayerItemAccessLogEvent","kind":"typeIdentifier","text":"AVPlayerItemAccessLogEvent"},{"text":"])","kind":"text"}],"url":"\/documentation\/gfpsdk\/gfpvideoadaptordelegate\/videoadadaptor(_:didreceive:)-sn3r","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdaptorDelegate\/videoAdAdaptor(_:didReceive:)-sn3r","navigatorTitle":[{"kind":"identifier","text":"videoAdAdaptor:didReceiveAccessLogEvents:"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdaptorDelegate/videoAdWasCompleted(_:)":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdaptorDelegate\/videoAdWasCompleted(_:)","role":"symbol","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"videoAdWasCompleted","kind":"identifier"},{"text":"(any ","kind":"text"},{"text":"GFPAdAdaptor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdAdaptor"},{"text":" & ","kind":"text"},{"text":"GFPVideoAdapting","preciseIdentifier":"c:objc(pl)GFPVideoAdapting","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"videoAdWasCompleted:"}],"abstract":[],"title":"videoAdWasCompleted(_:)","url":"\/documentation\/gfpsdk\/gfpvideoadaptordelegate\/videoadwascompleted(_:)","type":"topic","required":true},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdaptorDelegate/videoAdAdaptor(_:didChangeCurrentTime:totalTime:)":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdaptorDelegate\/videoAdAdaptor(_:didChangeCurrentTime:totalTime:)","navigatorTitle":[{"text":"videoAdAdaptor:didChangeCurrentTime:totalTime:","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[],"title":"videoAdAdaptor(_:didChangeCurrentTime:totalTime:)","url":"\/documentation\/gfpsdk\/gfpvideoadaptordelegate\/videoadadaptor(_:didchangecurrenttime:totaltime:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"videoAdAdaptor"},{"text":"(any ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPAdAdaptor","kind":"typeIdentifier","text":"GFPAdAdaptor"},{"text":" & ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)GFPVideoAdapting","text":"GFPVideoAdapting"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didChangeCurrentTime"},{"kind":"text","text":": "},{"text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"totalTime"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":")","kind":"text"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdaptorDelegate":{"navigatorTitle":[{"kind":"identifier","text":"GFPVideoAdaptorDelegate"}],"type":"topic","url":"\/documentation\/gfpsdk\/gfpvideoadaptordelegate","kind":"symbol","abstract":[],"title":"GFPVideoAdaptorDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPVideoAdaptorDelegate"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdaptorDelegate","role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdaptorDelegate/videoAdWasPaused(_:)":{"type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdaptorDelegate\/videoAdWasPaused(_:)","abstract":[],"title":"videoAdWasPaused(_:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"videoAdWasPaused"},{"kind":"text","text":"(any "},{"text":"GFPAdAdaptor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdAdaptor"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"GFPVideoAdapting","preciseIdentifier":"c:objc(pl)GFPVideoAdapting"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"videoAdWasPaused:","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpvideoadaptordelegate\/videoadwaspaused(_:)","required":true,"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdaptorDelegate/videoAdAdaptorDidDismissDefault(inAppBrowser:)":{"url":"\/documentation\/gfpsdk\/gfpvideoadaptordelegate\/videoadadaptordiddismissdefault(inappbrowser:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"videoAdAdaptorDidDismissDefault","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"inAppBrowser"},{"kind":"text","text":": any "},{"preciseIdentifier":"c:objc(cs)GFPAdAdaptor","text":"GFPAdAdaptor","kind":"typeIdentifier"},{"text":" & ","kind":"text"},{"kind":"typeIdentifier","text":"GFPVideoAdapting","preciseIdentifier":"c:objc(pl)GFPVideoAdapting"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdaptorDelegate\/videoAdAdaptorDidDismissDefault(inAppBrowser:)","kind":"symbol","navigatorTitle":[{"text":"videoAdAdaptorDidDismissDefaultInAppBrowser:","kind":"identifier"}],"required":true,"role":"symbol","title":"videoAdAdaptorDidDismissDefault(inAppBrowser:)","type":"topic","abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdaptorDelegate/videoAdAdaptor(_:playControlWillHide:)":{"abstract":[],"url":"\/documentation\/gfpsdk\/gfpvideoadaptordelegate\/videoadadaptor(_:playcontrolwillhide:)","role":"symbol","title":"videoAdAdaptor(_:playControlWillHide:)","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdaptorDelegate\/videoAdAdaptor(_:playControlWillHide:)","type":"topic","navigatorTitle":[{"text":"videoAdAdaptor:playControlWillHide:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"videoAdAdaptor","kind":"identifier"},{"kind":"text","text":"(any "},{"text":"GFPAdAdaptor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdAdaptor"},{"text":" & ","kind":"text"},{"text":"GFPVideoAdapting","preciseIdentifier":"c:objc(pl)GFPVideoAdapting","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"playControlWillHide"},{"kind":"text","text":": "},{"text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdaptorDelegate/videoAdAdaptor(_:playControlWillShow:)":{"title":"videoAdAdaptor(_:playControlWillShow:)","type":"topic","abstract":[],"url":"\/documentation\/gfpsdk\/gfpvideoadaptordelegate\/videoadadaptor(_:playcontrolwillshow:)","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdaptorDelegate\/videoAdAdaptor(_:playControlWillShow:)","required":true,"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"videoAdAdaptor:playControlWillShow:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"videoAdAdaptor"},{"kind":"text","text":"(any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdAdaptor","text":"GFPAdAdaptor"},{"kind":"text","text":" & "},{"text":"GFPVideoAdapting","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)GFPVideoAdapting"},{"text":", ","kind":"text"},{"text":"playControlWillShow","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"TimeInterval"},{"kind":"text","text":")"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdaptorDelegate/videoAdWasClicked(_:)":{"required":true,"navigatorTitle":[{"text":"videoAdWasClicked:","kind":"identifier"}],"title":"videoAdWasClicked(_:)","abstract":[],"type":"topic","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdaptorDelegate\/videoAdWasClicked(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"videoAdWasClicked"},{"kind":"text","text":"(any "},{"text":"GFPAdAdaptor","preciseIdentifier":"c:objc(cs)GFPAdAdaptor","kind":"typeIdentifier"},{"kind":"text","text":" & "},{"preciseIdentifier":"c:objc(pl)GFPVideoAdapting","kind":"typeIdentifier","text":"GFPVideoAdapting"},{"text":")","kind":"text"}],"url":"\/documentation\/gfpsdk\/gfpvideoadaptordelegate\/videoadwasclicked(_:)","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdaptorDelegate/videoAdCanBeSkipped(_:)":{"url":"\/documentation\/gfpsdk\/gfpvideoadaptordelegate\/videoadcanbeskipped(_:)","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdaptorDelegate\/videoAdCanBeSkipped(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"videoAdCanBeSkipped","kind":"identifier"},{"text":"(any ","kind":"text"},{"text":"GFPAdAdaptor","preciseIdentifier":"c:objc(cs)GFPAdAdaptor","kind":"typeIdentifier"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)GFPVideoAdapting","text":"GFPVideoAdapting"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"videoAdCanBeSkipped:","kind":"identifier"}],"type":"topic","kind":"symbol","title":"videoAdCanBeSkipped(_:)","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Protocol","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"GFPVideoAdaptorDelegate","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","value":[{"text":"GFPVideoAdaptorDelegate","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":[{"text":"GFPVideoAdaptorDelegate","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdaptorDelegate\/videoAdAdaptor(_:didChangeCurrentTime:totalTime:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdaptorDelegate\/videoAdAdaptor(_:didReceive:)-m66","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdaptorDelegate\/videoAdAdaptor(_:didReceive:)-sn3r","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdaptorDelegate\/videoAdAdaptor(_:playControlWillHide:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdaptorDelegate\/videoAdAdaptor(_:playControlWillShow:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdaptorDelegate\/videoAdAdaptorDidDismissDefault(inAppBrowser:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdaptorDelegate\/videoAdAdaptorDidPresentDefault(inAppBrowser:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdaptorDelegate\/videoAdCanBeSkipped(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdaptorDelegate\/videoAdCloseBtnTapped(inPIP:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdaptorDelegate\/videoAdReturnBtnTapped(inPIP:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdaptorDelegate\/videoAdWasClicked(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdaptorDelegate\/videoAdWasCompleted(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdaptorDelegate\/videoAdWasPaused(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdaptorDelegate\/videoAdWasResumed(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdaptorDelegate\/videoAdWasSkipped(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdaptorDelegate\/videoAdWasStarted(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdaptorDelegate\/videoAdaptor(_:didFailWithError:)"],"generated":true}]},{"path":"\/relationshipsSections","op":"replace","value":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject"],"kind":"relationships"}]},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@protocol"},{"text":" ","kind":"text"},{"text":"GFPVideoAdaptorDelegate","kind":"identifier"},{"kind":"text","text":" <"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"},{"kind":"text","text":">"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"videoAdaptor:didFailWithError:","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdaptorDelegate~1videoAdaptor(_:didFailWithError:)\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdaptorDelegate~1videoAdaptor(_:didFailWithError:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"videoAdaptor:didFailWithError:","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"videoAdAdaptorDidPresentDefaultInAppBrowser:","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdaptorDelegate~1videoAdAdaptorDidPresentDefault(inAppBrowser:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"videoAdAdaptorDidPresentDefaultInAppBrowser:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdaptorDelegate~1videoAdAdaptorDidPresentDefault(inAppBrowser:)\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdaptorDelegate~1videoAdWasSkipped(_:)\/title","value":"videoAdWasSkipped:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"videoAdWasSkipped:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdaptorDelegate~1videoAdWasSkipped(_:)\/fragments","op":"replace"},{"value":"videoAdReturnBtnTappedInPIP:","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdaptorDelegate~1videoAdReturnBtnTapped(inPIP:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"videoAdReturnBtnTappedInPIP:"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdaptorDelegate~1videoAdReturnBtnTapped(inPIP:)\/fragments"},{"value":"videoAdCloseBtnTappedInPIP:","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdaptorDelegate~1videoAdCloseBtnTapped(inPIP:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdaptorDelegate~1videoAdCloseBtnTapped(inPIP:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"videoAdCloseBtnTappedInPIP:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdaptorDelegate~1videoAdAdaptor(_:didReceive:)-m66\/title","op":"replace","value":"videoAdAdaptor:didReceiveAccessLog:"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdaptorDelegate~1videoAdAdaptor(_:didReceive:)-m66\/fragments","value":[{"text":"- ","kind":"text"},{"text":"videoAdAdaptor:didReceiveAccessLog:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdaptorDelegate~1videoAdWasStarted(_:)\/title","value":"videoAdWasStarted:","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdaptorDelegate~1videoAdWasStarted(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"videoAdWasStarted:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdaptorDelegate~1videoAdWasResumed(_:)\/title","value":"videoAdWasResumed:"},{"value":[{"kind":"text","text":"- "},{"text":"videoAdWasResumed:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdaptorDelegate~1videoAdWasResumed(_:)\/fragments"},{"value":"videoAdAdaptor:didReceiveAccessLogEvents:","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdaptorDelegate~1videoAdAdaptor(_:didReceive:)-sn3r\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"videoAdAdaptor:didReceiveAccessLogEvents:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdaptorDelegate~1videoAdAdaptor(_:didReceive:)-sn3r\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdaptorDelegate~1videoAdWasCompleted(_:)\/title","value":"videoAdWasCompleted:"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdaptorDelegate~1videoAdWasCompleted(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"videoAdWasCompleted:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdaptorDelegate~1videoAdAdaptor(_:didChangeCurrentTime:totalTime:)\/title","value":"videoAdAdaptor:didChangeCurrentTime:totalTime:"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdaptorDelegate~1videoAdAdaptor(_:didChangeCurrentTime:totalTime:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"videoAdAdaptor:didChangeCurrentTime:totalTime:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdaptorDelegate\/title","value":"GFPVideoAdaptorDelegate"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdaptorDelegate\/fragments","op":"replace","value":[{"text":"GFPVideoAdaptorDelegate","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"GFPVideoAdaptorDelegate"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdaptorDelegate\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdaptorDelegate~1videoAdWasPaused(_:)\/title","op":"replace","value":"videoAdWasPaused:"},{"value":[{"text":"- ","kind":"text"},{"text":"videoAdWasPaused:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdaptorDelegate~1videoAdWasPaused(_:)\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdaptorDelegate~1videoAdAdaptorDidDismissDefault(inAppBrowser:)\/title","value":"videoAdAdaptorDidDismissDefaultInAppBrowser:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"videoAdAdaptorDidDismissDefaultInAppBrowser:"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdaptorDelegate~1videoAdAdaptorDidDismissDefault(inAppBrowser:)\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdaptorDelegate~1videoAdAdaptor(_:playControlWillHide:)\/title","op":"replace","value":"videoAdAdaptor:playControlWillHide:"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdaptorDelegate~1videoAdAdaptor(_:playControlWillHide:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"videoAdAdaptor:playControlWillHide:","kind":"identifier"}]},{"op":"replace","value":"videoAdAdaptor:playControlWillShow:","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdaptorDelegate~1videoAdAdaptor(_:playControlWillShow:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"videoAdAdaptor:playControlWillShow:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdaptorDelegate~1videoAdAdaptor(_:playControlWillShow:)\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdaptorDelegate~1videoAdWasClicked(_:)\/title","value":"videoAdWasClicked:","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdaptorDelegate~1videoAdWasClicked(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"videoAdWasClicked:"}],"op":"replace"},{"value":"videoAdCanBeSkipped:","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdaptorDelegate~1videoAdCanBeSkipped(_:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"videoAdCanBeSkipped:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdaptorDelegate~1videoAdCanBeSkipped(_:)\/fragments"}]}]}