{"kind":"symbol","relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject"],"title":"Inherits From","type":"inheritsFrom"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"GFPVideoAdPIPDelegate","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObjectProtocol","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpvideoadpipdelegate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpvideoadpipdelegate"]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdPIPDelegate","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"GFPVideoAdPIPDelegate"}],"role":"symbol","modules":[{"name":"GFPSDK"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPVideoAdPIPDelegate"}],"title":"GFPVideoAdPIPDelegate","symbolKind":"protocol","roleHeading":"Protocol","externalID":"c:objc(pl)GFPVideoAdPIPDelegate"},"topicSections":[{"generated":true,"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdPIPDelegate\/videoAdCloseBtnTapped(inPIP:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdPIPDelegate\/videoAdReturnBtnTapped(inPIP:)"],"title":"Instance Methods","anchor":"Instance-Methods"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdPIPDelegate/videoAdCloseBtnTapped(inPIP:)":{"kind":"symbol","title":"videoAdCloseBtnTapped(inPIP:)","abstract":[{"type":"text","text":"PIP 영역 상단의 닫기 버튼 클릭 시 호출됩니다."}],"type":"topic","role":"symbol","url":"\/documentation\/gfpsdk\/gfpvideoadpipdelegate\/videoadclosebtntapped(inpip:)","navigatorTitle":[{"text":"videoAdCloseBtnTappedInPIP:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"videoAdCloseBtnTapped","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"inPIP"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)GFPVideoAdManager","kind":"typeIdentifier","text":"GFPVideoAdManager"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdPIPDelegate\/videoAdCloseBtnTapped(inPIP:)"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdPIPDelegate":{"navigatorTitle":[{"kind":"identifier","text":"GFPVideoAdPIPDelegate"}],"kind":"symbol","url":"\/documentation\/gfpsdk\/gfpvideoadpipdelegate","abstract":[],"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPVideoAdPIPDelegate"}],"title":"GFPVideoAdPIPDelegate","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdPIPDelegate","role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdPIPDelegate/videoAdReturnBtnTapped(inPIP:)":{"abstract":[{"type":"text","text":"PIP 영역 상단의 리턴 버튼 클릭 시 호출됩니다."}],"title":"videoAdReturnBtnTapped(inPIP:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"videoAdReturnBtnTapped","kind":"identifier"},{"kind":"text","text":"("},{"text":"inPIP","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"GFPVideoAdManager","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoAdManager"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdPIPDelegate\/videoAdReturnBtnTapped(inPIP:)","url":"\/documentation\/gfpsdk\/gfpvideoadpipdelegate\/videoadreturnbtntapped(inpip:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"videoAdReturnBtnTappedInPIP:"}],"kind":"symbol","role":"symbol","required":true},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Protocol","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"GFPVideoAdPIPDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GFPVideoAdPIPDelegate"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"GFPVideoAdPIPDelegate","kind":"identifier"}],"op":"replace"},{"value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdPIPDelegate\/videoAdCloseBtnTapped(inPIP:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdPIPDelegate\/videoAdReturnBtnTapped(inPIP:)"],"generated":true,"anchor":"Instance-Methods"}],"op":"replace","path":"\/topicSections"},{"value":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From"}],"path":"\/relationshipsSections","op":"replace"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPVideoAdPIPDelegate","kind":"identifier"},{"text":" <","kind":"text"},{"preciseIdentifier":"c:objc(pl)NSObject","text":"NSObject","kind":"typeIdentifier"},{"text":">","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdPIPDelegate~1videoAdCloseBtnTapped(inPIP:)\/title","value":"videoAdCloseBtnTappedInPIP:","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdPIPDelegate~1videoAdCloseBtnTapped(inPIP:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"videoAdCloseBtnTappedInPIP:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdPIPDelegate\/title","value":"GFPVideoAdPIPDelegate"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdPIPDelegate\/fragments","op":"replace","value":[{"text":"GFPVideoAdPIPDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdPIPDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"GFPVideoAdPIPDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdPIPDelegate~1videoAdReturnBtnTapped(inPIP:)\/title","op":"replace","value":"videoAdReturnBtnTappedInPIP:"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdPIPDelegate~1videoAdReturnBtnTapped(inPIP:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"videoAdReturnBtnTappedInPIP:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}