{"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoProviderIMAErrorKey","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/gfpsdk\/gfpvideoproviderimaerrorkey"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gfpsdk\/gfpvideoproviderimaerrorkey"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPVideoProviderIMAErrorKey"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"externalID":"c:@GFPVideoProviderIMAErrorKey","symbolKind":"var","role":"symbol","title":"GFPVideoProviderIMAErrorKey","roleHeading":"Global Variable","navigatorTitle":[{"text":"GFPVideoProviderIMAErrorKey","kind":"identifier"}],"modules":[{"name":"GFPSDK"}]},"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"GFPVideoProviderIMAErrorKey","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoProviderIMAErrorKey":{"kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoProviderIMAErrorKey","url":"\/documentation\/gfpsdk\/gfpvideoproviderimaerrorkey","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPVideoProviderIMAErrorKey"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"title":"GFPVideoProviderIMAErrorKey","role":"symbol","type":"topic","navigatorTitle":[{"text":"GFPVideoProviderIMAErrorKey","kind":"identifier"}],"abstract":[]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Global Variable","path":"\/metadata\/roleHeading","op":"replace"},{"value":"GFPVideoProviderIMAErrorKey","op":"replace","path":"\/metadata\/title"},{"value":"var","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"GFPVideoProviderIMAErrorKey"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"extern","kind":"keyword"},{"kind":"text","text":" "},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"GFPVideoProviderIMAErrorKey","kind":"identifier"},{"kind":"text","text":";"}]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoProviderIMAErrorKey\/title","value":"GFPVideoProviderIMAErrorKey"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoProviderIMAErrorKey\/fragments","value":[{"text":"GFPVideoProviderIMAErrorKey","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}