{"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdQoeBaseInfo","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"relationshipsSections":[{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"},{"title":"Inherited By","type":"inheritedBy","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdQoeInfo"],"kind":"relationships"},{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s7CVarArgP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s23CustomStringConvertibleP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH"]}],"topicSections":[{"anchor":"Initializers","title":"Initializers","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdQoeBaseInfo\/init(placementType:duration:skipOffset:mediaWidth:mediaHeight:)"],"generated":true},{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdQoeBaseInfo\/duration","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdQoeBaseInfo\/mediaHeight","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdQoeBaseInfo\/mediaWidth","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdQoeBaseInfo\/placementType","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdQoeBaseInfo\/skipOffset"],"anchor":"Instance-Properties"},{"generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdQoeBaseInfo\/update(_:)"],"title":"Instance Methods"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpvideoadqoebaseinfo"]},{"paths":["\/documentation\/gfpsdk\/gfpvideoadqoebaseinfo"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","metadata":{"externalID":"c:objc(cs)GFPVideoAdQoeBaseInfo","role":"symbol","modules":[{"name":"GFPSDK"}],"navigatorTitle":[{"text":"GFPVideoAdQoeBaseInfo","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPVideoAdQoeBaseInfo"}],"title":"GFPVideoAdQoeBaseInfo","roleHeading":"Class","symbolKind":"class"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"GFPVideoAdQoeBaseInfo","kind":"identifier"}],"platforms":["iOS"]}]}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject"},"doc://com.navercorp.da.gfp.GFPSDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdQoeInfo":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"GFPVideoAdQoeInfo"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdQoeInfo","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPVideoAdQoeInfo","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpvideoadqoeinfo","role":"symbol","kind":"symbol","title":"GFPVideoAdQoeInfo"},"doc://com.navercorp.da.gfp.GFPSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH"},"doc://com.navercorp.da.gfp.GFPSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s23CustomStringConvertibleP"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdQoeBaseInfo/mediaHeight":{"role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdQoeBaseInfo\/mediaHeight","abstract":[{"text":"광고 영상 세로 길이","type":"text"}],"navigatorTitle":[{"text":"mediaHeight","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpvideoadqoebaseinfo\/mediaheight","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"mediaHeight","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"type":"topic","title":"mediaHeight"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdQoeBaseInfo/placementType":{"navigatorTitle":[{"kind":"identifier","text":"placementType"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdQoeBaseInfo\/placementType","title":"placementType","kind":"symbol","abstract":[{"text":"광고 위치 명","type":"text"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"placementType"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"type":"topic","url":"\/documentation\/gfpsdk\/gfpvideoadqoebaseinfo\/placementtype"},"doc://com.navercorp.da.gfp.GFPSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s28CustomDebugStringConvertibleP"},"doc://com.navercorp.da.gfp.GFPSDK/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s7CVarArgP"},"doc://com.navercorp.da.gfp.GFPSDK/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdQoeBaseInfo/update(_:)":{"navigatorTitle":[{"kind":"identifier","text":"updateSize:"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdQoeBaseInfo\/update(_:)","title":"update(_:)","kind":"symbol","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"update"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize","text":"CGSize"},{"text":")","kind":"text"}],"type":"topic","url":"\/documentation\/gfpsdk\/gfpvideoadqoebaseinfo\/update(_:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdQoeBaseInfo/skipOffset":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"광고 스킵 오프셋 (초)"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"skipOffset","kind":"identifier"},{"kind":"text","text":": "},{"text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier"}],"title":"skipOffset","navigatorTitle":[{"kind":"identifier","text":"skipOffset"}],"url":"\/documentation\/gfpsdk\/gfpvideoadqoebaseinfo\/skipoffset","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdQoeBaseInfo\/skipOffset","role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdQoeBaseInfo/mediaWidth":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdQoeBaseInfo\/mediaWidth","title":"mediaWidth","type":"topic","navigatorTitle":[{"text":"mediaWidth","kind":"identifier"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mediaWidth"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"광고 영상 가로 길이"}],"url":"\/documentation\/gfpsdk\/gfpvideoadqoebaseinfo\/mediawidth","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdQoeBaseInfo/duration":{"kind":"symbol","type":"topic","abstract":[{"text":"광고 영상 길이 (초)","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"duration","kind":"identifier"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"}],"title":"duration","navigatorTitle":[{"kind":"identifier","text":"duration"}],"url":"\/documentation\/gfpsdk\/gfpvideoadqoebaseinfo\/duration","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdQoeBaseInfo\/duration","role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdQoeBaseInfo/init(placementType:duration:skipOffset:mediaWidth:mediaHeight:)":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdQoeBaseInfo\/init(placementType:duration:skipOffset:mediaWidth:mediaHeight:)","title":"init(placementType:duration:skipOffset:mediaWidth:mediaHeight:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithPlacementType:duration:skipOffset:mediaWidth:mediaHeight:"}],"role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"placementType","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"GFPVideoPlacementType","preciseIdentifier":"c:@E@GFPVideoPlacementType","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"duration","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"skipOffset","kind":"externalParam"},{"kind":"text","text":": "},{"text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"mediaWidth"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"mediaHeight"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[],"url":"\/documentation\/gfpsdk\/gfpvideoadqoebaseinfo\/init(placementtype:duration:skipoffset:mediawidth:mediaheight:)","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdQoeBaseInfo":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdQoeBaseInfo","url":"\/documentation\/gfpsdk\/gfpvideoadqoebaseinfo","role":"symbol","title":"GFPVideoAdQoeBaseInfo","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPVideoAdQoeBaseInfo","kind":"identifier"}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPVideoAdQoeBaseInfo"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"op":"replace","value":"GFPVideoAdQoeBaseInfo","path":"\/metadata\/title"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GFPVideoAdQoeBaseInfo"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"GFPVideoAdQoeBaseInfo"}]},{"path":"\/topicSections","value":[{"generated":true,"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdQoeBaseInfo\/duration","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdQoeBaseInfo\/mediaHeight","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdQoeBaseInfo\/mediaWidth","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdQoeBaseInfo\/placementType","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdQoeBaseInfo\/skipOffset"]},{"generated":true,"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdQoeBaseInfo\/init(placementType:duration:skipOffset:mediaWidth:mediaHeight:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdQoeBaseInfo\/update(_:)"]}],"op":"replace"},{"path":"\/relationshipsSections","op":"replace","value":[{"title":"Inherits From","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"},{"kind":"relationships","title":"Inherited By","type":"inheritedBy","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdQoeInfo"]}]},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPVideoAdQoeBaseInfo"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"GFPVideoAdQoeInfo","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdQoeInfo\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdQoeInfo\/fragments","op":"replace","value":[{"text":"GFPVideoAdQoeInfo","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdQoeInfo\/navigatorTitle","value":[{"text":"GFPVideoAdQoeInfo","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdQoeBaseInfo~1mediaHeight\/title","value":"mediaHeight"},{"value":[{"text":"mediaHeight","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdQoeBaseInfo~1mediaHeight\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdQoeBaseInfo~1placementType\/title","value":"placementType"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdQoeBaseInfo~1placementType\/fragments","value":[{"text":"placementType","kind":"identifier"}]},{"op":"replace","value":"updateSize:","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdQoeBaseInfo~1update(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdQoeBaseInfo~1update(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateSize:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdQoeBaseInfo~1skipOffset\/title","value":"skipOffset"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdQoeBaseInfo~1skipOffset\/fragments","op":"replace","value":[{"kind":"identifier","text":"skipOffset"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdQoeBaseInfo~1mediaWidth\/title","value":"mediaWidth"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdQoeBaseInfo~1mediaWidth\/fragments","op":"replace","value":[{"text":"mediaWidth","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdQoeBaseInfo~1duration\/title","value":"duration","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdQoeBaseInfo~1duration\/fragments","value":[{"text":"duration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdQoeBaseInfo~1init(placementType:duration:skipOffset:mediaWidth:mediaHeight:)\/title","value":"initWithPlacementType:duration:skipOffset:mediaWidth:mediaHeight:","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdQoeBaseInfo~1init(placementType:duration:skipOffset:mediaWidth:mediaHeight:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithPlacementType:duration:skipOffset:mediaWidth:mediaHeight:","kind":"identifier"}],"op":"replace"},{"value":"GFPVideoAdQoeBaseInfo","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdQoeBaseInfo\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdQoeBaseInfo\/fragments","value":[{"text":"GFPVideoAdQoeBaseInfo","kind":"identifier"}],"op":"replace"},{"value":[{"text":"GFPVideoAdQoeBaseInfo","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdQoeBaseInfo\/navigatorTitle","op":"replace"}]}]}