{"sections":[],"metadata":{"externalID":"c:@GFPVideoProviderFANErrorKey","navigatorTitle":[{"kind":"identifier","text":"GFPVideoProviderFANErrorKey"}],"title":"GFPVideoProviderFANErrorKey","role":"symbol","symbolKind":"var","roleHeading":"Global Variable","modules":[{"name":"GFPSDK"}],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"GFPVideoProviderFANErrorKey","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}]},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoProviderFANErrorKey","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPVideoProviderFANErrorKey","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"languages":["swift"]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"variants":[{"paths":["\/documentation\/gfpsdk\/gfpvideoproviderfanerrorkey"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpvideoproviderfanerrorkey"]}],"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoProviderFANErrorKey":{"navigatorTitle":[{"text":"GFPVideoProviderFANErrorKey","kind":"identifier"}],"title":"GFPVideoProviderFANErrorKey","abstract":[],"type":"topic","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoProviderFANErrorKey","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"GFPVideoProviderFANErrorKey","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"url":"\/documentation\/gfpsdk\/gfpvideoproviderfanerrorkey","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Global Variable","op":"replace"},{"op":"replace","value":"GFPVideoProviderFANErrorKey","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"var"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GFPVideoProviderFANErrorKey"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"GFPVideoProviderFANErrorKey","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoProviderFANErrorKey\/title","value":"GFPVideoProviderFANErrorKey"},{"value":[{"kind":"identifier","text":"GFPVideoProviderFANErrorKey"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoProviderFANErrorKey\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}