{"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManagerPIPDelegate"},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"GFPVideoAdScheduleManagerPIPDelegate","kind":"identifier"},{"kind":"text","text":" : "},{"text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"navigatorTitle":[{"text":"GFPVideoAdScheduleManagerPIPDelegate","kind":"identifier"}],"externalID":"c:objc(pl)GFPVideoAdScheduleManagerPIPDelegate","modules":[{"name":"GFPSDK"}],"role":"symbol","title":"GFPVideoAdScheduleManagerPIPDelegate","symbolKind":"protocol","roleHeading":"Protocol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPVideoAdScheduleManagerPIPDelegate"}]},"topicSections":[{"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManagerPIPDelegate\/scheduleManager(_:didTappedCloseBtnInPIP:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManagerPIPDelegate\/scheduleManager(_:didTappedReturnBtnInPIP:)"],"generated":true}],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpvideoadschedulemanagerpipdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gfpsdk\/gfpvideoadschedulemanagerpipdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)NSObject":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdScheduleManagerPIPDelegate":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"GFPVideoAdScheduleManagerPIPDelegate","kind":"identifier"}],"abstract":[],"navigatorTitle":[{"text":"GFPVideoAdScheduleManagerPIPDelegate","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpvideoadschedulemanagerpipdelegate","kind":"symbol","type":"topic","role":"symbol","title":"GFPVideoAdScheduleManagerPIPDelegate","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManagerPIPDelegate"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdScheduleManagerPIPDelegate/scheduleManager(_:didTappedCloseBtnInPIP:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"scheduleManager"},{"kind":"text","text":"("},{"text":"GFPVideoAdScheduleManager","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoAdScheduleManager"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didTappedCloseBtnInPIP"},{"kind":"text","text":": "},{"text":"GFPVideoAdBreakResult","preciseIdentifier":"c:objc(cs)GFPVideoAdBreakResult","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"scheduleManager:didTappedCloseBtnInPIP:"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManagerPIPDelegate\/scheduleManager(_:didTappedCloseBtnInPIP:)","url":"\/documentation\/gfpsdk\/gfpvideoadschedulemanagerpipdelegate\/schedulemanager(_:didtappedclosebtninpip:)","kind":"symbol","role":"symbol","required":true,"abstract":[{"type":"text","text":"PIP 영역 상단의 닫기 버튼 클릭 시 호출됩니다."}],"type":"topic","title":"scheduleManager(_:didTappedCloseBtnInPIP:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdScheduleManagerPIPDelegate/scheduleManager(_:didTappedReturnBtnInPIP:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"scheduleManager"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"GFPVideoAdScheduleManager","preciseIdentifier":"c:objc(cs)GFPVideoAdScheduleManager"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didTappedReturnBtnInPIP"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPVideoAdBreakResult","text":"GFPVideoAdBreakResult","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"scheduleManager(_:didTappedReturnBtnInPIP:)","navigatorTitle":[{"kind":"identifier","text":"scheduleManager:didTappedReturnBtnInPIP:"}],"url":"\/documentation\/gfpsdk\/gfpvideoadschedulemanagerpipdelegate\/schedulemanager(_:didtappedreturnbtninpip:)","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManagerPIPDelegate\/scheduleManager(_:didTappedReturnBtnInPIP:)","role":"symbol","type":"topic","kind":"symbol","abstract":[{"text":"PIP 영역 상단의 리턴 버튼 클릭 시 호출됩니다.","type":"text"}],"required":true}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"GFPVideoAdScheduleManagerPIPDelegate"},{"value":"protocol","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"GFPVideoAdScheduleManagerPIPDelegate"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"text":"GFPVideoAdScheduleManagerPIPDelegate","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"path":"\/topicSections","value":[{"anchor":"Instance-Methods","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManagerPIPDelegate\/scheduleManager(_:didTappedCloseBtnInPIP:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManagerPIPDelegate\/scheduleManager(_:didTappedReturnBtnInPIP:)"],"generated":true,"title":"Instance Methods"}],"op":"replace"},{"value":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject"],"kind":"relationships"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPVideoAdScheduleManagerPIPDelegate"},{"text":" <","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier"},{"kind":"text","text":">"}]}],"kind":"declarations"}},{"value":"GFPVideoAdScheduleManagerPIPDelegate","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManagerPIPDelegate\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManagerPIPDelegate\/fragments","value":[{"kind":"identifier","text":"GFPVideoAdScheduleManagerPIPDelegate"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManagerPIPDelegate\/navigatorTitle","value":[{"text":"GFPVideoAdScheduleManagerPIPDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManagerPIPDelegate~1scheduleManager(_:didTappedCloseBtnInPIP:)\/title","value":"scheduleManager:didTappedCloseBtnInPIP:"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManagerPIPDelegate~1scheduleManager(_:didTappedCloseBtnInPIP:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"scheduleManager:didTappedCloseBtnInPIP:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManagerPIPDelegate~1scheduleManager(_:didTappedReturnBtnInPIP:)\/title","value":"scheduleManager:didTappedReturnBtnInPIP:","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManagerPIPDelegate~1scheduleManager(_:didTappedReturnBtnInPIP:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"scheduleManager:didTappedReturnBtnInPIP:"}]}]}]}