{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPVideoMediator","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoMediator","interfaceLanguage":"swift"},"metadata":{"title":"GFPVideoMediator","role":"symbol","roleHeading":"Class","symbolKind":"class","externalID":"c:objc(cs)GFPVideoMediator","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPVideoMediator"}],"navigatorTitle":[{"text":"GFPVideoMediator","kind":"identifier"}],"modules":[{"name":"GFPSDK"}]},"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediator"],"kind":"relationships"},{"title":"Conforms To","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPResponseInfoPresentable","doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s7CVarArgP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s23CustomStringConvertibleP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH"],"type":"conformsTo","kind":"relationships"}],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpvideomediator"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpvideomediator"]}],"kind":"symbol","sections":[],"topicSections":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoMediator\/delegate","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoMediator\/reportDelegate"],"generated":true,"title":"Instance Properties"}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s28CustomDebugStringConvertibleP"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoMediator/reportDelegate":{"title":"reportDelegate","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"reportDelegate"},{"text":": (any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)GFPEventReportDelegate","text":"GFPEventReportDelegate"},{"text":")?","kind":"text"}],"role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoMediator\/reportDelegate","navigatorTitle":[{"kind":"identifier","text":"reportDelegate"}],"abstract":[],"kind":"symbol","url":"\/documentation\/gfpsdk\/gfpvideomediator\/reportdelegate","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPMediator":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediator","title":"GFPMediator","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPMediator"}],"url":"\/documentation\/gfpsdk\/gfpmediator","type":"topic","abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPMediator"}]},"doc://com.navercorp.da.gfp.GFPSDK/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoMediator/delegate":{"title":"delegate","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"kind":"text","text":": (any "},{"kind":"typeIdentifier","text":"GFPVideoMediatorDelegate","preciseIdentifier":"c:objc(pl)GFPVideoMediatorDelegate"},{"text":")?","kind":"text"}],"role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoMediator\/delegate","navigatorTitle":[{"text":"delegate","kind":"identifier"}],"abstract":[],"kind":"symbol","url":"\/documentation\/gfpsdk\/gfpvideomediator\/delegate","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoMediator":{"title":"GFPVideoMediator","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoMediator","role":"symbol","kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPVideoMediator"}],"navigatorTitle":[{"kind":"identifier","text":"GFPVideoMediator"}],"type":"topic","url":"\/documentation\/gfpsdk\/gfpvideomediator"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPResponseInfoPresentable":{"kind":"symbol","title":"GFPResponseInfoPresentable","url":"\/documentation\/gfpsdk\/gfpresponseinfopresentable","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPResponseInfoPresentable"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPResponseInfoPresentable","type":"topic","navigatorTitle":[{"text":"GFPResponseInfoPresentable","kind":"identifier"}],"abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s7CVarArgP"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoMediator/loadVideoAdaptorWithAdUnitID:videoContext:adParam:videoParam:timeoutInterval:":{"title":"loadVideoAdaptorWithAdUnitID:videoContext:adParam:videoParam:timeoutInterval:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"loadVideoAdaptorWithAdUnitID:videoContext:adParam:videoParam:timeoutInterval:"}],"role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoMediator\/loadVideoAdaptorWithAdUnitID:videoContext:adParam:videoParam:timeoutInterval:","navigatorTitle":[{"text":"loadVideoAdaptorWithAdUnitID:videoContext:adParam:videoParam:timeoutInterval:","kind":"identifier"}],"abstract":[],"kind":"symbol","url":"\/documentation\/gfpsdk\/gfpvideomediator\/loadvideoadaptorwithadunitid:videocontext:adparam:videoparam:timeoutinterval:","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"GFPVideoMediator"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"value":[{"kind":"identifier","text":"GFPVideoMediator"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"GFPVideoMediator","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"generated":true,"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoMediator\/delegate","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoMediator\/reportDelegate"],"anchor":"Instance-Properties","title":"Instance Properties"},{"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoMediator\/loadVideoAdaptorWithAdUnitID:videoContext:adParam:videoParam:timeoutInterval:"],"generated":true}],"path":"\/topicSections","op":"replace"},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediator"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"GFPVideoMediator","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPMediator","text":"GFPMediator","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediator"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"reportDelegate","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoMediator~1reportDelegate\/title"},{"value":[{"text":"reportDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoMediator~1reportDelegate\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMediator\/title","value":"GFPMediator"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMediator\/fragments","value":[{"text":"GFPMediator","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"GFPMediator"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMediator\/navigatorTitle"},{"value":"delegate","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoMediator~1delegate\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoMediator~1delegate\/fragments","value":[{"kind":"identifier","text":"delegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoMediator\/title","value":"GFPVideoMediator"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoMediator\/fragments","value":[{"text":"GFPVideoMediator","kind":"identifier"}],"op":"replace"},{"value":[{"text":"GFPVideoMediator","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoMediator\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPResponseInfoPresentable\/title","value":"GFPResponseInfoPresentable"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPResponseInfoPresentable\/fragments","value":[{"kind":"identifier","text":"GFPResponseInfoPresentable"}],"op":"replace"},{"value":[{"text":"GFPResponseInfoPresentable","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPResponseInfoPresentable\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}