{"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPVideoAdScheduleManagerQoeDelegate"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject","text":"NSObjectProtocol"}]}]}],"metadata":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPVideoAdScheduleManagerQoeDelegate"}],"symbolKind":"protocol","modules":[{"name":"GFPSDK"}],"title":"GFPVideoAdScheduleManagerQoeDelegate","roleHeading":"Protocol","externalID":"c:objc(pl)GFPVideoAdScheduleManagerQoeDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPVideoAdScheduleManagerQoeDelegate"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManagerQoeDelegate"},"sections":[],"kind":"symbol","topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManagerQoeDelegate\/scheduleManager(_:canBeSkipAdWith:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManagerQoeDelegate\/scheduleManager(_:didCompleteAdWitQoeInfo:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManagerQoeDelegate\/scheduleManager(_:didLoadAdWith:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManagerQoeDelegate\/scheduleManager(_:didPauseAdWith:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManagerQoeDelegate\/scheduleManager(_:didReceiveAdClickEventWitQoeInfo:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManagerQoeDelegate\/scheduleManager(_:didReciveAdErrorForQoe:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManagerQoeDelegate\/scheduleManager(_:didResumeAdWith:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManagerQoeDelegate\/scheduleManager(_:didSkipAdWith:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManagerQoeDelegate\/scheduleManager(_:didStartAdWith:)"],"generated":true,"anchor":"Instance-Methods"}],"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpvideoadschedulemanagerqoedelegate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpvideoadschedulemanagerqoedelegate"]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdScheduleManagerQoeDelegate/scheduleManager(_:didStartAdWith:)":{"abstract":[{"type":"text","text":"광고가 시작 된 경우 발생"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"scheduleManager:didStartAdWithQoeInfo:"}],"role":"symbol","title":"scheduleManager(_:didStartAdWith:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"scheduleManager"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoAdScheduleManager","text":"GFPVideoAdScheduleManager"},{"kind":"text","text":", "},{"text":"didStartAdWith","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoAdQoeInfo","text":"GFPVideoAdQoeInfo"},{"text":")","kind":"text"}],"url":"\/documentation\/gfpsdk\/gfpvideoadschedulemanagerqoedelegate\/schedulemanager(_:didstartadwith:)","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManagerQoeDelegate\/scheduleManager(_:didStartAdWith:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdScheduleManagerQoeDelegate/scheduleManager(_:didReciveAdErrorForQoe:)":{"navigatorTitle":[{"kind":"identifier","text":"scheduleManager:didReciveAdErrorForQoe:"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManagerQoeDelegate\/scheduleManager(_:didReciveAdErrorForQoe:)","title":"scheduleManager(_:didReciveAdErrorForQoe:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"scheduleManager","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoAdScheduleManager","text":"GFPVideoAdScheduleManager"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didReciveAdErrorForQoe"},{"text":": ","kind":"text"},{"text":"GFPError","kind":"typeIdentifier","preciseIdentifier":"c:@M@NaverAdsServices@objc(cs)GFPError"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"광고 관련 오류가 발생한 경우 발생"}],"role":"symbol","url":"\/documentation\/gfpsdk\/gfpvideoadschedulemanagerqoedelegate\/schedulemanager(_:didreciveaderrorforqoe:)","kind":"symbol","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdScheduleManagerQoeDelegate":{"kind":"symbol","abstract":[],"url":"\/documentation\/gfpsdk\/gfpvideoadschedulemanagerqoedelegate","type":"topic","title":"GFPVideoAdScheduleManagerQoeDelegate","navigatorTitle":[{"kind":"identifier","text":"GFPVideoAdScheduleManagerQoeDelegate"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManagerQoeDelegate","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPVideoAdScheduleManagerQoeDelegate"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdScheduleManagerQoeDelegate/scheduleManager(_:didSkipAdWith:)":{"abstract":[{"type":"text","text":"광고가 스킵 된 경우 발생"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"scheduleManager:didSkipAdWithQoeInfo:"}],"role":"symbol","title":"scheduleManager(_:didSkipAdWith:)","required":true,"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"scheduleManager","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)GFPVideoAdScheduleManager","text":"GFPVideoAdScheduleManager","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didSkipAdWith"},{"text":": ","kind":"text"},{"text":"GFPVideoAdQoeInfo","preciseIdentifier":"c:objc(cs)GFPVideoAdQoeInfo","kind":"typeIdentifier"},{"kind":"text","text":")"}],"url":"\/documentation\/gfpsdk\/gfpvideoadschedulemanagerqoedelegate\/schedulemanager(_:didskipadwith:)","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManagerQoeDelegate\/scheduleManager(_:didSkipAdWith:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdScheduleManagerQoeDelegate/scheduleManager(_:didReceiveAdClickEventWitQoeInfo:)":{"kind":"symbol","required":true,"type":"topic","navigatorTitle":[{"kind":"identifier","text":"scheduleManager:didReceiveAdClickEventWitQoeInfo:"}],"url":"\/documentation\/gfpsdk\/gfpvideoadschedulemanagerqoedelegate\/schedulemanager(_:didreceiveadclickeventwitqoeinfo:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"scheduleManager"},{"text":"(","kind":"text"},{"text":"GFPVideoAdScheduleManager","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoAdScheduleManager"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didReceiveAdClickEventWitQoeInfo"},{"text":": ","kind":"text"},{"text":"GFPVideoAdQoeInfo","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoAdQoeInfo"},{"kind":"text","text":")"}],"role":"symbol","abstract":[{"text":"광고가 클릭 된 경우 발생","type":"text"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManagerQoeDelegate\/scheduleManager(_:didReceiveAdClickEventWitQoeInfo:)","title":"scheduleManager(_:didReceiveAdClickEventWitQoeInfo:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdScheduleManagerQoeDelegate/scheduleManager(_:canBeSkipAdWith:)":{"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"scheduleManager"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)GFPVideoAdScheduleManager","text":"GFPVideoAdScheduleManager","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"canBeSkipAdWith","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPVideoAdQoeInfo","kind":"typeIdentifier","text":"GFPVideoAdQoeInfo"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"scheduleManager:canBeSkipAdWithQoeInfo:","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManagerQoeDelegate\/scheduleManager(_:canBeSkipAdWith:)","url":"\/documentation\/gfpsdk\/gfpvideoadschedulemanagerqoedelegate\/schedulemanager(_:canbeskipadwith:)","role":"symbol","abstract":[{"type":"text","text":"광고를 스킵 할 수 있을 때 발생"}],"type":"topic","title":"scheduleManager(_:canBeSkipAdWith:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdScheduleManagerQoeDelegate/scheduleManager(_:didPauseAdWith:)":{"type":"topic","url":"\/documentation\/gfpsdk\/gfpvideoadschedulemanagerqoedelegate\/schedulemanager(_:didpauseadwith:)","title":"scheduleManager(_:didPauseAdWith:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"scheduleManager"},{"text":"(","kind":"text"},{"text":"GFPVideoAdScheduleManager","preciseIdentifier":"c:objc(cs)GFPVideoAdScheduleManager","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"didPauseAdWith","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GFPVideoAdQoeInfo","preciseIdentifier":"c:objc(cs)GFPVideoAdQoeInfo"},{"text":")","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"scheduleManager:didPauseAdWithQoeInfo:","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"광고가 일시중지 된 경우 발생"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManagerQoeDelegate\/scheduleManager(_:didPauseAdWith:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdScheduleManagerQoeDelegate/scheduleManager(_:didResumeAdWith:)":{"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"scheduleManager"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)GFPVideoAdScheduleManager","text":"GFPVideoAdScheduleManager","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"didResumeAdWith","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPVideoAdQoeInfo","kind":"typeIdentifier","text":"GFPVideoAdQoeInfo"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"scheduleManager:didResumeAdWithQoeInfo:","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManagerQoeDelegate\/scheduleManager(_:didResumeAdWith:)","url":"\/documentation\/gfpsdk\/gfpvideoadschedulemanagerqoedelegate\/schedulemanager(_:didresumeadwith:)","required":true,"role":"symbol","abstract":[{"type":"text","text":"광고가 재시작 된 경우 발생"}],"type":"topic","title":"scheduleManager(_:didResumeAdWith:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdScheduleManagerQoeDelegate/scheduleManager(_:didLoadAdWith:)":{"type":"topic","url":"\/documentation\/gfpsdk\/gfpvideoadschedulemanagerqoedelegate\/schedulemanager(_:didloadadwith:)","title":"scheduleManager(_:didLoadAdWith:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"scheduleManager"},{"text":"(","kind":"text"},{"text":"GFPVideoAdScheduleManager","preciseIdentifier":"c:objc(cs)GFPVideoAdScheduleManager","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"didLoadAdWith","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GFPVideoAdQoeInfo","preciseIdentifier":"c:objc(cs)GFPVideoAdQoeInfo"},{"text":")","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"scheduleManager:didLoadAdWithQoeInfo:","kind":"identifier"}],"kind":"symbol","required":true,"abstract":[{"type":"text","text":"광고가 로드된 경우 발생"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManagerQoeDelegate\/scheduleManager(_:didLoadAdWith:)"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdScheduleManagerQoeDelegate/scheduleManager(_:didCompleteAdWitQoeInfo:)":{"type":"topic","url":"\/documentation\/gfpsdk\/gfpvideoadschedulemanagerqoedelegate\/schedulemanager(_:didcompleteadwitqoeinfo:)","title":"scheduleManager(_:didCompleteAdWitQoeInfo:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"scheduleManager"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)GFPVideoAdScheduleManager","text":"GFPVideoAdScheduleManager","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"didCompleteAdWitQoeInfo","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPVideoAdQoeInfo","kind":"typeIdentifier","text":"GFPVideoAdQoeInfo"},{"kind":"text","text":")"}],"role":"symbol","navigatorTitle":[{"text":"scheduleManager:didCompleteAdWitQoeInfo:","kind":"identifier"}],"kind":"symbol","required":true,"abstract":[{"type":"text","text":"광고 재생이 종료 된 경우 발생"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManagerQoeDelegate\/scheduleManager(_:didCompleteAdWitQoeInfo:)"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"value":"GFPVideoAdScheduleManagerQoeDelegate","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"value":[{"text":"GFPVideoAdScheduleManagerQoeDelegate","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"GFPVideoAdScheduleManagerQoeDelegate","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"generated":true,"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManagerQoeDelegate\/scheduleManager(_:canBeSkipAdWith:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManagerQoeDelegate\/scheduleManager(_:didCompleteAdWitQoeInfo:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManagerQoeDelegate\/scheduleManager(_:didLoadAdWith:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManagerQoeDelegate\/scheduleManager(_:didPauseAdWith:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManagerQoeDelegate\/scheduleManager(_:didReceiveAdClickEventWitQoeInfo:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManagerQoeDelegate\/scheduleManager(_:didReciveAdErrorForQoe:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManagerQoeDelegate\/scheduleManager(_:didResumeAdWith:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManagerQoeDelegate\/scheduleManager(_:didSkipAdWith:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManagerQoeDelegate\/scheduleManager(_:didStartAdWith:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject"]}]},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"text":"GFPVideoAdScheduleManagerQoeDelegate","kind":"identifier"},{"text":" <","kind":"text"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(pl)NSObject"},{"kind":"text","text":">"}]}]}},{"value":"scheduleManager:didStartAdWithQoeInfo:","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManagerQoeDelegate~1scheduleManager(_:didStartAdWith:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"scheduleManager:didStartAdWithQoeInfo:"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManagerQoeDelegate~1scheduleManager(_:didStartAdWith:)\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManagerQoeDelegate~1scheduleManager(_:didReciveAdErrorForQoe:)\/title","value":"scheduleManager:didReciveAdErrorForQoe:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"scheduleManager:didReciveAdErrorForQoe:"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManagerQoeDelegate~1scheduleManager(_:didReciveAdErrorForQoe:)\/fragments"},{"op":"replace","value":"GFPVideoAdScheduleManagerQoeDelegate","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManagerQoeDelegate\/title"},{"op":"replace","value":[{"kind":"identifier","text":"GFPVideoAdScheduleManagerQoeDelegate"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManagerQoeDelegate\/fragments"},{"op":"replace","value":[{"text":"GFPVideoAdScheduleManagerQoeDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManagerQoeDelegate\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManagerQoeDelegate~1scheduleManager(_:didSkipAdWith:)\/title","value":"scheduleManager:didSkipAdWithQoeInfo:"},{"value":[{"kind":"text","text":"- "},{"text":"scheduleManager:didSkipAdWithQoeInfo:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManagerQoeDelegate~1scheduleManager(_:didSkipAdWith:)\/fragments"},{"op":"replace","value":"scheduleManager:didReceiveAdClickEventWitQoeInfo:","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManagerQoeDelegate~1scheduleManager(_:didReceiveAdClickEventWitQoeInfo:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"scheduleManager:didReceiveAdClickEventWitQoeInfo:"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManagerQoeDelegate~1scheduleManager(_:didReceiveAdClickEventWitQoeInfo:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManagerQoeDelegate~1scheduleManager(_:canBeSkipAdWith:)\/title","value":"scheduleManager:canBeSkipAdWithQoeInfo:"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManagerQoeDelegate~1scheduleManager(_:canBeSkipAdWith:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"scheduleManager:canBeSkipAdWithQoeInfo:","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"scheduleManager:didPauseAdWithQoeInfo:","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManagerQoeDelegate~1scheduleManager(_:didPauseAdWith:)\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManagerQoeDelegate~1scheduleManager(_:didPauseAdWith:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"scheduleManager:didPauseAdWithQoeInfo:","kind":"identifier"}]},{"value":"scheduleManager:didResumeAdWithQoeInfo:","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManagerQoeDelegate~1scheduleManager(_:didResumeAdWith:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"scheduleManager:didResumeAdWithQoeInfo:"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManagerQoeDelegate~1scheduleManager(_:didResumeAdWith:)\/fragments"},{"value":"scheduleManager:didLoadAdWithQoeInfo:","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManagerQoeDelegate~1scheduleManager(_:didLoadAdWith:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManagerQoeDelegate~1scheduleManager(_:didLoadAdWith:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"scheduleManager:didLoadAdWithQoeInfo:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManagerQoeDelegate~1scheduleManager(_:didCompleteAdWitQoeInfo:)\/title","value":"scheduleManager:didCompleteAdWitQoeInfo:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"scheduleManager:didCompleteAdWitQoeInfo:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManagerQoeDelegate~1scheduleManager(_:didCompleteAdWitQoeInfo:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}