{"kind":"symbol","relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s7CVarArgP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s23CustomStringConvertibleP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH"],"title":"Conforms To","type":"conformsTo","kind":"relationships"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdPlayerSetting"},"metadata":{"navigatorTitle":[{"text":"GFPVideoAdPlayerSetting","kind":"identifier"}],"roleHeading":"Class","externalID":"c:@M@GFPSDK@objc(cs)GFPVideoAdPlayerSetting","modules":[{"name":"GFPSDK"}],"symbolKind":"class","role":"symbol","title":"GFPVideoAdPlayerSetting","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"GFPVideoAdPlayerSetting","kind":"identifier"}]},"topicSections":[{"anchor":"Initializers","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdPlayerSetting\/init()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdPlayerSetting\/init(action:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdPlayerSetting\/init(action:audioSetting:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdPlayerSetting\/init(action:audioSetting:disableExternalPlayBack:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdPlayerSetting\/init(audioSetting:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdPlayerSetting\/init(disableExternalPlayback:)"],"title":"Initializers","generated":true},{"anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdPlayerSetting\/audioSetting","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdPlayerSetting\/backAction","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdPlayerSetting\/description","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdPlayerSetting\/disableExternalPlayback"],"title":"Instance Properties"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objcMembers","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"GFPVideoAdPlayerSetting","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpvideoadplayersetting"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gfpsdk\/gfpvideoadplayersetting"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdPlayerSetting/init(action:audioSetting:)":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdPlayerSetting\/init(action:audioSetting:)","abstract":[],"role":"symbol","title":"init(action:audioSetting:)","kind":"symbol","url":"\/documentation\/gfpsdk\/gfpvideoadplayersetting\/init(action:audiosetting:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"action"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"GFPVideoBackgroundActionType","preciseIdentifier":"c:@M@GFPSDK@E@GFPVideoBackgroundActionType"},{"text":", ","kind":"text"},{"text":"audioSetting","kind":"externalParam"},{"kind":"text","text":": "},{"text":"GFPVideoAudioSettingType","kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPVideoAudioSettingType"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"initWithAction:audioSetting:"}],"type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdPlayerSetting/init()":{"title":"init()","url":"\/documentation\/gfpsdk\/gfpvideoadplayersetting\/init()","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"init"}],"kind":"symbol","type":"topic","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdPlayerSetting\/init()"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdPlayerSetting/backAction":{"abstract":[{"type":"text","text":"광고 재생 도중 Background 진입 시 동작 option 처리. (Default는 Pause)"}],"title":"backAction","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"backAction"},{"text":": ","kind":"text"},{"text":"GFPVideoBackgroundActionType","preciseIdentifier":"c:@M@GFPSDK@E@GFPVideoBackgroundActionType","kind":"typeIdentifier"}],"url":"\/documentation\/gfpsdk\/gfpvideoadplayersetting\/backaction","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdPlayerSetting\/backAction","navigatorTitle":[{"kind":"identifier","text":"backAction"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdPlayerSetting/init(audioSetting:)":{"title":"init(audioSetting:)","url":"\/documentation\/gfpsdk\/gfpvideoadplayersetting\/init(audiosetting:)","role":"symbol","navigatorTitle":[{"text":"initWithAudioSetting:","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[],"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"audioSetting","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GFPVideoAudioSettingType","preciseIdentifier":"c:@E@GFPVideoAudioSettingType"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdPlayerSetting\/init(audioSetting:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdPlayerSetting/disableExternalPlayback":{"abstract":[{"text":"externalPlayBack 비활성화 여부 (Default는 false)","type":"text"}],"title":"disableExternalPlayback","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"disableExternalPlayback","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"url":"\/documentation\/gfpsdk\/gfpvideoadplayersetting\/disableexternalplayback","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdPlayerSetting\/disableExternalPlayback","navigatorTitle":[{"text":"disableExternalPlayback","kind":"identifier"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH","title":"Swift.Hashable"},"doc://com.navercorp.da.gfp.GFPSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.navercorp.da.gfp.GFPSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdPlayerSetting/init(action:audioSetting:disableExternalPlayBack:)":{"abstract":[],"title":"init(action:audioSetting:disableExternalPlayBack:)","type":"topic","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"action","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@GFPSDK@E@GFPVideoBackgroundActionType","text":"GFPVideoBackgroundActionType"},{"kind":"text","text":", "},{"text":"audioSetting","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"GFPVideoAudioSettingType","kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPVideoAudioSettingType"},{"text":", ","kind":"text"},{"text":"disableExternalPlayBack","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":")","kind":"text"}],"url":"\/documentation\/gfpsdk\/gfpvideoadplayersetting\/init(action:audiosetting:disableexternalplayback:)","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdPlayerSetting\/init(action:audioSetting:disableExternalPlayBack:)","navigatorTitle":[{"text":"initWithAction:audioSetting:disableExternalPlayback:","kind":"identifier"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject"},"doc://com.navercorp.da.gfp.GFPSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s23CustomStringConvertibleP"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdPlayerSetting/init(disableExternalPlayback:)":{"title":"init(disableExternalPlayback:)","url":"\/documentation\/gfpsdk\/gfpvideoadplayersetting\/init(disableexternalplayback:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithDisableExternalPlayback:"}],"kind":"symbol","type":"topic","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"disableExternalPlayback"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdPlayerSetting\/init(disableExternalPlayback:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdPlayerSetting/description":{"abstract":[],"title":"description","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"description","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"url":"\/documentation\/gfpsdk\/gfpvideoadplayersetting\/description","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdPlayerSetting\/description","navigatorTitle":[{"text":"description","kind":"identifier"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdPlayerSetting/init(action:)":{"title":"init(action:)","url":"\/documentation\/gfpsdk\/gfpvideoadplayersetting\/init(action:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithAction:"}],"kind":"symbol","type":"topic","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"action"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@GFPSDK@E@GFPVideoBackgroundActionType","kind":"typeIdentifier","text":"GFPVideoBackgroundActionType"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdPlayerSetting\/init(action:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s7CVarArgP"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdPlayerSetting/audioSetting":{"title":"audioSetting","url":"\/documentation\/gfpsdk\/gfpvideoadplayersetting\/audiosetting","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"audioSetting"}],"kind":"symbol","type":"topic","abstract":[{"text":"광고 재생 도중 Audio output 관련 동작 정리. (Optional, Default는 AVPlayer 기본 동작)","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"audioSetting"},{"text":": ","kind":"text"},{"text":"GFPVideoAudioSettingType","preciseIdentifier":"c:@E@GFPVideoAudioSettingType","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdPlayerSetting\/audioSetting"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdPlayerSetting":{"navigatorTitle":[{"text":"GFPVideoAdPlayerSetting","kind":"identifier"}],"title":"GFPVideoAdPlayerSetting","url":"\/documentation\/gfpsdk\/gfpvideoadplayersetting","kind":"symbol","abstract":[],"role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdPlayerSetting","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPVideoAdPlayerSetting"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"value":"GFPVideoAdPlayerSetting","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","value":[{"text":"GFPVideoAdPlayerSetting","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"GFPVideoAdPlayerSetting","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdPlayerSetting\/audioSetting","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdPlayerSetting\/backAction","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdPlayerSetting\/description","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdPlayerSetting\/disableExternalPlayback"],"generated":true},{"title":"Instance Methods","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdPlayerSetting\/init()","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdPlayerSetting\/init(action:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdPlayerSetting\/init(action:audioSetting:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdPlayerSetting\/init(action:audioSetting:disableExternalPlayBack:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdPlayerSetting\/init(audioSetting:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdPlayerSetting\/init(disableExternalPlayback:)"],"anchor":"Instance-Methods","generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject"]}]},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"GFPVideoAdPlayerSetting","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdPlayerSetting~1init(action:audioSetting:)\/title","value":"initWithAction:audioSetting:"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdPlayerSetting~1init(action:audioSetting:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithAction:audioSetting:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdPlayerSetting~1init()\/title","op":"replace","value":"init"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdPlayerSetting~1init()\/fragments","value":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdPlayerSetting~1backAction\/title","value":"backAction"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdPlayerSetting~1backAction\/fragments","op":"replace","value":[{"kind":"identifier","text":"backAction"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdPlayerSetting~1init(audioSetting:)\/title","value":"initWithAudioSetting:","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdPlayerSetting~1init(audioSetting:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithAudioSetting:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdPlayerSetting~1disableExternalPlayback\/title","op":"replace","value":"disableExternalPlayback"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdPlayerSetting~1disableExternalPlayback\/fragments","value":[{"kind":"identifier","text":"disableExternalPlayback"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdPlayerSetting~1init(action:audioSetting:disableExternalPlayBack:)\/title","value":"initWithAction:audioSetting:disableExternalPlayback:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdPlayerSetting~1init(action:audioSetting:disableExternalPlayBack:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithAction:audioSetting:disableExternalPlayback:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdPlayerSetting~1init(disableExternalPlayback:)\/title","value":"initWithDisableExternalPlayback:"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdPlayerSetting~1init(disableExternalPlayback:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithDisableExternalPlayback:"}]},{"value":"description","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdPlayerSetting~1description\/title"},{"value":[{"text":"description","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdPlayerSetting~1description\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdPlayerSetting~1init(action:)\/title","value":"initWithAction:"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdPlayerSetting~1init(action:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithAction:"}],"op":"replace"},{"value":"audioSetting","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdPlayerSetting~1audioSetting\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdPlayerSetting~1audioSetting\/fragments","value":[{"kind":"identifier","text":"audioSetting"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdPlayerSetting\/title","value":"GFPVideoAdPlayerSetting"},{"op":"replace","value":[{"text":"GFPVideoAdPlayerSetting","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdPlayerSetting\/fragments"},{"op":"replace","value":[{"text":"GFPVideoAdPlayerSetting","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdPlayerSetting\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}