{"topicSections":[{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoSchedule\/init(dictionary:noticeDuration:withError:)"],"generated":true,"title":"Initializers","anchor":"Initializers"},{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoSchedule\/adBreakList","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoSchedule\/head","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoSchedule\/lastType","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoSchedule\/midAdBreakList","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoSchedule\/midPostAdBreakList","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoSchedule\/postAdBreakList","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoSchedule\/postSourceID","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoSchedule\/preAdBreakList","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoSchedule\/requestID","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoSchedule\/scheduleID"]},{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoSchedule\/adBreak(with:)"],"generated":true,"anchor":"Instance-Methods","title":"Instance Methods"}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpvideoschedule"]},{"paths":["\/documentation\/gfpsdk\/gfpvideoschedule"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"modules":[{"name":"GFPSDK"}],"roleHeading":"Class","title":"GFPVideoSchedule","symbolKind":"class","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPVideoSchedule","kind":"identifier"}],"externalID":"c:objc(cs)GFPVideoSchedule","navigatorTitle":[{"text":"GFPVideoSchedule","kind":"identifier"}]},"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"},{"kind":"relationships","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s7CVarArgP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s23CustomStringConvertibleP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH"],"title":"Conforms To","type":"conformsTo"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"GFPVideoSchedule","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoSchedule"},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoSchedule/requestID":{"kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoSchedule\/requestID","navigatorTitle":[{"kind":"identifier","text":"requestID"}],"abstract":[],"type":"topic","title":"requestID","url":"\/documentation\/gfpsdk\/gfpvideoschedule\/requestid","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requestID","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoSchedule/postSourceID":{"navigatorTitle":[{"text":"postSourceID","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoSchedule\/postSourceID","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"postSourceID"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"abstract":[],"title":"postSourceID","kind":"symbol","url":"\/documentation\/gfpsdk\/gfpvideoschedule\/postsourceid"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoSchedule/adBreak(with:)":{"role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoSchedule\/adBreak(with:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"adBreak","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)GFPVideoAdSource","kind":"typeIdentifier","text":"GFPVideoAdSource"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoAdBreak","text":"GFPVideoAdBreak"},{"text":"?","kind":"text"}],"kind":"symbol","navigatorTitle":[{"text":"adBreakWithAdSource:","kind":"identifier"}],"title":"adBreak(with:)","type":"topic","abstract":[],"url":"\/documentation\/gfpsdk\/gfpvideoschedule\/adbreak(with:)"},"doc://com.navercorp.da.gfp.GFPSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s28CustomDebugStringConvertibleP"},"doc://com.navercorp.da.gfp.GFPSDK/objc(cs)NSObject":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoSchedule/midAdBreakList":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"midAdBreakList"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPVideoAdBreak","kind":"typeIdentifier","text":"GFPVideoAdBreak"},{"kind":"text","text":"]"}],"abstract":[],"type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoSchedule\/midAdBreakList","url":"\/documentation\/gfpsdk\/gfpvideoschedule\/midadbreaklist","role":"symbol","title":"midAdBreakList","navigatorTitle":[{"text":"midAdBreakList","kind":"identifier"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoSchedule/head":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"head"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoScheduleHead","text":"GFPVideoScheduleHead"}],"url":"\/documentation\/gfpsdk\/gfpvideoschedule\/head","navigatorTitle":[{"text":"head","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoSchedule\/head","title":"head","abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoSchedule/scheduleID":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoSchedule\/scheduleID","abstract":[],"role":"symbol","title":"scheduleID","kind":"symbol","url":"\/documentation\/gfpsdk\/gfpvideoschedule\/scheduleid","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"scheduleID","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"navigatorTitle":[{"text":"scheduleID","kind":"identifier"}],"type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoSchedule/midPostAdBreakList":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"midPostAdBreakList"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoAdBreak","text":"GFPVideoAdBreak"},{"text":"]","kind":"text"}],"url":"\/documentation\/gfpsdk\/gfpvideoschedule\/midpostadbreaklist","navigatorTitle":[{"text":"midPostAdBreakList","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoSchedule\/midPostAdBreakList","title":"midPostAdBreakList","abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoSchedule/init(dictionary:noticeDuration:withError:)":{"type":"topic","abstract":[],"role":"symbol","title":"init(dictionary:noticeDuration:withError:)","kind":"symbol","url":"\/documentation\/gfpsdk\/gfpvideoschedule\/init(dictionary:noticeduration:witherror:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"dictionary"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier","text":"AnyHashable"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"text":"]?, ","kind":"text"},{"text":"noticeDuration","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"TimeInterval"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withError"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SA","kind":"typeIdentifier","text":"AutoreleasingUnsafeMutablePointer"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","text":"GFPError","preciseIdentifier":"c:@M@NaverAdsServices@objc(cs)GFPError"},{"text":"?>?)","kind":"text"}],"navigatorTitle":[{"text":"initWithDictionary:noticeDuration:withError:","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoSchedule\/init(dictionary:noticeDuration:withError:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoSchedule/postAdBreakList":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"postAdBreakList"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPVideoAdBreak","kind":"typeIdentifier","text":"GFPVideoAdBreak"},{"text":"]","kind":"text"}],"url":"\/documentation\/gfpsdk\/gfpvideoschedule\/postadbreaklist","navigatorTitle":[{"kind":"identifier","text":"postAdBreakList"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoSchedule\/postAdBreakList","title":"postAdBreakList","abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoSchedule/lastType":{"url":"\/documentation\/gfpsdk\/gfpvideoschedule\/lasttype","role":"symbol","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"lastType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"GFPVideoPlacementType","kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPVideoPlacementType"}],"type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoSchedule\/lastType","title":"lastType","kind":"symbol","navigatorTitle":[{"text":"lastType","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoSchedule/preAdBreakList":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoSchedule\/preAdBreakList","abstract":[],"role":"symbol","title":"preAdBreakList","kind":"symbol","url":"\/documentation\/gfpsdk\/gfpvideoschedule\/preadbreaklist","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"preAdBreakList"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPVideoAdBreak","text":"GFPVideoAdBreak","kind":"typeIdentifier"},{"kind":"text","text":"]"}],"navigatorTitle":[{"text":"preAdBreakList","kind":"identifier"}],"type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH"},"doc://com.navercorp.da.gfp.GFPSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject"},"doc://com.navercorp.da.gfp.GFPSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s7CVarArgP"},"doc://com.navercorp.da.gfp.GFPSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s23CustomStringConvertibleP"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoSchedule/adBreakList":{"kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoSchedule\/adBreakList","url":"\/documentation\/gfpsdk\/gfpvideoschedule\/adbreaklist","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"adBreakList"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"GFPVideoAdBreak","preciseIdentifier":"c:objc(cs)GFPVideoAdBreak"},{"kind":"text","text":"]"}],"title":"adBreakList","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"adBreakList"}],"abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoSchedule":{"type":"topic","abstract":[],"title":"GFPVideoSchedule","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPVideoSchedule","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpvideoschedule","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoSchedule","navigatorTitle":[{"text":"GFPVideoSchedule","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"GFPVideoSchedule","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"value":[{"text":"GFPVideoSchedule","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"GFPVideoSchedule","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoSchedule\/adBreakList","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoSchedule\/head","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoSchedule\/lastType","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoSchedule\/midAdBreakList","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoSchedule\/midPostAdBreakList","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoSchedule\/postAdBreakList","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoSchedule\/postSourceID","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoSchedule\/preAdBreakList","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoSchedule\/requestID","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoSchedule\/scheduleID"],"anchor":"Instance-Properties"},{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoSchedule\/adBreak(with:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoSchedule\/init(dictionary:noticeDuration:withError:)"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"title":"Inherits From","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"}]},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPVideoSchedule"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"value":"requestID","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoSchedule~1requestID\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoSchedule~1requestID\/fragments","value":[{"text":"requestID","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoSchedule~1postSourceID\/title","value":"postSourceID","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoSchedule~1postSourceID\/fragments","value":[{"kind":"identifier","text":"postSourceID"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoSchedule~1adBreak(with:)\/title","value":"adBreakWithAdSource:","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoSchedule~1adBreak(with:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"adBreakWithAdSource:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoSchedule~1midAdBreakList\/title","value":"midAdBreakList","op":"replace"},{"value":[{"kind":"identifier","text":"midAdBreakList"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoSchedule~1midAdBreakList\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoSchedule~1head\/title","value":"head","op":"replace"},{"op":"replace","value":[{"text":"head","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoSchedule~1head\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoSchedule~1scheduleID\/title","value":"scheduleID"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoSchedule~1scheduleID\/fragments","value":[{"text":"scheduleID","kind":"identifier"}],"op":"replace"},{"value":"midPostAdBreakList","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoSchedule~1midPostAdBreakList\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoSchedule~1midPostAdBreakList\/fragments","value":[{"text":"midPostAdBreakList","kind":"identifier"}],"op":"replace"},{"value":"initWithDictionary:noticeDuration:withError:","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoSchedule~1init(dictionary:noticeDuration:withError:)\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoSchedule~1init(dictionary:noticeDuration:withError:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithDictionary:noticeDuration:withError:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoSchedule~1postAdBreakList\/title","value":"postAdBreakList"},{"value":[{"text":"postAdBreakList","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoSchedule~1postAdBreakList\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoSchedule~1lastType\/title","value":"lastType","op":"replace"},{"value":[{"text":"lastType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoSchedule~1lastType\/fragments"},{"value":"preAdBreakList","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoSchedule~1preAdBreakList\/title","op":"replace"},{"value":[{"text":"preAdBreakList","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoSchedule~1preAdBreakList\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoSchedule~1adBreakList\/title","value":"adBreakList"},{"value":[{"text":"adBreakList","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoSchedule~1adBreakList\/fragments","op":"replace"},{"value":"GFPVideoSchedule","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoSchedule\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoSchedule\/fragments","op":"replace","value":[{"text":"GFPVideoSchedule","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"GFPVideoSchedule"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoSchedule\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}