{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdInfo"},"topicSections":[{"anchor":"Initializers","title":"Initializers","generated":true,"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdInfo\/init(provider:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdInfo\/init(provider:url:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdInfo\/init(provider:url:remindAdList:remindViewList:loudnessNormalization:)"]},{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdInfo\/adProviderName","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdInfo\/loudnessNormalization","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdInfo\/nonLinearViewList","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdInfo\/remindAdList","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdInfo\/url"]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s7CVarArgP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s23CustomStringConvertibleP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH"],"type":"conformsTo"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"GFPVideoAdInfo","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpvideoadinfo"]},{"paths":["\/documentation\/gfpsdk\/gfpvideoadinfo"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"title":"GFPVideoAdInfo","symbolKind":"class","modules":[{"name":"GFPSDK"}],"navigatorTitle":[{"text":"GFPVideoAdInfo","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPVideoAdInfo","kind":"identifier"}],"role":"symbol","externalID":"c:objc(cs)GFPVideoAdInfo","roleHeading":"Class"},"references":{"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdInfo/init(provider:)":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdInfo\/init(provider:)","title":"init(provider:)","role":"symbol","url":"\/documentation\/gfpsdk\/gfpvideoadinfo\/init(provider:)","kind":"symbol","navigatorTitle":[{"text":"initWithProvider:","kind":"identifier"}],"type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"provider"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdInfo/remindAdList":{"title":"remindAdList","type":"topic","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdInfo\/remindAdList","url":"\/documentation\/gfpsdk\/gfpvideoadinfo\/remindadlist","abstract":[{"type":"text","text":"로드된 Remind Ad (Text, Banner) : SMR 전용 상품"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"remindAdList"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPRemindAd","text":"GFPRemindAd"},{"kind":"text","text":"]?"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"remindAdList"}]},"doc://com.navercorp.da.gfp.GFPSDK/SH":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/objc(cs)NSObject":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdInfo/nonLinearViewList":{"title":"nonLinearViewList","type":"topic","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdInfo\/nonLinearViewList","url":"\/documentation\/gfpsdk\/gfpvideoadinfo\/nonlinearviewlist","abstract":[{"text":"로드된 Remind Ad (Text, Banner) View","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"nonLinearViewList"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"GFPNonLinearAdView","preciseIdentifier":"c:objc(cs)GFPNonLinearAdView"},{"text":"]?","kind":"text"}],"kind":"symbol","navigatorTitle":[{"text":"nonLinearViewList","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdInfo/init(provider:url:remindAdList:remindViewList:loudnessNormalization:)":{"abstract":[],"url":"\/documentation\/gfpsdk\/gfpvideoadinfo\/init(provider:url:remindadlist:remindviewlist:loudnessnormalization:)","role":"symbol","title":"init(provider:url:remindAdList:remindViewList:loudnessNormalization:)","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdInfo\/init(provider:url:remindAdList:remindViewList:loudnessNormalization:)","navigatorTitle":[{"text":"initWithProvider:url:remindAdList:remindViewList:loudnessNormalization:","kind":"identifier"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"provider","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"url"},{"kind":"text","text":": "},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"remindAdList"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPRemindAd","text":"GFPRemindAd","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"remindViewList","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPNonLinearAdView","text":"GFPNonLinearAdView","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"loudnessNormalization","kind":"externalParam"},{"kind":"text","text":": "},{"text":"GFPLoudnessNormalization","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPLoudnessNormalization"},{"kind":"text","text":")"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s28CustomDebugStringConvertibleP"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdInfo/loudnessNormalization":{"abstract":[{"type":"text","text":"로드된 Loudness Normalization."}],"url":"\/documentation\/gfpsdk\/gfpvideoadinfo\/loudnessnormalization","role":"symbol","title":"loudnessNormalization","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdInfo\/loudnessNormalization","navigatorTitle":[{"text":"loudnessNormalization","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"loudnessNormalization","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPLoudnessNormalization","text":"GFPLoudnessNormalization","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdInfo/adProviderName":{"navigatorTitle":[{"text":"adProviderName","kind":"identifier"}],"title":"adProviderName","abstract":[{"text":"로드된 광고 제공자 명 (없으면 nil)","type":"text"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdInfo\/adProviderName","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"adProviderName","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"url":"\/documentation\/gfpsdk\/gfpvideoadinfo\/adprovidername","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdInfo/url":{"kind":"symbol","title":"url","url":"\/documentation\/gfpsdk\/gfpvideoadinfo\/url","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"url"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdInfo\/url","type":"topic","navigatorTitle":[{"kind":"identifier","text":"url"}],"abstract":[{"text":"로드된 비디오 광고 URL","type":"text"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdInfo":{"kind":"symbol","title":"GFPVideoAdInfo","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdInfo","role":"symbol","navigatorTitle":[{"text":"GFPVideoAdInfo","kind":"identifier"}],"type":"topic","url":"\/documentation\/gfpsdk\/gfpvideoadinfo","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPVideoAdInfo"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdInfo/init(provider:url:)":{"kind":"symbol","title":"init(provider:url:)","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdInfo\/init(provider:url:)","role":"symbol","navigatorTitle":[{"text":"initWithProvider:url:","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpvideoadinfo\/init(provider:url:)","abstract":[],"type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"provider"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"url","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"text":"?)","kind":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"GFPVideoAdInfo"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"GFPVideoAdInfo","kind":"identifier"}]},{"op":"replace","value":[{"text":"GFPVideoAdInfo","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"generated":true,"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdInfo\/adProviderName","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdInfo\/loudnessNormalization","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdInfo\/nonLinearViewList","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdInfo\/remindAdList","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdInfo\/url"]},{"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdInfo\/init(provider:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdInfo\/init(provider:url:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdInfo\/init(provider:url:remindAdList:remindViewList:loudnessNormalization:)"],"generated":true}],"path":"\/topicSections"},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"}],"op":"replace"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPVideoAdInfo"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","value":"initWithProvider:","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdInfo~1init(provider:)\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdInfo~1init(provider:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithProvider:"}],"op":"replace"},{"value":"remindAdList","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdInfo~1remindAdList\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdInfo~1remindAdList\/fragments","value":[{"text":"remindAdList","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdInfo~1nonLinearViewList\/title","value":"nonLinearViewList","op":"replace"},{"value":[{"kind":"identifier","text":"nonLinearViewList"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdInfo~1nonLinearViewList\/fragments"},{"value":"initWithProvider:url:remindAdList:remindViewList:loudnessNormalization:","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdInfo~1init(provider:url:remindAdList:remindViewList:loudnessNormalization:)\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdInfo~1init(provider:url:remindAdList:remindViewList:loudnessNormalization:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"initWithProvider:url:remindAdList:remindViewList:loudnessNormalization:","kind":"identifier"}]},{"value":"loudnessNormalization","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdInfo~1loudnessNormalization\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdInfo~1loudnessNormalization\/fragments","value":[{"kind":"identifier","text":"loudnessNormalization"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdInfo~1adProviderName\/title","value":"adProviderName"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdInfo~1adProviderName\/fragments","op":"replace","value":[{"text":"adProviderName","kind":"identifier"}]},{"op":"replace","value":"url","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdInfo~1url\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdInfo~1url\/fragments","op":"replace","value":[{"kind":"identifier","text":"url"}]},{"value":"GFPVideoAdInfo","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdInfo\/title"},{"value":[{"kind":"identifier","text":"GFPVideoAdInfo"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdInfo\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdInfo\/navigatorTitle","value":[{"text":"GFPVideoAdInfo","kind":"identifier"}]},{"value":"initWithProvider:url:","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdInfo~1init(provider:url:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdInfo~1init(provider:url:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithProvider:url:"}],"op":"replace"}]}]}