{"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/gfpsdk\/gfpvideomediatordelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpvideomediatordelegate"]}],"sections":[],"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoMediatorDelegate","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"text":"GFPVideoMediatorDelegate","kind":"identifier"}],"role":"symbol","title":"GFPVideoMediatorDelegate","symbolKind":"protocol","roleHeading":"Protocol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPVideoMediatorDelegate"}],"externalID":"c:objc(pl)GFPVideoMediatorDelegate","modules":[{"name":"GFPSDK"}]},"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"GFPVideoMediatorDelegate","kind":"identifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"topicSections":[{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoMediatorDelegate\/videoMediator(_:didFailToLoadVideoAdaptorWithError:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoMediatorDelegate\/videoMediator(_:didLoadVideoAdaptor:)"],"generated":true,"title":"Instance Methods","anchor":"Instance-Methods"}],"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject"]}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoMediatorDelegate":{"url":"\/documentation\/gfpsdk\/gfpvideomediatordelegate","navigatorTitle":[{"kind":"identifier","text":"GFPVideoMediatorDelegate"}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPVideoMediatorDelegate","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoMediatorDelegate","type":"topic","abstract":[],"title":"GFPVideoMediatorDelegate","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoMediatorDelegate/videoMediator(_:didLoadVideoAdaptor:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"videoMediator","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPVideoMediator","kind":"typeIdentifier","text":"GFPVideoMediator"},{"text":", ","kind":"text"},{"text":"didLoadVideoAdaptor","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"GFPAdAdaptor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdAdaptor"},{"text":" & ","kind":"text"},{"preciseIdentifier":"c:objc(pl)GFPVideoAdapting","text":"GFPVideoAdapting","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoMediatorDelegate\/videoMediator(_:didLoadVideoAdaptor:)","title":"videoMediator(_:didLoadVideoAdaptor:)","required":true,"type":"topic","role":"symbol","abstract":[],"navigatorTitle":[{"text":"videoMediator:didLoadVideoAdaptor:","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpvideomediatordelegate\/videomediator(_:didloadvideoadaptor:)","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoMediatorDelegate/videoMediator(_:didFailToLoadVideoAdaptorWithError:)":{"required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"videoMediator","kind":"identifier"},{"text":"(","kind":"text"},{"text":"GFPVideoMediator","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoMediator"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFailToLoadVideoAdaptorWithError"},{"kind":"text","text":": "},{"text":"GFPError","preciseIdentifier":"c:@M@NaverAdsServices@objc(cs)GFPError","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[],"navigatorTitle":[{"text":"videoMediator:didFailToLoadVideoAdaptorWithError:","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpvideomediatordelegate\/videomediator(_:didfailtoloadvideoadaptorwitherror:)","kind":"symbol","type":"topic","role":"symbol","title":"videoMediator(_:didFailToLoadVideoAdaptorWithError:)","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoMediatorDelegate\/videoMediator(_:didFailToLoadVideoAdaptorWithError:)"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)NSObject":{"title":"NSObject","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Protocol"},{"value":"GFPVideoMediatorDelegate","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"value":[{"kind":"identifier","text":"GFPVideoMediatorDelegate"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"GFPVideoMediatorDelegate","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoMediatorDelegate\/videoMediator(_:didFailToLoadVideoAdaptorWithError:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoMediatorDelegate\/videoMediator(_:didLoadVideoAdaptor:)"],"title":"Instance Methods"}],"path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPVideoMediatorDelegate","kind":"identifier"},{"kind":"text","text":" <"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject","text":"NSObject"},{"text":">","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"GFPVideoMediatorDelegate","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoMediatorDelegate\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoMediatorDelegate\/fragments","value":[{"text":"GFPVideoMediatorDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoMediatorDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"GFPVideoMediatorDelegate"}],"op":"replace"},{"value":"videoMediator:didLoadVideoAdaptor:","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoMediatorDelegate~1videoMediator(_:didLoadVideoAdaptor:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoMediatorDelegate~1videoMediator(_:didLoadVideoAdaptor:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"videoMediator:didLoadVideoAdaptor:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoMediatorDelegate~1videoMediator(_:didFailToLoadVideoAdaptorWithError:)\/title","value":"videoMediator:didFailToLoadVideoAdaptorWithError:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"videoMediator:didFailToLoadVideoAdaptorWithError:"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoMediatorDelegate~1videoMediator(_:didFailToLoadVideoAdaptorWithError:)\/fragments"}]}]}