{"variants":[{"paths":["\/documentation\/gfpsdk\/gfpvideoadscheduledelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpvideoadscheduledelegate"]}],"kind":"symbol","topicSections":[{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleDelegate\/scheduleManager(_:didFailScheduleWithError:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleDelegate\/scheduleManager(_:didLoadedSchedule:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleDelegate\/scheduleManagerContentPauseRequest(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleDelegate\/scheduleManagerContentResumeRequest(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleDelegate\/scheduleManagerDidCompleted(_:)"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"}],"metadata":{"role":"symbol","navigatorTitle":[{"text":"GFPVideoAdScheduleDelegate","kind":"identifier"}],"symbolKind":"protocol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"GFPVideoAdScheduleDelegate","kind":"identifier"}],"roleHeading":"Protocol","title":"GFPVideoAdScheduleDelegate","modules":[{"name":"GFPSDK"}],"externalID":"c:objc(pl)GFPVideoAdScheduleDelegate"},"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject"],"type":"inheritsFrom","kind":"relationships"},{"kind":"relationships","title":"Inherited By","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManagerDelegate"],"type":"inheritedBy"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPVideoAdScheduleDelegate"},{"kind":"text","text":" : "},{"text":"NSObjectProtocol","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleDelegate","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdScheduleDelegate/scheduleManagerContentPauseRequest(_:)":{"role":"symbol","navigatorTitle":[{"text":"scheduleManagerContentPauseRequest:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"scheduleManagerContentPauseRequest","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"GFPVideoAdScheduleManager","preciseIdentifier":"c:objc(cs)GFPVideoAdScheduleManager"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleDelegate\/scheduleManagerContentPauseRequest(_:)","type":"topic","abstract":[{"text":"컨텐츠를 정지할 시점이 되었을 때 호출됩니다.","type":"text"}],"kind":"symbol","url":"\/documentation\/gfpsdk\/gfpvideoadscheduledelegate\/schedulemanagercontentpauserequest(_:)","title":"scheduleManagerContentPauseRequest(_:)"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)NSObject":{"title":"NSObject","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdScheduleDelegate":{"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPVideoAdScheduleDelegate","kind":"identifier"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"GFPVideoAdScheduleDelegate"}],"role":"symbol","url":"\/documentation\/gfpsdk\/gfpvideoadscheduledelegate","title":"GFPVideoAdScheduleDelegate","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleDelegate"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdScheduleManagerDelegate":{"type":"topic","kind":"symbol","url":"\/documentation\/gfpsdk\/gfpvideoadschedulemanagerdelegate","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManagerDelegate","title":"GFPVideoAdScheduleManagerDelegate","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"GFPVideoAdScheduleManagerDelegate"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPVideoAdScheduleManagerDelegate"}],"role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdScheduleDelegate/scheduleManager(_:didFailScheduleWithError:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"scheduleManager"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoAdScheduleManager","text":"GFPVideoAdScheduleManager"},{"text":", ","kind":"text"},{"text":"didFailScheduleWithError","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@NaverAdsServices@objc(cs)GFPError","text":"GFPError","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"scheduleManager:didFailScheduleWithError:","kind":"identifier"}],"abstract":[{"text":"광고 스케쥴 로드에 실패할 경우 호출됩니다. 스케쥴 매니저에서 start 를 호출하면 광고가 재생됩니다.","type":"text"},{"type":"text","text":" "},{"text":"(컨텐츠 영상을 재생해 주세요.)","type":"text"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleDelegate\/scheduleManager(_:didFailScheduleWithError:)","url":"\/documentation\/gfpsdk\/gfpvideoadscheduledelegate\/schedulemanager(_:didfailschedulewitherror:)","required":true,"role":"symbol","type":"topic","kind":"symbol","title":"scheduleManager(_:didFailScheduleWithError:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdScheduleDelegate/scheduleManagerDidCompleted(_:)":{"required":true,"navigatorTitle":[{"text":"scheduleManagerDidCompleted:","kind":"identifier"}],"title":"scheduleManagerDidCompleted(_:)","abstract":[{"text":"광고 스케쥴의 수행이 모두  완료된 경우 호출됩니다.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"컨텐츠 영상 종료 시점 (후광고가 있는 경우, 후광고 종료 시점)"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleDelegate\/scheduleManagerDidCompleted(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"scheduleManagerDidCompleted"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPVideoAdScheduleManager","kind":"typeIdentifier","text":"GFPVideoAdScheduleManager"},{"text":")","kind":"text"}],"url":"\/documentation\/gfpsdk\/gfpvideoadscheduledelegate\/schedulemanagerdidcompleted(_:)","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdScheduleDelegate/scheduleManagerContentResumeRequest(_:)":{"url":"\/documentation\/gfpsdk\/gfpvideoadscheduledelegate\/schedulemanagercontentresumerequest(_:)","navigatorTitle":[{"kind":"identifier","text":"scheduleManagerContentResumeRequest:"}],"title":"scheduleManagerContentResumeRequest(_:)","kind":"symbol","type":"topic","role":"symbol","abstract":[{"text":"컨텐츠를 재생할 시점이 되었을 때 호출됩니다.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"scheduleManagerContentResumeRequest"},{"kind":"text","text":"("},{"text":"GFPVideoAdScheduleManager","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoAdScheduleManager"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleDelegate\/scheduleManagerContentResumeRequest(_:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdScheduleDelegate/scheduleManager(_:didLoadedSchedule:)":{"navigatorTitle":[{"text":"scheduleManager:didLoadedSchedule:","kind":"identifier"}],"title":"scheduleManager(_:didLoadedSchedule:)","abstract":[{"type":"text","text":"광고 스케쥴이 성공적으로 로드가 완료된 경우 호출됩니다."}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleDelegate\/scheduleManager(_:didLoadedSchedule:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"scheduleManager"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPVideoAdScheduleManager","kind":"typeIdentifier","text":"GFPVideoAdScheduleManager"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didLoadedSchedule"},{"text":": [","kind":"text"},{"text":"GFPVideoAdBreak","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoAdBreak"},{"kind":"text","text":"]?)"}],"url":"\/documentation\/gfpsdk\/gfpvideoadscheduledelegate\/schedulemanager(_:didloadedschedule:)","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Protocol","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"GFPVideoAdScheduleDelegate","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"protocol"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"GFPVideoAdScheduleDelegate","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"GFPVideoAdScheduleDelegate","kind":"identifier"}]},{"op":"replace","value":[{"generated":true,"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleDelegate\/scheduleManager(_:didFailScheduleWithError:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleDelegate\/scheduleManager(_:didLoadedSchedule:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleDelegate\/scheduleManagerContentPauseRequest(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleDelegate\/scheduleManagerContentResumeRequest(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleDelegate\/scheduleManagerDidCompleted(_:)"]}],"path":"\/topicSections"},{"value":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject"]},{"title":"Inherited By","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManagerDelegate"],"type":"inheritedBy","kind":"relationships"}],"path":"\/relationshipsSections","op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPVideoAdScheduleDelegate","kind":"identifier"},{"text":" <","kind":"text"},{"preciseIdentifier":"c:objc(pl)NSObject","text":"NSObject","kind":"typeIdentifier"},{"text":">","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleDelegate~1scheduleManagerContentPauseRequest(_:)\/title","value":"scheduleManagerContentPauseRequest:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"scheduleManagerContentPauseRequest:"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleDelegate~1scheduleManagerContentPauseRequest(_:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleDelegate\/title","value":"GFPVideoAdScheduleDelegate"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleDelegate\/fragments","value":[{"kind":"identifier","text":"GFPVideoAdScheduleDelegate"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"GFPVideoAdScheduleDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManagerDelegate\/title","value":"GFPVideoAdScheduleManagerDelegate"},{"value":[{"text":"GFPVideoAdScheduleManagerDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManagerDelegate\/fragments"},{"value":[{"kind":"identifier","text":"GFPVideoAdScheduleManagerDelegate"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManagerDelegate\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleDelegate~1scheduleManager(_:didFailScheduleWithError:)\/title","value":"scheduleManager:didFailScheduleWithError:"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleDelegate~1scheduleManager(_:didFailScheduleWithError:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"scheduleManager:didFailScheduleWithError:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleDelegate~1scheduleManagerDidCompleted(_:)\/title","value":"scheduleManagerDidCompleted:"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleDelegate~1scheduleManagerDidCompleted(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"scheduleManagerDidCompleted:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleDelegate~1scheduleManagerContentResumeRequest(_:)\/title","value":"scheduleManagerContentResumeRequest:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"scheduleManagerContentResumeRequest:"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleDelegate~1scheduleManagerContentResumeRequest(_:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleDelegate~1scheduleManager(_:didLoadedSchedule:)\/title","value":"scheduleManager:didLoadedSchedule:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"scheduleManager:didLoadedSchedule:"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleDelegate~1scheduleManager(_:didLoadedSchedule:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}