{"metadata":{"role":"symbol","modules":[{"name":"GFPSDK"}],"externalID":"c:objc(pl)GFPVideoAdManagerDelegate","symbolKind":"protocol","title":"GFPVideoAdManagerDelegate","navigatorTitle":[{"kind":"identifier","text":"GFPVideoAdManagerDelegate"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPVideoAdManagerDelegate","kind":"identifier"}],"roleHeading":"Protocol"},"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject"],"type":"inheritsFrom"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"GFPVideoAdManagerDelegate","kind":"identifier"},{"kind":"text","text":" : "},{"text":"NSObjectProtocol","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpvideoadmanagerdelegate"]},{"paths":["\/documentation\/gfpsdk\/gfpvideoadmanagerdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManagerDelegate\/videoAdManager(_:didChangeCurrentTime:totalTime:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManagerDelegate\/videoAdManager(_:didFailWithError:responseInfo:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManagerDelegate\/videoAdManager(_:didReceive:)-3ws0n","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManagerDelegate\/videoAdManager(_:didReceive:)-98ycb","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManagerDelegate\/videoAdManager(_:playControlWillHide:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManagerDelegate\/videoAdManager(_:playControlWillShow:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManagerDelegate\/videoAdManagerDidCompleteAd(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManagerDelegate\/videoAdManagerDidDismissDefault(inAppBrowser:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManagerDelegate\/videoAdManagerDidLoadAd(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManagerDelegate\/videoAdManagerDidPauseAd(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManagerDelegate\/videoAdManagerDidPresentDefault(inAppBrowser:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManagerDelegate\/videoAdManagerDidResumeAd(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManagerDelegate\/videoAdManagerDidStartAd(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManagerDelegate\/videoAdWasClicked(_:)"],"generated":true}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"kind":"symbol","identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManagerDelegate","interfaceLanguage":"swift"},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdManagerDelegate/videoAdManagerDidPauseAd(_:)":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"videoAdManagerDidPauseAd:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"videoAdManagerDidPauseAd","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)GFPVideoAdManager","text":"GFPVideoAdManager","kind":"typeIdentifier"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManagerDelegate\/videoAdManagerDidPauseAd(_:)","type":"topic","abstract":[{"text":"광고 재생 정지시 호출됩니다.","type":"text"}],"kind":"symbol","url":"\/documentation\/gfpsdk\/gfpvideoadmanagerdelegate\/videoadmanagerdidpausead(_:)","title":"videoAdManagerDidPauseAd(_:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdManagerDelegate/videoAdManagerDidDismissDefault(inAppBrowser:)":{"required":true,"role":"symbol","abstract":[{"text":"Default In App Browser 사용 시, SFSafariViewController가 정상적으로 Dismiss 시 호출됩니다.","type":"text"}],"title":"videoAdManagerDidDismissDefault(inAppBrowser:)","navigatorTitle":[{"text":"videoAdManagerDidDismissDefaultInAppBrowser:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"videoAdManagerDidDismissDefault","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"inAppBrowser"},{"text":": ","kind":"text"},{"text":"GFPVideoAdManager","preciseIdentifier":"c:objc(cs)GFPVideoAdManager","kind":"typeIdentifier"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManagerDelegate\/videoAdManagerDidDismissDefault(inAppBrowser:)","type":"topic","kind":"symbol","url":"\/documentation\/gfpsdk\/gfpvideoadmanagerdelegate\/videoadmanagerdiddismissdefault(inappbrowser:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdManagerDelegate/videoAdManager(_:didReceive:)-3ws0n":{"url":"\/documentation\/gfpsdk\/gfpvideoadmanagerdelegate\/videoadmanager(_:didreceive:)-3ws0n","title":"videoAdManager(_:didReceive:)","abstract":[{"type":"text","text":"재생중인 광고플레이어가 AVPlayer 일 때(현재 NDA 한정), AVPlayerItem 에서 AccessLogEvent 가 발생한 경우 호출됩니다."}],"role":"symbol","required":true,"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManagerDelegate\/videoAdManager(_:didReceive:)-3ws0n","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"videoAdManager","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)GFPVideoAdManager","kind":"typeIdentifier","text":"GFPVideoAdManager"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didReceive"},{"text":": ","kind":"text"},{"text":"AVPlayerItemAccessLog","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVPlayerItemAccessLog"},{"text":")","kind":"text"}],"kind":"symbol","navigatorTitle":[{"text":"videoAdManager:didReceiveAccessLog:","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdManagerDelegate":{"type":"topic","url":"\/documentation\/gfpsdk\/gfpvideoadmanagerdelegate","title":"GFPVideoAdManagerDelegate","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManagerDelegate","kind":"symbol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPVideoAdManagerDelegate"}],"navigatorTitle":[{"kind":"identifier","text":"GFPVideoAdManagerDelegate"}],"abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdManagerDelegate/videoAdManagerDidLoadAd(_:)":{"required":true,"url":"\/documentation\/gfpsdk\/gfpvideoadmanagerdelegate\/videoadmanagerdidloadad(_:)","navigatorTitle":[{"text":"videoAdManagerDidLoadAd:","kind":"identifier"}],"abstract":[{"type":"text","text":"광고가 성공적으로 로드될 경우 호출됩니다. 광고 매니저에서 startAd 를 호출하면 광고가 재생됩니다."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"videoAdManagerDidLoadAd"},{"kind":"text","text":"("},{"text":"GFPVideoAdManager","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoAdManager"},{"text":")","kind":"text"}],"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManagerDelegate\/videoAdManagerDidLoadAd(_:)","title":"videoAdManagerDidLoadAd(_:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdManagerDelegate/videoAdManagerDidResumeAd(_:)":{"required":true,"role":"symbol","abstract":[{"text":"광고 재생 재 시작시 호출됩니다.","type":"text"}],"title":"videoAdManagerDidResumeAd(_:)","navigatorTitle":[{"text":"videoAdManagerDidResumeAd:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoAdManagerDidResumeAd"},{"text":"(","kind":"text"},{"text":"GFPVideoAdManager","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoAdManager"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManagerDelegate\/videoAdManagerDidResumeAd(_:)","type":"topic","kind":"symbol","url":"\/documentation\/gfpsdk\/gfpvideoadmanagerdelegate\/videoadmanagerdidresumead(_:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdManagerDelegate/videoAdManager(_:playControlWillShow:)":{"required":true,"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"videoAdManager","kind":"identifier"},{"text":"(","kind":"text"},{"text":"GFPVideoAdManager","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoAdManager"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"playControlWillShow"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"재생 컨트롤 Hide 애니메이션 시작 시 호출됩니다."}],"navigatorTitle":[{"text":"videoAdManager:playControlWillShow:","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpvideoadmanagerdelegate\/videoadmanager(_:playcontrolwillshow:)","kind":"symbol","type":"topic","role":"symbol","title":"videoAdManager(_:playControlWillShow:)","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManagerDelegate\/videoAdManager(_:playControlWillShow:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdManagerDelegate/videoAdManager(_:didReceive:)-98ycb":{"navigatorTitle":[{"text":"videoAdManager:didReceiveAccessLogEvents:","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpvideoadmanagerdelegate\/videoadmanager(_:didreceive:)-98ycb","title":"videoAdManager(_:didReceive:)","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManagerDelegate\/videoAdManager(_:didReceive:)-98ycb","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"videoAdManager","kind":"identifier"},{"kind":"text","text":"("},{"text":"GFPVideoAdManager","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoAdManager"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceive"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:objc(cs)AVPlayerItemAccessLogEvent","kind":"typeIdentifier","text":"AVPlayerItemAccessLogEvent"},{"text":"])","kind":"text"}],"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"재생중인 광고플레이어가 AVPlayer 일 때(현재 NDA 한정), AVPlayerItem 에서 AccessLogEvent 가 발생한 경우 호출됩니다."}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdManagerDelegate/videoAdManagerDidCompleteAd(_:)":{"title":"videoAdManagerDidCompleteAd(_:)","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManagerDelegate\/videoAdManagerDidCompleteAd(_:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoAdManagerDidCompleteAd"},{"kind":"text","text":"("},{"text":"GFPVideoAdManager","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoAdManager"},{"text":")","kind":"text"}],"abstract":[{"text":"광고 재생 종료시 호출됩니다.","type":"text"},{"type":"text","text":" "},{"text":"(본 영상을 재생해 주세요.)","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"videoAdManagerDidCompleteAd:"}],"url":"\/documentation\/gfpsdk\/gfpvideoadmanagerdelegate\/videoadmanagerdidcompletead(_:)","type":"topic","role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdManagerDelegate/videoAdManagerDidStartAd(_:)":{"required":true,"url":"\/documentation\/gfpsdk\/gfpvideoadmanagerdelegate\/videoadmanagerdidstartad(_:)","navigatorTitle":[{"text":"videoAdManagerDidStartAd:","kind":"identifier"}],"abstract":[{"type":"text","text":"광고 재생 시작시 호출됩니다."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"videoAdManagerDidStartAd"},{"kind":"text","text":"("},{"text":"GFPVideoAdManager","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoAdManager"},{"text":")","kind":"text"}],"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManagerDelegate\/videoAdManagerDidStartAd(_:)","title":"videoAdManagerDidStartAd(_:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdManagerDelegate/videoAdManager(_:didChangeCurrentTime:totalTime:)":{"role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManagerDelegate\/videoAdManager(_:didChangeCurrentTime:totalTime:)","type":"topic","abstract":[{"text":"광고 중인 영상의  현재 progress가 변경될 떄마다 호출됩니다.","type":"text"}],"url":"\/documentation\/gfpsdk\/gfpvideoadmanagerdelegate\/videoadmanager(_:didchangecurrenttime:totaltime:)","title":"videoAdManager(_:didChangeCurrentTime:totalTime:)","navigatorTitle":[{"kind":"identifier","text":"videoAdManager:didChangeCurrentTime:totalTime:"}],"required":true,"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"videoAdManager","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GFPVideoAdManager","preciseIdentifier":"c:objc(cs)GFPVideoAdManager"},{"text":", ","kind":"text"},{"text":"didChangeCurrentTime","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"kind":"text","text":", "},{"text":"totalTime","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":")","kind":"text"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdManagerDelegate/videoAdManager(_:didFailWithError:responseInfo:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"videoAdManager"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoAdManager","text":"GFPVideoAdManager"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didFailWithError"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@NaverAdsServices@objc(cs)GFPError","text":"GFPError","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"responseInfo","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"GFPLoadResponseInfo","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPLoadResponseInfo"},{"kind":"text","text":")"}],"kind":"symbol","navigatorTitle":[{"text":"videoAdManager:didFailWithError:responseInfo:","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManagerDelegate\/videoAdManager(_:didFailWithError:responseInfo:)","abstract":[{"text":"광고 로드\/재생에 실패한 경우 호출됩니다.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"(본 영상을 재생해 주세요.)"}],"role":"symbol","url":"\/documentation\/gfpsdk\/gfpvideoadmanagerdelegate\/videoadmanager(_:didfailwitherror:responseinfo:)","title":"videoAdManager(_:didFailWithError:responseInfo:)","required":true,"type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)NSObject":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","type":"unresolvable","title":"NSObject"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdManagerDelegate/videoAdManager(_:playControlWillHide:)":{"required":true,"url":"\/documentation\/gfpsdk\/gfpvideoadmanagerdelegate\/videoadmanager(_:playcontrolwillhide:)","navigatorTitle":[{"kind":"identifier","text":"videoAdManager:playControlWillHide:"}],"abstract":[{"text":"재생 컨트롤 Show 애니메이션 시작 시 호출됩니다.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoAdManager"},{"text":"(","kind":"text"},{"text":"GFPVideoAdManager","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoAdManager"},{"kind":"text","text":", "},{"text":"playControlWillHide","kind":"externalParam"},{"kind":"text","text":": "},{"text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManagerDelegate\/videoAdManager(_:playControlWillHide:)","title":"videoAdManager(_:playControlWillHide:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdManagerDelegate/videoAdManagerDidPresentDefault(inAppBrowser:)":{"type":"topic","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Default In App Browser 사용 시, SFSafariViewController가 정상적으로 Present 시 호출됩니다."}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManagerDelegate\/videoAdManagerDidPresentDefault(inAppBrowser:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"videoAdManagerDidPresentDefault","kind":"identifier"},{"text":"(","kind":"text"},{"text":"inAppBrowser","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoAdManager","text":"GFPVideoAdManager"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"videoAdManagerDidPresentDefaultInAppBrowser:","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpvideoadmanagerdelegate\/videoadmanagerdidpresentdefault(inappbrowser:)","title":"videoAdManagerDidPresentDefault(inAppBrowser:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdManagerDelegate/videoAdWasClicked(_:)":{"role":"symbol","abstract":[{"type":"text","text":"광고 클릭시 호출됩니다."}],"title":"videoAdWasClicked(_:)","navigatorTitle":[{"text":"videoAdWasClicked:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"videoAdWasClicked","kind":"identifier"},{"text":"(","kind":"text"},{"text":"GFPVideoAdManager","preciseIdentifier":"c:objc(cs)GFPVideoAdManager","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManagerDelegate\/videoAdWasClicked(_:)","type":"topic","kind":"symbol","url":"\/documentation\/gfpsdk\/gfpvideoadmanagerdelegate\/videoadwasclicked(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Protocol","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"GFPVideoAdManagerDelegate"},{"op":"replace","value":"protocol","path":"\/metadata\/symbolKind"},{"value":[{"text":"GFPVideoAdManagerDelegate","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"GFPVideoAdManagerDelegate","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManagerDelegate\/videoAdManager(_:didChangeCurrentTime:totalTime:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManagerDelegate\/videoAdManager(_:didFailWithError:responseInfo:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManagerDelegate\/videoAdManager(_:didReceive:)-3ws0n","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManagerDelegate\/videoAdManager(_:didReceive:)-98ycb","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManagerDelegate\/videoAdManager(_:playControlWillHide:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManagerDelegate\/videoAdManager(_:playControlWillShow:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManagerDelegate\/videoAdManagerDidCompleteAd(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManagerDelegate\/videoAdManagerDidDismissDefault(inAppBrowser:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManagerDelegate\/videoAdManagerDidLoadAd(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManagerDelegate\/videoAdManagerDidPauseAd(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManagerDelegate\/videoAdManagerDidPresentDefault(inAppBrowser:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManagerDelegate\/videoAdManagerDidResumeAd(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManagerDelegate\/videoAdManagerDidStartAd(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManagerDelegate\/videoAdWasClicked(_:)"],"generated":true}]},{"value":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject"]}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPVideoAdManagerDelegate"},{"text":" <","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier"},{"kind":"text","text":">"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManagerDelegate~1videoAdManagerDidPauseAd(_:)\/title","value":"videoAdManagerDidPauseAd:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"videoAdManagerDidPauseAd:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManagerDelegate~1videoAdManagerDidPauseAd(_:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManagerDelegate~1videoAdManagerDidDismissDefault(inAppBrowser:)\/title","value":"videoAdManagerDidDismissDefaultInAppBrowser:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"videoAdManagerDidDismissDefaultInAppBrowser:"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManagerDelegate~1videoAdManagerDidDismissDefault(inAppBrowser:)\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManagerDelegate~1videoAdManager(_:didReceive:)-3ws0n\/title","value":"videoAdManager:didReceiveAccessLog:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManagerDelegate~1videoAdManager(_:didReceive:)-3ws0n\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"videoAdManager:didReceiveAccessLog:"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManagerDelegate\/title","value":"GFPVideoAdManagerDelegate","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"GFPVideoAdManagerDelegate"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManagerDelegate\/fragments"},{"value":[{"text":"GFPVideoAdManagerDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManagerDelegate\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManagerDelegate~1videoAdManagerDidLoadAd(_:)\/title","value":"videoAdManagerDidLoadAd:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"videoAdManagerDidLoadAd:"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManagerDelegate~1videoAdManagerDidLoadAd(_:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManagerDelegate~1videoAdManagerDidResumeAd(_:)\/title","value":"videoAdManagerDidResumeAd:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"videoAdManagerDidResumeAd:"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManagerDelegate~1videoAdManagerDidResumeAd(_:)\/fragments"},{"op":"replace","value":"videoAdManager:playControlWillShow:","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManagerDelegate~1videoAdManager(_:playControlWillShow:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManagerDelegate~1videoAdManager(_:playControlWillShow:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"videoAdManager:playControlWillShow:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManagerDelegate~1videoAdManager(_:didReceive:)-98ycb\/title","value":"videoAdManager:didReceiveAccessLogEvents:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManagerDelegate~1videoAdManager(_:didReceive:)-98ycb\/fragments","value":[{"kind":"text","text":"- "},{"text":"videoAdManager:didReceiveAccessLogEvents:","kind":"identifier"}]},{"value":"videoAdManagerDidCompleteAd:","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManagerDelegate~1videoAdManagerDidCompleteAd(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManagerDelegate~1videoAdManagerDidCompleteAd(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"videoAdManagerDidCompleteAd:","kind":"identifier"}]},{"op":"replace","value":"videoAdManagerDidStartAd:","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManagerDelegate~1videoAdManagerDidStartAd(_:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"videoAdManagerDidStartAd:"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManagerDelegate~1videoAdManagerDidStartAd(_:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManagerDelegate~1videoAdManager(_:didChangeCurrentTime:totalTime:)\/title","value":"videoAdManager:didChangeCurrentTime:totalTime:","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManagerDelegate~1videoAdManager(_:didChangeCurrentTime:totalTime:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"videoAdManager:didChangeCurrentTime:totalTime:","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"videoAdManager:didFailWithError:responseInfo:","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManagerDelegate~1videoAdManager(_:didFailWithError:responseInfo:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"videoAdManager:didFailWithError:responseInfo:"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManagerDelegate~1videoAdManager(_:didFailWithError:responseInfo:)\/fragments"},{"value":"videoAdManager:playControlWillHide:","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManagerDelegate~1videoAdManager(_:playControlWillHide:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManagerDelegate~1videoAdManager(_:playControlWillHide:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"videoAdManager:playControlWillHide:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManagerDelegate~1videoAdManagerDidPresentDefault(inAppBrowser:)\/title","value":"videoAdManagerDidPresentDefaultInAppBrowser:"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManagerDelegate~1videoAdManagerDidPresentDefault(inAppBrowser:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"videoAdManagerDidPresentDefaultInAppBrowser:","kind":"identifier"}]},{"value":"videoAdWasClicked:","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManagerDelegate~1videoAdWasClicked(_:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"videoAdWasClicked:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManagerDelegate~1videoAdWasClicked(_:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}