{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpvideoeventdelegate"]},{"paths":["\/documentation\/gfpsdk\/gfpvideoeventdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"GFPVideoEventDelegate"}],"externalID":"c:objc(pl)GFPVideoEventDelegate","symbolKind":"protocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPVideoEventDelegate","kind":"identifier"}],"role":"symbol","roleHeading":"Protocol","modules":[{"name":"GFPSDK"}],"title":"GFPVideoEventDelegate"},"topicSections":[{"generated":true,"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoEventDelegate\/adPlayer(_:didChangeBufferedTime:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoEventDelegate\/adPlayer(_:didChangeCurrentTime:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoEventDelegate\/adPlayer(_:didTappedControlButton:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoEventDelegate\/adPlayerDidChangeMuteState(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoEventDelegate\/adPlayerDidComplete(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoEventDelegate\/adPlayerDidPause(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoEventDelegate\/adPlayerDidPlay(_:)"],"anchor":"Instance-Methods","title":"Instance Methods"}],"relationshipsSections":[{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"GFPVideoEventDelegate","kind":"identifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoEventDelegate"},"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoEventDelegate/adPlayerDidPlay(_:)":{"required":true,"navigatorTitle":[{"kind":"identifier","text":"adPlayerDidPlay:"}],"title":"adPlayerDidPlay(_:)","abstract":[{"text":"네이티브 광고 영상 재생 시 호출됩니다.","type":"text"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoEventDelegate\/adPlayerDidPlay(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"adPlayerDidPlay","kind":"identifier"},{"kind":"text","text":"("},{"text":"GFPVideoController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoController"},{"text":"!)","kind":"text"}],"url":"\/documentation\/gfpsdk\/gfpvideoeventdelegate\/adplayerdidplay(_:)","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoEventDelegate/adPlayer(_:didChangeCurrentTime:)":{"role":"symbol","navigatorTitle":[{"text":"adPlayer:didChangeCurrentTime:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"adPlayer"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)GFPVideoController","kind":"typeIdentifier","text":"GFPVideoController"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"didChangeCurrentTime"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoEventDelegate\/adPlayer(_:didChangeCurrentTime:)","type":"topic","abstract":[{"type":"text","text":"네이티브 광고 영상의 현재 진행률 변경 시 호출됩니다."}],"kind":"symbol","url":"\/documentation\/gfpsdk\/gfpvideoeventdelegate\/adplayer(_:didchangecurrenttime:)","required":true,"title":"adPlayer(_:didChangeCurrentTime:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoEventDelegate/adPlayer(_:didTappedControlButton:)":{"required":true,"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"adPlayer:didTappedControlButton:"}],"abstract":[{"text":"네이티브 광고 영상의 control 버튼 클릭 시 호출 됩니다.","type":"text"},{"type":"text","text":" "},{"text":"sdk에서 제공하는 default controlView 사용시 호출되며,  customControlView 사용시 호출되지 않습니다.","type":"text"}],"kind":"symbol","title":"adPlayer(_:didTappedControlButton:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"adPlayer","kind":"identifier"},{"kind":"text","text":"("},{"text":"GFPVideoController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoController"},{"text":"!, ","kind":"text"},{"text":"didTappedControlButton","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@GFPControlButtonType","text":"GFPControlButtonType","kind":"typeIdentifier"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoEventDelegate\/adPlayer(_:didTappedControlButton:)","url":"\/documentation\/gfpsdk\/gfpvideoeventdelegate\/adplayer(_:didtappedcontrolbutton:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoEventDelegate/adPlayerDidPause(_:)":{"type":"topic","title":"adPlayerDidPause(_:)","abstract":[{"type":"text","text":"네이티브 광고 영상 정지 시 호출됩니다."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"adPlayerDidPause","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoController","text":"GFPVideoController"},{"text":"!)","kind":"text"}],"url":"\/documentation\/gfpsdk\/gfpvideoeventdelegate\/adplayerdidpause(_:)","role":"symbol","required":true,"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoEventDelegate\/adPlayerDidPause(_:)","navigatorTitle":[{"text":"adPlayerDidPause:","kind":"identifier"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoEventDelegate/adPlayerDidChangeMuteState(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"adPlayerDidChangeMuteState"},{"kind":"text","text":"("},{"text":"GFPVideoController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoController"},{"kind":"text","text":"!)"}],"url":"\/documentation\/gfpsdk\/gfpvideoeventdelegate\/adplayerdidchangemutestate(_:)","title":"adPlayerDidChangeMuteState(_:)","abstract":[{"type":"text","text":"네이티브 광고 영상 플레이어에 mute  상태가 변경 될 때 호출됩니다."}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoEventDelegate\/adPlayerDidChangeMuteState(_:)","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"adPlayerDidChangeMuteState:","kind":"identifier"}],"type":"topic","required":true},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoEventDelegate/adPlayer(_:didChangeBufferedTime:)":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoEventDelegate\/adPlayer(_:didChangeBufferedTime:)","abstract":[{"type":"text","text":"네이티브 광고 영상의 버퍼 진행률 변경 시 호출됩니다."}],"required":true,"role":"symbol","title":"adPlayer(_:didChangeBufferedTime:)","kind":"symbol","url":"\/documentation\/gfpsdk\/gfpvideoeventdelegate\/adplayer(_:didchangebufferedtime:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"adPlayer","kind":"identifier"},{"kind":"text","text":"("},{"text":"GFPVideoController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoController"},{"text":"!, ","kind":"text"},{"kind":"externalParam","text":"didChangeBufferedTime"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"adPlayer:didChangeBufferedTime:"}],"type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoEventDelegate/adPlayerDidComplete(_:)":{"required":true,"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoEventDelegate\/adPlayerDidComplete(_:)","navigatorTitle":[{"text":"adPlayerDidComplete:","kind":"identifier"}],"abstract":[{"text":"네이티브 광고 영상 재생 완료 시 호출됩니다.","type":"text"}],"title":"adPlayerDidComplete(_:)","role":"symbol","kind":"symbol","url":"\/documentation\/gfpsdk\/gfpvideoeventdelegate\/adplayerdidcomplete(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"adPlayerDidComplete","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GFPVideoController","preciseIdentifier":"c:objc(cs)GFPVideoController"},{"kind":"text","text":"!)"}],"type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoEventDelegate":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPVideoEventDelegate"}],"navigatorTitle":[{"kind":"identifier","text":"GFPVideoEventDelegate"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoEventDelegate","url":"\/documentation\/gfpsdk\/gfpvideoeventdelegate","kind":"symbol","role":"symbol","abstract":[],"title":"GFPVideoEventDelegate","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"GFPVideoEventDelegate"},{"op":"replace","value":"protocol","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"GFPVideoEventDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"GFPVideoEventDelegate"}],"op":"replace"},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoEventDelegate\/adPlayer(_:didChangeBufferedTime:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoEventDelegate\/adPlayer(_:didChangeCurrentTime:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoEventDelegate\/adPlayer(_:didTappedControlButton:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoEventDelegate\/adPlayerDidChangeMuteState(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoEventDelegate\/adPlayerDidComplete(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoEventDelegate\/adPlayerDidPause(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoEventDelegate\/adPlayerDidPlay(_:)"],"anchor":"Instance-Methods","title":"Instance Methods","generated":true}]},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"}],"op":"replace"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPVideoEventDelegate","kind":"identifier"},{"text":" <","kind":"text"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(pl)NSObject"},{"text":">","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoEventDelegate~1adPlayerDidPlay(_:)\/title","value":"adPlayerDidPlay:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoEventDelegate~1adPlayerDidPlay(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"adPlayerDidPlay:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoEventDelegate~1adPlayer(_:didChangeCurrentTime:)\/title","value":"adPlayer:didChangeCurrentTime:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"adPlayer:didChangeCurrentTime:"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoEventDelegate~1adPlayer(_:didChangeCurrentTime:)\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoEventDelegate~1adPlayer(_:didTappedControlButton:)\/title","op":"replace","value":"adPlayer:didTappedControlButton:"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoEventDelegate~1adPlayer(_:didTappedControlButton:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"adPlayer:didTappedControlButton:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoEventDelegate~1adPlayerDidPause(_:)\/title","value":"adPlayerDidPause:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"adPlayerDidPause:"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoEventDelegate~1adPlayerDidPause(_:)\/fragments","op":"replace"},{"op":"replace","value":"adPlayerDidChangeMuteState:","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoEventDelegate~1adPlayerDidChangeMuteState(_:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"adPlayerDidChangeMuteState:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoEventDelegate~1adPlayerDidChangeMuteState(_:)\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoEventDelegate~1adPlayer(_:didChangeBufferedTime:)\/title","op":"replace","value":"adPlayer:didChangeBufferedTime:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"adPlayer:didChangeBufferedTime:"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoEventDelegate~1adPlayer(_:didChangeBufferedTime:)\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoEventDelegate~1adPlayerDidComplete(_:)\/title","value":"adPlayerDidComplete:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"adPlayerDidComplete:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoEventDelegate~1adPlayerDidComplete(_:)\/fragments","op":"replace"},{"op":"replace","value":"GFPVideoEventDelegate","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoEventDelegate\/title"},{"value":[{"kind":"identifier","text":"GFPVideoEventDelegate"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoEventDelegate\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoEventDelegate\/navigatorTitle","value":[{"text":"GFPVideoEventDelegate","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}