{"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"sections":[],"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject"]},{"type":"conformsTo","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s7CVarArgP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s8CopyableP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s23CustomStringConvertibleP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH","doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)WKScriptMessageHandlerWithReply"],"title":"Conforms To","kind":"relationships"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpwebviewmanager"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpwebviewmanager"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPWebViewManager","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"topicSections":[{"anchor":"Instance-Methods","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPWebViewManager\/addHandlers(to:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPWebViewManager\/examineWebViewStatus(webView:result:)"],"generated":true,"title":"Instance Methods"},{"generated":true,"anchor":"Type-Properties","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPWebViewManager\/shared"],"title":"Type Properties"},{"title":"Default Implementations","anchor":"Default-Implementations","generated":true,"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPWebViewManager\/WKScriptMessageHandlerWithReply-Implementations"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPWebViewManager"},"metadata":{"symbolKind":"class","modules":[{"name":"GFPSDK"}],"roleHeading":"Class","title":"GFPWebViewManager","externalID":"c:@M@GFPSDK@objc(cs)GFPWebViewManager","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPWebViewManager"}],"navigatorTitle":[{"text":"GFPWebViewManager","kind":"identifier"}]},"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s23CustomStringConvertibleP"},"doc://com.navercorp.da.gfp.GFPSDK/s7CVarArgP":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPWebViewManager/shared":{"url":"\/documentation\/gfpsdk\/gfpwebviewmanager\/shared","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"shared","kind":"identifier"},{"text":": ","kind":"text"},{"text":"GFPWebViewManager","preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPWebViewManager","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPWebViewManager\/shared","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"shared"}],"role":"symbol","title":"shared","type":"topic","abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/objc(cs)NSObject":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)NSObject":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)WKScriptMessageHandlerWithReply":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)WKScriptMessageHandlerWithReply","title":"WKScriptMessageHandlerWithReply","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/s8CopyableP":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s8CopyableP","title":"Swift.Copyable","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPWebViewManager/addHandlers(to:)":{"type":"topic","role":"symbol","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPWebViewManager\/addHandlers(to:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"addHandlers","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"text":"WKUserContentController","preciseIdentifier":"c:objc(cs)WKUserContentController","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"addHandlersTo:","kind":"identifier"}],"title":"addHandlers(to:)","url":"\/documentation\/gfpsdk\/gfpwebviewmanager\/addhandlers(to:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPWebViewManager/init":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPWebViewManager\/init","title":"init","url":"\/documentation\/gfpsdk\/gfpwebviewmanager\/init","navigatorTitle":[{"text":"init","kind":"identifier"}],"role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"abstract":[],"kind":"symbol","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/SH":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/SQ":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPWebViewManager/WKScriptMessageHandlerWithReply-Implementations":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPWebViewManager\/WKScriptMessageHandlerWithReply-Implementations","kind":"article","type":"topic","abstract":[],"role":"collectionGroup","title":"WKScriptMessageHandlerWithReply Implementations","url":"\/documentation\/gfpsdk\/gfpwebviewmanager\/wkscriptmessagehandlerwithreply-implementations"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPWebViewManager":{"title":"GFPWebViewManager","role":"symbol","navigatorTitle":[{"text":"GFPWebViewManager","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpwebviewmanager","kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPWebViewManager","abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPWebViewManager"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPWebViewManager/examineWebViewStatus(webView:result:)":{"role":"symbol","title":"examineWebViewStatus(webView:result:)","abstract":[],"url":"\/documentation\/gfpsdk\/gfpwebviewmanager\/examinewebviewstatus(webview:result:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"examineWebViewStatus","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"webView"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKWebView","text":"WKWebView"},{"text":", ","kind":"text"},{"text":"result","kind":"externalParam"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":"?, [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"text":"]?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"examineWebViewStatusWithWebView:result:","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPWebViewManager\/examineWebViewStatus(webView:result:)","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"GFPWebViewManager"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"GFPWebViewManager","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"GFPWebViewManager","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPWebViewManager\/addHandlers(to:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPWebViewManager\/examineWebViewStatus(webView:result:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPWebViewManager\/init"]},{"generated":true,"anchor":"Type-Properties","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPWebViewManager\/shared"],"title":"Type Properties"},{"anchor":"Default-Implementations","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPWebViewManager\/WKScriptMessageHandlerWithReply-Implementations"],"generated":true,"title":"Default Implementations"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships"},{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)WKScriptMessageHandlerWithReply"]}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPWebViewManager"},{"kind":"text","text":" : "},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"value":"shared","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPWebViewManager~1shared\/title","op":"replace"},{"value":[{"kind":"identifier","text":"shared"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPWebViewManager~1shared\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPWebViewManager~1addHandlers(to:)\/title","value":"addHandlersTo:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"addHandlersTo:"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPWebViewManager~1addHandlers(to:)\/fragments"},{"value":"GFPWebViewManager","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPWebViewManager\/title"},{"op":"replace","value":[{"kind":"identifier","text":"GFPWebViewManager"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPWebViewManager\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPWebViewManager\/navigatorTitle","value":[{"kind":"identifier","text":"GFPWebViewManager"}],"op":"replace"},{"value":"examineWebViewStatusWithWebView:result:","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPWebViewManager~1examineWebViewStatus(webView:result:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"examineWebViewStatusWithWebView:result:"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPWebViewManager~1examineWebViewStatus(webView:result:)\/fragments"}]}]}