{"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"variants":[{"paths":["\/documentation\/gfpsdk\/icon"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/icon"]}],"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPTrackingPresentable"]},{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSCopying","doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s7CVarArgP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s23CustomStringConvertibleP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH"],"type":"conformsTo"}],"metadata":{"navigatorTitle":[{"text":"Icon","kind":"identifier"}],"role":"symbol","symbolKind":"class","roleHeading":"Class","externalID":"c:objc(cs)Icon","modules":[{"name":"GFPSDK"}],"title":"Icon","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Icon"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"topicSections":[{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/Icon\/apiFramework","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/Icon\/code","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/Icon\/duration","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/Icon\/hasDuration","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/Icon\/offset","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/Icon\/resource","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/Icon\/value","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/Icon\/xPosition","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/Icon\/yPosition"],"anchor":"Instance-Properties","generated":true,"title":"Instance Properties"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Icon","kind":"identifier"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/Icon","interfaceLanguage":"swift"},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/Icon/yPosition":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"yPosition"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/Icon\/yPosition","title":"yPosition","url":"\/documentation\/gfpsdk\/icon\/yposition","abstract":[],"kind":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"yPosition","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/Icon/duration":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"duration"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"}],"navigatorTitle":[{"text":"duration","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/gfpsdk\/icon\/duration","title":"duration","abstract":[],"role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/Icon\/duration"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/Icon":{"url":"\/documentation\/gfpsdk\/icon","title":"Icon","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/Icon","kind":"symbol","role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Icon","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"Icon"}],"abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/Icon/initWithDomElement:duration:error:":{"role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/Icon\/initWithDomElement:duration:error:","type":"topic","abstract":[],"url":"\/documentation\/gfpsdk\/icon\/initwithdomelement:duration:error:","title":"initWithDomElement:duration:error:","navigatorTitle":[{"text":"initWithDomElement:duration:error:","kind":"identifier"}],"fragments":[{"text":"- ","kind":"text"},{"text":"initWithDomElement:duration:error:","kind":"identifier"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/Icon/code":{"navigatorTitle":[{"kind":"identifier","text":"code"}],"role":"symbol","kind":"symbol","title":"code","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"code"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPResourceCode","text":"GFPResourceCode"}],"type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/Icon\/code","abstract":[],"url":"\/documentation\/gfpsdk\/icon\/code"},"doc://com.navercorp.da.gfp.GFPSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s28CustomDebugStringConvertibleP"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject"},"doc://com.navercorp.da.gfp.GFPSDK/SH":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)NSCopying":{"type":"unresolvable","title":"Foundation.NSCopying","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSCopying"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/Icon/value":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"value"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/Icon\/value","title":"value","url":"\/documentation\/gfpsdk\/icon\/value","abstract":[],"kind":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"value","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPTrackingPresentable":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPTrackingPresentable","abstract":[],"role":"symbol","title":"GFPTrackingPresentable","kind":"symbol","url":"\/documentation\/gfpsdk\/gfptrackingpresentable","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPTrackingPresentable"}],"navigatorTitle":[{"text":"GFPTrackingPresentable","kind":"identifier"}],"type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","title":"Swift.Equatable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/Icon/resource":{"navigatorTitle":[{"text":"resource","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/icon\/resource","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"resource"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)BaseStaticResource","kind":"typeIdentifier","text":"BaseStaticResource"}],"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/Icon\/resource","title":"resource"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/Icon/apiFramework":{"role":"symbol","abstract":[],"type":"topic","navigatorTitle":[{"text":"apiFramework","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/icon\/apiframework","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/Icon\/apiFramework","kind":"symbol","title":"apiFramework","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"apiFramework","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/Icon/iconWithDomElement:duration:error:":{"role":"symbol","abstract":[],"title":"iconWithDomElement:duration:error:","navigatorTitle":[{"kind":"identifier","text":"iconWithDomElement:duration:error:"}],"fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"iconWithDomElement:duration:error:"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/Icon\/iconWithDomElement:duration:error:","type":"topic","kind":"symbol","url":"\/documentation\/gfpsdk\/icon\/iconwithdomelement:duration:error:"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/Icon/xPosition":{"navigatorTitle":[{"text":"xPosition","kind":"identifier"}],"title":"xPosition","url":"\/documentation\/gfpsdk\/icon\/xposition","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/Icon\/xPosition","role":"symbol","type":"topic","kind":"symbol","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"xPosition"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s23CustomStringConvertibleP"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/Icon/hasDuration":{"role":"symbol","abstract":[],"title":"hasDuration","navigatorTitle":[{"text":"hasDuration","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hasDuration"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/Icon\/hasDuration","type":"topic","kind":"symbol","url":"\/documentation\/gfpsdk\/icon\/hasduration"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/Icon/offset":{"role":"symbol","navigatorTitle":[{"text":"offset","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/Icon\/offset","title":"offset","abstract":[],"url":"\/documentation\/gfpsdk\/icon\/offset","kind":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"offset"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s7CVarArgP"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"Icon","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"Icon","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"Icon"}],"op":"replace"},{"path":"\/topicSections","value":[{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/Icon\/apiFramework","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/Icon\/code","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/Icon\/duration","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/Icon\/hasDuration","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/Icon\/offset","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/Icon\/resource","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/Icon\/value","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/Icon\/xPosition","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/Icon\/yPosition"],"anchor":"Instance-Properties"},{"generated":true,"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/Icon\/initWithDomElement:duration:error:"],"title":"Instance Methods","anchor":"Instance-Methods"},{"anchor":"Type-Methods","generated":true,"title":"Type Methods","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/Icon\/iconWithDomElement:duration:error:"]}],"op":"replace"},{"value":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPTrackingPresentable"]}],"op":"replace","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Icon"},{"kind":"text","text":" : "},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPTrackingPresentable","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPTrackingPresentable","text":"GFPTrackingPresentable"}],"languages":["occ"]}]}},{"value":"yPosition","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1Icon~1yPosition\/title"},{"op":"replace","value":[{"text":"yPosition","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1Icon~1yPosition\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1Icon~1duration\/title","op":"replace","value":"duration"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1Icon~1duration\/fragments","op":"replace","value":[{"text":"duration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1Icon\/title","value":"Icon"},{"op":"replace","value":[{"text":"Icon","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1Icon\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1Icon\/navigatorTitle","value":[{"kind":"identifier","text":"Icon"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1Icon~1code\/title","value":"code","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1Icon~1code\/fragments","value":[{"text":"code","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1Icon~1value\/title","value":"value","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1Icon~1value\/fragments","value":[{"kind":"identifier","text":"value"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPTrackingPresentable\/title","value":"GFPTrackingPresentable","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPTrackingPresentable\/fragments","value":[{"kind":"identifier","text":"GFPTrackingPresentable"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPTrackingPresentable\/navigatorTitle","op":"replace","value":[{"text":"GFPTrackingPresentable","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1Icon~1resource\/title","op":"replace","value":"resource"},{"op":"replace","value":[{"text":"resource","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1Icon~1resource\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1Icon~1apiFramework\/title","value":"apiFramework"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1Icon~1apiFramework\/fragments","value":[{"text":"apiFramework","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1Icon~1xPosition\/title","value":"xPosition"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1Icon~1xPosition\/fragments","value":[{"text":"xPosition","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1Icon~1hasDuration\/title","value":"hasDuration"},{"op":"replace","value":[{"text":"hasDuration","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1Icon~1hasDuration\/fragments"},{"value":"offset","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1Icon~1offset\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1Icon~1offset\/fragments","value":[{"text":"offset","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}