{"metadata":{"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"kGFPDefaultUnifiedAdRequestTimeout","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"}],"symbolKind":"var","roleHeading":"Global Variable","navigatorTitle":[{"kind":"identifier","text":"kGFPDefaultUnifiedAdRequestTimeout"}],"modules":[{"name":"GFPSDK"}],"title":"kGFPDefaultUnifiedAdRequestTimeout","role":"symbol","externalID":"c:@kGFPDefaultUnifiedAdRequestTimeout"},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/kGFPDefaultUnifiedAdRequestTimeout","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"kGFPDefaultUnifiedAdRequestTimeout"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"TimeInterval"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/gfpsdk\/kgfpdefaultunifiedadrequesttimeout"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gfpsdk\/kgfpdefaultunifiedadrequesttimeout"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/kGFPDefaultUnifiedAdRequestTimeout":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/kGFPDefaultUnifiedAdRequestTimeout","type":"topic","abstract":[],"url":"\/documentation\/gfpsdk\/kgfpdefaultunifiedadrequesttimeout","navigatorTitle":[{"kind":"identifier","text":"kGFPDefaultUnifiedAdRequestTimeout"}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"kGFPDefaultUnifiedAdRequestTimeout"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"TimeInterval"}],"title":"kGFPDefaultUnifiedAdRequestTimeout","role":"symbol","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Global Variable","path":"\/metadata\/roleHeading"},{"value":"kGFPDefaultUnifiedAdRequestTimeout","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"var"},{"value":[{"kind":"identifier","text":"kGFPDefaultUnifiedAdRequestTimeout"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"extern","kind":"keyword"},{"kind":"text","text":" "},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","text":"NSTimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":" "},{"text":"kGFPDefaultUnifiedAdRequestTimeout","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"kGFPDefaultUnifiedAdRequestTimeout","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1kGFPDefaultUnifiedAdRequestTimeout\/title"},{"value":[{"text":"kGFPDefaultUnifiedAdRequestTimeout","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1kGFPDefaultUnifiedAdRequestTimeout\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}