{"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"},{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s7CVarArgP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s23CustomStringConvertibleP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"variants":[{"paths":["\/documentation\/gfpsdk\/kgfpvideoglobaloptions"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gfpsdk\/kgfpvideoglobaloptions"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objcMembers","kind":"attribute"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"kGFPVideoGlobalOptions","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/kGFPVideoGlobalOptions"},"metadata":{"role":"symbol","modules":[{"name":"GFPSDK"}],"roleHeading":"Class","externalID":"c:@M@GFPSDK@objc(cs)kGFPVideoGlobalOptions","title":"kGFPVideoGlobalOptions","navigatorTitle":[{"text":"kGFPVideoGlobalOptions","kind":"identifier"}],"symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kGFPVideoGlobalOptions","kind":"identifier"}]},"kind":"symbol","topicSections":[{"anchor":"Type-Properties","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/kGFPVideoGlobalOptions\/disableAutoPlay_changed","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/kGFPVideoGlobalOptions\/globalPlayPolicy_changed"],"generated":true,"title":"Type Properties"}],"sections":[],"references":{"doc://com.navercorp.da.gfp.GFPSDK/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/kGFPVideoGlobalOptions/disableAutoPlay_changed":{"abstract":[],"url":"\/documentation\/gfpsdk\/kgfpvideoglobaloptions\/disableautoplay_changed","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"disableAutoPlay_changed"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"disableAutoPlay_changed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"title":"disableAutoPlay_changed","kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/kGFPVideoGlobalOptions\/disableAutoPlay_changed","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/kGFPVideoGlobalOptions":{"navigatorTitle":[{"kind":"identifier","text":"kGFPVideoGlobalOptions"}],"title":"kGFPVideoGlobalOptions","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"kGFPVideoGlobalOptions"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/kGFPVideoGlobalOptions","url":"\/documentation\/gfpsdk\/kgfpvideoglobaloptions","abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/kGFPVideoGlobalOptions/globalPlayPolicy_changed":{"navigatorTitle":[{"kind":"identifier","text":"globalPlayPolicy_changed"}],"title":"globalPlayPolicy_changed","type":"topic","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"globalPlayPolicy_changed"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/kGFPVideoGlobalOptions\/globalPlayPolicy_changed","kind":"symbol","abstract":[],"url":"\/documentation\/gfpsdk\/kgfpvideoglobaloptions\/globalplaypolicy_changed"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/kGFPVideoGlobalOptions/init":{"navigatorTitle":[{"text":"init","kind":"identifier"}],"type":"topic","title":"init","kind":"symbol","url":"\/documentation\/gfpsdk\/kgfpvideoglobaloptions\/init","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/kGFPVideoGlobalOptions\/init","fragments":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}],"role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s7CVarArgP","type":"unresolvable"},"doc://com.navercorp.da.gfp.GFPSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s23CustomStringConvertibleP","type":"unresolvable"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"kGFPVideoGlobalOptions"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"kGFPVideoGlobalOptions"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"kGFPVideoGlobalOptions"}]},{"path":"\/topicSections","op":"replace","value":[{"generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/kGFPVideoGlobalOptions\/init"],"title":"Instance Methods"},{"title":"Type Properties","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/kGFPVideoGlobalOptions\/disableAutoPlay_changed","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/kGFPVideoGlobalOptions\/globalPlayPolicy_changed"],"generated":true,"anchor":"Type-Properties"}]},{"value":[{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kGFPVideoGlobalOptions","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":"disableAutoPlay_changed","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1kGFPVideoGlobalOptions~1disableAutoPlay_changed\/title","op":"replace"},{"value":[{"kind":"identifier","text":"disableAutoPlay_changed"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1kGFPVideoGlobalOptions~1disableAutoPlay_changed\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1kGFPVideoGlobalOptions\/title","op":"replace","value":"kGFPVideoGlobalOptions"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1kGFPVideoGlobalOptions\/fragments","value":[{"kind":"identifier","text":"kGFPVideoGlobalOptions"}],"op":"replace"},{"value":[{"kind":"identifier","text":"kGFPVideoGlobalOptions"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1kGFPVideoGlobalOptions\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1kGFPVideoGlobalOptions~1globalPlayPolicy_changed\/title","value":"globalPlayPolicy_changed","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"globalPlayPolicy_changed"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1kGFPVideoGlobalOptions~1globalPlayPolicy_changed\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}