{"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"kGFPDefaultBannerAdRequestTimeout","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"}],"title":"kGFPDefaultBannerAdRequestTimeout","navigatorTitle":[{"kind":"identifier","text":"kGFPDefaultBannerAdRequestTimeout"}],"externalID":"c:@kGFPDefaultBannerAdRequestTimeout","role":"symbol","modules":[{"name":"GFPSDK"}],"roleHeading":"Global Variable","symbolKind":"var"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kGFPDefaultBannerAdRequestTimeout","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"}]}]}],"kind":"symbol","variants":[{"paths":["\/documentation\/gfpsdk\/kgfpdefaultbanneradrequesttimeout"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/kgfpdefaultbanneradrequesttimeout"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/kGFPDefaultBannerAdRequestTimeout"},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/kGFPDefaultBannerAdRequestTimeout":{"navigatorTitle":[{"text":"kGFPDefaultBannerAdRequestTimeout","kind":"identifier"}],"title":"kGFPDefaultBannerAdRequestTimeout","abstract":[],"type":"topic","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/kGFPDefaultBannerAdRequestTimeout","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kGFPDefaultBannerAdRequestTimeout","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"}],"url":"\/documentation\/gfpsdk\/kgfpdefaultbanneradrequesttimeout","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Global Variable"},{"op":"replace","value":"kGFPDefaultBannerAdRequestTimeout","path":"\/metadata\/title"},{"value":"var","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"kGFPDefaultBannerAdRequestTimeout"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"text":"const","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"NSTimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":" ","kind":"text"},{"text":"kGFPDefaultBannerAdRequestTimeout","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"kGFPDefaultBannerAdRequestTimeout","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1kGFPDefaultBannerAdRequestTimeout\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1kGFPDefaultBannerAdRequestTimeout\/fragments","value":[{"kind":"identifier","text":"kGFPDefaultBannerAdRequestTimeout"}],"op":"replace"}]}]}