{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"kGFPVideoAdPlacementTypeUnknown","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}]}]}],"variants":[{"paths":["\/documentation\/gfpsdk\/kgfpvideoadplacementtypeunknown"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gfpsdk\/kgfpvideoadplacementtypeunknown"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"role":"symbol","title":"kGFPVideoAdPlacementTypeUnknown","roleHeading":"Global Variable","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"kGFPVideoAdPlacementTypeUnknown","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"externalID":"c:@kGFPVideoAdPlacementTypeUnknown","symbolKind":"var","navigatorTitle":[{"kind":"identifier","text":"kGFPVideoAdPlacementTypeUnknown"}],"modules":[{"name":"GFPSDK"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/kGFPVideoAdPlacementTypeUnknown"},"sections":[],"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/kGFPVideoAdPlacementTypeUnknown":{"abstract":[],"url":"\/documentation\/gfpsdk\/kgfpvideoadplacementtypeunknown","role":"symbol","title":"kGFPVideoAdPlacementTypeUnknown","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/kGFPVideoAdPlacementTypeUnknown","type":"topic","navigatorTitle":[{"text":"kGFPVideoAdPlacementTypeUnknown","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"kGFPVideoAdPlacementTypeUnknown","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Global Variable"},{"op":"replace","value":"kGFPVideoAdPlacementTypeUnknown","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"var","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"kGFPVideoAdPlacementTypeUnknown","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"kGFPVideoAdPlacementTypeUnknown"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1kGFPVideoAdPlacementTypeUnknown\/title","value":"kGFPVideoAdPlacementTypeUnknown","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1kGFPVideoAdPlacementTypeUnknown\/fragments","op":"replace","value":[{"text":"kGFPVideoAdPlacementTypeUnknown","kind":"identifier"}]}]}]}