{"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/kgfpdefaultrewardedadrequesttimeout"]},{"paths":["\/documentation\/gfpsdk\/kgfpdefaultrewardedadrequesttimeout"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"kGFPDefaultRewardedAdRequestTimeout"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/kGFPDefaultRewardedAdRequestTimeout"},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"kGFPDefaultRewardedAdRequestTimeout"}],"externalID":"c:@kGFPDefaultRewardedAdRequestTimeout","symbolKind":"var","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"kGFPDefaultRewardedAdRequestTimeout"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"}],"modules":[{"name":"GFPSDK"}],"roleHeading":"Global Variable","role":"symbol","title":"kGFPDefaultRewardedAdRequestTimeout"},"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/kGFPDefaultRewardedAdRequestTimeout":{"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"kGFPDefaultRewardedAdRequestTimeout"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"}],"url":"\/documentation\/gfpsdk\/kgfpdefaultrewardedadrequesttimeout","navigatorTitle":[{"text":"kGFPDefaultRewardedAdRequestTimeout","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/kGFPDefaultRewardedAdRequestTimeout","kind":"symbol","type":"topic","title":"kGFPDefaultRewardedAdRequestTimeout","role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Global Variable"},{"path":"\/metadata\/title","value":"kGFPDefaultRewardedAdRequestTimeout","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"var"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"kGFPDefaultRewardedAdRequestTimeout"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","text":"NSTimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":" "},{"text":"kGFPDefaultRewardedAdRequestTimeout","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1kGFPDefaultRewardedAdRequestTimeout\/title","op":"replace","value":"kGFPDefaultRewardedAdRequestTimeout"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1kGFPDefaultRewardedAdRequestTimeout\/fragments","value":[{"kind":"identifier","text":"kGFPDefaultRewardedAdRequestTimeout"}],"op":"replace"}]}]}