{"metadata":{"externalID":"c:@kGFPDefaultInterstitialAdRequestTimeout","roleHeading":"Global Variable","symbolKind":"var","role":"symbol","title":"kGFPDefaultInterstitialAdRequestTimeout","modules":[{"name":"GFPSDK"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"kGFPDefaultInterstitialAdRequestTimeout"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"}],"navigatorTitle":[{"text":"kGFPDefaultInterstitialAdRequestTimeout","kind":"identifier"}]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"kGFPDefaultInterstitialAdRequestTimeout"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"TimeInterval"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/kgfpdefaultinterstitialadrequesttimeout"]},{"paths":["\/documentation\/gfpsdk\/kgfpdefaultinterstitialadrequesttimeout"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/kGFPDefaultInterstitialAdRequestTimeout"},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/kGFPDefaultInterstitialAdRequestTimeout":{"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"kGFPDefaultInterstitialAdRequestTimeout"},{"kind":"text","text":": "},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"}],"kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/kGFPDefaultInterstitialAdRequestTimeout","title":"kGFPDefaultInterstitialAdRequestTimeout","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"kGFPDefaultInterstitialAdRequestTimeout"}],"type":"topic","role":"symbol","url":"\/documentation\/gfpsdk\/kgfpdefaultinterstitialadrequesttimeout"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Global Variable","op":"replace"},{"path":"\/metadata\/title","value":"kGFPDefaultInterstitialAdRequestTimeout","op":"replace"},{"path":"\/metadata\/symbolKind","value":"var","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"kGFPDefaultInterstitialAdRequestTimeout"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"extern","kind":"keyword"},{"kind":"text","text":" "},{"text":"const","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"NSTimeInterval"},{"text":" ","kind":"text"},{"kind":"identifier","text":"kGFPDefaultInterstitialAdRequestTimeout"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1kGFPDefaultInterstitialAdRequestTimeout\/title","value":"kGFPDefaultInterstitialAdRequestTimeout"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1kGFPDefaultInterstitialAdRequestTimeout\/fragments","value":[{"kind":"identifier","text":"kGFPDefaultInterstitialAdRequestTimeout"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}