{"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/kgfpvideoadplacementtypepreroll"]},{"paths":["\/documentation\/gfpsdk\/kgfpvideoadplacementtypepreroll"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"kGFPVideoAdPlacementTypePreRoll","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"kGFPVideoAdPlacementTypePreRoll","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"roleHeading":"Global Variable","role":"symbol","externalID":"c:@kGFPVideoAdPlacementTypePreRoll","symbolKind":"var","navigatorTitle":[{"text":"kGFPVideoAdPlacementTypePreRoll","kind":"identifier"}],"modules":[{"name":"GFPSDK"}]},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/kGFPVideoAdPlacementTypePreRoll","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kGFPVideoAdPlacementTypePreRoll","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/kGFPVideoAdPlacementTypePreRoll":{"abstract":[],"type":"topic","title":"kGFPVideoAdPlacementTypePreRoll","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kGFPVideoAdPlacementTypePreRoll","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"url":"\/documentation\/gfpsdk\/kgfpvideoadplacementtypepreroll","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/kGFPVideoAdPlacementTypePreRoll","navigatorTitle":[{"kind":"identifier","text":"kGFPVideoAdPlacementTypePreRoll"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Global Variable","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"kGFPVideoAdPlacementTypePreRoll","op":"replace"},{"value":"var","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"kGFPVideoAdPlacementTypePreRoll","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"extern","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"kGFPVideoAdPlacementTypePreRoll"},{"text":";","kind":"text"}]}]}},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1kGFPVideoAdPlacementTypePreRoll\/title","value":"kGFPVideoAdPlacementTypePreRoll","op":"replace"},{"value":[{"kind":"identifier","text":"kGFPVideoAdPlacementTypePreRoll"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1kGFPVideoAdPlacementTypePreRoll\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}