{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/kGFPAAPParamKeyKeyChartBoost"},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"kGFPAAPParamKeyKeyChartBoost"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/kgfpaapparamkeykeychartboost"]},{"paths":["\/documentation\/gfpsdk\/kgfpaapparamkeykeychartboost"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Global Variable","modules":[{"name":"GFPSDK"}],"role":"symbol","title":"kGFPAAPParamKeyKeyChartBoost","navigatorTitle":[{"kind":"identifier","text":"kGFPAAPParamKeyKeyChartBoost"}],"symbolKind":"var","externalID":"c:GFPAPIQueryItems.h@kGFPAAPParamKeyKeyChartBoost","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kGFPAAPParamKeyKeyChartBoost","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}]},"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/kGFPAAPParamKeyKeyChartBoost":{"title":"kGFPAAPParamKeyKeyChartBoost","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"kGFPAAPParamKeyKeyChartBoost","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"type":"topic","abstract":[],"role":"symbol","navigatorTitle":[{"text":"kGFPAAPParamKeyKeyChartBoost","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/kgfpaapparamkeykeychartboost","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/kGFPAAPParamKeyKeyChartBoost"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Global Variable","op":"replace"},{"value":"kGFPAAPParamKeyKeyChartBoost","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"var"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"kGFPAAPParamKeyKeyChartBoost"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" * ","kind":"text"},{"text":"kGFPAAPParamKeyKeyChartBoost","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"op":"replace","value":"kGFPAAPParamKeyKeyChartBoost","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1kGFPAAPParamKeyKeyChartBoost\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1kGFPAAPParamKeyKeyChartBoost\/fragments","value":[{"kind":"identifier","text":"kGFPAAPParamKeyKeyChartBoost"}]}]}]}