{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/nonlinearviewdelegate"]},{"paths":["\/documentation\/gfpsdk\/nonlinearviewdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NonLinearViewDelegate","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/NonLinearViewDelegate"},"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"externalID":"c:objc(pl)NonLinearViewDelegate","navigatorTitle":[{"text":"NonLinearViewDelegate","kind":"identifier"}],"roleHeading":"Protocol","symbolKind":"protocol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"NonLinearViewDelegate"}],"modules":[{"name":"GFPSDK"}],"role":"symbol","title":"NonLinearViewDelegate"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/NonLinearViewDelegate\/nonLinearView(_:didClose:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/NonLinearViewDelegate\/nonLinearView(inAppBrowserDissmissed:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/NonLinearViewDelegate\/nonLinearView(inAppBrowserPresented:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/NonLinearViewDelegate\/nonLinearView(onActiveImpression:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/NonLinearViewDelegate\/nonLinearViewWasClicked(_:)"],"generated":true,"anchor":"Instance-Methods"}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject"]}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/NonLinearViewDelegate/nonLinearView(onActiveImpression:)":{"type":"topic","navigatorTitle":[{"text":"nonLinearViewOnActiveImpression:","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/nonlinearviewdelegate\/nonlinearview(onactiveimpression:)","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/NonLinearViewDelegate\/nonLinearView(onActiveImpression:)","title":"nonLinearView(onActiveImpression:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"nonLinearView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"onActiveImpression"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"GFPNonLinearAdView","preciseIdentifier":"c:objc(cs)GFPNonLinearAdView"},{"text":")","kind":"text"}],"kind":"symbol","abstract":[],"required":true},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/NonLinearViewDelegate/nonLinearView(inAppBrowserDissmissed:)":{"navigatorTitle":[{"text":"nonLinearViewInAppBrowserDissmissed:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"nonLinearView"},{"kind":"text","text":"("},{"text":"inAppBrowserDissmissed","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GFPNonLinearAdView","preciseIdentifier":"c:objc(cs)GFPNonLinearAdView"},{"text":")","kind":"text"}],"abstract":[],"type":"topic","role":"symbol","title":"nonLinearView(inAppBrowserDissmissed:)","kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/NonLinearViewDelegate\/nonLinearView(inAppBrowserDissmissed:)","url":"\/documentation\/gfpsdk\/nonlinearviewdelegate\/nonlinearview(inappbrowserdissmissed:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/NonLinearViewDelegate":{"url":"\/documentation\/gfpsdk\/nonlinearviewdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NonLinearViewDelegate","kind":"identifier"}],"role":"symbol","abstract":[],"title":"NonLinearViewDelegate","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/NonLinearViewDelegate","navigatorTitle":[{"kind":"identifier","text":"NonLinearViewDelegate"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/NonLinearViewDelegate/nonLinearViewWasClicked(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"nonLinearViewWasClicked"},{"text":"(","kind":"text"},{"text":"GFPNonLinearAdView","preciseIdentifier":"c:objc(cs)GFPNonLinearAdView","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"nonLinearViewWasClicked:"}],"abstract":[],"url":"\/documentation\/gfpsdk\/nonlinearviewdelegate\/nonlinearviewwasclicked(_:)","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/NonLinearViewDelegate\/nonLinearViewWasClicked(_:)","required":true,"title":"nonLinearViewWasClicked(_:)"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/NonLinearViewDelegate/nonLinearView(_:didClose:)":{"required":true,"navigatorTitle":[{"kind":"identifier","text":"nonLinearView:didClose:"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"nonLinearView"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPNonLinearAdView","text":"GFPNonLinearAdView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didClose"},{"text":": ","kind":"text"},{"text":"UIButton","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIButton"},{"text":")","kind":"text"}],"abstract":[],"type":"topic","role":"symbol","title":"nonLinearView(_:didClose:)","kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/NonLinearViewDelegate\/nonLinearView(_:didClose:)","url":"\/documentation\/gfpsdk\/nonlinearviewdelegate\/nonlinearview(_:didclose:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/NonLinearViewDelegate/nonLinearView(inAppBrowserPresented:)":{"required":true,"navigatorTitle":[{"kind":"identifier","text":"nonLinearViewInAppBrowserPresented:"}],"title":"nonLinearView(inAppBrowserPresented:)","abstract":[],"type":"topic","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/NonLinearViewDelegate\/nonLinearView(inAppBrowserPresented:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"nonLinearView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"inAppBrowserPresented","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)GFPNonLinearAdView","text":"GFPNonLinearAdView","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/gfpsdk\/nonlinearviewdelegate\/nonlinearview(inappbrowserpresented:)","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Protocol"},{"value":"NonLinearViewDelegate","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"path":"\/metadata\/fragments","value":[{"text":"NonLinearViewDelegate","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"text":"NonLinearViewDelegate","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"value":[{"generated":true,"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/NonLinearViewDelegate\/nonLinearView(_:didClose:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/NonLinearViewDelegate\/nonLinearView(inAppBrowserDissmissed:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/NonLinearViewDelegate\/nonLinearView(inAppBrowserPresented:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/NonLinearViewDelegate\/nonLinearView(onActiveImpression:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/NonLinearViewDelegate\/nonLinearViewWasClicked(_:)"]}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","value":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject"]}],"op":"replace"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"NonLinearViewDelegate"},{"kind":"text","text":" <"},{"preciseIdentifier":"c:objc(pl)NSObject","text":"NSObject","kind":"typeIdentifier"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1NonLinearViewDelegate~1nonLinearView(onActiveImpression:)\/title","value":"nonLinearViewOnActiveImpression:"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1NonLinearViewDelegate~1nonLinearView(onActiveImpression:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"nonLinearViewOnActiveImpression:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1NonLinearViewDelegate~1nonLinearView(inAppBrowserDissmissed:)\/title","op":"replace","value":"nonLinearViewInAppBrowserDissmissed:"},{"value":[{"text":"- ","kind":"text"},{"text":"nonLinearViewInAppBrowserDissmissed:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1NonLinearViewDelegate~1nonLinearView(inAppBrowserDissmissed:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1NonLinearViewDelegate\/title","value":"NonLinearViewDelegate"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1NonLinearViewDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"NonLinearViewDelegate"}]},{"op":"replace","value":[{"kind":"identifier","text":"NonLinearViewDelegate"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1NonLinearViewDelegate\/navigatorTitle"},{"value":"nonLinearViewWasClicked:","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1NonLinearViewDelegate~1nonLinearViewWasClicked(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1NonLinearViewDelegate~1nonLinearViewWasClicked(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"nonLinearViewWasClicked:"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1NonLinearViewDelegate~1nonLinearView(_:didClose:)\/title","value":"nonLinearView:didClose:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"nonLinearView:didClose:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1NonLinearViewDelegate~1nonLinearView(_:didClose:)\/fragments","op":"replace"},{"value":"nonLinearViewInAppBrowserPresented:","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1NonLinearViewDelegate~1nonLinearView(inAppBrowserPresented:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1NonLinearViewDelegate~1nonLinearView(inAppBrowserPresented:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"nonLinearViewInAppBrowserPresented:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}