{"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NonLinear"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/nonlinear"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/nonlinear"]}],"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/NonLinear","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/NonLinear\/apiFramework","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/NonLinear\/clickThrough","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/NonLinear\/clickTracking","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/NonLinear\/nonLinearID","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/NonLinear\/resource","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/NonLinear\/size"],"generated":true}],"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject"],"kind":"relationships"},{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s7CVarArgP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/s23CustomStringConvertibleP","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH"],"type":"conformsTo"}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"NonLinear"}],"externalID":"c:objc(cs)NonLinear","symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"NonLinear"}],"role":"symbol","roleHeading":"Class","modules":[{"name":"GFPSDK"}],"title":"NonLinear"},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/NonLinear":{"abstract":[],"url":"\/documentation\/gfpsdk\/nonlinear","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/NonLinear","role":"symbol","title":"NonLinear","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NonLinear"}],"navigatorTitle":[{"text":"NonLinear","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/NonLinear/resource":{"role":"symbol","abstract":[],"title":"resource","navigatorTitle":[{"text":"resource","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"resource"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)StaticResource","text":"StaticResource"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/NonLinear\/resource","url":"\/documentation\/gfpsdk\/nonlinear\/resource","kind":"symbol","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/NonLinear/nonLinearID":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nonLinearID","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"navigatorTitle":[{"text":"nonLinearID","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/NonLinear\/nonLinearID","role":"symbol","abstract":[],"url":"\/documentation\/gfpsdk\/nonlinear\/nonlinearid","title":"nonLinearID"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/NonLinear/clickTracking":{"abstract":[],"url":"\/documentation\/gfpsdk\/nonlinear\/clicktracking","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/NonLinear\/clickTracking","role":"symbol","title":"clickTracking","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"clickTracking","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"clickTracking"}],"kind":"symbol","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/NonLinear/clickThrough":{"url":"\/documentation\/gfpsdk\/nonlinear\/clickthrough","abstract":[],"title":"clickThrough","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/NonLinear\/clickThrough","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"clickThrough","kind":"identifier"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"clickThrough"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/NonLinear/size":{"role":"symbol","abstract":[],"title":"size","navigatorTitle":[{"text":"size","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"size"},{"kind":"text","text":": "},{"text":"CGSize","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/NonLinear\/size","url":"\/documentation\/gfpsdk\/nonlinear\/size","kind":"symbol","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject","title":"NSObject"},"doc://com.navercorp.da.gfp.GFPSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.navercorp.da.gfp.GFPSDK/objc(pl)NSObject":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.navercorp.da.gfp.GFPSDK/SH":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.navercorp.da.gfp.GFPSDK/s7CVarArgP":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/NonLinear/apiFramework":{"role":"symbol","abstract":[],"title":"apiFramework","navigatorTitle":[{"text":"apiFramework","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"apiFramework"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/NonLinear\/apiFramework","url":"\/documentation\/gfpsdk\/nonlinear\/apiframework","kind":"symbol","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/NonLinear/initWithDomElement:error:":{"navigatorTitle":[{"kind":"identifier","text":"initWithDomElement:error:"}],"url":"\/documentation\/gfpsdk\/nonlinear\/initwithdomelement:error:","abstract":[],"fragments":[{"kind":"text","text":"- "},{"text":"initWithDomElement:error:","kind":"identifier"}],"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/NonLinear\/initWithDomElement:error:","title":"initWithDomElement:error:"},"doc://com.navercorp.da.gfp.GFPSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/SQ","title":"Swift.Equatable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","value":"NonLinear","op":"replace"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"NonLinear","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"NonLinear"}],"op":"replace"},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/NonLinear\/apiFramework","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/NonLinear\/clickThrough","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/NonLinear\/clickTracking","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/NonLinear\/nonLinearID","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/NonLinear\/resource","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/NonLinear\/size"],"generated":true,"anchor":"Instance-Properties"},{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/NonLinear\/initWithDomElement:error:"],"anchor":"Instance-Methods"}]},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"}],"op":"replace"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"NonLinear"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1NonLinear\/title","op":"replace","value":"NonLinear"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1NonLinear\/fragments","op":"replace","value":[{"text":"NonLinear","kind":"identifier"}]},{"value":[{"text":"NonLinear","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1NonLinear\/navigatorTitle"},{"value":"resource","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1NonLinear~1resource\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1NonLinear~1resource\/fragments","value":[{"kind":"identifier","text":"resource"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1NonLinear~1nonLinearID\/title","value":"nonLinearID","op":"replace"},{"value":[{"text":"nonLinearID","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1NonLinear~1nonLinearID\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1NonLinear~1clickTracking\/title","value":"clickTracking","op":"replace"},{"op":"replace","value":[{"text":"clickTracking","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1NonLinear~1clickTracking\/fragments"},{"value":"clickThrough","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1NonLinear~1clickThrough\/title"},{"value":[{"text":"clickThrough","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1NonLinear~1clickThrough\/fragments","op":"replace"},{"op":"replace","value":"size","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1NonLinear~1size\/title"},{"op":"replace","value":[{"text":"size","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1NonLinear~1size\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1NonLinear~1apiFramework\/title","value":"apiFramework"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1NonLinear~1apiFramework\/fragments","value":[{"text":"apiFramework","kind":"identifier"}]}]}]}