{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpservererrorresponse\/init(withdictionary:)"]},{"paths":["\/documentation\/gfpsdk\/gfpservererrorresponse\/init(withdictionary:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPServerErrorResponse"]]},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"?("},{"text":"withDictionary","kind":"externalParam"},{"kind":"text","text":" "},{"text":"dict","kind":"internalParam"},{"text":": [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"])"}],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPServerErrorResponse\/init(withDictionary:)"},"kind":"symbol","metadata":{"title":"init(withDictionary:)","symbolKind":"init","role":"symbol","externalID":"c:@M@GFPSDK@objc(cs)GFPServerErrorResponse(im)initWithDictionary:","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"withDictionary"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"])"}],"modules":[{"name":"GFPSDK"}],"navigatorTitle":[{"kind":"identifier","text":"initWithDictionary:"}],"roleHeading":"Initializer"},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPServerErrorResponse":{"url":"\/documentation\/gfpsdk\/gfpservererrorresponse","title":"GFPServerErrorResponse","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPServerErrorResponse","kind":"symbol","role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPServerErrorResponse","kind":"identifier"}],"navigatorTitle":[{"text":"GFPServerErrorResponse","kind":"identifier"}],"abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPServerErrorResponse/init(withDictionary:)":{"type":"topic","title":"init(withDictionary:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"withDictionary"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"])","kind":"text"}],"abstract":[],"url":"\/documentation\/gfpsdk\/gfpservererrorresponse\/init(withdictionary:)","kind":"symbol","navigatorTitle":[{"text":"initWithDictionary:","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPServerErrorResponse\/init(withDictionary:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"initWithDictionary:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDictionary:"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithDictionary:"},{"text":"(","kind":"text"},{"text":"NSDictionary<NSString *,id>","preciseIdentifier":"c:Q$objc(cs)NSDictionary","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"dict","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"value":"GFPServerErrorResponse","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPServerErrorResponse\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPServerErrorResponse\/fragments","value":[{"kind":"identifier","text":"GFPServerErrorResponse"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPServerErrorResponse\/navigatorTitle","value":[{"kind":"identifier","text":"GFPServerErrorResponse"}]},{"value":"initWithDictionary:","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPServerErrorResponse~1init(withDictionary:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithDictionary:"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPServerErrorResponse~1init(withDictionary:)\/fragments"}]}]}