{"primaryContentSections":[{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithElement:"},{"kind":"text","text":"("},{"text":"DDXMLElement","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)DDXMLElement"},{"kind":"text","text":" *) "},{"text":"aElement","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"error:"},{"text":"(","kind":"text"},{"text":"GFPError","kind":"typeIdentifier","preciseIdentifier":"c:@M@NaverAdsServices@objc(cs)GFPError"},{"text":" * *) ","kind":"text"},{"kind":"internalParam","text":"aError"},{"text":";","kind":"text"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/gfpsdk\/htmlresource\/initwithelement:error:"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"role":"symbol","modules":[{"name":"GFPSDK"}],"externalID":"c:objc(cs)HTMLResource(im)initWithElement:error:","symbolKind":"method","title":"initWithElement:error:","navigatorTitle":[{"kind":"identifier","text":"initWithElement:error:"}],"fragments":[{"text":"- ","kind":"text"},{"text":"initWithElement:error:","kind":"identifier"}],"roleHeading":"Instance Method"},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/HTMLResource\/initWithElement:error:"},"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/HTMLResource"]]},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/HTMLResource/initWithElement:error:":{"abstract":[],"role":"symbol","url":"\/documentation\/gfpsdk\/htmlresource\/initwithelement:error:","fragments":[{"kind":"text","text":"- "},{"text":"initWithElement:error:","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"initWithElement:error:"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/HTMLResource\/initWithElement:error:","title":"initWithElement:error:","kind":"symbol","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/HTMLResource":{"title":"HTMLResource","url":"\/documentation\/gfpsdk\/htmlresource","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/HTMLResource","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HTMLResource","kind":"identifier"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"HTMLResource","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1HTMLResource\/title","op":"replace","value":"HTMLResource"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1HTMLResource\/fragments","value":[{"text":"HTMLResource","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"HTMLResource"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1HTMLResource\/navigatorTitle"}]}]}