{"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpvideoeventdelegate\/adplayerdidpause(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gfpsdk\/gfpvideoeventdelegate\/adplayerdidpause(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"modules":[{"name":"GFPSDK"}],"externalID":"c:objc(pl)GFPVideoEventDelegate(im)adPlayerDidPause:","roleHeading":"Instance Method","title":"adPlayerDidPause(_:)","role":"symbol","required":true,"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"adPlayerDidPause"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoController","text":"GFPVideoController"},{"kind":"text","text":"!)"}],"navigatorTitle":[{"kind":"identifier","text":"adPlayerDidPause:"}]},"kind":"symbol","abstract":[{"text":"네이티브 광고 영상 정지 시 호출됩니다.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoEventDelegate"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"adPlayerDidPause","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"videoController","kind":"internalParam"},{"kind":"text","text":": "},{"text":"GFPVideoController","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoController"},{"text":"!)","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"네이티브 비디오 컨트롤 객체"}]}],"name":"videoController"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoEventDelegate\/adPlayerDidPause(_:)"},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoEventDelegate/adPlayerDidPause(_:)":{"type":"topic","title":"adPlayerDidPause(_:)","abstract":[{"type":"text","text":"네이티브 광고 영상 정지 시 호출됩니다."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"adPlayerDidPause","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoController","text":"GFPVideoController"},{"text":"!)","kind":"text"}],"url":"\/documentation\/gfpsdk\/gfpvideoeventdelegate\/adplayerdidpause(_:)","role":"symbol","required":true,"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoEventDelegate\/adPlayerDidPause(_:)","navigatorTitle":[{"text":"adPlayerDidPause:","kind":"identifier"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoEventDelegate":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPVideoEventDelegate"}],"navigatorTitle":[{"kind":"identifier","text":"GFPVideoEventDelegate"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoEventDelegate","url":"\/documentation\/gfpsdk\/gfpvideoeventdelegate","kind":"symbol","role":"symbol","abstract":[],"title":"GFPVideoEventDelegate","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoController":{"url":"\/documentation\/gfpsdk\/gfpvideocontroller","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPVideoController"}],"role":"symbol","abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"GFPVideoController"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoController","title":"GFPVideoController","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"adPlayerDidPause:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"adPlayerDidPause:"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"adPlayerDidPause:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoController","text":"GFPVideoController"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"videoController"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"네이티브 비디오 컨트롤 객체","type":"text"}]}],"name":"videoController"}],"kind":"parameters"}},{"value":"adPlayerDidPause:","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoEventDelegate~1adPlayerDidPause(_:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoEventDelegate~1adPlayerDidPause(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"adPlayerDidPause:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoEventDelegate\/title","value":"GFPVideoEventDelegate"},{"op":"replace","value":[{"text":"GFPVideoEventDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoEventDelegate\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoEventDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"GFPVideoEventDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoController\/title","value":"GFPVideoController","op":"replace"},{"value":[{"kind":"identifier","text":"GFPVideoController"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoController\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoController\/navigatorTitle","value":[{"kind":"identifier","text":"GFPVideoController"}],"op":"replace"}]}]}