{"variants":[{"paths":["\/documentation\/gfpsdk\/gfpvideoeventdelegate\/adplayerdidchangemutestate(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gfpsdk\/gfpvideoeventdelegate\/adplayerdidchangemutestate(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"네이티브 광고 영상 플레이어에 mute  상태가 변경 될 때 호출됩니다."}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"metadata":{"role":"symbol","externalID":"c:objc(pl)GFPVideoEventDelegate(im)adPlayerDidChangeMuteState:","roleHeading":"Instance Method","symbolKind":"method","modules":[{"name":"GFPSDK"}],"navigatorTitle":[{"kind":"identifier","text":"adPlayerDidChangeMuteState:"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"adPlayerDidChangeMuteState","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoController","text":"GFPVideoController"},{"kind":"text","text":"!)"}],"title":"adPlayerDidChangeMuteState(_:)","required":true},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoEventDelegate"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"adPlayerDidChangeMuteState"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"videoController","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)GFPVideoController","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoController","text":"GFPVideoController","kind":"typeIdentifier"},{"kind":"text","text":"!)"}],"platforms":["iOS"]}]},{"parameters":[{"name":"videoController","content":[{"inlineContent":[{"type":"text","text":"네이티브 비디오 컨트롤 객체"}],"type":"paragraph"}]}],"kind":"parameters"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoEventDelegate\/adPlayerDidChangeMuteState(_:)"},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoEventDelegate/adPlayerDidChangeMuteState(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"adPlayerDidChangeMuteState"},{"kind":"text","text":"("},{"text":"GFPVideoController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoController"},{"kind":"text","text":"!)"}],"url":"\/documentation\/gfpsdk\/gfpvideoeventdelegate\/adplayerdidchangemutestate(_:)","title":"adPlayerDidChangeMuteState(_:)","abstract":[{"type":"text","text":"네이티브 광고 영상 플레이어에 mute  상태가 변경 될 때 호출됩니다."}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoEventDelegate\/adPlayerDidChangeMuteState(_:)","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"adPlayerDidChangeMuteState:","kind":"identifier"}],"type":"topic","required":true},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoEventDelegate":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPVideoEventDelegate"}],"navigatorTitle":[{"kind":"identifier","text":"GFPVideoEventDelegate"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoEventDelegate","url":"\/documentation\/gfpsdk\/gfpvideoeventdelegate","kind":"symbol","role":"symbol","abstract":[],"title":"GFPVideoEventDelegate","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoController":{"url":"\/documentation\/gfpsdk\/gfpvideocontroller","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPVideoController"}],"role":"symbol","abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"GFPVideoController"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoController","title":"GFPVideoController","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"adPlayerDidChangeMuteState:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"adPlayerDidChangeMuteState:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"adPlayerDidChangeMuteState:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoController","text":"GFPVideoController","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoController"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"videoController"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"videoController","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"네이티브 비디오 컨트롤 객체"}]}]}]}},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoEventDelegate~1adPlayerDidChangeMuteState(_:)\/title","op":"replace","value":"adPlayerDidChangeMuteState:"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoEventDelegate~1adPlayerDidChangeMuteState(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"adPlayerDidChangeMuteState:","kind":"identifier"}]},{"value":"GFPVideoEventDelegate","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoEventDelegate\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoEventDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"GFPVideoEventDelegate"}]},{"value":[{"text":"GFPVideoEventDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoEventDelegate\/navigatorTitle"},{"value":"GFPVideoController","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoController\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoController\/fragments","op":"replace","value":[{"text":"GFPVideoController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoController\/navigatorTitle","value":[{"text":"GFPVideoController","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}