{"variants":[{"paths":["\/documentation\/gfpsdk\/gfpvideoeventdelegate\/adplayerdidcomplete(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gfpsdk\/gfpvideoeventdelegate\/adplayerdidcomplete(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Instance Method","required":true,"modules":[{"name":"GFPSDK"}],"symbolKind":"method","navigatorTitle":[{"text":"adPlayerDidComplete:","kind":"identifier"}],"role":"symbol","title":"adPlayerDidComplete(_:)","externalID":"c:objc(pl)GFPVideoEventDelegate(im)adPlayerDidComplete:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"adPlayerDidComplete"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)GFPVideoController","text":"GFPVideoController","kind":"typeIdentifier"},{"text":"!)","kind":"text"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"네이티브 광고 영상 재생 완료 시 호출됩니다.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoEventDelegate"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"adPlayerDidComplete","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"videoController","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"GFPVideoController","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoController","preciseIdentifier":"c:objc(cs)GFPVideoController"},{"text":"!)","kind":"text"}],"platforms":["iOS"]}]},{"parameters":[{"name":"videoController","content":[{"inlineContent":[{"text":"네이티브 비디오 컨트롤 객체","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoEventDelegate\/adPlayerDidComplete(_:)"},"sections":[],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoController":{"url":"\/documentation\/gfpsdk\/gfpvideocontroller","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPVideoController"}],"role":"symbol","abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"GFPVideoController"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoController","title":"GFPVideoController","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoEventDelegate":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPVideoEventDelegate"}],"navigatorTitle":[{"kind":"identifier","text":"GFPVideoEventDelegate"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoEventDelegate","url":"\/documentation\/gfpsdk\/gfpvideoeventdelegate","kind":"symbol","role":"symbol","abstract":[],"title":"GFPVideoEventDelegate","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoEventDelegate/adPlayerDidComplete(_:)":{"required":true,"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoEventDelegate\/adPlayerDidComplete(_:)","navigatorTitle":[{"text":"adPlayerDidComplete:","kind":"identifier"}],"abstract":[{"text":"네이티브 광고 영상 재생 완료 시 호출됩니다.","type":"text"}],"title":"adPlayerDidComplete(_:)","role":"symbol","kind":"symbol","url":"\/documentation\/gfpsdk\/gfpvideoeventdelegate\/adplayerdidcomplete(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"adPlayerDidComplete","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GFPVideoController","preciseIdentifier":"c:objc(cs)GFPVideoController"},{"kind":"text","text":"!)"}],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","value":"adPlayerDidComplete:","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"adPlayerDidComplete:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"adPlayerDidComplete:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"GFPVideoController","preciseIdentifier":"c:objc(cs)GFPVideoController","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoController"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"videoController"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"videoController","content":[{"inlineContent":[{"text":"네이티브 비디오 컨트롤 객체","type":"text"}],"type":"paragraph"}]}]}},{"op":"replace","value":"GFPVideoController","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoController\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoController\/fragments","value":[{"kind":"identifier","text":"GFPVideoController"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoController\/navigatorTitle","value":[{"kind":"identifier","text":"GFPVideoController"}]},{"value":"GFPVideoEventDelegate","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoEventDelegate\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoEventDelegate\/fragments","value":[{"text":"GFPVideoEventDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoEventDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"GFPVideoEventDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoEventDelegate~1adPlayerDidComplete(_:)\/title","value":"adPlayerDidComplete:"},{"value":[{"kind":"text","text":"- "},{"text":"adPlayerDidComplete:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoEventDelegate~1adPlayerDidComplete(_:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}