{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpvideoeventdelegate\/adplayer(_:didchangebufferedtime:)"]},{"paths":["\/documentation\/gfpsdk\/gfpvideoeventdelegate\/adplayer(_:didchangebufferedtime:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoEventDelegate"]]},"abstract":[{"type":"text","text":"네이티브 광고 영상의 버퍼 진행률 변경 시 호출됩니다."}],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"adPlayer"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)GFPVideoController","text":"GFPVideoController","kind":"typeIdentifier"},{"kind":"text","text":"!, "},{"text":"didChangeBufferedTime","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":")"}],"roleHeading":"Instance Method","modules":[{"name":"GFPSDK"}],"required":true,"role":"symbol","symbolKind":"method","title":"adPlayer(_:didChangeBufferedTime:)","externalID":"c:objc(pl)GFPVideoEventDelegate(im)adPlayer:didChangeBufferedTime:","navigatorTitle":[{"text":"adPlayer:didChangeBufferedTime:","kind":"identifier"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoEventDelegate\/adPlayer(_:didChangeBufferedTime:)"},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"adPlayer","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"videoController","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"GFPVideoController","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoController","preciseIdentifier":"c:objc(cs)GFPVideoController","kind":"typeIdentifier"},{"kind":"text","text":"!, "},{"text":"didChangeBufferedTime","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"bufferedTime"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":")"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"네이티브 비디오 컨트롤 객체"}],"type":"paragraph"}],"name":"videoController"},{"name":"bufferedTime","content":[{"inlineContent":[{"text":"버퍼 시간","type":"text"}],"type":"paragraph"}]}]}],"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoEventDelegate/adPlayer(_:didChangeBufferedTime:)":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoEventDelegate\/adPlayer(_:didChangeBufferedTime:)","abstract":[{"type":"text","text":"네이티브 광고 영상의 버퍼 진행률 변경 시 호출됩니다."}],"required":true,"role":"symbol","title":"adPlayer(_:didChangeBufferedTime:)","kind":"symbol","url":"\/documentation\/gfpsdk\/gfpvideoeventdelegate\/adplayer(_:didchangebufferedtime:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"adPlayer","kind":"identifier"},{"kind":"text","text":"("},{"text":"GFPVideoController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoController"},{"text":"!, ","kind":"text"},{"kind":"externalParam","text":"didChangeBufferedTime"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"adPlayer:didChangeBufferedTime:"}],"type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoEventDelegate":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPVideoEventDelegate"}],"navigatorTitle":[{"kind":"identifier","text":"GFPVideoEventDelegate"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoEventDelegate","url":"\/documentation\/gfpsdk\/gfpvideoeventdelegate","kind":"symbol","role":"symbol","abstract":[],"title":"GFPVideoEventDelegate","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoController":{"url":"\/documentation\/gfpsdk\/gfpvideocontroller","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPVideoController"}],"role":"symbol","abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"GFPVideoController"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoController","title":"GFPVideoController","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"adPlayer:didChangeBufferedTime:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"adPlayer:didChangeBufferedTime:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"adPlayer:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)GFPVideoController","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoController","kind":"typeIdentifier","text":"GFPVideoController"},{"text":" *) ","kind":"text"},{"text":"videoController","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"didChangeBufferedTime:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"NSTimeInterval"},{"kind":"text","text":") "},{"text":"bufferedTime","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"네이티브 비디오 컨트롤 객체"}],"type":"paragraph"}],"name":"videoController"},{"name":"bufferedTime","content":[{"inlineContent":[{"type":"text","text":"버퍼 시간"}],"type":"paragraph"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoEventDelegate~1adPlayer(_:didChangeBufferedTime:)\/title","value":"adPlayer:didChangeBufferedTime:"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoEventDelegate~1adPlayer(_:didChangeBufferedTime:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"adPlayer:didChangeBufferedTime:","kind":"identifier"}]},{"op":"replace","value":"GFPVideoEventDelegate","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoEventDelegate\/title"},{"op":"replace","value":[{"kind":"identifier","text":"GFPVideoEventDelegate"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoEventDelegate\/fragments"},{"value":[{"kind":"identifier","text":"GFPVideoEventDelegate"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoEventDelegate\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoController\/title","value":"GFPVideoController"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoController\/fragments","value":[{"kind":"identifier","text":"GFPVideoController"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoController\/navigatorTitle","value":[{"text":"GFPVideoController","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}