{"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoEventDelegate"]]},"abstract":[{"type":"text","text":"네이티브 광고 영상의 control 버튼 클릭 시 호출 됩니다."},{"text":" ","type":"text"},{"type":"text","text":"sdk에서 제공하는 default controlView 사용시 호출되며,  customControlView 사용시 호출되지 않습니다."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"adPlayer","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"videoController"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoController","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoController","text":"GFPVideoController"},{"text":"!, ","kind":"text"},{"kind":"externalParam","text":"didTappedControlButton"},{"text":" ","kind":"text"},{"text":"buttonType","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"GFPControlButtonType","kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPControlButtonType","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPControlButtonType"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"parameters":[{"content":[{"inlineContent":[{"text":"Control 버튼 타입","type":"text"}],"type":"paragraph"}],"name":"buttonType"}],"kind":"parameters"}],"metadata":{"role":"symbol","modules":[{"name":"GFPSDK"}],"externalID":"c:objc(pl)GFPVideoEventDelegate(im)adPlayer:didTappedControlButton:","symbolKind":"method","title":"adPlayer(_:didTappedControlButton:)","navigatorTitle":[{"kind":"identifier","text":"adPlayer:didTappedControlButton:"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"adPlayer","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)GFPVideoController","text":"GFPVideoController","kind":"typeIdentifier"},{"text":"!, ","kind":"text"},{"kind":"externalParam","text":"didTappedControlButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GFPControlButtonType","preciseIdentifier":"c:@E@GFPControlButtonType"},{"kind":"text","text":")"}],"roleHeading":"Instance Method","required":true},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpvideoeventdelegate\/adplayer(_:didtappedcontrolbutton:)"]},{"paths":["\/documentation\/gfpsdk\/gfpvideoeventdelegate\/adplayer(_:didtappedcontrolbutton:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoEventDelegate\/adPlayer(_:didTappedControlButton:)","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPControlButtonType":{"kind":"symbol","title":"GFPControlButtonType","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPControlButtonType"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPControlButtonType","role":"symbol","type":"topic","url":"\/documentation\/gfpsdk\/gfpcontrolbuttontype","navigatorTitle":[{"kind":"identifier","text":"GFPControlButtonType"}],"abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoEventDelegate/adPlayer(_:didTappedControlButton:)":{"required":true,"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"adPlayer:didTappedControlButton:"}],"abstract":[{"text":"네이티브 광고 영상의 control 버튼 클릭 시 호출 됩니다.","type":"text"},{"type":"text","text":" "},{"text":"sdk에서 제공하는 default controlView 사용시 호출되며,  customControlView 사용시 호출되지 않습니다.","type":"text"}],"kind":"symbol","title":"adPlayer(_:didTappedControlButton:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"adPlayer","kind":"identifier"},{"kind":"text","text":"("},{"text":"GFPVideoController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoController"},{"text":"!, ","kind":"text"},{"text":"didTappedControlButton","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@GFPControlButtonType","text":"GFPControlButtonType","kind":"typeIdentifier"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoEventDelegate\/adPlayer(_:didTappedControlButton:)","url":"\/documentation\/gfpsdk\/gfpvideoeventdelegate\/adplayer(_:didtappedcontrolbutton:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoEventDelegate":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPVideoEventDelegate"}],"navigatorTitle":[{"kind":"identifier","text":"GFPVideoEventDelegate"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoEventDelegate","url":"\/documentation\/gfpsdk\/gfpvideoeventdelegate","kind":"symbol","role":"symbol","abstract":[],"title":"GFPVideoEventDelegate","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoController":{"url":"\/documentation\/gfpsdk\/gfpvideocontroller","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPVideoController"}],"role":"symbol","abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"GFPVideoController"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoController","title":"GFPVideoController","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"adPlayer:didTappedControlButton:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"adPlayer:didTappedControlButton:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"adPlayer:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"GFPVideoController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoController","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoController"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"videoController"},{"kind":"text","text":" "},{"text":"didTappedControlButton:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPControlButtonType","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPControlButtonType","text":"GFPControlButtonType"},{"kind":"text","text":") "},{"kind":"internalParam","text":"buttonType"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Control 버튼 타입"}]}],"name":"buttonType"}]},"op":"replace"},{"op":"replace","value":"GFPControlButtonType","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPControlButtonType\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPControlButtonType\/fragments","value":[{"kind":"identifier","text":"GFPControlButtonType"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPControlButtonType\/navigatorTitle","op":"replace","value":[{"text":"GFPControlButtonType","kind":"identifier"}]},{"value":"adPlayer:didTappedControlButton:","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoEventDelegate~1adPlayer(_:didTappedControlButton:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoEventDelegate~1adPlayer(_:didTappedControlButton:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"adPlayer:didTappedControlButton:"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoEventDelegate\/title","value":"GFPVideoEventDelegate","op":"replace"},{"value":[{"kind":"identifier","text":"GFPVideoEventDelegate"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoEventDelegate\/fragments"},{"value":[{"text":"GFPVideoEventDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoEventDelegate\/navigatorTitle"},{"value":"GFPVideoController","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoController\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoController\/fragments","value":[{"kind":"identifier","text":"GFPVideoController"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoController\/navigatorTitle","value":[{"text":"GFPVideoController","kind":"identifier"}],"op":"replace"}]}]}