{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpnativestyleinfo\/darkcolor"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpnativestyleinfo\/darkcolor"]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeStyleInfo"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeStyleInfo\/darkColor"},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"kind":"symbol","metadata":{"roleHeading":"Instance Property","role":"symbol","navigatorTitle":[{"text":"darkColor","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"darkColor"},{"kind":"text","text":": "},{"text":"GFPNativeStyleDetailInfo","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPNativeStyleDetailInfo"},{"text":"?","kind":"text"}],"modules":[{"name":"GFPSDK"}],"symbolKind":"property","externalID":"c:objc(cs)GFPNativeStyleInfo(py)darkColor","title":"darkColor"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"darkColor"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeStyleDetailInfo","preciseIdentifier":"c:objc(cs)GFPNativeStyleDetailInfo","text":"GFPNativeStyleDetailInfo"},{"kind":"text","text":"? { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeStyleInfo/darkColor":{"role":"symbol","navigatorTitle":[{"text":"darkColor","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"darkColor","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GFPNativeStyleDetailInfo","preciseIdentifier":"c:objc(cs)GFPNativeStyleDetailInfo"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeStyleInfo\/darkColor","type":"topic","abstract":[],"kind":"symbol","url":"\/documentation\/gfpsdk\/gfpnativestyleinfo\/darkcolor","title":"darkColor"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeStyleDetailInfo":{"navigatorTitle":[{"kind":"identifier","text":"GFPNativeStyleDetailInfo"}],"role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeStyleDetailInfo","type":"topic","title":"GFPNativeStyleDetailInfo","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPNativeStyleDetailInfo","kind":"identifier"}],"abstract":[],"url":"\/documentation\/gfpsdk\/gfpnativestyledetailinfo","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeStyleInfo":{"title":"GFPNativeStyleInfo","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeStyleInfo","navigatorTitle":[{"text":"GFPNativeStyleInfo","kind":"identifier"}],"abstract":[],"kind":"symbol","type":"topic","url":"\/documentation\/gfpsdk\/gfpnativestyleinfo","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPNativeStyleInfo"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","value":"darkColor","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"darkColor","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"GFPNativeStyleDetailInfo","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeStyleDetailInfo","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPNativeStyleDetailInfo"},{"kind":"text","text":" * "},{"kind":"identifier","text":"darkColor"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":"darkColor","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeStyleInfo~1darkColor\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeStyleInfo~1darkColor\/fragments","value":[{"kind":"identifier","text":"darkColor"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeStyleDetailInfo\/title","value":"GFPNativeStyleDetailInfo"},{"value":[{"kind":"identifier","text":"GFPNativeStyleDetailInfo"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeStyleDetailInfo\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeStyleDetailInfo\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"GFPNativeStyleDetailInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeStyleInfo\/title","value":"GFPNativeStyleInfo"},{"value":[{"text":"GFPNativeStyleInfo","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeStyleInfo\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeStyleInfo\/navigatorTitle","value":[{"kind":"identifier","text":"GFPNativeStyleInfo"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}