{"kind":"symbol","metadata":{"title":"scheduleManager(_:didTappedReturnBtnInPIP:)","modules":[{"name":"GFPSDK"}],"required":true,"role":"symbol","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"scheduleManager","kind":"identifier"},{"text":"(","kind":"text"},{"text":"GFPVideoAdScheduleManager","preciseIdentifier":"c:objc(cs)GFPVideoAdScheduleManager","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didTappedReturnBtnInPIP"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"GFPVideoAdBreakResult","preciseIdentifier":"c:objc(cs)GFPVideoAdBreakResult"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"scheduleManager:didTappedReturnBtnInPIP:"}],"symbolKind":"method","externalID":"c:objc(pl)GFPVideoAdScheduleManagerPIPDelegate(im)scheduleManager:didTappedReturnBtnInPIP:"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManagerPIPDelegate\/scheduleManager(_:didTappedReturnBtnInPIP:)"},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"PIP 영역 상단의 리턴 버튼 클릭 시 호출됩니다."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"scheduleManager","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"aScheduleAdManager","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPVideoAdScheduleManager","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager","text":"GFPVideoAdScheduleManager","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"didTappedReturnBtnInPIP","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"aResult"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPVideoAdBreakResult","text":"GFPVideoAdBreakResult","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdBreakResult","kind":"typeIdentifier"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"스케쥴 매니저"}],"type":"paragraph"}],"name":"aScheduleAdManager"},{"name":"aResult","content":[{"type":"paragraph","inlineContent":[{"text":"재생 광고 정보*","type":"text"}]}]}],"kind":"parameters"}],"sections":[],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpvideoadschedulemanagerpipdelegate\/schedulemanager(_:didtappedreturnbtninpip:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gfpsdk\/gfpvideoadschedulemanagerpipdelegate\/schedulemanager(_:didtappedreturnbtninpip:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManagerPIPDelegate"]]},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdBreakResult":{"abstract":[],"kind":"symbol","title":"GFPVideoAdBreakResult","navigatorTitle":[{"text":"GFPVideoAdBreakResult","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdBreakResult","url":"\/documentation\/gfpsdk\/gfpvideoadbreakresult","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"GFPVideoAdBreakResult","kind":"identifier"}],"role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdScheduleManagerPIPDelegate/scheduleManager(_:didTappedReturnBtnInPIP:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"scheduleManager"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"GFPVideoAdScheduleManager","preciseIdentifier":"c:objc(cs)GFPVideoAdScheduleManager"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didTappedReturnBtnInPIP"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPVideoAdBreakResult","text":"GFPVideoAdBreakResult","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"scheduleManager(_:didTappedReturnBtnInPIP:)","navigatorTitle":[{"kind":"identifier","text":"scheduleManager:didTappedReturnBtnInPIP:"}],"url":"\/documentation\/gfpsdk\/gfpvideoadschedulemanagerpipdelegate\/schedulemanager(_:didtappedreturnbtninpip:)","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManagerPIPDelegate\/scheduleManager(_:didTappedReturnBtnInPIP:)","role":"symbol","type":"topic","kind":"symbol","abstract":[{"text":"PIP 영역 상단의 리턴 버튼 클릭 시 호출됩니다.","type":"text"}],"required":true},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdScheduleManager":{"kind":"symbol","type":"topic","url":"\/documentation\/gfpsdk\/gfpvideoadschedulemanager","title":"GFPVideoAdScheduleManager","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager","navigatorTitle":[{"kind":"identifier","text":"GFPVideoAdScheduleManager"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPVideoAdScheduleManager"}],"abstract":[],"role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdScheduleManagerPIPDelegate":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"GFPVideoAdScheduleManagerPIPDelegate","kind":"identifier"}],"abstract":[],"navigatorTitle":[{"text":"GFPVideoAdScheduleManagerPIPDelegate","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpvideoadschedulemanagerpipdelegate","kind":"symbol","type":"topic","role":"symbol","title":"GFPVideoAdScheduleManagerPIPDelegate","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManagerPIPDelegate"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"scheduleManager:didTappedReturnBtnInPIP:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"scheduleManager:didTappedReturnBtnInPIP:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"scheduleManager:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPVideoAdScheduleManager","text":"GFPVideoAdScheduleManager","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"aScheduleAdManager"},{"text":" ","kind":"text"},{"text":"didTappedReturnBtnInPIP:","kind":"identifier"},{"kind":"text","text":"("},{"text":"GFPVideoAdBreakResult","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdBreakResult","preciseIdentifier":"c:objc(cs)GFPVideoAdBreakResult"},{"text":" *) ","kind":"text"},{"text":"aResult","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"aScheduleAdManager","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"스케쥴 매니저"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"재생 광고 정보*"}]}],"name":"aResult"}]}},{"op":"replace","value":"GFPVideoAdBreakResult","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdBreakResult\/title"},{"op":"replace","value":[{"kind":"identifier","text":"GFPVideoAdBreakResult"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdBreakResult\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"GFPVideoAdBreakResult"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdBreakResult\/navigatorTitle"},{"value":"scheduleManager:didTappedReturnBtnInPIP:","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManagerPIPDelegate~1scheduleManager(_:didTappedReturnBtnInPIP:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManagerPIPDelegate~1scheduleManager(_:didTappedReturnBtnInPIP:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"scheduleManager:didTappedReturnBtnInPIP:"}]},{"op":"replace","value":"GFPVideoAdScheduleManager","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager\/title"},{"value":[{"kind":"identifier","text":"GFPVideoAdScheduleManager"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager\/navigatorTitle","op":"replace","value":[{"text":"GFPVideoAdScheduleManager","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManagerPIPDelegate\/title","value":"GFPVideoAdScheduleManagerPIPDelegate"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManagerPIPDelegate\/fragments","op":"replace","value":[{"text":"GFPVideoAdScheduleManagerPIPDelegate","kind":"identifier"}]},{"value":[{"text":"GFPVideoAdScheduleManagerPIPDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManagerPIPDelegate\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}