{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"scheduleManager","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"aScheduleAdManager"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager","text":"GFPVideoAdScheduleManager","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoAdScheduleManager"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didTappedCloseBtnInPIP"},{"kind":"text","text":" "},{"text":"aResult","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"GFPVideoAdBreakResult","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdBreakResult","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoAdBreakResult"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"스케쥴 매니저","type":"text"}]}],"name":"aScheduleAdManager"},{"content":[{"inlineContent":[{"type":"text","text":"재생 광고 정보*"}],"type":"paragraph"}],"name":"aResult"}],"kind":"parameters"}],"metadata":{"required":true,"externalID":"c:objc(pl)GFPVideoAdScheduleManagerPIPDelegate(im)scheduleManager:didTappedCloseBtnInPIP:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"scheduleManager"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPVideoAdScheduleManager","text":"GFPVideoAdScheduleManager","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didTappedCloseBtnInPIP"},{"text":": ","kind":"text"},{"text":"GFPVideoAdBreakResult","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoAdBreakResult"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"scheduleManager:didTappedCloseBtnInPIP:","kind":"identifier"}],"modules":[{"name":"GFPSDK"}],"symbolKind":"method","role":"symbol","roleHeading":"Instance Method","title":"scheduleManager(_:didTappedCloseBtnInPIP:)"},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManagerPIPDelegate"]]},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManagerPIPDelegate\/scheduleManager(_:didTappedCloseBtnInPIP:)","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpvideoadschedulemanagerpipdelegate\/schedulemanager(_:didtappedclosebtninpip:)"]},{"paths":["\/documentation\/gfpsdk\/gfpvideoadschedulemanagerpipdelegate\/schedulemanager(_:didtappedclosebtninpip:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"abstract":[{"type":"text","text":"PIP 영역 상단의 닫기 버튼 클릭 시 호출됩니다."}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdScheduleManagerPIPDelegate":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"GFPVideoAdScheduleManagerPIPDelegate","kind":"identifier"}],"abstract":[],"navigatorTitle":[{"text":"GFPVideoAdScheduleManagerPIPDelegate","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpvideoadschedulemanagerpipdelegate","kind":"symbol","type":"topic","role":"symbol","title":"GFPVideoAdScheduleManagerPIPDelegate","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManagerPIPDelegate"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdScheduleManagerPIPDelegate/scheduleManager(_:didTappedCloseBtnInPIP:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"scheduleManager"},{"kind":"text","text":"("},{"text":"GFPVideoAdScheduleManager","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoAdScheduleManager"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didTappedCloseBtnInPIP"},{"kind":"text","text":": "},{"text":"GFPVideoAdBreakResult","preciseIdentifier":"c:objc(cs)GFPVideoAdBreakResult","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"scheduleManager:didTappedCloseBtnInPIP:"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManagerPIPDelegate\/scheduleManager(_:didTappedCloseBtnInPIP:)","url":"\/documentation\/gfpsdk\/gfpvideoadschedulemanagerpipdelegate\/schedulemanager(_:didtappedclosebtninpip:)","kind":"symbol","role":"symbol","required":true,"abstract":[{"type":"text","text":"PIP 영역 상단의 닫기 버튼 클릭 시 호출됩니다."}],"type":"topic","title":"scheduleManager(_:didTappedCloseBtnInPIP:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdScheduleManager":{"kind":"symbol","type":"topic","url":"\/documentation\/gfpsdk\/gfpvideoadschedulemanager","title":"GFPVideoAdScheduleManager","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager","navigatorTitle":[{"kind":"identifier","text":"GFPVideoAdScheduleManager"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPVideoAdScheduleManager"}],"abstract":[],"role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdBreakResult":{"abstract":[],"kind":"symbol","title":"GFPVideoAdBreakResult","navigatorTitle":[{"text":"GFPVideoAdBreakResult","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdBreakResult","url":"\/documentation\/gfpsdk\/gfpvideoadbreakresult","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"GFPVideoAdBreakResult","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"scheduleManager:didTappedCloseBtnInPIP:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"scheduleManager:didTappedCloseBtnInPIP:"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"scheduleManager:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoAdScheduleManager","text":"GFPVideoAdScheduleManager"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"aScheduleAdManager"},{"kind":"text","text":" "},{"kind":"identifier","text":"didTappedCloseBtnInPIP:"},{"text":"(","kind":"text"},{"text":"GFPVideoAdBreakResult","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdBreakResult","preciseIdentifier":"c:objc(cs)GFPVideoAdBreakResult"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"aResult"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"value":{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"스케쥴 매니저"}],"type":"paragraph"}],"name":"aScheduleAdManager"},{"name":"aResult","content":[{"inlineContent":[{"type":"text","text":"재생 광고 정보*"}],"type":"paragraph"}]}],"kind":"parameters"},"path":"\/primaryContentSections\/1","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManagerPIPDelegate\/title","value":"GFPVideoAdScheduleManagerPIPDelegate","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManagerPIPDelegate\/fragments","op":"replace","value":[{"text":"GFPVideoAdScheduleManagerPIPDelegate","kind":"identifier"}]},{"op":"replace","value":[{"text":"GFPVideoAdScheduleManagerPIPDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManagerPIPDelegate\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManagerPIPDelegate~1scheduleManager(_:didTappedCloseBtnInPIP:)\/title","op":"replace","value":"scheduleManager:didTappedCloseBtnInPIP:"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManagerPIPDelegate~1scheduleManager(_:didTappedCloseBtnInPIP:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"scheduleManager:didTappedCloseBtnInPIP:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager\/title","value":"GFPVideoAdScheduleManager","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager\/fragments","value":[{"kind":"identifier","text":"GFPVideoAdScheduleManager"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager\/navigatorTitle","value":[{"kind":"identifier","text":"GFPVideoAdScheduleManager"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdBreakResult\/title","value":"GFPVideoAdBreakResult"},{"value":[{"kind":"identifier","text":"GFPVideoAdBreakResult"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdBreakResult\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdBreakResult\/navigatorTitle","value":[{"text":"GFPVideoAdBreakResult","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}