{"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdInfoSlotPresentable\/slotItems"},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdInfoSlotPresentable"]]},"variants":[{"paths":["\/documentation\/gfpsdk\/gfpnativeadinfoslotpresentable\/slotitems"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"NSArray<GFPNativeAdInfo *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"text":"slotItems","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","metadata":{"roleHeading":"Instance Method","title":"slotItems","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"slotItems"}],"role":"symbol","externalID":"c:objc(pl)GFPNativeAdInfoSlotPresentable(im)slotItems","navigatorTitle":[{"text":"slotItems","kind":"identifier"}],"symbolKind":"method","modules":[{"name":"GFPSDK"}]},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdInfoSlotPresentable":{"kind":"symbol","title":"GFPNativeAdInfoSlotPresentable","abstract":[],"role":"symbol","url":"\/documentation\/gfpsdk\/gfpnativeadinfoslotpresentable","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdInfoSlotPresentable","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPNativeAdInfoSlotPresentable"}],"navigatorTitle":[{"kind":"identifier","text":"GFPNativeAdInfoSlotPresentable"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdInfoSlotPresentable/slotItems":{"navigatorTitle":[{"text":"slotItems","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpnativeadinfoslotpresentable\/slotitems","abstract":[],"fragments":[{"text":"- ","kind":"text"},{"text":"slotItems","kind":"identifier"}],"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdInfoSlotPresentable\/slotItems","title":"slotItems"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdInfoSlotPresentable\/title","value":"GFPNativeAdInfoSlotPresentable"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdInfoSlotPresentable\/fragments","op":"replace","value":[{"text":"GFPNativeAdInfoSlotPresentable","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdInfoSlotPresentable\/navigatorTitle","value":[{"text":"GFPNativeAdInfoSlotPresentable","kind":"identifier"}],"op":"replace"}]}]}