{"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdDelegate\/nativeAdWasMuted(_:)","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdDelegate"]]},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nativeAdWasMuted","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"nativeAd"},{"text":": ","kind":"text"},{"text":"GFPNativeAd","preciseIdentifier":"c:objc(cs)GFPNativeAd","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAd","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"name":"nativeAd","content":[{"type":"paragraph","inlineContent":[{"text":"네이티브 광고 객체","type":"text"}]}]}],"kind":"parameters"}],"metadata":{"modules":[{"name":"GFPSDK"}],"required":true,"role":"symbol","roleHeading":"Instance Method","title":"nativeAdWasMuted(_:)","externalID":"c:objc(pl)GFPNativeAdDelegate(im)nativeAdWasMuted:","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"nativeAdWasMuted"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GFPNativeAd","preciseIdentifier":"c:objc(cs)GFPNativeAd"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"nativeAdWasMuted:"}]},"abstract":[{"text":"광고 뮤트 시 호출됩니다.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpnativeaddelegate\/nativeadwasmuted(_:)"]},{"paths":["\/documentation\/gfpsdk\/gfpnativeaddelegate\/nativeadwasmuted(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdDelegate":{"abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdDelegate","url":"\/documentation\/gfpsdk\/gfpnativeaddelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPNativeAdDelegate"}],"role":"symbol","navigatorTitle":[{"text":"GFPNativeAdDelegate","kind":"identifier"}],"type":"topic","kind":"symbol","title":"GFPNativeAdDelegate"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdDelegate/nativeAdWasMuted(_:)":{"type":"topic","url":"\/documentation\/gfpsdk\/gfpnativeaddelegate\/nativeadwasmuted(_:)","title":"nativeAdWasMuted(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"nativeAdWasMuted"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GFPNativeAd","preciseIdentifier":"c:objc(cs)GFPNativeAd"},{"kind":"text","text":")"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"nativeAdWasMuted:"}],"kind":"symbol","required":true,"abstract":[{"type":"text","text":"광고 뮤트 시 호출됩니다."}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdDelegate\/nativeAdWasMuted(_:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAd":{"abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAd","url":"\/documentation\/gfpsdk\/gfpnativead","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPNativeAd"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPNativeAd"}],"type":"topic","kind":"symbol","title":"GFPNativeAd"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"value":"nativeAdWasMuted:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"nativeAdWasMuted:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"nativeAdWasMuted:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)GFPNativeAd","text":"GFPNativeAd","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAd"},{"text":" *) ","kind":"text"},{"text":"nativeAd","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}},{"value":{"kind":"parameters","parameters":[{"name":"nativeAd","content":[{"type":"paragraph","inlineContent":[{"text":"네이티브 광고 객체","type":"text"}]}]}]},"path":"\/primaryContentSections\/1","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdDelegate\/title","value":"GFPNativeAdDelegate"},{"value":[{"text":"GFPNativeAdDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdDelegate\/fragments","op":"replace"},{"op":"replace","value":[{"text":"GFPNativeAdDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdDelegate\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdDelegate~1nativeAdWasMuted(_:)\/title","value":"nativeAdWasMuted:","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdDelegate~1nativeAdWasMuted(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"nativeAdWasMuted:","kind":"identifier"}],"op":"replace"},{"value":"GFPNativeAd","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAd\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAd\/fragments","value":[{"kind":"identifier","text":"GFPNativeAd"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAd\/navigatorTitle","value":[{"kind":"identifier","text":"GFPNativeAd"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}