{"metadata":{"symbolKind":"method","modules":[{"name":"GFPSDK"}],"roleHeading":"Instance Method","title":"nativeAdWasSeen(_:)","externalID":"c:objc(pl)GFPNativeAdDelegate(im)nativeAdWasSeen:","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nativeAdWasSeen","kind":"identifier"},{"kind":"text","text":"("},{"text":"GFPNativeAd","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPNativeAd"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"nativeAdWasSeen:","kind":"identifier"}]},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdDelegate\/nativeAdWasSeen(_:)","interfaceLanguage":"swift"},"abstract":[{"text":"광고가 사용자에게 보여진 경우 호출됩니다.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdDelegate"]]},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpnativeaddelegate\/nativeadwasseen(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpnativeaddelegate\/nativeadwasseen(_:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"optional"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nativeAdWasSeen","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"nativeAd"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPNativeAd","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAd","kind":"typeIdentifier","text":"GFPNativeAd"},{"text":")","kind":"text"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"nativeAd","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"네이티브 광고 응답객체"}]}]}]}],"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdDelegate/nativeAdWasSeen(_:)":{"navigatorTitle":[{"text":"nativeAdWasSeen:","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"광고가 사용자에게 보여진 경우 호출됩니다."}],"url":"\/documentation\/gfpsdk\/gfpnativeaddelegate\/nativeadwasseen(_:)","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdDelegate\/nativeAdWasSeen(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"nativeAdWasSeen"},{"text":"(","kind":"text"},{"text":"GFPNativeAd","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPNativeAd"},{"kind":"text","text":")"}],"title":"nativeAdWasSeen(_:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdDelegate":{"abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdDelegate","url":"\/documentation\/gfpsdk\/gfpnativeaddelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPNativeAdDelegate"}],"role":"symbol","navigatorTitle":[{"text":"GFPNativeAdDelegate","kind":"identifier"}],"type":"topic","kind":"symbol","title":"GFPNativeAdDelegate"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAd":{"abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAd","url":"\/documentation\/gfpsdk\/gfpnativead","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPNativeAd"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPNativeAd"}],"type":"topic","kind":"symbol","title":"GFPNativeAd"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","value":"nativeAdWasSeen:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"nativeAdWasSeen:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"text":"nativeAdWasSeen:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAd","kind":"typeIdentifier","text":"GFPNativeAd","preciseIdentifier":"c:objc(cs)GFPNativeAd"},{"kind":"text","text":" *) "},{"text":"nativeAd","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/primaryContentSections\/1","op":"replace","value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"네이티브 광고 응답객체"}]}],"name":"nativeAd"}],"kind":"parameters"}},{"value":"nativeAdWasSeen:","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdDelegate~1nativeAdWasSeen(_:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"nativeAdWasSeen:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdDelegate~1nativeAdWasSeen(_:)\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdDelegate\/title","op":"replace","value":"GFPNativeAdDelegate"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdDelegate\/fragments","op":"replace","value":[{"text":"GFPNativeAdDelegate","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"GFPNativeAdDelegate"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdDelegate\/navigatorTitle"},{"value":"GFPNativeAd","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAd\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAd\/fragments","value":[{"text":"GFPNativeAd","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAd\/navigatorTitle","op":"replace","value":[{"text":"GFPNativeAd","kind":"identifier"}]}]}]}