{"abstract":[{"text":"광고 뮤트 취소 시 호출됩니다.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdDelegate"]]},"sections":[],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpnativeaddelegate\/nativeadwascanceledmute(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpnativeaddelegate\/nativeadwascanceledmute(_:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"nativeAdWasCanceledMute"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"nativeAd"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAd","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPNativeAd","text":"GFPNativeAd"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"name":"nativeAd","content":[{"inlineContent":[{"text":"네이티브 광고 객체","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"}],"metadata":{"modules":[{"name":"GFPSDK"}],"navigatorTitle":[{"kind":"identifier","text":"nativeAdWasCanceledMute:"}],"symbolKind":"method","role":"symbol","roleHeading":"Instance Method","required":true,"externalID":"c:objc(pl)GFPNativeAdDelegate(im)nativeAdWasCanceledMute:","title":"nativeAdWasCanceledMute(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"nativeAdWasCanceledMute"},{"text":"(","kind":"text"},{"text":"GFPNativeAd","preciseIdentifier":"c:objc(cs)GFPNativeAd","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdDelegate\/nativeAdWasCanceledMute(_:)"},"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdDelegate":{"abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdDelegate","url":"\/documentation\/gfpsdk\/gfpnativeaddelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPNativeAdDelegate"}],"role":"symbol","navigatorTitle":[{"text":"GFPNativeAdDelegate","kind":"identifier"}],"type":"topic","kind":"symbol","title":"GFPNativeAdDelegate"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAd":{"abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAd","url":"\/documentation\/gfpsdk\/gfpnativead","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPNativeAd"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPNativeAd"}],"type":"topic","kind":"symbol","title":"GFPNativeAd"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdDelegate/nativeAdWasCanceledMute(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"nativeAdWasCanceledMute"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPNativeAd","kind":"typeIdentifier","text":"GFPNativeAd"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"nativeAdWasCanceledMute:"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdDelegate\/nativeAdWasCanceledMute(_:)","url":"\/documentation\/gfpsdk\/gfpnativeaddelegate\/nativeadwascanceledmute(_:)","kind":"symbol","role":"symbol","required":true,"abstract":[{"type":"text","text":"광고 뮤트 취소 시 호출됩니다."}],"type":"topic","title":"nativeAdWasCanceledMute(_:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"nativeAdWasCanceledMute:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"nativeAdWasCanceledMute:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"nativeAdWasCanceledMute:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAd","kind":"typeIdentifier","text":"GFPNativeAd","preciseIdentifier":"c:objc(cs)GFPNativeAd"},{"kind":"text","text":" *) "},{"text":"nativeAd","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"네이티브 광고 객체"}],"type":"paragraph"}],"name":"nativeAd"}]},"op":"replace","path":"\/primaryContentSections\/1"},{"op":"replace","value":"GFPNativeAdDelegate","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdDelegate\/title"},{"value":[{"kind":"identifier","text":"GFPNativeAdDelegate"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdDelegate\/fragments"},{"value":[{"kind":"identifier","text":"GFPNativeAdDelegate"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdDelegate\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAd\/title","value":"GFPNativeAd"},{"value":[{"text":"GFPNativeAd","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAd\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAd\/navigatorTitle","value":[{"kind":"identifier","text":"GFPNativeAd"}],"op":"replace"},{"value":"nativeAdWasCanceledMute:","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdDelegate~1nativeAdWasCanceledMute(_:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"nativeAdWasCanceledMute:"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdDelegate~1nativeAdWasCanceledMute(_:)\/fragments","op":"replace"}]}]}