{"metadata":{"symbolKind":"init","role":"symbol","externalID":"c:objc(cs)GFPReward(im)initWithRewardType:rewardAmount:","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"rewardType","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"rewardAmount","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithRewardType:rewardAmount:","kind":"identifier"}],"roleHeading":"Initializer","modules":[{"name":"GFPSDK"}],"title":"init(rewardType:rewardAmount:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"rewardType"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"rewardAmount","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"text":")","kind":"text"}]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPReward"]]},"variants":[{"paths":["\/documentation\/gfpsdk\/gfpreward\/init(rewardtype:rewardamount:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpreward\/init(rewardtype:rewardamount:)"]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPReward\/init(rewardType:rewardAmount:)","interfaceLanguage":"swift"},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPReward":{"kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPReward","url":"\/documentation\/gfpsdk\/gfpreward","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPReward","kind":"identifier"}],"title":"GFPReward","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GFPReward"}],"abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPReward/init(rewardType:rewardAmount:)":{"url":"\/documentation\/gfpsdk\/gfpreward\/init(rewardtype:rewardamount:)","title":"init(rewardType:rewardAmount:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"rewardType"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"rewardAmount"},{"text":": ","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":")","kind":"text"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPReward\/init(rewardType:rewardAmount:)","type":"topic","navigatorTitle":[{"text":"initWithRewardType:rewardAmount:","kind":"identifier"}],"abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","value":"initWithRewardType:rewardAmount:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithRewardType:rewardAmount:"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"initWithRewardType:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"rewardType"},{"text":" ","kind":"text"},{"text":"rewardAmount:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"rewardAmount"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPReward\/title","op":"replace","value":"GFPReward"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPReward\/fragments","op":"replace","value":[{"kind":"identifier","text":"GFPReward"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPReward\/navigatorTitle","value":[{"kind":"identifier","text":"GFPReward"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPReward~1init(rewardType:rewardAmount:)\/title","value":"initWithRewardType:rewardAmount:"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPReward~1init(rewardType:rewardAmount:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithRewardType:rewardAmount:","kind":"identifier"}],"op":"replace"}]}]}