{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpbaseeventreporter\/providerevent"]},{"paths":["\/documentation\/gfpsdk\/gfpbaseeventreporter\/providerevent"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBaseEventReporter"]]},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBaseEventReporter\/providerEvent","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"kind":"symbol","metadata":{"title":"providerEvent","role":"symbol","externalID":"c:objc(cs)GFPBaseEventReporter(py)providerEvent","roleHeading":"Instance Property","modules":[{"name":"GFPSDK"}],"symbolKind":"property","navigatorTitle":[{"text":"providerEvent","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"providerEvent","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"GFPAdInfoEvent","preciseIdentifier":"c:objc(cs)GFPAdInfoEvent"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"providerEvent"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPAdInfoEvent","kind":"typeIdentifier","text":"GFPAdInfoEvent","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdInfoEvent"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBaseEventReporter/providerEvent":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"providerEvent","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"GFPAdInfoEvent","preciseIdentifier":"c:objc(cs)GFPAdInfoEvent"}],"abstract":[],"navigatorTitle":[{"text":"providerEvent","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpbaseeventreporter\/providerevent","kind":"symbol","type":"topic","role":"symbol","title":"providerEvent","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBaseEventReporter\/providerEvent"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBaseEventReporter":{"title":"GFPBaseEventReporter","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPBaseEventReporter","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpbaseeventreporter","navigatorTitle":[{"text":"GFPBaseEventReporter","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBaseEventReporter"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdInfoEvent":{"title":"GFPAdInfoEvent","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdInfoEvent","role":"symbol","url":"\/documentation\/gfpsdk\/gfpadinfoevent","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"GFPAdInfoEvent","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"GFPAdInfoEvent"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"providerEvent"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"providerEvent"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPAdInfoEvent","text":"GFPAdInfoEvent","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdInfoEvent"},{"text":" * ","kind":"text"},{"text":"providerEvent","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"providerEvent","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBaseEventReporter~1providerEvent\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBaseEventReporter~1providerEvent\/fragments","value":[{"text":"providerEvent","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBaseEventReporter\/title","value":"GFPBaseEventReporter"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBaseEventReporter\/fragments","value":[{"kind":"identifier","text":"GFPBaseEventReporter"}]},{"value":[{"kind":"identifier","text":"GFPBaseEventReporter"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBaseEventReporter\/navigatorTitle"},{"op":"replace","value":"GFPAdInfoEvent","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdInfoEvent\/title"},{"value":[{"kind":"identifier","text":"GFPAdInfoEvent"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdInfoEvent\/fragments"},{"value":[{"text":"GFPAdInfoEvent","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdInfoEvent\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}