{"variants":[{"paths":["\/documentation\/gfpsdk\/gfpbaseeventreporter\/reportproviderevent(_:queryitems:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpbaseeventreporter\/reportproviderevent(_:queryitems:)"]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBaseEventReporter"]]},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"reportProviderEvent","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"providerEvtObjs","kind":"internalParam"},{"kind":"text","text":": ["},{"text":"GFPAdEventObject","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdEventObject","preciseIdentifier":"c:objc(cs)GFPAdEventObject"},{"text":"], ","kind":"text"},{"text":"queryItems","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"URLQueryItem","preciseIdentifier":"s:10Foundation12URLQueryItemV","kind":"typeIdentifier"},{"kind":"text","text":"]?)"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBaseEventReporter\/reportProviderEvent(_:queryItems:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"roleHeading":"Instance Method","modules":[{"name":"GFPSDK"}],"externalID":"c:objc(cs)GFPBaseEventReporter(im)reportProviderEvent:queryItems:","role":"symbol","symbolKind":"method","title":"reportProviderEvent(_:queryItems:)","navigatorTitle":[{"text":"reportProviderEvent:queryItems:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"reportProviderEvent","kind":"identifier"},{"kind":"text","text":"(["},{"text":"GFPAdEventObject","preciseIdentifier":"c:objc(cs)GFPAdEventObject","kind":"typeIdentifier"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"queryItems"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation12URLQueryItemV","text":"URLQueryItem"},{"kind":"text","text":"]?)"}]},"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBaseEventReporter/reportProviderEvent(_:queryItems:)":{"type":"topic","title":"reportProviderEvent(_:queryItems:)","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"reportProviderEvent","kind":"identifier"},{"text":"([","kind":"text"},{"text":"GFPAdEventObject","preciseIdentifier":"c:objc(cs)GFPAdEventObject","kind":"typeIdentifier"},{"kind":"text","text":"], "},{"text":"queryItems","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"URLQueryItem","preciseIdentifier":"s:10Foundation12URLQueryItemV"},{"text":"]?)","kind":"text"}],"url":"\/documentation\/gfpsdk\/gfpbaseeventreporter\/reportproviderevent(_:queryitems:)","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBaseEventReporter\/reportProviderEvent(_:queryItems:)","navigatorTitle":[{"text":"reportProviderEvent:queryItems:","kind":"identifier"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdEventObject":{"type":"topic","navigatorTitle":[{"text":"GFPAdEventObject","kind":"identifier"}],"abstract":[{"type":"text","text":"GFPAdEventObject"}],"role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdEventObject","title":"GFPAdEventObject","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPAdEventObject"}],"url":"\/documentation\/gfpsdk\/gfpadeventobject","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBaseEventReporter":{"title":"GFPBaseEventReporter","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPBaseEventReporter","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpbaseeventreporter","navigatorTitle":[{"text":"GFPBaseEventReporter","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBaseEventReporter"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","value":"reportProviderEvent:queryItems:","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"reportProviderEvent:queryItems:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"text":"reportProviderEvent:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<GFPAdEventObject *>"},{"kind":"text","text":" *) "},{"text":"providerEvtObjs","kind":"internalParam"},{"kind":"text","text":" "},{"text":"queryItems:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSArray<NSURLQueryItem *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"text":"queryItems","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBaseEventReporter~1reportProviderEvent(_:queryItems:)\/title","value":"reportProviderEvent:queryItems:"},{"value":[{"kind":"text","text":"- "},{"text":"reportProviderEvent:queryItems:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBaseEventReporter~1reportProviderEvent(_:queryItems:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdEventObject\/title","value":"GFPAdEventObject"},{"value":[{"text":"GFPAdEventObject","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdEventObject\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdEventObject\/navigatorTitle","op":"replace","value":[{"text":"GFPAdEventObject","kind":"identifier"}]},{"op":"replace","value":"GFPBaseEventReporter","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBaseEventReporter\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBaseEventReporter\/fragments","value":[{"kind":"identifier","text":"GFPBaseEventReporter"}],"op":"replace"},{"value":[{"kind":"identifier","text":"GFPBaseEventReporter"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBaseEventReporter\/navigatorTitle","op":"replace"}]}]}