{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"reportProviderEvent"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"providerEvtObjs","kind":"internalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"GFPAdEventObject","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdEventObject","preciseIdentifier":"c:objc(cs)GFPAdEventObject"},{"text":"])","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBaseEventReporter"]]},"metadata":{"modules":[{"name":"GFPSDK"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"reportProviderEvent","kind":"identifier"},{"text":"([","kind":"text"},{"text":"GFPAdEventObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdEventObject"},{"text":"])","kind":"text"}],"navigatorTitle":[{"text":"reportProviderEvent:","kind":"identifier"}],"symbolKind":"method","roleHeading":"Instance Method","externalID":"c:objc(cs)GFPBaseEventReporter(im)reportProviderEvent:","title":"reportProviderEvent(_:)","role":"symbol"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpbaseeventreporter\/reportproviderevent(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpbaseeventreporter\/reportproviderevent(_:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBaseEventReporter\/reportProviderEvent(_:)"},"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdEventObject":{"type":"topic","navigatorTitle":[{"text":"GFPAdEventObject","kind":"identifier"}],"abstract":[{"type":"text","text":"GFPAdEventObject"}],"role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdEventObject","title":"GFPAdEventObject","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPAdEventObject"}],"url":"\/documentation\/gfpsdk\/gfpadeventobject","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBaseEventReporter/reportProviderEvent(_:)":{"type":"topic","title":"reportProviderEvent(_:)","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"reportProviderEvent"},{"text":"([","kind":"text"},{"text":"GFPAdEventObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdEventObject"},{"kind":"text","text":"])"}],"url":"\/documentation\/gfpsdk\/gfpbaseeventreporter\/reportproviderevent(_:)","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBaseEventReporter\/reportProviderEvent(_:)","navigatorTitle":[{"text":"reportProviderEvent:","kind":"identifier"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBaseEventReporter":{"title":"GFPBaseEventReporter","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPBaseEventReporter","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpbaseeventreporter","navigatorTitle":[{"text":"GFPBaseEventReporter","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBaseEventReporter"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"reportProviderEvent:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"reportProviderEvent:","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"reportProviderEvent:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<GFPAdEventObject *>"},{"text":" *) ","kind":"text"},{"text":"providerEvtObjs","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdEventObject\/title","value":"GFPAdEventObject"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdEventObject\/fragments","value":[{"text":"GFPAdEventObject","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdEventObject\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"GFPAdEventObject"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBaseEventReporter~1reportProviderEvent(_:)\/title","value":"reportProviderEvent:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"reportProviderEvent:"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBaseEventReporter~1reportProviderEvent(_:)\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBaseEventReporter\/title","op":"replace","value":"GFPBaseEventReporter"},{"op":"replace","value":[{"text":"GFPBaseEventReporter","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBaseEventReporter\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"GFPBaseEventReporter"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBaseEventReporter\/navigatorTitle"}]}]}