{"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdParam"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"currentPageUrl"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? { "},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"abstract":[{"type":"text","text":"현재 페이지를 나타내는 url"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdParam\/currentPageUrl"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"currentPageUrl"}],"externalID":"c:objc(cs)GFPAdParam(py)currentPageUrl","roleHeading":"Instance Property","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"currentPageUrl"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"modules":[{"name":"GFPSDK"}],"title":"currentPageUrl","role":"symbol"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpadparam\/currentpageurl"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpadparam\/currentpageurl"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdParam/currentPageUrl":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"currentPageUrl"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic","title":"currentPageUrl","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"현재 페이지를 나타내는 url"}],"navigatorTitle":[{"text":"currentPageUrl","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpadparam\/currentpageurl","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdParam\/currentPageUrl"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdParam":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdParam","abstract":[],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPAdParam"}],"navigatorTitle":[{"text":"GFPAdParam","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpadparam","type":"topic","kind":"symbol","title":"GFPAdParam"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"currentPageUrl","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"kind":"identifier","text":"currentPageUrl"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"currentPageUrl"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdParam~1currentPageUrl\/title","value":"currentPageUrl"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdParam~1currentPageUrl\/fragments","value":[{"text":"currentPageUrl","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdParam\/title","value":"GFPAdParam","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdParam\/fragments","value":[{"text":"GFPAdParam","kind":"identifier"}],"op":"replace"},{"value":[{"text":"GFPAdParam","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdParam\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}