{"metadata":{"role":"collectionGroup","title":"Equatable Implementations","modules":[{"name":"GFPSDK"}],"roleHeading":"API Collection"},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUserParamGenderType\/Equatable-Implementations","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUserParamGenderType"]]},"sections":[],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpuserparamgendertype\/equatable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"article","topicSections":[{"generated":true,"title":"Operators","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUserParamGenderType\/!=(_:_:)"],"anchor":"Operators"}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPUserParamGenderType/!=(_:_:)":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUserParamGenderType\/!=(_:_:)","url":"\/documentation\/gfpsdk\/gfpuserparamgendertype\/!=(_:_:)","type":"topic","abstract":[],"kind":"symbol","title":"!=(_:_:)","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPUserParamGenderType":{"role":"symbol","type":"topic","title":"GFPUserParamGenderType","navigatorTitle":[{"kind":"identifier","text":"GFPUserParamGenderType"}],"abstract":[],"url":"\/documentation\/gfpsdk\/gfpuserparamgendertype","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPUserParamGenderType"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUserParamGenderType","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPUserParamGenderType\/title","op":"replace","value":"GFPUserParamGenderType"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPUserParamGenderType\/fragments","value":[{"kind":"identifier","text":"GFPUserParamGenderType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPUserParamGenderType\/navigatorTitle","value":[{"kind":"identifier","text":"GFPUserParamGenderType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}