{"topicSections":[{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUserParamGenderType\/hashValue"],"anchor":"Instance-Properties","title":"Instance Properties","generated":true},{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUserParamGenderType\/hash(into:)"],"anchor":"Instance-Methods"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"kind":"article","hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUserParamGenderType"]]},"variants":[{"paths":["\/documentation\/gfpsdk\/gfpuserparamgendertype\/rawrepresentable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"role":"collectionGroup","modules":[{"name":"GFPSDK"}],"title":"RawRepresentable Implementations","roleHeading":"API Collection"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUserParamGenderType\/RawRepresentable-Implementations"},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPUserParamGenderType/hashValue":{"kind":"symbol","type":"topic","conformance":{"conformancePrefix":[{"text":"Conforms when","type":"text"}],"availabilityPrefix":[{"type":"text","text":"Available when"}],"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"text":" and ","type":"text"},{"code":"RawValue","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":".","type":"text"}]},"abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUserParamGenderType\/hashValue","role":"symbol","title":"hashValue","url":"\/documentation\/gfpsdk\/gfpuserparamgendertype\/hashvalue","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"hashValue","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPUserParamGenderType/hash(into:)":{"url":"\/documentation\/gfpsdk\/gfpuserparamgendertype\/hash(into:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"hash","kind":"identifier"},{"text":"(","kind":"text"},{"text":"into","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"keyword","text":"inout"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"s:s6HasherV","text":"Hasher"},{"text":")","kind":"text"}],"kind":"symbol","abstract":[],"conformance":{"availabilityPrefix":[{"text":"Available when","type":"text"}],"constraints":[{"code":"Self","type":"codeVoice"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}],"conformancePrefix":[{"text":"Conforms when","type":"text"}]},"title":"hash(into:)","role":"symbol","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUserParamGenderType\/hash(into:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPUserParamGenderType":{"role":"symbol","type":"topic","title":"GFPUserParamGenderType","navigatorTitle":[{"kind":"identifier","text":"GFPUserParamGenderType"}],"abstract":[],"url":"\/documentation\/gfpsdk\/gfpuserparamgendertype","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPUserParamGenderType"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUserParamGenderType","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"patch":[{"value":"GFPUserParamGenderType","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPUserParamGenderType\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPUserParamGenderType\/fragments","value":[{"text":"GFPUserParamGenderType","kind":"identifier"}],"op":"replace"},{"value":[{"text":"GFPUserParamGenderType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPUserParamGenderType\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}