{"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdBannerWebViewOptions\/contentInsetAdjustmentBehavior"},"metadata":{"title":"contentInsetAdjustmentBehavior","role":"symbol","modules":[{"name":"GFPSDK"}],"roleHeading":"Instance Property","symbolKind":"property","navigatorTitle":[{"text":"contentInsetAdjustmentBehavior","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"contentInsetAdjustmentBehavior"},{"kind":"text","text":": "},{"text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@E@UIScrollViewContentInsetAdjustmentBehavior","kind":"typeIdentifier","text":"ContentInsetAdjustmentBehavior"}],"externalID":"c:objc(cs)GFPAdBannerWebViewOptions(py)contentInsetAdjustmentBehavior"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"contentInsetAdjustmentBehavior"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIScrollView","text":"UIScrollView"},{"text":".","kind":"text"},{"text":"ContentInsetAdjustmentBehavior","kind":"typeIdentifier","preciseIdentifier":"c:@E@UIScrollViewContentInsetAdjustmentBehavior"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpadbannerwebviewoptions\/contentinsetadjustmentbehavior"]},{"paths":["\/documentation\/gfpsdk\/gfpadbannerwebviewoptions\/contentinsetadjustmentbehavior"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdBannerWebViewOptions"]]},"sections":[],"abstract":[{"text":"Banner Inset 설정 insets mode","type":"text"}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdBannerWebViewOptions/contentInsetAdjustmentBehavior":{"navigatorTitle":[{"kind":"identifier","text":"contentInsetAdjustmentBehavior"}],"title":"contentInsetAdjustmentBehavior","url":"\/documentation\/gfpsdk\/gfpadbannerwebviewoptions\/contentinsetadjustmentbehavior","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdBannerWebViewOptions\/contentInsetAdjustmentBehavior","role":"symbol","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Banner Inset 설정 insets mode"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"contentInsetAdjustmentBehavior","kind":"identifier"},{"kind":"text","text":": "},{"text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView","kind":"typeIdentifier"},{"text":".","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@UIScrollViewContentInsetAdjustmentBehavior","text":"ContentInsetAdjustmentBehavior"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdBannerWebViewOptions":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdBannerWebViewOptions","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPAdBannerWebViewOptions"}],"navigatorTitle":[{"text":"GFPAdBannerWebViewOptions","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/gfpsdk\/gfpadbannerwebviewoptions","title":"GFPAdBannerWebViewOptions","kind":"symbol","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"contentInsetAdjustmentBehavior"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"contentInsetAdjustmentBehavior"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"assign","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@UIScrollViewContentInsetAdjustmentBehavior","text":"UIScrollViewContentInsetAdjustmentBehavior"},{"text":" ","kind":"text"},{"kind":"identifier","text":"contentInsetAdjustmentBehavior"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"contentInsetAdjustmentBehavior","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdBannerWebViewOptions~1contentInsetAdjustmentBehavior\/title","op":"replace"},{"value":[{"text":"contentInsetAdjustmentBehavior","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdBannerWebViewOptions~1contentInsetAdjustmentBehavior\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdBannerWebViewOptions\/title","value":"GFPAdBannerWebViewOptions"},{"value":[{"kind":"identifier","text":"GFPAdBannerWebViewOptions"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdBannerWebViewOptions\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdBannerWebViewOptions\/navigatorTitle","op":"replace","value":[{"text":"GFPAdBannerWebViewOptions","kind":"identifier"}]}]}]}