{"abstract":[{"text":"Banner Inset 설정 default size","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdBannerWebViewOptions\/defaultContentOffset"},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"defaultContentOffset","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint","text":"CGPoint"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/gfpsdk\/gfpadbannerwebviewoptions\/defaultcontentoffset"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpadbannerwebviewoptions\/defaultcontentoffset"]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdBannerWebViewOptions"]]},"metadata":{"symbolKind":"property","externalID":"c:objc(cs)GFPAdBannerWebViewOptions(py)defaultContentOffset","role":"symbol","modules":[{"name":"GFPSDK"}],"navigatorTitle":[{"kind":"identifier","text":"defaultContentOffset"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"defaultContentOffset"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint","text":"CGPoint"}],"roleHeading":"Instance Property","title":"defaultContentOffset"},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdBannerWebViewOptions":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdBannerWebViewOptions","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPAdBannerWebViewOptions"}],"navigatorTitle":[{"text":"GFPAdBannerWebViewOptions","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/gfpsdk\/gfpadbannerwebviewoptions","title":"GFPAdBannerWebViewOptions","kind":"symbol","abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdBannerWebViewOptions/defaultContentOffset":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdBannerWebViewOptions\/defaultContentOffset","navigatorTitle":[{"text":"defaultContentOffset","kind":"identifier"}],"abstract":[{"type":"text","text":"Banner Inset 설정 default size"}],"title":"defaultContentOffset","role":"symbol","kind":"symbol","url":"\/documentation\/gfpsdk\/gfpadbannerwebviewoptions\/defaultcontentoffset","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"defaultContentOffset"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint","text":"CGPoint"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","value":"defaultContentOffset","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"defaultContentOffset","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"assign","kind":"keyword"},{"kind":"text","text":", "},{"text":"readwrite","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@S@CGPoint","text":"CGPoint","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"defaultContentOffset","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":"GFPAdBannerWebViewOptions","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdBannerWebViewOptions\/title","op":"replace"},{"value":[{"kind":"identifier","text":"GFPAdBannerWebViewOptions"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdBannerWebViewOptions\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdBannerWebViewOptions\/navigatorTitle","value":[{"kind":"identifier","text":"GFPAdBannerWebViewOptions"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdBannerWebViewOptions~1defaultContentOffset\/title","op":"replace","value":"defaultContentOffset"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdBannerWebViewOptions~1defaultContentOffset\/fragments","value":[{"text":"defaultContentOffset","kind":"identifier"}],"op":"replace"}]}]}