{"metadata":{"symbolKind":"method","externalID":"c:objc(pl)GFPBannerAdaptorDelegate(im)bannerAdaptor:didChangeWith:","required":true,"modules":[{"name":"GFPSDK"}],"role":"symbol","navigatorTitle":[{"text":"bannerAdaptor:didChangeWith:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bannerAdaptor"},{"text":"(any ","kind":"text"},{"text":"GFPAdAdaptor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdAdaptor"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"GFPBannerAdapting","preciseIdentifier":"c:objc(pl)GFPBannerAdapting"},{"kind":"text","text":", "},{"text":"didChangeWith","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"])"}],"title":"bannerAdaptor(_:didChangeWith:)","roleHeading":"Instance Method"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bannerAdaptor"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"bannerAdaptor"},{"kind":"text","text":": any "},{"text":"GFPAdAdaptor","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAdaptor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdAdaptor"},{"text":" & ","kind":"text"},{"text":"GFPBannerAdapting","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerAdapting","preciseIdentifier":"c:objc(pl)GFPBannerAdapting"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didChangeWith"},{"text":" ","kind":"text"},{"text":"adMeta","kind":"internalParam"},{"text":": [","kind":"text"},{"text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"])","kind":"text"}],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpbanneradaptordelegate\/banneradaptor(_:didchangewith:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gfpsdk\/gfpbanneradaptordelegate\/banneradaptor(_:didchangewith:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerAdaptorDelegate"]]},"kind":"symbol","identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerAdaptorDelegate\/bannerAdaptor(_:didChangeWith:)","interfaceLanguage":"swift"},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerAdaptorDelegate/bannerAdaptor(_:didChangeWith:)":{"required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"bannerAdaptor"},{"text":"(any ","kind":"text"},{"text":"GFPAdAdaptor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdAdaptor"},{"text":" & ","kind":"text"},{"preciseIdentifier":"c:objc(pl)GFPBannerAdapting","text":"GFPBannerAdapting","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didChangeWith","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"])","kind":"text"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"bannerAdaptor:didChangeWith:"}],"url":"\/documentation\/gfpsdk\/gfpbanneradaptordelegate\/banneradaptor(_:didchangewith:)","kind":"symbol","type":"topic","role":"symbol","title":"bannerAdaptor(_:didChangeWith:)","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerAdaptorDelegate\/bannerAdaptor(_:didChangeWith:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerAdapting":{"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GFPBannerAdapting"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPBannerAdapting"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerAdapting","kind":"symbol","title":"GFPBannerAdapting","abstract":[],"url":"\/documentation\/gfpsdk\/gfpbanneradapting"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdAdaptor":{"navigatorTitle":[{"kind":"identifier","text":"GFPAdAdaptor"}],"title":"GFPAdAdaptor","url":"\/documentation\/gfpsdk\/gfpadadaptor","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAdaptor","abstract":[],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPAdAdaptor"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerAdaptorDelegate":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPBannerAdaptorDelegate"}],"abstract":[],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPBannerAdaptorDelegate"}],"url":"\/documentation\/gfpsdk\/gfpbanneradaptordelegate","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerAdaptorDelegate","role":"symbol","title":"GFPBannerAdaptorDelegate","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"bannerAdaptor:didChangeWith:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"bannerAdaptor:didChangeWith:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"bannerAdaptor:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"GFPAdAdaptor<GFPBannerAdapting>","preciseIdentifier":"c:Q$objc(cs)GFPAdAdaptorobjc(pl)GFPBannerAdapting"},{"text":" *) ","kind":"text"},{"text":"bannerAdaptor","kind":"internalParam"},{"kind":"text","text":" "},{"text":"didChangeWith:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSDictionary","text":"NSDictionary","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"adMeta"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"bannerAdaptor:didChangeWith:","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerAdaptorDelegate~1bannerAdaptor(_:didChangeWith:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerAdaptorDelegate~1bannerAdaptor(_:didChangeWith:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"bannerAdaptor:didChangeWith:"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerAdapting\/title","value":"GFPBannerAdapting","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerAdapting\/fragments","value":[{"text":"GFPBannerAdapting","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"GFPBannerAdapting"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerAdapting\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdaptor\/title","value":"GFPAdAdaptor"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdaptor\/fragments","value":[{"text":"GFPAdAdaptor","kind":"identifier"}]},{"value":[{"text":"GFPAdAdaptor","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdaptor\/navigatorTitle"},{"value":"GFPBannerAdaptorDelegate","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerAdaptorDelegate\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerAdaptorDelegate\/fragments","value":[{"kind":"identifier","text":"GFPBannerAdaptorDelegate"}]},{"op":"replace","value":[{"kind":"identifier","text":"GFPBannerAdaptorDelegate"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerAdaptorDelegate\/navigatorTitle"}]}]}