{"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bannerAdWas"},{"text":"(","kind":"text"},{"text":"onActiveImpression","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"bannerAdaptor"},{"text":": any ","kind":"text"},{"text":"GFPAdAdaptor","preciseIdentifier":"c:objc(cs)GFPAdAdaptor","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAdaptor","kind":"typeIdentifier"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"GFPBannerAdapting","preciseIdentifier":"c:objc(pl)GFPBannerAdapting","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerAdapting"},{"kind":"text","text":")"}],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpbanneradaptordelegate\/banneradwas(onactiveimpression:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpbanneradaptordelegate\/banneradwas(onactiveimpression:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerAdaptorDelegate\/bannerAdWas(onActiveImpression:)"},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerAdaptorDelegate"]]},"metadata":{"externalID":"c:objc(pl)GFPBannerAdaptorDelegate(im)bannerAdWasOnActiveImpression:","required":true,"navigatorTitle":[{"text":"bannerAdWasOnActiveImpression:","kind":"identifier"}],"title":"bannerAdWas(onActiveImpression:)","role":"symbol","symbolKind":"method","roleHeading":"Instance Method","modules":[{"name":"GFPSDK"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"bannerAdWas","kind":"identifier"},{"kind":"text","text":"("},{"text":"onActiveImpression","kind":"externalParam"},{"text":": any ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPAdAdaptor","text":"GFPAdAdaptor","kind":"typeIdentifier"},{"text":" & ","kind":"text"},{"text":"GFPBannerAdapting","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)GFPBannerAdapting"},{"text":")","kind":"text"}]},"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerAdapting":{"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GFPBannerAdapting"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPBannerAdapting"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerAdapting","kind":"symbol","title":"GFPBannerAdapting","abstract":[],"url":"\/documentation\/gfpsdk\/gfpbanneradapting"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdAdaptor":{"navigatorTitle":[{"kind":"identifier","text":"GFPAdAdaptor"}],"title":"GFPAdAdaptor","url":"\/documentation\/gfpsdk\/gfpadadaptor","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAdaptor","abstract":[],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPAdAdaptor"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerAdaptorDelegate":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPBannerAdaptorDelegate"}],"abstract":[],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPBannerAdaptorDelegate"}],"url":"\/documentation\/gfpsdk\/gfpbanneradaptordelegate","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerAdaptorDelegate","role":"symbol","title":"GFPBannerAdaptorDelegate","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerAdaptorDelegate/bannerAdWas(onActiveImpression:)":{"abstract":[],"title":"bannerAdWas(onActiveImpression:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bannerAdWas"},{"text":"(","kind":"text"},{"text":"onActiveImpression","kind":"externalParam"},{"text":": any ","kind":"text"},{"kind":"typeIdentifier","text":"GFPAdAdaptor","preciseIdentifier":"c:objc(cs)GFPAdAdaptor"},{"kind":"text","text":" & "},{"text":"GFPBannerAdapting","preciseIdentifier":"c:objc(pl)GFPBannerAdapting","kind":"typeIdentifier"},{"kind":"text","text":")"}],"url":"\/documentation\/gfpsdk\/gfpbanneradaptordelegate\/banneradwas(onactiveimpression:)","role":"symbol","required":true,"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerAdaptorDelegate\/bannerAdWas(onActiveImpression:)","navigatorTitle":[{"kind":"identifier","text":"bannerAdWasOnActiveImpression:"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","value":"bannerAdWasOnActiveImpression:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"bannerAdWasOnActiveImpression:"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"bannerAdWasOnActiveImpression:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)GFPAdAdaptorobjc(pl)GFPBannerAdapting","text":"GFPAdAdaptor<GFPBannerAdapting>"},{"kind":"text","text":" *) "},{"text":"bannerAdaptor","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerAdapting\/title","value":"GFPBannerAdapting","op":"replace"},{"op":"replace","value":[{"text":"GFPBannerAdapting","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerAdapting\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerAdapting\/navigatorTitle","value":[{"text":"GFPBannerAdapting","kind":"identifier"}]},{"op":"replace","value":"GFPAdAdaptor","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdaptor\/title"},{"op":"replace","value":[{"kind":"identifier","text":"GFPAdAdaptor"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdaptor\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdaptor\/navigatorTitle","value":[{"kind":"identifier","text":"GFPAdAdaptor"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerAdaptorDelegate\/title","value":"GFPBannerAdaptorDelegate","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerAdaptorDelegate\/fragments","value":[{"text":"GFPBannerAdaptorDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerAdaptorDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"GFPBannerAdaptorDelegate"}],"op":"replace"},{"value":"bannerAdWasOnActiveImpression:","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerAdaptorDelegate~1bannerAdWas(onActiveImpression:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"bannerAdWasOnActiveImpression:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerAdaptorDelegate~1bannerAdWas(onActiveImpression:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}