{"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoDisplayType"]]},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"navigatorTitle":[{"text":"GFPVideoDisplayTypeCasting","kind":"identifier"}],"role":"symbol","symbolKind":"case","roleHeading":"Case","externalID":"c:@M@GFPSDK@E@GFPVideoDisplayType@GFPVideoDisplayTypeCasting","modules":[{"name":"GFPSDK"}],"title":"GFPVideoDisplayType.casting","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"casting","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"casting"}],"platforms":["iOS"]}]}],"kind":"symbol","variants":[{"paths":["\/documentation\/gfpsdk\/gfpvideodisplaytype\/casting"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpvideodisplaytype\/casting"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoDisplayType\/casting"},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoDisplayType":{"navigatorTitle":[{"text":"GFPVideoDisplayType","kind":"identifier"}],"title":"GFPVideoDisplayType","url":"\/documentation\/gfpsdk\/gfpvideodisplaytype","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoDisplayType","role":"symbol","type":"topic","kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"GFPVideoDisplayType","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoDisplayType/casting":{"type":"topic","title":"GFPVideoDisplayType.casting","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"casting","kind":"identifier"}],"abstract":[],"url":"\/documentation\/gfpsdk\/gfpvideodisplaytype\/casting","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPVideoDisplayTypeCasting"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoDisplayType\/casting"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"GFPVideoDisplayTypeCasting"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GFPVideoDisplayTypeCasting"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"GFPVideoDisplayTypeCasting"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoDisplayType\/title","op":"replace","value":"GFPVideoDisplayType"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoDisplayType\/fragments","value":[{"kind":"identifier","text":"GFPVideoDisplayType"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoDisplayType\/navigatorTitle","value":[{"kind":"identifier","text":"GFPVideoDisplayType"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoDisplayType~1casting\/title","value":"GFPVideoDisplayTypeCasting"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoDisplayType~1casting\/fragments","value":[{"kind":"identifier","text":"GFPVideoDisplayTypeCasting"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}