{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoDisplayType\/PIP"},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PIP"}]}],"kind":"declarations"}],"metadata":{"role":"symbol","externalID":"c:@M@GFPSDK@E@GFPVideoDisplayType@GFPVideoDisplayTypePIP","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"PIP","kind":"identifier"}],"modules":[{"name":"GFPSDK"}],"symbolKind":"case","title":"GFPVideoDisplayType.PIP","roleHeading":"Case","navigatorTitle":[{"text":"GFPVideoDisplayTypePIP","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoDisplayType"]]},"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpvideodisplaytype\/pip"]},{"paths":["\/documentation\/gfpsdk\/gfpvideodisplaytype\/pip"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoDisplayType/PIP":{"type":"topic","url":"\/documentation\/gfpsdk\/gfpvideodisplaytype\/pip","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"PIP","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoDisplayType\/PIP","title":"GFPVideoDisplayType.PIP","navigatorTitle":[{"kind":"identifier","text":"GFPVideoDisplayTypePIP"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoDisplayType":{"navigatorTitle":[{"text":"GFPVideoDisplayType","kind":"identifier"}],"title":"GFPVideoDisplayType","url":"\/documentation\/gfpsdk\/gfpvideodisplaytype","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoDisplayType","role":"symbol","type":"topic","kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"GFPVideoDisplayType","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"value":"GFPVideoDisplayTypePIP","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"text":"GFPVideoDisplayTypePIP","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"GFPVideoDisplayTypePIP"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":"GFPVideoDisplayTypePIP","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoDisplayType~1PIP\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoDisplayType~1PIP\/fragments","op":"replace","value":[{"kind":"identifier","text":"GFPVideoDisplayTypePIP"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoDisplayType\/title","value":"GFPVideoDisplayType"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoDisplayType\/fragments","value":[{"text":"GFPVideoDisplayType","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"GFPVideoDisplayType"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoDisplayType\/navigatorTitle"}]}]}