{"kind":"article","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpnativeaddatatype\/setalgebra-implementations"]}],"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdDataType\/SetAlgebra-Implementations","interfaceLanguage":"swift"},"topicSections":[{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdDataType\/init(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdDataType\/init(arrayLiteral:)"],"title":"Initializers","generated":true,"anchor":"Initializers"},{"title":"Instance Properties","generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdDataType\/isEmpty"]},{"title":"Instance Methods","anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdDataType\/isDisjoint(with:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdDataType\/isStrictSubset(of:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdDataType\/isStrictSuperset(of:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdDataType\/isSubset(of:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdDataType\/isSuperset(of:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdDataType\/subtract(_:)","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdDataType\/subtracting(_:)"]}],"metadata":{"role":"collectionGroup","title":"SetAlgebra Implementations","modules":[{"name":"GFPSDK"}],"roleHeading":"API Collection"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdDataType"]]},"sections":[],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdDataType/isDisjoint(with:)":{"kind":"symbol","abstract":[],"url":"\/documentation\/gfpsdk\/gfpnativeaddatatype\/isdisjoint(with:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"isDisjoint","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"with"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Self"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdDataType\/isDisjoint(with:)","title":"isDisjoint(with:)","role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdDataType/isStrictSuperset(of:)":{"role":"symbol","type":"topic","abstract":[],"title":"isStrictSuperset(of:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"isStrictSuperset","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"of"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdDataType\/isStrictSuperset(of:)","url":"\/documentation\/gfpsdk\/gfpnativeaddatatype\/isstrictsuperset(of:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdDataType/init(_:)":{"role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"<","kind":"text"},{"text":"S","kind":"genericParameter"},{"kind":"text","text":">("},{"text":"S","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdDataType\/init(_:)","type":"topic","abstract":[],"url":"\/documentation\/gfpsdk\/gfpnativeaddatatype\/init(_:)","kind":"symbol","title":"init(_:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdDataType":{"navigatorTitle":[{"text":"GFPNativeAdDataType","kind":"identifier"}],"type":"topic","title":"GFPNativeAdDataType","kind":"symbol","url":"\/documentation\/gfpsdk\/gfpnativeaddatatype","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdDataType","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPNativeAdDataType"}],"role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdDataType/isStrictSubset(of:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"isStrictSubset","kind":"identifier"},{"text":"(","kind":"text"},{"text":"of","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"abstract":[],"url":"\/documentation\/gfpsdk\/gfpnativeaddatatype\/isstrictsubset(of:)","kind":"symbol","type":"topic","role":"symbol","title":"isStrictSubset(of:)","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdDataType\/isStrictSubset(of:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdDataType/init(arrayLiteral:)":{"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"arrayLiteral","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":".","kind":"text"},{"kind":"typeIdentifier","text":"Element","preciseIdentifier":"s:s10SetAlgebraP7ElementQa"},{"text":"...)","kind":"text"}],"abstract":[],"url":"\/documentation\/gfpsdk\/gfpnativeaddatatype\/init(arrayliteral:)","kind":"symbol","type":"topic","role":"symbol","title":"init(arrayLiteral:)","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdDataType\/init(arrayLiteral:)","conformance":{"conformancePrefix":[{"type":"text","text":"Conforms when"}],"constraints":[{"type":"codeVoice","code":"ArrayLiteralElement"},{"text":" is ","type":"text"},{"type":"codeVoice","code":"Self.Element"},{"type":"text","text":"."}],"availabilityPrefix":[{"type":"text","text":"Available when"}]}},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdDataType/isSuperset(of:)":{"abstract":[],"url":"\/documentation\/gfpsdk\/gfpnativeaddatatype\/issuperset(of:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isSuperset"},{"kind":"text","text":"("},{"kind":"externalParam","text":"of"},{"kind":"text","text":": "},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdDataType\/isSuperset(of:)","kind":"symbol","title":"isSuperset(of:)","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdDataType/subtracting(_:)":{"url":"\/documentation\/gfpsdk\/gfpnativeaddatatype\/subtracting(_:)","title":"subtracting(_:)","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdDataType\/subtracting(_:)","kind":"symbol","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"subtracting"},{"kind":"text","text":"("},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Self","kind":"typeIdentifier"}],"abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdDataType/subtract(_:)":{"url":"\/documentation\/gfpsdk\/gfpnativeaddatatype\/subtract(_:)","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdDataType\/subtract(_:)","abstract":[],"title":"subtract(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"subtract"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":")"}],"type":"topic","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdDataType/isSubset(of:)":{"title":"isSubset(of:)","abstract":[],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"isSubset","kind":"identifier"},{"kind":"text","text":"("},{"text":"of","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Self"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"url":"\/documentation\/gfpsdk\/gfpnativeaddatatype\/issubset(of:)","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdDataType\/isSubset(of:)","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdDataType/isEmpty":{"type":"topic","url":"\/documentation\/gfpsdk\/gfpnativeaddatatype\/isempty","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdDataType\/isEmpty","title":"isEmpty","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"isEmpty","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"kind":"symbol","abstract":[]}},"variantOverrides":[{"patch":[{"value":"GFPNativeAdDataType","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdDataType\/title","op":"replace"},{"value":[{"kind":"identifier","text":"GFPNativeAdDataType"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdDataType\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdDataType\/navigatorTitle","value":[{"text":"GFPNativeAdDataType","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}