{"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"metadata":{"navigatorTitle":[{"text":"adResponseSizeWithDictionary:","kind":"identifier"}],"role":"symbol","title":"adResponseSizeWith(dictionary:)","symbolKind":"method","roleHeading":"Type Method","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"adResponseSizeWith","kind":"identifier"},{"text":"(","kind":"text"},{"text":"dictionary","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"]) -> [","kind":"text"},{"text":"GFPWaterfallAdSize","kind":"typeIdentifier","preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPWaterfallAdSize"},{"kind":"text","text":"]"}],"externalID":"c:@M@GFPSDK@objc(cs)GFPInternalUtils(cm)adResponseSizeWithDictionary:","modules":[{"name":"GFPSDK"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"adResponseSizeWith"},{"kind":"text","text":"("},{"kind":"externalParam","text":"dictionary"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier","text":"AnyHashable"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]) -> ["},{"preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPWaterfallAdSize","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPWaterfallAdSize","kind":"typeIdentifier","text":"GFPWaterfallAdSize"},{"kind":"text","text":"]"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpinternalutils\/adresponsesizewith(dictionary:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpinternalutils\/adresponsesizewith(dictionary:)"]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInternalUtils"]]},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInternalUtils\/adResponseSizeWith(dictionary:)","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPInternalUtils":{"abstract":[],"url":"\/documentation\/gfpsdk\/gfpinternalutils","role":"symbol","title":"GFPInternalUtils","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInternalUtils","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GFPInternalUtils"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPInternalUtils","kind":"identifier"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPWaterfallAdSize":{"title":"GFPWaterfallAdSize","url":"\/documentation\/gfpsdk\/gfpwaterfalladsize","role":"symbol","navigatorTitle":[{"text":"GFPWaterfallAdSize","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPWaterfallAdSize","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPWaterfallAdSize"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPInternalUtils/adResponseSizeWith(dictionary:)":{"url":"\/documentation\/gfpsdk\/gfpinternalutils\/adresponsesizewith(dictionary:)","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"adResponseSizeWith"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"dictionary"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier","text":"AnyHashable"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]) -> [","kind":"text"},{"text":"GFPWaterfallAdSize","kind":"typeIdentifier","preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPWaterfallAdSize"},{"text":"]","kind":"text"}],"navigatorTitle":[{"text":"adResponseSizeWithDictionary:","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInternalUtils\/adResponseSizeWith(dictionary:)","title":"adResponseSizeWith(dictionary:)","kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"value":"adResponseSizeWithDictionary:","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"adResponseSizeWithDictionary:"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"NSArray<GFPWaterfallAdSize *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"adResponseSizeWithDictionary:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSDictionary","preciseIdentifier":"c:objc(cs)NSDictionary"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"dictionary"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"value":"GFPInternalUtils","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInternalUtils\/title"},{"op":"replace","value":[{"kind":"identifier","text":"GFPInternalUtils"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInternalUtils\/fragments"},{"op":"replace","value":[{"text":"GFPInternalUtils","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInternalUtils\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPWaterfallAdSize\/title","value":"GFPWaterfallAdSize"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPWaterfallAdSize\/fragments","value":[{"text":"GFPWaterfallAdSize","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPWaterfallAdSize\/navigatorTitle","value":[{"text":"GFPWaterfallAdSize","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInternalUtils~1adResponseSizeWith(dictionary:)\/title","op":"replace","value":"adResponseSizeWithDictionary:"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"adResponseSizeWithDictionary:"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInternalUtils~1adResponseSizeWith(dictionary:)\/fragments"}]}]}