{"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"adResponseSizeWith"},{"text":"(","kind":"text"},{"text":"string","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":") -> [","kind":"text"},{"text":"GFPWaterfallAdSize","kind":"typeIdentifier","preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPWaterfallAdSize"},{"text":"]","kind":"text"}],"roleHeading":"Type Method","modules":[{"name":"GFPSDK"}],"role":"symbol","symbolKind":"method","navigatorTitle":[{"text":"adResponseSizeWithString:","kind":"identifier"}],"title":"adResponseSizeWith(string:)","externalID":"c:@M@GFPSDK@objc(cs)GFPInternalUtils(cm)adResponseSizeWithString:"},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInternalUtils"]]},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInternalUtils\/adResponseSizeWith(string:)","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"adResponseSizeWith"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"string"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":") -> ["},{"text":"GFPWaterfallAdSize","kind":"typeIdentifier","preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPWaterfallAdSize","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPWaterfallAdSize"},{"kind":"text","text":"]"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpinternalutils\/adresponsesizewith(string:)"]},{"paths":["\/documentation\/gfpsdk\/gfpinternalutils\/adresponsesizewith(string:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPWaterfallAdSize":{"title":"GFPWaterfallAdSize","url":"\/documentation\/gfpsdk\/gfpwaterfalladsize","role":"symbol","navigatorTitle":[{"text":"GFPWaterfallAdSize","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPWaterfallAdSize","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPWaterfallAdSize"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPInternalUtils":{"abstract":[],"url":"\/documentation\/gfpsdk\/gfpinternalutils","role":"symbol","title":"GFPInternalUtils","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInternalUtils","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GFPInternalUtils"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPInternalUtils","kind":"identifier"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPInternalUtils/adResponseSizeWith(string:)":{"url":"\/documentation\/gfpsdk\/gfpinternalutils\/adresponsesizewith(string:)","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"adResponseSizeWith"},{"kind":"text","text":"("},{"text":"string","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":") -> [","kind":"text"},{"kind":"typeIdentifier","text":"GFPWaterfallAdSize","preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPWaterfallAdSize"},{"text":"]","kind":"text"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInternalUtils\/adResponseSizeWith(string:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"adResponseSizeWithString:"}],"role":"symbol","title":"adResponseSizeWith(string:)","type":"topic","abstract":[]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"adResponseSizeWithString:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"text":"adResponseSizeWithString:","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","text":"NSArray<GFPWaterfallAdSize *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"text":"adResponseSizeWithString:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"string","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPWaterfallAdSize\/title","value":"GFPWaterfallAdSize","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPWaterfallAdSize\/fragments","value":[{"kind":"identifier","text":"GFPWaterfallAdSize"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPWaterfallAdSize\/navigatorTitle","value":[{"kind":"identifier","text":"GFPWaterfallAdSize"}],"op":"replace"},{"value":"GFPInternalUtils","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInternalUtils\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInternalUtils\/fragments","value":[{"kind":"identifier","text":"GFPInternalUtils"}],"op":"replace"},{"value":[{"text":"GFPInternalUtils","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInternalUtils\/navigatorTitle"},{"value":"adResponseSizeWithString:","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInternalUtils~1adResponseSizeWith(string:)\/title","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"adResponseSizeWithString:"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInternalUtils~1adResponseSizeWith(string:)\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}