{"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"interstitialAdManager","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"GFPInterstitialAdManager","preciseIdentifier":"c:objc(cs)GFPInterstitialAdManager"},{"kind":"text","text":", "},{"text":"didComplete","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"GFPInterstitialAd","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPInterstitialAd"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"interstitialAdManager:didCompleteAd:","kind":"identifier"}],"externalID":"c:objc(pl)GFPInterstitialAdManagerDelegate(im)interstitialAdManager:didCompleteAd:","role":"symbol","roleHeading":"Instance Method","title":"interstitialAdManager(_:didComplete:)","required":true,"modules":[{"name":"GFPSDK"}],"symbolKind":"method"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"interstitialAdManager","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"manager","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdManager","preciseIdentifier":"c:objc(cs)GFPInterstitialAdManager","text":"GFPInterstitialAdManager"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didComplete"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"interstitialAd"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAd","preciseIdentifier":"c:objc(cs)GFPInterstitialAd","text":"GFPInterstitialAd","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"]}]}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpinterstitialadmanagerdelegate\/interstitialadmanager(_:didcomplete:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpinterstitialadmanagerdelegate\/interstitialadmanager(_:didcomplete:)"]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdManagerDelegate"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdManagerDelegate\/interstitialAdManager(_:didComplete:)"},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPInterstitialAdManagerDelegate/interstitialAdManager(_:didComplete:)":{"kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdManagerDelegate\/interstitialAdManager(_:didComplete:)","url":"\/documentation\/gfpsdk\/gfpinterstitialadmanagerdelegate\/interstitialadmanager(_:didcomplete:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"interstitialAdManager"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPInterstitialAdManager","text":"GFPInterstitialAdManager"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didComplete"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)GFPInterstitialAd","kind":"typeIdentifier","text":"GFPInterstitialAd"},{"text":")","kind":"text"}],"title":"interstitialAdManager(_:didComplete:)","role":"symbol","type":"topic","required":true,"navigatorTitle":[{"text":"interstitialAdManager:didCompleteAd:","kind":"identifier"}],"abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPInterstitialAdManager":{"kind":"symbol","title":"GFPInterstitialAdManager","url":"\/documentation\/gfpsdk\/gfpinterstitialadmanager","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPInterstitialAdManager","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdManager","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GFPInterstitialAdManager"}],"abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPInterstitialAdManagerDelegate":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPInterstitialAdManagerDelegate","kind":"identifier"}],"role":"symbol","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdManagerDelegate","kind":"symbol","type":"topic","url":"\/documentation\/gfpsdk\/gfpinterstitialadmanagerdelegate","title":"GFPInterstitialAdManagerDelegate","navigatorTitle":[{"kind":"identifier","text":"GFPInterstitialAdManagerDelegate"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPInterstitialAd":{"navigatorTitle":[{"text":"GFPInterstitialAd","kind":"identifier"}],"abstract":[],"url":"\/documentation\/gfpsdk\/gfpinterstitialad","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAd","type":"topic","kind":"symbol","title":"GFPInterstitialAd","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPInterstitialAd"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"interstitialAdManager:didCompleteAd:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"interstitialAdManager:didCompleteAd:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"interstitialAdManager:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdManager","preciseIdentifier":"c:objc(cs)GFPInterstitialAdManager","text":"GFPInterstitialAdManager","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"manager","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didCompleteAd:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAd","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPInterstitialAd","text":"GFPInterstitialAd"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"interstitialAd"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdManagerDelegate~1interstitialAdManager(_:didComplete:)\/title","value":"interstitialAdManager:didCompleteAd:"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdManagerDelegate~1interstitialAdManager(_:didComplete:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"interstitialAdManager:didCompleteAd:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdManager\/title","op":"replace","value":"GFPInterstitialAdManager"},{"value":[{"kind":"identifier","text":"GFPInterstitialAdManager"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdManager\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdManager\/navigatorTitle","value":[{"kind":"identifier","text":"GFPInterstitialAdManager"}]},{"value":"GFPInterstitialAdManagerDelegate","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdManagerDelegate\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdManagerDelegate\/fragments","op":"replace","value":[{"text":"GFPInterstitialAdManagerDelegate","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"GFPInterstitialAdManagerDelegate"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdManagerDelegate\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAd\/title","value":"GFPInterstitialAd"},{"value":[{"text":"GFPInterstitialAd","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAd\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAd\/navigatorTitle","value":[{"text":"GFPInterstitialAd","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}