{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpinterstitialadmanagerdelegate\/interstitialadmanager(_:didstart:)"]},{"paths":["\/documentation\/gfpsdk\/gfpinterstitialadmanagerdelegate\/interstitialadmanager(_:didstart:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdManagerDelegate"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"interstitialAdManager","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"manager","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdManager","preciseIdentifier":"c:objc(cs)GFPInterstitialAdManager","text":"GFPInterstitialAdManager"},{"kind":"text","text":", "},{"text":"didStart","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"interstitialAd"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAd","text":"GFPInterstitialAd","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPInterstitialAd"},{"kind":"text","text":")"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdManagerDelegate\/interstitialAdManager(_:didStart:)"},"kind":"symbol","metadata":{"title":"interstitialAdManager(_:didStart:)","symbolKind":"method","modules":[{"name":"GFPSDK"}],"role":"symbol","externalID":"c:objc(pl)GFPInterstitialAdManagerDelegate(im)interstitialAdManager:didStartAd:","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"interstitialAdManager","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)GFPInterstitialAdManager","kind":"typeIdentifier","text":"GFPInterstitialAdManager"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didStart"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPInterstitialAd","text":"GFPInterstitialAd"},{"kind":"text","text":")"}],"required":true,"navigatorTitle":[{"kind":"identifier","text":"interstitialAdManager:didStartAd:"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPInterstitialAdManager":{"kind":"symbol","title":"GFPInterstitialAdManager","url":"\/documentation\/gfpsdk\/gfpinterstitialadmanager","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPInterstitialAdManager","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdManager","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GFPInterstitialAdManager"}],"abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPInterstitialAdManagerDelegate/interstitialAdManager(_:didStart:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"interstitialAdManager"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPInterstitialAdManager","text":"GFPInterstitialAdManager"},{"kind":"text","text":", "},{"text":"didStart","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GFPInterstitialAd","preciseIdentifier":"c:objc(cs)GFPInterstitialAd"},{"text":")","kind":"text"}],"title":"interstitialAdManager(_:didStart:)","navigatorTitle":[{"kind":"identifier","text":"interstitialAdManager:didStartAd:"}],"url":"\/documentation\/gfpsdk\/gfpinterstitialadmanagerdelegate\/interstitialadmanager(_:didstart:)","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdManagerDelegate\/interstitialAdManager(_:didStart:)","role":"symbol","type":"topic","kind":"symbol","abstract":[],"required":true},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPInterstitialAd":{"navigatorTitle":[{"text":"GFPInterstitialAd","kind":"identifier"}],"abstract":[],"url":"\/documentation\/gfpsdk\/gfpinterstitialad","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAd","type":"topic","kind":"symbol","title":"GFPInterstitialAd","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPInterstitialAd"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPInterstitialAdManagerDelegate":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPInterstitialAdManagerDelegate","kind":"identifier"}],"role":"symbol","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdManagerDelegate","kind":"symbol","type":"topic","url":"\/documentation\/gfpsdk\/gfpinterstitialadmanagerdelegate","title":"GFPInterstitialAdManagerDelegate","navigatorTitle":[{"kind":"identifier","text":"GFPInterstitialAdManagerDelegate"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"interstitialAdManager:didStartAd:","path":"\/metadata\/title","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"interstitialAdManager:didStartAd:"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"interstitialAdManager:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPInterstitialAdManager","text":"GFPInterstitialAdManager","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdManager"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"manager"},{"text":" ","kind":"text"},{"text":"didStartAd:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAd","text":"GFPInterstitialAd","preciseIdentifier":"c:objc(cs)GFPInterstitialAd","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"interstitialAd","kind":"internalParam"},{"text":";","kind":"text"}]}]}},{"value":"GFPInterstitialAdManager","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdManager\/title"},{"value":[{"text":"GFPInterstitialAdManager","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdManager\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdManager\/navigatorTitle","value":[{"kind":"identifier","text":"GFPInterstitialAdManager"}],"op":"replace"},{"op":"replace","value":"interstitialAdManager:didStartAd:","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdManagerDelegate~1interstitialAdManager(_:didStart:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"interstitialAdManager:didStartAd:"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdManagerDelegate~1interstitialAdManager(_:didStart:)\/fragments"},{"value":"GFPInterstitialAd","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAd\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAd\/fragments","value":[{"text":"GFPInterstitialAd","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAd\/navigatorTitle","value":[{"kind":"identifier","text":"GFPInterstitialAd"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdManagerDelegate\/title","value":"GFPInterstitialAdManagerDelegate","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdManagerDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"GFPInterstitialAdManagerDelegate"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdManagerDelegate\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"GFPInterstitialAdManagerDelegate"}]}]}]}