{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"interstitialAdManager","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"manager"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)GFPInterstitialAdManager","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdManager","text":"GFPInterstitialAdManager","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"didClose","kind":"externalParam"},{"kind":"text","text":" "},{"text":"interstitialAd","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPInterstitialAd","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAd","text":"GFPInterstitialAd","kind":"typeIdentifier"},{"kind":"text","text":")"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpinterstitialadmanagerdelegate\/interstitialadmanager(_:didclose:)"]},{"paths":["\/documentation\/gfpsdk\/gfpinterstitialadmanagerdelegate\/interstitialadmanager(_:didclose:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"method","externalID":"c:objc(pl)GFPInterstitialAdManagerDelegate(im)interstitialAdManager:didCloseAd:","modules":[{"name":"GFPSDK"}],"navigatorTitle":[{"kind":"identifier","text":"interstitialAdManager:didCloseAd:"}],"title":"interstitialAdManager(_:didClose:)","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"interstitialAdManager","kind":"identifier"},{"text":"(","kind":"text"},{"text":"GFPInterstitialAdManager","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPInterstitialAdManager"},{"text":", ","kind":"text"},{"text":"didClose","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)GFPInterstitialAd","kind":"typeIdentifier","text":"GFPInterstitialAd"},{"text":")","kind":"text"}],"required":true,"role":"symbol"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdManagerDelegate\/interstitialAdManager(_:didClose:)"},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdManagerDelegate"]]},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPInterstitialAdManagerDelegate":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPInterstitialAdManagerDelegate","kind":"identifier"}],"role":"symbol","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdManagerDelegate","kind":"symbol","type":"topic","url":"\/documentation\/gfpsdk\/gfpinterstitialadmanagerdelegate","title":"GFPInterstitialAdManagerDelegate","navigatorTitle":[{"kind":"identifier","text":"GFPInterstitialAdManagerDelegate"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPInterstitialAdManagerDelegate/interstitialAdManager(_:didClose:)":{"type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdManagerDelegate\/interstitialAdManager(_:didClose:)","required":true,"role":"symbol","abstract":[],"navigatorTitle":[{"text":"interstitialAdManager:didCloseAd:","kind":"identifier"}],"title":"interstitialAdManager(_:didClose:)","kind":"symbol","url":"\/documentation\/gfpsdk\/gfpinterstitialadmanagerdelegate\/interstitialadmanager(_:didclose:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"interstitialAdManager","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPInterstitialAdManager","text":"GFPInterstitialAdManager"},{"kind":"text","text":", "},{"text":"didClose","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPInterstitialAd","text":"GFPInterstitialAd","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPInterstitialAdManager":{"kind":"symbol","title":"GFPInterstitialAdManager","url":"\/documentation\/gfpsdk\/gfpinterstitialadmanager","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPInterstitialAdManager","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdManager","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GFPInterstitialAdManager"}],"abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPInterstitialAd":{"navigatorTitle":[{"text":"GFPInterstitialAd","kind":"identifier"}],"abstract":[],"url":"\/documentation\/gfpsdk\/gfpinterstitialad","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAd","type":"topic","kind":"symbol","title":"GFPInterstitialAd","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPInterstitialAd"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","value":"interstitialAdManager:didCloseAd:","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"interstitialAdManager:didCloseAd:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"interstitialAdManager:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdManager","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPInterstitialAdManager","text":"GFPInterstitialAdManager"},{"text":" *) ","kind":"text"},{"text":"manager","kind":"internalParam"},{"kind":"text","text":" "},{"text":"didCloseAd:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)GFPInterstitialAd","kind":"typeIdentifier","text":"GFPInterstitialAd","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAd"},{"kind":"text","text":" *) "},{"text":"interstitialAd","kind":"internalParam"},{"kind":"text","text":";"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdManagerDelegate\/title","op":"replace","value":"GFPInterstitialAdManagerDelegate"},{"value":[{"kind":"identifier","text":"GFPInterstitialAdManagerDelegate"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdManagerDelegate\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdManagerDelegate\/navigatorTitle","value":[{"text":"GFPInterstitialAdManagerDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdManagerDelegate~1interstitialAdManager(_:didClose:)\/title","value":"interstitialAdManager:didCloseAd:"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdManagerDelegate~1interstitialAdManager(_:didClose:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"interstitialAdManager:didCloseAd:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdManager\/title","op":"replace","value":"GFPInterstitialAdManager"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdManager\/fragments","value":[{"kind":"identifier","text":"GFPInterstitialAdManager"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdManager\/navigatorTitle","value":[{"kind":"identifier","text":"GFPInterstitialAdManager"}]},{"value":"GFPInterstitialAd","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAd\/title"},{"op":"replace","value":[{"text":"GFPInterstitialAd","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAd\/fragments"},{"value":[{"kind":"identifier","text":"GFPInterstitialAd"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAd\/navigatorTitle","op":"replace"}]}]}