{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"adMute","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdChoicesType"]]},"metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"adMute","kind":"identifier"}],"navigatorTitle":[{"text":"GFPAdChoicesTypeAdMute","kind":"identifier"}],"symbolKind":"case","roleHeading":"Case","externalID":"c:@E@GFPAdChoicesType@GFPAdChoicesTypeAdMute","title":"GFPAdChoicesType.adMute","modules":[{"name":"GFPSDK"}]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpadchoicestype\/admute"]},{"paths":["\/documentation\/gfpsdk\/gfpadchoicestype\/admute"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdChoicesType\/adMute","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdChoicesType/adMute":{"navigatorTitle":[{"text":"GFPAdChoicesTypeAdMute","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpadchoicestype\/admute","abstract":[],"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"adMute"}],"role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdChoicesType\/adMute","type":"topic","title":"GFPAdChoicesType.adMute"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdChoicesType":{"abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdChoicesType","role":"symbol","url":"\/documentation\/gfpsdk\/gfpadchoicestype","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"GFPAdChoicesType","kind":"identifier"}],"navigatorTitle":[{"text":"GFPAdChoicesType","kind":"identifier"}],"kind":"symbol","title":"GFPAdChoicesType","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"GFPAdChoicesTypeAdMute","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"GFPAdChoicesTypeAdMute","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"GFPAdChoicesTypeAdMute"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdChoicesType~1adMute\/title","value":"GFPAdChoicesTypeAdMute","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdChoicesType~1adMute\/fragments","value":[{"text":"GFPAdChoicesTypeAdMute","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdChoicesType\/title","value":"GFPAdChoicesType"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdChoicesType\/fragments","op":"replace","value":[{"text":"GFPAdChoicesType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdChoicesType\/navigatorTitle","value":[{"text":"GFPAdChoicesType","kind":"identifier"}],"op":"replace"}]}]}