{"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdChoicesType"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/gfpsdk\/gfpadchoicestype\/privacy"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gfpsdk\/gfpadchoicestype\/privacy"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdChoicesType\/privacy","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"GFPAdChoicesTypePrivacy"}],"role":"symbol","title":"GFPAdChoicesType.privacy","symbolKind":"case","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"privacy","kind":"identifier"}],"externalID":"c:@E@GFPAdChoicesType@GFPAdChoicesTypePrivacy","modules":[{"name":"GFPSDK"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"privacy","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdChoicesType/privacy":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"privacy","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpadchoicestype\/privacy","kind":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdChoicesType\/privacy","role":"symbol","navigatorTitle":[{"text":"GFPAdChoicesTypePrivacy","kind":"identifier"}],"title":"GFPAdChoicesType.privacy"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdChoicesType":{"abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdChoicesType","role":"symbol","url":"\/documentation\/gfpsdk\/gfpadchoicestype","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"GFPAdChoicesType","kind":"identifier"}],"navigatorTitle":[{"text":"GFPAdChoicesType","kind":"identifier"}],"kind":"symbol","title":"GFPAdChoicesType","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"value":"GFPAdChoicesTypePrivacy","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","value":[{"text":"GFPAdChoicesTypePrivacy","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"GFPAdChoicesTypePrivacy","kind":"identifier"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdChoicesType~1privacy\/title","value":"GFPAdChoicesTypePrivacy","op":"replace"},{"op":"replace","value":[{"text":"GFPAdChoicesTypePrivacy","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdChoicesType~1privacy\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdChoicesType\/title","op":"replace","value":"GFPAdChoicesType"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdChoicesType\/fragments","value":[{"kind":"identifier","text":"GFPAdChoicesType"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdChoicesType\/navigatorTitle","value":[{"text":"GFPAdChoicesType","kind":"identifier"}],"op":"replace"}]}]}