{"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeViewUtils"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeViewUtils\/cornerInfo(with:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"cornerInfo"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"with"},{"text":" ","kind":"text"},{"text":"position","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"GFPAdChoicesViewPosition","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdChoicesViewPosition","preciseIdentifier":"c:@E@GFPAdChoicesViewPosition","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"GFPCornerInfo","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPCornerInfo","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPCornerInfo"}],"languages":["swift"],"platforms":["iOS"]}]}],"metadata":{"roleHeading":"Type Method","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cornerInfo"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"with"},{"text":": ","kind":"text"},{"text":"GFPAdChoicesViewPosition","preciseIdentifier":"c:@E@GFPAdChoicesViewPosition","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"GFPCornerInfo","preciseIdentifier":"c:objc(cs)GFPCornerInfo","kind":"typeIdentifier"}],"symbolKind":"method","externalID":"c:objc(cs)GFPNativeViewUtils(cm)cornerInfoWith:","modules":[{"name":"GFPSDK"}],"title":"cornerInfo(with:)","role":"symbol","navigatorTitle":[{"text":"cornerInfoWith:","kind":"identifier"}]},"variants":[{"paths":["\/documentation\/gfpsdk\/gfpnativeviewutils\/cornerinfo(with:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gfpsdk\/gfpnativeviewutils\/cornerinfo(with:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeViewUtils/cornerInfo(with:)":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeViewUtils\/cornerInfo(with:)","navigatorTitle":[{"kind":"identifier","text":"cornerInfoWith:"}],"abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"cornerInfo","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"GFPAdChoicesViewPosition","preciseIdentifier":"c:@E@GFPAdChoicesViewPosition"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"GFPCornerInfo","preciseIdentifier":"c:objc(cs)GFPCornerInfo"}],"title":"cornerInfo(with:)","type":"topic","url":"\/documentation\/gfpsdk\/gfpnativeviewutils\/cornerinfo(with:)","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdChoicesViewPosition":{"url":"\/documentation\/gfpsdk\/gfpadchoicesviewposition","role":"symbol","abstract":[],"type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPAdChoicesViewPosition"}],"title":"GFPAdChoicesViewPosition","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdChoicesViewPosition","navigatorTitle":[{"kind":"identifier","text":"GFPAdChoicesViewPosition"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeViewUtils":{"kind":"symbol","abstract":[],"title":"GFPNativeViewUtils","role":"symbol","url":"\/documentation\/gfpsdk\/gfpnativeviewutils","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPNativeViewUtils"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeViewUtils","navigatorTitle":[{"text":"GFPNativeViewUtils","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPCornerInfo":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPCornerInfo","navigatorTitle":[{"kind":"identifier","text":"GFPCornerInfo"}],"abstract":[],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPCornerInfo","kind":"identifier"}],"title":"GFPCornerInfo","type":"topic","kind":"symbol","url":"\/documentation\/gfpsdk\/gfpcornerinfo"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"value":"cornerInfoWith:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"cornerInfoWith:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPCornerInfo","text":"GFPCornerInfo","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPCornerInfo"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"cornerInfoWith:"},{"kind":"text","text":"("},{"text":"GFPAdChoicesViewPosition","kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPAdChoicesViewPosition","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdChoicesViewPosition"},{"text":") ","kind":"text"},{"text":"position","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeViewUtils~1cornerInfo(with:)\/title","op":"replace","value":"cornerInfoWith:"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"cornerInfoWith:"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeViewUtils~1cornerInfo(with:)\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdChoicesViewPosition\/title","value":"GFPAdChoicesViewPosition","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdChoicesViewPosition\/fragments","value":[{"kind":"identifier","text":"GFPAdChoicesViewPosition"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdChoicesViewPosition\/navigatorTitle","value":[{"text":"GFPAdChoicesViewPosition","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeViewUtils\/title","op":"replace","value":"GFPNativeViewUtils"},{"value":[{"text":"GFPNativeViewUtils","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeViewUtils\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeViewUtils\/navigatorTitle","value":[{"kind":"identifier","text":"GFPNativeViewUtils"}]},{"value":"GFPCornerInfo","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPCornerInfo\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPCornerInfo\/fragments","value":[{"text":"GFPCornerInfo","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"GFPCornerInfo"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPCornerInfo\/navigatorTitle"}]}]}