{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpbannerview\/init(adunitid:rootviewcontroller:adparam:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpbannerview\/init(adunitid:rootviewcontroller:adparam:)"]}],"abstract":[{"type":"text","text":"배너 광고를 생성합니다."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerView\/init(adUnitID:rootViewController:adParam:)"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"text":"adUnitID","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"rootViewController"},{"kind":"text","text":": "},{"text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"adParam","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdParam","text":"GFPAdParam","preciseIdentifier":"c:objc(cs)GFPAdParam","kind":"typeIdentifier"},{"text":"?)","kind":"text"}]}]},{"parameters":[{"name":"adUnitID","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"배너 광고 유닛 아이디"}]}]},{"name":"rootViewController","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"최상단 뷰 컨트롤러"}]}]},{"name":"adParam","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"광고 요청에 사용할 파라미터"}]}]}],"kind":"parameters"}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerView"]]},"metadata":{"modules":[{"name":"GFPSDK"}],"navigatorTitle":[{"text":"initWithAdUnitID:rootViewController:adParam:","kind":"identifier"}],"symbolKind":"init","role":"symbol","roleHeading":"Initializer","externalID":"c:objc(cs)GFPBannerView(im)initWithAdUnitID:rootViewController:adParam:","title":"init(adUnitID:rootViewController:adParam:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"adUnitID","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"rootViewController"},{"text":": ","kind":"text"},{"text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"adParam"},{"text":": ","kind":"text"},{"text":"GFPAdParam","preciseIdentifier":"c:objc(cs)GFPAdParam","kind":"typeIdentifier"},{"text":"?)","kind":"text"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerView":{"navigatorTitle":[{"text":"GFPBannerView","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerView","title":"GFPBannerView","role":"symbol","url":"\/documentation\/gfpsdk\/gfpbannerview","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPBannerView"}],"type":"topic","kind":"symbol","abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerView/init(adUnitID:rootViewController:adParam:)":{"abstract":[{"type":"text","text":"배너 광고를 생성합니다."}],"url":"\/documentation\/gfpsdk\/gfpbannerview\/init(adunitid:rootviewcontroller:adparam:)","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerView\/init(adUnitID:rootViewController:adParam:)","type":"topic","role":"symbol","title":"init(adUnitID:rootViewController:adParam:)","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"adUnitID","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"rootViewController","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"adParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)GFPAdParam","text":"GFPAdParam","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"initWithAdUnitID:rootViewController:adParam:"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdParam":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdParam","abstract":[],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPAdParam"}],"navigatorTitle":[{"text":"GFPAdParam","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpadparam","type":"topic","kind":"symbol","title":"GFPAdParam"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"initWithAdUnitID:rootViewController:adParam:","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"initWithAdUnitID:rootViewController:adParam:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"text":"initWithAdUnitID:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"adUnitID","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"rootViewController:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":" *) ","kind":"text"},{"text":"rootViewController","kind":"internalParam"},{"kind":"text","text":" "},{"text":"adParam:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GFPAdParam","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdParam","preciseIdentifier":"c:objc(cs)GFPAdParam"},{"kind":"text","text":" *) "},{"text":"adParam","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"배너 광고 유닛 아이디"}]}],"name":"adUnitID"},{"name":"rootViewController","content":[{"type":"paragraph","inlineContent":[{"text":"최상단 뷰 컨트롤러","type":"text"}]}]},{"name":"adParam","content":[{"inlineContent":[{"type":"text","text":"광고 요청에 사용할 파라미터"}],"type":"paragraph"}]}],"kind":"parameters"}},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerView\/title","value":"GFPBannerView"},{"value":[{"kind":"identifier","text":"GFPBannerView"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerView\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerView\/navigatorTitle","op":"replace","value":[{"text":"GFPBannerView","kind":"identifier"}]},{"op":"replace","value":"initWithAdUnitID:rootViewController:adParam:","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerView~1init(adUnitID:rootViewController:adParam:)\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerView~1init(adUnitID:rootViewController:adParam:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithAdUnitID:rootViewController:adParam:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdParam\/title","value":"GFPAdParam","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdParam\/fragments","value":[{"text":"GFPAdParam","kind":"identifier"}]},{"op":"replace","value":[{"text":"GFPAdParam","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdParam\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}