{"abstract":[{"type":"text","text":"배너 레이아웃 타입. (기본값: GFPBannerViewLayoutTypeFixed)"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpbannerview\/layouttype"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpbannerview\/layouttype"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerView"]]},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerView\/layoutType","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"GFPSDK"}],"title":"layoutType","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"layoutType"},{"text":": ","kind":"text"},{"text":"GFPBannerViewLayoutType","kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPBannerViewLayoutType"}],"role":"symbol","externalID":"c:objc(cs)GFPBannerView(py)layoutType","navigatorTitle":[{"text":"layoutType","kind":"identifier"}],"roleHeading":"Instance Property"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"layoutType"},{"text":": ","kind":"text"},{"text":"GFPBannerViewLayoutType","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerViewLayoutType","kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPBannerViewLayoutType"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerView/layoutType":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerView\/layoutType","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"layoutType","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GFPBannerViewLayoutType","preciseIdentifier":"c:@E@GFPBannerViewLayoutType"}],"abstract":[{"type":"text","text":"배너 레이아웃 타입. (기본값: GFPBannerViewLayoutTypeFixed)"}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"layoutType"}],"url":"\/documentation\/gfpsdk\/gfpbannerview\/layouttype","title":"layoutType","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerView":{"navigatorTitle":[{"text":"GFPBannerView","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerView","title":"GFPBannerView","role":"symbol","url":"\/documentation\/gfpsdk\/gfpbannerview","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPBannerView"}],"type":"topic","kind":"symbol","abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerViewLayoutType":{"kind":"symbol","title":"GFPBannerViewLayoutType","url":"\/documentation\/gfpsdk\/gfpbannerviewlayouttype","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPBannerViewLayoutType"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerViewLayoutType","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GFPBannerViewLayoutType"}],"abstract":[]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","value":"layoutType","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"value":[{"text":"layoutType","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"assign","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readwrite","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@E@GFPBannerViewLayoutType","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerViewLayoutType","kind":"typeIdentifier","text":"GFPBannerViewLayoutType"},{"text":" ","kind":"text"},{"kind":"identifier","text":"layoutType"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerView~1layoutType\/title","value":"layoutType","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerView~1layoutType\/fragments","value":[{"kind":"identifier","text":"layoutType"}],"op":"replace"},{"op":"replace","value":"GFPBannerView","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerView\/title"},{"value":[{"kind":"identifier","text":"GFPBannerView"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerView\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerView\/navigatorTitle","value":[{"text":"GFPBannerView","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerViewLayoutType\/title","value":"GFPBannerViewLayoutType"},{"op":"replace","value":[{"text":"GFPBannerViewLayoutType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerViewLayoutType\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"GFPBannerViewLayoutType"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerViewLayoutType\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}