{"abstract":[{"text":"쇼핑광고의 Badge 지원","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLabelOption\/badgeOption"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"badgeOption"},{"text":": ","kind":"text"},{"text":"GFPBadgeOption","preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPBadgeOption","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBadgeOption"},{"text":"?","kind":"text"}],"platforms":["iOS"]}]}],"metadata":{"modules":[{"name":"GFPSDK"}],"externalID":"c:@M@GFPSDK@objc(cs)GFPLabelOption(py)badgeOption","roleHeading":"Instance Property","title":"badgeOption","role":"symbol","symbolKind":"property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"badgeOption","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPBadgeOption","text":"GFPBadgeOption"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"badgeOption"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfplabeloption\/badgeoption"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfplabeloption\/badgeoption"]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLabelOption"]]},"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPLabelOption":{"title":"GFPLabelOption","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLabelOption","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPLabelOption","kind":"identifier"}],"type":"topic","url":"\/documentation\/gfpsdk\/gfplabeloption","kind":"symbol","navigatorTitle":[{"text":"GFPLabelOption","kind":"identifier"}],"role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPLabelOption/badgeOption":{"url":"\/documentation\/gfpsdk\/gfplabeloption\/badgeoption","title":"badgeOption","abstract":[{"type":"text","text":"쇼핑광고의 Badge 지원"}],"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"badgeOption","kind":"identifier"},{"text":": ","kind":"text"},{"text":"GFPBadgeOption","kind":"typeIdentifier","preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPBadgeOption"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLabelOption\/badgeOption","type":"topic","navigatorTitle":[{"kind":"identifier","text":"badgeOption"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBadgeOption":{"title":"GFPBadgeOption","abstract":[],"url":"\/documentation\/gfpsdk\/gfpbadgeoption","role":"symbol","navigatorTitle":[{"text":"GFPBadgeOption","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBadgeOption","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"GFPBadgeOption","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"badgeOption","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","value":[{"kind":"identifier","text":"badgeOption"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"GFPBadgeOption","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBadgeOption","preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPBadgeOption"},{"kind":"text","text":" * "},{"kind":"identifier","text":"badgeOption"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","value":"GFPLabelOption","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLabelOption\/title"},{"value":[{"text":"GFPLabelOption","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLabelOption\/fragments","op":"replace"},{"value":[{"text":"GFPLabelOption","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLabelOption\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLabelOption~1badgeOption\/title","value":"badgeOption","op":"replace"},{"value":[{"text":"badgeOption","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLabelOption~1badgeOption\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBadgeOption\/title","value":"GFPBadgeOption"},{"op":"replace","value":[{"text":"GFPBadgeOption","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBadgeOption\/fragments"},{"value":[{"text":"GFPBadgeOption","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBadgeOption\/navigatorTitle","op":"replace"}]}]}