{"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLabelOption\/init(text:textColor:bgColor:highlightBgColor:isBold:badgeOption:spannableOption:)","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(initWithText:textColor:bgColor:highlightBgColor:isBold:badgeOption:spannableOption:) ","kind":"text"},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"text"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"textColor"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"bgColor"},{"kind":"text","text":": "},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"highlightBgColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"?, "},{"text":"isBold","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"badgeOption"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GFPBadgeOption","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBadgeOption","preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPBadgeOption"},{"text":"?, ","kind":"text"},{"text":"spannableOption","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPSpannableOption","preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPSpannableOption","text":"GFPSpannableOption"},{"text":"]?)","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLabelOption"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfplabeloption\/init(text:textcolor:bgcolor:highlightbgcolor:isbold:badgeoption:spannableoption:)"]},{"paths":["\/documentation\/gfpsdk\/gfplabeloption\/init(text:textcolor:bgcolor:highlightbgcolor:isbold:badgeoption:spannableoption:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:@M@GFPSDK@objc(cs)GFPLabelOption(im)initWithText:textColor:bgColor:highlightBgColor:isBold:badgeOption:spannableOption:","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"text"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"textColor"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"kind":"text","text":"?, "},{"text":"bgColor","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":"?, ","kind":"text"},{"text":"highlightBgColor","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"isBold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"badgeOption"},{"kind":"text","text":": "},{"text":"GFPBadgeOption","kind":"typeIdentifier","preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPBadgeOption"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"spannableOption"},{"kind":"text","text":": ["},{"text":"GFPSpannableOption","kind":"typeIdentifier","preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPSpannableOption"},{"text":"]?)","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"initWithText:textColor:bgColor:highlightBgColor:isBold:badgeOption:spannableOption:"}],"modules":[{"name":"GFPSDK"}],"symbolKind":"init","role":"symbol","title":"init(text:textColor:bgColor:highlightBgColor:isBold:badgeOption:spannableOption:)","roleHeading":"Initializer"},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPLabelOption/init(text:textColor:bgColor:highlightBgColor:isBold:badgeOption:spannableOption:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"text","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"textColor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"?, "},{"text":"bgColor","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"highlightBgColor"},{"kind":"text","text":": "},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"isBold"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"badgeOption","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"GFPBadgeOption","kind":"typeIdentifier","preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPBadgeOption"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"spannableOption"},{"text":": [","kind":"text"},{"text":"GFPSpannableOption","kind":"typeIdentifier","preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPSpannableOption"},{"text":"]?)","kind":"text"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLabelOption\/init(text:textColor:bgColor:highlightBgColor:isBold:badgeOption:spannableOption:)","kind":"symbol","title":"init(text:textColor:bgColor:highlightBgColor:isBold:badgeOption:spannableOption:)","role":"symbol","type":"topic","url":"\/documentation\/gfpsdk\/gfplabeloption\/init(text:textcolor:bgcolor:highlightbgcolor:isbold:badgeoption:spannableoption:)","navigatorTitle":[{"text":"initWithText:textColor:bgColor:highlightBgColor:isBold:badgeOption:spannableOption:","kind":"identifier"}],"abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPLabelOption":{"title":"GFPLabelOption","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLabelOption","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPLabelOption","kind":"identifier"}],"type":"topic","url":"\/documentation\/gfpsdk\/gfplabeloption","kind":"symbol","navigatorTitle":[{"text":"GFPLabelOption","kind":"identifier"}],"role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPSpannableOption":{"title":"GFPSpannableOption","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPSpannableOption","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"GFPSpannableOption","kind":"identifier"}],"type":"topic","url":"\/documentation\/gfpsdk\/gfpspannableoption","kind":"symbol","navigatorTitle":[{"text":"GFPSpannableOption","kind":"identifier"}],"role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBadgeOption":{"title":"GFPBadgeOption","abstract":[],"url":"\/documentation\/gfpsdk\/gfpbadgeoption","role":"symbol","navigatorTitle":[{"text":"GFPBadgeOption","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBadgeOption","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"GFPBadgeOption","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"initWithText:textColor:bgColor:highlightBgColor:isBold:badgeOption:spannableOption:","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithText:textColor:bgColor:highlightBgColor:isBold:badgeOption:spannableOption:"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithText:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"text"},{"text":" ","kind":"text"},{"kind":"identifier","text":"textColor:"},{"kind":"text","text":"("},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"textColor"},{"text":" ","kind":"text"},{"text":"bgColor:","kind":"identifier"},{"kind":"text","text":"("},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":" *) ","kind":"text"},{"text":"bgColor","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"highlightBgColor:","kind":"identifier"},{"kind":"text","text":"("},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"highlightBgColor","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isBold:"},{"text":"(","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"isBold","kind":"internalParam"},{"kind":"text","text":" "},{"text":"badgeOption:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBadgeOption","preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPBadgeOption","text":"GFPBadgeOption"},{"kind":"text","text":" *) "},{"text":"badgeOption","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"spannableOption:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<GFPSpannableOption *>"},{"kind":"text","text":" *) "},{"text":"spannableOption","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLabelOption~1init(text:textColor:bgColor:highlightBgColor:isBold:badgeOption:spannableOption:)\/title","value":"initWithText:textColor:bgColor:highlightBgColor:isBold:badgeOption:spannableOption:","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithText:textColor:bgColor:highlightBgColor:isBold:badgeOption:spannableOption:"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLabelOption~1init(text:textColor:bgColor:highlightBgColor:isBold:badgeOption:spannableOption:)\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLabelOption\/title","value":"GFPLabelOption","op":"replace"},{"value":[{"kind":"identifier","text":"GFPLabelOption"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLabelOption\/fragments"},{"value":[{"text":"GFPLabelOption","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLabelOption\/navigatorTitle","op":"replace"},{"value":"GFPSpannableOption","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPSpannableOption\/title","op":"replace"},{"value":[{"kind":"identifier","text":"GFPSpannableOption"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPSpannableOption\/fragments"},{"op":"replace","value":[{"text":"GFPSpannableOption","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPSpannableOption\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBadgeOption\/title","value":"GFPBadgeOption"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBadgeOption\/fragments","value":[{"kind":"identifier","text":"GFPBadgeOption"}]},{"op":"replace","value":[{"kind":"identifier","text":"GFPBadgeOption"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBadgeOption\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}