{"metadata":{"role":"symbol","externalID":"c:@M@GFPSDK@objc(cs)GFPLabelOption(py)spnnableOption","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"spnnableOption"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPSpannableOption","kind":"typeIdentifier","text":"GFPSpannableOption"},{"text":"]?","kind":"text"}],"modules":[{"name":"GFPSDK"}],"symbolKind":"property","title":"spnnableOption","roleHeading":"Instance Property","navigatorTitle":[{"text":"spnnableOption","kind":"identifier"}]},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLabelOption\/spnnableOption","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"쇼핑광고 AttributeString 처리","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfplabeloption\/spnnableoption"]},{"paths":["\/documentation\/gfpsdk\/gfplabeloption\/spnnableoption"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"spnnableOption","kind":"identifier"},{"text":": [","kind":"text"},{"text":"GFPSpannableOption","preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPSpannableOption","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPSpannableOption","kind":"typeIdentifier"},{"text":"]?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLabelOption"]]},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPLabelOption":{"title":"GFPLabelOption","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLabelOption","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPLabelOption","kind":"identifier"}],"type":"topic","url":"\/documentation\/gfpsdk\/gfplabeloption","kind":"symbol","navigatorTitle":[{"text":"GFPLabelOption","kind":"identifier"}],"role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPLabelOption/spnnableOption":{"type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"spnnableOption","kind":"identifier"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPSpannableOption","text":"GFPSpannableOption","kind":"typeIdentifier"},{"text":"]?","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLabelOption\/spnnableOption","abstract":[{"type":"text","text":"쇼핑광고 AttributeString 처리"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"spnnableOption"}],"url":"\/documentation\/gfpsdk\/gfplabeloption\/spnnableoption","title":"spnnableOption"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPSpannableOption":{"title":"GFPSpannableOption","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPSpannableOption","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"GFPSpannableOption","kind":"identifier"}],"type":"topic","url":"\/documentation\/gfpsdk\/gfpspannableoption","kind":"symbol","navigatorTitle":[{"text":"GFPSpannableOption","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"spnnableOption","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"text":"spnnableOption","kind":"identifier"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<GFPSpannableOption *>"},{"kind":"text","text":" * "},{"text":"spnnableOption","kind":"identifier"},{"kind":"text","text":";"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLabelOption\/title","value":"GFPLabelOption","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLabelOption\/fragments","op":"replace","value":[{"text":"GFPLabelOption","kind":"identifier"}]},{"op":"replace","value":[{"text":"GFPLabelOption","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLabelOption\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLabelOption~1spnnableOption\/title","op":"replace","value":"spnnableOption"},{"value":[{"text":"spnnableOption","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLabelOption~1spnnableOption\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPSpannableOption\/title","value":"GFPSpannableOption"},{"op":"replace","value":[{"text":"GFPSpannableOption","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPSpannableOption\/fragments"},{"value":[{"kind":"identifier","text":"GFPSpannableOption"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPSpannableOption\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}