{"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpvideoadqoeinfo\/init(unknownwithprovider:)"]},{"paths":["\/documentation\/gfpsdk\/gfpvideoadqoeinfo\/init(unknownwithprovider:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdQoeInfo"]]},"sections":[],"metadata":{"modules":[{"name":"GFPSDK"}],"title":"init(unKnownWithProvider:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"unKnownWithProvider","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"initUnKnownWithProvider:","kind":"identifier"}],"roleHeading":"Initializer","symbolKind":"init","externalID":"c:objc(cs)GFPVideoAdQoeInfo(im)initUnKnownWithProvider:"},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdQoeInfo\/init(unKnownWithProvider:)","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"text":"unKnownWithProvider","kind":"externalParam"},{"kind":"text","text":" "},{"text":"provider","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdQoeInfo":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"GFPVideoAdQoeInfo"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdQoeInfo","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPVideoAdQoeInfo","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpvideoadqoeinfo","role":"symbol","kind":"symbol","title":"GFPVideoAdQoeInfo"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdQoeInfo/init(unKnownWithProvider:)":{"type":"topic","url":"\/documentation\/gfpsdk\/gfpvideoadqoeinfo\/init(unknownwithprovider:)","title":"init(unKnownWithProvider:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"unKnownWithProvider","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initUnKnownWithProvider:"}],"kind":"symbol","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdQoeInfo\/init(unKnownWithProvider:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"initUnKnownWithProvider:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initUnKnownWithProvider:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"text":") ","kind":"text"},{"text":"initUnKnownWithProvider:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"provider"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace"},{"value":"GFPVideoAdQoeInfo","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdQoeInfo\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdQoeInfo\/fragments","value":[{"kind":"identifier","text":"GFPVideoAdQoeInfo"}],"op":"replace"},{"value":[{"text":"GFPVideoAdQoeInfo","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdQoeInfo\/navigatorTitle"},{"op":"replace","value":"initUnKnownWithProvider:","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdQoeInfo~1init(unKnownWithProvider:)\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdQoeInfo~1init(unKnownWithProvider:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initUnKnownWithProvider:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}