{"abstract":[{"type":"text","text":"PIP 영역 상단의 닫기 버튼 클릭 시 호출됩니다."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdPIPDelegate"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/gfpsdk\/gfpvideoadpipdelegate\/videoadclosebtntapped(inpip:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpvideoadpipdelegate\/videoadclosebtntapped(inpip:)"]}],"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"videoAdCloseBtnTapped","kind":"identifier"},{"text":"(","kind":"text"},{"text":"inPIP","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GFPVideoAdManager","preciseIdentifier":"c:objc(cs)GFPVideoAdManager"},{"text":")","kind":"text"}],"roleHeading":"Instance Method","externalID":"c:objc(pl)GFPVideoAdPIPDelegate(im)videoAdCloseBtnTappedInPIP:","symbolKind":"method","navigatorTitle":[{"text":"videoAdCloseBtnTappedInPIP:","kind":"identifier"}],"modules":[{"name":"GFPSDK"}],"role":"symbol","title":"videoAdCloseBtnTapped(inPIP:)"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdPIPDelegate\/videoAdCloseBtnTapped(inPIP:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"optional","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"videoAdCloseBtnTapped"},{"kind":"text","text":"("},{"text":"inPIP","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"videoAdManager"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoAdManager","text":"GFPVideoAdManager","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager"},{"kind":"text","text":")"}]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"비디오 광고 매니저","type":"text"}]}],"name":"videoAdManager"}]}],"sections":[],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdManager":{"type":"topic","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager","role":"symbol","url":"\/documentation\/gfpsdk\/gfpvideoadmanager","title":"GFPVideoAdManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPVideoAdManager"}],"kind":"symbol","navigatorTitle":[{"text":"GFPVideoAdManager","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdPIPDelegate":{"navigatorTitle":[{"kind":"identifier","text":"GFPVideoAdPIPDelegate"}],"kind":"symbol","url":"\/documentation\/gfpsdk\/gfpvideoadpipdelegate","abstract":[],"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPVideoAdPIPDelegate"}],"title":"GFPVideoAdPIPDelegate","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdPIPDelegate","role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdPIPDelegate/videoAdCloseBtnTapped(inPIP:)":{"kind":"symbol","title":"videoAdCloseBtnTapped(inPIP:)","abstract":[{"type":"text","text":"PIP 영역 상단의 닫기 버튼 클릭 시 호출됩니다."}],"type":"topic","role":"symbol","url":"\/documentation\/gfpsdk\/gfpvideoadpipdelegate\/videoadclosebtntapped(inpip:)","navigatorTitle":[{"text":"videoAdCloseBtnTappedInPIP:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"videoAdCloseBtnTapped","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"inPIP"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)GFPVideoAdManager","kind":"typeIdentifier","text":"GFPVideoAdManager"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdPIPDelegate\/videoAdCloseBtnTapped(inPIP:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"videoAdCloseBtnTappedInPIP:","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"videoAdCloseBtnTappedInPIP:"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"videoAdCloseBtnTappedInPIP:"},{"kind":"text","text":"("},{"text":"GFPVideoAdManager","preciseIdentifier":"c:objc(cs)GFPVideoAdManager","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager"},{"kind":"text","text":" *) "},{"text":"videoAdManager","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"kind":"parameters","parameters":[{"name":"videoAdManager","content":[{"type":"paragraph","inlineContent":[{"text":"비디오 광고 매니저","type":"text"}]}]}]},"op":"replace","path":"\/primaryContentSections\/1"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManager\/title","op":"replace","value":"GFPVideoAdManager"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManager\/fragments","value":[{"kind":"identifier","text":"GFPVideoAdManager"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManager\/navigatorTitle","value":[{"text":"GFPVideoAdManager","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdPIPDelegate\/title","value":"GFPVideoAdPIPDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdPIPDelegate\/fragments","value":[{"text":"GFPVideoAdPIPDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdPIPDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"GFPVideoAdPIPDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdPIPDelegate~1videoAdCloseBtnTapped(inPIP:)\/title","op":"replace","value":"videoAdCloseBtnTappedInPIP:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"videoAdCloseBtnTappedInPIP:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdPIPDelegate~1videoAdCloseBtnTapped(inPIP:)\/fragments"}]}]}