{"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdPIPDelegate\/videoAdReturnBtnTapped(inPIP:)","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"text":"PIP 영역 상단의 리턴 버튼 클릭 시 호출됩니다.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"optional","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"videoAdReturnBtnTapped","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"inPIP"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"videoAdManager"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPVideoAdManager","text":"GFPVideoAdManager","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"]}]},{"parameters":[{"name":"videoAdManager","content":[{"inlineContent":[{"type":"text","text":"비디오 광고 매니저"}],"type":"paragraph"}]}],"kind":"parameters"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdPIPDelegate"]]},"metadata":{"externalID":"c:objc(pl)GFPVideoAdPIPDelegate(im)videoAdReturnBtnTappedInPIP:","modules":[{"name":"GFPSDK"}],"required":true,"roleHeading":"Instance Method","role":"symbol","title":"videoAdReturnBtnTapped(inPIP:)","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"videoAdReturnBtnTapped","kind":"identifier"},{"text":"(","kind":"text"},{"text":"inPIP","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoAdManager","text":"GFPVideoAdManager"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"videoAdReturnBtnTappedInPIP:","kind":"identifier"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpvideoadpipdelegate\/videoadreturnbtntapped(inpip:)"]},{"paths":["\/documentation\/gfpsdk\/gfpvideoadpipdelegate\/videoadreturnbtntapped(inpip:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdManager":{"type":"topic","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager","role":"symbol","url":"\/documentation\/gfpsdk\/gfpvideoadmanager","title":"GFPVideoAdManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPVideoAdManager"}],"kind":"symbol","navigatorTitle":[{"text":"GFPVideoAdManager","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdPIPDelegate":{"navigatorTitle":[{"kind":"identifier","text":"GFPVideoAdPIPDelegate"}],"kind":"symbol","url":"\/documentation\/gfpsdk\/gfpvideoadpipdelegate","abstract":[],"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPVideoAdPIPDelegate"}],"title":"GFPVideoAdPIPDelegate","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdPIPDelegate","role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdPIPDelegate/videoAdReturnBtnTapped(inPIP:)":{"abstract":[{"type":"text","text":"PIP 영역 상단의 리턴 버튼 클릭 시 호출됩니다."}],"title":"videoAdReturnBtnTapped(inPIP:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"videoAdReturnBtnTapped","kind":"identifier"},{"kind":"text","text":"("},{"text":"inPIP","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"GFPVideoAdManager","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoAdManager"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdPIPDelegate\/videoAdReturnBtnTapped(inPIP:)","url":"\/documentation\/gfpsdk\/gfpvideoadpipdelegate\/videoadreturnbtntapped(inpip:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"videoAdReturnBtnTappedInPIP:"}],"kind":"symbol","role":"symbol","required":true}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","value":"videoAdReturnBtnTappedInPIP:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"videoAdReturnBtnTappedInPIP:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"videoAdReturnBtnTappedInPIP:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPVideoAdManager","text":"GFPVideoAdManager","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"videoAdManager"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"비디오 광고 매니저"}]}],"name":"videoAdManager"}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManager\/title","op":"replace","value":"GFPVideoAdManager"},{"value":[{"text":"GFPVideoAdManager","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManager\/fragments"},{"op":"replace","value":[{"text":"GFPVideoAdManager","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManager\/navigatorTitle"},{"value":"GFPVideoAdPIPDelegate","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdPIPDelegate\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdPIPDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"GFPVideoAdPIPDelegate"}]},{"op":"replace","value":[{"kind":"identifier","text":"GFPVideoAdPIPDelegate"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdPIPDelegate\/navigatorTitle"},{"value":"videoAdReturnBtnTappedInPIP:","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdPIPDelegate~1videoAdReturnBtnTapped(inPIP:)\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdPIPDelegate~1videoAdReturnBtnTapped(inPIP:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"videoAdReturnBtnTappedInPIP:"}],"op":"replace"}]}]}