{"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPS2SAdClickDelegate\/openURLWith(_:landingHandler:)","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPS2SAdClickDelegate"]]},"metadata":{"modules":[{"name":"GFPSDK"}],"roleHeading":"Instance Method","role":"symbol","title":"openURLWith(_:landingHandler:)","navigatorTitle":[{"kind":"identifier","text":"openURLWith:landingHandler:"}],"symbolKind":"method","required":true,"externalID":"c:@M@GFPSDK@objc(pl)GFPS2SAdClickDelegate(im)openURLWith:landingHandler:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"openURLWith"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"landingHandler"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"GFPS2SAdLandingHandler","preciseIdentifier":"s:6GFPSDK22GFPS2SAdLandingHandlera"},{"text":")","kind":"text"}]},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"openURLWith","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"urlString","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"landingHandler"},{"text":": ","kind":"text"},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPS2SAdLandingHandler-7ff0","text":"GFPS2SAdLandingHandler","preciseIdentifier":"s:6GFPSDK22GFPS2SAdLandingHandlera"},{"kind":"text","text":")"}],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfps2sadclickdelegate\/openurlwith(_:landinghandler:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfps2sadclickdelegate\/openurlwith(_:landinghandler:)"]}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPS2SAdLandingHandler-7ff0":{"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"GFPS2SAdLandingHandler","kind":"identifier"}],"navigatorTitle":[{"text":"GFPS2SAdLandingHandler","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPS2SAdLandingHandler-7ff0","url":"\/documentation\/gfpsdk\/gfps2sadlandinghandler-7ff0","kind":"symbol","role":"symbol","abstract":[],"type":"topic","title":"GFPS2SAdLandingHandler"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPS2SAdClickDelegate":{"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPS2SAdClickDelegate"}],"kind":"symbol","navigatorTitle":[{"text":"GFPS2SAdClickDelegate","kind":"identifier"}],"abstract":[],"title":"GFPS2SAdClickDelegate","role":"symbol","url":"\/documentation\/gfpsdk\/gfps2sadclickdelegate","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPS2SAdClickDelegate","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPS2SAdClickDelegate/openURLWith(_:landingHandler:)":{"type":"topic","abstract":[],"title":"openURLWith(_:landingHandler:)","role":"symbol","url":"\/documentation\/gfpsdk\/gfps2sadclickdelegate\/openurlwith(_:landinghandler:)","navigatorTitle":[{"text":"openURLWith:landingHandler:","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPS2SAdClickDelegate\/openURLWith(_:landingHandler:)","required":true,"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"openURLWith"},{"kind":"text","text":"("},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"landingHandler","kind":"externalParam"},{"kind":"text","text":": "},{"text":"GFPS2SAdLandingHandler","kind":"typeIdentifier","preciseIdentifier":"s:6GFPSDK22GFPS2SAdLandingHandlera"},{"kind":"text","text":")"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"openURLWith:landingHandler:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"openURLWith:landingHandler:"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"openURLWith:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"urlString"},{"text":" ","kind":"text"},{"kind":"identifier","text":"landingHandler:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":" (^"},{"kind":"text","text":")("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"text":" ","kind":"text"},{"kind":"internalParam","text":""},{"text":")) ","kind":"text"},{"text":"landingHandler","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPS2SAdClickDelegate\/title","value":"GFPS2SAdClickDelegate","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPS2SAdClickDelegate\/fragments","value":[{"text":"GFPS2SAdClickDelegate","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPS2SAdClickDelegate\/navigatorTitle","value":[{"text":"GFPS2SAdClickDelegate","kind":"identifier"}]},{"value":"openURLWith:landingHandler:","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPS2SAdClickDelegate~1openURLWith(_:landingHandler:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"openURLWith:landingHandler:"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPS2SAdClickDelegate~1openURLWith(_:landingHandler:)\/fragments"}]}]}