{"kind":"symbol","metadata":{"title":"attachmentInfo","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"attachmentInfo","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdAttachmentInfo","text":"GFPAdAttachmentInfo"}],"roleHeading":"Instance Property","role":"symbol","modules":[{"name":"GFPSDK"}],"symbolKind":"property","externalID":"c:objc(cs)GFPAdAdaptor(py)attachmentInfo","navigatorTitle":[{"text":"attachmentInfo","kind":"identifier"}]},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAdaptor\/attachmentInfo","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"attachmentInfo"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)GFPAdAttachmentInfo","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAttachmentInfo","kind":"typeIdentifier","text":"GFPAdAttachmentInfo"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpadadaptor\/attachmentinfo"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gfpsdk\/gfpadadaptor\/attachmentinfo"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAdaptor"]]},"sections":[],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdAdaptor":{"navigatorTitle":[{"kind":"identifier","text":"GFPAdAdaptor"}],"title":"GFPAdAdaptor","url":"\/documentation\/gfpsdk\/gfpadadaptor","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAdaptor","abstract":[],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPAdAdaptor"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdAdaptor/attachmentInfo":{"navigatorTitle":[{"text":"attachmentInfo","kind":"identifier"}],"title":"attachmentInfo","abstract":[],"type":"topic","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAdaptor\/attachmentInfo","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"attachmentInfo","kind":"identifier"},{"kind":"text","text":": "},{"text":"GFPAdAttachmentInfo","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdAttachmentInfo"}],"url":"\/documentation\/gfpsdk\/gfpadadaptor\/attachmentinfo","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdAttachmentInfo":{"type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAttachmentInfo","abstract":[],"title":"GFPAdAttachmentInfo","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"GFPAdAttachmentInfo","kind":"identifier"}],"navigatorTitle":[{"text":"GFPAdAttachmentInfo","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpadattachmentinfo","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"value":"attachmentInfo","path":"\/metadata\/title","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"attachmentInfo"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"atomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"text":"readwrite","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)GFPAdAttachmentInfo","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAttachmentInfo","kind":"typeIdentifier","text":"GFPAdAttachmentInfo"},{"text":" * ","kind":"text"},{"text":"attachmentInfo","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"value":"GFPAdAdaptor","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdaptor\/title","op":"replace"},{"value":[{"kind":"identifier","text":"GFPAdAdaptor"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdaptor\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdaptor\/navigatorTitle","value":[{"text":"GFPAdAdaptor","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdaptor~1attachmentInfo\/title","value":"attachmentInfo","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdaptor~1attachmentInfo\/fragments","value":[{"text":"attachmentInfo","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAttachmentInfo\/title","value":"GFPAdAttachmentInfo","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"GFPAdAttachmentInfo"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAttachmentInfo\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAttachmentInfo\/navigatorTitle","value":[{"text":"GFPAdAttachmentInfo","kind":"identifier"}]}]}]}