{"metadata":{"symbolKind":"method","modules":[{"name":"GFPSDK"}],"roleHeading":"Instance Method","title":"loadAd(completionHandler:timeoutMillis:)","externalID":"c:objc(cs)GFPAdAdaptor(im)loadAdWithCompletionHandler:timeoutMillis:","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadAd"},{"text":"(","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:GFPAdAdapting.h@T@GFPAdAdaptorLoadCompletionHandler","text":"GFPAdAdaptorLoadCompletionHandler","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"timeoutMillis","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?)"}],"navigatorTitle":[{"text":"loadAdWithCompletionHandler:timeoutMillis:","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"loadAd","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPAdAdaptorLoadCompletionHandler","preciseIdentifier":"c:GFPAdAdapting.h@T@GFPAdAdaptorLoadCompletionHandler","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAdaptorLoadCompletionHandler"},{"kind":"text","text":", "},{"text":"timeoutMillis","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"kind":"text","text":"?)"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpadadaptor\/loadad(completionhandler:timeoutmillis:)"]},{"paths":["\/documentation\/gfpsdk\/gfpadadaptor\/loadad(completionhandler:timeoutmillis:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAdaptor"]]},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAdaptor\/loadAd(completionHandler:timeoutMillis:)","interfaceLanguage":"swift"},"sections":[],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdAdaptor/loadAd(completionHandler:timeoutMillis:)":{"abstract":[],"url":"\/documentation\/gfpsdk\/gfpadadaptor\/loadad(completionhandler:timeoutmillis:)","title":"loadAd(completionHandler:timeoutMillis:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"loadAd","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"completionHandler"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"GFPAdAdaptorLoadCompletionHandler","preciseIdentifier":"c:GFPAdAdapting.h@T@GFPAdAdaptorLoadCompletionHandler"},{"kind":"text","text":", "},{"text":"timeoutMillis","kind":"externalParam"},{"kind":"text","text":": "},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?)"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"loadAdWithCompletionHandler:timeoutMillis:"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAdaptor\/loadAd(completionHandler:timeoutMillis:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdAdaptor":{"navigatorTitle":[{"kind":"identifier","text":"GFPAdAdaptor"}],"title":"GFPAdAdaptor","url":"\/documentation\/gfpsdk\/gfpadadaptor","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAdaptor","abstract":[],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPAdAdaptor"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdAdaptorLoadCompletionHandler":{"navigatorTitle":[{"kind":"identifier","text":"GFPAdAdaptorLoadCompletionHandler"}],"url":"\/documentation\/gfpsdk\/gfpadadaptorloadcompletionhandler","abstract":[],"fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"GFPAdAdaptorLoadCompletionHandler","kind":"identifier"}],"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAdaptorLoadCompletionHandler","title":"GFPAdAdaptorLoadCompletionHandler"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"loadAdWithCompletionHandler:timeoutMillis:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"loadAdWithCompletionHandler:timeoutMillis:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"loadAdWithCompletionHandler:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"void (^)(GFPError *, GFPLoadEvent *, GFPEventExtraInfo *)","kind":"typeIdentifier","preciseIdentifier":"c:BFv(#*$@M@NaverAdsServices@objc(cs)GFPError#*$objc(cs)GFPLoadEvent#*$objc(cs)GFPEventExtraInfo)"},{"kind":"text","text":") "},{"text":"completionHandler","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"timeoutMillis:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"timeoutMillis"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"loadAdWithCompletionHandler:timeoutMillis:","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdaptor~1loadAd(completionHandler:timeoutMillis:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"loadAdWithCompletionHandler:timeoutMillis:"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdaptor~1loadAd(completionHandler:timeoutMillis:)\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdaptor\/title","value":"GFPAdAdaptor","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdaptor\/fragments","value":[{"text":"GFPAdAdaptor","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdaptor\/navigatorTitle","value":[{"text":"GFPAdAdaptor","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdaptorLoadCompletionHandler\/title","value":"GFPAdAdaptorLoadCompletionHandler","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdaptorLoadCompletionHandler\/fragments","value":[{"kind":"identifier","text":"GFPAdAdaptorLoadCompletionHandler"}]},{"op":"replace","value":[{"kind":"identifier","text":"GFPAdAdaptorLoadCompletionHandler"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdaptorLoadCompletionHandler\/navigatorTitle"}]}]}