{"variants":[{"paths":["\/documentation\/gfpsdk\/gfpadadaptor\/markedattachedonsuperview()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gfpsdk\/gfpadadaptor\/markedattachedonsuperview()"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAdaptor"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"markedAttachedOnSuperView","kind":"identifier"},{"text":"()","kind":"text"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAdaptor\/markedAttachedOnSuperView()"},"kind":"symbol","metadata":{"modules":[{"name":"GFPSDK"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"markedAttachedOnSuperView","kind":"identifier"},{"kind":"text","text":"()"}],"navigatorTitle":[{"text":"markedAttachedOnSuperView","kind":"identifier"}],"symbolKind":"method","roleHeading":"Instance Method","externalID":"c:objc(cs)GFPAdAdaptor(im)markedAttachedOnSuperView","title":"markedAttachedOnSuperView()","role":"symbol"},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdAdaptor/markedAttachedOnSuperView()":{"navigatorTitle":[{"text":"markedAttachedOnSuperView","kind":"identifier"}],"title":"markedAttachedOnSuperView()","abstract":[],"type":"topic","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAdaptor\/markedAttachedOnSuperView()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"markedAttachedOnSuperView","kind":"identifier"},{"text":"()","kind":"text"}],"url":"\/documentation\/gfpsdk\/gfpadadaptor\/markedattachedonsuperview()","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdAdaptor":{"navigatorTitle":[{"kind":"identifier","text":"GFPAdAdaptor"}],"title":"GFPAdAdaptor","url":"\/documentation\/gfpsdk\/gfpadadaptor","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAdaptor","abstract":[],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPAdAdaptor"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","value":"markedAttachedOnSuperView","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"text":"- ","kind":"text"},{"text":"markedAttachedOnSuperView","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"text":"markedAttachedOnSuperView","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdaptor~1markedAttachedOnSuperView()\/title","value":"markedAttachedOnSuperView"},{"value":[{"text":"- ","kind":"text"},{"text":"markedAttachedOnSuperView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdaptor~1markedAttachedOnSuperView()\/fragments"},{"value":"GFPAdAdaptor","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdaptor\/title"},{"op":"replace","value":[{"text":"GFPAdAdaptor","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdaptor\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdaptor\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"GFPAdAdaptor"}]}]}]}