{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpadadaptor\/starttrackingrenderedimp(with:completionhandler:)"]},{"paths":["\/documentation\/gfpsdk\/gfpadadaptor\/starttrackingrenderedimp(with:completionhandler:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAdaptor"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAdaptor\/startTrackingRenderedImp(with:completionHandler:)"},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"kind":"symbol","metadata":{"roleHeading":"Instance Method","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"startTrackingRenderedImpWithView:completionHandler:"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"startTrackingRenderedImp"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"},{"text":", ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"kind":"text","text":": ("},{"text":"GFPImpressionTrackingTarget","preciseIdentifier":"c:objc(cs)GFPImpressionTrackingTarget","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}],"modules":[{"name":"GFPSDK"}],"symbolKind":"method","externalID":"c:objc(cs)GFPAdAdaptor(im)startTrackingRenderedImpWithView:completionHandler:","title":"startTrackingRenderedImp(with:completionHandler:)"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"startTrackingRenderedImp","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"viewToBeTracked"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"text":"@escaping","kind":"keyword"},{"text":" (","kind":"text"},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionTrackingTarget","text":"GFPImpressionTrackingTarget","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPImpressionTrackingTarget"},{"kind":"text","text":") -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"languages":["swift"]},{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"startTrackingRenderedImp"},{"kind":"text","text":"("},{"text":"with","kind":"externalParam"},{"kind":"text","text":" "},{"text":"viewToBeTracked","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"},{"kind":"text","text":") "},{"kind":"keyword","text":"async"},{"text":" -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPImpressionTrackingTarget","text":"GFPImpressionTrackingTarget","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionTrackingTarget"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPImpressionTrackingTarget":{"navigatorTitle":[{"text":"GFPImpressionTrackingTarget","kind":"identifier"}],"title":"GFPImpressionTrackingTarget","url":"\/documentation\/gfpsdk\/gfpimpressiontrackingtarget","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionTrackingTarget","role":"symbol","type":"topic","kind":"symbol","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPImpressionTrackingTarget","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdAdaptor":{"navigatorTitle":[{"kind":"identifier","text":"GFPAdAdaptor"}],"title":"GFPAdAdaptor","url":"\/documentation\/gfpsdk\/gfpadadaptor","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAdaptor","abstract":[],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPAdAdaptor"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdAdaptor/startTrackingRenderedImp(with:completionHandler:)":{"abstract":[],"url":"\/documentation\/gfpsdk\/gfpadadaptor\/starttrackingrenderedimp(with:completionhandler:)","title":"startTrackingRenderedImp(with:completionHandler:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"startTrackingRenderedImp","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"with"},{"text":": ","kind":"text"},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":", "},{"text":"completionHandler","kind":"externalParam"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"GFPImpressionTrackingTarget","preciseIdentifier":"c:objc(cs)GFPImpressionTrackingTarget"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"role":"symbol","navigatorTitle":[{"text":"startTrackingRenderedImpWithView:completionHandler:","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAdaptor\/startTrackingRenderedImp(with:completionHandler:)"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"startTrackingRenderedImpWithView:completionHandler:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startTrackingRenderedImpWithView:completionHandler:"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"startTrackingRenderedImpWithView:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIView","text":"UIView","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"viewToBeTracked"},{"text":" ","kind":"text"},{"text":"completionHandler:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":" (^"},{"text":")(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPImpressionTrackingTarget","text":"GFPImpressionTrackingTarget","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionTrackingTarget"},{"kind":"text","text":" * "},{"text":"target","kind":"internalParam"},{"kind":"text","text":")) "},{"kind":"internalParam","text":"completionHandler"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"GFPImpressionTrackingTarget","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTrackingTarget\/title","op":"replace"},{"op":"replace","value":[{"text":"GFPImpressionTrackingTarget","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTrackingTarget\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTrackingTarget\/navigatorTitle","value":[{"text":"GFPImpressionTrackingTarget","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdaptor\/title","value":"GFPAdAdaptor"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdaptor\/fragments","value":[{"kind":"identifier","text":"GFPAdAdaptor"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdaptor\/navigatorTitle","value":[{"kind":"identifier","text":"GFPAdAdaptor"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdaptor~1startTrackingRenderedImp(with:completionHandler:)\/title","value":"startTrackingRenderedImpWithView:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdaptor~1startTrackingRenderedImp(with:completionHandler:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"startTrackingRenderedImpWithView:completionHandler:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}