{"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"trackingAttachedOnSuperView","kind":"identifier"},{"kind":"text","text":"("},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"GFPEventExtraInfo","preciseIdentifier":"c:objc(cs)GFPEventExtraInfo"},{"kind":"text","text":")"}],"role":"symbol","navigatorTitle":[{"text":"trackingAttachedOnSuperViewWith:","kind":"identifier"}],"roleHeading":"Instance Method","externalID":"c:objc(cs)GFPAdAdaptor(im)trackingAttachedOnSuperViewWith:","symbolKind":"method","title":"trackingAttachedOnSuperView(with:)","modules":[{"name":"GFPSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAdaptor"]]},"variants":[{"paths":["\/documentation\/gfpsdk\/gfpadadaptor\/trackingattachedonsuperview(with:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gfpsdk\/gfpadadaptor\/trackingattachedonsuperview(with:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"trackingAttachedOnSuperView"},{"kind":"text","text":"("},{"text":"with","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"aExtraInfo","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"GFPEventExtraInfo","preciseIdentifier":"c:objc(cs)GFPEventExtraInfo","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPEventExtraInfo"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAdaptor\/trackingAttachedOnSuperView(with:)"},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdAdaptor":{"navigatorTitle":[{"kind":"identifier","text":"GFPAdAdaptor"}],"title":"GFPAdAdaptor","url":"\/documentation\/gfpsdk\/gfpadadaptor","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAdaptor","abstract":[],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPAdAdaptor"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdAdaptor/trackingAttachedOnSuperView(with:)":{"navigatorTitle":[{"text":"trackingAttachedOnSuperViewWith:","kind":"identifier"}],"title":"trackingAttachedOnSuperView(with:)","abstract":[],"type":"topic","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAdaptor\/trackingAttachedOnSuperView(with:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackingAttachedOnSuperView"},{"kind":"text","text":"("},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPEventExtraInfo","text":"GFPEventExtraInfo"},{"text":")","kind":"text"}],"url":"\/documentation\/gfpsdk\/gfpadadaptor\/trackingattachedonsuperview(with:)","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPEventExtraInfo":{"navigatorTitle":[{"text":"GFPEventExtraInfo","kind":"identifier"}],"role":"symbol","title":"GFPEventExtraInfo","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPEventExtraInfo"}],"type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPEventExtraInfo","abstract":[],"url":"\/documentation\/gfpsdk\/gfpeventextrainfo"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"trackingAttachedOnSuperViewWith:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"trackingAttachedOnSuperViewWith:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"text":"trackingAttachedOnSuperViewWith:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"GFPEventExtraInfo","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPEventExtraInfo","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPEventExtraInfo"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"aExtraInfo"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"value":"GFPAdAdaptor","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdaptor\/title"},{"value":[{"kind":"identifier","text":"GFPAdAdaptor"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdaptor\/fragments"},{"value":[{"text":"GFPAdAdaptor","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdaptor\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdaptor~1trackingAttachedOnSuperView(with:)\/title","value":"trackingAttachedOnSuperViewWith:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdaptor~1trackingAttachedOnSuperView(with:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"trackingAttachedOnSuperViewWith:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPEventExtraInfo\/title","value":"GFPEventExtraInfo"},{"op":"replace","value":[{"text":"GFPEventExtraInfo","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPEventExtraInfo\/fragments"},{"value":[{"text":"GFPEventExtraInfo","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPEventExtraInfo\/navigatorTitle"}]}]}