{"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAdaptor"]]},"sections":[],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpadadaptor\/viewableimpinfo"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpadadaptor\/viewableimpinfo"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"viewableImpInfo","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdImpressionInfo","kind":"typeIdentifier","text":"GFPAdImpressionInfo","preciseIdentifier":"c:objc(cs)GFPAdImpressionInfo"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAdaptor\/viewableImpInfo","interfaceLanguage":"swift"},"metadata":{"externalID":"c:objc(cs)GFPAdAdaptor(py)viewableImpInfo","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"viewableImpInfo","kind":"identifier"},{"text":": ","kind":"text"},{"text":"GFPAdImpressionInfo","preciseIdentifier":"c:objc(cs)GFPAdImpressionInfo","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"viewableImpInfo","kind":"identifier"}],"modules":[{"name":"GFPSDK"}],"symbolKind":"property","role":"symbol","roleHeading":"Instance Property","title":"viewableImpInfo"},"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdAdaptor":{"navigatorTitle":[{"kind":"identifier","text":"GFPAdAdaptor"}],"title":"GFPAdAdaptor","url":"\/documentation\/gfpsdk\/gfpadadaptor","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAdaptor","abstract":[],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPAdAdaptor"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdImpressionInfo":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"GFPAdImpressionInfo","kind":"identifier"}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"GFPAdImpressionInfo","kind":"identifier"}],"abstract":[{"type":"text","text":"GFPAdImpressionInfo"}],"role":"symbol","title":"GFPAdImpressionInfo","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdImpressionInfo","url":"\/documentation\/gfpsdk\/gfpadimpressioninfo"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdAdaptor/viewableImpInfo":{"abstract":[],"url":"\/documentation\/gfpsdk\/gfpadadaptor\/viewableimpinfo","title":"viewableImpInfo","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"viewableImpInfo","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdImpressionInfo","text":"GFPAdImpressionInfo"}],"role":"symbol","navigatorTitle":[{"text":"viewableImpInfo","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAdaptor\/viewableImpInfo"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","value":"viewableImpInfo","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"viewableImpInfo"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"text":"readwrite","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdImpressionInfo","kind":"typeIdentifier","text":"GFPAdImpressionInfo","preciseIdentifier":"c:objc(cs)GFPAdImpressionInfo"},{"kind":"text","text":" * "},{"kind":"identifier","text":"viewableImpInfo"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdaptor\/title","op":"replace","value":"GFPAdAdaptor"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdaptor\/fragments","value":[{"text":"GFPAdAdaptor","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdaptor\/navigatorTitle","value":[{"text":"GFPAdAdaptor","kind":"identifier"}]},{"op":"replace","value":"GFPAdImpressionInfo","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdImpressionInfo\/title"},{"value":[{"text":"GFPAdImpressionInfo","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdImpressionInfo\/fragments"},{"value":[{"kind":"identifier","text":"GFPAdImpressionInfo"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdImpressionInfo\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdaptor~1viewableImpInfo\/title","value":"viewableImpInfo"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdaptor~1viewableImpInfo\/fragments","value":[{"kind":"identifier","text":"viewableImpInfo"}],"op":"replace"}]}]}