{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpcreativetype\/nonlinear"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpcreativetype\/nonlinear"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPCreativeType\/nonLinear"},"sections":[],"metadata":{"modules":[{"name":"GFPSDK"}],"role":"symbol","roleHeading":"Type Property","title":"nonLinear","externalID":"c:@E@GFPCreativeType@GFPCreativeNonLinear","symbolKind":"property","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"nonLinear"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"GFPCreativeType","preciseIdentifier":"c:@E@GFPCreativeType"}],"navigatorTitle":[{"kind":"identifier","text":"GFPCreativeNonLinear"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nonLinear","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"GFPCreativeType","preciseIdentifier":"c:@E@GFPCreativeType","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPCreativeType"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPCreativeType"]]},"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPCreativeType/nonLinear":{"abstract":[],"url":"\/documentation\/gfpsdk\/gfpcreativetype\/nonlinear","role":"symbol","title":"nonLinear","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPCreativeType\/nonLinear","type":"topic","navigatorTitle":[{"text":"GFPCreativeNonLinear","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"nonLinear"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@GFPCreativeType","text":"GFPCreativeType","kind":"typeIdentifier"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPCreativeType":{"kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPCreativeType","url":"\/documentation\/gfpsdk\/gfpcreativetype","abstract":[],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPCreativeType","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"GFPCreativeType"}],"role":"symbol","type":"topic","title":"GFPCreativeType"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"value":"GFPCreativeNonLinear","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GFPCreativeNonLinear"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"GFPCreativeNonLinear"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","value":"GFPCreativeNonLinear","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPCreativeType~1nonLinear\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPCreativeType~1nonLinear\/fragments","value":[{"kind":"identifier","text":"GFPCreativeNonLinear"}]},{"value":"GFPCreativeType","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPCreativeType\/title"},{"value":[{"kind":"identifier","text":"GFPCreativeType"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPCreativeType\/fragments"},{"value":[{"text":"GFPCreativeType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPCreativeType\/navigatorTitle"}]}]}