{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeContextPresentable\/renderingSetting"},"sections":[],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"symbolKind":"property","externalID":"c:objc(pl)GFPNativeContextPresentable(py)renderingSetting","modules":[{"name":"GFPSDK"}],"navigatorTitle":[{"text":"renderingSetting","kind":"identifier"}],"title":"renderingSetting","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"renderingSetting"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPNativeAdRenderingSetting","text":"GFPNativeAdRenderingSetting"}],"role":"symbol","required":true},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"renderingSetting","kind":"identifier"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdRenderingSetting","text":"GFPNativeAdRenderingSetting","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPNativeAdRenderingSetting"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpnativecontextpresentable\/renderingsetting"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gfpsdk\/gfpnativecontextpresentable\/renderingsetting"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeContextPresentable"]]},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeContextPresentable":{"role":"symbol","title":"GFPNativeContextPresentable","url":"\/documentation\/gfpsdk\/gfpnativecontextpresentable","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeContextPresentable","navigatorTitle":[{"text":"GFPNativeContextPresentable","kind":"identifier"}],"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPNativeContextPresentable","kind":"identifier"}],"abstract":[],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdRenderingSetting":{"abstract":[],"kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdRenderingSetting","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPNativeAdRenderingSetting"}],"url":"\/documentation\/gfpsdk\/gfpnativeadrenderingsetting","title":"GFPNativeAdRenderingSetting","navigatorTitle":[{"kind":"identifier","text":"GFPNativeAdRenderingSetting"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeContextPresentable/renderingSetting":{"url":"\/documentation\/gfpsdk\/gfpnativecontextpresentable\/renderingsetting","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"renderingSetting","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPNativeAdRenderingSetting","text":"GFPNativeAdRenderingSetting","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeContextPresentable\/renderingSetting","kind":"symbol","navigatorTitle":[{"text":"renderingSetting","kind":"identifier"}],"required":true,"role":"symbol","title":"renderingSetting","type":"topic","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","value":"renderingSetting","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"text":"renderingSetting","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"GFPNativeAdRenderingSetting","preciseIdentifier":"c:objc(cs)GFPNativeAdRenderingSetting","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdRenderingSetting"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"renderingSetting"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeContextPresentable\/title","op":"replace","value":"GFPNativeContextPresentable"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeContextPresentable\/fragments","value":[{"text":"GFPNativeContextPresentable","kind":"identifier"}],"op":"replace"},{"value":[{"text":"GFPNativeContextPresentable","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeContextPresentable\/navigatorTitle","op":"replace"},{"value":"GFPNativeAdRenderingSetting","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdRenderingSetting\/title","op":"replace"},{"op":"replace","value":[{"text":"GFPNativeAdRenderingSetting","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdRenderingSetting\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdRenderingSetting\/navigatorTitle","value":[{"text":"GFPNativeAdRenderingSetting","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeContextPresentable~1renderingSetting\/title","value":"renderingSetting"},{"value":[{"text":"renderingSetting","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeContextPresentable~1renderingSetting\/fragments","op":"replace"}]}]}