{"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdManagerDelegate"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"rewardedAdManagerDidPresentDefault","kind":"identifier"},{"kind":"text","text":"("},{"text":"inAppBrowser","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"manager"},{"kind":"text","text":": "},{"text":"GFPRewardedAdManager","preciseIdentifier":"c:objc(cs)GFPRewardedAdManager","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdManager","kind":"typeIdentifier"},{"kind":"text","text":")"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfprewardedadmanagerdelegate\/rewardedadmanagerdidpresentdefault(inappbrowser:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfprewardedadmanagerdelegate\/rewardedadmanagerdidpresentdefault(inappbrowser:)"]}],"kind":"symbol","metadata":{"externalID":"c:objc(pl)GFPRewardedAdManagerDelegate(im)rewardedAdManagerDidPresentDefaultInAppBrowser:","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"rewardedAdManagerDidPresentDefault","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"inAppBrowser"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GFPRewardedAdManager","preciseIdentifier":"c:objc(cs)GFPRewardedAdManager"},{"kind":"text","text":")"}],"modules":[{"name":"GFPSDK"}],"required":true,"title":"rewardedAdManagerDidPresentDefault(inAppBrowser:)","navigatorTitle":[{"text":"rewardedAdManagerDidPresentDefaultInAppBrowser:","kind":"identifier"}],"symbolKind":"method","role":"symbol","roleHeading":"Instance Method"},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdManagerDelegate\/rewardedAdManagerDidPresentDefault(inAppBrowser:)","interfaceLanguage":"swift"},"sections":[],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRewardedAdManagerDelegate/rewardedAdManagerDidPresentDefault(inAppBrowser:)":{"required":true,"url":"\/documentation\/gfpsdk\/gfprewardedadmanagerdelegate\/rewardedadmanagerdidpresentdefault(inappbrowser:)","navigatorTitle":[{"kind":"identifier","text":"rewardedAdManagerDidPresentDefaultInAppBrowser:"}],"abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rewardedAdManagerDidPresentDefault","kind":"identifier"},{"kind":"text","text":"("},{"text":"inAppBrowser","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"GFPRewardedAdManager","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPRewardedAdManager"},{"text":")","kind":"text"}],"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdManagerDelegate\/rewardedAdManagerDidPresentDefault(inAppBrowser:)","title":"rewardedAdManagerDidPresentDefault(inAppBrowser:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRewardedAdManagerDelegate":{"title":"GFPRewardedAdManagerDelegate","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdManagerDelegate","url":"\/documentation\/gfpsdk\/gfprewardedadmanagerdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPRewardedAdManagerDelegate"}],"kind":"symbol","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPRewardedAdManagerDelegate"}],"type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRewardedAdManager":{"title":"GFPRewardedAdManager","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdManager","url":"\/documentation\/gfpsdk\/gfprewardedadmanager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPRewardedAdManager"}],"kind":"symbol","abstract":[],"role":"symbol","navigatorTitle":[{"text":"GFPRewardedAdManager","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"rewardedAdManagerDidPresentDefaultInAppBrowser:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"rewardedAdManagerDidPresentDefaultInAppBrowser:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"text":"rewardedAdManagerDidPresentDefaultInAppBrowser:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPRewardedAdManager","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdManager","text":"GFPRewardedAdManager"},{"text":" *) ","kind":"text"},{"text":"manager","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdManagerDelegate~1rewardedAdManagerDidPresentDefault(inAppBrowser:)\/title","value":"rewardedAdManagerDidPresentDefaultInAppBrowser:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"rewardedAdManagerDidPresentDefaultInAppBrowser:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdManagerDelegate~1rewardedAdManagerDidPresentDefault(inAppBrowser:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdManagerDelegate\/title","value":"GFPRewardedAdManagerDelegate"},{"value":[{"text":"GFPRewardedAdManagerDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdManagerDelegate\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdManagerDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"GFPRewardedAdManagerDelegate"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdManager\/title","value":"GFPRewardedAdManager","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdManager\/fragments","value":[{"kind":"identifier","text":"GFPRewardedAdManager"}]},{"value":[{"kind":"identifier","text":"GFPRewardedAdManager"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdManager\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}