{"metadata":{"externalID":"c:objc(pl)GFPRewardedAdManagerDelegate(im)rewardedAdManagerDidDismissDefaultInAppBrowser:","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"rewardedAdManagerDidDismissDefault","kind":"identifier"},{"text":"(","kind":"text"},{"text":"inAppBrowser","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"GFPRewardedAdManager","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPRewardedAdManager"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"rewardedAdManagerDidDismissDefaultInAppBrowser:"}],"modules":[{"name":"GFPSDK"}],"symbolKind":"method","role":"symbol","roleHeading":"Instance Method","title":"rewardedAdManagerDidDismissDefault(inAppBrowser:)"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdManagerDelegate\/rewardedAdManagerDidDismissDefault(inAppBrowser:)"},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"optional","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"rewardedAdManagerDidDismissDefault"},{"text":"(","kind":"text"},{"text":"inAppBrowser","kind":"externalParam"},{"kind":"text","text":" "},{"text":"manager","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdManager","text":"GFPRewardedAdManager","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPRewardedAdManager"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdManagerDelegate"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/gfpsdk\/gfprewardedadmanagerdelegate\/rewardedadmanagerdiddismissdefault(inappbrowser:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gfpsdk\/gfprewardedadmanagerdelegate\/rewardedadmanagerdiddismissdefault(inappbrowser:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRewardedAdManagerDelegate":{"title":"GFPRewardedAdManagerDelegate","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdManagerDelegate","url":"\/documentation\/gfpsdk\/gfprewardedadmanagerdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPRewardedAdManagerDelegate"}],"kind":"symbol","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPRewardedAdManagerDelegate"}],"type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRewardedAdManager":{"title":"GFPRewardedAdManager","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdManager","url":"\/documentation\/gfpsdk\/gfprewardedadmanager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPRewardedAdManager"}],"kind":"symbol","abstract":[],"role":"symbol","navigatorTitle":[{"text":"GFPRewardedAdManager","kind":"identifier"}],"type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRewardedAdManagerDelegate/rewardedAdManagerDidDismissDefault(inAppBrowser:)":{"role":"symbol","navigatorTitle":[{"text":"rewardedAdManagerDidDismissDefaultInAppBrowser:","kind":"identifier"}],"type":"topic","title":"rewardedAdManagerDidDismissDefault(inAppBrowser:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"rewardedAdManagerDidDismissDefault","kind":"identifier"},{"kind":"text","text":"("},{"text":"inAppBrowser","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"GFPRewardedAdManager","preciseIdentifier":"c:objc(cs)GFPRewardedAdManager","kind":"typeIdentifier"},{"kind":"text","text":")"}],"url":"\/documentation\/gfpsdk\/gfprewardedadmanagerdelegate\/rewardedadmanagerdiddismissdefault(inappbrowser:)","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdManagerDelegate\/rewardedAdManagerDidDismissDefault(inAppBrowser:)"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"rewardedAdManagerDidDismissDefaultInAppBrowser:","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"rewardedAdManagerDidDismissDefaultInAppBrowser:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"rewardedAdManagerDidDismissDefaultInAppBrowser:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GFPRewardedAdManager","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdManager","preciseIdentifier":"c:objc(cs)GFPRewardedAdManager"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"manager"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace"},{"value":"GFPRewardedAdManagerDelegate","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdManagerDelegate\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdManagerDelegate\/fragments","op":"replace","value":[{"text":"GFPRewardedAdManagerDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdManagerDelegate\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"GFPRewardedAdManagerDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdManager\/title","value":"GFPRewardedAdManager"},{"value":[{"text":"GFPRewardedAdManager","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdManager\/fragments"},{"value":[{"text":"GFPRewardedAdManager","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdManager\/navigatorTitle"},{"op":"replace","value":"rewardedAdManagerDidDismissDefaultInAppBrowser:","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdManagerDelegate~1rewardedAdManagerDidDismissDefault(inAppBrowser:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rewardedAdManagerDidDismissDefaultInAppBrowser:"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdManagerDelegate~1rewardedAdManagerDidDismissDefault(inAppBrowser:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}