{"metadata":{"title":"rewardedAdManager(_:didClose:)","symbolKind":"method","modules":[{"name":"GFPSDK"}],"role":"symbol","externalID":"c:objc(pl)GFPRewardedAdManagerDelegate(im)rewardedAdManager:didCloseAd:","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"rewardedAdManager","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPRewardedAdManager","kind":"typeIdentifier","text":"GFPRewardedAdManager"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didClose"},{"text":": ","kind":"text"},{"text":"GFPRewardedAd","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPRewardedAd"},{"kind":"text","text":")"}],"required":true,"navigatorTitle":[{"text":"rewardedAdManager:didCloseAd:","kind":"identifier"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdManagerDelegate\/rewardedAdManager(_:didClose:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rewardedAdManager"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"manager","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdManager","text":"GFPRewardedAdManager","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPRewardedAdManager"},{"kind":"text","text":", "},{"text":"didClose","kind":"externalParam"},{"kind":"text","text":" "},{"text":"rewardedAd","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPRewardedAd","text":"GFPRewardedAd","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAd"},{"text":")","kind":"text"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfprewardedadmanagerdelegate\/rewardedadmanager(_:didclose:)"]},{"paths":["\/documentation\/gfpsdk\/gfprewardedadmanagerdelegate\/rewardedadmanager(_:didclose:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdManagerDelegate"]]},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRewardedAdManagerDelegate/rewardedAdManager(_:didClose:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rewardedAdManager"},{"kind":"text","text":"("},{"text":"GFPRewardedAdManager","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPRewardedAdManager"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didClose"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPRewardedAd","text":"GFPRewardedAd"},{"text":")","kind":"text"}],"title":"rewardedAdManager(_:didClose:)","navigatorTitle":[{"kind":"identifier","text":"rewardedAdManager:didCloseAd:"}],"url":"\/documentation\/gfpsdk\/gfprewardedadmanagerdelegate\/rewardedadmanager(_:didclose:)","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdManagerDelegate\/rewardedAdManager(_:didClose:)","role":"symbol","type":"topic","kind":"symbol","abstract":[],"required":true},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRewardedAdManager":{"title":"GFPRewardedAdManager","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdManager","url":"\/documentation\/gfpsdk\/gfprewardedadmanager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPRewardedAdManager"}],"kind":"symbol","abstract":[],"role":"symbol","navigatorTitle":[{"text":"GFPRewardedAdManager","kind":"identifier"}],"type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRewardedAdManagerDelegate":{"title":"GFPRewardedAdManagerDelegate","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdManagerDelegate","url":"\/documentation\/gfpsdk\/gfprewardedadmanagerdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPRewardedAdManagerDelegate"}],"kind":"symbol","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPRewardedAdManagerDelegate"}],"type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRewardedAd":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAd","url":"\/documentation\/gfpsdk\/gfprewardedad","navigatorTitle":[{"kind":"identifier","text":"GFPRewardedAd"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPRewardedAd","kind":"identifier"}],"kind":"symbol","abstract":[],"type":"topic","title":"GFPRewardedAd","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"rewardedAdManager:didCloseAd:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"rewardedAdManager:didCloseAd:","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"rewardedAdManager:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPRewardedAdManager","text":"GFPRewardedAdManager","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdManager"},{"kind":"text","text":" *) "},{"text":"manager","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didCloseAd:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAd","text":"GFPRewardedAd","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPRewardedAd"},{"kind":"text","text":" *) "},{"text":"rewardedAd","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdManagerDelegate~1rewardedAdManager(_:didClose:)\/title","value":"rewardedAdManager:didCloseAd:"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdManagerDelegate~1rewardedAdManager(_:didClose:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"rewardedAdManager:didCloseAd:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdManager\/title","value":"GFPRewardedAdManager"},{"value":[{"text":"GFPRewardedAdManager","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdManager\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdManager\/navigatorTitle","op":"replace","value":[{"text":"GFPRewardedAdManager","kind":"identifier"}]},{"value":"GFPRewardedAdManagerDelegate","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdManagerDelegate\/title"},{"op":"replace","value":[{"text":"GFPRewardedAdManagerDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdManagerDelegate\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdManagerDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"GFPRewardedAdManagerDelegate"}]},{"value":"GFPRewardedAd","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAd\/title"},{"op":"replace","value":[{"kind":"identifier","text":"GFPRewardedAd"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAd\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAd\/navigatorTitle","value":[{"text":"GFPRewardedAd","kind":"identifier"}]}]}]}