{"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdManagerDelegate\/rewardedAdManager(_:didStart:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rewardedAdManager","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"manager","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdManager","text":"GFPRewardedAdManager","preciseIdentifier":"c:objc(cs)GFPRewardedAdManager"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didStart"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"rewardedAd"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAd","kind":"typeIdentifier","text":"GFPRewardedAd","preciseIdentifier":"c:objc(cs)GFPRewardedAd"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/gfpsdk\/gfprewardedadmanagerdelegate\/rewardedadmanager(_:didstart:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfprewardedadmanagerdelegate\/rewardedadmanager(_:didstart:)"]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdManagerDelegate"]]},"metadata":{"symbolKind":"method","required":true,"role":"symbol","modules":[{"name":"GFPSDK"}],"externalID":"c:objc(pl)GFPRewardedAdManagerDelegate(im)rewardedAdManager:didStartAd:","navigatorTitle":[{"text":"rewardedAdManager:didStartAd:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"rewardedAdManager"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)GFPRewardedAdManager","text":"GFPRewardedAdManager","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didStart","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPRewardedAd","text":"GFPRewardedAd","kind":"typeIdentifier"},{"kind":"text","text":")"}],"roleHeading":"Instance Method","title":"rewardedAdManager(_:didStart:)"},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRewardedAd":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAd","url":"\/documentation\/gfpsdk\/gfprewardedad","navigatorTitle":[{"kind":"identifier","text":"GFPRewardedAd"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPRewardedAd","kind":"identifier"}],"kind":"symbol","abstract":[],"type":"topic","title":"GFPRewardedAd","role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRewardedAdManagerDelegate/rewardedAdManager(_:didStart:)":{"type":"topic","title":"rewardedAdManager(_:didStart:)","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rewardedAdManager"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPRewardedAdManager","text":"GFPRewardedAdManager"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didStart"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPRewardedAd","text":"GFPRewardedAd","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/gfpsdk\/gfprewardedadmanagerdelegate\/rewardedadmanager(_:didstart:)","role":"symbol","required":true,"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdManagerDelegate\/rewardedAdManager(_:didStart:)","navigatorTitle":[{"text":"rewardedAdManager:didStartAd:","kind":"identifier"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRewardedAdManagerDelegate":{"title":"GFPRewardedAdManagerDelegate","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdManagerDelegate","url":"\/documentation\/gfpsdk\/gfprewardedadmanagerdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPRewardedAdManagerDelegate"}],"kind":"symbol","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPRewardedAdManagerDelegate"}],"type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRewardedAdManager":{"title":"GFPRewardedAdManager","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdManager","url":"\/documentation\/gfpsdk\/gfprewardedadmanager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPRewardedAdManager"}],"kind":"symbol","abstract":[],"role":"symbol","navigatorTitle":[{"text":"GFPRewardedAdManager","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","value":"rewardedAdManager:didStartAd:","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"rewardedAdManager:didStartAd:","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"rewardedAdManager:"},{"text":"(","kind":"text"},{"text":"GFPRewardedAdManager","preciseIdentifier":"c:objc(cs)GFPRewardedAdManager","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdManager"},{"text":" *) ","kind":"text"},{"text":"manager","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didStartAd:"},{"text":"(","kind":"text"},{"text":"GFPRewardedAd","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPRewardedAd","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAd"},{"kind":"text","text":" *) "},{"text":"rewardedAd","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"value":"GFPRewardedAd","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAd\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAd\/fragments","value":[{"text":"GFPRewardedAd","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAd\/navigatorTitle","value":[{"kind":"identifier","text":"GFPRewardedAd"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdManagerDelegate~1rewardedAdManager(_:didStart:)\/title","op":"replace","value":"rewardedAdManager:didStartAd:"},{"value":[{"text":"- ","kind":"text"},{"text":"rewardedAdManager:didStartAd:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdManagerDelegate~1rewardedAdManager(_:didStart:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdManagerDelegate\/title","value":"GFPRewardedAdManagerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdManagerDelegate\/fragments","value":[{"kind":"identifier","text":"GFPRewardedAdManagerDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdManagerDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"GFPRewardedAdManagerDelegate"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdManager\/title","value":"GFPRewardedAdManager","op":"replace"},{"value":[{"text":"GFPRewardedAdManager","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdManager\/fragments"},{"op":"replace","value":[{"text":"GFPRewardedAdManager","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdManager\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}