{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rewardedAdManager"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"manager"},{"text":": ","kind":"text"},{"text":"GFPRewardedAdManager","preciseIdentifier":"c:objc(cs)GFPRewardedAdManager","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdManager"},{"kind":"text","text":", "},{"kind":"externalParam","text":"wasClickedAd"},{"kind":"text","text":" "},{"text":"rewardedAd","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPRewardedAd","text":"GFPRewardedAd","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAd","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfprewardedadmanagerdelegate\/rewardedadmanager(_:wasclickedad:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfprewardedadmanagerdelegate\/rewardedadmanager(_:wasclickedad:)"]}],"metadata":{"symbolKind":"method","externalID":"c:objc(pl)GFPRewardedAdManagerDelegate(im)rewardedAdManager:wasClickedAd:","modules":[{"name":"GFPSDK"}],"navigatorTitle":[{"kind":"identifier","text":"rewardedAdManager:wasClickedAd:"}],"title":"rewardedAdManager(_:wasClickedAd:)","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rewardedAdManager"},{"kind":"text","text":"("},{"text":"GFPRewardedAdManager","preciseIdentifier":"c:objc(cs)GFPRewardedAdManager","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"wasClickedAd","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPRewardedAd","text":"GFPRewardedAd"},{"kind":"text","text":")"}],"role":"symbol","required":true},"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdManagerDelegate"]]},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdManagerDelegate\/rewardedAdManager(_:wasClickedAd:)","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRewardedAdManagerDelegate":{"title":"GFPRewardedAdManagerDelegate","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdManagerDelegate","url":"\/documentation\/gfpsdk\/gfprewardedadmanagerdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPRewardedAdManagerDelegate"}],"kind":"symbol","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPRewardedAdManagerDelegate"}],"type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRewardedAd":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAd","url":"\/documentation\/gfpsdk\/gfprewardedad","navigatorTitle":[{"kind":"identifier","text":"GFPRewardedAd"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPRewardedAd","kind":"identifier"}],"kind":"symbol","abstract":[],"type":"topic","title":"GFPRewardedAd","role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRewardedAdManagerDelegate/rewardedAdManager(_:wasClickedAd:)":{"required":true,"role":"symbol","type":"topic","navigatorTitle":[{"text":"rewardedAdManager:wasClickedAd:","kind":"identifier"}],"abstract":[],"title":"rewardedAdManager(_:wasClickedAd:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rewardedAdManager"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"GFPRewardedAdManager","preciseIdentifier":"c:objc(cs)GFPRewardedAdManager"},{"kind":"text","text":", "},{"text":"wasClickedAd","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)GFPRewardedAd","kind":"typeIdentifier","text":"GFPRewardedAd"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdManagerDelegate\/rewardedAdManager(_:wasClickedAd:)","url":"\/documentation\/gfpsdk\/gfprewardedadmanagerdelegate\/rewardedadmanager(_:wasclickedad:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRewardedAdManager":{"title":"GFPRewardedAdManager","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdManager","url":"\/documentation\/gfpsdk\/gfprewardedadmanager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPRewardedAdManager"}],"kind":"symbol","abstract":[],"role":"symbol","navigatorTitle":[{"text":"GFPRewardedAdManager","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"rewardedAdManager:wasClickedAd:","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"rewardedAdManager:wasClickedAd:"}],"path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"rewardedAdManager:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"GFPRewardedAdManager","preciseIdentifier":"c:objc(cs)GFPRewardedAdManager","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdManager"},{"kind":"text","text":" *) "},{"text":"manager","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"wasClickedAd:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GFPRewardedAd","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAd","preciseIdentifier":"c:objc(cs)GFPRewardedAd"},{"text":" *) ","kind":"text"},{"text":"rewardedAd","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdManagerDelegate\/title","value":"GFPRewardedAdManagerDelegate","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdManagerDelegate\/fragments","op":"replace","value":[{"text":"GFPRewardedAdManagerDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdManagerDelegate\/navigatorTitle","value":[{"text":"GFPRewardedAdManagerDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAd\/title","value":"GFPRewardedAd"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAd\/fragments","value":[{"kind":"identifier","text":"GFPRewardedAd"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAd\/navigatorTitle","value":[{"kind":"identifier","text":"GFPRewardedAd"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdManagerDelegate~1rewardedAdManager(_:wasClickedAd:)\/title","op":"replace","value":"rewardedAdManager:wasClickedAd:"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdManagerDelegate~1rewardedAdManager(_:wasClickedAd:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"rewardedAdManager:wasClickedAd:"}]},{"op":"replace","value":"GFPRewardedAdManager","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdManager\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdManager\/fragments","value":[{"kind":"identifier","text":"GFPRewardedAdManager"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdManager\/navigatorTitle","value":[{"text":"GFPRewardedAdManager","kind":"identifier"}]}]}]}