{"kind":"symbol","sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"resized","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@GFPBannerSizeChangeType","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerSizeChangeType","text":"GFPBannerSizeChangeType"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpbannersizechangetype\/resized"]},{"paths":["\/documentation\/gfpsdk\/gfpbannersizechangetype\/resized"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"GFPBannerSizeChangeResized"}],"role":"symbol","title":"resized","symbolKind":"property","roleHeading":"Type Property","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"resized","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@GFPBannerSizeChangeType","kind":"typeIdentifier","text":"GFPBannerSizeChangeType"}],"externalID":"c:@E@GFPBannerSizeChangeType@GFPBannerSizeChangeResized","modules":[{"name":"GFPSDK"}]},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerSizeChangeType\/resized","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerSizeChangeType"]]},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerSizeChangeType":{"url":"\/documentation\/gfpsdk\/gfpbannersizechangetype","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerSizeChangeType","type":"topic","role":"symbol","abstract":[],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPBannerSizeChangeType","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"GFPBannerSizeChangeType"}],"title":"GFPBannerSizeChangeType","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerSizeChangeType/resized":{"navigatorTitle":[{"kind":"identifier","text":"GFPBannerSizeChangeResized"}],"type":"topic","kind":"symbol","role":"symbol","abstract":[],"url":"\/documentation\/gfpsdk\/gfpbannersizechangetype\/resized","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerSizeChangeType\/resized","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"resized","kind":"identifier"},{"kind":"text","text":": "},{"text":"GFPBannerSizeChangeType","kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPBannerSizeChangeType"}],"title":"resized"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"GFPBannerSizeChangeResized"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","value":[{"text":"GFPBannerSizeChangeResized","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"GFPBannerSizeChangeResized","kind":"identifier"}]}]}},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerSizeChangeType\/title","value":"GFPBannerSizeChangeType","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"GFPBannerSizeChangeType"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerSizeChangeType\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerSizeChangeType\/navigatorTitle","op":"replace","value":[{"text":"GFPBannerSizeChangeType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerSizeChangeType~1resized\/title","value":"GFPBannerSizeChangeResized","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerSizeChangeType~1resized\/fragments","value":[{"text":"GFPBannerSizeChangeResized","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}