{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"restore","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@GFPBannerSizeChangeType","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerSizeChangeType","kind":"typeIdentifier","text":"GFPBannerSizeChangeType"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerSizeChangeType"]]},"metadata":{"roleHeading":"Type Property","title":"restore","externalID":"c:@E@GFPBannerSizeChangeType@GFPBannerSizeChangeRestore","modules":[{"name":"GFPSDK"}],"navigatorTitle":[{"kind":"identifier","text":"GFPBannerSizeChangeRestore"}],"symbolKind":"property","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"restore","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@GFPBannerSizeChangeType","kind":"typeIdentifier","text":"GFPBannerSizeChangeType"}]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpbannersizechangetype\/restore"]},{"paths":["\/documentation\/gfpsdk\/gfpbannersizechangetype\/restore"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerSizeChangeType\/restore","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerSizeChangeType/restore":{"abstract":[],"url":"\/documentation\/gfpsdk\/gfpbannersizechangetype\/restore","navigatorTitle":[{"text":"GFPBannerSizeChangeRestore","kind":"identifier"}],"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerSizeChangeType\/restore","title":"restore","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"restore","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPBannerSizeChangeType","text":"GFPBannerSizeChangeType"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerSizeChangeType":{"url":"\/documentation\/gfpsdk\/gfpbannersizechangetype","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerSizeChangeType","type":"topic","role":"symbol","abstract":[],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPBannerSizeChangeType","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"GFPBannerSizeChangeType"}],"title":"GFPBannerSizeChangeType","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"GFPBannerSizeChangeRestore"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","value":[{"kind":"identifier","text":"GFPBannerSizeChangeRestore"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"GFPBannerSizeChangeRestore","kind":"identifier"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"GFPBannerSizeChangeRestore","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerSizeChangeType~1restore\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerSizeChangeType~1restore\/fragments","value":[{"text":"GFPBannerSizeChangeRestore","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerSizeChangeType\/title","value":"GFPBannerSizeChangeType"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerSizeChangeType\/fragments","value":[{"text":"GFPBannerSizeChangeType","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"GFPBannerSizeChangeType"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerSizeChangeType\/navigatorTitle"}]}]}