{"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPPrivacySetting"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpprivacysetting\/init(underageofconsent:childdirected:)"]},{"paths":["\/documentation\/gfpsdk\/gfpprivacysetting\/init(underageofconsent:childdirected:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"text":"underAgeOfConsent","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"childDirected"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"text":"?)","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPPrivacySetting\/init(underAgeOfConsent:childDirected:)","interfaceLanguage":"swift"},"metadata":{"externalID":"c:objc(cs)GFPPrivacySetting(im)initWithUnderAgeOfConsent:childDirected:","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"underAgeOfConsent","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"kind":"text","text":"?, "},{"text":"childDirected","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"initWithUnderAgeOfConsent:childDirected:"}],"modules":[{"name":"GFPSDK"}],"symbolKind":"init","role":"symbol","title":"init(underAgeOfConsent:childDirected:)","roleHeading":"Initializer"},"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPPrivacySetting":{"type":"topic","url":"\/documentation\/gfpsdk\/gfpprivacysetting","role":"symbol","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPPrivacySetting","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPPrivacySetting","title":"GFPPrivacySetting","navigatorTitle":[{"text":"GFPPrivacySetting","kind":"identifier"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPPrivacySetting/init(underAgeOfConsent:childDirected:)":{"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"underAgeOfConsent","kind":"externalParam"},{"kind":"text","text":": "},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"childDirected"},{"text":": ","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"?)","kind":"text"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"initWithUnderAgeOfConsent:childDirected:"}],"url":"\/documentation\/gfpsdk\/gfpprivacysetting\/init(underageofconsent:childdirected:)","kind":"symbol","type":"topic","role":"symbol","title":"init(underAgeOfConsent:childDirected:)","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPPrivacySetting\/init(underAgeOfConsent:childDirected:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","value":"initWithUnderAgeOfConsent:childDirected:","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithUnderAgeOfConsent:childDirected:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"initWithUnderAgeOfConsent:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"underAgeOfConsent"},{"kind":"text","text":" "},{"text":"childDirected:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"childDirected","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"GFPPrivacySetting","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPPrivacySetting\/title"},{"value":[{"text":"GFPPrivacySetting","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPPrivacySetting\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"GFPPrivacySetting"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPPrivacySetting\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPPrivacySetting~1init(underAgeOfConsent:childDirected:)\/title","value":"initWithUnderAgeOfConsent:childDirected:"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPPrivacySetting~1init(underAgeOfConsent:childDirected:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithUnderAgeOfConsent:childDirected:","kind":"identifier"}],"op":"replace"}]}]}