{"variants":[{"paths":["\/documentation\/gfpsdk\/gfpprivacysetting\/underageofconsent"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gfpsdk\/gfpprivacysetting\/underageofconsent"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"성인이 아닌 사용자에 대한 광고 요청 여부"}],"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPPrivacySetting\/underAgeOfConsent"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"underAgeOfConsent"},{"text":": ","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}]}]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"underAgeOfConsent"}],"roleHeading":"Instance Property","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"underAgeOfConsent","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"symbolKind":"property","modules":[{"name":"GFPSDK"}],"externalID":"c:objc(cs)GFPPrivacySetting(py)underAgeOfConsent","title":"underAgeOfConsent"},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPPrivacySetting"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPPrivacySetting":{"type":"topic","url":"\/documentation\/gfpsdk\/gfpprivacysetting","role":"symbol","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPPrivacySetting","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPPrivacySetting","title":"GFPPrivacySetting","navigatorTitle":[{"text":"GFPPrivacySetting","kind":"identifier"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPPrivacySetting/underAgeOfConsent":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"underAgeOfConsent","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier","text":"NSNumber"},{"text":"?","kind":"text"}],"type":"topic","abstract":[{"type":"text","text":"성인이 아닌 사용자에 대한 광고 요청 여부"}],"url":"\/documentation\/gfpsdk\/gfpprivacysetting\/underageofconsent","title":"underAgeOfConsent","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPPrivacySetting\/underAgeOfConsent","role":"symbol","navigatorTitle":[{"text":"underAgeOfConsent","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"value":"underAgeOfConsent","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"value":[{"text":"underAgeOfConsent","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":" * ","kind":"text"},{"text":"underAgeOfConsent","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"value":"GFPPrivacySetting","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPPrivacySetting\/title"},{"value":[{"kind":"identifier","text":"GFPPrivacySetting"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPPrivacySetting\/fragments"},{"value":[{"text":"GFPPrivacySetting","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPPrivacySetting\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPPrivacySetting~1underAgeOfConsent\/title","value":"underAgeOfConsent"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPPrivacySetting~1underAgeOfConsent\/fragments","op":"replace","value":[{"text":"underAgeOfConsent","kind":"identifier"}]}]}]}