{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"scheduleParam","kind":"identifier"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdScheduleParam","preciseIdentifier":"c:objc(cs)GFPAdScheduleParam","kind":"typeIdentifier","text":"GFPAdScheduleParam"},{"kind":"text","text":"? { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdvertiseParams\/scheduleParam"},"metadata":{"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"scheduleParam","kind":"identifier"},{"kind":"text","text":": "},{"text":"GFPAdScheduleParam","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdScheduleParam"},{"text":"?","kind":"text"}],"role":"symbol","symbolKind":"property","modules":[{"name":"GFPSDK"}],"navigatorTitle":[{"kind":"identifier","text":"scheduleParam"}],"externalID":"c:objc(cs)GFPAdvertiseParams(py)scheduleParam","title":"scheduleParam"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpadvertiseparams\/scheduleparam"]},{"paths":["\/documentation\/gfpsdk\/gfpadvertiseparams\/scheduleparam"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdvertiseParams"]]},"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdvertiseParams/scheduleParam":{"kind":"symbol","role":"symbol","title":"scheduleParam","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdvertiseParams\/scheduleParam","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"scheduleParam"},{"text":": ","kind":"text"},{"text":"GFPAdScheduleParam","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdScheduleParam"},{"kind":"text","text":"?"}],"abstract":[],"navigatorTitle":[{"text":"scheduleParam","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpadvertiseparams\/scheduleparam","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdvertiseParams":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdvertiseParams","kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPAdvertiseParams","kind":"identifier"}],"abstract":[],"navigatorTitle":[{"text":"GFPAdvertiseParams","kind":"identifier"}],"title":"GFPAdvertiseParams","url":"\/documentation\/gfpsdk\/gfpadvertiseparams"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdScheduleParam":{"title":"GFPAdScheduleParam","type":"topic","url":"\/documentation\/gfpsdk\/gfpadscheduleparam","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPAdScheduleParam","kind":"identifier"}],"navigatorTitle":[{"text":"GFPAdScheduleParam","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdScheduleParam","role":"symbol","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"scheduleParam"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"scheduleParam","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"GFPAdScheduleParam","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdScheduleParam","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdScheduleParam"},{"kind":"text","text":" * "},{"text":"scheduleParam","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"op":"replace","value":"scheduleParam","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdvertiseParams~1scheduleParam\/title"},{"value":[{"kind":"identifier","text":"scheduleParam"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdvertiseParams~1scheduleParam\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdvertiseParams\/title","value":"GFPAdvertiseParams"},{"value":[{"text":"GFPAdvertiseParams","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdvertiseParams\/fragments"},{"value":[{"text":"GFPAdvertiseParams","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdvertiseParams\/navigatorTitle","op":"replace"},{"value":"GFPAdScheduleParam","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdScheduleParam\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdScheduleParam\/fragments","value":[{"text":"GFPAdScheduleParam","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdScheduleParam\/navigatorTitle","value":[{"text":"GFPAdScheduleParam","kind":"identifier"}],"op":"replace"}]}]}