{"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithDomElement:"},{"text":"(","kind":"text"},{"text":"DDXMLElement","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)DDXMLElement"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"aElement"},{"text":" ","kind":"text"},{"kind":"identifier","text":"error:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@NaverAdsServices@objc(cs)GFPError","text":"GFPError","kind":"typeIdentifier"},{"text":" * *) ","kind":"text"},{"kind":"internalParam","text":"aError"},{"text":";","kind":"text"}]}]}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpcreativeextension\/initwithdomelement:error:"]}],"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPCreativeExtension\/initWithDomElement:error:","interfaceLanguage":"occ"},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPCreativeExtension"]]},"metadata":{"modules":[{"name":"GFPSDK"}],"symbolKind":"method","navigatorTitle":[{"text":"initWithDomElement:error:","kind":"identifier"}],"title":"initWithDomElement:error:","roleHeading":"Instance Method","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithDomElement:error:"}],"externalID":"c:objc(cs)GFPCreativeExtension(im)initWithDomElement:error:","role":"symbol"},"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPCreativeExtension":{"abstract":[],"kind":"symbol","role":"symbol","title":"GFPCreativeExtension","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GFPCreativeExtension"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPCreativeExtension"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPCreativeExtension","url":"\/documentation\/gfpsdk\/gfpcreativeextension"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPCreativeExtension/initWithDomElement:error:":{"navigatorTitle":[{"text":"initWithDomElement:error:","kind":"identifier"}],"type":"topic","title":"initWithDomElement:error:","kind":"symbol","url":"\/documentation\/gfpsdk\/gfpcreativeextension\/initwithdomelement:error:","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPCreativeExtension\/initWithDomElement:error:","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithDomElement:error:"}],"role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPCreativeExtension\/title","value":"GFPCreativeExtension"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPCreativeExtension\/fragments","value":[{"text":"GFPCreativeExtension","kind":"identifier"}]},{"op":"replace","value":[{"text":"GFPCreativeExtension","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPCreativeExtension\/navigatorTitle"}]}]}