source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '13.0'

def real_podspec # Real
  pod 'NAMSDK'
  pod 'NAMSDK/MediationNDA'
  pod 'NAMSDK/MediationNDAVideo'
  pod 'NAMSDK/MediationDFP'  
  pod 'NAMSDK/MediationFAN'
  pod 'NAMSDK/MediationInMobi'
  pod 'NAMSDK/MediationUnity'
  pod 'NAMSDK/MediationAppLovin'
  pod 'NAMSDK/MediationVungle'
end


def local_podspec # Local
  pod 'NAMSDK', :path => "../"               # SDK 본체
  pod 'NAMSDK/MediationNDA', :path => "../"
  pod 'NAMSDK/MediationNDAVideo', :path => "../"
  pod 'NAMSDK/MediationDFP', :path => "../"
  pod 'NAMSDK/MediationFAN', :path => "../"
  pod 'NAMSDK/MediationInMobi', :path => "../"
  pod 'NAMSDK/MediationUnity', :path => "../"
  pod 'NAMSDK/MediationAppLovin', :path => "../"
  pod 'NAMSDK/MediationVungle', :path => "../"
end


def headerBidding_sdk
  pod 'AmazonPublisherServicesSDK', '3.4.6' # 헤더비딩 Amazon
end

def sample
  pod 'SnapKit'
end

target 'SwiftSample' do
  use_frameworks!
  
  local_podspec
  #real_podspec
  headerBidding_sdk
  sample

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    
    target.build_configurations.each do |config|
      
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'  

    end
  end
end
