{"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoPlayPolicy"]]},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoPlayPolicy\/autoPlay","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpvideoplaypolicy\/autoplay"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpvideoplaypolicy\/autoplay"]}],"metadata":{"role":"symbol","title":"autoPlay","roleHeading":"Type Property","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"autoPlay","kind":"identifier"},{"text":": ","kind":"text"},{"text":"GFPVideoPlayPolicy","kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPVideoPlayPolicy"}],"externalID":"c:@E@GFPVideoPlayPolicy@GFPVideoPlayPolicyAutoPlay","symbolKind":"property","navigatorTitle":[{"text":"GFPVideoPlayPolicyAutoPlay","kind":"identifier"}],"modules":[{"name":"GFPSDK"}]},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"autoPlay"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoPlayPolicy","text":"GFPVideoPlayPolicy","preciseIdentifier":"c:@E@GFPVideoPlayPolicy","kind":"typeIdentifier"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoPlayPolicy":{"abstract":[],"title":"GFPVideoPlayPolicy","url":"\/documentation\/gfpsdk\/gfpvideoplaypolicy","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPVideoPlayPolicy","kind":"identifier"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPVideoPlayPolicy"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoPlayPolicy","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoPlayPolicy/autoPlay":{"title":"autoPlay","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoPlayPolicy\/autoPlay","role":"symbol","kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"autoPlay","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPVideoPlayPolicy","text":"GFPVideoPlayPolicy"}],"navigatorTitle":[{"text":"GFPVideoPlayPolicyAutoPlay","kind":"identifier"}],"type":"topic","url":"\/documentation\/gfpsdk\/gfpvideoplaypolicy\/autoplay"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"value":"GFPVideoPlayPolicyAutoPlay","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GFPVideoPlayPolicyAutoPlay"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"GFPVideoPlayPolicyAutoPlay","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoPlayPolicy\/title","op":"replace","value":"GFPVideoPlayPolicy"},{"value":[{"text":"GFPVideoPlayPolicy","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoPlayPolicy\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"GFPVideoPlayPolicy"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoPlayPolicy\/navigatorTitle","op":"replace"},{"op":"replace","value":"GFPVideoPlayPolicyAutoPlay","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoPlayPolicy~1autoPlay\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoPlayPolicy~1autoPlay\/fragments","op":"replace","value":[{"kind":"identifier","text":"GFPVideoPlayPolicyAutoPlay"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}