{"variants":[{"paths":["\/documentation\/gfpsdk\/gfpvideoplaypolicy\/autoplayonlywifi"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpvideoplaypolicy\/autoplayonlywifi"]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoPlayPolicy"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"autoPlayOnlyWiFi","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoPlayPolicy","preciseIdentifier":"c:@E@GFPVideoPlayPolicy","text":"GFPVideoPlayPolicy"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoPlayPolicy\/autoPlayOnlyWiFi","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"title":"autoPlayOnlyWiFi","symbolKind":"property","modules":[{"name":"GFPSDK"}],"role":"symbol","externalID":"c:@E@GFPVideoPlayPolicy@GFPVideoPlayPolicyAutoPlayOnlyWiFi","roleHeading":"Type Property","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"autoPlayOnlyWiFi","kind":"identifier"},{"kind":"text","text":": "},{"text":"GFPVideoPlayPolicy","kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPVideoPlayPolicy"}],"navigatorTitle":[{"text":"GFPVideoPlayPolicyAutoPlayOnlyWiFi","kind":"identifier"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoPlayPolicy/autoPlayOnlyWiFi":{"title":"autoPlayOnlyWiFi","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoPlayPolicy\/autoPlayOnlyWiFi","role":"symbol","kind":"symbol","abstract":[],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"autoPlayOnlyWiFi","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPVideoPlayPolicy","text":"GFPVideoPlayPolicy"}],"navigatorTitle":[{"kind":"identifier","text":"GFPVideoPlayPolicyAutoPlayOnlyWiFi"}],"type":"topic","url":"\/documentation\/gfpsdk\/gfpvideoplaypolicy\/autoplayonlywifi"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoPlayPolicy":{"abstract":[],"title":"GFPVideoPlayPolicy","url":"\/documentation\/gfpsdk\/gfpvideoplaypolicy","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPVideoPlayPolicy","kind":"identifier"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPVideoPlayPolicy"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoPlayPolicy","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"GFPVideoPlayPolicyAutoPlayOnlyWiFi","op":"replace"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GFPVideoPlayPolicyAutoPlayOnlyWiFi"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"GFPVideoPlayPolicyAutoPlayOnlyWiFi","kind":"identifier"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoPlayPolicy~1autoPlayOnlyWiFi\/title","value":"GFPVideoPlayPolicyAutoPlayOnlyWiFi","op":"replace"},{"value":[{"text":"GFPVideoPlayPolicyAutoPlayOnlyWiFi","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoPlayPolicy~1autoPlayOnlyWiFi\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoPlayPolicy\/title","value":"GFPVideoPlayPolicy","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"GFPVideoPlayPolicy"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoPlayPolicy\/fragments"},{"value":[{"kind":"identifier","text":"GFPVideoPlayPolicy"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoPlayPolicy\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}