{"abstract":[{"text":"Inherited from ","type":"text"},{"code":"OptionSet.init()","type":"codeVoice"},{"type":"text","text":"."}],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpvideoplaypolicy\/init()"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoPlayPolicy","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoPlayPolicy\/OptionSet-Implementations"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"init","kind":"keyword"},{"kind":"text","text":"()"}]}]}],"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoPlayPolicy\/init()","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"role":"symbol","title":"init()","modules":[{"name":"GFPSDK","relatedModules":["Swift"]}],"fragments":[{"kind":"identifier","text":"init"},{"text":"()","kind":"text"}],"roleHeading":"Initializer","symbolKind":"init","conformance":{"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}],"constraints":[{"type":"codeVoice","code":"RawValue"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"FixedWidthInteger"},{"text":".","type":"text"}]},"externalID":"s:s9OptionSetPss17FixedWidthInteger8RawValueRpzrlExycfc::SYNTHESIZED::c:@E@GFPVideoPlayPolicy","extendedModule":"Swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoPlayPolicy/OptionSet-Implementations":{"title":"OptionSet Implementations","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoPlayPolicy\/OptionSet-Implementations","kind":"article","abstract":[],"url":"\/documentation\/gfpsdk\/gfpvideoplaypolicy\/optionset-implementations","type":"topic","role":"collectionGroup"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoPlayPolicy/init()":{"conformance":{"conformancePrefix":[{"type":"text","text":"Conforms when"}],"constraints":[{"code":"RawValue","type":"codeVoice"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"FixedWidthInteger"},{"type":"text","text":"."}],"availabilityPrefix":[{"type":"text","text":"Available when"}]},"title":"init()","abstract":[],"type":"topic","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoPlayPolicy\/init()","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"()"}],"url":"\/documentation\/gfpsdk\/gfpvideoplaypolicy\/init()","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoPlayPolicy":{"abstract":[],"title":"GFPVideoPlayPolicy","url":"\/documentation\/gfpsdk\/gfpvideoplaypolicy","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPVideoPlayPolicy","kind":"identifier"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPVideoPlayPolicy"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoPlayPolicy","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoPlayPolicy\/title","op":"replace","value":"GFPVideoPlayPolicy"},{"value":[{"text":"GFPVideoPlayPolicy","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoPlayPolicy\/fragments"},{"value":[{"text":"GFPVideoPlayPolicy","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoPlayPolicy\/navigatorTitle"}]}]}