{"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdChoicesViewPosition\/init()","interfaceLanguage":"swift"},"metadata":{"extendedModule":"Swift","title":"init()","modules":[{"name":"GFPSDK","relatedModules":["Swift"]}],"symbolKind":"init","role":"symbol","externalID":"s:s9OptionSetPss17FixedWidthInteger8RawValueRpzrlExycfc::SYNTHESIZED::c:@E@GFPAdChoicesViewPosition","roleHeading":"Initializer","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"conformance":{"availabilityPrefix":[{"text":"Available when","type":"text"}],"constraints":[{"type":"codeVoice","code":"RawValue"},{"text":" conforms to ","type":"text"},{"code":"FixedWidthInteger","type":"codeVoice"},{"text":".","type":"text"}],"conformancePrefix":[{"text":"Conforms when","type":"text"}]}},"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"OptionSet.init()"},{"type":"text","text":"."}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"text":"()","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdChoicesViewPosition","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdChoicesViewPosition\/OptionSet-Implementations"]]},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpadchoicesviewposition\/init()"]}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdChoicesViewPosition/init()":{"type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdChoicesViewPosition\/init()","title":"init()","kind":"symbol","abstract":[],"conformance":{"conformancePrefix":[{"type":"text","text":"Conforms when"}],"constraints":[{"type":"codeVoice","code":"RawValue"},{"text":" conforms to ","type":"text"},{"code":"FixedWidthInteger","type":"codeVoice"},{"type":"text","text":"."}],"availabilityPrefix":[{"type":"text","text":"Available when"}]},"role":"symbol","url":"\/documentation\/gfpsdk\/gfpadchoicesviewposition\/init()","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"()"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdChoicesViewPosition":{"url":"\/documentation\/gfpsdk\/gfpadchoicesviewposition","role":"symbol","abstract":[],"type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPAdChoicesViewPosition"}],"title":"GFPAdChoicesViewPosition","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdChoicesViewPosition","navigatorTitle":[{"kind":"identifier","text":"GFPAdChoicesViewPosition"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdChoicesViewPosition/OptionSet-Implementations":{"url":"\/documentation\/gfpsdk\/gfpadchoicesviewposition\/optionset-implementations","title":"OptionSet Implementations","abstract":[],"type":"topic","kind":"article","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdChoicesViewPosition\/OptionSet-Implementations","role":"collectionGroup"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdChoicesViewPosition\/title","op":"replace","value":"GFPAdChoicesViewPosition"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdChoicesViewPosition\/fragments","op":"replace","value":[{"text":"GFPAdChoicesViewPosition","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"GFPAdChoicesViewPosition"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdChoicesViewPosition\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}