{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpadchoicesviewposition\/topleftcorner"]},{"paths":["\/documentation\/gfpsdk\/gfpadchoicesviewposition\/topleftcorner"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdChoicesViewPosition"]]},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"topLeftCorner","kind":"identifier"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdChoicesViewPosition","text":"GFPAdChoicesViewPosition","preciseIdentifier":"c:@E@GFPAdChoicesViewPosition","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdChoicesViewPosition\/topLeftCorner"},"kind":"symbol","metadata":{"title":"topLeftCorner","symbolKind":"property","role":"symbol","externalID":"c:@E@GFPAdChoicesViewPosition@GFPAdChoicesViewPositionTopLeftCorner","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"topLeftCorner"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"GFPAdChoicesViewPosition","preciseIdentifier":"c:@E@GFPAdChoicesViewPosition"}],"modules":[{"name":"GFPSDK"}],"navigatorTitle":[{"text":"GFPAdChoicesViewPositionTopLeftCorner","kind":"identifier"}],"roleHeading":"Type Property"},"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdChoicesViewPosition":{"url":"\/documentation\/gfpsdk\/gfpadchoicesviewposition","role":"symbol","abstract":[],"type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPAdChoicesViewPosition"}],"title":"GFPAdChoicesViewPosition","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdChoicesViewPosition","navigatorTitle":[{"kind":"identifier","text":"GFPAdChoicesViewPosition"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdChoicesViewPosition/topLeftCorner":{"type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"GFPAdChoicesViewPositionTopLeftCorner"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdChoicesViewPosition\/topLeftCorner","title":"topLeftCorner","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"topLeftCorner","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPAdChoicesViewPosition","text":"GFPAdChoicesViewPosition"}],"url":"\/documentation\/gfpsdk\/gfpadchoicesviewposition\/topleftcorner","kind":"symbol","role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"GFPAdChoicesViewPositionTopLeftCorner","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","value":[{"kind":"identifier","text":"GFPAdChoicesViewPositionTopLeftCorner"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"GFPAdChoicesViewPositionTopLeftCorner","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdChoicesViewPosition\/title","value":"GFPAdChoicesViewPosition","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdChoicesViewPosition\/fragments","value":[{"kind":"identifier","text":"GFPAdChoicesViewPosition"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdChoicesViewPosition\/navigatorTitle","value":[{"kind":"identifier","text":"GFPAdChoicesViewPosition"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdChoicesViewPosition~1topLeftCorner\/title","value":"GFPAdChoicesViewPositionTopLeftCorner"},{"op":"replace","value":[{"kind":"identifier","text":"GFPAdChoicesViewPositionTopLeftCorner"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdChoicesViewPosition~1topLeftCorner\/fragments"}]}]}