{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"audio","kind":"identifier"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPControlButtonType","text":"GFPControlButtonType","preciseIdentifier":"c:@E@GFPControlButtonType","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}]}],"sections":[],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpcontrolbuttontype\/audio"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpcontrolbuttontype\/audio"]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPControlButtonType"]]},"metadata":{"navigatorTitle":[{"text":"GFPControlButtonTypeAudio","kind":"identifier"}],"role":"symbol","symbolKind":"property","roleHeading":"Type Property","externalID":"c:@E@GFPControlButtonType@GFPControlButtonTypeAudio","modules":[{"name":"GFPSDK"}],"title":"audio","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"audio","kind":"identifier"},{"kind":"text","text":": "},{"text":"GFPControlButtonType","kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPControlButtonType"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPControlButtonType\/audio","interfaceLanguage":"swift"},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPControlButtonType/audio":{"navigatorTitle":[{"kind":"identifier","text":"GFPControlButtonTypeAudio"}],"title":"audio","abstract":[],"type":"topic","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPControlButtonType\/audio","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"audio","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@GFPControlButtonType","kind":"typeIdentifier","text":"GFPControlButtonType"}],"url":"\/documentation\/gfpsdk\/gfpcontrolbuttontype\/audio","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPControlButtonType":{"kind":"symbol","title":"GFPControlButtonType","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPControlButtonType"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPControlButtonType","role":"symbol","type":"topic","url":"\/documentation\/gfpsdk\/gfpcontrolbuttontype","navigatorTitle":[{"kind":"identifier","text":"GFPControlButtonType"}],"abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"GFPControlButtonTypeAudio"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GFPControlButtonTypeAudio"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"GFPControlButtonTypeAudio","kind":"identifier"}]}],"kind":"declarations"},"op":"replace"},{"value":"GFPControlButtonTypeAudio","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPControlButtonType~1audio\/title","op":"replace"},{"value":[{"kind":"identifier","text":"GFPControlButtonTypeAudio"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPControlButtonType~1audio\/fragments"},{"value":"GFPControlButtonType","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPControlButtonType\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPControlButtonType\/fragments","value":[{"kind":"identifier","text":"GFPControlButtonType"}]},{"op":"replace","value":[{"text":"GFPControlButtonType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPControlButtonType\/navigatorTitle"}]}]}