{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPControlButtonType\/formUnion(_:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"mutating"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"formUnion","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"other","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Self"},{"text":")","kind":"text"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPControlButtonType","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPControlButtonType\/OptionSet-Implementations"]]},"kind":"symbol","metadata":{"modules":[{"name":"GFPSDK","relatedModules":["Swift"]}],"conformance":{"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"text":"Conforms when","type":"text"}],"constraints":[{"type":"codeVoice","code":"RawValue"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"FixedWidthInteger"},{"type":"text","text":"."}]},"externalID":"s:s9OptionSetPss17FixedWidthInteger8RawValueRpzrlE9formUnionyyxF::SYNTHESIZED::c:@E@GFPControlButtonType","extendedModule":"Swift","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"formUnion"},{"kind":"text","text":"("},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":")"}],"role":"symbol","roleHeading":"Instance Method","title":"formUnion(_:)"},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"OptionSet.formUnion(_:)"},{"type":"text","text":"."}],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpcontrolbuttontype\/formunion(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPControlButtonType/OptionSet-Implementations":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPControlButtonType\/OptionSet-Implementations","title":"OptionSet Implementations","url":"\/documentation\/gfpsdk\/gfpcontrolbuttontype\/optionset-implementations","role":"collectionGroup","type":"topic","abstract":[],"kind":"article"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPControlButtonType/formUnion(_:)":{"title":"formUnion(_:)","role":"symbol","url":"\/documentation\/gfpsdk\/gfpcontrolbuttontype\/formunion(_:)","kind":"symbol","type":"topic","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"formUnion","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":")"}],"conformance":{"constraints":[{"type":"codeVoice","code":"RawValue"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"FixedWidthInteger"},{"type":"text","text":"."}],"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"text":"Conforms when","type":"text"}]},"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPControlButtonType\/formUnion(_:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPControlButtonType":{"kind":"symbol","title":"GFPControlButtonType","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPControlButtonType"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPControlButtonType","role":"symbol","type":"topic","url":"\/documentation\/gfpsdk\/gfpcontrolbuttontype","navigatorTitle":[{"kind":"identifier","text":"GFPControlButtonType"}],"abstract":[]}},"variantOverrides":[{"patch":[{"value":"GFPControlButtonType","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPControlButtonType\/title","op":"replace"},{"value":[{"text":"GFPControlButtonType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPControlButtonType\/fragments","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"GFPControlButtonType"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPControlButtonType\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}