{"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPControlButtonType"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpcontrolbuttontype\/pause"]},{"paths":["\/documentation\/gfpsdk\/gfpcontrolbuttontype\/pause"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"pause"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPControlButtonType","text":"GFPControlButtonType","kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPControlButtonType"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"externalID":"c:@E@GFPControlButtonType@GFPControlButtonTypePause","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"pause","kind":"identifier"},{"text":": ","kind":"text"},{"text":"GFPControlButtonType","kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPControlButtonType"}],"navigatorTitle":[{"text":"GFPControlButtonTypePause","kind":"identifier"}],"modules":[{"name":"GFPSDK"}],"symbolKind":"property","role":"symbol","roleHeading":"Type Property","title":"pause"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPControlButtonType\/pause"},"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPControlButtonType":{"kind":"symbol","title":"GFPControlButtonType","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPControlButtonType"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPControlButtonType","role":"symbol","type":"topic","url":"\/documentation\/gfpsdk\/gfpcontrolbuttontype","navigatorTitle":[{"kind":"identifier","text":"GFPControlButtonType"}],"abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPControlButtonType/pause":{"navigatorTitle":[{"text":"GFPControlButtonTypePause","kind":"identifier"}],"title":"pause","abstract":[],"type":"topic","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPControlButtonType\/pause","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"pause","kind":"identifier"},{"kind":"text","text":": "},{"text":"GFPControlButtonType","kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPControlButtonType"}],"url":"\/documentation\/gfpsdk\/gfpcontrolbuttontype\/pause","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"GFPControlButtonTypePause","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","value":[{"text":"GFPControlButtonTypePause","kind":"identifier"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"GFPControlButtonTypePause","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"value":"GFPControlButtonType","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPControlButtonType\/title","op":"replace"},{"op":"replace","value":[{"text":"GFPControlButtonType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPControlButtonType\/fragments"},{"value":[{"text":"GFPControlButtonType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPControlButtonType\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPControlButtonType~1pause\/title","op":"replace","value":"GFPControlButtonTypePause"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPControlButtonType~1pause\/fragments","value":[{"kind":"identifier","text":"GFPControlButtonTypePause"}],"op":"replace"}]}]}