{"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"abstract":[{"type":"text","text":"전면형광고 요청 타임아웃 (기본값 60초, kGFPDefaultInterstitialAdRequestTimeout)"}],"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"interstitialAdRequestTimeout","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"TimeInterval"}],"role":"symbol","roleHeading":"Instance Property","externalID":"c:objc(cs)GFPAdConfiguration(py)interstitialAdRequestTimeout","symbolKind":"property","title":"interstitialAdRequestTimeout","modules":[{"name":"GFPSDK"}],"navigatorTitle":[{"kind":"identifier","text":"interstitialAdRequestTimeout"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpadconfiguration\/interstitialadrequesttimeout"]},{"paths":["\/documentation\/gfpsdk\/gfpadconfiguration\/interstitialadrequesttimeout"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"interstitialAdRequestTimeout"},{"kind":"text","text":": "},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdConfiguration"]]},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdConfiguration\/interstitialAdRequestTimeout","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdConfiguration/interstitialAdRequestTimeout":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"interstitialAdRequestTimeout","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"}],"url":"\/documentation\/gfpsdk\/gfpadconfiguration\/interstitialadrequesttimeout","kind":"symbol","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdConfiguration\/interstitialAdRequestTimeout","abstract":[{"type":"text","text":"전면형광고 요청 타임아웃 (기본값 60초, kGFPDefaultInterstitialAdRequestTimeout)"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"interstitialAdRequestTimeout"}],"title":"interstitialAdRequestTimeout"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdConfiguration":{"type":"topic","url":"\/documentation\/gfpsdk\/gfpadconfiguration","role":"symbol","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPAdConfiguration","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdConfiguration","title":"GFPAdConfiguration","navigatorTitle":[{"text":"GFPAdConfiguration","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"value":"interstitialAdRequestTimeout","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","value":[{"text":"interstitialAdRequestTimeout","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"assign","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"NSTimeInterval"},{"kind":"text","text":" "},{"text":"interstitialAdRequestTimeout","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdConfiguration~1interstitialAdRequestTimeout\/title","value":"interstitialAdRequestTimeout"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdConfiguration~1interstitialAdRequestTimeout\/fragments","value":[{"text":"interstitialAdRequestTimeout","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdConfiguration\/title","value":"GFPAdConfiguration","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"GFPAdConfiguration"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdConfiguration\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdConfiguration\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"GFPAdConfiguration"}]}]}]}