{"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpadconfiguration\/phase"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpadconfiguration\/phase"]}],"metadata":{"navigatorTitle":[{"text":"phase","kind":"identifier"}],"externalID":"c:objc(cs)GFPAdConfiguration(py)phase","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"phase"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GFPPhaseType","preciseIdentifier":"c:@E@GFPPhaseType"}],"modules":[{"name":"GFPSDK"}],"roleHeading":"Instance Property","role":"symbol","title":"phase"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"phase","kind":"identifier"},{"text":": ","kind":"text"},{"text":"GFPPhaseType","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPPhaseType","kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPPhaseType"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdConfiguration"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdConfiguration\/phase"},"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPPhaseType":{"kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPPhaseType","url":"\/documentation\/gfpsdk\/gfpphasetype","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"GFPPhaseType","kind":"identifier"}],"title":"GFPPhaseType","role":"symbol","type":"topic","navigatorTitle":[{"text":"GFPPhaseType","kind":"identifier"}],"abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdConfiguration/phase":{"navigatorTitle":[{"kind":"identifier","text":"phase"}],"url":"\/documentation\/gfpsdk\/gfpadconfiguration\/phase","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"phase","kind":"identifier"},{"text":": ","kind":"text"},{"text":"GFPPhaseType","kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPPhaseType"}],"role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdConfiguration\/phase","title":"phase"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdConfiguration":{"type":"topic","url":"\/documentation\/gfpsdk\/gfpadconfiguration","role":"symbol","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPAdConfiguration","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdConfiguration","title":"GFPAdConfiguration","navigatorTitle":[{"text":"GFPAdConfiguration","kind":"identifier"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"value":"phase","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","value":[{"text":"phase","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"assign","kind":"keyword"},{"kind":"text","text":") "},{"text":"GFPPhaseType","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPPhaseType","kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPPhaseType"},{"text":" ","kind":"text"},{"kind":"identifier","text":"phase"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPPhaseType\/title","value":"GFPPhaseType"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPPhaseType\/fragments","value":[{"kind":"identifier","text":"GFPPhaseType"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPPhaseType\/navigatorTitle","value":[{"text":"GFPPhaseType","kind":"identifier"}],"op":"replace"},{"value":"phase","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdConfiguration~1phase\/title"},{"value":[{"kind":"identifier","text":"phase"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdConfiguration~1phase\/fragments"},{"value":"GFPAdConfiguration","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdConfiguration\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdConfiguration\/fragments","op":"replace","value":[{"text":"GFPAdConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"GFPAdConfiguration"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}