{"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLanguageType\/fr"},"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"fr"}],"navigatorTitle":[{"kind":"identifier","text":"GFPLanguageType_fr"}],"roleHeading":"Case","externalID":"c:@E@GFPLanguageType@GFPLanguageType_fr","role":"symbol","modules":[{"name":"GFPSDK"}],"title":"GFPLanguageType.fr","symbolKind":"case"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fr"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfplanguagetype\/fr"]},{"paths":["\/documentation\/gfpsdk\/gfplanguagetype\/fr"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLanguageType"]]},"sections":[],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPLanguageType/fr":{"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"fr"}],"kind":"symbol","title":"GFPLanguageType.fr","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLanguageType\/fr","abstract":[],"navigatorTitle":[{"text":"GFPLanguageType_fr","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfplanguagetype\/fr"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPLanguageType":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLanguageType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPLanguageType"}],"kind":"symbol","navigatorTitle":[{"text":"GFPLanguageType","kind":"identifier"}],"title":"GFPLanguageType","type":"topic","url":"\/documentation\/gfpsdk\/gfplanguagetype","abstract":[],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"GFPLanguageType_fr"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"GFPLanguageType_fr","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"GFPLanguageType_fr"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLanguageType~1fr\/title","op":"replace","value":"GFPLanguageType_fr"},{"value":[{"kind":"identifier","text":"GFPLanguageType_fr"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLanguageType~1fr\/fragments"},{"value":"GFPLanguageType","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLanguageType\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLanguageType\/fragments","value":[{"kind":"identifier","text":"GFPLanguageType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLanguageType\/navigatorTitle","value":[{"text":"GFPLanguageType","kind":"identifier"}]}]}]}