{"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"adSources"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withDictionary"},{"kind":"text","text":" "},{"text":"aDicts","kind":"internalParam"},{"text":": [[","kind":"text"},{"text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"text":"]], ","kind":"text"},{"text":"type","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"aType"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@GFPVideoPlacementType","text":"GFPVideoPlacementType","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoPlacementType"},{"text":") -> [","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPVideoAdSource","text":"GFPVideoAdSource","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdSource"},{"text":"]","kind":"text"}],"languages":["swift"]}]}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpvideoadsource\/adsources(withdictionary:type:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpvideoadsource\/adsources(withdictionary:type:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdSource\/adSources(withDictionary:type:)"},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdSource"]]},"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"adSources"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withDictionary"},{"text":": [[","kind":"text"},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]], "},{"text":"type","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"GFPVideoPlacementType","preciseIdentifier":"c:@E@GFPVideoPlacementType","kind":"typeIdentifier"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","text":"GFPVideoAdSource","preciseIdentifier":"c:objc(cs)GFPVideoAdSource"},{"text":"]","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"adSourcesWithDictionary:type:"}],"roleHeading":"Type Method","modules":[{"name":"GFPSDK"}],"externalID":"c:objc(cs)GFPVideoAdSource(cm)adSourcesWithDictionary:type:","role":"symbol","title":"adSources(withDictionary:type:)","symbolKind":"method"},"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdSource":{"kind":"symbol","title":"GFPVideoAdSource","url":"\/documentation\/gfpsdk\/gfpvideoadsource","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPVideoAdSource","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdSource","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GFPVideoAdSource"}],"abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdSource/adSources(withDictionary:type:)":{"type":"topic","url":"\/documentation\/gfpsdk\/gfpvideoadsource\/adsources(withdictionary:type:)","role":"symbol","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"adSources","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"withDictionary"},{"text":": [[","kind":"text"},{"text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]], ","kind":"text"},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"text":"GFPVideoPlacementType","kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPVideoPlacementType"},{"kind":"text","text":") -> ["},{"text":"GFPVideoAdSource","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoAdSource"},{"kind":"text","text":"]"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdSource\/adSources(withDictionary:type:)","title":"adSources(withDictionary:type:)","navigatorTitle":[{"kind":"identifier","text":"adSourcesWithDictionary:type:"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoPlacementType":{"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPVideoPlacementType","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"GFPVideoPlacementType","kind":"identifier"}],"type":"topic","title":"GFPVideoPlacementType","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoPlacementType","kind":"symbol","url":"\/documentation\/gfpsdk\/gfpvideoplacementtype","abstract":[]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"adSourcesWithDictionary:type:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"adSourcesWithDictionary:type:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<GFPVideoAdSource *>"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"adSourcesWithDictionary:"},{"kind":"text","text":"("},{"text":"NSArray<NSDictionary *>","preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"aDicts"},{"kind":"text","text":" "},{"text":"type:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@E@GFPVideoPlacementType","text":"GFPVideoPlacementType","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoPlacementType"},{"kind":"text","text":") "},{"kind":"internalParam","text":"aType"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdSource\/title","op":"replace","value":"GFPVideoAdSource"},{"value":[{"text":"GFPVideoAdSource","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdSource\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdSource\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"GFPVideoAdSource"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdSource~1adSources(withDictionary:type:)\/title","value":"adSourcesWithDictionary:type:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdSource~1adSources(withDictionary:type:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"adSourcesWithDictionary:type:"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoPlacementType\/title","op":"replace","value":"GFPVideoPlacementType"},{"value":[{"text":"GFPVideoPlacementType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoPlacementType\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoPlacementType\/navigatorTitle","value":[{"kind":"identifier","text":"GFPVideoPlacementType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}