{"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPProviding"]]},"metadata":{"required":true,"symbolKind":"method","title":"createAdAdaptor(with:error:)","modules":[{"name":"GFPSDK"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"createAdAdaptor"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"text":"GFPAdAdaptorParam","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdAdaptorParam"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SA","text":"AutoreleasingUnsafeMutablePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"GFPError","preciseIdentifier":"c:@M@NaverAdsServices@objc(cs)GFPError","kind":"typeIdentifier"},{"kind":"text","text":"?>?) -> (any "},{"kind":"typeIdentifier","text":"GFPAdAdaptor","preciseIdentifier":"c:objc(cs)GFPAdAdaptor"},{"text":" & ","kind":"text"},{"preciseIdentifier":"c:objc(pl)GFPAdAdapting","kind":"typeIdentifier","text":"GFPAdAdapting"},{"text":")?","kind":"text"}],"roleHeading":"Instance Method","navigatorTitle":[{"text":"createAdAdaptorWithParam:error:","kind":"identifier"}],"externalID":"c:objc(pl)GFPProviding(im)createAdAdaptorWithParam:error:"},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"createAdAdaptor"},{"kind":"text","text":"("},{"text":"with","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"param","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"GFPAdAdaptorParam","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAdaptorParam","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdAdaptorParam"},{"text":", ","kind":"text"},{"text":"error","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SA","text":"AutoreleasingUnsafeMutablePointer","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@NaverAdsServices@objc(cs)GFPError","text":"GFPError"},{"text":"?>?) -> (any ","kind":"text"},{"kind":"typeIdentifier","text":"GFPAdAdaptor","preciseIdentifier":"c:objc(cs)GFPAdAdaptor","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAdaptor"},{"kind":"text","text":" & "},{"text":"GFPAdAdapting","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAdapting","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)GFPAdAdapting"},{"kind":"text","text":")?"}]}]},{"kind":"parameters","parameters":[{"name":"param","content":[{"type":"paragraph","inlineContent":[{"text":"어댑터 파라미터","type":"text"}]}]}]},{"kind":"content","content":[{"level":2,"anchor":"return-value","text":"Return Value","type":"heading"},{"inlineContent":[{"text":"광고 어댑터","type":"text"}],"type":"paragraph"}]}],"abstract":[{"text":"초기화에 실패하면 nil 리턴","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPProviding\/createAdAdaptor(with:error:)"},"sections":[],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpproviding\/createadadaptor(with:error:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gfpsdk\/gfpproviding\/createadadaptor(with:error:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdAdaptorParam":{"navigatorTitle":[{"text":"GFPAdAdaptorParam","kind":"identifier"}],"abstract":[],"title":"GFPAdAdaptorParam","url":"\/documentation\/gfpsdk\/gfpadadaptorparam","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAdaptorParam","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"GFPAdAdaptorParam","kind":"identifier"}],"type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPProviding":{"title":"GFPProviding","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPProviding","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPProviding","kind":"identifier"}],"abstract":[],"navigatorTitle":[{"text":"GFPProviding","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpproviding","type":"topic","role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdAdaptor":{"navigatorTitle":[{"kind":"identifier","text":"GFPAdAdaptor"}],"title":"GFPAdAdaptor","url":"\/documentation\/gfpsdk\/gfpadadaptor","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAdaptor","abstract":[],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPAdAdaptor"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdAdapting":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"GFPAdAdapting","kind":"identifier"}],"abstract":[],"url":"\/documentation\/gfpsdk\/gfpadadapting","kind":"symbol","role":"symbol","title":"GFPAdAdapting","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAdapting","type":"topic","navigatorTitle":[{"text":"GFPAdAdapting","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPProviding/createAdAdaptor(with:error:)":{"required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createAdAdaptor"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)GFPAdAdaptorParam","text":"GFPAdAdaptorParam","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"error"},{"text":": ","kind":"text"},{"text":"AutoreleasingUnsafeMutablePointer","preciseIdentifier":"s:SA","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@NaverAdsServices@objc(cs)GFPError","text":"GFPError"},{"kind":"text","text":"?>?) -> (any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdAdaptor","text":"GFPAdAdaptor"},{"kind":"text","text":" & "},{"text":"GFPAdAdapting","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)GFPAdAdapting"},{"text":")?","kind":"text"}],"abstract":[{"type":"text","text":"초기화에 실패하면 nil 리턴"}],"navigatorTitle":[{"kind":"identifier","text":"createAdAdaptorWithParam:error:"}],"url":"\/documentation\/gfpsdk\/gfpproviding\/createadadaptor(with:error:)","kind":"symbol","type":"topic","role":"symbol","title":"createAdAdaptor(with:error:)","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPProviding\/createAdAdaptor(with:error:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"createAdAdaptorWithParam:error:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"createAdAdaptorWithParam:error:"}]},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"GFPAdAdaptor<GFPAdAdapting>","preciseIdentifier":"c:Q$objc(cs)GFPAdAdaptorobjc(pl)GFPAdAdapting"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"createAdAdaptorWithParam:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPAdAdaptorParam","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAdaptorParam","text":"GFPAdAdaptorParam"},{"text":" *) ","kind":"text"},{"text":"param","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"error:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@NaverAdsServices@objc(cs)GFPError","text":"GFPError"},{"kind":"text","text":" * *) "},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}]}]},"op":"replace"},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"param","content":[{"inlineContent":[{"type":"text","text":"어댑터 파라미터"}],"type":"paragraph"}]}]},"op":"replace"},{"op":"replace","value":{"content":[{"text":"Return Value","type":"heading","anchor":"return-value","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"광고 어댑터"}]}],"kind":"content"},"path":"\/primaryContentSections\/2"},{"op":"replace","value":"GFPAdAdaptorParam","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdaptorParam\/title"},{"op":"replace","value":[{"kind":"identifier","text":"GFPAdAdaptorParam"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdaptorParam\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdaptorParam\/navigatorTitle","value":[{"kind":"identifier","text":"GFPAdAdaptorParam"}],"op":"replace"},{"value":"GFPProviding","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPProviding\/title"},{"value":[{"kind":"identifier","text":"GFPProviding"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPProviding\/fragments"},{"op":"replace","value":[{"text":"GFPProviding","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPProviding\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdaptor\/title","value":"GFPAdAdaptor"},{"op":"replace","value":[{"kind":"identifier","text":"GFPAdAdaptor"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdaptor\/fragments"},{"value":[{"kind":"identifier","text":"GFPAdAdaptor"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdaptor\/navigatorTitle","op":"replace"},{"op":"replace","value":"GFPAdAdapting","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdapting\/title"},{"value":[{"kind":"identifier","text":"GFPAdAdapting"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdapting\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"GFPAdAdapting"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdapting\/navigatorTitle"},{"value":"createAdAdaptorWithParam:error:","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPProviding~1createAdAdaptor(with:error:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"createAdAdaptorWithParam:error:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPProviding~1createAdAdaptor(with:error:)\/fragments","op":"replace"}]}]}