{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"metadata":{"title":"initializeSDK(with:)","role":"symbol","modules":[{"name":"GFPSDK"}],"roleHeading":"Instance Method","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"initializeSDKWith:"}],"required":true,"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"initializeSDK"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"GFPAdInitProviderInfo","kind":"typeIdentifier","preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPAdInitProviderInfo"},{"kind":"text","text":")"}],"externalID":"c:objc(pl)GFPProviding(im)initializeSDKWith:"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"initializeSDK","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"text":" ","kind":"text"},{"text":"providerInfo","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPAdInitProviderInfo","text":"GFPAdInitProviderInfo","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdInitProviderInfo","kind":"typeIdentifier"},{"text":")","kind":"text"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpproviding\/initializesdk(with:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpproviding\/initializesdk(with:)"]}],"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPProviding\/initializeSDK(with:)","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPProviding"]]},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPProviding":{"title":"GFPProviding","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPProviding","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPProviding","kind":"identifier"}],"abstract":[],"navigatorTitle":[{"text":"GFPProviding","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpproviding","type":"topic","role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdInitProviderInfo":{"title":"GFPAdInitProviderInfo","url":"\/documentation\/gfpsdk\/gfpadinitproviderinfo","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPAdInitProviderInfo"}],"navigatorTitle":[{"kind":"identifier","text":"GFPAdInitProviderInfo"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdInitProviderInfo","type":"topic","role":"symbol","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPProviding/initializeSDK(with:)":{"required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"initializeSDK"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPAdInitProviderInfo","kind":"typeIdentifier","text":"GFPAdInitProviderInfo"},{"kind":"text","text":")"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"initializeSDKWith:"}],"url":"\/documentation\/gfpsdk\/gfpproviding\/initializesdk(with:)","kind":"symbol","type":"topic","role":"symbol","title":"initializeSDK(with:)","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPProviding\/initializeSDK(with:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"initializeSDKWith:","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initializeSDKWith:"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initializeSDKWith:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPAdInitProviderInfo","text":"GFPAdInitProviderInfo","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdInitProviderInfo","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"providerInfo","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"value":"GFPProviding","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPProviding\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPProviding\/fragments","value":[{"text":"GFPProviding","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPProviding\/navigatorTitle","value":[{"kind":"identifier","text":"GFPProviding"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdInitProviderInfo\/title","value":"GFPAdInitProviderInfo"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdInitProviderInfo\/fragments","op":"replace","value":[{"kind":"identifier","text":"GFPAdInitProviderInfo"}]},{"op":"replace","value":[{"text":"GFPAdInitProviderInfo","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdInitProviderInfo\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPProviding~1initializeSDK(with:)\/title","value":"initializeSDKWith:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initializeSDKWith:"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPProviding~1initializeSDK(with:)\/fragments"}]}]}