{"metadata":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"providerRenderTypes"},{"text":"() -> [","kind":"text"},{"preciseIdentifier":"c:GFPProvider.h@T@GFPProviderRenderType","kind":"typeIdentifier","text":"GFPProviderRenderType"},{"kind":"text","text":"]"}],"modules":[{"name":"GFPSDK"}],"roleHeading":"Instance Method","required":true,"navigatorTitle":[{"text":"providerRenderTypes","kind":"identifier"}],"symbolKind":"method","externalID":"c:objc(pl)GFPProviding(im)providerRenderTypes","title":"providerRenderTypes()"},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPProviding\/providerRenderTypes()","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpproviding\/providerrendertypes()"]},{"paths":["\/documentation\/gfpsdk\/gfpproviding\/providerrendertypes()"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"providerRenderTypes","kind":"identifier"},{"kind":"text","text":"() -> ["},{"text":"GFPProviderRenderType","kind":"typeIdentifier","preciseIdentifier":"c:GFPProvider.h@T@GFPProviderRenderType","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPProviderRenderType"},{"text":"]","kind":"text"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPProviding"]]},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPProviding/providerRenderTypes()":{"url":"\/documentation\/gfpsdk\/gfpproviding\/providerrendertypes()","required":true,"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPProviding\/providerRenderTypes()","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"providerRenderTypes"},{"text":"() -> [","kind":"text"},{"preciseIdentifier":"c:GFPProvider.h@T@GFPProviderRenderType","text":"GFPProviderRenderType","kind":"typeIdentifier"},{"kind":"text","text":"]"}],"navigatorTitle":[{"text":"providerRenderTypes","kind":"identifier"}],"type":"topic","kind":"symbol","title":"providerRenderTypes()","abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPProviding":{"title":"GFPProviding","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPProviding","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPProviding","kind":"identifier"}],"abstract":[],"navigatorTitle":[{"text":"GFPProviding","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpproviding","type":"topic","role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPProviderRenderType":{"abstract":[],"title":"GFPProviderRenderType","type":"topic","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPProviderRenderType","navigatorTitle":[{"kind":"identifier","text":"GFPProviderRenderType"}],"kind":"symbol","url":"\/documentation\/gfpsdk\/gfpproviderrendertype","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"GFPProviderRenderType","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"providerRenderTypes"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"providerRenderTypes"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<NSString *>"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"providerRenderTypes"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPProviding~1providerRenderTypes()\/title","value":"providerRenderTypes","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"providerRenderTypes","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPProviding~1providerRenderTypes()\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPProviding\/title","value":"GFPProviding","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPProviding\/fragments","value":[{"kind":"identifier","text":"GFPProviding"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPProviding\/navigatorTitle","value":[{"kind":"identifier","text":"GFPProviding"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPProviderRenderType\/title","value":"GFPProviderRenderType","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPProviderRenderType\/fragments","op":"replace","value":[{"text":"GFPProviderRenderType","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"GFPProviderRenderType"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPProviderRenderType\/navigatorTitle"}]}]}