{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRichTrackingURLs\/init(trackingArr:)"},"metadata":{"title":"init(trackingArr:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"trackingArr"},{"text":": [","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"])"}],"roleHeading":"Initializer","role":"symbol","externalID":"c:objc(cs)GFPRichTrackingURLs(im)initWithTrackingArr:","symbolKind":"init","navigatorTitle":[{"text":"initWithTrackingArr:","kind":"identifier"}],"modules":[{"name":"GFPSDK"}]},"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"kind":"externalParam","text":"trackingArr"},{"kind":"text","text":" "},{"text":"richTrackingArr","kind":"internalParam"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"text":"])","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRichTrackingURLs"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfprichtrackingurls\/init(trackingarr:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfprichtrackingurls\/init(trackingarr:)"]}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRichTrackingURLs/init(trackingArr:)":{"title":"init(trackingArr:)","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRichTrackingURLs\/init(trackingArr:)","url":"\/documentation\/gfpsdk\/gfprichtrackingurls\/init(trackingarr:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"trackingArr"},{"text":": [","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"])","kind":"text"}],"kind":"symbol","abstract":[],"role":"symbol","navigatorTitle":[{"text":"initWithTrackingArr:","kind":"identifier"}],"type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRichTrackingURLs":{"title":"GFPRichTrackingURLs","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRichTrackingURLs","url":"\/documentation\/gfpsdk\/gfprichtrackingurls","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPRichTrackingURLs","kind":"identifier"}],"kind":"symbol","abstract":[],"role":"symbol","navigatorTitle":[{"text":"GFPRichTrackingURLs","kind":"identifier"}],"type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"initWithTrackingArr:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithTrackingArr:"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithTrackingArr:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSArray","text":"NSArray"},{"kind":"text","text":" *) "},{"text":"richTrackingArr","kind":"internalParam"},{"kind":"text","text":";"}]}]}},{"value":"initWithTrackingArr:","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRichTrackingURLs~1init(trackingArr:)\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRichTrackingURLs~1init(trackingArr:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithTrackingArr:","kind":"identifier"}],"op":"replace"},{"value":"GFPRichTrackingURLs","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRichTrackingURLs\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRichTrackingURLs\/fragments","op":"replace","value":[{"text":"GFPRichTrackingURLs","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRichTrackingURLs\/navigatorTitle","value":[{"kind":"identifier","text":"GFPRichTrackingURLs"}]}]}]}