{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfprichtrackingurls\/trackingwithkey:"]}],"metadata":{"externalID":"c:objc(cs)GFPRichTrackingURLs(im)trackingWithKey:","navigatorTitle":[{"text":"trackingWithKey:","kind":"identifier"}],"fragments":[{"kind":"text","text":"- "},{"text":"trackingWithKey:","kind":"identifier"}],"modules":[{"name":"GFPSDK"}],"symbolKind":"method","role":"symbol","roleHeading":"Instance Method","title":"trackingWithKey:"},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRichTrackingURLs"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRichTrackingURLs\/trackingWithKey:","interfaceLanguage":"occ"},"primaryContentSections":[{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPRichDetailInfo","text":"GFPRichDetailInfo"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"trackingWithKey:"},{"kind":"text","text":"("},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"key","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRichTrackingURLs/trackingWithKey:":{"title":"trackingWithKey:","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRichTrackingURLs\/trackingWithKey:","url":"\/documentation\/gfpsdk\/gfprichtrackingurls\/trackingwithkey:","fragments":[{"kind":"text","text":"- "},{"text":"trackingWithKey:","kind":"identifier"}],"kind":"symbol","abstract":[],"role":"symbol","navigatorTitle":[{"text":"trackingWithKey:","kind":"identifier"}],"type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRichTrackingURLs":{"title":"GFPRichTrackingURLs","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRichTrackingURLs","url":"\/documentation\/gfpsdk\/gfprichtrackingurls","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPRichTrackingURLs","kind":"identifier"}],"kind":"symbol","abstract":[],"role":"symbol","navigatorTitle":[{"text":"GFPRichTrackingURLs","kind":"identifier"}],"type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRichTrackingURLs\/title","op":"replace","value":"GFPRichTrackingURLs"},{"value":[{"text":"GFPRichTrackingURLs","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRichTrackingURLs\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRichTrackingURLs\/navigatorTitle","value":[{"kind":"identifier","text":"GFPRichTrackingURLs"}],"op":"replace"}]}]}