{"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdInfoSize"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdInfoSize\/init(dictionary:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"init","kind":"keyword"},{"kind":"text","text":"?("},{"text":"dictionary","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"adInfoSizeDict"},{"text":": [","kind":"text"},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?)"}],"languages":["swift"]}]}],"sections":[],"metadata":{"role":"symbol","title":"init(dictionary:)","roleHeading":"Initializer","fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"dictionary"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]?)"}],"externalID":"c:objc(cs)GFPAdInfoSize(im)initWithDictionary:","symbolKind":"init","navigatorTitle":[{"text":"initWithDictionary:","kind":"identifier"}],"modules":[{"name":"GFPSDK"}]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpadinfosize\/init(dictionary:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpadinfosize\/init(dictionary:)"]}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdInfoSize/init(dictionary:)":{"title":"init(dictionary:)","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdInfoSize\/init(dictionary:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"dictionary","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]?)"}],"navigatorTitle":[{"kind":"identifier","text":"initWithDictionary:"}],"url":"\/documentation\/gfpsdk\/gfpadinfosize\/init(dictionary:)","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdInfoSize":{"type":"topic","abstract":[{"text":"GFPAdInfoSize","type":"text"}],"title":"GFPAdInfoSize","role":"symbol","url":"\/documentation\/gfpsdk\/gfpadinfosize","navigatorTitle":[{"kind":"identifier","text":"GFPAdInfoSize"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdInfoSize","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPAdInfoSize"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"initWithDictionary:","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithDictionary:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"initWithDictionary:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSDictionary","kind":"typeIdentifier","text":"NSDictionary"},{"kind":"text","text":" *) "},{"text":"adInfoSizeDict","kind":"internalParam"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdInfoSize~1init(dictionary:)\/title","value":"initWithDictionary:","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithDictionary:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdInfoSize~1init(dictionary:)\/fragments"},{"value":"GFPAdInfoSize","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdInfoSize\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdInfoSize\/fragments","value":[{"text":"GFPAdInfoSize","kind":"identifier"}],"op":"replace"},{"value":[{"text":"GFPAdInfoSize","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdInfoSize\/navigatorTitle"}]}]}