{"metadata":{"title":"createQoeTrackingInfo(host:path:timeTable:serviceId:ownerServiceId:appId:viewerInfo:)","symbolKind":"method","role":"symbol","externalID":"c:@M@GFPSDK@objc(cs)GFPQoeTrackingInfo(cm)createQoeTrackingInfoWith:path:timeTable:serviceId:ownerServiceId:appId:viewerInfo:","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"createQoeTrackingInfo","kind":"identifier"},{"kind":"text","text":"("},{"text":"host","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"path","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"timeTable","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":"], ","kind":"text"},{"text":"serviceId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"ownerServiceId"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"appId"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"viewerInfo"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPQoeTrackingInfo","text":"GFPQoeTrackingInfo","kind":"typeIdentifier"}],"modules":[{"name":"GFPSDK"}],"navigatorTitle":[{"text":"createQoeTrackingInfoWith:path:timeTable:serviceId:ownerServiceId:appId:viewerInfo:","kind":"identifier"}],"roleHeading":"Type Method"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPQoeTrackingInfo\/createQoeTrackingInfo(host:path:timeTable:serviceId:ownerServiceId:appId:viewerInfo:)"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(createQoeTrackingInfoWith:path:timeTable:serviceId:ownerServiceId:appId:viewerInfo:) ","kind":"text"},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"createQoeTrackingInfo","kind":"identifier"},{"text":"(","kind":"text"},{"text":"host","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"path","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"timeTable"},{"text":": [","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":"], "},{"text":"serviceId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"text":"ownerServiceId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"appId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"viewerInfo","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":") -> ","kind":"text"},{"text":"GFPQoeTrackingInfo","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPQoeTrackingInfo","preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPQoeTrackingInfo"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpqoetrackinginfo\/createqoetrackinginfo(host:path:timetable:serviceid:ownerserviceid:appid:viewerinfo:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpqoetrackinginfo\/createqoetrackinginfo(host:path:timetable:serviceid:ownerserviceid:appid:viewerinfo:)"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPQoeTrackingInfo"]]},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPQoeTrackingInfo/createQoeTrackingInfo(host:path:timeTable:serviceId:ownerServiceId:appId:viewerInfo:)":{"navigatorTitle":[{"kind":"identifier","text":"createQoeTrackingInfoWith:path:timeTable:serviceId:ownerServiceId:appId:viewerInfo:"}],"type":"topic","title":"createQoeTrackingInfo(host:path:timeTable:serviceId:ownerServiceId:appId:viewerInfo:)","kind":"symbol","url":"\/documentation\/gfpsdk\/gfpqoetrackinginfo\/createqoetrackinginfo(host:path:timetable:serviceid:ownerserviceid:appid:viewerinfo:)","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPQoeTrackingInfo\/createQoeTrackingInfo(host:path:timeTable:serviceId:ownerServiceId:appId:viewerInfo:)","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createQoeTrackingInfo","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"host"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"path","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"timeTable","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"serviceId"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"ownerServiceId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"appId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"viewerInfo","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"text":"GFPQoeTrackingInfo","preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPQoeTrackingInfo","kind":"typeIdentifier"}],"role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPQoeTrackingInfo":{"role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"GFPQoeTrackingInfo"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPQoeTrackingInfo"}],"kind":"symbol","type":"topic","title":"GFPQoeTrackingInfo","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPQoeTrackingInfo","url":"\/documentation\/gfpsdk\/gfpqoetrackinginfo"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"path":"\/metadata\/title","op":"replace","value":"createQoeTrackingInfoWith:path:timeTable:serviceId:ownerServiceId:appId:viewerInfo:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"+ "},{"text":"createQoeTrackingInfoWith:path:timeTable:serviceId:ownerServiceId:appId:viewerInfo:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"text":"GFPQoeTrackingInfo","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPQoeTrackingInfo","kind":"typeIdentifier","preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPQoeTrackingInfo"},{"text":" *) ","kind":"text"},{"text":"createQoeTrackingInfoWith:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"host"},{"text":" ","kind":"text"},{"text":"path:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"path"},{"text":" ","kind":"text"},{"kind":"identifier","text":"timeTable:"},{"text":"(","kind":"text"},{"text":"NSArray<NSNumber *>","preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"timeTable"},{"kind":"text","text":" "},{"text":"serviceId:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"serviceId"},{"text":" ","kind":"text"},{"text":"ownerServiceId:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"ownerServiceId"},{"kind":"text","text":" "},{"kind":"identifier","text":"appId:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"appId","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"viewerInfo:"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"viewerInfo"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"value":"createQoeTrackingInfoWith:path:timeTable:serviceId:ownerServiceId:appId:viewerInfo:","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPQoeTrackingInfo~1createQoeTrackingInfo(host:path:timeTable:serviceId:ownerServiceId:appId:viewerInfo:)\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPQoeTrackingInfo~1createQoeTrackingInfo(host:path:timeTable:serviceId:ownerServiceId:appId:viewerInfo:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"createQoeTrackingInfoWith:path:timeTable:serviceId:ownerServiceId:appId:viewerInfo:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPQoeTrackingInfo\/title","value":"GFPQoeTrackingInfo","op":"replace"},{"value":[{"text":"GFPQoeTrackingInfo","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPQoeTrackingInfo\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPQoeTrackingInfo\/navigatorTitle","value":[{"kind":"identifier","text":"GFPQoeTrackingInfo"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}