{"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRenderDisplayAgent\/init(type:scheme:)"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"type","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"aType"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"GFPRenderDisplayAgentType","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRenderDisplayAgentType","preciseIdentifier":"c:@E@GFPRenderDisplayAgentType"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"scheme"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"aScheme"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":")"}],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"deprecationSummary":[{"inlineContent":[{"text":"Use S2S Click Handler instead. it will be removed next version","type":"text"}],"type":"paragraph"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfprenderdisplayagent\/init(type:scheme:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfprenderdisplayagent\/init(type:scheme:)"]}],"metadata":{"title":"init(type:scheme:)","symbolKind":"init","platforms":[],"role":"symbol","externalID":"c:objc(cs)GFPRenderDisplayAgent(im)initWithType:scheme:","modules":[{"name":"GFPSDK"}],"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"type","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@GFPRenderDisplayAgentType","kind":"typeIdentifier","text":"GFPRenderDisplayAgentType"},{"text":", ","kind":"text"},{"text":"scheme","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"roleHeading":"Initializer","navigatorTitle":[{"kind":"identifier","text":"initWithType:scheme:"}]},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRenderDisplayAgent"]]},"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRenderDisplayAgentType":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPRenderDisplayAgentType","kind":"identifier"}],"kind":"symbol","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRenderDisplayAgentType","type":"topic","title":"GFPRenderDisplayAgentType","role":"symbol","url":"\/documentation\/gfpsdk\/gfprenderdisplayagenttype","navigatorTitle":[{"kind":"identifier","text":"GFPRenderDisplayAgentType"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRenderDisplayAgent":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPRenderDisplayAgent"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPRenderDisplayAgent"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRenderDisplayAgent","abstract":[],"role":"symbol","url":"\/documentation\/gfpsdk\/gfprenderdisplayagent","title":"GFPRenderDisplayAgent","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRenderDisplayAgent/init(type:scheme:)":{"abstract":[],"type":"topic","title":"init(type:scheme:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"type"},{"text":": ","kind":"text"},{"text":"GFPRenderDisplayAgentType","kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPRenderDisplayAgentType"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"scheme"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":")"}],"deprecated":true,"url":"\/documentation\/gfpsdk\/gfprenderdisplayagent\/init(type:scheme:)","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRenderDisplayAgent\/init(type:scheme:)","navigatorTitle":[{"text":"initWithType:scheme:","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/platforms","op":"replace","value":[]},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"initWithType:scheme:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithType:scheme:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"text":"initWithType:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRenderDisplayAgentType","text":"GFPRenderDisplayAgentType","kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPRenderDisplayAgentType"},{"kind":"text","text":") "},{"kind":"internalParam","text":"aType"},{"kind":"text","text":" "},{"kind":"identifier","text":"scheme:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"aScheme","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"op":"replace"},{"value":"GFPRenderDisplayAgentType","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRenderDisplayAgentType\/title"},{"value":[{"kind":"identifier","text":"GFPRenderDisplayAgentType"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRenderDisplayAgentType\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRenderDisplayAgentType\/navigatorTitle","value":[{"kind":"identifier","text":"GFPRenderDisplayAgentType"}],"op":"replace"},{"op":"replace","value":"GFPRenderDisplayAgent","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRenderDisplayAgent\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRenderDisplayAgent\/fragments","value":[{"text":"GFPRenderDisplayAgent","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRenderDisplayAgent\/navigatorTitle","value":[{"text":"GFPRenderDisplayAgent","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRenderDisplayAgent~1init(type:scheme:)\/title","value":"initWithType:scheme:"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithType:scheme:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRenderDisplayAgent~1init(type:scheme:)\/fragments"}]}]}