{"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"text":"dict","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"aDict","kind":"internalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"link"},{"kind":"text","text":" "},{"text":"aLink","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GFPNativeLinkInfo","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeLinkInfo","preciseIdentifier":"c:objc(cs)GFPNativeLinkInfo"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeCTAInfo"]]},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeCTAInfo\/init(dict:link:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpnativectainfo\/init(dict:link:)"]},{"paths":["\/documentation\/gfpsdk\/gfpnativectainfo\/init(dict:link:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"role":"symbol","roleHeading":"Initializer","title":"init(dict:link:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"dict","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"], ","kind":"text"},{"text":"link","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)GFPNativeLinkInfo","text":"GFPNativeLinkInfo","kind":"typeIdentifier"},{"kind":"text","text":")"}],"externalID":"c:objc(cs)GFPNativeCTAInfo(im)initWithDict:link:","symbolKind":"init","navigatorTitle":[{"kind":"identifier","text":"initWithDict:link:"}],"modules":[{"name":"GFPSDK"}]},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeCTAInfo/init(dict:link:)":{"title":"init(dict:link:)","kind":"symbol","navigatorTitle":[{"text":"initWithDict:link:","kind":"identifier"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"dict","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"link"},{"text":": ","kind":"text"},{"text":"GFPNativeLinkInfo","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPNativeLinkInfo"},{"text":")","kind":"text"}],"role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeCTAInfo\/init(dict:link:)","url":"\/documentation\/gfpsdk\/gfpnativectainfo\/init(dict:link:)","type":"topic","abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeCTAInfo":{"navigatorTitle":[{"text":"GFPNativeCTAInfo","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeCTAInfo","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPNativeCTAInfo","kind":"identifier"}],"title":"GFPNativeCTAInfo","abstract":[],"kind":"symbol","type":"topic","url":"\/documentation\/gfpsdk\/gfpnativectainfo"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeLinkInfo":{"navigatorTitle":[{"text":"GFPNativeLinkInfo","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeLinkInfo","title":"GFPNativeLinkInfo","type":"topic","url":"\/documentation\/gfpsdk\/gfpnativelinkinfo","abstract":[],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPNativeLinkInfo"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"initWithDict:link:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithDict:link:","kind":"identifier"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithDict:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSDictionary","text":"NSDictionary","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"aDict","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"link:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)GFPNativeLinkInfo","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeLinkInfo","kind":"typeIdentifier","text":"GFPNativeLinkInfo"},{"text":" *) ","kind":"text"},{"text":"aLink","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":"initWithDict:link:","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeCTAInfo~1init(dict:link:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithDict:link:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeCTAInfo~1init(dict:link:)\/fragments","op":"replace"},{"value":"GFPNativeCTAInfo","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeCTAInfo\/title","op":"replace"},{"value":[{"kind":"identifier","text":"GFPNativeCTAInfo"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeCTAInfo\/fragments"},{"value":[{"kind":"identifier","text":"GFPNativeCTAInfo"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeCTAInfo\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeLinkInfo\/title","value":"GFPNativeLinkInfo","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeLinkInfo\/fragments","value":[{"kind":"identifier","text":"GFPNativeLinkInfo"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeLinkInfo\/navigatorTitle","value":[{"text":"GFPNativeLinkInfo","kind":"identifier"}],"op":"replace"}]}]}