{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"abstract":[{"text":"광고 매니저를 종료 시킵니다.","type":"text"},{"text":" ","type":"text"},{"text":"(재생중 화면 전환이 발생하거나, 어플리케이션 동작과정에서 로드된 광고매니저의 리소스를 해제할 필요가 있는 경우)","type":"text"}],"metadata":{"symbolKind":"method","externalID":"c:objc(cs)GFPVideoAdManager(im)destroy","modules":[{"name":"GFPSDK"}],"navigatorTitle":[{"text":"destroy","kind":"identifier"}],"title":"destroy()","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"destroy","kind":"identifier"},{"text":"()","kind":"text"}],"role":"symbol"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpvideoadmanager\/destroy()"]},{"paths":["\/documentation\/gfpsdk\/gfpvideoadmanager\/destroy()"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"destroy"},{"text":"()","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager"]]},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager\/destroy()","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdManager":{"type":"topic","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager","role":"symbol","url":"\/documentation\/gfpsdk\/gfpvideoadmanager","title":"GFPVideoAdManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPVideoAdManager"}],"kind":"symbol","navigatorTitle":[{"text":"GFPVideoAdManager","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdManager/destroy()":{"abstract":[{"type":"text","text":"광고 매니저를 종료 시킵니다."},{"text":" ","type":"text"},{"text":"(재생중 화면 전환이 발생하거나, 어플리케이션 동작과정에서 로드된 광고매니저의 리소스를 해제할 필요가 있는 경우)","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"destroy","kind":"identifier"},{"text":"()","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"destroy","kind":"identifier"}],"type":"topic","url":"\/documentation\/gfpsdk\/gfpvideoadmanager\/destroy()","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager\/destroy()","title":"destroy()","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"destroy","path":"\/metadata\/title","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"destroy","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"destroy","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManager\/title","op":"replace","value":"GFPVideoAdManager"},{"op":"replace","value":[{"kind":"identifier","text":"GFPVideoAdManager"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManager\/fragments"},{"value":[{"kind":"identifier","text":"GFPVideoAdManager"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManager\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManager~1destroy()\/title","value":"destroy","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManager~1destroy()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"destroy"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}