{"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager"]]},"metadata":{"role":"symbol","roleHeading":"Instance Property","title":"renderingSetting","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"renderingSetting","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPVideoAdRenderingSetting","kind":"typeIdentifier","text":"GFPVideoAdRenderingSetting"},{"text":"?","kind":"text"}],"externalID":"c:objc(cs)GFPVideoAdManager(py)renderingSetting","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"renderingSetting"}],"modules":[{"name":"GFPSDK"}]},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"renderingSetting","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GFPVideoAdRenderingSetting","preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPVideoAdRenderingSetting","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdRenderingSetting"},{"kind":"text","text":"? { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"]}]}],"abstract":[{"type":"text","text":"광고 렌터링 세팅 (Optional)"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager\/renderingSetting"},"sections":[],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpvideoadmanager\/renderingsetting"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gfpsdk\/gfpvideoadmanager\/renderingsetting"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdManager/renderingSetting":{"kind":"symbol","title":"renderingSetting","abstract":[{"type":"text","text":"광고 렌터링 세팅 (Optional)"}],"type":"topic","url":"\/documentation\/gfpsdk\/gfpvideoadmanager\/renderingsetting","navigatorTitle":[{"kind":"identifier","text":"renderingSetting"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager\/renderingSetting","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"renderingSetting"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPVideoAdRenderingSetting","text":"GFPVideoAdRenderingSetting"},{"kind":"text","text":"?"}],"role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdRenderingSetting":{"type":"topic","abstract":[],"kind":"symbol","navigatorTitle":[{"text":"GFPVideoAdRenderingSetting","kind":"identifier"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPVideoAdRenderingSetting"}],"title":"GFPVideoAdRenderingSetting","url":"\/documentation\/gfpsdk\/gfpvideoadrenderingsetting","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdRenderingSetting"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdManager":{"type":"topic","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager","role":"symbol","url":"\/documentation\/gfpsdk\/gfpvideoadmanager","title":"GFPVideoAdManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPVideoAdManager"}],"kind":"symbol","navigatorTitle":[{"text":"GFPVideoAdManager","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","value":"renderingSetting","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"renderingSetting","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"text":"readwrite","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdRenderingSetting","preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPVideoAdRenderingSetting","text":"GFPVideoAdRenderingSetting"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"renderingSetting"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManager~1renderingSetting\/title","value":"renderingSetting"},{"value":[{"kind":"identifier","text":"renderingSetting"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManager~1renderingSetting\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdRenderingSetting\/title","op":"replace","value":"GFPVideoAdRenderingSetting"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdRenderingSetting\/fragments","value":[{"text":"GFPVideoAdRenderingSetting","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdRenderingSetting\/navigatorTitle","value":[{"kind":"identifier","text":"GFPVideoAdRenderingSetting"}]},{"value":"GFPVideoAdManager","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManager\/title"},{"op":"replace","value":[{"kind":"identifier","text":"GFPVideoAdManager"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManager\/fragments"},{"value":[{"kind":"identifier","text":"GFPVideoAdManager"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManager\/navigatorTitle"}]}]}