{"metadata":{"roleHeading":"Instance Method","required":true,"externalID":"c:objc(pl)GFPBannerByLoaderDelegate(im)bannerAdLoader:didFailToSizeAdWithError:mediator:","modules":[{"name":"GFPSDK"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bannerAdLoader"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)GFPBannerView","text":"GFPBannerView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didFailToSizeAdWithError"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@NaverAdsServices@objc(cs)GFPError","text":"GFPError"},{"kind":"text","text":", "},{"text":"mediator","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"GFPUnifiedMediator","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPUnifiedMediator"},{"text":")","kind":"text"}],"title":"bannerAdLoader(_:didFailToSizeAdWithError:mediator:)","symbolKind":"method","navigatorTitle":[{"text":"bannerAdLoader:didFailToSizeAdWithError:mediator:","kind":"identifier"}],"role":"symbol"},"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bannerAdLoader","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"bannerView","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerView","preciseIdentifier":"c:objc(cs)GFPBannerView","text":"GFPBannerView"},{"kind":"text","text":", "},{"text":"didFailToSizeAdWithError","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"GFPError","preciseIdentifier":"c:@M@NaverAdsServices@objc(cs)GFPError","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"mediator"},{"text":": ","kind":"text"},{"text":"GFPUnifiedMediator","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUnifiedMediator","preciseIdentifier":"c:objc(cs)GFPUnifiedMediator"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerByLoaderDelegate"]]},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerByLoaderDelegate\/bannerAdLoader(_:didFailToSizeAdWithError:mediator:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpbannerbyloaderdelegate\/banneradloader(_:didfailtosizeadwitherror:mediator:)"]},{"paths":["\/documentation\/gfpsdk\/gfpbannerbyloaderdelegate\/banneradloader(_:didfailtosizeadwitherror:mediator:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerByLoaderDelegate":{"navigatorTitle":[{"text":"GFPBannerByLoaderDelegate","kind":"identifier"}],"type":"topic","title":"GFPBannerByLoaderDelegate","kind":"symbol","url":"\/documentation\/gfpsdk\/gfpbannerbyloaderdelegate","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerByLoaderDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPBannerByLoaderDelegate"}],"role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPUnifiedMediator":{"abstract":[],"type":"topic","title":"GFPUnifiedMediator","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPUnifiedMediator","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpunifiedmediator","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUnifiedMediator","navigatorTitle":[{"text":"GFPUnifiedMediator","kind":"identifier"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerView":{"navigatorTitle":[{"text":"GFPBannerView","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerView","title":"GFPBannerView","role":"symbol","url":"\/documentation\/gfpsdk\/gfpbannerview","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPBannerView"}],"type":"topic","kind":"symbol","abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerByLoaderDelegate/bannerAdLoader(_:didFailToSizeAdWithError:mediator:)":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerByLoaderDelegate\/bannerAdLoader(_:didFailToSizeAdWithError:mediator:)","url":"\/documentation\/gfpsdk\/gfpbannerbyloaderdelegate\/banneradloader(_:didfailtosizeadwitherror:mediator:)","navigatorTitle":[{"kind":"identifier","text":"bannerAdLoader:didFailToSizeAdWithError:mediator:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bannerAdLoader"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPBannerView","kind":"typeIdentifier","text":"GFPBannerView"},{"text":", ","kind":"text"},{"text":"didFailToSizeAdWithError","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"GFPError","kind":"typeIdentifier","preciseIdentifier":"c:@M@NaverAdsServices@objc(cs)GFPError"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mediator"},{"kind":"text","text":": "},{"text":"GFPUnifiedMediator","preciseIdentifier":"c:objc(cs)GFPUnifiedMediator","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","abstract":[],"type":"topic","required":true,"title":"bannerAdLoader(_:didFailToSizeAdWithError:mediator:)","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"bannerAdLoader:didFailToSizeAdWithError:mediator:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"bannerAdLoader:didFailToSizeAdWithError:mediator:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"bannerAdLoader:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)GFPBannerView","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerView","kind":"typeIdentifier","text":"GFPBannerView"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"bannerView"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didFailToSizeAdWithError:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@NaverAdsServices@objc(cs)GFPError","kind":"typeIdentifier","text":"GFPError"},{"text":" *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"mediator:","kind":"identifier"},{"kind":"text","text":"("},{"text":"GFPUnifiedMediator","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPUnifiedMediator","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUnifiedMediator"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"mediator"},{"kind":"text","text":";"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerByLoaderDelegate\/title","value":"GFPBannerByLoaderDelegate","op":"replace"},{"op":"replace","value":[{"text":"GFPBannerByLoaderDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerByLoaderDelegate\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerByLoaderDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"GFPBannerByLoaderDelegate"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPUnifiedMediator\/title","op":"replace","value":"GFPUnifiedMediator"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPUnifiedMediator\/fragments","value":[{"kind":"identifier","text":"GFPUnifiedMediator"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPUnifiedMediator\/navigatorTitle","value":[{"kind":"identifier","text":"GFPUnifiedMediator"}]},{"value":"GFPBannerView","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerView\/title","op":"replace"},{"value":[{"kind":"identifier","text":"GFPBannerView"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerView\/fragments"},{"value":[{"text":"GFPBannerView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerView\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerByLoaderDelegate~1bannerAdLoader(_:didFailToSizeAdWithError:mediator:)\/title","value":"bannerAdLoader:didFailToSizeAdWithError:mediator:"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerByLoaderDelegate~1bannerAdLoader(_:didFailToSizeAdWithError:mediator:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"bannerAdLoader:didFailToSizeAdWithError:mediator:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}