{"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLimitQueue\/dequeue()","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"dequeue"},{"kind":"text","text":"() -> "},{"text":"GFPQueueObject","kind":"typeIdentifier","preciseIdentifier":"c:@M@GFPSDK@objc(pl)GFPQueueObject","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPQueueObject"},{"text":"?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/gfpsdk\/gfplimitqueue\/dequeue()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfplimitqueue\/dequeue()"]}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLimitQueue"]]},"metadata":{"modules":[{"name":"GFPSDK"}],"role":"symbol","roleHeading":"Instance Method","title":"dequeue()","externalID":"c:@M@GFPSDK@objc(cs)GFPLimitQueue(im)dequeue","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dequeue"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:@M@GFPSDK@objc(pl)GFPQueueObject","text":"GFPQueueObject","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"dequeue"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPLimitQueue":{"abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLimitQueue","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"GFPLimitQueue","kind":"identifier"}],"kind":"symbol","type":"topic","title":"GFPLimitQueue","url":"\/documentation\/gfpsdk\/gfplimitqueue","role":"symbol","navigatorTitle":[{"text":"GFPLimitQueue","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPQueueObject":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPQueueObject","kind":"symbol","abstract":[],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPQueueObject","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"GFPQueueObject","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpqueueobject","title":"GFPQueueObject"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPLimitQueue/dequeue()":{"title":"dequeue()","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dequeue"},{"kind":"text","text":"() -> "},{"text":"GFPQueueObject","kind":"typeIdentifier","preciseIdentifier":"c:@M@GFPSDK@objc(pl)GFPQueueObject"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"dequeue","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLimitQueue\/dequeue()","url":"\/documentation\/gfpsdk\/gfplimitqueue\/dequeue()"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"dequeue"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"dequeue","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id<GFPQueueObject>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@GFPSDK@objc(pl)GFPQueueObject"},{"kind":"text","text":") "},{"kind":"identifier","text":"dequeue"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLimitQueue\/title","value":"GFPLimitQueue"},{"op":"replace","value":[{"kind":"identifier","text":"GFPLimitQueue"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLimitQueue\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLimitQueue\/navigatorTitle","value":[{"text":"GFPLimitQueue","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPQueueObject\/title","op":"replace","value":"GFPQueueObject"},{"value":[{"text":"GFPQueueObject","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPQueueObject\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPQueueObject\/navigatorTitle","value":[{"kind":"identifier","text":"GFPQueueObject"}]},{"op":"replace","value":"dequeue","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLimitQueue~1dequeue()\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLimitQueue~1dequeue()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"dequeue"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}