{"variants":[{"paths":["\/documentation\/gfpsdk\/gfplimitqueue\/enqueue(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfplimitqueue\/enqueue(_:)"]}],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLimitQueue\/enqueue(_:)"},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLimitQueue"]]},"sections":[],"metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"enqueue","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@GFPSDK@objc(pl)GFPQueueObject","text":"GFPQueueObject"},{"text":"?)","kind":"text"}],"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"enqueue:"}],"modules":[{"name":"GFPSDK"}],"title":"enqueue(_:)","externalID":"c:@M@GFPSDK@objc(cs)GFPLimitQueue(im)enqueue:","roleHeading":"Instance Method"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"enqueue"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"queueObject","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPQueueObject","preciseIdentifier":"c:@M@GFPSDK@objc(pl)GFPQueueObject","text":"GFPQueueObject"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPQueueObject":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPQueueObject","kind":"symbol","abstract":[],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPQueueObject","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"GFPQueueObject","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpqueueobject","title":"GFPQueueObject"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPLimitQueue/enqueue(_:)":{"abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLimitQueue\/enqueue(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"enqueue"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@GFPSDK@objc(pl)GFPQueueObject","text":"GFPQueueObject","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"kind":"symbol","type":"topic","title":"enqueue(_:)","url":"\/documentation\/gfpsdk\/gfplimitqueue\/enqueue(_:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"enqueue:"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPLimitQueue":{"abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLimitQueue","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"GFPLimitQueue","kind":"identifier"}],"kind":"symbol","type":"topic","title":"GFPLimitQueue","url":"\/documentation\/gfpsdk\/gfplimitqueue","role":"symbol","navigatorTitle":[{"text":"GFPLimitQueue","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"enqueue:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"text":"- ","kind":"text"},{"text":"enqueue:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"enqueue:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Qo@M@GFPSDK@objc(pl)GFPQueueObject","text":"id<GFPQueueObject>","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"queueObject"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"value":"GFPQueueObject","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPQueueObject\/title"},{"value":[{"text":"GFPQueueObject","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPQueueObject\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPQueueObject\/navigatorTitle","value":[{"text":"GFPQueueObject","kind":"identifier"}],"op":"replace"},{"value":"enqueue:","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLimitQueue~1enqueue(_:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"enqueue:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLimitQueue~1enqueue(_:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLimitQueue\/title","op":"replace","value":"GFPLimitQueue"},{"value":[{"kind":"identifier","text":"GFPLimitQueue"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLimitQueue\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLimitQueue\/navigatorTitle","value":[{"kind":"identifier","text":"GFPLimitQueue"}]}]}]}