{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfploudnessnormalization\/properties"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfploudnessnormalization\/properties"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLoudnessNormalization"]]},"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"properties"},{"kind":"text","text":": "},{"text":"GFPProperties","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPProperties"},{"kind":"text","text":"?"}],"roleHeading":"Instance Property","symbolKind":"property","modules":[{"name":"GFPSDK"}],"role":"symbol","navigatorTitle":[{"text":"properties","kind":"identifier"}],"title":"properties","externalID":"c:objc(cs)GFPLoudnessNormalization(py)properties"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLoudnessNormalization\/properties"},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"properties"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)GFPProperties","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPProperties","text":"GFPProperties"},{"kind":"text","text":"? { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}]}]}],"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPProperties":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPProperties"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"GFPProperties"}],"url":"\/documentation\/gfpsdk\/gfpproperties","kind":"symbol","type":"topic","role":"symbol","title":"GFPProperties","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPProperties"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPLoudnessNormalization":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPLoudnessNormalization","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"GFPLoudnessNormalization"}],"kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLoudnessNormalization","type":"topic","role":"symbol","abstract":[],"url":"\/documentation\/gfpsdk\/gfploudnessnormalization","title":"GFPLoudnessNormalization"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPLoudnessNormalization/properties":{"abstract":[],"type":"topic","title":"properties","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"properties"},{"text":": ","kind":"text"},{"text":"GFPProperties","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPProperties"},{"text":"?","kind":"text"}],"url":"\/documentation\/gfpsdk\/gfploudnessnormalization\/properties","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLoudnessNormalization\/properties","navigatorTitle":[{"kind":"identifier","text":"properties"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"properties"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"properties"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPProperties","text":"GFPProperties","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPProperties"},{"text":" * ","kind":"text"},{"text":"properties","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPProperties\/title","op":"replace","value":"GFPProperties"},{"value":[{"kind":"identifier","text":"GFPProperties"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPProperties\/fragments","op":"replace"},{"value":[{"text":"GFPProperties","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPProperties\/navigatorTitle"},{"value":"GFPLoudnessNormalization","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLoudnessNormalization\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLoudnessNormalization\/fragments","value":[{"kind":"identifier","text":"GFPLoudnessNormalization"}],"op":"replace"},{"op":"replace","value":[{"text":"GFPLoudnessNormalization","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLoudnessNormalization\/navigatorTitle"},{"op":"replace","value":"properties","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLoudnessNormalization~1properties\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLoudnessNormalization~1properties\/fragments","value":[{"text":"properties","kind":"identifier"}]}]}]}