{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpnativeadinfolinkpresentable\/datatype"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpnativeadinfolinkpresentable\/datatype"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdInfoLinkPresentable"]]},"metadata":{"required":true,"title":"dataType","externalID":"c:objc(pl)GFPNativeAdInfoLinkPresentable(py)dataType","role":"symbol","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dataType","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPNativeAdDataType","text":"GFPNativeAdDataType"}],"modules":[{"name":"GFPSDK"}],"navigatorTitle":[{"text":"dataType","kind":"identifier"}],"roleHeading":"Instance Property"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"dataType","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdDataType","kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPNativeAdDataType","text":"GFPNativeAdDataType"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdInfoLinkPresentable\/dataType","interfaceLanguage":"swift"},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdInfoLinkPresentable":{"kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdInfoLinkPresentable","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GFPNativeAdInfoLinkPresentable"}],"abstract":[],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPNativeAdInfoLinkPresentable","kind":"identifier"}],"title":"GFPNativeAdInfoLinkPresentable","url":"\/documentation\/gfpsdk\/gfpnativeadinfolinkpresentable","role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdDataType":{"navigatorTitle":[{"text":"GFPNativeAdDataType","kind":"identifier"}],"type":"topic","title":"GFPNativeAdDataType","kind":"symbol","url":"\/documentation\/gfpsdk\/gfpnativeaddatatype","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdDataType","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPNativeAdDataType"}],"role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdInfoLinkPresentable/dataType":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdInfoLinkPresentable\/dataType","title":"dataType","type":"topic","navigatorTitle":[{"kind":"identifier","text":"dataType"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dataType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"GFPNativeAdDataType","kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPNativeAdDataType"}],"abstract":[],"kind":"symbol","url":"\/documentation\/gfpsdk\/gfpnativeadinfolinkpresentable\/datatype","required":true}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"dataType"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"dataType"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"assign","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdDataType","kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPNativeAdDataType","text":"GFPNativeAdDataType"},{"text":" ","kind":"text"},{"text":"dataType","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"value":"GFPNativeAdInfoLinkPresentable","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdInfoLinkPresentable\/title"},{"value":[{"kind":"identifier","text":"GFPNativeAdInfoLinkPresentable"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdInfoLinkPresentable\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdInfoLinkPresentable\/navigatorTitle","value":[{"text":"GFPNativeAdInfoLinkPresentable","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdDataType\/title","value":"GFPNativeAdDataType"},{"op":"replace","value":[{"text":"GFPNativeAdDataType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdDataType\/fragments"},{"value":[{"kind":"identifier","text":"GFPNativeAdDataType"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdDataType\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdInfoLinkPresentable~1dataType\/title","value":"dataType","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdInfoLinkPresentable~1dataType\/fragments","op":"replace","value":[{"kind":"identifier","text":"dataType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}