{"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdInfoLinkPresentable"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"link"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeLinkInfo","text":"GFPNativeLinkInfo","preciseIdentifier":"c:objc(cs)GFPNativeLinkInfo","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"metadata":{"required":true,"navigatorTitle":[{"text":"link","kind":"identifier"}],"externalID":"c:objc(pl)GFPNativeAdInfoLinkPresentable(py)link","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"link","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPNativeLinkInfo","text":"GFPNativeLinkInfo","kind":"typeIdentifier"}],"role":"symbol","modules":[{"name":"GFPSDK"}],"roleHeading":"Instance Property","title":"link"},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdInfoLinkPresentable\/link","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/gfpsdk\/gfpnativeadinfolinkpresentable\/link"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpnativeadinfolinkpresentable\/link"]}],"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeLinkInfo":{"navigatorTitle":[{"text":"GFPNativeLinkInfo","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeLinkInfo","title":"GFPNativeLinkInfo","type":"topic","url":"\/documentation\/gfpsdk\/gfpnativelinkinfo","abstract":[],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPNativeLinkInfo"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdInfoLinkPresentable/link":{"url":"\/documentation\/gfpsdk\/gfpnativeadinfolinkpresentable\/link","role":"symbol","required":true,"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdInfoLinkPresentable\/link","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"link"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPNativeLinkInfo","text":"GFPNativeLinkInfo"}],"title":"link","abstract":[],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"link"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdInfoLinkPresentable":{"kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdInfoLinkPresentable","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GFPNativeAdInfoLinkPresentable"}],"abstract":[],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPNativeAdInfoLinkPresentable","kind":"identifier"}],"title":"GFPNativeAdInfoLinkPresentable","url":"\/documentation\/gfpsdk\/gfpnativeadinfolinkpresentable","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"value":"link","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"link","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"GFPNativeLinkInfo","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeLinkInfo","preciseIdentifier":"c:objc(cs)GFPNativeLinkInfo"},{"kind":"text","text":" * "},{"kind":"identifier","text":"link"},{"text":";","kind":"text"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeLinkInfo\/title","value":"GFPNativeLinkInfo","op":"replace"},{"value":[{"text":"GFPNativeLinkInfo","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeLinkInfo\/fragments","op":"replace"},{"op":"replace","value":[{"text":"GFPNativeLinkInfo","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeLinkInfo\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdInfoLinkPresentable~1link\/title","value":"link"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdInfoLinkPresentable~1link\/fragments","value":[{"text":"link","kind":"identifier"}]},{"op":"replace","value":"GFPNativeAdInfoLinkPresentable","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdInfoLinkPresentable\/title"},{"value":[{"kind":"identifier","text":"GFPNativeAdInfoLinkPresentable"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdInfoLinkPresentable\/fragments","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"GFPNativeAdInfoLinkPresentable"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdInfoLinkPresentable\/navigatorTitle"}]}]}