{"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMraidSupportType"]]},"metadata":{"symbolKind":"property","title":"inlineVideo","modules":[{"name":"GFPSDK"}],"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"inlineVideo","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"GFPMraidSupportType","preciseIdentifier":"c:@E@GFPMraidSupportType"}],"roleHeading":"Type Property","navigatorTitle":[{"text":"GFPMraidSupportInlineVideo","kind":"identifier"}],"externalID":"c:@E@GFPMraidSupportType@GFPMraidSupportInlineVideo"},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"inlineVideo","kind":"identifier"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMraidSupportType","preciseIdentifier":"c:@E@GFPMraidSupportType","kind":"typeIdentifier","text":"GFPMraidSupportType"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMraidSupportType\/inlineVideo"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpmraidsupporttype\/inlinevideo"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpmraidsupporttype\/inlinevideo"]}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPMraidSupportType":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPMraidSupportType"}],"kind":"symbol","navigatorTitle":[{"text":"GFPMraidSupportType","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMraidSupportType","abstract":[],"role":"symbol","url":"\/documentation\/gfpsdk\/gfpmraidsupporttype","title":"GFPMraidSupportType","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPMraidSupportType/inlineVideo":{"type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMraidSupportType\/inlineVideo","url":"\/documentation\/gfpsdk\/gfpmraidsupporttype\/inlinevideo","kind":"symbol","title":"inlineVideo","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"inlineVideo","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPMraidSupportType","text":"GFPMraidSupportType"}],"role":"symbol","abstract":[],"navigatorTitle":[{"text":"GFPMraidSupportInlineVideo","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"GFPMraidSupportInlineVideo","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"GFPMraidSupportInlineVideo"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"GFPMraidSupportInlineVideo"}]}]}},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMraidSupportType\/title","value":"GFPMraidSupportType","op":"replace"},{"value":[{"text":"GFPMraidSupportType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMraidSupportType\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMraidSupportType\/navigatorTitle","value":[{"text":"GFPMraidSupportType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMraidSupportType~1inlineVideo\/title","value":"GFPMraidSupportInlineVideo","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMraidSupportType~1inlineVideo\/fragments","value":[{"kind":"identifier","text":"GFPMraidSupportInlineVideo"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}