{"variants":[{"paths":["\/documentation\/gfpsdk\/gfpmraidsupporttype\/picture"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gfpsdk\/gfpmraidsupporttype\/picture"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMraidSupportType"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"picture"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMraidSupportType","preciseIdentifier":"c:@E@GFPMraidSupportType","text":"GFPMraidSupportType"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMraidSupportType\/picture"},"kind":"symbol","metadata":{"symbolKind":"property","title":"picture","modules":[{"name":"GFPSDK"}],"role":"symbol","externalID":"c:@E@GFPMraidSupportType@GFPMraidSupportPicture","roleHeading":"Type Property","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"picture","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@GFPMraidSupportType","text":"GFPMraidSupportType","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"GFPMraidSupportPicture","kind":"identifier"}]},"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPMraidSupportType/picture":{"type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMraidSupportType\/picture","url":"\/documentation\/gfpsdk\/gfpmraidsupporttype\/picture","kind":"symbol","title":"picture","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"picture","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPMraidSupportType","text":"GFPMraidSupportType"}],"role":"symbol","abstract":[],"navigatorTitle":[{"text":"GFPMraidSupportPicture","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPMraidSupportType":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPMraidSupportType"}],"kind":"symbol","navigatorTitle":[{"text":"GFPMraidSupportType","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMraidSupportType","abstract":[],"role":"symbol","url":"\/documentation\/gfpsdk\/gfpmraidsupporttype","title":"GFPMraidSupportType","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","value":"GFPMraidSupportPicture","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GFPMraidSupportPicture"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"GFPMraidSupportPicture"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMraidSupportType~1picture\/title","value":"GFPMraidSupportPicture"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMraidSupportType~1picture\/fragments","value":[{"kind":"identifier","text":"GFPMraidSupportPicture"}],"op":"replace"},{"value":"GFPMraidSupportType","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMraidSupportType\/title"},{"op":"replace","value":[{"kind":"identifier","text":"GFPMraidSupportType"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMraidSupportType\/fragments"},{"value":[{"text":"GFPMraidSupportType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMraidSupportType\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}