{"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMraidSupportType\/VPAID","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"VPAID","kind":"identifier"},{"text":": ","kind":"text"},{"text":"GFPMraidSupportType","preciseIdentifier":"c:@E@GFPMraidSupportType","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMraidSupportType","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"modules":[{"name":"GFPSDK"}],"role":"symbol","title":"VPAID","externalID":"c:@E@GFPMraidSupportType@GFPMraidSupportVPAID","roleHeading":"Type Property","symbolKind":"property","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"VPAID"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"GFPMraidSupportType","preciseIdentifier":"c:@E@GFPMraidSupportType"}],"navigatorTitle":[{"kind":"identifier","text":"GFPMraidSupportVPAID"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpmraidsupporttype\/vpaid"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpmraidsupporttype\/vpaid"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMraidSupportType"]]},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPMraidSupportType/VPAID":{"type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMraidSupportType\/VPAID","url":"\/documentation\/gfpsdk\/gfpmraidsupporttype\/vpaid","kind":"symbol","title":"VPAID","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"VPAID"},{"kind":"text","text":": "},{"text":"GFPMraidSupportType","kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPMraidSupportType"}],"role":"symbol","abstract":[],"navigatorTitle":[{"text":"GFPMraidSupportVPAID","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPMraidSupportType":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPMraidSupportType"}],"kind":"symbol","navigatorTitle":[{"text":"GFPMraidSupportType","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMraidSupportType","abstract":[],"role":"symbol","url":"\/documentation\/gfpsdk\/gfpmraidsupporttype","title":"GFPMraidSupportType","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"GFPMraidSupportVPAID"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GFPMraidSupportVPAID"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"GFPMraidSupportVPAID","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMraidSupportType~1VPAID\/title","op":"replace","value":"GFPMraidSupportVPAID"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMraidSupportType~1VPAID\/fragments","op":"replace","value":[{"text":"GFPMraidSupportVPAID","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMraidSupportType\/title","value":"GFPMraidSupportType","op":"replace"},{"value":[{"text":"GFPMraidSupportType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMraidSupportType\/fragments"},{"value":[{"kind":"identifier","text":"GFPMraidSupportType"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMraidSupportType\/navigatorTitle"}]}]}