{"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPEventReportDelegate"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/gfpsdk\/gfpeventreportdelegate\/reporttrackingattachedimp(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gfpsdk\/gfpeventreportdelegate\/reporttrackingattachedimp(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPEventReportDelegate\/reportTrackingAttachedImp(_:)","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"text":"reportTrackingAttachedImp:","kind":"identifier"}],"role":"symbol","title":"reportTrackingAttachedImp(_:)","required":true,"roleHeading":"Instance Method","symbolKind":"method","externalID":"c:objc(pl)GFPEventReportDelegate(im)reportTrackingAttachedImp:","modules":[{"name":"GFPSDK"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"reportTrackingAttachedImp"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"reportTrackingAttachedImp","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"aUrl"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":")","kind":"text"}]}],"kind":"declarations"}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPEventReportDelegate":{"kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPEventReportDelegate","title":"GFPEventReportDelegate","url":"\/documentation\/gfpsdk\/gfpeventreportdelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"GFPEventReportDelegate","kind":"identifier"}],"abstract":[],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPEventReportDelegate"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPEventReportDelegate/reportTrackingAttachedImp(_:)":{"abstract":[],"required":true,"url":"\/documentation\/gfpsdk\/gfpeventreportdelegate\/reporttrackingattachedimp(_:)","role":"symbol","title":"reportTrackingAttachedImp(_:)","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPEventReportDelegate\/reportTrackingAttachedImp(_:)","navigatorTitle":[{"kind":"identifier","text":"reportTrackingAttachedImp:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"reportTrackingAttachedImp"},{"kind":"text","text":"("},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"reportTrackingAttachedImp:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"reportTrackingAttachedImp:"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"reportTrackingAttachedImp:"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"aUrl","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"GFPEventReportDelegate","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPEventReportDelegate\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPEventReportDelegate\/fragments","op":"replace","value":[{"text":"GFPEventReportDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPEventReportDelegate\/navigatorTitle","value":[{"text":"GFPEventReportDelegate","kind":"identifier"}]},{"value":"reportTrackingAttachedImp:","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPEventReportDelegate~1reportTrackingAttachedImp(_:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"reportTrackingAttachedImp:"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPEventReportDelegate~1reportTrackingAttachedImp(_:)\/fragments"}]}]}