{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"reportTrackingRenderedImp","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"aUrl","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"required":true,"symbolKind":"method","externalID":"c:objc(pl)GFPEventReportDelegate(im)reportTrackingRenderedImp:","modules":[{"name":"GFPSDK"}],"title":"reportTrackingRenderedImp(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"reportTrackingRenderedImp"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"reportTrackingRenderedImp:"}],"roleHeading":"Instance Method"},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","variants":[{"paths":["\/documentation\/gfpsdk\/gfpeventreportdelegate\/reporttrackingrenderedimp(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpeventreportdelegate\/reporttrackingrenderedimp(_:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPEventReportDelegate\/reportTrackingRenderedImp(_:)"},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPEventReportDelegate"]]},"sections":[],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPEventReportDelegate":{"kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPEventReportDelegate","title":"GFPEventReportDelegate","url":"\/documentation\/gfpsdk\/gfpeventreportdelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"GFPEventReportDelegate","kind":"identifier"}],"abstract":[],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPEventReportDelegate"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPEventReportDelegate/reportTrackingRenderedImp(_:)":{"kind":"symbol","required":true,"abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"reportTrackingRenderedImp","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"title":"reportTrackingRenderedImp(_:)","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPEventReportDelegate\/reportTrackingRenderedImp(_:)","type":"topic","role":"symbol","navigatorTitle":[{"text":"reportTrackingRenderedImp:","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpeventreportdelegate\/reporttrackingrenderedimp(_:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"value":"reportTrackingRenderedImp:","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"text":"reportTrackingRenderedImp:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"reportTrackingRenderedImp:"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"aUrl"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPEventReportDelegate\/title","op":"replace","value":"GFPEventReportDelegate"},{"value":[{"text":"GFPEventReportDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPEventReportDelegate\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPEventReportDelegate\/navigatorTitle","value":[{"text":"GFPEventReportDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPEventReportDelegate~1reportTrackingRenderedImp(_:)\/title","value":"reportTrackingRenderedImp:","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPEventReportDelegate~1reportTrackingRenderedImp(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"reportTrackingRenderedImp:"}],"op":"replace"}]}]}