{"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdProviderSettingType"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpadprovidersettingtype\/gfpadprovidersettingtypenone"]}],"metadata":{"role":"symbol","externalID":"c:@E@GFPAdProviderSettingType@GFPAdProviderSettingTypeNone","symbolKind":"case","modules":[{"name":"GFPSDK"}],"title":"GFPAdProviderSettingTypeNone","roleHeading":"Enumeration Case","fragments":[{"kind":"identifier","text":"GFPAdProviderSettingTypeNone"}],"navigatorTitle":[{"kind":"identifier","text":"GFPAdProviderSettingTypeNone"}]},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdProviderSettingType\/GFPAdProviderSettingTypeNone","interfaceLanguage":"occ"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"GFPAdProviderSettingTypeNone","kind":"identifier"}],"platforms":["iOS"]}]}],"sections":[],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdProviderSettingType/GFPAdProviderSettingTypeNone":{"url":"\/documentation\/gfpsdk\/gfpadprovidersettingtype\/gfpadprovidersettingtypenone","title":"GFPAdProviderSettingTypeNone","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdProviderSettingType\/GFPAdProviderSettingTypeNone","role":"symbol","kind":"symbol","type":"topic","fragments":[{"text":"GFPAdProviderSettingTypeNone","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdProviderSettingType":{"abstract":[],"role":"symbol","navigatorTitle":[{"text":"GFPAdProviderSettingType","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPAdProviderSettingType","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpadprovidersettingtype","title":"GFPAdProviderSettingType","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdProviderSettingType","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"GFPAdProviderSettingType","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdProviderSettingType\/title"},{"value":[{"kind":"identifier","text":"GFPAdProviderSettingType"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdProviderSettingType\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdProviderSettingType\/navigatorTitle","value":[{"kind":"identifier","text":"GFPAdProviderSettingType"}]}]}]}