{"abstract":[{"type":"text","text":"Inherited from "},{"code":"SetAlgebra.isEmpty","type":"codeVoice"},{"type":"text","text":"."}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"metadata":{"symbolKind":"property","title":"isEmpty","modules":[{"name":"GFPSDK","relatedModules":["Swift"]}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isEmpty"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"roleHeading":"Instance Property","externalID":"s:s10SetAlgebraPsE7isEmptySbvp::SYNTHESIZED::c:@E@GFPAdProviderSettingType","extendedModule":"Swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEmpty"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpadprovidersettingtype\/isempty"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdProviderSettingType","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdProviderSettingType\/SetAlgebra-Implementations"]]},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdProviderSettingType\/isEmpty","interfaceLanguage":"swift"},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdProviderSettingType":{"abstract":[],"role":"symbol","navigatorTitle":[{"text":"GFPAdProviderSettingType","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPAdProviderSettingType","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpadprovidersettingtype","title":"GFPAdProviderSettingType","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdProviderSettingType","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdProviderSettingType/SetAlgebra-Implementations":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdProviderSettingType\/SetAlgebra-Implementations","type":"topic","url":"\/documentation\/gfpsdk\/gfpadprovidersettingtype\/setalgebra-implementations","abstract":[],"kind":"article","title":"SetAlgebra Implementations","role":"collectionGroup"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdProviderSettingType/isEmpty":{"kind":"symbol","title":"isEmpty","url":"\/documentation\/gfpsdk\/gfpadprovidersettingtype\/isempty","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"isEmpty","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdProviderSettingType\/isEmpty","abstract":[]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdProviderSettingType\/title","value":"GFPAdProviderSettingType","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdProviderSettingType\/fragments","value":[{"text":"GFPAdProviderSettingType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdProviderSettingType\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"GFPAdProviderSettingType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}