{"metadata":{"role":"symbol","modules":[{"name":"GFPSDK"}],"externalID":"c:@E@GFPAdProviderSettingType@GFPAdProviderSettingTypeLAN","roleHeading":"Type Property","symbolKind":"property","title":"LAN","navigatorTitle":[{"kind":"identifier","text":"GFPAdProviderSettingTypeLAN"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"LAN"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@GFPAdProviderSettingType","text":"GFPAdProviderSettingType","kind":"typeIdentifier"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdProviderSettingType\/LAN","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdProviderSettingType"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"LAN","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdProviderSettingType","text":"GFPAdProviderSettingType","preciseIdentifier":"c:@E@GFPAdProviderSettingType","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpadprovidersettingtype\/lan"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpadprovidersettingtype\/lan"]}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdProviderSettingType":{"abstract":[],"role":"symbol","navigatorTitle":[{"text":"GFPAdProviderSettingType","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPAdProviderSettingType","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpadprovidersettingtype","title":"GFPAdProviderSettingType","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdProviderSettingType","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdProviderSettingType/LAN":{"url":"\/documentation\/gfpsdk\/gfpadprovidersettingtype\/lan","title":"LAN","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdProviderSettingType\/LAN","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"GFPAdProviderSettingTypeLAN","kind":"identifier"}],"type":"topic","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"LAN"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@GFPAdProviderSettingType","kind":"typeIdentifier","text":"GFPAdProviderSettingType"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"GFPAdProviderSettingTypeLAN"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"value":[{"text":"GFPAdProviderSettingTypeLAN","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"GFPAdProviderSettingTypeLAN"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdProviderSettingType\/title","value":"GFPAdProviderSettingType","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdProviderSettingType\/fragments","value":[{"text":"GFPAdProviderSettingType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdProviderSettingType\/navigatorTitle","value":[{"text":"GFPAdProviderSettingType","kind":"identifier"}]},{"value":"GFPAdProviderSettingTypeLAN","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdProviderSettingType~1LAN\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdProviderSettingType~1LAN\/fragments","value":[{"text":"GFPAdProviderSettingTypeLAN","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}