{"abstract":[{"type":"text","text":"광고 자동 재생 비활성화 전역 설정 (기본값 NO)"},{"text":" ","type":"text"},{"text":"단, S2S 아웃스트림 광고에 한해 useGlobalOptions이 활성화 되었을 경우 적용됩니다.","type":"text"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"disableAutoPlayback"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}]}]},{"content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"items":[{"content":[{"inlineContent":[{"type":"text","text":"YES: YES로 설정 시 재생되는 광고가 정지하며, 재생 조건 도달 시에도 광고를 재생시키지 않습니다."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"NO: NO로 설정 시 재생 조건 도달 시 광고를 재생합니다."}],"type":"paragraph"}]}],"type":"unorderedList"}],"kind":"content"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpvideoglobaloptions\/disableautoplayback"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpvideoglobaloptions\/disableautoplayback"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoGlobalOptions\/disableAutoPlayback"},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoGlobalOptions"]]},"metadata":{"externalID":"c:objc(cs)GFPVideoGlobalOptions(cpy)disableAutoPlayback","navigatorTitle":[{"text":"disableAutoPlayback","kind":"identifier"}],"title":"disableAutoPlayback","role":"symbol","symbolKind":"property","roleHeading":"Type Property","modules":[{"name":"GFPSDK"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"disableAutoPlayback","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoGlobalOptions/disableAutoPlayback":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoGlobalOptions\/disableAutoPlayback","url":"\/documentation\/gfpsdk\/gfpvideoglobaloptions\/disableautoplayback","role":"symbol","title":"disableAutoPlayback","kind":"symbol","abstract":[{"type":"text","text":"광고 자동 재생 비활성화 전역 설정 (기본값 NO)"},{"text":" ","type":"text"},{"text":"단, S2S 아웃스트림 광고에 한해 useGlobalOptions이 활성화 되었을 경우 적용됩니다.","type":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"disableAutoPlayback"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"disableAutoPlayback","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoGlobalOptions":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoGlobalOptions","url":"\/documentation\/gfpsdk\/gfpvideoglobaloptions","role":"symbol","title":"GFPVideoGlobalOptions","kind":"symbol","abstract":[],"type":"topic","navigatorTitle":[{"text":"GFPVideoGlobalOptions","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPVideoGlobalOptions"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Property"},{"path":"\/metadata\/title","value":"disableAutoPlayback","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"disableAutoPlayback"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"class"},{"text":", ","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"assign","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"disableAutoPlayback","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoGlobalOptions~1disableAutoPlayback\/title","op":"replace","value":"disableAutoPlayback"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoGlobalOptions~1disableAutoPlayback\/fragments","value":[{"kind":"identifier","text":"disableAutoPlayback"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoGlobalOptions\/title","op":"replace","value":"GFPVideoGlobalOptions"},{"value":[{"kind":"identifier","text":"GFPVideoGlobalOptions"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoGlobalOptions\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"GFPVideoGlobalOptions"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoGlobalOptions\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}