{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"abstract":[{"type":"text","text":"광고 자동 재생 정책 전역 설정 (기본값 Auto)"},{"type":"text","text":" "},{"type":"text","text":"단, S2S 아웃스트림 광고에 한해 useGlobalOptions이 활성화 되었을 경우 적용됩니다."}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"globalPlayPolicy"}],"externalID":"c:objc(cs)GFPVideoGlobalOptions(cpy)globalPlayPolicy","symbolKind":"property","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"globalPlayPolicy"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@GFPVideoPlayPolicy","text":"GFPVideoPlayPolicy","kind":"typeIdentifier"}],"modules":[{"name":"GFPSDK"}],"roleHeading":"Type Property","role":"symbol","title":"globalPlayPolicy"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpvideoglobaloptions\/globalplaypolicy"]},{"paths":["\/documentation\/gfpsdk\/gfpvideoglobaloptions\/globalplaypolicy"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"globalPlayPolicy","kind":"identifier"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoPlayPolicy","kind":"typeIdentifier","text":"GFPVideoPlayPolicy","preciseIdentifier":"c:@E@GFPVideoPlayPolicy"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}]}],"kind":"declarations"},{"kind":"content","content":[{"level":2,"text":"Discussion","type":"heading","anchor":"discussion"},{"items":[{"content":[{"inlineContent":[{"text":"Auto: 네트워크가 WiFi, Cellular 일 때 영상 끝까지 재생됩니다.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Auto Only WiFi: 네트워크가 WiFi 일 때 영상 끝까지 재생됩니다. Cellular의 경우 n초 재생 후 정지합니다."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Manual: 광고 노출 시 영상이 일시정지 상태에서 노출됩니다. 재생 시점은 서비스에서 결정합니다."}]}]}],"type":"unorderedList"}]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoGlobalOptions"]]},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoGlobalOptions\/globalPlayPolicy","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoGlobalOptions":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoGlobalOptions","url":"\/documentation\/gfpsdk\/gfpvideoglobaloptions","role":"symbol","title":"GFPVideoGlobalOptions","kind":"symbol","abstract":[],"type":"topic","navigatorTitle":[{"text":"GFPVideoGlobalOptions","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPVideoGlobalOptions"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoPlayPolicy":{"abstract":[],"title":"GFPVideoPlayPolicy","url":"\/documentation\/gfpsdk\/gfpvideoplaypolicy","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPVideoPlayPolicy","kind":"identifier"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPVideoPlayPolicy"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoPlayPolicy","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoGlobalOptions/globalPlayPolicy":{"role":"symbol","abstract":[{"text":"광고 자동 재생 정책 전역 설정 (기본값 Auto)","type":"text"},{"type":"text","text":" "},{"text":"단, S2S 아웃스트림 광고에 한해 useGlobalOptions이 활성화 되었을 경우 적용됩니다.","type":"text"}],"title":"globalPlayPolicy","navigatorTitle":[{"text":"globalPlayPolicy","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"globalPlayPolicy","kind":"identifier"},{"kind":"text","text":": "},{"text":"GFPVideoPlayPolicy","preciseIdentifier":"c:@E@GFPVideoPlayPolicy","kind":"typeIdentifier"}],"url":"\/documentation\/gfpsdk\/gfpvideoglobaloptions\/globalplaypolicy","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoGlobalOptions\/globalPlayPolicy","kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Type Property","op":"replace"},{"path":"\/metadata\/title","value":"globalPlayPolicy","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"globalPlayPolicy"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":", "},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"GFPVideoPlayPolicy","preciseIdentifier":"c:@E@GFPVideoPlayPolicy","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoPlayPolicy"},{"kind":"text","text":" "},{"kind":"identifier","text":"globalPlayPolicy"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoGlobalOptions\/title","value":"GFPVideoGlobalOptions"},{"value":[{"text":"GFPVideoGlobalOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoGlobalOptions\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoGlobalOptions\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"GFPVideoGlobalOptions"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoPlayPolicy\/title","value":"GFPVideoPlayPolicy","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoPlayPolicy\/fragments","op":"replace","value":[{"text":"GFPVideoPlayPolicy","kind":"identifier"}]},{"value":[{"text":"GFPVideoPlayPolicy","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoPlayPolicy\/navigatorTitle"},{"op":"replace","value":"globalPlayPolicy","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoGlobalOptions~1globalPlayPolicy\/title"},{"value":[{"text":"globalPlayPolicy","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoGlobalOptions~1globalPlayPolicy\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}