{"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpadnativeoptions\/init"]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdNativeOptions"]]},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"kind":"identifier","text":"init"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdNativeOptions\/init","interfaceLanguage":"occ"},"kind":"symbol","metadata":{"symbolKind":"method","title":"init","modules":[{"name":"GFPSDK"}],"role":"symbol","externalID":"c:@M@GFPSDK@objc(cs)GFPAdNativeOptions(im)init","roleHeading":"Instance Method","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"navigatorTitle":[{"kind":"identifier","text":"init"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdNativeOptions/init":{"navigatorTitle":[{"kind":"identifier","text":"init"}],"title":"init","url":"\/documentation\/gfpsdk\/gfpadnativeoptions\/init","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdNativeOptions\/init","role":"symbol","type":"topic","kind":"symbol","abstract":[],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdNativeOptions":{"navigatorTitle":[{"kind":"identifier","text":"GFPAdNativeOptions"}],"url":"\/documentation\/gfpsdk\/gfpadnativeoptions","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPAdNativeOptions","kind":"identifier"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdNativeOptions","abstract":[],"title":"GFPAdNativeOptions"}},"variantOverrides":[{"patch":[{"value":"GFPAdNativeOptions","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdNativeOptions\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdNativeOptions\/fragments","value":[{"kind":"identifier","text":"GFPAdNativeOptions"}]},{"value":[{"text":"GFPAdNativeOptions","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdNativeOptions\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}