{"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"symbolKind":"init","modules":[{"name":"GFPSDK"}],"title":"init(dictionary:link:)","roleHeading":"Initializer","externalID":"c:objc(cs)GFPNativeMediaExtensionInfo(im)initWithDictionary:link:","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"text":"dictionary","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"text":"]?, ","kind":"text"},{"kind":"externalParam","text":"link"},{"kind":"text","text":": "},{"text":"GFPNativeLinkInfo","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPNativeLinkInfo"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"initWithDictionary:link:","kind":"identifier"}]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeMediaExtensionInfo\/init(dictionary:link:)"},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeMediaExtensionInfo"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"init","kind":"keyword"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"dictionary"},{"text":" ","kind":"text"},{"text":"aDict","kind":"internalParam"},{"text":": [","kind":"text"},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"link"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPNativeLinkInfo","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeLinkInfo","kind":"typeIdentifier","text":"GFPNativeLinkInfo"},{"kind":"text","text":")"}],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpnativemediaextensioninfo\/init(dictionary:link:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gfpsdk\/gfpnativemediaextensioninfo\/init(dictionary:link:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeMediaExtensionInfo/init(dictionary:link:)":{"role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeMediaExtensionInfo\/init(dictionary:link:)","type":"topic","abstract":[],"url":"\/documentation\/gfpsdk\/gfpnativemediaextensioninfo\/init(dictionary:link:)","title":"init(dictionary:link:)","navigatorTitle":[{"text":"initWithDictionary:link:","kind":"identifier"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"dictionary","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier","text":"AnyHashable"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"]?, ","kind":"text"},{"kind":"externalParam","text":"link"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPNativeLinkInfo","text":"GFPNativeLinkInfo"},{"kind":"text","text":")"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeMediaExtensionInfo":{"url":"\/documentation\/gfpsdk\/gfpnativemediaextensioninfo","abstract":[],"title":"GFPNativeMediaExtensionInfo","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeMediaExtensionInfo","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPNativeMediaExtensionInfo"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPNativeMediaExtensionInfo","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeLinkInfo":{"navigatorTitle":[{"text":"GFPNativeLinkInfo","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeLinkInfo","title":"GFPNativeLinkInfo","type":"topic","url":"\/documentation\/gfpsdk\/gfpnativelinkinfo","abstract":[],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPNativeLinkInfo"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"initWithDictionary:link:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"initWithDictionary:link:","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithDictionary:"},{"text":"(","kind":"text"},{"text":"NSDictionary","preciseIdentifier":"c:objc(cs)NSDictionary","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"aDict","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"link:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)GFPNativeLinkInfo","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeLinkInfo","kind":"typeIdentifier","text":"GFPNativeLinkInfo"},{"kind":"text","text":" *) "},{"text":"link","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace"},{"value":"initWithDictionary:link:","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeMediaExtensionInfo~1init(dictionary:link:)\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeMediaExtensionInfo~1init(dictionary:link:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithDictionary:link:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeMediaExtensionInfo\/title","value":"GFPNativeMediaExtensionInfo"},{"op":"replace","value":[{"text":"GFPNativeMediaExtensionInfo","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeMediaExtensionInfo\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeMediaExtensionInfo\/navigatorTitle","value":[{"kind":"identifier","text":"GFPNativeMediaExtensionInfo"}]},{"op":"replace","value":"GFPNativeLinkInfo","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeLinkInfo\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeLinkInfo\/fragments","value":[{"kind":"identifier","text":"GFPNativeLinkInfo"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeLinkInfo\/navigatorTitle","value":[{"kind":"identifier","text":"GFPNativeLinkInfo"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}