{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeMediaExtensionInfo"]]},"sections":[],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"removeRichInfo"}],"externalID":"c:objc(cs)GFPNativeMediaExtensionInfo(im)removeRichInfo","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"removeRichInfo"},{"kind":"text","text":"()"}],"symbolKind":"method","roleHeading":"Instance Method","title":"removeRichInfo()","modules":[{"name":"GFPSDK"}],"role":"symbol"},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeMediaExtensionInfo\/removeRichInfo()","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpnativemediaextensioninfo\/removerichinfo()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpnativemediaextensioninfo\/removerichinfo()"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"removeRichInfo","kind":"identifier"},{"text":"()","kind":"text"}]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeMediaExtensionInfo/removeRichInfo()":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeMediaExtensionInfo\/removeRichInfo()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"removeRichInfo","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"removeRichInfo"}],"type":"topic","role":"symbol","url":"\/documentation\/gfpsdk\/gfpnativemediaextensioninfo\/removerichinfo()","title":"removeRichInfo()","kind":"symbol","abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeMediaExtensionInfo":{"url":"\/documentation\/gfpsdk\/gfpnativemediaextensioninfo","abstract":[],"title":"GFPNativeMediaExtensionInfo","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeMediaExtensionInfo","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPNativeMediaExtensionInfo"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPNativeMediaExtensionInfo","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"removeRichInfo","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"removeRichInfo"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"removeRichInfo","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeMediaExtensionInfo~1removeRichInfo()\/title","value":"removeRichInfo"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"removeRichInfo","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeMediaExtensionInfo~1removeRichInfo()\/fragments"},{"op":"replace","value":"GFPNativeMediaExtensionInfo","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeMediaExtensionInfo\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeMediaExtensionInfo\/fragments","op":"replace","value":[{"text":"GFPNativeMediaExtensionInfo","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeMediaExtensionInfo\/navigatorTitle","value":[{"text":"GFPNativeMediaExtensionInfo","kind":"identifier"}],"op":"replace"}]}]}