{"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdMediaType"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"image","kind":"identifier"}]}]}],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpnativeadmediatype\/image"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gfpsdk\/gfpnativeadmediatype\/image"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdMediaType\/image","interfaceLanguage":"swift"},"metadata":{"role":"symbol","symbolKind":"case","modules":[{"name":"GFPSDK"}],"roleHeading":"Case","externalID":"c:@E@GFPNativeAdMediaType@GFPNativeAdMediaTypeImage","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"image","kind":"identifier"}],"navigatorTitle":[{"text":"GFPNativeAdMediaTypeImage","kind":"identifier"}],"title":"GFPNativeAdMediaType.image"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdMediaType/image":{"title":"GFPNativeAdMediaType.image","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdMediaType\/image","role":"symbol","kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"image"}],"navigatorTitle":[{"kind":"identifier","text":"GFPNativeAdMediaTypeImage"}],"type":"topic","url":"\/documentation\/gfpsdk\/gfpnativeadmediatype\/image"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdMediaType":{"url":"\/documentation\/gfpsdk\/gfpnativeadmediatype","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdMediaType","type":"topic","kind":"symbol","title":"GFPNativeAdMediaType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"GFPNativeAdMediaType","kind":"identifier"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"GFPNativeAdMediaType"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"GFPNativeAdMediaTypeImage","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"GFPNativeAdMediaTypeImage"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"GFPNativeAdMediaTypeImage","kind":"identifier"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdMediaType~1image\/title","value":"GFPNativeAdMediaTypeImage","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdMediaType~1image\/fragments","value":[{"text":"GFPNativeAdMediaTypeImage","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdMediaType\/title","value":"GFPNativeAdMediaType"},{"value":[{"text":"GFPNativeAdMediaType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdMediaType\/fragments"},{"value":[{"text":"GFPNativeAdMediaType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdMediaType\/navigatorTitle"}]}]}