{"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"GFPNativeAdMediaTypeSVG"}],"role":"symbol","symbolKind":"case","title":"GFPNativeAdMediaType.SVG","roleHeading":"Case","externalID":"c:@E@GFPNativeAdMediaType@GFPNativeAdMediaTypeSVG","modules":[{"name":"GFPSDK"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"SVG"}]},"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdMediaType\/SVG"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"SVG","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpnativeadmediatype\/svg"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpnativeadmediatype\/svg"]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdMediaType"]]},"sections":[],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdMediaType":{"url":"\/documentation\/gfpsdk\/gfpnativeadmediatype","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdMediaType","type":"topic","kind":"symbol","title":"GFPNativeAdMediaType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"GFPNativeAdMediaType","kind":"identifier"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"GFPNativeAdMediaType"}],"role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdMediaType/SVG":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SVG"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdMediaType\/SVG","type":"topic","kind":"symbol","title":"GFPNativeAdMediaType.SVG","role":"symbol","abstract":[],"url":"\/documentation\/gfpsdk\/gfpnativeadmediatype\/svg","navigatorTitle":[{"text":"GFPNativeAdMediaTypeSVG","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","value":"GFPNativeAdMediaTypeSVG","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"text":"GFPNativeAdMediaTypeSVG","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"GFPNativeAdMediaTypeSVG"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdMediaType\/title","value":"GFPNativeAdMediaType","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"GFPNativeAdMediaType"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdMediaType\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdMediaType\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"GFPNativeAdMediaType"}]},{"value":"GFPNativeAdMediaTypeSVG","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdMediaType~1SVG\/title"},{"op":"replace","value":[{"kind":"identifier","text":"GFPNativeAdMediaTypeSVG"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdMediaType~1SVG\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}