{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdMediaType\/unknown"},"sections":[],"metadata":{"modules":[{"name":"GFPSDK"}],"title":"GFPNativeAdMediaType.unknown","navigatorTitle":[{"text":"GFPNativeAdMediaTypeUnknown","kind":"identifier"}],"roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unknown"}],"symbolKind":"case","role":"symbol","externalID":"c:@E@GFPNativeAdMediaType@GFPNativeAdMediaTypeUnknown"},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"unknown","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdMediaType"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpnativeadmediatype\/unknown"]},{"paths":["\/documentation\/gfpsdk\/gfpnativeadmediatype\/unknown"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdMediaType/unknown":{"title":"GFPNativeAdMediaType.unknown","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"unknown","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdMediaType\/unknown","abstract":[],"kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/gfpsdk\/gfpnativeadmediatype\/unknown","navigatorTitle":[{"kind":"identifier","text":"GFPNativeAdMediaTypeUnknown"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdMediaType":{"url":"\/documentation\/gfpsdk\/gfpnativeadmediatype","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdMediaType","type":"topic","kind":"symbol","title":"GFPNativeAdMediaType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"GFPNativeAdMediaType","kind":"identifier"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"GFPNativeAdMediaType"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"value":"GFPNativeAdMediaTypeUnknown","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"kind":"identifier","text":"GFPNativeAdMediaTypeUnknown"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"GFPNativeAdMediaTypeUnknown","kind":"identifier"}],"platforms":["iOS"]}]}},{"value":"GFPNativeAdMediaTypeUnknown","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdMediaType~1unknown\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdMediaType~1unknown\/fragments","value":[{"text":"GFPNativeAdMediaTypeUnknown","kind":"identifier"}]},{"value":"GFPNativeAdMediaType","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdMediaType\/title"},{"op":"replace","value":[{"kind":"identifier","text":"GFPNativeAdMediaType"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdMediaType\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdMediaType\/navigatorTitle","value":[{"kind":"identifier","text":"GFPNativeAdMediaType"}]}]}]}