{"metadata":{"role":"symbol","externalID":"c:objc(pl)GFPVideoAdQoeDelegate(im)videoAdManager:didStartAdWithQoeInfo:","required":true,"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"videoAdManager","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPVideoAdManager","text":"GFPVideoAdManager","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didStartAdWith"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPVideoAdQoeInfo","text":"GFPVideoAdQoeInfo","kind":"typeIdentifier"},{"text":")","kind":"text"}],"modules":[{"name":"GFPSDK"}],"symbolKind":"method","title":"videoAdManager(_:didStartAdWith:)","roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"videoAdManager:didStartAdWithQoeInfo:"}]},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdQoeDelegate\/videoAdManager(_:didStartAdWith:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"광고가 시작 된 경우 발생"}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdQoeDelegate"]]},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"videoAdManager"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"videoAdManager","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"GFPVideoAdManager","preciseIdentifier":"c:objc(cs)GFPVideoAdManager","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager"},{"text":", ","kind":"text"},{"text":"didStartAdWith","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"info"},{"kind":"text","text":": "},{"text":"GFPVideoAdQoeInfo","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdQoeInfo","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoAdQoeInfo"},{"text":")","kind":"text"}]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"비디오 매니저"}]}],"name":"videoAdManager"},{"content":[{"inlineContent":[{"type":"text","text":"QOE 정보"}],"type":"paragraph"}],"name":"info"}],"kind":"parameters"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpvideoadqoedelegate\/videoadmanager(_:didstartadwith:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpvideoadqoedelegate\/videoadmanager(_:didstartadwith:)"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdQoeInfo":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"GFPVideoAdQoeInfo"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdQoeInfo","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPVideoAdQoeInfo","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpvideoadqoeinfo","role":"symbol","kind":"symbol","title":"GFPVideoAdQoeInfo"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdManager":{"type":"topic","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager","role":"symbol","url":"\/documentation\/gfpsdk\/gfpvideoadmanager","title":"GFPVideoAdManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPVideoAdManager"}],"kind":"symbol","navigatorTitle":[{"text":"GFPVideoAdManager","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdQoeDelegate/videoAdManager(_:didStartAdWith:)":{"required":true,"navigatorTitle":[{"text":"videoAdManager:didStartAdWithQoeInfo:","kind":"identifier"}],"title":"videoAdManager(_:didStartAdWith:)","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdQoeDelegate\/videoAdManager(_:didStartAdWith:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"videoAdManager"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPVideoAdManager","text":"GFPVideoAdManager","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didStartAdWith","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"GFPVideoAdQoeInfo","preciseIdentifier":"c:objc(cs)GFPVideoAdQoeInfo"},{"text":")","kind":"text"}],"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"광고가 시작 된 경우 발생"}],"url":"\/documentation\/gfpsdk\/gfpvideoadqoedelegate\/videoadmanager(_:didstartadwith:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdQoeDelegate":{"title":"GFPVideoAdQoeDelegate","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdQoeDelegate","url":"\/documentation\/gfpsdk\/gfpvideoadqoedelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPVideoAdQoeDelegate","kind":"identifier"}],"kind":"symbol","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPVideoAdQoeDelegate"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"videoAdManager:didStartAdWithQoeInfo:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"videoAdManager:didStartAdWithQoeInfo:"}]},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"videoAdManager:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPVideoAdManager","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager","text":"GFPVideoAdManager"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"videoAdManager"},{"text":" ","kind":"text"},{"text":"didStartAdWithQoeInfo:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPVideoAdQoeInfo","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdQoeInfo","kind":"typeIdentifier","text":"GFPVideoAdQoeInfo"},{"kind":"text","text":" *) "},{"text":"info","kind":"internalParam"},{"kind":"text","text":";"}]}]}},{"path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"videoAdManager","content":[{"type":"paragraph","inlineContent":[{"text":"비디오 매니저","type":"text"}]}]},{"name":"info","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"QOE 정보"}]}]}],"kind":"parameters"},"op":"replace"},{"value":"GFPVideoAdQoeInfo","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdQoeInfo\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdQoeInfo\/fragments","value":[{"text":"GFPVideoAdQoeInfo","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdQoeInfo\/navigatorTitle","op":"replace","value":[{"text":"GFPVideoAdQoeInfo","kind":"identifier"}]},{"op":"replace","value":"GFPVideoAdManager","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManager\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManager\/fragments","value":[{"text":"GFPVideoAdManager","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManager\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"GFPVideoAdManager"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdQoeDelegate~1videoAdManager(_:didStartAdWith:)\/title","value":"videoAdManager:didStartAdWithQoeInfo:"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdQoeDelegate~1videoAdManager(_:didStartAdWith:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"videoAdManager:didStartAdWithQoeInfo:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdQoeDelegate\/title","op":"replace","value":"GFPVideoAdQoeDelegate"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdQoeDelegate\/fragments","op":"replace","value":[{"text":"GFPVideoAdQoeDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdQoeDelegate\/navigatorTitle","value":[{"text":"GFPVideoAdQoeDelegate","kind":"identifier"}]}]}]}