{"abstract":[{"type":"text","text":"광고가 로드된 경우 발생"}],"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"videoAdManager"},{"text":"(","kind":"text"},{"text":"GFPVideoAdManager","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoAdManager"},{"text":", ","kind":"text"},{"text":"didLoadAdWith","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPVideoAdQoeInfo","kind":"typeIdentifier","text":"GFPVideoAdQoeInfo"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"videoAdManager:didLoadAdWithQoeInfo:","kind":"identifier"}],"modules":[{"name":"GFPSDK"}],"required":true,"roleHeading":"Instance Method","externalID":"c:objc(pl)GFPVideoAdQoeDelegate(im)videoAdManager:didLoadAdWithQoeInfo:","title":"videoAdManager(_:didLoadAdWith:)","symbolKind":"method","role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"videoAdManager"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"videoAdManager"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPVideoAdManager","text":"GFPVideoAdManager","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager"},{"text":", ","kind":"text"},{"text":"didLoadAdWith","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"info"},{"text":": ","kind":"text"},{"text":"GFPVideoAdQoeInfo","preciseIdentifier":"c:objc(cs)GFPVideoAdQoeInfo","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdQoeInfo"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"videoAdManager","content":[{"inlineContent":[{"text":"비디오 매니저","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"QOE 정보"}]}],"name":"info"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpvideoadqoedelegate\/videoadmanager(_:didloadadwith:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpvideoadqoedelegate\/videoadmanager(_:didloadadwith:)"]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdQoeDelegate"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdQoeDelegate\/videoAdManager(_:didLoadAdWith:)"},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdManager":{"type":"topic","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager","role":"symbol","url":"\/documentation\/gfpsdk\/gfpvideoadmanager","title":"GFPVideoAdManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPVideoAdManager"}],"kind":"symbol","navigatorTitle":[{"text":"GFPVideoAdManager","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdQoeDelegate/videoAdManager(_:didLoadAdWith:)":{"navigatorTitle":[{"text":"videoAdManager:didLoadAdWithQoeInfo:","kind":"identifier"}],"type":"topic","title":"videoAdManager(_:didLoadAdWith:)","kind":"symbol","url":"\/documentation\/gfpsdk\/gfpvideoadqoedelegate\/videoadmanager(_:didloadadwith:)","abstract":[{"text":"광고가 로드된 경우 발생","type":"text"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdQoeDelegate\/videoAdManager(_:didLoadAdWith:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"videoAdManager","kind":"identifier"},{"kind":"text","text":"("},{"text":"GFPVideoAdManager","preciseIdentifier":"c:objc(cs)GFPVideoAdManager","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didLoadAdWith","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GFPVideoAdQoeInfo","preciseIdentifier":"c:objc(cs)GFPVideoAdQoeInfo"},{"text":")","kind":"text"}],"required":true,"role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdQoeInfo":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"GFPVideoAdQoeInfo"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdQoeInfo","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPVideoAdQoeInfo","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpvideoadqoeinfo","role":"symbol","kind":"symbol","title":"GFPVideoAdQoeInfo"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdQoeDelegate":{"title":"GFPVideoAdQoeDelegate","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdQoeDelegate","url":"\/documentation\/gfpsdk\/gfpvideoadqoedelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPVideoAdQoeDelegate","kind":"identifier"}],"kind":"symbol","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPVideoAdQoeDelegate"}],"type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"videoAdManager:didLoadAdWithQoeInfo:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"videoAdManager:didLoadAdWithQoeInfo:"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"videoAdManager:"},{"kind":"text","text":"("},{"text":"GFPVideoAdManager","preciseIdentifier":"c:objc(cs)GFPVideoAdManager","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"videoAdManager","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didLoadAdWithQoeInfo:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPVideoAdQoeInfo","text":"GFPVideoAdQoeInfo","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdQoeInfo","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"info"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"videoAdManager","content":[{"inlineContent":[{"type":"text","text":"비디오 매니저"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"QOE 정보"}]}],"name":"info"}],"kind":"parameters"},"op":"replace"},{"value":"GFPVideoAdManager","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManager\/title"},{"op":"replace","value":[{"text":"GFPVideoAdManager","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManager\/fragments"},{"op":"replace","value":[{"text":"GFPVideoAdManager","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManager\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdQoeDelegate~1videoAdManager(_:didLoadAdWith:)\/title","value":"videoAdManager:didLoadAdWithQoeInfo:","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdQoeDelegate~1videoAdManager(_:didLoadAdWith:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"videoAdManager:didLoadAdWithQoeInfo:","kind":"identifier"}]},{"value":"GFPVideoAdQoeInfo","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdQoeInfo\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdQoeInfo\/fragments","value":[{"kind":"identifier","text":"GFPVideoAdQoeInfo"}],"op":"replace"},{"value":[{"kind":"identifier","text":"GFPVideoAdQoeInfo"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdQoeInfo\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdQoeDelegate\/title","op":"replace","value":"GFPVideoAdQoeDelegate"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdQoeDelegate\/fragments","value":[{"kind":"identifier","text":"GFPVideoAdQoeDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdQoeDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"GFPVideoAdQoeDelegate"}],"op":"replace"}]}]}