{"metadata":{"role":"symbol","modules":[{"name":"GFPSDK"}],"externalID":"c:objc(pl)GFPVideoAdQoeDelegate(im)videoAdManager:didReceiveAdClickEventWitQoeInfo:","symbolKind":"method","title":"videoAdManager(_:didReceiveAdClickEventWitQoeInfo:)","navigatorTitle":[{"text":"videoAdManager:didReceiveAdClickEventWitQoeInfo:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"videoAdManager","kind":"identifier"},{"text":"(","kind":"text"},{"text":"GFPVideoAdManager","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoAdManager"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceiveAdClickEventWitQoeInfo"},{"kind":"text","text":": "},{"text":"GFPVideoAdQoeInfo","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoAdQoeInfo"},{"text":")","kind":"text"}],"roleHeading":"Instance Method","required":true},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoAdManager"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"videoAdManager"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager","text":"GFPVideoAdManager","preciseIdentifier":"c:objc(cs)GFPVideoAdManager","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didReceiveAdClickEventWitQoeInfo","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"info","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdQoeInfo","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoAdQoeInfo","text":"GFPVideoAdQoeInfo"},{"kind":"text","text":")"}],"platforms":["iOS"]}]},{"parameters":[{"name":"videoAdManager","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"비디오 매니저"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"QOE 정보"}]}],"name":"info"}],"kind":"parameters"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpvideoadqoedelegate\/videoadmanager(_:didreceiveadclickeventwitqoeinfo:)"]},{"paths":["\/documentation\/gfpsdk\/gfpvideoadqoedelegate\/videoadmanager(_:didreceiveadclickeventwitqoeinfo:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"광고가 클릭 된 경우 발생"}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdQoeDelegate"]]},"kind":"symbol","identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdQoeDelegate\/videoAdManager(_:didReceiveAdClickEventWitQoeInfo:)","interfaceLanguage":"swift"},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdQoeInfo":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"GFPVideoAdQoeInfo"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdQoeInfo","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPVideoAdQoeInfo","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpvideoadqoeinfo","role":"symbol","kind":"symbol","title":"GFPVideoAdQoeInfo"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdQoeDelegate":{"title":"GFPVideoAdQoeDelegate","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdQoeDelegate","url":"\/documentation\/gfpsdk\/gfpvideoadqoedelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPVideoAdQoeDelegate","kind":"identifier"}],"kind":"symbol","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPVideoAdQoeDelegate"}],"type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdQoeDelegate/videoAdManager(_:didReceiveAdClickEventWitQoeInfo:)":{"required":true,"role":"symbol","abstract":[{"text":"광고가 클릭 된 경우 발생","type":"text"}],"title":"videoAdManager(_:didReceiveAdClickEventWitQoeInfo:)","navigatorTitle":[{"kind":"identifier","text":"videoAdManager:didReceiveAdClickEventWitQoeInfo:"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"videoAdManager"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"GFPVideoAdManager","preciseIdentifier":"c:objc(cs)GFPVideoAdManager"},{"text":", ","kind":"text"},{"text":"didReceiveAdClickEventWitQoeInfo","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"GFPVideoAdQoeInfo","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoAdQoeInfo"},{"kind":"text","text":")"}],"url":"\/documentation\/gfpsdk\/gfpvideoadqoedelegate\/videoadmanager(_:didreceiveadclickeventwitqoeinfo:)","type":"topic","kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdQoeDelegate\/videoAdManager(_:didReceiveAdClickEventWitQoeInfo:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdManager":{"type":"topic","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager","role":"symbol","url":"\/documentation\/gfpsdk\/gfpvideoadmanager","title":"GFPVideoAdManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPVideoAdManager"}],"kind":"symbol","navigatorTitle":[{"text":"GFPVideoAdManager","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"videoAdManager:didReceiveAdClickEventWitQoeInfo:","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"videoAdManager:didReceiveAdClickEventWitQoeInfo:","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"videoAdManager:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)GFPVideoAdManager","text":"GFPVideoAdManager","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"videoAdManager"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didReceiveAdClickEventWitQoeInfo:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdQoeInfo","preciseIdentifier":"c:objc(cs)GFPVideoAdQoeInfo","text":"GFPVideoAdQoeInfo","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"info","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"videoAdManager","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"비디오 매니저"}]}]},{"name":"info","content":[{"type":"paragraph","inlineContent":[{"text":"QOE 정보","type":"text"}]}]}]}},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdQoeInfo\/title","op":"replace","value":"GFPVideoAdQoeInfo"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdQoeInfo\/fragments","value":[{"text":"GFPVideoAdQoeInfo","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"GFPVideoAdQoeInfo"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdQoeInfo\/navigatorTitle"},{"op":"replace","value":"GFPVideoAdQoeDelegate","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdQoeDelegate\/title"},{"value":[{"kind":"identifier","text":"GFPVideoAdQoeDelegate"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdQoeDelegate\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdQoeDelegate\/navigatorTitle","op":"replace","value":[{"text":"GFPVideoAdQoeDelegate","kind":"identifier"}]},{"value":"videoAdManager:didReceiveAdClickEventWitQoeInfo:","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdQoeDelegate~1videoAdManager(_:didReceiveAdClickEventWitQoeInfo:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdQoeDelegate~1videoAdManager(_:didReceiveAdClickEventWitQoeInfo:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"videoAdManager:didReceiveAdClickEventWitQoeInfo:"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManager\/title","value":"GFPVideoAdManager","op":"replace"},{"value":[{"text":"GFPVideoAdManager","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManager\/fragments","op":"replace"},{"value":[{"text":"GFPVideoAdManager","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManager\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}