{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"optional"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"videoAdManager"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"videoAdManager","kind":"internalParam"},{"kind":"text","text":": "},{"text":"GFPVideoAdManager","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoAdManager"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didResumeAdWith"},{"text":" ","kind":"text"},{"text":"info","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)GFPVideoAdQoeInfo","text":"GFPVideoAdQoeInfo","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdQoeInfo","kind":"typeIdentifier"},{"kind":"text","text":")"}]}]},{"parameters":[{"name":"videoAdManager","content":[{"type":"paragraph","inlineContent":[{"text":"비디오 매니저","type":"text"}]}]},{"name":"info","content":[{"type":"paragraph","inlineContent":[{"text":"QOE 정보","type":"text"}]}]}],"kind":"parameters"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpvideoadqoedelegate\/videoadmanager(_:didresumeadwith:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpvideoadqoedelegate\/videoadmanager(_:didresumeadwith:)"]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdQoeDelegate"]]},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdQoeDelegate\/videoAdManager(_:didResumeAdWith:)","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"kind":"symbol","metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"videoAdManager"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPVideoAdManager","text":"GFPVideoAdManager","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didResumeAdWith"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPVideoAdQoeInfo","text":"GFPVideoAdQoeInfo","kind":"typeIdentifier"},{"text":")","kind":"text"}],"roleHeading":"Instance Method","modules":[{"name":"GFPSDK"}],"externalID":"c:objc(pl)GFPVideoAdQoeDelegate(im)videoAdManager:didResumeAdWithQoeInfo:","role":"symbol","title":"videoAdManager(_:didResumeAdWith:)","symbolKind":"method","navigatorTitle":[{"text":"videoAdManager:didResumeAdWithQoeInfo:","kind":"identifier"}],"required":true},"abstract":[{"type":"text","text":"광고가 재시작 된 경우 발생"}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdManager":{"type":"topic","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager","role":"symbol","url":"\/documentation\/gfpsdk\/gfpvideoadmanager","title":"GFPVideoAdManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPVideoAdManager"}],"kind":"symbol","navigatorTitle":[{"text":"GFPVideoAdManager","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdQoeDelegate":{"title":"GFPVideoAdQoeDelegate","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdQoeDelegate","url":"\/documentation\/gfpsdk\/gfpvideoadqoedelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPVideoAdQoeDelegate","kind":"identifier"}],"kind":"symbol","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPVideoAdQoeDelegate"}],"type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdQoeInfo":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"GFPVideoAdQoeInfo"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdQoeInfo","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPVideoAdQoeInfo","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpvideoadqoeinfo","role":"symbol","kind":"symbol","title":"GFPVideoAdQoeInfo"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdQoeDelegate/videoAdManager(_:didResumeAdWith:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"videoAdManager","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoAdManager","text":"GFPVideoAdManager"},{"text":", ","kind":"text"},{"text":"didResumeAdWith","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"GFPVideoAdQoeInfo","preciseIdentifier":"c:objc(cs)GFPVideoAdQoeInfo"},{"text":")","kind":"text"}],"url":"\/documentation\/gfpsdk\/gfpvideoadqoedelegate\/videoadmanager(_:didresumeadwith:)","title":"videoAdManager(_:didResumeAdWith:)","abstract":[{"type":"text","text":"광고가 재시작 된 경우 발생"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdQoeDelegate\/videoAdManager(_:didResumeAdWith:)","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"videoAdManager:didResumeAdWithQoeInfo:","kind":"identifier"}],"type":"topic","required":true},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"videoAdManager:didResumeAdWithQoeInfo:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"videoAdManager:didResumeAdWithQoeInfo:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"videoAdManager:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoAdManager","text":"GFPVideoAdManager","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"videoAdManager"},{"kind":"text","text":" "},{"kind":"identifier","text":"didResumeAdWithQoeInfo:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPVideoAdQoeInfo","text":"GFPVideoAdQoeInfo","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdQoeInfo","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"info","kind":"internalParam"},{"kind":"text","text":";"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"비디오 매니저","type":"text"}]}],"name":"videoAdManager"},{"name":"info","content":[{"inlineContent":[{"text":"QOE 정보","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"}},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManager\/title","value":"GFPVideoAdManager"},{"value":[{"kind":"identifier","text":"GFPVideoAdManager"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManager\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManager\/navigatorTitle","value":[{"text":"GFPVideoAdManager","kind":"identifier"}]},{"value":"GFPVideoAdQoeDelegate","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdQoeDelegate\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdQoeDelegate\/fragments","value":[{"kind":"identifier","text":"GFPVideoAdQoeDelegate"}],"op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"GFPVideoAdQoeDelegate"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdQoeDelegate\/navigatorTitle"},{"op":"replace","value":"GFPVideoAdQoeInfo","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdQoeInfo\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdQoeInfo\/fragments","value":[{"text":"GFPVideoAdQoeInfo","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdQoeInfo\/navigatorTitle","value":[{"text":"GFPVideoAdQoeInfo","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdQoeDelegate~1videoAdManager(_:didResumeAdWith:)\/title","op":"replace","value":"videoAdManager:didResumeAdWithQoeInfo:"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdQoeDelegate~1videoAdManager(_:didResumeAdWith:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"videoAdManager:didResumeAdWithQoeInfo:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}