{"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfprewardedadprovideroption\/aps"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfprewardedadprovideroption\/aps"]}],"metadata":{"title":"GFPRewardedAdProviderOption.APS","modules":[{"name":"GFPSDK"}],"roleHeading":"Case","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"APS","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"GFPRewardedAdProviderOptionAPS"}],"symbolKind":"case","externalID":"c:@M@GFPSDK@E@GFPRewardedAdProviderOption@GFPRewardedAdProviderOptionAPS"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdProviderOption"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"APS"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdProviderOption\/APS","interfaceLanguage":"swift"},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRewardedAdProviderOption/APS":{"url":"\/documentation\/gfpsdk\/gfprewardedadprovideroption\/aps","title":"GFPRewardedAdProviderOption.APS","type":"topic","navigatorTitle":[{"text":"GFPRewardedAdProviderOptionAPS","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"APS"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdProviderOption\/APS"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRewardedAdProviderOption":{"type":"topic","navigatorTitle":[{"text":"GFPRewardedAdProviderOption","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdProviderOption","abstract":[{"type":"text","text":"GFP에서 지원하는 Reward 광고 제공자 목록"}],"kind":"symbol","url":"\/documentation\/gfpsdk\/gfprewardedadprovideroption","title":"GFPRewardedAdProviderOption","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPRewardedAdProviderOption"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"GFPRewardedAdProviderOptionAPS","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"GFPRewardedAdProviderOptionAPS"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"GFPRewardedAdProviderOptionAPS"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdProviderOption~1APS\/title","value":"GFPRewardedAdProviderOptionAPS"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdProviderOption~1APS\/fragments","op":"replace","value":[{"kind":"identifier","text":"GFPRewardedAdProviderOptionAPS"}]},{"op":"replace","value":"GFPRewardedAdProviderOption","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdProviderOption\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdProviderOption\/fragments","value":[{"kind":"identifier","text":"GFPRewardedAdProviderOption"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdProviderOption\/navigatorTitle","value":[{"text":"GFPRewardedAdProviderOption","kind":"identifier"}],"op":"replace"}]}]}