{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfprewardedadprovideroption\/bidmachine"]},{"paths":["\/documentation\/gfpsdk\/gfprewardedadprovideroption\/bidmachine"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"navigatorTitle":[{"text":"GFPRewardedAdProviderOptionBidMachine","kind":"identifier"}],"externalID":"c:@M@GFPSDK@E@GFPRewardedAdProviderOption@GFPRewardedAdProviderOptionBidMachine","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BidMachine"}],"role":"symbol","modules":[{"name":"GFPSDK"}],"roleHeading":"Case","title":"GFPRewardedAdProviderOption.BidMachine"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BidMachine"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdProviderOption"]]},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdProviderOption\/BidMachine","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRewardedAdProviderOption/BidMachine":{"navigatorTitle":[{"kind":"identifier","text":"GFPRewardedAdProviderOptionBidMachine"}],"url":"\/documentation\/gfpsdk\/gfprewardedadprovideroption\/bidmachine","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"BidMachine","kind":"identifier"}],"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdProviderOption\/BidMachine","title":"GFPRewardedAdProviderOption.BidMachine"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRewardedAdProviderOption":{"type":"topic","navigatorTitle":[{"text":"GFPRewardedAdProviderOption","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdProviderOption","abstract":[{"type":"text","text":"GFP에서 지원하는 Reward 광고 제공자 목록"}],"kind":"symbol","url":"\/documentation\/gfpsdk\/gfprewardedadprovideroption","title":"GFPRewardedAdProviderOption","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPRewardedAdProviderOption"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"GFPRewardedAdProviderOptionBidMachine"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","value":[{"text":"GFPRewardedAdProviderOptionBidMachine","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"GFPRewardedAdProviderOptionBidMachine"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"GFPRewardedAdProviderOptionBidMachine","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdProviderOption~1BidMachine\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdProviderOption~1BidMachine\/fragments","value":[{"kind":"identifier","text":"GFPRewardedAdProviderOptionBidMachine"}]},{"value":"GFPRewardedAdProviderOption","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdProviderOption\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdProviderOption\/fragments","value":[{"text":"GFPRewardedAdProviderOption","kind":"identifier"}]},{"value":[{"text":"GFPRewardedAdProviderOption","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdProviderOption\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}