{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfprewardedadprovideroption\/chartboost"]},{"paths":["\/documentation\/gfpsdk\/gfprewardedadprovideroption\/chartboost"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdProviderOption"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdProviderOption\/chartBoost"},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"kind":"symbol","metadata":{"externalID":"c:@M@GFPSDK@E@GFPRewardedAdProviderOption@GFPRewardedAdProviderOptionChartBoost","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"chartBoost"}],"navigatorTitle":[{"kind":"identifier","text":"GFPRewardedAdProviderOptionChartBoost"}],"role":"symbol","title":"GFPRewardedAdProviderOption.chartBoost","symbolKind":"case","modules":[{"name":"GFPSDK"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"chartBoost"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRewardedAdProviderOption/chartBoost":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdProviderOption\/chartBoost","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"chartBoost","kind":"identifier"}],"navigatorTitle":[{"text":"GFPRewardedAdProviderOptionChartBoost","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/gfpsdk\/gfprewardedadprovideroption\/chartboost","title":"GFPRewardedAdProviderOption.chartBoost","kind":"symbol","abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRewardedAdProviderOption":{"type":"topic","navigatorTitle":[{"text":"GFPRewardedAdProviderOption","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdProviderOption","abstract":[{"type":"text","text":"GFP에서 지원하는 Reward 광고 제공자 목록"}],"kind":"symbol","url":"\/documentation\/gfpsdk\/gfprewardedadprovideroption","title":"GFPRewardedAdProviderOption","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPRewardedAdProviderOption"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"value":"GFPRewardedAdProviderOptionChartBoost","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"GFPRewardedAdProviderOptionChartBoost"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"GFPRewardedAdProviderOptionChartBoost"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"value":"GFPRewardedAdProviderOptionChartBoost","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdProviderOption~1chartBoost\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"GFPRewardedAdProviderOptionChartBoost"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdProviderOption~1chartBoost\/fragments"},{"value":"GFPRewardedAdProviderOption","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdProviderOption\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdProviderOption\/fragments","value":[{"text":"GFPRewardedAdProviderOption","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdProviderOption\/navigatorTitle","value":[{"text":"GFPRewardedAdProviderOption","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}