{"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdProviderOption"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"vungle"}],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"navigatorTitle":[{"text":"GFPRewardedAdProviderOptionVungle","kind":"identifier"}],"externalID":"c:@M@GFPSDK@E@GFPRewardedAdProviderOption@GFPRewardedAdProviderOptionVungle","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"vungle","kind":"identifier"}],"modules":[{"name":"GFPSDK"}],"role":"symbol","roleHeading":"Case","title":"GFPRewardedAdProviderOption.vungle"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfprewardedadprovideroption\/vungle"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfprewardedadprovideroption\/vungle"]}],"sections":[],"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdProviderOption\/vungle","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRewardedAdProviderOption":{"type":"topic","navigatorTitle":[{"text":"GFPRewardedAdProviderOption","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdProviderOption","abstract":[{"type":"text","text":"GFP에서 지원하는 Reward 광고 제공자 목록"}],"kind":"symbol","url":"\/documentation\/gfpsdk\/gfprewardedadprovideroption","title":"GFPRewardedAdProviderOption","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPRewardedAdProviderOption"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRewardedAdProviderOption/vungle":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPRewardedAdProviderOptionVungle"}],"abstract":[],"url":"\/documentation\/gfpsdk\/gfprewardedadprovideroption\/vungle","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdProviderOption\/vungle","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"vungle"}],"title":"GFPRewardedAdProviderOption.vungle"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"GFPRewardedAdProviderOptionVungle"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"GFPRewardedAdProviderOptionVungle","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"GFPRewardedAdProviderOptionVungle"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdProviderOption\/title","value":"GFPRewardedAdProviderOption"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdProviderOption\/fragments","value":[{"kind":"identifier","text":"GFPRewardedAdProviderOption"}]},{"op":"replace","value":[{"text":"GFPRewardedAdProviderOption","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdProviderOption\/navigatorTitle"},{"op":"replace","value":"GFPRewardedAdProviderOptionVungle","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdProviderOption~1vungle\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdProviderOption~1vungle\/fragments","op":"replace","value":[{"text":"GFPRewardedAdProviderOptionVungle","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}