{"metadata":{"role":"symbol","externalID":"s:SQsE2neoiySbx_xtFZ::SYNTHESIZED::c:@E@GFPLoadEventStat","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"extendedModule":"Swift","modules":[{"name":"GFPSDK","relatedModules":["Swift"]}],"symbolKind":"op","title":"!=(_:_:)","roleHeading":"Operator"},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLoadEventStat\/!=(_:_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"Equatable.!=(_:_:)"},{"text":".","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLoadEventStat","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLoadEventStat\/Equatable-Implementations"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"lhs","kind":"internalParam"},{"kind":"text","text":": "},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"internalParam","text":"rhs"},{"kind":"text","text":": "},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]}]}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfploadeventstat\/!=(_:_:)"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPLoadEventStat":{"url":"\/documentation\/gfpsdk\/gfploadeventstat","title":"GFPLoadEventStat","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLoadEventStat","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"GFPLoadEventStat","kind":"identifier"}],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPLoadEventStat"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPLoadEventStat/Equatable-Implementations":{"role":"collectionGroup","abstract":[],"title":"Equatable Implementations","url":"\/documentation\/gfpsdk\/gfploadeventstat\/equatable-implementations","type":"topic","kind":"article","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLoadEventStat\/Equatable-Implementations"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPLoadEventStat/!=(_:_:)":{"kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"role":"symbol","type":"topic","url":"\/documentation\/gfpsdk\/gfploadeventstat\/!=(_:_:)","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLoadEventStat\/!=(_:_:)","title":"!=(_:_:)","abstract":[]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLoadEventStat\/title","op":"replace","value":"GFPLoadEventStat"},{"value":[{"kind":"identifier","text":"GFPLoadEventStat"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLoadEventStat\/fragments"},{"value":[{"kind":"identifier","text":"GFPLoadEventStat"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLoadEventStat\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}