{"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLoadEventStat"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLoadEventStat\/adSelected"},"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"Don’t change the value. This is the value defined in the specification."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"adSelected"}]}]}],"metadata":{"role":"symbol","externalID":"c:@E@GFPLoadEventStat@GFPLoadEventStatAdSelected","symbolKind":"case","navigatorTitle":[{"text":"GFPLoadEventStatAdSelected","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"adSelected","kind":"identifier"}],"modules":[{"name":"GFPSDK"}],"roleHeading":"Case","title":"GFPLoadEventStat.adSelected"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfploadeventstat\/adselected"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfploadeventstat\/adselected"]}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPLoadEventStat":{"url":"\/documentation\/gfpsdk\/gfploadeventstat","title":"GFPLoadEventStat","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLoadEventStat","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"GFPLoadEventStat","kind":"identifier"}],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPLoadEventStat"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPLoadEventStat/adSelected":{"role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLoadEventStat\/adSelected","type":"topic","abstract":[{"text":"Don’t change the value. This is the value defined in the specification.","type":"text"}],"url":"\/documentation\/gfpsdk\/gfploadeventstat\/adselected","title":"GFPLoadEventStat.adSelected","navigatorTitle":[{"text":"GFPLoadEventStatAdSelected","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"adSelected"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"GFPLoadEventStatAdSelected","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GFPLoadEventStatAdSelected"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"GFPLoadEventStatAdSelected","kind":"identifier"}]}]},"path":"\/primaryContentSections\/0"},{"value":"GFPLoadEventStat","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLoadEventStat\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLoadEventStat\/fragments","value":[{"kind":"identifier","text":"GFPLoadEventStat"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLoadEventStat\/navigatorTitle","value":[{"kind":"identifier","text":"GFPLoadEventStat"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLoadEventStat~1adSelected\/title","value":"GFPLoadEventStatAdSelected","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLoadEventStat~1adSelected\/fragments","value":[{"text":"GFPLoadEventStatAdSelected","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}