{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"head","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"GFPVideoScheduleHead","preciseIdentifier":"c:objc(cs)GFPVideoScheduleHead","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoScheduleHead"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpvideoschedule\/head"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpvideoschedule\/head"]}],"kind":"symbol","metadata":{"navigatorTitle":[{"text":"head","kind":"identifier"}],"externalID":"c:objc(cs)GFPVideoSchedule(py)head","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"head"},{"text":": ","kind":"text"},{"text":"GFPVideoScheduleHead","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoScheduleHead"}],"role":"symbol","roleHeading":"Instance Property","modules":[{"name":"GFPSDK"}],"title":"head"},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoSchedule"]]},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoSchedule\/head","interfaceLanguage":"swift"},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoSchedule":{"type":"topic","abstract":[],"title":"GFPVideoSchedule","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPVideoSchedule","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpvideoschedule","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoSchedule","navigatorTitle":[{"text":"GFPVideoSchedule","kind":"identifier"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoScheduleHead":{"navigatorTitle":[{"text":"GFPVideoScheduleHead","kind":"identifier"}],"title":"GFPVideoScheduleHead","type":"topic","abstract":[],"url":"\/documentation\/gfpsdk\/gfpvideoschedulehead","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPVideoScheduleHead"}],"kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoScheduleHead"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoSchedule/head":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"head"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoScheduleHead","text":"GFPVideoScheduleHead"}],"url":"\/documentation\/gfpsdk\/gfpvideoschedule\/head","navigatorTitle":[{"text":"head","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoSchedule\/head","title":"head","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","value":"head","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"kind":"identifier","text":"head"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoScheduleHead","preciseIdentifier":"c:objc(cs)GFPVideoScheduleHead","kind":"typeIdentifier","text":"GFPVideoScheduleHead"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"head"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"GFPVideoSchedule","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoSchedule\/title"},{"value":[{"text":"GFPVideoSchedule","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoSchedule\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoSchedule\/navigatorTitle","value":[{"kind":"identifier","text":"GFPVideoSchedule"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoScheduleHead\/title","value":"GFPVideoScheduleHead","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoScheduleHead\/fragments","value":[{"kind":"identifier","text":"GFPVideoScheduleHead"}],"op":"replace"},{"value":[{"kind":"identifier","text":"GFPVideoScheduleHead"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoScheduleHead\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoSchedule~1head\/title","value":"head","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoSchedule~1head\/fragments","value":[{"kind":"identifier","text":"head"}],"op":"replace"}]}]}