{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpvideoschedule\/postadbreaklist"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpvideoschedule\/postadbreaklist"]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoSchedule"]]},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"postAdBreakList","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"GFPVideoAdBreak","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdBreak","preciseIdentifier":"c:objc(cs)GFPVideoAdBreak"},{"kind":"text","text":"] { "},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoSchedule\/postAdBreakList","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"title":"postAdBreakList","symbolKind":"property","modules":[{"name":"GFPSDK"}],"role":"symbol","externalID":"c:objc(cs)GFPVideoSchedule(py)postAdBreakList","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"postAdBreakList","kind":"identifier"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:objc(cs)GFPVideoAdBreak","text":"GFPVideoAdBreak","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"navigatorTitle":[{"text":"postAdBreakList","kind":"identifier"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoSchedule/postAdBreakList":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"postAdBreakList"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPVideoAdBreak","kind":"typeIdentifier","text":"GFPVideoAdBreak"},{"text":"]","kind":"text"}],"url":"\/documentation\/gfpsdk\/gfpvideoschedule\/postadbreaklist","navigatorTitle":[{"kind":"identifier","text":"postAdBreakList"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoSchedule\/postAdBreakList","title":"postAdBreakList","abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdBreak":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPVideoAdBreak","kind":"identifier"}],"kind":"symbol","role":"symbol","abstract":[],"type":"topic","url":"\/documentation\/gfpsdk\/gfpvideoadbreak","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdBreak","title":"GFPVideoAdBreak","navigatorTitle":[{"text":"GFPVideoAdBreak","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoSchedule":{"type":"topic","abstract":[],"title":"GFPVideoSchedule","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPVideoSchedule","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpvideoschedule","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoSchedule","navigatorTitle":[{"text":"GFPVideoSchedule","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"postAdBreakList"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"postAdBreakList"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<GFPVideoAdBreak *>","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"postAdBreakList","kind":"identifier"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoSchedule~1postAdBreakList\/title","op":"replace","value":"postAdBreakList"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoSchedule~1postAdBreakList\/fragments","value":[{"text":"postAdBreakList","kind":"identifier"}],"op":"replace"},{"value":"GFPVideoAdBreak","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdBreak\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdBreak\/fragments","value":[{"text":"GFPVideoAdBreak","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"GFPVideoAdBreak"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdBreak\/navigatorTitle","op":"replace"},{"value":"GFPVideoSchedule","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoSchedule\/title","op":"replace"},{"value":[{"kind":"identifier","text":"GFPVideoSchedule"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoSchedule\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoSchedule\/navigatorTitle","value":[{"kind":"identifier","text":"GFPVideoSchedule"}],"op":"replace"}]}]}