{"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPVideoDisplayMode","text":"GFPVideoDisplayMode"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"mode"}],"roleHeading":"Instance Property","externalID":"c:objc(cs)GFPVideoCastingView(py)mode","symbolKind":"property","title":"mode","modules":[{"name":"GFPSDK"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mode"},{"kind":"text","text":": "},{"text":"GFPVideoDisplayMode","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoDisplayMode","preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPVideoDisplayMode"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoCastingView\/mode","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoCastingView"]]},"sections":[],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpvideocastingview\/mode"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpvideocastingview\/mode"]}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoCastingView":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPVideoCastingView","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"GFPVideoCastingView"}],"url":"\/documentation\/gfpsdk\/gfpvideocastingview","abstract":[],"kind":"symbol","role":"symbol","title":"GFPVideoCastingView","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoCastingView","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoDisplayMode":{"navigatorTitle":[{"text":"GFPVideoDisplayMode","kind":"identifier"}],"type":"topic","title":"GFPVideoDisplayMode","kind":"symbol","url":"\/documentation\/gfpsdk\/gfpvideodisplaymode","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoDisplayMode","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPVideoDisplayMode","kind":"identifier"}],"role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoCastingView/mode":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mode","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"GFPVideoDisplayMode","preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPVideoDisplayMode"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoCastingView\/mode","navigatorTitle":[{"text":"mode","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[],"title":"mode","role":"symbol","url":"\/documentation\/gfpsdk\/gfpvideocastingview\/mode"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"value":"mode","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"mode","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"text":"GFPVideoDisplayMode","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoDisplayMode","preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPVideoDisplayMode"},{"kind":"text","text":" * "},{"text":"mode","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoCastingView\/title","op":"replace","value":"GFPVideoCastingView"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoCastingView\/fragments","value":[{"kind":"identifier","text":"GFPVideoCastingView"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoCastingView\/navigatorTitle","value":[{"kind":"identifier","text":"GFPVideoCastingView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoDisplayMode\/title","value":"GFPVideoDisplayMode"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoDisplayMode\/fragments","value":[{"text":"GFPVideoDisplayMode","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"GFPVideoDisplayMode"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoDisplayMode\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoCastingView~1mode\/title","value":"mode","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoCastingView~1mode\/fragments","value":[{"text":"mode","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}