{"metadata":{"symbolKind":"init","title":"init(log:)","modules":[{"name":"GFPSDK"}],"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"log"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPLogReqInfo","text":"GFPLogReqInfo","kind":"typeIdentifier"},{"text":")","kind":"text"}],"roleHeading":"Initializer","navigatorTitle":[{"text":"initWithLog:","kind":"identifier"}],"externalID":"c:objc(cs)GFPAPIQueryItems(im)initWithLog:"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"text":"log","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"aLogInfo"},{"kind":"text","text":": "},{"text":"GFPLogReqInfo","preciseIdentifier":"c:objc(cs)GFPLogReqInfo","kind":"typeIdentifier"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAPIQueryItems"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAPIQueryItems\/init(log:)"},"sections":[],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpapiqueryitems\/init(log:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpapiqueryitems\/init(log:)"]}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAPIQueryItems/init(log:)":{"type":"topic","abstract":[],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"log","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPLogReqInfo","kind":"typeIdentifier","text":"GFPLogReqInfo"},{"text":")","kind":"text"}],"title":"init(log:)","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAPIQueryItems\/init(log:)","role":"symbol","kind":"symbol","url":"\/documentation\/gfpsdk\/gfpapiqueryitems\/init(log:)","navigatorTitle":[{"text":"initWithLog:","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAPIQueryItems":{"url":"\/documentation\/gfpsdk\/gfpapiqueryitems","abstract":[],"title":"GFPAPIQueryItems","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAPIQueryItems","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPAPIQueryItems"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPAPIQueryItems"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","value":"initWithLog:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithLog:","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"text":"initWithLog:","kind":"identifier"},{"kind":"text","text":"("},{"text":"GFPLogReqInfo","preciseIdentifier":"c:objc(cs)GFPLogReqInfo","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"aLogInfo","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAPIQueryItems~1init(log:)\/title","value":"initWithLog:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithLog:"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAPIQueryItems~1init(log:)\/fragments","op":"replace"},{"value":"GFPAPIQueryItems","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAPIQueryItems\/title","op":"replace"},{"value":[{"text":"GFPAPIQueryItems","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAPIQueryItems\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAPIQueryItems\/navigatorTitle","value":[{"text":"GFPAPIQueryItems","kind":"identifier"}],"op":"replace"}]}]}