{"metadata":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"adParam","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPAdParam","text":"GFPAdParam","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"videoParam","kind":"externalParam"},{"kind":"text","text":": "},{"text":"GFPVideoAdParam","kind":"typeIdentifier","preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPVideoAdParam"},{"text":"?, ","kind":"text"},{"text":"extraParam","kind":"externalParam"},{"kind":"text","text":": "},{"text":"GFPExtraRequestParam","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPExtraRequestParam"},{"text":"?)","kind":"text"}],"externalID":"c:objc(cs)GFPAPIQueryItems(im)initWith:adParam:videoParam:extraParam:","title":"init(_:adParam:videoParam:extraParam:)","role":"symbol","symbolKind":"init","roleHeading":"Initializer","navigatorTitle":[{"text":"initWith:adParam:videoParam:extraParam:","kind":"identifier"}],"modules":[{"name":"GFPSDK"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"aUnitID","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"adParam","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"aAdParam","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPAdParam","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdParam","kind":"typeIdentifier","text":"GFPAdParam"},{"kind":"text","text":"?, "},{"text":"videoParam","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"aVideoAdParam"},{"text":": ","kind":"text"},{"text":"GFPVideoAdParam","kind":"typeIdentifier","preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPVideoAdParam","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdParam"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"extraParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"aExtraParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPExtraRequestParam","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPExtraRequestParam","text":"GFPExtraRequestParam"},{"kind":"text","text":"?)"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpapiqueryitems\/init(_:adparam:videoparam:extraparam:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpapiqueryitems\/init(_:adparam:videoparam:extraparam:)"]}],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAPIQueryItems"]]},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAPIQueryItems\/init(_:adParam:videoParam:extraParam:)","interfaceLanguage":"swift"},"sections":[],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAPIQueryItems/init(_:adParam:videoParam:extraParam:)":{"type":"topic","abstract":[],"title":"init(_:adParam:videoParam:extraParam:)","role":"symbol","url":"\/documentation\/gfpsdk\/gfpapiqueryitems\/init(_:adparam:videoparam:extraparam:)","navigatorTitle":[{"text":"initWith:adParam:videoParam:extraParam:","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAPIQueryItems\/init(_:adParam:videoParam:extraParam:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"adParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"GFPAdParam","preciseIdentifier":"c:objc(cs)GFPAdParam"},{"text":"?, ","kind":"text"},{"text":"videoParam","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GFPVideoAdParam","preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPVideoAdParam"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"extraParam"},{"text":": ","kind":"text"},{"text":"GFPExtraRequestParam","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPExtraRequestParam"},{"text":"?)","kind":"text"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAPIQueryItems":{"url":"\/documentation\/gfpsdk\/gfpapiqueryitems","abstract":[],"title":"GFPAPIQueryItems","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAPIQueryItems","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPAPIQueryItems"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPAPIQueryItems"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPExtraRequestParam":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPExtraRequestParam","type":"topic","abstract":[],"url":"\/documentation\/gfpsdk\/gfpextrarequestparam","navigatorTitle":[{"text":"GFPExtraRequestParam","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"GFPExtraRequestParam","kind":"identifier"}],"title":"GFPExtraRequestParam","role":"symbol","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdParam":{"abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPVideoAdParam"}],"role":"symbol","navigatorTitle":[{"text":"GFPVideoAdParam","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdParam","url":"\/documentation\/gfpsdk\/gfpvideoadparam","kind":"symbol","title":"GFPVideoAdParam"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdParam":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdParam","abstract":[],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPAdParam"}],"navigatorTitle":[{"text":"GFPAdParam","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpadparam","type":"topic","kind":"symbol","title":"GFPAdParam"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","value":"initWith:adParam:videoParam:extraParam:","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWith:adParam:videoParam:extraParam:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWith:"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"aUnitID","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"adParam:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)GFPAdParam","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdParam","kind":"typeIdentifier","text":"GFPAdParam"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"aAdParam"},{"text":" ","kind":"text"},{"text":"videoParam:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPVideoAdParam","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdParam","kind":"typeIdentifier","text":"GFPVideoAdParam"},{"kind":"text","text":" *) "},{"text":"aVideoAdParam","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"extraParam:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GFPExtraRequestParam","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPExtraRequestParam","preciseIdentifier":"c:objc(cs)GFPExtraRequestParam"},{"kind":"text","text":" *) "},{"text":"aExtraParam","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAPIQueryItems~1init(_:adParam:videoParam:extraParam:)\/title","value":"initWith:adParam:videoParam:extraParam:","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWith:adParam:videoParam:extraParam:"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAPIQueryItems~1init(_:adParam:videoParam:extraParam:)\/fragments"},{"value":"GFPAPIQueryItems","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAPIQueryItems\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAPIQueryItems\/fragments","value":[{"kind":"identifier","text":"GFPAPIQueryItems"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAPIQueryItems\/navigatorTitle","value":[{"text":"GFPAPIQueryItems","kind":"identifier"}]},{"op":"replace","value":"GFPExtraRequestParam","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPExtraRequestParam\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPExtraRequestParam\/fragments","value":[{"text":"GFPExtraRequestParam","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"text":"GFPExtraRequestParam","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPExtraRequestParam\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdParam\/title","op":"replace","value":"GFPVideoAdParam"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdParam\/fragments","op":"replace","value":[{"text":"GFPVideoAdParam","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdParam\/navigatorTitle","value":[{"text":"GFPVideoAdParam","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"GFPAdParam","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdParam\/title"},{"value":[{"kind":"identifier","text":"GFPAdParam"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdParam\/fragments"},{"value":[{"kind":"identifier","text":"GFPAdParam"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdParam\/navigatorTitle","op":"replace"}]}]}