{"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAPIQueryItems\/items","interfaceLanguage":"swift"},"metadata":{"externalID":"c:objc(cs)GFPAPIQueryItems(py)items","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"items","kind":"identifier"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:10Foundation12URLQueryItemV","kind":"typeIdentifier","text":"URLQueryItem"},{"kind":"text","text":"]"}],"navigatorTitle":[{"text":"items","kind":"identifier"}],"role":"symbol","title":"items","symbolKind":"property","modules":[{"name":"GFPSDK"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"items","kind":"identifier"},{"kind":"text","text":": ["},{"text":"URLQueryItem","preciseIdentifier":"s:10Foundation12URLQueryItemV","kind":"typeIdentifier"},{"kind":"text","text":"] { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpapiqueryitems\/items"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpapiqueryitems\/items"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAPIQueryItems"]]},"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAPIQueryItems/items":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAPIQueryItems\/items","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"items","kind":"identifier"},{"kind":"text","text":": ["},{"text":"URLQueryItem","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation12URLQueryItemV"},{"text":"]","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"items"}],"type":"topic","role":"symbol","kind":"symbol","title":"items","url":"\/documentation\/gfpsdk\/gfpapiqueryitems\/items","abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAPIQueryItems":{"url":"\/documentation\/gfpsdk\/gfpapiqueryitems","abstract":[],"title":"GFPAPIQueryItems","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAPIQueryItems","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPAPIQueryItems"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPAPIQueryItems"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"items"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"items","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSURLQueryItem *>"},{"kind":"text","text":" * "},{"text":"items","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"op":"replace","value":"items","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAPIQueryItems~1items\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAPIQueryItems~1items\/fragments","value":[{"text":"items","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAPIQueryItems\/title","value":"GFPAPIQueryItems","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAPIQueryItems\/fragments","value":[{"text":"GFPAPIQueryItems","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAPIQueryItems\/navigatorTitle","value":[{"text":"GFPAPIQueryItems","kind":"identifier"}],"op":"replace"}]}]}