{"abstract":[{"text":"광고 로드\/재생에 실패한 경우 호출됩니다.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"(본 영상을 재생해 주세요.)"}],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpvideoadmanagerdelegate\/videoadmanager(_:didfailwitherror:responseinfo:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpvideoadmanagerdelegate\/videoadmanager(_:didfailwitherror:responseinfo:)"]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManagerDelegate"]]},"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"videoAdManager","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"videoAdManager"},{"kind":"text","text":": "},{"text":"GFPVideoAdManager","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoAdManager"},{"text":", ","kind":"text"},{"text":"didFailWithError","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"error"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@NaverAdsServices@objc(cs)GFPError","kind":"typeIdentifier","text":"GFPError"},{"text":", ","kind":"text"},{"text":"responseInfo","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)GFPLoadResponseInfo","text":"GFPLoadResponseInfo","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLoadResponseInfo"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"videoAdManager","content":[{"type":"paragraph","inlineContent":[{"text":"비디오 광고 매니저","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"에러내용","type":"text"}]}],"name":"error"},{"name":"responseInfo","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"광고 응답 정보객체"}]}]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"role":"symbol","roleHeading":"Instance Method","title":"videoAdManager(_:didFailWithError:responseInfo:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"videoAdManager","kind":"identifier"},{"text":"(","kind":"text"},{"text":"GFPVideoAdManager","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoAdManager"},{"text":", ","kind":"text"},{"text":"didFailWithError","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"GFPError","kind":"typeIdentifier","preciseIdentifier":"c:@M@NaverAdsServices@objc(cs)GFPError"},{"kind":"text","text":", "},{"kind":"externalParam","text":"responseInfo"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)GFPLoadResponseInfo","text":"GFPLoadResponseInfo","kind":"typeIdentifier"},{"kind":"text","text":")"}],"externalID":"c:objc(pl)GFPVideoAdManagerDelegate(im)videoAdManager:didFailWithError:responseInfo:","symbolKind":"method","navigatorTitle":[{"text":"videoAdManager:didFailWithError:responseInfo:","kind":"identifier"}],"required":true,"modules":[{"name":"GFPSDK"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManagerDelegate\/videoAdManager(_:didFailWithError:responseInfo:)"},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdManagerDelegate/videoAdManager(_:didFailWithError:responseInfo:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"videoAdManager"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoAdManager","text":"GFPVideoAdManager"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didFailWithError"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@NaverAdsServices@objc(cs)GFPError","text":"GFPError","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"responseInfo","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"GFPLoadResponseInfo","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPLoadResponseInfo"},{"kind":"text","text":")"}],"kind":"symbol","navigatorTitle":[{"text":"videoAdManager:didFailWithError:responseInfo:","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManagerDelegate\/videoAdManager(_:didFailWithError:responseInfo:)","abstract":[{"text":"광고 로드\/재생에 실패한 경우 호출됩니다.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"(본 영상을 재생해 주세요.)"}],"role":"symbol","url":"\/documentation\/gfpsdk\/gfpvideoadmanagerdelegate\/videoadmanager(_:didfailwitherror:responseinfo:)","title":"videoAdManager(_:didFailWithError:responseInfo:)","required":true,"type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPLoadResponseInfo":{"title":"GFPLoadResponseInfo","url":"\/documentation\/gfpsdk\/gfploadresponseinfo","role":"symbol","navigatorTitle":[{"text":"GFPLoadResponseInfo","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"GFPLoadResponseInfo","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLoadResponseInfo"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdManager":{"type":"topic","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager","role":"symbol","url":"\/documentation\/gfpsdk\/gfpvideoadmanager","title":"GFPVideoAdManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPVideoAdManager"}],"kind":"symbol","navigatorTitle":[{"text":"GFPVideoAdManager","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdManagerDelegate":{"type":"topic","url":"\/documentation\/gfpsdk\/gfpvideoadmanagerdelegate","title":"GFPVideoAdManagerDelegate","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManagerDelegate","kind":"symbol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPVideoAdManagerDelegate"}],"navigatorTitle":[{"kind":"identifier","text":"GFPVideoAdManagerDelegate"}],"abstract":[]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"videoAdManager:didFailWithError:responseInfo:","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"videoAdManager:didFailWithError:responseInfo:"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"text":"videoAdManager:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoAdManager","text":"GFPVideoAdManager"},{"kind":"text","text":" *) "},{"text":"videoAdManager","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didFailWithError:"},{"kind":"text","text":"("},{"text":"GFPError","kind":"typeIdentifier","preciseIdentifier":"c:@M@NaverAdsServices@objc(cs)GFPError"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"error"},{"kind":"text","text":" "},{"kind":"identifier","text":"responseInfo:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLoadResponseInfo","text":"GFPLoadResponseInfo","preciseIdentifier":"c:objc(cs)GFPLoadResponseInfo"},{"kind":"text","text":" *) "},{"text":"responseInfo","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"비디오 광고 매니저","type":"text"}],"type":"paragraph"}],"name":"videoAdManager"},{"content":[{"inlineContent":[{"text":"에러내용","type":"text"}],"type":"paragraph"}],"name":"error"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"광고 응답 정보객체"}]}],"name":"responseInfo"}]}},{"op":"replace","value":"videoAdManager:didFailWithError:responseInfo:","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManagerDelegate~1videoAdManager(_:didFailWithError:responseInfo:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"videoAdManager:didFailWithError:responseInfo:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManagerDelegate~1videoAdManager(_:didFailWithError:responseInfo:)\/fragments"},{"value":"GFPLoadResponseInfo","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLoadResponseInfo\/title","op":"replace"},{"op":"replace","value":[{"text":"GFPLoadResponseInfo","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLoadResponseInfo\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLoadResponseInfo\/navigatorTitle","value":[{"kind":"identifier","text":"GFPLoadResponseInfo"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManager\/title","op":"replace","value":"GFPVideoAdManager"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManager\/fragments","value":[{"text":"GFPVideoAdManager","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManager\/navigatorTitle","value":[{"kind":"identifier","text":"GFPVideoAdManager"}]},{"op":"replace","value":"GFPVideoAdManagerDelegate","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManagerDelegate\/title"},{"value":[{"text":"GFPVideoAdManagerDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManagerDelegate\/fragments"},{"value":[{"text":"GFPVideoAdManagerDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManagerDelegate\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}