{"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Default In App Browser 사용 시, SFSafariViewController가 정상적으로 Dismiss 시 호출됩니다."}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManagerDelegate"]]},"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpvideoadmanagerdelegate\/videoadmanagerdiddismissdefault(inappbrowser:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpvideoadmanagerdelegate\/videoadmanagerdiddismissdefault(inappbrowser:)"]}],"metadata":{"title":"videoAdManagerDidDismissDefault(inAppBrowser:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"videoAdManagerDidDismissDefault"},{"text":"(","kind":"text"},{"text":"inAppBrowser","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GFPVideoAdManager","preciseIdentifier":"c:objc(cs)GFPVideoAdManager"},{"text":")","kind":"text"}],"roleHeading":"Instance Method","role":"symbol","externalID":"c:objc(pl)GFPVideoAdManagerDelegate(im)videoAdManagerDidDismissDefaultInAppBrowser:","required":true,"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"videoAdManagerDidDismissDefaultInAppBrowser:"}],"modules":[{"name":"GFPSDK"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManagerDelegate\/videoAdManagerDidDismissDefault(inAppBrowser:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"optional"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"videoAdManagerDidDismissDefault","kind":"identifier"},{"kind":"text","text":"("},{"text":"inAppBrowser","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"videoAdManager","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager","text":"GFPVideoAdManager","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoAdManager"},{"text":")","kind":"text"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"videoAdManager","content":[{"inlineContent":[{"type":"text","text":"비디오 광고 매니저"}],"type":"paragraph"}]}]}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdManagerDelegate":{"type":"topic","url":"\/documentation\/gfpsdk\/gfpvideoadmanagerdelegate","title":"GFPVideoAdManagerDelegate","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManagerDelegate","kind":"symbol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPVideoAdManagerDelegate"}],"navigatorTitle":[{"kind":"identifier","text":"GFPVideoAdManagerDelegate"}],"abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdManagerDelegate/videoAdManagerDidDismissDefault(inAppBrowser:)":{"required":true,"role":"symbol","abstract":[{"text":"Default In App Browser 사용 시, SFSafariViewController가 정상적으로 Dismiss 시 호출됩니다.","type":"text"}],"title":"videoAdManagerDidDismissDefault(inAppBrowser:)","navigatorTitle":[{"text":"videoAdManagerDidDismissDefaultInAppBrowser:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"videoAdManagerDidDismissDefault","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"inAppBrowser"},{"text":": ","kind":"text"},{"text":"GFPVideoAdManager","preciseIdentifier":"c:objc(cs)GFPVideoAdManager","kind":"typeIdentifier"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManagerDelegate\/videoAdManagerDidDismissDefault(inAppBrowser:)","type":"topic","kind":"symbol","url":"\/documentation\/gfpsdk\/gfpvideoadmanagerdelegate\/videoadmanagerdiddismissdefault(inappbrowser:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdManager":{"type":"topic","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager","role":"symbol","url":"\/documentation\/gfpsdk\/gfpvideoadmanager","title":"GFPVideoAdManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPVideoAdManager"}],"kind":"symbol","navigatorTitle":[{"text":"GFPVideoAdManager","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"videoAdManagerDidDismissDefaultInAppBrowser:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"videoAdManagerDidDismissDefaultInAppBrowser:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"videoAdManagerDidDismissDefaultInAppBrowser:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager","text":"GFPVideoAdManager","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoAdManager"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"videoAdManager"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","value":{"kind":"parameters","parameters":[{"name":"videoAdManager","content":[{"type":"paragraph","inlineContent":[{"text":"비디오 광고 매니저","type":"text"}]}]}]},"path":"\/primaryContentSections\/1"},{"value":"GFPVideoAdManagerDelegate","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManagerDelegate\/title"},{"op":"replace","value":[{"kind":"identifier","text":"GFPVideoAdManagerDelegate"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManagerDelegate\/fragments"},{"op":"replace","value":[{"text":"GFPVideoAdManagerDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManagerDelegate\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManagerDelegate~1videoAdManagerDidDismissDefault(inAppBrowser:)\/title","value":"videoAdManagerDidDismissDefaultInAppBrowser:","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManagerDelegate~1videoAdManagerDidDismissDefault(inAppBrowser:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"videoAdManagerDidDismissDefaultInAppBrowser:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManager\/title","value":"GFPVideoAdManager","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"GFPVideoAdManager"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManager\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManager\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"GFPVideoAdManager"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}