{"metadata":{"role":"symbol","modules":[{"name":"GFPSDK"}],"externalID":"c:objc(pl)GFPVideoAdManagerDelegate(im)videoAdManagerDidResumeAd:","symbolKind":"method","roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"videoAdManagerDidResumeAd:"}],"title":"videoAdManagerDidResumeAd(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"videoAdManagerDidResumeAd","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"GFPVideoAdManager","preciseIdentifier":"c:objc(cs)GFPVideoAdManager"},{"text":")","kind":"text"}],"required":true},"abstract":[{"text":"광고 재생 재 시작시 호출됩니다.","type":"text"}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManagerDelegate\/videoAdManagerDidResumeAd(_:)"},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"optional","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"videoAdManagerDidResumeAd","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"videoAdManager"},{"text":": ","kind":"text"},{"text":"GFPVideoAdManager","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoAdManager","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager"},{"text":")","kind":"text"}]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"비디오 광고 매니저"}],"type":"paragraph"}],"name":"videoAdManager"}],"kind":"parameters"}],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpvideoadmanagerdelegate\/videoadmanagerdidresumead(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpvideoadmanagerdelegate\/videoadmanagerdidresumead(_:)"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManagerDelegate"]]},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdManager":{"type":"topic","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager","role":"symbol","url":"\/documentation\/gfpsdk\/gfpvideoadmanager","title":"GFPVideoAdManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPVideoAdManager"}],"kind":"symbol","navigatorTitle":[{"text":"GFPVideoAdManager","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdManagerDelegate/videoAdManagerDidResumeAd(_:)":{"required":true,"role":"symbol","abstract":[{"text":"광고 재생 재 시작시 호출됩니다.","type":"text"}],"title":"videoAdManagerDidResumeAd(_:)","navigatorTitle":[{"text":"videoAdManagerDidResumeAd:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoAdManagerDidResumeAd"},{"text":"(","kind":"text"},{"text":"GFPVideoAdManager","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoAdManager"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManagerDelegate\/videoAdManagerDidResumeAd(_:)","type":"topic","kind":"symbol","url":"\/documentation\/gfpsdk\/gfpvideoadmanagerdelegate\/videoadmanagerdidresumead(_:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdManagerDelegate":{"type":"topic","url":"\/documentation\/gfpsdk\/gfpvideoadmanagerdelegate","title":"GFPVideoAdManagerDelegate","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManagerDelegate","kind":"symbol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPVideoAdManagerDelegate"}],"navigatorTitle":[{"kind":"identifier","text":"GFPVideoAdManagerDelegate"}],"abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"videoAdManagerDidResumeAd:","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"videoAdManagerDidResumeAd:"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"videoAdManagerDidResumeAd:","kind":"identifier"},{"kind":"text","text":"("},{"text":"GFPVideoAdManager","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoAdManager","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager"},{"text":" *) ","kind":"text"},{"text":"videoAdManager","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"videoAdManager","content":[{"type":"paragraph","inlineContent":[{"text":"비디오 광고 매니저","type":"text"}]}]}],"kind":"parameters"}},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManager\/title","value":"GFPVideoAdManager"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManager\/fragments","op":"replace","value":[{"kind":"identifier","text":"GFPVideoAdManager"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManager\/navigatorTitle","op":"replace","value":[{"text":"GFPVideoAdManager","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManagerDelegate~1videoAdManagerDidResumeAd(_:)\/title","op":"replace","value":"videoAdManagerDidResumeAd:"},{"value":[{"kind":"text","text":"- "},{"text":"videoAdManagerDidResumeAd:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManagerDelegate~1videoAdManagerDidResumeAd(_:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManagerDelegate\/title","value":"GFPVideoAdManagerDelegate"},{"value":[{"kind":"identifier","text":"GFPVideoAdManagerDelegate"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManagerDelegate\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManagerDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"GFPVideoAdManagerDelegate"}]}]}]}