{"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManagerDelegate\/videoAdManagerDidCompleteAd(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"광고 재생 종료시 호출됩니다."},{"type":"text","text":" "},{"type":"text","text":"(본 영상을 재생해 주세요.)"}],"metadata":{"title":"videoAdManagerDidCompleteAd(_:)","role":"symbol","externalID":"c:objc(pl)GFPVideoAdManagerDelegate(im)videoAdManagerDidCompleteAd:","modules":[{"name":"GFPSDK"}],"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"videoAdManagerDidCompleteAd","kind":"identifier"},{"text":"(","kind":"text"},{"text":"GFPVideoAdManager","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoAdManager"},{"kind":"text","text":")"}],"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"videoAdManagerDidCompleteAd:"}]},"variants":[{"paths":["\/documentation\/gfpsdk\/gfpvideoadmanagerdelegate\/videoadmanagerdidcompletead(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gfpsdk\/gfpvideoadmanagerdelegate\/videoadmanagerdidcompletead(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"optional"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoAdManagerDidCompleteAd"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"videoAdManager","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager","text":"GFPVideoAdManager","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoAdManager"},{"text":")","kind":"text"}],"languages":["swift"]}]},{"parameters":[{"content":[{"inlineContent":[{"text":"비디오 광고 매니저","type":"text"}],"type":"paragraph"}],"name":"videoAdManager"}],"kind":"parameters"}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManagerDelegate"]]},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdManagerDelegate":{"type":"topic","url":"\/documentation\/gfpsdk\/gfpvideoadmanagerdelegate","title":"GFPVideoAdManagerDelegate","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManagerDelegate","kind":"symbol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPVideoAdManagerDelegate"}],"navigatorTitle":[{"kind":"identifier","text":"GFPVideoAdManagerDelegate"}],"abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdManagerDelegate/videoAdManagerDidCompleteAd(_:)":{"title":"videoAdManagerDidCompleteAd(_:)","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManagerDelegate\/videoAdManagerDidCompleteAd(_:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoAdManagerDidCompleteAd"},{"kind":"text","text":"("},{"text":"GFPVideoAdManager","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoAdManager"},{"text":")","kind":"text"}],"abstract":[{"text":"광고 재생 종료시 호출됩니다.","type":"text"},{"type":"text","text":" "},{"text":"(본 영상을 재생해 주세요.)","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"videoAdManagerDidCompleteAd:"}],"url":"\/documentation\/gfpsdk\/gfpvideoadmanagerdelegate\/videoadmanagerdidcompletead(_:)","type":"topic","role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdManager":{"type":"topic","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager","role":"symbol","url":"\/documentation\/gfpsdk\/gfpvideoadmanager","title":"GFPVideoAdManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPVideoAdManager"}],"kind":"symbol","navigatorTitle":[{"text":"GFPVideoAdManager","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"videoAdManagerDidCompleteAd:","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"videoAdManagerDidCompleteAd:"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"videoAdManagerDidCompleteAd:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager","text":"GFPVideoAdManager","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoAdManager"},{"text":" *) ","kind":"text"},{"text":"videoAdManager","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"비디오 광고 매니저"}],"type":"paragraph"}],"name":"videoAdManager"}]},"op":"replace","path":"\/primaryContentSections\/1"},{"op":"replace","value":"GFPVideoAdManagerDelegate","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManagerDelegate\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManagerDelegate\/fragments","op":"replace","value":[{"text":"GFPVideoAdManagerDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManagerDelegate\/navigatorTitle","value":[{"text":"GFPVideoAdManagerDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManagerDelegate~1videoAdManagerDidCompleteAd(_:)\/title","value":"videoAdManagerDidCompleteAd:"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManagerDelegate~1videoAdManagerDidCompleteAd(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"videoAdManagerDidCompleteAd:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManager\/title","value":"GFPVideoAdManager"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManager\/fragments","op":"replace","value":[{"text":"GFPVideoAdManager","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManager\/navigatorTitle","op":"replace","value":[{"text":"GFPVideoAdManager","kind":"identifier"}]}]}]}