{"abstract":[{"type":"text","text":"재생중인 광고플레이어가 AVPlayer 일 때(현재 NDA 한정), AVPlayerItem 에서 AccessLogEvent 가 발생한 경우 호출됩니다."}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"metadata":{"navigatorTitle":[{"text":"videoAdManager:didReceiveAccessLog:","kind":"identifier"}],"role":"symbol","title":"videoAdManager(_:didReceive:)","required":true,"roleHeading":"Instance Method","symbolKind":"method","externalID":"c:objc(pl)GFPVideoAdManagerDelegate(im)videoAdManager:didReceiveAccessLog:","modules":[{"name":"GFPSDK"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"videoAdManager","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)GFPVideoAdManager","text":"GFPVideoAdManager","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didReceive","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)AVPlayerItemAccessLog","text":"AVPlayerItemAccessLog","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":[{"introducedAt":"4.3","name":"iOS","deprecated":false,"beta":false,"unavailable":false},{"beta":false,"name":"iPadOS","deprecated":false,"unavailable":false,"introducedAt":"4.3"},{"beta":false,"name":"Mac Catalyst","introducedAt":"4.3","deprecated":false,"unavailable":false}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"videoAdManager","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"videoAdManager","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GFPVideoAdManager","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager","preciseIdentifier":"c:objc(cs)GFPVideoAdManager"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didReceive"},{"kind":"text","text":" "},{"kind":"internalParam","text":"accessLog"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)AVPlayerItemAccessLog","kind":"typeIdentifier","text":"AVPlayerItemAccessLog"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"비디오 광고 매니저","type":"text"}]}],"name":"videoAdManager"},{"name":"accessLog","content":[{"inlineContent":[{"type":"text","text":"AVPlayerItemAccessLog"}],"type":"paragraph"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpvideoadmanagerdelegate\/videoadmanager(_:didreceive:)-3ws0n"]},{"paths":["\/documentation\/gfpsdk\/gfpvideoadmanagerdelegate\/videoadmanager(_:didreceive:)-3ws0n"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManagerDelegate"]]},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManagerDelegate\/videoAdManager(_:didReceive:)-3ws0n","interfaceLanguage":"swift"},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdManagerDelegate":{"type":"topic","url":"\/documentation\/gfpsdk\/gfpvideoadmanagerdelegate","title":"GFPVideoAdManagerDelegate","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManagerDelegate","kind":"symbol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPVideoAdManagerDelegate"}],"navigatorTitle":[{"kind":"identifier","text":"GFPVideoAdManagerDelegate"}],"abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdManagerDelegate/videoAdManager(_:didReceive:)-3ws0n":{"url":"\/documentation\/gfpsdk\/gfpvideoadmanagerdelegate\/videoadmanager(_:didreceive:)-3ws0n","title":"videoAdManager(_:didReceive:)","abstract":[{"type":"text","text":"재생중인 광고플레이어가 AVPlayer 일 때(현재 NDA 한정), AVPlayerItem 에서 AccessLogEvent 가 발생한 경우 호출됩니다."}],"role":"symbol","required":true,"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManagerDelegate\/videoAdManager(_:didReceive:)-3ws0n","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"videoAdManager","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)GFPVideoAdManager","kind":"typeIdentifier","text":"GFPVideoAdManager"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didReceive"},{"text":": ","kind":"text"},{"text":"AVPlayerItemAccessLog","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVPlayerItemAccessLog"},{"text":")","kind":"text"}],"kind":"symbol","navigatorTitle":[{"text":"videoAdManager:didReceiveAccessLog:","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdManager":{"type":"topic","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager","role":"symbol","url":"\/documentation\/gfpsdk\/gfpvideoadmanager","title":"GFPVideoAdManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPVideoAdManager"}],"kind":"symbol","navigatorTitle":[{"text":"GFPVideoAdManager","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"videoAdManager:didReceiveAccessLog:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"videoAdManager:didReceiveAccessLog:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"videoAdManager:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoAdManager","text":"GFPVideoAdManager"},{"kind":"text","text":" *) "},{"text":"videoAdManager","kind":"internalParam"},{"kind":"text","text":" "},{"text":"didReceiveAccessLog:","kind":"identifier"},{"kind":"text","text":"("},{"text":"AVPlayerItemAccessLog","preciseIdentifier":"c:objc(cs)AVPlayerItemAccessLog","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"accessLog","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/primaryContentSections\/1","op":"replace","value":{"kind":"parameters","parameters":[{"name":"videoAdManager","content":[{"inlineContent":[{"type":"text","text":"비디오 광고 매니저"}],"type":"paragraph"}]},{"name":"accessLog","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"AVPlayerItemAccessLog"}]}]}]}},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManagerDelegate\/title","value":"GFPVideoAdManagerDelegate","op":"replace"},{"value":[{"kind":"identifier","text":"GFPVideoAdManagerDelegate"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManagerDelegate\/fragments","op":"replace"},{"value":[{"text":"GFPVideoAdManagerDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManagerDelegate\/navigatorTitle"},{"value":"videoAdManager:didReceiveAccessLog:","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManagerDelegate~1videoAdManager(_:didReceive:)-3ws0n\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManagerDelegate~1videoAdManager(_:didReceive:)-3ws0n\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"videoAdManager:didReceiveAccessLog:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManager\/title","value":"GFPVideoAdManager"},{"op":"replace","value":[{"text":"GFPVideoAdManager","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManager\/fragments"},{"value":[{"kind":"identifier","text":"GFPVideoAdManager"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManager\/navigatorTitle"}]}]}