{"abstract":[{"type":"text","text":"재생 컨트롤 Hide 애니메이션 시작 시 호출됩니다."}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManagerDelegate"]]},"sections":[],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpvideoadmanagerdelegate\/videoadmanager(_:playcontrolwillshow:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gfpsdk\/gfpvideoadmanagerdelegate\/videoadmanager(_:playcontrolwillshow:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"optional","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"videoAdManager"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"videoAdManager","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager","text":"GFPVideoAdManager","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoAdManager"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"playControlWillShow"},{"text":" ","kind":"text"},{"text":"duration","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Animation 타임","type":"text"}]}],"name":"duration"}],"kind":"parameters"}],"metadata":{"externalID":"c:objc(pl)GFPVideoAdManagerDelegate(im)videoAdManager:playControlWillShow:","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"videoAdManager","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoAdManager","text":"GFPVideoAdManager"},{"kind":"text","text":", "},{"text":"playControlWillShow","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"videoAdManager:playControlWillShow:","kind":"identifier"}],"modules":[{"name":"GFPSDK"}],"symbolKind":"method","role":"symbol","title":"videoAdManager(_:playControlWillShow:)","roleHeading":"Instance Method"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManagerDelegate\/videoAdManager(_:playControlWillShow:)"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdManager":{"type":"topic","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager","role":"symbol","url":"\/documentation\/gfpsdk\/gfpvideoadmanager","title":"GFPVideoAdManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPVideoAdManager"}],"kind":"symbol","navigatorTitle":[{"text":"GFPVideoAdManager","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdManagerDelegate/videoAdManager(_:playControlWillShow:)":{"required":true,"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"videoAdManager","kind":"identifier"},{"text":"(","kind":"text"},{"text":"GFPVideoAdManager","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoAdManager"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"playControlWillShow"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"재생 컨트롤 Hide 애니메이션 시작 시 호출됩니다."}],"navigatorTitle":[{"text":"videoAdManager:playControlWillShow:","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpvideoadmanagerdelegate\/videoadmanager(_:playcontrolwillshow:)","kind":"symbol","type":"topic","role":"symbol","title":"videoAdManager(_:playControlWillShow:)","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManagerDelegate\/videoAdManager(_:playControlWillShow:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdManagerDelegate":{"type":"topic","url":"\/documentation\/gfpsdk\/gfpvideoadmanagerdelegate","title":"GFPVideoAdManagerDelegate","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManagerDelegate","kind":"symbol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPVideoAdManagerDelegate"}],"navigatorTitle":[{"kind":"identifier","text":"GFPVideoAdManagerDelegate"}],"abstract":[]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"videoAdManager:playControlWillShow:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"videoAdManager:playControlWillShow:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"videoAdManager:"},{"kind":"text","text":"("},{"text":"GFPVideoAdManager","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdManager","preciseIdentifier":"c:objc(cs)GFPVideoAdManager"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"videoAdManager"},{"text":" ","kind":"text"},{"kind":"identifier","text":"playControlWillShow:"},{"text":"(","kind":"text"},{"text":"NSTimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":") ","kind":"text"},{"text":"duration","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"Animation 타임","type":"text"}],"type":"paragraph"}],"name":"duration"}]}},{"value":"GFPVideoAdManager","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManager\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManager\/fragments","value":[{"kind":"identifier","text":"GFPVideoAdManager"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManager\/navigatorTitle","value":[{"kind":"identifier","text":"GFPVideoAdManager"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManagerDelegate~1videoAdManager(_:playControlWillShow:)\/title","value":"videoAdManager:playControlWillShow:"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManagerDelegate~1videoAdManager(_:playControlWillShow:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"videoAdManager:playControlWillShow:","kind":"identifier"}]},{"value":"GFPVideoAdManagerDelegate","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManagerDelegate\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManagerDelegate\/fragments","value":[{"text":"GFPVideoAdManagerDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdManagerDelegate\/navigatorTitle","value":[{"text":"GFPVideoAdManagerDelegate","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}