{"metadata":{"role":"symbol","modules":[{"name":"GFPSDK"}],"externalID":"c:@M@GFPSDK@E@GFPVideoProviderOption@GFPVideoProviderOptionEnd","symbolKind":"case","title":"GFPVideoProviderOption.end","navigatorTitle":[{"text":"GFPVideoProviderOptionEnd","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"end","kind":"identifier"}],"roleHeading":"Case"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"end"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpvideoprovideroption\/end"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpvideoprovideroption\/end"]}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoProviderOption"]]},"kind":"symbol","identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoProviderOption\/end","interfaceLanguage":"swift"},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoProviderOption/end":{"role":"symbol","abstract":[],"title":"GFPVideoProviderOption.end","navigatorTitle":[{"text":"GFPVideoProviderOptionEnd","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"end","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoProviderOption\/end","type":"topic","kind":"symbol","url":"\/documentation\/gfpsdk\/gfpvideoprovideroption\/end"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoProviderOption":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoProviderOption","abstract":[{"text":"GFP에서 지원하는 비디오광고 제공자 목록","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPVideoProviderOption"}],"navigatorTitle":[{"text":"GFPVideoProviderOption","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpvideoprovideroption","type":"topic","title":"GFPVideoProviderOption"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"GFPVideoProviderOptionEnd","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"GFPVideoProviderOptionEnd","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"GFPVideoProviderOptionEnd","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoProviderOption~1end\/title","value":"GFPVideoProviderOptionEnd","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoProviderOption~1end\/fragments","value":[{"kind":"identifier","text":"GFPVideoProviderOptionEnd"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoProviderOption\/title","value":"GFPVideoProviderOption"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoProviderOption\/fragments","value":[{"text":"GFPVideoProviderOption","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoProviderOption\/navigatorTitle","value":[{"text":"GFPVideoProviderOption","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}