{"variants":[{"paths":["\/documentation\/gfpsdk\/gfpvideoprovideroption\/ima"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpvideoprovideroption\/ima"]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoProviderOption"]]},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"IMA"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoProviderOption\/IMA"},"kind":"symbol","metadata":{"role":"symbol","modules":[{"name":"GFPSDK"}],"symbolKind":"case","title":"GFPVideoProviderOption.IMA","roleHeading":"Case","externalID":"c:@M@GFPSDK@E@GFPVideoProviderOption@GFPVideoProviderOptionIMA","navigatorTitle":[{"kind":"identifier","text":"GFPVideoProviderOptionIMA"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"IMA"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoProviderOption":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoProviderOption","abstract":[{"text":"GFP에서 지원하는 비디오광고 제공자 목록","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPVideoProviderOption"}],"navigatorTitle":[{"text":"GFPVideoProviderOption","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpvideoprovideroption","type":"topic","title":"GFPVideoProviderOption"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoProviderOption/IMA":{"title":"GFPVideoProviderOption.IMA","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"IMA"}],"url":"\/documentation\/gfpsdk\/gfpvideoprovideroption\/ima","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoProviderOption\/IMA","navigatorTitle":[{"kind":"identifier","text":"GFPVideoProviderOptionIMA"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"GFPVideoProviderOptionIMA"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GFPVideoProviderOptionIMA"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"GFPVideoProviderOptionIMA"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoProviderOption\/title","value":"GFPVideoProviderOption"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoProviderOption\/fragments","value":[{"text":"GFPVideoProviderOption","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoProviderOption\/navigatorTitle","value":[{"kind":"identifier","text":"GFPVideoProviderOption"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoProviderOption~1IMA\/title","value":"GFPVideoProviderOptionIMA"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoProviderOption~1IMA\/fragments","value":[{"text":"GFPVideoProviderOptionIMA","kind":"identifier"}]}]}]}