{"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoProviderOption"]]},"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpvideoprovideroption\/nda"]},{"paths":["\/documentation\/gfpsdk\/gfpvideoprovideroption\/nda"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"modules":[{"name":"GFPSDK"}],"navigatorTitle":[{"text":"GFPVideoProviderOptionNDA","kind":"identifier"}],"symbolKind":"case","role":"symbol","roleHeading":"Case","externalID":"c:@M@GFPSDK@E@GFPVideoProviderOption@GFPVideoProviderOptionNDA","title":"GFPVideoProviderOption.NDA","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NDA"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoProviderOption\/NDA"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"NDA","kind":"identifier"}]}],"kind":"declarations"}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoProviderOption":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoProviderOption","abstract":[{"text":"GFP에서 지원하는 비디오광고 제공자 목록","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPVideoProviderOption"}],"navigatorTitle":[{"text":"GFPVideoProviderOption","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpvideoprovideroption","type":"topic","title":"GFPVideoProviderOption"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoProviderOption/NDA":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NDA"}],"navigatorTitle":[{"text":"GFPVideoProviderOptionNDA","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpvideoprovideroption\/nda","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoProviderOption\/NDA","kind":"symbol","role":"symbol","abstract":[],"type":"topic","title":"GFPVideoProviderOption.NDA"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"GFPVideoProviderOptionNDA"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"text":"GFPVideoProviderOptionNDA","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"GFPVideoProviderOptionNDA"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"value":"GFPVideoProviderOption","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoProviderOption\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"GFPVideoProviderOption"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoProviderOption\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoProviderOption\/navigatorTitle","value":[{"text":"GFPVideoProviderOption","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoProviderOption~1NDA\/title","value":"GFPVideoProviderOptionNDA"},{"value":[{"text":"GFPVideoProviderOptionNDA","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoProviderOption~1NDA\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}