{"kind":"symbol","metadata":{"title":"GFPVideoProviderOption.none","role":"symbol","modules":[{"name":"GFPSDK"}],"roleHeading":"Case","symbolKind":"case","navigatorTitle":[{"text":"GFPVideoProviderOptionNone","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"none","kind":"identifier"}],"externalID":"c:@M@GFPSDK@E@GFPVideoProviderOption@GFPVideoProviderOptionNone"},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoProviderOption\/none","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"none","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpvideoprovideroption\/none"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpvideoprovideroption\/none"]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoProviderOption"]]},"sections":[],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoProviderOption":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoProviderOption","abstract":[{"text":"GFP에서 지원하는 비디오광고 제공자 목록","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPVideoProviderOption"}],"navigatorTitle":[{"text":"GFPVideoProviderOption","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpvideoprovideroption","type":"topic","title":"GFPVideoProviderOption"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoProviderOption/none":{"type":"topic","title":"GFPVideoProviderOption.none","abstract":[],"role":"symbol","url":"\/documentation\/gfpsdk\/gfpvideoprovideroption\/none","navigatorTitle":[{"kind":"identifier","text":"GFPVideoProviderOptionNone"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoProviderOption\/none","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"none","kind":"identifier"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"GFPVideoProviderOptionNone","op":"replace"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"GFPVideoProviderOptionNone"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"GFPVideoProviderOptionNone"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"value":"GFPVideoProviderOption","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoProviderOption\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoProviderOption\/fragments","value":[{"text":"GFPVideoProviderOption","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoProviderOption\/navigatorTitle","value":[{"kind":"identifier","text":"GFPVideoProviderOption"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoProviderOption~1none\/title","value":"GFPVideoProviderOptionNone"},{"op":"replace","value":[{"kind":"identifier","text":"GFPVideoProviderOptionNone"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoProviderOption~1none\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}