{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpimpressiontracker\/exposedinfo(inscreen:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpimpressiontracker\/exposedinfo(inscreen:)"]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionTracker"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"exposedInfo"},{"kind":"text","text":"("},{"text":"inScreen","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"view"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"text":") -> ","kind":"text"},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPExposedInfo","text":"GFPExposedInfo","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPExposedInfo"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionTracker\/exposedInfo(inScreen:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"symbolKind":"method","title":"exposedInfo(inScreen:)","modules":[{"name":"GFPSDK"}],"role":"symbol","externalID":"c:objc(cs)GFPImpressionTracker(cm)exposedInfoInScreen:","roleHeading":"Type Method","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"exposedInfo","kind":"identifier"},{"kind":"text","text":"("},{"text":"inScreen","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIView","preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"GFPExposedInfo","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPExposedInfo"}],"navigatorTitle":[{"text":"exposedInfoInScreen:","kind":"identifier"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPImpressionTracker":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPImpressionTracker"}],"navigatorTitle":[{"text":"GFPImpressionTracker","kind":"identifier"}],"abstract":[],"type":"topic","url":"\/documentation\/gfpsdk\/gfpimpressiontracker","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionTracker","kind":"symbol","title":"GFPImpressionTracker"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPExposedInfo":{"navigatorTitle":[{"text":"GFPExposedInfo","kind":"identifier"}],"kind":"symbol","title":"GFPExposedInfo","url":"\/documentation\/gfpsdk\/gfpexposedinfo","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPExposedInfo","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPExposedInfo"}],"type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPImpressionTracker/exposedInfo(inScreen:)":{"navigatorTitle":[{"kind":"identifier","text":"exposedInfoInScreen:"}],"title":"exposedInfo(inScreen:)","url":"\/documentation\/gfpsdk\/gfpimpressiontracker\/exposedinfo(inscreen:)","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionTracker\/exposedInfo(inScreen:)","role":"symbol","type":"topic","kind":"symbol","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"exposedInfo","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"inScreen"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"text":") -> ","kind":"text"},{"text":"GFPExposedInfo","preciseIdentifier":"c:objc(cs)GFPExposedInfo","kind":"typeIdentifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"path":"\/metadata\/title","value":"exposedInfoInScreen:","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"exposedInfoInScreen:"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPExposedInfo","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPExposedInfo","kind":"typeIdentifier","text":"GFPExposedInfo"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"exposedInfoInScreen:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"},{"kind":"text","text":" *) "},{"text":"view","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"GFPImpressionTracker","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTracker\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTracker\/fragments","value":[{"text":"GFPImpressionTracker","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTracker\/navigatorTitle","op":"replace","value":[{"text":"GFPImpressionTracker","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPExposedInfo\/title","value":"GFPExposedInfo","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPExposedInfo\/fragments","value":[{"kind":"identifier","text":"GFPExposedInfo"}]},{"value":[{"kind":"identifier","text":"GFPExposedInfo"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPExposedInfo\/navigatorTitle","op":"replace"},{"value":"exposedInfoInScreen:","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTracker~1exposedInfo(inScreen:)\/title"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"exposedInfoInScreen:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTracker~1exposedInfo(inScreen:)\/fragments"}]}]}