{"metadata":{"externalID":"c:objc(cs)GFPImpressionTracker(im)stopTracking:","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopTracking"},{"kind":"text","text":"("},{"text":"GFPImpressionTrackingTarget","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPImpressionTrackingTarget"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"stopTracking:","kind":"identifier"}],"modules":[{"name":"GFPSDK"}],"symbolKind":"method","role":"symbol","roleHeading":"Instance Method","title":"stopTracking(_:)"},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionTracker\/stopTracking(_:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/gfpsdk\/gfpimpressiontracker\/stoptracking(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpimpressiontracker\/stoptracking(_:)"]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"stopTracking"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"target","kind":"internalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionTrackingTarget","text":"GFPImpressionTrackingTarget","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPImpressionTrackingTarget"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionTracker"]]},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPImpressionTracker":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPImpressionTracker"}],"navigatorTitle":[{"text":"GFPImpressionTracker","kind":"identifier"}],"abstract":[],"type":"topic","url":"\/documentation\/gfpsdk\/gfpimpressiontracker","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionTracker","kind":"symbol","title":"GFPImpressionTracker"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPImpressionTracker/stopTracking(_:)":{"navigatorTitle":[{"text":"stopTracking:","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpimpressiontracker\/stoptracking(_:)","type":"topic","kind":"symbol","title":"stopTracking(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stopTracking","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"GFPImpressionTrackingTarget","preciseIdentifier":"c:objc(cs)GFPImpressionTrackingTarget"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionTracker\/stopTracking(_:)","role":"symbol","abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPImpressionTrackingTarget":{"navigatorTitle":[{"text":"GFPImpressionTrackingTarget","kind":"identifier"}],"title":"GFPImpressionTrackingTarget","url":"\/documentation\/gfpsdk\/gfpimpressiontrackingtarget","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionTrackingTarget","role":"symbol","type":"topic","kind":"symbol","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPImpressionTrackingTarget","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"stopTracking:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"stopTracking:"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"stopTracking:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPImpressionTrackingTarget","text":"GFPImpressionTrackingTarget","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPImpressionTrackingTarget"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"target"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTracker\/title","value":"GFPImpressionTracker","op":"replace"},{"value":[{"text":"GFPImpressionTracker","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTracker\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTracker\/navigatorTitle","value":[{"text":"GFPImpressionTracker","kind":"identifier"}],"op":"replace"},{"value":"stopTracking:","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTracker~1stopTracking(_:)\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTracker~1stopTracking(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"stopTracking:","kind":"identifier"}],"op":"replace"},{"value":"GFPImpressionTrackingTarget","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTrackingTarget\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTrackingTarget\/fragments","op":"replace","value":[{"text":"GFPImpressionTrackingTarget","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPImpressionTrackingTarget\/navigatorTitle","value":[{"kind":"identifier","text":"GFPImpressionTrackingTarget"}]}]}]}