{"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLoadResponseInfo"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"recordSuccessResponseInfo"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"aLoadResponseInfo","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInternalResponseInfo","text":"GFPInternalResponseInfo","preciseIdentifier":"c:objc(cs)GFPInternalResponseInfo"},{"kind":"text","text":", "},{"kind":"externalParam","text":"endTime"},{"kind":"text","text":" "},{"text":"aEndTime","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"kind":"text","text":")"}],"platforms":["iOS"]}]}],"metadata":{"role":"symbol","modules":[{"name":"GFPSDK"}],"externalID":"c:objc(cs)GFPLoadResponseInfo(im)recordSuccessResponseInfo:endTime:","symbolKind":"method","title":"recordSuccessResponseInfo(_:endTime:)","navigatorTitle":[{"kind":"identifier","text":"recordSuccessResponseInfo:endTime:"}],"extendedModule":"GFPSDK","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"recordSuccessResponseInfo","kind":"identifier"},{"kind":"text","text":"("},{"text":"GFPInternalResponseInfo","preciseIdentifier":"c:objc(cs)GFPInternalResponseInfo","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"endTime","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfploadresponseinfo\/recordsuccessresponseinfo(_:endtime:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfploadresponseinfo\/recordsuccessresponseinfo(_:endtime:)"]}],"sections":[],"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLoadResponseInfo\/recordSuccessResponseInfo(_:endTime:)","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPInternalResponseInfo":{"abstract":[],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInternalResponseInfo","url":"\/documentation\/gfpsdk\/gfpinternalresponseinfo","navigatorTitle":[{"text":"GFPInternalResponseInfo","kind":"identifier"}],"title":"GFPInternalResponseInfo","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPInternalResponseInfo","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPLoadResponseInfo/recordSuccessResponseInfo(_:endTime:)":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLoadResponseInfo\/recordSuccessResponseInfo(_:endTime:)","url":"\/documentation\/gfpsdk\/gfploadresponseinfo\/recordsuccessresponseinfo(_:endtime:)","navigatorTitle":[{"kind":"identifier","text":"recordSuccessResponseInfo:endTime:"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"recordSuccessResponseInfo","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GFPInternalResponseInfo","preciseIdentifier":"c:objc(cs)GFPInternalResponseInfo"},{"kind":"text","text":", "},{"kind":"externalParam","text":"endTime"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"kind":"text","text":")"}],"kind":"symbol","abstract":[],"type":"topic","title":"recordSuccessResponseInfo(_:endTime:)","role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPLoadResponseInfo":{"title":"GFPLoadResponseInfo","url":"\/documentation\/gfpsdk\/gfploadresponseinfo","role":"symbol","navigatorTitle":[{"text":"GFPLoadResponseInfo","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"GFPLoadResponseInfo","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLoadResponseInfo"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"recordSuccessResponseInfo:endTime:","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"recordSuccessResponseInfo:endTime:"}]},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"recordSuccessResponseInfo:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GFPInternalResponseInfo","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInternalResponseInfo","preciseIdentifier":"c:objc(cs)GFPInternalResponseInfo"},{"text":" *) ","kind":"text"},{"text":"aLoadResponseInfo","kind":"internalParam"},{"kind":"text","text":" "},{"text":"endTime:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier","text":"NSNumber"},{"kind":"text","text":" *) "},{"text":"aEndTime","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInternalResponseInfo\/title","value":"GFPInternalResponseInfo"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInternalResponseInfo\/fragments","op":"replace","value":[{"kind":"identifier","text":"GFPInternalResponseInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInternalResponseInfo\/navigatorTitle","value":[{"text":"GFPInternalResponseInfo","kind":"identifier"}]},{"value":"recordSuccessResponseInfo:endTime:","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLoadResponseInfo~1recordSuccessResponseInfo(_:endTime:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"recordSuccessResponseInfo:endTime:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLoadResponseInfo~1recordSuccessResponseInfo(_:endTime:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLoadResponseInfo\/title","value":"GFPLoadResponseInfo"},{"op":"replace","value":[{"text":"GFPLoadResponseInfo","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLoadResponseInfo\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLoadResponseInfo\/navigatorTitle","value":[{"text":"GFPLoadResponseInfo","kind":"identifier"}],"op":"replace"}]}]}