{"metadata":{"role":"symbol","modules":[{"name":"GFPSDK"}],"externalID":"c:objc(cs)GFPLoadResponseInfo(im)recordErrorResponseInfo:event:","symbolKind":"method","title":"recordErrorResponseInfo(_:event:)","navigatorTitle":[{"kind":"identifier","text":"recordErrorResponseInfo:event:"}],"extendedModule":"GFPSDK","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"recordErrorResponseInfo"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)GFPInternalResponseInfo","kind":"typeIdentifier","text":"GFPInternalResponseInfo"},{"text":", ","kind":"text"},{"text":"event","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"GFPLoadEvent","preciseIdentifier":"c:objc(cs)GFPLoadEvent","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"recordErrorResponseInfo"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"aLoadResponseInfo","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInternalResponseInfo","text":"GFPInternalResponseInfo","preciseIdentifier":"c:objc(cs)GFPInternalResponseInfo","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"event"},{"text":" ","kind":"text"},{"text":"aLoadEvent","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPLoadEvent","text":"GFPLoadEvent","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLoadEvent"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfploadresponseinfo\/recorderrorresponseinfo(_:event:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfploadresponseinfo\/recorderrorresponseinfo(_:event:)"]}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLoadResponseInfo"]]},"kind":"symbol","identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLoadResponseInfo\/recordErrorResponseInfo(_:event:)","interfaceLanguage":"swift"},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPInternalResponseInfo":{"abstract":[],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInternalResponseInfo","url":"\/documentation\/gfpsdk\/gfpinternalresponseinfo","navigatorTitle":[{"text":"GFPInternalResponseInfo","kind":"identifier"}],"title":"GFPInternalResponseInfo","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPInternalResponseInfo","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPLoadResponseInfo":{"title":"GFPLoadResponseInfo","url":"\/documentation\/gfpsdk\/gfploadresponseinfo","role":"symbol","navigatorTitle":[{"text":"GFPLoadResponseInfo","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"GFPLoadResponseInfo","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLoadResponseInfo"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPLoadEvent":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPLoadEvent","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"GFPLoadEvent","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLoadEvent","abstract":[],"role":"symbol","url":"\/documentation\/gfpsdk\/gfploadevent","title":"GFPLoadEvent","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPLoadResponseInfo/recordErrorResponseInfo(_:event:)":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLoadResponseInfo\/recordErrorResponseInfo(_:event:)","url":"\/documentation\/gfpsdk\/gfploadresponseinfo\/recorderrorresponseinfo(_:event:)","navigatorTitle":[{"kind":"identifier","text":"recordErrorResponseInfo:event:"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"recordErrorResponseInfo","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GFPInternalResponseInfo","preciseIdentifier":"c:objc(cs)GFPInternalResponseInfo"},{"kind":"text","text":", "},{"kind":"externalParam","text":"event"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPLoadEvent","text":"GFPLoadEvent"},{"text":")","kind":"text"}],"kind":"symbol","abstract":[],"type":"topic","title":"recordErrorResponseInfo(_:event:)","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"value":"recordErrorResponseInfo:event:","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"recordErrorResponseInfo:event:"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"recordErrorResponseInfo:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"GFPInternalResponseInfo","preciseIdentifier":"c:objc(cs)GFPInternalResponseInfo","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInternalResponseInfo"},{"kind":"text","text":" *) "},{"text":"aLoadResponseInfo","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"event:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)GFPLoadEvent","text":"GFPLoadEvent","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLoadEvent"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"aLoadEvent"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInternalResponseInfo\/title","value":"GFPInternalResponseInfo","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInternalResponseInfo\/fragments","op":"replace","value":[{"kind":"identifier","text":"GFPInternalResponseInfo"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInternalResponseInfo\/navigatorTitle","value":[{"kind":"identifier","text":"GFPInternalResponseInfo"}],"op":"replace"},{"op":"replace","value":"GFPLoadResponseInfo","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLoadResponseInfo\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLoadResponseInfo\/fragments","op":"replace","value":[{"kind":"identifier","text":"GFPLoadResponseInfo"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLoadResponseInfo\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"GFPLoadResponseInfo"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLoadEvent\/title","op":"replace","value":"GFPLoadEvent"},{"value":[{"text":"GFPLoadEvent","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLoadEvent\/fragments","op":"replace"},{"value":[{"text":"GFPLoadEvent","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLoadEvent\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLoadResponseInfo~1recordErrorResponseInfo(_:event:)\/title","op":"replace","value":"recordErrorResponseInfo:event:"},{"value":[{"kind":"text","text":"- "},{"text":"recordErrorResponseInfo:event:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLoadResponseInfo~1recordErrorResponseInfo(_:event:)\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}