{"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoMediatorDelegate"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpvideomediatordelegate\/videomediator(_:didfailtoloadvideoadaptorwitherror:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpvideomediatordelegate\/videomediator(_:didfailtoloadvideoadaptorwitherror:)"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"videoMediator","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"mediator","kind":"internalParam"},{"kind":"text","text":": "},{"text":"GFPVideoMediator","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoMediator","preciseIdentifier":"c:objc(cs)GFPVideoMediator"},{"text":", ","kind":"text"},{"text":"didFailToLoadVideoAdaptorWithError","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GFPError","preciseIdentifier":"c:@M@NaverAdsServices@objc(cs)GFPError"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoMediatorDelegate\/videoMediator(_:didFailToLoadVideoAdaptorWithError:)","interfaceLanguage":"swift"},"metadata":{"required":true,"externalID":"c:objc(pl)GFPVideoMediatorDelegate(im)videoMediator:didFailToLoadVideoAdaptorWithError:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"videoMediator","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GFPVideoMediator","preciseIdentifier":"c:objc(cs)GFPVideoMediator"},{"kind":"text","text":", "},{"text":"didFailToLoadVideoAdaptorWithError","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@NaverAdsServices@objc(cs)GFPError","text":"GFPError","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"videoMediator:didFailToLoadVideoAdaptorWithError:","kind":"identifier"}],"modules":[{"name":"GFPSDK"}],"symbolKind":"method","role":"symbol","roleHeading":"Instance Method","title":"videoMediator(_:didFailToLoadVideoAdaptorWithError:)"},"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoMediator":{"title":"GFPVideoMediator","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoMediator","role":"symbol","kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPVideoMediator"}],"navigatorTitle":[{"kind":"identifier","text":"GFPVideoMediator"}],"type":"topic","url":"\/documentation\/gfpsdk\/gfpvideomediator"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoMediatorDelegate/videoMediator(_:didFailToLoadVideoAdaptorWithError:)":{"required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"videoMediator","kind":"identifier"},{"text":"(","kind":"text"},{"text":"GFPVideoMediator","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoMediator"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFailToLoadVideoAdaptorWithError"},{"kind":"text","text":": "},{"text":"GFPError","preciseIdentifier":"c:@M@NaverAdsServices@objc(cs)GFPError","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[],"navigatorTitle":[{"text":"videoMediator:didFailToLoadVideoAdaptorWithError:","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpvideomediatordelegate\/videomediator(_:didfailtoloadvideoadaptorwitherror:)","kind":"symbol","type":"topic","role":"symbol","title":"videoMediator(_:didFailToLoadVideoAdaptorWithError:)","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoMediatorDelegate\/videoMediator(_:didFailToLoadVideoAdaptorWithError:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoMediatorDelegate":{"url":"\/documentation\/gfpsdk\/gfpvideomediatordelegate","navigatorTitle":[{"kind":"identifier","text":"GFPVideoMediatorDelegate"}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPVideoMediatorDelegate","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoMediatorDelegate","type":"topic","abstract":[],"title":"GFPVideoMediatorDelegate","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"videoMediator:didFailToLoadVideoAdaptorWithError:","op":"replace","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"videoMediator:didFailToLoadVideoAdaptorWithError:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"text":"videoMediator:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoMediator","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoMediator","text":"GFPVideoMediator"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"mediator"},{"kind":"text","text":" "},{"text":"didFailToLoadVideoAdaptorWithError:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"GFPError","kind":"typeIdentifier","preciseIdentifier":"c:@M@NaverAdsServices@objc(cs)GFPError"},{"kind":"text","text":" *) "},{"text":"error","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoMediator\/title","value":"GFPVideoMediator","op":"replace"},{"value":[{"text":"GFPVideoMediator","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoMediator\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"GFPVideoMediator"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoMediator\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoMediatorDelegate~1videoMediator(_:didFailToLoadVideoAdaptorWithError:)\/title","op":"replace","value":"videoMediator:didFailToLoadVideoAdaptorWithError:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"videoMediator:didFailToLoadVideoAdaptorWithError:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoMediatorDelegate~1videoMediator(_:didFailToLoadVideoAdaptorWithError:)\/fragments"},{"value":"GFPVideoMediatorDelegate","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoMediatorDelegate\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoMediatorDelegate\/fragments","value":[{"text":"GFPVideoMediatorDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoMediatorDelegate\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"GFPVideoMediatorDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}