{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpvideomediatordelegate\/videomediator(_:didloadvideoadaptor:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpvideomediatordelegate\/videomediator(_:didloadvideoadaptor:)"]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoMediatorDelegate\/videoMediator(_:didLoadVideoAdaptor:)"},"metadata":{"role":"symbol","roleHeading":"Instance Method","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"videoMediator","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)GFPVideoMediator","text":"GFPVideoMediator","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didLoadVideoAdaptor"},{"text":": any ","kind":"text"},{"text":"GFPAdAdaptor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdAdaptor"},{"kind":"text","text":" & "},{"text":"GFPVideoAdapting","preciseIdentifier":"c:objc(pl)GFPVideoAdapting","kind":"typeIdentifier"},{"text":")","kind":"text"}],"externalID":"c:objc(pl)GFPVideoMediatorDelegate(im)videoMediator:didLoadVideoAdaptor:","title":"videoMediator(_:didLoadVideoAdaptor:)","modules":[{"name":"GFPSDK"}],"navigatorTitle":[{"text":"videoMediator:didLoadVideoAdaptor:","kind":"identifier"}],"required":true},"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoMediatorDelegate"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"videoMediator","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"mediator","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoMediator","text":"GFPVideoMediator","preciseIdentifier":"c:objc(cs)GFPVideoMediator"},{"kind":"text","text":", "},{"text":"didLoadVideoAdaptor","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"adaptor"},{"text":": any ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAdaptor","preciseIdentifier":"c:objc(cs)GFPAdAdaptor","text":"GFPAdAdaptor"},{"kind":"text","text":" & "},{"preciseIdentifier":"c:objc(pl)GFPVideoAdapting","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdapting","kind":"typeIdentifier","text":"GFPVideoAdapting"},{"kind":"text","text":")"}],"languages":["swift"]}]}],"sections":[],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoMediator":{"title":"GFPVideoMediator","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoMediator","role":"symbol","kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPVideoMediator"}],"navigatorTitle":[{"kind":"identifier","text":"GFPVideoMediator"}],"type":"topic","url":"\/documentation\/gfpsdk\/gfpvideomediator"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdapting":{"title":"GFPVideoAdapting","type":"topic","abstract":[],"url":"\/documentation\/gfpsdk\/gfpvideoadapting","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdapting","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPVideoAdapting"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPVideoAdapting"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoMediatorDelegate/videoMediator(_:didLoadVideoAdaptor:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"videoMediator","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPVideoMediator","kind":"typeIdentifier","text":"GFPVideoMediator"},{"text":", ","kind":"text"},{"text":"didLoadVideoAdaptor","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"GFPAdAdaptor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdAdaptor"},{"text":" & ","kind":"text"},{"preciseIdentifier":"c:objc(pl)GFPVideoAdapting","text":"GFPVideoAdapting","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoMediatorDelegate\/videoMediator(_:didLoadVideoAdaptor:)","title":"videoMediator(_:didLoadVideoAdaptor:)","required":true,"type":"topic","role":"symbol","abstract":[],"navigatorTitle":[{"text":"videoMediator:didLoadVideoAdaptor:","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpvideomediatordelegate\/videomediator(_:didloadvideoadaptor:)","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdAdaptor":{"navigatorTitle":[{"kind":"identifier","text":"GFPAdAdaptor"}],"title":"GFPAdAdaptor","url":"\/documentation\/gfpsdk\/gfpadadaptor","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAdaptor","abstract":[],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPAdAdaptor"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoMediatorDelegate":{"url":"\/documentation\/gfpsdk\/gfpvideomediatordelegate","navigatorTitle":[{"kind":"identifier","text":"GFPVideoMediatorDelegate"}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPVideoMediatorDelegate","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoMediatorDelegate","type":"topic","abstract":[],"title":"GFPVideoMediatorDelegate","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","value":"videoMediator:didLoadVideoAdaptor:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"videoMediator:didLoadVideoAdaptor:"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"videoMediator:","kind":"identifier"},{"kind":"text","text":"("},{"text":"GFPVideoMediator","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoMediator","preciseIdentifier":"c:objc(cs)GFPVideoMediator"},{"kind":"text","text":" *) "},{"text":"mediator","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"didLoadVideoAdaptor:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"GFPAdAdaptor<GFPVideoAdapting>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)GFPAdAdaptorobjc(pl)GFPVideoAdapting"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"adaptor"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"value":"GFPVideoMediator","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoMediator\/title"},{"value":[{"text":"GFPVideoMediator","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoMediator\/fragments","op":"replace"},{"op":"replace","value":[{"text":"GFPVideoMediator","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoMediator\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdapting\/title","value":"GFPVideoAdapting"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdapting\/fragments","value":[{"kind":"identifier","text":"GFPVideoAdapting"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdapting\/navigatorTitle","value":[{"text":"GFPVideoAdapting","kind":"identifier"}]},{"value":"videoMediator:didLoadVideoAdaptor:","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoMediatorDelegate~1videoMediator(_:didLoadVideoAdaptor:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoMediatorDelegate~1videoMediator(_:didLoadVideoAdaptor:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"videoMediator:didLoadVideoAdaptor:"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdaptor\/title","value":"GFPAdAdaptor","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdaptor\/fragments","value":[{"kind":"identifier","text":"GFPAdAdaptor"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdaptor\/navigatorTitle","value":[{"text":"GFPAdAdaptor","kind":"identifier"}]},{"op":"replace","value":"GFPVideoMediatorDelegate","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoMediatorDelegate\/title"},{"value":[{"text":"GFPVideoMediatorDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoMediatorDelegate\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoMediatorDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"GFPVideoMediatorDelegate"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}