{"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerViewDelegate\/bannerView(_:didChangeAdMeta:)","interfaceLanguage":"swift"},"metadata":{"title":"bannerView(_:didChangeAdMeta:)","role":"symbol","modules":[{"name":"GFPSDK"}],"symbolKind":"method","roleHeading":"Instance Method","navigatorTitle":[{"text":"bannerView:didChangeAdMeta:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bannerView"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"GFPBannerView","preciseIdentifier":"c:objc(cs)GFPBannerView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didChangeAdMeta"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":" : "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"])","kind":"text"}],"externalID":"c:objc(pl)GFPBannerViewDelegate(im)bannerView:didChangeAdMeta:"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"optional","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"bannerView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"bannerView"},{"kind":"text","text":": "},{"text":"GFPBannerView","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerView","preciseIdentifier":"c:objc(cs)GFPBannerView"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didChangeAdMeta"},{"text":" ","kind":"text"},{"text":"adMeta","kind":"internalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"])"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"GFPBannerView","type":"text"}]}],"name":"bannerView"},{"name":"adMeta","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"NSDictionary"}]}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpbannerviewdelegate\/bannerview(_:didchangeadmeta:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpbannerviewdelegate\/bannerview(_:didchangeadmeta:)"]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerViewDelegate"]]},"sections":[],"abstract":[{"type":"text","text":"배너 광고 소재에서 MetaData 변경 시 호출됩니다."}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerView":{"navigatorTitle":[{"text":"GFPBannerView","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerView","title":"GFPBannerView","role":"symbol","url":"\/documentation\/gfpsdk\/gfpbannerview","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPBannerView"}],"type":"topic","kind":"symbol","abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerViewDelegate/bannerView(_:didChangeAdMeta:)":{"url":"\/documentation\/gfpsdk\/gfpbannerviewdelegate\/bannerview(_:didchangeadmeta:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"bannerView","kind":"identifier"},{"kind":"text","text":"("},{"text":"GFPBannerView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPBannerView"},{"text":", ","kind":"text"},{"text":"didChangeAdMeta","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"])","kind":"text"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerViewDelegate\/bannerView(_:didChangeAdMeta:)","kind":"symbol","navigatorTitle":[{"text":"bannerView:didChangeAdMeta:","kind":"identifier"}],"role":"symbol","title":"bannerView(_:didChangeAdMeta:)","type":"topic","abstract":[{"type":"text","text":"배너 광고 소재에서 MetaData 변경 시 호출됩니다."}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerViewDelegate":{"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPBannerViewDelegate","kind":"identifier"}],"kind":"symbol","abstract":[],"url":"\/documentation\/gfpsdk\/gfpbannerviewdelegate","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerViewDelegate","title":"GFPBannerViewDelegate","type":"topic","navigatorTitle":[{"text":"GFPBannerViewDelegate","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"bannerView:didChangeAdMeta:","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"bannerView:didChangeAdMeta:"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"bannerView:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerView","text":"GFPBannerView","preciseIdentifier":"c:objc(cs)GFPBannerView"},{"kind":"text","text":" *) "},{"text":"bannerView","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"didChangeAdMeta:"},{"text":"(","kind":"text"},{"text":"NSDictionary<NSString *,NSString *>","preciseIdentifier":"c:Q$objc(cs)NSDictionary","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"adMeta"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/primaryContentSections\/1","op":"replace","value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"GFPBannerView","type":"text"}]}],"name":"bannerView"},{"name":"adMeta","content":[{"inlineContent":[{"type":"text","text":"NSDictionary"}],"type":"paragraph"}]}],"kind":"parameters"}},{"value":"GFPBannerView","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerView\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerView\/fragments","value":[{"kind":"identifier","text":"GFPBannerView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerView\/navigatorTitle","value":[{"kind":"identifier","text":"GFPBannerView"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerViewDelegate~1bannerView(_:didChangeAdMeta:)\/title","value":"bannerView:didChangeAdMeta:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerViewDelegate~1bannerView(_:didChangeAdMeta:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"bannerView:didChangeAdMeta:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerViewDelegate\/title","value":"GFPBannerViewDelegate"},{"value":[{"text":"GFPBannerViewDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerViewDelegate\/fragments"},{"value":[{"text":"GFPBannerViewDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerViewDelegate\/navigatorTitle","op":"replace"}]}]}