{"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerViewDelegate"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerViewDelegate\/bannerAdWasClicked(_:)"},"sections":[],"abstract":[{"type":"text","text":"배너 광고 클릭 시 호출됩니다."}],"metadata":{"navigatorTitle":[{"text":"bannerAdWasClicked:","kind":"identifier"}],"symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"bannerAdWasClicked","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GFPBannerView","preciseIdentifier":"c:objc(cs)GFPBannerView"},{"text":")","kind":"text"}],"roleHeading":"Instance Method","role":"symbol","title":"bannerAdWasClicked(_:)","externalID":"c:objc(pl)GFPBannerViewDelegate(im)bannerAdWasClicked:","modules":[{"name":"GFPSDK"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"optional"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"bannerAdWasClicked"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"bannerView"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)GFPBannerView","text":"GFPBannerView","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerView"},{"text":")","kind":"text"}]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"GFPBannerView","type":"text"}],"type":"paragraph"}],"name":"bannerView"}]}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpbannerviewdelegate\/banneradwasclicked(_:)"]},{"paths":["\/documentation\/gfpsdk\/gfpbannerviewdelegate\/banneradwasclicked(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerView":{"navigatorTitle":[{"text":"GFPBannerView","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerView","title":"GFPBannerView","role":"symbol","url":"\/documentation\/gfpsdk\/gfpbannerview","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPBannerView"}],"type":"topic","kind":"symbol","abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerViewDelegate":{"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPBannerViewDelegate","kind":"identifier"}],"kind":"symbol","abstract":[],"url":"\/documentation\/gfpsdk\/gfpbannerviewdelegate","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerViewDelegate","title":"GFPBannerViewDelegate","type":"topic","navigatorTitle":[{"text":"GFPBannerViewDelegate","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerViewDelegate/bannerAdWasClicked(_:)":{"title":"bannerAdWasClicked(_:)","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerViewDelegate\/bannerAdWasClicked(_:)","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"배너 광고 클릭 시 호출됩니다."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"bannerAdWasClicked"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPBannerView","text":"GFPBannerView"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"bannerAdWasClicked:"}],"type":"topic","url":"\/documentation\/gfpsdk\/gfpbannerviewdelegate\/banneradwasclicked(_:)"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"bannerAdWasClicked:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"bannerAdWasClicked:"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"bannerAdWasClicked:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerView","text":"GFPBannerView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPBannerView"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"bannerView"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"value":{"kind":"parameters","parameters":[{"name":"bannerView","content":[{"type":"paragraph","inlineContent":[{"text":"GFPBannerView","type":"text"}]}]}]},"op":"replace","path":"\/primaryContentSections\/1"},{"value":"GFPBannerView","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerView\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerView\/fragments","op":"replace","value":[{"text":"GFPBannerView","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerView\/navigatorTitle","value":[{"text":"GFPBannerView","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerViewDelegate\/title","op":"replace","value":"GFPBannerViewDelegate"},{"op":"replace","value":[{"text":"GFPBannerViewDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerViewDelegate\/fragments"},{"value":[{"kind":"identifier","text":"GFPBannerViewDelegate"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerViewDelegate\/navigatorTitle"},{"value":"bannerAdWasClicked:","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerViewDelegate~1bannerAdWasClicked(_:)\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerViewDelegate~1bannerAdWasClicked(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"bannerAdWasClicked:"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}