{"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpbannerviewdelegate\/banneradwasseen(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpbannerviewdelegate\/banneradwasseen(_:)"]}],"metadata":{"title":"bannerAdWasSeen(_:)","required":true,"modules":[{"name":"GFPSDK"}],"role":"symbol","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bannerAdWasSeen","kind":"identifier"},{"text":"(","kind":"text"},{"text":"GFPBannerView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPBannerView"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"bannerAdWasSeen:","kind":"identifier"}],"symbolKind":"method","externalID":"c:objc(pl)GFPBannerViewDelegate(im)bannerAdWasSeen:"},"kind":"symbol","abstract":[{"text":"배너 광고가 사용자에게 보여진 경우 호출됩니다.(viewable impression)","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerViewDelegate"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bannerAdWasSeen"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"bannerView"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"GFPBannerView","preciseIdentifier":"c:objc(cs)GFPBannerView","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerView"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"GFPBannerView"}],"type":"paragraph"}],"name":"bannerView"}],"kind":"parameters"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerViewDelegate\/bannerAdWasSeen(_:)"},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerViewDelegate/bannerAdWasSeen(_:)":{"url":"\/documentation\/gfpsdk\/gfpbannerviewdelegate\/banneradwasseen(_:)","title":"bannerAdWasSeen(_:)","type":"topic","required":true,"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"bannerAdWasSeen","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPBannerView","text":"GFPBannerView"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"bannerAdWasSeen:"}],"abstract":[{"type":"text","text":"배너 광고가 사용자에게 보여진 경우 호출됩니다.(viewable impression)"}],"kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerViewDelegate\/bannerAdWasSeen(_:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerView":{"navigatorTitle":[{"text":"GFPBannerView","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerView","title":"GFPBannerView","role":"symbol","url":"\/documentation\/gfpsdk\/gfpbannerview","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPBannerView"}],"type":"topic","kind":"symbol","abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerViewDelegate":{"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPBannerViewDelegate","kind":"identifier"}],"kind":"symbol","abstract":[],"url":"\/documentation\/gfpsdk\/gfpbannerviewdelegate","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerViewDelegate","title":"GFPBannerViewDelegate","type":"topic","navigatorTitle":[{"text":"GFPBannerViewDelegate","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"bannerAdWasSeen:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"bannerAdWasSeen:","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"text":"bannerAdWasSeen:","kind":"identifier"},{"kind":"text","text":"("},{"text":"GFPBannerView","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPBannerView"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"bannerView"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"GFPBannerView"}],"type":"paragraph"}],"name":"bannerView"}],"kind":"parameters"},"op":"replace","path":"\/primaryContentSections\/1"},{"value":"bannerAdWasSeen:","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerViewDelegate~1bannerAdWasSeen(_:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"bannerAdWasSeen:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerViewDelegate~1bannerAdWasSeen(_:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerView\/title","value":"GFPBannerView"},{"value":[{"text":"GFPBannerView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerView\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerView\/navigatorTitle","value":[{"text":"GFPBannerView","kind":"identifier"}]},{"op":"replace","value":"GFPBannerViewDelegate","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerViewDelegate\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerViewDelegate\/fragments","value":[{"kind":"identifier","text":"GFPBannerViewDelegate"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerViewDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"GFPBannerViewDelegate"}],"op":"replace"}]}]}