{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerViewDelegate\/bannerView(_:didLoad:)"},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerViewDelegate"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bannerView"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"bannerView","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)GFPBannerView","text":"GFPBannerView","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerView"},{"text":", ","kind":"text"},{"text":"didLoad","kind":"externalParam"},{"kind":"text","text":" "},{"text":"nativeAd","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAd","preciseIdentifier":"c:objc(cs)GFPNativeAd","text":"GFPNativeAd","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"로드를 요청한 GFPBannerView 객체"}]}],"name":"bannerView"},{"name":"nativeAd","content":[{"inlineContent":[{"text":"네이티브 광고 응답","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpbannerviewdelegate\/bannerview(_:didload:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpbannerviewdelegate\/bannerview(_:didload:)"]}],"abstract":[{"type":"text","text":"GFPBannerView 의 네이티브 광고 로드가 허용(nativeAdEnabled = YES)되어 있을 때, 네이티브 광고가 정상적으로 로드되면 호출됩니다."}],"kind":"symbol","metadata":{"externalID":"c:objc(pl)GFPBannerViewDelegate(im)bannerView:didLoadNativeAd:","navigatorTitle":[{"kind":"identifier","text":"bannerView:didLoadNativeAd:"}],"title":"bannerView(_:didLoad:)","role":"symbol","symbolKind":"method","roleHeading":"Instance Method","modules":[{"name":"GFPSDK"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"bannerView"},{"kind":"text","text":"("},{"text":"GFPBannerView","preciseIdentifier":"c:objc(cs)GFPBannerView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didLoad"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPNativeAd","text":"GFPNativeAd"},{"kind":"text","text":")"}]},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerViewDelegate/bannerView(_:didLoad:)":{"navigatorTitle":[{"kind":"identifier","text":"bannerView:didLoadNativeAd:"}],"url":"\/documentation\/gfpsdk\/gfpbannerviewdelegate\/bannerview(_:didload:)","title":"bannerView(_:didLoad:)","role":"symbol","abstract":[{"type":"text","text":"GFPBannerView 의 네이티브 광고 로드가 허용(nativeAdEnabled = YES)되어 있을 때, 네이티브 광고가 정상적으로 로드되면 호출됩니다."}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"bannerView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GFPBannerView","preciseIdentifier":"c:objc(cs)GFPBannerView"},{"text":", ","kind":"text"},{"text":"didLoad","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GFPNativeAd","preciseIdentifier":"c:objc(cs)GFPNativeAd"},{"kind":"text","text":")"}],"type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerViewDelegate\/bannerView(_:didLoad:)","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerViewDelegate":{"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPBannerViewDelegate","kind":"identifier"}],"kind":"symbol","abstract":[],"url":"\/documentation\/gfpsdk\/gfpbannerviewdelegate","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerViewDelegate","title":"GFPBannerViewDelegate","type":"topic","navigatorTitle":[{"text":"GFPBannerViewDelegate","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerView":{"navigatorTitle":[{"text":"GFPBannerView","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerView","title":"GFPBannerView","role":"symbol","url":"\/documentation\/gfpsdk\/gfpbannerview","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPBannerView"}],"type":"topic","kind":"symbol","abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAd":{"abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAd","url":"\/documentation\/gfpsdk\/gfpnativead","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPNativeAd"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPNativeAd"}],"type":"topic","kind":"symbol","title":"GFPNativeAd"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"bannerView:didLoadNativeAd:","path":"\/metadata\/title","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"bannerView:didLoadNativeAd:"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"bannerView:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerView","preciseIdentifier":"c:objc(cs)GFPBannerView","text":"GFPBannerView","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"bannerView","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"didLoadNativeAd:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPNativeAd","text":"GFPNativeAd","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAd"},{"kind":"text","text":" *) "},{"text":"nativeAd","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"kind":"parameters","parameters":[{"name":"bannerView","content":[{"inlineContent":[{"text":"로드를 요청한 GFPBannerView 객체","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"네이티브 광고 응답","type":"text"}],"type":"paragraph"}],"name":"nativeAd"}]}},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerViewDelegate~1bannerView(_:didLoad:)\/title","value":"bannerView:didLoadNativeAd:","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerViewDelegate~1bannerView(_:didLoad:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"bannerView:didLoadNativeAd:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerViewDelegate\/title","value":"GFPBannerViewDelegate","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerViewDelegate\/fragments","value":[{"kind":"identifier","text":"GFPBannerViewDelegate"}]},{"value":[{"kind":"identifier","text":"GFPBannerViewDelegate"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerViewDelegate\/navigatorTitle","op":"replace"},{"value":"GFPBannerView","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerView\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerView\/fragments","value":[{"kind":"identifier","text":"GFPBannerView"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerView\/navigatorTitle","op":"replace","value":[{"text":"GFPBannerView","kind":"identifier"}]},{"value":"GFPNativeAd","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAd\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAd\/fragments","value":[{"kind":"identifier","text":"GFPNativeAd"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAd\/navigatorTitle","value":[{"kind":"identifier","text":"GFPNativeAd"}],"op":"replace"}]}]}