{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"notYetLoaded","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"metadata":{"title":"notYetLoaded","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"notYetLoaded"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"roleHeading":"Instance Property","role":"symbol","externalID":"c:objc(cs)GFPVideoAdSourceInfo(py)notYetLoaded","symbolKind":"property","navigatorTitle":[{"text":"notYetLoaded","kind":"identifier"}],"modules":[{"name":"GFPSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdSourceInfo"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdSourceInfo\/notYetLoaded"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpvideoadsourceinfo\/notyetloaded"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpvideoadsourceinfo\/notyetloaded"]}],"sections":[],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdSourceInfo/notYetLoaded":{"abstract":[],"type":"topic","title":"notYetLoaded","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"notYetLoaded"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/gfpsdk\/gfpvideoadsourceinfo\/notyetloaded","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdSourceInfo\/notYetLoaded","navigatorTitle":[{"kind":"identifier","text":"notYetLoaded"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdSourceInfo":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"GFPVideoAdSourceInfo","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"GFPVideoAdSourceInfo"}],"url":"\/documentation\/gfpsdk\/gfpvideoadsourceinfo","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdSourceInfo","kind":"symbol","role":"symbol","abstract":[],"type":"topic","title":"GFPVideoAdSourceInfo"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"notYetLoaded","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"notYetLoaded","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"assign"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":" "},{"text":"notYetLoaded","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdSourceInfo~1notYetLoaded\/title","value":"notYetLoaded"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdSourceInfo~1notYetLoaded\/fragments","value":[{"text":"notYetLoaded","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdSourceInfo\/title","value":"GFPVideoAdSourceInfo","op":"replace"},{"value":[{"text":"GFPVideoAdSourceInfo","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdSourceInfo\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdSourceInfo\/navigatorTitle","value":[{"text":"GFPVideoAdSourceInfo","kind":"identifier"}]}]}]}