{"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"title":"dict","roleHeading":"Instance Property","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dict"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"]?","kind":"text"}],"modules":[{"name":"GFPSDK"}],"navigatorTitle":[{"text":"dict","kind":"identifier"}],"externalID":"c:objc(cs)GFPContentInfo(py)dict","symbolKind":"property"},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPContentInfo\/dict","interfaceLanguage":"swift"},"sections":[],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpcontentinfo\/dict"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpcontentinfo\/dict"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPContentInfo"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dict","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":" : ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"]? { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPContentInfo/dict":{"kind":"symbol","title":"dict","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPContentInfo\/dict","url":"\/documentation\/gfpsdk\/gfpcontentinfo\/dict","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"dict"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":" : ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"]?","kind":"text"}],"navigatorTitle":[{"text":"dict","kind":"identifier"}],"abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPContentInfo":{"type":"topic","abstract":[],"kind":"symbol","navigatorTitle":[{"text":"GFPContentInfo","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPContentInfo","url":"\/documentation\/gfpsdk\/gfpcontentinfo","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPContentInfo","kind":"identifier"}],"title":"GFPContentInfo"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"value":"dict","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"text":"dict","kind":"identifier"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSDictionary<NSString *,NSString *>","preciseIdentifier":"c:Q$objc(cs)NSDictionary"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"dict"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"value":"dict","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPContentInfo~1dict\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPContentInfo~1dict\/fragments","op":"replace","value":[{"text":"dict","kind":"identifier"}]},{"value":"GFPContentInfo","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPContentInfo\/title"},{"value":[{"text":"GFPContentInfo","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPContentInfo\/fragments"},{"value":[{"text":"GFPContentInfo","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPContentInfo\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}