{"metadata":{"role":"symbol","modules":[{"name":"GFPSDK"}],"externalID":"c:objc(pl)GFPClickLandingUtilDelegate(im)didDissmissDefaultInAppBrowse:","symbolKind":"method","title":"didDissmissDefault(inAppBrowse:)","navigatorTitle":[{"kind":"identifier","text":"didDissmissDefaultInAppBrowse:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didDissmissDefault","kind":"identifier"},{"text":"(","kind":"text"},{"text":"inAppBrowse","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPClickLandingUtil","kind":"typeIdentifier","text":"GFPClickLandingUtil"},{"kind":"text","text":")"}],"roleHeading":"Instance Method","required":true},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"didDissmissDefault"},{"text":"(","kind":"text"},{"text":"inAppBrowse","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"landingUtil"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPClickLandingUtil","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPClickLandingUtil","text":"GFPClickLandingUtil"},{"kind":"text","text":")"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpclicklandingutildelegate\/diddissmissdefault(inappbrowse:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gfpsdk\/gfpclicklandingutildelegate\/diddissmissdefault(inappbrowse:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPClickLandingUtilDelegate"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPClickLandingUtilDelegate\/didDissmissDefault(inAppBrowse:)"},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPClickLandingUtilDelegate/didDissmissDefault(inAppBrowse:)":{"required":true,"role":"symbol","abstract":[],"title":"didDissmissDefault(inAppBrowse:)","navigatorTitle":[{"text":"didDissmissDefaultInAppBrowse:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"didDissmissDefault","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"inAppBrowse"},{"text":": ","kind":"text"},{"text":"GFPClickLandingUtil","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPClickLandingUtil"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPClickLandingUtilDelegate\/didDissmissDefault(inAppBrowse:)","type":"topic","kind":"symbol","url":"\/documentation\/gfpsdk\/gfpclicklandingutildelegate\/diddissmissdefault(inappbrowse:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPClickLandingUtilDelegate":{"navigatorTitle":[{"kind":"identifier","text":"GFPClickLandingUtilDelegate"}],"url":"\/documentation\/gfpsdk\/gfpclicklandingutildelegate","abstract":[],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPClickLandingUtilDelegate","kind":"identifier"}],"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPClickLandingUtilDelegate","title":"GFPClickLandingUtilDelegate"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPClickLandingUtil":{"url":"\/documentation\/gfpsdk\/gfpclicklandingutil","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPClickLandingUtil"}],"type":"topic","kind":"symbol","title":"GFPClickLandingUtil","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPClickLandingUtil","navigatorTitle":[{"text":"GFPClickLandingUtil","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","value":"didDissmissDefaultInAppBrowse:","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"didDissmissDefaultInAppBrowse:"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"didDissmissDefaultInAppBrowse:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)GFPClickLandingUtil","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPClickLandingUtil","text":"GFPClickLandingUtil","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"landingUtil","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPClickLandingUtilDelegate~1didDissmissDefault(inAppBrowse:)\/title","value":"didDissmissDefaultInAppBrowse:"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPClickLandingUtilDelegate~1didDissmissDefault(inAppBrowse:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"didDissmissDefaultInAppBrowse:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPClickLandingUtilDelegate\/title","value":"GFPClickLandingUtilDelegate","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPClickLandingUtilDelegate\/fragments","value":[{"text":"GFPClickLandingUtilDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPClickLandingUtilDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"GFPClickLandingUtilDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPClickLandingUtil\/title","value":"GFPClickLandingUtil"},{"value":[{"text":"GFPClickLandingUtil","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPClickLandingUtil\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPClickLandingUtil\/navigatorTitle","value":[{"kind":"identifier","text":"GFPClickLandingUtil"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}