{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpclicklandingutildelegate\/didpresentdefault(inappbrowse:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpclicklandingutildelegate\/didpresentdefault(inappbrowse:)"]}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"title":"didPresentDefault(inAppBrowse:)","role":"symbol","modules":[{"name":"GFPSDK"}],"roleHeading":"Instance Method","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"didPresentDefaultInAppBrowse:"}],"required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didPresentDefault","kind":"identifier"},{"kind":"text","text":"("},{"text":"inAppBrowse","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)GFPClickLandingUtil","text":"GFPClickLandingUtil","kind":"typeIdentifier"},{"kind":"text","text":")"}],"externalID":"c:objc(pl)GFPClickLandingUtilDelegate(im)didPresentDefaultInAppBrowse:"},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPClickLandingUtilDelegate\/didPresentDefault(inAppBrowse:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"didPresentDefault","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"inAppBrowse"},{"text":" ","kind":"text"},{"text":"landingUtil","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPClickLandingUtil","text":"GFPClickLandingUtil","preciseIdentifier":"c:objc(cs)GFPClickLandingUtil"},{"text":")","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPClickLandingUtilDelegate"]]},"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPClickLandingUtilDelegate":{"navigatorTitle":[{"kind":"identifier","text":"GFPClickLandingUtilDelegate"}],"url":"\/documentation\/gfpsdk\/gfpclicklandingutildelegate","abstract":[],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPClickLandingUtilDelegate","kind":"identifier"}],"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPClickLandingUtilDelegate","title":"GFPClickLandingUtilDelegate"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPClickLandingUtilDelegate/didPresentDefault(inAppBrowse:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didPresentDefault","kind":"identifier"},{"kind":"text","text":"("},{"text":"inAppBrowse","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"GFPClickLandingUtil","preciseIdentifier":"c:objc(cs)GFPClickLandingUtil","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[],"url":"\/documentation\/gfpsdk\/gfpclicklandingutildelegate\/didpresentdefault(inappbrowse:)","navigatorTitle":[{"kind":"identifier","text":"didPresentDefaultInAppBrowse:"}],"required":true,"kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPClickLandingUtilDelegate\/didPresentDefault(inAppBrowse:)","type":"topic","title":"didPresentDefault(inAppBrowse:)","role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPClickLandingUtil":{"url":"\/documentation\/gfpsdk\/gfpclicklandingutil","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPClickLandingUtil"}],"type":"topic","kind":"symbol","title":"GFPClickLandingUtil","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPClickLandingUtil","navigatorTitle":[{"text":"GFPClickLandingUtil","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"didPresentDefaultInAppBrowse:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"didPresentDefaultInAppBrowse:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"didPresentDefaultInAppBrowse:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPClickLandingUtil","text":"GFPClickLandingUtil","preciseIdentifier":"c:objc(cs)GFPClickLandingUtil","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"landingUtil"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPClickLandingUtilDelegate\/title","value":"GFPClickLandingUtilDelegate","op":"replace"},{"value":[{"text":"GFPClickLandingUtilDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPClickLandingUtilDelegate\/fragments"},{"value":[{"text":"GFPClickLandingUtilDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPClickLandingUtilDelegate\/navigatorTitle","op":"replace"},{"value":"didPresentDefaultInAppBrowse:","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPClickLandingUtilDelegate~1didPresentDefault(inAppBrowse:)\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPClickLandingUtilDelegate~1didPresentDefault(inAppBrowse:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"didPresentDefaultInAppBrowse:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPClickLandingUtil\/title","value":"GFPClickLandingUtil"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPClickLandingUtil\/fragments","value":[{"kind":"identifier","text":"GFPClickLandingUtil"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPClickLandingUtil\/navigatorTitle","value":[{"kind":"identifier","text":"GFPClickLandingUtil"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}