{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBundle\/sharedInstance"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"sharedInstance","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"GFPBundle","preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPBundle","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBundle"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpbundle\/sharedinstance"]},{"paths":["\/documentation\/gfpsdk\/gfpbundle\/sharedinstance"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"property","modules":[{"name":"GFPSDK"}],"roleHeading":"Type Property","title":"sharedInstance","externalID":"c:@M@GFPSDK@objc(cs)GFPBundle(cpy)sharedInstance","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"sharedInstance"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"GFPBundle","preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPBundle"}],"navigatorTitle":[{"text":"sharedInstance","kind":"identifier"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBundle"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBundle/sharedInstance":{"title":"sharedInstance","url":"\/documentation\/gfpsdk\/gfpbundle\/sharedinstance","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBundle\/sharedInstance","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"sharedInstance","kind":"identifier"},{"kind":"text","text":": "},{"text":"GFPBundle","kind":"typeIdentifier","preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPBundle"}],"navigatorTitle":[{"text":"sharedInstance","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBundle":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"GFPBundle","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"GFPBundle","url":"\/documentation\/gfpsdk\/gfpbundle","navigatorTitle":[{"text":"GFPBundle","kind":"identifier"}],"abstract":[],"type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBundle"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Property"},{"value":"sharedInstance","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"sharedInstance","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"GFPBundle","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBundle","kind":"typeIdentifier","preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPBundle"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"sharedInstance"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBundle~1sharedInstance\/title","value":"sharedInstance"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBundle~1sharedInstance\/fragments","value":[{"kind":"identifier","text":"sharedInstance"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBundle\/title","value":"GFPBundle"},{"value":[{"text":"GFPBundle","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBundle\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBundle\/navigatorTitle","value":[{"kind":"identifier","text":"GFPBundle"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}