{"abstract":[{"text":"광고 재생 시작 가능 시  호출됩니다.","type":"text"}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"externalID":"c:objc(pl)GFPVideoAdScheduleManagerDelegate(im)scheduleManager:didStartReadyAd:","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"scheduleManager"},{"kind":"text","text":"("},{"text":"GFPVideoAdScheduleManager","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoAdScheduleManager"},{"text":", ","kind":"text"},{"text":"didStartReadyAd","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoAdBreakResult","text":"GFPVideoAdBreakResult"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"scheduleManager:didStartReadyAd:"}],"modules":[{"name":"GFPSDK"}],"required":true,"title":"scheduleManager(_:didStartReadyAd:)","role":"symbol","symbolKind":"method"},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManagerDelegate"]]},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManagerDelegate\/scheduleManager(_:didStartReadyAd:)","interfaceLanguage":"swift"},"sections":[],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpvideoadschedulemanagerdelegate\/schedulemanager(_:didstartreadyad:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gfpsdk\/gfpvideoadschedulemanagerdelegate\/schedulemanager(_:didstartreadyad:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"scheduleManager","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"aScheduleAdManager"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)GFPVideoAdScheduleManager","text":"GFPVideoAdScheduleManager","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"didStartReadyAd","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"aResult"},{"kind":"text","text":": "},{"text":"GFPVideoAdBreakResult","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoAdBreakResult","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdBreakResult"},{"kind":"text","text":")"}]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"스케쥴 매니저"}]}],"name":"aScheduleAdManager"},{"name":"aResult","content":[{"inlineContent":[{"text":"재생 광고 정보","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdBreakResult":{"abstract":[],"kind":"symbol","title":"GFPVideoAdBreakResult","navigatorTitle":[{"text":"GFPVideoAdBreakResult","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdBreakResult","url":"\/documentation\/gfpsdk\/gfpvideoadbreakresult","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"GFPVideoAdBreakResult","kind":"identifier"}],"role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdScheduleManagerDelegate":{"type":"topic","kind":"symbol","url":"\/documentation\/gfpsdk\/gfpvideoadschedulemanagerdelegate","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManagerDelegate","title":"GFPVideoAdScheduleManagerDelegate","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"GFPVideoAdScheduleManagerDelegate"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPVideoAdScheduleManagerDelegate"}],"role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdScheduleManagerDelegate/scheduleManager(_:didStartReadyAd:)":{"navigatorTitle":[{"text":"scheduleManager:didStartReadyAd:","kind":"identifier"}],"abstract":[{"type":"text","text":"광고 재생 시작 가능 시  호출됩니다."}],"title":"scheduleManager(_:didStartReadyAd:)","required":true,"url":"\/documentation\/gfpsdk\/gfpvideoadschedulemanagerdelegate\/schedulemanager(_:didstartreadyad:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"scheduleManager","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPVideoAdScheduleManager","text":"GFPVideoAdScheduleManager","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didStartReadyAd","kind":"externalParam"},{"kind":"text","text":": "},{"text":"GFPVideoAdBreakResult","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoAdBreakResult"},{"text":")","kind":"text"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManagerDelegate\/scheduleManager(_:didStartReadyAd:)","role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdScheduleManager":{"kind":"symbol","type":"topic","url":"\/documentation\/gfpsdk\/gfpvideoadschedulemanager","title":"GFPVideoAdScheduleManager","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager","navigatorTitle":[{"kind":"identifier","text":"GFPVideoAdScheduleManager"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPVideoAdScheduleManager"}],"abstract":[],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"scheduleManager:didStartReadyAd:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"scheduleManager:didStartReadyAd:","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"scheduleManager:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager","text":"GFPVideoAdScheduleManager","preciseIdentifier":"c:objc(cs)GFPVideoAdScheduleManager"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"aScheduleAdManager"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didStartReadyAd:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdBreakResult","text":"GFPVideoAdBreakResult","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoAdBreakResult"},{"text":" *) ","kind":"text"},{"text":"aResult","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"aScheduleAdManager","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"스케쥴 매니저"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"재생 광고 정보"}],"type":"paragraph"}],"name":"aResult"}]}},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdBreakResult\/title","value":"GFPVideoAdBreakResult"},{"op":"replace","value":[{"text":"GFPVideoAdBreakResult","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdBreakResult\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdBreakResult\/navigatorTitle","value":[{"text":"GFPVideoAdBreakResult","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManagerDelegate\/title","value":"GFPVideoAdScheduleManagerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManagerDelegate\/fragments","value":[{"kind":"identifier","text":"GFPVideoAdScheduleManagerDelegate"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManagerDelegate\/navigatorTitle","op":"replace","value":[{"text":"GFPVideoAdScheduleManagerDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManagerDelegate~1scheduleManager(_:didStartReadyAd:)\/title","value":"scheduleManager:didStartReadyAd:","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManagerDelegate~1scheduleManager(_:didStartReadyAd:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"scheduleManager:didStartReadyAd:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager\/title","value":"GFPVideoAdScheduleManager"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager\/fragments","op":"replace","value":[{"text":"GFPVideoAdScheduleManager","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager\/navigatorTitle","op":"replace","value":[{"text":"GFPVideoAdScheduleManager","kind":"identifier"}]}]}]}