{"abstract":[{"text":"광고 로드, 재생에 실패한 경우 호출됩니다.","type":"text"},{"text":" ","type":"text"},{"text":"(컨텐츠 영상을 재생해 주세요.)","type":"text"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"optional","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"scheduleManager"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"aScheduleAdManager","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"GFPVideoAdScheduleManager","preciseIdentifier":"c:objc(cs)GFPVideoAdScheduleManager","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFailWith"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"aResult"},{"kind":"text","text":": "},{"text":"GFPVideoAdBreakResult","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdBreakResult","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoAdBreakResult"},{"kind":"text","text":")"}]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"스케쥴 매니저"}]}],"name":"aScheduleAdManager"},{"content":[{"type":"paragraph","inlineContent":[{"text":"에러 결과","type":"text"}]}],"name":"aResult"}],"kind":"parameters"}],"sections":[],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpvideoadschedulemanagerdelegate\/schedulemanager(_:didfailwith:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gfpsdk\/gfpvideoadschedulemanagerdelegate\/schedulemanager(_:didfailwith:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManagerDelegate\/scheduleManager(_:didFailWith:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManagerDelegate"]]},"metadata":{"externalID":"c:objc(pl)GFPVideoAdScheduleManagerDelegate(im)scheduleManager:didFailWithResult:","required":true,"navigatorTitle":[{"kind":"identifier","text":"scheduleManager:didFailWithResult:"}],"title":"scheduleManager(_:didFailWith:)","role":"symbol","symbolKind":"method","roleHeading":"Instance Method","modules":[{"name":"GFPSDK"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"scheduleManager"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPVideoAdScheduleManager","text":"GFPVideoAdScheduleManager","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"didFailWith","kind":"externalParam"},{"kind":"text","text":": "},{"text":"GFPVideoAdBreakResult","preciseIdentifier":"c:objc(cs)GFPVideoAdBreakResult","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdScheduleManagerDelegate":{"type":"topic","kind":"symbol","url":"\/documentation\/gfpsdk\/gfpvideoadschedulemanagerdelegate","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManagerDelegate","title":"GFPVideoAdScheduleManagerDelegate","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"GFPVideoAdScheduleManagerDelegate"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPVideoAdScheduleManagerDelegate"}],"role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdScheduleManager":{"kind":"symbol","type":"topic","url":"\/documentation\/gfpsdk\/gfpvideoadschedulemanager","title":"GFPVideoAdScheduleManager","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager","navigatorTitle":[{"kind":"identifier","text":"GFPVideoAdScheduleManager"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPVideoAdScheduleManager"}],"abstract":[],"role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdBreakResult":{"abstract":[],"kind":"symbol","title":"GFPVideoAdBreakResult","navigatorTitle":[{"text":"GFPVideoAdBreakResult","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdBreakResult","url":"\/documentation\/gfpsdk\/gfpvideoadbreakresult","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"GFPVideoAdBreakResult","kind":"identifier"}],"role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdScheduleManagerDelegate/scheduleManager(_:didFailWith:)":{"navigatorTitle":[{"kind":"identifier","text":"scheduleManager:didFailWithResult:"}],"url":"\/documentation\/gfpsdk\/gfpvideoadschedulemanagerdelegate\/schedulemanager(_:didfailwith:)","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManagerDelegate\/scheduleManager(_:didFailWith:)","kind":"symbol","title":"scheduleManager(_:didFailWith:)","required":true,"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"scheduleManager","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPVideoAdScheduleManager","kind":"typeIdentifier","text":"GFPVideoAdScheduleManager"},{"kind":"text","text":", "},{"text":"didFailWith","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPVideoAdBreakResult","kind":"typeIdentifier","text":"GFPVideoAdBreakResult"},{"text":")","kind":"text"}],"abstract":[{"text":"광고 로드, 재생에 실패한 경우 호출됩니다.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"(컨텐츠 영상을 재생해 주세요.)"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"scheduleManager:didFailWithResult:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"scheduleManager:didFailWithResult:","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"scheduleManager:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"GFPVideoAdScheduleManager","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoAdScheduleManager","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager"},{"text":" *) ","kind":"text"},{"text":"aScheduleAdManager","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"didFailWithResult:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)GFPVideoAdBreakResult","kind":"typeIdentifier","text":"GFPVideoAdBreakResult","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdBreakResult"},{"text":" *) ","kind":"text"},{"text":"aResult","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}},{"value":{"kind":"parameters","parameters":[{"name":"aScheduleAdManager","content":[{"inlineContent":[{"type":"text","text":"스케쥴 매니저"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"에러 결과"}]}],"name":"aResult"}]},"path":"\/primaryContentSections\/1","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManagerDelegate\/title","value":"GFPVideoAdScheduleManagerDelegate"},{"op":"replace","value":[{"kind":"identifier","text":"GFPVideoAdScheduleManagerDelegate"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManagerDelegate\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManagerDelegate\/navigatorTitle","value":[{"text":"GFPVideoAdScheduleManagerDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager\/title","value":"GFPVideoAdScheduleManager","op":"replace"},{"value":[{"text":"GFPVideoAdScheduleManager","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager\/navigatorTitle","op":"replace","value":[{"text":"GFPVideoAdScheduleManager","kind":"identifier"}]},{"value":"GFPVideoAdBreakResult","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdBreakResult\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdBreakResult\/fragments","op":"replace","value":[{"text":"GFPVideoAdBreakResult","kind":"identifier"}]},{"value":[{"text":"GFPVideoAdBreakResult","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdBreakResult\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManagerDelegate~1scheduleManager(_:didFailWith:)\/title","value":"scheduleManager:didFailWithResult:","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManagerDelegate~1scheduleManager(_:didFailWith:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"scheduleManager:didFailWithResult:"}],"op":"replace"}]}]}