{"abstract":[{"type":"text","text":"광고 스케쥴 재생 종료시 호출됩니다."}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManagerDelegate"]]},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManagerDelegate\/scheduleManager(_:didCompleteAd:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"scheduleManager"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"aScheduleAdManager"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)GFPVideoAdScheduleManager","text":"GFPVideoAdScheduleManager","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didCompleteAd"},{"kind":"text","text":" "},{"kind":"internalParam","text":"aResult"},{"text":": ","kind":"text"},{"text":"GFPVideoAdBreakResult","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdBreakResult","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoAdBreakResult"},{"kind":"text","text":")"}]}]},{"parameters":[{"content":[{"inlineContent":[{"text":"스케쥴 매니저","type":"text"}],"type":"paragraph"}],"name":"aScheduleAdManager"}],"kind":"parameters"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpvideoadschedulemanagerdelegate\/schedulemanager(_:didcompletead:)"]},{"paths":["\/documentation\/gfpsdk\/gfpvideoadschedulemanagerdelegate\/schedulemanager(_:didcompletead:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:objc(pl)GFPVideoAdScheduleManagerDelegate(im)scheduleManager:didCompleteAd:","required":true,"navigatorTitle":[{"text":"scheduleManager:didCompleteAd:","kind":"identifier"}],"title":"scheduleManager(_:didCompleteAd:)","role":"symbol","symbolKind":"method","roleHeading":"Instance Method","modules":[{"name":"GFPSDK"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"scheduleManager","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoAdScheduleManager","text":"GFPVideoAdScheduleManager"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didCompleteAd"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GFPVideoAdBreakResult","preciseIdentifier":"c:objc(cs)GFPVideoAdBreakResult"},{"kind":"text","text":")"}]},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdBreakResult":{"abstract":[],"kind":"symbol","title":"GFPVideoAdBreakResult","navigatorTitle":[{"text":"GFPVideoAdBreakResult","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdBreakResult","url":"\/documentation\/gfpsdk\/gfpvideoadbreakresult","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"GFPVideoAdBreakResult","kind":"identifier"}],"role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdScheduleManagerDelegate/scheduleManager(_:didCompleteAd:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"scheduleManager","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPVideoAdScheduleManager","text":"GFPVideoAdScheduleManager","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didCompleteAd"},{"text":": ","kind":"text"},{"text":"GFPVideoAdBreakResult","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoAdBreakResult"},{"kind":"text","text":")"}],"title":"scheduleManager(_:didCompleteAd:)","navigatorTitle":[{"kind":"identifier","text":"scheduleManager:didCompleteAd:"}],"url":"\/documentation\/gfpsdk\/gfpvideoadschedulemanagerdelegate\/schedulemanager(_:didcompletead:)","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManagerDelegate\/scheduleManager(_:didCompleteAd:)","role":"symbol","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"광고 스케쥴 재생 종료시 호출됩니다."}],"required":true},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdScheduleManagerDelegate":{"type":"topic","kind":"symbol","url":"\/documentation\/gfpsdk\/gfpvideoadschedulemanagerdelegate","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManagerDelegate","title":"GFPVideoAdScheduleManagerDelegate","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"GFPVideoAdScheduleManagerDelegate"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPVideoAdScheduleManagerDelegate"}],"role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdScheduleManager":{"kind":"symbol","type":"topic","url":"\/documentation\/gfpsdk\/gfpvideoadschedulemanager","title":"GFPVideoAdScheduleManager","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager","navigatorTitle":[{"kind":"identifier","text":"GFPVideoAdScheduleManager"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPVideoAdScheduleManager"}],"abstract":[],"role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"scheduleManager:didCompleteAd:","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"scheduleManager:didCompleteAd:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"text":"scheduleManager:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPVideoAdScheduleManager","text":"GFPVideoAdScheduleManager","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager"},{"kind":"text","text":" *) "},{"text":"aScheduleAdManager","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didCompleteAd:"},{"text":"(","kind":"text"},{"text":"GFPVideoAdBreakResult","preciseIdentifier":"c:objc(cs)GFPVideoAdBreakResult","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdBreakResult","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"aResult"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"스케쥴 매니저"}],"type":"paragraph"}],"name":"aScheduleAdManager"}]},"path":"\/primaryContentSections\/1"},{"op":"replace","value":"GFPVideoAdBreakResult","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdBreakResult\/title"},{"value":[{"text":"GFPVideoAdBreakResult","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdBreakResult\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdBreakResult\/navigatorTitle","value":[{"text":"GFPVideoAdBreakResult","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManagerDelegate~1scheduleManager(_:didCompleteAd:)\/title","value":"scheduleManager:didCompleteAd:"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManagerDelegate~1scheduleManager(_:didCompleteAd:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"scheduleManager:didCompleteAd:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManagerDelegate\/title","value":"GFPVideoAdScheduleManagerDelegate"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManagerDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"GFPVideoAdScheduleManagerDelegate"}]},{"value":[{"text":"GFPVideoAdScheduleManagerDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManagerDelegate\/navigatorTitle","op":"replace"},{"value":"GFPVideoAdScheduleManager","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager\/title"},{"value":[{"kind":"identifier","text":"GFPVideoAdScheduleManager"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"GFPVideoAdScheduleManager"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}