{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"optional","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"scheduleManager"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"aScheduleAdManager","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPVideoAdScheduleManager","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager","kind":"typeIdentifier","text":"GFPVideoAdScheduleManager"},{"text":", ","kind":"text"},{"text":"didStartAd","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"aResult"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)GFPVideoAdBreakResult","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdBreakResult","kind":"typeIdentifier","text":"GFPVideoAdBreakResult"},{"kind":"text","text":")"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"aScheduleAdManager","content":[{"inlineContent":[{"type":"text","text":"스케쥴 매니저"}],"type":"paragraph"}]},{"name":"aResult","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"재생 광고 정보"}]}]}]}],"abstract":[{"text":"광고 재생 시작시 호출됩니다.","type":"text"}],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpvideoadschedulemanagerdelegate\/schedulemanager(_:didstartad:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gfpsdk\/gfpvideoadschedulemanagerdelegate\/schedulemanager(_:didstartad:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"method","required":true,"modules":[{"name":"GFPSDK"}],"roleHeading":"Instance Method","title":"scheduleManager(_:didStartAd:)","externalID":"c:objc(pl)GFPVideoAdScheduleManagerDelegate(im)scheduleManager:didStartAd:","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"scheduleManager"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoAdScheduleManager","text":"GFPVideoAdScheduleManager"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didStartAd"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPVideoAdBreakResult","text":"GFPVideoAdBreakResult","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"scheduleManager:didStartAd:","kind":"identifier"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManagerDelegate\/scheduleManager(_:didStartAd:)"},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManagerDelegate"]]},"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdScheduleManager":{"kind":"symbol","type":"topic","url":"\/documentation\/gfpsdk\/gfpvideoadschedulemanager","title":"GFPVideoAdScheduleManager","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager","navigatorTitle":[{"kind":"identifier","text":"GFPVideoAdScheduleManager"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPVideoAdScheduleManager"}],"abstract":[],"role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdBreakResult":{"abstract":[],"kind":"symbol","title":"GFPVideoAdBreakResult","navigatorTitle":[{"text":"GFPVideoAdBreakResult","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdBreakResult","url":"\/documentation\/gfpsdk\/gfpvideoadbreakresult","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"GFPVideoAdBreakResult","kind":"identifier"}],"role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdScheduleManagerDelegate/scheduleManager(_:didStartAd:)":{"required":true,"kind":"symbol","title":"scheduleManager(_:didStartAd:)","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManagerDelegate\/scheduleManager(_:didStartAd:)","url":"\/documentation\/gfpsdk\/gfpvideoadschedulemanagerdelegate\/schedulemanager(_:didstartad:)","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"scheduleManager"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPVideoAdScheduleManager","text":"GFPVideoAdScheduleManager","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didStartAd","kind":"externalParam"},{"kind":"text","text":": "},{"text":"GFPVideoAdBreakResult","preciseIdentifier":"c:objc(cs)GFPVideoAdBreakResult","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"scheduleManager:didStartAd:","kind":"identifier"}],"abstract":[{"text":"광고 재생 시작시 호출됩니다.","type":"text"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdScheduleManagerDelegate":{"type":"topic","kind":"symbol","url":"\/documentation\/gfpsdk\/gfpvideoadschedulemanagerdelegate","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManagerDelegate","title":"GFPVideoAdScheduleManagerDelegate","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"GFPVideoAdScheduleManagerDelegate"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPVideoAdScheduleManagerDelegate"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"scheduleManager:didStartAd:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"scheduleManager:didStartAd:","kind":"identifier"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"scheduleManager:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPVideoAdScheduleManager","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager","kind":"typeIdentifier","text":"GFPVideoAdScheduleManager"},{"text":" *) ","kind":"text"},{"text":"aScheduleAdManager","kind":"internalParam"},{"kind":"text","text":" "},{"text":"didStartAd:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPVideoAdBreakResult","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdBreakResult","kind":"typeIdentifier","text":"GFPVideoAdBreakResult"},{"kind":"text","text":" *) "},{"text":"aResult","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"스케쥴 매니저"}],"type":"paragraph"}],"name":"aScheduleAdManager"},{"name":"aResult","content":[{"type":"paragraph","inlineContent":[{"text":"재생 광고 정보","type":"text"}]}]}]},"op":"replace"},{"value":"GFPVideoAdScheduleManager","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager\/fragments","value":[{"text":"GFPVideoAdScheduleManager","kind":"identifier"}]},{"op":"replace","value":[{"text":"GFPVideoAdScheduleManager","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdBreakResult\/title","value":"GFPVideoAdBreakResult","op":"replace"},{"value":[{"kind":"identifier","text":"GFPVideoAdBreakResult"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdBreakResult\/fragments"},{"value":[{"text":"GFPVideoAdBreakResult","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdBreakResult\/navigatorTitle"},{"value":"scheduleManager:didStartAd:","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManagerDelegate~1scheduleManager(_:didStartAd:)\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManagerDelegate~1scheduleManager(_:didStartAd:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"scheduleManager:didStartAd:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManagerDelegate\/title","value":"GFPVideoAdScheduleManagerDelegate"},{"value":[{"text":"GFPVideoAdScheduleManagerDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManagerDelegate\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManagerDelegate\/navigatorTitle","op":"replace","value":[{"text":"GFPVideoAdScheduleManagerDelegate","kind":"identifier"}]}]}]}