{"variants":[{"paths":["\/documentation\/gfpsdk\/gfpresourcecode\/adchoices"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpresourcecode\/adchoices"]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPResourceCode"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPResourceCode\/adChoices"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"kind":"symbol","metadata":{"modules":[{"name":"GFPSDK"}],"roleHeading":"Type Property","symbolKind":"property","role":"symbol","title":"adChoices","externalID":"c:@E@GFPResourceCode@GFPResourceAdChoices","navigatorTitle":[{"kind":"identifier","text":"GFPResourceAdChoices"}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"adChoices"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPResourceCode","text":"GFPResourceCode"}]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"adChoices"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPResourceCode","text":"GFPResourceCode","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPResourceCode"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPResourceCode/adChoices":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"adChoices"},{"kind":"text","text":": "},{"text":"GFPResourceCode","kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPResourceCode"}],"navigatorTitle":[{"kind":"identifier","text":"GFPResourceAdChoices"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPResourceCode\/adChoices","url":"\/documentation\/gfpsdk\/gfpresourcecode\/adchoices","kind":"symbol","role":"symbol","abstract":[],"title":"adChoices","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPResourceCode":{"title":"GFPResourceCode","type":"topic","abstract":[],"url":"\/documentation\/gfpsdk\/gfpresourcecode","kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPResourceCode","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPResourceCode","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"GFPResourceCode","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"GFPResourceAdChoices"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"GFPResourceAdChoices","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"GFPResourceAdChoices","kind":"identifier"}]}]}},{"value":"GFPResourceAdChoices","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPResourceCode~1adChoices\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPResourceCode~1adChoices\/fragments","value":[{"kind":"identifier","text":"GFPResourceAdChoices"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPResourceCode\/title","value":"GFPResourceCode","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPResourceCode\/fragments","value":[{"kind":"identifier","text":"GFPResourceCode"}]},{"value":[{"text":"GFPResourceCode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPResourceCode\/navigatorTitle"}]}]}