{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpresourcecode\/adprovidernotice"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpresourcecode\/adprovidernotice"]}],"metadata":{"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"adProviderNotice","kind":"identifier"},{"kind":"text","text":": "},{"text":"GFPResourceCode","kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPResourceCode"}],"role":"symbol","externalID":"c:@E@GFPResourceCode@GFPResourceAdProviderNotice","symbolKind":"property","roleHeading":"Type Property","title":"adProviderNotice","modules":[{"name":"GFPSDK"}],"navigatorTitle":[{"text":"GFPResourceAdProviderNotice","kind":"identifier"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"adProviderNotice"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPResourceCode","preciseIdentifier":"c:@E@GFPResourceCode","text":"GFPResourceCode","kind":"typeIdentifier"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPResourceCode"]]},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPResourceCode\/adProviderNotice","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPResourceCode/adProviderNotice":{"url":"\/documentation\/gfpsdk\/gfpresourcecode\/adprovidernotice","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"adProviderNotice","kind":"identifier"},{"text":": ","kind":"text"},{"text":"GFPResourceCode","kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPResourceCode"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPResourceCode\/adProviderNotice","title":"adProviderNotice","navigatorTitle":[{"kind":"identifier","text":"GFPResourceAdProviderNotice"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPResourceCode":{"title":"GFPResourceCode","type":"topic","abstract":[],"url":"\/documentation\/gfpsdk\/gfpresourcecode","kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPResourceCode","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPResourceCode","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"GFPResourceCode","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"value":"GFPResourceAdProviderNotice","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GFPResourceAdProviderNotice"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"GFPResourceAdProviderNotice","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPResourceCode~1adProviderNotice\/title","value":"GFPResourceAdProviderNotice","op":"replace"},{"value":[{"kind":"identifier","text":"GFPResourceAdProviderNotice"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPResourceCode~1adProviderNotice\/fragments"},{"op":"replace","value":"GFPResourceCode","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPResourceCode\/title"},{"op":"replace","value":[{"text":"GFPResourceCode","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPResourceCode\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPResourceCode\/navigatorTitle","value":[{"text":"GFPResourceCode","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}