{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"providerNotice"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@GFPResourceCode","text":"GFPResourceCode","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPResourceCode"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPResourceCode\/providerNotice"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPResourceCode"]]},"variants":[{"paths":["\/documentation\/gfpsdk\/gfpresourcecode\/providernotice"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpresourcecode\/providernotice"]}],"metadata":{"role":"symbol","modules":[{"name":"GFPSDK"}],"externalID":"c:@E@GFPResourceCode@GFPResourceProviderNotice","symbolKind":"property","title":"providerNotice","navigatorTitle":[{"kind":"identifier","text":"GFPResourceProviderNotice"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"providerNotice","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@GFPResourceCode","kind":"typeIdentifier","text":"GFPResourceCode"}],"roleHeading":"Type Property"},"sections":[],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPResourceCode/providerNotice":{"url":"\/documentation\/gfpsdk\/gfpresourcecode\/providernotice","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"providerNotice"},{"text":": ","kind":"text"},{"text":"GFPResourceCode","kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPResourceCode"}],"title":"providerNotice","kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPResourceCode\/providerNotice","type":"topic","navigatorTitle":[{"text":"GFPResourceProviderNotice","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPResourceCode":{"title":"GFPResourceCode","type":"topic","abstract":[],"url":"\/documentation\/gfpsdk\/gfpresourcecode","kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPResourceCode","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPResourceCode","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"GFPResourceCode","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"GFPResourceProviderNotice","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"value":[{"text":"GFPResourceProviderNotice","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"GFPResourceProviderNotice"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPResourceCode~1providerNotice\/title","value":"GFPResourceProviderNotice","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPResourceCode~1providerNotice\/fragments","value":[{"kind":"identifier","text":"GFPResourceProviderNotice"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPResourceCode\/title","value":"GFPResourceCode"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPResourceCode\/fragments","value":[{"kind":"identifier","text":"GFPResourceCode"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPResourceCode\/navigatorTitle","value":[{"kind":"identifier","text":"GFPResourceCode"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}