{"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdProviderOption"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpinterstitialadprovideroption\/chartboost"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpinterstitialadprovideroption\/chartboost"]}],"sections":[],"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdProviderOption\/chartBoost","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"GFPInterstitialAdProviderOptionChartBoost"}],"symbolKind":"case","title":"GFPInterstitialAdProviderOption.chartBoost","role":"symbol","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"chartBoost"}],"externalID":"c:@M@GFPSDK@E@GFPInterstitialAdProviderOption@GFPInterstitialAdProviderOptionChartBoost","modules":[{"name":"GFPSDK"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"chartBoost"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPInterstitialAdProviderOption":{"navigatorTitle":[{"text":"GFPInterstitialAdProviderOption","kind":"identifier"}],"abstract":[{"type":"text","text":"GFP에서 지원하는 Interstitial 광고 제공자 목록"}],"title":"GFPInterstitialAdProviderOption","url":"\/documentation\/gfpsdk\/gfpinterstitialadprovideroption","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdProviderOption","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPInterstitialAdProviderOption"}],"type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPInterstitialAdProviderOption/chartBoost":{"type":"topic","url":"\/documentation\/gfpsdk\/gfpinterstitialadprovideroption\/chartboost","abstract":[],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"chartBoost","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"GFPInterstitialAdProviderOptionChartBoost","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdProviderOption\/chartBoost","title":"GFPInterstitialAdProviderOption.chartBoost"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"GFPInterstitialAdProviderOptionChartBoost","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"GFPInterstitialAdProviderOptionChartBoost","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"GFPInterstitialAdProviderOptionChartBoost","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"value":"GFPInterstitialAdProviderOption","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdProviderOption\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdProviderOption\/fragments","value":[{"text":"GFPInterstitialAdProviderOption","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"GFPInterstitialAdProviderOption"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdProviderOption\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdProviderOption~1chartBoost\/title","value":"GFPInterstitialAdProviderOptionChartBoost","op":"replace"},{"value":[{"kind":"identifier","text":"GFPInterstitialAdProviderOptionChartBoost"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdProviderOption~1chartBoost\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}