{"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdProviderOption"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","sections":[],"metadata":{"navigatorTitle":[{"text":"GFPInterstitialAdProviderOptionDFP","kind":"identifier"}],"externalID":"c:@M@GFPSDK@E@GFPInterstitialAdProviderOption@GFPInterstitialAdProviderOptionDFP","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"DFP","kind":"identifier"}],"role":"symbol","modules":[{"name":"GFPSDK"}],"roleHeading":"Case","title":"GFPInterstitialAdProviderOption.DFP"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"DFP","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpinterstitialadprovideroption\/dfp"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gfpsdk\/gfpinterstitialadprovideroption\/dfp"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdProviderOption\/DFP"},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPInterstitialAdProviderOption/DFP":{"type":"topic","url":"\/documentation\/gfpsdk\/gfpinterstitialadprovideroption\/dfp","abstract":[],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"DFP","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"GFPInterstitialAdProviderOptionDFP","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdProviderOption\/DFP","title":"GFPInterstitialAdProviderOption.DFP"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPInterstitialAdProviderOption":{"navigatorTitle":[{"text":"GFPInterstitialAdProviderOption","kind":"identifier"}],"abstract":[{"type":"text","text":"GFP에서 지원하는 Interstitial 광고 제공자 목록"}],"title":"GFPInterstitialAdProviderOption","url":"\/documentation\/gfpsdk\/gfpinterstitialadprovideroption","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdProviderOption","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPInterstitialAdProviderOption"}],"type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"GFPInterstitialAdProviderOptionDFP","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"GFPInterstitialAdProviderOptionDFP","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"GFPInterstitialAdProviderOptionDFP","kind":"identifier"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"GFPInterstitialAdProviderOptionDFP","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdProviderOption~1DFP\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdProviderOption~1DFP\/fragments","value":[{"kind":"identifier","text":"GFPInterstitialAdProviderOptionDFP"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdProviderOption\/title","value":"GFPInterstitialAdProviderOption","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdProviderOption\/fragments","value":[{"kind":"identifier","text":"GFPInterstitialAdProviderOption"}],"op":"replace"},{"value":[{"kind":"identifier","text":"GFPInterstitialAdProviderOption"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdProviderOption\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}