{"kind":"article","hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdProviderOption"]]},"topicSections":[{"generated":true,"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdProviderOption\/!=(_:_:)"],"anchor":"Operators","title":"Operators"}],"metadata":{"modules":[{"name":"GFPSDK"}],"roleHeading":"API Collection","title":"Equatable Implementations","role":"collectionGroup"},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdProviderOption\/Equatable-Implementations","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpinterstitialadprovideroption\/equatable-implementations"]}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPInterstitialAdProviderOption/!=(_:_:)":{"type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/gfpsdk\/gfpinterstitialadprovideroption\/!=(_:_:)","title":"!=(_:_:)","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdProviderOption\/!=(_:_:)","kind":"symbol","role":"symbol","abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPInterstitialAdProviderOption":{"navigatorTitle":[{"text":"GFPInterstitialAdProviderOption","kind":"identifier"}],"abstract":[{"type":"text","text":"GFP에서 지원하는 Interstitial 광고 제공자 목록"}],"title":"GFPInterstitialAdProviderOption","url":"\/documentation\/gfpsdk\/gfpinterstitialadprovideroption","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdProviderOption","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPInterstitialAdProviderOption"}],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"GFPInterstitialAdProviderOption","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdProviderOption\/title"},{"value":[{"kind":"identifier","text":"GFPInterstitialAdProviderOption"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdProviderOption\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdProviderOption\/navigatorTitle","value":[{"kind":"identifier","text":"GFPInterstitialAdProviderOption"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}