{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpinterstitialadprovideroption\/is"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpinterstitialadprovideroption\/is"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdProviderOption\/IS"},"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"navigatorTitle":[{"text":"GFPInterstitialAdProviderOptionIS","kind":"identifier"}],"title":"GFPInterstitialAdProviderOption.IS","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"IS","kind":"identifier"}],"modules":[{"name":"GFPSDK"}],"externalID":"c:@M@GFPSDK@E@GFPInterstitialAdProviderOption@GFPInterstitialAdProviderOptionIS","role":"symbol","roleHeading":"Case","symbolKind":"case"},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"IS"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdProviderOption"]]},"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPInterstitialAdProviderOption":{"navigatorTitle":[{"text":"GFPInterstitialAdProviderOption","kind":"identifier"}],"abstract":[{"type":"text","text":"GFP에서 지원하는 Interstitial 광고 제공자 목록"}],"title":"GFPInterstitialAdProviderOption","url":"\/documentation\/gfpsdk\/gfpinterstitialadprovideroption","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdProviderOption","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPInterstitialAdProviderOption"}],"type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPInterstitialAdProviderOption/IS":{"abstract":[],"url":"\/documentation\/gfpsdk\/gfpinterstitialadprovideroption\/is","title":"GFPInterstitialAdProviderOption.IS","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"IS","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPInterstitialAdProviderOptionIS"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdProviderOption\/IS"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"GFPInterstitialAdProviderOptionIS"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"kind":"identifier","text":"GFPInterstitialAdProviderOptionIS"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"GFPInterstitialAdProviderOptionIS","kind":"identifier"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdProviderOption\/title","value":"GFPInterstitialAdProviderOption","op":"replace"},{"value":[{"kind":"identifier","text":"GFPInterstitialAdProviderOption"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdProviderOption\/fragments","op":"replace"},{"op":"replace","value":[{"text":"GFPInterstitialAdProviderOption","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdProviderOption\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdProviderOption~1IS\/title","value":"GFPInterstitialAdProviderOptionIS"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdProviderOption~1IS\/fragments","value":[{"text":"GFPInterstitialAdProviderOptionIS","kind":"identifier"}]}]}]}