{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpvideodisplaymode\/normal()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpvideodisplaymode\/normal()"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoDisplayMode"]]},"metadata":{"modules":[{"name":"GFPSDK"}],"role":"symbol","roleHeading":"Type Method","title":"normal()","externalID":"c:@M@GFPSDK@objc(cs)GFPVideoDisplayMode(cm)normal","symbolKind":"method","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"normal","kind":"identifier"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPVideoDisplayMode","text":"GFPVideoDisplayMode","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"normal"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"normal","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"GFPVideoDisplayMode","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoDisplayMode","kind":"typeIdentifier","preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPVideoDisplayMode"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoDisplayMode\/normal()","interfaceLanguage":"swift"},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoDisplayMode/normal()":{"abstract":[],"url":"\/documentation\/gfpsdk\/gfpvideodisplaymode\/normal()","role":"symbol","title":"normal()","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoDisplayMode\/normal()","type":"topic","navigatorTitle":[{"text":"normal","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"normal","kind":"identifier"},{"kind":"text","text":"() -> "},{"text":"GFPVideoDisplayMode","kind":"typeIdentifier","preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPVideoDisplayMode"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoDisplayMode":{"navigatorTitle":[{"text":"GFPVideoDisplayMode","kind":"identifier"}],"type":"topic","title":"GFPVideoDisplayMode","kind":"symbol","url":"\/documentation\/gfpsdk\/gfpvideodisplaymode","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoDisplayMode","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPVideoDisplayMode","kind":"identifier"}],"role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"value":"normal","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"normal"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"text":"GFPVideoDisplayMode","preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPVideoDisplayMode","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoDisplayMode","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"normal"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoDisplayMode~1normal()\/title","op":"replace","value":"normal"},{"value":[{"kind":"text","text":"+ "},{"text":"normal","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoDisplayMode~1normal()\/fragments","op":"replace"},{"value":"GFPVideoDisplayMode","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoDisplayMode\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoDisplayMode\/fragments","value":[{"kind":"identifier","text":"GFPVideoDisplayMode"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoDisplayMode\/navigatorTitle","value":[{"kind":"identifier","text":"GFPVideoDisplayMode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}