{"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"avPlayerItem","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"playerItem"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVPlayerItem","text":"AVPlayerItem"},{"kind":"text","text":", "},{"text":"rate","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"playRate","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"metadata":{"title":"init(avPlayerItem:rate:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"avPlayerItem"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)AVPlayerItem","kind":"typeIdentifier","text":"AVPlayerItem"},{"text":", ","kind":"text"},{"text":"rate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"kind":"text","text":")"}],"roleHeading":"Initializer","role":"symbol","externalID":"c:objc(cs)GFPVideoAdQoePlayerInfo(im)initWithAVPlayerItem:rate:","symbolKind":"init","navigatorTitle":[{"kind":"identifier","text":"initWithAVPlayerItem:rate:"}],"modules":[{"name":"GFPSDK"}]},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdQoePlayerInfo\/init(avPlayerItem:rate:)-44j29","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpvideoadqoeplayerinfo\/init(avplayeritem:rate:)-44j29"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpvideoadqoeplayerinfo\/init(avplayeritem:rate:)-44j29"]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdQoePlayerInfo"]]},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdQoePlayerInfo":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"GFPVideoAdQoePlayerInfo","kind":"identifier"}],"title":"GFPVideoAdQoePlayerInfo","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdQoePlayerInfo","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPVideoAdQoePlayerInfo"}],"url":"\/documentation\/gfpsdk\/gfpvideoadqoeplayerinfo","kind":"symbol","abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdQoePlayerInfo/init(avPlayerItem:rate:)-44j29":{"abstract":[],"title":"init(avPlayerItem:rate:)","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"avPlayerItem"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVPlayerItem","text":"AVPlayerItem"},{"text":", ","kind":"text"},{"text":"rate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"kind":"text","text":")"}],"url":"\/documentation\/gfpsdk\/gfpvideoadqoeplayerinfo\/init(avplayeritem:rate:)-44j29","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdQoePlayerInfo\/init(avPlayerItem:rate:)-44j29","navigatorTitle":[{"kind":"identifier","text":"initWithAVPlayerItem:rate:"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"initWithAVPlayerItem:rate:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithAVPlayerItem:rate:"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithAVPlayerItem:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)AVPlayerItem","text":"AVPlayerItem","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"playerItem"},{"text":" ","kind":"text"},{"text":"rate:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:f","text":"float"},{"kind":"text","text":") "},{"kind":"internalParam","text":"playRate"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"GFPVideoAdQoePlayerInfo","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdQoePlayerInfo\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdQoePlayerInfo\/fragments","value":[{"kind":"identifier","text":"GFPVideoAdQoePlayerInfo"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdQoePlayerInfo\/navigatorTitle","op":"replace","value":[{"text":"GFPVideoAdQoePlayerInfo","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdQoePlayerInfo~1init(avPlayerItem:rate:)-44j29\/title","value":"initWithAVPlayerItem:rate:"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdQoePlayerInfo~1init(avPlayerItem:rate:)-44j29\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithAVPlayerItem:rate:","kind":"identifier"}],"op":"replace"}]}]}