{"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdQoePlayerInfo\/init(AVPlayerItem:rate:)-7cf3a","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdQoePlayerInfo"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpvideoadqoeplayerinfo\/init(avplayeritem:rate:)-7cf3a"]}],"metadata":{"externalID":"c:objc(cs)GFPVideoAdQoePlayerInfo(im)initWithAVPlayerItem:rate:::SYNTHESIZED::c:objc(cs)GFPVideoAdQoePlayerInfo","modules":[{"name":"GFPSDK"}],"symbolKind":"init","title":"init(AVPlayerItem:rate:)","platforms":[],"role":"symbol","roleHeading":"Initializer","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"AVPlayerItem","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVPlayerItem","text":"AVPlayerItem"},{"text":", ","kind":"text"},{"text":"rate","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"kind":"text","text":")"}]},"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"text":"Inherited from ","type":"text"},{"code":"GFPVideoAdQoePlayerInfo.init(AVPlayerItem:rate:)","type":"codeVoice"},{"type":"text","text":"."}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"AVPlayerItem","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"playerItem","kind":"internalParam"},{"kind":"text","text":": "},{"text":"AVPlayerItem","preciseIdentifier":"c:objc(cs)AVPlayerItem","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"rate"},{"kind":"text","text":" "},{"kind":"internalParam","text":"playRate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdQoePlayerInfo":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"GFPVideoAdQoePlayerInfo","kind":"identifier"}],"title":"GFPVideoAdQoePlayerInfo","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdQoePlayerInfo","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPVideoAdQoePlayerInfo"}],"url":"\/documentation\/gfpsdk\/gfpvideoadqoeplayerinfo","kind":"symbol","abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdQoePlayerInfo/init(AVPlayerItem:rate:)-7cf3a":{"abstract":[],"type":"topic","kind":"symbol","url":"\/documentation\/gfpsdk\/gfpvideoadqoeplayerinfo\/init(avplayeritem:rate:)-7cf3a","role":"symbol","title":"init(AVPlayerItem:rate:)","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdQoePlayerInfo\/init(AVPlayerItem:rate:)-7cf3a","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"AVPlayerItem","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVPlayerItem","text":"AVPlayerItem"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"rate"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"},{"text":")","kind":"text"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdQoePlayerInfo\/title","value":"GFPVideoAdQoePlayerInfo","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdQoePlayerInfo\/fragments","value":[{"text":"GFPVideoAdQoePlayerInfo","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdQoePlayerInfo\/navigatorTitle","value":[{"kind":"identifier","text":"GFPVideoAdQoePlayerInfo"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}