{"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdQoePlayerInfo"]]},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdQoePlayerInfo\/updateBufferedTime(with:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpvideoadqoeplayerinfo\/updatebufferedtime(with:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpvideoadqoeplayerinfo\/updatebufferedtime(with:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"updateBufferedTime"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"aValue","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"NSValue","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSValue"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"externalID":"c:objc(cs)GFPVideoAdQoePlayerInfo(im)updateBufferedTimeWith:","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"updateBufferedTime","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSValue","text":"NSValue"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"updateBufferedTimeWith:"}],"modules":[{"name":"GFPSDK"}],"symbolKind":"method","role":"symbol","roleHeading":"Instance Method","title":"updateBufferedTime(with:)"},"sections":[],"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdQoePlayerInfo/updateBufferedTime(with:)":{"url":"\/documentation\/gfpsdk\/gfpvideoadqoeplayerinfo\/updatebufferedtime(with:)","kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdQoePlayerInfo\/updateBufferedTime(with:)","abstract":[],"title":"updateBufferedTime(with:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"updateBufferedTime"},{"kind":"text","text":"("},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSValue","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSValue"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"updateBufferedTimeWith:","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdQoePlayerInfo":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"GFPVideoAdQoePlayerInfo","kind":"identifier"}],"title":"GFPVideoAdQoePlayerInfo","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdQoePlayerInfo","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPVideoAdQoePlayerInfo"}],"url":"\/documentation\/gfpsdk\/gfpvideoadqoeplayerinfo","kind":"symbol","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"updateBufferedTimeWith:","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"updateBufferedTimeWith:","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"text":"updateBufferedTimeWith:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSValue","preciseIdentifier":"c:objc(cs)NSValue","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"aValue","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdQoePlayerInfo~1updateBufferedTime(with:)\/title","value":"updateBufferedTimeWith:","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdQoePlayerInfo~1updateBufferedTime(with:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"updateBufferedTimeWith:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdQoePlayerInfo\/title","op":"replace","value":"GFPVideoAdQoePlayerInfo"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdQoePlayerInfo\/fragments","op":"replace","value":[{"text":"GFPVideoAdQoePlayerInfo","kind":"identifier"}]},{"value":[{"text":"GFPVideoAdQoePlayerInfo","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdQoePlayerInfo\/navigatorTitle","op":"replace"}]}]}