{"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearAdView"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpnonlinearadview\/attribute"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpnonlinearadview\/attribute"]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearAdView\/attribute"},"metadata":{"role":"symbol","title":"attribute","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"attribute","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPTextAdViewAttribute","kind":"typeIdentifier","text":"GFPTextAdViewAttribute"}],"externalID":"c:objc(cs)GFPNonLinearAdView(py)attribute","symbolKind":"property","navigatorTitle":[{"text":"attribute","kind":"identifier"}],"modules":[{"name":"GFPSDK"}]},"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"attribute"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPTextAdViewAttribute","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPTextAdViewAttribute","text":"GFPTextAdViewAttribute"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}]}]}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNonLinearAdView":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearAdView","title":"GFPNonLinearAdView","type":"topic","url":"\/documentation\/gfpsdk\/gfpnonlinearadview","abstract":[],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPNonLinearAdView"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPNonLinearAdView","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNonLinearAdView/attribute":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"attribute"},{"kind":"text","text":": "},{"text":"GFPTextAdViewAttribute","kind":"typeIdentifier","preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPTextAdViewAttribute"}],"kind":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearAdView\/attribute","url":"\/documentation\/gfpsdk\/gfpnonlinearadview\/attribute","title":"attribute","role":"symbol","navigatorTitle":[{"text":"attribute","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPTextAdViewAttribute":{"navigatorTitle":[{"text":"GFPTextAdViewAttribute","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfptextadviewattribute","type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPTextAdViewAttribute","title":"GFPTextAdViewAttribute","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPTextAdViewAttribute"}],"abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"attribute"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"attribute","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"kind":"text","text":") "},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPTextAdViewAttribute","text":"GFPTextAdViewAttribute","preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPTextAdViewAttribute","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"attribute","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearAdView\/title","value":"GFPNonLinearAdView"},{"op":"replace","value":[{"kind":"identifier","text":"GFPNonLinearAdView"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearAdView\/fragments"},{"value":[{"text":"GFPNonLinearAdView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearAdView\/navigatorTitle"},{"value":"attribute","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearAdView~1attribute\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearAdView~1attribute\/fragments","value":[{"kind":"identifier","text":"attribute"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPTextAdViewAttribute\/title","value":"GFPTextAdViewAttribute","op":"replace"},{"op":"replace","value":[{"text":"GFPTextAdViewAttribute","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPTextAdViewAttribute\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPTextAdViewAttribute\/navigatorTitle","value":[{"text":"GFPTextAdViewAttribute","kind":"identifier"}]}]}]}