{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"init"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/kGFPAdInterfaceStyle\/init","interfaceLanguage":"occ"},"metadata":{"roleHeading":"Instance Method","navigatorTitle":[{"text":"init","kind":"identifier"}],"fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"role":"symbol","externalID":"c:@M@GFPSDK@objc(cs)kGFPAdInterfaceStyle(im)init","modules":[{"name":"GFPSDK"}],"title":"init","symbolKind":"method"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/kGFPAdInterfaceStyle"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/gfpsdk\/kgfpadinterfacestyle\/init"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/kGFPAdInterfaceStyle":{"kind":"symbol","url":"\/documentation\/gfpsdk\/kgfpadinterfacestyle","type":"topic","role":"symbol","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kGFPAdInterfaceStyle","kind":"identifier"}],"navigatorTitle":[{"text":"kGFPAdInterfaceStyle","kind":"identifier"}],"title":"kGFPAdInterfaceStyle","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/kGFPAdInterfaceStyle"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/kGFPAdInterfaceStyle/init":{"navigatorTitle":[{"text":"init","kind":"identifier"}],"title":"init","url":"\/documentation\/gfpsdk\/kgfpadinterfacestyle\/init","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/kGFPAdInterfaceStyle\/init","role":"symbol","type":"topic","kind":"symbol","abstract":[],"fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1kGFPAdInterfaceStyle\/title","value":"kGFPAdInterfaceStyle"},{"value":[{"text":"kGFPAdInterfaceStyle","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1kGFPAdInterfaceStyle\/fragments"},{"value":[{"kind":"identifier","text":"kGFPAdInterfaceStyle"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1kGFPAdInterfaceStyle\/navigatorTitle"}]}]}