{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(initWith:) ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"deviceInfo","kind":"externalParam"},{"kind":"text","text":": "},{"text":"GFPUADeviceInfo","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUADeviceInfo","preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPUADeviceInfo","kind":"typeIdentifier"},{"kind":"text","text":")"}]}]}],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpuseragent\/init(deviceinfo:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpuseragent\/init(deviceinfo:)"]}],"metadata":{"symbolKind":"init","role":"symbol","title":"init(deviceInfo:)","modules":[{"name":"GFPSDK"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"deviceInfo"},{"kind":"text","text":": "},{"text":"GFPUADeviceInfo","preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPUADeviceInfo","kind":"typeIdentifier"},{"text":")","kind":"text"}],"externalID":"c:@M@GFPSDK@objc(cs)GFPUserAgent(im)initWith:","navigatorTitle":[{"kind":"identifier","text":"initWith:"}],"roleHeading":"Initializer"},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUserAgent\/init(deviceInfo:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUserAgent"]]},"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPUserAgent":{"abstract":[],"url":"\/documentation\/gfpsdk\/gfpuseragent","title":"GFPUserAgent","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPUserAgent"}],"role":"symbol","navigatorTitle":[{"text":"GFPUserAgent","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUserAgent"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPUserAgent/init(deviceInfo:)":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUserAgent\/init(deviceInfo:)","abstract":[],"kind":"symbol","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"deviceInfo","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPUADeviceInfo","text":"GFPUADeviceInfo"},{"kind":"text","text":")"}],"type":"topic","navigatorTitle":[{"text":"initWith:","kind":"identifier"}],"title":"init(deviceInfo:)","url":"\/documentation\/gfpsdk\/gfpuseragent\/init(deviceinfo:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPUADeviceInfo":{"type":"topic","navigatorTitle":[{"text":"GFPUADeviceInfo","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUADeviceInfo","kind":"symbol","url":"\/documentation\/gfpsdk\/gfpuadeviceinfo","abstract":[],"title":"GFPUADeviceInfo","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"GFPUADeviceInfo","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","value":"initWith:","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"text":"initWith:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWith:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPUADeviceInfo","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUADeviceInfo","kind":"typeIdentifier","text":"GFPUADeviceInfo"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"deviceInfo"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"value":"GFPUserAgent","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPUserAgent\/title","op":"replace"},{"value":[{"text":"GFPUserAgent","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPUserAgent\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPUserAgent\/navigatorTitle","value":[{"text":"GFPUserAgent","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPUserAgent~1init(deviceInfo:)\/title","value":"initWith:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPUserAgent~1init(deviceInfo:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWith:","kind":"identifier"}]},{"value":"GFPUADeviceInfo","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPUADeviceInfo\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPUADeviceInfo\/fragments","value":[{"text":"GFPUADeviceInfo","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPUADeviceInfo\/navigatorTitle","value":[{"text":"GFPUADeviceInfo","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}