{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedStatus"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedStatus\/notYet"},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"notYet"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedStatus","preciseIdentifier":"c:@E@GFPRewardedStatus","kind":"typeIdentifier","text":"GFPRewardedStatus"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfprewardedstatus\/notyet"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfprewardedstatus\/notyet"]}],"metadata":{"title":"notYet","externalID":"c:@E@GFPRewardedStatus@GFPRewardedNotYet","modules":[{"name":"GFPSDK"}],"navigatorTitle":[{"text":"GFPRewardedNotYet","kind":"identifier"}],"symbolKind":"property","role":"symbol","roleHeading":"Type Property","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"notYet"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@GFPRewardedStatus","text":"GFPRewardedStatus","kind":"typeIdentifier"}]},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRewardedStatus":{"type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPRewardedStatus"}],"kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedStatus","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPRewardedStatus"}],"url":"\/documentation\/gfpsdk\/gfprewardedstatus","title":"GFPRewardedStatus"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRewardedStatus/notYet":{"abstract":[],"url":"\/documentation\/gfpsdk\/gfprewardedstatus\/notyet","title":"notYet","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"notYet"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@GFPRewardedStatus","kind":"typeIdentifier","text":"GFPRewardedStatus"}],"role":"symbol","navigatorTitle":[{"text":"GFPRewardedNotYet","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedStatus\/notYet"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"GFPRewardedNotYet"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GFPRewardedNotYet"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"GFPRewardedNotYet","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedStatus\/title","value":"GFPRewardedStatus"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedStatus\/fragments","op":"replace","value":[{"kind":"identifier","text":"GFPRewardedStatus"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedStatus\/navigatorTitle","op":"replace","value":[{"text":"GFPRewardedStatus","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedStatus~1notYet\/title","value":"GFPRewardedNotYet","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"GFPRewardedNotYet"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedStatus~1notYet\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}