{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfprewardedstatus\/showed"]},{"paths":["\/documentation\/gfpsdk\/gfprewardedstatus\/showed"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedStatus\/showed","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"modules":[{"name":"GFPSDK"}],"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"GFPRewardedShowed"}],"title":"showed","roleHeading":"Type Property","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"showed"},{"text":": ","kind":"text"},{"text":"GFPRewardedStatus","preciseIdentifier":"c:@E@GFPRewardedStatus","kind":"typeIdentifier"}],"externalID":"c:@E@GFPRewardedStatus@GFPRewardedShowed","role":"symbol"},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"showed","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@GFPRewardedStatus","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedStatus","text":"GFPRewardedStatus"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedStatus"]]},"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRewardedStatus":{"type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPRewardedStatus"}],"kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedStatus","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPRewardedStatus"}],"url":"\/documentation\/gfpsdk\/gfprewardedstatus","title":"GFPRewardedStatus"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRewardedStatus/showed":{"abstract":[],"url":"\/documentation\/gfpsdk\/gfprewardedstatus\/showed","title":"showed","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"showed","kind":"identifier"},{"text":": ","kind":"text"},{"text":"GFPRewardedStatus","kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPRewardedStatus"}],"role":"symbol","navigatorTitle":[{"text":"GFPRewardedShowed","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedStatus\/showed"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"GFPRewardedShowed","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"GFPRewardedShowed"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"GFPRewardedShowed","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"GFPRewardedStatus","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedStatus\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedStatus\/fragments","value":[{"kind":"identifier","text":"GFPRewardedStatus"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedStatus\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"GFPRewardedStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedStatus~1showed\/title","value":"GFPRewardedShowed"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedStatus~1showed\/fragments","value":[{"text":"GFPRewardedShowed","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}