{"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"SetAlgebra.subtract(_:)"},{"type":"text","text":"."}],"metadata":{"externalID":"s:s10SetAlgebraPsE8subtractyyxF::SYNTHESIZED::c:@E@GFPRewardedStatus","title":"subtract(_:)","role":"symbol","extendedModule":"Swift","roleHeading":"Instance Method","symbolKind":"method","modules":[{"relatedModules":["Swift"],"name":"GFPSDK"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"subtract","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfprewardedstatus\/subtract(_:)"]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedStatus","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedStatus\/SetAlgebra-Implementations"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedStatus\/subtract(_:)"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"mutating","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"subtract"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"other"},{"text":": ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":")"}]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRewardedStatus/subtract(_:)":{"abstract":[],"url":"\/documentation\/gfpsdk\/gfprewardedstatus\/subtract(_:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"subtract","kind":"identifier"},{"kind":"text","text":"("},{"text":"Self","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"subtract(_:)","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedStatus\/subtract(_:)","role":"symbol","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRewardedStatus/SetAlgebra-Implementations":{"title":"SetAlgebra Implementations","type":"topic","abstract":[],"url":"\/documentation\/gfpsdk\/gfprewardedstatus\/setalgebra-implementations","kind":"article","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedStatus\/SetAlgebra-Implementations","role":"collectionGroup"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRewardedStatus":{"type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPRewardedStatus"}],"kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedStatus","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPRewardedStatus"}],"url":"\/documentation\/gfpsdk\/gfprewardedstatus","title":"GFPRewardedStatus"}},"variantOverrides":[{"patch":[{"value":"GFPRewardedStatus","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedStatus\/title","op":"replace"},{"op":"replace","value":[{"text":"GFPRewardedStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedStatus\/fragments"},{"value":[{"text":"GFPRewardedStatus","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedStatus\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}