{"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAssetViewProtocol\/advertiseAssetView()","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Instance Method","role":"symbol","platforms":[{"unavailable":false,"introducedAt":"2.0","deprecated":false,"beta":false,"name":"iOS"},{"deprecated":false,"name":"iPadOS","unavailable":false,"introducedAt":"2.0","beta":false},{"beta":false,"name":"Mac Catalyst","introducedAt":"2.0","deprecated":false,"unavailable":false}],"navigatorTitle":[{"text":"advertiseAssetView","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"advertiseAssetView"},{"text":"() -> ","kind":"text"},{"text":"UIView","preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"modules":[{"name":"GFPSDK"}],"required":true,"symbolKind":"method","externalID":"c:objc(pl)GFPNativeAssetViewProtocol(im)advertiseAssetView","title":"advertiseAssetView()"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"optional","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"advertiseAssetView","kind":"identifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"text":"?","kind":"text"}]}]}],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpnativeassetviewprotocol\/advertiseassetview()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gfpsdk\/gfpnativeassetviewprotocol\/advertiseassetview()"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAssetViewProtocol"]]},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAssetViewProtocol":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPNativeAssetViewProtocol"}],"type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAssetViewProtocol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"GFPNativeAssetViewProtocol"}],"url":"\/documentation\/gfpsdk\/gfpnativeassetviewprotocol","title":"GFPNativeAssetViewProtocol","role":"symbol","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAssetViewProtocol/advertiseAssetView()":{"required":true,"role":"symbol","abstract":[],"title":"advertiseAssetView()","navigatorTitle":[{"kind":"identifier","text":"advertiseAssetView"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"advertiseAssetView"},{"text":"() -> ","kind":"text"},{"text":"UIView","preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAssetViewProtocol\/advertiseAssetView()","url":"\/documentation\/gfpsdk\/gfpnativeassetviewprotocol\/advertiseassetview()","type":"topic","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"advertiseAssetView"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"advertiseAssetView"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":" *) "},{"text":"advertiseAssetView","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","value":"GFPNativeAssetViewProtocol","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAssetViewProtocol\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAssetViewProtocol\/fragments","value":[{"text":"GFPNativeAssetViewProtocol","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAssetViewProtocol\/navigatorTitle","value":[{"text":"GFPNativeAssetViewProtocol","kind":"identifier"}],"op":"replace"},{"value":"advertiseAssetView","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAssetViewProtocol~1advertiseAssetView()\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAssetViewProtocol~1advertiseAssetView()\/fragments","value":[{"kind":"text","text":"- "},{"text":"advertiseAssetView","kind":"identifier"}]}]}]}