{"variants":[{"paths":["\/documentation\/gfpsdk\/gfpnativeassetviewprotocol\/ctaassetview()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gfpsdk\/gfpnativeassetviewprotocol\/ctaassetview()"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ctaAssetView"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"c:objc(cs)UIView","text":"UIView","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"navigatorTitle":[{"text":"ctaAssetView","kind":"identifier"}],"role":"symbol","title":"ctaAssetView()","symbolKind":"method","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"ctaAssetView","kind":"identifier"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier","text":"UIView"},{"kind":"text","text":"?"}],"externalID":"c:objc(pl)GFPNativeAssetViewProtocol(im)ctaAssetView","modules":[{"name":"GFPSDK"}],"platforms":[{"beta":false,"deprecated":false,"unavailable":false,"introducedAt":"2.0","name":"iOS"},{"beta":false,"deprecated":false,"name":"iPadOS","unavailable":false,"introducedAt":"2.0"},{"unavailable":false,"beta":false,"introducedAt":"2.0","name":"Mac Catalyst","deprecated":false}]},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAssetViewProtocol\/ctaAssetView()","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAssetViewProtocol"]]},"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAssetViewProtocol/ctaAssetView()":{"url":"\/documentation\/gfpsdk\/gfpnativeassetviewprotocol\/ctaassetview()","navigatorTitle":[{"text":"ctaAssetView","kind":"identifier"}],"type":"topic","title":"ctaAssetView()","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAssetViewProtocol\/ctaAssetView()","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ctaAssetView"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"?"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAssetViewProtocol":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPNativeAssetViewProtocol"}],"type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAssetViewProtocol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"GFPNativeAssetViewProtocol"}],"url":"\/documentation\/gfpsdk\/gfpnativeassetviewprotocol","title":"GFPNativeAssetViewProtocol","role":"symbol","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"ctaAssetView"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"ctaAssetView","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"text":" *) ","kind":"text"},{"text":"ctaAssetView","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAssetViewProtocol~1ctaAssetView()\/title","value":"ctaAssetView"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"ctaAssetView"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAssetViewProtocol~1ctaAssetView()\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAssetViewProtocol\/title","value":"GFPNativeAssetViewProtocol"},{"value":[{"text":"GFPNativeAssetViewProtocol","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAssetViewProtocol\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAssetViewProtocol\/navigatorTitle","value":[{"text":"GFPNativeAssetViewProtocol","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}