{"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAssetViewProtocol"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mediaContainerView","kind":"identifier"},{"kind":"text","text":"() -> "},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"?"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"metadata":{"platforms":[{"unavailable":false,"name":"iOS","introducedAt":"2.0","beta":false,"deprecated":false},{"deprecated":false,"introducedAt":"2.0","beta":false,"name":"iPadOS","unavailable":false},{"name":"Mac Catalyst","unavailable":false,"beta":false,"deprecated":false,"introducedAt":"2.0"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"mediaContainerView"}],"symbolKind":"method","title":"mediaContainerView()","roleHeading":"Instance Method","modules":[{"name":"GFPSDK"}],"required":true,"externalID":"c:objc(pl)GFPNativeAssetViewProtocol(im)mediaContainerView","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mediaContainerView","kind":"identifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"},{"text":"?","kind":"text"}]},"variants":[{"paths":["\/documentation\/gfpsdk\/gfpnativeassetviewprotocol\/mediacontainerview()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpnativeassetviewprotocol\/mediacontainerview()"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAssetViewProtocol\/mediaContainerView()"},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAssetViewProtocol":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPNativeAssetViewProtocol"}],"type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAssetViewProtocol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"GFPNativeAssetViewProtocol"}],"url":"\/documentation\/gfpsdk\/gfpnativeassetviewprotocol","title":"GFPNativeAssetViewProtocol","role":"symbol","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAssetViewProtocol/mediaContainerView()":{"required":true,"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAssetViewProtocol\/mediaContainerView()","navigatorTitle":[{"kind":"identifier","text":"mediaContainerView"}],"abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"mediaContainerView","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIView","text":"UIView","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","url":"\/documentation\/gfpsdk\/gfpnativeassetviewprotocol\/mediacontainerview()","title":"mediaContainerView()","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"mediaContainerView","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"mediaContainerView"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":" *) "},{"text":"mediaContainerView","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"value":"GFPNativeAssetViewProtocol","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAssetViewProtocol\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAssetViewProtocol\/fragments","value":[{"text":"GFPNativeAssetViewProtocol","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAssetViewProtocol\/navigatorTitle","op":"replace","value":[{"text":"GFPNativeAssetViewProtocol","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAssetViewProtocol~1mediaContainerView()\/title","value":"mediaContainerView"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"mediaContainerView"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAssetViewProtocol~1mediaContainerView()\/fragments"}]}]}