{"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"type":"text","text":"Remind 광고가 사라지면 호출됩니다. (상황 : Duration 시간이 지난 이후,  가로 세로 화면 전환시, Close 버튼 클릭 시)."}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearDelegate"]]},"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpnonlineardelegate\/nonlineardidhide(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gfpsdk\/gfpnonlineardelegate\/nonlineardidhide(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"nonLinearDidHide(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"nonLinearDidHide"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@E@GFPRemindType","text":"GFPRemindType","kind":"typeIdentifier"},{"kind":"text","text":")"}],"roleHeading":"Instance Method","role":"symbol","required":true,"externalID":"c:objc(pl)GFPNonLinearDelegate(im)nonLinearDidHide:","symbolKind":"method","navigatorTitle":[{"text":"nonLinearDidHide:","kind":"identifier"}],"modules":[{"name":"GFPSDK"}]},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearDelegate\/nonLinearDidHide(_:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"optional","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nonLinearDidHide","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"type","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRemindType","kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPRemindType","text":"GFPRemindType"},{"kind":"text","text":")"}]}]},{"kind":"parameters","parameters":[{"name":"type","content":[{"type":"paragraph","inlineContent":[{"text":"GFPRemindType","type":"text"}]}]}]}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNonLinearDelegate":{"url":"\/documentation\/gfpsdk\/gfpnonlineardelegate","abstract":[],"title":"GFPNonLinearDelegate","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearDelegate","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPNonLinearDelegate"}],"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPNonLinearDelegate"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNonLinearDelegate/nonLinearDidHide(_:)":{"type":"topic","abstract":[{"text":"Remind 광고가 사라지면 호출됩니다. (상황 : Duration 시간이 지난 이후,  가로 세로 화면 전환시, Close 버튼 클릭 시).","type":"text"}],"title":"nonLinearDidHide(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"nonLinearDidHide","kind":"identifier"},{"text":"(","kind":"text"},{"text":"GFPRemindType","preciseIdentifier":"c:@E@GFPRemindType","kind":"typeIdentifier"},{"kind":"text","text":")"}],"url":"\/documentation\/gfpsdk\/gfpnonlineardelegate\/nonlineardidhide(_:)","role":"symbol","required":true,"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearDelegate\/nonLinearDidHide(_:)","navigatorTitle":[{"kind":"identifier","text":"nonLinearDidHide:"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRemindType":{"url":"\/documentation\/gfpsdk\/gfpremindtype","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPRemindType"}],"navigatorTitle":[{"text":"GFPRemindType","kind":"identifier"}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRemindType","kind":"symbol","title":"GFPRemindType","abstract":[]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"nonLinearDidHide:","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"nonLinearDidHide:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"nonLinearDidHide:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRemindType","kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPRemindType","text":"GFPRemindType"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"type"},{"kind":"text","text":";"}]}]}},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"type","content":[{"inlineContent":[{"type":"text","text":"GFPRemindType"}],"type":"paragraph"}]}]},"op":"replace"},{"op":"replace","value":"GFPNonLinearDelegate","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearDelegate\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearDelegate\/fragments","value":[{"text":"GFPNonLinearDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"GFPNonLinearDelegate"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearDelegate~1nonLinearDidHide(_:)\/title","value":"nonLinearDidHide:"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearDelegate~1nonLinearDidHide(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"nonLinearDidHide:","kind":"identifier"}]},{"value":"GFPRemindType","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRemindType\/title"},{"op":"replace","value":[{"kind":"identifier","text":"GFPRemindType"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRemindType\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRemindType\/navigatorTitle","op":"replace","value":[{"text":"GFPRemindType","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}