{"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearDelegate"]]},"sections":[],"abstract":[{"type":"text","text":"Remind 광고 클릭시 호출됩니다."}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"optional","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"nonLinearWasClicked"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"type"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRemindType","preciseIdentifier":"c:@E@GFPRemindType","kind":"typeIdentifier","text":"GFPRemindType"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"GFPRemindType"}]}],"name":"type"}],"kind":"parameters"}],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpnonlineardelegate\/nonlinearwasclicked(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gfpsdk\/gfpnonlineardelegate\/nonlinearwasclicked(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:objc(pl)GFPNonLinearDelegate(im)nonLinearWasClicked:","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nonLinearWasClicked","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPRemindType","text":"GFPRemindType"},{"text":")","kind":"text"}],"roleHeading":"Instance Method","modules":[{"name":"GFPSDK"}],"title":"nonLinearWasClicked(_:)","navigatorTitle":[{"text":"nonLinearWasClicked:","kind":"identifier"}],"symbolKind":"method","role":"symbol"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearDelegate\/nonLinearWasClicked(_:)"},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRemindType":{"url":"\/documentation\/gfpsdk\/gfpremindtype","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPRemindType"}],"navigatorTitle":[{"text":"GFPRemindType","kind":"identifier"}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRemindType","kind":"symbol","title":"GFPRemindType","abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNonLinearDelegate/nonLinearWasClicked(_:)":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearDelegate\/nonLinearWasClicked(_:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"nonLinearWasClicked:"}],"title":"nonLinearWasClicked(_:)","required":true,"url":"\/documentation\/gfpsdk\/gfpnonlineardelegate\/nonlinearwasclicked(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nonLinearWasClicked","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@E@GFPRemindType","kind":"typeIdentifier","text":"GFPRemindType"},{"kind":"text","text":")"}],"type":"topic","abstract":[{"type":"text","text":"Remind 광고 클릭시 호출됩니다."}],"role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNonLinearDelegate":{"url":"\/documentation\/gfpsdk\/gfpnonlineardelegate","abstract":[],"title":"GFPNonLinearDelegate","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearDelegate","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPNonLinearDelegate"}],"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPNonLinearDelegate"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"nonLinearWasClicked:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"nonLinearWasClicked:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"nonLinearWasClicked:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@E@GFPRemindType","text":"GFPRemindType","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRemindType"},{"kind":"text","text":") "},{"text":"type","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"GFPRemindType","type":"text"}],"type":"paragraph"}],"name":"type"}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRemindType\/title","value":"GFPRemindType","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRemindType\/fragments","op":"replace","value":[{"text":"GFPRemindType","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"GFPRemindType"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRemindType\/navigatorTitle"},{"value":"nonLinearWasClicked:","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearDelegate~1nonLinearWasClicked(_:)\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearDelegate~1nonLinearWasClicked(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"nonLinearWasClicked:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearDelegate\/title","value":"GFPNonLinearDelegate"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearDelegate\/fragments","value":[{"kind":"identifier","text":"GFPNonLinearDelegate"}],"op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"GFPNonLinearDelegate"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearDelegate\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}