{"metadata":{"role":"symbol","modules":[{"name":"GFPSDK"}],"externalID":"c:objc(pl)GFPNonLinearDelegate(im)nonLinearOnActiveImpression:","symbolKind":"method","title":"nonLinear(onActiveImpression:)","navigatorTitle":[{"text":"nonLinearOnActiveImpression:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"nonLinear","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"onActiveImpression"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPRemindType","text":"GFPRemindType"},{"kind":"text","text":")"}],"roleHeading":"Instance Method","required":true},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"nonLinear"},{"text":"(","kind":"text"},{"text":"onActiveImpression","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"type"},{"kind":"text","text":": "},{"text":"GFPRemindType","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRemindType","kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPRemindType"},{"text":")","kind":"text"}]}]},{"parameters":[{"name":"type","content":[{"inlineContent":[{"type":"text","text":"GFPRemindType"}],"type":"paragraph"}]}],"kind":"parameters"}],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpnonlineardelegate\/nonlinear(onactiveimpression:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gfpsdk\/gfpnonlineardelegate\/nonlinear(onactiveimpression:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"Remind 광고가 사용자에게 보여질 경우 호출됩니다.."}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearDelegate"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearDelegate\/nonLinear(onActiveImpression:)"},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNonLinearDelegate":{"url":"\/documentation\/gfpsdk\/gfpnonlineardelegate","abstract":[],"title":"GFPNonLinearDelegate","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearDelegate","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPNonLinearDelegate"}],"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPNonLinearDelegate"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRemindType":{"url":"\/documentation\/gfpsdk\/gfpremindtype","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPRemindType"}],"navigatorTitle":[{"text":"GFPRemindType","kind":"identifier"}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRemindType","kind":"symbol","title":"GFPRemindType","abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNonLinearDelegate/nonLinear(onActiveImpression:)":{"type":"topic","abstract":[{"text":"Remind 광고가 사용자에게 보여질 경우 호출됩니다..","type":"text"}],"title":"nonLinear(onActiveImpression:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"nonLinear"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"onActiveImpression"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPRemindType","text":"GFPRemindType"},{"text":")","kind":"text"}],"url":"\/documentation\/gfpsdk\/gfpnonlineardelegate\/nonlinear(onactiveimpression:)","role":"symbol","required":true,"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearDelegate\/nonLinear(onActiveImpression:)","navigatorTitle":[{"text":"nonLinearOnActiveImpression:","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"value":"nonLinearOnActiveImpression:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"nonLinearOnActiveImpression:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"text":"nonLinearOnActiveImpression:","kind":"identifier"},{"kind":"text","text":"("},{"text":"GFPRemindType","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRemindType","kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPRemindType"},{"text":") ","kind":"text"},{"text":"type","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"type","content":[{"type":"paragraph","inlineContent":[{"text":"GFPRemindType","type":"text"}]}]}],"kind":"parameters"}},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearDelegate\/title","value":"GFPNonLinearDelegate","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearDelegate\/fragments","value":[{"text":"GFPNonLinearDelegate","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"GFPNonLinearDelegate"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearDelegate\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRemindType\/title","value":"GFPRemindType","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRemindType\/fragments","value":[{"kind":"identifier","text":"GFPRemindType"}],"op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"GFPRemindType"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRemindType\/navigatorTitle"},{"value":"nonLinearOnActiveImpression:","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearDelegate~1nonLinear(onActiveImpression:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearDelegate~1nonLinear(onActiveImpression:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"nonLinearOnActiveImpression:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}