{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isStrictSubset"},{"text":"(","kind":"text"},{"text":"of","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"other"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]}]}],"sections":[],"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoPlacementType\/isStrictSubset(of:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"SetAlgebra.isStrictSubset(of:)"},{"text":".","type":"text"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpvideoplacementtype\/isstrictsubset(of:)"]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoPlacementType","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoPlacementType\/SetAlgebra-Implementations"]]},"metadata":{"title":"isStrictSubset(of:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isStrictSubset"},{"kind":"text","text":"("},{"text":"of","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"roleHeading":"Instance Method","extendedModule":"Swift","externalID":"s:s10SetAlgebraPsE14isStrictSubset2ofSbx_tF::SYNTHESIZED::c:@E@GFPVideoPlacementType","role":"symbol","symbolKind":"method","modules":[{"relatedModules":["Swift"],"name":"GFPSDK"}]},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoPlacementType/isStrictSubset(of:)":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoPlacementType\/isStrictSubset(of:)","title":"isStrictSubset(of:)","abstract":[],"url":"\/documentation\/gfpsdk\/gfpvideoplacementtype\/isstrictsubset(of:)","role":"symbol","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isStrictSubset"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"of"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Self"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoPlacementType":{"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPVideoPlacementType","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"GFPVideoPlacementType","kind":"identifier"}],"type":"topic","title":"GFPVideoPlacementType","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoPlacementType","kind":"symbol","url":"\/documentation\/gfpsdk\/gfpvideoplacementtype","abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoPlacementType/SetAlgebra-Implementations":{"kind":"article","title":"SetAlgebra Implementations","abstract":[],"type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoPlacementType\/SetAlgebra-Implementations","url":"\/documentation\/gfpsdk\/gfpvideoplacementtype\/setalgebra-implementations","role":"collectionGroup"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoPlacementType\/title","value":"GFPVideoPlacementType"},{"value":[{"text":"GFPVideoPlacementType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoPlacementType\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoPlacementType\/navigatorTitle","value":[{"text":"GFPVideoPlacementType","kind":"identifier"}]}]}]}