{"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoPlacementType"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpvideoplacementtype\/mid"]},{"paths":["\/documentation\/gfpsdk\/gfpvideoplacementtype\/mid"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mid"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoPlacementType","kind":"typeIdentifier","text":"GFPVideoPlacementType","preciseIdentifier":"c:@E@GFPVideoPlacementType"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"metadata":{"modules":[{"name":"GFPSDK"}],"navigatorTitle":[{"kind":"identifier","text":"GFPVideoPlacementTypeMid"}],"role":"symbol","title":"mid","symbolKind":"property","externalID":"c:@E@GFPVideoPlacementType@GFPVideoPlacementTypeMid","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"mid","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPVideoPlacementType","text":"GFPVideoPlacementType"}],"roleHeading":"Type Property"},"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoPlacementType\/mid","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoPlacementType":{"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPVideoPlacementType","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"GFPVideoPlacementType","kind":"identifier"}],"type":"topic","title":"GFPVideoPlacementType","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoPlacementType","kind":"symbol","url":"\/documentation\/gfpsdk\/gfpvideoplacementtype","abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoPlacementType/mid":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mid","kind":"identifier"},{"kind":"text","text":": "},{"text":"GFPVideoPlacementType","kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPVideoPlacementType"}],"navigatorTitle":[{"text":"GFPVideoPlacementTypeMid","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpvideoplacementtype\/mid","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoPlacementType\/mid","kind":"symbol","role":"symbol","abstract":[],"type":"topic","title":"mid"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"op":"replace","value":"GFPVideoPlacementTypeMid","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GFPVideoPlacementTypeMid"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"GFPVideoPlacementTypeMid"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":"GFPVideoPlacementType","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoPlacementType\/title"},{"value":[{"kind":"identifier","text":"GFPVideoPlacementType"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoPlacementType\/fragments","op":"replace"},{"value":[{"text":"GFPVideoPlacementType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoPlacementType\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoPlacementType~1mid\/title","value":"GFPVideoPlacementTypeMid","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoPlacementType~1mid\/fragments","op":"replace","value":[{"kind":"identifier","text":"GFPVideoPlacementTypeMid"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}