{"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdRenderingSetting"]]},"metadata":{"role":"symbol","title":"addRenderer(with:rendererView:)","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"addRenderer","kind":"identifier"},{"kind":"text","text":"("},{"text":"with","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"rendererView","kind":"externalParam"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"},{"kind":"text","text":" & "},{"preciseIdentifier":"c:objc(pl)GFPNativeRendererViewProtocol","kind":"typeIdentifier","text":"GFPNativeRendererViewProtocol"},{"kind":"text","text":")"}],"externalID":"c:objc(cs)GFPNativeSimpleAdRenderingSetting(im)addRendererWith:rendererView:","symbolKind":"method","navigatorTitle":[{"text":"addRendererWith:rendererView:","kind":"identifier"}],"modules":[{"name":"GFPSDK"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"addRenderer"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"key"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"rendererView","kind":"externalParam"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"text":" & ","kind":"text"},{"preciseIdentifier":"c:objc(pl)GFPNativeRendererViewProtocol","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeRendererViewProtocol","text":"GFPNativeRendererViewProtocol"},{"text":")","kind":"text"}],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdRenderingSetting\/addRenderer(with:rendererView:)","interfaceLanguage":"swift"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpnativesimpleadrenderingsetting\/addrenderer(with:rendererview:)"]},{"paths":["\/documentation\/gfpsdk\/gfpnativesimpleadrenderingsetting\/addrenderer(with:rendererview:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeSimpleAdRenderingSetting":{"type":"topic","url":"\/documentation\/gfpsdk\/gfpnativesimpleadrenderingsetting","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPNativeSimpleAdRenderingSetting"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdRenderingSetting","title":"GFPNativeSimpleAdRenderingSetting","navigatorTitle":[{"text":"GFPNativeSimpleAdRenderingSetting","kind":"identifier"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeSimpleAdRenderingSetting/addRenderer(with:rendererView:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"addRenderer"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"rendererView","kind":"externalParam"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"},{"text":" & ","kind":"text"},{"text":"GFPNativeRendererViewProtocol","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)GFPNativeRendererViewProtocol"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"addRendererWith:rendererView:","kind":"identifier"}],"title":"addRenderer(with:rendererView:)","url":"\/documentation\/gfpsdk\/gfpnativesimpleadrenderingsetting\/addrenderer(with:rendererview:)","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdRenderingSetting\/addRenderer(with:rendererView:)","type":"topic","role":"symbol","abstract":[],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeRendererViewProtocol":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPNativeRendererViewProtocol"}],"url":"\/documentation\/gfpsdk\/gfpnativerendererviewprotocol","abstract":[],"type":"topic","title":"GFPNativeRendererViewProtocol","navigatorTitle":[{"text":"GFPNativeRendererViewProtocol","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeRendererViewProtocol","role":"symbol","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"addRendererWith:rendererView:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"addRendererWith:rendererView:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"addRendererWith:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"key"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rendererView:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"UIView<GFPNativeRendererViewProtocol>","preciseIdentifier":"c:Q$objc(cs)UIViewobjc(pl)GFPNativeRendererViewProtocol"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"rendererView"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"GFPNativeSimpleAdRenderingSetting","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdRenderingSetting\/title"},{"op":"replace","value":[{"text":"GFPNativeSimpleAdRenderingSetting","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdRenderingSetting\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdRenderingSetting\/navigatorTitle","value":[{"kind":"identifier","text":"GFPNativeSimpleAdRenderingSetting"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdRenderingSetting~1addRenderer(with:rendererView:)\/title","value":"addRendererWith:rendererView:","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdRenderingSetting~1addRenderer(with:rendererView:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"addRendererWith:rendererView:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeRendererViewProtocol\/title","value":"GFPNativeRendererViewProtocol","op":"replace"},{"value":[{"kind":"identifier","text":"GFPNativeRendererViewProtocol"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeRendererViewProtocol\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"GFPNativeRendererViewProtocol"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeRendererViewProtocol\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}