{"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"maxExtendingHeight","kind":"identifier"},{"kind":"text","text":": "},{"text":"GFPMaxExtendingHeightSetter","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMaxExtendingHeightSetter","kind":"typeIdentifier","preciseIdentifier":"c:GFPNativeAdRenderingSetting.h@T@GFPMaxExtendingHeightSetter"},{"text":"? { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}]}]},{"kind":"content","content":[{"type":"heading","anchor":"discussion","text":"Discussion","level":2},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"maxExtendingHeight <= 0: 높이를 제한하지 않음"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"maxExtendingHeight > 0: 높이를 제한 함."},{"type":"text","text":" "},{"type":"text","text":"(기본값 -1)"}],"type":"paragraph"}]}]}]}],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpnativesimpleadrenderingsetting\/maxextendingheight"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpnativesimpleadrenderingsetting\/maxextendingheight"]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdRenderingSetting\/maxExtendingHeight"},"kind":"symbol","abstract":[{"text":"확장형 리치형 광고의 최대 확장 높이를 제한합니다.","type":"text"},{"type":"text","text":" "},{"text":"광고가 호출된 이후에도 동적으로 관리할 수 있습니다.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"9:16 비율의 동영상도 제공하는 스페셜 DA 프리미엄형 “뉴” 동영상 확장형 이후로 부터 출시된 일부 광고 상품 부터 적용됩니다."}],"metadata":{"role":"symbol","modules":[{"name":"GFPSDK"}],"externalID":"c:objc(cs)GFPNativeSimpleAdRenderingSetting(py)maxExtendingHeight","symbolKind":"property","title":"maxExtendingHeight","navigatorTitle":[{"kind":"identifier","text":"maxExtendingHeight"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"maxExtendingHeight","kind":"identifier"},{"kind":"text","text":": "},{"text":"GFPMaxExtendingHeightSetter","kind":"typeIdentifier","preciseIdentifier":"c:GFPNativeAdRenderingSetting.h@T@GFPMaxExtendingHeightSetter"},{"text":"?","kind":"text"}],"roleHeading":"Instance Property"},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdRenderingSetting"]]},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeSimpleAdRenderingSetting":{"type":"topic","url":"\/documentation\/gfpsdk\/gfpnativesimpleadrenderingsetting","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPNativeSimpleAdRenderingSetting"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdRenderingSetting","title":"GFPNativeSimpleAdRenderingSetting","navigatorTitle":[{"text":"GFPNativeSimpleAdRenderingSetting","kind":"identifier"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPMaxExtendingHeightSetter":{"abstract":[],"kind":"symbol","title":"GFPMaxExtendingHeightSetter","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"GFPMaxExtendingHeightSetter","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMaxExtendingHeightSetter","type":"topic","role":"symbol","url":"\/documentation\/gfpsdk\/gfpmaxextendingheightsetter","navigatorTitle":[{"text":"GFPMaxExtendingHeightSetter","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeSimpleAdRenderingSetting/maxExtendingHeight":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"maxExtendingHeight","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:GFPNativeAdRenderingSetting.h@T@GFPMaxExtendingHeightSetter","text":"GFPMaxExtendingHeightSetter"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"maxExtendingHeight"}],"title":"maxExtendingHeight","url":"\/documentation\/gfpsdk\/gfpnativesimpleadrenderingsetting\/maxextendingheight","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdRenderingSetting\/maxExtendingHeight","type":"topic","role":"symbol","abstract":[{"text":"확장형 리치형 광고의 최대 확장 높이를 제한합니다.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"광고가 호출된 이후에도 동적으로 관리할 수 있습니다."},{"type":"text","text":" "},{"text":"9:16 비율의 동영상도 제공하는 스페셜 DA 프리미엄형 “뉴” 동영상 확장형 이후로 부터 출시된 일부 광고 상품 부터 적용됩니다.","type":"text"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"maxExtendingHeight","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"value":[{"kind":"identifier","text":"maxExtendingHeight"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"text":") ","kind":"text"},{"text":"double (^)(void)","kind":"typeIdentifier","preciseIdentifier":"c:BFd()"},{"text":" ","kind":"text"},{"kind":"identifier","text":"maxExtendingHeight"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdRenderingSetting\/title","value":"GFPNativeSimpleAdRenderingSetting","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdRenderingSetting\/fragments","value":[{"text":"GFPNativeSimpleAdRenderingSetting","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"GFPNativeSimpleAdRenderingSetting"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdRenderingSetting\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMaxExtendingHeightSetter\/title","value":"GFPMaxExtendingHeightSetter","op":"replace"},{"value":[{"kind":"identifier","text":"GFPMaxExtendingHeightSetter"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMaxExtendingHeightSetter\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMaxExtendingHeightSetter\/navigatorTitle","value":[{"text":"GFPMaxExtendingHeightSetter","kind":"identifier"}],"op":"replace"},{"value":"maxExtendingHeight","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdRenderingSetting~1maxExtendingHeight\/title","op":"replace"},{"value":[{"kind":"identifier","text":"maxExtendingHeight"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdRenderingSetting~1maxExtendingHeight\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}