{"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"네이티브 심플에 기반한  리치형 광고 비디오 플레이어 이벤트를 위한 델리게이트 설정"}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdRenderingSetting"]]},"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpnativesimpleadrenderingsetting\/videoeventdelegate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpnativesimpleadrenderingsetting\/videoeventdelegate"]}],"metadata":{"title":"videoEventDelegate","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"videoEventDelegate","kind":"identifier"},{"kind":"text","text":": (any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)GFPNativeVideoEventDelegate","text":"GFPNativeVideoEventDelegate"},{"text":")?","kind":"text"}],"roleHeading":"Instance Property","role":"symbol","externalID":"c:objc(cs)GFPNativeSimpleAdRenderingSetting(py)videoEventDelegate","symbolKind":"property","navigatorTitle":[{"text":"videoEventDelegate","kind":"identifier"}],"modules":[{"name":"GFPSDK"}]},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdRenderingSetting\/videoEventDelegate","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"weak","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"videoEventDelegate","kind":"identifier"},{"kind":"text","text":": (any "},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeVideoEventDelegate","text":"GFPNativeVideoEventDelegate","preciseIdentifier":"c:objc(pl)GFPNativeVideoEventDelegate","kind":"typeIdentifier"},{"kind":"text","text":")? { "},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}]}]}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeSimpleAdRenderingSetting":{"type":"topic","url":"\/documentation\/gfpsdk\/gfpnativesimpleadrenderingsetting","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPNativeSimpleAdRenderingSetting"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdRenderingSetting","title":"GFPNativeSimpleAdRenderingSetting","navigatorTitle":[{"text":"GFPNativeSimpleAdRenderingSetting","kind":"identifier"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeSimpleAdRenderingSetting/videoEventDelegate":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"videoEventDelegate"},{"kind":"text","text":": (any "},{"kind":"typeIdentifier","text":"GFPNativeVideoEventDelegate","preciseIdentifier":"c:objc(pl)GFPNativeVideoEventDelegate"},{"kind":"text","text":")?"}],"navigatorTitle":[{"text":"videoEventDelegate","kind":"identifier"}],"title":"videoEventDelegate","url":"\/documentation\/gfpsdk\/gfpnativesimpleadrenderingsetting\/videoeventdelegate","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdRenderingSetting\/videoEventDelegate","type":"topic","role":"symbol","abstract":[{"type":"text","text":"네이티브 심플에 기반한  리치형 광고 비디오 플레이어 이벤트를 위한 델리게이트 설정"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeVideoEventDelegate":{"role":"symbol","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeVideoEventDelegate","type":"topic","kind":"symbol","url":"\/documentation\/gfpsdk\/gfpnativevideoeventdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPNativeVideoEventDelegate","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"GFPNativeVideoEventDelegate"}],"title":"GFPNativeVideoEventDelegate"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","value":"videoEventDelegate","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","value":[{"text":"videoEventDelegate","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"weak","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)GFPNativeVideoEventDelegate","text":"id<GFPNativeVideoEventDelegate>"},{"kind":"text","text":" "},{"text":"videoEventDelegate","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","value":"GFPNativeSimpleAdRenderingSetting","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdRenderingSetting\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdRenderingSetting\/fragments","value":[{"text":"GFPNativeSimpleAdRenderingSetting","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdRenderingSetting\/navigatorTitle","op":"replace","value":[{"text":"GFPNativeSimpleAdRenderingSetting","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdRenderingSetting~1videoEventDelegate\/title","op":"replace","value":"videoEventDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdRenderingSetting~1videoEventDelegate\/fragments","value":[{"text":"videoEventDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeVideoEventDelegate\/title","op":"replace","value":"GFPNativeVideoEventDelegate"},{"value":[{"text":"GFPNativeVideoEventDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeVideoEventDelegate\/fragments","op":"replace"},{"value":[{"text":"GFPNativeVideoEventDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeVideoEventDelegate\/navigatorTitle"}]}]}