{"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAdaptorParam"]]},"metadata":{"fragments":[{"text":"adHTML","kind":"identifier"}],"navigatorTitle":[{"text":"adHTML","kind":"identifier"}],"externalID":"c:objc(cs)GFPAdAdaptorParam(py)adHTML","role":"symbol","roleHeading":"Instance Property","title":"adHTML","modules":[{"name":"GFPSDK"}],"symbolKind":"property"},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"GFPAdHTML","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdHTML"},{"kind":"text","text":" * "},{"kind":"identifier","text":"adHTML"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}],"abstract":[{"type":"text","text":"NDA 관련 Banner, Video ADM"}],"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAdaptorParam\/adHTML","interfaceLanguage":"occ"},"sections":[],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpadadaptorparam\/adhtml"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdAdaptorParam":{"navigatorTitle":[{"text":"GFPAdAdaptorParam","kind":"identifier"}],"abstract":[],"title":"GFPAdAdaptorParam","url":"\/documentation\/gfpsdk\/gfpadadaptorparam","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAdaptorParam","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"GFPAdAdaptorParam","kind":"identifier"}],"type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdAdaptorParam/adHTML":{"abstract":[{"text":"NDA 관련 Banner, Video ADM","type":"text"}],"fragments":[{"kind":"identifier","text":"adHTML"}],"role":"symbol","type":"topic","url":"\/documentation\/gfpsdk\/gfpadadaptorparam\/adhtml","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAdaptorParam\/adHTML","title":"adHTML","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdaptorParam\/title","value":"GFPAdAdaptorParam","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdaptorParam\/fragments","value":[{"kind":"identifier","text":"GFPAdAdaptorParam"}]},{"op":"replace","value":[{"text":"GFPAdAdaptorParam","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdaptorParam\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}