{"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAdaptorParam\/init(ad:eventReporter:context:renderType:adParam:extra:config:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"text":"ad","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"GFPAd","preciseIdentifier":"c:objc(cs)GFPAd","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"eventReporter"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPEventReporter","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPEventReporter","text":"GFPEventReporter"},{"text":", ","kind":"text"},{"text":"context","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"GFPContext","preciseIdentifier":"c:objc(cs)GFPContext","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPContext","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"renderType"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPProviderRenderType","text":"GFPProviderRenderType","preciseIdentifier":"c:GFPProvider.h@T@GFPProviderRenderType","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"adParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdParam","preciseIdentifier":"c:objc(cs)GFPAdParam","text":"GFPAdParam"},{"text":"?, ","kind":"text"},{"text":"extra","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)GFPWaterfallExtra","text":"GFPWaterfallExtra","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPWaterfallExtra","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"config","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPWaterfallConfig","kind":"typeIdentifier","text":"GFPWaterfallConfig","preciseIdentifier":"c:objc(cs)GFPWaterfallConfig"},{"kind":"text","text":"?)"}]}]}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpadadaptorparam\/init(ad:eventreporter:context:rendertype:adparam:extra:config:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpadadaptorparam\/init(ad:eventreporter:context:rendertype:adparam:extra:config:)"]}],"metadata":{"role":"symbol","roleHeading":"Initializer","externalID":"c:objc(cs)GFPAdAdaptorParam(im)initWithAd:eventReporter:context:renderType:adParam:extra:config:","title":"init(ad:eventReporter:context:renderType:adParam:extra:config:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"ad","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPAd","kind":"typeIdentifier","text":"GFPAd"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"eventReporter"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"GFPEventReporter","preciseIdentifier":"c:objc(cs)GFPEventReporter"},{"kind":"text","text":", "},{"text":"context","kind":"externalParam"},{"kind":"text","text":": "},{"text":"GFPContext","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPContext"},{"kind":"text","text":", "},{"text":"renderType","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"GFPProviderRenderType","kind":"typeIdentifier","preciseIdentifier":"c:GFPProvider.h@T@GFPProviderRenderType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"adParam"},{"kind":"text","text":": "},{"text":"GFPAdParam","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdParam"},{"kind":"text","text":"?, "},{"text":"extra","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPWaterfallExtra","text":"GFPWaterfallExtra"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"config"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"GFPWaterfallConfig","preciseIdentifier":"c:objc(cs)GFPWaterfallConfig"},{"text":"?)","kind":"text"}],"modules":[{"name":"GFPSDK"}],"navigatorTitle":[{"text":"initWithAd:eventReporter:context:renderType:adParam:extra:config:","kind":"identifier"}],"symbolKind":"init"},"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAdaptorParam"]]},"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPContext":{"type":"topic","navigatorTitle":[{"text":"GFPContext","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/gfpsdk\/gfpcontext","role":"symbol","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPContext"}],"title":"GFPContext","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPContext"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPEventReporter":{"url":"\/documentation\/gfpsdk\/gfpeventreporter","navigatorTitle":[{"text":"GFPEventReporter","kind":"identifier"}],"title":"GFPEventReporter","kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPEventReporter","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPEventReporter"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdAdaptorParam":{"navigatorTitle":[{"text":"GFPAdAdaptorParam","kind":"identifier"}],"abstract":[],"title":"GFPAdAdaptorParam","url":"\/documentation\/gfpsdk\/gfpadadaptorparam","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAdaptorParam","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"GFPAdAdaptorParam","kind":"identifier"}],"type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdParam":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdParam","abstract":[],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPAdParam"}],"navigatorTitle":[{"text":"GFPAdParam","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpadparam","type":"topic","kind":"symbol","title":"GFPAdParam"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPProviderRenderType":{"abstract":[],"title":"GFPProviderRenderType","type":"topic","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPProviderRenderType","navigatorTitle":[{"kind":"identifier","text":"GFPProviderRenderType"}],"kind":"symbol","url":"\/documentation\/gfpsdk\/gfpproviderrendertype","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"GFPProviderRenderType","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdAdaptorParam/init(ad:eventReporter:context:renderType:adParam:extra:config:)":{"type":"topic","url":"\/documentation\/gfpsdk\/gfpadadaptorparam\/init(ad:eventreporter:context:rendertype:adparam:extra:config:)","title":"init(ad:eventReporter:context:renderType:adParam:extra:config:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"ad","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)GFPAd","text":"GFPAd","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"eventReporter","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GFPEventReporter","preciseIdentifier":"c:objc(cs)GFPEventReporter"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"context"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"GFPContext","preciseIdentifier":"c:objc(cs)GFPContext"},{"kind":"text","text":", "},{"kind":"externalParam","text":"renderType"},{"text":": ","kind":"text"},{"text":"GFPProviderRenderType","kind":"typeIdentifier","preciseIdentifier":"c:GFPProvider.h@T@GFPProviderRenderType"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"adParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"GFPAdParam","preciseIdentifier":"c:objc(cs)GFPAdParam"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"extra"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)GFPWaterfallExtra","text":"GFPWaterfallExtra","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"config","kind":"externalParam"},{"kind":"text","text":": "},{"text":"GFPWaterfallConfig","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPWaterfallConfig"},{"text":"?)","kind":"text"}],"role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"initWithAd:eventReporter:context:renderType:adParam:extra:config:"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAdaptorParam\/init(ad:eventReporter:context:renderType:adParam:extra:config:)","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAd":{"title":"GFPAd","abstract":[{"type":"text","text":"GFPAd"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAd","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"GFPAd","kind":"identifier"}],"type":"topic","url":"\/documentation\/gfpsdk\/gfpad","kind":"symbol","navigatorTitle":[{"text":"GFPAd","kind":"identifier"}],"role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPWaterfallExtra":{"abstract":[],"navigatorTitle":[{"text":"GFPWaterfallExtra","kind":"identifier"}],"title":"GFPWaterfallExtra","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPWaterfallExtra","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPWaterfallExtra"}],"url":"\/documentation\/gfpsdk\/gfpwaterfallextra","kind":"symbol","role":"symbol","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPWaterfallConfig":{"navigatorTitle":[{"text":"GFPWaterfallConfig","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPWaterfallConfig","url":"\/documentation\/gfpsdk\/gfpwaterfallconfig","kind":"symbol","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"GFPWaterfallConfig","kind":"identifier"}],"title":"GFPWaterfallConfig","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"initWithAd:eventReporter:context:renderType:adParam:extra:config:","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"initWithAd:eventReporter:context:renderType:adParam:extra:config:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"text":") ","kind":"text"},{"text":"initWithAd:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAd","text":"GFPAd","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAd"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"ad"},{"kind":"text","text":" "},{"text":"eventReporter:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GFPEventReporter","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPEventReporter","preciseIdentifier":"c:objc(cs)GFPEventReporter"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"eventReporter"},{"kind":"text","text":" "},{"text":"context:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPContext","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPContext","text":"GFPContext"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"context"},{"text":" ","kind":"text"},{"text":"renderType:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"renderType","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"adParam:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdParam","text":"GFPAdParam","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdParam"},{"text":" *) ","kind":"text"},{"text":"adParam","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"extra:"},{"text":"(","kind":"text"},{"text":"GFPWaterfallExtra","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPWaterfallExtra","preciseIdentifier":"c:objc(cs)GFPWaterfallExtra","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"extra"},{"kind":"text","text":" "},{"kind":"identifier","text":"config:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPWaterfallConfig","kind":"typeIdentifier","text":"GFPWaterfallConfig","preciseIdentifier":"c:objc(cs)GFPWaterfallConfig"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"config"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPContext\/title","value":"GFPContext","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPContext\/fragments","value":[{"kind":"identifier","text":"GFPContext"}]},{"op":"replace","value":[{"text":"GFPContext","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPContext\/navigatorTitle"},{"op":"replace","value":"GFPEventReporter","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPEventReporter\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPEventReporter\/fragments","value":[{"kind":"identifier","text":"GFPEventReporter"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPEventReporter\/navigatorTitle","value":[{"text":"GFPEventReporter","kind":"identifier"}],"op":"replace"},{"value":"GFPAdAdaptorParam","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdaptorParam\/title"},{"value":[{"text":"GFPAdAdaptorParam","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdaptorParam\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdaptorParam\/navigatorTitle","op":"replace","value":[{"text":"GFPAdAdaptorParam","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdParam\/title","value":"GFPAdParam"},{"op":"replace","value":[{"text":"GFPAdParam","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdParam\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdParam\/navigatorTitle","value":[{"kind":"identifier","text":"GFPAdParam"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPProviderRenderType\/title","value":"GFPProviderRenderType","op":"replace"},{"value":[{"kind":"identifier","text":"GFPProviderRenderType"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPProviderRenderType\/fragments"},{"value":[{"kind":"identifier","text":"GFPProviderRenderType"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPProviderRenderType\/navigatorTitle","op":"replace"},{"value":"initWithAd:eventReporter:context:renderType:adParam:extra:config:","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdaptorParam~1init(ad:eventReporter:context:renderType:adParam:extra:config:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"initWithAd:eventReporter:context:renderType:adParam:extra:config:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdaptorParam~1init(ad:eventReporter:context:renderType:adParam:extra:config:)\/fragments"},{"op":"replace","value":"GFPAd","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAd\/title"},{"op":"replace","value":[{"text":"GFPAd","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAd\/fragments"},{"value":[{"kind":"identifier","text":"GFPAd"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAd\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPWaterfallExtra\/title","op":"replace","value":"GFPWaterfallExtra"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPWaterfallExtra\/fragments","op":"replace","value":[{"kind":"identifier","text":"GFPWaterfallExtra"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPWaterfallExtra\/navigatorTitle","op":"replace","value":[{"text":"GFPWaterfallExtra","kind":"identifier"}]},{"value":"GFPWaterfallConfig","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPWaterfallConfig\/title"},{"value":[{"text":"GFPWaterfallConfig","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPWaterfallConfig\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPWaterfallConfig\/navigatorTitle","value":[{"kind":"identifier","text":"GFPWaterfallConfig"}],"op":"replace"}]}]}