{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAdaptorParam\/renderType"},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAdaptorParam"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"renderType"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:GFPProvider.h@T@GFPProviderRenderType","text":"GFPProviderRenderType","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPProviderRenderType"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"선택된 RenderType"}],"kind":"symbol","metadata":{"modules":[{"name":"GFPSDK"}],"role":"symbol","roleHeading":"Instance Property","externalID":"c:objc(cs)GFPAdAdaptorParam(py)renderType","title":"renderType","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"renderType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"GFPProviderRenderType","preciseIdentifier":"c:GFPProvider.h@T@GFPProviderRenderType","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"renderType"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpadadaptorparam\/rendertype"]},{"paths":["\/documentation\/gfpsdk\/gfpadadaptorparam\/rendertype"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPProviderRenderType":{"abstract":[],"title":"GFPProviderRenderType","type":"topic","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPProviderRenderType","navigatorTitle":[{"kind":"identifier","text":"GFPProviderRenderType"}],"kind":"symbol","url":"\/documentation\/gfpsdk\/gfpproviderrendertype","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"GFPProviderRenderType","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdAdaptorParam":{"navigatorTitle":[{"text":"GFPAdAdaptorParam","kind":"identifier"}],"abstract":[],"title":"GFPAdAdaptorParam","url":"\/documentation\/gfpsdk\/gfpadadaptorparam","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAdaptorParam","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"GFPAdAdaptorParam","kind":"identifier"}],"type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdAdaptorParam/renderType":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"renderType"},{"text":": ","kind":"text"},{"text":"GFPProviderRenderType","preciseIdentifier":"c:GFPProvider.h@T@GFPProviderRenderType","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"renderType"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAdaptorParam\/renderType","url":"\/documentation\/gfpsdk\/gfpadadaptorparam\/rendertype","title":"renderType","type":"topic","abstract":[{"type":"text","text":"선택된 RenderType"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"value":"renderType","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"renderType"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"renderType","kind":"identifier"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPProviderRenderType\/title","value":"GFPProviderRenderType","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"GFPProviderRenderType"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPProviderRenderType\/fragments"},{"value":[{"kind":"identifier","text":"GFPProviderRenderType"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPProviderRenderType\/navigatorTitle"},{"value":"GFPAdAdaptorParam","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdaptorParam\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdaptorParam\/fragments","op":"replace","value":[{"text":"GFPAdAdaptorParam","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdaptorParam\/navigatorTitle","value":[{"kind":"identifier","text":"GFPAdAdaptorParam"}]},{"op":"replace","value":"renderType","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdaptorParam~1renderType\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdaptorParam~1renderType\/fragments","op":"replace","value":[{"text":"renderType","kind":"identifier"}]}]}]}