{"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpadadaptorparam\/sdkrequestinfo"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gfpsdk\/gfpadadaptorparam\/sdkrequestinfo"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"navigatorTitle":[{"text":"sdkRequestInfo","kind":"identifier"}],"externalID":"c:objc(cs)GFPAdAdaptorParam(py)sdkRequestInfo","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"sdkRequestInfo","kind":"identifier"},{"kind":"text","text":": ["},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"modules":[{"name":"GFPSDK"}],"roleHeading":"Instance Property","role":"symbol","title":"sdkRequestInfo"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sdkRequestInfo"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"},{"kind":"text","text":"] { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAdaptorParam"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAdaptorParam\/sdkRequestInfo"},"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdAdaptorParam/sdkRequestInfo":{"navigatorTitle":[{"text":"sdkRequestInfo","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpadadaptorparam\/sdkrequestinfo","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"sdkRequestInfo"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAdaptorParam\/sdkRequestInfo","title":"sdkRequestInfo"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdAdaptorParam":{"navigatorTitle":[{"text":"GFPAdAdaptorParam","kind":"identifier"}],"abstract":[],"title":"GFPAdAdaptorParam","url":"\/documentation\/gfpsdk\/gfpadadaptorparam","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAdaptorParam","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"GFPAdAdaptorParam","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"sdkRequestInfo"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"sdkRequestInfo","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:Q$objc(cs)NSDictionary","text":"NSDictionary<NSString *,NSObject *>","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"sdkRequestInfo"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdaptorParam~1sdkRequestInfo\/title","value":"sdkRequestInfo","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdaptorParam~1sdkRequestInfo\/fragments","value":[{"text":"sdkRequestInfo","kind":"identifier"}],"op":"replace"},{"value":"GFPAdAdaptorParam","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdaptorParam\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdaptorParam\/fragments","op":"replace","value":[{"kind":"identifier","text":"GFPAdAdaptorParam"}]},{"value":[{"kind":"identifier","text":"GFPAdAdaptorParam"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdaptorParam\/navigatorTitle"}]}]}