{"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAttachmentInfo"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"canSendAttachedEvnet","kind":"identifier"},{"kind":"text","text":"() -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpadattachmentinfo\/cansendattachedevnet()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpadattachmentinfo\/cansendattachedevnet()"]}],"metadata":{"role":"symbol","externalID":"c:objc(cs)GFPAdAttachmentInfo(im)canSendAttachedEvnet","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"canSendAttachedEvnet","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"modules":[{"name":"GFPSDK"}],"symbolKind":"method","roleHeading":"Instance Method","title":"canSendAttachedEvnet()","navigatorTitle":[{"text":"canSendAttachedEvnet","kind":"identifier"}]},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAttachmentInfo\/canSendAttachedEvnet()","interfaceLanguage":"swift"},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdAttachmentInfo/canSendAttachedEvnet()":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"canSendAttachedEvnet","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"title":"canSendAttachedEvnet()","abstract":[],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAttachmentInfo\/canSendAttachedEvnet()","type":"topic","navigatorTitle":[{"kind":"identifier","text":"canSendAttachedEvnet"}],"url":"\/documentation\/gfpsdk\/gfpadattachmentinfo\/cansendattachedevnet()"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdAttachmentInfo":{"type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAttachmentInfo","abstract":[],"title":"GFPAdAttachmentInfo","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"GFPAdAttachmentInfo","kind":"identifier"}],"navigatorTitle":[{"text":"GFPAdAttachmentInfo","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpadattachmentinfo","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"canSendAttachedEvnet"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"canSendAttachedEvnet","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"canSendAttachedEvnet"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAttachmentInfo~1canSendAttachedEvnet()\/title","value":"canSendAttachedEvnet"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAttachmentInfo~1canSendAttachedEvnet()\/fragments","value":[{"kind":"text","text":"- "},{"text":"canSendAttachedEvnet","kind":"identifier"}],"op":"replace"},{"value":"GFPAdAttachmentInfo","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAttachmentInfo\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAttachmentInfo\/fragments","value":[{"kind":"identifier","text":"GFPAdAttachmentInfo"}]},{"value":[{"text":"GFPAdAttachmentInfo","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAttachmentInfo\/navigatorTitle"}]}]}