{"metadata":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"markedAttachImpressioned"},{"kind":"text","text":"()"}],"navigatorTitle":[{"kind":"identifier","text":"markedAttachImpressioned"}],"symbolKind":"method","roleHeading":"Instance Method","externalID":"c:objc(cs)GFPAdAttachmentInfo(im)markedAttachImpressioned","title":"markedAttachImpressioned()","modules":[{"name":"GFPSDK"}]},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAttachmentInfo\/markedAttachImpressioned()","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"markedAttachImpressioned"},{"text":"()","kind":"text"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpadattachmentinfo\/markedattachimpressioned()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpadattachmentinfo\/markedattachimpressioned()"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAttachmentInfo"]]},"sections":[],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdAttachmentInfo":{"type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAttachmentInfo","abstract":[],"title":"GFPAdAttachmentInfo","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"GFPAdAttachmentInfo","kind":"identifier"}],"navigatorTitle":[{"text":"GFPAdAttachmentInfo","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpadattachmentinfo","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdAttachmentInfo/markedAttachImpressioned()":{"type":"topic","abstract":[],"title":"markedAttachImpressioned()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"markedAttachImpressioned","kind":"identifier"},{"text":"()","kind":"text"}],"url":"\/documentation\/gfpsdk\/gfpadattachmentinfo\/markedattachimpressioned()","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAttachmentInfo\/markedAttachImpressioned()","navigatorTitle":[{"text":"markedAttachImpressioned","kind":"identifier"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"markedAttachImpressioned","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"markedAttachImpressioned"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"markedAttachImpressioned","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAttachmentInfo\/title","value":"GFPAdAttachmentInfo","op":"replace"},{"value":[{"text":"GFPAdAttachmentInfo","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAttachmentInfo\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAttachmentInfo\/navigatorTitle","value":[{"kind":"identifier","text":"GFPAdAttachmentInfo"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAttachmentInfo~1markedAttachImpressioned()\/title","value":"markedAttachImpressioned","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"markedAttachImpressioned"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAttachmentInfo~1markedAttachImpressioned()\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}