{"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAttachmentInfo\/markedAttachedOnSuperView()","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"markedAttachedOnSuperView","kind":"identifier"},{"text":"()","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpadattachmentinfo\/markedattachedonsuperview()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpadattachmentinfo\/markedattachedonsuperview()"]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAttachmentInfo"]]},"metadata":{"symbolKind":"method","externalID":"c:objc(cs)GFPAdAttachmentInfo(im)markedAttachedOnSuperView","role":"symbol","modules":[{"name":"GFPSDK"}],"navigatorTitle":[{"kind":"identifier","text":"markedAttachedOnSuperView"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"markedAttachedOnSuperView","kind":"identifier"},{"kind":"text","text":"()"}],"roleHeading":"Instance Method","title":"markedAttachedOnSuperView()"},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdAttachmentInfo":{"type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAttachmentInfo","abstract":[],"title":"GFPAdAttachmentInfo","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"GFPAdAttachmentInfo","kind":"identifier"}],"navigatorTitle":[{"text":"GFPAdAttachmentInfo","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpadattachmentinfo","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdAttachmentInfo/markedAttachedOnSuperView()":{"abstract":[],"title":"markedAttachedOnSuperView()","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"markedAttachedOnSuperView","kind":"identifier"},{"text":"()","kind":"text"}],"url":"\/documentation\/gfpsdk\/gfpadattachmentinfo\/markedattachedonsuperview()","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAttachmentInfo\/markedAttachedOnSuperView()","navigatorTitle":[{"kind":"identifier","text":"markedAttachedOnSuperView"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"markedAttachedOnSuperView"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"markedAttachedOnSuperView","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"markedAttachedOnSuperView"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAttachmentInfo\/title","value":"GFPAdAttachmentInfo","op":"replace"},{"value":[{"kind":"identifier","text":"GFPAdAttachmentInfo"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAttachmentInfo\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAttachmentInfo\/navigatorTitle","value":[{"text":"GFPAdAttachmentInfo","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAttachmentInfo~1markedAttachedOnSuperView()\/title","value":"markedAttachedOnSuperView"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAttachmentInfo~1markedAttachedOnSuperView()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"markedAttachedOnSuperView"}]}]}]}