{"variants":[{"paths":["\/documentation\/gfpsdk\/staticresource\/initwithimageresourceelement:error:"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/StaticResource"]]},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/StaticResource\/initWithImageResourceElement:error:","interfaceLanguage":"occ"},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"kind":"symbol","metadata":{"roleHeading":"Instance Method","role":"symbol","navigatorTitle":[{"text":"initWithImageResourceElement:error:","kind":"identifier"}],"fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithImageResourceElement:error:"}],"modules":[{"name":"GFPSDK"}],"symbolKind":"method","externalID":"c:objc(cs)StaticResource(im)initWithImageResourceElement:error:","title":"initWithImageResourceElement:error:"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithImageResourceElement:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)DDXMLElement","kind":"typeIdentifier","text":"DDXMLElement"},{"kind":"text","text":" *) "},{"text":"aElement","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"error:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@NaverAdsServices@objc(cs)GFPError","text":"GFPError"},{"text":" * *) ","kind":"text"},{"text":"aError","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/StaticResource":{"abstract":[],"role":"symbol","url":"\/documentation\/gfpsdk\/staticresource","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StaticResource","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"StaticResource"}],"kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/StaticResource","type":"topic","title":"StaticResource"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/StaticResource/initWithImageResourceElement:error:":{"kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithImageResourceElement:error:"}],"url":"\/documentation\/gfpsdk\/staticresource\/initwithimageresourceelement:error:","type":"topic","title":"initWithImageResourceElement:error:","role":"symbol","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/StaticResource\/initWithImageResourceElement:error:","navigatorTitle":[{"kind":"identifier","text":"initWithImageResourceElement:error:"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1StaticResource\/title","value":"StaticResource"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1StaticResource\/fragments","op":"replace","value":[{"text":"StaticResource","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1StaticResource\/navigatorTitle","value":[{"text":"StaticResource","kind":"identifier"}],"op":"replace"}]}]}