{"metadata":{"role":"symbol","modules":[{"name":"GFPSDK"}],"externalID":"c:@M@GFPSDK@E@GFPVideoBackgroundActionType@GFPVideoBackgroundActionTypePause","symbolKind":"case","title":"GFPVideoBackgroundActionType.pause","navigatorTitle":[{"kind":"identifier","text":"GFPVideoBackgroundActionTypePause"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pause","kind":"identifier"}],"roleHeading":"Case"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"pause","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpvideobackgroundactiontype\/pause"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpvideobackgroundactiontype\/pause"]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoBackgroundActionType"]]},"kind":"symbol","identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoBackgroundActionType\/pause","interfaceLanguage":"swift"},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoBackgroundActionType/pause":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"pause","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpvideobackgroundactiontype\/pause","kind":"symbol","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoBackgroundActionType\/pause","abstract":[],"role":"symbol","navigatorTitle":[{"text":"GFPVideoBackgroundActionTypePause","kind":"identifier"}],"title":"GFPVideoBackgroundActionType.pause"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoBackgroundActionType":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPVideoBackgroundActionType"}],"type":"topic","title":"GFPVideoBackgroundActionType","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoBackgroundActionType","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPVideoBackgroundActionType","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpvideobackgroundactiontype"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"value":"GFPVideoBackgroundActionTypePause","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"GFPVideoBackgroundActionTypePause","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"GFPVideoBackgroundActionTypePause"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoBackgroundActionType~1pause\/title","value":"GFPVideoBackgroundActionTypePause","op":"replace"},{"value":[{"text":"GFPVideoBackgroundActionTypePause","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoBackgroundActionType~1pause\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoBackgroundActionType\/title","value":"GFPVideoBackgroundActionType","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"GFPVideoBackgroundActionType"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoBackgroundActionType\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoBackgroundActionType\/navigatorTitle","value":[{"text":"GFPVideoBackgroundActionType","kind":"identifier"}],"op":"replace"}]}]}