{"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPWaterfallList\/requestID","interfaceLanguage":"swift"},"metadata":{"externalID":"c:objc(cs)GFPWaterfallList(py)requestID","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestID"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"requestID","kind":"identifier"}],"modules":[{"name":"GFPSDK"}],"symbolKind":"property","role":"symbol","title":"requestID","roleHeading":"Instance Property"},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPWaterfallList"]]},"sections":[],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpwaterfalllist\/requestid"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpwaterfalllist\/requestid"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"requestID"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"? { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPWaterfallList":{"title":"GFPWaterfallList","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPWaterfallList","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPWaterfallList"}],"abstract":[{"text":"GFPWaterfallList","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"GFPWaterfallList"}],"url":"\/documentation\/gfpsdk\/gfpwaterfalllist","type":"topic","role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPWaterfallList/requestID":{"title":"requestID","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPWaterfallList\/requestID","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"requestID"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"requestID"}],"url":"\/documentation\/gfpsdk\/gfpwaterfalllist\/requestid","type":"topic","role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"requestID","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","value":[{"text":"requestID","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" * "},{"text":"requestID","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"GFPWaterfallList","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPWaterfallList\/title"},{"value":[{"kind":"identifier","text":"GFPWaterfallList"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPWaterfallList\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPWaterfallList\/navigatorTitle","op":"replace","value":[{"text":"GFPWaterfallList","kind":"identifier"}]},{"value":"requestID","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPWaterfallList~1requestID\/title"},{"value":[{"kind":"identifier","text":"requestID"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPWaterfallList~1requestID\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}