{"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPWebViewManager\/addHandlers(to:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addHandlers","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"to"},{"kind":"text","text":" "},{"text":"userContentController","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"WKUserContentController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKUserContentController"},{"text":")","kind":"text"}],"languages":["swift"]}]}],"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpwebviewmanager\/addhandlers(to:)"]},{"paths":["\/documentation\/gfpsdk\/gfpwebviewmanager\/addhandlers(to:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPWebViewManager"]]},"metadata":{"externalID":"c:@M@GFPSDK@objc(cs)GFPWebViewManager(im)addHandlersTo:","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"addHandlers","kind":"identifier"},{"kind":"text","text":"("},{"text":"to","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)WKUserContentController","text":"WKUserContentController","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"addHandlersTo:","kind":"identifier"}],"modules":[{"name":"GFPSDK"}],"symbolKind":"method","role":"symbol","title":"addHandlers(to:)","roleHeading":"Instance Method"},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPWebViewManager":{"title":"GFPWebViewManager","role":"symbol","navigatorTitle":[{"text":"GFPWebViewManager","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpwebviewmanager","kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPWebViewManager","abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPWebViewManager"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPWebViewManager/addHandlers(to:)":{"type":"topic","role":"symbol","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPWebViewManager\/addHandlers(to:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"addHandlers","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"text":"WKUserContentController","preciseIdentifier":"c:objc(cs)WKUserContentController","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"addHandlersTo:","kind":"identifier"}],"title":"addHandlers(to:)","url":"\/documentation\/gfpsdk\/gfpwebviewmanager\/addhandlers(to:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"addHandlersTo:","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"addHandlersTo:","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"addHandlersTo:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKUserContentController","text":"WKUserContentController"},{"text":" *) ","kind":"text"},{"text":"userContentController","kind":"internalParam"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":"GFPWebViewManager","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPWebViewManager\/title"},{"value":[{"text":"GFPWebViewManager","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPWebViewManager\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPWebViewManager\/navigatorTitle","op":"replace","value":[{"text":"GFPWebViewManager","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPWebViewManager~1addHandlers(to:)\/title","value":"addHandlersTo:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"addHandlersTo:"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPWebViewManager~1addHandlers(to:)\/fragments"}]}]}