{"metadata":{"role":"collectionGroup","title":"WKScriptMessageHandlerWithReply Implementations","roleHeading":"API Collection","modules":[{"name":"GFPSDK"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpwebviewmanager\/wkscriptmessagehandlerwithreply-implementations"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpwebviewmanager\/wkscriptmessagehandlerwithreply-implementations"]}],"kind":"article","topicSections":[{"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPWebViewManager\/userContentController(_:didReceive:)"],"anchor":"Instance-Methods","title":"Instance Methods","generated":true}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPWebViewManager"]]},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPWebViewManager\/WKScriptMessageHandlerWithReply-Implementations","interfaceLanguage":"swift"},"sections":[],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPWebViewManager/userContentController(_:didReceive:)":{"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"userContentController"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"WKUserContentController","preciseIdentifier":"c:objc(cs)WKUserContentController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WKScriptMessage","preciseIdentifier":"c:objc(cs)WKScriptMessage"},{"kind":"text","text":") "},{"text":"async","kind":"keyword"},{"kind":"text","text":" -> ("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?, "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?)","kind":"text"}],"url":"\/documentation\/gfpsdk\/gfpwebviewmanager\/usercontentcontroller(_:didreceive:)","title":"userContentController(_:didReceive:)","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPWebViewManager\/userContentController(_:didReceive:)","navigatorTitle":[{"kind":"identifier","text":"userContentController:didReceiveScriptMessage:replyHandler:"}],"abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPWebViewManager":{"title":"GFPWebViewManager","role":"symbol","navigatorTitle":[{"text":"GFPWebViewManager","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpwebviewmanager","kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPWebViewManager","abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPWebViewManager"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"anchor":"Instance-Methods","title":"Instance Methods","generated":true,"identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPWebViewManager\/userContentController(_:didReceive:)"]}]},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPWebViewManager~1userContentController(_:didReceive:)\/title","value":"userContentController:didReceiveScriptMessage:replyHandler:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPWebViewManager~1userContentController(_:didReceive:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"userContentController:didReceiveScriptMessage:replyHandler:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPWebViewManager\/title","value":"GFPWebViewManager","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPWebViewManager\/fragments","op":"replace","value":[{"text":"GFPWebViewManager","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPWebViewManager\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"GFPWebViewManager"}]}]}]}