{"metadata":{"role":"symbol","modules":[{"name":"GFPSDK"}],"platforms":[{"name":"iOS","beta":false,"introducedAt":"2.0","deprecated":false,"unavailable":false},{"introducedAt":"2.0","beta":false,"name":"iPadOS","deprecated":false,"unavailable":false},{"name":"Mac Catalyst","beta":false,"unavailable":false,"introducedAt":"2.0","deprecated":false}],"externalID":"c:objc(pl)NonLinearViewDelegate(im)nonLinearView:didClose:","symbolKind":"method","title":"nonLinearView(_:didClose:)","navigatorTitle":[{"kind":"identifier","text":"nonLinearView:didClose:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"nonLinearView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"GFPNonLinearAdView","preciseIdentifier":"c:objc(cs)GFPNonLinearAdView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didClose","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIButton","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIButton"},{"kind":"text","text":")"}],"roleHeading":"Instance Method","required":true},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"nonLinearView"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"aView"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)GFPNonLinearAdView","text":"GFPNonLinearAdView","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearAdView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didClose"},{"text":" ","kind":"text"},{"text":"sender","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIButton","text":"UIButton","kind":"typeIdentifier"},{"kind":"text","text":")"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/nonlinearviewdelegate\/nonlinearview(_:didclose:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/nonlinearviewdelegate\/nonlinearview(_:didclose:)"]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/NonLinearViewDelegate"]]},"kind":"symbol","identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/NonLinearViewDelegate\/nonLinearView(_:didClose:)","interfaceLanguage":"swift"},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/NonLinearViewDelegate":{"url":"\/documentation\/gfpsdk\/nonlinearviewdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NonLinearViewDelegate","kind":"identifier"}],"role":"symbol","abstract":[],"title":"NonLinearViewDelegate","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/NonLinearViewDelegate","navigatorTitle":[{"kind":"identifier","text":"NonLinearViewDelegate"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNonLinearAdView":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearAdView","title":"GFPNonLinearAdView","type":"topic","url":"\/documentation\/gfpsdk\/gfpnonlinearadview","abstract":[],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPNonLinearAdView"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPNonLinearAdView","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/NonLinearViewDelegate/nonLinearView(_:didClose:)":{"required":true,"navigatorTitle":[{"kind":"identifier","text":"nonLinearView:didClose:"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"nonLinearView"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPNonLinearAdView","text":"GFPNonLinearAdView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didClose"},{"text":": ","kind":"text"},{"text":"UIButton","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIButton"},{"text":")","kind":"text"}],"abstract":[],"type":"topic","role":"symbol","title":"nonLinearView(_:didClose:)","kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/NonLinearViewDelegate\/nonLinearView(_:didClose:)","url":"\/documentation\/gfpsdk\/nonlinearviewdelegate\/nonlinearview(_:didclose:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","value":"nonLinearView:didClose:","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"nonLinearView:didClose:"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"nonLinearView:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"GFPNonLinearAdView","preciseIdentifier":"c:objc(cs)GFPNonLinearAdView","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearAdView"},{"kind":"text","text":" *) "},{"text":"aView","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didClose:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UIButton","text":"UIButton","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"sender"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1NonLinearViewDelegate\/title","value":"NonLinearViewDelegate"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1NonLinearViewDelegate\/fragments","value":[{"kind":"identifier","text":"NonLinearViewDelegate"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1NonLinearViewDelegate\/navigatorTitle","value":[{"text":"NonLinearViewDelegate","kind":"identifier"}]},{"op":"replace","value":"GFPNonLinearAdView","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearAdView\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearAdView\/fragments","value":[{"kind":"identifier","text":"GFPNonLinearAdView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearAdView\/navigatorTitle","value":[{"kind":"identifier","text":"GFPNonLinearAdView"}]},{"op":"replace","value":"nonLinearView:didClose:","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1NonLinearViewDelegate~1nonLinearView(_:didClose:)\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1NonLinearViewDelegate~1nonLinearView(_:didClose:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"nonLinearView:didClose:","kind":"identifier"}],"op":"replace"}]}]}