{"metadata":{"navigatorTitle":[{"text":"nonLinearViewOnActiveImpression:","kind":"identifier"}],"required":true,"modules":[{"name":"GFPSDK"}],"role":"symbol","externalID":"c:objc(pl)NonLinearViewDelegate(im)nonLinearViewOnActiveImpression:","title":"nonLinearView(onActiveImpression:)","symbolKind":"method","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"nonLinearView"},{"kind":"text","text":"("},{"text":"onActiveImpression","kind":"externalParam"},{"kind":"text","text":": "},{"text":"GFPNonLinearAdView","preciseIdentifier":"c:objc(cs)GFPNonLinearAdView","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/nonlinearviewdelegate\/nonlinearview(onactiveimpression:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/nonlinearviewdelegate\/nonlinearview(onactiveimpression:)"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/NonLinearViewDelegate\/nonLinearView(onActiveImpression:)","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nonLinearView","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"onActiveImpression"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"aView"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearAdView","preciseIdentifier":"c:objc(cs)GFPNonLinearAdView","text":"GFPNonLinearAdView","kind":"typeIdentifier"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/NonLinearViewDelegate"]]},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNonLinearAdView":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearAdView","title":"GFPNonLinearAdView","type":"topic","url":"\/documentation\/gfpsdk\/gfpnonlinearadview","abstract":[],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPNonLinearAdView"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPNonLinearAdView","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/NonLinearViewDelegate/nonLinearView(onActiveImpression:)":{"type":"topic","navigatorTitle":[{"text":"nonLinearViewOnActiveImpression:","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/nonlinearviewdelegate\/nonlinearview(onactiveimpression:)","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/NonLinearViewDelegate\/nonLinearView(onActiveImpression:)","title":"nonLinearView(onActiveImpression:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"nonLinearView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"onActiveImpression"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"GFPNonLinearAdView","preciseIdentifier":"c:objc(cs)GFPNonLinearAdView"},{"text":")","kind":"text"}],"kind":"symbol","abstract":[],"required":true},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/NonLinearViewDelegate":{"url":"\/documentation\/gfpsdk\/nonlinearviewdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NonLinearViewDelegate","kind":"identifier"}],"role":"symbol","abstract":[],"title":"NonLinearViewDelegate","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/NonLinearViewDelegate","navigatorTitle":[{"kind":"identifier","text":"NonLinearViewDelegate"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"nonLinearViewOnActiveImpression:","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"nonLinearViewOnActiveImpression:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"nonLinearViewOnActiveImpression:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearAdView","preciseIdentifier":"c:objc(cs)GFPNonLinearAdView","text":"GFPNonLinearAdView","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"aView","kind":"internalParam"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"value":"GFPNonLinearAdView","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearAdView\/title"},{"op":"replace","value":[{"text":"GFPNonLinearAdView","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearAdView\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearAdView\/navigatorTitle","value":[{"text":"GFPNonLinearAdView","kind":"identifier"}],"op":"replace"},{"value":"nonLinearViewOnActiveImpression:","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1NonLinearViewDelegate~1nonLinearView(onActiveImpression:)\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1NonLinearViewDelegate~1nonLinearView(onActiveImpression:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"nonLinearViewOnActiveImpression:","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"NonLinearViewDelegate","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1NonLinearViewDelegate\/title"},{"value":[{"text":"NonLinearViewDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1NonLinearViewDelegate\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1NonLinearViewDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"NonLinearViewDelegate"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}