{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/nonlinearviewdelegate\/nonlinearview(inappbrowserdissmissed:)"]},{"paths":["\/documentation\/gfpsdk\/nonlinearviewdelegate\/nonlinearview(inappbrowserdissmissed:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/NonLinearViewDelegate"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/NonLinearViewDelegate\/nonLinearView(inAppBrowserDissmissed:)"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"kind":"symbol","metadata":{"symbolKind":"method","role":"symbol","externalID":"c:objc(pl)NonLinearViewDelegate(im)nonLinearViewInAppBrowserDissmissed:","modules":[{"name":"GFPSDK"}],"navigatorTitle":[{"text":"nonLinearViewInAppBrowserDissmissed:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nonLinearView","kind":"identifier"},{"kind":"text","text":"("},{"text":"inAppBrowserDissmissed","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GFPNonLinearAdView","preciseIdentifier":"c:objc(cs)GFPNonLinearAdView"},{"kind":"text","text":")"}],"roleHeading":"Instance Method","title":"nonLinearView(inAppBrowserDissmissed:)"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"nonLinearView","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"inAppBrowserDissmissed"},{"kind":"text","text":" "},{"kind":"internalParam","text":"aView"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPNonLinearAdView","text":"GFPNonLinearAdView","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearAdView"},{"text":")","kind":"text"}]}],"kind":"declarations"}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/NonLinearViewDelegate":{"url":"\/documentation\/gfpsdk\/nonlinearviewdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NonLinearViewDelegate","kind":"identifier"}],"role":"symbol","abstract":[],"title":"NonLinearViewDelegate","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/NonLinearViewDelegate","navigatorTitle":[{"kind":"identifier","text":"NonLinearViewDelegate"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNonLinearAdView":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearAdView","title":"GFPNonLinearAdView","type":"topic","url":"\/documentation\/gfpsdk\/gfpnonlinearadview","abstract":[],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPNonLinearAdView"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPNonLinearAdView","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/NonLinearViewDelegate/nonLinearView(inAppBrowserDissmissed:)":{"navigatorTitle":[{"text":"nonLinearViewInAppBrowserDissmissed:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"nonLinearView"},{"kind":"text","text":"("},{"text":"inAppBrowserDissmissed","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GFPNonLinearAdView","preciseIdentifier":"c:objc(cs)GFPNonLinearAdView"},{"text":")","kind":"text"}],"abstract":[],"type":"topic","role":"symbol","title":"nonLinearView(inAppBrowserDissmissed:)","kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/NonLinearViewDelegate\/nonLinearView(inAppBrowserDissmissed:)","url":"\/documentation\/gfpsdk\/nonlinearviewdelegate\/nonlinearview(inappbrowserdissmissed:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"value":"nonLinearViewInAppBrowserDissmissed:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"nonLinearViewInAppBrowserDissmissed:"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"nonLinearViewInAppBrowserDissmissed:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)GFPNonLinearAdView","text":"GFPNonLinearAdView","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearAdView"},{"text":" *) ","kind":"text"},{"text":"aView","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1NonLinearViewDelegate\/title","value":"NonLinearViewDelegate"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1NonLinearViewDelegate\/fragments","value":[{"kind":"identifier","text":"NonLinearViewDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1NonLinearViewDelegate\/navigatorTitle","op":"replace","value":[{"text":"NonLinearViewDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearAdView\/title","value":"GFPNonLinearAdView"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearAdView\/fragments","value":[{"text":"GFPNonLinearAdView","kind":"identifier"}]},{"op":"replace","value":[{"text":"GFPNonLinearAdView","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearAdView\/navigatorTitle"},{"value":"nonLinearViewInAppBrowserDissmissed:","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1NonLinearViewDelegate~1nonLinearView(inAppBrowserDissmissed:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1NonLinearViewDelegate~1nonLinearView(inAppBrowserDissmissed:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"nonLinearViewInAppBrowserDissmissed:","kind":"identifier"}],"op":"replace"}]}]}