{"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPCombinedProviderOption"]]},"sections":[],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpcombinedprovideroption\/dfp"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpcombinedprovideroption\/dfp"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DFP"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPCombinedProviderOption\/DFP","interfaceLanguage":"swift"},"metadata":{"externalID":"c:@M@GFPSDK@E@GFPCombinedProviderOption@GFPCombinedProviderOptionDFP","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"DFP"}],"navigatorTitle":[{"text":"GFPCombinedProviderOptionDFP","kind":"identifier"}],"modules":[{"name":"GFPSDK"}],"symbolKind":"case","role":"symbol","title":"GFPCombinedProviderOption.DFP","roleHeading":"Case"},"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPCombinedProviderOption":{"navigatorTitle":[{"text":"GFPCombinedProviderOption","kind":"identifier"}],"type":"topic","title":"GFPCombinedProviderOption","kind":"symbol","url":"\/documentation\/gfpsdk\/gfpcombinedprovideroption","abstract":[{"type":"text","text":"GFP에서 지원하는 Combined (배너, 네이티브)광고 제공자 목록"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPCombinedProviderOption","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPCombinedProviderOption"}],"role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPCombinedProviderOption/DFP":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DFP"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"GFPCombinedProviderOptionDFP"}],"url":"\/documentation\/gfpsdk\/gfpcombinedprovideroption\/dfp","kind":"symbol","type":"topic","role":"symbol","title":"GFPCombinedProviderOption.DFP","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPCombinedProviderOption\/DFP"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"GFPCombinedProviderOptionDFP"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"GFPCombinedProviderOptionDFP"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"GFPCombinedProviderOptionDFP"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPCombinedProviderOption\/title","value":"GFPCombinedProviderOption","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPCombinedProviderOption\/fragments","value":[{"kind":"identifier","text":"GFPCombinedProviderOption"}],"op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"GFPCombinedProviderOption"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPCombinedProviderOption\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPCombinedProviderOption~1DFP\/title","value":"GFPCombinedProviderOptionDFP","op":"replace"},{"value":[{"text":"GFPCombinedProviderOptionDFP","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPCombinedProviderOption~1DFP\/fragments"}]}]}