{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"hashValue"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"RawRepresentable.hashValue"},{"text":".","type":"text"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPCombinedProviderOption","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPCombinedProviderOption\/RawRepresentable-Implementations"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPCombinedProviderOption\/hashValue"},"metadata":{"externalID":"s:SYsSHRzSH8RawValueSYRpzrlE04hashB0Sivp::SYNTHESIZED::c:@M@GFPSDK@E@GFPCombinedProviderOption","conformance":{"availabilityPrefix":[{"text":"Available when","type":"text"}],"conformancePrefix":[{"text":"Conforms when","type":"text"}],"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"code":"RawValue","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":"."}]},"symbolKind":"property","roleHeading":"Instance Property","extendedModule":"Swift","title":"hashValue","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hashValue"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"role":"symbol","modules":[{"name":"GFPSDK","relatedModules":["Swift"]}]},"variants":[{"paths":["\/documentation\/gfpsdk\/gfpcombinedprovideroption\/hashvalue"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPCombinedProviderOption":{"navigatorTitle":[{"text":"GFPCombinedProviderOption","kind":"identifier"}],"type":"topic","title":"GFPCombinedProviderOption","kind":"symbol","url":"\/documentation\/gfpsdk\/gfpcombinedprovideroption","abstract":[{"type":"text","text":"GFP에서 지원하는 Combined (배너, 네이티브)광고 제공자 목록"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPCombinedProviderOption","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPCombinedProviderOption"}],"role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPCombinedProviderOption/RawRepresentable-Implementations":{"role":"collectionGroup","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPCombinedProviderOption\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/gfpsdk\/gfpcombinedprovideroption\/rawrepresentable-implementations","title":"RawRepresentable Implementations"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPCombinedProviderOption/hashValue":{"type":"topic","title":"hashValue","kind":"symbol","url":"\/documentation\/gfpsdk\/gfpcombinedprovideroption\/hashvalue","abstract":[],"conformance":{"availabilityPrefix":[{"text":"Available when","type":"text"}],"constraints":[{"code":"Self","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"code":"RawValue","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":"."}],"conformancePrefix":[{"type":"text","text":"Conforms when"}]},"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPCombinedProviderOption\/hashValue","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hashValue"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"value":"GFPCombinedProviderOption","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPCombinedProviderOption\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPCombinedProviderOption\/fragments","op":"replace","value":[{"kind":"identifier","text":"GFPCombinedProviderOption"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPCombinedProviderOption\/navigatorTitle","value":[{"kind":"identifier","text":"GFPCombinedProviderOption"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}