{"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPWaterfallExtra\/dedup","interfaceLanguage":"occ"},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPWaterfallExtra"]]},"sections":[],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpwaterfallextra\/dedup"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"GFPWaterfallDedup","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPWaterfallDedup"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"dedup"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"symbolKind":"property","title":"dedup","fragments":[{"text":"dedup","kind":"identifier"}],"externalID":"c:objc(cs)GFPWaterfallExtra(py)dedup","role":"symbol","modules":[{"name":"GFPSDK"}],"navigatorTitle":[{"kind":"identifier","text":"dedup"}],"roleHeading":"Instance Property"},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPWaterfallExtra/dedup":{"abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPWaterfallExtra\/dedup","fragments":[{"text":"dedup","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","title":"dedup","url":"\/documentation\/gfpsdk\/gfpwaterfallextra\/dedup"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPWaterfallExtra":{"abstract":[],"navigatorTitle":[{"text":"GFPWaterfallExtra","kind":"identifier"}],"title":"GFPWaterfallExtra","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPWaterfallExtra","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPWaterfallExtra"}],"url":"\/documentation\/gfpsdk\/gfpwaterfallextra","kind":"symbol","role":"symbol","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPWaterfallExtra\/title","op":"replace","value":"GFPWaterfallExtra"},{"value":[{"text":"GFPWaterfallExtra","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPWaterfallExtra\/fragments"},{"value":[{"kind":"identifier","text":"GFPWaterfallExtra"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPWaterfallExtra\/navigatorTitle"}]}]}