{"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager"]]},"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpvideoadschedulemanager\/advertiseparams"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gfpsdk\/gfpvideoadschedulemanager\/advertiseparams"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"advertiseParams","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"advertiseParams","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdvertiseParams","text":"GFPAdvertiseParams"},{"kind":"text","text":"?"}],"roleHeading":"Instance Property","role":"symbol","externalID":"c:objc(cs)GFPVideoAdScheduleManager(py)advertiseParams","symbolKind":"property","navigatorTitle":[{"text":"advertiseParams","kind":"identifier"}],"modules":[{"name":"GFPSDK"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager\/advertiseParams"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"advertiseParams","kind":"identifier"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdvertiseParams","text":"GFPAdvertiseParams","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdvertiseParams"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdScheduleManager":{"kind":"symbol","type":"topic","url":"\/documentation\/gfpsdk\/gfpvideoadschedulemanager","title":"GFPVideoAdScheduleManager","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager","navigatorTitle":[{"kind":"identifier","text":"GFPVideoAdScheduleManager"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPVideoAdScheduleManager"}],"abstract":[],"role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdScheduleManager/advertiseParams":{"role":"symbol","abstract":[],"title":"advertiseParams","navigatorTitle":[{"kind":"identifier","text":"advertiseParams"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"advertiseParams","kind":"identifier"},{"text":": ","kind":"text"},{"text":"GFPAdvertiseParams","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdvertiseParams"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager\/advertiseParams","type":"topic","kind":"symbol","url":"\/documentation\/gfpsdk\/gfpvideoadschedulemanager\/advertiseparams"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdvertiseParams":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdvertiseParams","kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPAdvertiseParams","kind":"identifier"}],"abstract":[],"navigatorTitle":[{"text":"GFPAdvertiseParams","kind":"identifier"}],"title":"GFPAdvertiseParams","url":"\/documentation\/gfpsdk\/gfpadvertiseparams"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"advertiseParams"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"advertiseParams","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdvertiseParams","text":"GFPAdvertiseParams","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdvertiseParams"},{"text":" * ","kind":"text"},{"text":"advertiseParams","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager\/title","value":"GFPVideoAdScheduleManager","op":"replace"},{"value":[{"text":"GFPVideoAdScheduleManager","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager\/navigatorTitle","value":[{"kind":"identifier","text":"GFPVideoAdScheduleManager"}],"op":"replace"},{"op":"replace","value":"advertiseParams","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager~1advertiseParams\/title"},{"op":"replace","value":[{"kind":"identifier","text":"advertiseParams"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager~1advertiseParams\/fragments"},{"value":"GFPAdvertiseParams","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdvertiseParams\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdvertiseParams\/fragments","value":[{"kind":"identifier","text":"GFPAdvertiseParams"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdvertiseParams\/navigatorTitle","value":[{"kind":"identifier","text":"GFPAdvertiseParams"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}