{"abstract":[{"type":"text","text":"RemindAd(Banner, Text) 광고를 사라지게 합니다."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hideNonLinearAd","kind":"identifier"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpvideoadschedulemanager\/hidenonlinearad()"]},{"paths":["\/documentation\/gfpsdk\/gfpvideoadschedulemanager\/hidenonlinearad()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager\/hideNonLinearAd()","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager"]]},"metadata":{"externalID":"c:objc(cs)GFPVideoAdScheduleManager(im)hideNonLinearAd","navigatorTitle":[{"kind":"identifier","text":"hideNonLinearAd"}],"title":"hideNonLinearAd()","role":"symbol","symbolKind":"method","roleHeading":"Instance Method","modules":[{"name":"GFPSDK"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"hideNonLinearAd","kind":"identifier"},{"kind":"text","text":"()"}]},"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdScheduleManager":{"kind":"symbol","type":"topic","url":"\/documentation\/gfpsdk\/gfpvideoadschedulemanager","title":"GFPVideoAdScheduleManager","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager","navigatorTitle":[{"kind":"identifier","text":"GFPVideoAdScheduleManager"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPVideoAdScheduleManager"}],"abstract":[],"role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdScheduleManager/hideNonLinearAd()":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager\/hideNonLinearAd()","navigatorTitle":[{"kind":"identifier","text":"hideNonLinearAd"}],"abstract":[{"text":"RemindAd(Banner, Text) 광고를 사라지게 합니다.","type":"text"}],"title":"hideNonLinearAd()","role":"symbol","kind":"symbol","url":"\/documentation\/gfpsdk\/gfpvideoadschedulemanager\/hidenonlinearad()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"hideNonLinearAd"},{"kind":"text","text":"()"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"hideNonLinearAd","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"hideNonLinearAd"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"hideNonLinearAd"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager\/title","op":"replace","value":"GFPVideoAdScheduleManager"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager\/fragments","op":"replace","value":[{"kind":"identifier","text":"GFPVideoAdScheduleManager"}]},{"op":"replace","value":[{"text":"GFPVideoAdScheduleManager","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager\/navigatorTitle"},{"value":"hideNonLinearAd","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager~1hideNonLinearAd()\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager~1hideNonLinearAd()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"hideNonLinearAd"}]}]}]}