{"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"renderingSetting","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GFPVideoAdRenderingSetting","preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPVideoAdRenderingSetting"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"renderingSetting"}],"roleHeading":"Instance Property","externalID":"c:objc(cs)GFPVideoAdScheduleManager(py)renderingSetting","modules":[{"name":"GFPSDK"}],"role":"symbol","symbolKind":"property","title":"renderingSetting"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager\/renderingSetting"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"renderingSetting","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdRenderingSetting","preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPVideoAdRenderingSetting","text":"GFPVideoAdRenderingSetting"},{"kind":"text","text":"? { "},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpvideoadschedulemanager\/renderingsetting"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpvideoadschedulemanager\/renderingsetting"]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager"]]},"sections":[],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdScheduleManager":{"kind":"symbol","type":"topic","url":"\/documentation\/gfpsdk\/gfpvideoadschedulemanager","title":"GFPVideoAdScheduleManager","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager","navigatorTitle":[{"kind":"identifier","text":"GFPVideoAdScheduleManager"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPVideoAdScheduleManager"}],"abstract":[],"role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdScheduleManager/renderingSetting":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager\/renderingSetting","url":"\/documentation\/gfpsdk\/gfpvideoadschedulemanager\/renderingsetting","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"renderingSetting"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"renderingSetting","kind":"identifier"},{"kind":"text","text":": "},{"text":"GFPVideoAdRenderingSetting","preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPVideoAdRenderingSetting","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"renderingSetting","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdRenderingSetting":{"type":"topic","abstract":[],"kind":"symbol","navigatorTitle":[{"text":"GFPVideoAdRenderingSetting","kind":"identifier"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPVideoAdRenderingSetting"}],"title":"GFPVideoAdRenderingSetting","url":"\/documentation\/gfpsdk\/gfpvideoadrenderingsetting","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdRenderingSetting"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"renderingSetting","op":"replace","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"renderingSetting"}],"path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPVideoAdRenderingSetting","text":"GFPVideoAdRenderingSetting","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdRenderingSetting"},{"kind":"text","text":" * "},{"text":"renderingSetting","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager\/title","value":"GFPVideoAdScheduleManager","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager\/fragments","value":[{"text":"GFPVideoAdScheduleManager","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"GFPVideoAdScheduleManager"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager\/navigatorTitle"},{"value":"renderingSetting","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager~1renderingSetting\/title","op":"replace"},{"op":"replace","value":[{"text":"renderingSetting","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager~1renderingSetting\/fragments"},{"value":"GFPVideoAdRenderingSetting","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdRenderingSetting\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdRenderingSetting\/fragments","op":"replace","value":[{"text":"GFPVideoAdRenderingSetting","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdRenderingSetting\/navigatorTitle","value":[{"kind":"identifier","text":"GFPVideoAdRenderingSetting"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}