{"abstract":[{"text":"RemindAd(Banner, Text) 광고를 노출합니다.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"ContainerType 없이 기본 위치에 노출. [배너 : Inner, 텍스트 : 가로 방향 (Inner), 세로 방향 (Outer)]"}],"metadata":{"title":"showNonLinearAd()","symbolKind":"method","modules":[{"name":"GFPSDK"}],"role":"symbol","externalID":"c:objc(cs)GFPVideoAdScheduleManager(im)showNonLinearAd","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"showNonLinearAd","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"showNonLinearAd","kind":"identifier"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager\/showNonLinearAd()","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"showNonLinearAd","kind":"identifier"},{"kind":"text","text":"()"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpvideoadschedulemanager\/shownonlinearad()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpvideoadschedulemanager\/shownonlinearad()"]}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdScheduleManager/showNonLinearAd()":{"navigatorTitle":[{"text":"showNonLinearAd","kind":"identifier"}],"title":"showNonLinearAd()","url":"\/documentation\/gfpsdk\/gfpvideoadschedulemanager\/shownonlinearad()","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager\/showNonLinearAd()","role":"symbol","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"RemindAd(Banner, Text) 광고를 노출합니다."},{"type":"text","text":" "},{"type":"text","text":"ContainerType 없이 기본 위치에 노출. [배너 : Inner, 텍스트 : 가로 방향 (Inner), 세로 방향 (Outer)]"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"showNonLinearAd","kind":"identifier"},{"text":"()","kind":"text"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdScheduleManager":{"kind":"symbol","type":"topic","url":"\/documentation\/gfpsdk\/gfpvideoadschedulemanager","title":"GFPVideoAdScheduleManager","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager","navigatorTitle":[{"kind":"identifier","text":"GFPVideoAdScheduleManager"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPVideoAdScheduleManager"}],"abstract":[],"role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"showNonLinearAd","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"showNonLinearAd","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"showNonLinearAd","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"value":"showNonLinearAd","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager~1showNonLinearAd()\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager~1showNonLinearAd()\/fragments","value":[{"kind":"text","text":"- "},{"text":"showNonLinearAd","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager\/title","value":"GFPVideoAdScheduleManager"},{"value":[{"text":"GFPVideoAdScheduleManager","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager\/navigatorTitle","op":"replace","value":[{"text":"GFPVideoAdScheduleManager","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}