{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpvideoadschedulemanager\/showoverlayview()"]},{"paths":["\/documentation\/gfpsdk\/gfpvideoadschedulemanager\/showoverlayview()"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"metadata":{"roleHeading":"Instance Method","symbolKind":"method","title":"showOverlayView()","navigatorTitle":[{"text":"showOverlayView","kind":"identifier"}],"modules":[{"name":"GFPSDK"}],"role":"symbol","externalID":"c:objc(cs)GFPVideoAdScheduleManager(im)showOverlayView","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showOverlayView"},{"kind":"text","text":"()"}]},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager\/showOverlayView()","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager"]]},"abstract":[{"type":"text","text":"광고의 Overlay(Seekbar, Pause, Resume, 선거 광고, 후광고 Text) 영역을 노출합니다."}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"showOverlayView"},{"kind":"text","text":"()"}]}]}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdScheduleManager":{"kind":"symbol","type":"topic","url":"\/documentation\/gfpsdk\/gfpvideoadschedulemanager","title":"GFPVideoAdScheduleManager","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager","navigatorTitle":[{"kind":"identifier","text":"GFPVideoAdScheduleManager"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPVideoAdScheduleManager"}],"abstract":[],"role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdScheduleManager/showOverlayView()":{"role":"symbol","abstract":[{"type":"text","text":"광고의 Overlay(Seekbar, Pause, Resume, 선거 광고, 후광고 Text) 영역을 노출합니다."}],"title":"showOverlayView()","navigatorTitle":[{"text":"showOverlayView","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"showOverlayView","kind":"identifier"},{"kind":"text","text":"()"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager\/showOverlayView()","type":"topic","kind":"symbol","url":"\/documentation\/gfpsdk\/gfpvideoadschedulemanager\/showoverlayview()"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"showOverlayView"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"showOverlayView","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"showOverlayView"},{"text":";","kind":"text"}]}]}},{"value":"GFPVideoAdScheduleManager","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager\/title","op":"replace"},{"value":[{"text":"GFPVideoAdScheduleManager","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager\/navigatorTitle","value":[{"text":"GFPVideoAdScheduleManager","kind":"identifier"}]},{"value":"showOverlayView","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager~1showOverlayView()\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager~1showOverlayView()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"showOverlayView"}]}]}]}