{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpvideoadschedulemanager\/shownonlinearad(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpvideoadschedulemanager\/shownonlinearad(_:)"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager"]]},"metadata":{"navigatorTitle":[{"text":"showNonLinearAd:","kind":"identifier"}],"modules":[{"name":"GFPSDK"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showNonLinearAd"},{"text":"(","kind":"text"},{"text":"GFPNonLinearContainerType","kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPNonLinearContainerType"},{"text":")","kind":"text"}],"title":"showNonLinearAd(_:)","roleHeading":"Instance Method","symbolKind":"method","externalID":"c:objc(cs)GFPVideoAdScheduleManager(im)showNonLinearAd:","role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"showNonLinearAd","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"type","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@GFPNonLinearContainerType","text":"GFPNonLinearContainerType","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearContainerType"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"parameters":[{"content":[{"inlineContent":[{"text":"RemindText 광고를 Content 영역 노출 위치 결정 [내부(Inner) 또는 외부(Outer)].","type":"text"}],"type":"paragraph"}],"name":"type"}],"kind":"parameters"}],"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"RemindAd(Banner, Text) 광고를 노출합니다."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager\/showNonLinearAd(_:)"},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdScheduleManager":{"kind":"symbol","type":"topic","url":"\/documentation\/gfpsdk\/gfpvideoadschedulemanager","title":"GFPVideoAdScheduleManager","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager","navigatorTitle":[{"kind":"identifier","text":"GFPVideoAdScheduleManager"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPVideoAdScheduleManager"}],"abstract":[],"role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdScheduleManager/showNonLinearAd(_:)":{"navigatorTitle":[{"text":"showNonLinearAd:","kind":"identifier"}],"type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"showNonLinearAd","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@E@GFPNonLinearContainerType","text":"GFPNonLinearContainerType","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"showNonLinearAd(_:)","url":"\/documentation\/gfpsdk\/gfpvideoadschedulemanager\/shownonlinearad(_:)","abstract":[{"text":"RemindAd(Banner, Text) 광고를 노출합니다.","type":"text"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager\/showNonLinearAd(_:)","role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNonLinearContainerType":{"abstract":[{"text":"RemindText 노출 위치에 따른 Type","type":"text"},{"type":"text","text":" "},{"text":"Container Inner : Content Player 영역 내부 노출.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Container Outer : Content Player 영역 외l부 노출."}],"kind":"symbol","title":"GFPNonLinearContainerType","navigatorTitle":[{"kind":"identifier","text":"GFPNonLinearContainerType"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearContainerType","url":"\/documentation\/gfpsdk\/gfpnonlinearcontainertype","type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPNonLinearContainerType"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","value":"showNonLinearAd:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"showNonLinearAd:","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"showNonLinearAd:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"GFPNonLinearContainerType","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearContainerType","preciseIdentifier":"c:@E@GFPNonLinearContainerType"},{"text":") ","kind":"text"},{"text":"type","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"RemindText 광고를 Content 영역 노출 위치 결정 [내부(Inner) 또는 외부(Outer)].","type":"text"}]}],"name":"type"}]},"op":"replace"},{"op":"replace","value":"GFPVideoAdScheduleManager","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager\/fragments","value":[{"text":"GFPVideoAdScheduleManager","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager\/navigatorTitle","value":[{"text":"GFPVideoAdScheduleManager","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager~1showNonLinearAd(_:)\/title","value":"showNonLinearAd:"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager~1showNonLinearAd(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"showNonLinearAd:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearContainerType\/title","op":"replace","value":"GFPNonLinearContainerType"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearContainerType\/fragments","value":[{"text":"GFPNonLinearContainerType","kind":"identifier"}]},{"value":[{"text":"GFPNonLinearContainerType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearContainerType\/navigatorTitle"}]}]}