{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"text":"creativeType","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"aCreativeType","kind":"internalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPProviderCreativeType","kind":"typeIdentifier","text":"GFPProviderCreativeType","preciseIdentifier":"c:GFPProvider.h@T@GFPProviderCreativeType"},{"text":", ","kind":"text"},{"text":"dictionary","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"aDict","kind":"internalParam"},{"text":": [","kind":"text"},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]?)"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPEventExtraInfo"]]},"metadata":{"role":"symbol","symbolKind":"init","modules":[{"name":"GFPSDK"}],"roleHeading":"Initializer","externalID":"c:objc(cs)GFPEventExtraInfo(im)initWithCreativeType:dictionary:","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"creativeType","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:GFPProvider.h@T@GFPProviderCreativeType","text":"GFPProviderCreativeType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"dictionary"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier","text":"AnyHashable"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]?)"}],"navigatorTitle":[{"kind":"identifier","text":"initWithCreativeType:dictionary:"}],"title":"init(creativeType:dictionary:)"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPEventExtraInfo\/init(creativeType:dictionary:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/gfpsdk\/gfpeventextrainfo\/init(creativetype:dictionary:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpeventextrainfo\/init(creativetype:dictionary:)"]}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPProviderCreativeType":{"type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPProviderCreativeType","abstract":[],"title":"GFPProviderCreativeType","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPProviderCreativeType","kind":"identifier"}],"navigatorTitle":[{"text":"GFPProviderCreativeType","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpprovidercreativetype","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPEventExtraInfo":{"navigatorTitle":[{"text":"GFPEventExtraInfo","kind":"identifier"}],"role":"symbol","title":"GFPEventExtraInfo","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPEventExtraInfo"}],"type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPEventExtraInfo","abstract":[],"url":"\/documentation\/gfpsdk\/gfpeventextrainfo"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPEventExtraInfo/init(creativeType:dictionary:)":{"navigatorTitle":[{"kind":"identifier","text":"initWithCreativeType:dictionary:"}],"title":"init(creativeType:dictionary:)","url":"\/documentation\/gfpsdk\/gfpeventextrainfo\/init(creativetype:dictionary:)","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPEventExtraInfo\/init(creativeType:dictionary:)","role":"symbol","type":"topic","kind":"symbol","abstract":[],"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"creativeType","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:GFPProvider.h@T@GFPProviderCreativeType","text":"GFPProviderCreativeType"},{"kind":"text","text":", "},{"text":"dictionary","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"text":"]?)","kind":"text"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithCreativeType:dictionary:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithCreativeType:dictionary:","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"initWithCreativeType:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"aCreativeType"},{"kind":"text","text":" "},{"kind":"identifier","text":"dictionary:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSDictionary","text":"NSDictionary","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"aDict"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPProviderCreativeType\/title","value":"GFPProviderCreativeType","op":"replace"},{"value":[{"text":"GFPProviderCreativeType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPProviderCreativeType\/fragments"},{"op":"replace","value":[{"text":"GFPProviderCreativeType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPProviderCreativeType\/navigatorTitle"},{"value":"GFPEventExtraInfo","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPEventExtraInfo\/title"},{"op":"replace","value":[{"text":"GFPEventExtraInfo","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPEventExtraInfo\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"GFPEventExtraInfo"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPEventExtraInfo\/navigatorTitle"},{"op":"replace","value":"initWithCreativeType:dictionary:","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPEventExtraInfo~1init(creativeType:dictionary:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPEventExtraInfo~1init(creativeType:dictionary:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithCreativeType:dictionary:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}