{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeTitleInfo"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"dict"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"aDict"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"text":"], ","kind":"text"},{"text":"link","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"aLink","kind":"internalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeLinkInfo","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPNativeLinkInfo","text":"GFPNativeLinkInfo"},{"kind":"text","text":")"}]}],"kind":"declarations"}],"metadata":{"title":"init(dict:link:)","symbolKind":"init","modules":[{"name":"GFPSDK"}],"role":"symbol","externalID":"c:objc(cs)GFPNativeTitleInfo(im)initWithDict:link:","roleHeading":"Initializer","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"dict","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"], ","kind":"text"},{"text":"link","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPNativeLinkInfo","text":"GFPNativeLinkInfo"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"initWithDict:link:"}]},"sections":[],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpnativetitleinfo\/init(dict:link:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpnativetitleinfo\/init(dict:link:)"]}],"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeTitleInfo\/init(dict:link:)","interfaceLanguage":"swift"},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeTitleInfo":{"navigatorTitle":[{"text":"GFPNativeTitleInfo","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeTitleInfo","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"GFPNativeTitleInfo","kind":"identifier"}],"title":"GFPNativeTitleInfo","abstract":[],"kind":"symbol","type":"topic","url":"\/documentation\/gfpsdk\/gfpnativetitleinfo"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeTitleInfo/init(dict:link:)":{"navigatorTitle":[{"text":"initWithDict:link:","kind":"identifier"}],"title":"init(dict:link:)","url":"\/documentation\/gfpsdk\/gfpnativetitleinfo\/init(dict:link:)","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeTitleInfo\/init(dict:link:)","role":"symbol","type":"topic","kind":"symbol","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"dict","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"link"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"GFPNativeLinkInfo","preciseIdentifier":"c:objc(cs)GFPNativeLinkInfo"},{"text":")","kind":"text"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeLinkInfo":{"navigatorTitle":[{"text":"GFPNativeLinkInfo","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeLinkInfo","title":"GFPNativeLinkInfo","type":"topic","url":"\/documentation\/gfpsdk\/gfpnativelinkinfo","abstract":[],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPNativeLinkInfo"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"initWithDict:link:","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithDict:link:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithDict:"},{"text":"(","kind":"text"},{"text":"NSDictionary","preciseIdentifier":"c:objc(cs)NSDictionary","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"aDict"},{"text":" ","kind":"text"},{"kind":"identifier","text":"link:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPNativeLinkInfo","text":"GFPNativeLinkInfo","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeLinkInfo","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"aLink","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"GFPNativeTitleInfo","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeTitleInfo\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeTitleInfo\/fragments","value":[{"text":"GFPNativeTitleInfo","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeTitleInfo\/navigatorTitle","value":[{"kind":"identifier","text":"GFPNativeTitleInfo"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeTitleInfo~1init(dict:link:)\/title","value":"initWithDict:link:","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeTitleInfo~1init(dict:link:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithDict:link:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeLinkInfo\/title","op":"replace","value":"GFPNativeLinkInfo"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeLinkInfo\/fragments","value":[{"text":"GFPNativeLinkInfo","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"GFPNativeLinkInfo"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeLinkInfo\/navigatorTitle"}]}]}