{"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdManager"]]},"abstract":[{"type":"text","text":"GFPSDK 설정"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"setAdConfiguration"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"sdkConfig","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdConfiguration","text":"GFPAdConfiguration","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdConfiguration"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"role":"symbol","modules":[{"name":"GFPSDK"}],"externalID":"c:objc(cs)GFPAdManager(cm)setAdConfiguration:","symbolKind":"method","title":"setAdConfiguration(_:)","navigatorTitle":[{"text":"setAdConfiguration:","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setAdConfiguration"},{"text":"(","kind":"text"},{"text":"GFPAdConfiguration","preciseIdentifier":"c:objc(cs)GFPAdConfiguration","kind":"typeIdentifier"},{"kind":"text","text":")"}],"roleHeading":"Type Method"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpadmanager\/setadconfiguration(_:)"]},{"paths":["\/documentation\/gfpsdk\/gfpadmanager\/setadconfiguration(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdManager\/setAdConfiguration(_:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdConfiguration":{"type":"topic","url":"\/documentation\/gfpsdk\/gfpadconfiguration","role":"symbol","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPAdConfiguration","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdConfiguration","title":"GFPAdConfiguration","navigatorTitle":[{"text":"GFPAdConfiguration","kind":"identifier"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdManager":{"abstract":[],"kind":"symbol","title":"GFPAdManager","navigatorTitle":[{"text":"GFPAdManager","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdManager","url":"\/documentation\/gfpsdk\/gfpadmanager","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPAdManager","kind":"identifier"}],"role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdManager/setAdConfiguration(_:)":{"type":"topic","url":"\/documentation\/gfpsdk\/gfpadmanager\/setadconfiguration(_:)","kind":"symbol","abstract":[{"type":"text","text":"GFPSDK 설정"}],"navigatorTitle":[{"kind":"identifier","text":"setAdConfiguration:"}],"role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdManager\/setAdConfiguration(_:)","title":"setAdConfiguration(_:)","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setAdConfiguration"},{"text":"(","kind":"text"},{"text":"GFPAdConfiguration","preciseIdentifier":"c:objc(cs)GFPAdConfiguration","kind":"typeIdentifier"},{"kind":"text","text":")"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Type Method","path":"\/metadata\/roleHeading"},{"value":"setAdConfiguration:","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"setAdConfiguration:"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"setAdConfiguration:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPAdConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdConfiguration","text":"GFPAdConfiguration"},{"kind":"text","text":" *) "},{"text":"sdkConfig","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdConfiguration\/title","value":"GFPAdConfiguration","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdConfiguration\/fragments","value":[{"kind":"identifier","text":"GFPAdConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdConfiguration\/navigatorTitle","value":[{"text":"GFPAdConfiguration","kind":"identifier"}]},{"op":"replace","value":"GFPAdManager","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdManager\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdManager\/fragments","value":[{"kind":"identifier","text":"GFPAdManager"}]},{"op":"replace","value":[{"text":"GFPAdManager","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdManager\/navigatorTitle"},{"value":"setAdConfiguration:","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdManager~1setAdConfiguration(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdManager~1setAdConfiguration(_:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"setAdConfiguration:","kind":"identifier"}]}]}]}