{"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdManager"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdManager\/setup(withPublisherCd:target:configuration:completionHandler:)"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpadmanager\/setup(withpublishercd:target:configuration:completionhandler:)"]},{"paths":["\/documentation\/gfpsdk\/gfpadmanager\/setup(withpublishercd:target:configuration:completionhandler:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"metadata":{"role":"symbol","modules":[{"name":"GFPSDK"}],"externalID":"c:objc(cs)GFPAdManager(cm)setupWithPublisherCd:target:configuration:completionHandler:","symbolKind":"method","title":"setup(withPublisherCd:target:configuration:completionHandler:)","navigatorTitle":[{"text":"setupWithPublisherCd:target:configuration:completionHandler:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setup","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withPublisherCd","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"text":"target","kind":"externalParam"},{"text":": (any ","kind":"text"},{"kind":"typeIdentifier","text":"GFPAdManagerDelegate","preciseIdentifier":"c:objc(pl)GFPAdManagerDelegate"},{"text":")?, ","kind":"text"},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdConfiguration","text":"GFPAdConfiguration"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"text":"GFPAdManagerCompletionHandler","kind":"typeIdentifier","preciseIdentifier":"c:GFPAdManager.h@T@GFPAdManagerCompletionHandler"},{"text":")","kind":"text"}],"roleHeading":"Type Method"},"abstract":[{"text":"광고 매니저를 초기화 합니다.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"GFP를 통해 광고를 받아올 광고 provider 등록할 필요 없이, cocoapods 등록한 provider 별로 초기화가 이루어 집니다."},{"type":"text","text":" "},{"text":"provider에 따라 초기화에 시간이 오래 걸릴 수 있으므로 어플리케이션 로드시점 한번만 호출해주시면 됩니다. (eg. IMA는 구글 문서기준 약 1~2초 소요)","type":"text"},{"type":"text","text":" "},{"type":"text","text":"여기서 초기화되지 않은 provider로 부터의 광고는 이후 서버로부터의 응답결과와 관계없이 처리되지 않습니다."},{"text":" ","type":"text"},{"type":"text","text":"오류결과는 completionHandler의 error 에서 확인해 주세요."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setup","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withPublisherCd"},{"text":" ","kind":"text"},{"text":"publisherCd","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"target","kind":"externalParam"},{"kind":"text","text":": (any "},{"kind":"typeIdentifier","text":"GFPAdManagerDelegate","preciseIdentifier":"c:objc(pl)GFPAdManagerDelegate","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdManagerDelegate"},{"kind":"text","text":")?, "},{"kind":"externalParam","text":"configuration"},{"text":": ","kind":"text"},{"text":"GFPAdConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdConfiguration","preciseIdentifier":"c:objc(cs)GFPAdConfiguration"},{"text":"?, ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"keyword"},{"kind":"text","text":" "},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdManagerCompletionHandler","kind":"typeIdentifier","preciseIdentifier":"c:GFPAdManager.h@T@GFPAdManagerCompletionHandler","text":"GFPAdManagerCompletionHandler"},{"text":")","kind":"text"}],"platforms":["iOS"]},{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setup"},{"kind":"text","text":"("},{"text":"withPublisherCd","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"publisherCd"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"target"},{"kind":"text","text":": (any "},{"text":"GFPAdManagerDelegate","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdManagerDelegate","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)GFPAdManagerDelegate"},{"kind":"text","text":")?, "},{"text":"configuration","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)GFPAdConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdConfiguration","text":"GFPAdConfiguration"},{"text":"?) ","kind":"text"},{"text":"async","kind":"keyword"},{"kind":"text","text":" -> "},{"preciseIdentifier":"c:@M@NaverAdsServices@objc(cs)GFPError","text":"GFPError","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"광고 퍼블리셔 Code","type":"text"}],"type":"paragraph"}],"name":"publisherCd"},{"content":[{"inlineContent":[{"type":"text","text":"Limited Ad Tracking 스테이터스 조회 Delegate"}],"type":"paragraph"}],"name":"target"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"광고 관련 설정 옵션"}]}],"name":"configuration"},{"name":"completionHandler","content":[{"type":"paragraph","inlineContent":[{"text":"초기화 결과 확인 handler","type":"text"}]}]}]}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdManager/setup(withPublisherCd:target:configuration:completionHandler:)":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setup"},{"kind":"text","text":"("},{"text":"withPublisherCd","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"target"},{"kind":"text","text":": (any "},{"text":"GFPAdManagerDelegate","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)GFPAdManagerDelegate"},{"kind":"text","text":")?, "},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"text":"GFPAdConfiguration","preciseIdentifier":"c:objc(cs)GFPAdConfiguration","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"completionHandler","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"GFPAdManagerCompletionHandler","kind":"typeIdentifier","preciseIdentifier":"c:GFPAdManager.h@T@GFPAdManagerCompletionHandler"},{"kind":"text","text":")"}],"url":"\/documentation\/gfpsdk\/gfpadmanager\/setup(withpublishercd:target:configuration:completionhandler:)","type":"topic","kind":"symbol","abstract":[{"text":"광고 매니저를 초기화 합니다.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"GFP를 통해 광고를 받아올 광고 provider 등록할 필요 없이, cocoapods 등록한 provider 별로 초기화가 이루어 집니다."},{"type":"text","text":" "},{"type":"text","text":"provider에 따라 초기화에 시간이 오래 걸릴 수 있으므로 어플리케이션 로드시점 한번만 호출해주시면 됩니다. (eg. IMA는 구글 문서기준 약 1~2초 소요)"},{"text":" ","type":"text"},{"type":"text","text":"여기서 초기화되지 않은 provider로 부터의 광고는 이후 서버로부터의 응답결과와 관계없이 처리되지 않습니다."},{"type":"text","text":" "},{"text":"오류결과는 completionHandler의 error 에서 확인해 주세요.","type":"text"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdManager\/setup(withPublisherCd:target:configuration:completionHandler:)","role":"symbol","navigatorTitle":[{"text":"setupWithPublisherCd:target:configuration:completionHandler:","kind":"identifier"}],"title":"setup(withPublisherCd:target:configuration:completionHandler:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdConfiguration":{"type":"topic","url":"\/documentation\/gfpsdk\/gfpadconfiguration","role":"symbol","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPAdConfiguration","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdConfiguration","title":"GFPAdConfiguration","navigatorTitle":[{"text":"GFPAdConfiguration","kind":"identifier"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdManagerDelegate":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdManagerDelegate","role":"symbol","abstract":[],"kind":"symbol","url":"\/documentation\/gfpsdk\/gfpadmanagerdelegate","type":"topic","title":"GFPAdManagerDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPAdManagerDelegate"}],"navigatorTitle":[{"text":"GFPAdManagerDelegate","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdManager":{"abstract":[],"kind":"symbol","title":"GFPAdManager","navigatorTitle":[{"text":"GFPAdManager","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdManager","url":"\/documentation\/gfpsdk\/gfpadmanager","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPAdManager","kind":"identifier"}],"role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdManagerCompletionHandler":{"type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdManagerCompletionHandler","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPAdManagerCompletionHandler"}],"abstract":[],"title":"GFPAdManagerCompletionHandler","navigatorTitle":[{"text":"GFPAdManagerCompletionHandler","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/gfpsdk\/gfpadmanagercompletionhandler"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"value":"setupWithPublisherCd:target:configuration:completionHandler:","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"setupWithPublisherCd:target:configuration:completionHandler:"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"setupWithPublisherCd:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"publisherCd","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"target:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id<GFPAdManagerDelegate>","preciseIdentifier":"c:Qoobjc(pl)GFPAdManagerDelegate","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"target"},{"text":" ","kind":"text"},{"text":"configuration:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)GFPAdConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdConfiguration","text":"GFPAdConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"configuration"},{"text":" ","kind":"text"},{"kind":"identifier","text":"completionHandler:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:BFv(#*$@M@NaverAdsServices@objc(cs)GFPError)","kind":"typeIdentifier","text":"void (^)(GFPError *)"},{"kind":"text","text":") "},{"kind":"internalParam","text":"completionHandler"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"parameters":[{"name":"publisherCd","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"광고 퍼블리셔 Code"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Limited Ad Tracking 스테이터스 조회 Delegate"}]}],"name":"target"},{"name":"configuration","content":[{"type":"paragraph","inlineContent":[{"text":"광고 관련 설정 옵션","type":"text"}]}]},{"name":"completionHandler","content":[{"inlineContent":[{"text":"초기화 결과 확인 handler","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},"op":"replace","path":"\/primaryContentSections\/1"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdManager~1setup(withPublisherCd:target:configuration:completionHandler:)\/title","op":"replace","value":"setupWithPublisherCd:target:configuration:completionHandler:"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"setupWithPublisherCd:target:configuration:completionHandler:"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdManager~1setup(withPublisherCd:target:configuration:completionHandler:)\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdConfiguration\/title","op":"replace","value":"GFPAdConfiguration"},{"value":[{"kind":"identifier","text":"GFPAdConfiguration"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdConfiguration\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"GFPAdConfiguration"}]},{"value":"GFPAdManagerDelegate","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdManagerDelegate\/title","op":"replace"},{"value":[{"kind":"identifier","text":"GFPAdManagerDelegate"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdManagerDelegate\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdManagerDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"GFPAdManagerDelegate"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdManager\/title","value":"GFPAdManager","op":"replace"},{"value":[{"kind":"identifier","text":"GFPAdManager"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdManager\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdManager\/navigatorTitle","value":[{"text":"GFPAdManager","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdManagerCompletionHandler\/title","value":"GFPAdManagerCompletionHandler"},{"value":[{"text":"GFPAdManagerCompletionHandler","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdManagerCompletionHandler\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdManagerCompletionHandler\/navigatorTitle","value":[{"text":"GFPAdManagerCompletionHandler","kind":"identifier"}]}]}]}