{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"setup","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withPublisherCd","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"publisherCd","kind":"internalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"serviceCd","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"target","kind":"externalParam"},{"kind":"text","text":": (any "},{"text":"GFPAdManagerDelegate","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdManagerDelegate","preciseIdentifier":"c:objc(pl)GFPAdManagerDelegate","kind":"typeIdentifier"},{"kind":"text","text":")?, "},{"kind":"externalParam","text":"configuration"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdConfiguration","text":"GFPAdConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdConfiguration"},{"text":"?, ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"kind":"text","text":": "},{"text":"@escaping","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPAdManagerCompletionHandler","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdManagerCompletionHandler","preciseIdentifier":"c:GFPAdManager.h@T@GFPAdManagerCompletionHandler"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]},{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setup"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"withPublisherCd"},{"kind":"text","text":" "},{"text":"publisherCd","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"text":"serviceCd","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"text":"target","kind":"externalParam"},{"kind":"text","text":": (any "},{"preciseIdentifier":"c:objc(pl)GFPAdManagerDelegate","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdManagerDelegate","kind":"typeIdentifier","text":"GFPAdManagerDelegate"},{"kind":"text","text":")?, "},{"text":"configuration","kind":"externalParam"},{"kind":"text","text":": "},{"text":"GFPAdConfiguration","preciseIdentifier":"c:objc(cs)GFPAdConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdConfiguration"},{"text":"?) ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@NaverAdsServices@objc(cs)GFPError","text":"GFPError"},{"kind":"text","text":"?"}]}],"kind":"declarations"},{"parameters":[{"name":"publisherCd","content":[{"type":"paragraph","inlineContent":[{"text":"광고 퍼블리셔 Code","type":"text"}]}]},{"name":"serviceCd","content":[{"inlineContent":[{"text":"발급 받은 Service Code (optional)","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Limited Ad Tracking 스테이터스 조회 Delegate"}]}],"name":"target"},{"name":"configuration","content":[{"inlineContent":[{"type":"text","text":"광고 관련 설정 옵션"}],"type":"paragraph"}]},{"name":"completionHandler","content":[{"type":"paragraph","inlineContent":[{"text":"초기화 결과 확인 handler","type":"text"}]}]}],"kind":"parameters"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdManager"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpadmanager\/setup(withpublishercd:servicecd:target:configuration:completionhandler:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpadmanager\/setup(withpublishercd:servicecd:target:configuration:completionhandler:)"]}],"metadata":{"navigatorTitle":[{"text":"setupWithPublisherCd:serviceCd:target:configuration:completionHandler:","kind":"identifier"}],"externalID":"c:objc(cs)GFPAdManager(cm)setupWithPublisherCd:serviceCd:target:configuration:completionHandler:","symbolKind":"method","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"setup"},{"text":"(","kind":"text"},{"text":"withPublisherCd","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"serviceCd"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"target"},{"text":": (any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)GFPAdManagerDelegate","text":"GFPAdManagerDelegate"},{"kind":"text","text":")?, "},{"text":"configuration","kind":"externalParam"},{"kind":"text","text":": "},{"text":"GFPAdConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdConfiguration"},{"text":"?, ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:GFPAdManager.h@T@GFPAdManagerCompletionHandler","kind":"typeIdentifier","text":"GFPAdManagerCompletionHandler"},{"kind":"text","text":")"}],"modules":[{"name":"GFPSDK"}],"role":"symbol","roleHeading":"Type Method","title":"setup(withPublisherCd:serviceCd:target:configuration:completionHandler:)"},"sections":[],"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdManager\/setup(withPublisherCd:serviceCd:target:configuration:completionHandler:)","interfaceLanguage":"swift"},"abstract":[{"text":"광고 매니저를 초기화 합니다.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"GFP를 통해 광고를 받아올 광고 provider 등록할 필요 없이, cocoapods 등록한 provider 별로 초기화가 이루어 집니다."},{"text":" ","type":"text"},{"type":"text","text":"provider에 따라 초기화에 시간이 오래 걸릴 수 있으므로 어플리케이션 로드시점 한번만 호출해주시면 됩니다. (eg. IMA는 구글 문서기준 약 1~2초 소요)"},{"type":"text","text":" "},{"text":"여기서 초기화되지 않은 provider로 부터의 광고는 이후 서버로부터의 응답결과와 관계없이 처리되지 않습니다.","type":"text"},{"type":"text","text":" "},{"text":"오류결과는 completionHandler의 error 에서 확인해 주세요.","type":"text"}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdManagerDelegate":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdManagerDelegate","role":"symbol","abstract":[],"kind":"symbol","url":"\/documentation\/gfpsdk\/gfpadmanagerdelegate","type":"topic","title":"GFPAdManagerDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPAdManagerDelegate"}],"navigatorTitle":[{"text":"GFPAdManagerDelegate","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdManagerCompletionHandler":{"type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdManagerCompletionHandler","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPAdManagerCompletionHandler"}],"abstract":[],"title":"GFPAdManagerCompletionHandler","navigatorTitle":[{"text":"GFPAdManagerCompletionHandler","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/gfpsdk\/gfpadmanagercompletionhandler"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdManager/setup(withPublisherCd:serviceCd:target:configuration:completionHandler:)":{"type":"topic","url":"\/documentation\/gfpsdk\/gfpadmanager\/setup(withpublishercd:servicecd:target:configuration:completionhandler:)","abstract":[{"text":"광고 매니저를 초기화 합니다.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"GFP를 통해 광고를 받아올 광고 provider 등록할 필요 없이, cocoapods 등록한 provider 별로 초기화가 이루어 집니다."},{"text":" ","type":"text"},{"type":"text","text":"provider에 따라 초기화에 시간이 오래 걸릴 수 있으므로 어플리케이션 로드시점 한번만 호출해주시면 됩니다. (eg. IMA는 구글 문서기준 약 1~2초 소요)"},{"text":" ","type":"text"},{"type":"text","text":"여기서 초기화되지 않은 provider로 부터의 광고는 이후 서버로부터의 응답결과와 관계없이 처리되지 않습니다."},{"type":"text","text":" "},{"text":"오류결과는 completionHandler의 error 에서 확인해 주세요.","type":"text"}],"title":"setup(withPublisherCd:serviceCd:target:configuration:completionHandler:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"setupWithPublisherCd:serviceCd:target:configuration:completionHandler:"}],"role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdManager\/setup(withPublisherCd:serviceCd:target:configuration:completionHandler:)","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setup","kind":"identifier"},{"kind":"text","text":"("},{"text":"withPublisherCd","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"text":"serviceCd","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"target","kind":"externalParam"},{"kind":"text","text":": (any "},{"preciseIdentifier":"c:objc(pl)GFPAdManagerDelegate","text":"GFPAdManagerDelegate","kind":"typeIdentifier"},{"kind":"text","text":")?, "},{"kind":"externalParam","text":"configuration"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"GFPAdConfiguration","preciseIdentifier":"c:objc(cs)GFPAdConfiguration"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GFPAdManagerCompletionHandler","preciseIdentifier":"c:GFPAdManager.h@T@GFPAdManagerCompletionHandler"},{"kind":"text","text":")"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdManager":{"abstract":[],"kind":"symbol","title":"GFPAdManager","navigatorTitle":[{"text":"GFPAdManager","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdManager","url":"\/documentation\/gfpsdk\/gfpadmanager","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPAdManager","kind":"identifier"}],"role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdConfiguration":{"type":"topic","url":"\/documentation\/gfpsdk\/gfpadconfiguration","role":"symbol","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPAdConfiguration","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdConfiguration","title":"GFPAdConfiguration","navigatorTitle":[{"text":"GFPAdConfiguration","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"setupWithPublisherCd:serviceCd:target:configuration:completionHandler:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"setupWithPublisherCd:serviceCd:target:configuration:completionHandler:"}],"path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"text":"setupWithPublisherCd:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"publisherCd"},{"kind":"text","text":" "},{"text":"serviceCd:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"serviceCd"},{"text":" ","kind":"text"},{"kind":"identifier","text":"target:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Qoobjc(pl)GFPAdManagerDelegate","text":"id<GFPAdManagerDelegate>","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"target","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"configuration:"},{"kind":"text","text":"("},{"text":"GFPAdConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdConfiguration","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdConfiguration"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"configuration"},{"text":" ","kind":"text"},{"text":"completionHandler:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:BFv(#*$@M@NaverAdsServices@objc(cs)GFPError)","text":"void (^)(GFPError *)","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"completionHandler"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"광고 퍼블리셔 Code"}]}],"name":"publisherCd"},{"name":"serviceCd","content":[{"inlineContent":[{"type":"text","text":"발급 받은 Service Code (optional)"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Limited Ad Tracking 스테이터스 조회 Delegate"}],"type":"paragraph"}],"name":"target"},{"name":"configuration","content":[{"inlineContent":[{"type":"text","text":"광고 관련 설정 옵션"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"초기화 결과 확인 handler"}],"type":"paragraph"}],"name":"completionHandler"}],"kind":"parameters"}},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdManagerDelegate\/title","op":"replace","value":"GFPAdManagerDelegate"},{"value":[{"text":"GFPAdManagerDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdManagerDelegate\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"GFPAdManagerDelegate"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdManagerDelegate\/navigatorTitle"},{"value":"GFPAdManagerCompletionHandler","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdManagerCompletionHandler\/title"},{"value":[{"text":"GFPAdManagerCompletionHandler","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdManagerCompletionHandler\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdManagerCompletionHandler\/navigatorTitle","value":[{"text":"GFPAdManagerCompletionHandler","kind":"identifier"}]},{"op":"replace","value":"setupWithPublisherCd:serviceCd:target:configuration:completionHandler:","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdManager~1setup(withPublisherCd:serviceCd:target:configuration:completionHandler:)\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdManager~1setup(withPublisherCd:serviceCd:target:configuration:completionHandler:)\/fragments","value":[{"kind":"text","text":"+ "},{"text":"setupWithPublisherCd:serviceCd:target:configuration:completionHandler:","kind":"identifier"}],"op":"replace"},{"value":"GFPAdManager","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdManager\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdManager\/fragments","value":[{"kind":"identifier","text":"GFPAdManager"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdManager\/navigatorTitle","value":[{"kind":"identifier","text":"GFPAdManager"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdConfiguration\/title","value":"GFPAdConfiguration"},{"value":[{"text":"GFPAdConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdConfiguration\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"GFPAdConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdConfiguration\/navigatorTitle"}]}]}