{"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","variants":[{"paths":["\/documentation\/gfpsdk\/gfpadmanager\/setup(withpublishercd:target:completionhandler:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpadmanager\/setup(withpublishercd:target:completionhandler:)"]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"setupWithPublisherCd:target:completionHandler:"}],"modules":[{"name":"GFPSDK"}],"title":"setup(withPublisherCd:target:completionHandler:)","role":"symbol","symbolKind":"method","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setup","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withPublisherCd","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"target","kind":"externalParam"},{"text":": (any ","kind":"text"},{"text":"GFPAdManagerDelegate","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)GFPAdManagerDelegate"},{"kind":"text","text":")?, "},{"text":"completionHandler","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:GFPAdManager.h@T@GFPAdManagerCompletionHandler","text":"GFPAdManagerCompletionHandler","kind":"typeIdentifier"},{"text":")","kind":"text"}],"roleHeading":"Type Method","externalID":"c:objc(cs)GFPAdManager(cm)setupWithPublisherCd:target:completionHandler:"},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setup"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"withPublisherCd"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"publisherCd"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"target","kind":"externalParam"},{"text":": (any ","kind":"text"},{"kind":"typeIdentifier","text":"GFPAdManagerDelegate","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdManagerDelegate","preciseIdentifier":"c:objc(pl)GFPAdManagerDelegate"},{"text":")?, ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"keyword","text":"@escaping"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:GFPAdManager.h@T@GFPAdManagerCompletionHandler","text":"GFPAdManagerCompletionHandler","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdManagerCompletionHandler"},{"text":")","kind":"text"}]},{"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setup","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withPublisherCd","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"publisherCd","kind":"internalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"target"},{"text":": (any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)GFPAdManagerDelegate","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdManagerDelegate","text":"GFPAdManagerDelegate"},{"text":")?) ","kind":"text"},{"kind":"keyword","text":"async"},{"text":" -> ","kind":"text"},{"text":"GFPError","kind":"typeIdentifier","preciseIdentifier":"c:@M@NaverAdsServices@objc(cs)GFPError"},{"text":"?","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"publisherCd","content":[{"inlineContent":[{"text":"광고 퍼블리셔 Code","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Limited Ad Tracking 스테이터스 조회 Delegate"}]}],"name":"target"},{"content":[{"inlineContent":[{"text":"초기화 결과 확인 handler","type":"text"}],"type":"paragraph"}],"name":"completionHandler"}]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdManager"]]},"abstract":[{"type":"text","text":"광고 매니저를 초기화 합니다."},{"text":" ","type":"text"},{"type":"text","text":"GFP를 통해 광고를 받아올 광고 provider 등록할 필요 없이, cocoapods 등록한 provider 별로 초기화가 이루어 집니다."},{"text":" ","type":"text"},{"type":"text","text":"provider에 따라 초기화에 시간이 오래 걸릴 수 있으므로 어플리케이션 로드시점 한번만 호출해주시면 됩니다. (eg. IMA는 구글 문서기준 약 1~2초 소요)"},{"type":"text","text":" "},{"text":"여기서 초기화되지 않은 provider로 부터의 광고는 이후 서버로부터의 응답결과와 관계없이 처리되지 않습니다.","type":"text"},{"type":"text","text":" "},{"text":"오류결과는 completionHandler의 error 에서 확인해 주세요.","type":"text"}],"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdManager\/setup(withPublisherCd:target:completionHandler:)","interfaceLanguage":"swift"},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdManagerCompletionHandler":{"type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdManagerCompletionHandler","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPAdManagerCompletionHandler"}],"abstract":[],"title":"GFPAdManagerCompletionHandler","navigatorTitle":[{"text":"GFPAdManagerCompletionHandler","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/gfpsdk\/gfpadmanagercompletionhandler"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdManager":{"abstract":[],"kind":"symbol","title":"GFPAdManager","navigatorTitle":[{"text":"GFPAdManager","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdManager","url":"\/documentation\/gfpsdk\/gfpadmanager","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPAdManager","kind":"identifier"}],"role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdManagerDelegate":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdManagerDelegate","role":"symbol","abstract":[],"kind":"symbol","url":"\/documentation\/gfpsdk\/gfpadmanagerdelegate","type":"topic","title":"GFPAdManagerDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPAdManagerDelegate"}],"navigatorTitle":[{"text":"GFPAdManagerDelegate","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdManager/setup(withPublisherCd:target:completionHandler:)":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setup"},{"text":"(","kind":"text"},{"text":"withPublisherCd","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?, ","kind":"text"},{"text":"target","kind":"externalParam"},{"kind":"text","text":": (any "},{"kind":"typeIdentifier","text":"GFPAdManagerDelegate","preciseIdentifier":"c:objc(pl)GFPAdManagerDelegate"},{"text":")?, ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:GFPAdManager.h@T@GFPAdManagerCompletionHandler","text":"GFPAdManagerCompletionHandler"},{"text":")","kind":"text"}],"url":"\/documentation\/gfpsdk\/gfpadmanager\/setup(withpublishercd:target:completionhandler:)","type":"topic","kind":"symbol","abstract":[{"text":"광고 매니저를 초기화 합니다.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"GFP를 통해 광고를 받아올 광고 provider 등록할 필요 없이, cocoapods 등록한 provider 별로 초기화가 이루어 집니다."},{"text":" ","type":"text"},{"type":"text","text":"provider에 따라 초기화에 시간이 오래 걸릴 수 있으므로 어플리케이션 로드시점 한번만 호출해주시면 됩니다. (eg. IMA는 구글 문서기준 약 1~2초 소요)"},{"text":" ","type":"text"},{"type":"text","text":"여기서 초기화되지 않은 provider로 부터의 광고는 이후 서버로부터의 응답결과와 관계없이 처리되지 않습니다."},{"type":"text","text":" "},{"text":"오류결과는 completionHandler의 error 에서 확인해 주세요.","type":"text"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdManager\/setup(withPublisherCd:target:completionHandler:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"setupWithPublisherCd:target:completionHandler:"}],"title":"setup(withPublisherCd:target:completionHandler:)"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"value":"setupWithPublisherCd:target:completionHandler:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"text":"setupWithPublisherCd:target:completionHandler:","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"setupWithPublisherCd:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"publisherCd"},{"text":" ","kind":"text"},{"text":"target:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<GFPAdManagerDelegate>","preciseIdentifier":"c:Qoobjc(pl)GFPAdManagerDelegate"},{"kind":"text","text":") "},{"text":"target","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"completionHandler:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:BFv(#*$@M@NaverAdsServices@objc(cs)GFPError)","text":"void (^)(GFPError *)"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"completionHandler"},{"text":";","kind":"text"}]}]},"op":"replace"},{"value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"광고 퍼블리셔 Code"}],"type":"paragraph"}],"name":"publisherCd"},{"content":[{"inlineContent":[{"text":"Limited Ad Tracking 스테이터스 조회 Delegate","type":"text"}],"type":"paragraph"}],"name":"target"},{"name":"completionHandler","content":[{"inlineContent":[{"type":"text","text":"초기화 결과 확인 handler"}],"type":"paragraph"}]}]},"op":"replace","path":"\/primaryContentSections\/1"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdManagerCompletionHandler\/title","op":"replace","value":"GFPAdManagerCompletionHandler"},{"value":[{"kind":"identifier","text":"GFPAdManagerCompletionHandler"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdManagerCompletionHandler\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdManagerCompletionHandler\/navigatorTitle","value":[{"kind":"identifier","text":"GFPAdManagerCompletionHandler"}]},{"value":"GFPAdManager","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdManager\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdManager\/fragments","value":[{"kind":"identifier","text":"GFPAdManager"}],"op":"replace"},{"op":"replace","value":[{"text":"GFPAdManager","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdManager\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdManagerDelegate\/title","value":"GFPAdManagerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdManagerDelegate\/fragments","value":[{"text":"GFPAdManagerDelegate","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"GFPAdManagerDelegate"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdManagerDelegate\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdManager~1setup(withPublisherCd:target:completionHandler:)\/title","value":"setupWithPublisherCd:target:completionHandler:"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"text":"setupWithPublisherCd:target:completionHandler:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdManager~1setup(withPublisherCd:target:completionHandler:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}