{"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdManager"]]},"variants":[{"paths":["\/documentation\/gfpsdk\/gfpadmanager\/setuserparam(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpadmanager\/setuserparam(_:)"]}],"sections":[],"metadata":{"externalID":"c:objc(cs)GFPAdManager(cm)setUserParam:","navigatorTitle":[{"kind":"identifier","text":"setUserParam:"}],"title":"setUserParam(_:)","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setUserParam","kind":"identifier"},{"text":"(","kind":"text"},{"text":"GFPUserParam","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPUserParam"},{"text":")","kind":"text"}],"symbolKind":"method","modules":[{"name":"GFPSDK"}],"role":"symbol","roleHeading":"Type Method"},"abstract":[{"type":"text","text":"유저 타겟 정보 설정"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdManager\/setUserParam(_:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"setUserParam","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"param"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPUserParam","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUserParam","text":"GFPUserParam"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdManager/setUserParam(_:)":{"role":"symbol","title":"setUserParam(_:)","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"setUserParam","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPUserParam","text":"GFPUserParam","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"setUserParam:"}],"abstract":[{"text":"유저 타겟 정보 설정","type":"text"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdManager\/setUserParam(_:)","type":"topic","url":"\/documentation\/gfpsdk\/gfpadmanager\/setuserparam(_:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPUserParam":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUserParam","url":"\/documentation\/gfpsdk\/gfpuserparam","title":"GFPUserParam","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPUserParam"}],"kind":"symbol","abstract":[],"role":"symbol","navigatorTitle":[{"text":"GFPUserParam","kind":"identifier"}],"type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdManager":{"abstract":[],"kind":"symbol","title":"GFPAdManager","navigatorTitle":[{"text":"GFPAdManager","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdManager","url":"\/documentation\/gfpsdk\/gfpadmanager","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPAdManager","kind":"identifier"}],"role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"setUserParam:"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"setUserParam:","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"setUserParam:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GFPUserParam","preciseIdentifier":"c:objc(cs)GFPUserParam","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUserParam"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"param"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace"},{"value":"setUserParam:","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdManager~1setUserParam(_:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdManager~1setUserParam(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"text":"setUserParam:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPUserParam\/title","value":"GFPUserParam"},{"value":[{"kind":"identifier","text":"GFPUserParam"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPUserParam\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"GFPUserParam"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPUserParam\/navigatorTitle","op":"replace"},{"value":"GFPAdManager","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdManager\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdManager\/fragments","value":[{"kind":"identifier","text":"GFPAdManager"}]},{"value":[{"text":"GFPAdManager","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdManager\/navigatorTitle","op":"replace"}]}]}