{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpadmanager\/setup(withpublishercd:servicecd:target:completionhandler:)"]},{"paths":["\/documentation\/gfpsdk\/gfpadmanager\/setup(withpublishercd:servicecd:target:completionhandler:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdManager"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"role":"symbol","symbolKind":"method","externalID":"c:objc(cs)GFPAdManager(cm)setupWithPublisherCd:serviceCd:target:completionHandler:","roleHeading":"Type Method","navigatorTitle":[{"kind":"identifier","text":"setupWithPublisherCd:serviceCd:target:completionHandler:"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setup","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"withPublisherCd"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"serviceCd"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"target"},{"kind":"text","text":": (any "},{"text":"GFPAdManagerDelegate","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)GFPAdManagerDelegate"},{"text":")?, ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:GFPAdManager.h@T@GFPAdManagerCompletionHandler","text":"GFPAdManagerCompletionHandler"},{"kind":"text","text":")"}],"modules":[{"name":"GFPSDK"}],"title":"setup(withPublisherCd:serviceCd:target:completionHandler:)"},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdManager\/setup(withPublisherCd:serviceCd:target:completionHandler:)","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"type":"text","text":"광고 매니저를 초기화 합니다."},{"type":"text","text":" "},{"text":"GFP를 통해 광고를 받아올 광고 provider 등록할 필요 없이, cocoapods 등록한 provider 별로 초기화가 이루어 집니다.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"provider에 따라 초기화에 시간이 오래 걸릴 수 있으므로 어플리케이션 로드시점 한번만 호출해주시면 됩니다. (eg. IMA는 구글 문서기준 약 1~2초 소요)"},{"type":"text","text":" "},{"text":"여기서 초기화되지 않은 provider로 부터의 광고는 이후 서버로부터의 응답결과와 관계없이 처리되지 않습니다.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"오류결과는 completionHandler의 error 에서 확인해 주세요."}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"setup"},{"text":"(","kind":"text"},{"text":"withPublisherCd","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"publisherCd"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?, ","kind":"text"},{"text":"serviceCd","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"text":"target","kind":"externalParam"},{"text":": (any ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdManagerDelegate","text":"GFPAdManagerDelegate","preciseIdentifier":"c:objc(pl)GFPAdManagerDelegate"},{"kind":"text","text":")?, "},{"text":"completionHandler","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdManagerCompletionHandler","text":"GFPAdManagerCompletionHandler","kind":"typeIdentifier","preciseIdentifier":"c:GFPAdManager.h@T@GFPAdManagerCompletionHandler"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]},{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setup"},{"text":"(","kind":"text"},{"text":"withPublisherCd","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"publisherCd"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"serviceCd"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"target"},{"text":": (any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)GFPAdManagerDelegate","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdManagerDelegate","text":"GFPAdManagerDelegate"},{"kind":"text","text":")?) "},{"kind":"keyword","text":"async"},{"text":" -> ","kind":"text"},{"text":"GFPError","kind":"typeIdentifier","preciseIdentifier":"c:@M@NaverAdsServices@objc(cs)GFPError"},{"text":"?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"name":"publisherCd","content":[{"inlineContent":[{"type":"text","text":"광고 퍼블리셔 Code"}],"type":"paragraph"}]},{"name":"serviceCd","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"발급 받은 Service Code (optional)"}]}]},{"name":"target","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Limited Ad Tracking 스테이터스 조회 Delegate"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"초기화 결과 확인 handler"}]}],"name":"completionHandler"}],"kind":"parameters"}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdManager":{"abstract":[],"kind":"symbol","title":"GFPAdManager","navigatorTitle":[{"text":"GFPAdManager","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdManager","url":"\/documentation\/gfpsdk\/gfpadmanager","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPAdManager","kind":"identifier"}],"role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdManagerCompletionHandler":{"type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdManagerCompletionHandler","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPAdManagerCompletionHandler"}],"abstract":[],"title":"GFPAdManagerCompletionHandler","navigatorTitle":[{"text":"GFPAdManagerCompletionHandler","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/gfpsdk\/gfpadmanagercompletionhandler"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdManagerDelegate":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdManagerDelegate","role":"symbol","abstract":[],"kind":"symbol","url":"\/documentation\/gfpsdk\/gfpadmanagerdelegate","type":"topic","title":"GFPAdManagerDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPAdManagerDelegate"}],"navigatorTitle":[{"text":"GFPAdManagerDelegate","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdManager/setup(withPublisherCd:serviceCd:target:completionHandler:)":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setup","kind":"identifier"},{"kind":"text","text":"("},{"text":"withPublisherCd","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"serviceCd"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"target"},{"text":": (any ","kind":"text"},{"text":"GFPAdManagerDelegate","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)GFPAdManagerDelegate"},{"text":")?, ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:GFPAdManager.h@T@GFPAdManagerCompletionHandler","text":"GFPAdManagerCompletionHandler","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","url":"\/documentation\/gfpsdk\/gfpadmanager\/setup(withpublishercd:servicecd:target:completionhandler:)","abstract":[{"text":"광고 매니저를 초기화 합니다.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"GFP를 통해 광고를 받아올 광고 provider 등록할 필요 없이, cocoapods 등록한 provider 별로 초기화가 이루어 집니다."},{"type":"text","text":" "},{"text":"provider에 따라 초기화에 시간이 오래 걸릴 수 있으므로 어플리케이션 로드시점 한번만 호출해주시면 됩니다. (eg. IMA는 구글 문서기준 약 1~2초 소요)","type":"text"},{"type":"text","text":" "},{"type":"text","text":"여기서 초기화되지 않은 provider로 부터의 광고는 이후 서버로부터의 응답결과와 관계없이 처리되지 않습니다."},{"type":"text","text":" "},{"type":"text","text":"오류결과는 completionHandler의 error 에서 확인해 주세요."}],"role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdManager\/setup(withPublisherCd:serviceCd:target:completionHandler:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"setupWithPublisherCd:serviceCd:target:completionHandler:"}],"title":"setup(withPublisherCd:serviceCd:target:completionHandler:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Type Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"setupWithPublisherCd:serviceCd:target:completionHandler:","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"setupWithPublisherCd:serviceCd:target:completionHandler:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"setupWithPublisherCd:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"publisherCd","kind":"internalParam"},{"kind":"text","text":" "},{"text":"serviceCd:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"serviceCd","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"target:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Qoobjc(pl)GFPAdManagerDelegate","text":"id<GFPAdManagerDelegate>","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"target"},{"kind":"text","text":" "},{"kind":"identifier","text":"completionHandler:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:BFv(#*$@M@NaverAdsServices@objc(cs)GFPError)","text":"void (^)(GFPError *)"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"completionHandler"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"value":{"parameters":[{"name":"publisherCd","content":[{"inlineContent":[{"type":"text","text":"광고 퍼블리셔 Code"}],"type":"paragraph"}]},{"name":"serviceCd","content":[{"inlineContent":[{"text":"발급 받은 Service Code (optional)","type":"text"}],"type":"paragraph"}]},{"name":"target","content":[{"inlineContent":[{"type":"text","text":"Limited Ad Tracking 스테이터스 조회 Delegate"}],"type":"paragraph"}]},{"name":"completionHandler","content":[{"inlineContent":[{"text":"초기화 결과 확인 handler","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},"op":"replace","path":"\/primaryContentSections\/1"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdManager\/title","value":"GFPAdManager","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdManager\/fragments","value":[{"kind":"identifier","text":"GFPAdManager"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdManager\/navigatorTitle","value":[{"text":"GFPAdManager","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdManagerCompletionHandler\/title","value":"GFPAdManagerCompletionHandler","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdManagerCompletionHandler\/fragments","value":[{"kind":"identifier","text":"GFPAdManagerCompletionHandler"}],"op":"replace"},{"value":[{"kind":"identifier","text":"GFPAdManagerCompletionHandler"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdManagerCompletionHandler\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdManagerDelegate\/title","value":"GFPAdManagerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdManagerDelegate\/fragments","value":[{"text":"GFPAdManagerDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdManagerDelegate\/navigatorTitle","value":[{"text":"GFPAdManagerDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdManager~1setup(withPublisherCd:serviceCd:target:completionHandler:)\/title","value":"setupWithPublisherCd:serviceCd:target:completionHandler:"},{"value":[{"text":"+ ","kind":"text"},{"text":"setupWithPublisherCd:serviceCd:target:completionHandler:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdManager~1setup(withPublisherCd:serviceCd:target:completionHandler:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}