{"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdDelegate"]]},"variants":[{"paths":["\/documentation\/gfpsdk\/gfpinterstitialaddelegate\/interstitialadrecieveimpression(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gfpsdk\/gfpinterstitialaddelegate\/interstitialadrecieveimpression(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"interstitialAdRecieveImpression"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"interstitialAd","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPInterstitialAd","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAd","kind":"typeIdentifier","text":"GFPInterstitialAd"},{"kind":"text","text":"!)"}]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdDelegate\/interstitialAdRecieveImpression(_:)"},"sections":[],"metadata":{"symbolKind":"method","required":true,"role":"symbol","modules":[{"name":"GFPSDK"}],"title":"interstitialAdRecieveImpression(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"interstitialAdRecieveImpression","kind":"identifier"},{"kind":"text","text":"("},{"text":"GFPInterstitialAd","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPInterstitialAd"},{"text":"!)","kind":"text"}],"externalID":"c:objc(pl)GFPInterstitialAdDelegate(im)interstitialAdRecieveImpression:","navigatorTitle":[{"kind":"identifier","text":"interstitialAdRecieveImpression:"}],"roleHeading":"Instance Method"},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPInterstitialAd":{"navigatorTitle":[{"text":"GFPInterstitialAd","kind":"identifier"}],"abstract":[],"url":"\/documentation\/gfpsdk\/gfpinterstitialad","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAd","type":"topic","kind":"symbol","title":"GFPInterstitialAd","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPInterstitialAd"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPInterstitialAdDelegate/interstitialAdRecieveImpression(_:)":{"role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdDelegate\/interstitialAdRecieveImpression(_:)","type":"topic","abstract":[],"url":"\/documentation\/gfpsdk\/gfpinterstitialaddelegate\/interstitialadrecieveimpression(_:)","title":"interstitialAdRecieveImpression(_:)","navigatorTitle":[{"text":"interstitialAdRecieveImpression:","kind":"identifier"}],"required":true,"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"interstitialAdRecieveImpression"},{"text":"(","kind":"text"},{"text":"GFPInterstitialAd","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPInterstitialAd"},{"kind":"text","text":"!)"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPInterstitialAdDelegate":{"navigatorTitle":[{"kind":"identifier","text":"GFPInterstitialAdDelegate"}],"role":"symbol","kind":"symbol","abstract":[],"url":"\/documentation\/gfpsdk\/gfpinterstitialaddelegate","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"GFPInterstitialAdDelegate","kind":"identifier"}],"title":"GFPInterstitialAdDelegate"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"interstitialAdRecieveImpression:","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"interstitialAdRecieveImpression:","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"interstitialAdRecieveImpression:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPInterstitialAd","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAd","kind":"typeIdentifier","text":"GFPInterstitialAd"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"interstitialAd"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAd\/title","value":"GFPInterstitialAd"},{"op":"replace","value":[{"kind":"identifier","text":"GFPInterstitialAd"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAd\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"GFPInterstitialAd"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAd\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdDelegate~1interstitialAdRecieveImpression(_:)\/title","value":"interstitialAdRecieveImpression:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"interstitialAdRecieveImpression:"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdDelegate~1interstitialAdRecieveImpression(_:)\/fragments"},{"op":"replace","value":"GFPInterstitialAdDelegate","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdDelegate\/title"},{"value":[{"text":"GFPInterstitialAdDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdDelegate\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"GFPInterstitialAdDelegate"}]}]}]}