{"metadata":{"role":"symbol","modules":[{"name":"GFPSDK"}],"externalID":"c:objc(pl)GFPInterstitialAdDelegate(im)interstitialAd:didFailedWithError:","symbolKind":"method","title":"interstitialAd(_:didFailedWithError:)","navigatorTitle":[{"kind":"identifier","text":"interstitialAd:didFailedWithError:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"interstitialAd"},{"text":"(","kind":"text"},{"text":"GFPInterstitialAd","preciseIdentifier":"c:objc(cs)GFPInterstitialAd","kind":"typeIdentifier"},{"text":"!, ","kind":"text"},{"text":"didFailedWithError","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"GFPError","preciseIdentifier":"c:@M@NaverAdsServices@objc(cs)GFPError","kind":"typeIdentifier"},{"text":"!)","kind":"text"}],"roleHeading":"Instance Method","required":true},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"interstitialAd"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"interstitialAd"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAd","kind":"typeIdentifier","text":"GFPInterstitialAd","preciseIdentifier":"c:objc(cs)GFPInterstitialAd"},{"kind":"text","text":"!, "},{"text":"didFailedWithError","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@NaverAdsServices@objc(cs)GFPError","text":"GFPError","kind":"typeIdentifier"},{"text":"!)","kind":"text"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpinterstitialaddelegate\/interstitialad(_:didfailedwitherror:)"]},{"paths":["\/documentation\/gfpsdk\/gfpinterstitialaddelegate\/interstitialad(_:didfailedwitherror:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdDelegate"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdDelegate\/interstitialAd(_:didFailedWithError:)"},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPInterstitialAd":{"navigatorTitle":[{"text":"GFPInterstitialAd","kind":"identifier"}],"abstract":[],"url":"\/documentation\/gfpsdk\/gfpinterstitialad","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAd","type":"topic","kind":"symbol","title":"GFPInterstitialAd","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPInterstitialAd"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPInterstitialAdDelegate":{"navigatorTitle":[{"kind":"identifier","text":"GFPInterstitialAdDelegate"}],"role":"symbol","kind":"symbol","abstract":[],"url":"\/documentation\/gfpsdk\/gfpinterstitialaddelegate","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"GFPInterstitialAdDelegate","kind":"identifier"}],"title":"GFPInterstitialAdDelegate"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPInterstitialAdDelegate/interstitialAd(_:didFailedWithError:)":{"required":true,"role":"symbol","abstract":[],"title":"interstitialAd(_:didFailedWithError:)","navigatorTitle":[{"text":"interstitialAd:didFailedWithError:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"interstitialAd"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPInterstitialAd","text":"GFPInterstitialAd","kind":"typeIdentifier"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"didFailedWithError"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@NaverAdsServices@objc(cs)GFPError","text":"GFPError","kind":"typeIdentifier"},{"text":"!)","kind":"text"}],"url":"\/documentation\/gfpsdk\/gfpinterstitialaddelegate\/interstitialad(_:didfailedwitherror:)","type":"topic","kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdDelegate\/interstitialAd(_:didFailedWithError:)"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"interstitialAd:didFailedWithError:","op":"replace","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"interstitialAd:didFailedWithError:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"interstitialAd:"},{"text":"(","kind":"text"},{"text":"GFPInterstitialAd","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPInterstitialAd","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAd"},{"kind":"text","text":" *) "},{"text":"interstitialAd","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"didFailedWithError:"},{"text":"(","kind":"text"},{"text":"GFPError","kind":"typeIdentifier","preciseIdentifier":"c:@M@NaverAdsServices@objc(cs)GFPError"},{"kind":"text","text":" *) "},{"text":"error","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAd\/title","value":"GFPInterstitialAd","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAd\/fragments","op":"replace","value":[{"text":"GFPInterstitialAd","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAd\/navigatorTitle","value":[{"kind":"identifier","text":"GFPInterstitialAd"}]},{"op":"replace","value":"GFPInterstitialAdDelegate","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdDelegate\/title"},{"value":[{"text":"GFPInterstitialAdDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdDelegate\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"GFPInterstitialAdDelegate"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdDelegate\/navigatorTitle"},{"value":"interstitialAd:didFailedWithError:","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdDelegate~1interstitialAd(_:didFailedWithError:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdDelegate~1interstitialAd(_:didFailedWithError:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"interstitialAd:didFailedWithError:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}