{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"weak","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"delegate"},{"text":": (any ","kind":"text"},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdAdaptorDelegate","preciseIdentifier":"c:objc(pl)GFPInterstitialAdAdaptorDelegate","kind":"typeIdentifier","text":"GFPInterstitialAdAdaptorDelegate"},{"text":")? { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpinterstitialadadapting\/delegate"]},{"paths":["\/documentation\/gfpsdk\/gfpinterstitialadadapting\/delegate"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"delegate","symbolKind":"property","role":"symbol","externalID":"c:objc(pl)GFPInterstitialAdAdapting(py)delegate","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"text":": (any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)GFPInterstitialAdAdaptorDelegate","text":"GFPInterstitialAdAdaptorDelegate","kind":"typeIdentifier"},{"text":")?","kind":"text"}],"navigatorTitle":[{"text":"delegate","kind":"identifier"}],"modules":[{"name":"GFPSDK"}],"required":true},"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdAdapting"]]},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdAdapting\/delegate","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPInterstitialAdAdapting":{"title":"GFPInterstitialAdAdapting","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdAdapting","url":"\/documentation\/gfpsdk\/gfpinterstitialadadapting","abstract":[],"kind":"symbol","navigatorTitle":[{"text":"GFPInterstitialAdAdapting","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"GFPInterstitialAdAdapting","kind":"identifier"}],"type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPInterstitialAdAdapting/delegate":{"navigatorTitle":[{"text":"delegate","kind":"identifier"}],"title":"delegate","type":"topic","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdAdapting\/delegate","url":"\/documentation\/gfpsdk\/gfpinterstitialadadapting\/delegate","abstract":[],"required":true,"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"delegate","kind":"identifier"},{"kind":"text","text":": (any "},{"text":"GFPInterstitialAdAdaptorDelegate","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)GFPInterstitialAdAdaptorDelegate"},{"kind":"text","text":")?"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPInterstitialAdAdaptorDelegate":{"url":"\/documentation\/gfpsdk\/gfpinterstitialadadaptordelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPInterstitialAdAdaptorDelegate","kind":"identifier"}],"role":"symbol","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdAdaptorDelegate","title":"GFPInterstitialAdAdaptorDelegate","navigatorTitle":[{"text":"GFPInterstitialAdAdaptorDelegate","kind":"identifier"}],"type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","value":"delegate","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"delegate","kind":"identifier"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"weak","kind":"keyword"},{"kind":"text","text":", "},{"text":"readwrite","kind":"keyword"},{"kind":"text","text":") "},{"text":"id<GFPInterstitialAdAdaptorDelegate>","preciseIdentifier":"c:Qoobjc(pl)GFPInterstitialAdAdaptorDelegate","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"op":"replace","value":"GFPInterstitialAdAdapting","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdAdapting\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdAdapting\/fragments","value":[{"text":"GFPInterstitialAdAdapting","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"GFPInterstitialAdAdapting"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdAdapting\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdAdapting~1delegate\/title","op":"replace","value":"delegate"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdAdapting~1delegate\/fragments","value":[{"text":"delegate","kind":"identifier"}]},{"value":"GFPInterstitialAdAdaptorDelegate","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdAdaptorDelegate\/title","op":"replace"},{"op":"replace","value":[{"text":"GFPInterstitialAdAdaptorDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdAdaptorDelegate\/fragments"},{"value":[{"text":"GFPInterstitialAdAdaptorDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdAdaptorDelegate\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}