{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"text":"type","kind":"externalParam"},{"kind":"text","text":" "},{"text":"aType","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@GFPRequestType","text":"GFPRequestType","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRequestType","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"path","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"aPath"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"queryItems","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"aQuery"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAPIQueryItems","text":"GFPAPIQueryItems","preciseIdentifier":"c:objc(cs)GFPAPIQueryItems","kind":"typeIdentifier"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAPIRequest"]]},"metadata":{"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"type","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPRequestType","text":"GFPRequestType"},{"text":", ","kind":"text"},{"text":"path","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?, ","kind":"text"},{"text":"queryItems","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GFPAPIQueryItems","preciseIdentifier":"c:objc(cs)GFPAPIQueryItems"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithType:path:queryItems:","kind":"identifier"}],"symbolKind":"init","roleHeading":"Initializer","externalID":"c:objc(cs)GFPAPIRequest(im)initWithType:path:queryItems:","title":"init(type:path:queryItems:)","modules":[{"name":"GFPSDK"}]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpapirequest\/init(type:path:queryitems:)"]},{"paths":["\/documentation\/gfpsdk\/gfpapirequest\/init(type:path:queryitems:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAPIRequest\/init(type:path:queryItems:)"},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAPIQueryItems":{"url":"\/documentation\/gfpsdk\/gfpapiqueryitems","abstract":[],"title":"GFPAPIQueryItems","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAPIQueryItems","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPAPIQueryItems"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPAPIQueryItems"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRequestType":{"abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRequestType","type":"topic","title":"GFPRequestType","navigatorTitle":[{"text":"GFPRequestType","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/gfpsdk\/gfprequesttype","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPRequestType"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAPIRequest":{"role":"symbol","type":"topic","navigatorTitle":[{"text":"GFPAPIRequest","kind":"identifier"}],"abstract":[],"title":"GFPAPIRequest","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPAPIRequest"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAPIRequest","url":"\/documentation\/gfpsdk\/gfpapirequest"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAPIRequest/init(type:path:queryItems:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"type"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPRequestType","text":"GFPRequestType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"path"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"queryItems","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)GFPAPIQueryItems","text":"GFPAPIQueryItems","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[],"url":"\/documentation\/gfpsdk\/gfpapirequest\/init(type:path:queryitems:)","navigatorTitle":[{"kind":"identifier","text":"initWithType:path:queryItems:"}],"kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAPIRequest\/init(type:path:queryItems:)","type":"topic","title":"init(type:path:queryItems:)","role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"value":"initWithType:path:queryItems:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithType:path:queryItems:"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"text":"initWithType:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPRequestType","text":"GFPRequestType","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRequestType"},{"text":") ","kind":"text"},{"text":"aType","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"path:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"aPath"},{"kind":"text","text":" "},{"text":"queryItems:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAPIQueryItems","text":"GFPAPIQueryItems","preciseIdentifier":"c:objc(cs)GFPAPIQueryItems","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"aQuery","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"value":"GFPAPIQueryItems","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAPIQueryItems\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAPIQueryItems\/fragments","op":"replace","value":[{"text":"GFPAPIQueryItems","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"GFPAPIQueryItems"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAPIQueryItems\/navigatorTitle"},{"value":"GFPRequestType","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRequestType\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRequestType\/fragments","value":[{"text":"GFPRequestType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRequestType\/navigatorTitle","value":[{"kind":"identifier","text":"GFPRequestType"}]},{"op":"replace","value":"GFPAPIRequest","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAPIRequest\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAPIRequest\/fragments","value":[{"kind":"identifier","text":"GFPAPIRequest"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAPIRequest\/navigatorTitle","op":"replace","value":[{"text":"GFPAPIRequest","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAPIRequest~1init(type:path:queryItems:)\/title","value":"initWithType:path:queryItems:","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAPIRequest~1init(type:path:queryItems:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"initWithType:path:queryItems:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}