{"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithDomElement:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)DDXMLElement","kind":"typeIdentifier","text":"DDXMLElement"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"aElement"},{"text":" ","kind":"text"},{"text":"duration:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"NSTimeInterval"},{"kind":"text","text":") "},{"text":"aDuration","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"error:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@NaverAdsServices@objc(cs)GFPError","kind":"typeIdentifier","text":"GFPError"},{"kind":"text","text":" * *) "},{"text":"aError","kind":"internalParam"},{"text":";","kind":"text"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/Icon"]]},"variants":[{"paths":["\/documentation\/gfpsdk\/icon\/initwithdomelement:duration:error:"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/Icon\/initWithDomElement:duration:error:"},"metadata":{"title":"initWithDomElement:duration:error:","role":"symbol","roleHeading":"Instance Method","symbolKind":"method","externalID":"c:objc(cs)Icon(im)initWithDomElement:duration:error:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithDomElement:duration:error:","kind":"identifier"}],"modules":[{"name":"GFPSDK"}],"navigatorTitle":[{"text":"initWithDomElement:duration:error:","kind":"identifier"}]},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/Icon":{"url":"\/documentation\/gfpsdk\/icon","title":"Icon","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/Icon","kind":"symbol","role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Icon","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"Icon"}],"abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/Icon/initWithDomElement:duration:error:":{"role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/Icon\/initWithDomElement:duration:error:","type":"topic","abstract":[],"url":"\/documentation\/gfpsdk\/icon\/initwithdomelement:duration:error:","title":"initWithDomElement:duration:error:","navigatorTitle":[{"text":"initWithDomElement:duration:error:","kind":"identifier"}],"fragments":[{"text":"- ","kind":"text"},{"text":"initWithDomElement:duration:error:","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1Icon\/title","value":"Icon"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1Icon\/fragments","value":[{"text":"Icon","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"Icon"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1Icon\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}