{"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUnifiedMediator\/delegate","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"weak","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"delegate","kind":"identifier"},{"text":": (any ","kind":"text"},{"kind":"typeIdentifier","text":"GFPUnifiedMediatorDelegate","preciseIdentifier":"c:objc(pl)GFPUnifiedMediatorDelegate","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUnifiedMediatorDelegate"},{"text":")? { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}]}]}],"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/gfpsdk\/gfpunifiedmediator\/delegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gfpsdk\/gfpunifiedmediator\/delegate"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUnifiedMediator"]]},"metadata":{"symbolKind":"property","title":"delegate","modules":[{"name":"GFPSDK"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"delegate","kind":"identifier"},{"kind":"text","text":": (any "},{"text":"GFPUnifiedMediatorDelegate","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)GFPUnifiedMediatorDelegate"},{"text":")?","kind":"text"}],"roleHeading":"Instance Property","navigatorTitle":[{"text":"delegate","kind":"identifier"}],"externalID":"c:objc(cs)GFPUnifiedMediator(py)delegate"},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPUnifiedMediator":{"abstract":[],"type":"topic","title":"GFPUnifiedMediator","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPUnifiedMediator","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpunifiedmediator","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUnifiedMediator","navigatorTitle":[{"text":"GFPUnifiedMediator","kind":"identifier"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPUnifiedMediator/delegate":{"title":"delegate","role":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"kind":"text","text":": (any "},{"preciseIdentifier":"c:objc(pl)GFPUnifiedMediatorDelegate","text":"GFPUnifiedMediatorDelegate","kind":"typeIdentifier"},{"text":")?","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUnifiedMediator\/delegate","navigatorTitle":[{"text":"delegate","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpunifiedmediator\/delegate","abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPUnifiedMediatorDelegate":{"type":"topic","navigatorTitle":[{"text":"GFPUnifiedMediatorDelegate","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/gfpsdk\/gfpunifiedmediatordelegate","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPUnifiedMediatorDelegate"}],"title":"GFPUnifiedMediatorDelegate","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUnifiedMediatorDelegate"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"delegate"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"kind":"identifier","text":"delegate"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"weak","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)GFPUnifiedMediatorDelegate","text":"id<GFPUnifiedMediatorDelegate>"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPUnifiedMediator\/title","op":"replace","value":"GFPUnifiedMediator"},{"op":"replace","value":[{"kind":"identifier","text":"GFPUnifiedMediator"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPUnifiedMediator\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"GFPUnifiedMediator"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPUnifiedMediator\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPUnifiedMediator~1delegate\/title","value":"delegate"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPUnifiedMediator~1delegate\/fragments","value":[{"text":"delegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPUnifiedMediatorDelegate\/title","op":"replace","value":"GFPUnifiedMediatorDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPUnifiedMediatorDelegate\/fragments","value":[{"kind":"identifier","text":"GFPUnifiedMediatorDelegate"}]},{"value":[{"text":"GFPUnifiedMediatorDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPUnifiedMediatorDelegate\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}