{"variants":[{"paths":["\/documentation\/gfpsdk\/gfpunifiedmediator\/loadadaptor(withadunitid:bannercontext:nativecontext:adparam:timeoutinterval:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpunifiedmediator\/loadadaptor(withadunitid:bannercontext:nativecontext:adparam:timeoutinterval:)"]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUnifiedMediator"]]},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"loadAdaptor","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withAdUnitID","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"adUnitID"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"bannerContext"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerContext","text":"GFPBannerContext","preciseIdentifier":"c:objc(cs)GFPBannerContext","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"nativeContext","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPNativeContext","text":"GFPNativeContext","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeContext"},{"text":"?, ","kind":"text"},{"text":"adParam","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdParam","text":"GFPAdParam","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdParam"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"timeoutInterval"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUnifiedMediator\/loadAdaptor(withAdUnitID:bannerContext:nativeContext:adParam:timeoutInterval:)"},"kind":"symbol","metadata":{"title":"loadAdaptor(withAdUnitID:bannerContext:nativeContext:adParam:timeoutInterval:)","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"loadAdaptor","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"withAdUnitID"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"bannerContext"},{"kind":"text","text":": "},{"text":"GFPBannerContext","preciseIdentifier":"c:objc(cs)GFPBannerContext","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"nativeContext","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"GFPNativeContext","preciseIdentifier":"c:objc(cs)GFPNativeContext"},{"kind":"text","text":"?, "},{"text":"adParam","kind":"externalParam"},{"kind":"text","text":": "},{"text":"GFPAdParam","preciseIdentifier":"c:objc(cs)GFPAdParam","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"timeoutInterval","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":")","kind":"text"}],"role":"symbol","modules":[{"name":"GFPSDK"}],"navigatorTitle":[{"text":"loadAdaptorWithAdUnitID:bannerContext:nativeContext:adParam:timeoutInterval:","kind":"identifier"}],"roleHeading":"Instance Method","externalID":"c:objc(cs)GFPUnifiedMediator(im)loadAdaptorWithAdUnitID:bannerContext:nativeContext:adParam:timeoutInterval:"},"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPUnifiedMediator/loadAdaptor(withAdUnitID:bannerContext:nativeContext:adParam:timeoutInterval:)":{"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"loadAdaptorWithAdUnitID:bannerContext:nativeContext:adParam:timeoutInterval:"}],"abstract":[],"title":"loadAdaptor(withAdUnitID:bannerContext:nativeContext:adParam:timeoutInterval:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"loadAdaptor","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withAdUnitID","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"bannerContext"},{"kind":"text","text":": "},{"text":"GFPBannerContext","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPBannerContext"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"nativeContext"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPNativeContext","text":"GFPNativeContext"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"adParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPAdParam","text":"GFPAdParam","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"timeoutInterval"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUnifiedMediator\/loadAdaptor(withAdUnitID:bannerContext:nativeContext:adParam:timeoutInterval:)","url":"\/documentation\/gfpsdk\/gfpunifiedmediator\/loadadaptor(withadunitid:bannercontext:nativecontext:adparam:timeoutinterval:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerContext":{"kind":"symbol","title":"GFPBannerContext","url":"\/documentation\/gfpsdk\/gfpbannercontext","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPBannerContext"}],"type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerContext","navigatorTitle":[{"kind":"identifier","text":"GFPBannerContext"}],"abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeContext":{"role":"symbol","title":"GFPNativeContext","url":"\/documentation\/gfpsdk\/gfpnativecontext","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeContext","navigatorTitle":[{"text":"GFPNativeContext","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"GFPNativeContext","kind":"identifier"}],"abstract":[],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPUnifiedMediator":{"abstract":[],"type":"topic","title":"GFPUnifiedMediator","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPUnifiedMediator","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpunifiedmediator","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUnifiedMediator","navigatorTitle":[{"text":"GFPUnifiedMediator","kind":"identifier"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdParam":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdParam","abstract":[],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPAdParam"}],"navigatorTitle":[{"text":"GFPAdParam","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpadparam","type":"topic","kind":"symbol","title":"GFPAdParam"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"loadAdaptorWithAdUnitID:bannerContext:nativeContext:adParam:timeoutInterval:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"loadAdaptorWithAdUnitID:bannerContext:nativeContext:adParam:timeoutInterval:"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"loadAdaptorWithAdUnitID:"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"adUnitID"},{"text":" ","kind":"text"},{"text":"bannerContext:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPBannerContext","text":"GFPBannerContext","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerContext"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"bannerContext"},{"kind":"text","text":" "},{"text":"nativeContext:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPNativeContext","text":"GFPNativeContext","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeContext"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"nativeContext"},{"kind":"text","text":" "},{"text":"adParam:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdParam","text":"GFPAdParam","preciseIdentifier":"c:objc(cs)GFPAdParam","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"adParam","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"timeoutInterval:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSTimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":") ","kind":"text"},{"text":"timeoutInterval","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"loadAdaptorWithAdUnitID:bannerContext:nativeContext:adParam:timeoutInterval:","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPUnifiedMediator~1loadAdaptor(withAdUnitID:bannerContext:nativeContext:adParam:timeoutInterval:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPUnifiedMediator~1loadAdaptor(withAdUnitID:bannerContext:nativeContext:adParam:timeoutInterval:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"loadAdaptorWithAdUnitID:bannerContext:nativeContext:adParam:timeoutInterval:","kind":"identifier"}]},{"op":"replace","value":"GFPBannerContext","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerContext\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerContext\/fragments","value":[{"kind":"identifier","text":"GFPBannerContext"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerContext\/navigatorTitle","value":[{"kind":"identifier","text":"GFPBannerContext"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeContext\/title","op":"replace","value":"GFPNativeContext"},{"value":[{"kind":"identifier","text":"GFPNativeContext"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeContext\/fragments"},{"value":[{"text":"GFPNativeContext","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeContext\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPUnifiedMediator\/title","op":"replace","value":"GFPUnifiedMediator"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPUnifiedMediator\/fragments","op":"replace","value":[{"kind":"identifier","text":"GFPUnifiedMediator"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPUnifiedMediator\/navigatorTitle","value":[{"kind":"identifier","text":"GFPUnifiedMediator"}]},{"value":"GFPAdParam","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdParam\/title","op":"replace"},{"value":[{"kind":"identifier","text":"GFPAdParam"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdParam\/fragments"},{"value":[{"text":"GFPAdParam","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdParam\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}