{"metadata":{"modules":[{"name":"GFPSDK"}],"externalID":"c:objc(cs)GFPAdDedupeManager(im)loadAdWith:","roleHeading":"Instance Method","title":"loadAd(with:)","role":"symbol","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"loadAd","kind":"identifier"},{"kind":"text","text":"("},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPAdLoader","kind":"typeIdentifier","text":"GFPAdLoader"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"loadAdWith:"}]},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdDedupeManager\/loadAd(with:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpaddedupemanager\/loadad(with:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpaddedupemanager\/loadad(with:)"]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadAd"},{"kind":"text","text":"("},{"text":"with","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"adLoader"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoader","text":"GFPAdLoader","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdLoader"},{"kind":"text","text":")"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdDedupeManager"]]},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdDedupeManager":{"title":"GFPAdDedupeManager","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdDedupeManager","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"GFPAdDedupeManager","kind":"identifier"}],"abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPAdDedupeManager"}],"url":"\/documentation\/gfpsdk\/gfpaddedupemanager"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdDedupeManager/loadAd(with:)":{"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"loadAdWith:"}],"abstract":[],"title":"loadAd(with:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"loadAd","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"GFPAdLoader","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdLoader"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdDedupeManager\/loadAd(with:)","url":"\/documentation\/gfpsdk\/gfpaddedupemanager\/loadad(with:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdLoader":{"navigatorTitle":[{"text":"GFPAdLoader","kind":"identifier"}],"kind":"symbol","title":"GFPAdLoader","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoader","url":"\/documentation\/gfpsdk\/gfpadloader","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPAdLoader"}],"type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"loadAdWith:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"loadAdWith:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"loadAdWith:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"GFPAdLoader","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdLoader","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoader"},{"text":" *) ","kind":"text"},{"text":"adLoader","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"value":"GFPAdDedupeManager","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdDedupeManager\/title"},{"op":"replace","value":[{"kind":"identifier","text":"GFPAdDedupeManager"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdDedupeManager\/fragments"},{"value":[{"kind":"identifier","text":"GFPAdDedupeManager"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdDedupeManager\/navigatorTitle"},{"value":"loadAdWith:","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdDedupeManager~1loadAd(with:)\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdDedupeManager~1loadAd(with:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"loadAdWith:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoader\/title","value":"GFPAdLoader"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoader\/fragments","value":[{"kind":"identifier","text":"GFPAdLoader"}]},{"value":[{"text":"GFPAdLoader","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoader\/navigatorTitle"}]}]}