{"sections":[],"kind":"symbol","metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DFP","kind":"identifier"}],"modules":[{"name":"GFPSDK"}],"navigatorTitle":[{"text":"GFPNativeProviderOptionDFP","kind":"identifier"}],"symbolKind":"case","role":"symbol","title":"GFPNativeProviderOption.DFP","roleHeading":"Case","externalID":"c:@M@GFPSDK@E@GFPNativeProviderOption@GFPNativeProviderOptionDFP"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DFP","kind":"identifier"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeProviderOption"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/gfpsdk\/gfpnativeprovideroption\/dfp"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpnativeprovideroption\/dfp"]}],"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeProviderOption\/DFP","interfaceLanguage":"swift"},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeProviderOption":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPNativeProviderOption"}],"title":"GFPNativeProviderOption","type":"topic","kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeProviderOption","url":"\/documentation\/gfpsdk\/gfpnativeprovideroption","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPNativeProviderOption","kind":"identifier"}],"abstract":[{"type":"text","text":"GFP에서 지원하는 네이티브광고 제공자 목록"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeProviderOption/DFP":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DFP"}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"GFPNativeProviderOptionDFP","kind":"identifier"}],"abstract":[],"role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeProviderOption\/DFP","title":"GFPNativeProviderOption.DFP","url":"\/documentation\/gfpsdk\/gfpnativeprovideroption\/dfp"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"GFPNativeProviderOptionDFP"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"GFPNativeProviderOptionDFP"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"GFPNativeProviderOptionDFP","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeProviderOption\/title","op":"replace","value":"GFPNativeProviderOption"},{"op":"replace","value":[{"text":"GFPNativeProviderOption","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeProviderOption\/fragments"},{"op":"replace","value":[{"text":"GFPNativeProviderOption","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeProviderOption\/navigatorTitle"},{"value":"GFPNativeProviderOptionDFP","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeProviderOption~1DFP\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeProviderOption~1DFP\/fragments","op":"replace","value":[{"kind":"identifier","text":"GFPNativeProviderOptionDFP"}]}]}]}