{"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/gfpsdk\/gfpnativeprovideroption\/lan"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpnativeprovideroption\/lan"]}],"metadata":{"title":"GFPNativeProviderOption.LAN","modules":[{"name":"GFPSDK"}],"roleHeading":"Case","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"LAN","kind":"identifier"}],"navigatorTitle":[{"text":"GFPNativeProviderOptionLAN","kind":"identifier"}],"symbolKind":"case","externalID":"c:@M@GFPSDK@E@GFPNativeProviderOption@GFPNativeProviderOptionLAN"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeProviderOption"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LAN"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeProviderOption\/LAN","interfaceLanguage":"swift"},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeProviderOption":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPNativeProviderOption"}],"title":"GFPNativeProviderOption","type":"topic","kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeProviderOption","url":"\/documentation\/gfpsdk\/gfpnativeprovideroption","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPNativeProviderOption","kind":"identifier"}],"abstract":[{"type":"text","text":"GFP에서 지원하는 네이티브광고 제공자 목록"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeProviderOption/LAN":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeProviderOption\/LAN","type":"topic","abstract":[],"url":"\/documentation\/gfpsdk\/gfpnativeprovideroption\/lan","navigatorTitle":[{"kind":"identifier","text":"GFPNativeProviderOptionLAN"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"LAN","kind":"identifier"}],"title":"GFPNativeProviderOption.LAN","role":"symbol","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"GFPNativeProviderOptionLAN"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","value":[{"kind":"identifier","text":"GFPNativeProviderOptionLAN"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"GFPNativeProviderOptionLAN","kind":"identifier"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeProviderOption\/title","value":"GFPNativeProviderOption","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeProviderOption\/fragments","value":[{"text":"GFPNativeProviderOption","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeProviderOption\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"GFPNativeProviderOption"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeProviderOption~1LAN\/title","value":"GFPNativeProviderOptionLAN","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeProviderOption~1LAN\/fragments","value":[{"text":"GFPNativeProviderOptionLAN","kind":"identifier"}]}]}]}