{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"HTML","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@GFPOMContantsType","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPOMContantsType","text":"GFPOMContantsType","kind":"typeIdentifier"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpomcontantstype\/html"]},{"paths":["\/documentation\/gfpsdk\/gfpomcontantstype\/html"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"role":"symbol","externalID":"c:@E@GFPOMContantsType@GFPOMContantsTypeHTML","symbolKind":"property","modules":[{"name":"GFPSDK"}],"title":"HTML","roleHeading":"Type Property","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"HTML"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GFPOMContantsType","preciseIdentifier":"c:@E@GFPOMContantsType"}],"navigatorTitle":[{"text":"GFPOMContantsTypeHTML","kind":"identifier"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPOMContantsType"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPOMContantsType\/HTML"},"sections":[],"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPOMContantsType":{"abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPOMContantsType","navigatorTitle":[{"text":"GFPOMContantsType","kind":"identifier"}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"GFPOMContantsType","kind":"identifier"}],"kind":"symbol","title":"GFPOMContantsType","url":"\/documentation\/gfpsdk\/gfpomcontantstype"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPOMContantsType/HTML":{"url":"\/documentation\/gfpsdk\/gfpomcontantstype\/html","title":"HTML","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPOMContantsType\/HTML","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPOMContantsTypeHTML"}],"type":"topic","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HTML"},{"kind":"text","text":": "},{"text":"GFPOMContantsType","kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPOMContantsType"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"GFPOMContantsTypeHTML","op":"replace"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GFPOMContantsTypeHTML"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"GFPOMContantsTypeHTML"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPOMContantsType\/title","value":"GFPOMContantsType","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"GFPOMContantsType"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPOMContantsType\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPOMContantsType\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"GFPOMContantsType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPOMContantsType~1HTML\/title","value":"GFPOMContantsTypeHTML"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPOMContantsType~1HTML\/fragments","value":[{"kind":"identifier","text":"GFPOMContantsTypeHTML"}]}]}]}