{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpomcontantstype\/video"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpomcontantstype\/video"]}],"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPOMContantsType\/video","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"video","kind":"identifier"},{"kind":"text","text":": "},{"text":"GFPOMContantsType","preciseIdentifier":"c:@E@GFPOMContantsType","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"GFPOMContantsTypeVideo"}],"roleHeading":"Type Property","modules":[{"name":"GFPSDK"}],"externalID":"c:@E@GFPOMContantsType@GFPOMContantsTypeVideo","role":"symbol","title":"video","symbolKind":"property"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"video","kind":"identifier"},{"kind":"text","text":": "},{"text":"GFPOMContantsType","kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPOMContantsType","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPOMContantsType"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPOMContantsType"]]},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPOMContantsType/video":{"url":"\/documentation\/gfpsdk\/gfpomcontantstype\/video","title":"video","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPOMContantsType\/video","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPOMContantsTypeVideo"}],"type":"topic","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"video","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPOMContantsType","text":"GFPOMContantsType"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPOMContantsType":{"abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPOMContantsType","navigatorTitle":[{"text":"GFPOMContantsType","kind":"identifier"}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"GFPOMContantsType","kind":"identifier"}],"kind":"symbol","title":"GFPOMContantsType","url":"\/documentation\/gfpsdk\/gfpomcontantstype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"GFPOMContantsTypeVideo"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"GFPOMContantsTypeVideo"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"GFPOMContantsTypeVideo","kind":"identifier"}]}],"kind":"declarations"}},{"value":"GFPOMContantsTypeVideo","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPOMContantsType~1video\/title"},{"value":[{"text":"GFPOMContantsTypeVideo","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPOMContantsType~1video\/fragments"},{"op":"replace","value":"GFPOMContantsType","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPOMContantsType\/title"},{"value":[{"kind":"identifier","text":"GFPOMContantsType"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPOMContantsType\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPOMContantsType\/navigatorTitle","op":"replace","value":[{"text":"GFPOMContantsType","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}