{"metadata":{"role":"symbol","modules":[{"name":"GFPSDK"}],"platforms":[{"introducedAt":"2.0","deprecated":false,"name":"iOS","unavailable":false,"beta":false},{"unavailable":false,"name":"iPadOS","beta":false,"introducedAt":"2.0","deprecated":false},{"deprecated":false,"introducedAt":"2.0","name":"Mac Catalyst","beta":false,"unavailable":false}],"externalID":"c:objc(pl)GFPUserInterestDelegate(im)ad:didChangeUserInterest:","symbolKind":"method","title":"ad(_:didChangeUserInterest:)","navigatorTitle":[{"kind":"identifier","text":"ad:didChangeUserInterest:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ad"},{"kind":"text","text":"("},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"},{"text":"!, ","kind":"text"},{"kind":"externalParam","text":"didChangeUserInterest"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"roleHeading":"Instance Method","required":true},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"ad","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"ad","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"},{"kind":"text","text":"!, "},{"text":"didChangeUserInterest","kind":"externalParam"},{"kind":"text","text":" "},{"text":"userInterest","kind":"internalParam"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpuserinterestdelegate\/ad(_:didchangeuserinterest:)"]},{"paths":["\/documentation\/gfpsdk\/gfpuserinterestdelegate\/ad(_:didchangeuserinterest:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUserInterestDelegate"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUserInterestDelegate\/ad(_:didChangeUserInterest:)"},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPUserInterestDelegate/ad(_:didChangeUserInterest:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"ad","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"},{"text":"!, ","kind":"text"},{"text":"didChangeUserInterest","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"ad(_:didChangeUserInterest:)","navigatorTitle":[{"kind":"identifier","text":"ad:didChangeUserInterest:"}],"url":"\/documentation\/gfpsdk\/gfpuserinterestdelegate\/ad(_:didchangeuserinterest:)","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUserInterestDelegate\/ad(_:didChangeUserInterest:)","role":"symbol","type":"topic","kind":"symbol","abstract":[],"required":true},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPUserInterestDelegate":{"abstract":[],"url":"\/documentation\/gfpsdk\/gfpuserinterestdelegate","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPUserInterestDelegate","role":"symbol","title":"GFPUserInterestDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"GFPUserInterestDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"GFPUserInterestDelegate","kind":"identifier"}],"kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","value":"ad:didChangeUserInterest:","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"ad:didChangeUserInterest:"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"ad:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"},{"kind":"text","text":" *) "},{"text":"ad","kind":"internalParam"},{"kind":"text","text":" "},{"text":"didChangeUserInterest:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"userInterest"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"value":"ad:didChangeUserInterest:","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPUserInterestDelegate~1ad(_:didChangeUserInterest:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPUserInterestDelegate~1ad(_:didChangeUserInterest:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"ad:didChangeUserInterest:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPUserInterestDelegate\/title","value":"GFPUserInterestDelegate","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPUserInterestDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"GFPUserInterestDelegate"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPUserInterestDelegate\/navigatorTitle","op":"replace","value":[{"text":"GFPUserInterestDelegate","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}