{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"adSize"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerAdSize","text":"GFPBannerAdSize","preciseIdentifier":"c:objc(cs)GFPBannerAdSize","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdBannerOptions"]]},"metadata":{"title":"adSize","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"adSize","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GFPBannerAdSize","preciseIdentifier":"c:objc(cs)GFPBannerAdSize"}],"roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)GFPAdBannerOptions(py)adSize","navigatorTitle":[{"text":"adSize","kind":"identifier"}],"modules":[{"name":"GFPSDK"}]},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdBannerOptions\/adSize","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpadbanneroptions\/adsize"]},{"paths":["\/documentation\/gfpsdk\/gfpadbanneroptions\/adsize"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"abstract":[{"text":"로드된 배너 광고 사이즈 정보 (없으면 nil)","type":"text"}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerAdSize":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"GFPBannerAdSize"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerAdSize","url":"\/documentation\/gfpsdk\/gfpbanneradsize","abstract":[],"kind":"symbol","title":"GFPBannerAdSize","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPBannerAdSize","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdBannerOptions":{"navigatorTitle":[{"text":"GFPAdBannerOptions","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"GFPAdBannerOptions","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdBannerOptions","type":"topic","abstract":[],"url":"\/documentation\/gfpsdk\/gfpadbanneroptions","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"GFPAdBannerOptions","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdBannerOptions/adSize":{"abstract":[{"text":"로드된 배너 광고 사이즈 정보 (없으면 nil)","type":"text"}],"title":"adSize","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"adSize","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPBannerAdSize","text":"GFPBannerAdSize","kind":"typeIdentifier"}],"url":"\/documentation\/gfpsdk\/gfpadbanneroptions\/adsize","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdBannerOptions\/adSize","navigatorTitle":[{"kind":"identifier","text":"adSize"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"adSize","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"adSize"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerAdSize","text":"GFPBannerAdSize","preciseIdentifier":"c:objc(cs)GFPBannerAdSize","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"adSize","kind":"identifier"},{"kind":"text","text":";"}]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerAdSize\/title","value":"GFPBannerAdSize"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerAdSize\/fragments","value":[{"text":"GFPBannerAdSize","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerAdSize\/navigatorTitle","op":"replace","value":[{"text":"GFPBannerAdSize","kind":"identifier"}]},{"value":"GFPAdBannerOptions","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdBannerOptions\/title"},{"op":"replace","value":[{"text":"GFPAdBannerOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdBannerOptions\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdBannerOptions\/navigatorTitle","value":[{"kind":"identifier","text":"GFPAdBannerOptions"}]},{"value":"adSize","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdBannerOptions~1adSize\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdBannerOptions~1adSize\/fragments","value":[{"text":"adSize","kind":"identifier"}],"op":"replace"}]}]}