{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdBannerOptions"]]},"abstract":[{"text":"Mraid 추가 feature Support 세팅 정보 ( 0 -> default )","type":"text"}],"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdBannerOptions\/mraidSupportType","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpadbanneroptions\/mraidsupporttype"]},{"paths":["\/documentation\/gfpsdk\/gfpadbanneroptions\/mraidsupporttype"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"mraidSupportType","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GFPMraidSupportType","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMraidSupportType","preciseIdentifier":"c:@E@GFPMraidSupportType"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"metadata":{"role":"symbol","externalID":"c:objc(cs)GFPAdBannerOptions(py)mraidSupportType","symbolKind":"property","roleHeading":"Instance Property","modules":[{"name":"GFPSDK"}],"title":"mraidSupportType","navigatorTitle":[{"text":"mraidSupportType","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mraidSupportType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"GFPMraidSupportType","kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPMraidSupportType"}]},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdBannerOptions/mraidSupportType":{"navigatorTitle":[{"text":"mraidSupportType","kind":"identifier"}],"type":"topic","url":"\/documentation\/gfpsdk\/gfpadbanneroptions\/mraidsupporttype","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdBannerOptions\/mraidSupportType","abstract":[{"text":"Mraid 추가 feature Support 세팅 정보 ( 0 -> default )","type":"text"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"mraidSupportType"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"GFPMraidSupportType","preciseIdentifier":"c:@E@GFPMraidSupportType"}],"kind":"symbol","title":"mraidSupportType"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdBannerOptions":{"navigatorTitle":[{"text":"GFPAdBannerOptions","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"GFPAdBannerOptions","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdBannerOptions","type":"topic","abstract":[],"url":"\/documentation\/gfpsdk\/gfpadbanneroptions","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"GFPAdBannerOptions","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPMraidSupportType":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPMraidSupportType"}],"kind":"symbol","navigatorTitle":[{"text":"GFPMraidSupportType","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMraidSupportType","abstract":[],"role":"symbol","url":"\/documentation\/gfpsdk\/gfpmraidsupporttype","title":"GFPMraidSupportType","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"mraidSupportType","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"mraidSupportType","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"readwrite","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"setter"},{"text":"=","kind":"text"},{"text":"setMraidSupportType:","kind":"identifier"},{"text":") ","kind":"text"},{"text":"GFPMraidSupportType","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMraidSupportType","preciseIdentifier":"c:@E@GFPMraidSupportType","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mraidSupportType"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"mraidSupportType","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdBannerOptions~1mraidSupportType\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdBannerOptions~1mraidSupportType\/fragments","value":[{"text":"mraidSupportType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdBannerOptions\/title","op":"replace","value":"GFPAdBannerOptions"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdBannerOptions\/fragments","value":[{"kind":"identifier","text":"GFPAdBannerOptions"}],"op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"GFPAdBannerOptions"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdBannerOptions\/navigatorTitle"},{"value":"GFPMraidSupportType","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMraidSupportType\/title"},{"value":[{"text":"GFPMraidSupportType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMraidSupportType\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMraidSupportType\/navigatorTitle","value":[{"text":"GFPMraidSupportType","kind":"identifier"}]}]}]}