{"variants":[{"paths":["\/documentation\/gfpsdk\/gfpadbanneroptions\/webviewoption"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpadbanneroptions\/webviewoption"]}],"abstract":[{"text":"Banner webview option 설정","type":"text"}],"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdBannerOptions\/webViewOption","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"modules":[{"name":"GFPSDK"}],"role":"symbol","roleHeading":"Instance Property","title":"webViewOption","externalID":"c:objc(cs)GFPAdBannerOptions(py)webViewOption","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"webViewOption"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPAdBannerWebViewOptions","kind":"typeIdentifier","text":"GFPAdBannerWebViewOptions"}],"navigatorTitle":[{"text":"webViewOption","kind":"identifier"}]},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"webViewOption","kind":"identifier"},{"kind":"text","text":": "},{"text":"GFPAdBannerWebViewOptions","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdBannerWebViewOptions","preciseIdentifier":"c:objc(cs)GFPAdBannerWebViewOptions"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdBannerOptions"]]},"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdBannerOptions":{"navigatorTitle":[{"text":"GFPAdBannerOptions","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"GFPAdBannerOptions","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdBannerOptions","type":"topic","abstract":[],"url":"\/documentation\/gfpsdk\/gfpadbanneroptions","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"GFPAdBannerOptions","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdBannerOptions/webViewOption":{"type":"topic","title":"webViewOption","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"webViewOption"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdBannerWebViewOptions","text":"GFPAdBannerWebViewOptions"}],"abstract":[{"type":"text","text":"Banner webview option 설정"}],"url":"\/documentation\/gfpsdk\/gfpadbanneroptions\/webviewoption","kind":"symbol","navigatorTitle":[{"text":"webViewOption","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdBannerOptions\/webViewOption"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdBannerWebViewOptions":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdBannerWebViewOptions","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPAdBannerWebViewOptions"}],"navigatorTitle":[{"text":"GFPAdBannerWebViewOptions","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/gfpsdk\/gfpadbannerwebviewoptions","title":"GFPAdBannerWebViewOptions","kind":"symbol","abstract":[]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"webViewOption","op":"replace","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"webViewOption","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readwrite"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdBannerWebViewOptions","text":"GFPAdBannerWebViewOptions","preciseIdentifier":"c:objc(cs)GFPAdBannerWebViewOptions"},{"kind":"text","text":" * "},{"text":"webViewOption","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdBannerOptions\/title","value":"GFPAdBannerOptions","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdBannerOptions\/fragments","value":[{"text":"GFPAdBannerOptions","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdBannerOptions\/navigatorTitle","value":[{"text":"GFPAdBannerOptions","kind":"identifier"}]},{"value":"webViewOption","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdBannerOptions~1webViewOption\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdBannerOptions~1webViewOption\/fragments","value":[{"kind":"identifier","text":"webViewOption"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdBannerWebViewOptions\/title","value":"GFPAdBannerWebViewOptions"},{"op":"replace","value":[{"text":"GFPAdBannerWebViewOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdBannerWebViewOptions\/fragments"},{"value":[{"kind":"identifier","text":"GFPAdBannerWebViewOptions"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdBannerWebViewOptions\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}