{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdManagerDelegate\/attStatus()"},"metadata":{"modules":[{"name":"GFPSDK"}],"externalID":"c:objc(pl)GFPAdManagerDelegate(im)attStatus","roleHeading":"Instance Method","title":"attStatus()","role":"symbol","required":true,"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"attStatus","kind":"identifier"},{"kind":"text","text":"() -> "},{"text":"GFPATTAuthorizationStatus","kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPATTAuthorizationStatus"}],"navigatorTitle":[{"text":"attStatus","kind":"identifier"}]},"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpadmanagerdelegate\/attstatus()"]},{"paths":["\/documentation\/gfpsdk\/gfpadmanagerdelegate\/attstatus()"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdManagerDelegate"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"attStatus","kind":"identifier"},{"kind":"text","text":"() -> "},{"text":"GFPATTAuthorizationStatus","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPATTAuthorizationStatus","kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPATTAuthorizationStatus"}]}]}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPATTAuthorizationStatus":{"abstract":[],"role":"symbol","url":"\/documentation\/gfpsdk\/gfpattauthorizationstatus","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPATTAuthorizationStatus"}],"navigatorTitle":[{"text":"GFPATTAuthorizationStatus","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPATTAuthorizationStatus","title":"GFPATTAuthorizationStatus","kind":"symbol","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdManagerDelegate/attStatus()":{"required":true,"role":"symbol","type":"topic","navigatorTitle":[{"text":"attStatus","kind":"identifier"}],"abstract":[],"kind":"symbol","title":"attStatus()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"attStatus","kind":"identifier"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"c:@E@GFPATTAuthorizationStatus","text":"GFPATTAuthorizationStatus","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdManagerDelegate\/attStatus()","url":"\/documentation\/gfpsdk\/gfpadmanagerdelegate\/attstatus()"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdManagerDelegate":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdManagerDelegate","role":"symbol","abstract":[],"kind":"symbol","url":"\/documentation\/gfpsdk\/gfpadmanagerdelegate","type":"topic","title":"GFPAdManagerDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPAdManagerDelegate"}],"navigatorTitle":[{"text":"GFPAdManagerDelegate","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","value":"attStatus","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"attStatus"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"GFPATTAuthorizationStatus","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPATTAuthorizationStatus","kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPATTAuthorizationStatus"},{"text":") ","kind":"text"},{"text":"attStatus","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"value":"GFPATTAuthorizationStatus","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPATTAuthorizationStatus\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPATTAuthorizationStatus\/fragments","value":[{"kind":"identifier","text":"GFPATTAuthorizationStatus"}],"op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"GFPATTAuthorizationStatus"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPATTAuthorizationStatus\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdManagerDelegate~1attStatus()\/title","op":"replace","value":"attStatus"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdManagerDelegate~1attStatus()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"attStatus"}]},{"value":"GFPAdManagerDelegate","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdManagerDelegate\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdManagerDelegate\/fragments","value":[{"kind":"identifier","text":"GFPAdManagerDelegate"}]},{"op":"replace","value":[{"kind":"identifier","text":"GFPAdManagerDelegate"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdManagerDelegate\/navigatorTitle"}]}]}