{"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdAdaptorDelegate"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpinterstitialadadaptordelegate\/interstitialadadaptor(_:didfailwitherror:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpinterstitialadadaptordelegate\/interstitialadadaptor(_:didfailwitherror:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"interstitialAdAdaptor"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"interstitialAdAdaptor","kind":"internalParam"},{"text":": any ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAdaptor","preciseIdentifier":"c:objc(cs)GFPAdAdaptor","text":"GFPAdAdaptor"},{"text":" & ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdAdapting","text":"GFPInterstitialAdAdapting","preciseIdentifier":"c:objc(pl)GFPInterstitialAdAdapting"},{"text":", ","kind":"text"},{"text":"didFailWithError","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GFPError","preciseIdentifier":"c:@M@NaverAdsServices@objc(cs)GFPError"},{"kind":"text","text":")"}]}]}],"metadata":{"externalID":"c:objc(pl)GFPInterstitialAdAdaptorDelegate(im)interstitialAdAdaptor:didFailWithError:","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"interstitialAdAdaptor","kind":"identifier"},{"text":"(any ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPAdAdaptor","text":"GFPAdAdaptor","kind":"typeIdentifier"},{"kind":"text","text":" & "},{"text":"GFPInterstitialAdAdapting","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)GFPInterstitialAdAdapting"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didFailWithError"},{"text":": ","kind":"text"},{"text":"GFPError","kind":"typeIdentifier","preciseIdentifier":"c:@M@NaverAdsServices@objc(cs)GFPError"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"interstitialAdAdaptor:didFailWithError:"}],"modules":[{"name":"GFPSDK"}],"symbolKind":"method","role":"symbol","title":"interstitialAdAdaptor(_:didFailWithError:)","roleHeading":"Instance Method"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdAdaptorDelegate\/interstitialAdAdaptor(_:didFailWithError:)"},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPInterstitialAdAdaptorDelegate/interstitialAdAdaptor(_:didFailWithError:)":{"role":"symbol","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"interstitialAdAdaptor","kind":"identifier"},{"text":"(any ","kind":"text"},{"text":"GFPAdAdaptor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdAdaptor"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"GFPInterstitialAdAdapting","preciseIdentifier":"c:objc(pl)GFPInterstitialAdAdapting"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didFailWithError"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@NaverAdsServices@objc(cs)GFPError","text":"GFPError","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdAdaptorDelegate\/interstitialAdAdaptor(_:didFailWithError:)","url":"\/documentation\/gfpsdk\/gfpinterstitialadadaptordelegate\/interstitialadadaptor(_:didfailwitherror:)","required":true,"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"interstitialAdAdaptor:didFailWithError:"}],"title":"interstitialAdAdaptor(_:didFailWithError:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdAdaptor":{"navigatorTitle":[{"kind":"identifier","text":"GFPAdAdaptor"}],"title":"GFPAdAdaptor","url":"\/documentation\/gfpsdk\/gfpadadaptor","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAdaptor","abstract":[],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPAdAdaptor"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPInterstitialAdAdaptorDelegate":{"url":"\/documentation\/gfpsdk\/gfpinterstitialadadaptordelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPInterstitialAdAdaptorDelegate","kind":"identifier"}],"role":"symbol","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdAdaptorDelegate","title":"GFPInterstitialAdAdaptorDelegate","navigatorTitle":[{"text":"GFPInterstitialAdAdaptorDelegate","kind":"identifier"}],"type":"topic","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPInterstitialAdAdapting":{"title":"GFPInterstitialAdAdapting","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInterstitialAdAdapting","url":"\/documentation\/gfpsdk\/gfpinterstitialadadapting","abstract":[],"kind":"symbol","navigatorTitle":[{"text":"GFPInterstitialAdAdapting","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"GFPInterstitialAdAdapting","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"interstitialAdAdaptor:didFailWithError:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"interstitialAdAdaptor:didFailWithError:"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"interstitialAdAdaptor:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Q$objc(cs)GFPAdAdaptorobjc(pl)GFPInterstitialAdAdapting","text":"GFPAdAdaptor<GFPInterstitialAdAdapting>","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"interstitialAdAdaptor"},{"kind":"text","text":" "},{"text":"didFailWithError:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"GFPError","preciseIdentifier":"c:@M@NaverAdsServices@objc(cs)GFPError","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"value":"interstitialAdAdaptor:didFailWithError:","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdAdaptorDelegate~1interstitialAdAdaptor(_:didFailWithError:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdAdaptorDelegate~1interstitialAdAdaptor(_:didFailWithError:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"interstitialAdAdaptor:didFailWithError:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdaptor\/title","value":"GFPAdAdaptor"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdaptor\/fragments","op":"replace","value":[{"kind":"identifier","text":"GFPAdAdaptor"}]},{"value":[{"text":"GFPAdAdaptor","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdaptor\/navigatorTitle","op":"replace"},{"op":"replace","value":"GFPInterstitialAdAdaptorDelegate","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdAdaptorDelegate\/title"},{"value":[{"kind":"identifier","text":"GFPInterstitialAdAdaptorDelegate"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdAdaptorDelegate\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdAdaptorDelegate\/navigatorTitle","value":[{"text":"GFPInterstitialAdAdaptorDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdAdapting\/title","value":"GFPInterstitialAdAdapting","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdAdapting\/fragments","value":[{"kind":"identifier","text":"GFPInterstitialAdAdapting"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInterstitialAdAdapting\/navigatorTitle","value":[{"kind":"identifier","text":"GFPInterstitialAdAdapting"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}