{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpconfigdictionaryconverter\/init(configuration:)"]},{"paths":["\/documentation\/gfpsdk\/gfpconfigdictionaryconverter\/init(configuration:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPConfigDictionaryConverter"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPConfigDictionaryConverter\/init(configuration:)"},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"kind":"symbol","metadata":{"externalID":"c:objc(cs)GFPConfigDictionaryConverter(im)initWithConfiguration:","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)GFPAdConfiguration","text":"GFPAdConfiguration","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithConfiguration:","kind":"identifier"}],"symbolKind":"init","title":"init(configuration:)","modules":[{"name":"GFPSDK"}],"roleHeading":"Initializer","role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":" "},{"text":"aConfiguration","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdConfiguration","preciseIdentifier":"c:objc(cs)GFPAdConfiguration","kind":"typeIdentifier","text":"GFPAdConfiguration"},{"kind":"text","text":")"}]}]}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPConfigDictionaryConverter":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPConfigDictionaryConverter","title":"GFPConfigDictionaryConverter","kind":"symbol","url":"\/documentation\/gfpsdk\/gfpconfigdictionaryconverter","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPConfigDictionaryConverter","kind":"identifier"}],"navigatorTitle":[{"text":"GFPConfigDictionaryConverter","kind":"identifier"}],"abstract":[],"type":"topic","role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPConfigDictionaryConverter/init(configuration:)":{"navigatorTitle":[{"kind":"identifier","text":"initWithConfiguration:"}],"title":"init(configuration:)","url":"\/documentation\/gfpsdk\/gfpconfigdictionaryconverter\/init(configuration:)","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPConfigDictionaryConverter\/init(configuration:)","role":"symbol","type":"topic","kind":"symbol","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"configuration"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"GFPAdConfiguration","preciseIdentifier":"c:objc(cs)GFPAdConfiguration"},{"text":")","kind":"text"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdConfiguration":{"type":"topic","url":"\/documentation\/gfpsdk\/gfpadconfiguration","role":"symbol","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPAdConfiguration","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdConfiguration","title":"GFPAdConfiguration","navigatorTitle":[{"text":"GFPAdConfiguration","kind":"identifier"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"initWithConfiguration:","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithConfiguration:"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithConfiguration:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)GFPAdConfiguration","text":"GFPAdConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdConfiguration"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"aConfiguration"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","value":"GFPConfigDictionaryConverter","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPConfigDictionaryConverter\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPConfigDictionaryConverter\/fragments","value":[{"kind":"identifier","text":"GFPConfigDictionaryConverter"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPConfigDictionaryConverter\/navigatorTitle","value":[{"text":"GFPConfigDictionaryConverter","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"initWithConfiguration:","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPConfigDictionaryConverter~1init(configuration:)\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPConfigDictionaryConverter~1init(configuration:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithConfiguration:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdConfiguration\/title","value":"GFPAdConfiguration"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdConfiguration\/fragments","op":"replace","value":[{"text":"GFPAdConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"GFPAdConfiguration"}]}]}]}