{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfprichmediadataadtype\/newvideoextendv2"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfprichmediadataadtype\/newvideoextendv2"]}],"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRichMediaDataAdType\/newVideoExtendV2","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"role":"symbol","roleHeading":"Case","title":"GFPRichMediaDataAdType.newVideoExtendV2","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"newVideoExtendV2"}],"externalID":"c:@M@GFPSDK@E@GFPRichMediaDataAdType@GFPRichMediaDataAdTypeNewVideoExtendV2","symbolKind":"case","navigatorTitle":[{"text":"GFPRichMediaDataAdTypeNewVideoExtendV2","kind":"identifier"}],"modules":[{"name":"GFPSDK"}]},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"newVideoExtendV2"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRichMediaDataAdType"]]},"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRichMediaDataAdType/newVideoExtendV2":{"kind":"symbol","url":"\/documentation\/gfpsdk\/gfprichmediadataadtype\/newvideoextendv2","title":"GFPRichMediaDataAdType.newVideoExtendV2","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRichMediaDataAdType\/newVideoExtendV2","type":"topic","role":"symbol","abstract":[],"navigatorTitle":[{"text":"GFPRichMediaDataAdTypeNewVideoExtendV2","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"newVideoExtendV2","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRichMediaDataAdType":{"abstract":[],"navigatorTitle":[{"text":"GFPRichMediaDataAdType","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRichMediaDataAdType","type":"topic","role":"symbol","title":"GFPRichMediaDataAdType","kind":"symbol","url":"\/documentation\/gfpsdk\/gfprichmediadataadtype","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPRichMediaDataAdType","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"GFPRichMediaDataAdTypeNewVideoExtendV2","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GFPRichMediaDataAdTypeNewVideoExtendV2"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"GFPRichMediaDataAdTypeNewVideoExtendV2"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","value":"GFPRichMediaDataAdTypeNewVideoExtendV2","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRichMediaDataAdType~1newVideoExtendV2\/title"},{"value":[{"kind":"identifier","text":"GFPRichMediaDataAdTypeNewVideoExtendV2"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRichMediaDataAdType~1newVideoExtendV2\/fragments"},{"value":"GFPRichMediaDataAdType","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRichMediaDataAdType\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRichMediaDataAdType\/fragments","op":"replace","value":[{"kind":"identifier","text":"GFPRichMediaDataAdType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRichMediaDataAdType\/navigatorTitle","value":[{"kind":"identifier","text":"GFPRichMediaDataAdType"}]}]}]}