{"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpmediatype\/equatable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"title":"Equatable Implementations","modules":[{"name":"GFPSDK"}],"role":"collectionGroup","roleHeading":"API Collection"},"topicSections":[{"title":"Operators","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaType\/!=(_:_:)"],"anchor":"Operators","generated":true}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaType"]]},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaType\/Equatable-Implementations","interfaceLanguage":"swift"},"kind":"article","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPMediaType/!=(_:_:)":{"title":"!=(_:_:)","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaType\/!=(_:_:)","role":"symbol","kind":"symbol","abstract":[],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Self"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"type":"topic","url":"\/documentation\/gfpsdk\/gfpmediatype\/!=(_:_:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPMediaType":{"url":"\/documentation\/gfpsdk\/gfpmediatype","title":"GFPMediaType","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaType","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPMediaType"}],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPMediaType"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"patch":[{"value":"GFPMediaType","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMediaType\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMediaType\/fragments","op":"replace","value":[{"text":"GFPMediaType","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"GFPMediaType"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMediaType\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}