{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpmediatype\/richmedia"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpmediatype\/richmedia"]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaType"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"richMedia"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaType\/richMedia"},"kind":"symbol","metadata":{"title":"GFPMediaType.richMedia","role":"symbol","externalID":"c:@M@GFPSDK@E@GFPMediaType@GFPMediaTypeRichMedia","roleHeading":"Case","modules":[{"name":"GFPSDK"}],"symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"GFPMediaTypeRichMedia"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"richMedia","kind":"identifier"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPMediaType/richMedia":{"url":"\/documentation\/gfpsdk\/gfpmediatype\/richmedia","abstract":[],"title":"GFPMediaType.richMedia","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaType\/richMedia","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPMediaTypeRichMedia"}],"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"richMedia","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPMediaType":{"url":"\/documentation\/gfpsdk\/gfpmediatype","title":"GFPMediaType","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaType","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPMediaType"}],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPMediaType"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"value":"GFPMediaTypeRichMedia","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"GFPMediaTypeRichMedia","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"GFPMediaTypeRichMedia"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"GFPMediaTypeRichMedia","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMediaType~1richMedia\/title"},{"op":"replace","value":[{"kind":"identifier","text":"GFPMediaTypeRichMedia"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMediaType~1richMedia\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMediaType\/title","value":"GFPMediaType"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMediaType\/fragments","value":[{"text":"GFPMediaType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMediaType\/navigatorTitle","value":[{"text":"GFPMediaType","kind":"identifier"}],"op":"replace"}]}]}