{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearFactory\/appendList(_:)"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpnonlinearfactory\/appendlist(_:)"]},{"paths":["\/documentation\/gfpsdk\/gfpnonlinearfactory\/appendlist(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","metadata":{"modules":[{"name":"GFPSDK"}],"navigatorTitle":[{"kind":"identifier","text":"appendList:"}],"role":"symbol","title":"appendList(_:)","externalID":"c:objc(cs)GFPNonLinearFactory(im)appendList:","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"appendList"},{"text":"([","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPRemindAd","text":"GFPRemindAd","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"roleHeading":"Instance Method"},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearFactory"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"appendList"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"aRemindList","kind":"internalParam"},{"kind":"text","text":": ["},{"text":"GFPRemindAd","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRemindAd","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPRemindAd"},{"text":"])","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRemindAd":{"role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRemindAd","navigatorTitle":[{"text":"GFPRemindAd","kind":"identifier"}],"type":"topic","url":"\/documentation\/gfpsdk\/gfpremindad","title":"GFPRemindAd","abstract":[],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPRemindAd","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNonLinearFactory/appendList(_:)":{"navigatorTitle":[{"kind":"identifier","text":"appendList:"}],"role":"symbol","kind":"symbol","title":"appendList(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"appendList","kind":"identifier"},{"kind":"text","text":"(["},{"text":"GFPRemindAd","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPRemindAd"},{"text":"])","kind":"text"}],"type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearFactory\/appendList(_:)","abstract":[],"url":"\/documentation\/gfpsdk\/gfpnonlinearfactory\/appendlist(_:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNonLinearFactory":{"title":"GFPNonLinearFactory","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearFactory","role":"symbol","kind":"symbol","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPNonLinearFactory"}],"navigatorTitle":[{"text":"GFPNonLinearFactory","kind":"identifier"}],"type":"topic","url":"\/documentation\/gfpsdk\/gfpnonlinearfactory"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","value":"appendList:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"appendList:"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"appendList:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSArray<GFPRemindAd *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"text":"aRemindList","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRemindAd\/title","value":"GFPRemindAd"},{"op":"replace","value":[{"text":"GFPRemindAd","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRemindAd\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRemindAd\/navigatorTitle","op":"replace","value":[{"text":"GFPRemindAd","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearFactory~1appendList(_:)\/title","op":"replace","value":"appendList:"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearFactory~1appendList(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"appendList:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearFactory\/title","value":"GFPNonLinearFactory"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearFactory\/fragments","op":"replace","value":[{"kind":"identifier","text":"GFPNonLinearFactory"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearFactory\/navigatorTitle","value":[{"text":"GFPNonLinearFactory","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}