{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearFactory\/nonLinearView(withOffset:)"},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearFactory"]]},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"nonLinearView"},{"kind":"text","text":"("},{"text":"withOffset","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"offSet"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPNonLinearAdView","kind":"typeIdentifier","text":"GFPNonLinearAdView","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearAdView"},{"text":"?","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","metadata":{"title":"nonLinearView(withOffset:)","symbolKind":"method","externalID":"c:objc(cs)GFPNonLinearFactory(im)nonLinearViewWithOffset:","modules":[{"name":"GFPSDK"}],"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nonLinearView","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"withOffset"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":") -> "},{"text":"GFPNonLinearAdView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPNonLinearAdView"},{"text":"?","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"nonLinearViewWithOffset:","kind":"identifier"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpnonlinearfactory\/nonlinearview(withoffset:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpnonlinearfactory\/nonlinearview(withoffset:)"]}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNonLinearFactory/nonLinearView(withOffset:)":{"url":"\/documentation\/gfpsdk\/gfpnonlinearfactory\/nonlinearview(withoffset:)","navigatorTitle":[{"text":"nonLinearViewWithOffset:","kind":"identifier"}],"title":"nonLinearView(withOffset:)","abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearFactory\/nonLinearView(withOffset:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"nonLinearView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withOffset","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPNonLinearAdView","text":"GFPNonLinearAdView","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNonLinearAdView":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearAdView","title":"GFPNonLinearAdView","type":"topic","url":"\/documentation\/gfpsdk\/gfpnonlinearadview","abstract":[],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPNonLinearAdView"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPNonLinearAdView","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNonLinearFactory":{"title":"GFPNonLinearFactory","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearFactory","role":"symbol","kind":"symbol","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPNonLinearFactory"}],"navigatorTitle":[{"text":"GFPNonLinearFactory","kind":"identifier"}],"type":"topic","url":"\/documentation\/gfpsdk\/gfpnonlinearfactory"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"nonLinearViewWithOffset:","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"nonLinearViewWithOffset:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearAdView","text":"GFPNonLinearAdView","preciseIdentifier":"c:objc(cs)GFPNonLinearAdView","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"nonLinearViewWithOffset:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"text":"offSet","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearFactory~1nonLinearView(withOffset:)\/title","value":"nonLinearViewWithOffset:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearFactory~1nonLinearView(withOffset:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"nonLinearViewWithOffset:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearAdView\/title","value":"GFPNonLinearAdView"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearAdView\/fragments","value":[{"text":"GFPNonLinearAdView","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearAdView\/navigatorTitle","value":[{"kind":"identifier","text":"GFPNonLinearAdView"}],"op":"replace"},{"value":"GFPNonLinearFactory","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearFactory\/title","op":"replace"},{"value":[{"text":"GFPNonLinearFactory","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearFactory\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearFactory\/navigatorTitle","value":[{"text":"GFPNonLinearFactory","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}