{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpnonlinearfactory\/remindad(withoffset:)"]},{"paths":["\/documentation\/gfpsdk\/gfpnonlinearfactory\/remindad(withoffset:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"metadata":{"roleHeading":"Instance Method","navigatorTitle":[{"text":"remindAdWithOffset:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"remindAd","kind":"identifier"},{"kind":"text","text":"("},{"text":"withOffset","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":") -> ","kind":"text"},{"text":"GFPRemindAd","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPRemindAd"},{"kind":"text","text":"?"}],"modules":[{"name":"GFPSDK"}],"title":"remindAd(withOffset:)","symbolKind":"method","role":"symbol","externalID":"c:objc(cs)GFPNonLinearFactory(im)remindAdWithOffset:"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearFactory"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"remindAd","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withOffset","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"aOffset","kind":"internalParam"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":") -> ","kind":"text"},{"text":"GFPRemindAd","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRemindAd","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPRemindAd"},{"kind":"text","text":"?"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearFactory\/remindAd(withOffset:)"},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRemindAd":{"role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRemindAd","navigatorTitle":[{"text":"GFPRemindAd","kind":"identifier"}],"type":"topic","url":"\/documentation\/gfpsdk\/gfpremindad","title":"GFPRemindAd","abstract":[],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPRemindAd","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNonLinearFactory":{"title":"GFPNonLinearFactory","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearFactory","role":"symbol","kind":"symbol","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPNonLinearFactory"}],"navigatorTitle":[{"text":"GFPNonLinearFactory","kind":"identifier"}],"type":"topic","url":"\/documentation\/gfpsdk\/gfpnonlinearfactory"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNonLinearFactory/remindAd(withOffset:)":{"type":"topic","url":"\/documentation\/gfpsdk\/gfpnonlinearfactory\/remindad(withoffset:)","navigatorTitle":[{"kind":"identifier","text":"remindAdWithOffset:"}],"abstract":[],"kind":"symbol","title":"remindAd(withOffset:)","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearFactory\/remindAd(withOffset:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"remindAd"},{"text":"(","kind":"text"},{"text":"withOffset","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"GFPRemindAd","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPRemindAd"},{"text":"?","kind":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"remindAdWithOffset:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"remindAdWithOffset:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"GFPRemindAd","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRemindAd","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPRemindAd"},{"text":" *) ","kind":"text"},{"text":"remindAdWithOffset:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"aOffset"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"GFPRemindAd","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRemindAd\/title"},{"value":[{"text":"GFPRemindAd","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRemindAd\/fragments","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"GFPRemindAd"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRemindAd\/navigatorTitle"},{"value":"GFPNonLinearFactory","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearFactory\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearFactory\/fragments","op":"replace","value":[{"text":"GFPNonLinearFactory","kind":"identifier"}]},{"op":"replace","value":[{"text":"GFPNonLinearFactory","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearFactory\/navigatorTitle"},{"op":"replace","value":"remindAdWithOffset:","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearFactory~1remindAd(withOffset:)\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearFactory~1remindAd(withOffset:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"remindAdWithOffset:"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}