{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearFactory\/update(_:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"update"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"aVideoInfo"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)GFPVideoAdInfo","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdInfo","text":"GFPVideoAdInfo"},{"kind":"text","text":")"}]}]}],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpnonlinearfactory\/update(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpnonlinearfactory\/update(_:)"]}],"metadata":{"role":"symbol","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"update","kind":"identifier"},{"text":"(","kind":"text"},{"text":"GFPVideoAdInfo","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoAdInfo"},{"kind":"text","text":")"}],"externalID":"c:objc(cs)GFPNonLinearFactory(im)updateVideoAdInfo:","modules":[{"name":"GFPSDK"}],"title":"update(_:)","navigatorTitle":[{"text":"updateVideoAdInfo:","kind":"identifier"}],"roleHeading":"Instance Method"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearFactory"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdInfo":{"kind":"symbol","title":"GFPVideoAdInfo","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdInfo","role":"symbol","navigatorTitle":[{"text":"GFPVideoAdInfo","kind":"identifier"}],"type":"topic","url":"\/documentation\/gfpsdk\/gfpvideoadinfo","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPVideoAdInfo"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNonLinearFactory":{"title":"GFPNonLinearFactory","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearFactory","role":"symbol","kind":"symbol","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPNonLinearFactory"}],"navigatorTitle":[{"text":"GFPNonLinearFactory","kind":"identifier"}],"type":"topic","url":"\/documentation\/gfpsdk\/gfpnonlinearfactory"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNonLinearFactory/update(_:)":{"url":"\/documentation\/gfpsdk\/gfpnonlinearfactory\/update(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"update"},{"kind":"text","text":"("},{"text":"GFPVideoAdInfo","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoAdInfo"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNonLinearFactory\/update(_:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"updateVideoAdInfo:"}],"role":"symbol","title":"update(_:)","type":"topic","abstract":[]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"value":"updateVideoAdInfo:","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateVideoAdInfo:"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"updateVideoAdInfo:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)GFPVideoAdInfo","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdInfo","text":"GFPVideoAdInfo"},{"text":" *) ","kind":"text"},{"text":"aVideoInfo","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"value":"GFPVideoAdInfo","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdInfo\/title","op":"replace"},{"value":[{"kind":"identifier","text":"GFPVideoAdInfo"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdInfo\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdInfo\/navigatorTitle","value":[{"text":"GFPVideoAdInfo","kind":"identifier"}]},{"op":"replace","value":"GFPNonLinearFactory","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearFactory\/title"},{"op":"replace","value":[{"kind":"identifier","text":"GFPNonLinearFactory"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearFactory\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearFactory\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"GFPNonLinearFactory"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearFactory~1update(_:)\/title","value":"updateVideoAdInfo:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"updateVideoAdInfo:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNonLinearFactory~1update(_:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}