{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdManager"]]},"metadata":{"role":"symbol","externalID":"c:objc(cs)GFPRewardedAdManager(im)initWithUnitID:adParam:","modules":[{"name":"GFPSDK"}],"symbolKind":"init","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"unitID"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"adParam","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdParam","text":"GFPAdParam"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"initWithUnitID:adParam:","kind":"identifier"}],"roleHeading":"Initializer","title":"init(unitID:adParam:)"},"variants":[{"paths":["\/documentation\/gfpsdk\/gfprewardedadmanager\/init(unitid:adparam:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfprewardedadmanager\/init(unitid:adparam:)"]}],"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdManager\/init(unitID:adParam:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"kind":"externalParam","text":"unitID"},{"kind":"text","text":" "},{"text":"adUnitID","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"adParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"GFPAdParam","preciseIdentifier":"c:objc(cs)GFPAdParam","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdParam"},{"kind":"text","text":")"}],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRewardedAdManager":{"title":"GFPRewardedAdManager","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdManager","url":"\/documentation\/gfpsdk\/gfprewardedadmanager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPRewardedAdManager"}],"kind":"symbol","abstract":[],"role":"symbol","navigatorTitle":[{"text":"GFPRewardedAdManager","kind":"identifier"}],"type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdParam":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdParam","abstract":[],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPAdParam"}],"navigatorTitle":[{"text":"GFPAdParam","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpadparam","type":"topic","kind":"symbol","title":"GFPAdParam"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRewardedAdManager/init(unitID:adParam:)":{"kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdManager\/init(unitID:adParam:)","role":"symbol","title":"init(unitID:adParam:)","type":"topic","abstract":[],"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"unitID","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"adParam","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPAdParam","kind":"typeIdentifier","text":"GFPAdParam"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"initWithUnitID:adParam:"}],"url":"\/documentation\/gfpsdk\/gfprewardedadmanager\/init(unitid:adparam:)"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"initWithUnitID:adParam:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithUnitID:adParam:"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"text":"initWithUnitID:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"adUnitID","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"adParam:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdParam","text":"GFPAdParam","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdParam"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"adParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"value":"GFPRewardedAdManager","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdManager\/title"},{"value":[{"kind":"identifier","text":"GFPRewardedAdManager"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdManager\/fragments"},{"value":[{"kind":"identifier","text":"GFPRewardedAdManager"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdManager\/navigatorTitle"},{"op":"replace","value":"GFPAdParam","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdParam\/title"},{"value":[{"text":"GFPAdParam","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdParam\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdParam\/navigatorTitle","value":[{"text":"GFPAdParam","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdManager~1init(unitID:adParam:)\/title","op":"replace","value":"initWithUnitID:adParam:"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdManager~1init(unitID:adParam:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithUnitID:adParam:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}