{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"show"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"rootViewController"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"},{"text":")","kind":"text"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/gfpsdk\/gfprewardedadmanager\/show(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfprewardedadmanager\/show(_:)"]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdManager"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdManager\/show(_:)"},"kind":"symbol","sections":[],"metadata":{"title":"show(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"show"},{"kind":"text","text":"("},{"text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier"},{"kind":"text","text":")"}],"roleHeading":"Instance Method","role":"symbol","externalID":"c:objc(cs)GFPRewardedAdManager(im)show:","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"show:"}],"modules":[{"name":"GFPSDK"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRewardedAdManager/show(_:)":{"navigatorTitle":[{"kind":"identifier","text":"show:"}],"type":"topic","title":"show(_:)","kind":"symbol","url":"\/documentation\/gfpsdk\/gfprewardedadmanager\/show(_:)","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdManager\/show(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"show","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier","text":"UIViewController"},{"text":")","kind":"text"}],"role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRewardedAdManager":{"title":"GFPRewardedAdManager","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRewardedAdManager","url":"\/documentation\/gfpsdk\/gfprewardedadmanager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPRewardedAdManager"}],"kind":"symbol","abstract":[],"role":"symbol","navigatorTitle":[{"text":"GFPRewardedAdManager","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"show:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"kind":"text","text":"- "},{"text":"show:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"show:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier","text":"UIViewController"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"rootViewController"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdManager~1show(_:)\/title","value":"show:"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdManager~1show(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"show:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdManager\/title","value":"GFPRewardedAdManager"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdManager\/fragments","value":[{"kind":"identifier","text":"GFPRewardedAdManager"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRewardedAdManager\/navigatorTitle","value":[{"kind":"identifier","text":"GFPRewardedAdManager"}],"op":"replace"}]}]}