{"metadata":{"symbolKind":"method","title":"initWithInlineElement:linearElement:","modules":[{"name":"GFPSDK"}],"role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"initWithInlineElement:linearElement:","kind":"identifier"}],"roleHeading":"Instance Method","navigatorTitle":[{"text":"initWithInlineElement:linearElement:","kind":"identifier"}],"externalID":"c:objc(cs)GFPTrackingURLs(im)initWithInlineElement:linearElement:"},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfptrackingurls\/initwithinlineelement:linearelement:"]}],"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPTrackingURLs\/initWithInlineElement:linearElement:","interfaceLanguage":"occ"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithInlineElement:"},{"text":"(","kind":"text"},{"text":"DDXMLElement","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)DDXMLElement"},{"kind":"text","text":" *) "},{"text":"aElement","kind":"internalParam"},{"kind":"text","text":" "},{"text":"linearElement:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DDXMLElement","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)DDXMLElement"},{"kind":"text","text":" *) "},{"text":"aLinearElement","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPTrackingURLs"]]},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPTrackingURLs":{"abstract":[],"type":"topic","title":"GFPTrackingURLs","role":"symbol","url":"\/documentation\/gfpsdk\/gfptrackingurls","kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPTrackingURLs","navigatorTitle":[{"kind":"identifier","text":"GFPTrackingURLs"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"GFPTrackingURLs","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPTrackingURLs/initWithInlineElement:linearElement:":{"fragments":[{"kind":"text","text":"- "},{"text":"initWithInlineElement:linearElement:","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"initWithInlineElement:linearElement:","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPTrackingURLs\/initWithInlineElement:linearElement:","abstract":[],"role":"symbol","url":"\/documentation\/gfpsdk\/gfptrackingurls\/initwithinlineelement:linearelement:","title":"initWithInlineElement:linearElement:","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPTrackingURLs\/title","value":"GFPTrackingURLs"},{"op":"replace","value":[{"kind":"identifier","text":"GFPTrackingURLs"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPTrackingURLs\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPTrackingURLs\/navigatorTitle","value":[{"kind":"identifier","text":"GFPTrackingURLs"}],"op":"replace"}]}]}