{"variants":[{"paths":["\/documentation\/gfpsdk\/gfptrackingurls\/init(viewtrackings:errortrackings:clickthrough:clicktracking:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gfpsdk\/gfptrackingurls\/init(viewtrackings:errortrackings:clickthrough:clicktracking:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"viewTrackings","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"aViewTrackings"},{"text":": [","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"], "},{"text":"errorTrackings","kind":"externalParam"},{"kind":"text","text":" "},{"text":"aErrorTrackings","kind":"internalParam"},{"kind":"text","text":": ["},{"text":"Any","kind":"keyword"},{"text":"], ","kind":"text"},{"text":"clickThrough","kind":"externalParam"},{"kind":"text","text":" "},{"text":"aClickThrough","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"text":"clickTracking","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"aClickTrackings"},{"text":": [","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"])"}]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPTrackingURLs\/init(viewTrackings:errorTrackings:clickThrough:clickTracking:)"},"metadata":{"externalID":"c:objc(cs)GFPTrackingURLs(im)initWithViewTrackings:errorTrackings:clickThrough:clickTracking:","role":"symbol","modules":[{"name":"GFPSDK"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"viewTrackings","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"errorTrackings"},{"text":": [","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"clickThrough"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"clickTracking"},{"kind":"text","text":": ["},{"text":"Any","kind":"keyword"},{"kind":"text","text":"])"}],"navigatorTitle":[{"text":"initWithViewTrackings:errorTrackings:clickThrough:clickTracking:","kind":"identifier"}],"title":"init(viewTrackings:errorTrackings:clickThrough:clickTracking:)","symbolKind":"init","roleHeading":"Initializer"},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPTrackingURLs"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPTrackingURLs/init(viewTrackings:errorTrackings:clickThrough:clickTracking:)":{"url":"\/documentation\/gfpsdk\/gfptrackingurls\/init(viewtrackings:errortrackings:clickthrough:clicktracking:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"viewTrackings"},{"text":": [","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"errorTrackings"},{"text":": [","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"clickThrough"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"clickTracking"},{"kind":"text","text":": ["},{"text":"Any","kind":"keyword"},{"text":"])","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"initWithViewTrackings:errorTrackings:clickThrough:clickTracking:"}],"title":"init(viewTrackings:errorTrackings:clickThrough:clickTracking:)","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPTrackingURLs\/init(viewTrackings:errorTrackings:clickThrough:clickTracking:)","abstract":[],"type":"topic","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPTrackingURLs":{"abstract":[],"type":"topic","title":"GFPTrackingURLs","role":"symbol","url":"\/documentation\/gfpsdk\/gfptrackingurls","kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPTrackingURLs","navigatorTitle":[{"kind":"identifier","text":"GFPTrackingURLs"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"GFPTrackingURLs","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithViewTrackings:errorTrackings:clickThrough:clickTracking:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithViewTrackings:errorTrackings:clickThrough:clickTracking:"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithViewTrackings:"},{"kind":"text","text":"("},{"text":"NSArray","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"aViewTrackings"},{"text":" ","kind":"text"},{"text":"errorTrackings:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSArray","text":"NSArray","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"aErrorTrackings","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"clickThrough:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"aClickThrough","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"clickTracking:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"aClickTrackings"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"initWithViewTrackings:errorTrackings:clickThrough:clickTracking:","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPTrackingURLs~1init(viewTrackings:errorTrackings:clickThrough:clickTracking:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithViewTrackings:errorTrackings:clickThrough:clickTracking:"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPTrackingURLs~1init(viewTrackings:errorTrackings:clickThrough:clickTracking:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPTrackingURLs\/title","value":"GFPTrackingURLs"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPTrackingURLs\/fragments","value":[{"text":"GFPTrackingURLs","kind":"identifier"}],"op":"replace"},{"value":[{"text":"GFPTrackingURLs","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPTrackingURLs\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}