{"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPTrackingURLs"]]},"metadata":{"externalID":"c:objc(cs)GFPTrackingURLs(im)initWithIconElement:","modules":[{"name":"GFPSDK"}],"roleHeading":"Instance Method","title":"initWithIconElement:","role":"symbol","symbolKind":"method","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithIconElement:"}],"navigatorTitle":[{"kind":"identifier","text":"initWithIconElement:"}]},"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithIconElement:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)DDXMLElement","text":"DDXMLElement"},{"text":" *) ","kind":"text"},{"text":"aElemnt","kind":"internalParam"},{"kind":"text","text":";"}]}]}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPTrackingURLs\/initWithIconElement:"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfptrackingurls\/initwithiconelement:"]}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPTrackingURLs/initWithIconElement:":{"navigatorTitle":[{"kind":"identifier","text":"initWithIconElement:"}],"title":"initWithIconElement:","abstract":[],"type":"topic","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPTrackingURLs\/initWithIconElement:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithIconElement:","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfptrackingurls\/initwithiconelement:","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPTrackingURLs":{"abstract":[],"type":"topic","title":"GFPTrackingURLs","role":"symbol","url":"\/documentation\/gfpsdk\/gfptrackingurls","kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPTrackingURLs","navigatorTitle":[{"kind":"identifier","text":"GFPTrackingURLs"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"GFPTrackingURLs","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"GFPTrackingURLs","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPTrackingURLs\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPTrackingURLs\/fragments","value":[{"text":"GFPTrackingURLs","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPTrackingURLs\/navigatorTitle","value":[{"kind":"identifier","text":"GFPTrackingURLs"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}