{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpvideosourcestatus\/completed"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpvideosourcestatus\/completed"]}],"metadata":{"title":"completed","role":"symbol","modules":[{"name":"GFPSDK"}],"externalID":"c:@E@GFPVideoSourceStatus@GFPVideoSourceStatusCompleted","navigatorTitle":[{"kind":"identifier","text":"GFPVideoSourceStatusCompleted"}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"completed","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@GFPVideoSourceStatus","kind":"typeIdentifier","text":"GFPVideoSourceStatus"}],"roleHeading":"Type Property","symbolKind":"property"},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoSourceStatus"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"completed"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@GFPVideoSourceStatus","text":"GFPVideoSourceStatus","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoSourceStatus","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoSourceStatus\/completed","interfaceLanguage":"swift"},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoSourceStatus":{"navigatorTitle":[{"kind":"identifier","text":"GFPVideoSourceStatus"}],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPVideoSourceStatus"}],"abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoSourceStatus","url":"\/documentation\/gfpsdk\/gfpvideosourcestatus","title":"GFPVideoSourceStatus","kind":"symbol","role":"symbol","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoSourceStatus/completed":{"type":"topic","url":"\/documentation\/gfpsdk\/gfpvideosourcestatus\/completed","role":"symbol","abstract":[],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"completed","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GFPVideoSourceStatus","preciseIdentifier":"c:@E@GFPVideoSourceStatus"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoSourceStatus\/completed","title":"completed","navigatorTitle":[{"kind":"identifier","text":"GFPVideoSourceStatusCompleted"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"value":"GFPVideoSourceStatusCompleted","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"GFPVideoSourceStatusCompleted"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"GFPVideoSourceStatusCompleted"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoSourceStatus\/title","op":"replace","value":"GFPVideoSourceStatus"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoSourceStatus\/fragments","value":[{"text":"GFPVideoSourceStatus","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoSourceStatus\/navigatorTitle","op":"replace","value":[{"text":"GFPVideoSourceStatus","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoSourceStatus~1completed\/title","value":"GFPVideoSourceStatusCompleted","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoSourceStatus~1completed\/fragments","op":"replace","value":[{"kind":"identifier","text":"GFPVideoSourceStatusCompleted"}]}]}]}