{"sections":[],"metadata":{"symbolKind":"case","title":"GFPVideoSourceStatusNotLoaded","modules":[{"name":"GFPSDK"}],"fragments":[{"text":"GFPVideoSourceStatusNotLoaded","kind":"identifier"}],"navigatorTitle":[{"text":"GFPVideoSourceStatusNotLoaded","kind":"identifier"}],"externalID":"c:@E@GFPVideoSourceStatus@GFPVideoSourceStatusNotLoaded","role":"symbol","roleHeading":"Enumeration Case"},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoSourceStatus\/GFPVideoSourceStatusNotLoaded","interfaceLanguage":"occ"},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoSourceStatus"]]},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpvideosourcestatus\/gfpvideosourcestatusnotloaded"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"GFPVideoSourceStatusNotLoaded"}]}],"kind":"declarations"}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoSourceStatus/GFPVideoSourceStatusNotLoaded":{"type":"topic","url":"\/documentation\/gfpsdk\/gfpvideosourcestatus\/gfpvideosourcestatusnotloaded","role":"symbol","abstract":[],"fragments":[{"kind":"identifier","text":"GFPVideoSourceStatusNotLoaded"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoSourceStatus\/GFPVideoSourceStatusNotLoaded","title":"GFPVideoSourceStatusNotLoaded","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoSourceStatus":{"navigatorTitle":[{"kind":"identifier","text":"GFPVideoSourceStatus"}],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPVideoSourceStatus"}],"abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoSourceStatus","url":"\/documentation\/gfpsdk\/gfpvideosourcestatus","title":"GFPVideoSourceStatus","kind":"symbol","role":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"GFPVideoSourceStatus","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoSourceStatus\/title"},{"value":[{"kind":"identifier","text":"GFPVideoSourceStatus"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoSourceStatus\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoSourceStatus\/navigatorTitle","value":[{"text":"GFPVideoSourceStatus","kind":"identifier"}]}]}]}