{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoSourceStatus"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pause","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoSourceStatus","text":"GFPVideoSourceStatus","preciseIdentifier":"c:@E@GFPVideoSourceStatus","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"modules":[{"name":"GFPSDK"}],"role":"symbol","navigatorTitle":[{"text":"GFPVideoSourceStatusPause","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"pause","kind":"identifier"},{"kind":"text","text":": "},{"text":"GFPVideoSourceStatus","kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPVideoSourceStatus"}],"symbolKind":"property","title":"pause","roleHeading":"Type Property","externalID":"c:@E@GFPVideoSourceStatus@GFPVideoSourceStatusPause"},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoSourceStatus\/pause"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpvideosourcestatus\/pause"]},{"paths":["\/documentation\/gfpsdk\/gfpvideosourcestatus\/pause"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoSourceStatus":{"navigatorTitle":[{"kind":"identifier","text":"GFPVideoSourceStatus"}],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPVideoSourceStatus"}],"abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoSourceStatus","url":"\/documentation\/gfpsdk\/gfpvideosourcestatus","title":"GFPVideoSourceStatus","kind":"symbol","role":"symbol","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoSourceStatus/pause":{"abstract":[],"title":"pause","url":"\/documentation\/gfpsdk\/gfpvideosourcestatus\/pause","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pause"},{"kind":"text","text":": "},{"text":"GFPVideoSourceStatus","kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPVideoSourceStatus"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoSourceStatus\/pause","kind":"symbol","navigatorTitle":[{"text":"GFPVideoSourceStatusPause","kind":"identifier"}],"role":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"value":"GFPVideoSourceStatusPause","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"GFPVideoSourceStatusPause"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"GFPVideoSourceStatusPause","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoSourceStatus\/title","value":"GFPVideoSourceStatus","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoSourceStatus\/fragments","op":"replace","value":[{"kind":"identifier","text":"GFPVideoSourceStatus"}]},{"op":"replace","value":[{"kind":"identifier","text":"GFPVideoSourceStatus"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoSourceStatus\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoSourceStatus~1pause\/title","op":"replace","value":"GFPVideoSourceStatusPause"},{"value":[{"text":"GFPVideoSourceStatusPause","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoSourceStatus~1pause\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}