{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"weak"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"carouselHeightDelegate","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@GFPSDK@objc(pl)GFPCarouselHeightDelegate","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPCarouselHeightDelegate","text":"GFPCarouselHeightDelegate","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpmediadata\/carouselheightdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpmediadata\/carouselheightdelegate"]}],"metadata":{"symbolKind":"property","title":"carouselHeightDelegate","modules":[{"name":"GFPSDK"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"carouselHeightDelegate","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GFPCarouselHeightDelegate","preciseIdentifier":"c:@M@GFPSDK@objc(pl)GFPCarouselHeightDelegate"},{"text":"?","kind":"text"}],"roleHeading":"Instance Property","navigatorTitle":[{"text":"carouselHeightDelegate","kind":"identifier"}],"externalID":"c:@M@GFPSDK@objc(cs)GFPMediaData(py)carouselHeightDelegate"},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaData"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaData\/carouselHeightDelegate","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPCarouselHeightDelegate":{"navigatorTitle":[{"text":"GFPCarouselHeightDelegate","kind":"identifier"}],"type":"topic","title":"GFPCarouselHeightDelegate","kind":"symbol","url":"\/documentation\/gfpsdk\/gfpcarouselheightdelegate","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPCarouselHeightDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPCarouselHeightDelegate"}],"role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPMediaData":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaData","url":"\/documentation\/gfpsdk\/gfpmediadata","abstract":[],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"GFPMediaData","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"GFPMediaData"}],"title":"GFPMediaData"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPMediaData/carouselHeightDelegate":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaData\/carouselHeightDelegate","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"carouselHeightDelegate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"GFPCarouselHeightDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@GFPSDK@objc(pl)GFPCarouselHeightDelegate"},{"text":"?","kind":"text"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"carouselHeightDelegate"}],"url":"\/documentation\/gfpsdk\/gfpmediadata\/carouselheightdelegate","title":"carouselHeightDelegate"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"carouselHeightDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"carouselHeightDelegate"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"weak","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:Qo@M@GFPSDK@objc(pl)GFPCarouselHeightDelegate","text":"id<GFPCarouselHeightDelegate>","kind":"typeIdentifier"},{"kind":"text","text":" "},{"kind":"identifier","text":"carouselHeightDelegate"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"value":"GFPCarouselHeightDelegate","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPCarouselHeightDelegate\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPCarouselHeightDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"GFPCarouselHeightDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPCarouselHeightDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"GFPCarouselHeightDelegate"}]},{"value":"GFPMediaData","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMediaData\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMediaData\/fragments","value":[{"kind":"identifier","text":"GFPMediaData"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMediaData\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"GFPMediaData"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMediaData~1carouselHeightDelegate\/title","value":"carouselHeightDelegate"},{"value":[{"text":"carouselHeightDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMediaData~1carouselHeightDelegate\/fragments","op":"replace"}]}]}