{"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaData\/createRichMediaInfo()"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(createRichMediaInfo) ","kind":"text"},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"createRichMediaInfo"},{"kind":"text","text":"() -> "},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaData","preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPMediaData","kind":"typeIdentifier","text":"GFPMediaData"}],"platforms":["iOS"]}]}],"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpmediadata\/createrichmediainfo()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpmediadata\/createrichmediainfo()"]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaData"]]},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"createRichMediaInfo"}],"title":"createRichMediaInfo()","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"createRichMediaInfo","kind":"identifier"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPMediaData","text":"GFPMediaData","kind":"typeIdentifier"}],"modules":[{"name":"GFPSDK"}],"externalID":"c:@M@GFPSDK@objc(cs)GFPMediaData(cm)createRichMediaInfo","role":"symbol","roleHeading":"Type Method","symbolKind":"method"},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPMediaData":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaData","url":"\/documentation\/gfpsdk\/gfpmediadata","abstract":[],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"GFPMediaData","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"GFPMediaData"}],"title":"GFPMediaData"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPMediaData/createRichMediaInfo()":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"createRichMediaInfo"},{"kind":"text","text":"() -> "},{"text":"GFPMediaData","kind":"typeIdentifier","preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPMediaData"}],"navigatorTitle":[{"text":"createRichMediaInfo","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaData\/createRichMediaInfo()","kind":"symbol","type":"topic","role":"symbol","abstract":[],"url":"\/documentation\/gfpsdk\/gfpmediadata\/createrichmediainfo()","title":"createRichMediaInfo()"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"value":"createRichMediaInfo","op":"replace","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"createRichMediaInfo","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaData","text":"GFPMediaData","kind":"typeIdentifier","preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPMediaData"},{"kind":"text","text":" *) "},{"text":"createRichMediaInfo","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMediaData\/title","value":"GFPMediaData","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMediaData\/fragments","value":[{"kind":"identifier","text":"GFPMediaData"}],"op":"replace"},{"op":"replace","value":[{"text":"GFPMediaData","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMediaData\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMediaData~1createRichMediaInfo()\/title","value":"createRichMediaInfo"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMediaData~1createRichMediaInfo()\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createRichMediaInfo"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}