{"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaData"]]},"sections":[],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpmediadata\/createvideoinfo(videocontroller:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpmediadata\/createvideoinfo(videocontroller:)"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(createVideoInfoWith:) ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"createVideoInfo","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"videoController"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoController","preciseIdentifier":"c:objc(cs)GFPVideoController","text":"GFPVideoController"},{"text":"?) -> ","kind":"text"},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaData","text":"GFPMediaData","kind":"typeIdentifier","preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPMediaData"}]}],"kind":"declarations"}],"metadata":{"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"createVideoInfo"},{"text":"(","kind":"text"},{"text":"videoController","kind":"externalParam"},{"kind":"text","text":": "},{"text":"GFPVideoController","preciseIdentifier":"c:objc(cs)GFPVideoController","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"GFPMediaData","preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPMediaData","kind":"typeIdentifier"}],"title":"createVideoInfo(videoController:)","roleHeading":"Type Method","modules":[{"name":"GFPSDK"}],"externalID":"c:@M@GFPSDK@objc(cs)GFPMediaData(cm)createVideoInfoWith:","symbolKind":"method","navigatorTitle":[{"text":"createVideoInfoWith:","kind":"identifier"}],"role":"symbol"},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaData\/createVideoInfo(videoController:)","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPMediaData":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaData","url":"\/documentation\/gfpsdk\/gfpmediadata","abstract":[],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"GFPMediaData","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"GFPMediaData"}],"title":"GFPMediaData"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoController":{"url":"\/documentation\/gfpsdk\/gfpvideocontroller","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPVideoController"}],"role":"symbol","abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"GFPVideoController"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoController","title":"GFPVideoController","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPMediaData/createVideoInfo(videoController:)":{"abstract":[],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createVideoInfo","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"videoController"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)GFPVideoController","text":"GFPVideoController","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPMediaData","kind":"typeIdentifier","text":"GFPMediaData"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaData\/createVideoInfo(videoController:)","title":"createVideoInfo(videoController:)","url":"\/documentation\/gfpsdk\/gfpmediadata\/createvideoinfo(videocontroller:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"createVideoInfoWith:"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"path":"\/metadata\/title","op":"replace","value":"createVideoInfoWith:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"text":"createVideoInfoWith:","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"text":"GFPMediaData","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaData","preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPMediaData"},{"text":" *) ","kind":"text"},{"text":"createVideoInfoWith:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoController","text":"GFPVideoController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoController"},{"text":" *) ","kind":"text"},{"text":"videoController","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMediaData\/title","value":"GFPMediaData","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMediaData\/fragments","value":[{"kind":"identifier","text":"GFPMediaData"}],"op":"replace"},{"value":[{"kind":"identifier","text":"GFPMediaData"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMediaData\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoController\/title","value":"GFPVideoController","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoController\/fragments","value":[{"text":"GFPVideoController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoController\/navigatorTitle","value":[{"text":"GFPVideoController","kind":"identifier"}]},{"value":"createVideoInfoWith:","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMediaData~1createVideoInfo(videoController:)\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMediaData~1createVideoInfo(videoController:)\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createVideoInfoWith:"}]}]}]}