{"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaData\/createC2SInfo(type:c2sAspectRatio:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaData"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(createC2SInfoWith:aspectRatio:) ","kind":"text"},{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"createC2SInfo"},{"text":"(","kind":"text"},{"text":"type","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaType","text":"GFPMediaType","kind":"typeIdentifier","preciseIdentifier":"c:@M@GFPSDK@E@GFPMediaType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"c2sAspectRatio"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier","text":"CGFloat"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPMediaData","text":"GFPMediaData","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaData","kind":"typeIdentifier"}]}]}],"metadata":{"role":"symbol","modules":[{"name":"GFPSDK"}],"roleHeading":"Type Method","title":"createC2SInfo(type:c2sAspectRatio:)","externalID":"c:@M@GFPSDK@objc(cs)GFPMediaData(cm)createC2SInfoWith:aspectRatio:","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"createC2SInfoWith:aspectRatio:"}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createC2SInfo","kind":"identifier"},{"kind":"text","text":"("},{"text":"type","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@GFPSDK@E@GFPMediaType","text":"GFPMediaType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"c2sAspectRatio"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"},{"kind":"text","text":") -> "},{"text":"GFPMediaData","preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPMediaData","kind":"typeIdentifier"}]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpmediadata\/createc2sinfo(type:c2saspectratio:)"]},{"paths":["\/documentation\/gfpsdk\/gfpmediadata\/createc2sinfo(type:c2saspectratio:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPMediaType":{"url":"\/documentation\/gfpsdk\/gfpmediatype","title":"GFPMediaType","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaType","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPMediaType"}],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPMediaType"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPMediaData":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaData","url":"\/documentation\/gfpsdk\/gfpmediadata","abstract":[],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"GFPMediaData","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"GFPMediaData"}],"title":"GFPMediaData"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPMediaData/createC2SInfo(type:c2sAspectRatio:)":{"kind":"symbol","type":"topic","abstract":[],"url":"\/documentation\/gfpsdk\/gfpmediadata\/createc2sinfo(type:c2saspectratio:)","navigatorTitle":[{"kind":"identifier","text":"createC2SInfoWith:aspectRatio:"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"createC2SInfo","kind":"identifier"},{"kind":"text","text":"("},{"text":"type","kind":"externalParam"},{"kind":"text","text":": "},{"text":"GFPMediaType","preciseIdentifier":"c:@M@GFPSDK@E@GFPMediaType","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"c2sAspectRatio"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":") -> "},{"text":"GFPMediaData","kind":"typeIdentifier","preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPMediaData"}],"title":"createC2SInfo(type:c2sAspectRatio:)","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaData\/createC2SInfo(type:c2sAspectRatio:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"createC2SInfoWith:aspectRatio:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createC2SInfoWith:aspectRatio:"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"text":"GFPMediaData","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaData","preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPMediaData"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"createC2SInfoWith:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@M@GFPSDK@E@GFPMediaType","text":"GFPMediaType","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPMediaType"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"type"},{"text":" ","kind":"text"},{"kind":"identifier","text":"aspectRatio:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@CGFloat","kind":"typeIdentifier","text":"CGFloat"},{"kind":"text","text":") "},{"text":"c2sAspectRatio","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"GFPMediaType","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMediaType\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMediaType\/fragments","value":[{"kind":"identifier","text":"GFPMediaType"}]},{"value":[{"kind":"identifier","text":"GFPMediaType"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMediaType\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMediaData\/title","op":"replace","value":"GFPMediaData"},{"value":[{"kind":"identifier","text":"GFPMediaData"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMediaData\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMediaData\/navigatorTitle","value":[{"kind":"identifier","text":"GFPMediaData"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMediaData~1createC2SInfo(type:c2sAspectRatio:)\/title","value":"createC2SInfoWith:aspectRatio:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPMediaData~1createC2SInfo(type:c2sAspectRatio:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"createC2SInfoWith:aspectRatio:","kind":"identifier"}]}]}]}