{"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRemindTextType"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"foldable"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@GFPRemindTextType","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRemindTextType","text":"GFPRemindTextType","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpremindtexttype\/foldable"]},{"paths":["\/documentation\/gfpsdk\/gfpremindtexttype\/foldable"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRemindTextType\/foldable"},"kind":"symbol","metadata":{"role":"symbol","modules":[{"name":"GFPSDK"}],"externalID":"c:@E@GFPRemindTextType@GFPRemindFoldable","symbolKind":"property","title":"foldable","navigatorTitle":[{"text":"GFPRemindFoldable","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"foldable"},{"text":": ","kind":"text"},{"text":"GFPRemindTextType","kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPRemindTextType"}],"roleHeading":"Type Property"},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRemindTextType/foldable":{"abstract":[],"type":"topic","title":"foldable","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"foldable","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@GFPRemindTextType","kind":"typeIdentifier","text":"GFPRemindTextType"}],"url":"\/documentation\/gfpsdk\/gfpremindtexttype\/foldable","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRemindTextType\/foldable","navigatorTitle":[{"text":"GFPRemindFoldable","kind":"identifier"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRemindTextType":{"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPRemindTextType","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPRemindTextType"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRemindTextType","abstract":[],"role":"symbol","url":"\/documentation\/gfpsdk\/gfpremindtexttype","title":"GFPRemindTextType","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"GFPRemindFoldable"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"GFPRemindFoldable","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"GFPRemindFoldable"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRemindTextType~1foldable\/title","op":"replace","value":"GFPRemindFoldable"},{"value":[{"text":"GFPRemindFoldable","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRemindTextType~1foldable\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRemindTextType\/title","value":"GFPRemindTextType"},{"op":"replace","value":[{"text":"GFPRemindTextType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRemindTextType\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRemindTextType\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"GFPRemindTextType"}]}]}]}