{"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInternalResponseInfo"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpinternalresponseinfo\/recordloademptytime()"]},{"paths":["\/documentation\/gfpsdk\/gfpinternalresponseinfo\/recordloademptytime()"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"recordLoadEmptyTime","kind":"identifier"},{"kind":"text","text":"()"}],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInternalResponseInfo\/recordLoadEmptyTime()"},"metadata":{"externalID":"c:objc(cs)GFPInternalResponseInfo(im)recordLoadEmptyTime","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"recordLoadEmptyTime","kind":"identifier"},{"kind":"text","text":"()"}],"extendedModule":"GFPSDK","modules":[{"name":"GFPSDK"}],"symbolKind":"method","navigatorTitle":[{"text":"recordLoadEmptyTime","kind":"identifier"}],"role":"symbol","roleHeading":"Instance Method","title":"recordLoadEmptyTime()"},"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPInternalResponseInfo/recordLoadEmptyTime()":{"url":"\/documentation\/gfpsdk\/gfpinternalresponseinfo\/recordloademptytime()","title":"recordLoadEmptyTime()","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInternalResponseInfo\/recordLoadEmptyTime()","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"recordLoadEmptyTime","kind":"identifier"}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"recordLoadEmptyTime"},{"kind":"text","text":"()"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPInternalResponseInfo":{"abstract":[],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPInternalResponseInfo","url":"\/documentation\/gfpsdk\/gfpinternalresponseinfo","navigatorTitle":[{"text":"GFPInternalResponseInfo","kind":"identifier"}],"title":"GFPInternalResponseInfo","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPInternalResponseInfo","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","value":"recordLoadEmptyTime","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"recordLoadEmptyTime"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"recordLoadEmptyTime","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":"recordLoadEmptyTime","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInternalResponseInfo~1recordLoadEmptyTime()\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInternalResponseInfo~1recordLoadEmptyTime()\/fragments","value":[{"kind":"text","text":"- "},{"text":"recordLoadEmptyTime","kind":"identifier"}]},{"op":"replace","value":"GFPInternalResponseInfo","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInternalResponseInfo\/title"},{"value":[{"text":"GFPInternalResponseInfo","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInternalResponseInfo\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPInternalResponseInfo\/navigatorTitle","op":"replace","value":[{"text":"GFPInternalResponseInfo","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}