{"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeRichInfo\/propertyWithKey:","interfaceLanguage":"occ"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPRichDetailInfo","kind":"typeIdentifier","text":"GFPRichDetailInfo"},{"text":" *) ","kind":"text"},{"text":"propertyWithKey:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"key"},{"kind":"text","text":";"}]}],"kind":"declarations"}],"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/gfpsdk\/gfpnativerichinfo\/propertywithkey:"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeRichInfo"]]},"metadata":{"symbolKind":"method","role":"symbol","externalID":"c:objc(cs)GFPNativeRichInfo(im)propertyWithKey:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"propertyWithKey:"}],"modules":[{"name":"GFPSDK"}],"roleHeading":"Instance Method","title":"propertyWithKey:","navigatorTitle":[{"text":"propertyWithKey:","kind":"identifier"}]},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeRichInfo":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPNativeRichInfo","kind":"identifier"}],"title":"GFPNativeRichInfo","role":"symbol","url":"\/documentation\/gfpsdk\/gfpnativerichinfo","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeRichInfo","kind":"symbol","type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"GFPNativeRichInfo"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeRichInfo/propertyWithKey:":{"navigatorTitle":[{"kind":"identifier","text":"propertyWithKey:"}],"url":"\/documentation\/gfpsdk\/gfpnativerichinfo\/propertywithkey:","fragments":[{"kind":"text","text":"- "},{"text":"propertyWithKey:","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol","abstract":[],"title":"propertyWithKey:","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeRichInfo\/propertyWithKey:"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeRichInfo\/title","value":"GFPNativeRichInfo","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeRichInfo\/fragments","op":"replace","value":[{"kind":"identifier","text":"GFPNativeRichInfo"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeRichInfo\/navigatorTitle","value":[{"kind":"identifier","text":"GFPNativeRichInfo"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}