{"metadata":{"modules":[{"name":"GFPSDK"}],"externalID":"c:objc(cs)GFPNativeRichInfo(py)richTrackings","roleHeading":"Instance Property","title":"richTrackings","role":"symbol","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"richTrackings","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"GFPRichTrackingURLs","preciseIdentifier":"c:objc(cs)GFPRichTrackingURLs"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"richTrackings","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"richTrackings"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRichTrackingURLs","preciseIdentifier":"c:objc(cs)GFPRichTrackingURLs","text":"GFPRichTrackingURLs"},{"kind":"text","text":"? { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpnativerichinfo\/richtrackings"]},{"paths":["\/documentation\/gfpsdk\/gfpnativerichinfo\/richtrackings"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeRichInfo"]]},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeRichInfo\/richTrackings","interfaceLanguage":"swift"},"sections":[],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeRichInfo":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPNativeRichInfo","kind":"identifier"}],"title":"GFPNativeRichInfo","role":"symbol","url":"\/documentation\/gfpsdk\/gfpnativerichinfo","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeRichInfo","kind":"symbol","type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"GFPNativeRichInfo"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeRichInfo/richTrackings":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"richTrackings"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPRichTrackingURLs","kind":"typeIdentifier","text":"GFPRichTrackingURLs"},{"kind":"text","text":"?"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"richTrackings"}],"url":"\/documentation\/gfpsdk\/gfpnativerichinfo\/richtrackings","kind":"symbol","type":"topic","role":"symbol","title":"richTrackings","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeRichInfo\/richTrackings"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRichTrackingURLs":{"title":"GFPRichTrackingURLs","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRichTrackingURLs","url":"\/documentation\/gfpsdk\/gfprichtrackingurls","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPRichTrackingURLs","kind":"identifier"}],"kind":"symbol","abstract":[],"role":"symbol","navigatorTitle":[{"text":"GFPRichTrackingURLs","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"richTrackings"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"richTrackings"}]},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"GFPRichTrackingURLs","preciseIdentifier":"c:objc(cs)GFPRichTrackingURLs","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRichTrackingURLs"},{"kind":"text","text":" * "},{"text":"richTrackings","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeRichInfo\/title","value":"GFPNativeRichInfo"},{"value":[{"text":"GFPNativeRichInfo","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeRichInfo\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeRichInfo\/navigatorTitle","value":[{"text":"GFPNativeRichInfo","kind":"identifier"}]},{"value":"richTrackings","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeRichInfo~1richTrackings\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeRichInfo~1richTrackings\/fragments","value":[{"kind":"identifier","text":"richTrackings"}],"op":"replace"},{"value":"GFPRichTrackingURLs","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRichTrackingURLs\/title"},{"value":[{"text":"GFPRichTrackingURLs","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRichTrackingURLs\/fragments"},{"value":[{"text":"GFPRichTrackingURLs","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRichTrackingURLs\/navigatorTitle"}]}]}