{"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpnativerichinfo\/videowithkey:"]}],"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeRichInfo\/videoWithKey:","interfaceLanguage":"occ"},"metadata":{"modules":[{"name":"GFPSDK"}],"externalID":"c:objc(cs)GFPNativeRichInfo(im)videoWithKey:","roleHeading":"Instance Method","title":"videoWithKey:","role":"symbol","symbolKind":"method","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"videoWithKey:"}],"navigatorTitle":[{"text":"videoWithKey:","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeRichInfo"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"GFPRichDetailInfo","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPRichDetailInfo"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"videoWithKey:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"key"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}],"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeRichInfo/videoWithKey:":{"role":"symbol","title":"videoWithKey:","url":"\/documentation\/gfpsdk\/gfpnativerichinfo\/videowithkey:","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeRichInfo\/videoWithKey:","navigatorTitle":[{"text":"videoWithKey:","kind":"identifier"}],"type":"topic","fragments":[{"kind":"text","text":"- "},{"text":"videoWithKey:","kind":"identifier"}],"abstract":[],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeRichInfo":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPNativeRichInfo","kind":"identifier"}],"title":"GFPNativeRichInfo","role":"symbol","url":"\/documentation\/gfpsdk\/gfpnativerichinfo","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeRichInfo","kind":"symbol","type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"GFPNativeRichInfo"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"GFPNativeRichInfo","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeRichInfo\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeRichInfo\/fragments","value":[{"text":"GFPNativeRichInfo","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"GFPNativeRichInfo"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeRichInfo\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}