{"abstract":[{"type":"text","text":"네이티브 광고에 adChoicesView 위치를 미디어 크기로 정할 지"},{"text":" ","type":"text"},{"type":"text","text":"전체 광고뷰로 정할 지 설정하는 옵션입니다."},{"type":"text","text":" "},{"text":"s2s 광고에 한해 지원되며, YES인 경우 전체 광고뷰로 설정합니다.","type":"text"},{"text":" ","type":"text"},{"text":"기본값은 NO입니다.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeBaseRenderingSetting"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpnativebaserenderingsetting\/adchoicespositioninfulladview"]},{"paths":["\/documentation\/gfpsdk\/gfpnativebaserenderingsetting\/adchoicespositioninfulladview"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"adChoicesPositionInFullAdView","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeBaseRenderingSetting\/adChoicesPositionInFullAdView"},"metadata":{"externalID":"c:objc(cs)GFPNativeBaseRenderingSetting(py)adChoicesPositionInFullAdView","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"adChoicesPositionInFullAdView"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"kind":"identifier","text":"adChoicesPositionInFullAdView"}],"modules":[{"name":"GFPSDK"}],"symbolKind":"property","role":"symbol","title":"adChoicesPositionInFullAdView","roleHeading":"Instance Property"},"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeBaseRenderingSetting/adChoicesPositionInFullAdView":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"adChoicesPositionInFullAdView","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"abstract":[{"text":"네이티브 광고에 adChoicesView 위치를 미디어 크기로 정할 지","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"전체 광고뷰로 정할 지 설정하는 옵션입니다."},{"type":"text","text":" "},{"text":"s2s 광고에 한해 지원되며, YES인 경우 전체 광고뷰로 설정합니다.","type":"text"},{"type":"text","text":" "},{"text":"기본값은 NO입니다.","type":"text"}],"navigatorTitle":[{"text":"adChoicesPositionInFullAdView","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpnativebaserenderingsetting\/adchoicespositioninfulladview","kind":"symbol","type":"topic","role":"symbol","title":"adChoicesPositionInFullAdView","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeBaseRenderingSetting\/adChoicesPositionInFullAdView"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeBaseRenderingSetting":{"url":"\/documentation\/gfpsdk\/gfpnativebaserenderingsetting","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeBaseRenderingSetting","kind":"symbol","type":"topic","navigatorTitle":[{"text":"GFPNativeBaseRenderingSetting","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"GFPNativeBaseRenderingSetting","kind":"identifier"}],"abstract":[],"title":"GFPNativeBaseRenderingSetting"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"value":"adChoicesPositionInFullAdView","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"value":[{"text":"adChoicesPositionInFullAdView","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"assign"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"adChoicesPositionInFullAdView","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"value":"adChoicesPositionInFullAdView","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeBaseRenderingSetting~1adChoicesPositionInFullAdView\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeBaseRenderingSetting~1adChoicesPositionInFullAdView\/fragments","op":"replace","value":[{"kind":"identifier","text":"adChoicesPositionInFullAdView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeBaseRenderingSetting\/title","value":"GFPNativeBaseRenderingSetting"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeBaseRenderingSetting\/fragments","value":[{"kind":"identifier","text":"GFPNativeBaseRenderingSetting"}]},{"op":"replace","value":[{"text":"GFPNativeBaseRenderingSetting","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeBaseRenderingSetting\/navigatorTitle"}]}]}