{"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"text":"네이티브 광고의 adChoices 를 Custom 하게 사용할 경우 활성화 합니다.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"해당 옵션을 활성할 경우 GFP는 adChoicesView 를 그리지 않습니다."},{"type":"text","text":" "},{"text":"단, s2s 광고에 한해 제공합니다. (c2s의 경우 옵션과 관계 없이 처리)","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"기본값은 NO 입니다."}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeBaseRenderingSetting"]]},"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpnativebaserenderingsetting\/enablecustomadchoices"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gfpsdk\/gfpnativebaserenderingsetting\/enablecustomadchoices"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"enableCustomAdChoices","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"enableCustomAdChoices","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"roleHeading":"Instance Property","role":"symbol","externalID":"c:objc(cs)GFPNativeBaseRenderingSetting(py)enableCustomAdChoices","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"enableCustomAdChoices"}],"modules":[{"name":"GFPSDK"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeBaseRenderingSetting\/enableCustomAdChoices"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"enableCustomAdChoices","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}]}]}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeBaseRenderingSetting/enableCustomAdChoices":{"abstract":[{"text":"네이티브 광고의 adChoices 를 Custom 하게 사용할 경우 활성화 합니다.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"해당 옵션을 활성할 경우 GFP는 adChoicesView 를 그리지 않습니다."},{"text":" ","type":"text"},{"text":"단, s2s 광고에 한해 제공합니다. (c2s의 경우 옵션과 관계 없이 처리)","type":"text"},{"text":" ","type":"text"},{"text":"기본값은 NO 입니다.","type":"text"}],"title":"enableCustomAdChoices","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"enableCustomAdChoices","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"url":"\/documentation\/gfpsdk\/gfpnativebaserenderingsetting\/enablecustomadchoices","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeBaseRenderingSetting\/enableCustomAdChoices","navigatorTitle":[{"kind":"identifier","text":"enableCustomAdChoices"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeBaseRenderingSetting":{"url":"\/documentation\/gfpsdk\/gfpnativebaserenderingsetting","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeBaseRenderingSetting","kind":"symbol","type":"topic","navigatorTitle":[{"text":"GFPNativeBaseRenderingSetting","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"GFPNativeBaseRenderingSetting","kind":"identifier"}],"abstract":[],"title":"GFPNativeBaseRenderingSetting"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"enableCustomAdChoices","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"enableCustomAdChoices"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":") "},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableCustomAdChoices"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":"enableCustomAdChoices","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeBaseRenderingSetting~1enableCustomAdChoices\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeBaseRenderingSetting~1enableCustomAdChoices\/fragments","value":[{"text":"enableCustomAdChoices","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeBaseRenderingSetting\/title","op":"replace","value":"GFPNativeBaseRenderingSetting"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeBaseRenderingSetting\/fragments","op":"replace","value":[{"text":"GFPNativeBaseRenderingSetting","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeBaseRenderingSetting\/navigatorTitle","value":[{"kind":"identifier","text":"GFPNativeBaseRenderingSetting"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}