{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpnativebaserenderingsetting\/mediaboldfont"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpnativebaserenderingsetting\/mediaboldfont"]}],"metadata":{"modules":[{"name":"GFPSDK"}],"title":"mediaBoldFont","roleHeading":"Instance Property","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"mediaBoldFont"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIFont","text":"UIFont","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"mediaBoldFont"}],"symbolKind":"property","externalID":"c:objc(cs)GFPNativeBaseRenderingSetting(py)mediaBoldFont"},"kind":"symbol","abstract":[{"type":"text","text":"캐러셀 광고의 MediaView 내부 폰트를 설정하고 싶을 때 전달합니다."},{"text":" ","type":"text"},{"text":"(기본값은 nil)","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeBaseRenderingSetting"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mediaBoldFont","kind":"identifier"},{"kind":"text","text":": "},{"text":"UIFont","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIFont"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeBaseRenderingSetting\/mediaBoldFont","interfaceLanguage":"swift"},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeBaseRenderingSetting":{"url":"\/documentation\/gfpsdk\/gfpnativebaserenderingsetting","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeBaseRenderingSetting","kind":"symbol","type":"topic","navigatorTitle":[{"text":"GFPNativeBaseRenderingSetting","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"GFPNativeBaseRenderingSetting","kind":"identifier"}],"abstract":[],"title":"GFPNativeBaseRenderingSetting"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeBaseRenderingSetting/mediaBoldFont":{"url":"\/documentation\/gfpsdk\/gfpnativebaserenderingsetting\/mediaboldfont","title":"mediaBoldFont","abstract":[{"text":"캐러셀 광고의 MediaView 내부 폰트를 설정하고 싶을 때 전달합니다.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"(기본값은 nil)"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"mediaBoldFont"},{"text":": ","kind":"text"},{"text":"UIFont","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIFont"},{"text":"?","kind":"text"}],"type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeBaseRenderingSetting\/mediaBoldFont","navigatorTitle":[{"kind":"identifier","text":"mediaBoldFont"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","value":"mediaBoldFont","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"mediaBoldFont"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIFont","text":"UIFont","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"mediaBoldFont","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"GFPNativeBaseRenderingSetting","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeBaseRenderingSetting\/title"},{"value":[{"text":"GFPNativeBaseRenderingSetting","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeBaseRenderingSetting\/fragments","op":"replace"},{"value":[{"text":"GFPNativeBaseRenderingSetting","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeBaseRenderingSetting\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeBaseRenderingSetting~1mediaBoldFont\/title","value":"mediaBoldFont"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeBaseRenderingSetting~1mediaBoldFont\/fragments","op":"replace","value":[{"text":"mediaBoldFont","kind":"identifier"}]}]}]}