{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpnativebaserenderingsetting\/preferredadchoicesviewposition"]},{"paths":["\/documentation\/gfpsdk\/gfpnativebaserenderingsetting\/preferredadchoicesviewposition"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeBaseRenderingSetting"]]},"abstract":[{"text":"네이티브 광고에 adChoicesView 위치를 설정합니다.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"NN의 경우 Google DFP adChoiceView 의 위치를 설정하며, Overlay 형식으로 네이티브 뷰의 네 귀퉁이중 한 곳에 그려집니다."},{"type":"text","text":" "},{"text":"NS의 경우 adChoicesView 내부에 마크가 그려집니다.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"기본값은 우측상단입니다."}],"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"preferredAdChoicesViewPosition"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GFPAdChoicesViewPosition","preciseIdentifier":"c:@E@GFPAdChoicesViewPosition"}],"roleHeading":"Instance Property","symbolKind":"property","role":"symbol","modules":[{"name":"GFPSDK"}],"navigatorTitle":[{"kind":"identifier","text":"preferredAdChoicesViewPosition"}],"title":"preferredAdChoicesViewPosition","externalID":"c:objc(cs)GFPNativeBaseRenderingSetting(py)preferredAdChoicesViewPosition"},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeBaseRenderingSetting\/preferredAdChoicesViewPosition","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"preferredAdChoicesViewPosition"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdChoicesViewPosition","preciseIdentifier":"c:@E@GFPAdChoicesViewPosition","text":"GFPAdChoicesViewPosition","kind":"typeIdentifier"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdChoicesViewPosition":{"url":"\/documentation\/gfpsdk\/gfpadchoicesviewposition","role":"symbol","abstract":[],"type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPAdChoicesViewPosition"}],"title":"GFPAdChoicesViewPosition","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdChoicesViewPosition","navigatorTitle":[{"kind":"identifier","text":"GFPAdChoicesViewPosition"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeBaseRenderingSetting/preferredAdChoicesViewPosition":{"title":"preferredAdChoicesViewPosition","abstract":[{"type":"text","text":"네이티브 광고에 adChoicesView 위치를 설정합니다."},{"text":" ","type":"text"},{"type":"text","text":"NN의 경우 Google DFP adChoiceView 의 위치를 설정하며, Overlay 형식으로 네이티브 뷰의 네 귀퉁이중 한 곳에 그려집니다."},{"type":"text","text":" "},{"type":"text","text":"NS의 경우 adChoicesView 내부에 마크가 그려집니다."},{"text":" ","type":"text"},{"text":"기본값은 우측상단입니다.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"preferredAdChoicesViewPosition","kind":"identifier"}],"type":"topic","url":"\/documentation\/gfpsdk\/gfpnativebaserenderingsetting\/preferredadchoicesviewposition","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"preferredAdChoicesViewPosition"},{"kind":"text","text":": "},{"text":"GFPAdChoicesViewPosition","kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPAdChoicesViewPosition"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeBaseRenderingSetting\/preferredAdChoicesViewPosition","role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeBaseRenderingSetting":{"url":"\/documentation\/gfpsdk\/gfpnativebaserenderingsetting","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeBaseRenderingSetting","kind":"symbol","type":"topic","navigatorTitle":[{"text":"GFPNativeBaseRenderingSetting","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"GFPNativeBaseRenderingSetting","kind":"identifier"}],"abstract":[],"title":"GFPNativeBaseRenderingSetting"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"preferredAdChoicesViewPosition","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"preferredAdChoicesViewPosition","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"assign","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdChoicesViewPosition","preciseIdentifier":"c:@E@GFPAdChoicesViewPosition","text":"GFPAdChoicesViewPosition"},{"kind":"text","text":" "},{"kind":"identifier","text":"preferredAdChoicesViewPosition"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","value":"GFPAdChoicesViewPosition","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdChoicesViewPosition\/title"},{"value":[{"kind":"identifier","text":"GFPAdChoicesViewPosition"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdChoicesViewPosition\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdChoicesViewPosition\/navigatorTitle","value":[{"kind":"identifier","text":"GFPAdChoicesViewPosition"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeBaseRenderingSetting~1preferredAdChoicesViewPosition\/title","op":"replace","value":"preferredAdChoicesViewPosition"},{"op":"replace","value":[{"text":"preferredAdChoicesViewPosition","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeBaseRenderingSetting~1preferredAdChoicesViewPosition\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeBaseRenderingSetting\/title","value":"GFPNativeBaseRenderingSetting"},{"value":[{"text":"GFPNativeBaseRenderingSetting","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeBaseRenderingSetting\/fragments"},{"value":[{"text":"GFPNativeBaseRenderingSetting","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeBaseRenderingSetting\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}