{"metadata":{"roleHeading":"Type Method","externalID":"c:objc(cs)GFPVideoAdBreak(cm)adBreaksWithDictionary:noticeDuration:withError:","navigatorTitle":[{"kind":"identifier","text":"adBreaksWithDictionary:noticeDuration:withError:"}],"role":"symbol","title":"adBreaks(withDictionary:noticeDuration:withError:)","symbolKind":"method","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"adBreaks"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withDictionary"},{"kind":"text","text":": [["},{"kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]], "},{"kind":"externalParam","text":"noticeDuration"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"withError","kind":"externalParam"},{"kind":"text","text":": "},{"text":"AutoreleasingUnsafeMutablePointer","preciseIdentifier":"s:SA","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:@M@NaverAdsServices@objc(cs)GFPError","kind":"typeIdentifier","text":"GFPError"},{"text":"?>?) -> [","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPVideoAdBreak","text":"GFPVideoAdBreak","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"modules":[{"name":"GFPSDK"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"adBreaks","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withDictionary","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"aDict","kind":"internalParam"},{"kind":"text","text":": [["},{"kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]], "},{"text":"noticeDuration","kind":"externalParam"},{"kind":"text","text":" "},{"text":"aNoticeDuration","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"withError"},{"kind":"text","text":" "},{"text":"aError","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SA","text":"AutoreleasingUnsafeMutablePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:@M@NaverAdsServices@objc(cs)GFPError","text":"GFPError","kind":"typeIdentifier"},{"kind":"text","text":"?>?) -> ["},{"preciseIdentifier":"c:objc(cs)GFPVideoAdBreak","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdBreak","text":"GFPVideoAdBreak","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpvideoadbreak\/adbreaks(withdictionary:noticeduration:witherror:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gfpsdk\/gfpvideoadbreak\/adbreaks(withdictionary:noticeduration:witherror:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdBreak"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdBreak\/adBreaks(withDictionary:noticeDuration:withError:)"},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdBreak/adBreaks(withDictionary:noticeDuration:withError:)":{"role":"symbol","abstract":[],"title":"adBreaks(withDictionary:noticeDuration:withError:)","navigatorTitle":[{"kind":"identifier","text":"adBreaksWithDictionary:noticeDuration:withError:"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"adBreaks","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withDictionary"},{"kind":"text","text":": [["},{"preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"]], ","kind":"text"},{"text":"noticeDuration","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"withError"},{"kind":"text","text":": "},{"text":"AutoreleasingUnsafeMutablePointer","kind":"typeIdentifier","preciseIdentifier":"s:SA"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","text":"GFPError","preciseIdentifier":"c:@M@NaverAdsServices@objc(cs)GFPError"},{"text":"?>?) -> [","kind":"text"},{"kind":"typeIdentifier","text":"GFPVideoAdBreak","preciseIdentifier":"c:objc(cs)GFPVideoAdBreak"},{"text":"]","kind":"text"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdBreak\/adBreaks(withDictionary:noticeDuration:withError:)","type":"topic","kind":"symbol","url":"\/documentation\/gfpsdk\/gfpvideoadbreak\/adbreaks(withdictionary:noticeduration:witherror:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdBreak":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPVideoAdBreak","kind":"identifier"}],"kind":"symbol","role":"symbol","abstract":[],"type":"topic","url":"\/documentation\/gfpsdk\/gfpvideoadbreak","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdBreak","title":"GFPVideoAdBreak","navigatorTitle":[{"text":"GFPVideoAdBreak","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"path":"\/metadata\/title","op":"replace","value":"adBreaksWithDictionary:noticeDuration:withError:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"text":"+ ","kind":"text"},{"text":"adBreaksWithDictionary:noticeDuration:withError:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"text":"NSArray<GFPVideoAdBreak *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"adBreaksWithDictionary:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSDictionary *>","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"aDict","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"noticeDuration:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSTimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":") "},{"kind":"internalParam","text":"aNoticeDuration"},{"kind":"text","text":" "},{"text":"withError:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@NaverAdsServices@objc(cs)GFPError","text":"GFPError"},{"text":" * *) ","kind":"text"},{"text":"aError","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","value":"adBreaksWithDictionary:noticeDuration:withError:","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdBreak~1adBreaks(withDictionary:noticeDuration:withError:)\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdBreak~1adBreaks(withDictionary:noticeDuration:withError:)\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"text":"adBreaksWithDictionary:noticeDuration:withError:","kind":"identifier"}]},{"value":"GFPVideoAdBreak","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdBreak\/title"},{"value":[{"kind":"identifier","text":"GFPVideoAdBreak"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdBreak\/fragments"},{"value":[{"kind":"identifier","text":"GFPVideoAdBreak"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdBreak\/navigatorTitle"}]}]}