{"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPCornerInfo"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpcornerinfo\/leftrighttype"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpcornerinfo\/leftrighttype"]}],"metadata":{"externalID":"c:objc(cs)GFPCornerInfo(py)leftRightType","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"leftRightType"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@GFPAlignment","text":"GFPAlignment","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"leftRightType"}],"modules":[{"name":"GFPSDK"}],"symbolKind":"property","role":"symbol","roleHeading":"Instance Property","title":"leftRightType"},"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPCornerInfo\/leftRightType","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"leftRightType","kind":"identifier"},{"kind":"text","text":": "},{"text":"GFPAlignment","kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPAlignment"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPCornerInfo":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPCornerInfo","navigatorTitle":[{"kind":"identifier","text":"GFPCornerInfo"}],"abstract":[],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPCornerInfo","kind":"identifier"}],"title":"GFPCornerInfo","type":"topic","kind":"symbol","url":"\/documentation\/gfpsdk\/gfpcornerinfo"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPCornerInfo/leftRightType":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"leftRightType","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPAlignment","text":"GFPAlignment"}],"navigatorTitle":[{"text":"leftRightType","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPCornerInfo\/leftRightType","url":"\/documentation\/gfpsdk\/gfpcornerinfo\/leftrighttype","kind":"symbol","role":"symbol","abstract":[],"type":"topic","title":"leftRightType"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"leftRightType"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"leftRightType","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"assign","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"GFPAlignment","preciseIdentifier":"c:@E@GFPAlignment"},{"kind":"text","text":" "},{"text":"leftRightType","kind":"identifier"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPCornerInfo\/title","value":"GFPCornerInfo","op":"replace"},{"value":[{"text":"GFPCornerInfo","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPCornerInfo\/fragments"},{"value":[{"text":"GFPCornerInfo","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPCornerInfo\/navigatorTitle"},{"op":"replace","value":"leftRightType","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPCornerInfo~1leftRightType\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPCornerInfo~1leftRightType\/fragments","op":"replace","value":[{"text":"leftRightType","kind":"identifier"}]}]}]}