{"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoaderDelegate\/adLoader(_:didReceive:)-18hky","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"text":"adLoader:didReceiveNativeSimpleAd:","kind":"identifier"}],"required":true,"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"adLoader","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"GFPAdLoader","preciseIdentifier":"c:objc(cs)GFPAdLoader"},{"text":"!, ","kind":"text"},{"kind":"externalParam","text":"didReceive"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)GFPNativeSimpleAd","text":"GFPNativeSimpleAd","kind":"typeIdentifier"},{"text":"!)","kind":"text"}],"title":"adLoader(_:didReceive:)","externalID":"c:objc(pl)GFPAdLoaderDelegate(im)adLoader:didReceiveNativeSimpleAd:","roleHeading":"Instance Method","symbolKind":"method","modules":[{"name":"GFPSDK"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"optional","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"adLoader","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"unifiedAdLoader","kind":"internalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoader","text":"GFPAdLoader","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdLoader"},{"text":"!, ","kind":"text"},{"kind":"externalParam","text":"didReceive"},{"text":" ","kind":"text"},{"text":"nativeSimpleAd","kind":"internalParam"},{"kind":"text","text":": "},{"text":"GFPNativeSimpleAd","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAd","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPNativeSimpleAd"},{"kind":"text","text":"!)"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"unifiedAdLoader","content":[{"inlineContent":[{"text":"통합 광고 로더","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"네이티브 광고 객체","type":"text"}],"type":"paragraph"}],"name":"nativeSimpleAd"}]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoaderDelegate"]]},"variants":[{"paths":["\/documentation\/gfpsdk\/gfpadloaderdelegate\/adloader(_:didreceive:)-18hky"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gfpsdk\/gfpadloaderdelegate\/adloader(_:didreceive:)-18hky"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"광고가 성공적으로 로드될 경우 호출됩니다. - NativeSimple"}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdLoader":{"navigatorTitle":[{"text":"GFPAdLoader","kind":"identifier"}],"kind":"symbol","title":"GFPAdLoader","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoader","url":"\/documentation\/gfpsdk\/gfpadloader","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPAdLoader"}],"type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdLoaderDelegate/adLoader(_:didReceive:)-18hky":{"abstract":[{"type":"text","text":"광고가 성공적으로 로드될 경우 호출됩니다. - NativeSimple"}],"type":"topic","title":"adLoader(_:didReceive:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"adLoader"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdLoader","text":"GFPAdLoader"},{"text":"!, ","kind":"text"},{"text":"didReceive","kind":"externalParam"},{"kind":"text","text":": "},{"text":"GFPNativeSimpleAd","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPNativeSimpleAd"},{"text":"!)","kind":"text"}],"url":"\/documentation\/gfpsdk\/gfpadloaderdelegate\/adloader(_:didreceive:)-18hky","role":"symbol","required":true,"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoaderDelegate\/adLoader(_:didReceive:)-18hky","navigatorTitle":[{"text":"adLoader:didReceiveNativeSimpleAd:","kind":"identifier"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeSimpleAd":{"type":"topic","navigatorTitle":[{"text":"GFPNativeSimpleAd","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPNativeSimpleAd"}],"title":"GFPNativeSimpleAd","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAd","url":"\/documentation\/gfpsdk\/gfpnativesimplead","abstract":[],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdLoaderDelegate":{"navigatorTitle":[{"kind":"identifier","text":"GFPAdLoaderDelegate"}],"title":"GFPAdLoaderDelegate","url":"\/documentation\/gfpsdk\/gfpadloaderdelegate","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoaderDelegate","role":"symbol","type":"topic","kind":"symbol","abstract":[],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPAdLoaderDelegate"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"adLoader:didReceiveNativeSimpleAd:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"adLoader:didReceiveNativeSimpleAd:"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"adLoader:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoader","text":"GFPAdLoader","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdLoader"},{"text":" *) ","kind":"text"},{"text":"unifiedAdLoader","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didReceiveNativeSimpleAd:"},{"kind":"text","text":"("},{"text":"GFPNativeSimpleAd","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAd","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPNativeSimpleAd"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"nativeSimpleAd"},{"text":";","kind":"text"}]}]}},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"unifiedAdLoader","content":[{"type":"paragraph","inlineContent":[{"text":"통합 광고 로더","type":"text"}]}]},{"name":"nativeSimpleAd","content":[{"inlineContent":[{"text":"네이티브 광고 객체","type":"text"}],"type":"paragraph"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoader\/title","op":"replace","value":"GFPAdLoader"},{"op":"replace","value":[{"kind":"identifier","text":"GFPAdLoader"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoader\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"GFPAdLoader"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoader\/navigatorTitle"},{"value":"adLoader:didReceiveNativeSimpleAd:","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoaderDelegate~1adLoader(_:didReceive:)-18hky\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"adLoader:didReceiveNativeSimpleAd:"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoaderDelegate~1adLoader(_:didReceive:)-18hky\/fragments"},{"value":"GFPNativeSimpleAd","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAd\/title","op":"replace"},{"value":[{"kind":"identifier","text":"GFPNativeSimpleAd"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAd\/fragments"},{"value":[{"text":"GFPNativeSimpleAd","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAd\/navigatorTitle"},{"value":"GFPAdLoaderDelegate","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoaderDelegate\/title"},{"value":[{"text":"GFPAdLoaderDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoaderDelegate\/fragments"},{"value":[{"kind":"identifier","text":"GFPAdLoaderDelegate"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoaderDelegate\/navigatorTitle"}]}]}