{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"adLoader"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"unifiedAdLoader"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"GFPAdLoader","preciseIdentifier":"c:objc(cs)GFPAdLoader","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoader"},{"kind":"text","text":"!, "},{"text":"didReceiveBannerAd","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"bannerView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerView","text":"GFPBannerView","preciseIdentifier":"c:objc(cs)GFPBannerView"},{"kind":"text","text":"!)"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"통합 광고 로더","type":"text"}]}],"name":"unifiedAdLoader"},{"name":"bannerView","content":[{"type":"paragraph","inlineContent":[{"text":"배너 광고 뷰","type":"text"}]}]}],"kind":"parameters"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpadloaderdelegate\/adloader(_:didreceivebannerad:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpadloaderdelegate\/adloader(_:didreceivebannerad:)"]}],"metadata":{"modules":[{"name":"GFPSDK"}],"title":"adLoader(_:didReceiveBannerAd:)","roleHeading":"Instance Method","role":"symbol","required":true,"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"adLoader","kind":"identifier"},{"text":"(","kind":"text"},{"text":"GFPAdLoader","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdLoader"},{"kind":"text","text":"!, "},{"text":"didReceiveBannerAd","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPBannerView","text":"GFPBannerView"},{"kind":"text","text":"!)"}],"navigatorTitle":[{"text":"adLoader:didReceiveBannerAd:","kind":"identifier"}],"symbolKind":"method","externalID":"c:objc(pl)GFPAdLoaderDelegate(im)adLoader:didReceiveBannerAd:"},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"광고가 성공적으로 로드될 경우 호출됩니다. - Banner"}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoaderDelegate"]]},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoaderDelegate\/adLoader(_:didReceiveBannerAd:)","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdLoader":{"navigatorTitle":[{"text":"GFPAdLoader","kind":"identifier"}],"kind":"symbol","title":"GFPAdLoader","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoader","url":"\/documentation\/gfpsdk\/gfpadloader","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPAdLoader"}],"type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdLoaderDelegate":{"navigatorTitle":[{"kind":"identifier","text":"GFPAdLoaderDelegate"}],"title":"GFPAdLoaderDelegate","url":"\/documentation\/gfpsdk\/gfpadloaderdelegate","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoaderDelegate","role":"symbol","type":"topic","kind":"symbol","abstract":[],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPAdLoaderDelegate"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdLoaderDelegate/adLoader(_:didReceiveBannerAd:)":{"abstract":[{"text":"광고가 성공적으로 로드될 경우 호출됩니다. - Banner","type":"text"}],"type":"topic","title":"adLoader(_:didReceiveBannerAd:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"adLoader","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPAdLoader","text":"GFPAdLoader","kind":"typeIdentifier"},{"text":"!, ","kind":"text"},{"kind":"externalParam","text":"didReceiveBannerAd"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPBannerView","text":"GFPBannerView","kind":"typeIdentifier"},{"kind":"text","text":"!)"}],"url":"\/documentation\/gfpsdk\/gfpadloaderdelegate\/adloader(_:didreceivebannerad:)","role":"symbol","required":true,"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoaderDelegate\/adLoader(_:didReceiveBannerAd:)","navigatorTitle":[{"text":"adLoader:didReceiveBannerAd:","kind":"identifier"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerView":{"navigatorTitle":[{"text":"GFPBannerView","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerView","title":"GFPBannerView","role":"symbol","url":"\/documentation\/gfpsdk\/gfpbannerview","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPBannerView"}],"type":"topic","kind":"symbol","abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"adLoader:didReceiveBannerAd:","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"adLoader:didReceiveBannerAd:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"adLoader:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoader","preciseIdentifier":"c:objc(cs)GFPAdLoader","kind":"typeIdentifier","text":"GFPAdLoader"},{"text":" *) ","kind":"text"},{"text":"unifiedAdLoader","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"didReceiveBannerAd:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerView","preciseIdentifier":"c:objc(cs)GFPBannerView","text":"GFPBannerView","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"bannerView","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","value":{"kind":"parameters","parameters":[{"name":"unifiedAdLoader","content":[{"inlineContent":[{"type":"text","text":"통합 광고 로더"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"배너 광고 뷰","type":"text"}]}],"name":"bannerView"}]},"path":"\/primaryContentSections\/1"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoader\/title","value":"GFPAdLoader","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoader\/fragments","value":[{"text":"GFPAdLoader","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"GFPAdLoader"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoader\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoaderDelegate\/title","value":"GFPAdLoaderDelegate"},{"op":"replace","value":[{"text":"GFPAdLoaderDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoaderDelegate\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoaderDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"GFPAdLoaderDelegate"}],"op":"replace"},{"op":"replace","value":"adLoader:didReceiveBannerAd:","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoaderDelegate~1adLoader(_:didReceiveBannerAd:)\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoaderDelegate~1adLoader(_:didReceiveBannerAd:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"adLoader:didReceiveBannerAd:","kind":"identifier"}],"op":"replace"},{"value":"GFPBannerView","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerView\/title"},{"value":[{"text":"GFPBannerView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerView\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerView\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"GFPBannerView"}]}]}]}