{"variants":[{"paths":["\/documentation\/gfpsdk\/gfpadloaderdelegate\/adloader(_:didfailwitherror:responseinfo:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gfpsdk\/gfpadloaderdelegate\/adloader(_:didfailwitherror:responseinfo:)"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"광고 로드에 실패한 경우 호출됩니다."}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"symbolKind":"method","role":"symbol","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"adLoader","kind":"identifier"},{"text":"(","kind":"text"},{"text":"GFPAdLoader","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdLoader"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"didFailWithError"},{"text":": ","kind":"text"},{"text":"GFPError","preciseIdentifier":"c:@M@NaverAdsServices@objc(cs)GFPError","kind":"typeIdentifier"},{"text":"!, ","kind":"text"},{"kind":"externalParam","text":"responseInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPLoadResponseInfo","text":"GFPLoadResponseInfo"},{"kind":"text","text":"!)"}],"externalID":"c:objc(pl)GFPAdLoaderDelegate(im)adLoader:didFailWithError:responseInfo:","modules":[{"name":"GFPSDK"}],"navigatorTitle":[{"text":"adLoader:didFailWithError:responseInfo:","kind":"identifier"}],"title":"adLoader(_:didFailWithError:responseInfo:)"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoaderDelegate\/adLoader(_:didFailWithError:responseInfo:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"optional"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"adLoader","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"unifiedAdLoader"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"GFPAdLoader","preciseIdentifier":"c:objc(cs)GFPAdLoader","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoader"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"didFailWithError"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"error"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@NaverAdsServices@objc(cs)GFPError","kind":"typeIdentifier","text":"GFPError"},{"kind":"text","text":"!, "},{"text":"responseInfo","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"GFPLoadResponseInfo","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLoadResponseInfo","preciseIdentifier":"c:objc(cs)GFPLoadResponseInfo"},{"text":"!)","kind":"text"}]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"통합 광고 로더","type":"text"}],"type":"paragraph"}],"name":"unifiedAdLoader"},{"name":"error","content":[{"inlineContent":[{"text":"에러내용","type":"text"}],"type":"paragraph"}]},{"name":"responseInfo","content":[{"inlineContent":[{"text":"광고 응답 정보객체","type":"text"}],"type":"paragraph"}]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoaderDelegate"]]},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPLoadResponseInfo":{"title":"GFPLoadResponseInfo","url":"\/documentation\/gfpsdk\/gfploadresponseinfo","role":"symbol","navigatorTitle":[{"text":"GFPLoadResponseInfo","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"GFPLoadResponseInfo","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLoadResponseInfo"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdLoader":{"navigatorTitle":[{"text":"GFPAdLoader","kind":"identifier"}],"kind":"symbol","title":"GFPAdLoader","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoader","url":"\/documentation\/gfpsdk\/gfpadloader","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPAdLoader"}],"type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdLoaderDelegate/adLoader(_:didFailWithError:responseInfo:)":{"abstract":[{"type":"text","text":"광고 로드에 실패한 경우 호출됩니다."}],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"adLoader"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdLoader","text":"GFPAdLoader"},{"text":"!, ","kind":"text"},{"text":"didFailWithError","kind":"externalParam"},{"kind":"text","text":": "},{"text":"GFPError","kind":"typeIdentifier","preciseIdentifier":"c:@M@NaverAdsServices@objc(cs)GFPError"},{"text":"!, ","kind":"text"},{"text":"responseInfo","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPLoadResponseInfo","text":"GFPLoadResponseInfo"},{"text":"!)","kind":"text"}],"url":"\/documentation\/gfpsdk\/gfpadloaderdelegate\/adloader(_:didfailwitherror:responseinfo:)","navigatorTitle":[{"kind":"identifier","text":"adLoader:didFailWithError:responseInfo:"}],"type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoaderDelegate\/adLoader(_:didFailWithError:responseInfo:)","title":"adLoader(_:didFailWithError:responseInfo:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdLoaderDelegate":{"navigatorTitle":[{"kind":"identifier","text":"GFPAdLoaderDelegate"}],"title":"GFPAdLoaderDelegate","url":"\/documentation\/gfpsdk\/gfpadloaderdelegate","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoaderDelegate","role":"symbol","type":"topic","kind":"symbol","abstract":[],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPAdLoaderDelegate"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"adLoader:didFailWithError:responseInfo:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"adLoader:didFailWithError:responseInfo:"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"adLoader:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"GFPAdLoader","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdLoader","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdLoader"},{"text":" *) ","kind":"text"},{"text":"unifiedAdLoader","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"didFailWithError:","kind":"identifier"},{"kind":"text","text":"("},{"text":"GFPError","preciseIdentifier":"c:@M@NaverAdsServices@objc(cs)GFPError","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"error","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"responseInfo:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"GFPLoadResponseInfo","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLoadResponseInfo","preciseIdentifier":"c:objc(cs)GFPLoadResponseInfo"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"responseInfo"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/primaryContentSections\/1","value":{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"통합 광고 로더"}],"type":"paragraph"}],"name":"unifiedAdLoader"},{"name":"error","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"에러내용"}]}]},{"name":"responseInfo","content":[{"type":"paragraph","inlineContent":[{"text":"광고 응답 정보객체","type":"text"}]}]}],"kind":"parameters"},"op":"replace"},{"op":"replace","value":"GFPLoadResponseInfo","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLoadResponseInfo\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLoadResponseInfo\/fragments","value":[{"kind":"identifier","text":"GFPLoadResponseInfo"}],"op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"GFPLoadResponseInfo"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLoadResponseInfo\/navigatorTitle"},{"value":"GFPAdLoader","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoader\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoader\/fragments","value":[{"kind":"identifier","text":"GFPAdLoader"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoader\/navigatorTitle","value":[{"text":"GFPAdLoader","kind":"identifier"}]},{"value":"adLoader:didFailWithError:responseInfo:","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoaderDelegate~1adLoader(_:didFailWithError:responseInfo:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"adLoader:didFailWithError:responseInfo:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoaderDelegate~1adLoader(_:didFailWithError:responseInfo:)\/fragments","op":"replace"},{"value":"GFPAdLoaderDelegate","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoaderDelegate\/title"},{"value":[{"text":"GFPAdLoaderDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoaderDelegate\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdLoaderDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"GFPAdLoaderDelegate"}]}]}]}