{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpvideoadaptordelegate\/videoadadaptordidpresentdefault(inappbrowser:)"]},{"paths":["\/documentation\/gfpsdk\/gfpvideoadaptordelegate\/videoadadaptordidpresentdefault(inappbrowser:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdaptorDelegate"]]},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdaptorDelegate\/videoAdAdaptorDidPresentDefault(inAppBrowser:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"kind":"symbol","metadata":{"title":"videoAdAdaptorDidPresentDefault(inAppBrowser:)","externalID":"c:objc(pl)GFPVideoAdaptorDelegate(im)videoAdAdaptorDidPresentDefaultInAppBrowser:","role":"symbol","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"videoAdAdaptorDidPresentDefault","kind":"identifier"},{"kind":"text","text":"("},{"text":"inAppBrowser","kind":"externalParam"},{"text":": any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdAdaptor","text":"GFPAdAdaptor"},{"text":" & ","kind":"text"},{"preciseIdentifier":"c:objc(pl)GFPVideoAdapting","text":"GFPVideoAdapting","kind":"typeIdentifier"},{"text":")","kind":"text"}],"modules":[{"name":"GFPSDK"}],"navigatorTitle":[{"kind":"identifier","text":"videoAdAdaptorDidPresentDefaultInAppBrowser:"}],"roleHeading":"Instance Method"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"videoAdAdaptorDidPresentDefault"},{"text":"(","kind":"text"},{"text":"inAppBrowser","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"videoAdaptor"},{"text":": any ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAdaptor","preciseIdentifier":"c:objc(cs)GFPAdAdaptor","text":"GFPAdAdaptor"},{"kind":"text","text":" & "},{"text":"GFPVideoAdapting","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdapting","preciseIdentifier":"c:objc(pl)GFPVideoAdapting"},{"text":")","kind":"text"}],"platforms":["iOS"]}]}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdapting":{"title":"GFPVideoAdapting","type":"topic","abstract":[],"url":"\/documentation\/gfpsdk\/gfpvideoadapting","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdapting","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPVideoAdapting"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPVideoAdapting"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdaptorDelegate":{"navigatorTitle":[{"kind":"identifier","text":"GFPVideoAdaptorDelegate"}],"type":"topic","url":"\/documentation\/gfpsdk\/gfpvideoadaptordelegate","kind":"symbol","abstract":[],"title":"GFPVideoAdaptorDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPVideoAdaptorDelegate"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdaptorDelegate","role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdAdaptor":{"navigatorTitle":[{"kind":"identifier","text":"GFPAdAdaptor"}],"title":"GFPAdAdaptor","url":"\/documentation\/gfpsdk\/gfpadadaptor","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAdaptor","abstract":[],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPAdAdaptor"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdaptorDelegate/videoAdAdaptorDidPresentDefault(inAppBrowser:)":{"type":"topic","title":"videoAdAdaptorDidPresentDefault(inAppBrowser:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"videoAdAdaptorDidPresentDefault","kind":"identifier"},{"kind":"text","text":"("},{"text":"inAppBrowser","kind":"externalParam"},{"kind":"text","text":": any "},{"text":"GFPAdAdaptor","preciseIdentifier":"c:objc(cs)GFPAdAdaptor","kind":"typeIdentifier"},{"text":" & ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)GFPVideoAdapting","text":"GFPVideoAdapting"},{"text":")","kind":"text"}],"abstract":[],"url":"\/documentation\/gfpsdk\/gfpvideoadaptordelegate\/videoadadaptordidpresentdefault(inappbrowser:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"videoAdAdaptorDidPresentDefaultInAppBrowser:"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdaptorDelegate\/videoAdAdaptorDidPresentDefault(inAppBrowser:)"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"videoAdAdaptorDidPresentDefaultInAppBrowser:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"videoAdAdaptorDidPresentDefaultInAppBrowser:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"videoAdAdaptorDidPresentDefaultInAppBrowser:"},{"text":"(","kind":"text"},{"text":"GFPAdAdaptor<GFPVideoAdapting>","preciseIdentifier":"c:Q$objc(cs)GFPAdAdaptorobjc(pl)GFPVideoAdapting","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"videoAdaptor","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"GFPVideoAdapting","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdapting\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdapting\/fragments","value":[{"text":"GFPVideoAdapting","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"GFPVideoAdapting"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdapting\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdaptorDelegate\/title","value":"GFPVideoAdaptorDelegate","op":"replace"},{"value":[{"text":"GFPVideoAdaptorDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdaptorDelegate\/fragments","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"GFPVideoAdaptorDelegate"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdaptorDelegate\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdaptor\/title","value":"GFPAdAdaptor"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdaptor\/fragments","op":"replace","value":[{"text":"GFPAdAdaptor","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdaptor\/navigatorTitle","value":[{"text":"GFPAdAdaptor","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdaptorDelegate~1videoAdAdaptorDidPresentDefault(inAppBrowser:)\/title","value":"videoAdAdaptorDidPresentDefaultInAppBrowser:"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdaptorDelegate~1videoAdAdaptorDidPresentDefault(inAppBrowser:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"videoAdAdaptorDidPresentDefaultInAppBrowser:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}