{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdaptorDelegate\/videoAdAdaptor(_:didReceive:)-m66"},"sections":[],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"platforms":[{"name":"iOS","introducedAt":"4.3","deprecated":false,"unavailable":false,"beta":false},{"name":"iPadOS","introducedAt":"4.3","unavailable":false,"deprecated":false,"beta":false},{"unavailable":false,"beta":false,"deprecated":false,"name":"Mac Catalyst","introducedAt":"4.3"}],"symbolKind":"method","required":true,"role":"symbol","modules":[{"name":"GFPSDK"}],"title":"videoAdAdaptor(_:didReceive:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"videoAdAdaptor","kind":"identifier"},{"text":"(any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdAdaptor","text":"GFPAdAdaptor"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)GFPVideoAdapting","text":"GFPVideoAdapting"},{"text":", ","kind":"text"},{"text":"didReceive","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVPlayerItemAccessLog","text":"AVPlayerItemAccessLog"},{"kind":"text","text":")"}],"externalID":"c:objc(pl)GFPVideoAdaptorDelegate(im)videoAdAdaptor:didReceiveAccessLog:","navigatorTitle":[{"kind":"identifier","text":"videoAdAdaptor:didReceiveAccessLog:"}],"roleHeading":"Instance Method"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"optional","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"videoAdAdaptor","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"videoAdaptor","kind":"internalParam"},{"kind":"text","text":": any "},{"text":"GFPAdAdaptor","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAdaptor","preciseIdentifier":"c:objc(cs)GFPAdAdaptor"},{"text":" & ","kind":"text"},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdapting","text":"GFPVideoAdapting","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)GFPVideoAdapting"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didReceive"},{"kind":"text","text":" "},{"text":"accessLog","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVPlayerItemAccessLog","text":"AVPlayerItemAccessLog"},{"text":")","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpvideoadaptordelegate\/videoadadaptor(_:didreceive:)-m66"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpvideoadaptordelegate\/videoadadaptor(_:didreceive:)-m66"]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdaptorDelegate"]]},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdAdaptor":{"navigatorTitle":[{"kind":"identifier","text":"GFPAdAdaptor"}],"title":"GFPAdAdaptor","url":"\/documentation\/gfpsdk\/gfpadadaptor","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAdaptor","abstract":[],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPAdAdaptor"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdapting":{"title":"GFPVideoAdapting","type":"topic","abstract":[],"url":"\/documentation\/gfpsdk\/gfpvideoadapting","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdapting","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPVideoAdapting"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPVideoAdapting"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdaptorDelegate/videoAdAdaptor(_:didReceive:)-m66":{"navigatorTitle":[{"text":"videoAdAdaptor:didReceiveAccessLog:","kind":"identifier"}],"required":true,"url":"\/documentation\/gfpsdk\/gfpvideoadaptordelegate\/videoadadaptor(_:didreceive:)-m66","kind":"symbol","role":"symbol","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdaptorDelegate\/videoAdAdaptor(_:didReceive:)-m66","type":"topic","title":"videoAdAdaptor(_:didReceive:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"videoAdAdaptor"},{"text":"(any ","kind":"text"},{"kind":"typeIdentifier","text":"GFPAdAdaptor","preciseIdentifier":"c:objc(cs)GFPAdAdaptor"},{"text":" & ","kind":"text"},{"kind":"typeIdentifier","text":"GFPVideoAdapting","preciseIdentifier":"c:objc(pl)GFPVideoAdapting"},{"text":", ","kind":"text"},{"text":"didReceive","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"AVPlayerItemAccessLog","preciseIdentifier":"c:objc(cs)AVPlayerItemAccessLog"},{"kind":"text","text":")"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdaptorDelegate":{"navigatorTitle":[{"kind":"identifier","text":"GFPVideoAdaptorDelegate"}],"type":"topic","url":"\/documentation\/gfpsdk\/gfpvideoadaptordelegate","kind":"symbol","abstract":[],"title":"GFPVideoAdaptorDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPVideoAdaptorDelegate"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdaptorDelegate","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","value":"videoAdAdaptor:didReceiveAccessLog:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"videoAdAdaptor:didReceiveAccessLog:","kind":"identifier"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"videoAdAdaptor:"},{"kind":"text","text":"("},{"text":"GFPAdAdaptor<GFPVideoAdapting>","preciseIdentifier":"c:Q$objc(cs)GFPAdAdaptorobjc(pl)GFPVideoAdapting","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"videoAdaptor"},{"kind":"text","text":" "},{"kind":"identifier","text":"didReceiveAccessLog:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)AVPlayerItemAccessLog","text":"AVPlayerItemAccessLog","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"accessLog","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdaptor\/title","value":"GFPAdAdaptor","op":"replace"},{"value":[{"text":"GFPAdAdaptor","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdaptor\/fragments","op":"replace"},{"value":[{"text":"GFPAdAdaptor","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdaptor\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdapting\/title","value":"GFPVideoAdapting"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdapting\/fragments","op":"replace","value":[{"kind":"identifier","text":"GFPVideoAdapting"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdapting\/navigatorTitle","value":[{"text":"GFPVideoAdapting","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdaptorDelegate~1videoAdAdaptor(_:didReceive:)-m66\/title","value":"videoAdAdaptor:didReceiveAccessLog:"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdaptorDelegate~1videoAdAdaptor(_:didReceive:)-m66\/fragments","value":[{"kind":"text","text":"- "},{"text":"videoAdAdaptor:didReceiveAccessLog:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdaptorDelegate\/title","value":"GFPVideoAdaptorDelegate","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdaptorDelegate\/fragments","value":[{"text":"GFPVideoAdaptorDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdaptorDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"GFPVideoAdaptorDelegate"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}