{"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdaptorDelegate"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoAdAdaptorDidDismissDefault"},{"kind":"text","text":"("},{"text":"inAppBrowser","kind":"externalParam"},{"kind":"text","text":": any "},{"text":"GFPAdAdaptor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdAdaptor"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"GFPVideoAdapting","preciseIdentifier":"c:objc(pl)GFPVideoAdapting"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"videoAdAdaptorDidDismissDefaultInAppBrowser:"}],"roleHeading":"Instance Method","externalID":"c:objc(pl)GFPVideoAdaptorDelegate(im)videoAdAdaptorDidDismissDefaultInAppBrowser:","modules":[{"name":"GFPSDK"}],"role":"symbol","required":true,"title":"videoAdAdaptorDidDismissDefault(inAppBrowser:)","symbolKind":"method"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"videoAdAdaptorDidDismissDefault","kind":"identifier"},{"kind":"text","text":"("},{"text":"inAppBrowser","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"videoAdaptor"},{"text":": any ","kind":"text"},{"kind":"typeIdentifier","text":"GFPAdAdaptor","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAdaptor","preciseIdentifier":"c:objc(cs)GFPAdAdaptor"},{"kind":"text","text":" & "},{"text":"GFPVideoAdapting","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdapting","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)GFPVideoAdapting"},{"kind":"text","text":")"}]}],"kind":"declarations"}],"kind":"symbol","variants":[{"paths":["\/documentation\/gfpsdk\/gfpvideoadaptordelegate\/videoadadaptordiddismissdefault(inappbrowser:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpvideoadaptordelegate\/videoadadaptordiddismissdefault(inappbrowser:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdaptorDelegate\/videoAdAdaptorDidDismissDefault(inAppBrowser:)"},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdaptorDelegate/videoAdAdaptorDidDismissDefault(inAppBrowser:)":{"url":"\/documentation\/gfpsdk\/gfpvideoadaptordelegate\/videoadadaptordiddismissdefault(inappbrowser:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"videoAdAdaptorDidDismissDefault","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"inAppBrowser"},{"kind":"text","text":": any "},{"preciseIdentifier":"c:objc(cs)GFPAdAdaptor","text":"GFPAdAdaptor","kind":"typeIdentifier"},{"text":" & ","kind":"text"},{"kind":"typeIdentifier","text":"GFPVideoAdapting","preciseIdentifier":"c:objc(pl)GFPVideoAdapting"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdaptorDelegate\/videoAdAdaptorDidDismissDefault(inAppBrowser:)","kind":"symbol","navigatorTitle":[{"text":"videoAdAdaptorDidDismissDefaultInAppBrowser:","kind":"identifier"}],"required":true,"role":"symbol","title":"videoAdAdaptorDidDismissDefault(inAppBrowser:)","type":"topic","abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdAdaptor":{"navigatorTitle":[{"kind":"identifier","text":"GFPAdAdaptor"}],"title":"GFPAdAdaptor","url":"\/documentation\/gfpsdk\/gfpadadaptor","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAdaptor","abstract":[],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPAdAdaptor"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdapting":{"title":"GFPVideoAdapting","type":"topic","abstract":[],"url":"\/documentation\/gfpsdk\/gfpvideoadapting","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdapting","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPVideoAdapting"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPVideoAdapting"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdaptorDelegate":{"navigatorTitle":[{"kind":"identifier","text":"GFPVideoAdaptorDelegate"}],"type":"topic","url":"\/documentation\/gfpsdk\/gfpvideoadaptordelegate","kind":"symbol","abstract":[],"title":"GFPVideoAdaptorDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPVideoAdaptorDelegate"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdaptorDelegate","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"videoAdAdaptorDidDismissDefaultInAppBrowser:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"videoAdAdaptorDidDismissDefaultInAppBrowser:"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"text":"videoAdAdaptorDidDismissDefaultInAppBrowser:","kind":"identifier"},{"kind":"text","text":"("},{"text":"GFPAdAdaptor<GFPVideoAdapting>","preciseIdentifier":"c:Q$objc(cs)GFPAdAdaptorobjc(pl)GFPVideoAdapting","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"videoAdaptor"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"value":"videoAdAdaptorDidDismissDefaultInAppBrowser:","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdaptorDelegate~1videoAdAdaptorDidDismissDefault(inAppBrowser:)\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdaptorDelegate~1videoAdAdaptorDidDismissDefault(inAppBrowser:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"videoAdAdaptorDidDismissDefaultInAppBrowser:"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdaptor\/title","value":"GFPAdAdaptor","op":"replace"},{"value":[{"text":"GFPAdAdaptor","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdaptor\/fragments","op":"replace"},{"value":[{"text":"GFPAdAdaptor","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdaptor\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdapting\/title","value":"GFPVideoAdapting","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"GFPVideoAdapting"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdapting\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdapting\/navigatorTitle","value":[{"text":"GFPVideoAdapting","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdaptorDelegate\/title","value":"GFPVideoAdaptorDelegate"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdaptorDelegate\/fragments","value":[{"text":"GFPVideoAdaptorDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdaptorDelegate\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"GFPVideoAdaptorDelegate"}]}]}]}