{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpvideoadaptordelegate\/videoadwaspaused(_:)"]},{"paths":["\/documentation\/gfpsdk\/gfpvideoadaptordelegate\/videoadwaspaused(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"metadata":{"externalID":"c:objc(pl)GFPVideoAdaptorDelegate(im)videoAdWasPaused:","modules":[{"name":"GFPSDK"}],"role":"symbol","required":true,"symbolKind":"method","navigatorTitle":[{"text":"videoAdWasPaused:","kind":"identifier"}],"roleHeading":"Instance Method","title":"videoAdWasPaused(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"videoAdWasPaused","kind":"identifier"},{"text":"(any ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPAdAdaptor","text":"GFPAdAdaptor","kind":"typeIdentifier"},{"kind":"text","text":" & "},{"preciseIdentifier":"c:objc(pl)GFPVideoAdapting","text":"GFPVideoAdapting","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdaptorDelegate"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoAdWasPaused"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"videoAdaptor"},{"kind":"text","text":": any "},{"preciseIdentifier":"c:objc(cs)GFPAdAdaptor","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAdaptor","kind":"typeIdentifier","text":"GFPAdAdaptor"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"GFPVideoAdapting","preciseIdentifier":"c:objc(pl)GFPVideoAdapting","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdapting"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdaptorDelegate\/videoAdWasPaused(_:)"},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdapting":{"title":"GFPVideoAdapting","type":"topic","abstract":[],"url":"\/documentation\/gfpsdk\/gfpvideoadapting","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdapting","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPVideoAdapting"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPVideoAdapting"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdAdaptor":{"navigatorTitle":[{"kind":"identifier","text":"GFPAdAdaptor"}],"title":"GFPAdAdaptor","url":"\/documentation\/gfpsdk\/gfpadadaptor","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdAdaptor","abstract":[],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPAdAdaptor"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdaptorDelegate/videoAdWasPaused(_:)":{"type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdaptorDelegate\/videoAdWasPaused(_:)","abstract":[],"title":"videoAdWasPaused(_:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"videoAdWasPaused"},{"kind":"text","text":"(any "},{"text":"GFPAdAdaptor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdAdaptor"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"GFPVideoAdapting","preciseIdentifier":"c:objc(pl)GFPVideoAdapting"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"videoAdWasPaused:","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpvideoadaptordelegate\/videoadwaspaused(_:)","required":true,"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdaptorDelegate":{"navigatorTitle":[{"kind":"identifier","text":"GFPVideoAdaptorDelegate"}],"type":"topic","url":"\/documentation\/gfpsdk\/gfpvideoadaptordelegate","kind":"symbol","abstract":[],"title":"GFPVideoAdaptorDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPVideoAdaptorDelegate"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdaptorDelegate","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"videoAdWasPaused:","path":"\/metadata\/title","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"videoAdWasPaused:"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"videoAdWasPaused:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Q$objc(cs)GFPAdAdaptorobjc(pl)GFPVideoAdapting","text":"GFPAdAdaptor<GFPVideoAdapting>","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"videoAdaptor","kind":"internalParam"},{"text":";","kind":"text"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdapting\/title","op":"replace","value":"GFPVideoAdapting"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdapting\/fragments","value":[{"kind":"identifier","text":"GFPVideoAdapting"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdapting\/navigatorTitle","value":[{"kind":"identifier","text":"GFPVideoAdapting"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdaptor\/title","value":"GFPAdAdaptor","op":"replace"},{"value":[{"text":"GFPAdAdaptor","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdaptor\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdAdaptor\/navigatorTitle","value":[{"kind":"identifier","text":"GFPAdAdaptor"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdaptorDelegate~1videoAdWasPaused(_:)\/title","value":"videoAdWasPaused:"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdaptorDelegate~1videoAdWasPaused(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"videoAdWasPaused:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdaptorDelegate\/title","value":"GFPVideoAdaptorDelegate"},{"value":[{"text":"GFPVideoAdaptorDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdaptorDelegate\/fragments"},{"value":[{"text":"GFPVideoAdaptorDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdaptorDelegate\/navigatorTitle"}]}]}