{"metadata":{"navigatorTitle":[{"text":"skipButtonTapped:","kind":"identifier"}],"modules":[{"name":"GFPSDK"}],"title":"skipButtonTapped(_:)","symbolKind":"method","roleHeading":"Instance Method","role":"symbol","externalID":"c:objc(pl)GFPVideoAdapting(im)skipButtonTapped:","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"skipButtonTapped"},{"kind":"text","text":"("},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdapting"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpvideoadapting\/skipbuttontapped(_:)"]},{"paths":["\/documentation\/gfpsdk\/gfpvideoadapting\/skipbuttontapped(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdapting\/skipButtonTapped(_:)"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"optional","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"skipButtonTapped"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"sender"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"?)"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdapting/skipButtonTapped(_:)":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdapting\/skipButtonTapped(_:)","navigatorTitle":[{"text":"skipButtonTapped:","kind":"identifier"}],"title":"skipButtonTapped(_:)","abstract":[],"url":"\/documentation\/gfpsdk\/gfpvideoadapting\/skipbuttontapped(_:)","type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"skipButtonTapped"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"?)"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdapting":{"title":"GFPVideoAdapting","type":"topic","abstract":[],"url":"\/documentation\/gfpsdk\/gfpvideoadapting","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdapting","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPVideoAdapting"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPVideoAdapting"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"skipButtonTapped:","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"skipButtonTapped:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"text":"skipButtonTapped:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"sender","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdapting~1skipButtonTapped(_:)\/title","value":"skipButtonTapped:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdapting~1skipButtonTapped(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"skipButtonTapped:"}]},{"op":"replace","value":"GFPVideoAdapting","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdapting\/title"},{"op":"replace","value":[{"text":"GFPVideoAdapting","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdapting\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdapting\/navigatorTitle","value":[{"kind":"identifier","text":"GFPVideoAdapting"}]}]}]}