{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/kGFPVideoGlobalOptions\/globalPlayPolicy_changed"},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/kGFPVideoGlobalOptions"]]},"variants":[{"paths":["\/documentation\/gfpsdk\/kgfpvideoglobaloptions\/globalplaypolicy_changed"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/kgfpvideoglobaloptions\/globalplaypolicy_changed"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"globalPlayPolicy_changed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}]}],"kind":"declarations"}],"metadata":{"symbolKind":"property","externalID":"c:@M@GFPSDK@objc(cs)kGFPVideoGlobalOptions(cpy)globalPlayPolicy_changed","modules":[{"name":"GFPSDK"}],"navigatorTitle":[{"text":"globalPlayPolicy_changed","kind":"identifier"}],"title":"globalPlayPolicy_changed","roleHeading":"Type Property","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"globalPlayPolicy_changed"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"role":"symbol"},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/kGFPVideoGlobalOptions":{"navigatorTitle":[{"kind":"identifier","text":"kGFPVideoGlobalOptions"}],"title":"kGFPVideoGlobalOptions","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"kGFPVideoGlobalOptions"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/kGFPVideoGlobalOptions","url":"\/documentation\/gfpsdk\/kgfpvideoglobaloptions","abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/kGFPVideoGlobalOptions/globalPlayPolicy_changed":{"navigatorTitle":[{"kind":"identifier","text":"globalPlayPolicy_changed"}],"title":"globalPlayPolicy_changed","type":"topic","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"globalPlayPolicy_changed"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/kGFPVideoGlobalOptions\/globalPlayPolicy_changed","kind":"symbol","abstract":[],"url":"\/documentation\/gfpsdk\/kgfpvideoglobaloptions\/globalplaypolicy_changed"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Type Property","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"globalPlayPolicy_changed"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"text":"globalPlayPolicy_changed","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"globalPlayPolicy_changed","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1kGFPVideoGlobalOptions\/title","value":"kGFPVideoGlobalOptions","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1kGFPVideoGlobalOptions\/fragments","value":[{"kind":"identifier","text":"kGFPVideoGlobalOptions"}],"op":"replace"},{"value":[{"kind":"identifier","text":"kGFPVideoGlobalOptions"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1kGFPVideoGlobalOptions\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1kGFPVideoGlobalOptions~1globalPlayPolicy_changed\/title","value":"globalPlayPolicy_changed","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1kGFPVideoGlobalOptions~1globalPlayPolicy_changed\/fragments","value":[{"text":"globalPlayPolicy_changed","kind":"identifier"}]}]}]}