{"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdMuteData\/reasonCodes"},"metadata":{"title":"reasonCodes","role":"symbol","modules":[{"name":"GFPSDK"}],"roleHeading":"Instance Property","symbolKind":"property","navigatorTitle":[{"text":"reasonCodes","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"reasonCodes"},{"text":": [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"externalID":"c:objc(cs)GFPAdMuteData(py)reasonCodes"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"reasonCodes"},{"kind":"text","text":": ["},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"] { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpadmutedata\/reasoncodes"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gfpsdk\/gfpadmutedata\/reasoncodes"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdMuteData"]]},"sections":[],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdMuteData/reasonCodes":{"navigatorTitle":[{"text":"reasonCodes","kind":"identifier"}],"role":"symbol","title":"reasonCodes","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"reasonCodes","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"]","kind":"text"}],"type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdMuteData\/reasonCodes","abstract":[],"url":"\/documentation\/gfpsdk\/gfpadmutedata\/reasoncodes"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdMuteData":{"navigatorTitle":[{"kind":"identifier","text":"GFPAdMuteData"}],"role":"symbol","title":"GFPAdMuteData","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPAdMuteData"}],"type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdMuteData","abstract":[],"url":"\/documentation\/gfpsdk\/gfpadmutedata"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","value":"reasonCodes","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"reasonCodes","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSString *>","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"reasonCodes","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"reasonCodes","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdMuteData~1reasonCodes\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdMuteData~1reasonCodes\/fragments","value":[{"kind":"identifier","text":"reasonCodes"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdMuteData\/title","value":"GFPAdMuteData"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdMuteData\/fragments","value":[{"kind":"identifier","text":"GFPAdMuteData"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdMuteData\/navigatorTitle","value":[{"text":"GFPAdMuteData","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}