{"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerAdSizeHelper"]]},"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpbanneradsizehelper\/type(with:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpbanneradsizehelper\/type(with:)"]}],"metadata":{"title":"type(with:)","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPBannerViewLayoutType","text":"GFPBannerViewLayoutType"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPBannerSizeType","text":"GFPBannerSizeType"}],"roleHeading":"Type Method","role":"symbol","externalID":"c:objc(cs)GFPBannerAdSizeHelper(cm)typeWith:","symbolKind":"method","navigatorTitle":[{"text":"typeWith:","kind":"identifier"}],"modules":[{"name":"GFPSDK"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerAdSizeHelper\/type(with:)"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"type"},{"kind":"text","text":"("},{"text":"with","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"aLayoutType","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerViewLayoutType","preciseIdentifier":"c:@E@GFPBannerViewLayoutType","kind":"typeIdentifier","text":"GFPBannerViewLayoutType"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"GFPBannerSizeType","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerSizeType","preciseIdentifier":"c:@E@GFPBannerSizeType"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerAdSizeHelper/type(with:)":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerAdSizeHelper\/type(with:)","url":"\/documentation\/gfpsdk\/gfpbanneradsizehelper\/type(with:)","title":"type(with:)","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"type","kind":"identifier"},{"kind":"text","text":"("},{"text":"with","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPBannerViewLayoutType","text":"GFPBannerViewLayoutType"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPBannerSizeType","text":"GFPBannerSizeType"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"typeWith:"}],"kind":"symbol","type":"topic","abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerAdSizeHelper":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerAdSizeHelper","url":"\/documentation\/gfpsdk\/gfpbanneradsizehelper","title":"GFPBannerAdSizeHelper","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPBannerAdSizeHelper"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPBannerAdSizeHelper"}],"kind":"symbol","type":"topic","abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerSizeType":{"role":"symbol","abstract":[],"title":"GFPBannerSizeType","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerSizeType","url":"\/documentation\/gfpsdk\/gfpbannersizetype","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPBannerSizeType"}],"navigatorTitle":[{"text":"GFPBannerSizeType","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerViewLayoutType":{"kind":"symbol","title":"GFPBannerViewLayoutType","url":"\/documentation\/gfpsdk\/gfpbannerviewlayouttype","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPBannerViewLayoutType"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerViewLayoutType","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GFPBannerViewLayoutType"}],"abstract":[]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"value":"typeWith:","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"typeWith:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerSizeType","text":"GFPBannerSizeType","preciseIdentifier":"c:@E@GFPBannerSizeType"},{"kind":"text","text":") "},{"text":"typeWith:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@E@GFPBannerViewLayoutType","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerViewLayoutType","text":"GFPBannerViewLayoutType"},{"kind":"text","text":") "},{"kind":"internalParam","text":"aLayoutType"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"typeWith:","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerAdSizeHelper~1type(with:)\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerAdSizeHelper~1type(with:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"typeWith:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerAdSizeHelper\/title","value":"GFPBannerAdSizeHelper"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerAdSizeHelper\/fragments","value":[{"text":"GFPBannerAdSizeHelper","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerAdSizeHelper\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"GFPBannerAdSizeHelper"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerSizeType\/title","value":"GFPBannerSizeType"},{"value":[{"text":"GFPBannerSizeType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerSizeType\/fragments"},{"value":[{"text":"GFPBannerSizeType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerSizeType\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerViewLayoutType\/title","value":"GFPBannerViewLayoutType","op":"replace"},{"value":[{"text":"GFPBannerViewLayoutType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerViewLayoutType\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerViewLayoutType\/navigatorTitle","value":[{"text":"GFPBannerViewLayoutType","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}