{"topicSections":[{"title":"Instance Properties","generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRichExtendMediaRatioType\/hashValue"]},{"title":"Instance Methods","generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRichExtendMediaRatioType\/hash(into:)"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfprichextendmediaratiotype\/_swiftnewtypewrapper-implementations"]}],"metadata":{"roleHeading":"API Collection","role":"collectionGroup","title":"_SwiftNewtypeWrapper Implementations","modules":[{"name":"GFPSDK"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRichExtendMediaRatioType\/_SwiftNewtypeWrapper-Implementations","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRichExtendMediaRatioType"]]},"sections":[],"kind":"article","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRichExtendMediaRatioType/hash(into:)":{"url":"\/documentation\/gfpsdk\/gfprichextendmediaratiotype\/hash(into:)","title":"hash(into:)","kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRichExtendMediaRatioType\/hash(into:)","conformance":{"constraints":[{"code":"Self","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"RawValue","type":"codeVoice"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}],"availabilityPrefix":[{"text":"Available when","type":"text"}],"conformancePrefix":[{"text":"Conforms when","type":"text"}]},"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hash"},{"kind":"text","text":"("},{"text":"into","kind":"externalParam"},{"kind":"text","text":": "},{"text":"inout","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:s6HasherV","text":"Hasher","kind":"typeIdentifier"},{"kind":"text","text":")"}],"abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRichExtendMediaRatioType/hashValue":{"conformance":{"availabilityPrefix":[{"text":"Available when","type":"text"}],"conformancePrefix":[{"text":"Conforms when","type":"text"}],"constraints":[{"code":"Self","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"RawValue","type":"codeVoice"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}]},"type":"topic","title":"hashValue","abstract":[],"role":"symbol","url":"\/documentation\/gfpsdk\/gfprichextendmediaratiotype\/hashvalue","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRichExtendMediaRatioType\/hashValue","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hashValue"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPRichExtendMediaRatioType":{"type":"topic","url":"\/documentation\/gfpsdk\/gfprichextendmediaratiotype","abstract":[],"navigatorTitle":[{"text":"GFPRichExtendMediaRatioType","kind":"identifier"}],"role":"symbol","title":"GFPRichExtendMediaRatioType","kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPRichExtendMediaRatioType","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"GFPRichExtendMediaRatioType","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRichExtendMediaRatioType\/title","op":"replace","value":"GFPRichExtendMediaRatioType"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRichExtendMediaRatioType\/fragments","op":"replace","value":[{"text":"GFPRichExtendMediaRatioType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPRichExtendMediaRatioType\/navigatorTitle","value":[{"text":"GFPRichExtendMediaRatioType","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}