{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"weak"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": (any "},{"kind":"typeIdentifier","text":"GFPBannerMediatorDelegate","preciseIdentifier":"c:objc(pl)GFPBannerMediatorDelegate","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerMediatorDelegate"},{"kind":"text","text":")? { "},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerMediator"]]},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerMediator\/delegate","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","metadata":{"symbolKind":"property","modules":[{"name":"GFPSDK"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"delegate","kind":"identifier"},{"kind":"text","text":": (any "},{"text":"GFPBannerMediatorDelegate","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)GFPBannerMediatorDelegate"},{"text":")?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"delegate"}],"title":"delegate","externalID":"c:objc(cs)GFPBannerMediator(py)delegate","roleHeading":"Instance Property","role":"symbol"},"sections":[],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpbannermediator\/delegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gfpsdk\/gfpbannermediator\/delegate"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerMediator/delegate":{"title":"delegate","navigatorTitle":[{"text":"delegate","kind":"identifier"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerMediator\/delegate","url":"\/documentation\/gfpsdk\/gfpbannermediator\/delegate","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"text":": (any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)GFPBannerMediatorDelegate","text":"GFPBannerMediatorDelegate"},{"text":")?","kind":"text"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerMediatorDelegate":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"GFPBannerMediatorDelegate"}],"kind":"symbol","url":"\/documentation\/gfpsdk\/gfpbannermediatordelegate","role":"symbol","abstract":[],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPBannerMediatorDelegate"}],"title":"GFPBannerMediatorDelegate","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerMediatorDelegate"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerMediator":{"type":"topic","navigatorTitle":[{"text":"GFPBannerMediator","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/gfpsdk\/gfpbannermediator","role":"symbol","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPBannerMediator"}],"title":"GFPBannerMediator","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerMediator"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"delegate","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"delegate"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"weak","kind":"keyword"},{"kind":"text","text":", "},{"text":"readwrite","kind":"keyword"},{"text":") ","kind":"text"},{"text":"id<GFPBannerMediatorDelegate>","kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)GFPBannerMediatorDelegate"},{"kind":"text","text":" "},{"text":"delegate","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"value":"delegate","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerMediator~1delegate\/title"},{"op":"replace","value":[{"kind":"identifier","text":"delegate"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerMediator~1delegate\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerMediatorDelegate\/title","value":"GFPBannerMediatorDelegate"},{"value":[{"text":"GFPBannerMediatorDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerMediatorDelegate\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerMediatorDelegate\/navigatorTitle","value":[{"text":"GFPBannerMediatorDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerMediator\/title","op":"replace","value":"GFPBannerMediator"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerMediator\/fragments","value":[{"text":"GFPBannerMediator","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"GFPBannerMediator"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerMediator\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}