{"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"loadBannerAdaptor","kind":"identifier"},{"kind":"text","text":"("},{"text":"withAdUnitID","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"bannerContext"},{"kind":"text","text":": "},{"text":"GFPBannerContext","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPBannerContext"},{"kind":"text","text":", "},{"text":"nativeContext","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"GFPNativeContext","preciseIdentifier":"c:objc(cs)GFPNativeContext","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"adParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdParam","text":"GFPAdParam"},{"kind":"text","text":"?, "},{"text":"timeoutInterval","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":")"}],"symbolKind":"method","role":"symbol","roleHeading":"Instance Method","externalID":"c:objc(cs)GFPBannerMediator(im)loadBannerAdaptorWithAdUnitID:bannerContext:nativeContext:adParam:timeoutInterval:","title":"loadBannerAdaptor(withAdUnitID:bannerContext:nativeContext:adParam:timeoutInterval:)","modules":[{"name":"GFPSDK"}],"navigatorTitle":[{"text":"loadBannerAdaptorWithAdUnitID:bannerContext:nativeContext:adParam:timeoutInterval:","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"loadBannerAdaptor","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withAdUnitID","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"adUnitID","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"bannerContext"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerContext","text":"GFPBannerContext","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPBannerContext"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"nativeContext"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GFPNativeContext","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeContext","preciseIdentifier":"c:objc(cs)GFPNativeContext"},{"text":", ","kind":"text"},{"text":"adParam","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdParam","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdParam","text":"GFPAdParam"},{"text":"?, ","kind":"text"},{"text":"timeoutInterval","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier"},{"kind":"text","text":")"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpbannermediator\/loadbanneradaptor(withadunitid:bannercontext:nativecontext:adparam:timeoutinterval:)"]},{"paths":["\/documentation\/gfpsdk\/gfpbannermediator\/loadbanneradaptor(withadunitid:bannercontext:nativecontext:adparam:timeoutinterval:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerMediator"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerMediator\/loadBannerAdaptor(withAdUnitID:bannerContext:nativeContext:adParam:timeoutInterval:)"},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerMediator":{"type":"topic","navigatorTitle":[{"text":"GFPBannerMediator","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/gfpsdk\/gfpbannermediator","role":"symbol","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPBannerMediator"}],"title":"GFPBannerMediator","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerMediator"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerMediator/loadBannerAdaptor(withAdUnitID:bannerContext:nativeContext:adParam:timeoutInterval:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"loadBannerAdaptor","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withAdUnitID","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"bannerContext"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPBannerContext","kind":"typeIdentifier","text":"GFPBannerContext"},{"text":", ","kind":"text"},{"text":"nativeContext","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"GFPNativeContext","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPNativeContext"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"adParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)GFPAdParam","text":"GFPAdParam","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"timeoutInterval","kind":"externalParam"},{"kind":"text","text":": "},{"text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/gfpsdk\/gfpbannermediator\/loadbanneradaptor(withadunitid:bannercontext:nativecontext:adparam:timeoutinterval:)","kind":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerMediator\/loadBannerAdaptor(withAdUnitID:bannerContext:nativeContext:adParam:timeoutInterval:)","role":"symbol","navigatorTitle":[{"text":"loadBannerAdaptorWithAdUnitID:bannerContext:nativeContext:adParam:timeoutInterval:","kind":"identifier"}],"title":"loadBannerAdaptor(withAdUnitID:bannerContext:nativeContext:adParam:timeoutInterval:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeContext":{"role":"symbol","title":"GFPNativeContext","url":"\/documentation\/gfpsdk\/gfpnativecontext","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeContext","navigatorTitle":[{"text":"GFPNativeContext","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"GFPNativeContext","kind":"identifier"}],"abstract":[],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdParam":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdParam","abstract":[],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPAdParam"}],"navigatorTitle":[{"text":"GFPAdParam","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpadparam","type":"topic","kind":"symbol","title":"GFPAdParam"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerContext":{"kind":"symbol","title":"GFPBannerContext","url":"\/documentation\/gfpsdk\/gfpbannercontext","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPBannerContext"}],"type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerContext","navigatorTitle":[{"kind":"identifier","text":"GFPBannerContext"}],"abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"loadBannerAdaptorWithAdUnitID:bannerContext:nativeContext:adParam:timeoutInterval:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"loadBannerAdaptorWithAdUnitID:bannerContext:nativeContext:adParam:timeoutInterval:","kind":"identifier"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"loadBannerAdaptorWithAdUnitID:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"text":"adUnitID","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"bannerContext:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPBannerContext","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerContext","text":"GFPBannerContext"},{"text":" *) ","kind":"text"},{"text":"bannerContext","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"nativeContext:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"GFPNativeContext","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeContext","preciseIdentifier":"c:objc(cs)GFPNativeContext"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"nativeContext"},{"kind":"text","text":" "},{"text":"adParam:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdParam","text":"GFPAdParam","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdParam"},{"kind":"text","text":" *) "},{"text":"adParam","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"timeoutInterval:"},{"kind":"text","text":"("},{"text":"NSTimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":") "},{"kind":"internalParam","text":"timeoutInterval"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerMediator\/title","value":"GFPBannerMediator"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerMediator\/fragments","op":"replace","value":[{"text":"GFPBannerMediator","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerMediator\/navigatorTitle","value":[{"text":"GFPBannerMediator","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerMediator~1loadBannerAdaptor(withAdUnitID:bannerContext:nativeContext:adParam:timeoutInterval:)\/title","value":"loadBannerAdaptorWithAdUnitID:bannerContext:nativeContext:adParam:timeoutInterval:"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerMediator~1loadBannerAdaptor(withAdUnitID:bannerContext:nativeContext:adParam:timeoutInterval:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"loadBannerAdaptorWithAdUnitID:bannerContext:nativeContext:adParam:timeoutInterval:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeContext\/title","value":"GFPNativeContext","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"GFPNativeContext"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeContext\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeContext\/navigatorTitle","value":[{"text":"GFPNativeContext","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdParam\/title","value":"GFPAdParam"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdParam\/fragments","value":[{"text":"GFPAdParam","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdParam\/navigatorTitle","value":[{"text":"GFPAdParam","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerContext\/title","value":"GFPBannerContext","op":"replace"},{"value":[{"kind":"identifier","text":"GFPBannerContext"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerContext\/fragments","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"GFPBannerContext"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerContext\/navigatorTitle"}]}]}