{"variants":[{"paths":["\/documentation\/gfpsdk\/gfpbannermediator\/reportdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gfpsdk\/gfpbannermediator\/reportdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"reportDelegate"},{"kind":"text","text":": (any "},{"kind":"typeIdentifier","text":"GFPEventReportDelegate","preciseIdentifier":"c:objc(pl)GFPEventReportDelegate"},{"kind":"text","text":")?"}],"navigatorTitle":[{"text":"reportDelegate","kind":"identifier"}],"roleHeading":"Instance Property","role":"symbol","externalID":"c:objc(cs)GFPBannerMediator(py)reportDelegate","modules":[{"name":"GFPSDK"}],"title":"reportDelegate","symbolKind":"property"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerMediator"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerMediator\/reportDelegate"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"weak","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"reportDelegate","kind":"identifier"},{"kind":"text","text":": (any "},{"text":"GFPEventReportDelegate","preciseIdentifier":"c:objc(pl)GFPEventReportDelegate","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPEventReportDelegate"},{"text":")? { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerMediator":{"type":"topic","navigatorTitle":[{"text":"GFPBannerMediator","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/gfpsdk\/gfpbannermediator","role":"symbol","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPBannerMediator"}],"title":"GFPBannerMediator","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerMediator"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPBannerMediator/reportDelegate":{"navigatorTitle":[{"kind":"identifier","text":"reportDelegate"}],"role":"symbol","kind":"symbol","title":"reportDelegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"reportDelegate","kind":"identifier"},{"text":": (any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)GFPEventReportDelegate","text":"GFPEventReportDelegate"},{"text":")?","kind":"text"}],"type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPBannerMediator\/reportDelegate","abstract":[],"url":"\/documentation\/gfpsdk\/gfpbannermediator\/reportdelegate"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPEventReportDelegate":{"kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPEventReportDelegate","title":"GFPEventReportDelegate","url":"\/documentation\/gfpsdk\/gfpeventreportdelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"GFPEventReportDelegate","kind":"identifier"}],"abstract":[],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GFPEventReportDelegate"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"reportDelegate"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"value":[{"text":"reportDelegate","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"weak"},{"kind":"text","text":") "},{"preciseIdentifier":"c:Qoobjc(pl)GFPEventReportDelegate","text":"id<GFPEventReportDelegate>","kind":"typeIdentifier"},{"kind":"text","text":" "},{"kind":"identifier","text":"reportDelegate"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"value":"GFPBannerMediator","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerMediator\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerMediator\/fragments","op":"replace","value":[{"kind":"identifier","text":"GFPBannerMediator"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerMediator\/navigatorTitle","value":[{"text":"GFPBannerMediator","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerMediator~1reportDelegate\/title","op":"replace","value":"reportDelegate"},{"value":[{"text":"reportDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPBannerMediator~1reportDelegate\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPEventReportDelegate\/title","value":"GFPEventReportDelegate","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPEventReportDelegate\/fragments","value":[{"kind":"identifier","text":"GFPEventReportDelegate"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPEventReportDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"GFPEventReportDelegate"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}