{"abstract":[{"text":"광고를 스킵 할 수 있을 때 발생","type":"text"}],"metadata":{"title":"scheduleManager(_:canBeSkipAdWith:)","symbolKind":"method","modules":[{"name":"GFPSDK"}],"role":"symbol","externalID":"c:objc(pl)GFPVideoAdScheduleManagerQoeDelegate(im)scheduleManager:canBeSkipAdWithQoeInfo:","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"scheduleManager","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)GFPVideoAdScheduleManager","text":"GFPVideoAdScheduleManager","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"canBeSkipAdWith","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"GFPVideoAdQoeInfo","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoAdQoeInfo"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"scheduleManager:canBeSkipAdWithQoeInfo:","kind":"identifier"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManagerQoeDelegate\/scheduleManager(_:canBeSkipAdWith:)"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManagerQoeDelegate"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"scheduleManager","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"aScheduleAdManager","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"GFPVideoAdScheduleManager","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager","preciseIdentifier":"c:objc(cs)GFPVideoAdScheduleManager"},{"kind":"text","text":", "},{"text":"canBeSkipAdWith","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"info"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)GFPVideoAdQoeInfo","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdQoeInfo","kind":"typeIdentifier","text":"GFPVideoAdQoeInfo"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"aScheduleAdManager","content":[{"inlineContent":[{"type":"text","text":"스케쥴 매니저"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"QOE 정보"}]}],"name":"info"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpvideoadschedulemanagerqoedelegate\/schedulemanager(_:canbeskipadwith:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpvideoadschedulemanagerqoedelegate\/schedulemanager(_:canbeskipadwith:)"]}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdScheduleManager":{"kind":"symbol","type":"topic","url":"\/documentation\/gfpsdk\/gfpvideoadschedulemanager","title":"GFPVideoAdScheduleManager","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager","navigatorTitle":[{"kind":"identifier","text":"GFPVideoAdScheduleManager"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPVideoAdScheduleManager"}],"abstract":[],"role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdQoeInfo":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"GFPVideoAdQoeInfo"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdQoeInfo","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPVideoAdQoeInfo","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpvideoadqoeinfo","role":"symbol","kind":"symbol","title":"GFPVideoAdQoeInfo"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdScheduleManagerQoeDelegate":{"kind":"symbol","abstract":[],"url":"\/documentation\/gfpsdk\/gfpvideoadschedulemanagerqoedelegate","type":"topic","title":"GFPVideoAdScheduleManagerQoeDelegate","navigatorTitle":[{"kind":"identifier","text":"GFPVideoAdScheduleManagerQoeDelegate"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManagerQoeDelegate","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPVideoAdScheduleManagerQoeDelegate"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdScheduleManagerQoeDelegate/scheduleManager(_:canBeSkipAdWith:)":{"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"scheduleManager"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)GFPVideoAdScheduleManager","text":"GFPVideoAdScheduleManager","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"canBeSkipAdWith","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPVideoAdQoeInfo","kind":"typeIdentifier","text":"GFPVideoAdQoeInfo"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"scheduleManager:canBeSkipAdWithQoeInfo:","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManagerQoeDelegate\/scheduleManager(_:canBeSkipAdWith:)","url":"\/documentation\/gfpsdk\/gfpvideoadschedulemanagerqoedelegate\/schedulemanager(_:canbeskipadwith:)","role":"symbol","abstract":[{"type":"text","text":"광고를 스킵 할 수 있을 때 발생"}],"type":"topic","title":"scheduleManager(_:canBeSkipAdWith:)"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","value":"scheduleManager:canBeSkipAdWithQoeInfo:","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"scheduleManager:canBeSkipAdWithQoeInfo:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"scheduleManager:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPVideoAdScheduleManager","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager","text":"GFPVideoAdScheduleManager"},{"text":" *) ","kind":"text"},{"text":"aScheduleAdManager","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"canBeSkipAdWithQoeInfo:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdQoeInfo","preciseIdentifier":"c:objc(cs)GFPVideoAdQoeInfo","kind":"typeIdentifier","text":"GFPVideoAdQoeInfo"},{"text":" *) ","kind":"text"},{"text":"info","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":{"parameters":[{"content":[{"inlineContent":[{"text":"스케쥴 매니저","type":"text"}],"type":"paragraph"}],"name":"aScheduleAdManager"},{"name":"info","content":[{"inlineContent":[{"text":"QOE 정보","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},"path":"\/primaryContentSections\/1"},{"op":"replace","value":"GFPVideoAdScheduleManager","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager\/title"},{"value":[{"kind":"identifier","text":"GFPVideoAdScheduleManager"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager\/navigatorTitle","value":[{"text":"GFPVideoAdScheduleManager","kind":"identifier"}]},{"value":"GFPVideoAdQoeInfo","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdQoeInfo\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdQoeInfo\/fragments","value":[{"text":"GFPVideoAdQoeInfo","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdQoeInfo\/navigatorTitle","value":[{"text":"GFPVideoAdQoeInfo","kind":"identifier"}]},{"value":"GFPVideoAdScheduleManagerQoeDelegate","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManagerQoeDelegate\/title","op":"replace"},{"value":[{"text":"GFPVideoAdScheduleManagerQoeDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManagerQoeDelegate\/fragments","op":"replace"},{"op":"replace","value":[{"text":"GFPVideoAdScheduleManagerQoeDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManagerQoeDelegate\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManagerQoeDelegate~1scheduleManager(_:canBeSkipAdWith:)\/title","value":"scheduleManager:canBeSkipAdWithQoeInfo:","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManagerQoeDelegate~1scheduleManager(_:canBeSkipAdWith:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"scheduleManager:canBeSkipAdWithQoeInfo:"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}