{"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"광고가 로드된 경우 발생"}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManagerQoeDelegate"]]},"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpvideoadschedulemanagerqoedelegate\/schedulemanager(_:didloadadwith:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpvideoadschedulemanagerqoedelegate\/schedulemanager(_:didloadadwith:)"]}],"metadata":{"title":"scheduleManager(_:didLoadAdWith:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"scheduleManager","kind":"identifier"},{"kind":"text","text":"("},{"text":"GFPVideoAdScheduleManager","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoAdScheduleManager"},{"text":", ","kind":"text"},{"text":"didLoadAdWith","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)GFPVideoAdQoeInfo","text":"GFPVideoAdQoeInfo","kind":"typeIdentifier"},{"text":")","kind":"text"}],"roleHeading":"Instance Method","role":"symbol","required":true,"externalID":"c:objc(pl)GFPVideoAdScheduleManagerQoeDelegate(im)scheduleManager:didLoadAdWithQoeInfo:","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"scheduleManager:didLoadAdWithQoeInfo:"}],"modules":[{"name":"GFPSDK"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManagerQoeDelegate\/scheduleManager(_:didLoadAdWith:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"scheduleManager","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"aScheduleAdManager","kind":"internalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoAdScheduleManager","text":"GFPVideoAdScheduleManager"},{"text":", ","kind":"text"},{"text":"didLoadAdWith","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"info","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdQoeInfo","text":"GFPVideoAdQoeInfo","preciseIdentifier":"c:objc(cs)GFPVideoAdQoeInfo"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"parameters":[{"name":"aScheduleAdManager","content":[{"inlineContent":[{"type":"text","text":"스케쥴 매니저"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"QOE 정보","type":"text"}]}],"name":"info"}],"kind":"parameters"}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdScheduleManager":{"kind":"symbol","type":"topic","url":"\/documentation\/gfpsdk\/gfpvideoadschedulemanager","title":"GFPVideoAdScheduleManager","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager","navigatorTitle":[{"kind":"identifier","text":"GFPVideoAdScheduleManager"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPVideoAdScheduleManager"}],"abstract":[],"role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdQoeInfo":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"GFPVideoAdQoeInfo"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdQoeInfo","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPVideoAdQoeInfo","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpvideoadqoeinfo","role":"symbol","kind":"symbol","title":"GFPVideoAdQoeInfo"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdScheduleManagerQoeDelegate":{"kind":"symbol","abstract":[],"url":"\/documentation\/gfpsdk\/gfpvideoadschedulemanagerqoedelegate","type":"topic","title":"GFPVideoAdScheduleManagerQoeDelegate","navigatorTitle":[{"kind":"identifier","text":"GFPVideoAdScheduleManagerQoeDelegate"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManagerQoeDelegate","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPVideoAdScheduleManagerQoeDelegate"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdScheduleManagerQoeDelegate/scheduleManager(_:didLoadAdWith:)":{"type":"topic","url":"\/documentation\/gfpsdk\/gfpvideoadschedulemanagerqoedelegate\/schedulemanager(_:didloadadwith:)","title":"scheduleManager(_:didLoadAdWith:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"scheduleManager"},{"text":"(","kind":"text"},{"text":"GFPVideoAdScheduleManager","preciseIdentifier":"c:objc(cs)GFPVideoAdScheduleManager","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"didLoadAdWith","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GFPVideoAdQoeInfo","preciseIdentifier":"c:objc(cs)GFPVideoAdQoeInfo"},{"text":")","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"scheduleManager:didLoadAdWithQoeInfo:","kind":"identifier"}],"kind":"symbol","required":true,"abstract":[{"type":"text","text":"광고가 로드된 경우 발생"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManagerQoeDelegate\/scheduleManager(_:didLoadAdWith:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","value":"scheduleManager:didLoadAdWithQoeInfo:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"scheduleManager:didLoadAdWithQoeInfo:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"scheduleManager:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoAdScheduleManager","text":"GFPVideoAdScheduleManager"},{"text":" *) ","kind":"text"},{"text":"aScheduleAdManager","kind":"internalParam"},{"kind":"text","text":" "},{"text":"didLoadAdWithQoeInfo:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdQoeInfo","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoAdQoeInfo","text":"GFPVideoAdQoeInfo"},{"text":" *) ","kind":"text"},{"text":"info","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"스케쥴 매니저"}]}],"name":"aScheduleAdManager"},{"name":"info","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"QOE 정보"}]}]}]},"path":"\/primaryContentSections\/1","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager\/title","value":"GFPVideoAdScheduleManager","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager\/fragments","value":[{"text":"GFPVideoAdScheduleManager","kind":"identifier"}],"op":"replace"},{"value":[{"text":"GFPVideoAdScheduleManager","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdQoeInfo\/title","value":"GFPVideoAdQoeInfo","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdQoeInfo\/fragments","op":"replace","value":[{"kind":"identifier","text":"GFPVideoAdQoeInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdQoeInfo\/navigatorTitle","value":[{"text":"GFPVideoAdQoeInfo","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManagerQoeDelegate\/title","op":"replace","value":"GFPVideoAdScheduleManagerQoeDelegate"},{"op":"replace","value":[{"text":"GFPVideoAdScheduleManagerQoeDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManagerQoeDelegate\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManagerQoeDelegate\/navigatorTitle","value":[{"text":"GFPVideoAdScheduleManagerQoeDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManagerQoeDelegate~1scheduleManager(_:didLoadAdWith:)\/title","value":"scheduleManager:didLoadAdWithQoeInfo:","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManagerQoeDelegate~1scheduleManager(_:didLoadAdWith:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"scheduleManager:didLoadAdWithQoeInfo:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}