{"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"scheduleManager"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"aScheduleAdManager","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"GFPVideoAdScheduleManager","preciseIdentifier":"c:objc(cs)GFPVideoAdScheduleManager","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager"},{"kind":"text","text":", "},{"text":"didReceiveAdClickEventWitQoeInfo","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"info","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdQoeInfo","text":"GFPVideoAdQoeInfo","preciseIdentifier":"c:objc(cs)GFPVideoAdQoeInfo"},{"kind":"text","text":")"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"스케쥴 매니저"}]}],"name":"aScheduleAdManager"},{"name":"info","content":[{"inlineContent":[{"text":"QOE 정보","type":"text"}],"type":"paragraph"}]}]}],"metadata":{"required":true,"modules":[{"name":"GFPSDK"}],"navigatorTitle":[{"text":"scheduleManager:didReceiveAdClickEventWitQoeInfo:","kind":"identifier"}],"title":"scheduleManager(_:didReceiveAdClickEventWitQoeInfo:)","symbolKind":"method","role":"symbol","externalID":"c:objc(pl)GFPVideoAdScheduleManagerQoeDelegate(im)scheduleManager:didReceiveAdClickEventWitQoeInfo:","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"scheduleManager"},{"kind":"text","text":"("},{"text":"GFPVideoAdScheduleManager","preciseIdentifier":"c:objc(cs)GFPVideoAdScheduleManager","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didReceiveAdClickEventWitQoeInfo"},{"text":": ","kind":"text"},{"text":"GFPVideoAdQoeInfo","preciseIdentifier":"c:objc(cs)GFPVideoAdQoeInfo","kind":"typeIdentifier"},{"kind":"text","text":")"}],"roleHeading":"Instance Method"},"abstract":[{"text":"광고가 클릭 된 경우 발생","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManagerQoeDelegate"]]},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManagerQoeDelegate\/scheduleManager(_:didReceiveAdClickEventWitQoeInfo:)","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpvideoadschedulemanagerqoedelegate\/schedulemanager(_:didreceiveadclickeventwitqoeinfo:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpvideoadschedulemanagerqoedelegate\/schedulemanager(_:didreceiveadclickeventwitqoeinfo:)"]}],"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdScheduleManagerQoeDelegate":{"kind":"symbol","abstract":[],"url":"\/documentation\/gfpsdk\/gfpvideoadschedulemanagerqoedelegate","type":"topic","title":"GFPVideoAdScheduleManagerQoeDelegate","navigatorTitle":[{"kind":"identifier","text":"GFPVideoAdScheduleManagerQoeDelegate"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManagerQoeDelegate","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPVideoAdScheduleManagerQoeDelegate"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdScheduleManagerQoeDelegate/scheduleManager(_:didReceiveAdClickEventWitQoeInfo:)":{"kind":"symbol","required":true,"type":"topic","navigatorTitle":[{"kind":"identifier","text":"scheduleManager:didReceiveAdClickEventWitQoeInfo:"}],"url":"\/documentation\/gfpsdk\/gfpvideoadschedulemanagerqoedelegate\/schedulemanager(_:didreceiveadclickeventwitqoeinfo:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"scheduleManager"},{"text":"(","kind":"text"},{"text":"GFPVideoAdScheduleManager","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoAdScheduleManager"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didReceiveAdClickEventWitQoeInfo"},{"text":": ","kind":"text"},{"text":"GFPVideoAdQoeInfo","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoAdQoeInfo"},{"kind":"text","text":")"}],"role":"symbol","abstract":[{"text":"광고가 클릭 된 경우 발생","type":"text"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManagerQoeDelegate\/scheduleManager(_:didReceiveAdClickEventWitQoeInfo:)","title":"scheduleManager(_:didReceiveAdClickEventWitQoeInfo:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdQoeInfo":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"GFPVideoAdQoeInfo"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdQoeInfo","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPVideoAdQoeInfo","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpvideoadqoeinfo","role":"symbol","kind":"symbol","title":"GFPVideoAdQoeInfo"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdScheduleManager":{"kind":"symbol","type":"topic","url":"\/documentation\/gfpsdk\/gfpvideoadschedulemanager","title":"GFPVideoAdScheduleManager","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager","navigatorTitle":[{"kind":"identifier","text":"GFPVideoAdScheduleManager"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPVideoAdScheduleManager"}],"abstract":[],"role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"scheduleManager:didReceiveAdClickEventWitQoeInfo:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"scheduleManager:didReceiveAdClickEventWitQoeInfo:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"scheduleManager:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager","text":"GFPVideoAdScheduleManager","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoAdScheduleManager"},{"text":" *) ","kind":"text"},{"text":"aScheduleAdManager","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"didReceiveAdClickEventWitQoeInfo:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)GFPVideoAdQoeInfo","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdQoeInfo","kind":"typeIdentifier","text":"GFPVideoAdQoeInfo"},{"kind":"text","text":" *) "},{"text":"info","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"스케쥴 매니저"}],"type":"paragraph"}],"name":"aScheduleAdManager"},{"content":[{"inlineContent":[{"text":"QOE 정보","type":"text"}],"type":"paragraph"}],"name":"info"}],"kind":"parameters"}},{"value":"GFPVideoAdScheduleManagerQoeDelegate","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManagerQoeDelegate\/title","op":"replace"},{"op":"replace","value":[{"text":"GFPVideoAdScheduleManagerQoeDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManagerQoeDelegate\/fragments"},{"value":[{"text":"GFPVideoAdScheduleManagerQoeDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManagerQoeDelegate\/navigatorTitle"},{"value":"scheduleManager:didReceiveAdClickEventWitQoeInfo:","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManagerQoeDelegate~1scheduleManager(_:didReceiveAdClickEventWitQoeInfo:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"scheduleManager:didReceiveAdClickEventWitQoeInfo:"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManagerQoeDelegate~1scheduleManager(_:didReceiveAdClickEventWitQoeInfo:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdQoeInfo\/title","value":"GFPVideoAdQoeInfo"},{"op":"replace","value":[{"kind":"identifier","text":"GFPVideoAdQoeInfo"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdQoeInfo\/fragments"},{"value":[{"text":"GFPVideoAdQoeInfo","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdQoeInfo\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager\/title","value":"GFPVideoAdScheduleManager"},{"value":[{"kind":"identifier","text":"GFPVideoAdScheduleManager"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"GFPVideoAdScheduleManager"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}