{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"optional"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"scheduleManager","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"aScheduleAdManager"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager","text":"GFPVideoAdScheduleManager","preciseIdentifier":"c:objc(cs)GFPVideoAdScheduleManager","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didPauseAdWith","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"info"},{"kind":"text","text":": "},{"text":"GFPVideoAdQoeInfo","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdQoeInfo","preciseIdentifier":"c:objc(cs)GFPVideoAdQoeInfo"},{"kind":"text","text":")"}]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"스케쥴 매니저"}]}],"name":"aScheduleAdManager"},{"content":[{"inlineContent":[{"type":"text","text":"QOE 정보"}],"type":"paragraph"}],"name":"info"}],"kind":"parameters"}],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpvideoadschedulemanagerqoedelegate\/schedulemanager(_:didpauseadwith:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpvideoadschedulemanagerqoedelegate\/schedulemanager(_:didpauseadwith:)"]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManagerQoeDelegate"]]},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManagerQoeDelegate\/scheduleManager(_:didPauseAdWith:)","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"kind":"symbol","metadata":{"modules":[{"name":"GFPSDK"}],"title":"scheduleManager(_:didPauseAdWith:)","roleHeading":"Instance Method","externalID":"c:objc(pl)GFPVideoAdScheduleManagerQoeDelegate(im)scheduleManager:didPauseAdWithQoeInfo:","role":"symbol","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"scheduleManager:didPauseAdWithQoeInfo:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"scheduleManager","kind":"identifier"},{"text":"(","kind":"text"},{"text":"GFPVideoAdScheduleManager","preciseIdentifier":"c:objc(cs)GFPVideoAdScheduleManager","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"didPauseAdWith","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)GFPVideoAdQoeInfo","text":"GFPVideoAdQoeInfo","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"abstract":[{"type":"text","text":"광고가 일시중지 된 경우 발생"}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdScheduleManagerQoeDelegate/scheduleManager(_:didPauseAdWith:)":{"type":"topic","url":"\/documentation\/gfpsdk\/gfpvideoadschedulemanagerqoedelegate\/schedulemanager(_:didpauseadwith:)","title":"scheduleManager(_:didPauseAdWith:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"scheduleManager"},{"text":"(","kind":"text"},{"text":"GFPVideoAdScheduleManager","preciseIdentifier":"c:objc(cs)GFPVideoAdScheduleManager","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"didPauseAdWith","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GFPVideoAdQoeInfo","preciseIdentifier":"c:objc(cs)GFPVideoAdQoeInfo"},{"text":")","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"scheduleManager:didPauseAdWithQoeInfo:","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"광고가 일시중지 된 경우 발생"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManagerQoeDelegate\/scheduleManager(_:didPauseAdWith:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdQoeInfo":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"GFPVideoAdQoeInfo"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdQoeInfo","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPVideoAdQoeInfo","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpvideoadqoeinfo","role":"symbol","kind":"symbol","title":"GFPVideoAdQoeInfo"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdScheduleManagerQoeDelegate":{"kind":"symbol","abstract":[],"url":"\/documentation\/gfpsdk\/gfpvideoadschedulemanagerqoedelegate","type":"topic","title":"GFPVideoAdScheduleManagerQoeDelegate","navigatorTitle":[{"kind":"identifier","text":"GFPVideoAdScheduleManagerQoeDelegate"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManagerQoeDelegate","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPVideoAdScheduleManagerQoeDelegate"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoAdScheduleManager":{"kind":"symbol","type":"topic","url":"\/documentation\/gfpsdk\/gfpvideoadschedulemanager","title":"GFPVideoAdScheduleManager","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager","navigatorTitle":[{"kind":"identifier","text":"GFPVideoAdScheduleManager"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPVideoAdScheduleManager"}],"abstract":[],"role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"scheduleManager:didPauseAdWithQoeInfo:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"scheduleManager:didPauseAdWithQoeInfo:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"scheduleManager:"},{"text":"(","kind":"text"},{"text":"GFPVideoAdScheduleManager","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdScheduleManager","preciseIdentifier":"c:objc(cs)GFPVideoAdScheduleManager"},{"kind":"text","text":" *) "},{"text":"aScheduleAdManager","kind":"internalParam"},{"kind":"text","text":" "},{"text":"didPauseAdWithQoeInfo:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoAdQoeInfo","text":"GFPVideoAdQoeInfo","preciseIdentifier":"c:objc(cs)GFPVideoAdQoeInfo","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"info"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":{"parameters":[{"name":"aScheduleAdManager","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"스케쥴 매니저"}]}]},{"name":"info","content":[{"inlineContent":[{"text":"QOE 정보","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},"path":"\/primaryContentSections\/1"},{"value":"scheduleManager:didPauseAdWithQoeInfo:","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManagerQoeDelegate~1scheduleManager(_:didPauseAdWith:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"scheduleManager:didPauseAdWithQoeInfo:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManagerQoeDelegate~1scheduleManager(_:didPauseAdWith:)\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdQoeInfo\/title","value":"GFPVideoAdQoeInfo","op":"replace"},{"op":"replace","value":[{"text":"GFPVideoAdQoeInfo","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdQoeInfo\/fragments"},{"op":"replace","value":[{"text":"GFPVideoAdQoeInfo","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdQoeInfo\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManagerQoeDelegate\/title","value":"GFPVideoAdScheduleManagerQoeDelegate"},{"op":"replace","value":[{"text":"GFPVideoAdScheduleManagerQoeDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManagerQoeDelegate\/fragments"},{"value":[{"text":"GFPVideoAdScheduleManagerQoeDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManagerQoeDelegate\/navigatorTitle"},{"op":"replace","value":"GFPVideoAdScheduleManager","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager\/title"},{"value":[{"text":"GFPVideoAdScheduleManager","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoAdScheduleManager\/navigatorTitle","op":"replace","value":[{"text":"GFPVideoAdScheduleManager","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}