{"abstract":[{"text":"네이티브 광고 미디어뷰 여백의 블러처리 여부를 설정합니다.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"(기본값은 NO)"}],"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdRenderingSetting\/enableMediaBackgroundBlur","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"enableMediaBackgroundBlur","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}]}]}],"metadata":{"title":"enableMediaBackgroundBlur","role":"symbol","externalID":"c:objc(cs)GFPNativeAdRenderingSetting(py)enableMediaBackgroundBlur","modules":[{"name":"GFPSDK"}],"navigatorTitle":[{"kind":"identifier","text":"enableMediaBackgroundBlur"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableMediaBackgroundBlur"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"roleHeading":"Instance Property","symbolKind":"property"},"kind":"symbol","variants":[{"paths":["\/documentation\/gfpsdk\/gfpnativeadrenderingsetting\/enablemediabackgroundblur"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gfpsdk\/gfpnativeadrenderingsetting\/enablemediabackgroundblur"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdRenderingSetting"]]},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdRenderingSetting/enableMediaBackgroundBlur":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"enableMediaBackgroundBlur","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"kind":"symbol","navigatorTitle":[{"text":"enableMediaBackgroundBlur","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdRenderingSetting\/enableMediaBackgroundBlur","abstract":[{"type":"text","text":"네이티브 광고 미디어뷰 여백의 블러처리 여부를 설정합니다."},{"type":"text","text":" "},{"type":"text","text":"(기본값은 NO)"}],"role":"symbol","url":"\/documentation\/gfpsdk\/gfpnativeadrenderingsetting\/enablemediabackgroundblur","title":"enableMediaBackgroundBlur","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdRenderingSetting":{"abstract":[],"kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdRenderingSetting","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPNativeAdRenderingSetting"}],"url":"\/documentation\/gfpsdk\/gfpnativeadrenderingsetting","title":"GFPNativeAdRenderingSetting","navigatorTitle":[{"kind":"identifier","text":"GFPNativeAdRenderingSetting"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","value":"enableMediaBackgroundBlur","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"enableMediaBackgroundBlur","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"text":" ","kind":"text"},{"kind":"identifier","text":"enableMediaBackgroundBlur"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"value":"enableMediaBackgroundBlur","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdRenderingSetting~1enableMediaBackgroundBlur\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdRenderingSetting~1enableMediaBackgroundBlur\/fragments","value":[{"text":"enableMediaBackgroundBlur","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdRenderingSetting\/title","value":"GFPNativeAdRenderingSetting"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdRenderingSetting\/fragments","value":[{"kind":"identifier","text":"GFPNativeAdRenderingSetting"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdRenderingSetting\/navigatorTitle","op":"replace","value":[{"text":"GFPNativeAdRenderingSetting","kind":"identifier"}]}]}]}