{"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdBase"]]},"metadata":{"role":"symbol","roleHeading":"Instance Property","title":"adProviderNativeAd","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"adProviderNativeAd"},{"kind":"text","text":": "},{"text":"Any","kind":"keyword"}],"externalID":"c:objc(cs)GFPNativeAdBase(py)adProviderNativeAd","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"adProviderNativeAd"}],"modules":[{"name":"GFPSDK"}]},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"adProviderNativeAd"},{"kind":"text","text":": "},{"text":"Any","kind":"keyword"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"content":[{"level":2,"text":"Discussion","anchor":"discussion","type":"heading"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"adProvider 가 GFPNativeAdProviderTypeFAN 인 경우,"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"GFPNativeAdRenderingSetting.hasMediaView == YES 이면, “FBNativeAd” 객체"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"GFPNativeAdRenderingSetting.hasMediaView == NO 이면, “FBNativeBannerAd” 객체"}],"type":"paragraph"}]}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"adProvider 가 GFPNativeAdProviderTypeDFP 인 경우, “NativeAd” 객체"}]}]},{"content":[{"inlineContent":[{"text":"adProvider 가 GFPNativeAdProviderTypeInMobi 인 경우, “IMNative” 객체","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"adProvider 가 GFPNativeAdProviderTypeLAN 인 경우, “FADAdViewCustomLayout” 객체 혹은 “FADNative” 객체"}],"type":"paragraph"}]}],"type":"unorderedList"}],"kind":"content"}],"abstract":[{"type":"text","text":"광고 제공자의 네이티브 광고 객체"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdBase\/adProviderNativeAd"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpnativeadbase\/adprovidernativead"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpnativeadbase\/adprovidernativead"]}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdBase/adProviderNativeAd":{"role":"symbol","abstract":[{"type":"text","text":"광고 제공자의 네이티브 광고 객체"}],"title":"adProviderNativeAd","navigatorTitle":[{"text":"adProviderNativeAd","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"adProviderNativeAd","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdBase\/adProviderNativeAd","url":"\/documentation\/gfpsdk\/gfpnativeadbase\/adprovidernativead","kind":"symbol","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdBase":{"kind":"symbol","role":"symbol","title":"GFPNativeAdBase","navigatorTitle":[{"kind":"identifier","text":"GFPNativeAdBase"}],"type":"topic","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPNativeAdBase","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpnativeadbase","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdBase"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"adProviderNativeAd"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"text":"adProviderNativeAd","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"kind":"text","text":" "},{"text":"adProviderNativeAd","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdBase~1adProviderNativeAd\/title","value":"adProviderNativeAd"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdBase~1adProviderNativeAd\/fragments","value":[{"kind":"identifier","text":"adProviderNativeAd"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdBase\/title","value":"GFPNativeAdBase","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdBase\/fragments","value":[{"text":"GFPNativeAdBase","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdBase\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"GFPNativeAdBase"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}