{"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpnativeadbase\/adstyleoption"]},{"paths":["\/documentation\/gfpsdk\/gfpnativeadbase\/adstyleoption"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"modules":[{"name":"GFPSDK"}],"externalID":"c:objc(cs)GFPNativeAdBase(py)adStyleOption","roleHeading":"Instance Property","title":"adStyleOption","role":"symbol","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"adStyleOption"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPAdStyleOption","text":"GFPAdStyleOption","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"adStyleOption"}]},"kind":"symbol","abstract":[{"text":"광고 배경 정보","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdBase"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"adStyleOption","kind":"identifier"},{"text":": ","kind":"text"},{"text":"GFPAdStyleOption","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdStyleOption","kind":"typeIdentifier","preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPAdStyleOption"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdBase\/adStyleOption"},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdStyleOption":{"abstract":[],"role":"symbol","url":"\/documentation\/gfpsdk\/gfpadstyleoption","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPAdStyleOption","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"GFPAdStyleOption"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdStyleOption","title":"GFPAdStyleOption","kind":"symbol","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdBase":{"kind":"symbol","role":"symbol","title":"GFPNativeAdBase","navigatorTitle":[{"kind":"identifier","text":"GFPNativeAdBase"}],"type":"topic","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPNativeAdBase","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpnativeadbase","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdBase"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdBase/adStyleOption":{"role":"symbol","abstract":[{"text":"광고 배경 정보","type":"text"}],"title":"adStyleOption","navigatorTitle":[{"kind":"identifier","text":"adStyleOption"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"adStyleOption","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPAdStyleOption","text":"GFPAdStyleOption","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdBase\/adStyleOption","type":"topic","kind":"symbol","url":"\/documentation\/gfpsdk\/gfpnativeadbase\/adstyleoption"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"adStyleOption","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"adStyleOption"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"GFPAdStyleOption","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdStyleOption","kind":"typeIdentifier","preciseIdentifier":"c:@M@GFPSDK@objc(cs)GFPAdStyleOption"},{"text":" * ","kind":"text"},{"text":"adStyleOption","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdStyleOption\/title","value":"GFPAdStyleOption"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdStyleOption\/fragments","value":[{"text":"GFPAdStyleOption","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdStyleOption\/navigatorTitle","value":[{"text":"GFPAdStyleOption","kind":"identifier"}],"op":"replace"},{"value":"GFPNativeAdBase","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdBase\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdBase\/fragments","value":[{"text":"GFPNativeAdBase","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdBase\/navigatorTitle","op":"replace","value":[{"text":"GFPNativeAdBase","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdBase~1adStyleOption\/title","value":"adStyleOption"},{"value":[{"text":"adStyleOption","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdBase~1adStyleOption\/fragments"}]}]}