{"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdBase"]]},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"symbolKind":"property","externalID":"c:objc(cs)GFPNativeAdBase(py)responseInfo","modules":[{"name":"GFPSDK"}],"navigatorTitle":[{"kind":"identifier","text":"responseInfo"}],"title":"responseInfo","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"responseInfo","kind":"identifier"},{"kind":"text","text":": "},{"text":"GFPLoadResponseInfo","preciseIdentifier":"c:objc(cs)GFPLoadResponseInfo","kind":"typeIdentifier"}],"role":"symbol"},"abstract":[{"type":"text","text":"광고 응답 객체"}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"responseInfo","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"GFPLoadResponseInfo","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLoadResponseInfo","preciseIdentifier":"c:objc(cs)GFPLoadResponseInfo"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpnativeadbase\/responseinfo"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpnativeadbase\/responseinfo"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdBase\/responseInfo"},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdBase":{"kind":"symbol","role":"symbol","title":"GFPNativeAdBase","navigatorTitle":[{"kind":"identifier","text":"GFPNativeAdBase"}],"type":"topic","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPNativeAdBase","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpnativeadbase","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdBase"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdBase/responseInfo":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"responseInfo","kind":"identifier"},{"text":": ","kind":"text"},{"text":"GFPLoadResponseInfo","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPLoadResponseInfo"}],"url":"\/documentation\/gfpsdk\/gfpnativeadbase\/responseinfo","kind":"symbol","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdBase\/responseInfo","abstract":[{"type":"text","text":"광고 응답 객체"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"responseInfo"}],"title":"responseInfo"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPLoadResponseInfo":{"title":"GFPLoadResponseInfo","url":"\/documentation\/gfpsdk\/gfploadresponseinfo","role":"symbol","navigatorTitle":[{"text":"GFPLoadResponseInfo","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"GFPLoadResponseInfo","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLoadResponseInfo"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"responseInfo"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"responseInfo","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPLoadResponseInfo","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPLoadResponseInfo","text":"GFPLoadResponseInfo","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"responseInfo","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdBase\/title","op":"replace","value":"GFPNativeAdBase"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdBase\/fragments","value":[{"text":"GFPNativeAdBase","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdBase\/navigatorTitle","value":[{"kind":"identifier","text":"GFPNativeAdBase"}]},{"value":"responseInfo","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdBase~1responseInfo\/title"},{"op":"replace","value":[{"kind":"identifier","text":"responseInfo"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdBase~1responseInfo\/fragments"},{"value":"GFPLoadResponseInfo","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLoadResponseInfo\/title"},{"op":"replace","value":[{"text":"GFPLoadResponseInfo","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLoadResponseInfo\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPLoadResponseInfo\/navigatorTitle","value":[{"kind":"identifier","text":"GFPLoadResponseInfo"}]}]}]}