{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"reportClick"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"aExtraInfo","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPEventExtraInfo","text":"GFPEventExtraInfo","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPEventExtraInfo"},{"text":"?)","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPEventReporter"]]},"metadata":{"roleHeading":"Instance Method","role":"symbol","navigatorTitle":[{"text":"reportClickWithExtraInfo:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"reportClick"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPEventExtraInfo","text":"GFPEventExtraInfo","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"modules":[{"name":"GFPSDK"}],"symbolKind":"method","externalID":"c:objc(cs)GFPEventReporter(im)reportClickWithExtraInfo:","title":"reportClick(with:)"},"kind":"symbol","variants":[{"paths":["\/documentation\/gfpsdk\/gfpeventreporter\/reportclick(with:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gfpsdk\/gfpeventreporter\/reportclick(with:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPEventReporter\/reportClick(with:)"},"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPEventReporter":{"url":"\/documentation\/gfpsdk\/gfpeventreporter","navigatorTitle":[{"text":"GFPEventReporter","kind":"identifier"}],"title":"GFPEventReporter","kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPEventReporter","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPEventReporter"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPEventReporter/reportClick(with:)":{"role":"symbol","title":"reportClick(with:)","url":"\/documentation\/gfpsdk\/gfpeventreporter\/reportclick(with:)","abstract":[],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"reportClick"},{"kind":"text","text":"("},{"text":"with","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GFPEventExtraInfo","preciseIdentifier":"c:objc(cs)GFPEventExtraInfo"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"reportClickWithExtraInfo:"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPEventReporter\/reportClick(with:)","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPEventExtraInfo":{"navigatorTitle":[{"text":"GFPEventExtraInfo","kind":"identifier"}],"role":"symbol","title":"GFPEventExtraInfo","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPEventExtraInfo"}],"type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPEventExtraInfo","abstract":[],"url":"\/documentation\/gfpsdk\/gfpeventextrainfo"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"reportClickWithExtraInfo:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"reportClickWithExtraInfo:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"reportClickWithExtraInfo:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPEventExtraInfo","text":"GFPEventExtraInfo","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPEventExtraInfo"},{"text":" *) ","kind":"text"},{"text":"aExtraInfo","kind":"internalParam"},{"kind":"text","text":";"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPEventReporter\/title","op":"replace","value":"GFPEventReporter"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPEventReporter\/fragments","value":[{"text":"GFPEventReporter","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPEventReporter\/navigatorTitle","value":[{"kind":"identifier","text":"GFPEventReporter"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPEventReporter~1reportClick(with:)\/title","op":"replace","value":"reportClickWithExtraInfo:"},{"value":[{"text":"- ","kind":"text"},{"text":"reportClickWithExtraInfo:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPEventReporter~1reportClick(with:)\/fragments","op":"replace"},{"value":"GFPEventExtraInfo","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPEventExtraInfo\/title"},{"value":[{"kind":"identifier","text":"GFPEventExtraInfo"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPEventExtraInfo\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPEventExtraInfo\/navigatorTitle","value":[{"text":"GFPEventExtraInfo","kind":"identifier"}],"op":"replace"}]}]}