{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpeventreporter\/reportrenderedimpressions(with:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpeventreporter\/reportrenderedimpressions(with:)"]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPEventReporter"]]},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPEventReporter\/reportRenderedImpressions(with:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"kind":"symbol","metadata":{"roleHeading":"Instance Method","role":"symbol","navigatorTitle":[{"text":"reportRenderedImpressionsWithExtraInfo:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"reportRenderedImpressions","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPEventExtraInfo","text":"GFPEventExtraInfo"},{"kind":"text","text":"?)"}],"modules":[{"name":"GFPSDK"}],"symbolKind":"method","externalID":"c:objc(cs)GFPEventReporter(im)reportRenderedImpressionsWithExtraInfo:","title":"reportRenderedImpressions(with:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"reportRenderedImpressions"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":" "},{"text":"aExtraInfo","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPEventExtraInfo","text":"GFPEventExtraInfo","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPEventExtraInfo"},{"text":"?)","kind":"text"}]}]}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPEventExtraInfo":{"navigatorTitle":[{"text":"GFPEventExtraInfo","kind":"identifier"}],"role":"symbol","title":"GFPEventExtraInfo","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPEventExtraInfo"}],"type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPEventExtraInfo","abstract":[],"url":"\/documentation\/gfpsdk\/gfpeventextrainfo"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPEventReporter":{"url":"\/documentation\/gfpsdk\/gfpeventreporter","navigatorTitle":[{"text":"GFPEventReporter","kind":"identifier"}],"title":"GFPEventReporter","kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPEventReporter","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPEventReporter"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPEventReporter/reportRenderedImpressions(with:)":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"reportRenderedImpressionsWithExtraInfo:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"reportRenderedImpressions","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)GFPEventExtraInfo","kind":"typeIdentifier","text":"GFPEventExtraInfo"},{"kind":"text","text":"?)"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPEventReporter\/reportRenderedImpressions(with:)","type":"topic","abstract":[],"url":"\/documentation\/gfpsdk\/gfpeventreporter\/reportrenderedimpressions(with:)","kind":"symbol","title":"reportRenderedImpressions(with:)"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"reportRenderedImpressionsWithExtraInfo:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"reportRenderedImpressionsWithExtraInfo:"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"reportRenderedImpressionsWithExtraInfo:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)GFPEventExtraInfo","text":"GFPEventExtraInfo","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPEventExtraInfo"},{"text":" *) ","kind":"text"},{"text":"aExtraInfo","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPEventExtraInfo\/title","value":"GFPEventExtraInfo","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPEventExtraInfo\/fragments","op":"replace","value":[{"kind":"identifier","text":"GFPEventExtraInfo"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPEventExtraInfo\/navigatorTitle","value":[{"kind":"identifier","text":"GFPEventExtraInfo"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPEventReporter\/title","value":"GFPEventReporter"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPEventReporter\/fragments","value":[{"kind":"identifier","text":"GFPEventReporter"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPEventReporter\/navigatorTitle","op":"replace","value":[{"text":"GFPEventReporter","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPEventReporter~1reportRenderedImpressions(with:)\/title","value":"reportRenderedImpressionsWithExtraInfo:"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPEventReporter~1reportRenderedImpressions(with:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"reportRenderedImpressionsWithExtraInfo:","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}