{"metadata":{"symbolKind":"method","title":"reportCustomEvents(with:)","role":"symbol","modules":[{"name":"GFPSDK"}],"navigatorTitle":[{"text":"reportCustomEventsWith:","kind":"identifier"}],"externalID":"c:objc(cs)GFPEventReporter(im)reportCustomEventsWith:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"reportCustomEvents"},{"kind":"text","text":"("},{"text":"with","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"GFPAdEventObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdEventObject"},{"text":"])","kind":"text"}],"roleHeading":"Instance Method"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"reportCustomEvents"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"with"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"eventObjects"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"GFPAdEventObject","preciseIdentifier":"c:objc(cs)GFPAdEventObject","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdEventObject"},{"kind":"text","text":"])"}],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/gfpsdk\/gfpeventreporter\/reportcustomevents(with:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gfpsdk\/gfpeventreporter\/reportcustomevents(with:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPEventReporter"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPEventReporter\/reportCustomEvents(with:)"},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPEventReporter/reportCustomEvents(with:)":{"navigatorTitle":[{"text":"reportCustomEventsWith:","kind":"identifier"}],"type":"topic","title":"reportCustomEvents(with:)","kind":"symbol","url":"\/documentation\/gfpsdk\/gfpeventreporter\/reportcustomevents(with:)","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPEventReporter\/reportCustomEvents(with:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"reportCustomEvents"},{"kind":"text","text":"("},{"text":"with","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"GFPAdEventObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdEventObject"},{"text":"])","kind":"text"}],"role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPEventReporter":{"url":"\/documentation\/gfpsdk\/gfpeventreporter","navigatorTitle":[{"text":"GFPEventReporter","kind":"identifier"}],"title":"GFPEventReporter","kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPEventReporter","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPEventReporter"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdEventObject":{"type":"topic","navigatorTitle":[{"text":"GFPAdEventObject","kind":"identifier"}],"abstract":[{"type":"text","text":"GFPAdEventObject"}],"role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdEventObject","title":"GFPAdEventObject","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPAdEventObject"}],"url":"\/documentation\/gfpsdk\/gfpadeventobject","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"reportCustomEventsWith:"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"reportCustomEventsWith:","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"reportCustomEventsWith:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<GFPAdEventObject *>"},{"kind":"text","text":" *) "},{"text":"eventObjects","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"reportCustomEventsWith:","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPEventReporter~1reportCustomEvents(with:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"reportCustomEventsWith:"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPEventReporter~1reportCustomEvents(with:)\/fragments"},{"value":"GFPEventReporter","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPEventReporter\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPEventReporter\/fragments","value":[{"kind":"identifier","text":"GFPEventReporter"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPEventReporter\/navigatorTitle","value":[{"text":"GFPEventReporter","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdEventObject\/title","op":"replace","value":"GFPAdEventObject"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdEventObject\/fragments","value":[{"text":"GFPAdEventObject","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdEventObject\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"GFPAdEventObject"}]}]}]}