{"sections":[],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpeventreporter\/reportattachimpressions(with:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpeventreporter\/reportattachimpressions(with:)"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPEventReporter"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"reportAttachImpressions","kind":"identifier"},{"kind":"text","text":"("},{"text":"with","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"aExtraInfo","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"GFPEventExtraInfo","preciseIdentifier":"c:objc(cs)GFPEventExtraInfo","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPEventExtraInfo"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]}],"metadata":{"modules":[{"name":"GFPSDK"}],"navigatorTitle":[{"kind":"identifier","text":"reportAttachImpressionsWithExtraInfo:"}],"role":"symbol","title":"reportAttachImpressions(with:)","symbolKind":"method","externalID":"c:objc(cs)GFPEventReporter(im)reportAttachImpressionsWithExtraInfo:","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"reportAttachImpressions","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPEventExtraInfo","text":"GFPEventExtraInfo"},{"kind":"text","text":"?)"}],"roleHeading":"Instance Method"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPEventReporter\/reportAttachImpressions(with:)"},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPEventExtraInfo":{"navigatorTitle":[{"text":"GFPEventExtraInfo","kind":"identifier"}],"role":"symbol","title":"GFPEventExtraInfo","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPEventExtraInfo"}],"type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPEventExtraInfo","abstract":[],"url":"\/documentation\/gfpsdk\/gfpeventextrainfo"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPEventReporter":{"url":"\/documentation\/gfpsdk\/gfpeventreporter","navigatorTitle":[{"text":"GFPEventReporter","kind":"identifier"}],"title":"GFPEventReporter","kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPEventReporter","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPEventReporter"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPEventReporter/reportAttachImpressions(with:)":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"reportAttachImpressionsWithExtraInfo:"}],"kind":"symbol","url":"\/documentation\/gfpsdk\/gfpeventreporter\/reportattachimpressions(with:)","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"reportAttachImpressions"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GFPEventExtraInfo","preciseIdentifier":"c:objc(cs)GFPEventExtraInfo"},{"kind":"text","text":"?)"}],"title":"reportAttachImpressions(with:)","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPEventReporter\/reportAttachImpressions(with:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"reportAttachImpressionsWithExtraInfo:"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"reportAttachImpressionsWithExtraInfo:","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"reportAttachImpressionsWithExtraInfo:"},{"text":"(","kind":"text"},{"text":"GFPEventExtraInfo","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPEventExtraInfo","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPEventExtraInfo"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"aExtraInfo"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"GFPEventExtraInfo","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPEventExtraInfo\/title","op":"replace"},{"value":[{"kind":"identifier","text":"GFPEventExtraInfo"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPEventExtraInfo\/fragments","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"GFPEventExtraInfo"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPEventExtraInfo\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPEventReporter\/title","op":"replace","value":"GFPEventReporter"},{"value":[{"text":"GFPEventReporter","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPEventReporter\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPEventReporter\/navigatorTitle","value":[{"text":"GFPEventReporter","kind":"identifier"}]},{"value":"reportAttachImpressionsWithExtraInfo:","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPEventReporter~1reportAttachImpressions(with:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPEventReporter~1reportAttachImpressions(with:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"reportAttachImpressionsWithExtraInfo:","kind":"identifier"}],"op":"replace"}]}]}