{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpnativesimpleaddelegate\/nativesimplead(_:didfailwitherror:)"]},{"paths":["\/documentation\/gfpsdk\/gfpnativesimpleaddelegate\/nativesimplead(_:didfailwitherror:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"role":"symbol","roleHeading":"Instance Method","title":"nativeSimpleAd(_:didFailWithError:)","symbolKind":"method","modules":[{"name":"GFPSDK"}],"externalID":"c:objc(pl)GFPNativeSimpleAdDelegate(im)nativeSimpleAd:didFailWithError:","navigatorTitle":[{"text":"nativeSimpleAd:didFailWithError:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"nativeSimpleAd"},{"text":"(","kind":"text"},{"text":"GFPNativeSimpleAd","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPNativeSimpleAd"},{"kind":"text","text":", "},{"text":"didFailWithError","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GFPError","preciseIdentifier":"c:@M@NaverAdsServices@objc(cs)GFPError"},{"kind":"text","text":")"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdDelegate\/nativeSimpleAd(_:didFailWithError:)"},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"에러 발생 시 호출됩니다."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"optional","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"nativeSimpleAd"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"nativeSimpleAd","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPNativeSimpleAd","text":"GFPNativeSimpleAd","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAd"},{"kind":"text","text":", "},{"text":"didFailWithError","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"GFPError","preciseIdentifier":"c:@M@NaverAdsServices@objc(cs)GFPError"},{"text":")","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"name":"nativeSimpleAd","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"네이티브 광고 객체"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"에러객체"}]}],"name":"error"}],"kind":"parameters"}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdDelegate"]]},"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeSimpleAdDelegate/nativeSimpleAd(_:didFailWithError:)":{"title":"nativeSimpleAd(_:didFailWithError:)","abstract":[{"text":"에러 발생 시 호출됩니다.","type":"text"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdDelegate\/nativeSimpleAd(_:didFailWithError:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"nativeSimpleAd","kind":"identifier"},{"kind":"text","text":"("},{"text":"GFPNativeSimpleAd","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPNativeSimpleAd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFailWithError"},{"text":": ","kind":"text"},{"text":"GFPError","preciseIdentifier":"c:@M@NaverAdsServices@objc(cs)GFPError","kind":"typeIdentifier"},{"kind":"text","text":")"}],"role":"symbol","type":"topic","url":"\/documentation\/gfpsdk\/gfpnativesimpleaddelegate\/nativesimplead(_:didfailwitherror:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"nativeSimpleAd:didFailWithError:"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeSimpleAdDelegate":{"kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdDelegate","role":"symbol","navigatorTitle":[{"text":"GFPNativeSimpleAdDelegate","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpnativesimpleaddelegate","title":"GFPNativeSimpleAdDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPNativeSimpleAdDelegate"}],"type":"topic","abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeSimpleAd":{"type":"topic","navigatorTitle":[{"text":"GFPNativeSimpleAd","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPNativeSimpleAd"}],"title":"GFPNativeSimpleAd","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAd","url":"\/documentation\/gfpsdk\/gfpnativesimplead","abstract":[],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"nativeSimpleAd:didFailWithError:","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"nativeSimpleAd:didFailWithError:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"nativeSimpleAd:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPNativeSimpleAd","text":"GFPNativeSimpleAd","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAd"},{"kind":"text","text":" *) "},{"text":"nativeSimpleAd","kind":"internalParam"},{"kind":"text","text":" "},{"text":"didFailWithError:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@NaverAdsServices@objc(cs)GFPError","text":"GFPError","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"nativeSimpleAd","content":[{"inlineContent":[{"type":"text","text":"네이티브 광고 객체"}],"type":"paragraph"}]},{"name":"error","content":[{"inlineContent":[{"type":"text","text":"에러객체"}],"type":"paragraph"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdDelegate~1nativeSimpleAd(_:didFailWithError:)\/title","op":"replace","value":"nativeSimpleAd:didFailWithError:"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdDelegate~1nativeSimpleAd(_:didFailWithError:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"nativeSimpleAd:didFailWithError:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdDelegate\/title","op":"replace","value":"GFPNativeSimpleAdDelegate"},{"op":"replace","value":[{"text":"GFPNativeSimpleAdDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdDelegate\/fragments"},{"value":[{"kind":"identifier","text":"GFPNativeSimpleAdDelegate"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdDelegate\/navigatorTitle","op":"replace"},{"op":"replace","value":"GFPNativeSimpleAd","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAd\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAd\/fragments","value":[{"text":"GFPNativeSimpleAd","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"text":"GFPNativeSimpleAd","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAd\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}