{"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdDelegate"]]},"variants":[{"paths":["\/documentation\/gfpsdk\/gfpnativesimpleaddelegate\/nativesimpleaddiddismissdefault(inappbrowser:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpnativesimpleaddelegate\/nativesimpleaddiddismissdefault(inappbrowser:)"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"title":"nativeSimpleAdDidDismissDefault(inAppBrowser:)","externalID":"c:objc(pl)GFPNativeSimpleAdDelegate(im)nativeSimpleAdDidDismissDefaultInAppBrowser:","symbolKind":"method","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"nativeSimpleAdDidDismissDefault"},{"text":"(","kind":"text"},{"text":"inAppBrowser","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPNativeSimpleAd","kind":"typeIdentifier","text":"GFPNativeSimpleAd"},{"text":")","kind":"text"}],"modules":[{"name":"GFPSDK"}],"navigatorTitle":[{"kind":"identifier","text":"nativeSimpleAdDidDismissDefaultInAppBrowser:"}],"roleHeading":"Instance Method"},"abstract":[{"text":"Default In App Browser 사용 시, 클릭이 이루어져서 SFSafariViewController가 정상적으로 Dismiss 시 호출됩니다.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"nativeSimpleAdDidDismissDefault"},{"kind":"text","text":"("},{"kind":"externalParam","text":"inAppBrowser"},{"kind":"text","text":" "},{"kind":"internalParam","text":"nativeSimpleAd"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GFPNativeSimpleAd","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAd","preciseIdentifier":"c:objc(cs)GFPNativeSimpleAd"},{"kind":"text","text":")"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"nativeSimpleAd","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"네이티브 광고 객체"}]}]}]}],"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdDelegate\/nativeSimpleAdDidDismissDefault(inAppBrowser:)","interfaceLanguage":"swift"},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeSimpleAdDelegate/nativeSimpleAdDidDismissDefault(inAppBrowser:)":{"navigatorTitle":[{"kind":"identifier","text":"nativeSimpleAdDidDismissDefaultInAppBrowser:"}],"title":"nativeSimpleAdDidDismissDefault(inAppBrowser:)","abstract":[{"type":"text","text":"Default In App Browser 사용 시, 클릭이 이루어져서 SFSafariViewController가 정상적으로 Dismiss 시 호출됩니다."}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdDelegate\/nativeSimpleAdDidDismissDefault(inAppBrowser:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"nativeSimpleAdDidDismissDefault"},{"kind":"text","text":"("},{"text":"inAppBrowser","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"GFPNativeSimpleAd","preciseIdentifier":"c:objc(cs)GFPNativeSimpleAd"},{"text":")","kind":"text"}],"url":"\/documentation\/gfpsdk\/gfpnativesimpleaddelegate\/nativesimpleaddiddismissdefault(inappbrowser:)","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeSimpleAd":{"type":"topic","navigatorTitle":[{"text":"GFPNativeSimpleAd","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPNativeSimpleAd"}],"title":"GFPNativeSimpleAd","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAd","url":"\/documentation\/gfpsdk\/gfpnativesimplead","abstract":[],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeSimpleAdDelegate":{"kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdDelegate","role":"symbol","navigatorTitle":[{"text":"GFPNativeSimpleAdDelegate","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpnativesimpleaddelegate","title":"GFPNativeSimpleAdDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPNativeSimpleAdDelegate"}],"type":"topic","abstract":[]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"nativeSimpleAdDidDismissDefaultInAppBrowser:","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"nativeSimpleAdDidDismissDefaultInAppBrowser:"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"nativeSimpleAdDidDismissDefaultInAppBrowser:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"GFPNativeSimpleAd","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAd","preciseIdentifier":"c:objc(cs)GFPNativeSimpleAd"},{"text":" *) ","kind":"text"},{"text":"nativeSimpleAd","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"op":"replace"},{"value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"네이티브 광고 객체"}]}],"name":"nativeSimpleAd"}],"kind":"parameters"},"path":"\/primaryContentSections\/1","op":"replace"},{"op":"replace","value":"nativeSimpleAdDidDismissDefaultInAppBrowser:","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdDelegate~1nativeSimpleAdDidDismissDefault(inAppBrowser:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"nativeSimpleAdDidDismissDefaultInAppBrowser:"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdDelegate~1nativeSimpleAdDidDismissDefault(inAppBrowser:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAd\/title","value":"GFPNativeSimpleAd"},{"op":"replace","value":[{"kind":"identifier","text":"GFPNativeSimpleAd"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAd\/fragments"},{"op":"replace","value":[{"text":"GFPNativeSimpleAd","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAd\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdDelegate\/title","value":"GFPNativeSimpleAdDelegate","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdDelegate\/fragments","value":[{"kind":"identifier","text":"GFPNativeSimpleAdDelegate"}]},{"op":"replace","value":[{"kind":"identifier","text":"GFPNativeSimpleAdDelegate"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdDelegate\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}