{"metadata":{"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nativeSimpleRichAdShrinkComplete","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPNativeSimpleAd","text":"GFPNativeSimpleAd"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"nativeSimpleRichAdShrinkComplete:","kind":"identifier"}],"modules":[{"name":"GFPSDK"}],"externalID":"c:objc(pl)GFPNativeSimpleAdDelegate(im)nativeSimpleRichAdShrinkComplete:","symbolKind":"method","role":"symbol","title":"nativeSimpleRichAdShrinkComplete(_:)","required":true},"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"paths":["\/documentation\/gfpsdk\/gfpnativesimpleaddelegate\/nativesimplerichadshrinkcomplete(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpnativesimpleaddelegate\/nativesimplerichadshrinkcomplete(_:)"]}],"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdDelegate\/nativeSimpleRichAdShrinkComplete(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Rich  Extend 광고에서 미디어뷰 사이즈 축소 완료 시 호출됩니다."}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"nativeSimpleRichAdShrinkComplete"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"nativeSimpleAd"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAd","kind":"typeIdentifier","text":"GFPNativeSimpleAd","preciseIdentifier":"c:objc(cs)GFPNativeSimpleAd"},{"text":")","kind":"text"}],"languages":["swift"]}]},{"parameters":[{"name":"nativeSimpleAd","content":[{"type":"paragraph","inlineContent":[{"text":"네이티브 광고 객체","type":"text"}]}]}],"kind":"parameters"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdDelegate"]]},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeSimpleAd":{"type":"topic","navigatorTitle":[{"text":"GFPNativeSimpleAd","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPNativeSimpleAd"}],"title":"GFPNativeSimpleAd","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAd","url":"\/documentation\/gfpsdk\/gfpnativesimplead","abstract":[],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeSimpleAdDelegate":{"kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdDelegate","role":"symbol","navigatorTitle":[{"text":"GFPNativeSimpleAdDelegate","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpnativesimpleaddelegate","title":"GFPNativeSimpleAdDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPNativeSimpleAdDelegate"}],"type":"topic","abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeSimpleAdDelegate/nativeSimpleRichAdShrinkComplete(_:)":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"nativeSimpleRichAdShrinkComplete:"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"nativeSimpleRichAdShrinkComplete","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPNativeSimpleAd","text":"GFPNativeSimpleAd"},{"text":")","kind":"text"}],"title":"nativeSimpleRichAdShrinkComplete(_:)","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdDelegate\/nativeSimpleRichAdShrinkComplete(_:)","url":"\/documentation\/gfpsdk\/gfpnativesimpleaddelegate\/nativesimplerichadshrinkcomplete(_:)","abstract":[{"text":"Rich  Extend 광고에서 미디어뷰 사이즈 축소 완료 시 호출됩니다.","type":"text"}],"kind":"symbol","required":true}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"nativeSimpleRichAdShrinkComplete:","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"nativeSimpleRichAdShrinkComplete:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"nativeSimpleRichAdShrinkComplete:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAd","text":"GFPNativeSimpleAd","preciseIdentifier":"c:objc(cs)GFPNativeSimpleAd"},{"text":" *) ","kind":"text"},{"text":"nativeSimpleAd","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/primaryContentSections\/1","op":"replace","value":{"kind":"parameters","parameters":[{"name":"nativeSimpleAd","content":[{"inlineContent":[{"type":"text","text":"네이티브 광고 객체"}],"type":"paragraph"}]}]}},{"value":"GFPNativeSimpleAd","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAd\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAd\/fragments","op":"replace","value":[{"kind":"identifier","text":"GFPNativeSimpleAd"}]},{"value":[{"kind":"identifier","text":"GFPNativeSimpleAd"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAd\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdDelegate\/title","value":"GFPNativeSimpleAdDelegate","op":"replace"},{"value":[{"text":"GFPNativeSimpleAdDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdDelegate\/fragments"},{"value":[{"text":"GFPNativeSimpleAdDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdDelegate\/navigatorTitle"},{"value":"nativeSimpleRichAdShrinkComplete:","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdDelegate~1nativeSimpleRichAdShrinkComplete(_:)\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdDelegate~1nativeSimpleRichAdShrinkComplete(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"nativeSimpleRichAdShrinkComplete:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}