{"abstract":[{"text":"Rich  Extend 광고에서 미디어뷰 사이즈 확장 완료 시 호출됩니다.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"optional"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"nativeSimpleRichAdExtendComplete"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"nativeSimpleAd","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPNativeSimpleAd","text":"GFPNativeSimpleAd","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAd"},{"kind":"text","text":")"}],"platforms":["iOS"]}]},{"parameters":[{"content":[{"inlineContent":[{"text":"네이티브 광고 객체","type":"text"}],"type":"paragraph"}],"name":"nativeSimpleAd"}],"kind":"parameters"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpnativesimpleaddelegate\/nativesimplerichadextendcomplete(_:)"]},{"paths":["\/documentation\/gfpsdk\/gfpnativesimpleaddelegate\/nativesimplerichadextendcomplete(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdDelegate\/nativeSimpleRichAdExtendComplete(_:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdDelegate"]]},"metadata":{"navigatorTitle":[{"text":"nativeSimpleRichAdExtendComplete:","kind":"identifier"}],"title":"nativeSimpleRichAdExtendComplete(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"nativeSimpleRichAdExtendComplete"},{"kind":"text","text":"("},{"text":"GFPNativeSimpleAd","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPNativeSimpleAd"},{"text":")","kind":"text"}],"role":"symbol","externalID":"c:objc(pl)GFPNativeSimpleAdDelegate(im)nativeSimpleRichAdExtendComplete:","modules":[{"name":"GFPSDK"}],"required":true,"roleHeading":"Instance Method","symbolKind":"method"},"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeSimpleAd":{"type":"topic","navigatorTitle":[{"text":"GFPNativeSimpleAd","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPNativeSimpleAd"}],"title":"GFPNativeSimpleAd","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAd","url":"\/documentation\/gfpsdk\/gfpnativesimplead","abstract":[],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeSimpleAdDelegate/nativeSimpleRichAdExtendComplete(_:)":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdDelegate\/nativeSimpleRichAdExtendComplete(_:)","url":"\/documentation\/gfpsdk\/gfpnativesimpleaddelegate\/nativesimplerichadextendcomplete(_:)","title":"nativeSimpleRichAdExtendComplete(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"nativeSimpleRichAdExtendComplete","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)GFPNativeSimpleAd","kind":"typeIdentifier","text":"GFPNativeSimpleAd"},{"kind":"text","text":")"}],"role":"symbol","navigatorTitle":[{"text":"nativeSimpleRichAdExtendComplete:","kind":"identifier"}],"kind":"symbol","required":true,"abstract":[{"text":"Rich  Extend 광고에서 미디어뷰 사이즈 확장 완료 시 호출됩니다.","type":"text"}],"type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeSimpleAdDelegate":{"kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdDelegate","role":"symbol","navigatorTitle":[{"text":"GFPNativeSimpleAdDelegate","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpnativesimpleaddelegate","title":"GFPNativeSimpleAdDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPNativeSimpleAdDelegate"}],"type":"topic","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"nativeSimpleRichAdExtendComplete:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"nativeSimpleRichAdExtendComplete:"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"nativeSimpleRichAdExtendComplete:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPNativeSimpleAd","text":"GFPNativeSimpleAd","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAd"},{"text":" *) ","kind":"text"},{"text":"nativeSimpleAd","kind":"internalParam"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"nativeSimpleAd","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"네이티브 광고 객체"}]}]}]}},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAd\/title","value":"GFPNativeSimpleAd","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAd\/fragments","value":[{"kind":"identifier","text":"GFPNativeSimpleAd"}],"op":"replace"},{"value":[{"kind":"identifier","text":"GFPNativeSimpleAd"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAd\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdDelegate~1nativeSimpleRichAdExtendComplete(_:)\/title","op":"replace","value":"nativeSimpleRichAdExtendComplete:"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdDelegate~1nativeSimpleRichAdExtendComplete(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"nativeSimpleRichAdExtendComplete:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdDelegate\/title","value":"GFPNativeSimpleAdDelegate"},{"value":[{"text":"GFPNativeSimpleAdDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdDelegate\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdDelegate\/navigatorTitle","value":[{"text":"GFPNativeSimpleAdDelegate","kind":"identifier"}],"op":"replace"}]}]}