{"sections":[],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpnativesimpleaddelegate\/nativesimplead(_:didchangerichadsizewith:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpnativesimpleaddelegate\/nativesimplead(_:didchangerichadsizewith:)"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdDelegate"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"text":"Rich  Extend 광고에서 미디어뷰 사이즈 변경 시마다 호출됩니다.","type":"text"}],"metadata":{"title":"nativeSimpleAd(_:didChangeRichAdSizeWith:)","role":"symbol","roleHeading":"Instance Method","symbolKind":"method","externalID":"c:objc(pl)GFPNativeSimpleAdDelegate(im)nativeSimpleAd:didChangeRichAdSizeWith:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"nativeSimpleAd"},{"text":"(","kind":"text"},{"text":"GFPNativeSimpleAd","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPNativeSimpleAd"},{"kind":"text","text":", "},{"text":"didChangeRichAdSizeWith","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier","text":"CGSize"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"nativeSimpleAd:didChangeRichAdSizeWith:","kind":"identifier"}],"required":true,"modules":[{"name":"GFPSDK"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"optional","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"nativeSimpleAd","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"nativeSimpleAd","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"GFPNativeSimpleAd","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPNativeSimpleAd","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didChangeRichAdSizeWith"},{"kind":"text","text":" "},{"text":"size","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"CGSize","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"nativeSimpleAd","content":[{"type":"paragraph","inlineContent":[{"text":"네이티브 광고 객체","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"변경된 사이즈"}]}],"name":"size"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdDelegate\/nativeSimpleAd(_:didChangeRichAdSizeWith:)"},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeSimpleAdDelegate":{"kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdDelegate","role":"symbol","navigatorTitle":[{"text":"GFPNativeSimpleAdDelegate","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpnativesimpleaddelegate","title":"GFPNativeSimpleAdDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPNativeSimpleAdDelegate"}],"type":"topic","abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeSimpleAdDelegate/nativeSimpleAd(_:didChangeRichAdSizeWith:)":{"title":"nativeSimpleAd(_:didChangeRichAdSizeWith:)","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdDelegate\/nativeSimpleAd(_:didChangeRichAdSizeWith:)","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Rich  Extend 광고에서 미디어뷰 사이즈 변경 시마다 호출됩니다."}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"nativeSimpleAd"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"GFPNativeSimpleAd","preciseIdentifier":"c:objc(cs)GFPNativeSimpleAd"},{"kind":"text","text":", "},{"text":"didChangeRichAdSizeWith","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGSize","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"nativeSimpleAd:didChangeRichAdSizeWith:","kind":"identifier"}],"required":true,"type":"topic","url":"\/documentation\/gfpsdk\/gfpnativesimpleaddelegate\/nativesimplead(_:didchangerichadsizewith:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeSimpleAd":{"type":"topic","navigatorTitle":[{"text":"GFPNativeSimpleAd","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPNativeSimpleAd"}],"title":"GFPNativeSimpleAd","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAd","url":"\/documentation\/gfpsdk\/gfpnativesimplead","abstract":[],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","value":"nativeSimpleAd:didChangeRichAdSizeWith:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"nativeSimpleAd:didChangeRichAdSizeWith:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"nativeSimpleAd:"},{"text":"(","kind":"text"},{"text":"GFPNativeSimpleAd","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAd","preciseIdentifier":"c:objc(cs)GFPNativeSimpleAd"},{"text":" *) ","kind":"text"},{"text":"nativeSimpleAd","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"didChangeRichAdSizeWith:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@S@CGSize","text":"CGSize","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"size","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"nativeSimpleAd","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"네이티브 광고 객체"}]}]},{"name":"size","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"변경된 사이즈"}]}]}],"kind":"parameters"}},{"value":"GFPNativeSimpleAdDelegate","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdDelegate\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdDelegate\/fragments","op":"replace","value":[{"text":"GFPNativeSimpleAdDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdDelegate\/navigatorTitle","value":[{"text":"GFPNativeSimpleAdDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdDelegate~1nativeSimpleAd(_:didChangeRichAdSizeWith:)\/title","value":"nativeSimpleAd:didChangeRichAdSizeWith:"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdDelegate~1nativeSimpleAd(_:didChangeRichAdSizeWith:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"nativeSimpleAd:didChangeRichAdSizeWith:","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"GFPNativeSimpleAd","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAd\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAd\/fragments","value":[{"text":"GFPNativeSimpleAd","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAd\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"GFPNativeSimpleAd"}]}]}]}