{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdDelegate\/nativeSimpleAdDidPresentDefault(inAppBrowser:)"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/gfpsdk\/gfpnativesimpleaddelegate\/nativesimpleaddidpresentdefault(inappbrowser:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpnativesimpleaddelegate\/nativesimpleaddidpresentdefault(inappbrowser:)"]}],"kind":"symbol","metadata":{"modules":[{"name":"GFPSDK"}],"navigatorTitle":[{"text":"nativeSimpleAdDidPresentDefaultInAppBrowser:","kind":"identifier"}],"role":"symbol","title":"nativeSimpleAdDidPresentDefault(inAppBrowser:)","symbolKind":"method","externalID":"c:objc(pl)GFPNativeSimpleAdDelegate(im)nativeSimpleAdDidPresentDefaultInAppBrowser:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nativeSimpleAdDidPresentDefault","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"inAppBrowser"},{"text":": ","kind":"text"},{"text":"GFPNativeSimpleAd","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPNativeSimpleAd"},{"text":")","kind":"text"}],"roleHeading":"Instance Method"},"abstract":[{"type":"text","text":"Default In App Browser 사용 시, 클릭이 이루어져서 SFSafariViewController가 정상적으로 Present 시 호출됩니다."}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdDelegate"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"optional","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nativeSimpleAdDidPresentDefault","kind":"identifier"},{"text":"(","kind":"text"},{"text":"inAppBrowser","kind":"externalParam"},{"kind":"text","text":" "},{"text":"nativeSimpleAd","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"GFPNativeSimpleAd","preciseIdentifier":"c:objc(cs)GFPNativeSimpleAd","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAd"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"name":"nativeSimpleAd","content":[{"inlineContent":[{"type":"text","text":"네이티브 광고 객체"}],"type":"paragraph"}]}],"kind":"parameters"}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeSimpleAdDelegate":{"kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdDelegate","role":"symbol","navigatorTitle":[{"text":"GFPNativeSimpleAdDelegate","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpnativesimpleaddelegate","title":"GFPNativeSimpleAdDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPNativeSimpleAdDelegate"}],"type":"topic","abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeSimpleAdDelegate/nativeSimpleAdDidPresentDefault(inAppBrowser:)":{"navigatorTitle":[{"text":"nativeSimpleAdDidPresentDefaultInAppBrowser:","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"nativeSimpleAdDidPresentDefault(inAppBrowser:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"nativeSimpleAdDidPresentDefault","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"inAppBrowser"},{"text":": ","kind":"text"},{"text":"GFPNativeSimpleAd","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPNativeSimpleAd"},{"text":")","kind":"text"}],"type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdDelegate\/nativeSimpleAdDidPresentDefault(inAppBrowser:)","abstract":[{"type":"text","text":"Default In App Browser 사용 시, 클릭이 이루어져서 SFSafariViewController가 정상적으로 Present 시 호출됩니다."}],"url":"\/documentation\/gfpsdk\/gfpnativesimpleaddelegate\/nativesimpleaddidpresentdefault(inappbrowser:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeSimpleAd":{"type":"topic","navigatorTitle":[{"text":"GFPNativeSimpleAd","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPNativeSimpleAd"}],"title":"GFPNativeSimpleAd","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAd","url":"\/documentation\/gfpsdk\/gfpnativesimplead","abstract":[],"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"nativeSimpleAdDidPresentDefaultInAppBrowser:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"nativeSimpleAdDidPresentDefaultInAppBrowser:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"text":"nativeSimpleAdDidPresentDefaultInAppBrowser:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"GFPNativeSimpleAd","preciseIdentifier":"c:objc(cs)GFPNativeSimpleAd","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAd"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"nativeSimpleAd"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"네이티브 광고 객체"}]}],"name":"nativeSimpleAd"}],"kind":"parameters"},"op":"replace","path":"\/primaryContentSections\/1"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdDelegate\/title","value":"GFPNativeSimpleAdDelegate","op":"replace"},{"value":[{"text":"GFPNativeSimpleAdDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdDelegate\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdDelegate\/navigatorTitle","value":[{"text":"GFPNativeSimpleAdDelegate","kind":"identifier"}]},{"op":"replace","value":"nativeSimpleAdDidPresentDefaultInAppBrowser:","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdDelegate~1nativeSimpleAdDidPresentDefault(inAppBrowser:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdDelegate~1nativeSimpleAdDidPresentDefault(inAppBrowser:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"nativeSimpleAdDidPresentDefaultInAppBrowser:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAd\/title","op":"replace","value":"GFPNativeSimpleAd"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAd\/fragments","op":"replace","value":[{"kind":"identifier","text":"GFPNativeSimpleAd"}]},{"value":[{"kind":"identifier","text":"GFPNativeSimpleAd"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAd\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}