{"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"text":"광고 뮤트 시 호출됩니다.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdDelegate"]]},"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpnativesimpleaddelegate\/nativesimpleadwasmuted(_:)"]},{"paths":["\/documentation\/gfpsdk\/gfpnativesimpleaddelegate\/nativesimpleadwasmuted(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"nativeSimpleAdWasMuted(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nativeSimpleAdWasMuted","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GFPNativeSimpleAd","preciseIdentifier":"c:objc(cs)GFPNativeSimpleAd"},{"text":")","kind":"text"}],"roleHeading":"Instance Method","role":"symbol","externalID":"c:objc(pl)GFPNativeSimpleAdDelegate(im)nativeSimpleAdWasMuted:","symbolKind":"method","navigatorTitle":[{"text":"nativeSimpleAdWasMuted:","kind":"identifier"}],"modules":[{"name":"GFPSDK"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdDelegate\/nativeSimpleAdWasMuted(_:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"optional"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"nativeSimpleAdWasMuted","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"nativeSimpleAd"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAd","preciseIdentifier":"c:objc(cs)GFPNativeSimpleAd","text":"GFPNativeSimpleAd"},{"text":")","kind":"text"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"nativeSimpleAd","content":[{"inlineContent":[{"text":"네이티브 광고 객체","type":"text"}],"type":"paragraph"}]}]}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeSimpleAdDelegate":{"kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdDelegate","role":"symbol","navigatorTitle":[{"text":"GFPNativeSimpleAdDelegate","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpnativesimpleaddelegate","title":"GFPNativeSimpleAdDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPNativeSimpleAdDelegate"}],"type":"topic","abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeSimpleAdDelegate/nativeSimpleAdWasMuted(_:)":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdDelegate\/nativeSimpleAdWasMuted(_:)","url":"\/documentation\/gfpsdk\/gfpnativesimpleaddelegate\/nativesimpleadwasmuted(_:)","title":"nativeSimpleAdWasMuted(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"nativeSimpleAdWasMuted","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GFPNativeSimpleAd","preciseIdentifier":"c:objc(cs)GFPNativeSimpleAd"},{"kind":"text","text":")"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"nativeSimpleAdWasMuted:"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"광고 뮤트 시 호출됩니다."}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeSimpleAd":{"type":"topic","navigatorTitle":[{"text":"GFPNativeSimpleAd","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPNativeSimpleAd"}],"title":"GFPNativeSimpleAd","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAd","url":"\/documentation\/gfpsdk\/gfpnativesimplead","abstract":[],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"nativeSimpleAdWasMuted:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"nativeSimpleAdWasMuted:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"nativeSimpleAdWasMuted:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAd","preciseIdentifier":"c:objc(cs)GFPNativeSimpleAd","text":"GFPNativeSimpleAd"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"nativeSimpleAd"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"네이티브 광고 객체","type":"text"}]}],"name":"nativeSimpleAd"}],"kind":"parameters"},"path":"\/primaryContentSections\/1","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdDelegate\/title","op":"replace","value":"GFPNativeSimpleAdDelegate"},{"value":[{"kind":"identifier","text":"GFPNativeSimpleAdDelegate"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdDelegate\/fragments","op":"replace"},{"value":[{"text":"GFPNativeSimpleAdDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdDelegate\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdDelegate~1nativeSimpleAdWasMuted(_:)\/title","value":"nativeSimpleAdWasMuted:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdDelegate~1nativeSimpleAdWasMuted(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"nativeSimpleAdWasMuted:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAd\/title","op":"replace","value":"GFPNativeSimpleAd"},{"value":[{"kind":"identifier","text":"GFPNativeSimpleAd"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAd\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAd\/navigatorTitle","value":[{"text":"GFPNativeSimpleAd","kind":"identifier"}]}]}]}