{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"init"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}],"sections":[],"metadata":{"title":"init","modules":[{"name":"GFPSDK"}],"role":"symbol","externalID":"c:@M@GFPSDK@objc(cs)GFPSDKPhase(im)init","symbolKind":"method","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"init"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPSDKPhase\/init"},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPSDKPhase"]]},"variants":[{"paths":["\/documentation\/gfpsdk\/gfpsdkphase\/init"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPSDKPhase/init":{"fragments":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}],"title":"init","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPSDKPhase\/init","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/gfpsdk\/gfpsdkphase\/init","abstract":[],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPSDKPhase":{"title":"GFPSDKPhase","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPSDKPhase","role":"symbol","url":"\/documentation\/gfpsdk\/gfpsdkphase","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPSDKPhase"}],"navigatorTitle":[{"text":"GFPSDKPhase","kind":"identifier"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPSDKPhase\/title","value":"GFPSDKPhase"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPSDKPhase\/fragments","op":"replace","value":[{"text":"GFPSDKPhase","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPSDKPhase\/navigatorTitle","value":[{"text":"GFPSDKPhase","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}