{"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPSDKPhase"]]},"metadata":{"role":"symbol","title":"waterfallPhase(with:)","roleHeading":"Type Method","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"waterfallPhase","kind":"identifier"},{"kind":"text","text":"("},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"GFPPhaseType","preciseIdentifier":"c:@E@GFPPhaseType","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"externalID":"c:@M@GFPSDK@objc(cs)GFPSDKPhase(cm)waterfallPhaseWith:","symbolKind":"method","navigatorTitle":[{"text":"waterfallPhaseWith:","kind":"identifier"}],"modules":[{"name":"GFPSDK"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"waterfallPhase","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"text":" ","kind":"text"},{"text":"aType","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"GFPPhaseType","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPPhaseType","kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPPhaseType"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPSDKPhase\/waterfallPhase(with:)"},"sections":[],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpsdkphase\/waterfallphase(with:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gfpsdk\/gfpsdkphase\/waterfallphase(with:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPSDKPhase/waterfallPhase(with:)":{"role":"symbol","abstract":[],"url":"\/documentation\/gfpsdk\/gfpsdkphase\/waterfallphase(with:)","title":"waterfallPhase(with:)","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"waterfallPhase","kind":"identifier"},{"kind":"text","text":"("},{"text":"with","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@GFPPhaseType","text":"GFPPhaseType"},{"kind":"text","text":") -> "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"waterfallPhaseWith:","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPSDKPhase\/waterfallPhase(with:)","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPPhaseType":{"kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPPhaseType","url":"\/documentation\/gfpsdk\/gfpphasetype","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"GFPPhaseType","kind":"identifier"}],"title":"GFPPhaseType","role":"symbol","type":"topic","navigatorTitle":[{"text":"GFPPhaseType","kind":"identifier"}],"abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPSDKPhase":{"title":"GFPSDKPhase","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPSDKPhase","role":"symbol","url":"\/documentation\/gfpsdk\/gfpsdkphase","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPSDKPhase"}],"navigatorTitle":[{"text":"GFPSDKPhase","kind":"identifier"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"waterfallPhaseWith:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"waterfallPhaseWith:"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"waterfallPhaseWith:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@E@GFPPhaseType","text":"GFPPhaseType","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPPhaseType"},{"kind":"text","text":") "},{"text":"aType","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPSDKPhase~1waterfallPhase(with:)\/title","value":"waterfallPhaseWith:"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPSDKPhase~1waterfallPhase(with:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"waterfallPhaseWith:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPPhaseType\/title","value":"GFPPhaseType","op":"replace"},{"op":"replace","value":[{"text":"GFPPhaseType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPPhaseType\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPPhaseType\/navigatorTitle","value":[{"text":"GFPPhaseType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPSDKPhase\/title","value":"GFPSDKPhase","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPSDKPhase\/fragments","value":[{"text":"GFPSDKPhase","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPSDKPhase\/navigatorTitle","value":[{"text":"GFPSDKPhase","kind":"identifier"}]}]}]}