{"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"variants":[{"paths":["\/documentation\/gfpsdk\/gfperrorcode\/bannerproviderloadfailed"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfperrorcode\/bannerproviderloadfailed"]}],"metadata":{"navigatorTitle":[{"text":"GFPErrorBannerProviderLoadFailed","kind":"identifier"}],"externalID":"c:@E@GFPErrorCode@GFPErrorBannerProviderLoadFailed","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"bannerProviderLoadFailed","kind":"identifier"}],"modules":[{"name":"GFPSDK"}],"roleHeading":"Case","role":"symbol","title":"GFPErrorCode.bannerProviderLoadFailed"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"bannerProviderLoadFailed","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode"]]},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/bannerProviderLoadFailed","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPErrorCode/bannerProviderLoadFailed":{"navigatorTitle":[{"text":"GFPErrorBannerProviderLoadFailed","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfperrorcode\/bannerproviderloadfailed","abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bannerProviderLoadFailed","kind":"identifier"}],"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/bannerProviderLoadFailed","title":"GFPErrorCode.bannerProviderLoadFailed"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPErrorCode":{"abstract":[],"url":"\/documentation\/gfpsdk\/gfperrorcode","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode","role":"symbol","title":"GFPErrorCode","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPErrorCode","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"GFPErrorCode"}],"kind":"symbol","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"GFPErrorBannerProviderLoadFailed","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"value":[{"text":"GFPErrorBannerProviderLoadFailed","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"GFPErrorBannerProviderLoadFailed"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":"GFPErrorBannerProviderLoadFailed","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1bannerProviderLoadFailed\/title"},{"op":"replace","value":[{"kind":"identifier","text":"GFPErrorBannerProviderLoadFailed"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1bannerProviderLoadFailed\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode\/title","value":"GFPErrorCode","op":"replace"},{"value":[{"kind":"identifier","text":"GFPErrorCode"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"GFPErrorCode"}]}]}]}