{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/initNativeProvider"},"metadata":{"title":"GFPErrorCode.initNativeProvider","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"initNativeProvider","kind":"identifier"}],"roleHeading":"Case","role":"symbol","externalID":"c:@E@GFPErrorCode@GFPErrorInitNativeProvider","symbolKind":"case","navigatorTitle":[{"text":"GFPErrorInitNativeProvider","kind":"identifier"}],"modules":[{"name":"GFPSDK"}]},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode"]]},"sections":[],"variants":[{"paths":["\/documentation\/gfpsdk\/gfperrorcode\/initnativeprovider"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gfpsdk\/gfperrorcode\/initnativeprovider"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"initNativeProvider","kind":"identifier"}]}],"kind":"declarations"}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPErrorCode/initNativeProvider":{"url":"\/documentation\/gfpsdk\/gfperrorcode\/initnativeprovider","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/initNativeProvider","navigatorTitle":[{"text":"GFPErrorInitNativeProvider","kind":"identifier"}],"kind":"symbol","title":"GFPErrorCode.initNativeProvider","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"initNativeProvider","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPErrorCode":{"abstract":[],"url":"\/documentation\/gfpsdk\/gfperrorcode","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode","role":"symbol","title":"GFPErrorCode","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPErrorCode","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"GFPErrorCode"}],"kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"value":"GFPErrorInitNativeProvider","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"text":"GFPErrorInitNativeProvider","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"GFPErrorInitNativeProvider"}],"platforms":["iOS"]}]},"op":"replace"},{"value":"GFPErrorInitNativeProvider","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1initNativeProvider\/title"},{"op":"replace","value":[{"text":"GFPErrorInitNativeProvider","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1initNativeProvider\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode\/title","value":"GFPErrorCode","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode\/fragments","value":[{"kind":"identifier","text":"GFPErrorCode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode\/navigatorTitle","value":[{"text":"GFPErrorCode","kind":"identifier"}]}]}]}