{"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/nativeVideoLoadFailed","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"nativeVideoLoadFailed","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"kind":"symbol","sections":[],"metadata":{"symbolKind":"case","modules":[{"name":"GFPSDK"}],"roleHeading":"Case","title":"GFPErrorCode.nativeVideoLoadFailed","externalID":"c:@E@GFPErrorCode@GFPErrorNativeVideoLoadFailed","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"nativeVideoLoadFailed"}],"navigatorTitle":[{"kind":"identifier","text":"GFPErrorNativeVideoLoadFailed"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfperrorcode\/nativevideoloadfailed"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfperrorcode\/nativevideoloadfailed"]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode"]]},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPErrorCode/nativeVideoLoadFailed":{"kind":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/nativeVideoLoadFailed","url":"\/documentation\/gfpsdk\/gfperrorcode\/nativevideoloadfailed","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"nativeVideoLoadFailed"}],"title":"GFPErrorCode.nativeVideoLoadFailed","role":"symbol","type":"topic","navigatorTitle":[{"text":"GFPErrorNativeVideoLoadFailed","kind":"identifier"}],"abstract":[]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPErrorCode":{"abstract":[],"url":"\/documentation\/gfpsdk\/gfperrorcode","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode","role":"symbol","title":"GFPErrorCode","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPErrorCode","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"GFPErrorCode"}],"kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"GFPErrorNativeVideoLoadFailed"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"text":"GFPErrorNativeVideoLoadFailed","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"GFPErrorNativeVideoLoadFailed","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1nativeVideoLoadFailed\/title","value":"GFPErrorNativeVideoLoadFailed","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"GFPErrorNativeVideoLoadFailed"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1nativeVideoLoadFailed\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode\/title","value":"GFPErrorCode"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode\/fragments","op":"replace","value":[{"kind":"identifier","text":"GFPErrorCode"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode\/navigatorTitle","value":[{"text":"GFPErrorCode","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}