{"sections":[],"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/nativeImageLoadFailed","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"nativeImageLoadFailed","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","metadata":{"title":"GFPErrorCode.nativeImageLoadFailed","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nativeImageLoadFailed","kind":"identifier"}],"roleHeading":"Case","role":"symbol","externalID":"c:@E@GFPErrorCode@GFPErrorNativeImageLoadFailed","symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"GFPErrorNativeImageLoadFailed"}],"modules":[{"name":"GFPSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/gfpsdk\/gfperrorcode\/nativeimageloadfailed"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfperrorcode\/nativeimageloadfailed"]}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPErrorCode/nativeImageLoadFailed":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"nativeImageLoadFailed","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"GFPErrorNativeImageLoadFailed"}],"url":"\/documentation\/gfpsdk\/gfperrorcode\/nativeimageloadfailed","abstract":[],"kind":"symbol","role":"symbol","title":"GFPErrorCode.nativeImageLoadFailed","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/nativeImageLoadFailed","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPErrorCode":{"abstract":[],"url":"\/documentation\/gfpsdk\/gfperrorcode","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode","role":"symbol","title":"GFPErrorCode","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPErrorCode","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"GFPErrorCode"}],"kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"GFPErrorNativeImageLoadFailed"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"text":"GFPErrorNativeImageLoadFailed","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"GFPErrorNativeImageLoadFailed"}],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"GFPErrorNativeImageLoadFailed","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1nativeImageLoadFailed\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1nativeImageLoadFailed\/fragments","value":[{"kind":"identifier","text":"GFPErrorNativeImageLoadFailed"}],"op":"replace"},{"op":"replace","value":"GFPErrorCode","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode\/title"},{"value":[{"kind":"identifier","text":"GFPErrorCode"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode\/navigatorTitle","value":[{"text":"GFPErrorCode","kind":"identifier"}],"op":"replace"}]}]}