{"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/paramInitInfo"},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"externalID":"c:@E@GFPErrorCode@GFPErrorParamInitInfo","role":"symbol","roleHeading":"Case","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"paramInitInfo","kind":"identifier"}],"navigatorTitle":[{"text":"GFPErrorParamInitInfo","kind":"identifier"}],"modules":[{"name":"GFPSDK"}],"title":"GFPErrorCode.paramInitInfo"},"sections":[],"variants":[{"paths":["\/documentation\/gfpsdk\/gfperrorcode\/paraminitinfo"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfperrorcode\/paraminitinfo"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"paramInitInfo","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPErrorCode/paramInitInfo":{"title":"GFPErrorCode.paramInitInfo","navigatorTitle":[{"kind":"identifier","text":"GFPErrorParamInitInfo"}],"url":"\/documentation\/gfpsdk\/gfperrorcode\/paraminitinfo","role":"symbol","kind":"symbol","abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"paramInitInfo","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/paramInitInfo","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPErrorCode":{"abstract":[],"url":"\/documentation\/gfpsdk\/gfperrorcode","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode","role":"symbol","title":"GFPErrorCode","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPErrorCode","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"GFPErrorCode"}],"kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"GFPErrorParamInitInfo","path":"\/metadata\/title","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GFPErrorParamInitInfo"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"GFPErrorParamInitInfo","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1paramInitInfo\/title","value":"GFPErrorParamInitInfo"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1paramInitInfo\/fragments","value":[{"kind":"identifier","text":"GFPErrorParamInitInfo"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode\/title","op":"replace","value":"GFPErrorCode"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode\/fragments","value":[{"kind":"identifier","text":"GFPErrorCode"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode\/navigatorTitle","op":"replace","value":[{"text":"GFPErrorCode","kind":"identifier"}]}]}]}