{"metadata":{"role":"symbol","externalID":"c:@E@GFPErrorCode@GFPErrorScheduleVideoLoadFailed","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"scheduleVideoLoadFailed","kind":"identifier"}],"modules":[{"name":"GFPSDK"}],"symbolKind":"case","roleHeading":"Case","title":"GFPErrorCode.scheduleVideoLoadFailed","navigatorTitle":[{"text":"GFPErrorScheduleVideoLoadFailed","kind":"identifier"}]},"kind":"symbol","sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/scheduleVideoLoadFailed","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"scheduleVideoLoadFailed","kind":"identifier"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfperrorcode\/schedulevideoloadfailed"]},{"paths":["\/documentation\/gfpsdk\/gfperrorcode\/schedulevideoloadfailed"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode"]]},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPErrorCode":{"abstract":[],"url":"\/documentation\/gfpsdk\/gfperrorcode","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode","role":"symbol","title":"GFPErrorCode","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPErrorCode","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"GFPErrorCode"}],"kind":"symbol","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPErrorCode/scheduleVideoLoadFailed":{"kind":"symbol","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPErrorCode\/scheduleVideoLoadFailed","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"scheduleVideoLoadFailed","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"GFPErrorScheduleVideoLoadFailed","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfperrorcode\/schedulevideoloadfailed","title":"GFPErrorCode.scheduleVideoLoadFailed"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"GFPErrorScheduleVideoLoadFailed"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"GFPErrorScheduleVideoLoadFailed"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"GFPErrorScheduleVideoLoadFailed"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode\/title","value":"GFPErrorCode","op":"replace"},{"value":[{"text":"GFPErrorCode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode\/fragments"},{"value":[{"text":"GFPErrorCode","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode\/navigatorTitle","op":"replace"},{"value":"GFPErrorScheduleVideoLoadFailed","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1scheduleVideoLoadFailed\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPErrorCode~1scheduleVideoLoadFailed\/fragments","value":[{"text":"GFPErrorScheduleVideoLoadFailed","kind":"identifier"}],"op":"replace"}]}]}