{"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"title":"init(withDictionary:)","role":"symbol","modules":[{"name":"GFPSDK"}],"roleHeading":"Initializer","symbolKind":"init","navigatorTitle":[{"kind":"identifier","text":"initWithDictionary:"}],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"text":"withDictionary","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"])"}],"externalID":"c:@M@GFPSDK@objc(cs)GFPServerError(im)initWithDictionary:"},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPServerError"]]},"variants":[{"paths":["\/documentation\/gfpsdk\/gfpservererror\/init(withdictionary:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpservererror\/init(withdictionary:)"]}],"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPServerError\/init(withDictionary:)","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"init","kind":"keyword"},{"kind":"text","text":"?("},{"text":"withDictionary","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"dict","kind":"internalParam"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"])"}]}]}],"sections":[],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPServerError/init(withDictionary:)":{"abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPServerError\/init(withDictionary:)","url":"\/documentation\/gfpsdk\/gfpservererror\/init(withdictionary:)","kind":"symbol","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"text":"withDictionary","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"])","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"initWithDictionary:"}],"title":"init(withDictionary:)","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPServerError":{"abstract":[],"url":"\/documentation\/gfpsdk\/gfpservererror","role":"symbol","title":"GFPServerError","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPServerError","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GFPServerError"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"GFPServerError","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithDictionary:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithDictionary:"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"initWithDictionary:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Q$objc(cs)NSDictionary","text":"NSDictionary<NSString *,id>","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"dict","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPServerError~1init(withDictionary:)\/title","value":"initWithDictionary:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithDictionary:"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPServerError~1init(withDictionary:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPServerError\/title","value":"GFPServerError"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPServerError\/fragments","value":[{"text":"GFPServerError","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"text":"GFPServerError","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPServerError\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}