{"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdInfoSourcePresentable\/tsource","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tsource","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"text":"? { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpnativeadinfosourcepresentable\/tsource"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpnativeadinfosourcepresentable\/tsource"]}],"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tsource","kind":"identifier"},{"kind":"text","text":": "},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"tsource"}],"externalID":"c:objc(pl)GFPNativeAdInfoSourcePresentable(py)tsource","role":"symbol","roleHeading":"Instance Property","title":"tsource","required":true,"platforms":[{"beta":false,"deprecated":false,"introducedAt":"8.0","unavailable":false,"name":"iOS"},{"unavailable":false,"introducedAt":"8.0","deprecated":false,"name":"iPadOS","beta":false},{"name":"Mac Catalyst","deprecated":false,"unavailable":false,"beta":false,"introducedAt":"8.0"}],"modules":[{"name":"GFPSDK"}],"symbolKind":"property"},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdInfoSourcePresentable"]]},"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdInfoSourcePresentable":{"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"GFPNativeAdInfoSourcePresentable","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdInfoSourcePresentable","navigatorTitle":[{"kind":"identifier","text":"GFPNativeAdInfoSourcePresentable"}],"abstract":[],"url":"\/documentation\/gfpsdk\/gfpnativeadinfosourcepresentable","type":"topic","title":"GFPNativeAdInfoSourcePresentable","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdInfoSourcePresentable/tsource":{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdInfoSourcePresentable\/tsource","url":"\/documentation\/gfpsdk\/gfpnativeadinfosourcepresentable\/tsource","abstract":[],"title":"tsource","kind":"symbol","required":true,"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tsource","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier","text":"URL"},{"kind":"text","text":"?"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"tsource"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"tsource"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"tsource","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"NSURL","preciseIdentifier":"c:objc(cs)NSURL"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"tsource"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace"},{"value":"GFPNativeAdInfoSourcePresentable","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdInfoSourcePresentable\/title"},{"value":[{"kind":"identifier","text":"GFPNativeAdInfoSourcePresentable"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdInfoSourcePresentable\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdInfoSourcePresentable\/navigatorTitle","value":[{"kind":"identifier","text":"GFPNativeAdInfoSourcePresentable"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdInfoSourcePresentable~1tsource\/title","value":"tsource","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdInfoSourcePresentable~1tsource\/fragments","value":[{"text":"tsource","kind":"identifier"}]}]}]}