{"metadata":{"modules":[{"name":"GFPSDK"}],"title":"initWithDictionary:data:needAdChoiceForRender:","roleHeading":"Instance Method","fragments":[{"kind":"text","text":"- "},{"text":"initWithDictionary:data:needAdChoiceForRender:","kind":"identifier"}],"externalID":"c:objc(cs)GFPAd(im)initWithDictionary:data:needAdChoiceForRender:","role":"symbol","symbolKind":"method","navigatorTitle":[{"text":"initWithDictionary:data:needAdChoiceForRender:","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"text":") ","kind":"text"},{"text":"initWithDictionary:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSDictionary","preciseIdentifier":"c:objc(cs)NSDictionary"},{"kind":"text","text":" *) "},{"text":"adDict","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"data:"},{"text":"(","kind":"text"},{"text":"GFPAdSkipData","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPAdSkipData"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"data"},{"text":" ","kind":"text"},{"text":"needAdChoiceForRender:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"needAdChoiceForRender"},{"kind":"text","text":";"}],"languages":["occ"]}]}],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpad\/initwithdictionary:data:needadchoiceforrender:"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAd"]]},"kind":"symbol","identifier":{"interfaceLanguage":"occ","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAd\/initWithDictionary:data:needAdChoiceForRender:"},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAd":{"title":"GFPAd","abstract":[{"type":"text","text":"GFPAd"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAd","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"GFPAd","kind":"identifier"}],"type":"topic","url":"\/documentation\/gfpsdk\/gfpad","kind":"symbol","navigatorTitle":[{"text":"GFPAd","kind":"identifier"}],"role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAd/initWithDictionary:data:needAdChoiceForRender:":{"abstract":[],"role":"symbol","kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"initWithDictionary:data:needAdChoiceForRender:","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpad\/initwithdictionary:data:needadchoiceforrender:","navigatorTitle":[{"text":"initWithDictionary:data:needAdChoiceForRender:","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAd\/initWithDictionary:data:needAdChoiceForRender:","title":"initWithDictionary:data:needAdChoiceForRender:"}},"variantOverrides":[{"patch":[{"value":"GFPAd","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAd\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAd\/fragments","value":[{"kind":"identifier","text":"GFPAd"}],"op":"replace"},{"op":"replace","value":[{"text":"GFPAd","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAd\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}