{"variants":[{"paths":["\/documentation\/gfpsdk\/gfpclicklandingutil\/initwith:skadnetwork:clickdelegate:inapplandingdelegate:"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPClickLandingUtil\/initWith:skAdNetwork:clickDelegate:inAppLandingDelegate:","interfaceLanguage":"occ"},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"metadata":{"modules":[{"name":"GFPSDK"}],"role":"symbol","title":"initWith:skAdNetwork:clickDelegate:inAppLandingDelegate:","externalID":"c:objc(cs)GFPClickLandingUtil(im)initWith:skAdNetwork:clickDelegate:inAppLandingDelegate:","roleHeading":"Instance Method","symbolKind":"method","fragments":[{"kind":"text","text":"- "},{"text":"initWith:skAdNetwork:clickDelegate:inAppLandingDelegate:","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"initWith:skAdNetwork:clickDelegate:inAppLandingDelegate:"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWith:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"aTarget"},{"text":" ","kind":"text"},{"text":"skAdNetwork:","kind":"identifier"},{"kind":"text","text":"("},{"text":"GFPSKAdNetworkInfo","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPSKAdNetworkInfo"},{"kind":"text","text":" *) "},{"text":"aSKAdNetwork","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"clickDelegate:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id<GFPS2SAdClickDelegate>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@GFPSDK@objc(pl)GFPS2SAdClickDelegate"},{"kind":"text","text":") "},{"text":"clickDelegate","kind":"internalParam"},{"kind":"text","text":" "},{"text":"inAppLandingDelegate:","kind":"identifier"},{"kind":"text","text":"("},{"text":"id<GFPClickLandingUtilDelegate>","kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)GFPClickLandingUtilDelegate"},{"kind":"text","text":") "},{"kind":"internalParam","text":"landingDelegate"},{"text":";","kind":"text"}],"languages":["occ"]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPClickLandingUtil"]]},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPClickLandingUtil/initWith:skAdNetwork:clickDelegate:inAppLandingDelegate:":{"navigatorTitle":[{"kind":"identifier","text":"initWith:skAdNetwork:clickDelegate:inAppLandingDelegate:"}],"url":"\/documentation\/gfpsdk\/gfpclicklandingutil\/initwith:skadnetwork:clickdelegate:inapplandingdelegate:","abstract":[],"fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWith:skAdNetwork:clickDelegate:inAppLandingDelegate:"}],"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPClickLandingUtil\/initWith:skAdNetwork:clickDelegate:inAppLandingDelegate:","title":"initWith:skAdNetwork:clickDelegate:inAppLandingDelegate:"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPClickLandingUtil":{"url":"\/documentation\/gfpsdk\/gfpclicklandingutil","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPClickLandingUtil"}],"type":"topic","kind":"symbol","title":"GFPClickLandingUtil","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPClickLandingUtil","navigatorTitle":[{"text":"GFPClickLandingUtil","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPClickLandingUtil\/title","op":"replace","value":"GFPClickLandingUtil"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPClickLandingUtil\/fragments","value":[{"text":"GFPClickLandingUtil","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"GFPClickLandingUtil"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPClickLandingUtil\/navigatorTitle"}]}]}