{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpclicklandingutil\/openlanding(_:)"]},{"paths":["\/documentation\/gfpsdk\/gfpclicklandingutil\/openlanding(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"openLanding(_:)","roleHeading":"Instance Method","modules":[{"name":"GFPSDK"}],"role":"symbol","externalID":"c:objc(cs)GFPClickLandingUtil(im)openLanding:","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"openLanding","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:GFPS2SAdClickDelegate.h@T@GFPS2SAdLandingHandler","text":"GFPS2SAdLandingHandler"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"openLanding:"}]},"sections":[],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPClickLandingUtil"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"openLanding"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"aCompletion","kind":"internalParam"},{"kind":"text","text":": "},{"text":"@escaping","kind":"keyword"},{"kind":"text","text":" "},{"text":"GFPS2SAdLandingHandler","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPS2SAdLandingHandler-1jl2l","preciseIdentifier":"c:GFPS2SAdClickDelegate.h@T@GFPS2SAdLandingHandler","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPClickLandingUtil\/openLanding(_:)","interfaceLanguage":"swift"},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPClickLandingUtil/openLanding(_:)":{"title":"openLanding(_:)","role":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"openLanding","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:GFPS2SAdClickDelegate.h@T@GFPS2SAdLandingHandler","text":"GFPS2SAdLandingHandler","kind":"typeIdentifier"},{"kind":"text","text":")"}],"abstract":[],"kind":"symbol","navigatorTitle":[{"text":"openLanding:","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpclicklandingutil\/openlanding(_:)","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPClickLandingUtil\/openLanding(_:)"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPClickLandingUtil":{"url":"\/documentation\/gfpsdk\/gfpclicklandingutil","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPClickLandingUtil"}],"type":"topic","kind":"symbol","title":"GFPClickLandingUtil","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPClickLandingUtil","navigatorTitle":[{"text":"GFPClickLandingUtil","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPS2SAdLandingHandler-1jl2l":{"abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPS2SAdLandingHandler-1jl2l","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPS2SAdLandingHandler","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"GFPS2SAdLandingHandler"}],"url":"\/documentation\/gfpsdk\/gfps2sadlandinghandler-1jl2l","type":"topic","title":"GFPS2SAdLandingHandler","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"openLanding:","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"kind":"text","text":"- "},{"text":"openLanding:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"openLanding:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(_Bool)","preciseIdentifier":"c:BFv(#b)"},{"text":") ","kind":"text"},{"text":"aCompletion","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPClickLandingUtil~1openLanding(_:)\/title","value":"openLanding:","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPClickLandingUtil~1openLanding(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"openLanding:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPClickLandingUtil\/title","value":"GFPClickLandingUtil","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPClickLandingUtil\/fragments","op":"replace","value":[{"kind":"identifier","text":"GFPClickLandingUtil"}]},{"value":[{"text":"GFPClickLandingUtil","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPClickLandingUtil\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPS2SAdLandingHandler-1jl2l\/title","value":"GFPS2SAdLandingHandler","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPS2SAdLandingHandler-1jl2l\/fragments","value":[{"kind":"identifier","text":"GFPS2SAdLandingHandler"}]},{"value":[{"text":"GFPS2SAdLandingHandler","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPS2SAdLandingHandler-1jl2l\/navigatorTitle"}]}]}