{"variants":[{"paths":["\/documentation\/gfpsdk\/gfpclicklandingutil\/openlanding(_:store:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gfpsdk\/gfpclicklandingutil\/openlanding(_:store:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPClickLandingUtil\/openLanding(_:store:)"},"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"metadata":{"roleHeading":"Instance Method","symbolKind":"method","title":"openLanding(_:store:)","navigatorTitle":[{"text":"openLanding:storeDelegate:","kind":"identifier"}],"modules":[{"name":"GFPSDK"}],"role":"symbol","externalID":"c:objc(cs)GFPClickLandingUtil(im)openLanding:storeDelegate:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"openLanding"},{"text":"(","kind":"text"},{"text":"GFPS2SAdLandingHandler","kind":"typeIdentifier","preciseIdentifier":"c:GFPS2SAdClickDelegate.h@T@GFPS2SAdLandingHandler"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"store"},{"kind":"text","text":": (any "},{"preciseIdentifier":"c:@M@NaverAdsServices@objc(pl)SKStoreViewControllerCloseDelegate","text":"SKStoreViewControllerCloseDelegate","kind":"typeIdentifier"},{"kind":"text","text":")?)"}]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"openLanding","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"aCompletion","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"keyword","text":"@escaping"},{"text":" ","kind":"text"},{"text":"GFPS2SAdLandingHandler","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPS2SAdLandingHandler-1jl2l","kind":"typeIdentifier","preciseIdentifier":"c:GFPS2SAdClickDelegate.h@T@GFPS2SAdLandingHandler"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"store"},{"kind":"text","text":" "},{"text":"delegate","kind":"internalParam"},{"text":": (any ","kind":"text"},{"kind":"typeIdentifier","text":"SKStoreViewControllerCloseDelegate","preciseIdentifier":"c:@M@NaverAdsServices@objc(pl)SKStoreViewControllerCloseDelegate"},{"text":")?)","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPClickLandingUtil"]]},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPS2SAdLandingHandler-1jl2l":{"abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPS2SAdLandingHandler-1jl2l","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPS2SAdLandingHandler","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"GFPS2SAdLandingHandler"}],"url":"\/documentation\/gfpsdk\/gfps2sadlandinghandler-1jl2l","type":"topic","title":"GFPS2SAdLandingHandler","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPClickLandingUtil":{"url":"\/documentation\/gfpsdk\/gfpclicklandingutil","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPClickLandingUtil"}],"type":"topic","kind":"symbol","title":"GFPClickLandingUtil","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPClickLandingUtil","navigatorTitle":[{"text":"GFPClickLandingUtil","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPClickLandingUtil/openLanding(_:store:)":{"navigatorTitle":[{"text":"openLanding:storeDelegate:","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpclicklandingutil\/openlanding(_:store:)","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"openLanding"},{"kind":"text","text":"("},{"text":"GFPS2SAdLandingHandler","kind":"typeIdentifier","preciseIdentifier":"c:GFPS2SAdClickDelegate.h@T@GFPS2SAdLandingHandler"},{"kind":"text","text":", "},{"kind":"externalParam","text":"store"},{"text":": (any ","kind":"text"},{"preciseIdentifier":"c:@M@NaverAdsServices@objc(pl)SKStoreViewControllerCloseDelegate","text":"SKStoreViewControllerCloseDelegate","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPClickLandingUtil\/openLanding(_:store:)","title":"openLanding(_:store:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"openLanding:storeDelegate:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"openLanding:storeDelegate:"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"openLanding:"},{"kind":"text","text":"("},{"text":"void (^)(_Bool)","kind":"typeIdentifier","preciseIdentifier":"c:BFv(#b)"},{"kind":"text","text":") "},{"kind":"internalParam","text":"aCompletion"},{"kind":"text","text":" "},{"text":"storeDelegate:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<SKStoreViewControllerCloseDelegate>","preciseIdentifier":"c:Qo@M@NaverAdsServices@objc(pl)SKStoreViewControllerCloseDelegate"},{"text":") ","kind":"text"},{"text":"delegate","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"GFPS2SAdLandingHandler","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPS2SAdLandingHandler-1jl2l\/title","op":"replace"},{"value":[{"kind":"identifier","text":"GFPS2SAdLandingHandler"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPS2SAdLandingHandler-1jl2l\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPS2SAdLandingHandler-1jl2l\/navigatorTitle","value":[{"text":"GFPS2SAdLandingHandler","kind":"identifier"}]},{"op":"replace","value":"GFPClickLandingUtil","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPClickLandingUtil\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPClickLandingUtil\/fragments","value":[{"kind":"identifier","text":"GFPClickLandingUtil"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPClickLandingUtil\/navigatorTitle","value":[{"kind":"identifier","text":"GFPClickLandingUtil"}]},{"value":"openLanding:storeDelegate:","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPClickLandingUtil~1openLanding(_:store:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"openLanding:storeDelegate:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPClickLandingUtil~1openLanding(_:store:)\/fragments"}]}]}