{"kind":"symbol","metadata":{"title":"openLanding(forExceptSKAdn:)","role":"symbol","modules":[{"name":"GFPSDK"}],"roleHeading":"Instance Method","symbolKind":"method","navigatorTitle":[{"text":"openLandingForExceptSKAdn:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"openLanding","kind":"identifier"},{"kind":"text","text":"("},{"text":"forExceptSKAdn","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:GFPS2SAdClickDelegate.h@T@GFPS2SAdLandingHandler","text":"GFPS2SAdLandingHandler","kind":"typeIdentifier"},{"text":")","kind":"text"}],"externalID":"c:objc(cs)GFPClickLandingUtil(im)openLandingForExceptSKAdn:"},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPClickLandingUtil\/openLanding(forExceptSKAdn:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"openLanding"},{"kind":"text","text":"("},{"text":"forExceptSKAdn","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"aCompletion"},{"kind":"text","text":": "},{"text":"@escaping","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPS2SAdLandingHandler","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPS2SAdLandingHandler-1jl2l","preciseIdentifier":"c:GFPS2SAdClickDelegate.h@T@GFPS2SAdLandingHandler","kind":"typeIdentifier"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpclicklandingutil\/openlanding(forexceptskadn:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpclicklandingutil\/openlanding(forexceptskadn:)"]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPClickLandingUtil"]]},"sections":[],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPClickLandingUtil":{"url":"\/documentation\/gfpsdk\/gfpclicklandingutil","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPClickLandingUtil"}],"type":"topic","kind":"symbol","title":"GFPClickLandingUtil","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPClickLandingUtil","navigatorTitle":[{"text":"GFPClickLandingUtil","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPClickLandingUtil/openLanding(forExceptSKAdn:)":{"type":"topic","abstract":[],"title":"openLanding(forExceptSKAdn:)","role":"symbol","url":"\/documentation\/gfpsdk\/gfpclicklandingutil\/openlanding(forexceptskadn:)","navigatorTitle":[{"kind":"identifier","text":"openLandingForExceptSKAdn:"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPClickLandingUtil\/openLanding(forExceptSKAdn:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"openLanding","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forExceptSKAdn"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:GFPS2SAdClickDelegate.h@T@GFPS2SAdLandingHandler","text":"GFPS2SAdLandingHandler","kind":"typeIdentifier"},{"kind":"text","text":")"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPS2SAdLandingHandler-1jl2l":{"abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPS2SAdLandingHandler-1jl2l","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPS2SAdLandingHandler","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"GFPS2SAdLandingHandler"}],"url":"\/documentation\/gfpsdk\/gfps2sadlandinghandler-1jl2l","type":"topic","title":"GFPS2SAdLandingHandler","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"openLandingForExceptSKAdn:","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"openLandingForExceptSKAdn:"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"openLandingForExceptSKAdn:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"void (^)(_Bool)","kind":"typeIdentifier","preciseIdentifier":"c:BFv(#b)"},{"text":") ","kind":"text"},{"text":"aCompletion","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPClickLandingUtil\/title","value":"GFPClickLandingUtil"},{"value":[{"text":"GFPClickLandingUtil","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPClickLandingUtil\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPClickLandingUtil\/navigatorTitle","value":[{"text":"GFPClickLandingUtil","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPClickLandingUtil~1openLanding(forExceptSKAdn:)\/title","op":"replace","value":"openLandingForExceptSKAdn:"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPClickLandingUtil~1openLanding(forExceptSKAdn:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"openLandingForExceptSKAdn:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPS2SAdLandingHandler-1jl2l\/title","value":"GFPS2SAdLandingHandler","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPS2SAdLandingHandler-1jl2l\/fragments","value":[{"text":"GFPS2SAdLandingHandler","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"GFPS2SAdLandingHandler"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPS2SAdLandingHandler-1jl2l\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}