{"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdStyleType\/isEmpty","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdStyleType","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdStyleType\/SetAlgebra-Implementations"]]},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEmpty"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"platforms":["iOS"]}]}],"metadata":{"externalID":"s:s10SetAlgebraPsE7isEmptySbvp::SYNTHESIZED::c:@E@GFPAdStyleType","title":"isEmpty","role":"symbol","extendedModule":"Swift","roleHeading":"Instance Property","symbolKind":"property","modules":[{"name":"GFPSDK","relatedModules":["Swift"]}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isEmpty"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]},"abstract":[{"type":"text","text":"Inherited from "},{"code":"SetAlgebra.isEmpty","type":"codeVoice"},{"type":"text","text":"."}],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpadstyletype\/isempty"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdStyleType/SetAlgebra-Implementations":{"type":"topic","url":"\/documentation\/gfpsdk\/gfpadstyletype\/setalgebra-implementations","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdStyleType\/SetAlgebra-Implementations","role":"collectionGroup","abstract":[],"kind":"article","title":"SetAlgebra Implementations"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdStyleType/isEmpty":{"title":"isEmpty","abstract":[],"type":"topic","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdStyleType\/isEmpty","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"isEmpty","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/gfpsdk\/gfpadstyletype\/isempty","kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdStyleType":{"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPAdStyleType"}],"url":"\/documentation\/gfpsdk\/gfpadstyletype","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdStyleType","role":"symbol","navigatorTitle":[{"text":"GFPAdStyleType","kind":"identifier"}],"title":"GFPAdStyleType","abstract":[],"kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdStyleType\/title","value":"GFPAdStyleType","op":"replace"},{"value":[{"text":"GFPAdStyleType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdStyleType\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdStyleType\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"GFPAdStyleType"}]}]}]}