{"kind":"symbol","identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdStyleType\/isStrictSuperset(of:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"code":"SetAlgebra.isStrictSuperset(of:)","type":"codeVoice"},{"text":".","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isStrictSuperset","kind":"identifier"},{"kind":"text","text":"("},{"text":"of","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"other"},{"kind":"text","text":": "},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpadstyletype\/isstrictsuperset(of:)"]}],"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"isStrictSuperset","kind":"identifier"},{"text":"(","kind":"text"},{"text":"of","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"roleHeading":"Instance Method","extendedModule":"Swift","externalID":"s:s10SetAlgebraPsE16isStrictSuperset2ofSbx_tF::SYNTHESIZED::c:@E@GFPAdStyleType","symbolKind":"method","modules":[{"name":"GFPSDK","relatedModules":["Swift"]}],"role":"symbol","title":"isStrictSuperset(of:)"},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdStyleType","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdStyleType\/SetAlgebra-Implementations"]]},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdStyleType/isStrictSuperset(of:)":{"title":"isStrictSuperset(of:)","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdStyleType\/isStrictSuperset(of:)","kind":"symbol","type":"topic","abstract":[],"url":"\/documentation\/gfpsdk\/gfpadstyletype\/isstrictsuperset(of:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"isStrictSuperset","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"of"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Self"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdStyleType/SetAlgebra-Implementations":{"type":"topic","url":"\/documentation\/gfpsdk\/gfpadstyletype\/setalgebra-implementations","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdStyleType\/SetAlgebra-Implementations","role":"collectionGroup","abstract":[],"kind":"article","title":"SetAlgebra Implementations"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdStyleType":{"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPAdStyleType"}],"url":"\/documentation\/gfpsdk\/gfpadstyletype","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdStyleType","role":"symbol","navigatorTitle":[{"text":"GFPAdStyleType","kind":"identifier"}],"title":"GFPAdStyleType","abstract":[],"kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"value":"GFPAdStyleType","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdStyleType\/title"},{"value":[{"kind":"identifier","text":"GFPAdStyleType"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdStyleType\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdStyleType\/navigatorTitle","value":[{"text":"GFPAdStyleType","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}