{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdStyleType\/outstreamVideo"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"outstreamVideo","kind":"identifier"},{"text":": ","kind":"text"},{"text":"GFPAdStyleType","preciseIdentifier":"c:@E@GFPAdStyleType","kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdStyleType"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpadstyletype\/outstreamvideo"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gfpsdk\/gfpadstyletype\/outstreamvideo"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"property","externalID":"c:@E@GFPAdStyleType@GFPAdStyleOutstreamVideo","modules":[{"name":"GFPSDK"}],"navigatorTitle":[{"text":"GFPAdStyleOutstreamVideo","kind":"identifier"}],"title":"outstreamVideo","roleHeading":"Type Property","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"outstreamVideo"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"GFPAdStyleType","preciseIdentifier":"c:@E@GFPAdStyleType"}],"role":"symbol"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdStyleType"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdStyleType":{"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPAdStyleType"}],"url":"\/documentation\/gfpsdk\/gfpadstyletype","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdStyleType","role":"symbol","navigatorTitle":[{"text":"GFPAdStyleType","kind":"identifier"}],"title":"GFPAdStyleType","abstract":[],"kind":"symbol","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdStyleType/outstreamVideo":{"navigatorTitle":[{"text":"GFPAdStyleOutstreamVideo","kind":"identifier"}],"title":"outstreamVideo","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"outstreamVideo"},{"kind":"text","text":": "},{"text":"GFPAdStyleType","preciseIdentifier":"c:@E@GFPAdStyleType","kind":"typeIdentifier"}],"role":"symbol","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdStyleType\/outstreamVideo","url":"\/documentation\/gfpsdk\/gfpadstyletype\/outstreamvideo","kind":"symbol","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"GFPAdStyleOutstreamVideo"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"kind":"identifier","text":"GFPAdStyleOutstreamVideo"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"GFPAdStyleOutstreamVideo","kind":"identifier"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"GFPAdStyleType","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdStyleType\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdStyleType\/fragments","value":[{"text":"GFPAdStyleType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdStyleType\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"GFPAdStyleType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdStyleType~1outstreamVideo\/title","value":"GFPAdStyleOutstreamVideo"},{"value":[{"text":"GFPAdStyleOutstreamVideo","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdStyleType~1outstreamVideo\/fragments","op":"replace"}]}]}