{"sections":[],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"GFPAdStyleUnknown"}],"roleHeading":"Type Property","externalID":"c:@E@GFPAdStyleType@GFPAdStyleUnknown","role":"symbol","symbolKind":"property","title":"unknown","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@GFPAdStyleType","kind":"typeIdentifier","text":"GFPAdStyleType"}],"modules":[{"name":"GFPSDK"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdStyleType\/unknown"},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdStyleType"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/gfpsdk\/gfpadstyletype\/unknown"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpadstyletype\/unknown"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"unknown","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdStyleType","text":"GFPAdStyleType","preciseIdentifier":"c:@E@GFPAdStyleType"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdStyleType":{"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPAdStyleType"}],"url":"\/documentation\/gfpsdk\/gfpadstyletype","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdStyleType","role":"symbol","navigatorTitle":[{"text":"GFPAdStyleType","kind":"identifier"}],"title":"GFPAdStyleType","abstract":[],"kind":"symbol","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdStyleType/unknown":{"type":"topic","url":"\/documentation\/gfpsdk\/gfpadstyletype\/unknown","abstract":[],"kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"unknown","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@GFPAdStyleType","kind":"typeIdentifier","text":"GFPAdStyleType"}],"navigatorTitle":[{"text":"GFPAdStyleUnknown","kind":"identifier"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdStyleType\/unknown","title":"unknown","role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"GFPAdStyleUnknown"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GFPAdStyleUnknown"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"GFPAdStyleUnknown","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdStyleType\/title","op":"replace","value":"GFPAdStyleType"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdStyleType\/fragments","value":[{"kind":"identifier","text":"GFPAdStyleType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdStyleType\/navigatorTitle","value":[{"kind":"identifier","text":"GFPAdStyleType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdStyleType~1unknown\/title","value":"GFPAdStyleUnknown"},{"value":[{"kind":"identifier","text":"GFPAdStyleUnknown"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdStyleType~1unknown\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}