{"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeContext\/init(rootViewController:renderingSetting:videoOptions:simpleAdRenderingSetting:clickDelegate:)","interfaceLanguage":"swift"},"metadata":{"title":"init(rootViewController:renderingSetting:videoOptions:simpleAdRenderingSetting:clickDelegate:)","role":"symbol","modules":[{"name":"GFPSDK"}],"symbolKind":"init","roleHeading":"Initializer","navigatorTitle":[{"text":"initWithRootViewController:renderingSetting:videoOptions:simpleAdRenderingSetting:clickDelegate:","kind":"identifier"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"rootViewController","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"renderingSetting","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPNativeAdRenderingSetting","kind":"typeIdentifier","text":"GFPNativeAdRenderingSetting"},{"kind":"text","text":", "},{"kind":"externalParam","text":"videoOptions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GFPVideoOptions","preciseIdentifier":"c:objc(cs)GFPVideoOptions"},{"text":"?, ","kind":"text"},{"text":"simpleAdRenderingSetting","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPNativeSimpleAdRenderingSetting","kind":"typeIdentifier","text":"GFPNativeSimpleAdRenderingSetting"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"clickDelegate"},{"text":": (any ","kind":"text"},{"preciseIdentifier":"c:@M@GFPSDK@objc(pl)GFPS2SAdClickDelegate","text":"GFPS2SAdClickDelegate","kind":"typeIdentifier"},{"kind":"text","text":")?)"}],"externalID":"c:objc(cs)GFPNativeContext(im)initWithRootViewController:renderingSetting:videoOptions:simpleAdRenderingSetting:clickDelegate:"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"rootViewController","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"},{"kind":"text","text":"?, "},{"text":"renderingSetting","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)GFPNativeAdRenderingSetting","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdRenderingSetting","kind":"typeIdentifier","text":"GFPNativeAdRenderingSetting"},{"kind":"text","text":", "},{"kind":"externalParam","text":"videoOptions"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GFPVideoOptions","text":"GFPVideoOptions","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoOptions","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"simpleAdRenderingSetting","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)GFPNativeSimpleAdRenderingSetting","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdRenderingSetting","kind":"typeIdentifier","text":"GFPNativeSimpleAdRenderingSetting"},{"text":", ","kind":"text"},{"text":"clickDelegate","kind":"externalParam"},{"text":": (any ","kind":"text"},{"preciseIdentifier":"c:@M@GFPSDK@objc(pl)GFPS2SAdClickDelegate","text":"GFPS2SAdClickDelegate","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPS2SAdClickDelegate","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gfpsdk\/gfpnativecontext\/init(rootviewcontroller:renderingsetting:videooptions:simpleadrenderingsetting:clickdelegate:)"]},{"paths":["\/documentation\/gfpsdk\/gfpnativecontext\/init(rootviewcontroller:renderingsetting:videooptions:simpleadrenderingsetting:clickdelegate:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeContext"]]},"sections":[],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeContext":{"role":"symbol","title":"GFPNativeContext","url":"\/documentation\/gfpsdk\/gfpnativecontext","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeContext","navigatorTitle":[{"text":"GFPNativeContext","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"GFPNativeContext","kind":"identifier"}],"abstract":[],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeAdRenderingSetting":{"abstract":[],"kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdRenderingSetting","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPNativeAdRenderingSetting"}],"url":"\/documentation\/gfpsdk\/gfpnativeadrenderingsetting","title":"GFPNativeAdRenderingSetting","navigatorTitle":[{"kind":"identifier","text":"GFPNativeAdRenderingSetting"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeContext/init(rootViewController:renderingSetting:videoOptions:simpleAdRenderingSetting:clickDelegate:)":{"abstract":[],"url":"\/documentation\/gfpsdk\/gfpnativecontext\/init(rootviewcontroller:renderingsetting:videooptions:simpleadrenderingsetting:clickdelegate:)","role":"symbol","title":"init(rootViewController:renderingSetting:videoOptions:simpleAdRenderingSetting:clickDelegate:)","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeContext\/init(rootViewController:renderingSetting:videoOptions:simpleAdRenderingSetting:clickDelegate:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithRootViewController:renderingSetting:videoOptions:simpleAdRenderingSetting:clickDelegate:"}],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"rootViewController","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"renderingSetting"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GFPNativeAdRenderingSetting","preciseIdentifier":"c:objc(cs)GFPNativeAdRenderingSetting"},{"kind":"text","text":", "},{"text":"videoOptions","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPVideoOptions","text":"GFPVideoOptions"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"simpleAdRenderingSetting"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPNativeSimpleAdRenderingSetting","text":"GFPNativeSimpleAdRenderingSetting"},{"kind":"text","text":", "},{"kind":"externalParam","text":"clickDelegate"},{"text":": (any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@GFPSDK@objc(pl)GFPS2SAdClickDelegate","text":"GFPS2SAdClickDelegate"},{"kind":"text","text":")?)"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeSimpleAdRenderingSetting":{"type":"topic","url":"\/documentation\/gfpsdk\/gfpnativesimpleadrenderingsetting","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPNativeSimpleAdRenderingSetting"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdRenderingSetting","title":"GFPNativeSimpleAdRenderingSetting","navigatorTitle":[{"text":"GFPNativeSimpleAdRenderingSetting","kind":"identifier"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPVideoOptions":{"type":"topic","url":"\/documentation\/gfpsdk\/gfpvideooptions","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoOptions","role":"symbol","kind":"symbol","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GFPVideoOptions","kind":"identifier"}],"title":"GFPVideoOptions","navigatorTitle":[{"text":"GFPVideoOptions","kind":"identifier"}]},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPS2SAdClickDelegate":{"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPS2SAdClickDelegate"}],"kind":"symbol","navigatorTitle":[{"text":"GFPS2SAdClickDelegate","kind":"identifier"}],"abstract":[],"title":"GFPS2SAdClickDelegate","role":"symbol","url":"\/documentation\/gfpsdk\/gfps2sadclickdelegate","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPS2SAdClickDelegate","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"initWithRootViewController:renderingSetting:videoOptions:simpleAdRenderingSetting:clickDelegate:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithRootViewController:renderingSetting:videoOptions:simpleAdRenderingSetting:clickDelegate:"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithRootViewController:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"rootViewController"},{"text":" ","kind":"text"},{"text":"renderingSetting:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GFPNativeAdRenderingSetting","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeAdRenderingSetting","preciseIdentifier":"c:objc(cs)GFPNativeAdRenderingSetting"},{"kind":"text","text":" *) "},{"text":"renderingSetting","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"videoOptions:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPVideoOptions","preciseIdentifier":"c:objc(cs)GFPVideoOptions","kind":"typeIdentifier","text":"GFPVideoOptions"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"videoOptions"},{"kind":"text","text":" "},{"kind":"identifier","text":"simpleAdRenderingSetting:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdRenderingSetting","text":"GFPNativeSimpleAdRenderingSetting","preciseIdentifier":"c:objc(cs)GFPNativeSimpleAdRenderingSetting","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"simpleAdRenderingSetting","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"clickDelegate:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"id<GFPS2SAdClickDelegate>","preciseIdentifier":"c:Qo@M@GFPSDK@objc(pl)GFPS2SAdClickDelegate"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"clickDelegate"},{"kind":"text","text":";"}]}]},"op":"replace"},{"op":"replace","value":"GFPNativeContext","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeContext\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeContext\/fragments","op":"replace","value":[{"kind":"identifier","text":"GFPNativeContext"}]},{"value":[{"text":"GFPNativeContext","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeContext\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdRenderingSetting\/title","op":"replace","value":"GFPNativeAdRenderingSetting"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdRenderingSetting\/fragments","value":[{"text":"GFPNativeAdRenderingSetting","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeAdRenderingSetting\/navigatorTitle","value":[{"kind":"identifier","text":"GFPNativeAdRenderingSetting"}]},{"value":"initWithRootViewController:renderingSetting:videoOptions:simpleAdRenderingSetting:clickDelegate:","op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeContext~1init(rootViewController:renderingSetting:videoOptions:simpleAdRenderingSetting:clickDelegate:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithRootViewController:renderingSetting:videoOptions:simpleAdRenderingSetting:clickDelegate:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeContext~1init(rootViewController:renderingSetting:videoOptions:simpleAdRenderingSetting:clickDelegate:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdRenderingSetting\/title","value":"GFPNativeSimpleAdRenderingSetting"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdRenderingSetting\/fragments","op":"replace","value":[{"text":"GFPNativeSimpleAdRenderingSetting","kind":"identifier"}]},{"op":"replace","value":[{"text":"GFPNativeSimpleAdRenderingSetting","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdRenderingSetting\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoOptions\/title","op":"replace","value":"GFPVideoOptions"},{"value":[{"kind":"identifier","text":"GFPVideoOptions"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoOptions\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPVideoOptions\/navigatorTitle","value":[{"kind":"identifier","text":"GFPVideoOptions"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPS2SAdClickDelegate\/title","value":"GFPS2SAdClickDelegate"},{"value":[{"text":"GFPS2SAdClickDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPS2SAdClickDelegate\/fragments","op":"replace"},{"value":[{"text":"GFPS2SAdClickDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPS2SAdClickDelegate\/navigatorTitle","op":"replace"}]}]}