{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdNativeSimpleOptions\/simpleAdRenderingSetting"},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"simpleAdRenderingSetting"},{"text":": ","kind":"text"},{"text":"GFPNativeSimpleAdRenderingSetting","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdRenderingSetting","preciseIdentifier":"c:objc(cs)GFPNativeSimpleAdRenderingSetting","kind":"typeIdentifier"},{"kind":"text","text":"?"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdNativeSimpleOptions"]]},"abstract":[{"type":"text","text":"네이티브 Simple 형(=단일 이미지) 광고 렌더링 세팅 (Optional)"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"role":"symbol","externalID":"c:@M@GFPSDK@objc(cs)GFPAdNativeSimpleOptions(py)simpleAdRenderingSetting","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"simpleAdRenderingSetting","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)GFPNativeSimpleAdRenderingSetting","text":"GFPNativeSimpleAdRenderingSetting","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"modules":[{"name":"GFPSDK"}],"symbolKind":"property","roleHeading":"Instance Property","title":"simpleAdRenderingSetting","navigatorTitle":[{"kind":"identifier","text":"simpleAdRenderingSetting"}]},"variants":[{"paths":["\/documentation\/gfpsdk\/gfpadnativesimpleoptions\/simpleadrenderingsetting"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gfpsdk\/gfpadnativesimpleoptions\/simpleadrenderingsetting"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdNativeSimpleOptions":{"url":"\/documentation\/gfpsdk\/gfpadnativesimpleoptions","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdNativeSimpleOptions","type":"topic","kind":"symbol","title":"GFPAdNativeSimpleOptions","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPAdNativeSimpleOptions"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"GFPAdNativeSimpleOptions"}],"role":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPNativeSimpleAdRenderingSetting":{"type":"topic","url":"\/documentation\/gfpsdk\/gfpnativesimpleadrenderingsetting","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GFPNativeSimpleAdRenderingSetting"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdRenderingSetting","title":"GFPNativeSimpleAdRenderingSetting","navigatorTitle":[{"text":"GFPNativeSimpleAdRenderingSetting","kind":"identifier"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPAdNativeSimpleOptions/simpleAdRenderingSetting":{"type":"topic","url":"\/documentation\/gfpsdk\/gfpadnativesimpleoptions\/simpleadrenderingsetting","role":"symbol","abstract":[{"type":"text","text":"네이티브 Simple 형(=단일 이미지) 광고 렌더링 세팅 (Optional)"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"simpleAdRenderingSetting"},{"text":": ","kind":"text"},{"text":"GFPNativeSimpleAdRenderingSetting","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GFPNativeSimpleAdRenderingSetting"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPAdNativeSimpleOptions\/simpleAdRenderingSetting","title":"simpleAdRenderingSetting","navigatorTitle":[{"kind":"identifier","text":"simpleAdRenderingSetting"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"simpleAdRenderingSetting","op":"replace","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"simpleAdRenderingSetting"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPNativeSimpleAdRenderingSetting","text":"GFPNativeSimpleAdRenderingSetting","preciseIdentifier":"c:objc(cs)GFPNativeSimpleAdRenderingSetting","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"simpleAdRenderingSetting","kind":"identifier"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"GFPAdNativeSimpleOptions","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdNativeSimpleOptions\/title","op":"replace"},{"value":[{"kind":"identifier","text":"GFPAdNativeSimpleOptions"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdNativeSimpleOptions\/fragments"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdNativeSimpleOptions\/navigatorTitle","value":[{"kind":"identifier","text":"GFPAdNativeSimpleOptions"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdRenderingSetting\/title","value":"GFPNativeSimpleAdRenderingSetting","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdRenderingSetting\/fragments","value":[{"text":"GFPNativeSimpleAdRenderingSetting","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPNativeSimpleAdRenderingSetting\/navigatorTitle","value":[{"kind":"identifier","text":"GFPNativeSimpleAdRenderingSetting"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdNativeSimpleOptions~1simpleAdRenderingSetting\/title","value":"simpleAdRenderingSetting"},{"value":[{"text":"simpleAdRenderingSetting","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPAdNativeSimpleOptions~1simpleAdRenderingSetting\/fragments"}]}]}