{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"metadata":{"symbolKind":"property","title":"clickDelegate","modules":[{"name":"GFPSDK"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"clickDelegate","kind":"identifier"},{"kind":"text","text":": (any "},{"kind":"typeIdentifier","text":"GFPS2SAdClickDelegate","preciseIdentifier":"c:@M@GFPSDK@objc(pl)GFPS2SAdClickDelegate"},{"text":")?","kind":"text"}],"roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"clickDelegate"}],"externalID":"c:objc(cs)GFPContext(py)clickDelegate"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"weak","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"clickDelegate","kind":"identifier"},{"kind":"text","text":": (any "},{"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPS2SAdClickDelegate","kind":"typeIdentifier","text":"GFPS2SAdClickDelegate","preciseIdentifier":"c:@M@GFPSDK@objc(pl)GFPS2SAdClickDelegate"},{"kind":"text","text":")? { "},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}]}]}],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpcontext\/clickdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gfpsdk\/gfpcontext\/clickdelegate"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPContext\/clickDelegate"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPContext"]]},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPContext":{"type":"topic","navigatorTitle":[{"text":"GFPContext","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/gfpsdk\/gfpcontext","role":"symbol","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPContext"}],"title":"GFPContext","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPContext"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPContext/clickDelegate":{"type":"topic","abstract":[],"title":"clickDelegate","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"clickDelegate"},{"text":": (any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@GFPSDK@objc(pl)GFPS2SAdClickDelegate","text":"GFPS2SAdClickDelegate"},{"text":")?","kind":"text"}],"url":"\/documentation\/gfpsdk\/gfpcontext\/clickdelegate","role":"symbol","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPContext\/clickDelegate","navigatorTitle":[{"kind":"identifier","text":"clickDelegate"}],"kind":"symbol"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPS2SAdClickDelegate":{"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GFPS2SAdClickDelegate"}],"kind":"symbol","navigatorTitle":[{"text":"GFPS2SAdClickDelegate","kind":"identifier"}],"abstract":[],"title":"GFPS2SAdClickDelegate","role":"symbol","url":"\/documentation\/gfpsdk\/gfps2sadclickdelegate","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPS2SAdClickDelegate","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"clickDelegate"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"text":"clickDelegate","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"weak"},{"kind":"text","text":") "},{"text":"id<GFPS2SAdClickDelegate>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@GFPSDK@objc(pl)GFPS2SAdClickDelegate"},{"kind":"text","text":" "},{"text":"clickDelegate","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"op":"replace","value":"GFPContext","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPContext\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPContext\/fragments","value":[{"kind":"identifier","text":"GFPContext"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPContext\/navigatorTitle","op":"replace","value":[{"text":"GFPContext","kind":"identifier"}]},{"value":"clickDelegate","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPContext~1clickDelegate\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPContext~1clickDelegate\/fragments","value":[{"text":"clickDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPS2SAdClickDelegate\/title","value":"GFPS2SAdClickDelegate","op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPS2SAdClickDelegate\/fragments","value":[{"kind":"identifier","text":"GFPS2SAdClickDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPS2SAdClickDelegate\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"GFPS2SAdClickDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}