{"sections":[],"kind":"symbol","metadata":{"externalID":"c:@M@GFPSDK@objc(cs)GFPStringUtilsExtension(im)init","title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"symbolKind":"method","roleHeading":"Instance Method","role":"symbol","modules":[{"name":"GFPSDK"}],"navigatorTitle":[{"kind":"identifier","text":"init"}]},"hierarchy":{"paths":[["doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPStringUtilsExtension"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"kind":"identifier","text":"init"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}],"variants":[{"paths":["\/documentation\/gfpsdk\/gfpstringutilsextension\/init"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPStringUtilsExtension\/init","interfaceLanguage":"occ"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK":{"abstract":[],"title":"GFPSDK","url":"\/documentation\/gfpsdk","kind":"symbol","role":"collection","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK","type":"topic"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPStringUtilsExtension/init":{"type":"topic","navigatorTitle":[{"text":"init","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/gfpsdk\/gfpstringutilsextension\/init","role":"symbol","abstract":[],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"title":"init","identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPStringUtilsExtension\/init"},"doc://com.navercorp.da.gfp.GFPSDK/documentation/GFPSDK/GFPStringUtilsExtension":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"GFPStringUtilsExtension","kind":"identifier"}],"url":"\/documentation\/gfpsdk\/gfpstringutilsextension","type":"topic","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.navercorp.da.gfp.GFPSDK\/documentation\/GFPSDK\/GFPStringUtilsExtension","role":"symbol","navigatorTitle":[{"text":"GFPStringUtilsExtension","kind":"identifier"}],"title":"GFPStringUtilsExtension"}},"variantOverrides":[{"patch":[{"op":"replace","value":"GFPStringUtilsExtension","path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPStringUtilsExtension\/title"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPStringUtilsExtension\/fragments","value":[{"kind":"identifier","text":"GFPStringUtilsExtension"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navercorp.da.gfp.GFPSDK~1documentation~1GFPSDK~1GFPStringUtilsExtension\/navigatorTitle","op":"replace","value":[{"text":"GFPStringUtilsExtension","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}